### ISSUE TITLE
Issues with Tooltips in Form Labels since upgrade to 2.8

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#5222]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: mac
- Browser and its version:  Safari and Chrome

#### What did you do? Please provide steps to re-produce your problem.

I tried to nest a tooltip in a form label like the registration form example:

https://ant.design/components/form/

In the past, this nesting of tooltips has worked. I think something may have broken on the 2.8.0 version?

#### What do you expected?

It was working, but does not work anymore. It is also worth noting that tooltips work outside normally, but just not when passed as a prop for form label.

#### What happen?

I did not see a tooltip pop up.

#### Re-producible online demo

http://codepen.io/anon/pen/mWRWzm?editors=0011

```
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { LocaleProvider, Switch, Form, Tooltip, Icon, locales, version } = antd;
moment.locale('en');


const FormItem = Form.Item;

const FormArea = Form.create()(React.createClass({
  getInitialState () {
    return {};
  },
   render() {

      const { getFieldDecorator } = this.props.form;
     return (
      <Form onSubmit={()=>console.log('submit')} >
        <FormItem label={(
            <span>
              Nickname&nbsp;
              <Tooltip title="What do you want other to call you?">
                <Icon type="question-circle-o" />
              </Tooltip>
            </span>
          )}>
            {getFieldDecorator('switchField', { rules: [{ required: false }],valuePropName: 'checked' })(
              <Switch />
            )}
          </FormItem>
      </Form>
     );
  },
}));
  


ReactDOM.render(
  <div>
    <p className="version">antd version: {version}</p>
    <LocaleProvider locale={locales.en_US}>
         <div>
         <Tooltip title="What do you want other to call you?">
          <Icon type="question-circle-o" />
         </Tooltip>
         <FormArea />
           
        </div>
    </LocaleProvider>
  </div>
, mountNode);
```

**Comment by benjycui** [comment]
Actually, it works fine, even in your demo.

Just make `Tooltip[title]` shorter, you will know what I said:

```diff
- <Tooltip title="What do you want other to call you?">
+ <Tooltip title="?">
```

**Comment by acomito** [comment]
hmm... but wont most use cases call for a tooltip with a sentence or sentences rather than a few characters?

**Comment by acomito** [comment]
I'm trying to track down the issue. This is the same code, same browser. One is 2.7.2 and the other is 2.8:

http://g.recordit.co/aDLz03GA9l.gif

http://g.recordit.co/fP9vjg1pUB.gif

Even my layout seems to shift for some reason. i'm going through the changelog now.

**Comment by afc163** [comment]
It is our bug.

**Comment by acomito** [comment]
oh okay, thanks @afc163!

**Comment by afc163** [comment]
- `vertical` works: http://codepen.io/anon/pen/XMpoBQ?editors=0011
- `inline` works: http://codepen.io/anon/pen/WpRLaJ?editors=0011
- `horizontal` not works: http://codepen.io/anon/pen/VpPqVj?editors=0011

**Comment by afc163** [comment]
We should use `@media only screen and (max-width: 1024px) {` over `@media (min-width: @screen-sm) {`. Don't change default styles of form item in `2.7.x`.
