### ISSUE TITLE
React attempted to reuse markup.... warning

### ISSUE THREAD

**Issue by eldyvoon** [ant-design/ant-design#5224]
I got this warning in my console

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

**Comment by yesmeck** [comment]
Could you provide a reproduce repo?

**Comment by afc163** [comment]
Please give us more information about it, your description is too simple to solve problem.

**Comment by afc163** [comment]
close for no detail.

**Comment by eldyvoon** [comment]
@afc163 sorry for the late, created temp repo here https://github.com/eldyvoon/ant-temp

start the server and run on localhost:3000, you can see the error in the console. Check app/components/Home.js how I used antd there. Thanks!

**Comment by yesmeck** [comment]
@eldyvoon I don't see any errors.

**Comment by yesmeck** [comment]
One possible reason is you have two copy of react in your node_modules. Try upgrade npm to the latest version or use yarn instead and reinstall node_modules.

**Comment by eldyvoon** [comment]
@yesmect, there's no error but warning, open ur console of chrome, you will see one. And why the Button of antd didn't render?

**Comment by yesmeck** [comment]
@eldyvoon  I don't see warnings neither.

**Comment by xueqingxiao** [comment]
@eldyvoon button was rendered correctly, and there is no warning.
![75218129072097](https://cloud.githubusercontent.com/assets/4010906/23842205/9c84d378-07ed-11e7-882c-6da8e66be829.jpg)

**Comment by eldyvoon** [comment]
@xueqingxiao Why are we getting the different result? http://i.imgur.com/U66Fyei.png

I can't see the button rendered properly like you did.

**Comment by yesmeck** [comment]
@eldyvoon What's your node and npm version?

**Comment by eldyvoon** [comment]
@yesmeck 

node: v6.9.0
npm: 3.10.8

**Comment by yesmeck** [comment]
@eddhannay Try npm 4.
