### ISSUE TITLE
How to set the initial value for Select in FormItem

### ISSUE THREAD

**Issue by KrisLeeCoder** [ant-design/ant-design#5226]
Select in FormItem:
```
<FormItem
    {...formItemLayout}
    label="Select your favorite"
>
    {getFieldDecorator("g24_channel", {
        initialValue: 0
    })(
        <Select>
            { favorite.map(item => <Option key={item.id}>{item.text}</Option>) }
        </Select>
    )}
</FormItem>
```

If `favorite` is `const favorite = [{id: 0, text: "apple"}, {id: 1, text: "banana"}];`, it will display `0`, not `apple`, by default on select.
If `favorite` is a ajax result set in `state`, it will also display `0`.
But I'm really intend to display the default option text `banana`.

BTW, the above code has a error in console:
`Warning: Failed prop type: Invalid prop 'value' supplied to 'Select'.`

**Comment by KrisLeeCoder** [comment]
Resolved by set the value prop in Option

**Comment by afc163** [comment]
Select value should be string.

**Comment by hurvajs77** [comment]
btw, it works, but I got always message in console `Warning: Failed prop type: Invalid prop 'value' supplied to 'Option'.`

Values supplied into `Option` are strings.

```
<Select
    defaultValue={defaultLanguage(activeLanguage)}
    onChange={this.onChangeLocale}
    style={{ width: 220 }}
>
    {languages &&
        languages
            .sort((a, b) => (a.sort > b.sort ? 1 : -1))
            .map(({ flag: code, displayName: name, cultureCode }) => (
                <Select.Option value={cultureCode} key={`language-switch-${cultureCode}`}>
                    <CountryFlag code={code} name={name} />
                    {name}
                </Select.Option>
            ))}
</Select>
```

I don't understand how AntD components works...

Similar case for `Select`. I got message: `Failed prop type: Invalid prop 'defaultValue' supplied to 'Select'`. There is another component supplied into default value, because I need display country flag and name.

**Comment by icharge** [comment]
> Select value should be string.

But How to do it with Multiple select value?

**Comment by marco-fp** [comment]
If user.roleList is falsy, do you see the placeholder? I can't get the placeholder to appear... (my value is a string and not an array)

**Comment by icharge** [comment]
> @icharge If user.roleList is falsy, do you see the placeholder? I can't get the placeholder to appear... (my value is a string and not an array)

I can see placeholder. Try to set default value when it is false. Like empty string `falsyValue || ''`.
In my case it is Array then I use empty Array  `user.roleList || []`.

**Comment by su8898** [comment]
That works! Thanks @meganrm. I see `valuePropName` mentioned in the [antd forms documentation](https://ant.design/components/form/) .

**Comment by sombek** [comment]
> I have found that you have to set `valuePropName` to "option" in the `getFieldDecorator` options in order for the placeholder text to show, but I can't find any documentation on this, so I wanted to share incase other people have run into the same issue.
> 
> ```
> {getFieldDecorator('roleList', {
>   initialValue: user.roleList || [],
>   valuePropName: 'option',
>   rules: [
>     { required: false, message: 'Assign roles for this user', type: 'array' },
>   ],
> })(
>   <Select mode="multiple" placeholder="Assign roles for this user">
>     <Select.Option value="role_admin">Administrator</Select.Option>
>     <Select.Option value="role_seller">Seller</Select.Option>
>     <Select.Option value="role_customer">Customer</Select.Option>
>   </Select>
> )}
> ```

Do you have any idea how would I do if I wanted to select the value and the text initially?

```js
<FormItem>
    {
        getFieldDecorator('key', {
                valuePropName: 'option',
                initialValue: this.props.ID,
            }
        )(
            <Select placeholder="The first next block of a group">
                {groups.map(group => <Option key={group.id} value={group.ID}>{`${group.name}`}</Option>)}
            </Select>
        )
    }
</FormItem>
```

**Comment by sombek** [comment]
UPDATE:
Don't use `valuePropName: 'option',` if the initial selected value is equal to one of the options values it will be selected automatically 🤕

**Comment by tarun4all** [comment]
{getFieldDecorator('session_type', {
										 valuePropName: 'option',
										 rules: [
											{ required: true, message: 'Please select your Session type!' },
										  ],
									})(
										<Select defaultValue='1' onChange={this.handleSessionType}>
											<Option value="1">Never</Option>
											<Option value="2">Session (30 Minutes)</Option>
											<Option value="3">Custom</Option>
										</Select>
									)}

try with this

**Comment by zif002** [comment]
If you have problem with **select** **multiple** and initial value then do form.item **valuePropName = "option"**
` <Form.Item 
        name="name" 
        valuePropName="option"
        label="Label"
        rules={[
          {
            required: true,
            message: 'Please choose item',
          },
        ]}
        >
        <Select
          mode="multiple"
          allowClear
          showSearch
          placeholder={'Input space'}
          defaultActiveFirstOption={true}
          showArrow={false}
          filterOption={false}

          labelInValue
          onSearch={handleSearch}
          onChange={handleChange}
          value={selectedItems}
          notFoundContent={loadingSpace ? <Spin size="small" /> : "no found"}
        >
          {options}
        </Select>
      </Form.Item>`

**Comment by zif002** [comment]
If you have problem with **select** **multiple** and initial value then do form.item **valuePropName = "option"**

```
<Form.Item 
  name="name" 
  valuePropName="option"
  label="Label"
  rules={[
    {
      required: true,
      message: 'Please choose item',
    },
  ]}
  >
  <Select
    mode="multiple"
    allowClear
    showSearch
    placeholder={'Input space'}
    defaultActiveFirstOption={true}
    showArrow={false}
    filterOption={false}

    labelInValue
    onSearch={handleSearch}
    onChange={handleChange}
    value={selectedItems}
    notFoundContent={loadingSpace ? <Spin size="small" /> : "no found"}
  >
    {options}
  </Select>
</Form.Item>
```

**Comment by zhouxlin** [comment]
valuePropName should be "value" it works in my code
```
<Form.Item label="status" required  name="status" valuePropName="value">
                    <Select >
                        <Select.Option value='developing'>开发中</Select.Option>
                        <Select.Option value='released'>已发布</Select.Option>
                    </Select>
              </Form.Item>
```
