### ISSUE TITLE
2.8.0 version has a error by webpack babel loader

### ISSUE THREAD

**Issue by Nsgj** [ant-design/ant-design#5230]
#### Environment(required)

- antd version:2.8.0
- OS and its version:win10
- Browser and its version:chrome

#### What did you do? Please provide steps to re-produce your problem.
when I use webpack has a error

#### What do you expected?
Dont has this problem when i use 2.7.x version

#### What happen?
ERROR in . /~/ antd /lib/carousel/index.js
Module not found:  Error: Cannot resolve module 'lodash.debounce'  in xxx\node_modules\antd \lib\carousel

 @ ./~/antd/lib/carousel/index.js 28:14-40

**Comment by afc163** [comment]
Sorry for missing that 😓

**Comment by afc163** [comment]
@yesmeck Do we have any way to prevent dependencies missing?

**Comment by yesmeck** [comment]
We can only install production dependencies and `antd-tools` on CI when we run `npm run dist`.

**Comment by yesmeck** [comment]
Weird, `antd#react-lazy-load` depends on `lodash.debounce`, it should be installed.

**Comment by yesmeck** [comment]
@afc163 Can no find a good way to prevent this...

**Comment by yesmeck** [comment]
More carefully when code review..

**Comment by afc163** [comment]
eslint can do it but it is not support TypeScript yet.
