### ISSUE TITLE
The label of `Form.Item` is covered by the `Slider` inside it.

### ISSUE THREAD

**Issue by HandsomeOne** [ant-design/ant-design#5231]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: Windows 10 64-bit
- Browser and its version: Firefox 52

#### What did you do? Please provide steps to re-produce your problem.

I put a `Slider` in a `Form.Item`.

#### What do you expected?

The label of the `Slider` appears above the `Slider`, like what the label of the `Input` behaves. 

#### What happen?

The label of the `Slider` is covered by the `Slider`.

#### Re-producible online demo

http://codepen.io/handsomeone/pen/VpPXaE?editors=0010

**Comment by HandsomeOne** [comment]
It seems that add style `clear: both;` to `.ant-form-item-control::before, .ant-form-item-control::after` helps.

**Comment by benjycui** [comment]
You need to set `Form.Item[labelCol]` and `Form.Item[wrapperCol]`, try to consult documentation.
