### ISSUE TITLE
antd2.8.0版本，form的inline模式在低版本Chrome下显示异常

### ISSUE THREAD

**Issue by liysw** [ant-design/ant-design#5232]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: win7
- Browser and its version: Chrome 45.0.2454.101 m，35.0.1916.114，55.0.2883.87 m

#### What did you do? Please provide steps to re-produce your problem.

form表单 inline模式在chrome低版本浏览器下是显示有问题，label和控件不在同一行。目前有测试了"45.0.2454.101 m"，"35.0.1916.114"两个版本都有问题，在“55.0.2883.87 m”版本下是正常的。
 

#### Re-producible online demo
正常显示效果：
![2](https://cloud.githubusercontent.com/assets/15522887/23742199/ebc1b014-04e6-11e7-93a7-a31945936ac2.png)

错误的显示效果：
![1](https://cloud.githubusercontent.com/assets/15522887/23742209/f3adb746-04e6-11e7-9882-5ce4e010ae8d.png)

**Comment by yesmeck** [comment]
这怎么还有证书错误。。。低版本的 Chrome 不认 Let's Encrypt  的证书吗？

**Comment by Gavinchen92** [comment]
高版本中inline模式的<Form> 的祖先元素为弹性盒模型也有这个问题
原因的.ant-form-inline ｛float: left｝ 将元素左浮动了，　我的解决方法是用！important将样式覆盖了
我现在用你们家的<Table>组件遇到很大的问题啊,  表格的高度不能自适应吗（比如继承父元素的高度，　我设置了100%还是会溢出），　因为我刚用也不知道是不是要用其他的方法
还有antd真是卡啊，想用react提升性能，结果好卡

**Comment by benjycui** [comment]
这个老旧的版本。。不考虑了吧。

**Comment by benjycui** [comment]
@Gavinchen92 性能问题，单独开 issue，并专门为该情景提供 demo，不然无法调试。

**Comment by Gavinchen92** [comment]
@benjycui ok   不过只是抱怨下, 具体表现在打开F12会卡5秒钟（我也不知道是不是antd问题还是react）
还有我最想问Table组件的高度可以自适应吗，我想让它继承父元素的高度， tbody自动 产生滚动条，
而不用设置scroll.y这个绝对高度, 最后可以加个QQ吗？（因为有很多问题不明白，你可以选择理或或者不理我）

**Comment by Gavinchen92** [comment]
@benjycui  现在项目太忙还是先不开issue了，等我空下来研究下再说
