### ISSUE TITLE
官网demo中 select组件 onSelect方法如果选取同一个option 第二次点击不会触发 onSelect

### ISSUE THREAD

**Issue by zhouxinyong** [ant-design/ant-design#5234]
#### Environment

- antd version: 2.8.0
- OS and its version: ubuntu 16.04
- Browser and its version: chrome

#### What did you do?

 select组件  onSelect事件

#### What do you expected?

如果选取同一个option 第二次点击应该会触发onSelect事件

#### What happen?

选取同一个option 第二次点击没有触发onSelect事件

**Comment by ddcat1115** [comment]
官网里只有 `onChange` 示例，选择同一选项时 `onSelect` 是会重新触发的...
