### ISSUE TITLE
InputNumber输入过多

### ISSUE THREAD

**Issue by giantwinner** [ant-design/ant-design#5235]
#### Environment(required)

- antd 2.8.0:
- OS and its version:
- Browser and its version:

#### What happen?

表单中的inputnumber 在输入过多后blur时候value会变成Infinity

**Comment by ddcat1115** [comment]
https://ant.design/components/form-cn/#components-form-demo-without-form-create

**Comment by afc163** [comment]
Can resolve big number now, this commit just resolve the `Infinity` issue.
