### ISSUE TITLE
Default responsive layout for `Form` may confuses users

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#5236]
- Current breakpoint is `768px`, in many cases layout `inline` tends to perform as `vertical`, which brings puzzles.
- Sometimes users just don't want a responsive layout, do we need a shutdown property?

**Comment by afc163** [comment]
- [ ] 768px => 576px
- [ ] `inline` should not became to `vertical`.

**Comment by afc163** [comment]
<img width="456" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23752341/eaba14c6-050f-11e7-88b0-f28d708ba5d6.png">
