### ISSUE TITLE
使用 antd-init 建的项目 咋用 Layout

### ISSUE THREAD

**Issue by wudi0431** [ant-design/ant-design#524]
我在 index.jsx 里面添加 layout 就报错  ReactDOM is  ReactDOM is not defined

import '../common/lib';
import App from '../component/App';
import React from 'react';
import { Row, Col } from 'antd';

//React.render(<App />, document.getElementById('react-content1'));

ReactDOM.render(
    <div>
        <Row>
            <Col span="12">.col-12</Col>
            <Col span="12">.col-12</Col>
        </Row>
        <Row className="testRowClassName">
            <Col span="8">.col-8</Col>
            <Col span="8">.col-8</Col>
            <Col span="8" className="testColClassName">.col-8</Col>
        </Row>
        <Row>
            <Col span="6">.col-6</Col>
            <Col span="6">.col-6</Col>
            <Col span="6">.col-6</Col>
            <Col span="6">.col-6</Col>
        </Row>
    </div>,
    document.getElementById('react-content')
);

**Comment by afc163** [comment]
try ` import ReactDOM from 'react-dom';`

**Comment by wudi0431** [comment]
我看了一 我本地装是 0.10.0-beta23的版本  我看到你们的 antd-init/boilerplate/package.json 
0.10.0-beta23 是 react的 0.14.2的版本吧 所以用这个 还是错的 import ReactDOM from 'react-dom';
"dependencies": {
    "antd": "0.9.x",
    "antd-build": "0.4.x",
    "react": "~0.13.0"
  },

**Comment by afc163** [comment]
```
"dependencies": {
  "antd": "0.10.0-beta23",
  "antd-build": "0.4.x",
  "react": "~0.14.2",
  "react-dom": "~0.14.2"
},
```

0.10.x 推荐用 react@0.14.x 的，升级上去吧。

**Comment by wudi0431** [comment]
嗯 那你们的 antd-init 也要升级哦  我先在本地该吧

**Comment by afc163** [comment]
0.10.x 还没正式发布。
