### ISSUE TITLE
Select does not work if two elements has the same value (but different keys)

### ISSUE THREAD

**Issue by mimol91** [ant-design/ant-design#5242]
#### What do you expected?
Works without error
#### What happen?
`Error: flattenChildren(...): Encountered two children with the same key, `.$590`. Child keys must be unique; when two children share a key, only the first child will be used
`

#### Re-producible online demo
http://codepen.io/anon/pen/XMpGvY?editors=001

**Comment by yesmeck** [comment]
`value` is used as `key` in Select internal, so please keep `value` unique.

**Comment by mimol91** [comment]
I cant. 
In example above two different countries have this same prefix.
Can it be solved somehow? Or I need to do some dirty hack?

**Comment by yesmeck** [comment]
It doesn't make sense, if two options have the same value, how can you tell which option is selected?

**Comment by mimol91** [comment]
Good point, but in this example I do not care which is selected.

**Comment by yesmeck** [comment]
Then you don't need set `value`, just give option a `key`.

**Comment by mimol91** [comment]
Hmm, but I mean I do not care if I select `Saint Martin` or `Guadeloupe`, but I need get selected prefix

**Comment by yesmeck** [comment]
How do you generate key? why they have same value but different key?

**Comment by mimol91** [comment]
Because either for `Saint Martin` or `Guadeloupe` you have +590 prefix key,
For `Germany` You will have `+49`

**Comment by yesmeck** [comment]
Maybe you can merge these two options into  one:

```javascript
<Option value="+590">Saint Martin/Guadeloupe</Option>
```

**Comment by mimol91** [comment]
+590 has at least 3 countries , so It can be long

**Comment by yesmeck** [comment]
I mean how do you generate the `key` prop for Option?

**Comment by mimol91** [comment]
https://github.com/razagill/react-phone-input/blob/master/src/country_data.js

**Comment by mimol91** [comment]
Any way to set value as object?

**Comment by yesmeck** [comment]
Try concat prefix key with country code:

```javascript
<Option value="+590-gp">Saint Martin/Guadeloupe</Option>
```

**Comment by yesmeck** [comment]
You must find a unique value for `value` prop.

**Comment by mimol91** [comment]
Ok, thanks, I will concatenate it
