### ISSUE TITLE
Highlight matched word in bold using Autocomplete

### ISSUE THREAD

**Issue by garyfoo** [ant-design/ant-design#5243]
Hello,

I have been trying to hack different ways to do this but I still can't figure it out

How do I highlight matched word in bold using Autocomplete?

Example:

<img width="237" alt="screenshot 2017-03-09 22 52 46" src="https://cloud.githubusercontent.com/assets/5109700/23755397/2c55db9e-051b-11e7-9257-2c8dcd5ead8e.png">

**Comment by yesmeck** [comment]
See this demo https://ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category
