### ISSUE TITLE
AutoComplete : Select focused item on Blur

### ISSUE THREAD

**Issue by shanielh** [ant-design/ant-design#5244]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: linux 
- Browser and its version: chrome latest

I created autocomplete input and I want it to select the "focused" item on blur, I would have done this from the "outside" but I have no event handler to do that (on item focused / on blur (option))

**Comment by afc163** [comment]
@RaoHai

**Comment by beeant** [comment]
I need this too..

**Comment by RaoHai** [comment]
Can `onSelect` meet your requirements?  Or `focused item` you mentioned means first element of matching options?

**Comment by shanielh** [comment]
In my case, I want "onSelect" to be called with the focused item (not the first available item) on blur. I would like to have the ability to distinguish between those two events. The best way to implement  it from my point of view is to create another onBlur event that receives the focused option.

**Comment by afc163** [comment]
trace #5764
