### ISSUE TITLE
Allow Custom Selection Dropdown in Table to be toggled off

### ISSUE THREAD

**Issue by simondiep** [ant-design/ant-design#5246]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: OSX El Capitan
- Browser and its version: Chrome v56

#### What did you do? Please provide steps to re-produce your problem.

I updated my web app from Ant 2.7.4 to 2.8.0.

#### What do you expected?

I expected no visual changes.  Since this new feature was added, it would be nice to have it disabled by default and opt-in.

#### What happen?

New Feature introduced in 2.8.0 - https://github.com/ant-design/ant-design/pull/4962
I noticed an additional dropdown icon that shows up on my Ant Table next to a checkbox.  When expanded, the dropdown shows two items, both in Chinese.

#### Re-producible online demo

https://ant.design/components/table/

**Comment by benjycui** [comment]
> When expanded, the dropdown shows two items, both in Chinese.

Try [LocaleProvider](https://ant.design/components/locale-provider/).

**Comment by benjycui** [comment]
And I had pointed out this https://github.com/ant-design/ant-design/pull/4962#issuecomment-281036434

cc @afc163 @infeng

**Comment by afc163** [comment]
How about `selections` could be `true` for default select dropdown.

- `not set`: no select dropdown
- `selections={true}`: have default select dropdown
- `selections={[ ... ]}`: have default select dropdown and more options

**Comment by infeng** [comment]
I think `selections={true}` is not necessary, it  can use `selections={[]}` replace

**Comment by afc163** [comment]
`selections={[]}` is hard to understand.

**Comment by infeng** [comment]
you are right, let me send a PR.

**Comment by transedward** [comment]
Can you consider the case with no default options but custom one?
I have a use case when using select all, I want to select all the rows across different pages, which current default option is just select rows in current page.
@afc163 @infeng

**Comment by benjycui** [comment]
> I have a use case when using select all, I want to select all the rows across different pages, which current default option is just select rows in current page.

Just listen to `onSelectAll` and select all the rows across different pages.

**Comment by transedward** [comment]
Thanks @benjycui, still looking forward an option we can't choose not to use dropdown

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5246#issuecomment-286632650
