### ISSUE TITLE
mac chrome 部分寬度下，步驟條抖動

### ISSUE THREAD

**Issue by feliciakuo** [ant-design/ant-design#5250]
Steps步驟條當中的第一個範例：簡單的步驟條

使用mac chrome檢視，在部分尺寸（例如：寬度1396 ＆ 寬度1498）之下，
因margin、padding計算問題導致步驟條不斷抖動

```javascript
<div class="ant-steps-item ant-steps-status-finish" style="margin-right: -77px; width: 50%;">
     <div class="ant-steps-tail" style="padding-right: 77px;">.....</div>
     .....
</div>
```

**Comment by afc163** [comment]
antd version?

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@feliciakuo

**Comment by feliciakuo** [comment]
不好意思，後來發現是因為在電腦解析度110%時檢視官方文件範例而致，
謝謝你的回覆

**Comment by afc163** [comment]
Thx! I reproduce it, and I think it is still a bug.
