### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by MuNaiYi520** [ant-design/ant-design#5252]
It is hoped that the Upload component will be able to provide attributes such as display and no display.

**Comment by yesmeck** [comment]
`{ condition ? <Upload /> : null}`

**Comment by MuNaiYi520** [comment]
Not the case, I hope to be able to preview, on the deletion, hoping to have the opportunity to let me go to the operation whether to show delete button.

**Comment by afc163** [comment]
Default upload list can't cover all situation, I suggest you set `showUploadList={false}` and create you own upload list form 'this.state.fileList'.

**Comment by MuNaiYi520** [comment]
@afc163 Thank you very much.
