### ISSUE TITLE
Input 框会随着suffix 更新而更新

### ISSUE THREAD

**Issue by NumerHero** [ant-design/ant-design#5255]
情况如下：

需求是 Input suffix 根据用户输入的值来控制state来控制 不同的Icon 提示
 
0 不展示 1 成功 2 失败

我一开始是这样写的

![image](https://cloud.githubusercontent.com/assets/12696061/23781653/cbc0dc7e-0589-11e7-9e84-a231c0b0a6ce.png)

后来发现第一次输入完根据用户输入修改了state后，当为 0 时，input内的内容会清空

后来将0的情况改成如下
![image](https://cloud.githubusercontent.com/assets/12696061/23781643/bd502118-0589-11e7-8aae-2b2fe3fb090e.png)

才能完美展示

我觉得是个bug

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@NumerHero

**Comment by NumerHero** [comment]
codepen 无法打开...

reproducible 很简单，就是一个input 一个state管理suffix （0，1，2）, 当第一次用户输入完成后 激发onBlur 事件验证输入的值，改变state的时候 由 0 变成 1 或者 0 变成 2 （1正确，2错误，0不显示Icon)

如果一开始 state 为0 suffix 为 null 的话，当用户第一次输入后 激发onBlur 事件会清空输入的值
 state 为0 suffix 为 <Icon type="">的话, 就不会清空input 内输入的值

**Comment by afc163** [comment]
翻墙，或给个 repo 吧，没办法看文字来重现。

**Comment by NumerHero** [comment]
...已经翻墙了，不知道为什么codepen 最近老上不去

**Comment by NumerHero** [comment]
我尽量 重现，写好后@您

**Comment by ystarlongzi** [comment]
@NumerHero 
根据你的描述，写了个 demo，并没有重现。[点击查看demo](http://codepen.io/ystarlongzi/pen/QpgjqX?editors=0010)

![111](https://cloud.githubusercontent.com/assets/2840462/23844865/cdd76924-07ff-11e7-9649-a00517d2fcfb.gif)

demo 代码如下：
```jsx
const {  Input, Icon, version } = antd;

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      status: 0,
    };
  }
  
  onBlur = e => {
    const { value } = e.target;
    const status = value ? Math.ceil(Math.random() * 2) : 0;
    
    setTimeout(() => {
      this.setState({
        status,
      });
    }, 200);
  }
  
  render() {
    const { state } = this;
    let suffix;
    
    switch (state.status) {
      case 0:
        suffix = null;
        break;
        
      case 1:
        suffix = <Icon type="check" />;
        break;
        
      case 2:
        suffix = <Icon type="close" />;
    }
    
    return (
      <div style={{width: 200}}>
        <p>
          当前状态：{state.status}
        </p>
        <p>
          <Input
            suffix={suffix}
            onBlur={this.onBlur}
          />
        </p>
      </div>
    );
  }
};

ReactDOM.render(<App />, mountNode);
```

BTW，你可以安装下[诡异通道](https://guiyitongdao.com/about.html)，他们的免费通道速度也很快、稳定。

**Comment by afc163** [comment]
Just reopen it if you can reproduce it.

**Comment by NumerHero** [comment]
got it

**Comment by NumerHero** [comment]
@ystarlongzi  好吧，我确实无法复现问题，这个问题是我使用 Dva 时候碰到的，也许是操作有错
BTW 我用的XX-net
