### ISSUE TITLE
Suggestion of button height implementation

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#5256]
button本身的高度是通过padding来撑开的，而非设置高度。

那有这样一个需求：

高度为30，字体是16px，似乎目前就无法做到了。

我本人的观点，就是为了不设置 大中小 三个高度，然后通过`line-height`来让它垂直居中呢？

**Comment by afc163** [comment]
直接设置 height 代替 padding-top 和 padding-bottom 就好，line-height 也不需要。

来个 PR 如何？

**Comment by henryzp** [comment]
@afc163 ，嗯。。line-height确实不需要。。

话说传统的IE直接height，会存在一些问题，也许是我记错了。。

我空了，提个PR吧

**Comment by afc163** [comment]
@henryzp

**Comment by myhere** [comment]
hi，`.ant-btn` 是不是应该设置下 line-height？

没有 line-height 的 `.ant-btn` 受限于 `<Button>` 使用，项目里其他元素没法直接使用这个 className，比如 `<a>`；

最近项目升级 antd 后发现使用 `.ant-btn` 的元素不居中了。

thanks~
