### ISSUE TITLE
Give the tr of the table  hover event to change its border

### ISSUE THREAD

**Issue by 957236298** [ant-design/ant-design#5258]
#### Environment(required)

- antd version:  V2.7.4
- OS and its version:
- Browser and its version:  Chrome 

#### What happen?

I give the tr of the table  hover event to change it's border,but there is a black line at the bottom of it.
And I can't find anywhere has been write to set it.

#### Re-producible online demo

http://codepen.io/anon/pen/xqgLmG?editors=0110

**Comment by afc163** [comment]
http://codepen.io/anon/pen/VppbXz?editors=0110

Try to set original border color when tr is not hovering.

Antd I think it is not a antd related issue.

**Comment by yesmeck** [comment]
Why do you need set  `border-collapse` to `collapse`?
