### ISSUE TITLE
form不显示 error message

### ISSUE THREAD

**Issue by snecker** [ant-design/ant-design#5263]
准备在弹窗中做一个表单验证,发现验证会打印在控制台下,但是表单中没有提示错误信息

如图
![image](https://cloud.githubusercontent.com/assets/4178594/23821952/2855b674-067c-11e7-9d53-6ad0ef317941.png)
控制台
![image](https://cloud.githubusercontent.com/assets/4178594/23821955/3298fcea-067c-11e7-8433-503141b3bf74.png)

```js

	const onConfirm = (e) => {
		e.preventDefault();
		validateFields((err, values) => {
			if (err) {
				console.log("请输入数据 ")
			}
		})
	}
```
```js
<Modal >
			<Form onSubmit={onConfirm}>
				<FormItem
					label="Note"
					labelCol={{span: 4}}
					wrapperCol={{span: 8}}
				>
					{getFieldDecorator('note', {
						rules: [{required: true, message: 'Please input your note!'}],
					})(
						<Input />
					)}
				</FormItem>

				<FormItem label="确认">
					<Button type="primary" htmlType="submit">
						Submit
					</Button>
				</FormItem>
			</Form>
</Modal >
```

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
closing for no response
