### ISSUE TITLE
BUG: Model.confirm throw error: Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5269]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: OS X
- Browser and its version: chrome

#### What did you do? Please provide steps to re-produce your problem.

when click ok button in confirm modal:
it throw: `Uncaught TypeError: Cannot read property 'apply' of undefined`, like following image:

![image](https://cloud.githubusercontent.com/assets/3498786/23832549/4667a316-0771-11e7-8d1b-cc0ca0a49b35.png)

My code is:

```
      confirm({
        title: 'are you sure?',
        onOk () {
          // onDeleteItem(record.id)
        }
      })
```

#### What do you expected?

without error throw

#### Re-producible online demo

http://codepen.io/anon/pen/mWmQJx?editors=001

![image](https://cloud.githubusercontent.com/assets/3498786/23832576/08685618-0772-11e7-9feb-0b0762e076ab.png)

actually in official documentation is wrong too:

![image](https://cloud.githubusercontent.com/assets/3498786/23832592/5a9067d2-0772-11e7-84e5-19cf7f12ace4.png)

**Comment by junbinku** [comment]
After hours of trying I have found out the issue. 


Instead of:

onOk() {   },
onCancel() {   },

Use:

onOk: () => {},
onCancel: () = {},


This is because these function has to be binded.

**Comment by BranceLee** [comment]
楼上正解啊，终于找到出路了！
  verifiedFile =()=>{
    const { location: { query } ,customer} = this.props
    const { companyId } = query || {}
    console.log(this.props);
    Modal.confirm({
      title:"开户提示",
      content:"用户资料不齐全是否开户",
      onOk:()=>{
        this.props.dispatch({
          type:"customer/AuditPass",
          payload:{
            companyId:companyId,
            processStatus:customer.processStatus
          }
        })
      }
    })
  }
