### ISSUE TITLE
Bug #5254 not fully fixed, if `Button`'s style comes from its classname, then the wrapping `Tooltip` is still broken.

### ISSUE THREAD

**Issue by HandsomeOne** [ant-design/ant-design#5270]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: Windows 10
- Browser and its version: Firefox 52

#### What did you do? Please provide steps to re-produce your problem.

```css
.btn {
  position: absolute;
  left: 24px;
  top: 152px;
}
```

```jsx
<Tooltip title="title">
  <Button disabled className="btn" >
    Disabled & Absolutely positioned
  </Button>
</Tooltip>
```

#### What do you expected?

`Tooltip` works fine.

#### What happen?

`Tooltip` doesn't work.

#### Re-producible online demo

http://codepen.io/handsomeone/pen/xqqRod?editors=0110

**Comment by HandsomeOne** [comment]
#5254

**Comment by benjycui** [comment]
Actually, you can just re-open the previous issue..

**Comment by HandsomeOne** [comment]
@benjycui Nope. I tried. And I found this: http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

> you cannot re-open your own issues **if a repo collaborator closed them**

**Comment by afc163** [comment]
It is a edge case and I can't find perfect solution for now, and it is all about fixing https://github.com/react-component/tooltip/issues/18 .

**Comment by afc163** [comment]
Just simply lift className for your user case.
