### ISSUE TITLE
table组件，fix header的时候，scroll-x方向会有两个scrollbar

### ISSUE THREAD

**Issue by hitzzc** [ant-design/ant-design#5274]
#### Environment(required)

- antd version:
- OS and its version: OSX 
- Browser and its version: chrome

#### What happen?
header和body会各有一个scrollbar，请问有什么解决方式么

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
same as #4637 

Sorry, it is a useful style and hard to remove it. I tried removing it at #4637 and intruduce a lot of issues.
