### ISSUE TITLE
标题与Radio标签对不齐

### ISSUE THREAD

**Issue by antgod** [ant-design/ant-design#5276]
#### Environment(required)

- antd version: 2.5.2
- OS and its version: mac
- Browser and its version: chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

1.  Radio外面包一层Group,外面包一层Form.Item
2.  Form.Item设置label文字
3.  问题发生了，文字与Radio没有垂直对齐

#### What do you expected?

label and radio component align center

#### What happen?

the label at top of the radio component

#### Re-producible online demo

https://riddle.alibaba-inc.com/riddles/e9180ff8

**Comment by afc163** [comment]
不要贴内网链接。:warning:

**Comment by afc163** [comment]
Try 2.8.1 first.
