### ISSUE TITLE
Error on Breadcrumb demo

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#5279]
https://ant.design/components/breadcrumb-cn/#components-breadcrumb-demo-router

The React Router demo is not showing, and console shows errors:

<img width="908" alt="dingtalk20170313140042" src="https://cloud.githubusercontent.com/assets/465125/23843251/776bf762-07f5-11e7-8763-0f2f81851a35.png">

**Comment by benjycui** [comment]
react-router@4 had published: https://github.com/ReactTraining/react-router/releases/tag/react-router%404.0.0

**Comment by benjycui** [comment]
`rm -rf node_modules and npm i`

And I am publishing the official website.
