### ISSUE TITLE
Upload 'onChange' invoked 4 times with status 'done' while upload one file

### ISSUE THREAD

**Issue by shaozj** [ant-design/ant-design#5280]
#### Environment(required)

- antd version: 2.5.3
- OS and its version: osx ei capitan
- Browser and its version: google chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

use upload component as follows:

```
import React from 'react';
import { Upload, Icon, Modal, Button } from 'antd';

class Cpnt extends React.Component {
  constructor(props) {
    super(props);
    const defaultProps = {
      action: '/common/ajaxUploadImg.json',
      listType: 'picture',
      fileList: [],
      onChange: this.handleChange,
      onPreview: this.handlePreview,
      withCredentials: true,
      previewVisible: false,
      previewImage: '',
      fileList: this.props.fileList || [],
      imgUrl: ''
    }
  
    this.state = {...defaultProps, ...this.props.params};
  }

  handleCancel = () => this.setState({ previewVisible: false })

  handlePreview = (file) => {
    console.log(file.url);
    this.setState({
      previewImage: file.url || file.thumbUrl,
      previewVisible: true
    });
  }

  handleChange = (info) => {
    this.setState({ fileList: info.fileList });
    console.log('====info====', info);
    this.props.params.onUploadChange && this.props.params.onUploadChange(info);
  }

  render() {
    const { previewVisible, previewImage, fileList } = this.state;

    return (
      <div className="clearfix upload-img">
        <Upload {...this.state}>
          <Button>
            <Icon type="upload" /> {this.props.data.title || '点击上传'}
          </Button>
        </Upload>
        <Modal visible={previewVisible} footer={null} onCancel={this.handleCancel}>
          <img alt="img" style={{ width: '100%' }} src={previewImage} />
        </Modal>
      </div>
    );
  }
}

ReactDOM.render(
  <Cpnt data={{}} params={{}}/>
, mountNode);
```

#### What do you expected?

When a file was uploaded, onChange function be invoked once with  status 'done' .

#### What happen?

When a file was uploaded, onChange function be invoked four times with  status 'done' .

#### Re-producible online demo

https://riddle.alibaba-inc.com/riddles/2856a1b4

**Comment by xueqingxiao** [comment]
@shaozj please provide a reproduce demo. http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by shaozj** [comment]
demo: https://riddle.alibaba-inc.com/riddles/2856a1b4
notice : replace the 'action' prop to a url that riddle can access.

**Comment by xueqingxiao** [comment]
could you provide [here](http://codepen.io/benjycui/pen/KgPZrE?editors=001)? Most people can't access internal network.

**Comment by afc163** [comment]
You shouldn't use a internal website in GitHub, use codepen inside. @shaozj

**Comment by afc163** [comment]
<img width="956" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23883984/0a6d6596-08a5-11e7-9854-bb189233f3a8.png">

**Comment by afc163** [comment]
http://codepen.io/anon/pen/aJwrpM?editors=0010

Sorry, I can't reproduce your problem and I think maybe you just `console.log` the file which is a reference object, you can try `console.log(file.status)` direactly.

**Comment by shaozj** [comment]
@afc163 , you are right ,  thanks.

**Comment by afc163** [comment]
I think this is still a problem what will make people confused.
