### ISSUE TITLE
CheckboxGroup组件defaultvalue 参数类型错误。

### ISSUE THREAD

**Issue by icepoint0** [ant-design/ant-design#5282]
环境：mac os
使用的是antd  CheckboxGroup组件。在传递数组的时候报错

> Failed prop type: Invalid prop `defaultValue` of type `object` supplied to `CheckboxGroup`, expected `array`.

另外 我用type of [] 打印出来的是object。

我现在使用的是mobx 观察的一个 数组对象。typeof 也是object。请问怎么才算array呢？我在js的类型里并没有看到array这个类型？求解。

**Comment by afc163** [comment]
https://developer.mozilla.org/zh/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

**Comment by yesmeck** [comment]
See https://mobx.js.org/refguide/array.html

> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.

**Comment by icepoint0** [comment]
能不要那么快 就定义错误吗。。？我已经解决了  用[...object]就可以 ， 我这个object 就是一个array 我自己new出来的。console.log 出来也是['a','b','c'] 不知道是你们的bug还是我不会用。

**Comment by afc163** [comment]
Sorry for rush, check @yesmeck's link.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/4382d4ea23251cf306c1b674d1af6d95bf1376e6/components/checkbox/Group.tsx#L37

**Comment by icepoint0** [comment]
@afc163 yeah！ 这是我想要的答案，谢谢！ty。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/KWqMEd?editors=0010
