### ISSUE TITLE
[FEATURE REQUEST]ability to global change font-size and components size

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5284]
I am using Antd to create some administration page for 30-40 olds users, Them feedback to me: the font size it too small, But It is fine for youngers

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/d124f88930b917f1d816c1a10bee206775b3d8de/components/style/themes/default.less#L38

https://ant.design/docs/react/customize-theme

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8233
