### ISSUE TITLE
Custom filter, the input box has a value, the icon does not change color

### ISSUE THREAD

**Issue by w137271323** [ant-design/ant-design#5287]
Custom filter, the input box has a value, the icon does not change color,does not satisfy the user experience.

**Comment by RaoHai** [comment]
You mean the funnel icon in Table component ?

**Comment by w137271323** [comment]
------------------ 原始邮件 ------------------
发件人: "陆离";<notifications@github.com>;
发送时间: 2017年3月14日(星期二) 中午11:21
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "佑掱，撁着沵"<137271323@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] Custom filter, the input box has a value,the icon does not change color (#5287)




You mean the funnel icon in Table component ?

**Comment by RaoHai** [comment]
If users use `filteredValue` to control filter mode, we could update icon color. 

But if they modify dataSource directly, just like https://ant.design/components/table/#components-table-demo-custom-filter-panel did, `Table` component cannot be conscious of the alteration of filter.

Or we can offer an extra props just like `isFiltered` to mark the dataSource has been filtered ?

**Comment by afc163** [comment]
I think `isFiltered` would be nice.

**Comment by w137271323** [comment]
就是说当自定义筛选的时候，输入框里输入东西后，自定义筛选的图标没有变颜色，如果某些原因导致用户忘记了输入框里有值时，他们就会觉得数据丢失了。




------------------ 原始邮件 ------------------
发件人: "notifications";<notifications@github.com>;
发送时间: 2017年3月14日(星期二) 中午1:44
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "佑掱，撁着沵"<137271323@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] Custom filter, the input box has a value,the icon does not change color (#5287)




I think isFiltered would be nice.

**Comment by w137271323** [comment]
就是说当自定义筛选的时候，输入框里输入东西后，自定义筛选的图标没有变颜色，如果某些原因导致用户忘记了输入框里有值时，他们就会觉得数据丢失了。




------------------ 原始邮件 ------------------
发件人: "notifications";<notifications@github.com>;
发送时间: 2017年3月14日(星期二) 中午12:27
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "佑掱，撁着沵"<137271323@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] Custom filter, the input box has a value,the icon does not change color (#5287)




If users use filteredValue to control filter mode, we could update icon color.
 
But if they modify dataSource directly, just like https://ant.design/components/table/#components-table-demo-custom-filter-panel did, Table component cannot be conscious of the alteration of filter.
 
Or we can offer an extra props just like isFiltered to mark the dataSource has been filtered ?
