### ISSUE TITLE
Modal.info close error in 2.8.1

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design#5288]
![image](https://cloud.githubusercontent.com/assets/11534583/23884195/48031832-08a6-11e7-9bff-8e6afa955a7f.png)

![image](https://cloud.githubusercontent.com/assets/11534583/23884221/779a7658-08a6-11e7-9cca-ff71e936a90d.png)

when i close the modal.info,
**the  default onCancel** are not provided, so it result some error !
but the offical example dont tell us to provide it, and the version before 2.81 dont occur the error.

#### Environment(required)

- antd version: 2.8.1
- OS and its version: 
- Browser and its version: chrome

**Comment by afc163** [comment]
#5278
