### ISSUE TITLE
Carousel 走马灯自动播放问题

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#529]
1.回到第一个会闪跳一下。
2.切到别的地方去等个一会再回来就白了，，啥都没了。。。

and里的也是这样。。。。

**Comment by afc163** [comment]
没有重现。

**Comment by afc163** [comment]
http://ant.design/components/carousel/#demo-autoplay

这个例子在 chrome 下，跳回来的时候会跳一下。把 speed 调大之后更明显。

@sorrycc

**Comment by jljsj33** [comment]
这个什么时候能搞啊？？？@sorrycc

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/174

**Comment by afc163** [comment]
应该是 react-slick 问题，等它修复。
