### ISSUE TITLE
table中自定义筛选框输入值之后，漏斗图标不变颜色的问题

### ISSUE THREAD

**Issue by xiiiAtCn** [ant-design/ant-design#5290]
#### Environment(required)

- antd version:2.8.1
- OS and its version:win10
- Browser and its version:56.0.2924.87

    table中列的自定义筛选框输入内容之后，点击搜索，数据可以正常筛选，但漏斗图标没有给出已经输入了数据的提示，很容易引起困惑。而在非自定义筛选中，选择筛选条件之后漏斗是有颜色变化的。是否可以增加接口，在自定义筛选时可以控制漏斗图标的样式。这是官网示例：https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel

**Comment by afc163** [comment]
duplicate #5287
