### ISSUE TITLE
Modal.confirm onOK and onClose error in 2.8.1 报错

### ISSUE THREAD

**Issue by pmg1989** [ant-design/ant-design#5291]
升级antd至2.8.1后，发现Modal.confirm 报错， 报错项目 [dva-admin](https://github.com/pmg1989/dva-admin)
![image](https://cloud.githubusercontent.com/assets/13361827/23886083/f1644660-08b2-11e7-9b41-daa372559ed9.png)

**Comment by yesmeck** [comment]
Duplicate of #5288
