### ISSUE TITLE
TreeSelect treeCheckStrictly true: Uncaught Error: must set key for <rc-animate> children

### ISSUE THREAD

**Issue by yuriwxc** [ant-design/ant-design#5292]
antd:2.81

TreeSelect 设置 treeCheckStrictly:true 时报错:
Uncaught Error: must set key for <rc-animate> children

http://codepen.io/yuriwxc/pen/QpgerK?editors=0011

**Comment by yuriwxc** [comment]
另外有没有选择上级不自动级联选中下级的Tree或者TreeSelect案例?

**Comment by yesmeck** [comment]
When set `treeCheckable` to `true`, `TreeSelect` will use `labelInValue` mode, which means your value should be a object like `{ value: '0-0-value', label: '0-0-label' }`.

We should add warning for this situation.

**Comment by afc163** [comment]
- [ ] TreeSelect
- [ ] Select

**Comment by yesmeck** [comment]
And, `Select` also needs warning when someone set `labelInValue` to `true`, but pass a string value to it.

**Comment by yuriwxc** [comment]
谢谢,   按照{ value: '0-0-value', label: '0-0-label' } 这种方式设置value已经好用了.

**Comment by yesmeck** [comment]
New version rc-select and rc-tree-select has released.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/PKabBd?editors=001

<img width="930" alt="image" src="https://user-images.githubusercontent.com/507615/29607069-a70476d6-8822-11e7-9c3a-7849747e8f07.png">

**Comment by afc163** [comment]
Is any way to set `treeCheckStrictly` and `labelInValue={false}` meanwhile?

**Comment by johhansantana** [comment]
I've tried using regular select field like this:
```jsx
const renderSelect2 = (field) => (
  <FormItem
    label={field.label}
    hasFeedback
  >
    <Select
      onChange={(event) => field.input.onChange(event)}
      placeholder={field.placeholder}
      mode={'multiple'}
    >
      {field.children}
    </Select>
  </FormItem>
)
```

and calling it like this:
```jsx
<Field
  label={'Categorías'}
  name="categories"
  component={renderSelect2}
  placeholder={'Categorías'}
>
  {
    categories.map((category, index) => (
      <Option 
        value={category.id}
        key={index}
      >
        {category.name}
      </Option>
    ))
  }
</Field>
```

it works at beginning but as soon as I select an option the same error appears.

It will give an error as soon as I click on the field:
![image](https://user-images.githubusercontent.com/9933887/31671248-fe377f8a-b305-11e7-9b39-8f34b9730434.png)

![rc-animate](https://user-images.githubusercontent.com/9933887/31671786-401f13bc-b307-11e7-990d-88cc3c990d6a.gif)

**Comment by benjycui** [comment]
@johhansantana 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by kairi1227** [comment]
This problem is happened when treeCheckStrictly is used with TreeSelect.TreeNode.
@benjycui

**Comment by benjycui** [comment]
@kairi1227 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by kairi1227** [comment]
@benjycui 
Demo:[https://codepen.io/xiaoyi_1222/pen/eemZmQ](https://codepen.io/xiaoyi_1222/pen/eemZmQ)

value is `{value: '', label: ''}`, as follow:
![error](https://user-images.githubusercontent.com/4525647/32154123-77671678-bd69-11e7-842b-ea20220fbccc.png)

value is `{value: 'leaf2', lable: 'your leaf'}` or 'undefined', as follows:
![right](https://user-images.githubusercontent.com/4525647/32154137-9a9f191a-bd69-11e7-92a6-c608a2680af2.png)
![right1](https://user-images.githubusercontent.com/4525647/32154138-9ad28336-bd69-11e7-82db-e865329efd64.png)

**Comment by benjycui** [comment]
TreeSelect will use `value` as key, so you can not set `value` as `''`, actually, it doesn't make sense that a value is empty. See: https://github.com/react-component/tree-select/blob/dd82d3acfd93d30d621f7e3b943ca30f83354476/src/Select.jsx#L823

**Comment by kairi1227** [comment]
Got it.

**Comment by benjycui** [comment]
奇怪的是这行检测为什么没有生效？ @yesmeck 

https://github.com/react-component/tree-select/blob/41712e0044f532e18f81e7a17bf9b6418d2dd3e9/src/PropTypes.js#L6

**Comment by yesmeck** [comment]
因为空字符串符合 `PropTypes.string.isRequired`。

**Comment by pbgodwin** [comment]
@benjycui I've managed to pull together a re-producible demo of the behavior  @johhansantana observed above:

https://codepen.io/pbgodwin/pen/ZayMNy

Seems to be that, when wrapped in a ReduxForm Field, a Select with mode set to "multiple" or "tags" will cause the render to fail and the console to print the error about a key for <rc-animate>'s children being undefined. Hope this helps, let me know if you have any follow up questions.
