### ISSUE TITLE
On implementing responsive sites

### ISSUE THREAD

**Issue by fgarcia** [ant-design/ant-design#5296]
I am exited looking at all the great stuff around Ant Design, however I could not find information about the team stand on responsive design

Some frameworks have spoiled me with components that look amazing no matter the display width. In this regard I've noticed that Ant Design is not as great in narrow displays, but then there is [Ant Design Mobile](https://mobile.ant.design/)

One month ago I would have ignored Ant Design because of how it responds whenever I shrink my browser window. However recently I've been struggling with edge cases where *responsive* is just not enough, so suddenly I kind of like the separation of two projects 

Which one is the current (and planned) relationship between the Desktop and Mobile UI projects? Is there an intention to make the Desktop version more mobile friendly?

BTW, I think this concern would make a great section within the [specification page](https://ant.design/docs/spec/introduce)

**Comment by benjycui** [comment]
Actually, we have tried to make antd's components more friendly in narrow displays. But it's not perfect now, for it's not a high priority task.

And you can PR or just give us some advice on how to improve antd in narrow displays.

**Comment by afc163** [comment]
We are love to make antd nicer in mobile device, just give us PR if you have any specific suggestion. 😄
