### ISSUE TITLE
WrappedSearchForm cannot pass prop with name of 'searchHandler'

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#5297]
when using `const WrappedSearchForm = Form.create()(FormComponent)`, `searchHandler` cannot be passed as a prop to `FormComponent` and got `undefined` while others like `searchHandler2` can~ if it's true, it should be mentioned in the docs

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by CallMeXYZ** [comment]
sry,found that one third party component occpies the props
