### ISSUE TITLE
DatePicker defaultValue 

### ISSUE THREAD

**Issue by DavidCHN** [ant-design/ant-design#5299]
#### Environment(required)

- antd version:2.8.1
- OS and its version:Win10
- Browser and its version:IE11

#### What did you do? Please provide steps to re-produce your problem.

DatePicker DefaultValue does not support strings?

**Comment by afc163** [comment]
Check https://ant.design/components/date-picker/#DatePicker

The type of `defaultValue` is moment object.

**Comment by DavidCHN** [comment]
butis Why?
西安图智信息技术有限公司 魏海龙 
地 址：陕西省西安市高新区高新三路8号橙仕空间1419室邮 编：710075手 机：15295182360Q  Q：1085550637电 话：029-89527330Email：weihl@geowit.cn网 址：http://www.geowit.cn
------------------------------------------------------------------发件人：偏右 <notifications@github.com>发送时间：2017年3月14日(星期二) 18:22收件人：ant-design/ant-design <ant-design@noreply.github.com>抄　送：魏海龙 <weihl@geowit.cn>; Author <author@noreply.github.com>主　题：Re: [ant-design/ant-design] DatePicker defaultValue (#5299)
Closed #5299.—
