### ISSUE TITLE
input 数字控件的问题

### ISSUE THREAD

**Issue by ascoders** [ant-design/ant-design#530]
1. 不支持浮点数字
2. 右边上下按钮按住希望能持续增大或缩小

**Comment by afc163** [comment]
1. step 设为 0.1 时应该是支持的，但是现在确实有 bug ，待修复。
2. 交互上的优化，欢迎 PR。

**Comment by afc163** [comment]
fixed by react-component/input-number#8

**Comment by afc163** [comment]
try `0.10.0-beta27`.

**Comment by xiao-hai** [comment]
@afc163 beta27中step设为0.1时的bug仍存在，增减按钮失效；手动输入小数，失去焦点时自动被四舍五入，这是什么情况......文档demo是正常的。
