### ISSUE TITLE
Table unexpected rerender when pagination is false

### ISSUE THREAD

**Issue by terence55** [ant-design/ant-design#5300]
Table组件中，针对pagination每次都会设置新的state，导致即使Table设置pagination={false}，在dataSource不变的情况下也会刷新。如果Table和其他组件一起使用，其他组件状态变更触发根节点render，同时Table的render每次都会被触发，在Table数据量大时存在效率问题，使得界面卡顿。即使使用Immutable重写shouldComponentUpdate也无法解决，因为Table前后的this.state.pagination和nextState.pagination确实是不同的对象。

```javascript
 Table.prototype.componentWillReceiveProps = function componentWillReceiveProps(nextProps) {
        this.columns = nextProps.columns || (0, _util.normalizeColumns)(nextProps.children);
        if ('pagination' in nextProps || 'pagination' in this.props) {
            this.setState(function (previousState) {
                var newPagination = (0, _objectAssign2["default"])({}, defaultPagination, previousState.pagination, nextProps.pagination);
                newPagination.current = newPagination.current || 1;
                newPagination.pageSize = newPagination.pageSize || 10;
                return { pagination: nextProps.pagination !== false ? newPagination : {} };
            });
        }
```

**Comment by afc163** [comment]
pagination 不变的时候确实不应该触发 `setState`，如果改为 immuatable 的话，原来的 demo 写法可能会失效，有点蛋疼。

@yesmeck 来看下。

**Comment by yesmeck** [comment]
先比较下 `nextProps.pagination !== this.props.pagination` 再  `setState` 不行吗？

> 如果Table和其他组件一起使用，其他组件状态变更触发根节点render，同时Table的render每次都会被触发

这种情况现在在 `Table` 组件内部是没法杜绝的，因为已经把内部的 `sCU` 去掉了，但是 `Table`  的父组件可以用 `sCU` 啊。

**Comment by fuchengwu** [comment]
我就是在外部包了一层做sCU，但是遍历state判断的时候，this.state.pagination和nextState.pagination永远都不是同个对象，因为每次pagination都被重新setState了

**Comment by yesmeck** [comment]
@fuchengwu 能给个例子吗？http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by fuchengwu** [comment]
像下面这么写就行，MyTable是继承了Table的组件

```html
 <MyTable
   columns={columns}
   pagination={false}
   dataSource={data} />
});
```

```javascript
shouldComponentUpdate: function (nextProps, nextState) {
    //...
    for (let prop in this.state) {
      if (typeof (this.state[prop]) !== 'function' && nextState[prop]) {
        if (!Immutable.is(this.state[prop], nextState[prop])) {
          console.log('not the same ' + prop + ': ' + this.state[prop].toString() + '; ' + nextState[prop].toString());
          return true;
        }
      }
    }
    return false;
  }
```

因为源码里是判断了props里有没有pagination，所以不写pagination属性反而不会触发反复render...

**Comment by yesmeck** [comment]
> 如果改为 immuatable 的话，原来的 demo 写法可能会失效，有点蛋疼。

@afc163 没看懂，哪里会失效？

**Comment by afc163** [comment]
看上面的提交。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/c61b47f7828a0fbc9492c0ca43e019410e4f2b26/components/table/Table.tsx#L208

这里如果直接改成 `this.props.pagination !== nextProps.pagination` 的话。

**Comment by yesmeck** [comment]
修改 state 本来就是不对的，没什么问题吧。

https://facebook.github.io/react/docs/react-component.html#state

> Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable

**Comment by yesmeck** [comment]
那把 ` return { pagination: nextProps.pagination !== false ? newPagination : {} };` 这里的 `{}` 提成常量好了，不要每次都创建一个新的 `{}`。

**Comment by yesmeck** [comment]
这样能解决`false`的问题。
