### ISSUE TITLE
Popconfirm + button 使用 disabled的问题

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#5301]
- antd version:2.8.1
- Browser and its version:Chrome 56.0.2924.87

Popconfirm + button 使用 disabled
button外层会产生一个span，点击button的时候 popconfirm会弹出，而且会对布局造成影响

希望disabled可以loading那样处理

**Comment by afc163** [comment]
> 会对布局造成影响

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Popconfirm 不需要包裹 span，针对它去掉了。

Popover 可能还会遇到这个问题。

**Comment by huyawei** [comment]
.... 实际上 的确会产生一个span，使用 codepen.io 单独写一个能看到button外层加了一个span，
然后这个span很可能对 margin 这种属性造成影响。
目前只能用三目运算符做判断来处理

**Comment by afc163** [comment]
给个 codepen 看看是如何影响 margin 的，我看看我能做什么兼容。

**Comment by huyawei** [comment]
http://codepen.io/madaos/pen/GWvZRJ

loading 那个button，点击不会弹出 popconfirm
disabled 那个button，点击会弹出popconfirm，感觉应该处理为跟loading最好
另外 f12看下 disabled的button。会看到外面有一层span，这个demo虽然看起来效果
三个button都加了margin-left:10px,但是看span还是紧挨着上一个button

**Comment by afc163** [comment]
1. 和 https://github.com/ant-design/ant-design/issues/5270 类似，06b17fd553dec67bbea51baa5024c42ad4c5604b 的修复提升了 className 可以缓解这个问题。
2. 09fd82def3eddd1bb00d79127fc66128abb5cda1 的修复之后，Popconfirm 不会遇到这个问题。
3. button disabled 如果不想弹出 Popconfirm ，建议业务自行处理就好。loading 是直接去除了鼠标事件，对于 disabled 不是很合适。

**Comment by huyawei** [comment]
好吧，那我用三目运算符做判断吧

**Comment by afc163** [comment]
这周发布后应该就能修复了，关注下。

**Comment by huyawei** [comment]
嗯 非常感谢
