### ISSUE TITLE
TreeSelect 弹出的下拉菜单width样式被覆盖

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#5302]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: mac/windows
- Browser and its version: chrome

#### What did you do? Please provide steps to re-produce your problem.

通过dropdownStyle传入样式width:'auto'

#### What do you expected?

dropdownStyle指定的宽度样式生效

#### What happen?

生成的dropdown的宽度被重写成了输入控件的宽度

**Comment by afc163** [comment]
https://ant.design/components/tree-select-cn/#API

`dropdownMatchSelectWidth={false}`
