### ISSUE TITLE
[BUG] InputNumber formatter not right when symbol is place behind of value

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5303]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: OS X
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

```
  <InputNumber formatter={value => `${value} %`} defaultValue={100} />

```

image below:
![image](https://cloud.githubusercontent.com/assets/3498786/23900525/a25b614c-08f4-11e7-9b4d-8abd9bec3449.png)

#### What do you expected?

`%` only present once, when type numbers into

#### Re-producible online demo

http://codepen.io/wytwyt01/pen/BWdzRV?editors=001

**Comment by minsungryu** [comment]
I think it's not a bug actually.

When you enter a number, value parameter returns a (number +%).

So every time you enter a number, it will be followed by an additional %.

I suggest you write this code

```
 <InputNumber formatter={(value) => `${value.replace('%', '')}%`} defaultValue={0} />
```

**Comment by benjycui** [comment]
@minsungryu if we just modify number with inc/dec button, it works fine.

We can try to do something, but not promise.

@TangMonk just follow @minsungryu advice

**Comment by benjycui** [comment]
@minsungryu I add your advice in demo, see: bb16e5f

But the UX still can be improved. Now, we cannot delete number while we put cursor after `%`

**Comment by minsungryu** [comment]
@benjycui I have modified some code in rc-input-number and I think it works fine.
I will send a pull request soon.
