### ISSUE TITLE
可以自定义 Tree中每个节点前面的小三角吗？

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#5305]
#### Environment(required)

- antd version:2.8.1
- OS and its version:
- Browser and its version:

#### What do you expected?
希望可以自定义Tree节点前面的小三角的形状、颜色、大小

**Comment by benjycui** [comment]
只能通过样式覆盖。

**Comment by changyijie** [comment]
样式覆盖不起作用  是我的配置问题吗
![image](https://cloud.githubusercontent.com/assets/22167211/23929991/7e499718-0964-11e7-8928-d598acc1a948.png)

**Comment by benjycui** [comment]
样式优先级的问题，自行排查。
