### ISSUE TITLE
[Improvement]InputNumber should accept null value

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5307]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: OS X
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

```
ReactDOM.render(
  <InputNumber defaultValue={null} />
, mountNode);
```

![image](https://cloud.githubusercontent.com/assets/3498786/23935905/d63eed4a-0989-11e7-9bc3-d1b473b1ad0c.png)

#### What do you expected?

Sometimes, The api server will give me the null value to me, when I assign null to the InputNumber components, it will throw `Cannot read property 'toString' of null`, It should Ignore the `null` value in internal, and present InputNumber without value. If cannot, should provide more friendly error message, instead of `Cannot read property 'toString' of null`

Now I have to do with the ugly this:

```
{getFieldDecorator('number', {
  initialValue: item.number ? item.number : undefined,
})(<InputNumber />)}
```

#### Re-producible online demo

http://codepen.io/wytwyt01/pen/perGXZ?editors=0010

**Comment by afc163** [comment]
fixed in https://github.com/react-component/input-number/commit/d7a332efbca330beffe83c0e8494b99a30b6672b, reinstall node_modules.
