### ISSUE TITLE
Failed to decode download font . OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by K-walker** [ant-design/ant-design#5308]
今天参照ant-design的文档介绍，来定制主题，但是却提示一个错误，如下：
```
Failed to decode downloaded font: http://localhost:8000/src/assets/fonts/iconfont.woff
 OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:8000/src/assets/fonts/iconfont.ttf
OTS parsing error: invalid version tag
```
我是按照文档来一步步操作的，使用 **dva-cli**  构建的项目，在 **.roadhogrc**  中添加  **theme.js**
theme.js:
```
module.exports = function () {
	return {
		'@icon-url':'"/src/assets/fonts/iconfont"'
	}
}
```
文档上也是这样说明的，可为什么就是没有效果，我也看了 [#1468](https://github.com/webpack/webpack/issues/1468) 这个issues ,情况和我一样，但是我按照他上面的解决方式来操作，还是不行，真的很苦恼，希望能大家能帮我解答下，谢谢了。

**Comment by afc163** [comment]
http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

**Comment by afc163** [comment]
给个 repo ？

**Comment by K-walker** [comment]
好的，我现在弄两个repo，一个用atool-build 构建（可以正常定制主题），一个用dva-cli 构建（异常），麻烦你看看，稍等啊。

**Comment by K-walker** [comment]
@afc163  ，久等了，我已经把问题 repo 放到 git 上了，麻烦您拉下来看看  [iconfont-demo](https://github.com/K-walker/iconfont-demo)

**Comment by afc163** [comment]
https://github.com/K-walker/iconfont-demo/pull/1

路径错了，roadhog 里 src 下是访问不到的。

**Comment by K-walker** [comment]
@afc163  哥们，还是不行啊，不是路径问题，我把iconfont放到根目录下，也还是报这个错啊。

**Comment by K-walker** [comment]
@afc163  多谢了，可以了。可是有点不是很明白，为什么放在其他目录就不行呢，而且在theme.js中引用的时候还不加public，奇怪，能给个解释吗？麻烦了
