### ISSUE TITLE
编辑表单问题

### ISSUE THREAD

**Issue by jpdan** [ant-design/ant-design#5309]
antd: 2.81

Modal中放Form
```javascript
Class CustomModal extends Component {
  render(){
      return <Modal visible={visible}><Form/></Modal>
   }
}

<CustomModal form={ (form)=> this.customForm=form} />
```
显示modal，如果修改表单值，设置表单值，如果添加，直接显示
```javascript
if(values){
  this.customForm.setFieldsValue(values)
}
this.setState({visible: true});
```
以前是没问题的，最新升级最新版本后
控制台提示：
Warning: Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.

看了一些提问和例子，建议用 mapPropsToFields，但是这个格式很麻烦啊
要每个字段设置value
```javascript
{
  userName: {value: 'aa'},
 age: {value: 10}
}
现在都是一个json串，{userName: 'aa', age: 10}
通过componentWillReceiveProps setFieldsValue又会造成死循环
用{getFieldDecorator("userName", { initinalValue: record['userName'] })(<Input/>)}，字段多了也麻烦
```
想问问有没好的办法，谢谢

**Comment by yesmeck** [comment]
Please format your issue in markdown https://segmentfault.com/markdown

**Comment by afc163** [comment]
I afraid you have to use `mapPropsToFields`, just make a util function for transforming data format.

**Comment by whx76** [comment]
@afc163 
升级到2.8.2 控制台提示：
Warning: Cannot use setFieldsValue until you use getFieldDecorator or getFieldProps to register it.
是否在componentWillReceiveProps时调用setFieldsValue就会出这个警告？ 
请问这个警告出现的原因是什么？什么情况下出现？

**Comment by yesmeck** [comment]
@whx76 警告说的很清楚了，在 `getFieldDecorator ` 注册 input 前不能调用 `setFieldsValue`。

**Comment by whx76** [comment]
thank. 我检查了下，不是调用位置问题是我代码setFieldsValue时传递了过多的值

**Comment by xiyouzhang** [comment]
我在componentDidMount中获取到data,使用form.setFieldsValue(data)，也报了同样的错误，你能再说清楚一点吗？
setFieldsValue时传递了过多的值是什么意思，难道不能直接直接form.setFieldsValue(data)吗 @whx76

**Comment by xiyouzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/18208901/26051271/410defb0-3994-11e7-997d-34a7e0f0a4b9.png)
在render里面每个filed都使用了getFieldDecorator ，componentDidMount使用form.setFieldsValue(data)，还是报了警告 @yesmeck

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by xiyouzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/18208901/26052691/e8856ba2-3998-11e7-9576-5296ec6bcf72.png)
![image](https://cloud.githubusercontent.com/assets/18208901/26052779/25093ee6-3999-11e7-922d-a197fdc7cabd.png)

**Comment by xiyouzhang** [comment]
![e8856ba2-3998-11e7-9576-5296ec6bcf72](https://cloud.githubusercontent.com/assets/18208901/26053166/5c429faa-399a-11e7-8d45-13dbf0ceaff7.png)
![25093ee6-3999-11e7-922d-a197fdc7cabd](https://cloud.githubusercontent.com/assets/18208901/26053172/60a08940-399a-11e7-8493-2874c25eb6d8.png)
@afc163

**Comment by xiyouzhang** [comment]
https://codepen.io/xiyouzhang/pen/YVvrwa @afc163

**Comment by afc163** [comment]
Please make sure that your code is working and warning is printed.

**Comment by whx76** [comment]
传递过多的值，是传递数组中包含了未在getFieldDecorator 中注册的值 导致出现警告 @xiyouzhang ,检查下你setFieldsValue里设置的字段内容是否超出getFieldDecorator中注册值

**Comment by xiyouzhang** [comment]
我都注册了的，但是警告依然在 @whx76

**Comment by benjycui** [comment]
@xiyouzhang sorry, it seems that your CodePen is broken, please make sure your CodePen work and it can re-produce bug with your steps.

**Comment by WinterWoods** [comment]
A redundant value is set to warn
`showModal = () => {
    this.setState({ visible: true, formData: { test: "多余的", Name: "正常值" } });
  }`
`componentDidMount() {
        this.props.form.setFieldsValue(this.props.formData);
    }`

**Comment by millionbug** [comment]
我也出现了这个问题，检查了一下，是我setFieldsValue的时候有一个字段拼写错误，所以无法set

**Comment by navono** [comment]
我在`setFieldsValue`前，使用`getFieldsValue`返回的值已经存在一个命名字段。然后再使用`setFieldsValue`更新这个命名字段。依旧提示说`Warning: Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.`。搞不懂。

**Comment by afc163** [comment]
你要在 render 的过程中使用 getFieldDecorator 注册这个字段。这个 warning 已经说的很清楚了。
