### ISSUE TITLE
动态表单的新提案

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#5311]
在很多场景下，我们都需要处理一些对象数组，通过 Form 来动态地 CURD. 目前官方的方案是用一个 `keys` 来 map 出这些动态表单。但是这种方法很麻烦，通常需要对最后 `getFieldsValue()` 的值重新序列化成数组形式。

比如我们的数据结构是这样的：

```js
{
  title: string,
  details: {
      position: number,
      url: string
  }[]
}
```

这里的 `details` 是一个对象数组，我们需要在页面动态地 CURD 这一个对象数组，如果用现在的方案，需要生成很多带 index 的 key, 比如 `position-1`, `position-2`, `url-1`, `url-2` 等等，然后最后还需要把这些 key 转化成正常的数组。

所以我认为可以有一种更好的方案去解决动态表单：

```jsx
class DynamicForm extends React.Component {
  const { getFieldDecorator, getFieldsDecorator, getFieldsHandler } = this.props.form
  
  @bind
  add () {
      const handler = getFieldsHandler('details')
      
      handler.add()
  }
  
  @bind
  remove () {
      // remove 还没想好怎么处理
  }
  
  @bind
  save () {
      const values = getFieldsValue() // => { title: 'foo', details: [...] }
  }
  
    return (
      <Form>
        <FormItem>
          {getFieldDecorator('title')(
              <Input />
          )}
        </FormItem>

        { /** here is the magic **/ }

        {getFieldsDecorator('details')(
          <div className='dynamic-form'>
            <FormItem>
              {getFieldDecorator('details.position')(
                <InputNumber />
              )}
            </FormItem>
            <FormItem>
              {getFieldDecorator('details.url')(
                <Input />
              )}
            </FormItem>
            <FormItem>
              <Button onClick={this.remove}>移除</Button>
            </FormItem>
          </div>
        )}

        <Button onClick={this.add}>新增</Button>
        <Button onClick={this.save}>保存</Button>
      </Form>
    )
}
```

大致是用一个叫 `getFieldsDecorator` 的方法，包装一个根据例子中的 `details` 数组 map 出来的组件。通过 `getFieldsHandler` 显露出来的 handler，去动态地新增和移除某个动态生成的表单组。

**Comment by benjycui** [comment]
嵌套 field 其实已经支持，只是不完美 http://react-component.github.io/form/examples/nested-field.html

Trace: https://github.com/ant-design/ant-design/issues/4711

**Comment by Kaijun** [comment]
@benjycui 这个 issue 描述的动态表单的使用方式其实很自然。使用嵌套 field 确实可以这个 issue 的一部分问题，但是还有两点比较疑惑，希望可以解答下：
- 是否可以不再维护一个 keys, 可以直接通过 getFieldValue('array') 然后 map 出 FormItem
- 如果 array 有初始值的情况又该怎么办？如何做到给初始值后，动态 Fields 自动填充数据？

以上这两个点是我目前使用嵌套 field 遇到的问题。 希望可以帮忙解答下！感谢！

**Comment by Kaijun** [comment]
@benjycui 对比了下 Element React 的 Form https://eleme.github.io/element-react/#/zh-CN/form 是否可以参考下，同样 Formsy 也是这种的 Form 设计。Form 本身不维护和 form data 强绑定的 store, validate rules 也是分离的
好处：Form 的渲染直接由源 formData 体现
坏处：没有办法做到接管 OnChange，需要用户主动去更新 formData

**Comment by benjycui** [comment]
@Kaijun 直接使用第三方库即可，如 https://www.npmjs.com/package/formsy-antd

`antd.Form` API 不会再做大的改动，影响面太大。
