### ISSUE TITLE
login icon not shows

### ISSUE THREAD

**Issue by zwpCode** [ant-design/ant-design#5312]
1.Icon图标-->方向性图标--><Icon type="login" />，login图标。此图标无法显示
2.官网地址。https://ant.design/components/icon-cn/

**Comment by yesmeck** [comment]
It shows on Chrome 56. What browser and OS are you using?

**Comment by afc163** [comment]
Try <kbd>Ctrl<kbd> + <kbd>Shift<kbd> + <kbd>R<kbd>

**Comment by afc163** [comment]
closing for can't reproduce.
