### ISSUE TITLE
Popconfirm 报错：Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Nothingexp** [ant-design/ant-design#5313]
Popconfirm在 Table 的 render 里进行调用的时候报错了
![image](https://cloud.githubusercontent.com/assets/21405348/23941744/fd5ccff8-09a4-11e7-8123-7792e2d54e9f.png)
点击“删除”的时候是正常显示，点击“停止”报错。
![image](https://cloud.githubusercontent.com/assets/21405348/23941817/3ee81fe0-09a5-11e7-83ff-fd107362d75e.png)
![image](https://cloud.githubusercontent.com/assets/21405348/23941846/578cb42a-09a5-11e7-892d-55750965abf1.png)

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
closing for no response
