### ISSUE TITLE
TreeSelect 多选时能否按照选择顺序排列?

### ISSUE THREAD

**Issue by yuriwxc** [ant-design/ant-design#5321]
antd: 2.8.1

使用TreeSelect组件进行级联多选时, 现在是按照树的节点先后顺序排列的, 
 能否按照用户选择的顺序,  即value数组的顺序进行排列?

**Comment by yesmeck** [comment]
现在的行为，感觉是有点不符合直接。

**Comment by yuriwxc** [comment]
我觉得按照value的顺序展现才合理吧,  比如我们做一个在组织机构树上选人的功能,  选中的用户不是按照选择的顺序展现更合理吗?

**Comment by yuriwxc** [comment]
或者onChange里面依然使用现在的排序, 但可以支持我们在onChange中改变value的顺序, 最终按照value的顺序展现?

**Comment by mxsl-gr** [comment]
@yuriwxc 这要看 checked 的方式, 一般都是树遍历下去=.=, 另外我其实是来试试 @ 功能的

**Comment by codeXian** [comment]
@afc163  @yesmeck  treeSelect多选排序，显示在Input上是依据什么来的，能简单介绍一下吗？

**Comment by zombieJ** [comment]
Select 会把 TreeNode 信息收集起来，根据 checked key 验证一遍所有的 keys 是否存在。最后将 keys 按照 type 合并
