### ISSUE TITLE
ant-input-preSuffix-wrapper 这个驼峰命名是否符合规范

### ISSUE THREAD

**Issue by hbrls** [ant-design/ant-design#5322]
#### Environment(required)

- antd@2

#### What did you do? Please provide steps to re-produce your problem.

https://github.com/ant-design/ant-design/blob/070ca82bc2461b68456ab97bb80a0fda4315aff3/components/input/style/mixin.less#L191

    .@{inputClass}-preSuffix-wrapper {
        ...
    }

#### What do you expected?

按之前看到的应该是 `pre-suffix`？我在做样式覆盖，所以这个类名影响到我了。

**Comment by afc163** [comment]
You can PR to correct it.

**Comment by afc163** [comment]
http://ant.design/components/upload/
