### ISSUE TITLE
Tab再Props更新后无法重绘

### ISSUE THREAD

**Issue by sam-zhou-insigma** [ant-design/ant-design#5325]
#### Environment(required)

- antd version:lastest
- OS and its version:Mac
- Browser and its version:Chome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.
采用了Tab来展示单条数据（多个字段被分组了）
我加载了数据，更新了数据，但是无法自动在Tab里显示。点击 Tab面板后显示新的数据。
我设置activityKey就能够自动显示数据，但是无法切换面板。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by sam-zhou-insigma** [comment]
not set id for Tab panel...  👎
