### ISSUE TITLE
icon 按需引入时 有些图标样式不能正常引入

### ISSUE THREAD

**Issue by Cecilxx** [ant-design/ant-design#5328]
#### Environment(required)

- antd version: 2.8.1

#### What did you do? Please provide steps to re-produce your problem.

按需导入icon图标：
```
<Icon type="file" />
<Icon type="wifi" />
```

#### What do you expected?

发现file类型的样式能正常显示，wifi类型的不能正常显示， 类似的还有man，woman等等

#### What happen?
1. type='file' 正常显示
2. type='wifi' 查看样式之后发现,只有.anttion的样式 并没有 .anticon-wifi 及 .anticon-wifi :before 的样式
3. 使用了babel-plugin-import

**Comment by benjycui** [comment]
提供一个可重现仓库，谢谢。

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by Cecilxx** [comment]
issue上面的版本是2.8.0 升级到2.8.1后没有问题了 不好意思😁
