### ISSUE TITLE
实现可以拖动容器

### ISSUE THREAD

**Issue by zhengbinzuo** [ant-design/ant-design#5329]
高大上的ANTD，居然还没有一个可以拖动高整宽度的容器，用户不能根据自己的喜欢来调整显示内容，导致用户体验特别不好，建议在现有的Sider上实现，实现了请联系 嗨南 修改线上功能，现在被用户吐槽中

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by afc163** [comment]
按照 https://ant.design/docs/react/recommendation-cn 这里的原则，我们不会重复造轮子，也不会添加设计规范中不涵盖的功能。React 业界已经有很多类似的组件可以直接用，你可以试试，感谢理解。

https://github.com/avocode/react-resizer
https://github.com/tomkp/react-split-pane
