### ISSUE TITLE
Table 组件中的数据不支持自定义设置 key 属性的名称吗？

### ISSUE THREAD

**Issue by maiwenan** [ant-design/ant-design#533]
在 `0.10.0-beta23` 版本，我通过设置Table 中 rowKey 属性返回每一行的 key 值（如：`return record.id`），可以不设置 `record.key` 值。但是在多选列表中，不设置 `record.key` 会导致数据的选中（这个是对的）与 ui 上选中的表现不一样。查看源码就在 Table 组件中看到了这样获取行数据的 key，key 属性名称不能自定义成如 id 这样吗？还有就是如果我的数据一开始都是默认选中的，表头的全选 `checkbox` 并不会选中。
```
getRecordKey: function getRecordKey(record, index) {
    return record.key || index;
}
```

**Comment by afc163** [comment]
使用属性 `rowKey(recode, index) {}` 进行自定义。

**Comment by maiwenan** [comment]
使用 `rowKey(record, index) {}` 是可以，但是在选择列表中依然需要有 `record.key` 的值才能表现正常。

**Comment by afc163** [comment]
嗯，貌似有问题，我回头看一下。

**Comment by afc163** [comment]
两个问题应该都已修复。

**Comment by afc163** [comment]
try `0.10.0-beta26`

**Comment by maiwenan** [comment]
测试过，已经可以了，谢谢了。
