### ISSUE TITLE
Affix 2.8.1版本 页面无法往下滚动

### ISSUE THREAD

**Issue by costaq** [ant-design/ant-design#5330]
#### Environment(required)

- antd version: 2.8.1
- Browser and its version:chrome 57.0.2987.98

**Comment by costaq** [comment]
23寸宽屏显示器会出现这情况，笔记本没事，是不是计算高度的逻辑错了

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Could you help us to find out where is wrong? It is hard to find so large screen.

**Comment by benjycui** [comment]
Close for we cannot re-produce it without your special environment.
