### ISSUE TITLE
Menu下选择菜单Link跳转页面，点击后菜单背景颜色不会改变

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#5332]
只有在加了Link后会出现此问题，点击背景颜色不会出现，有时点两下会出现，还会出现混乱的现象

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.

![image](https://cloud.githubusercontent.com/assets/18717051/23987289/d04ba84e-0a63-11e7-8e1e-9f43e3ee2917.png)
去除link 标签后就会正常

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
