### ISSUE TITLE
Dragger component does not work with formDecorator

### ISSUE THREAD

**Issue by mimol91** [ant-design/ant-design#5334]
#### Environment(required)

- antd version: 2.8.1
- OS and its version Linux mint:
- Browser and its version Chrome :56

#### What did you do? Please provide steps to re-produce your problem.
Trying to use formDecorator with `Dragger` component.

P.S.
`Upload` works fine

#### What happen?
Error: Cannot read property `onChange` of undefined

#### Re-producible online demo
http://codepen.io/anon/pen/XMeyvb?editors=1111

## Hacky solution
Change `<Dragger>` to `<Upload  type={"drag"}>`

**Comment by benjycui** [comment]
`getFieldDecorator` cannot work with functional stateless component.
