### ISSUE TITLE
Table sorter only works in one direction.

### ISSUE THREAD

**Issue by JesperWe** [ant-design/ant-design#5335]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: na
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

Use a `sorter` on a table column 

#### What do you expected?

Clicking on one direction arrow produces the reverse sorting order of clicking the other.

#### What happen?

Sorting works in descending order, but not in ascending.

#### Re-producible online demo

Visible on https://ant.design/components/table/#components-table-demo-head:
Click "Up" on Name column produces: Jim - Jim - Joe - John.
Click "Down" incorrectly produces: John - Jim - Joe - Jim.

**Comment by yesmeck** [comment]
See source code, name is compared by length.

**Comment by JesperWe** [comment]
Sorry, I missed that in the demo, I just thought I could get by without creating a CodePen.
The problem is still there though.
Here is the CodePen: http://codepen.io/anon/pen/LWzogv?editors=001

**Comment by yesmeck** [comment]
CompareFunction should return a number than a boolean value. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by JesperWe** [comment]
I see. I was confused by the docs saying "function|boolean". Maybe change that to "boolean|function returning -1/0/1" ?

**Comment by yesmeck** [comment]
`function|boolean` means `sorter` can be a function or a boolean value. Maybe we add link to MDN.

**Comment by JesperWe** [comment]
I found more things missing in docs. Will write PR.

**Comment by jakelauer** [comment]
This issue does still happen. Please see this demo: https://codepen.io/anon/pen/rdKzZr?&editors=001

I have changed the ages so they are all different. Descending works correctly and produces [**41, 36, 32, 31, 22, 6**], but ascending produces [**32, 41, 22, 36, 6, 31**]. It looks to me like the data is being sorted in pairs (32, 41) / (22, 36) / (6, 31). Each of those pairs is sorted ascending, but the list of pairs is out of order.

**Comment by mftaha** [comment]
happens with me as well
