### ISSUE TITLE
getFieldDecorator is not defined

### ISSUE THREAD

**Issue by acmeid** [ant-design/ant-design#5337]
#### Form表单 getFieldDecorator is not defined

- antd version:2.8.1
- OS and its version: mac 10.11.6
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

根据官方文档书写Form表单的例子，报错： getFieldDecorator is not defined

**Comment by acmeid** [comment]
完善

**Comment by afc163** [comment]
It is working in demo, please check your code: https://ant.design/components/form/

**Comment by acmeid** [comment]
谢谢你的提醒
我的项目是使用dva-cli创建的，routes的写法是：
`
import React from 'react';
import { connect } from 'dva';
import styles from './order-add.less';
import { Table, Popconfirm, Button, Form, Row, Col, Input } from 'antd';
const createForm = Form.create;
const FormItem = Form.Item;

const orderAdd = (props) => {
  const { getFieldDecorator } = props.form
}

export default connect(({ orderAdd }) => ({
  orderAdd
}))(orderAdd);
`

对比官方的例子，我想我可能没有正确调用createForm导致的，我应该怎么去调用createForm才能让它正确运行？

**Comment by afc163** [comment]
按官方演示中的写法来写：https://ant.design/components/form/#components-form-demo-horizontal-login

**Comment by acmeid** [comment]
我想应该是要这么调用：

```
let WrappedOrderAdd = Form.create()(orderAdd)

export default connect(({ orderAdd }) => ({
  orderAdd
}))(WrappedOrderAdd);
```

@afc163 非常感谢~
