### ISSUE TITLE
IE11浏览器会出现【对象不支持“startsWith”属性或方法】

### ISSUE THREAD

**Issue by enet2006** [ant-design/ant-design#5338]
IE会出现JS异常， 对象不支持“startsWith”属性或方法。
js有用webpack做打包
-----------------------------------------------------------
这段代码导致的
  // check for non-matching names
	  if (!query.startsWith(name)) {
	    return false;
	  }

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

RTFM
