### ISSUE TITLE
Under the Menu selection Menu Link jump page, click on the Menu after the background color will not change

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#5339]
Only after added the Link tag will appear this problem, click on the background color won't appear, point two times sometimes occur, also can appear the phenomenon of chaos

#### Environment(required)

- antd version:"antd": "^2.8.1",
- OS and its version:
- Browser and its version:

#### What happen?
![image](https://cloud.githubusercontent.com/assets/18717051/23989130/39f75c86-0a6c-11e7-8716-5b6276794a98.png)
After remove the link tag will be normal

#### Re-producible online demo
https://github.com/SynChron1zed/itemPc

**Comment by SynChron1zed** [comment]
@benjycui

**Comment by benjycui** [comment]
An online demo is better in your use case. Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

> Only after added the Link tag will appear this problem, click on the background color won't appear, point two times sometimes occur, also can appear the phenomenon of chaos

And you had better to provide steps to re-produce it.

**Comment by SynChron1zed** [comment]
@benjycui 
http://codepen.io/anon/pen/JWOpLa?editors=1010

I don't know how the link tag should be introduced, the code is as follows.

**Comment by benjycui** [comment]
@SynChron1zed you can try to read CodePen's documentation..

**Comment by SynChron1zed** [comment]
@benjycui      I think I said the problem is very clear,  even if  link tag  dont introduced，you should help me 
![image](https://cloud.githubusercontent.com/assets/18717051/24128969/61072fa2-0e1a-11e7-9ed3-faad5fea55e3.png)

**Comment by afc163** [comment]
Please make your codepen working, or we cannot check your problem.

**Comment by SynChron1zed** [comment]
@afc163 I want to know link tag introduced ， codepen i dont find How to introduce ，Please！

**Comment by afc163** [comment]
<img width="606" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24133485/41bd1918-0e38-11e7-92f7-26fecc74503e.png">

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/24134187/7900f688-0e3d-11e7-9939-827e06c7eff5.png)

I don't want to waste time on this problem, this time I can use other methods to solve.codepen Really very convenient, but my page is comments, there are some other things.

https://github.com/SynChron1zed/itemPc

If you have time code I put on the git I don't think that solve the problem of speed is much slower than on codepen

thanks!

@afc163

**Comment by benjycui** [comment]
We want to help you. But we don't have so much time to dig into a pile of code.

So, please provide a re-producible online demo and steps which can re-produce your issue 100%.

Otherwise, just close your issue.

**Comment by afc163** [comment]
It is not a bug of antd. You have a wrong react-router config that clicking Link will re-render the Layouty component and the whole menus.

Check: https://github.com/SynChron1zed/itemPc/pull/1
