### ISSUE TITLE
Cascader search can't use [Backspace] delete single word and lose focus

### ISSUE THREAD

**Issue by angular-moon** [ant-design/ant-design#5340]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: window7
- Browser and its version: chrome  56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
use Cascader search,  can't use [Backspace] delete single word and lose focus.
A bad experience

#### What do you expected?
i think you kown

#### What happen?
delete all words and lose focus.

**Comment by benjycui** [comment]
Re-producible demo: https://ant.design/components/cascader-cn/#components-cascader-demo-search

**Comment by benjycui** [comment]
rc-cascader's keyboard support introduce this bug, https://github.com/react-component/cascader/blob/master/HISTORY.md#0110--2017-01-17

**Comment by angular-moon** [comment]
Thank you for responding so quickly

**Comment by Far3t** [comment]
Is there a workaround to make the backspace work in Cascader search? 
Or do we need to wait for a bugfix?
