### ISSUE TITLE
Locale-provider of Table for German missing selectAll and selectInvert

### ISSUE THREAD

**Issue by Knacktus** [ant-design/ant-design#5348]
Hi guys,

sorry, I don't know how to work with Github, so I can't submit a fix the proper way. I guess I would need to do something like a pull request?

AntD Version 2.81

For the German locale two entries for the table are missing. I've updated the de_DE.js and de_DE.d.ts file as follows. I'm a native German speaker, so the translation should be fine :-):

```
// de_DE.js
// selectAll and selectInvert were missing
// ...
    Table: {
        filterTitle: 'Filter-Menü',
        filterConfirm: 'OK',
        filterReset: 'Zurücksetzen',
        emptyText: 'Keine Daten',
        selectAll: 'Selektiere Alle',
        selectInvert: 'Selektion Invertieren'
    },
// ...
```

```
// de_DE.d.ts
// selectAll and selectInvert were missing
// ...
    Table: {
        filterTitle: string;
        filterConfirm: string;
        filterReset: string;
        emptyText: string;
        selectAll: string;
        selectInvert: string;
    };
// ...
```

Next weekend I'll lern this pull request stuff :-).

Cheers,

Jan

**Comment by benjycui** [comment]
Could you just PR to fix this? None of antd's maintainers know German..

**Comment by Knacktus** [comment]
OK, I'll give it a try (create a PR) in a couple of hours. Need to go to work now.
