### ISSUE TITLE
Dropdown 中 Menu.Item 包括的蓝色区域中文字之外的部分无法触发点击事件

### ISSUE THREAD

**Issue by TheWaWaR** [ant-design/ant-design#535]
测试页面 ( 0.10.0-beta25 ): http://ant.design/components/dropdown/ 

1. 点击 Menu.Item 蓝色区域中 文字之外的部分无法触发点击事件
2. 有时候点击文字本身也不会触发点击事件 (较难重现)

**Comment by TheWaWaR** [comment]
beta30 中还有同样的问题：第一次点击是可以触发点击事件的，之后点击蓝色非文字区域都无效。

**Comment by TheWaWaR** [comment]
<Dropdown> . <触发事件> 里面点击菜单好像都没反应了？

测试版本: http://ant.design/components/dropdown/  (0.10.1)

**Comment by afc163** [comment]
有的啊，看控制台。

**Comment by TheWaWaR** [comment]
好吧，已经可以了，因为我看之前都是 alert 的。
