### ISSUE TITLE
使用jest测试引入了antd的组件会报错

### ISSUE THREAD

**Issue by fariyAhill** [ant-design/ant-design#5362]
#### Environment(required)

- antd version:2.8.1
- OS and its version:macos 10.12.3
- Browser and its version: chrome  56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

1.在一个组件中引用antd的Calendar组件。以下是代码

`import React, { Component } from 'react';
import { Calendar } from 'antd';

function onPanelChange(value, mode) {
    console.log(value, mode);
}

class Root extends Component {
    render() {
        return (
            <div>hello</div>
        );
    }
}

export default Root;`

2.在测试文件中引用该组件进行测试。代码：
`import React from 'react';
import { shallow } from 'enzyme';

import Root from './index';

test('should have hello', () => {
    const wrapper = shallow(<Root />);
    expect(wrapper.text()).toEqual('hello');
})`

3.在项目目录中已经配置了babelrc
#### What happen?
执行jest index.test.js，报错提示为‘matchMedia not present, legacy browsers require a [polyfill’]([url](url
![jesterror](https://cloud.githubusercontent.com/assets/12928690/24031322/e76469ee-0b1c-11e7-98eb-37b1dd288406.png)
))

**Comment by fariyAhill** [comment]
如果在引用antd组件的文件中改为import Calendar from 'antd/lib/calendar' 的方式则不会报错；用import { Calendar } from 'antd' 的引入方式就有测试报错问题

**Comment by bang88** [comment]
在仓库根目录的测试目录找到match Media 的配置

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/blob/master/tests/setup.js

**Comment by fariyAhill** [comment]
@yesmeck  thanks
