### ISSUE TITLE
Antd Form2.8.1 动态增减表单项 Bug 反馈

### ISSUE THREAD

**Issue by duckywang1** [ant-design/ant-design#5363]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: MacOS 
- Browser and its version: Chrome 最新版

#### What did you do? 

照着官方写的 动态增减表单项 的demo。使用<对象数组>的时候出现问题。  
麻烦看一下我的 github READEME。已经写了详细的说明和必现的方法。也提供了打包后的文件，谢谢。

#### Re-producible online demo

在 https://github.com/duckywang1/issueforantdform

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

建议提供最小可重现demo，和构建无关的问题，没必要提供 repo

**Comment by duckywang1** [comment]
http://codepen.io/duckywang/pen/ZeaXaX

**Comment by duckywang1** [comment]
### 我干了什么／发生了什么：  

如何触发Bug:  
0. 打开 开发者工具 
1. 点击 Add Circle+++ 这个button。加载2个或以上的卡片。假设加载2个吧。以数组 [0, 1]表示其序号。可以往里面随意输入数据。
2. 点击<卡片0>右上角的delete，即可触发 remove 函数，删除<卡片0>。<卡片1>则成为数组中第一个卡片。
3. 再次点击 Add Circle+++ 这个button。新的卡片称之为<卡片2>。<卡片1>的数据消失，并且无法触发其 onchange 函数.(程序报错为 Cannot read property 'onChange' of undefined )。
4. <卡片2> 表现正常。

数据的监控：    
0. 加载2个卡片并且输入数据后，表单数据是这样的。
```
{
  radiusKeys: [
    0: 0,
    1: 1
  ],
  circle: [
    { color: 0, radius: 0 }
    { color: 1, radius: 1 }
  ]
}
```  
1. 删除卡片0后  
```
{
  radiusKeys: [
    0: 1,
  ],
  circle: [
    { color: 1, radius: 1 }
  ]
}
```  
1. 新建卡片2后  
```
{
  radiusKeys: [
    0: 1,
    1: 2
  ]
}
```    

经过不断地Log之后，估计是以下这段代码出现了问题：   

```
Form.setFieldsValue({
  key: value,
});

接着追踪到 rc-form / lib / createBaseForm.js 的 function setFields 的 nowValues[f] = _this6.getValueFromFields(f, nowFields); 这一行改动了数据。
```

Bug的特征：    
由于看不懂源码，只能提供一下出现错误的感觉。感觉是setFieldsValue的时候 index 和 unique key 冲撞了。

**Comment by hansnow** [comment]
It's not a bug. try this at line 46
``` diff
--- <Card title="收集信息" extra={<a href="javascript:void(0)" onClick={ (e) => _this.remove(k) } >Delete</a>} style={{ width: 300 }} key={index} >
+++ <Card title="收集信息" extra={<a href="javascript:void(0)" onClick={ (e) => _this.remove(k) } >Delete</a>} style={{ width: 300 }} key={k} >
```
demo: http://codepen.io/hansnow/pen/vxpXEx

every card should be set a **stable** key, but `index` are not stable, use `uuid` instead.

**Comment by afc163** [comment]
@hansnow is right. Same as:

https://github.com/ant-design/ant-design/issues/4478 
https://github.com/ant-design/ant-design/issues/4518
https://github.com/ant-design/ant-design/issues/1815

**Comment by Kaijun** [comment]
@benjycui @afc163 可以问下动态表单如何使用setFieldsInitialValue？还需要同时额外的设置keys吗？

**Comment by yyxie** [comment]
提交的数据中有undefined项，是因为什么？能避免吗？@afc163

**Comment by zoii** [comment]
@Kaijun 后来setFieldsInitialValue这个方法的问题你解决了吗 我现在也碰到类似的问题
