### ISSUE TITLE
When loading is true, the modal button should be disabled

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#5365]
#### Environment(required)
- antd version:2.8.1
- OS and its version: ubuntu 16.04
- Browser and its version: chrome 57

#### What did you do? Please provide steps to re-produce your problem.
Quick double click  modal ok button.

#### What do you expected?
When loading  is true, the button should be disabled

#### Re-producible online demo
http://codepen.io/xjdata/pen/XMzEKy

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4925

**Comment by afc163** [comment]
Maybe we should support `loading={{ delay: xxx }}` and default value of `delay` is 0.

@RaoHai
