### ISSUE TITLE
Async Table filters 异步加载表格的filters字段  

### ISSUE THREAD

**Issue by Justinidlerz** [ant-design/ant-design#5366]
异步加载表格的filters字段  

抱歉英文水平较差，如有语法错误还望多多包涵指出
本想开发这个功能再提PR的  
但近期工作较忙抽不开时间去阅读该部分代码  
所以仅到此提出这个问题

#### Environment(required)

- antd version: 2.8.0
- OS and its version: Mac OS Sierra 10.12.3
- Browser and its version: chrome  56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
When i want to use author key filter my article list table , authors list must be request from the server, but the columns filters only can set a array, so i can't async to set my authors list.
我使用Table组件想要过滤作者字段的时候发现作者字段只可以同步的形式传入一个数组被初始渲染，但是我的作者列表却需要通过服务器异步加载回来。

#### What do you expected?
Can i set a function in this key to callback event when i click the filter icon before open the filter list,  then i request and callback author list when the user to click the icon.
我希望可以给该字段传入一个回调方法，当点击这个过滤icon点击的时候触发这个事件返回这个列表

**Comment by yesmeck** [comment]
没看懂你的需求，能给个 demo 吗？ http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Justinidlerz** [comment]
大概这样：http://codepen.io/anon/pen/RpjyGj?editors=1111

**Comment by Justinidlerz** [comment]
sorry, 刚刚少写了一些内容，现在可以正常运行了

**Comment by yesmeck** [comment]
大概明白你的意思了。因为一开始 `column.filters` 是空的，所以过滤图标不会显示，但是你又希望在点击过滤图标后再去加载 `column.filters` 里的数据。

一个暂时比较 hack 的办法，先自己给 `column.title` 加一个过滤的图标，绑定点击事件，数据加载后再把自己加的图标去掉。
