### ISSUE TITLE
[BUG] Both add bordered and scroll.x to Table will made fixed column overflow

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5373]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: OS X
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

sample code bellow:

```
  <div style={{width: 1100}}>
      <Table scroll={{ x: 1200 }} columns={columns}
        dataSource={data} rowKey={record => record.id} bordered></Table>  
  </div>
```

#### What happen?

When I add bordered prop to Table component, fixed column will overflow:

![image](https://cloud.githubusercontent.com/assets/3498786/24047454/bd01054c-0b60-11e7-9589-1bb4bc4a788a.png)

if Increase the value of scroll.x, the overflow gap will bigger.

#### Re-producible online demo

http://codepen.io/wytwyt01/pen/XMzOXg?editors=0010

**Comment by afc163** [comment]
http://codepen.io/anon/pen/pedGwN?editors=0010

You should leave one column at least to be flexible width.

**Comment by TangMonk** [comment]
@afc163 

But the flexed column is too many spaces:

![image](https://cloud.githubusercontent.com/assets/3498786/24047973/5e47f068-0b62-11e7-9cbc-1a7845d0b2d5.png)

**Comment by afc163** [comment]
You can leave multiple columns to be flexible.

**Comment by TangMonk** [comment]
@afc163 thanks, I understood , The `scroll.x` equal to all the sum of fixed and flexed column width
