### ISSUE TITLE
http://design.alipay.com/develop/web/components/form/

### ISSUE THREAD

**Issue by lihua123569** [ant-design/ant-design#5376]
http://design.alipay.com/develop/web/components/form/
中文api打不开

**Comment by NE-SmallTown** [comment]
Seem like some code error make it crash.Try https://ant.design/components/form-cn/,IMO,if it is possible,search on https://ant.design/docs/react/introduce-cn is better than  http://design.alipay.com/develop/web/components/.

Finally,it will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by afc163** [comment]
https://ant.design/components/form-cn
