### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#5377]
#I notice that at react-conf [linclark](https://github.com/linclark) make a [speech](http://conf.reactjs.org/speakers/lin) about react-fiber,though [dan](https://github.com/gaearon) has post a few videos on youtube recent months.This means that it will release soon, [although it still hasn't done 100%](http://isfiberreadyyet.com/),but now it has been alpha.4.

So,I notice that there are many old or compatible components,methods,styles etc in antd,I agree with that they are important.But back to now and forward to the future,both for antd and ourselfs,we nedd to research something such as [[Fiber] Umbrella for remaining features / bugs](https://github.com/facebook/react/issues/7925), [React 15.5 and 16 Umbrella](https://github.com/facebook/react/issues/8854) (there are many concepts and new things so I can't list all of them,if you want to know,just search the '[Fiber]' as the key in React repo).

We should know which methods or concepts will be removed,such as [Plan for Addons in React 16](https://github.com/facebook/react/issues/9207) and what we can do to improve though fiber has been doing much and huge perf optimize for us and most of current api won't change.

So,IMO,I think maybe we can think about how to refactor from now,of course react team will post change log and upgrade guide,but we still need to go in depth to make us understand better.

Finally,I know it will spend long time and much energy to do it,but “The first step is always difficult".Hope this will helps.

---

Edited by @benjycui

A list of react-component that we need to make them support React@16

* [x] rc-animate
* [x] rc-calendar
* [x] rc-cascader
* [x] rc-checkbox
* [x] rc-collapse
* [x] rc-dialog
* [x] rc-dropdown
* [x] rc-editor-mention
* [x] rc-form
* [x] rc-input-number
* [x] rc-menu https://github.com/react-component/menu/pull/99
* [x] rc-notification https://github.com/react-component/notification/issues/21 https://github.com/ant-design/ant-design/pull/7844
* [x] rc-pagination
* [x] rc-progress
* [x] rc-rate
* [x] rc-select
* [x] rc-slider
* [x] rc-steps
* [x] rc-switch
* [x] rc-table
* [x] rc-tabs
* [x] rc-time-picker
* [x] rc-tooltip
* [x] rc-tree
* [x] rc-tree-select
* [x] rc-upload
* [x] rc-util

**Comment by afc163** [comment]
Yes, we can create new branch and update react to 16 Umbrella, and see what we can do at this moment.

**Comment by NE-SmallTown** [comment]
Yup,to be honest,I am too busy to go in depth into react-fiber,just hope this reminder would help :smiley:

**Comment by NE-SmallTown** [comment]
Maybe we need notice [this](https://github.com/facebook/react/issues/9214#issuecomment-287763538) because we have much animation.

**Comment by NE-SmallTown** [comment]
[remove React.createClass](https://github.com/facebook/react/pull/9232/commits/a425dfd277145705cd93073e2b43e794fdb6fd65#diff-5ea54557b8e1c5165984c312191ec8d3R74)

[relevant pr and more details](https://github.com/facebook/react/pull/9232)

I remember that antd and react-component before has discussed that change all ES5 syntax to ES6 and need time to do that.So,just for memo.

**Comment by benjycui** [comment]
There is not `React.createClass` in antd now, but react-component had use lots of `React.createClass`

You can grep to make sure this point.

**Comment by afc163** [comment]
There are lots of work~

**Comment by NE-SmallTown** [comment]
@benjycui Yep,update comment.Sorry for that I don't describe very clear,my actual meaning is that antd rely on react-component,so if react-component don't change,so antd's change will be limited too.

**Comment by NE-SmallTown** [comment]
@afc163 Yeah,for everyone is too.Maybe make to our goal this year? :smile:

**Comment by monkindey** [comment]
Can [this one](https://github.com/reactjs/react-codemod) helps? Or be inspired by it?

**Comment by NE-SmallTown** [comment]
@monkindey I almost forget it.Thanks!But so far I don't use it,so have no experience on it.Waiting evaluation of members~

**Comment by monkindey** [comment]
yep, I think there will be some unpredictable situation using it, but may be we can learn something from it.

**Comment by monkindey** [comment]
According to [dan twitter](https://twitter.com/dan_abramov/status/844525649318567937) and [acdlite pr](https://github.com/facebook/react/pull/9232), may be we can import the `react-create-class` package, no need to rewrite anything.

**Comment by NE-SmallTown** [comment]
[Is there any side effect or perf affect of this change](https://twitter.com/Heaven_xz/status/844541270408122368) and [what's your suggestion on our project which use React.createClass?Stay current,use codemod,or use ES6?](https://twitter.com/dan_abramov/status/844542453860483072) and [Could you tell me what's your reason of chosing that use a codemod to ES6](https://twitter.com/Heaven_xz/status/844552426204020736)

**Comment by NE-SmallTown** [comment]
[onChange -> onInput, and don't polyfill onInput for uncontrolled components](https://github.com/facebook/react/issues/9657)

This maybe is just a idea,so just for reminding

**Comment by NE-SmallTown** [comment]
Form this [tweet](https://twitter.com/dan_abramov/status/908484886734008320), it seems that maybe we need refactor(I don't dig into the src code so I am not sure whether we have the usage in the tweet).

And there are 2 codeopen you can view:

[before(react 15)](https://codepen.io/NE-SmallTown/pen/OxVbvJ?&editors=001)

[now(react 16)](https://codepen.io/NE-SmallTown/pen/OxVbvJ?&editors=001)

cc @afc163

**Comment by monkindey** [comment]
Related usage information 

https://github.com/facebook/react/issues/10309#issuecomment-318433235

Now you can use `createPortal` instead of `unstable_createPortal`

**Comment by wangyazhen** [comment]
Keep an eye on

**Comment by afc163** [comment]
- [ ]  https://github.com/ant-design/ant-design/issues/7784
- [ ] https://github.com/ant-design/ant-design/issues/7754

**Comment by pdeva** [comment]
considering all linked issues are closed, can we mark this issue as closed and do a release `2.13.5` with React 16 supported?...

**Comment by malekjaroslav** [comment]
That would be awesome!

**Comment by abenhamdine** [comment]
> considering all linked issues are closed, can we mark this issue as closed and do a release 2.13.5 with React 16 supported?...

I don't think it's sufficient, every rc component listed at the top of this thread has to be updated in order to support react16.

**Comment by ZheyangSong** [comment]
Tracking...Really need to see support to `react-fiber`.

**Comment by yesmeck** [comment]
A highlight note after upgrade to React 16 (See https://github.com/react-component/trigger#react-16-note), some components rely on rc-trigger or using `ReactDom.createPortal` will introduce a breaking change.

**Comment by pencilcheck** [comment]
Is there any workaround for now to use react 16 with antd?

**Comment by Harrisonl** [comment]
Just wondering if there is a way branch that gets react 16 working with antd yet? Or an estimated date? Love the library and the support you guys provide and would love to see it grow with the react community.

**Comment by abenhamdine** [comment]
rc-time-picker  can be checked, see https://github.com/react-component/time-picker/commit/fd231e087cdf327826297e58c5b4a8a895ec9e40

**Comment by afc163** [comment]
Not yet until we upgrade rc-time-picker version in branch antd-3.0.

**Comment by abenhamdine** [comment]
> Not yet until we upgrade rc-time-picker version in branch antd-3.0.

ah ok sorry for the noise

**Comment by RaoHai** [comment]
+ https://github.com/react-component/editor-mention/pull/20

**Comment by yesmeck** [comment]
All `rc-component` antd rely on has upgrade to React 16.

**Comment by malekjaroslav** [comment]
@yesmeck will there be an update of dependencies in `antd`?

**Comment by yesmeck** [comment]
Yes, we are updating dependencies, https://github.com/ant-design/ant-design/pull/8150

**Comment by int64ago** [comment]
@yesmeck Any plan for release date ?

**Comment by yesmeck** [comment]
The end of this month.

**Comment by damiangreen** [comment]
Was this released? Which version?

**Comment by iugo** [comment]
@damiangreen v3.0.0 https://github.com/ant-design/ant-design/blob/master/CHANGELOG.en-US.md#300

**Comment by feibi** [comment]
record it, form still warn it
