### ISSUE TITLE
InputNumber不支持小数？

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#538]
0.9.5版本的InputNumber不能输入小数点，且step最小值为1。
可否支持2位小数？step为1倒是可以接受。

**Comment by yiminghe** [comment]
不要用小数，浮点运算不准确

**Comment by xiao-hai** [comment]
@yiminghe 如果不考虑精度问题呢？控件能否这么做。

**Comment by afc163** [comment]
duplicate issue #530
