### ISSUE TITLE
Local css/less module support

### ISSUE THREAD

**Issue by JasonKid** [ant-design/ant-design#5385]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: not important
- Browser and its version: not important

#### What did you do? Please provide steps to re-produce your problem.
My website is not use antd for global, but I just want use some of the components of antd. I have my own normal css, but after I import a component and its style, it overrides my normal css.

#### What do you expected?
import the style with a css module.

#### My temporary solution 
<index.jsx>:
```
import 'antd/lib/date-picker/style/index.css';
import 'antd/lib/input/style/index.css';
import 'antd/lib/time-picker/style/index.css';
```

<index.less>
```
:global {
  .antd {
    @import "~antd/lib/style/themes/default";
    @import "~antd/lib/style/core/index";
  }
}
```

After that, append className 'antd' for the antd component wrapper.

**Comment by yesmeck** [comment]
Hello @JasonKid , we don't have plan to support css modules.

**Comment by zhaozhiming** [comment]
@yesmeck why? It seems antd's early version can support css module, why the latest version not?

**Comment by benjycui** [comment]
> @yesmeck why? It seems antd's early version can support css module, why the latest version not?

It depends on your webpack config, not antd.

**Comment by zhaozhiming** [comment]
@benjycui Could you show out the correct webpack(2) config for antd? My webpack config as follow:

```js
{
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              modules: true,
              localIdentName: '[name]__[local]--[hash:base64:5]'
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: () => [
                autoprefixer({
                  browsers: [
                    '>1%',
                    'last 4 versions',
                    'Firefox ESR',
                    'not ie < 9',
                  ],
                }),
              ],
            },
          },
        ],
      },

```

**Comment by benjycui** [comment]
@yesmeck means that antd doesn't use css-modules.

I am sorry that I am not familiar with webpack@2.
