### ISSUE TITLE
关于getFieldDecorator的报错信息

### ISSUE THREAD

**Issue by acmeid** [ant-design/ant-design#5386]
我在使用getFieldDecorator的时候遇到了一个无法解决的问题

- antd version:2.8.1
- OS and its version:mac 10.11.6
- Browser and its version:chrome 56.0.2924.87 (64-bit)

```
                  <FormItem label="收货人手机" colon={false}>
                    {getFieldDecorator('phone', {
                      initialValue: phoneaaa,
                      rules: [{ required: true, message: '请输入收货人手机号码' },
                      { len: 11, message: '请输入正确的手机号码' }],
                    })(
                      <Input type="tel" />
                    )}
                  </FormItem>
```

```
let WrappedOrderAdd = Form.create({
  onFieldsChange (props, fields) {
    console.log(fields)
    // props.dispatch({ type: 'orderAdd/changeForm', payload: {nihao: 136} });
  },
  mapPropsToFields (props) {
    // console.log(props)
  },
  onValuesChange (props, values) {
    // console.log(values)
    props.dispatch({ type: 'orderAdd/changeForm', payload: 11 });
  }
})(orderAdd)
```

浏览器报错：

> Uncaught TypeError: Cannot read property 'phone' of undefined

我看了文档，但是没有说需要在哪里定义'phone'。希望可以提供一些帮助解决这个报错问题

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by bang88** [comment]
```js
mapPropsToFields (props) {
    // console.log(props)
这里要有返回值

  },
```

**Comment by acmeid** [comment]
@bang88  非常感谢
我明白了，mapPropsToFields 和 onFieldsChange 可以粗略理解成是建立双向绑定。

厚颜无耻的再提个问题，假如建立多个绑定：
// state:
{
  formData = {
    name: {value: null},
    phone: {value: null}
    ......
  }
}
// options:
mapPropsToFields (props) {
  return {
    name: {
      ...props.app.formData.name,
      value: props.app.formData.name.value,
    }
    phone: {
      ...props.app.formData.phone,
      value: props.app.formData.phone.value,
    },
    ......
  };
}

这里是否有更加简洁的写法？可以遍历formData简洁的把数据return出去🤔
我自己试了几次没有成功，查看了文档和[rc-form](http://react-component.github.io/form/)，发现都是只写了一个，希望能给个例子或者提示😁

**Comment by benjycui** [comment]
自行写个工具函数即可。
