### ISSUE TITLE
Rewrite demo in TypeScript?

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5390]
So that we can find issues in TypeScript definition.

We can upgrade demos' format:

```tsx
// components/*/demo/basic.tsx
demo
  .meta({...})
  .intro(`
  markdown syntax
  `)
  code(() => {

  })
  .css...
```

While building website, we transform TypeScript to ES2016, so that developers cannot tell any differences.

**Comment by afc163** [comment]
> we transform TypeScript to ES2016

If we can do this, we should put a RadioButton of switching demo code between TypeScript and ES6.

**Comment by paranoidjk** [comment]
Agree with write demo in typescript and compile it to ES6， but @benjycui demo code syntax not feel very good，suggest we still use markdown meta info

**Comment by benjycui** [comment]
> suggest we still use markdown meta info

If we write demo code in markdown file, VSCode cannot show Type warning..

**Comment by paranoidjk** [comment]
@benjycui
 ok,  understand. I just want to make sure that we still can display demo code on website as the same way.

**Comment by benjycui** [comment]
We can support both of markdown and new syntax.

**Comment by paranoidjk** [comment]
Suggest we do this earlier. Many tsd problem could be found during development.

https://github.com/ant-design/ant-design-mobile/commit/e4a496e0d681388f0966d87f2af9562036f9175a
https://github.com/ant-design/ant-design-mobile/commit/5fd21d1539f19fe80fd415716d349d82c1a77408

...etc

cc @shepherdwind

**Comment by paranoidjk** [comment]
cc @jljsj33

**Comment by yesmeck** [comment]
How about separate ts code from markdown? `basic.md` loads the same name `basic.tsx` automatically through bisheng-plugin-antd.

**Comment by emersonlaurentino** [comment]
What do you think about using [MDX](https://github.com/mdx-js/mdx)?

**Comment by afc163** [comment]
Already supported in 4.0: https://github.com/ant-design/ant-design/blame/master/components/form/demo/basic.md

<img width="978" alt="image" src="https://user-images.githubusercontent.com/507615/75510863-40773500-5a27-11ea-9db1-0129de4fc14c.png">

Feel free to migrate more examples to TypeScript.
