### ISSUE TITLE
Upload 组件没有办法设置timeout？

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#5394]
Upload 组件没有办法设置timeout？

**Comment by afc163** [comment]
I don't understand your problem.

Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by CyanChoi** [comment]
同问，超过一分钟的就直接502了，文件小的可以上传成功

**Comment by forever4313** [comment]
@CyanChoi  是这样的，如果不设置timeout，默认请求是无限时长的，
所以，如果你这个1分钟应该是服务器拦截掉的，
如果你们用nginx，可以考虑将nginx里的timeout 设置的长一点。
如果是tomcat 也把对应的timeout设置久一点。
不同服务器有不同的设置方式
