### ISSUE TITLE
modal 内容里select位置错乱

### ISSUE THREAD

**Issue by wangyazhen** [ant-design/ant-design#5395]
**Modal** 弹出后我能通过什么方法来给`html`添加`overflow: hidden`  防止页面滚动   
目前只是给`body` 添加了`overflow: hidden` 但是页面内容还是可以滚动的. 

`modal`中如果有`select` 就会导致位置错乱. 

Hope to answer as soon as possible, will be appreciated .

**Comment by afc163** [comment]
I am no sure what your problem is? Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by wangyazhen** [comment]
codepan 地址: [demo](http://codepen.io/anon/pen/BWYyXG)
正常时候:
![image](https://cloud.githubusercontent.com/assets/5687531/24090627/eba97e42-0d7c-11e7-92b5-ce26473e5453.png)

出现的问题:
![image](https://cloud.githubusercontent.com/assets/5687531/24090679/62497c64-0d7d-11e7-9bf9-15226ecd2dc3.png)

**Comment by wangyazhen** [comment]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: win 10
- Browser and its version: chrome 56.0.2924.87

**Comment by afc163** [comment]
> 弹出后我能通过什么方法来给html添加overflow: hidden 防止页面滚动
目前只是给body 添加了overflow: hidden 但是页面内容还是可以滚动的.

> modal中如果有select 就会导致位置错乱.

这是两个问题还是同一个问题？

**Comment by wangyazhen** [comment]
是一个问题,  
因为我发现位置错乱是因为页面还能滑动,  

如果给`html`加上`overflow: hidden` 不让它滚动就可以解决这个问题了  
但我不知道应该用什么方法给`html`加样式

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#API

看看 `getPopupContainer`。

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/3487

**Comment by wangyazhen** [comment]
那如果弹出`modal`后  怎么不让`html`滚动 
这算一个新的问题了吧 是否要 `new issue`

**Comment by afc163** [comment]
就在这里讨论即可。

html 会滚动一般是全局样式没设好，看看能否在 codepen 里重现出来？

**Comment by wangyazhen** [comment]
在刚才的那个[code demo](http://codepen.io/anon/pen/BWYyXG)中  滑动鼠标轮 可以看到 `antd version`的滚动

**Comment by afc163** [comment]
我这里没有出现滚动条，你能录制一个 gif 看看么？

<img width="1182" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24092875/0c625da2-0d8c-11e7-8fef-d5b6fb7efc29.png">

**Comment by wangyazhen** [comment]
没有滚动条,  但是可以滑动, 就转动鼠标轮就能看到了

![t](https://cloud.githubusercontent.com/assets/5687531/24094024/c297bab8-0d91-11e7-8d23-7c21da76459c.gif)

**Comment by afc163** [comment]
找了一个鼠标还是没重现出来.. 😓 

另外这段代码是参考自 bootstrap：http://getbootstrap.com/javascript/#modals 目测它也没有给 html 去加 `overflow: hidden`。按目前的信息我暂时不确定是 html 标签的问题。

**Comment by wangyazhen** [comment]
这个问题不是bug, 我想问的是怎么通过一个比较优雅点的方法, 比如监听`modal`弹出事件 来做给`html`标签添加样式去掉样式的这个事情

![t](https://cloud.githubusercontent.com/assets/5687531/24094609/6f6c7dbc-0d94-11e7-808b-c38d5413a9d1.gif)

**Comment by afc163** [comment]
visible 是你控制的，在 visbile 被 setState 时去操作 dom 即可。

**Comment by wangyazhen** [comment]
我这么想过, 但是我有好几个modal的  不能在每个地方都去操作吧 .

**Comment by afc163** [comment]
封装一个 Modal 来调用。

这个问题看上去很奇怪，我找台 windows 机器试试，感觉滚动条不应该出现。

**Comment by wangyazhen** [comment]
谢谢你的耐心解答, 祝 **ant-design** 越来越好 💯
