### ISSUE TITLE
Issue template site

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5396]
https://github.com/vuejs/vue/commit/84856a3a767084fa5b93a85ea5e75720f84d370e

- [x] https://github.com/vuejs/vue-issue-helper
- [x] bot：https://github.com/vuejs/vue/issues/5225#issuecomment-287662951

**Comment by yesmeck** [comment]
I'm curious how they implement the bot.

**Comment by bang88** [comment]
https://github.com/github/hubot

**Comment by bang88** [comment]
Or write a node server use github 's webhook

**Comment by yesmeck** [comment]
We can build a bot like @facebook-github-bot.

**Comment by yesmeck** [comment]
@afc163 Need a domain `new-issue.ant.design`.

**Comment by yesmeck** [comment]
https://ant-design.github.io/antd-issue-helper/

**Comment by afc163** [comment]
Added

**Comment by benjycui** [comment]
And `new-issue.mobile.ant.design` ?

**Comment by yesmeck** [comment]
`https://new-issue.ant.design?repo=ant-desgin-mobile`

**Comment by paranoidjk** [comment]
@yesmeck do you create a bot to auto close issue  too?

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-bot ...
