### ISSUE TITLE
Usage of Modal maybe could be improved

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#5398]
Current the [doc](https://github.com/ant-design/ant-design/blob/master/components/modal/demo/basic.md) usage:

```
<Button type="primary" onClick={this.showModal}>Open a modal dialog</Button>

<Modal title="Basic Modal" visible={this.state.visible} onOk={this.handleOk} onCancel={this.handleCancel}
>
```

I think maybe we can assess how much is the possibility of the user will click the button.If it is probable,above usage is good.But if not,maybe we can use:

```
<Button type="primary" onClick={this.showModal}>Open a modal dialog</Button>

{this.state.visible && <Modal title="Basic Modal" visible={this.state.visible} onOk={this.handleOk} onCancel={this.handleCancel}}
```

to avoid unnecessary code execution.

**Comment by afc163** [comment]
That will make Modal render and destroy repeatly when visible is changed.

**Comment by NE-SmallTown** [comment]
Yup,but like login box,image that you are watching a live stream,if you want login,you will click the button,visible(false) -> true,and then after you login,the button will become your avatar,so,there is no opportunity to change the visible again,because the <Button> has been removed.

And if you don't want to login(assuming the live stream website allow you watch HD even you don't login),you will not click the button,so you won't click it forever.So we don't need to execute the extra code.

**Comment by afc163** [comment]
`visible` is controlled all by yourself. When you login, you must set visible to false to make login modal disappear.

**Comment by afc163** [comment]
And rc-dialog had optimized the unshown dialog initial render perfermance by a lazy render box: https://github.com/react-component/dialog/blob/master/src/LazyRenderBox.tsx

**Comment by NE-SmallTown** [comment]
Ye,I have noticed `LazyRenderBox.tsx` when I check the src code yesterday.

But sorry for that I don't understand your meaning about "render and destroy process would be a bigger perfermance issue then render a lazy modal **once**".

Assume I am a user,I go to a website,there is a "login in" button.So,I have 2 choices:

- One: don't click the "login in" button because I just want to look through some contents of the website and also offline will not affect me to look through.

So,in this situation,use `{this.state.visible && <Modal ...... />}` is better than `<Modal visible={this.state.visible}`.

- Two: I decide to login in,but from sociology,user won't click the login in button and then close it in most cases.So,`this.state.visible` from `false` to `true`,and then we render the `Modal` component.And after the user click the `ensure` button,`this.state.visible` from `true` to `false`.So the usage of `{this.state.visible && <Modal ...... />}` will cause the `Modal` component unmount.

Here the most important thing is that `this.state.visible` **won't change** anymore,because the `login in` button **has disappeared** and **become your avatar**.

But the usage of `<Modal visible={this.state.visible} />` will cause the component **still exists** in the page,we **can't show the modal again** because the login in button has disappeared.There is no reason to make it alive.

In the doc,the most important reason we need the `<Modal visible={this.state.visible} />` usage is that we can show and close it **many times**.But as I say above,it is not appropriate for the particular case.
