### ISSUE TITLE
table的滚动scroll滚动条可以支持大小设置吗？

### ISSUE THREAD

**Issue by vipweixiao** [ant-design/ant-design#5403]
antd.2.2.0版本，滚动条特别小，想调大点，不知如何设置（看文档中比这大...）

![image](https://cloud.githubusercontent.com/assets/17379078/24093477/fb6d0652-0d8e-11e7-9a4a-d48acb39e52f.png)

**Comment by afc163** [comment]
We don't override scroll bar style, I think it is your code.
