### ISSUE TITLE
Suggestions: control display/hidden for each component.

### ISSUE THREAD

**Issue by ckcz123** [ant-design/ant-design#5405]
I wonder if we can add `hidden` option for each component?

That is, we can use a bool state to control whether to display a certain component, such as Alert (e.g. login error) or some forms (e.g. some additional information for users to fill).

That is, we can use 
`<Alert message={errorMsg} type="error" hidden={!loginError} showIcon  />`
instead of
`{loginError?<Alert message={errorMsg} type="error" showIcon />:""}`

**Comment by afc163** [comment]
You should use like ` {loginError ? <Alert message={errorMsg} type="error" showIcon /> : null}`, it is our and React's recommendation.

https://facebook.github.io/react/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored
