### ISSUE TITLE
[Table] Popover and SelectionCheckboxAll items behaviour

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5407]
In case of table inside of Popover any click on 'selectAll' will close Popover.

**Comment by hansnow** [comment]
There is no `event argument` passed to `rowSelection`'s `onSelectAll` or `onSelectInvert`, so controlling `Popover.visible` manually seems to be the only choice for the moment.

**Comment by afc163** [comment]
@plandem 
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by plandem** [comment]
sure. here is it:
http://codepen.io/anon/pen/mWXYVx?editors=001
