### ISSUE TITLE
validateFieldsAndScroll does not work with nested getFieldDecorator

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#5410]
- antd version: 2.7.1
- OS and its version: Mac Os Sierra
- Browser and its version: chrome 56

#### What did you do? Please provide steps to re-produce your problem.

using `validateFieldsAndScroll` with nested getFieldDecorator.id. eg
```
{getFieldDecorator('user.firstName', {
              })(
                <Input
                  type="textarea"
                  rows={4}
                />)}
```
#### What do you expected?

validate and scroll to the `user.firstName` input

#### What happen?

does not scroll

#### Re-producible online demo

http://codepen.io/kossel/pen/xqpbww?editors=0010

Additional information:

I debugged it, looks like it's problem of rc-form:
cause:
https://github.com/react-component/form/blob/master/src/createDOMForm.js#L63
when use id with "." (dot)  such as "user.firstname" can not find the instance because `user.firstName != 'user.firstName'`

root cause:
https://github.com/react-component/form/blob/master/src/createBaseForm.js#L307
lodash set will make the fieldKey (id) `user.firstName` into  `user={firstName: 'value'}`

so I changed it to 
` alreadyErrors[name] = { errors: field.errors } ;`
works so far, **but I not sure if this will create any side effect**, or there is a better solution.
If needed I can create a PR but I would like to know your opinion

**Comment by benjycui** [comment]
You can try to PR to rc-form, then we can review you changes. Thanks.

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`
