### ISSUE TITLE
Progress 组件在 TypeScript 2.2.1 中提示错误

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#5414]
Error:(85, 21) TS2605:JSX element type 'Progress' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Progress'.
Error:(85, 21) TS2607:JSX element class does not support attributes because it does not have a 'props' property

WebStorm 提示错误，但是可以编译通过，是用法有问题么？

antd 版本 2.8.1

![screen shot 2017-03-21 at 10 49 43 am](https://cloud.githubusercontent.com/assets/138192/24130587/7e93e29a-0e24-11e7-9093-ba79d2a15b85.png)
![screen shot 2017-03-21 at 10 50 00 am](https://cloud.githubusercontent.com/assets/138192/24130588/7e9484b6-0e24-11e7-8407-b2610ec62c80.png)

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is+not+a+constructor+function+is%3Aclosed

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#typescript

**Comment by abbish** [comment]
我添加了 https://github.com/ant-design/ant-design#typescript 中提到的配置选项，所以可以编译通过，只是 WebStorm 上面依旧留下了这些提示信息

**Comment by afc163** [comment]
感觉是 WebStorm 的配置问题？

**Comment by abbish** [comment]
感觉 webstorm 没有正确使用 tsconfig.json 去做提示检查
