### ISSUE TITLE
Carousel 组件结合Layout.Content 和Layout.Sider 组件使用宽度超出屏幕

### ISSUE THREAD

**Issue by K-walker** [ant-design/ant-design#5415]
使用Layout组件进行布局，发现在Content组件中嵌套Carousel组件，在有Sider组件的情况下，Carousel组件宽度会超出屏幕，下面会出现滚动条，代码如下：
```
class Main extends React.Component {
	render () {
		return (
			<Layout>
				<Layout>
					<Content>
						<Carousel autoplay dots="false" >
							<div>1</div>
							<div>2</div>
							<div>3</div>
						</Carousel>
					</Content>
					<Sider></Sider>
				</Layout>
			</Layout>
		)
	}
}
```
如果把Sider组件去掉，就能正常显示，加上Sider组件，Carousel组件的宽度就会超出屏幕，这算不算bug啊，求解！

**Comment by K-walker** [comment]
找到解决方法了，给`Content  `组件加个 `overflow:hidden` 即可

**Comment by benjycui** [comment]
> 找到解决方法了，给Content组件加个 overflow:hidden 即可

这个会把 Carousel 给裁剪掉一部分吧？

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by huyawei** [comment]
http://codepen.io/huyawei/pen/NpyVzQ

**Comment by benjycui** [comment]
@huyawei 只给 demo，不描述问题，看不懂的。

**Comment by huyawei** [comment]
@benjycui   (⊙o⊙)… 我是帮lz回答的  加了 overflow:hidden没问题
里面放了两个 layout 第一个对content加了overflow hidden
第二个是lz的代码

**Comment by K-walker** [comment]
@benjycui 我的问题已经描述很清楚了啊，上面就是我的代码啊

**Comment by afc163** [comment]
@K-walker 

一个可重现的 codpen 能节约很多时间 😃，就像 @huyawei 帮助提供的那样。

**Comment by K-walker** [comment]
@afc163  我昨天注册了半天，硬是没收到codepen的邮件，所以用不了，好忧桑

**Comment by afc163** [comment]
不用注册的，我都是匿名用。

（我一登录就跳转死循环 😓 ）

**Comment by K-walker** [comment]
@afc163  好了，这是问题demo [GWxBoe](https://codepen.io/anon/pen/GWxBoe) 问题的描述我写在css 注释中。
