### ISSUE TITLE
getFieldDecorator id嵌套写法

### ISSUE THREAD

**Issue by acmeid** [ant-design/ant-design#5416]
[this.props.form.getFieldDecorator(id, options)](https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options))

id嵌套写法没有生效

- antd version: 2.8.1
- OS and its version: mac 10.11.6
- Browser and its version:  chrome 56.0.2924.87 (64-bit)

关键代码如下：
```
<FormItem label="数量" colon={false}>
  {getFieldDecorator('services[0].num', {
      rules: [{ required: true, message: '请输入数量' }],
   })(
      <InputNumber />
   )}
</FormItem>

services: [{
    num: {value: 1}
}]
```

上面代码中的services没有同步到表单中
我已经执行了Form.create，并正确书写了mapPropsToFields。
假如上面不是嵌套写法，model和表单里面都去掉services这一层，则是正常的。

我希望可以正确运行嵌套写法，最好文档可以提供例子。

**Comment by afc163** [comment]
http://react-component.github.io/form/examples/nested-field.html

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
close for no response
