### ISSUE TITLE
Can't resolve './UploadList'

### ISSUE THREAD

**Issue by wangqianliangM** [ant-design/ant-design#5417]
#### Environment(required)

- antd version: 2.8.2
- OS and its version: macOs 10.12.3
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
`import { Upload } from 'antd'`

and use babel-plugin-import to pack

#### What do you expected?
It works fine as official website.

#### What happen?
```ERROR in ./~/antd/lib/upload/Upload.js
Module not found: Error: Can't resolve './UploadList' in '..../node_modules/antd/lib/upload'
```

**Comment by afc163** [comment]
Try `rm -rf node_modules && npm install`

**Comment by wheatma** [comment]
It works, but why? @afc163
