### ISSUE TITLE
最低能兼容到 ie几

### ISSUE THREAD

**Issue by liaohui1080** [ant-design/ant-design#5419]
最低能兼容到 ie几,

**Comment by yesmeck** [comment]
IE9.

**Comment by afc163** [comment]
文档里能找到的不要轻易开 issue。

**Comment by liaohui1080** [comment]
SCRIPT5022: matchMedia not present, legacy browsers require a polyfill
MediaQueryDispatch.js (15,1)

ie9下出现这样的错误

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started-cn#兼容性
