### ISSUE TITLE
DatePicker的disabledDate如何选择多个时间段？

### ISSUE THREAD

**Issue by conan2008** [ant-design/ant-design#5422]
const disabledDate = function (current) {
  // can not select days after today
  return current && current.getTime() > Date.now();
};

ReactDOM.render(
  <DatePicker disabledDate={disabledDate} />
, mountNode);

请问如何禁选多个时间段。比如禁止选择 2017-03-11到 2017-03-14  和  2017-04-11到 2017-04-14

**Comment by afc163** [comment]
It is a function, you can disable whatever the date you want.
