### ISSUE TITLE
loadData tree alway get this error:cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by zyx4986** [ant-design/ant-design#5424]
i use tree like this:

Tree loadData={onLoadData}
{treeNode}
/Tree

but it get this error when i expand a node：
uncaught typeerror:cannot read property 'then' of undefined

though it work well, i want known the reason

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
close for no response
