### ISSUE TITLE
Add a step by step instruction of TypeScript

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5426]
@bang88 @infeng @yesmeck 

Seems we need a documentation for new ts users.

**Comment by bang88** [comment]
#5390 I think this will be more acceptable. don't want write documents. show me the code 😄

**Comment by afc163** [comment]
It is more about workflow, tsconfig and enviornment, not a specified component usage.

**Comment by bang88** [comment]
Get,  thus we need a complete example. not just document it.

**Comment by yesmeck** [comment]
How about add a individual page on website for TypeScript users which covers two parts:

1. Create a TypeScript antd project from scratch;
1. A FAQ list for common errors.

**Comment by infeng** [comment]
we can also introduce how to use Typescript in vscode and provide a antd code snippets extension in vscode.

**Comment by afc163** [comment]
Like: https://ant.design/docs/react/use-with-create-react-app

**Comment by bang88** [comment]
- [x] Code Snippets Extension https://github.com/bang88/antd-snippets
- [x] create-react-app-typescript https://github.com/wmonk/create-react-app-typescript

**Comment by eaglepigjim** [comment]
It would be awesome if each of the demos had an option to see the code in ES6 or Tyescript

**Comment by seamc** [comment]
I have been successful with using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript), ejecting, and adding `babel-loader` to the webpack pipeline.  TypeScript can target ES6 and adding Babel allows for use of `babel-plugin-import`.

```bash
$ npm install -g create-react-app yarn react-scripts-ts
```
... 

```bash
$ create-react-app antd-demo-ts --scripts-version=react-scripts-ts
```

```bash
$ cd antd-demo-ts
$ yarn start
```

Install `antd`, update `App.tsx`, etc.  Check out the import situation.  Then eject.

```bash
$ yarn run eject
```
...
```bash
$ yarn add babel-core babel-loader babel-plugin-import babel-preset-react babel-preset-es2015 --save-dev
```

config/webpack.config.dev.js
```diff
{
  test: /\.(ts|tsx)$/,
  include: paths.appSrc,
+  loader: 'babel!ts'
-  loader: 'ts',
},
```

Create `.babelrc`
```diff
+{
+    "presets": ["react", "es2015"],
+    "plugins": [["import", {"libraryName": "antd", "style": "css" }]]
+}
```

Update `tsconfig.json`.
```diff
{
  "compilerOptions": {
    "outDir": "build/dist",
+   "module": "es6",
-   "module": "commonjs",    
+   "target": "es6",
-   "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": false,
+   "jsx": "preserve",
-   "jsx": "react",    
    "moduleResolution": "node",
    "rootDir": "src",
+   "forceConsistentCasingInFileNames": false,
-   "forceConsistentCasingInFileNames": true,

+   "allowSyntheticDefaultImports": true,

  ...

```

Importing an individual component and its CSS should now work as intended.

**Comment by mixj93** [comment]
thx a lot!
AllowSyntheticDefaultImports: true REALLY useful!

**Comment by abenhamdine** [comment]
I tried steps described in https://github.com/ant-design/ant-design/issues/5426#issuecomment-288543893 and it works perfectly thx a lot !

**Comment by afc163** [comment]
@seamc Could you add this into offcial documentation?

**Comment by abenhamdine** [comment]
For future readers : please see pending PR https://github.com/ant-design/ant-design/pull/6193 and  comments in order to use last version of create-react-app-typescript

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/pull/8230
