### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by aaronplanell** [ant-design/ant-design#5428]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: Ubuntu 16.04
- Browser and its version: Google Chrome Versión 57.0.2987.98 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

I'm using some components in a project and they fail when I create the snapshots with Jest.

#### What do you expected?

Works fine.

#### What happen?

It lauchs this error:
```
    TypeError: Cannot read property 'ownerDocument' of null
      
      at offset (node_modules/rc-tabs/lib/InkTabBarMixin.js:44:17)
      at _componentDidUpdate (node_modules/rc-tabs/lib/InkTabBarMixin.js:63:25)
      at componentDidMount (node_modules/rc-tabs/lib/InkTabBarMixin.js:116:5)
      at chainedFunction [as componentDidMount] (node_modules/react/lib/ReactClass.js:521:9)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
```

But, if i mock 'antd' the problem dissapear:
```
jest.mock('antd');
```

In fact, it works only mocking the *rc-tabs* component:
```
jest.mock('rc-tabs');
``` 

The problem is that when I mock the antd/rc-tabs the snapshot is almost empty. For instance:
```
exports[`test RSFilters Snapshot matchs 1`] = `
<div
  style={
    Object {
      "height": "100%",
    }
  } />
`;
```

**Comment by afc163** [comment]
You shouldn't mock rc-tabs

**Comment by aaronplanell** [comment]
Hello!

Hehehe. OK, but, which is the solution? 

What I mean, if i don't mock `rc-tabs` or `antd` the tests throw the error: 
```
TypeError: Cannot read property 'ownerDocument' of null
```

It seems that the `offset` method of the file `InkTabBarMixin.js` of the package `rc-tabs` receives an argument, but it doesn't control if this argument is `null`. If you correct it, then fails another method of `rc-tabs` for something similar.

I think check the library `rc-tabs` is not the point, what I want is mock it and check that the structure of my code matchs with the snapshot. I'm pretty sure that there are some solution or, at least, snapshots must work with `antd` in case you use them. What do you think about it?

Best regards!

**Comment by yesmeck** [comment]
@aaronplanell What's you test looks like?

**Comment by aaronplanell** [comment]
Hello @yesmeck & @afc163 ,

I create a new repository only with `create-react-app` and `ant design`: [https://github.com/aaronplanell/ant-design-issue_5428](https://github.com/aaronplanell/ant-design-issue_5428).

It's easy to reproduce the problem described in the issue, just:
```
$ git clone https://github.com/aaronplanell/ant-design-issue_5428
$ cd ant-design-issue_5428
$ npm install
$ npm test
```

In any case, in the `README.md` file you would see, step by step, how the project was created.

I repeate, I think the solution is mocking the `rc-tabs` library, but then the snapshot is almost empty. 

PS: I put in copy to @cpojer from Jest team.

**Comment by aaronplanell** [comment]
Eps! What about this? Have you reproduced the error?

**Comment by yesmeck** [comment]
@aaronplanell You need jsdom to make refs works.

**Comment by yesmeck** [comment]
Recommend using enzyme for React testing. :)

**Comment by yesmeck** [comment]
And enzyme-to-json for snapshot testing,

**Comment by aaronplanell** [comment]
Hello @yesmeck !!! 

Thanks for your answer. The enviroment is actually configured with `jsdom` in the `package.json`:
```
    "test": "react-scripts test --env=jsdom",
```

I use [Jest](https://github.com/facebook/jest) for many reasons:

1. It's the default test runner of [create-react-app](https://github.com/facebookincubator/create-react-app).
2. It's very very quick.
3. As React, it was developed by Facebook team, and this is guarantee for future releases.

I'm pretty sure that there is another solution. Anyway, I've got all this tests/snapshots created:
```
Test Suites: 65 passed, 65 total
Tests:       154 passed, 154 total
Snapshots:   29 passed, 29 total
```

Make the change to [enzyme](https://github.com/airbnb/enzyme) is absolutely discarded, hehehe. 

Any other solution?

Best regards and thanks for your answer!!!

**Comment by yesmeck** [comment]
@aaronplanell Here is a issue about using ref in react-test-renderer https://github.com/facebook/react/issues/7740, I have no time to dig in to this at this moment.

Enzyme is not a replacement of jest, it's a tool like react-test-utils, actually it's base on react-test-utils, you should try it, see antd's tests  https://github.com/ant-design/ant-design/blob/master/components/button/__tests__/index.test.js#L7-L12

**Comment by aaronplanell** [comment]
Solved in: https://github.com/facebook/react/issues/9244
