### ISSUE TITLE
Layout, Sider and really long content

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5429]
There is no any information about this at documentation for Layout, but how to be with long content (no such kind of demo).

I supposed that **Sider** would have height of view-port and attached to top, but in reality it has height 100%. Is it supposed behavior?! And if so, then how to fix it in recommended way?! :)

E.g.:
http://codepen.io/anon/pen/KWodpM?editors=001

**Comment by afc163** [comment]
@ddcat1115 We should provide a usage about fixed sider like GitLab.

**Comment by PiereDome** [comment]
I have created the fixed sidebar by setting the height to 100vh and then the content to 100vh as well with a overflow of scroll. Below is a codepen of that solution.

[http://codepen.io/PiereDome/pen/wJmgZo?editors=0010](http://codepen.io/PiereDome/pen/wJmgZo?editors=0010)

**Comment by benjycui** [comment]
@PiereDome you can PR to us, just add a new demo in [Layout](https://ant.design/components/layout/).

**Comment by PiereDome** [comment]
@benjycui I have installed locally, but I am developing on a windows machine and getting the following issue for every component: 
`ERROR in ./~/bisheng/tmp/components--layout-demo.index.js
Module not found: Error: Cannot resolve module 'C:UserpedersenDesktopant-design
ode_moduleishenglibloaderssource-loader' in C:\Users\bpedersen\Desktop\ant-design\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/components--layout-demo.index.js 7:20-200`

I looked into the bisheng module and it looks like it is referencing the tmp folder that has the following incorrect paths created.
`module.exports = {
    'basic': require('C:\Users\bpedersen\Desktop\ant-design\node_modules\bisheng\lib\loaders\source-loader!C:\\Users\\bpedersen\\Desktop\\ant-design\\components\\layout\\demo\\basic.md'),
    'custom-trigger': require('C:\Users\bpedersen\Desktop\ant-design\node_modules\bisheng\lib\loaders\source-loader!C:\\Users\\bpedersen\\Desktop\\ant-design\\components\\layout\\demo\\custom-trigger.md'),
   etc...
}`

I tried to manually fix them, but each npm start overwrites them, so we need to fix the issue in the bisheng library.

**Comment by benjycui** [comment]
@PiereDome trace: https://github.com/ant-design/ant-design/issues/5452

**Comment by benjycui** [comment]
@PiereDome `rm -rf node_modules && npm i`, then, you can start ant-design locally.
