### ISSUE TITLE
table组件 的 getCheckboxProps 无法'动态' 设置么?

### ISSUE THREAD

**Issue by shelwei** [ant-design/ant-design#543]
先上代码
```javascript
        let selected = this.state.selects[this.curSelect] ? this.state.selects[this.curSelect] : [];
        const pvlgSelection = {
            getCheckboxProps: (record) => {
                return {
                    defaultChecked: selected.indexOf(record.privilege) >= 0,
                    disabled: false
                };
            },
            onSelect: this.handleSelect,
            onSelectAll: this.handleSelectAll
        };
```

我的需求是, 我有多个item 如, A, B, C,  共用一个Table组件, Table数据是 1,2,3,4...n
不同的item的table 列选择不一样, 比如, 点击A是默认选中 2,3; 点击B默认选中 3,4 

代码如上, 但是实际上却没有选中

**Comment by afc163** [comment]
看不太懂。

**Comment by shelwei** [comment]
@afc163 或者这么说:
示例代码: http://120.24.237.80:8999/

**Comment by afc163** [comment]
试试升级到最新的 `0.10.0-beta27` 先？

**Comment by shelwei** [comment]
@afc163 升级到 0.10.0-beta27 可以😂, 多谢啦!

**Comment by Rpeanut** [comment]
@shelwinnn  我目前的需求和你的一样，就是A/B两个组件都在公用这个table，先打开那个组件的table，默认会选中，但是打开另外一个组件，前一个组件的默认选中状态会带到该组件的默认选中中

**Comment by Rpeanut** [comment]
@afc163 
rowSelection() {
    const { showType } = this.props
    const { defaultValue } = this.state
    const typeFlag = showType === 'ou'
    const type = typeFlag ? 'radio' : 'checkbox '
    return {
      type,
      onChange: (selectedRowKeys, selectedRows) => {
        if (typeFlag) {
          this.setState({
            ouSelectedRows: selectedRows,
            ouSelectedRowKeys: selectedRowKeys,
          })
        } else {
          this.setState({
            ouDataMapSelectedRows: selectedRows,
            ouDataMapSelectedRowKeys: selectedRowKeys,
          })
        }
      },
      getCheckboxProps: record => ({ defaultChecked:
                                      defaultValue.indexOf(record.id.toString()) >= 0 })
    }
  }``

--------------------------------------------------------------------------------
`  componentWillReceiveProps(nextProps) {
    const { showType } = this.props
    const { ouId, ouDataMapId } = nextProps
    const defaultValue = nextProps.showType === 'ou' ? [ouId] : ouDataMapId
    if (showType !== nextProps.showType) {
      this.setState({
        defaultValue
      })
    }
  }`
----------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/16949017/24179710/b9a044ba-0eeb-11e7-985c-ce3b0e789d97.png)
![image](https://cloud.githubusercontent.com/assets/16949017/24179723/ce57f4de-0eeb-11e7-8b82-2a79e1deafd5.png)
