### ISSUE TITLE
时间区间选择器

### ISSUE THREAD

**Issue by dingshuangxi888** [ant-design/ant-design#5430]
#### Environment(required)

- antd version: 最新
- OS and its version: macOS 最新
- Browser and its version: Chrome 最新

#### What did you do? Please provide steps to re-produce your problem.

时间区间组件，选择一个区间值后，下次再打开这个区间，时间选择器不能展示成我之前选择的值

比如下图，我选择的是值是2016-03-28 21:43:36到2019-04-26 21:43:36
但是点击重新选择的时候，选择范围右边变成了前面时间后的一个月

<img width="373" alt="2017-03-21 9 46 33" src="https://cloud.githubusercontent.com/assets/5010921/24150203/0eb222b4-0e80-11e7-9aff-be1e4aeb5241.png">
<img width="571" alt="2017-03-21 9 46 43" src="https://cloud.githubusercontent.com/assets/5010921/24150219/1ef9116e-0e80-11e7-8a5e-d3476130f45a.png">

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/5188 It is by design.

**Comment by dingshuangxi888** [comment]
这设计，我只能说放弃使用了

**Comment by afc163** [comment]
你希望展示的是 2019-04-26 这个区间么？

**Comment by afc163** [comment]
看了下，目前业界最流行的 RangePicker 都是这样的交互，例如 http://www.daterangepicker.com/#examples 

我们没有更好的方案前，暂时不会做多余的优化。

**Comment by dingshuangxi888** [comment]
业界是这样，不一定是对的吧，按照合理性来说就应该原来是怎么样，选择的时候就怎么样
