### ISSUE TITLE
add Demo for Layout with 2 menu

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5431]
You have such image as example for [navigation pattern](https://ant.design/docs/pattern/navigation):

![](https://os.alipayobjects.com/rmsportal/xXaCRVPIfmjDyIL.png)

I suggest to add the demo for it.

**Comment by afc163** [comment]
Same as https://ant.design/components/layout/#components-layout-demo-top

If you look for second navgition, here it is: http://1x.ant.design/docs/spec/layout#docs-spec-layout-demo-top

**Comment by plandem** [comment]
Yeah, but there is no example at 2.x branch. Although you have such screenshot at navigation pattern. I suggest to add demo for this case.
