### ISSUE TITLE
search-box 跟 getFieldDecorator 如何搭配？

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#5432]
- antd version:2.8.2

实际上从1.x版本就开始用这个组件

https://ant.design/components/select-cn/#components-select-demo-search-box

`<Select`
`    combobox`
`    value={this.state.value}`
`    placeholder={this.props.placeholder}`
`    notFoundContent=""`
`    style={this.props.style}`
`    defaultActiveFirstOption={false}`
`    showArrow={false}`
`    filterOption={false}`
`    onChange={this.handleChange}`
`>`
`    {options}`
`</Select>`

首先官方demo里，onChange改成onSearch更合适
`data.push({
     value: r[0],
     text: r[0],
});`

而且这里 显示值跟实际值都是取得 同一个值，如果把value换成 id之类的值，选中之后文本框里显示的是
value 而不是text，这个问题从1.x到现在一直存在，
之前还可以用一个state在onSelect事件里自己存储下，但是跟getFieldDecorator 搭配起来用而且是必填项的话，getFieldDecorator 只能存储 text 而不能存储value，这个感觉很棘手

**Comment by yesmeck** [comment]
> 如果把value换成 id之类的值，选中之后文本框里显示的是 value 而不是text

用 `labelInValue`。

**Comment by huyawei** [comment]
这法子还真是。。我自己在琢磨琢磨好的处理方法吧

**Comment by huyawei** [comment]
1.model
`datas.push({value: r.name,key: r.id,text: r.name,});`
2.ui
`const options = props.state.data.map(d => <Option key={d.value} v={d.key}>{d.text}</Option>);`
3.onSelect
`console.log(e.props.v)`
