### ISSUE TITLE
Why Carousel Panel indicates the point not to come out ？

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#5433]
setting dots is invalid

#### Environment(required)

- antd version:2.8.1
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.
http://codepen.io/benjycui/pen/KgPZrE?editors=0110

**Comment by SynChron1zed** [comment]
http://codepen.io/anon/pen/dvmgXW?editors=0110  this

**Comment by SynChron1zed** [comment]
http://codepen.io/anon/pen/aJYRmN?editors=0110 this

**Comment by SynChron1zed** [comment]
http://codepen.io/anon/pen/JWLmbR?editors=0110 this

**Comment by afc163** [comment]
http://codepen.io/anon/pen/qroJjr?editors=0110

**Comment by SynChron1zed** [comment]
@afc163  The stripes can be set to point？

**Comment by afc163** [comment]
You can try to customize css youself.
