### ISSUE TITLE
Upload 组件，上传失败的，能不能支持重传？

### ISSUE THREAD

**Issue by jsrider** [ant-design/ant-design#5436]
有没有一个 接口，我点重传按钮，就可以调用接口，让失败的文件重新上传？

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
Not yet, and no plan.

Just collect file in onChange, and the you can re-upload any time you want.

**Comment by jsrider** [comment]
Ok, thanks, then how to call re-upload in onChange? Re-uplaod function you are not exposed
