### ISSUE TITLE
upload file failed more than 4 Mins

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#5437]
#### Environment(required)

- antd version: 2.8.2
- OS and its version: win7 dvajs
- Browser and its version: chrome 56

#### What did you do? Please provide steps to re-produce your problem.

just use Dragger component
```javascript
const props = {
            name: 'file',
            multiple: false,
            showUploadList: true,
            accept:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel",
            action: '/nol/import/importDelivOrd.action',
            headers:header,
            onChange:this.handleChange
            
        };
       <Dragger {...props} >

```

#### What do you expected?
no matter how long ,get  response from server

#### What happen?

if  upload progress last more than 4 mins , front end will get error, and no response 

![tim 20170322175554](https://cloud.githubusercontent.com/assets/5886162/24192832/423c5b80-0f2b-11e7-8952-79cbff8b0d7e.png)

try customRequest ,use dvajs's default fetch lib , get error too
try customRequest ,use ajax ,get error too

**use postman upload file ,  no matter how long ,it works well**

upload a file and make a break point in server

**Comment by afc163** [comment]
More like a server-side problem.

**Comment by forever4313** [comment]
but use Postman ,  works well

**Comment by yesmeck** [comment]
Have you tried on other browsers?

**Comment by forever4313** [comment]
tried FF ,failed too
 is this a  dva bug?

**Comment by forever4313** [comment]
confirm : this is a dva's bug,tried other request ,also timeout 
I guess that  dva will retry a request if it last more than 2 mins,if the second request also time out(2 mins) ,it will be fail  2+2 = 4 mins
