### ISSUE TITLE
Table - Custom filtering and demo

### ISSUE THREAD

**Issue by eaglepigjim** [ant-design/ant-design#5439]
Would it make sense to simplify filtering on a column to just have a property:
filterable: true|false.

In this mode, it would create a filter based on the data in the table (based on the demo):
      filters: [
        { text: 'John Brown', value: 'John Brown' },
        { text: 'Jim Green', value: 'Jim Green' },
        { text: 'Joe Black', value: 'Joe Black' },
        { text: 'Jim Red', value: 'Jim Red' },
      ],
      onFilter: (value, record) => record.name === value,

Also the custom filtering demo only covers one column. Is there a way to mix the standard filtering with 1 or 2 custom columns? I have tried doing this myself unsuccessfully.

I think it would help greatly if the custom filtering demo also had filters on the Age and Address columns, with one of those being a regular filter.

**Comment by benjycui** [comment]
markdown

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by afc163** [comment]
Check this demo: https://ant.design/components/table/#components-table-demo-head

It contains two columns filters

**Comment by afc163** [comment]
Try like the above demo.
