### ISSUE TITLE
Icons URLs

### ISSUE THREAD

**Issue by FacundoGFlores** [ant-design/ant-design#5440]
Is it possible to change Icons' URL? Currently they are:

`@icon-url               : "https://at.alicdn.com/t/font_k9s3hj21flqmpldi";`

but they take too much to load. 

I've tested downloading the icons and loading them locally, and the app works perfectly!  But the solution is not very good because I'm hardcoding the `url` in the `node_modules`. 

So, would it be a good idea to overwrite the `url` through webpack?

**Comment by yesmeck** [comment]
See https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont#local-hosted-iconfont
