### ISSUE TITLE
Alert组件info类型的颜色与primary-color关联是否合理？

### ISSUE THREAD

**Issue by pasturn** [ant-design/ant-design#5442]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: Win 10
- Browser and its version: Chrome 56

#### What did you do? Please provide steps to re-produce your problem.

我修改了primary-color，同时引入了Alert组件，类型是info

#### What do you expected?

Alert组件info类型颜色与官网demo一致，颜色独立于primary-color

#### What happen?

Alert组件info颜色与我修改的primary-color一致。

**Comment by afc163** [comment]
Add a `@info-color` in all info type component: Alert, message, notification, Modal.info.
