### ISSUE TITLE
Radio控件与form表单、Modal控件结合使用的时候更改radio选中值无效

### ISSUE THREAD

**Issue by encorehe** [ant-design/ant-design#5448]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What do you expected?
我这边的一个需求是：首先RadioGroup中，默认第一个radio是选中状态，然后选中第二个radio弹出一个Modal层，点Modal层的取消时，radio默认选中到第一个 此时 radio却还是选中的是第二个radio 不是第一个，事实是初始值已经被更改过来了。

`<FormItem label='使用范围' hasFeedback {...formItemLayout}>
            {getFieldDecorator('useLimitType', {
              initialValue: item.useLimitType != undefined?item.useLimitType:tempLimitNum ,
              rules: [
                {
                  required: true
                }
              ]
            })(<RadioGroup onChange = { onLimitChange} >
              <Radio value={0}>全商品通用</Radio>
              <Radio value={1}>限类别使用</Radio>
              <Radio value={2}>限课程使用</Radio>
            </RadioGroup>)}
          </FormItem>`
` const onLimitChange = (e) => {
      changeTLimit(e.target.value);
    };`

`  changeTLimit: (v) => {
            if (v === 1) {
                dispatch({
                    type: 'couponRuleManger/showClassifiedModal',
                    payload: {
                        tempLimitNum: v
                    }
                })
            }`

            if (v === 0) {
                dispatch({
                    type: 'couponRuleManger/renData',
                    payload: {
                        tempLimitNum: v
                    }
                })
            }

        }`

**Comment by afc163** [comment]
@ant-design-bot markdown

**Comment by afc163** [comment]
Note the `initialValue` only works in first render, you should use `mapPropsToFields` to sync your data from global state.

https://ant.design/components/form-cn/#components-form-demo-global-state
