### ISSUE TITLE
 @ D:\react\kongjian\node_modules\antd\lib\checkbox\style\index.css (line 128, column 7)

### ISSUE THREAD

**Issue by aiyuekuang** [ant-design/ant-design#5449]
为什么我的有多个地方有css的报错
@media \0screen {
  .ant-checkbox-checked .ant-checkbox-inner:before,
  .ant-checkbox-checked .ant-checkbox-inner:after {
    font-family: 'anticon';
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    content: "\e632";
    font-weight: bold;
    font-size: 8px;
    border: 0;
    color: #fff;
    left: 2px;
    top: 3px;
    position: absolute;
  }
}
这段就是这段

**Comment by afc163** [comment]
官网工具是没问题的。自建脚手架的话，建议参考 atool-build 的配置：https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js
