### ISSUE TITLE
项目不能正常启动

### ISSUE THREAD

**Issue by waitinghope** [ant-design/ant-design#5452]
#### Environment(required)

- antd version:
2.8.2
- OS and its version:
win7
- Browser and its version:
chrome latest

npm 3.10.3
node v6.6.0
#### What did you do? Please provide steps to re-produce your problem.

$ git clone git@github.com:ant-design/ant-design.git
$ npm install

![image](https://cloud.githubusercontent.com/assets/3109596/24238441/3a6d106a-0fe5-11e7-9eff-cf9bf3237fca.png)

$npm install --no-optional 

$ npm start
![image](https://cloud.githubusercontent.com/assets/3109596/24238488/5e4f016e-0fe5-11e7-97ca-90aa37d9977f.png)

#### What do you expected?

项目正常启动

#### What happen?

npm start 报错。

**Comment by bang88** [comment]
Not support windows development this moment. 😢

**Comment by waitinghope** [comment]
Wow.....ok.

**Comment by benjycui** [comment]
It should work after this PR https://github.com/benjycui/bisheng/pull/62

Could you try to find the problem and try to fix it?

We have no Windows machine..

**Comment by bang88** [comment]
I will try it later. 😄

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

Thanks to @bang88

**Comment by waitinghope** [comment]
![image](https://cloud.githubusercontent.com/assets/3109596/24387565/754af9d8-13a8-11e7-8d1a-6c208a450f04.png)
Thank you very much.
