### ISSUE TITLE
Enable Arrows for Carousel

### ISSUE THREAD

**Issue by mewdew** [ant-design/ant-design#5458]
#### Environment(required)

- antd version: 2.8.2
- OS and its version: Ubuntu 16.04
- Browser and its version: Chrome 57.0.2987.110

#### What did you do? Please provide steps to re-produce your problem.

I'm using ant-carousel.

#### What do you expected?

I expected the arrow navigation feature to be available. However, it has been set to false.

#### What happen?

No flexibility for using arrow feature as it has been explicitly set as false.

#### Re-producible online demo

Request: Set the prop as bool to keep option open for usage.

``` javascript

import React, { PropTypes } from 'react';

export default class Carousel extends React.Component<CarouselProps, any> {
  static defaultProps = {
    dots: true,
    arrows: PropTypes.bool,
    prefixCls: 'ant-carousel',
    draggable: false,
  };

```

**Comment by afc163** [comment]
You can set it to `true` and provide arrow styles by youself, it will be passed to react-slick: https://github.com/akiran/react-slick
