### ISSUE TITLE
Modal footer divider persists when buttons removed

### ISSUE THREAD

**Issue by llhupp** [ant-design/ant-design#5462]
The Modal component shows the bottom divider when the `footer` prop is set to `null`.

#### Environment(required)

- antd version 2.8.0:
- macOS Sierra (version 10.12.3):
- Chrome version 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

1) Render `Modal` component with the `visible` prop `true` and the `footer` prop as some non-null element.
2) Update the `footer` prop to `null`
3) BUG bottom divider continues to show even though footer content is null.

#### What do you expected?
I would expect the footer section and divider to be hidden as it is in this image.
![footer_hidden](http://i.imgur.com/G1V0O2f.png)

#### What happen?
It is not hidden.
![divider_visible](http://i.imgur.com/qxZY3ml.png)

**Comment by NE-SmallTown** [comment]
Check [this](https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L173) you will find that we just add your custom component to the footer container.

So if you want to implement your goal,you should make some change in the src code such as add a property in footer i.e.:

```
if(props.footer) {
   if(props.footer.isCustom) {
       footer = {props.footer};
   } else {
       footer = (
        <div className={`${prefixCls}-footer`} ref="footer">
          {props.footer}
        </div>
      );
   }
)
```

Of course you can do this via judging `props.footer` is `null`,at now we use `if(props.footer)`,so `null` and `undefined` will be treated as the same.

Welecome pr~

**Comment by benjycui** [comment]
It seems that we cannot set `Modal[footer=null]` to hide footer now.

But we can update [this line of code](https://github.com/ant-design/ant-design/blob/4a9ae162c67284d89379d0315d6ac85dec5ecaa7/components/modal/Modal.tsx#L164) to achieve your target:

```jsx
footer={footer === undefined ? defaultFooter : footer}
```

**Comment by afc163** [comment]
You can use `footer={[]}` now.

**Comment by benjycui** [comment]
`footer=[]` will not work as @llhupp 's expectation:

![image](https://cloud.githubusercontent.com/assets/3580607/24279637/0ee51b58-1086-11e7-900c-9bc30758a4ba.png)

**Comment by reid3290** [comment]
Is this actually a bug? I have used antd for a while in my project, but i never dive into the codes. Is this a good one for beginner to start with? Thx.

**Comment by afc163** [comment]
@reid3290 Yes, I think it is a pretty clear one and solution of @benjycui will works well. PR is always welcome.

**Comment by NE-SmallTown** [comment]
IMO,maybe we can provide more  fine-grained api [like I say avove](https://github.com/ant-design/ant-design/issues/5462#issuecomment-288912515).Because there must be some people will consider that keep the bottom line is better.So base on this,if you just want to achieve your target,set border be `none` is better.And if you want to pr,change the `footer` api to a `object` such as `footer {object} {element : node,showBorder: boolean......}` is better.

**Comment by reid3290** [comment]
Fair point. But IMO, the top border of the footer is kind of a divider to seperate it from the content. If you don't need the footer, then you don't need the divider. I think this is more common. If some people really want the divider but not the footer, it makes more sense to add bottom border to the content div. Changing the footer api would make it unnecessarily tedious.

**Comment by NE-SmallTown** [comment]
Yeah~That's up to you,just hope maybe it will inspired you.For me both of them are ok.

**Comment by llhupp** [comment]
Thanks, everyone! The library looks great and I look forward to trying out the fix. As a side note, we found a workaround in 2.8.0 where we remount the modal when we change the footer.
