### ISSUE TITLE
[question] customize ant.design or use rc-*

### ISSUE THREAD

**Issue by kud** [ant-design/ant-design#5464]
Hello,

For a project, I would like to use ant.design because there's lots of good components already done.
However, we have our own design and I can't use the design of ant.design for that. Even if I customize it via https://ant.design/docs/react/customize-theme, it's not enough. So my question is:

Is it better to:
- customize ant.design by overriding the css with my own classes/css?
- use rc-* components as it seems to be the base of ant.design?

Thank you.

**Comment by benjycui** [comment]
I don't know. Because I don't know how many differences between your own design and Ant Design

You must make your own decision.
