### ISSUE TITLE
建议：能把 react-component 的文档链接放到antd 相应组件的文档的下面吗

### ISSUE THREAD

**Issue by xwork-io** [ant-design/ant-design#5465]
这样查一下 antd 没有标注的属性就方便了。

**Comment by NE-SmallTown** [comment]
You should **not** use the api which is not mentioned in the doc.If you want to overwrite your own libraries based on antd or react-component.Just clone and look up at your local.

**Comment by benjycui** [comment]
Actually, antd's components' API are not the same as rc-component's
