### ISSUE TITLE
Select组件中的Option的value类型

### ISSUE THREAD

**Issue by acmeid** [ant-design/ant-design#5470]
#### Environment(required)

- antd version: 2.8.1
- OS and its version: mac 10.11.6
- Browser and its version: chrome 56.0.2924.87 (64-bit)

我在使用Select组件的时候，发现Option的value取值类型是String，如果是其他类型就会报错：

> Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `Option`, expected `string`.

通常Option的value值的类型是Number，我希望不会出现这个报错信息

**Comment by yesmeck** [comment]
Duplicate of #2857

**Comment by acmeid** [comment]
谢谢
