### ISSUE TITLE
Table 增加Scroll属性后暂无数据展示问题

### ISSUE THREAD

**Issue by lycandjava** [ant-design/ant-design#5474]
#### Environment(required)

- antd version:**1.5.0**
- OS and its version:**window**
- Browser and its version:**chrome 49+**
 
#### 表格使用 scroll属性后，查询返回暂无数据时显示异常
 在增加表格查询条件时，尤其是select条件查询时，出现这种问题的概率几乎为100%，但是有一些特定的浏览器是没有问题 的，如果去掉了scroll属性就都OK了，请大家帮忙分析下具体如何处理，谢谢

```
   <Table scroll={{y:adaptHeight}} loading={this.state.loading} rowClassName={this.changeRowClassName} useFixedHeader columns={columns}
                                       dataSource={this.state.data} pagination={this.state.pagination}
                                       onChange={this.handleTableChange.bind(this)} rowKey={record => record.id}/>
```
#### 下面是出问题的图片展示：
![问题图片](https://thumbnail0.baidupcs.com/thumbnail/72a0543f4fa966121be2c9a99e2b33db?fid=2454535033-250528-123108735342674&time=1490328000&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-A9T7G4FvO14LFP2X6xY9FDad5Dw%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=1914010618476341628&dp-callid=0&size=c710_u400&quality=100)

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
And I suggest you use antd latest version. We don't maintain antd 1.x anymore.

**Comment by lycandjava** [comment]
问题已经解决了，采用遮挡的方式，因为真实的dom已经进行卸载了，谢谢@afc163
.ant-table-placeholder{
  border: none;
  height: 100%;/*这里面原始高度为100px*/
  line-height: 100%;  /*这里面原始高度为100px*/
  text-align: center;
  font-size: 12px;
  color: #999;
  border-bottom: 1px solid #e9e9e9;
  top:35px;/*这里根据实际情况自己调整下*/
  padding-top:50px;/*这里根据实际情况自己调整下*/
  left: 0;
  width: 100%;
  empty-cells: show;    background: #fff;
}
