### ISSUE TITLE
ERROR in ./~/antd/lib/upload/Upload.js

### ISSUE THREAD

**Issue by zedwang** [ant-design/ant-design#5475]
打包的时候报错：Module not found: Error: Cannot resolve 'file' or 'directory' ./UploadList ，我看了下Upload.js里有UploadList的依赖，但是lib包里却没有UploadList.js这个文件

**Comment by yesmeck** [comment]
antd 版本？ 如何安装的？操作系统？

**Comment by zedwang** [comment]
我是用yarn install antd --save 安装的，版本是2.8.2，win10的环境

**Comment by afc163** [comment]
是有的：https://unpkg.com/antd@2.8.2/lib/upload/

`cat node_modules/antd/package.json | grep version`

**Comment by zedwang** [comment]
可能是我的网络环境不好，我刚重新单独装了一次有了。谢谢你们的答复！
