### ISSUE TITLE
IE  antd 报 startWith方法 不支持。

### ISSUE THREAD

**Issue by Aaronphy** [ant-design/ant-design#5476]
#### Environment(required)

- antd version:2.1.0
- OS and its version: mac os
- Browser and its version:id

#### What did you do? Please provide steps to re-produce your problem.

page break down
#### What do you expected?
page works well

#### What happen?
antd => string.startWidth does`t polyfill in IE

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/search?q=startsWith&type=Issues&utf8=%E2%9C%93

https://github.com/ant-design/ant-design/issues/3400
