### ISSUE TITLE
DatePicker initialValue 设置的格式是什么

### ISSUE THREAD

**Issue by 422809585mls** [ant-design/ant-design#5481]
Unexpected token (256:67)

           </FormItem>
        <FormItem {...formItemLayout} label="到期时间">
256          {getFieldDecorator('startTime',{ initialValue:{moment('2015-01-01', 'YYYY-MM-DD')}  })(                                                                                                                        ^                                                          
              <DatePicker style={{width:284}} format={ 'YYYY/MM/DD'} disabled={editable}/>)}
            </FormItem>
        </div>): ''}

- antd version:
- OS and its version:
- Browser and its version:

**Comment by 422809585mls** [comment]
<FormItem {...formItemLayout} label="到期时间">
                 {getFieldDecorator('endTime' ,{initialValue: {moment('2015-01-01', 'YYYY-MM-DD')}})(
                    <DatePicker   format={ 'YYYY/MM/DD'} disabled={editable}/>)}
            </FormItem>   
这样总报错

**Comment by afc163** [comment]
Check you antd version, if you are using antd@1.x, please read http://1x.ant.design/

**Comment by 422809585mls** [comment]
我用的2.0

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
> 这样总报错

And what is the error?

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by afc163** [comment]
It works in http://ant.design/components/date-picker , you are better to provide a re-producible demo or we can't resolve your problem.
