### ISSUE TITLE
DatePicker debug

### ISSUE THREAD

**Issue by erdun** [ant-design/ant-design#5482]
when i pick the time 14:00, it will over 8 hours than the time you pick.

[exmaple](http://codepen.io/erdun/pen/MpVVmm/?editors=0010)
![image](https://cloud.githubusercontent.com/assets/16429864/24283965/a80b0672-10a3-11e7-8e4d-d82de59d2ecd.png)
![image](https://cloud.githubusercontent.com/assets/16429864/24283970/b17685ec-10a3-11e7-9332-2589a257cdff.png)

save the date time in database and read it, it will show 22:00

**Comment by afc163** [comment]
<img width="122" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24286358/db1ef184-10af-11e7-9b15-3c38f85cd2e9.png">

**Comment by afc163** [comment]
Did I miss something? You demo just works fine.

<img width="939" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24293926/132bb1c4-10cf-11e7-92b3-67aa45ca9721.png">

**Comment by yesmeck** [comment]
> save the date time in database and read it, it will show 22:00

Sound like your server didn't handles date correctly,

**Comment by erdun** [comment]
it's proxy. when I closed proxy. it's all right.
thx
