### ISSUE TITLE
Table组件开启pagination的sizeChanger出现bug

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#5486]

**Comment by yesmeck** [comment]
请按模板来提交 issue。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
close for no re-producible demo
