### ISSUE TITLE
Can't add onKeyDown event listener with the AutoComplete Customize Input Component

### ISSUE THREAD

**Issue by fiture** [ant-design/ant-design#5487]
#### Environment(required)

- antd version: 2.8.1

#### What did you do? Please provide steps to re-produce your problem.

```js
function onKeyDown(){
    console.log('E.. not work.');
}

<AutoComplete
            dataSource={['test']}
            style={{ width: 200, height: 50 }}
            optionLabelProp="text"
          >
            <input  onKeyDown={onKeyDown}/>
          </AutoComplete>
```

#### What do you expected?

So, any way to add a custom input onKeyDown or onChange event callback with this AutoComplete component?

By the way，I found this: https://github.com/react-component/select/blob/master/src/Select.jsx#L470

It may be the point.

**Comment by yesmeck** [comment]
Try reinstall node_modules.

**Comment by fiture** [comment]
@yesmeck thanks a lot to work with this issue.

It may be able to work independently `select` component. 

But in the `AutoComplete`  component：
https://github.com/ant-design/ant-design/blob/master/components/auto-complete/InputElement.tsx#L14

```js
    return React.cloneElement(this.props.children, {
      ...this.props,
      ref: ele => this.ele = (ele as HTMLInputElement),
    }, null);
```

The `onKeyDown` and other props lost...  as a result AutoComplete Customize Input Component `onKeyDown`  still not working..

**Comment by yesmeck** [comment]
@RaoHai
