### ISSUE TITLE
feat: add `innerRef`

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5489]

**Comment by benjycui** [comment]
Don't use ref with antd's component, it's unstable.

**Comment by benjycui** [comment]
`innerRef` may have conflict with styled-component, we can use other name, such as: https://github.com/react-component/form/pull/87

**Comment by benjycui** [comment]
See: https://reacttraining.com/react-router/web/api/withRouter/wrappedComponentRef-func

We even use the same prop name....

**Comment by tkrotoff** [comment]
FYI
- material-ui has `inputRef` on all its components, see https://github.com/callemall/material-ui/blob/v1.0.0-beta.12/src/Input/Input.js#L255 and https://github.com/callemall/material-ui/search?utf8=%E2%9C%93&q=inputRef&type=
- reactstrap defines `getRef` (will be renamed `innerRef` in the future?), see https://github.com/reactstrap/reactstrap/issues/583
- React-Bootstrap defines `inputRef`, see https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.3/src/Checkbox.js#L26

**Comment by NugzarGaguliya** [comment]
What about inerRef? Is it in progress?

**Comment by yesmeck** [comment]
Closing since it's inactive.

**Comment by yesmeck** [comment]
https://github.com/reactjs/rfcs/pull/30

**Comment by valerii-cognite** [comment]
What is the status for the issue?

**Comment by Tymek** [comment]
@yesmeck could you reopen it? I'd like to contribute if it's possible to implement this.

**Comment by yesmeck** [comment]
This issue doesn't have a clear goal, I see you've proposed a PR, we can discuss on the PR.
