### ISSUE TITLE
Local development doesn't work.

### ISSUE THREAD

**Issue by reid3290** [ant-design/ant-design#5491]
#### Environment(required)

- node v7.3.0
- npm 4.0.3
- window10

#### What did you do? Please provide steps to re-produce your problem.

1. fork
2. git clone
3. npm install
4. npm start

#### What do you expected?

It works fine as the contributing guide says.

#### What happen?
![image](https://cloud.githubusercontent.com/assets/9301137/24289942/267d5784-10be-11e7-80f9-dab90f48f13e.png)
A bunch of "module not found" error.

**Comment by bang88** [comment]
duplicated #5452
