### ISSUE TITLE
Table组件开启pagination的sizeChanger BUG

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#5492]
Table组件开启pagination的sizeChanger，再 40/页 =》 30/页时 ，大 =》 小 出现闪屏效果

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by yesmeck** [comment]
请按模板问题来提 issue.

**Comment by NE-SmallTown** [comment]
First,you should just edit in your previous issue,file another issue is unnecessary and confused.

Second,please don't just copy your previous unqualified words, and you should learn how to ask question.
