### ISSUE TITLE
Is it possible to disable the  nested fields format syntax?

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#5497]
ref: [this.props.form.getFieldDecorator(id, options)](https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options))

this syntax is very useful, but when I must use string which contains `.` as field id, the very syntax breaks things. Add something like `options.disableNestedField` will be convenient.

**Comment by benjycui** [comment]
No, this will make rc-form more complicated.

I am going to simplify rc-form, and may introduce some breaking changes(Maybe in antd@3.0)

So, I don't want rc-form to be more complicated.

Just use `-` in your id, and you can replace it to `.` before submit.
