### ISSUE TITLE
Suggest to change the color of the placeholder to gray

### ISSUE THREAD

**Issue by motorguo** [ant-design/ant-design#5500]
#### Environment(required)

```
"antd": "^2.8.1",
```

#### What did you do? Please provide steps to re-produce your problem.
```
import { InputNumber } from 'antd';
```

#### What do you expected?
![image](https://cloud.githubusercontent.com/assets/16831715/24321366/54bdb360-1185-11e7-9d9f-7bea595f807f.png)

#### What happen?
![image](https://cloud.githubusercontent.com/assets/16831715/24321290/aef5917e-1183-11e7-835d-e7fc99f298f5.png)

#### Re-producible online demo

http://codepen.io/ThomasOzil/pen/oZMyWg?editors=0110

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
I re-produce it! http://codepen.io/anon/pen/jBpgyq?editors=0010
