### ISSUE TITLE
Input ‘onKeyDown’ incorrect to key down event

### ISSUE THREAD

**Issue by xiruibing** [ant-design/ant-design#5505]
#### Environment(required)

- antd version:2.8.3
- OS and its version:win10
- Browser and its version:Chrome v56

#### What did you do? Please provide steps to re-produce your problem.

I'm trying to call keydown event in input component, but it‘s incorrectly. Finally, i use onKeyPress, it's ok. Use keypress event not solve the question.   how can i do?  help, help, help.

```jsx
  handleKeyDown(event) {
    console.log(event);
  }

  render() {
    return (
      <Input onKeyDown={this.handleKeyDown} />
    );
  }
```

#### What do you expected?

onKeyDown,onKeyUp,onKeyPress correct.

**Comment by benjycui** [comment]
Customized [`onKeyDown` will be overrided](https://github.com/ant-design/ant-design/blob/c004001a5f11eb7c447e90076f6620c5896caa3e/components/input/Input.tsx#L265), but others may work.

**Comment by benjycui** [comment]
Oops, [`onKeyDown` should work](https://github.com/ant-design/ant-design/blob/c004001a5f11eb7c447e90076f6620c5896caa3e/components/input/Input.tsx#L124)...

**Comment by benjycui** [comment]
I tried `onKeyDown` locally, and it works fine.

**Comment by afc163** [comment]
> Hellp
@yesmeck

**Comment by xiruibing** [comment]
@ant-design-bot

**Comment by benjycui** [comment]
It works fine:

![image](https://cloud.githubusercontent.com/assets/3580607/24388720/2fcba0d6-13af-11e7-899a-ea8f61120e37.png)

**Comment by afc163** [comment]
@xiruibing

**Comment by afc163** [comment]
close for no response
