### ISSUE TITLE
动态添加多个的timepicker时，删除上一个timepicker时其选择的时间会被强加到下面一个timepicker

### ISSUE THREAD

**Issue by wonyun** [ant-design/ant-design#5507]
#### Environment(required)

- antd version: 2.5.2
- OS and its version: mac  OS X EL Capitan
- Browser and its version:   57.0.2987.98 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
如题，在动态添加的多个timepicker，在删除某个timepicker时，其选择的时间会保留到其下面的一个timepicker，而不是随着timepicker的删除而被丢弃掉。

#### What do you expected?
希望随着timepicker的删除，其选择的时间值也丢弃的而不是保留。

#### What happen?
删除的timepicker，其选中的时间值被保留到其后面的timepicker

#### Re-producible online demo
[请猛戳demo](http://codepen.io/fetest/pen/jBaaRQ?editors=1010)

**Comment by yesmeck** [comment]
用 `index` 做 `key`  的缘故，如果你的数据是变化的，不应该用数组的 `index` 做 `key`。

**Comment by wonyun** [comment]
@yesmeck 实际项目中，我用字符串和index混合做为key也不行，难道timepicker不能用index作为key的组成部分么？

**Comment by yesmeck** [comment]
跟 `antd` 没关系，你用有变化的数据的 `index` 做 `key` 就是会有这种问题的。参考：https://facebook.github.io/react/docs/reconciliation.html#recursing-on-children

**Comment by wonyun** [comment]
@yesmeck 不太对啊，我重新用Math.random().toString().substr(2)来生成每个timepicker都不行，遇到动态添加Timepicker的这个问题，有什么好的解法么，求教！

**Comment by benjycui** [comment]
`key`要稳定且唯一，建议再认真学习 React

**Comment by wonyun** [comment]
@benjycui 谢谢指导，这块确实需要深入研究一下
