### ISSUE TITLE
official demo InputNumber page can not connect on Safari 

### ISSUE THREAD

**Issue by dotaeye** [ant-design/ant-design#5510]
#### Environment(required)

- antd version: 2.8.3
- OS and its version: MAC
- Browser and its version: Safari

#### What did you do? Please provide steps to re-produce your problem.

when I connect to the https://ant.design/components/input-number-cn/, the page no response.

**Comment by afc163** [comment]
Fixed in rc-input-number@3.3.4, try reinstall node_modules.

**Comment by afc163** [comment]
Thx for reporting! 😄
