### ISSUE TITLE
The placeholder text color of the InputNumber component is not set.

### ISSUE THREAD

**Issue by BiosSun** [ant-design/ant-design#5516]
#### Environment

- antd version: 2.8.1
- OS and its version: macOS 10.12.2
- Browser and its version: Google Chrome Canary 59.0.3047.0（64-bit)

#### What do you expected?

希望 InputNumber 组件能够支持 placeholder 属性，为其提供和 Input 组件所一致的色值样式，并在文档中明确阐述该属性。

#### What happen?

![image](https://cloud.githubusercontent.com/assets/2755933/24359953/6df88ea4-1338-11e7-9d43-d4e1a62de803.png)

#### Re-producible online demo

示例: http://codepen.io/anon/pen/oZPZBy?editors=0010

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/5500
