### ISSUE TITLE
Tree 组件标签不能写在同一行

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design#5519]
#### Environment(required)

- antd version: 2.8.3
- OS and its version: win10
- Browser and its version: chrome 56

#### What did you do? Please provide steps to re-produce your problem.

直接引入 Tree 组件使用，将Tree标签写在同一行

#### What do you expected?

正常展示树组件

#### What happen?

JS报错  Uncaught TypeError: Cannot read property 'children' of undefined

#### Re-producible online demo

[http://codepen.io/anon/pen/GWXXeV?editors=001](http://codepen.io/anon/pen/GWXXeV?editors=001)

只要把 Tree 标签分行就可以

**Comment by yesmeck** [comment]
写同一行就会把中间的空格也算进去，现在 `Tree` 的子元素只能是 `TreeNode`。
