### ISSUE TITLE
the form couldnot get the treeselect's or transfer value,how can i submit treeselect value through form

### ISSUE THREAD

**Issue by zyx4986** [ant-design/ant-design#5520]
i submit treeselect's value like this 
`\<Form>
..other form item..
     \<FormItem>
         {getFiledDecorator('orgid')  ...
         (\<TreeSelect>
             \</TreeSelect>)
         }
....
    \</FormItem>
</Form>`
i want to submit the treeselect's value like this 
   validateFields(errors,values){
       values['orgid']
    }
but it return undefind, transfer get the same result

**Comment by afc163** [comment]
TreeSelect is working: http://codepen.io/anon/pen/bqxQqK?editors=0010

**Comment by afc163** [comment]
And set `valuePropName` to `targetKeys` for Transfer in getFiledDecorator.

**Comment by zyx4986** [comment]
明白，直接用treeselect标签ok，我用了dva框架，在components把treeselect封装成了另外一个名字orgtreeselect，然后使用orgtreeselect标签就获取不了值，这个可以怎么处理呢？ @afc163

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
