### ISSUE TITLE
Tricks about Testing with Jest & Enzyme

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5522]
We had used Jest & Enzyme for testing for some time, and found that it's not perfect:

1. `jsdom` doesn't support layout https://github.com/tmpvar/jsdom/issues/1322 , so we need to mock some value and function while testing.
1. There is not default browser behavior while testing, e.g. if we trigger `onKeyDown` and `onKeyUp`, `onKeyPress` will not be trigger automatically.
1. It seems that simulated event will not propagate(I am not sure).

But Jest & Enzyme is the most universal test solution in React community and we cannot find better solution, so we will keep using Jest & Enzyme.

And we need to find(actually, we had found some) tricks to solve problems while using Jest & Enzyme, and document them. So that other antd members and our community can benefit from this documentation.

e.g.

1. Every component which will be rendered to `document.body` by default should support `getContainer` `getPopupContainer`, so that we can render them to specific node while testing.(Tooltip, Popover, Popconfirm, Dropdown, Modal...)
1. Mock `getBoundingClientRect`

```jsx
div.getBoundingClientRect = () => ({
    width,
    height,
    top: 0,
    left: 0,
    right: width,
    bottom: height,
});
```

...

And we need to find a place to put this documentation, wiki or ant.design

**Comment by yesmeck** [comment]
We can mock `rc-trigger`([example](https://github.com/react-component/select/blob/master/tests/__mocks__/rc-trigger.js)), then `Popup` component will render to the same root with parent component.

**Comment by swillis12** [comment]
@afc163 @benjycui did you document these tricks somewhere?

**Comment by MuYunyun** [comment]
is there a better way instead of mocking getBoundingClientRect? If there are plenty of places to use getBoundingClientRect in one component, and mock getBoundingClientRect can be a bit hard.

**Comment by DercilioFontes** [comment]
I was googling to solve an issue of testing in CI failing with "Exceeded timeout of 5000 ms for a test." and I realized that one test was affecting another, changing the state of notifications or modals. Well, it seems to me. They work fine in my Mac. It is fine inn CI when I run it with only one test checking the notification text. But with a second one, it times out. 

I even changed the code to use the `contextHolder` as follows, but it didn't work. The fist test passes, but the second one, doesn't.

```typescript
const MyComponent = () => {
...
const [api, contextHolder] = notification.useNotification();

...

return (
  <>
    {contextHolder}
    <Mycomponent
...
```
And test to:

```typescript
test('submit shows "Site updated successfully"', async () => {
  ...
  render(
    <ConfigProvider>
      <UpsertAdminSiteComponent />
    </ConfigProvider>
  );
  
  ...
  
  expect(await screen.findByText('Something updated successfully')).toBeVisible();
```

Any tricks to solve this?

How should I use `getContainer`? Pass it to a parent component?
