### ISSUE TITLE
IE9 TreeSelect arrow-icon hidden

### ISSUE THREAD

**Issue by fangxingli** [ant-design/ant-design#5526]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: Win7
- Browser and its version: IE9

#### What did you do? Please provide steps to re-produce your problem.

使用Antd 2.7.2版本，用webpack打包，在IE9环境下，TreeSelect组建父节点箭头图标失效

#### What do you expected?

TreeSelect 父节点箭头图标在没有展开的情况下可见

#### What happen?

TreeSelect 父节点箭头图标在没有展开的情况下隐藏了，展开后可见向下的图标

**Comment by benjycui** [comment]
Try `2.8.3`

And if you still meet this issue, please provide a re-producible demo.

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by fangxingli** [comment]
@benjycui When update 2.8.3, i meet this issue again. But i do not known how to provide a re-producible demo with codepen. So here are issue image hrefs:
http://ohst187d7.bkt.clouddn.com/001.png
http://ohst187d7.bkt.clouddn.com/002.png

**Comment by benjycui** [comment]
If you cannot provide a re-producible without your business code, it means that it not an issue of antd, but an issue in your own code.

**Comment by benjycui** [comment]
Actually, I cannot see this issue in ant.design

**Comment by fangxingli** [comment]
Maybe you are right, this issue will be closed if i could not provide more progress information tomorrow

**Comment by fangxingli** [comment]
The ant-design home page seems also not compatible with IE9, isn't it?

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/24442554/3fe0b1f4-1491-11e7-9c70-161134201142.png)

**Comment by fangxingli** [comment]
Ok, I got the codepen works, http://codepen.io/anon/pen/LWXOwR?editors=001, is that correct? In IE9, the webpage could not even be opened.

**Comment by benjycui** [comment]
Or try to provide your demo with gh-pages...

**Comment by afc163** [comment]
close for no response
