### ISSUE TITLE
Anchor component does not work with Typescript

### ISSUE THREAD

**Issue by mitchelldemler** [ant-design/ant-design#5527]
I am pretty novice with Typescript and I've had a go at fixing the source code for the Anchor component, but I have wasted a few days now trying to get this to work.

Does anyone have a working example of how to get this working? Or is there someone that can make a PR to get it fixed. I would love to help, but my skills are lacking.

Current implementation:

```
return (
  <div>
    <Anchor>
      <Link href="#Anchor1">Anchor 1</Link>
    </Anchor>
    <div>
      <h1 id="Anchor1>Anchor 1</h1>
      <p>Content</p>
    </div>
  </div>
)
```

(So far I have made bounds, offsetTop and onClick optional props in AnchorLinkProps)

**Comment by afc163** [comment]
Could you describe what problem you encounter exactly?

**Comment by mitchelldemler** [comment]
I get an error TypeError: Cannot read property 'href' of undefined. Which is from AnchorLink._this.renderAnchorLink.

I have tried to meddle with this method, but I'm not getting very far. My apologies if this is a usage error.

**Comment by mitchelldemler** [comment]
Got it working, I didn't realise that the content of the AnchorLink should be set with the title prop, instead of text inside. See above PR for fixing the optional/required props.

For future reference, **wrong:**

```
<Link href="#Anchor1">wrong</Link>
```

**Correct:**
```
return (
  <div>
    <Anchor>
      <Link href="#Anchor1" title="Anchor 1" />
    </Anchor>
    <div>
      <h1 id="Anchor1>Anchor 1</h1>
      <p>Content</p>
    </div>
  </div>
)
```
