### ISSUE TITLE
i want to submit the tranfer through form,when i set valuepropname it send a warning like this

### ISSUE THREAD

**Issue by zyx4986** [ant-design/ant-design#5532]
getfieldDecorator will override targetkeys,so please don't set targetkeys directly and use setfiledsvalue to set it

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
Use initialValue than set targetKeys to Transfer.
