### ISSUE TITLE
`Datepicker` 英文版 placeholder 有误

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#554]
![image](https://cloud.githubusercontent.com/assets/3580607/11264040/73cf1052-8ecb-11e5-8810-84d9b41d0464.png)

**Comment by afc163** [comment]
placeholder 貌似不在国际化配置中。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/424#issuecomment-150492079 这里是有提到的，其实提供与否并不是很关键，就当一个小优化吧。

**Comment by afc163** [comment]
好。

**Comment by yiminghe** [comment]
这也要内置...
