### ISSUE TITLE
FormItem doesn't detect control input inside

### ISSUE THREAD

**Issue by gaastonsr** [ant-design/ant-design#5540]
#### Environment

- antd version: 2.7.4
- OS and its version: OS X 10.12.3
- Browser and its version: Chrome 56

#### What did you do? Please provide steps to re-produce your problem.

We wrap our form fields into their own component which contain their validation logic. Example

UsernameInput.js
```js
class UsernameInput extends Component {
  render() {
    return this.props.form.getFieldDecorator(this.props.id, {
      rules: [...]
    })(InputComponent);
  }
}
```

And we want to use them in our forms like this

```js
// imports here

class CustomForm {
  render() {
    return (<Form>
      <Form.Item>
        <UsernameInput form={this.props.form} />
      </Form.Item>
    </Form>);
  }
}

export default Form.create()(CustomForm);
```

This doesn't work because [FormItem.getControls](https://github.com/ant-design/ant-design/blob/50f46d0919d2313f14569419aaa9656eb4ede9bb/components/form/FormItem.tsx#L86) doesn't detect the component as a control. Just sees the wrapper as UsernameInput.

#### What do you expected?

`FormItem` to detect `UsernameInput` and work as any input control. Show error messages, feedback, helps, etc.

#### What happen?

`FormItem` doesn't find the control inside.

**Comment by benjycui** [comment]
It's difficult to solve this issue. Could you post your advice(how to implement) here if any?

**Comment by gaastonsr** [comment]
We solved this by calling the component as a function

CustomForm.js
```js
// imports here

class CustomForm {
  render() {
    return (<Form>
      <Form.Item>
        {UsernameInput({ form: this.props.form })}
      </Form.Item>
    </Form>);
  }
}

export default Form.create()(CustomForm);
```

But if you're open to ideas, I think a possible solution would be to define a context in the `FormItem` and the `Input` can register themselves when it's present. Example

FormItem.js
```js
class FormItem extends Component {
  static childContextTypes = {
    registerControl: PropTypes.func
  };

  getChildContext() {
    return { registerControl: this.registerControl }; 
  }

  registerControl(control) {
    this.controls.push(control);
  }
}
```

Input.js
```js
class Input extends Component {
  static contextTypes = {
    registerControl: PropTypes.func
  };

  componentDidMount() {
    if (this.context.registerControl) {
      this.registerControl(this);
    }
  }
}
```

**Comment by benjycui** [comment]
I will try to find a solution.

**Comment by Gerdinand** [comment]
I can get the values of sub components, the validation will also trigger. However, the validation doesn't show. For example: 

```javascript
this.props.form.validateFieldsAndScroll(['postcode', 'postcode2'],(err: any, values: any) => { 
  console.log(err,values);
})
```
`postcode` is inside a child component, `postcode2` is inside the same component as the form. This results in the validation being triggered (seen in the console log `async-validator: ["postcode is required"]`, but the callback of `validateFields` is never called (if there is an error in a child component). Furthermore, the error does not show up in the HTML either, for none of the input fields (also not for input fields which are in the top level form). So it seems like getting a validation error in a child component crashes the function.

I've not yet found any workaround for this, your help will be greatly appreciated

**Comment by sbyps** [comment]
@gaastonsr could u show your whole code about the UsernameInput with this workaround?

**Comment by Nomeyho** [comment]
Hi @gaastonsr and @sbyps, 

I would also be interested in the UsernameInput or on how to implement the nested input.

Thanks

**Comment by JonDum** [comment]
Just ran into this today on antd@3.9.3. Still an issue. @gaastonsr's function workaround is imo more elegant than requiring all form component's to check for context.

**Comment by afc163** [comment]
Please check new form component in antd v4, v3 form will not be maintained in short time.

**Comment by mMarcos208** [comment]
I have the problem with another input outside antd components. Any solution?

```
import CurrencyInput, {CurrencyInputProps} from 'react-currency-input'

 <Form.Item validateStatus="error" hasFeedback={true} help={help} className="mb-0">
      <CurrencyInput />
    </Form.Item>
    
 ```

**Comment by MudulOzan** [comment]
Still have the same problem, any workaround for 4.3?
