### ISSUE TITLE
一个页面有多个Modal组件要显示

### ISSUE THREAD

**Issue by FANUP** [ant-design/ant-design#5541]
#### Environment(required)

- antd version: 2.7.1
- OS and its version: window 7
- Browser and its version: Chrome 50

#### What did you do? Please provide steps to re-produce your problem.
如果一个页面有多个Modal组件要显示，如何定义Modal的z-index，使其能够按我期望的顺序来叠放Modal，现在的顺序是乱的。

#### What do you expected?
能够按我期望的顺序来叠放Modal

**Comment by NE-SmallTown** [comment]
FYI,[twitter](https://twitter.com/) does good.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
It works as expected in some cases, but I don't know your use case.

**Comment by afc163** [comment]
`<Modal style={{ zIndex: 1000 }} />` or `<Modal wrapStyle={{ zIndex: 1000 }} />`

**Comment by FANUP** [comment]
@afc163 Exactly!But <Modal style={{ zIndex: 1000 }} /> no working，<Modal wrapStyle={{ zIndex: 1000 }} />working

**Comment by FANUP** [comment]
@afc163 Exactly!But `<Modal style={{ zIndex: 1000 }} />` no working，`<Modal wrapStyle={{ zIndex: 1000 }} />` working！
