### ISSUE TITLE
2.8.3版本中BreadCrumb异常

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#5542]
@afc163 
antd版本从2.8.2升级到2.8.3时，项目中使用的BreadCrumb组件报错了。
原因是我们的router中存在有部分路径中不需要提供breadcrumbName。
请问：当您升级了“[itemRender不再依赖router.breadcrumbName](https://github.com/ant-design/ant-design/commit/ac1c7f312bc46ba6ef7aacace43e4ac99b87dd54)时：我们针对不需要提供breadcrumbName的router如何使用？

**Comment by afc163** [comment]
Could you provide your code of using BreadCrumb?

**Comment by kairi1227** [comment]
@afc163 
## Router 部分代码：
```javascript
const routes = [
   {
     path: '/',
     component: App,
    indexRoute: {component: IndexPage},
    childRoutes: [
       {
          path: 'index',
          component: IndexPage
        },
        {
          path: 'main',
          breadcrumbName: '首页',
          component: Layout,
          indexRoute: {component: BuildIndex}
      ｝
    ]
  }
];

return <Router history={history} routes={routes}/>;
```
这个router中只有 /main只才显示breadcrumbName，在/ 和/index时都不显示。

## 有BreadCrumb的相关代码
```javascript
<Content className={styles['content']}>
  <Breadcrumb routes={routes} separator=">" className={styles['bread-crumb']} itemRender={(route) =>  route.breadcrumbName} />
  <div className={styles['main']}>
    {children}
  </div>
</Content>
```

**Comment by afc163** [comment]
我没有看到报错，但是这里确实可以改进一下。

**Comment by kairi1227** [comment]
thx @afc163 坐等升级。

**Comment by afc163** [comment]
你可以参考我的改动自己本地试试，毕竟我没有重现出报错。

**Comment by kairi1227** [comment]
@afc163 
sorry，抛的异常是router.breadcrumbName为null引起的，与BreadCrumb组件没关系，只是渲然到页面上不合理，如下图：
![image](https://cloud.githubusercontent.com/assets/4525647/24483921/b27f3c66-152d-11e7-90e3-72fac806cac3.png)
