### ISSUE TITLE
antd版本2.7.0，npm install后，发现Carousel组件 intereface CarouselProps缺少arrows属性，请问如何 添加未声明的属性

### ISSUE THREAD

**Issue by tancyan** [ant-design/ant-design#5543]
目前项目采用的是typescript2.0,antd2.7.0,针对node_modules/lib/antd/carousel/index.d.ts中缺少某些应有的属性，应该如何在现有的基础上解决。

1.组件中的引用 ，报arrows属性不存在
` <Carousel dots={false} arrows={true}  >
                {
                    this.props.days.map(function(item, index){
                        return <div><h3>{item.day}</h3></div>
                    })
                }
            </Carousel>`
2.node_modules/lib/antd/carousel/index.d.ts 缺少arrows属性
/// <reference types="react" />
import React from 'react';
export declare type CarouselEffect = 'scrollx' | 'fade';
export interface CarouselProps {
    /** 动画效果函数，可取 scrollx, fade */
    effect?: CarouselEffect;
    /** 是否显示面板指示点 */
    dots?: boolean;
    /** 垂直显示 */
    vertical?: boolean;
    /** 是否自动切换 */
    autoplay?: boolean;
    /** 动画效果 */
    easing?: string;
    /** 切换面板的回调 */
    beforeChange?: (from: number, to: number) => void;
    /** 切换面板的回调 */
    afterChange?: (current: number) => void;
    /** 行内样式 */
    style?: React.CSSProperties;
    prefixCls?: string;
}
export default class Carousel extends React.Component<CarouselProps, any> {
    static defaultProps: {
        dots: boolean;
        arrows: boolean;
        prefixCls: string;
        draggable: boolean;
    };
    render(): JSX.Element;
}

**Comment by afc163** [comment]
PR is welcomes

**Comment by tancyan** [comment]
我想问下，如果不升级antd，有没有其他解决方法？

**Comment by benjycui** [comment]
minor 版本都是兼容的，直接升级即可。

**Comment by tancyan** [comment]
antd升级到2.8.3也没有那个属性呀，请问，你说的升级是antd的吗？

**Comment by benjycui** [comment]
`2.9.0`
