### ISSUE TITLE
InputNumber，通过state设置的值，为什么失去焦点的时候输入框的值（是数字）就没了

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#5544]
一个InputNumber，通过state设置的值，为什么失去焦点的时候输入框的内容就没了。

`<InputNumber min={0} max={99999999999} value={this.state.income[key]} onChange={this.income.bind(this,key)} step={1} style={{ width: '100%'}}/>
income(key,value){
            let inC = this.state.income;
            let outC = this.state.outcome;
            inC[key] = value;
            outC[key] = null;
            this.setState({
                income:inC,
                outcome:outC
            },() => console.log(this.state.income));
        }`
如果设置成defaultValue失去焦点，值还在，但是不能通过state设置value了，这里初始化state时，state.income=[]，所以value开始得到的this.state.income[key]为undefined，但是onchange内设置state是没问题的。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
close for no response
