### ISSUE TITLE
listView的renderRow中使用Checkbox导致滚动条无法滚动

### ISSUE THREAD

**Issue by Run-Snail** [ant-design/ant-design#5545]
#### Environment(required)

- antd version:1.0.7
- OS and its version:win7
- Browser and its version:Chrome v54:

#### What did you do? Please provide steps to re-produce your problem.

i am tring to use checkbox component in listView component. but it can not scroll. it can roll if delete checkbox component. I use wrong?  help! help! help!

  renderRow(item, sectionID, rowID, highlightRow) {
    return (
       <CheckboxItem key={rowID} >
            <li className=" pd15 lightgrey-02 fs12 lh22 pt12 pb12" >
            <span className="fl mt1">{item.khmc}</span>
            <span className="pl15 fl mt1">{item.khh}</span>
            </li>
        </CheckboxItem>
    );
  }

#### What do you expected?

it can roll

**Comment by benjycui** [comment]
antd-mobile 的问题请到对应的仓库提问。
