### ISSUE TITLE
[Feature discussion]  more robust built-in support for i18n 

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5553]
### Let's see the truth
I suppose that we probably would like to create agnostic to any i18n library, but let's see the truth - it's **NOT** agnostic already - antd using own tiny library to solve i18n problems and LocaleProvider is part of it. 

More over because of lack of functionalities we have to create hack here and there, extend it with getLocale() in most components that needed it and etc.

I suggest to revise it and use external solution (I still remember times when we switched to [moment](http://momentjs.com/) for dates).

There are 3 main players on the market: i18next, react-intl and polyglot. I suggest to stick with [polyglot](https://github.com/airbnb/polyglot.js)

### And here are my **why**:
1. it's small and not bloated - 2.8k minified (probably we already have half of it to solve i18n problems with own implementation)

2.  interpolation and pluralization out of box (E.g.: Pagination/Transfer already potential users of pluralization)

3. easy to use, easy to integrate, really small API to learn

4. it's battle-tested and supported by Airbnb

### How it can helps us? (just example)
1. we will create global variable at _utils
```js
polyglot = new Polyglot();
```
2. remove own workarounds to get i18n and replace it with something like:
```js
polyglot.t('Table.filterTitle', {_: 'default title');
```
3. all current locale files will be same as right now - without any changes

4. to change locale for app we will use LocaleProvider as like now but with some changes(just example):
```jsx
import React, { PropTypes } from 'react';
import { polyglot } from '../utils';

/**
 * i18n provider with some shorthand helpers
 */
export class I18Provider extends React.Component {
	initLocale({ locale, messages }) {
		i18n.locale(locale);
		i18n.clear();
		i18n.extend(messages);
	}

	getChildContext = () => ({
		i18n: i18n.t.bind(i18n)
	});

	componentWillMount() {
		this.initLocale(this.props);
	}

	componentWillReceiveProps(nextProps) {
		if (nextProps.locale !== this.props.locale) {
			this.initLocale(nextProps);
		}
	}

	render() {
		return React.Children.only(this.props.children);
	}
}

I18Provider.propTypes = {
	children: PropTypes.element.isRequired,
	locale: React.PropTypes.string.isRequired,
	messages: React.PropTypes.object.isRequired,
};

I18Provider.childContextTypes = {
	i18n: PropTypes.func.isRequired,
};

/**
 * i18n wrapper for component
 * @param WrappedComponent
 * @returns {function(*, *): XML}
 */
export const injectI18n = (WrappedComponent) => {
	function getDisplayName(component) {
		return component.displayName || component.name || 'Component';
	}

	const InjectI18n = (props, context) => <WrappedComponent {...props} i18n={context.i18n} />;

	InjectI18n.contextTypes = {
		i18n: PropTypes.func.isRequired,
	};

	InjectI18n.displayName = `InjectI18n(${getDisplayName(WrappedComponent)})`;

	return InjectI18n;
};
```

5. after that anyone will have built-in support for i18n. And no any magic anymore. Just 2.8Kb to bundle and functionalities that will be enough for 99% of apps.

6. moreover, to override built-in locale we will need to do just something like this:
```js
polyglot.extend({ 
    Table: {
        filterTitle: 'my supper title!',
    }
);
```

**Comment by yesmeck** [comment]
@plandem Try use http://new-issue.ant.design
