### ISSUE TITLE
[Feature discussion] more robust built-in support for i18n

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5554]
#### Let's see the truth
I suppose that we probably would like to create agnostic to any i18n library, but let's see the truth - it's **NOT** agnostic already - antd using own tiny library to solve i18n problems and LocaleProvider is part of it. 

More over, because of lack of functionalities we have to create hacks here and there, extend it with getLocale() in most components that needed it and etc.

I suggest to revise it and use external solution (I still remember time when we switched to [moment](http://momentjs.com/) for dates).

There are 3 main players on the market: i18next, react-intl and polyglot. I suggest to stick with [polyglot](https://github.com/airbnb/polyglot.js)

#### And here is my **why**:
1. it's small and not bloated - 2.8k minified (probably we already have half of it to solve i18n problems with own implementation)

2.  interpolation and pluralization out of box (E.g.: Pagination/Transfer already potential users of pluralization)

3. easy to use, easy to integrate, really small API to learn

4. it's battle-tested and supported by Airbnb

#### How it can helps us? (just example)
1. we will create global variable at _utils
```js
polyglot = new Polyglot();
```
2. remove own workarounds to get i18n and replace it with something like:
```js
polyglot.t('Table.filterTitle', {_: 'default title'});
```
3. all current locale files will be same as right now - without any changes

4. to change locale for app we will use LocaleProvider as like now but with some changes(just example):
```jsx
import React, { PropTypes } from 'react';
import { polyglot } from '../utils';

/**
 * i18n provider with some shorthand helpers
 */
export class I18Provider extends React.Component {
	initLocale({ locale, messages }) {
		polyglot.locale(locale);
		polyglot.clear();
		polyglot.extend(messages);
	}

	getChildContext = () => ({
		i18n: polyglot.t.bind(polyglot)
	});

	componentWillMount() {
		this.initLocale(this.props);
	}

	componentWillReceiveProps(nextProps) {
		if (nextProps.locale !== this.props.locale) {
			this.initLocale(nextProps);
		}
	}

	render() {
		return React.Children.only(this.props.children);
	}
}

I18Provider.propTypes = {
	children: PropTypes.element.isRequired,
	locale: React.PropTypes.string.isRequired,
	messages: React.PropTypes.object.isRequired,
};

I18Provider.childContextTypes = {
	i18n: PropTypes.func.isRequired,
};

/**
 * i18n wrapper for component
 * @param WrappedComponent
 * @returns {function(*, *): XML}
 */
export const injectI18n = (WrappedComponent) => {
	function getDisplayName(component) {
		return component.displayName || component.name || 'Component';
	}

	const InjectI18n = (props, context) => <WrappedComponent {...props} i18n={context.i18n} />;

	InjectI18n.contextTypes = {
		i18n: PropTypes.func.isRequired,
	};

	InjectI18n.displayName = `InjectI18n(${getDisplayName(WrappedComponent)})`;

	return InjectI18n;
};
```

5. after that anyone will have built-in support for i18n. And no any magic anymore. Just 2.8Kb to bundle and functionalities that will be enough for 99% of apps.

6. moreover, to override built-in locale we will need to do just something like this:
```js
polyglot.extend({ 
    Table: {
        filterTitle: 'my supper title!',
    }
);
```

**Comment by plandem** [comment]
If you want I can't refactor and create pull-request for it.

**Comment by benjycui** [comment]
I don't understand your use case. 

1. Are you going to use locales in antd's locale files? 
2. Or are you going to override some default locales which antd had provided?

If it is 1, how about https://github.com/ant-design/ant-design/issues/5103 ?

**Comment by benjycui** [comment]
And we must make sure that this will work with TypeScript..

**Comment by plandem** [comment]
@benjycui it's 1, 2 and also:

3.  LocaleProvider doesn't support pluralization, E.g. Transfer you singular and plural words (item/items), but in Russian we have like 5 cases for plural.

4. If I want to create own component based on antd and make it public, then I will have to solve i18n problem by self again, because antd doesn't provide any functionalities for it. 

5. If I want to make app to support i18n, then I will have to solve this problem again.

I just ask, why end-users must solve i18n problem again and again when antd already solved it internally with own limited solution (no pluralization)?! If antd will provide public API for i18n (just improve LocaleProvider a bit), then users will not have any problems with i18n locales in own apps in 99% cases.

Let's recap. E.g. we upgrade LocaleProvider with this methods:
```jsx
export class LocaleProvider extends React.Component {
	constructor(props) {
		this.initLocale(props);
	}

	componentWillReceiveProps(nextProps) {
		if (nextProps.locale !== this.props.locale) {
			this.initLocale(nextProps);
		}
	}

	initLocale({ locale, messages }) {
		this.polyglot = new Polyglot({ locale, phrases: messages });
	}

	getChildContext = () => ({
		antLocale: {
			t: polyglot.t.bind(this.polyglot),
			extend: polyglot.extend.bind(this.polyglot),
			clear: polyglot.clear.bind(this.polyglot),
		}
	});
}

LocaleProvider.childContextTypes = {
	antLocale: PropTypes.shape({
		t: PropTypes.func,
		extend: PropTypes.func,
		clear: PropTypes.func,
	}),
};
```

In this case our LocaleProvide will solve all the cases that I mentioned: 1,2,3,4,5:
for 1,3,4,5 - use antLocale.t,
for 2 - use antLocale.extend,

```jsx
export const injectLocale = (componentName, defaultLocale) => (Component) => {

	const defaultLanguage = 'en';
	const noLocale = (id, substitutions) => Polyglot. transformPhrase(defaultLocale[id], substitutions, defaultLanguage);

	const injectLocale = (props, { antLocale }) => <WrappedComponent {...props} locale={antLocale ? antLocale.t.bind(componentName) : noLocale} />;

	injectLocale.contextTypes = {
		antLocale: PropTypes.any,
	};

	injectLocale.displayName = `injectLocale(${componentName})`;
	return injectLocale;
};
```
for antd components we can use this:
```
class Table extends React.Component {
	render(){
		const { locale } = this.props;
		<div>{locale('filterTitle')}</div>
	}
}

export default injectLocale('Table', {
    filterTitle: 'Filter Menu',
    filterConfirm: 'OK',
    filterReset: 'Reset',
    emptyText: 'No Data',
    selectAll: 'Select All',
    selectInvert: 'Select Invert',
})(Table);
```

From app side user can use antLocale like this:
```
class App extends React.Component {
    constructor(props, context) {
       super(props, context);

       //to override some built-in locale
       context.antLocale.extend({ Table: { filterTitle: 'New Filter Menu' }});

      //to use i18n
      console.log(context.antLocale.t('app.button.edit')); //app.button.edit: 'Edit'

      //to use pluralization
      console.log(context.antLocale.t('app.total_cars', { count: 5 })); //app.total_cars: '%{count} car |||| %{count} cars'

      //to use interpolation
      console.log(context.antLocale.t('app.hello', { name: 5 })); //app.hello:  Hello '%{name}!'
    }
}

App.contextTypes = {
	antLocale: PropTypes.any,
};
```

So as you see, in 99% cases built-in LocaleProvider will be enough in that cases

**Comment by plandem** [comment]
I can refactor code and make PR for last version that I wrote here.

**Comment by benjycui** [comment]
Sorry for the late response.

Not all of the projects which had used antd need `LocaleProvider`, e.g. a project just need to provide Chinese locale. This is a point that we need to consider while designing APIs of `LocaleProvider` and so on.

> If I want to create own component based on antd and make it public, then I will have to solve i18n problem by self again, because antd doesn't provide any functionalities for it.

We just need something like #5103 , and it should work with TypeScript(The most difficult point...).

> If I want to make app to support i18n, then I will have to solve this problem again.

1. antd should work with `react-intl` and `polyglot` and other i18n solution, so I don't understand why you think this is a problem. Even if we use `polyglot` in antd, I  don't think we should expose `_util/polyglot`(as you said) to developers. Developer still need to choose their own i18n solution, though we can recommend polyglot to help them to reduce bundle size.
2. Even if we use `polyglot` in antd and recommend developers to use polyglot, I don't think it is a best practice to expose polyglot instance which had been used in antd to developers: 
    1. developers may override antd's locales by mistake
    2. and developers have to know details of antd's locale file to avoid the above point, even though they don't need to override antd's default locale.

> Or are you going to override some default locales which antd had provided?

I don't think `polyglot.extend({ ... })`is better than `LocaleProvider[locale={...}]`... And `antLocale.extend` `antLocale.clear` may make bugs harder to trace. A controlled property(`LocaleProvider[locale]`) is more predictable(Think in React and Redux).

**Comment by benjycui** [comment]
> LocaleProvider doesn't support pluralization, E.g. Transfer uses singular and plural words (item/items), but in Russian we have like 5 cases for plural.

This is a problem we need to solve.

But I think that we should not expos polyglot to developers.

**Comment by benjycui** [comment]
And `injectLocale` should not expose `polyglot.extend` and `polyglot.clear` to components. In case that some third-part components which are based on antd modify locale silently.

**Comment by benjycui** [comment]
@plandem thx, learn a lot while thinking about this issue.

**Comment by plandem** [comment]
@benjycui the only reason to expose **polyglot** to developers is optimization for dependencies :) 

BUT! We need to provide a way to override default locale without pain, e.g. in our case we use a different texts for Table ("Clear all on that page" instead of "Clear all").

**Comment by plandem** [comment]
@benjycui 

> Not all of the projects which had used antd need LocaleProvider, e.g. a project just need to provide Chinese locale. This is a point that we need to consider while designing APIs of LocaleProvider and so on.

This code solves it:
```jsx
const defaultLanguage = 'en';
	const noLocale = (id, substitutions) => Polyglot.transformPhrase(defaultLocale[id], substitutions, defaultLanguage);

	const injectLocale = (props, { antLocale }) => (
		const locale = antLocale 
			? (id, substitutions) => antLocale.t(`${componentName}.${id}`, substitutions) 
			: noLocale;

		<WrappedComponent {...props} locale={locale}/>
	);
```
In case if there is no LocaleProvider, then use:
```js
Polyglot.transformPhrase(defaultLocale[id], substitutions, defaultLanguage);
```

**Comment by benjycui** [comment]
> BUT! We need to provide a way to override default locale without pain, e.g. in our case we use a different texts for Table ("Clear all on that page" instead of "Clear all").

I don't understand, will this be hard to developers? I don't think `polyglot.extend` is much simpler.

```jsx
const locale = deepCopy(defaultLocale);
locale.Table.clear = 'xx'
```

**Comment by plandem** [comment]
> I don't understand, will this be hard to developers? I don't think polyglot.extend is much simpler.
Nope. I'm talking that we must preserve easy way to override default texts :)

**Comment by benjycui** [comment]
So, let me draw a conclusion.

1. We need to provide a solution to solve pluralization
2. We need to provide a way to reuse locales which are provided by antd.LocaleProvider, e.g. https://github.com/ant-design/ant-design/issues/5103

**Comment by plandem** [comment]
I'm sure that it would be a good idea to provide a way to localize components bases on antd. E.g. I created a new component and want to make it public.
