### ISSUE TITLE
Carousel and echarts is not compatible！

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#5555]
### Version
2.8.3

### Environment
chrome

### Reproduction link
[http://codepen.io/anon/pen/JWLmbR](http://codepen.io/anon/pen/JWLmbR)

### Steps to reproduce
 Carousel cannot load the r echarts the last page, for example，Id is the main and the main2 page load out, if main3, not by echarts rendering is written on the page, there is no problem, if you remove main3, main1 will render not to come out, please his operation

### What is expected?
Echarts renders the page to load

### What is actually happening?
Echarts not renders the page to last

**Comment by afc163** [comment]
I can't understand what you said...you can try to use Chinese.

**Comment by SynChron1zed** [comment]
@afc163  例子中  Carousel  的第一个 和第二个页面 是echarts 渲染的，第三个是直接写的  ，如果去掉第三个页面 ，前二个echarts渲染的页面就只能渲染出第一个页面，第二个会显示不出来

**Comment by gaastonsr** [comment]
I appreciate trying to describe your problem in English first.

**Comment by SynChron1zed** [comment]
@gaastonsr  To solve the problem first

**Comment by afc163** [comment]
Because `infinite` mode of `react-slick` will clone their children for loopless display, so echart init will affect to wrong node. So here is the solutions:

1. init every node: http://codepen.io/anon/pen/jBQZvm?editors=0010
2. turn off `infinite`: http://codepen.io/anon/pen/peQaQr

**Comment by SynChron1zed** [comment]
@afc163  ok thanks !!!
