### ISSUE TITLE
Pagination style suggestion

### ISSUE THREAD

**Issue by ken1987** [ant-design/ant-design#5557]
### What problem does this feature solve?
在使用Pagination时，希望内容能靠右对齐，那么需要如下代码：
``` jsx
<div class="clearfix">
  <Pagination size="small" style={{float: right}} />
</div>
```

### What does the proposed API look like?
把使用 float 布局的样式，改用 inline-block

那样，只需要添加一句样式就能居右对齐，且不需要格外的标签

```html
<Pagination size="small" style={{text-align: right}} />
```

**Comment by afc163** [comment]
I think this could be accepted, can you propose a PR for this?

Also `style={{text-align: right}}` should be `style={{textAlign: right}}`.

**Comment by afc163** [comment]
@ken1987
