### ISSUE TITLE
缓存 `locale` 以优化性能

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#556]
发现 `Datepicker` 中多次用到 [getLocale](https://github.com/ant-design/ant-design/blob/develop-0.10.0/components/datepicker/index.jsx#L41)，这个函数在每次调用的时候，都会生成新的对象。

我看了下代码，并没有哪些地方修改了 `getLocale` 返回的值，也就是说这个 `locale` 是只读的（或者说有些地方我忽略了？）。

所以建议可以把 `locale` 的值存进 `this.state.locale`，然后仅在 `componentWillReceiveProps ` 时才更新一下，这样会省点性能。

@afc163 @yiminghe

**Comment by yiminghe** [comment]
ok
