### ISSUE TITLE
Update or/and remove normalize.css from /lib/style/index.css

### ISSUE THREAD

**Issue by kud** [ant-design/ant-design#5561]
### What problem does this feature solve?
Be updated about normalize.css

### What does the proposed API look like?
I would like to be able to handle myself normalize.css or maybe use an updated version of normalize.css which is no more 5.0.0 but 6.0.0.

**Comment by coocooooo** [comment]
如果用<style src="https://....">的形式引入其他css库如bootstrap.css，然后引入antd，normalize.css会覆盖bootstrap.css中的样式（如 ul，ol，li），建议自己处理normalize.css
