### ISSUE TITLE
disabled fieldsed

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5562]
### Version
2.8.3

### Environment
osx, chrome

### Reproduction link
[http://codepen.io/anon/pen/xqQVpa?editors=001](http://codepen.io/anon/pen/xqQVpa?editors=001)

### Steps to reproduce
just disable fieldset

### What is expected?
all form elements must be disabled

### What is actually happening?
ant version of elements are not disabled

**Comment by afc163** [comment]
I am not sure we should support this feature. You can use `disabled` of each Component now.

**Comment by benjycui** [comment]
And this may not work with developers' customized form controls.

**Comment by benjycui** [comment]
And if we try to achieve this with CSS, we need to maintain a long list.

**Comment by plandem** [comment]
@afc163 in my case it's headache to disable each control manually :( too many controls, I hoped for built-in html feature :(

**Comment by plandem** [comment]
@benjycui why we can't use overlay for fieldset to disable controls? E.g.:
```
	fieldset { position: relative; }
	fieldset[disabled]::after { content: ''; display: inline-block; position: absolute; top: 0; left: 0; right: 0; bottom: 0; pointer-events: all; background: rgba(128,128,128,0.2); }
	[disabled] { pointer-events: none; }
```

**Comment by benjycui** [comment]
> @benjycui why we can't use overlay for fieldset to disable controls? E.g.:

Actually, antd's components are just divs, and disabled style are applied to several parts of a component, so it is not easy to control all the form controls disabled style with CSS.

Anyway, you can try to PR, e.g. make Select disabled status follow `fieldset[disabled]` first.

**Comment by plandem** [comment]
@benjycui it's not PR, want to ask - can we use it like this, for example:
```
	fieldset {
	  position: relative;
	  border: none;
	}

	fieldset[disabled]::after {
	  content: '';
	  display: inline-block;
	  position: absolute;
	  top: 0;
	  left: 0;
	  right: 0;
	  bottom: 0;
	  pointer-events: all;
	  background: rgba(255, 255, 255, 0.01);
	}

	fieldset[disabled] {
	  .@{btn-prefix-cls} {
		.button-color(@btn-disable-color; @btn-disable-bg; @btn-disable-border);
	  }

	  .@{select-prefix-cls} {
		color: @disabled-color;

		&-selection {
		  background: @background-color-base;
		}

		.@{select-prefix-cls}-selection--multiple .@{select-prefix-cls}-selection__choice__remove {
		  display: none;
		}
	  }

	  .@{switch-prefix-cls} {
		background: #f4f4f4;
		border-color: #f4f4f4;

		&:after {
		  background: #ccc;
		}

		.@{switch-prefix-cls}-inner {
		  color: @disabled-color;
		}
	  }
	}

	[disabled] { pointer-events: none; }
```

events will be prevent via overlay, so we only need to make it looks like disabled.

**Comment by afc163** [comment]
You can propose PR for this just for your usage.

**Comment by benjycui** [comment]
Actually, your solution https://github.com/ant-design/ant-design/issues/5562#issuecomment-290407027 is just what I had said:



> And if we try to achieve this with CSS, we need to maintain a long list.

**Comment by benjycui** [comment]
How about this:

```jsx
// Fieldset
class Fieldset extends React.Component {
  getChildContext() {
    return { disabled }
  }
  ...
}
```

```jsx
// Fieldset.Disable
function Disable(Component) {
  return class extends React.Component {
    contextTypes = {
      disabled: boolean
    }
    render() {
      return <Component {...this.context} />
    }
  }
}
```

Then you can wrap any component that you had used in Fieldset

```jsx
const Select = Fieldset.Disable(antd.Select)
```

**Comment by benjycui** [comment]
And I think your use case is an edge case now, I don't think we need to make form controls' disabled status follow fieldset until it becomes a common use case.

If others meet issue like @plandem , just post your use case in this issue, then we will consider.

**Comment by plandem** [comment]
Ok, I will use CSS way for my own case :)
