### ISSUE TITLE
backTop组件的target指向的对象没有缓动效果

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#5564]
### What problem does this feature solve?
项目内顶部固定，滚动的是一个指定的div元素，通过target指定该滚动元素后，由于`scrollToTop`方法中，`currentScrollTop()`获得的总是window或body的scrollTop，所以缓动函数总是返回0，导致指定的滚动元素立即回到顶部。
既然有这样一个外部接口提供target，或许对target也进行动画处理比较好。

### What does the proposed API look like?
```
currentScrollTop(this.props.target());
// 引入target
const currentScrollTop = (target) => {
  const targetScrollTop = target && target.scrollTop;
  return targetScrollTop || window.pageYOffset || document.body.scrollTop || document.documentElement.scrollTop;
};
```

**Comment by afc163** [comment]
Did you propose a bug but not a feature request?

**Comment by afc163** [comment]
I think this is a bug, you should choose `bug report` in issue templates.
