### ISSUE TITLE
multipie=true with OptGroup in Select will cause error.

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#5567]
### Version
2.8.2

### Environment
win10 chrome 56

### Reproduction link
[http://codepen.io/Frezc/pen/zZMRNp?editors=0010](http://codepen.io/Frezc/pen/zZMRNp?editors=0010)

### Steps to reproduce
在multiple为true的Select中使用OptGroup。

### What is expected?
正常使用

### What is actually happening?
无法使用

**Comment by yesmeck** [comment]
Try reinstall node_modules.
