### ISSUE TITLE
Steps组件  findDOMNode was called on an unmounted component

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#5568]
### Version
2.8.2

### Environment
Win7 Chrome57.0.2987.98

### Steps to reproduce
1. 组件状态变至unmout
2. redux的immtablestate改动触发render

### What is expected?
判断unmout状态下不去做render

### What is actually happening?
invariant.js:43 Uncaught Error: findDOMNode was called on an unmounted component.

---
使用dva，immutablejs

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/5501
