### ISSUE TITLE
Button 作为 Input addonAfter

### ISSUE THREAD

**Issue by MarshallChen** [ant-design/ant-design#557]
好像样式上是有问题的 还是说我的做法是错误的？

```javascript
const {
  Input,
  Button
} from 'antd';

<Input size="large" addonAfter={
  <Button type="primary" children="Hello" />
} />

```

**Comment by benjycui** [comment]
现在的设计，只考虑下面的情况。

![image](https://cloud.githubusercontent.com/assets/3580607/11266470/b64190a4-8edf-11e5-91c4-0ce8a0737326.png)

直接把 `Button` 放在 `Input` 右边不行么？

**Comment by afc163** [comment]
需要类似上面的样式放按钮的，下期会单独做这个样式。

目前就按 @benjycui 说的直接放就行，暂不支持 addonAfter 用法。
