### ISSUE TITLE
Can we have configurable option for no of rows in table? Like drop down below/above the  table having numbers. If user selects any number from drop down, it will show that many number of rows.

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#5572]
### What problem does this feature solve?
Actually user can decide how many rows at a time she wants to view. Even show all option the dropdown will show all data in one go. It is required feature in our project for specific requirements. Before we were using jquery which supports this feature. Now we are moving to reactjs.

### What does the proposed API look like?
we can have configure option  in which we can add list of numbers for rows.

**Comment by yesmeck** [comment]
Do you mean pagination?

**Comment by KalpanaPagariya** [comment]
No, the way in jquery it works. drop down menu showing how many rows at a time we want to show. Suppose tehre is one drop down above table having numbers like ["5","10","15"."All"]. When user selects 5 from drop down, table will show only 5 records at a time and. if user selects All, all rows will be visible under table (no need of pagination in this case)

**Comment by plandem** [comment]
for me it's looks like Pagination, you can adjust settings for own needs.

**Comment by benjycui** [comment]
Just use `Table` with pagination which had `showSizeChanger`

```jsx
import { Table, Icon } from 'antd';

const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  render: text => <a href="#">{text}</a>,
}, {
  title: 'Age',
  dataIndex: 'age',
  key: 'age',
}, {
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
}, {
  title: 'Action',
  key: 'action',
  render: (text, record) => (
    <span>
      <a href="#">Action 一 {record.name}</a>
      <span className="ant-divider" />
      <a href="#">Delete</a>
      <span className="ant-divider" />
      <a href="#" className="ant-dropdown-link">
        More actions <Icon type="down" />
      </a>
    </span>
  ),
}];

const data = [{
  key: '1',
  name: 'John Brown',
  age: 32,
  address: 'New York No. 1 Lake Park',
}, {
  key: '2',
  name: 'Jim Green',
  age: 42,
  address: 'London No. 1 Lake Park',
}, {
  key: '3',
  name: 'Joe Black',
  age: 32,
  address: 'Sidney No. 1 Lake Park',
}];

ReactDOM.render(
  <Table columns={columns} dataSource={data} pagination={{ showSizeChanger: true }} />, 
  mountNode
);
```
