### ISSUE TITLE
What the different between RangePicker's value and defaultValue?

### ISSUE THREAD

**Issue by walkerqiao** [ant-design/ant-design#5574]
What the different between RangePicker's value and defaultValue?

```
class DateRange extends Compent {
   const {
     range, // from wrapper compent's state
     format,
     .....
   } = this.props

  render() {
     const rpProps = {
        showTime: true,
        format,
       defaultValue: range,
       // value: range,
     }

     return (
        <RangePicker {...rpProps} />
     )
  }
}
```
RangePicker's props is passed from parent wrapper component. Wrapper component remain the state and sync the value to RangePicker's props.

If i changed the range state out of the RangePicker, it does not change the RangePicker's UI when i am using defaultValue to range. when i use 'value: range', I can get the right UI render, But i can't rerange the RangePicker.

I don't known why? and i don't known what different between value and defaultValue props.

This is my Component:
```
         RangePicker                         shortcuts
+---------------------+
|     Select Date range  |            1 week    |    2 weeks   |   1 month     |   half year      |     1 year
+---------------------+
```

The Component provide two way to choose your date range:
1. directly select from the RangePicker
2. click the shortcuts from the right

when click the shortcuts, the RangePicker should stay sync with the shortcuts. 

I use defaultValue, it does not stay sync when i click shortcuts. it can stay sync when i using value: range, but the RangePicker can't be reselected.

**Comment by afc163** [comment]
@walkerqiao Try http://new-issue.ant.design/?repo=ant-design
