### ISSUE TITLE
button bug

### ISSUE THREAD

**Issue by TBRMAN** [ant-design/ant-design#5578]
### What problem does this feature solve?
在button标签内部的a标签和link在火狐浏览器中不能使用

### What does the proposed API look like?
兼容火狐

**Comment by TBRMAN** [comment]
------

**Comment by yesmeck** [comment]
请按 bug 的模版来提 issue。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4560#issuecomment-271765901
