### ISSUE TITLE
RangePikcer with shortcuts has some problem

### ISSUE THREAD

**Issue by walkerqiao** [ant-design/ant-design#5579]
### Version
2.8.3

### Environment
macbook, chrome, ant-design

### Reproduction link
[https://github.com/walkerqiao/ada/blob/master/src/components/Filter/DateRange.js](https://github.com/walkerqiao/ada/blob/master/src/components/Filter/DateRange.js)

### Steps to reproduce
```
const pickerProps = {
      showTime: true,
      style: {width: '200px'},
      format: this.props.format || 'YYYY-MM-DD',
      defaultValue: range || [],
      onChange: function(date, dateString) {
        console.log(date)
      }
    }
```

This code can reselect RangePicker, but the shortcut does sync the value to RangePicker.

```
    const pickerProps = {
      showTime: true,
      style: {width: '200px'},
      format: this.props.format || 'YYYY-MM-DD',
      defaultValue: range || [],
      value: range || [],   // add this line
      onChange: function(date, dateString) {
        console.log(date)
      }
    }
```

The code above can do the sync, but can't reselect the RangePicker.

### What is expected?
```
    RangePicker                                shortcuts
 ------------- 
| RangePicker |                 1 week | 2 weeks | 1 month | 3 month | half year | 1 year
 ------------- 
```

I need the component can select range from RangePicker  or the right shortcuts, and need shortcuts has feedback to RangePicker's UI.

### What is actually happening?
1. when i click the item of shortcuts, I can't  keep sync with RangePicker's value, but can reselect the RangePicker. (using defaultValue)
2. when i click the RangePicker, I can't reselect the date range, but can keep sync with the shortcuts. (using value)

---
what is the different between value and defaultValue props, and how can i do that in my component?

**Comment by walkerqiao** [comment]
It seems i have find the solution:

```
const {
   onChange,
  ...
} = this.props
// in my DateRange.js
    const pickerProps = {
      showTime: true,
      style: {width: '200px'},
      format: this.props.format || 'YYYY-MM-DD',
      defaultValue: range || [],
      value: range || [],   // add this line
      onChange: function(date, dateString) {
        onChange(date, dateString) // this is passed from container component, ant it sync the state of the range
      }
    }

// in my container component

```
const onChange = (date, dateString) => {
    dispatch({
       type: 'xxx/calendar',
       payload: {
          date,
          dateString,
       }
    })
}

const drProps = {
   onChange,
   ...
}

<DateRange {...drProps} />
```

it seems works, and i will test it then.

**Comment by yesmeck** [comment]
You can not pass `defaultValue` and `value` to `RangePikcer` at the same time. 

See:
https://facebook.github.io/react/docs/uncontrolled-components.html
https://facebook.github.io/react/docs/forms.html

**Comment by walkerqiao** [comment]
@yesmeck, Thank you very much!  I had read the article above, and learned more. 

I think i did known why, thanks.

this is my translate article from the article above. http://joescott.coding.me/blog/2017/03/31/react-form/
