### ISSUE TITLE
Select被更数据之后，默认选择的还是上一次选择的数据。

### ISSUE THREAD

**Issue by GoDotDotDot** [ant-design/ant-design#5581]
### Version
2.8.3

### Environment
系统：Win10, 浏览器：57.0.2987.98 (64-bit)，react：15.3.1

### Reproduction link
[https://github.com/GoDotDotDot/antd-select.git](https://github.com/GoDotDotDot/antd-select.git)

### Steps to reproduce
1.select随便选择一条
2.点击data1，更新数据，默认加载的是data2
3.会发现select默认选择数据不变，依旧是上一个数据的默认选择项，但是option已经更新为新数据了

### What is expected?
更新数据option和默认选择数据都会变，即默认选择数据显示新数据的第一条

### What is actually happening?
option数据更新了，但是默认选择数据没变

---
类似级联，外部传数据给select。select更新数据并初始选择项为新数据的第一条

**Comment by yesmeck** [comment]
It's a intended behavior, if you want change selected option, you can use `value`.
