### ISSUE TITLE
ant.design访问不了拉！！！

### ISSUE THREAD

**Issue by zhangjiayin** [ant-design/ant-design#5587]
### Version
2.8.3

### Environment
ant.design访问不了拉！！！

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
ant.design访问不了拉！！！

### What is expected?
ant.design访问不了拉！！！

### What is actually happening?
ant.design访问不了拉！！！

**Comment by afc163** [comment]
实测可以，请检查网络环境。

**Comment by zhangjiayin** [comment]
traceroute ant.design
traceroute to ant.design (47.88.240.14), 30 hops max, 60 byte packets
 1  gateway (192.168.100.1)  0.536 ms  0.536 ms  0.531 ms
 2  192.168.1.1 (192.168.1.1)  1.669 ms  1.696 ms  1.693 ms
 3  111.204.112.49 (111.204.112.49)  18.298 ms  20.200 ms  24.266 ms
 4  124.65.238.25 (124.65.238.25)  3.666 ms  3.665 ms  3.918 ms
 5  123.126.7.209 (123.126.7.209)  5.693 ms  5.696 ms  5.694 ms
 6  61.148.155.209 (61.148.155.209)  3.631 ms  3.898 ms  3.888 ms
 7  202.96.12.1 (202.96.12.1)  4.783 ms  6.420 ms  6.367 ms
 8  219.158.7.22 (219.158.7.22)  34.493 ms * *
 9  * * *
10  * * *
11  203.208.171.82 (203.208.171.82)  105.801 ms *  112.304 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * 47.88.240.14 (47.88.240.14)  2828.294 ms

nc -v ant.design 443 不通 我被封了？

**Comment by zhangjiayin** [comment]
This site can’t be reached

ant.design took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_TIMED_OUT

**Comment by afc163** [comment]
```
nc -v ant.design 443
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 10.15.231.45 port 60612
	dst 47.88.240.14 port 443
	rank info not available
	TCP aux info available

Connection to ant.design port 443 [tcp/https] succeeded!
```

不了解，试试翻墙？

**Comment by zhangjiayin** [comment]
翻墙是好的 。。。。 原来在新加坡！
