### ISSUE TITLE
Async validate when the session is invalid

### ISSUE THREAD

**Issue by zzzzxiao** [ant-design/ant-design#5592]
### Version
2.8.0

### Environment
windows7,chrome, react: ^15.4.0,react-dom: ^15.4.0

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
When I use Ajax validate  whether the user is exist,and the request will response a session error message to callback(of validator ) when session is invalid.and then a login dialog open and I login and continue to submit the form,but the session error is already exist.

### What is expected?
If I login successfully and submit form again,the session error will not be exist.

### What is actually happening?
I login successfully and continue submit form,but the validateFields function return error of session invalid.Actually the session is valid

**Comment by zzzzxiao** [comment]
![image](https://cloud.githubusercontent.com/assets/5946172/24574977/82ce81f6-16cd-11e7-8043-63f4ad5d4935.png)
error in the image will show if session invalid when async validate a input,but when I login and continue to submit the form, the validateFields function always show the same error,I think this is a bug of validateFields function

**Comment by benjycui** [comment]
Try to use [`setFields`](https://ant.design/components/form/#Form.create(options)) to clear errors after login
