### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by BoizZ** [ant-design/ant-design#5593]
### What problem does this feature solve?
打包变小或者编译变快

### What does the proposed API look like?
既然用ts重写了，按需加载插件还依赖babel就显得不完美了，加一层编译总觉得会变慢一些，不知道是不是心理作用。

**Comment by yesmeck** [comment]
有具体可以执行的方法？

**Comment by afc163** [comment]
问题略泛，不容易讨论。。

**Comment by BoizZ** [comment]
@afc163 意思是如果用ts来写的话就会用ts-loader来编译，可能不会用到babel，因此推荐的babel-plugin-import插件就没办法派上用场了，如果要减小包的大小，只能通过单个引入的方式，或者加入babel编译。

**Comment by yesmeck** [comment]
`ts-loader` 前再加 `babel-loader` 吧，没什么具体可以执行的建议的话就关了。

**Comment by bang88** [comment]
> 意思是如果用ts来写的话就会用ts-loader来编译，可能不会用到babel，因此推荐的babel-plugin-import插件就没办法派上用场了，如果要减小包的大小，只能通过单个引入的方式，或者加入babel编译。

这里有个类似的模块，可以解决import的问题。但是不用babel还有很多东西要考虑 😢 

https://github.com/bang88/modular-typescript-import
