### ISSUE TITLE
antd Tabs 组件当TabPane过多时不会出现Tab滚动效果

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#5596]
### Version
2.8.2

### Environment
chrome 5.4  

### Reproduction link
[http://127.0.0.1](http://127.0.0.1)

### Steps to reproduce
生成足够多的TabPane以致于容器无法容纳

### What is expected?
生成Tab滚动效果

### What is actually happening?
不会出现Tab滚动效果

**Comment by yesmeck** [comment]
Reproduction link....

**Comment by afc163** [comment]
close for no re-produciable.
