### ISSUE TITLE
table组件加载大量数据时速度过慢

### ISSUE THREAD

**Issue by licuicui** [ant-design/ant-design#5599]
### Version
2.7.0

### Environment
MacOS 10.11.6 Chrome56.0.2924.87 react15.4.2

### Reproduction link
[http://codepen.io/licuicui/pen/aJXzyO?editors=1111](http://codepen.io/licuicui/pen/aJXzyO?editors=1111)

### Steps to reproduce
1.定义columns的长度为14，2.固定表头和一二列，3.分别在willmount、render、didmount查看时间,4dataSource为1000条

### What is expected?
渲染速度控制到2s至3s

### What is actually happening?
渲染速度5s

**Comment by ywzhaiqi** [comment]
个人看法，好像是 react 渲染 1000 条 li 就有点慢了，一般要分页或只渲染看到的部分。

**Comment by yesmeck** [comment]
暂时建议分页吧。

**Comment by afc163** [comment]
之前专门优化过，目前没有更好的优化手段，可以等待 react@16 或者尝试直接给 PR ~
