### ISSUE TITLE
AutoComplete: Async loading of options fail first render.

### ISSUE THREAD

**Issue by JesperWe** [ant-design/ant-design#5601]
### Version
2.8.3

### Environment
Any

### Reproduction link
[http://codepen.io/JesperWe/pen/XMOzqP](http://codepen.io/JesperWe/pen/XMOzqP)

(Type 'res' slooowly in the input field. Notice first menu item does not appear until second character typed.)

### Steps to reproduce
1. Start with `dataSource = []`
2. When user enters one character search text, do async request for results to server. (Simulated by `setTimeout` in the codepen)
3. When result arrives, update AutoComplete dataSource.

### What is expected?
Menu to pop up with option from *first* async server result.

### What is actually happening?
Menu is *not* appearing until dataSource has been updated 2 times (after request made on second character returns).
After second update each new async result updates the menu as expected.

---
This issue is only present when using async loading and on the **first** update of dataSource from `[]` to `[...some options...]`.

**Comment by mitchelldemler** [comment]
Believe it's the same as this issue: #4393

What I did was copy the Autocomplete component from v2.6.4 and manually imported it into my project. v2.7 is when your issue was introduced.

Using the v2.6.4 Autocomplete means you can't customise the Input though.

**Comment by JesperWe** [comment]
Hum. If that is the case (trying to decode the Chinese) it means that it has been known for three months and not fixed... Not so good news. 

I'll leave this issue open, Chinese speaking devs feel free to close it "Same as" if it is indeed the same as #4393.

**Comment by JesperWe** [comment]
Working around by downgrading to antd@2.6 was not an option for me. I have made a different workaround, which is to do a "dummy" async update of `dataSource` once before any real data is present. 

In my case I don't actually execute the search until the user has entered two characters, so updating dataSource with a dummy <Option> item after the first character is typed makes everything work as the user expects.

**Comment by JesperWe** [comment]
I have tried to trace the problem a bit. I think it is actually in `rc-select`, because looking at the react properties of this sub-tree after the first update:

![image](https://cloud.githubusercontent.com/assets/1643015/24662890/bd916fde-1956-11e7-9dfe-e598b1b3cf4f.png)

... AutoComplete correctly has `dataSource: Array[1]`.

... Select correctly has `children: Array[1]`.

... the second Select correctly has `children: Array[1]`.

... but selectTrigger incorrectly has `options: Array[0]`.

**Comment by ZedZhang** [comment]
Got the same problem here.

**Comment by RaoHai** [comment]
Thanks @JesperWe.

This bug happened because of this equation:

https://github.com/react-component/select/blob/master/src/Select.jsx#L695

a customised input element, defaultly in antd, an `<Antd.Input />` , will always not equals activeElement of document.

**Comment by RaoHai** [comment]
* [ ] https://github.com/react-component/select/pull/177
* [ ] https://github.com/ant-design/ant-design/pull/5633

both merged then get fix..

**Comment by yesmeck** [comment]
A new version of rc-select has released, try reinstall node_modules.
