### ISSUE TITLE
Calendar: First day of week

### ISSUE THREAD

**Issue by Twisterking** [ant-design/ant-design#5605]
## EDIT: ##
Okay ... I do not understand. I used your codepen snippet and it works just fine there. [click here](http://codepen.io/anon/pen/NpJRrw)
ONLY by changing the `locale={locales.en_US}` to `locale={locales.de_DE}` the calendar now starts with Monday. The weird thing is: in my react app this does not work. I provide the `<LocaleProvider/>` component with the exact same `locale` prop as in the codepen snippet but it does not work - the week still starts with Sunday! :-(
Also: Some text is in German, but for example the weekdays and the months themselves are still English ("May" instead of "Mai").
[Screenshot](https://picload.org/image/rcrrlpol/bildschirmfoto2017-04-03um20.0.png)

Any ideas on this?
I tried pretty much anything, I even copied the `locales.de_DE` object from codepen into my app and used it there - no luck. I really am out of ideas what I am doing wrong ...

## EDIT 2: ##
So apparently the `moment.locale('de')` is important. I don't know why it did not change anything in the codepen snippet but apparently I was just missing this import: `import 'moment/locale/de';`.

**@ ANT dev group:**
Maybe mention this somewhere in all "date" components that setting the `moment.locale('xyz')` and importing the right file is very important!

**Comment by Twisterking** [comment]
Original post:

### What problem does this feature solve?
In pretty much all countries around the world the week starts with Monday!
I desperately need this feature as starting the week on Sunday confuses all my users!

### What does the proposed API look like?
firstDayOfWeek: Int or String

**Comment by dbx834** [comment]
For anyone struggling with this —

```jsx
import { LocaleProvider, Calendar } from 'antd';
import en_GB from 'antd/lib/locale-provider/en_GB';

...

<LocaleProvider locale={en_GB}>
    <Calendar
        dateFullCellRender={dateFullCellRender}
        onSelect={this.onSelect}
        defaultValue={this.state.selectedDate}
        ...
    />
</LocaleProvider>
```

— should work.

**Comment by Q-back** [comment]
Thanks to @Twisterking 

## Full answer
```javascript
...
import { ConfigProvider } from 'antd';
import en_GB from 'antd/lib/locale-provider/en_GB';
import moment from 'moment';
import 'moment/locale/en-gb';  // important!

moment.locale('en-gb');  // important!
ReactDOM.render(
  (
    <ConfigProvider locale={en_GB}>
      <App />
    </ConfigProvider>
  ),
  document.getElementById('root')
);
```
This should change first day in all DatePickers to Monday.

**Comment by danielrob** [comment]
Actually I believe the 
```
moment.locale('en-gb');  // important!
```
Is not important since AntD completely ignores it. For example we have 
```
import { ConfigProvider } from 'antd';
import en_GB from 'antd/lib/locale-provider/en_GB';
import moment from 'moment';
import 'moment/locale/en-nz';  
import 'moment/locale/en-gb';  // for AntD since it doesn't support en-nz. 

moment.locale('en-nz');  // for our general moment use
ReactDOM.render(
  (
    <ConfigProvider locale={en_GB}>
      <App />
    </ConfigProvider>
  ),
  document.getElementById('root')
);
```

And this results in starting with monday if and only if the `import 'moment/locale/en-gb';` is there, and regardless of whether `moment.locale('en-nz');` has been set or not.

**Comment by MostafaMDZH** [comment]
This worked for me:
https://stackoverflow.com/a/75912884/5328721
