### ISSUE TITLE
当Table组件在fieldset包裹时，用scroll来固定列出现布局混乱！

### ISSUE THREAD

**Issue by junhwong** [ant-design/ant-design#5606]
### Version
2.9.0

### Environment
chrome

### Reproduction link
参见：https://ant.design/components/table-cn/#components-table-demo-fixed-columns

### Steps to reproduce
```
<fieldset><Table ...></fieldset>
```

### What is expected?
与演示一样

### What is actually happening?
错乱

**Comment by yesmeck** [comment]
Try set a fixed width on table `<Table style={{ width: '900px' }} columns={columns} dataSource={data} scroll={{ x: 1300 }} />`.

**Comment by junhwong** [comment]
@yesmeck 试过的的哈，无论是把表格的大小固定还是把它的父容器(包括fieldset和fieldset的容器都设置过)， 调试很久才发现这个BUG的(对比官网的DEMO)， 改成其它元素才正常的。所以，报告给你们！

**Comment by yesmeck** [comment]
能给个 demo 吗？我这边设置宽度后是可以的。

**Comment by junhwong** [comment]
Fieldset
```js
const fieldset = {
    padding: '.35em .625em .75em',
    border: '1px solid silver',
    minHeight: '600px',
    width: '100%',
}

const legend = {
    border: 0,
    margin: 0,
    padding: '0 .5em',
    width: 'auto',
    color: '#108ee9',
}
class Fieldset extends React.Component {
    constructor(props) {
        super(props)
    }
    state = {}
    render() {
        let wrapper = {...fieldset, ...this.props.style || {}}
        return <fieldset style={wrapper}>
            <legend style={legend}>{this.props.title}</legend>
            {this.props.children}
        </fieldset>
    }
}
export default Fieldset
```


```

+            <Fieldset title="订单明细">
 	143
+                <Table scroll={{ x: 2000, y: 200 }} bordered size="small" pagination={false} columns={columns} dataSource={data} />
 	144
+            </Fieldset>
 	145
+        </div>

```


大致这样，我看的历史记录，摘的一些

**Comment by junhwong** [comment]
还有，提一下，固定列在嵌套表格中，布局也是错乱的，[可展开](https://ant.design/components/table-cn/#components-table-demo-expand)

**Comment by yesmeck** [comment]
@junhwong 在线 demo http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by junhwong** [comment]
好的。
另外再提一点的就是，表格一般只能自适应于容器，如果设置宽度的话，就需要手动来监视和窗口的变化，不符合实际应用

**Comment by junhwong** [comment]
@yesmeck  你看这个就是直接的效果  http://codepen.io/anon/pen/rygMRo

**Comment by junhwong** [comment]
在上面的例子里设置宽是正常的，但这样：
```js
<Fieldset title="订单明细" style={{ width: '900px' }}>
    <p className="version">antd version: {version}</p>
    <Table style={{ width: '100%' }} columns={columns} dataSource={data} scroll={{ x: 1300 }} />
  </Fieldset>
```

就不行了，所以我认为这是个BUG

**Comment by yesmeck** [comment]
Try 

```css
fieldset {
  min-width: inherit; 
}
```

See http://stackoverflow.com/a/16720242/398988
