### ISSUE TITLE
How to prevent Autocomplete change value onSelect

### ISSUE THREAD

**Issue by lgordey** [ant-design/ant-design#5610]
### Version
2.8.3

### Environment
Chrome 57

### Reproduction link
[http://codepen.io/lgordey/pen/wJOQmM?editors=1111](http://codepen.io/lgordey/pen/wJOQmM?editors=1111)

### Steps to reproduce
Make changes in input, select value from autocomplete.
Repeat a few times.

### What is expected?
I expect that `this.setState({ text: '' });` will clear input, but component rewrite it after changing state.
So I can do it just like
```javascript
setTimeout(() => { this.setState({ text: '' }) }, 100);
```

### What is actually happening?
Input is not clearing by setting empty string state to text.

---
Maybe there is some extra method to detect selection and prevent changing input value?

**Comment by JesperWe** [comment]
onSelect is called before onChange. I work around this issue by setting a flag (`this.dontRunOnChangeAfterOnSelect = true`) in onSelect and then in onChange if that flag is true I just reset it and return.

**Comment by RaoHai** [comment]
How about select action do not trigger onChange defaultly? Or add an extra callback called `onInputChange`?

**Comment by JesperWe** [comment]
Personally I think having both `onChange` and `onInputChange` would be a bit confusing.

A boolean prop `selectTriggersOnChange` (default = `true` for backward compat) seems like a better DX.

**Comment by lgordey** [comment]
I made PR to base select, is it ok?
- [ ] https://github.com/react-component/select/pull/178
- [ ] here will be PR to `ant`

**Comment by damiangreen** [comment]
is this not merged yet? just hit this problem

**Comment by JesperWe** [comment]
It should be, 2.10.0 changelog says "AutoComplete supports to listen to search events by onSearch", but then it links to a completely unrelated issue ;-)

**Comment by benjycui** [comment]
cc @yesmeck @RaoHai

**Comment by yesmeck** [comment]
Use `onSearch` instead of `onChange`.

**Comment by chenghaohao** [comment]
@yesmeck  老哥，有没有考虑过这种情况，如果onSearch 用debounce延迟了几百毫秒执行，然后输入框输入值后快速的回车执行某一项操作，需要带上input的value，这种情况获取的input的value就是空的。onChange可以满足，保存input的value到state，但是选择option的时候也会触发这个onChange，option的key和input的value又是不同的值。。所以就比较尴尬。。选择某一项，然后回车就会导致bug。。。

**Comment by yesmeck** [comment]
@chenghaohao 没看懂，给个 demo ？

**Comment by chenghaohao** [comment]
@yesmeck  谢老哥回复，我找到了一种处理方法setTimeout(() => this.onChange(opt.props.value2), 0);
在onSelect的时候在异步调一次onChange，暂且处理了选择Autocomplete option 时同时触发onChange的问题。 因为我需要输入框的字符串，option的key是数据的id，选择的option的时候，我保存的这个input值会被这个id给覆盖掉。
