### ISSUE TITLE
TreeSelect loadData "Cannot read property 'then' of undefined"

### ISSUE THREAD

**Issue by zpczpc** [ant-design/ant-design#5612]
### Version
2.8.2

### Environment
系统win10、浏览器谷歌

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
动态添加数据时报错

### What is expected?
解决此问题

### What is actually happening?
无

**Comment by imrobin** [comment]
need demo

**Comment by yesmeck** [comment]
Close since no demo is provided.

**Comment by Dylanwooo** [comment]
you need to return a promise object like this `return new Promise((resolve) => { ... }`

**Comment by eduludi** [comment]
Here is an reproducible demo: 

https://codepen.io/eduludi-the-encoder/pen/rvZbXR

The component seems to work fine, but when you click on a expand arrow, show an error in the console: `"Cannot read property 'then' of undefined"`, as @ONEGISER mentioned.

**Comment by yesmeck** [comment]
> you need to return a promise object like this return new Promise((resolve) => { ... }

@eduludi

**Comment by eduludi** [comment]
Thank for your answer @yesmeck. Would be nice to have this info in the documentation for loadData.

**Comment by duzliang** [comment]
By return a promise object has resolved this problem, But there is another problem that the treeDate is assembled in right form, but the tree node isn't expand when I click the arrow

**Comment by Mathround** [comment]
> you need to return a promise object like this `return new Promise((resolve) => { ... }`

不错，完美解决我的问题，不知为啥官方demo却没这个警告提示
