### ISSUE TITLE
[http://new-issue.ant.design/] Issues is not working.

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5614]
https://www.dropbox.com/s/rh7d2jipdc977qa/Screenshot%202017-04-04%2017.55.44.png?dl=0

**Comment by yesmeck** [comment]
Seems like you reach the github api rate limiting.

**Comment by plandem** [comment]
Yes, but it's my first issue today! And I can't even post issue via you form, because you don't catch exception for autocomplete api requests. But I can create issue manually via github, that will be auto-closed, because I don't know format of issue :(

**Comment by benjycui** [comment]
> Seems like you reach the github api rate limiting.

Maybe we can add GitHub auth for new-issue.ant.design ?
