### ISSUE TITLE
[new-issue.ant.design] Bug! Autocomplete Issues is not working

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5617]
### Version
2.9.0

### Environment
osx, chrome

### Reproduction link
[https://www.dropbox.com/s/rh7d2jipdc977qa/Screenshot%202017-04-04%2017.55.44.png?dl=0](https://www.dropbox.com/s/rh7d2jipdc977qa/Screenshot%202017-04-04%2017.55.44.png?dl=0)

### Steps to reproduce
after some time http://new-issue.ant.design/?repo=ant-design throws a lot of exception in console

### What is expected?
working

### What is actually happening?
not working

**Comment by plandem** [comment]
My api rate limit at github is fine - I got this at my FIRST issue at github for today. Looks like your autocomplete hit the api rate limit

**Comment by yesmeck** [comment]
Should be ok now.
