### ISSUE TITLE
[Feature discussion] Table and "autoheight" respecting parent's container height

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5618]
### What problem does this feature solve?
It would be nice to have ability to set default pageSize equal to number of rows that will fit to parent container.

### What does the proposed API look like?
```jsx
<Table pagination={{pageSize: true}}/>
```

**Comment by afc163** [comment]
Try `<Table dataSource={this.state.data} pagination={{ pageSize: this.state.data.length }} />`?

**Comment by plandem** [comment]
nope! I have 10k records. I want to get something like 'responsive' table - that will auto set pageSize

**Comment by afc163** [comment]
Could you describle your requirememt more specified?

**Comment by plandem** [comment]
@afc163, ok will try again:

1. E.g. we have 10k records
2. At my screen resolution table will fit pageSize=10 without any scrollbars
3. At other computer with HD display table will fit pageSize=25 without any scrollbars.

It would be cool to have ability to automatically set pageSize  equal to number of rows that table will fit without any scrollbars. So it will not depend on screen resolution..

**Comment by afc163** [comment]
You mean the `pageSize `number will adapt to screen height responsively? I think it is better to be a HOC feature.

**Comment by plandem** [comment]
Yep - default pageSize that will adapt to screen height responsively.

**Comment by afc163** [comment]
I suggest you do it in upper Component, it is to complex and special requirement for a basic component.
