### ISSUE TITLE
打包后的文件很大，用了babel-plugin-import 还是很大

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#5626]
### Version
2.9.0

### Environment
chrome 

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
{
  "presets": [
    "react",
    "es2015"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ],
    "transform-object-rest-spread",
    "transform-object-assign"
  ]
}

### What is expected?
 打包后缩小体积

### What is actually happening?
很大 高达12M

**Comment by yesmeck** [comment]
自己分析下吧 https://github.com/webpack/analyse

**Comment by guoxiangwen** [comment]
上传的json文件是什么文件呢？

**Comment by yesmeck** [comment]
`webpack --profile --json > stats.json`

**Comment by guoxiangwen** [comment]
![image](https://cloud.githubusercontent.com/assets/7627191/24696381/dee4ff28-1a1b-11e7-8efa-3b8377ee0d96.png)
分析后 发现还是antd没有按需加载，我用了import插件的，什么地方出问题了呢 可能

**Comment by guoxiangwen** [comment]
补充，好奇怪，我不把antd放在vendors 打包出来就变小了。什么原因

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5025#issuecomment-282642242
