### ISSUE TITLE
Enable noImplicitAny in tsconfig.json

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#5627]
There are many implicit `any` types in our codebase, we should give these variables a appropriate type declaration for better TypeScript support.

Ref: https://github.com/ant-design/ant-design/pull/5609#discussion_r109763481

---

If someone is interested in this issue, just reply this issue which component you are going to handle:

* [x] back-top https://github.com/ant-design/ant-design/pull/6835
* [x] carousel
* [x] dropdown
* [x] input
* [x] message
* [x] progress
* [x] spin
* [x] tag
* [x] tree-select
* [x] badge
* [x] cascader
* [x] form
* [x] input-number
* [x] modal
* [x] radio
* [x] steps
* [x] time-picker
* [x] upload
* [x] affix
* [x] breadcrumb
* [x] checkbox
* [x] grid
* [x] layout
* [x] notification
* [x] rate
* [x] timeline
* [x] version
* [x] alert @bang88  https://github.com/ant-design/ant-design/pull/5836
* [x] anchor
* [x] button
* [x] col
* [x] icon
* [x] locale-provider
* [x] pagination
* [x] row
* [x] switch
* [x] tooltip
* [x] calendar
* [x] collapse
* [x] mention
* [x] popconfirm
* [x] select
* [x] table
* [x] transfer
* [x] auto-complete
* [x] card
* [x] date-picker
* [x] menu
* [x] popover
* [x] slider
* [x] tabs
* [x] tree

**Comment by bang88** [comment]
Any updates ?

**Comment by bang88** [comment]
```sh
11 function getTargetRect(target): ClientRect {
                          ~~~~~~

components/affix/index.tsx(11,24): error TS7006: Parameter 'target' implicitly has an 'any' type.
```
source code
```tsx
function getTargetRect(target): ClientRect {
  // this check is for SSR ?
  return target !== window ?
    target.getBoundingClientRect() :
    { top: 0, left: 0, bottom: 0 };
}
```

**Comment by benjycui** [comment]
> this check is for SSR ?

Yep

**Comment by bang88** [comment]
Should be provide a function to do this work. Don't check target is window.
We just need to know the current environment is server or client ?

**Comment by yesmeck** [comment]
canUseDom? https://github.com/react-component/util#domcanusedom

**Comment by bang88** [comment]
Yep, some thing like this.

**Comment by benjycui** [comment]
If someone is interested in this issue, you can reply here that which component you are going to handle:

See: https://github.com/ant-design/ant-design/issues/5627#issue-219446706

**Comment by chenshuai2144** [comment]
I can modify these what I should do?From which branch to start!

**Comment by 0x80** [comment]
I'm new to typescript, but an important reason to use it is having strict types. While this issue is being worked on, is there maybe a way to use noImplicitAny in my own app code but disable it for antd components at the same time?

**Comment by yesmeck** [comment]
@0x80 You can set `skipLibCheck` to `true` in tsconfig.json.

**Comment by 0x80** [comment]
@yesmeck Awesome! thanks

**Comment by yesmeck** [comment]
Will enable this option in antd 3.
