### ISSUE TITLE
demo里面用二个date分开的组成的daterange问题，选择之后，在这之间的时间范围没有颜色

### ISSUE THREAD

**Issue by killdada** [ant-design/ant-design#5630]
### Version
2.9.0

### Environment
chrome

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end](https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end)

### Steps to reproduce
选择了颜色范围之后

### What is expected?
范围之内应该跟rangerpicker有个背景色，不然不明确知道选择的是哪一段时间范围

### What is actually happening?
没有背景是

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
It seems that it's impossible for DatePicker until we add new feature to it.

Maybe we can replace DatePicker with RangePicker like this http://react-component.github.io/calendar/examples/start-end-range.html

**Comment by rdewolff** [comment]
+1 for english, overall :)

**Comment by benjycui** [comment]
Close, background highlight is impossible for `DatePicker`, just use RangePicker.
