### ISSUE TITLE
transfer 搜索时 不能正确显示搜索结果

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#5631]
### Version
2.9.0

### Environment
codepen环境

### Reproduction link
[http://codepen.io/yuecjnadt/pen/dvLRPm?editors=0010](http://codepen.io/yuecjnadt/pen/dvLRPm?editors=0010)

### Steps to reproduce
搜索222时，搜索出一个结果但是不显示

### What is expected?
显示content222

### What is actually happening?
空的显示框

---
定位后发现是react-lazy-load的问题
https://github.com/loktar00/react-lazy-load/blob/master/src/utils/inViewport.js#L30 这行代码在搜索时 定位到的element还未重新渲染（还是未搜索时的dom节点）

**Comment by benjycui** [comment]
Try `Transfer[lazy=false]`

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
@afc163 I think that we can just remove `Transfer[lazy]` in `antd@3.0`, it is usless and buggy.

And we should try https://github.com/ant-design/ant-design/issues/3789 to improve performance.

**Comment by wangtao0101** [comment]
@benjycui I try lazy=false，but it will cause performance problem.

**Comment by benjycui** [comment]
Oops....

**Comment by afc163** [comment]
Let's try to fix this first.
