### ISSUE TITLE
autocomplete: 使用 allowClear 时组件渲染出错

### ISSUE THREAD

**Issue by pinggod** [ant-design/ant-design#5634]
### Version
2.9.0

### Environment
macOS 10.12 / Chrome 57

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/1784ea7](https://riddle.alibaba-inc.com/riddles/1784ea7)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/1784ea7

### What is expected?
clear 的图标在输入框之内

### What is actually happening?
clear 的图标在输入框之外

**Comment by pinggod** [comment]
<img width="259" alt="2017-04-05 16 22 14" src="https://cloud.githubusercontent.com/assets/9530963/24696890/c52b0094-1a1d-11e7-8626-3f6bee306624.png">

**Comment by RaoHai** [comment]
😆

**Comment by RaoHai** [comment]
最好把 demo 地址换一下，不要用内网地址。。

**Comment by phongm** [comment]
有没有人遇到跟我一样的问题：数据总是慢一拍，第一次不会出下拉框，第二次出第一次的结果，第三次出第二次的结果
