### ISSUE TITLE
Error: The value/defaultValue of DatePicker or MonthPicker must be a moment object after `antd@2.0`, 

### ISSUE THREAD

**Issue by tailorsira** [ant-design/ant-design#5637]
### Version
2.7.4

### Environment
win10, chrome56.0.2924.87 (64-bit)

### Reproduction link
[http://codepen.io/anon/pen/ZeZaqJ?editors=001](http://codepen.io/anon/pen/ZeZaqJ?editors=001)

### Steps to reproduce
when I set defaultValue={moment().fromNow()}

### What is expected?
the page can display the current date

### What is actually happening?
An error occurred:  The value/defaultValue of DatePicker or MonthPicker must be a moment object after `antd@2.0`

---
if I set the defaultValue={moment()}, there is no error

**Comment by afc163** [comment]
`moment().fromNow()` is a string, not a moment instance.

**Comment by tailorsira** [comment]
so If I want set defaultValue is an hour ago from now, how to do it? Thank you.

**Comment by afc163** [comment]
Operate your moment instance by http://momentjs.com/

**Comment by tailorsira** [comment]
Got it, thank you.
const startTime = moment()
startTime.startOf('hour').fromNow()

<DatePicker  defaultValue={startTime}  />

**Comment by tailorsira** [comment]
Got it, thank you.
const startTime = moment()
startTime.startOf('hour').fromNow()
<DatePicker defaultValue={startTime} />

**Comment by tailorsira** [comment]
Got it, thank you.
const startTime = moment()
startTime.startOf('hour').fromNow() <DataPicker defaultValue={startTime} />
