### ISSUE TITLE
IE中Affix组件无效

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#5638]
使用自己搭建的webpack+react+antd环境，出现问题如下
[antd中的affix组件依赖什么特性？IE中报“调用的对象无效”](https://segmentfault.com/q/1010000008954441)

然后在官方推荐的脚手架之一reactSPA中，添加一个Affix组件，现象也是在chrome中正常，在IE中无效果。

环境：windows10+IE11/EDGE

**Comment by yesmeck** [comment]
See https://ant.design/docs/react/getting-started-cn#兼容性
