### ISSUE TITLE
0.10.0-beta27版本的Datepicker自定义样式无效？

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#564]
刚升级组件，Datepicker自定义的style失效了，是出bug了吗？

**Comment by benjycui** [comment]
0.10.0 已经发布 https://www.npmjs.com/package/antd

另外能详细描述下？最好能给出代码。

**Comment by xiao-hai** [comment]
@benjycui 我先升级正式版试一下再说。

**Comment by afc163** [comment]
try `0.10.1`
