### ISSUE TITLE
New demo page proposal

### ISSUE THREAD

**Issue by kvolkovich-sc** [ant-design/ant-design#5641]
### What problem does this feature solve?
Hello!

Recently we release first public version of this project.

https://github.com/OpusCapitaBES/js-react-showroom-client

It allows to write documentation in markdown and run all docs in sandbox with code examples.
It often useful to have possibility to play with components at web page before use it in project.

Do you interested in adding more interactivity to your demo-page?)
I can make it and send you pull-request. Of course it can use your brand styles.

### What does the proposed API look like?
![showroom-demo](https://raw.githubusercontent.com/OpusCapitaBES/js-react-showroom-client/93f035a18e6c35de46bfca299a32708ce9e52c1e/docs/demo.gif)

**Comment by benjycui** [comment]
Thanks, but I think https://github.com/ant-design/ant-design/issues/5140 is good enough.

**Comment by benjycui** [comment]
With CodePen(or something like that), we can even share edited code to others.

**Comment by kvolkovich-sc** [comment]
Maybe you are right =)
