### ISSUE TITLE
Breadcrumb React Router integration is out of date.

### ISSUE THREAD

**Issue by PolyPik** [ant-design/ant-design#5644]
### Version
2.9.0

### Environment
Windows 10, Chrome 57.0.2987.133, react 15.4.2, react-dom 15.4.2, react-router-dom 4.0.0

### Reproduction link
[https://codepen.io/Worlder/pen/MpRRPq](https://codepen.io/Worlder/pen/MpRRPq)

### Steps to reproduce
In the Codepen, click on the 'Home' link and note the output.

### What is expected?
The Route component passes the following props to the component specified in the 'component' prop of the Route component.

* routes
* params
* children

### What is actually happening?
The Route component passes the following props to the component specified in the 'component' prop of the Route component.

* match
* location
* history

---
Either fix the Breadcrumb react router integration for react-router v4.x.x or remove those specific examples entirely from the Breadcrumb section of this website.

**Comment by benjycui** [comment]
We need to make Breadcrumb work with both(react-router@3 react-router@4) and provide two demos for them respectively.

**Comment by plandem** [comment]
I would suggest to remove support for React Router. Breadcrumb must be router agnostic

**Comment by benjycui** [comment]
> Breadcrumb must be router agnostic

I agree.

The old design of Breadcrumb is not ideal:
1. We [add `breadcrumbName` to `ReactRouter.Route`](https://github.com/ant-design/ant-design/blob/55d6d420bf228e9f94f49e57085cb8fa6060e2fc/components/breadcrumb/demo/router.md#en-us), which is not an official property and will make developers confusing(`ReactRouter.Route[breadcrumbName]` is API of `antd.Breadcrumb`).
1. `react-router@4` will not pass `routes` to component, so we cannot [generate `Breadcrumb.Item` automatically](https://github.com/ant-design/ant-design/blob/55d6d420bf228e9f94f49e57085cb8fa6060e2fc/components/breadcrumb/Breadcrumb.tsx#L70-L87).

**Comment by benjycui** [comment]
I will just update demo to show how to work with `react-router@4`, and we need to write more codes.
