### ISSUE TITLE
Feature Request: Vertical Mode/Grid display for CheckboxGroup

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#5645]
### What problem does this feature solve?
Currently, the CheckboxGroup options are always rendered in one single line. I want to have the checkboxes displayed Vertically (or in a grid). 

### What does the proposed API look like?
Add a prop called `mode` that allows you to pass in a string value `horizontal`, `vertical` or `grid-3x3`. Alternatively, you could allow elements to be added into a `CheckboxGroup` in JSX.
```
<CheckboxGroup>
{
	checkBoxOptions.map(option => <Checkbox key={ option.value }>{ option.label }</Checkbox>)
}
</CheckboxGroup>
```

**Comment by afc163** [comment]
You can follow this demo: https://ant.design/components/radio-cn/#components-radio-demo-radiogroup-more 

It is same as CheckGroup.

**Comment by kappa-gooner** [comment]
@afc163 , 
No, `CheckboxGroup` and `RadioGroup` don't seem to work the same way. 
In a `RadioGroup`, we're able to add JSX children; while in the CheckboxGroup, you're having to pass them in as props. There's no ability at the moment to pass the Checkboxes as children or style them.

Please correct me if am wrong.

**Comment by benjycui** [comment]
I am not sure if @ascoders are interested in this issue, to make this work:

```jsx
getFieldDecorator('hobbies')(
  <Checkbox.Group>
    <Row>
      <Checkbox ... />
      <Checkbox ... />
    </Row>
    <Row>
      <Checkbox ... />
      <Checkbox ... />
    </Row>
  </Checkbox.Group>
)
```

**Comment by benjycui** [comment]
Actually, this feature is useful in real world...
