### ISSUE TITLE
In the public and the asstes why can't request a json file

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#5650]
### Version
2.9.0

### Environment
chrome

### Reproduction link
[https://github.com/sorrycc/roadhog#配置](https://github.com/sorrycc/roadhog#配置)

### Steps to reproduce
 无法提供

### What is expected?
请求可以获取本地的json

### What is actually happening?
start 和build json文件都不会被编译 放在public 里面build后会有 但是开发环境还是请求不到！

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/24747283/72a2d352-1aee-11e7-89b1-32eb459bde7b.png)

**Comment by yesmeck** [comment]
Please file issue to https://github.com/sorrycc/roadhog
