### ISSUE TITLE
Select all in multiple select

### ISSUE THREAD

**Issue by abonec** [ant-design/ant-design#5653]
### What problem does this feature solve?
Add option which select or deselect other options in the list.

Or it may be done manually by adding <Option value='select_all'>All</Option>
and programmer can add custom logic to onChange if you pass some select object to onChange function:

onChange(event, select) {
 if(event == 'select_all') {select.select_all()}
}

Demo is here:
http://files.topmission.ru/tmp/out-1.ogv

### What does the proposed API look like?
<Select selectAll={true} ... >...
or
onChange(event, select) {
 if(event == 'select_all') {select.select_all()}
}

**Comment by yesmeck** [comment]
You can implement this feature by yourself, see http://codepen.io/yesmeck/pen/pemrBV?editors=0010

**Comment by abonec** [comment]
Ok but it looks like a workaround.

**Comment by yesmeck** [comment]
It works any way.
