### ISSUE TITLE
turn off badges in multiple select

### ISSUE THREAD

**Issue by abonec** [ant-design/ant-design#5654]
### What problem does this feature solve?
If select list is very large when selecting all elements will lead to expanding select to enormous size. It will be better if Select will be with just preselected placeholder and selected items will be only in dropdown list like in following demo:
http://files.topmission.ru/tmp/out-1.ogv

### What does the proposed API look like?
<Select mode="multiple" onlyPlaceholder={placeholderContainer}.... >

**Comment by yesmeck** [comment]
Hello @abonec, you can use Dropdown to implement the same component in your video.

**Comment by abonec** [comment]
@yesmeck I need all of the functionality from `Select` (multi-selection, search within list etc) that `Dropdown` doesn't implement.
All I need from `Dropdown` that `Select` don't have is ability to be size-fixed

**Comment by afc163** [comment]
I think it is better to customize it as your high-order component. We won't official supply it now.

**Comment by abonec** [comment]
how it can be implemented using hoc?
