### ISSUE TITLE
ThemeProvider

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5656]
## Usage

Change theme globally:

```jsx
<ThemeProvider 
  theme={{
    ...
  }}
>
  <Button>Hello</Button>
</ThemeProvider>
```

Only override theme variables for specific element, and these variables will be merged with global vairables:

```jsx
<Button theme={{ ... }}>Hello</Button>
```

### Implementation

This feature means that we need to introduce CSS-in-JS solution to `antd`

CSS-in-JS solutions: https://github.com/MicheleBertoli/css-in-js

* To implement ThemeProvider, we must choose a CSS-in-JS solution which can get JS variable dynamically.
* To make it easier to migrate to this CSS-in-JS solution, it must support:
  * Pseudo class such as hover & focus style, because we don't want to set these styles by events.
  * Pseudo elements, for components like Icon & Calendar.
  * CSS Selector Combinators such as `+` & `>`, actually, we had used `+` in Checkbox, etc.
  * Features like auto-prefixer will be better.
  * Media query

CSS Selectors https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
> CSS Selectors are important to `antd`, because it can simplify JavaScript's code

For compatibility, this CSS-in-JS solution should support server-side rendering, because SSR is an important feature of `antd`.

### Compatibility

Developers may use `.ant-btn` to override `antd`'s default style, so we need to reserve these `className`s, even though we don't need them. And this also means that we cannot use inline styles, e.g. `material-ui`

**Comment by benjycui** [comment]
This feature is low-priority.

**Comment by NE-SmallTown** [comment]
Maybe [this](https://github.com/javivelasco/react-css-themr) helps?

**Comment by benjycui** [comment]
@NE-SmallTown We want to set `fontSizeBase`  or `fontSizeLg` variable dynamically in runtime. And it seems that `react-css-themr` doesn't support this use case.

> To implement ThemeProvider, we must choose a CSS-in-JS solution which can get JS variable dynamically.

**Comment by NE-SmallTown** [comment]
@benjycui You mean something like [this](https://github.com/styled-components/styled-components)?

**Comment by bang88** [comment]
IMO. I don't want set Theme separately.i think most use case are update the Root Component then apply the new Theme for children Components. Maybe change the container's className can fit our needs.

**Comment by benjycui** [comment]
The reason for ThemeProvider is that we can modify theme variables dynamically, and we don't need to introduce build process while defining theme.

The reason for `Button[theme]` and something like that, is we don't need to expose DOM structure to developers. Anytime a developer want to modify some styles of a component, we just expose corresponding theme variables. e.g. we want to set the height of TabPane's content

Before:

```css
.ant-tabs-content,
.ant-tabs-tabpane > div {
  height: 100%;
}
```

After:

```jsx
<TabPane theme={{ tabPaneContentHeight: '100%' }} />
```

This is what I want, to hide DOM structure and a pile of `className`s to developers. What they need to know is a semantic variable.

**Comment by bang88** [comment]
This can handle by overwrite ant's css. and it's easy to use.  😄

**Comment by benjycui** [comment]
> This can handle by overwrite ant's css. and it's easy to use. 😄

Nope, in some case, we don't need to override all the TabPane's content height. And it's not easy for  non-professional front-end engineer(e.g. full-stack engineer in Ant Financial) to handle this..

And this will improve the abstraction of a component:

> to hide DOM structure and a pile of classNames to developers

**Comment by bang88** [comment]
I see. that's your use case.

**Comment by paranoidjk** [comment]
ThemeProvider
LocaleProvider
PlatformProvider

whats next.... why not combine those context all in one ?

**Comment by afc163** [comment]
CompositeProvider

**Comment by paranoidjk** [comment]
Seriously, If we decide to make a ThemeProvider,  something like `CompositeProvider` may be better for usage..

And, 
@benjycui 
>  Anytime a developer want to modify some styles of a component, we just expose corresponding theme variables. e.g. we want to set the height of TabPane's content

In my opinion, `theme variable ` should keep as less as possible, since those `design token` won't increase with code base.

override style may be a better and more freely method,  otherwise there have to be a bunch of theme variable in antd , and one need to take a deep look in the doc,  in order to find about what props is used to change what style.

**Comment by afc163** [comment]
I am just kidding for `CompositeProvider`, it might be a solution for indepent package but inappropriate in antd.

**Comment by NE-SmallTown** [comment]
IMO,maybe we can think about some plugin mechanisms such as `webpack-plugins`,`babel-plugins` in antd.So wen can turn the power of enhancement to more developers rather than us.Maybe you can call it "antd ecosystem".

**Comment by bang88** [comment]
> Use `style `props instead
 ```jsx
<TabPane theme={{ tabPaneContentHeight: '100%' }} />
```
or wrap its content in a div container then style it.

I think this is not Theme things. just some customize can't use it every. if so they can write a custom Component do these things. otherwise.

1. Style problem using style resolve it.
2. Maybe we can extract ant theme and icon in a separate package 

Its not so hard to do these things. Full Stack dev need to know some basic css. or they are not full stack dev 😄

**Comment by NE-SmallTown** [comment]
> Use styleprops instead

If this can resolve it,it can't be called *theme*,AFAIK,theme is about the whole component's style.e.g.:

```
A component we want to add in lib:

render () {
  return (
    <div id="1">
       <div id="2"><span id="3"></span></div>
       <div id="4">
    </div>
  );
}
```

So,if we call it *theme*,we can change all style of the component(i.e. 1,2,3 and 4....).If we just use `style`,you probably mean the outermost wrap(i.e. id=1 above).Of course you can provide all styles such as `_1style`,`_2style`,`3_style`... to developers,but that's too inconvenient and bad.This is the reason why *theme* exists.

**Comment by benjycui** [comment]
> > to hide DOM structure and a pile of classNames to developers

> I see. that's your use case.

@bang88  It's not a use case, but a design principle of components.

**Comment by plandem** [comment]
Maybe some ideas from here: https://github.com/andreypopp/rethemeable

**Comment by jbe456** [comment]
FYI, we've been successfully using https://github.com/rtsao/styletron/ for our library to integrate dynamic themed components. 

We use it like this (we have more utils, but this is to give you an idea):
```
import {injectStylePrefixed} from 'styletron-utils';

...

<div className={injectStylePrefixed(styletronClient, theme.style())}>
  ...
</div>
```

But there are other ways to integrate it (cf their main page)

NB: I'm not related to that library, just a consumer, and also interested in using ant-design once it will integrate dynamic theming :-)

**Comment by neekey** [comment]
[*A Unified Styling Language*](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660)  This article may provide more thoughts about CSS-in-JS

**Comment by neekey** [comment]
Also, I am quite against overwriting CSS selectors, because it will end up with a lot of `!important`. So I try to avoid overwrite Antd's style class name directly. I think the next version of anted should not recommend user to use this way to customise as well, or antd should just use things like css module to hide its class names.

For the aspect of totally control (that's actually always our goal in software development), a way of overwriting style without worrying about the priority issue will be one of the goal (for example, inline-style, the last style applied wins the game).

**Comment by neekey** [comment]
Another proposal, can we use `rem` instead of `px` in the next version? the hard coded `px` is anti-design for theming. For example, in the current theming system, variables does not comply with each other well if you change the `font-size-base` to a big value due to the hard coded button `height`:

![image](https://user-images.githubusercontent.com/499870/28253393-e2f5f614-6ae6-11e7-9feb-fd6a40b0e7fd.png)

you can try it [here](https://insiight.github.io/ant-design-theme-builder/#/button)

**Comment by zunder** [comment]
What is the current state on the whole theming topic as for now?

**Comment by yesmeck** [comment]
After tried styled-components, we decide keep using less in antd 3, it's too many works to convert current less code to js, and it's a breaking change to those people who overriding style with less variables. Also, styled-components has some downsides like leaking of source map.

Any way, themes can be implement through building multiple versions of css.

**Comment by rgbkrk** [comment]
Would people consider making the base LESS variables be overridable with [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) [\[en\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) [\[zh\]](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_variables)?

```css
:root {
 --ant-main-color: var(--default-ant-main-color);
}
```

Where the `--default-ant-main-color` is generated from the current LESS setup, yet the components rely on the `--ant-main-color`

**Comment by EugeneHuang95** [comment]
I just find the color picker in the official site‘s footer can change the theme color dynamically.
how it works ?

**Comment by jbe456** [comment]
It seems like they use the "browser" integration from less:

```
<link rel="stylesheet/less" type="text/css" href="styles.less" />
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.0.0/less.min.js" ></script>
```

cf http://lesscss.org/

**Comment by AndrewEastwood** [comment]
any movement around this one? because that'd be a really essential feature modifying in a modern way in runtime (not build phase)

**Comment by shengbeiniao** [comment]
mark，need css3 variable

**Comment by xiaoxiangmoe** [comment]
[CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for theme is great.

**Comment by medihack** [comment]
Yes, we really need a good solution. Things like dynamic theme switching is state of the art and most of the modern UI libraries have a solution for this now or at least something on the horizon. Some switched to CSS in JS frameworks, but (unfortunately) I don't see this move happen in Ant Design (I really appreciate how Emotion handles this). So we need some other solution and the easiest way would be to introduce CSS custom properties (aka CSS variables). It's a bit like just replacing the LESS variables with CSS properties. The downside would be to lose IE11 support, but the upside is worth it in my opinion (and I work in healthcare where IE11 is still a thing).

**Comment by luokebi** [comment]
Is there a plan for this feature? Four years have passed. @afc163 @benjycui

**Comment by pavolgolias** [comment]
Recently we had similar use case - we would like to implement visual customization per user. User can set up preferred system colors. So we need to change `primary-color` programmatically after application is loaded and request for users settings is finished.

**Comment by VAllens** [comment]
[CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for theme is great.

Is there a plan for this feature? Four years have passed. @afc163 @benjycui

**Comment by arvinxx** [comment]
6年前的想法在v5里实现了🤣

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/issues/38671
