### ISSUE TITLE
spin 置为false后仍然不消失

### ISSUE THREAD

**Issue by TracyDa** [ant-design/ant-design#5664]
spin初始化的时候置为true，然后程序查询数据，查询几次后，会根据查询次数大于5或者查询返回码成功来判断是否停止载入。

```
<Spin tip="正在准备数据" size="large" delay={500} spinning={ !(this.state.is_spin == 0 || this.state.time > 5) }>
</Spin>
```

<img width="199" alt="2017-04-07 5 10 11" src="https://cloud.githubusercontent.com/assets/16920793/24794604/cb0876ee-1bb8-11e7-8d18-dea5929c2921.png">

spin背景的模糊效果已经消失了，但是spin的文字和旋转图案还在，而我在debug的时候发现spinning的值已经是false了，哪里出问题了吗？

其它地方用的spin没有出现过这个问题。

**Comment by TracyDa** [comment]
自己解决了，

```
<Spin tip="正在准备数据" size="large" delay={500}
          spinning={ !(this.state.is_spin == 0 || this.state.time > 2) }>
        <TableElement dict={d0} content={this.state.basic_data} labels="基本信息"/>
        <TableElement dict={d0} content={this.state.basic_data} labels="基本信息"/>
 </Spin>

```

我的spin里面有多个组件，就会出现这种情况：

<img width="370" alt="2017-04-07 6 20 29" src="https://cloud.githubusercontent.com/assets/16920793/24796267/eb955f48-1bbe-11e7-8558-994a0711585e.png">

里面只有一个的时候就没有问题。

**Comment by afc163** [comment]
try http://new-issue.ant.design/?repo=ant-design

**Comment by weiweian90** [comment]
使用delay属性时，如果spinning为true时，多次触发Spin内部的componentWillRecieveProps时，会创建多个定时器， 导致最后spinning为false时，其实Spin内部的定时器还没执行，最后Spin内部的spinning实际上是为true
