### ISSUE TITLE
upload 上传文件时，Cascader控件出错

### ISSUE THREAD

**Issue by funyaliga** [ant-design/ant-design#5666]
### Version
2.5.2

### Environment
mac、win, chrome

### Reproduction link
[http://codepen.io/funya/pen/wJbOwY?editors=0010](http://codepen.io/funya/pen/wJbOwY?editors=0010)

### Steps to reproduce
![avatar](https://raw.githubusercontent.com/funyaliga/js/master/linshi/bug2.gif)

upload和Cascader组件都在formItem里面， 
upload上传比较大的文件（我测试是用8MB的文件），
文件上传中时
Cascader级联选择第二级会立马闪掉选不中。

### What is expected?
Cascader能选第二级

**Comment by SherryWuWu** [comment]
遇到了同样的问题，新版本上有解决吗？

**Comment by SherryWuWu** [comment]
也遇上一样的问题，upload跟Cascader一起用会出错，版本是2.8.3的

**Comment by afc163** [comment]
Reinstall node_modules.
