### ISSUE TITLE
Option to hide header of Calendar

### ISSUE THREAD

**Issue by reflog** [ant-design/ant-design#5668]
### What problem does this feature solve?
Right now there is no way (that I can see) to hide year/month selector on top of the calendar.
That could be very useful.

### What does the proposed API look like?
Adding a prop like `headerHidden={true}`

**Comment by afc163** [comment]
I suggest to hide header by customizing `className` now.

**Comment by afc163** [comment]
http://codepen.io/anon/pen/JWQgMB?editors=0110
