### ISSUE TITLE
Table able to select all across pagination

### ISSUE THREAD

**Issue by Far3t** [ant-design/ant-design#5669]
### What problem does this feature solve?
Being able to select every rows of the table, even though there is a pagination.

### What does the proposed API look like?
I know I can make a custom select but I think, it could be a better option to implement it into antd directly.
I do not have time for now to look into the code and make a PR, I just would like to know if this is an option that can be worth considering for you? or not?

**Comment by benjycui** [comment]
You can generate selected keys when users click select all button.

It's a use case instead of a feature, for antd cannot know what "all" means in your application. All data that had load? Or all data in database?
