### ISSUE TITLE
能否将jsx和css文件分开？

### ISSUE THREAD

**Issue by hui** [ant-design/ant-design#567]
类似 https://github.com/react-bootstrap/react-bootstrap
将样式文件和jsx分开，我遇到一个问题是想将ant-design集成到 https://github.com/flintjs/flint 时出错，最终将less删掉单独做了一个 https://github.com/hui/ant-design

anyway, 只是一个建议~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#usage-example

**Comment by afc163** [comment]
0.11.0 中将会移出 css 。
