### ISSUE TITLE
Is it possible to use an object as value in Option component?

### ISSUE THREAD

**Issue by beeant** [ant-design/ant-design#5670]
### What problem does this feature solve?
How can I use an Object as value in Option component?
Currently, when I use object as value props in Option component, I got [Object object] after selecting the option.

### What does the proposed API look like?
```javascript
const item = {id: 1, name: "Selecion"};
<Select>
  <Option value={item}>{item.name}</Option>
</Select>
```
or
```javascript
<AutoComplete>
  <AutoComplete.Option value={item}>{item.name}</Option>
</AutoComplete>

```

**Comment by afc163** [comment]
Not supported yet, please trace #2857

**Comment by dickeylth** [comment]
So what's current suggestion? `JSON.stringify`?

**Comment by benjycui** [comment]
Map

```jsx
<Option value={id} />

{
  [id]: value
}
```
