### ISSUE TITLE
ESLint 提示警告 Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by encorehe** [ant-design/ant-design#5673]
Problem description

在终端 输入了 npm update ant 然后发现
浏览器控制台出现警告  Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

warning.js:36 Warning: AnimateChild: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

antd: 2.8.0
React: 15.4.1
Browser: Chrome

**Comment by NE-SmallTown** [comment]
Please care about [react's update](https://github.com/facebook/react/blob/e5ce3fd368fd3022a910550c8b5c9639997d613a/docs/_posts/2017-04-07-react-v15.5.0.md#migrating-from-reactproptypes)
