### ISSUE TITLE
Replace moment by date-fns

### ISSUE THREAD

**Issue by hlehmann** [ant-design/ant-design#5677]
### What problem does this feature solve?
I am using ant.desing and webpack 2.
We recently had to switch from moment to date-fns for the following reasons:
https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189
https://github.com/webpack/webpack/issues/3128

moment is not modularized, and webpack include all locals in builds (~300kb).

### What does the proposed API look like?
Would it be possible to avoid using moment as dependency ?
Date-fns is build using es2015 modules and result to a much smaller package.

**Comment by afc163** [comment]
Actually I like it but it would be a break change. We are still looking up to a offcial solution from moment. #3128 #2373

You can use noParse for extra locales size fow now: https://github.com/ant-tool/atool-build/blob/fb88dfc49cee4d9d38f5d45a7bdd03a183663c2f/src/getWebpackCommonConfig.js#L91

**Comment by hlehmann** [comment]
Yes I also noticed that date-fns is preparing a new release with breaking change. 
Better to wait and see evolution on moment and date-fns

**Comment by afc163** [comment]
close it now

**Comment by d0ruk** [comment]
@afc163 

Any news on this?

Moment is too overkill for my usage, and I can't trim it down even with webpack.

**Comment by hlehmann** [comment]
I am currently waiting for date-fns v2, alpha.0 have just been released.

**Comment by benjycui** [comment]
My answer is nope.

1. Replace `moment` with `date-fns` is a **huge** breaking change
1. After https://github.com/moment/moment/issues/2373 , we can reduce the bundle size even we keep using moment.
1. `moment` is more popular.

**Comment by bkniffler** [comment]
Your referenced issue @benjycui doesn't show any decisions on reducing the bundle size, only some ideas by users and a lot of people stating they changed to date-fns. It might be a breaking change, but momentjs is just not feasible in an es2015 world. I'm totally for replacing moment with date-fns. And for the sake of bundle size and conformity, antd should too.

**Comment by andriijas** [comment]
jquery is also popular @benjycui   :)

there are long time benefits even if it introduces breaking change. It can be added to 3.0 or 4.0

better and consistent API that promotes immutability for example.

Of course even better would be if the most common features of moment and date fns was standardized and introduced in browsers...

Anyway lets start in another end, how much moment does ant really use? Maybe we can make a small util library to manage time and date without moment instead.

**Comment by andriijas** [comment]
I took a quick look in ant 3.0 code, seems like not very much of moment is used in date and time picker, mostly formatting, which is basically drop in replacement in date fns and it could reduce

**Comment by andriijas** [comment]
Either that or if they output timestamp users can supply function for formatting which canuse  whatever library they want to format the output

`<DatePicker display={(value) => whateverFormatter(value)} />`

**Comment by zachguo** [comment]
`moment` is BIG.
<img width="799" alt="screen shot 2017-12-07 at 2 29 34 pm" src="https://user-images.githubusercontent.com/3478203/33741922-1d8bfa3c-db5b-11e7-8bdc-83b8c7ef36de.png">

**Comment by bkniffler** [comment]
@zachguo There is ways to reduce it (`new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /de/),` if you just want 'de' locale for example), but then again, the core on its own is huge. And I'm not a fan of telling the bundler to exclude files instead of just including the stuff you need.

**Comment by andriijas** [comment]
I wish for ant 3.5 or 4.0 to be slimmer. Less external dependencies and not so much more features, it already has a good foundation and now just need to be trimmed. 

There is also Luxon which is a new lib by moment  author.

**Comment by hlehmann** [comment]
Currently date picker and other elements with dates return moment instance instead of pure Date.
It would be great to get directly a Date which is what we get with other date pickers.

Is there any reason to prefer a moment over a Date on `{value, onChange}`?

```
interface Props {
  value:Date
  onChange:(value:Date)=>void
}
```

**Comment by yesmeck** [comment]
I wrote a rfc https://github.com/ant-design/ant-design/issues/8649.

**Comment by xxyuk** [comment]
Here is a good way of replacing Moment.js in Ant Design (Antd) with Day.js to reduce bundle size

https://github.com/iamkun/dayjs/issues/529 detailing how to replace Moment.js with Day.js in 3 simple steps. Bundle size reduced from 65kb -> 4.19 kb.

It works good with me.

**Comment by tylik1** [comment]
` 
plugins: [
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en-gb/)
    ] 

`

This plugin helps to exclude unneeded locales from moment.js

**Comment by ryanscdavis** [comment]
Thanks @tylik1 , this tip helped to cut bundle size down by almost 1MB!

> `plugins: [ new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en-gb/) ] `
> 
> This plugin helps to exclude unneeded locales from moment.js
