### ISSUE TITLE
Keyboard friendly DatePicker component

### ISSUE THREAD

**Issue by mitchelldemler** [ant-design/ant-design#5685]
### What problem does this feature solve?
Issue: current DatePicker component is not very keyboard friendly.

My use case: we need to cater for "power users", who tab through the form and enter everything by typing at a fast pace.

The DatePicker component should be an aid and not a hindrance to users who do not use the mouse when filling out the form.

* Tabbing away from a DatePicker should close the Calendar and focus the next input in the form (tabindex). 
* Tabbing to a DatePicker input should keep focus on the input, so that the user can enter the date manually if they choose.

### What does the proposed API look like?

1. One idea is to remove the input from the Calendar dropdown, and let users type in the input that is first shown on the page: 
![suggestion](http://i.imgur.com/Jt37YrQ.jpg)

Please discuss feedback, and any ARIA standards that could be met.

**Comment by afc163** [comment]
Sorry, no plan to do that, the input inside calendar allow user to input date string manually.

**Comment by mitchelldemler** [comment]
@afc163 okay that's fine, but just to repeat my points:

- Tabbing away from a DatePicker should close the Calendar and focus the next input in the form (tabindex).
- Tabbing to a DatePicker input should keep focus on the input, so that the user can enter the date manually if they choose.

If this isn't possible, the datepicker isn't usable in a form.

**Comment by samsch** [comment]
Also missing is closing the picker with esc key.

@mitchelldemler I'm looking at date pickers to use, but I also need good keyboard accessibility. Unless I find a different picker which has what I need (or is closer), I'll probably need to fork and make these changes. If you also are working or plan to work on this, I'm open to collaborate.

**Comment by mitchelldemler** [comment]
I spent a bit of time trying to get it working, but there were just too many accessibility issues. Under time pressure from my work I implemented https://hacker0x01.github.io/react-datepicker/ and it was very easy to style to look like the antd picker.

**Comment by annjawn** [comment]
I agree, Datepicker has massive accessibility issues which makes it literally un-usable in a form.

**Comment by astrikov-d** [comment]
Agree, ant.design's datepicker is not very keyboard friendly.

@mitchelldemler I understand that you've left your comment long time ago, but can you please give some example how to use react-datepicker with ant.design's `getFieldDecorator`?

**Comment by annjawn** [comment]
Meanwhile, i've created a custom Datepicker that is keyboard friendly and also takes care of the poor performance in large forms. It uses `<Calendar/>`, `<Popover/>` and `<Input/>` components and gives a somewhat bearable datepicker that can be used in a form. It handles `Tab` and `Esc` keys for proper keyboard accessibility inside a form. You must use `trigger: "dateChange"` and `validateTrigger: "onChange"` in the `getFieldDecorator`. It also won't cause performance issue if used inside of a Large `<Form />` component since the `trigger` is `debounced` after a delay, you can change the delay to whatever suits you in [this line](https://gist.github.com/annjawn/66ba488a41883adcecb9b46c8853b5a3#file-customdatepicker-js-L37).

Here it is.

https://gist.github.com/annjawn/66ba488a41883adcecb9b46c8853b5a3

Usage:
```js
import Datepicker from 'components/customDatepicker';

....
//date validation 
checkdate = (rule, value, callback) => {
    if (value) {
      callback();
      return;
    }
    callback('Date is required!');
  };

render(){
     .....
    <Form.Item>
     {getFieldDecorator('dateValue', {
                      validateTrigger: "onChange",
                      trigger: "dateChange",
                      valuePropName: "value",
                      rules: [{ validator: this.checkdate }]            
                    })(                      
                      <Datepicker
                        disabledDate={this.disabledDate}
                        format='MM-DD-YYYY'
                        placeholder='MM-DD-YYYY'   
                      />                      
          )}      
    </Form.Item>
    .....
}
```

**Comment by Gus-vcx** [comment]
This is a bit of a hack, but I was able to use something like this to at least tab in and out of the DatePicker and close with escape key by setting the `open` prop.

```
  componentDidMount() {
    const dateInput = document.getElementsByClassName('ant-calendar-picker-input')
    dateInput && dateInput.length > 0 && dateInput[0].addEventListener('focus', () => {
        this.setState({ open: true })
        this.handleKeyEvents()
    })
  }

  handleKeyEvents = () => {
    setTimeout(() => {
      const input = document.getElementsByClassName('ant-calendar-input')
      input && input.length > 0 && input[0].addEventListener('keydown', (event) => {
        if (event.code === 'Tab' || event.code === 'Escape') {
            this.setState({ open: false })
        }
      })
    }, 500)
  }

  render() {
    return(
      <DatePicker
         ...
         open={this.state.open}
       />
    )
  }
```

**Comment by snax4a** [comment]
> ```js
> import Datepicker from 'components/customDatepicker';
> ```

In your example changing year and month is not working, can you please look into it and help me solve this issue?

**Comment by snax4a** [comment]
@annjawn In your example changing year and month is not working, can you please look into it and help me solve this issue?

**Comment by annjawn** [comment]
@snax4a I’ve actually solved the problem in my project but forgot to update the gist. Will update it today. 👍🏽

**Comment by snax4a** [comment]
@andriijas Nice thanks, do you maybe know if it's possible to have this focus trigger and also able to click outside to close this popover? I am fighting with this but it looks like the only way to close it will be this close button :(

**Comment by andriijas** [comment]
@snax4a wrong mention? :)  hope you figure it out. have a nice day, cheers

**Comment by annjawn** [comment]
Hey @snax4a , yes, focus is tricky I tried really hard and spent a lot of time to make it work but there simply isn't a nice way to do it without changing the internals unfortunately. That's the tradeoff with this. Not sure if the new Ant 4.0 version addresses this. They do have a number of `<Form>` improvements in that version.

**Comment by jailsonpaca** [comment]
I solve this problem with this solution:
`import React, { useState } from "react";
import InputMask from "inputmask-core";
import moment from "moment";
import { DatePicker } from "antd";

function DatePickerComponent({ ...props }) {
  const [value, setValue] = useState(moment());
  const [text, setText] = useState("");
  var mask = new InputMask({ pattern: "11/11/1111" });

  return (
    <DatePicker
      value={value}
      onChange={(e) => {
        if (!e) {
          setValue(null);
          setText("");
        }
      }}
      dropdownClassName="datePicker"
      htmlTitle={{ format: "DD/MM/YYYY" }}
      format="DD/MM/YYYY"
      onKeyDown={(e) => {
        console.log(e.key);
        if (e.key !== "Backspace") {
          const newText = text.concat(e.key);
          setText(newText);
          console.log(newText, mask.paste(newText), mask.getValue());
          if (newText.length === 8) {
            setValue(moment(mask.getValue(), "DD/MM/YYYY"));
          }
        } else {
          const newText = text.slice(0, -1);
          setText(newText);
        }
      }}
      {...props}
    />
  );
}`
