### ISSUE TITLE
InputNumber 不支持 maxLength

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#5686]
### Version
2.9.1

### Environment
···

### Reproduction link
[about:blank](about:blank)

### Steps to reproduce
···

### What is expected?
可支持maxLength

### What is actually happening?
InputNumber 不支持 maxLength

---
InputNumber 不支持 maxLength

**Comment by afc163** [comment]
Why are you need `maxLength`? Try `max`?

**Comment by afc163** [comment]
Try reinstall `node_modules`.
