### ISSUE TITLE
RangePicker给默认值不生效，版本1.x

### ISSUE THREAD

**Issue by qh19940106cheng** [ant-design/ant-design#5688]
### What problem does this feature solve?
给日期控件默认值不生效，格式为yyyy-MM-dd HH:mm:ss

### What does the proposed API look like?
给日期控件默认值，在不升级版本情况下。

**Comment by ddcat1115** [comment]
Default value of RangePicker should be `[string/date, string/date]`, have you set the correct value?

Any way, provide us a reproducible demo is more efficient  http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by qh19940106cheng** [comment]
1.x version no moment, using the defaultValue [string/date, string/date]，but，no effect

**Comment by benjycui** [comment]
> Any way, provide us a reproducible demo is more efficient http://codepen.io/benjycui/pen/KgPZrE?editors=001
