### ISSUE TITLE
TreeSelect 不管点上面的节点还是下面的节点都往 绑定的div方法缩小

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#5689]
### Version
2.9.1

### Environment
win7  chrome版本 59.0.3043.0  

### Reproduction link
http://codepen.io/anon/pen/NpQvPQ?editors=0011
### Steps to reproduce
点击关闭树结构节点时  会向远离绑定div方向移动 导致和输入框中间有空白

### What is expected?
点击关闭树结构节点时  向绑定div方向移动

### What is actually happening?
点击关闭树结构节点时  会向远离绑定div方向移动

**Comment by benjycui** [comment]
感觉应该在树展开或者关闭时，re-align 一下。

**Comment by afc163** [comment]
similar with #5130

**Comment by afc163** [comment]
Try antd latest version and reinstall node_modules.
