### ISSUE TITLE
AutoComplete 组件有办法在输入拼音输入期间能不触发onChange事件不？

### ISSUE THREAD

**Issue by funreading** [ant-design/ant-design#5690]
### Version
2.9.1

### Environment
chrome

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
![avatar](http://wx2.sinaimg.cn/mw1024/69539033gy1fehm53f009j20ax0ergmc.jpg)

如图，在中文输入拼音时，我每敲个字母他都触发了onChange事件

有没办法让他在敲拼音时不触发，直到我空格输入中文后才触发？

**Comment by RaoHai** [comment]
dup and a temporary solution : https://github.com/ant-design/ant-design/issues/4689
