### ISSUE TITLE
在DatePicker中的showTime参数，value和defaultValue设置没有效果，相对应的format就有效果

### ISSUE THREAD

**Issue by Ben07** [ant-design/ant-design#5691]
### Version
2.9.1

### Environment
win10,chrome57

### Reproduction link
[https://codepen.io/Benholic/pen/RpXLoP](https://codepen.io/Benholic/pen/RpXLoP)

### Steps to reproduce
`<DatePicker showTime={{defaultValue:moment('00:00:00','HH:mm:ss')}} format="YYYY-MM-DD HH:mm:ss" />`

### What is expected?
选日期的时候时间为00:00:00

### What is actually happening?
选日期的时候时间为当前时间

---
我看到issue中有人提。回答的大部分是看文档，我不清楚他们自己有没尝试过。
我在版本1.9.1，2.4.3，2.9.1中都按照文档的来写。都没有想要的效果

**Comment by benjycui** [comment]
Similar https://github.com/ant-design/ant-design/issues/2375

**Comment by Ben07** [comment]
@benjycui 那个issue我也看过，给了我一个已经解决的错觉。
不好意思。创建了重复的issue

**Comment by benjycui** [comment]
Found bug, but waiting for https://github.com/ant-design/ant-design/pull/5663

**Comment by funreading** [comment]
请问..这个bug修复大概什么时候能发布(｡•́︿•̀｡)

**Comment by benjycui** [comment]
`2.10.2`
