### ISSUE TITLE
Table not aligned

### ISSUE THREAD

**Issue by wangzhongquan** [ant-design/ant-design#5692]
### Version
2.9.0

### Environment
windows7     chrome 版本 56.0.2924.87

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
在demo-表格中，实例【表格分组】部分，当向下滚动滚动条时，第一列数据高度与其他列不一致

### What is expected?
在demo-表格中，实例【表格分组】部分，当向下滚动滚动条时，第一列数据高度与其他列一致

### What is actually happening?
在demo-表格中，实例【表格分组】部分，当向下滚动滚动条时，第一列数据高度与其他列不一致

---
在包含展开/折叠的表格使用时，也会出这个问题。
有可能的原因是，拼接整个表格的时候，由于出现滚动条，使得第一列的高度与右边各列的高度不一致

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by wangzhongquan** [comment]
@benjycui 
由于这个codepen工具我不太会用保存代码功能，请将下面的代码复制到
 [http://codepen.io/benjycui/pen/KgPZrE?editors=001](url)
中，覆盖它先前已有的所有代码，并执行run，
展开表格中第一列的三个可展开项，滚动到底部，会出现首列未与其他列对齐

所有代码如下
 
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { LocaleProvider, DatePicker, locales, version , Table } = antd;
moment.locale('en');

const obj = {
columns:[{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  fixed: 'left',
  width: 300
}, {
  title: 'Other',
  children: [{
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
    width: 100,
    sorter: (a, b) => a.age - b.age
  }, {
    title: 'Address',
    children: [{
      title: 'Street',
      dataIndex: 'street',
      key: 'street',
      width: 200
    }, {
      title: 'Block',
      children: [{
        title: 'Building',
        dataIndex: 'building',
        key: 'building',
        width: 50,
      }, {
        title: 'Door No.',
        dataIndex: 'number',
        key: 'number',
        width: 100,
      }]
    }]
  }]
}, {
  title: 'Company',
  children: [{
    title: 'Company Address',
    dataIndex: 'companyAddress',
    key: 'companyAddress',
    width: 200,
  }, {
    title: 'Company Name',
    dataIndex: 'companyName',
    key: 'companyName',
    width: 200,
  }],
}, {
  title: 'Gender',
  dataIndex: 'gender',
  key: 'gender',
  width: 60
}],

rows:[{
    key: 1,
    name: 'Joh'+1,
    age: 1 + 1,
    street: 'Lake Park',
    building: 'C',
    number: 2035,
    companyAddress: 'Lake Street 42',
    companyName: 'SoftLake Co',
    gender: '0',
	children: [{
		key: 99,
		name: 'Jo122',
		age: 5,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  },
	  {
		key: 111,
		name: 'Jo12',
		age: 2,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  },
	  {
		key: 112,
		name: 'Jo001',
		age: 8547,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  }
	  ]
  },
  {
    key: 8,
    name: 'Joh8',
    age: 958,
    street: 'Lake Park',
    building: 'C',
    number: 2035,
    companyAddress: 'Lake Street 42',
    companyName: 'SoftLake Co',
    gender: '0',
    children: [{
		key: 399,
		name: 'Jo122',
		age: 5,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  },
	  {
		key: 3111,
		name: 'Jo12',
		age: 2,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  },
	  {
		key: 3112,
		name: 'Jo001',
		age: 8547,
		street: 'Lake Park',
		building: 'C',
		number: 2035,
		companyAddress: 'Lake Street 42',
		companyName: 'SoftLake Co',
		gender: 'M'
	  }
	  ]
	},
	{
	    key: 'ujnh',
	    name: 'Joh8',
	    age: 958,
	    street: 'Lake Park',
	    building: 'C',
	    number: 2035,
	    companyAddress: 'Lake Street 42',
	    companyName: 'SoftLake Co',
	    gender: '0',
	    children: [{
			key: 3949,
			name: 'Jo122',
			age: 5,
			street: 'Lake Park',
			building: 'C',
			number: 2035,
			companyAddress: 'Lake Street 42',
			companyName: 'SoftLake Co',
			gender: 'M'
		  },
		  {
			key: 31511,
			name: 'Jo12',
			age: 2,
			street: 'Lake Park',
			building: 'C',
			number: 2035,
			companyAddress: 'Lake Street 42',
			companyName: 'SoftLake Co',
			gender: 'M'
		  },
		  {
			key: 31612,
			name: 'Jo001',
			age: 8547,
			street: 'Lake Park',
			building: 'C',
			number: 2035,
			companyAddress: 'Lake Street 42',
			companyName: 'SoftLake Co',
			gender: 'M'
		  }
	  ]
    }
  ]
}


class TableMRP extends React.Component {
	  state = { 
			data: [],
			pagination: {}, 
			columns:[],
			loading: false
		  };
		  handleTableChange = (pagination, filters, sorter) => {
			const pager = { ...this.state.pagination };
			pager.current = pagination.current;
			this.setState({
			  pagination: pager,
			});
			this.fetch({
			  results: pagination.pageSize,
			  page: pagination.current,
			  sortField: sorter.field,
			  sortOrder: sorter.order,
			  ...filters,
			});
		  }
	  
	   fetch  = (params = {}) => { 
			this.setState({ loading: true }); 
		 
        
			  this.setState({
          loading: false,
          columns: obj.columns,
          data:obj.rows           
			  }); 
		 
		  }
	  
	   componentDidMount() {
	 	this.fetch({
		 
		});
	  }
		  render() { 
			  return  (
			  <div>  
				  <Table 
					columns={this.state.columns}
					dataSource={this.state.data}
					reloadDataFromUrl={this.componentDidMount}
					bordered 
					scroll={{y: 540 }}
				  />
				</div>
			  )
		  } 
	 }

ReactDOM.render(

      <TableMRP />
			

,  mountNode);

**Comment by LiXinWei1225** [comment]
表格--固定列--表头分组内容布局混乱

**Comment by afc163** [comment]
@ant-design-bot markdown

**Comment by afc163** [comment]
http://codepen.io/anon/pen/OmVWKg?editors=0010

@yesmeck

<img width="802" alt="image" src="https://cloud.githubusercontent.com/assets/507615/25070587/35dd03c2-22d5-11e7-8f36-685e7deffc53.png">
