### ISSUE TITLE
TreeSelect arrow direction always is down

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5693]
### Version
2.9.1

### Environment
OSX, Chrome 57

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-basic](https://ant.design/components/tree-select-cn/#components-tree-select-demo-basic)

### Steps to reproduce
open or close a node in TreeSelect

### What is expected?
arrow direction is different
![1](https://cloud.githubusercontent.com/assets/4329120/24853062/5447641a-1e0c-11e7-8a81-b1db6df514a6.gif)

### What is actually happening?
arrow direction is the same
![2](https://cloud.githubusercontent.com/assets/4329120/24853088/6dc223ee-1e0c-11e7-8343-2fb9f4390ca1.gif)

Do you do that on purpose or it's a bug?

**Comment by afc163** [comment]
#5659 是同一个问题，但是它没有按规范提交报告。
