### ISSUE TITLE
从2.4.1升级到2.9.1报错

### ISSUE THREAD

**Issue by Pines-Cheng** [ant-design/ant-design#5695]
### Version
2.9.1

### Environment
- Mac 
- node：v7.7.3 
- npm:4.1.2

### Reproduction link
[https://github.com/ant-design/ant-design/issues/5694](https://github.com/ant-design/ant-design/issues/5694)

### Steps to reproduce
从2.4.1升级到2.9.1报错

### What is expected?
![image](https://cloud.githubusercontent.com/assets/9441951/24854099/bbec735a-1e0f-11e7-968b-efe6b2dd5605.png)

### What is actually happening?
控制台报错。

---
js部分直接使用的antd.min.js文件，CSS部分引入的index.less做变量覆盖。
链接实在是提供不了，请无视。

**Comment by yesmeck** [comment]
错误栈里没有 antd 请先确认是 antd 的问题吧，不能提供 codepen 的话可以提供一个能重现的 repo。

**Comment by Pines-Cheng** [comment]
回退到2.4.1就好了。
