### ISSUE TITLE
table--fixed columms--Grouping table head layout is not responsive

### ISSUE THREAD

**Issue by LiXinWei1225** [ant-design/ant-design#5697]
### Version
2.9.1

### Environment
google chrome/window 7/react-web

### Reproduction link
[https://ant.design/components/table/#components-table-demo-grouping-columns](https://ant.design/components/table/#components-table-demo-grouping-columns)

### Steps to reproduce
I just visited the page and found the layout problems!

### What is expected?
a better layout responsiveness

### What is actually happening?
the layout is not responding well to the screen size

**Comment by yesmeck** [comment]
Could you upload a screenshot?

**Comment by LiXinWei1225** [comment]
![grouping_table_head](https://cloud.githubusercontent.com/assets/19964970/24891086/327285c8-1ea6-11e7-833b-5a4d4eba77c4.png)

**Comment by LiXinWei1225** [comment]
![grouping_table_head](https://cloud.githubusercontent.com/assets/19964970/24891138/70ace176-1ea6-11e7-9be1-80127f17aafd.png)

**Comment by LiXinWei1225** [comment]
![grouping_table_head](https://cloud.githubusercontent.com/assets/19964970/24891298/75d99544-1ea7-11e7-9094-d54b9516bc1a.png)

**Comment by afc163** [comment]
The scroll.x is `1010` in this demo, I think your screen width is bigger than it. Maybe we can set a larger value @yesmeck
