### ISSUE TITLE
multiple select in Cascader

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5698]
### What problem does this feature solve?
I want to choose multiple leaf children
Now I use TreeSelect to achieve that, I generate every parent TreeNode to be `disableCheckbox`, only the leaf TreeNode can be selected.
But the problem is my PM want that in Cascader style :) :) :)

If you have time~

### What does the proposed API look like?
multiple select in Cascader, only leaf can be selected, when it's selected, the Cascader doesn't hide, only when the user click the blank area, the  Cascader hides.

**Comment by afc163** [comment]
#5026 

You can customzie a multiple select via Dropdown. http://ant.design/components/dropdown
