### ISSUE TITLE
Wrapping a form component

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#5700]
### Version
2.9.0

### Environment
FF 52

### Reproduction link
[https://github.com/megawac/antd-form-issue](https://github.com/megawac/antd-form-issue)

### Steps to reproduce
I've been trying to figure out how to wrap an ant-design form component. I have several Selects that will have the same options, so I wanted to create a SelectWrapper (see snippet below) which passes through the form props to a standard `Select` form component and does something with a separate property.

```js
function ReusableCountrySelect({countries, ...props}) {
  return (
    <Select
      {...props}
    >
      {
        countries.map(c => (
          <Select.Option
            value={c.id}
            key={c.id}
          >{c.name}</Select.Option>
        ))
      }
    </Select>
  );
}
```

### What is expected?
The `ReusuableCountrySelect` to behave similar to a standard form component.

### What is actually happening?
When a user tries to use this `Select` component an error is generated,

> createBaseForm.js:98 Uncaught TypeError: Cannot read property 'onChange' of undefined

despite me passing through the form props to the `Select`. 

This is likely just me misunderstanding something with the Form state lifecycle

---
FYI asked on SO a couple days ago (http://stackoverflow.com/questions/43286302).

**Comment by bang88** [comment]
Please see https://ant.design/components/form/#components-form-demo-customized-form-controls
> Customized or third-party form controls can be used in Form, too. Controls must follow these conventions:
It has a controlled property value or other name which is equal to the value of valuePropName.
It has event onChange or an event which name is equal to the value of trigger.

**Comment by bang88** [comment]
Or replace your react stateless components with 
```jsx

class ReusableCountrySelect extends React.Component {
  render() {
    const { countries, ...props } = this.props;
    return (
      <Select {...props}>
        {countries.map(c => (
          <Select.Option value={c.id} key={c.id}>{c.name}</Select.Option>
        ))}
      </Select>
    );
  }
}
```

**Comment by yesmeck** [comment]
As @bang88 said, Form need controls's ref, but a functional component don't have ref.

**Comment by megawac** [comment]
Thank you for the answer :100:
