### ISSUE TITLE
Modal.confirm onOK not reset loading state when promise reject

### ISSUE THREAD

**Issue by aegisho** [ant-design/ant-design#5705]
### What problem does this feature solve?
when promise is reject， set loading state to false

### What does the proposed API look like?
components/modal/ActionButton.tsx
function onClick
```javascript
this.setState({ loading: true });
        ret.then((...args) => {
          // It's unnecessary to set loading=false, for the Modal will be unmounted after close.
          // this.setState({ loading: false });
          closeModal(...args);
        });
```
add catch function to set loading to false

**Comment by benjycui** [comment]
It works fine in demo https://ant.design/components/modal/#components-modal-demo-confirm-promise

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close for no re-producible demo.
