### ISSUE TITLE
Could you add a less variable for table row hovering color? 新增表格行 hover 背景色 less 变量

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#5706]
### What problem does this feature solve?
I'd like the the background to be light gray, instead of light primary-color, but when I looked up in less-variable I didn't find it. Could you add a less variable for table row hovering color?
thank you and wish your response.
----------------------------
我在使用 Ant Design 时，想要让鼠标悬浮在表格上时，改行变成灰色。但是当我在 less 变量文件中查找时没有找到这个变量，请问你们是否可以添加这个变量，让我可以自定义鼠标悬浮时表格单行背景色？

### What does the proposed API look like?
```less
@table-row-background-hover :  @primary-1;
```

**Comment by kappa-gooner** [comment]
Raised PR #5711 to add the variables.
