### ISSUE TITLE
menu 组件内部使用 a 标签时，应该覆盖掉 a:focus { text-decration: underline } 样式

### ISSUE THREAD

**Issue by pinggod** [ant-design/ant-design#5707]
### Version
2.9.1

### Environment
macOS, chrome 57

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
https://ant.design/docs/react/introduce-cn 
点击顶部导航菜单

### What is expected?
针对 menu 组件内的 a 标签默认不要有下划线，也就是覆盖到默认的 a:focus 样式，之前并没有这个样式

### What is actually happening?
点击 menu 组件内部的 a 标签，会触发  a:focus { text-decration: underline }

**Comment by pinggod** [comment]
<img width="432" alt="2017-04-11 3 27 48" src="https://cloud.githubusercontent.com/assets/9530963/24897639/4bb6fe26-1ecc-11e7-9b36-b8f26aec9725.png">

**Comment by afc163** [comment]
来个 PR 吧。
