### ISSUE TITLE
mention 不支持IE10及以下版本， IE11没试过。

### ISSUE THREAD

**Issue by sunas** [ant-design/ant-design#5708]
### Version
2.9.1

### Environment
mention  不支持IE10及以下版本， IE11没试过。

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
直接调用在IE下可见

### What is expected?
至少兼容到IE9+，不是号称antd可以兼容IE9么。

### What is actually happening?
不支持IE10及以下版本， IE11没试过

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3400#issuecomment-253181445
