### ISSUE TITLE
Missing props in InputNumber component

### ISSUE THREAD

**Issue by whtang906** [ant-design/ant-design#5717]
### Version
2.9.1

### Environment
Not necessary

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx)

### Steps to reproduce
Not necessary

### What is expected?
`parser?: (displayValue: string) => value: number` should be added into `InputNumberProps`

### What is actually happening?
Something missing in `InputNumberProps`

**Comment by afc163** [comment]
You mean `parser`?

**Comment by whtang906** [comment]
Oh, forgot to mention. Yes I mean parser.

**Comment by afc163** [comment]
Could you give us a PR to fix it?

**Comment by whtang906** [comment]
Submitted.
