### ISSUE TITLE
上传组件upload从2.8.1开始，没有调用onchange事件

### ISSUE THREAD

**Issue by xwy55555** [ant-design/ant-design#5719]
### Version
2.9.1

### Environment
win10,chrome最新,

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
基于dva构建工程，用2.8.0时，上传功能正常，之后的版本上传时没有调用onchange事件

### What is expected?
上传时出现进度条，并调用onchange事件。

### What is actually happening?
上传组件upload从2.8.1开始，没有调用onchange事件

---
这个提bug的页面真SB呀。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by TangMonk** [comment]
这样骂人SB不太好吧

**Comment by afc163** [comment]
close for no response

**Comment by kcshan** [comment]
为什么他说sb你们都回答了 我好好说话 中英文换着提issue 你们秒删

**Comment by afc163** [comment]
关你 issue 的是机器人。

**Comment by xwy55555** [comment]
申明一下，大家不要这么玻璃心，好么！ 
我是说提bug的页面SB，并没有攻击人。
因为有的bug确实没法通过一个url来重现。
唉，大家都是要关注问题本身吧！
好歹我花了很多时间去证实这个bug。

**Comment by and80506** [comment]
开源的世界一切都是那么美好，使用开源代码相当于免费获得别人的帮助。这个问题不能解决之前就另想办法。提issue不就是回馈社区么，我从来也不指望为了我修复我提的issue。
