### ISSUE TITLE
RangePicker's `placeholder` prop do not work in version 2.1.0

### ISSUE THREAD

**Issue by klouskingsley** [ant-design/ant-design#5721]
### Version
2.1.0

### Environment
windows10, chrome 57, react v0.14.8

### Reproduction link
[http://codepen.io/klouskingsley/pen/JNPNrx?editors=1111](http://codepen.io/klouskingsley/pen/JNPNrx?editors=1111)

### Steps to reproduce
set an array for `placeholder`

### What is expected?
change the placeholder of RangePicker

### What is actually happening?
RangePicker show the default placeholder

**Comment by afc163** [comment]
I believe it is fixed after 2.5.0, you can upgrade to latest of 2.x.
