### ISSUE TITLE
Menu defaultOpenKeys & defaultSelectedKeys not working with multiple children

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#573]
Sorry, only speak English.

When using the `Menu` component, with the mode 'inline', the `defaultOpenKeys` doesn't work.

The example, http://ant.design/components/menu/#demo-sider, doesn't work when doing it locally, even when exactly copying the example.

Cheers

**Comment by Ehesp** [comment]
Infact, it seems that `defaultSelectedKeys` also does not work for me, when there is multiple Menu items. 

Works (`defaultSelectedKeys`):

```
<Menu mode='inline' defaultSelectedKeys={ ['subscription-plans'] }>
    <Menu.Item key='subscription-plans'>
        <Icon type='unlock' /> Subscription Plans
    </Menu.Item>
</Menu>
```

Does not work:

```
<Menu mode='inline' defaultSelectedKeys={ ['subscription-plans'] }>
    <Menu.Item key='subscription-plans'>
         <Icon type='unlock' /> Subscription Plans
    </Menu.Item>
    <Menu.Item key='something-else'>
        <Icon type='unlock' /> Something Else
    </Menu.Item>
</Menu>
```

Works (defaultOpenKeys):

```
<Menu mode={ mode } defaultOpenKeys={ ['account'] }>
    <Menu.SubMenu key='account' title={ <span><Icon type='setting' />My Account</span> }>
        <Menu.Item key='profile'>Profile</Menu.Item>
	<Menu.Item key='change-password'>Change Password</Menu.Item>
    </Menu.SubMenu>
</Menu>
```

Does not work:

```
<Menu mode={ mode } defaultOpenKeys={ ['account'] }>
    <Menu.SubMenu key='account' title={ <span><Icon type='setting' />My Account</span> }>
        <Menu.Item key='profile'>Profile</Menu.Item>
	<Menu.Item key='change-password'>Change Password</Menu.Item>
    </Menu.SubMenu>
    <Menu.Item key='team-members'>
        <Icon type='team' /> Team Members
    </Menu.Item>
</Menu>
```

**Comment by yiminghe** [comment]
need demo, fork http://jsfiddle.net/yiminghe/a0pzy83a/1/ and add

**Comment by Ehesp** [comment]
Thanks, helped me debug the issue.

Turns out I was wrapping the menu inside a custom Component which uses [Radium](https://github.com/FormidableLabs/radium). Seem Radium is overriding some of your own styling causing it to not work on initial load. Not sure if this is really an issue you should care about, but your call to decide that!

**Comment by lyuehh** [comment]
补充一下，用 [react-css-modules](https://github.com/gajus/react-css-modules) 处理过的也不行，比如

```javascript
CSSModules(XXX, style)  // XXX 包含 menu，用到了 defaultOpenKeys，那 defaultOpenKeys 就不生效
```
给后来的提个醒..

**Comment by motorguo** [comment]
这个坑我从 PC 踩到 `mobile.ant.d` ，现在又踩回 PC
