### ISSUE TITLE
Menu component with OK and reset options

### ISSUE THREAD

**Issue by sashakru** [ant-design/ant-design#5733]
### What problem does this feature solve?
I would like to use [Dropdown](https://ant.design/components/dropdown/) component with Menu and provide two options `OK` and `Reset` buttons (as provided in [Table](https://ant.design/components/table/) example),

after some research I didn't find any mention about this functionality in Dropdown or Menu component api.

### What does the proposed API look like?
This is code that are used in Table component:
```
<FilterDropdownMenuWrapper className={`${prefixCls}-dropdown`}>
        <Menu
          multiple={multiple}
          onClick={this.handleMenuItemClick}
          prefixCls={`${dropdownPrefixCls}-menu`}
          className={dropdownMenuClass}
          onSelect={this.setSelectedKeys}
          onDeselect={this.setSelectedKeys}
          selectedKeys={this.state.selectedKeys}
        >
          {this.renderMenus(column.filters)}
        </Menu>
        <div className={`${prefixCls}-dropdown-btns`}>
          <a
            className={`${prefixCls}-dropdown-link confirm`}
            onClick={this.handleConfirm}
          >
            {locale.filterConfirm}
          </a>
          <a
            className={`${prefixCls}-dropdown-link clear`}
            onClick={this.handleClearFilters}
          >
            {locale.filterReset}
          </a>
        </div>
      </FilterDropdownMenuWrapper>
```

As possible api we could provided some props on Menu component that will provide OK and Reset functionality out of the box `<Menu showOkBtn showResetBtn />`

**Comment by plandem** [comment]
Popover with Menu + Buttons?

**Comment by sashakru** [comment]
@plandem I'm not completely sure about right naming (I'm only started to work with antd) but I think it is `Dropdown` component that get `Menu` component as a `overlay` prop ,
 take a look at [Table](https://ant.design/components/table/#components-table-demo-reset-filter) example, `Name` column have a filter with `Ok` and `Reset`buttons.

**Comment by plandem** [comment]
Actually issues are for real bugs/feature requests. As I said, you can get it via Popover with Menu + Buttons

**Comment by sashakru** [comment]
I could be very useful if you can provide this kind of functionality out of the box.

**Comment by benjycui** [comment]
Agree with @plandem , and I don't think this should be added to `antd`, it's easy to implement by developers and not a common use case.
