### ISSUE TITLE
getFieldDecorator(xxx)后面加上其他内容，会导致无法获取到输入值

### ISSUE THREAD

**Issue by iamhanson** [ant-design/ant-design#5734]
### Version
2.9.1

### Environment
MACOS

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
<FormItem
              {...formItemLayout}
              label="日活用户" >
              {getFieldDecorator('dau')(&lt;span&gt;&lt;Input style={{ width: &quot;50%&quot; }} /&gt;&amp;nbsp;万&lt;/span&gt;)}
            </FormItem>

### What is expected?
获取到dau的值

### What is actually happening?
未获取到dau输入值，输入框也一样

---
这里是想在输入框后面加上一个单位，万，但是这样的话，在提交的时候无法获取到输入值

**Comment by afc163** [comment]
Hey @iamhanson , It is not a bug, it is a intended behavious. You shoud wrap the form component direactly via `getFieldDecorator`.

```jsx
<span>
   {getFieldDecorator('dau')(<Input style={{ width: "50%" }} />)}&nbsp;万
</span>
```
