### ISSUE TITLE
upload上传到oss

### ISSUE THREAD

**Issue by nicelj** [ant-design/ant-design#5737]
### Version
2.8.3

### Environment
windows

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
运行官方upload中的照片墙demo，将action改成oss的地址，并将data改成oss上传的参数

### What is expected?
成功上传

### What is actually happening?
没有上传，status和percent会改变，但是response为空

**Comment by fatesq** [comment]
请问你是怎么解决得

**Comment by nicelj** [comment]
没毛病，是可以上传的 参数正确就行

**Comment by Victorkangsh** [comment]
直接填地址怎么验证，有demo或截图可以看一下吗？
