### ISSUE TITLE
Table无数据时，是否可以支持自定义交互，而不是‘暂无数据‘

### ISSUE THREAD

**Issue by ningyanbo** [ant-design/ant-design#5738]
而locale是为国际化而备。
。。。。。。
！！！

**Comment by allan2coder** [comment]
<Table locale={{ emptyText=（<div>自定义</div>) }}>

**Comment by allan2coder** [comment]
`locale={{
                    emptyText: (
                        <div>
                            自定义内容
                        </div>
                    )
                }}`
