### ISSUE TITLE
local iconfont still trying to get CDN font in some cases

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5739]
### Version
2.9.1

### Environment
osx, chrome

### Reproduction link
[https://www.dropbox.com/s/qvlax6ou9ychms3/Screenshot%202017-04-12%2013.35.04.png?dl=0](https://www.dropbox.com/s/qvlax6ou9ychms3/Screenshot%202017-04-12%2013.35.04.png?dl=0)

### Steps to reproduce
Just did as recommended for local iconfont.

### What is expected?
no any request to CDN fonts

### What is actually happening?
in some cases its trying to get

---
As you can see, first request goes to CDN from **InkTabBarMixin.js**, next one as supposed - to local iconfont.

**Comment by afc163** [comment]
Could you provide your source code?

**Comment by plandem** [comment]
ok, looks like I found:
```
module.exports = function(webpackConfig) {
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: true,
  }]);
  return webpackConfig;
};
```

If I use:
```json
style: true
```
then I will have both - CDN font request and local font. But in readme of plugin we have:
```
["import", { "libraryName": "antd", "style": true }]: import js and css modularly (LESS/Sass source files)
```

So looks like it's **babel-plugin-import** issue

P.S.:
You can get this issue at example (just modify as I wrote above):
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by afc163** [comment]
Please provide your reproducible code or I can't check your problem.

**Comment by plandem** [comment]
Man, as I said - got this [example ](https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont) and set **style: true** and got this CDN request.

webpack.config.js
```js
module.exports = function(webpackConfig) {
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: true,
  }]);
  return webpackConfig;
};
```

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import './index.less';
import { Icon, Button } from 'antd';

const Demo = React.createClass({
  render() {
    return <Button type="primary"><Icon type="smile" /> Button</Button>;
  }
});

ReactDOM.render(<Demo />, document.getElementById('container'));
```

https://www.dropbox.com/s/1ovn6pxpcsudcq2/Screenshot%202017-04-12%2016.55.19.png?dl=0

**Comment by afc163** [comment]
OK, here is the problem:

When you choose import less via `@import "~antd/dist/antd.less";`, then you should not use `style` option of `babel-plugin-import`. They are doing same thing here. So the cdn fonts is imported by babel-plugin-import in your demo.

If you prefer to import style by `babel-plugin-import`, then you should override the `@icon-url` variable in `package.theme`: https://ant.design/docs/react/customize-theme#1)-Using-theme-property-(recommended-way)

**Comment by sultan99** [comment]
@afc163 is it possible to trick it with **css** without **_less_**?

```
"plugins": [
	"flow-react-proptypes",
	"styled-components",
	["import", {"libraryName": "antd", "style": "css}]
]
```

**Comment by hackwaly** [comment]
@afc163 Your solution doesn't work still!
