### ISSUE TITLE
有推Vue版本的计划吗？

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design#574]
ant-design有着比较全面的企业应用开发所需的组件，非常棒！
react不太适合有大量模板的开发（参看：http://cn.vuejs.org/guide/comparison.html）
vue也是国人开发的，请问有没有计划考虑用vue来封装ant-design。
个人认为如果用vue来封装，代码量应该比react少很多！
谢谢!

**Comment by benjycui** [comment]
Try: [vue-antd](https://github.com/okoala/vue-antd)

**Comment by rendongsc** [comment]
知道是有的，且源代码已看。
只是建议能够官方可以有vue的实现！

**Comment by yiminghe** [comment]
换库成本太大，不实现的.

**Comment by xiaolongyuan** [comment]
@benjycui  vue-antd 死掉很久了  不更新了

**Comment by benjycui** [comment]
@okoala

**Comment by xiaolongyuan** [comment]
@benjycui  关注很久了  看提交记录就知道没戏了

**Comment by okoala** [comment]
不会死，来了~~

**Comment by benjycui** [comment]
@okoala 加油 :+1:

**Comment by xiaolongyuan** [comment]
@benjycui  @okoala   vue-antd 已死 根本不见作者对此项目有任何维护的迹象

**Comment by afc163** [comment]
光吐槽并不能帮助项目成功。

**Comment by djyde** [comment]
@afc163 有没有官方支持的计划？

**Comment by xiaolongyuan** [comment]
有没有官方支持的计划？

**Comment by benjycui** [comment]
@xiaolongyuan 结论已经更新到楼顶 https://github.com/ant-design/ant-design/issues/574#issue-118307026

**Comment by xiaolongyuan** [comment]
@benjycui  感谢回复

**Comment by benjycui** [comment]
@okoala vue-antd 的需求是有的，如果是因为个人精力有限，可以考虑迁移到 vue-antd/vue-antd 并征集 collabrators?

**Comment by xiaolongyuan** [comment]
@okoala @benjycui 对的  以前有人提过 现在的库作者的确完成了很多工作 可以开放给社区维护 毕竟vue 好的（开源）ui组件太（没）少（有）  这还是一个没有完善的库，项目就有这么多的star 
最后，为身为国内大厂的开源精神点赞

**Comment by transtone** [comment]
近来在做vue-antd的复用。首先感谢 @okoala 做了很多的前期工作。
在此稍稍评价一下：
1. vue-antd 步子太大，想一步到位复制 ant-design 整个项目。，为此还不惜使用了一些黑魔法，如：okoala/vue-antd-docs-loader，，一不小心就扯到蛋了。
2. 作者本人的主观意愿太强，es6的变化也太快，旁人几乎很难加入维护。
3. ant-design 更新很快，vue-antd一开始又没稳定成型，于是一步跟不上步步跟不上。

个人建议：
1. 开发环境 vue-cli 化，这样入门不至于太生疏。
2. 样式紧跟ant-design的步伐，因为是纯引用，没啥太大难度。
3. 重构并完善现有组件。像ant-design的组件其实是 rc-component 的小组件合并一样，将vue-antd项目的组件也拆分开来，这样大家维护起来也相对容易。

我其实是想来做这方面的事情的，可个人能力有限，对现有的两个项目都没有深入的理解。板砖是扔出来了，大神们再不出手是不是有点对不起观众啊。

**Comment by hisland** [comment]
想用vue, 就看准这个ui库, 想加入也期待

**Comment by chaoren1641** [comment]
凭一己之力绝对做不成vue-antd，看看antd的源代码就知道了，光是rc-table或rc-calendar这种功能性比较复杂的组件就够呛了。目前vue-antd也就实现了antd里面一小半功能简单的组件。 


而antd的代码贡献者到现在有60位左右之多，应该有几个同学是全职开发的，还是得有公司业务驱动提供人力支持才做得好啊：）

只有等到vue在市场占有方面大幅超过react才有这种可能吧

**Comment by peirancao** [comment]
不知道目前有多少开发者因为vue放弃了antd转而自己实现这些组件。。

**Comment by wucuida** [comment]
有用vue重构ant小组件的想法，但不知道该怎么做，谁能提供一个思路呀

**Comment by djyde** [comment]
@wucuida 我的想法是这样的，像 ant.design 一样，先把组件本身选做出来，比如 vue-form, vue-datepicker, etc. 再根据一种优秀的设计语言为它们写样式。

**Comment by netputer** [comment]
https://github.com/ElemeFE/element

**Comment by wangfengcool** [comment]
临渊羡鱼，不如退而结网

**Comment by afc163** [comment]
推荐两个：

https://github.com/iview/iview/
https://github.com/FE-Driver/vue-beauty

**Comment by develar** [comment]
@afc163 So, for non-chinese users, view is recommend ;) Since vue-beauty doesn't have english site :) What about Element? Or as Element doesn't strictly implement spec, it is not recommended?

**Comment by snowdream** [comment]
希望提供vue的版本。

**Comment by wahengchang** [comment]
文件太少了，跟本無從入手
