### ISSUE TITLE
Changing "required" flag in a form in runtime doesn't affect the rule

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#5740]
### Version
2.9.1

### Environment
ubuntu 16.04, chrome 57.0.2987.110, react 15.5

### Reproduction link
[http://codepen.io/anon/pen/oWNXVK?editors=0010](http://codepen.io/anon/pen/oWNXVK?editors=0010)

### Steps to reproduce
in the codepin example: click the checkbox and then submit

### What is expected?
a validation error appears saying that the textbox field is required

### What is actually happening?
the error is not present

**Comment by AhmedSayed77** [comment]
I dont't know why but it actually works in the code pen and doesn't work in my project. Will re invistigate. sorry for the issue

**Comment by AhmedSayed77** [comment]
after further investigation this happens:
path A:
1 - click submit
2- click checkbox
3- click submit again
result: the form submits with no errors

path B:
1-click checkbox first
2- submit -> error appears
3- click checkbox again
4- submit
result: error again

**Comment by benjycui** [comment]
It is not a bug, but a use case:

```jsx
props.form.validateFields({ force: true }, (err, values) => {
  ...
})
```

**Comment by AhmedSayed77** [comment]
works, thanks
