### ISSUE TITLE
select 选中option，调用select的focus事件

### ISSUE THREAD

**Issue by 39Er** [ant-design/ant-design#5741]
### Version
2.9.1

### Environment
ubuntu16.04，node4.5

### Reproduction link
[http://codepen.io/anon/pen/YVzypq?editors=0011](http://codepen.io/anon/pen/YVzypq?editors=0011)

### Steps to reproduce
搜索框和下拉同时使用时，选中option时，触发focus事件

### What is expected?
选中option时，不触发focus，即不会打印aaa

### What is actually happening?
选择option时，打印aaa

**Comment by RaoHai** [comment]
similar #5244

@yesmeck  add a `onFocus` callback on `<Select.Option />` or add callback `onOptionFocus` on `Select`, which is better?

**Comment by 39Er** [comment]
@RaoHai  我需要在focus在Select时，动态加载Option，并且支持搜索框,但在选中Option时，又会调用一次动态加载方法...

**Comment by 39Er** [comment]
Please fix it fast , I'm waiting for it,Thank U

**Comment by 39Er** [comment]
@RaoHai Please fix it fast , I'm waiting for it,Thank U

**Comment by yesmeck** [comment]
Reinstall node_modules.

**Comment by 39Er** [comment]
@yesmeck  when will the antd package.json update?It still use the old version

**Comment by yesmeck** [comment]
Just reinstall node_modules, npm will install rc-select@6.8.4

**Comment by 39Er** [comment]
@yesmeck  that's right. Thank U !
