### ISSUE TITLE
Prefix on Select?

### ISSUE THREAD

**Issue by kud** [ant-design/ant-design#5744]
### What problem does this feature solve?
I'd like to add an icon in my Select.

### What does the proposed API look like?

```javascript
<Select prefix={ <Icon type="search" /> } />
```

**Comment by afc163** [comment]
It will make Select extremely complicated. 😨

**Comment by kud** [comment]
No worries, thanks for your time. ;)

**Comment by afc163** [comment]
You can try https://ant.design/components/input/#components-input-demo-group

**Comment by iiiok** [comment]
I encounter the same issue.
My work around is :
1.use the suffixIcon.
2. reset the css for that icon, from "right:11px" to "left: 11px;" 
and add a margin-left to the input element, all under your .ant-select-selection__rendered.

**Comment by PhilDore11** [comment]
Another solution is to use CSS to hide the prefix:
https://codesandbox.io/s/select-prefix-u6uv0

**Comment by baurine** [comment]
Works fine by @PhilDore11 's solution, the prefix can be the `<Icon/>` component, for example:

```
    // jsx
    <Option value="jack" className="option">
      <Icon type="user"/> Jack
    </Option>

    // css
    .option .anticon {
        display: none;
    }
```

**Comment by baurine** [comment]
> Another solution is to use CSS to hide the prefix:
> https://codesandbox.io/s/select-prefix-u6uv0

Btw, it seems this link gets 404.

**Comment by freewind** [comment]
Use "Input.Group" can't compose an icon and a select in a pretty way

**Comment by RixBai** [comment]
I have the same problem.
Can we make a api for prefix icon?

**Comment by shreyansRS** [comment]
https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

Like if you found your solution. Most it solves it.

**Comment by shreyansRS** [comment]
> I have the same problem.
> Can we make a api for prefix icon?

https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

**Comment by mrtk0y** [comment]
You guys can try this way, make a relative div, and absolute the prefix icon, it's got the job done for me
`
  <Form.Item
                name="relationship"
                rules={[{ required: true, message: 'Vui lòng nhập lại mật khẩu!' }]}
                className="relative"
              >
                <img src="/Images/authentication-parent.svg" alt="" srcSet="" 
style={{
 position: absolute;
      left: 2rem;
      top: 50%;
      transform: translateY(-50%);
      z-index: 9;
}}
 />
                
            <Select
                  className="register__form__input-select"
                  style={{ width: '100%' }}
                  defaultValue="parent"
                >
                  <Select.Option value="parent">
                    <Icon type="user" />
                    Phụ huynh
                  </Select.Option>
                  <Select.Option value="kid">
                    <Icon type="user" />
                    Học sinh
                  </Select.Option>
                </Select>
              </Form.Item>
`

**Comment by debotos** [comment]
My custom solution,

```js
// imports
import { Select } from 'antd'
import { UnorderedListOutlined } from '@ant-design/icons'
import styled from 'styled-components'
// jsx
<div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
  <PrefixListIcon />
  <Select defaultValue='default' style={{ width: 140 }} onChange={() => {}}>
    <Select.Option value='default'>Default List</Select.Option>
  </Select>
</div>
// styles
const PrefixListIcon = styled(UnorderedListOutlined)`
  padding: 8px;
  border: 1px solid #d9d9d9;
  border-right: none;
  border-bottom-left-radius: 2px;
  border-top-left-radius: 2px !important;
  background: #fff;
`
```

**Comment by jvaclavik** [comment]
Actually having an icon as a prefix is a quite common use case. For example, if you need to create language switcher similar like this one: 
![image](https://user-images.githubusercontent.com/858321/97070982-12112000-15dd-11eb-9bee-105c4c9f82cf.png)

`Input.Group` doesn't help here.

**Comment by Ollie-lee** [comment]
> > I have the same problem.
> > Can we make a api for prefix icon?
> 
> https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

This works perfectly fine!

**Comment by GarfieldZHU** [comment]
> > I have the same problem.
> > Can we make a api for prefix icon?
> 
> https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

It works well for antd 3.x, but not works in 4.x. 
Any solutions for 4.x?

**Comment by NikolMarg** [comment]
> > > I have the same problem.
> > > Can we make a api for prefix icon?
> > 
> > 
> > https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js
> 
> It works well for antd 3.x, but not works in 4.x.
> Any solutions for 4.x?

It's the same thing, just replace the `<Icon type="search" />` with `<SearchOutlined />` or the icon of your choice, as Icons have changed in 4.x.

**Comment by abstrekt** [comment]
one solution that worked for is to not provide the ```options``` array & instead manually construct using 
```<a-select-option> <img :src="option.img" /> {{ option.label }} </a-select-option>```

In this the prefix icons appears in the dropdown options as well as on the select option when anything is select,

**Comment by tanmayaBiswalOdiware** [comment]
> It's the same thing, just replace the `<Icon type="search" />` with `<SearchOutlined />` or the icon of your choice, as Icons have changed in 4.x.

No, this solution doesn't work in 4.x

**Comment by P1GAS** [comment]
> > > > I have the same problem.
> > > > Can we make a api for prefix icon?
> > > 
> > > 
> > > https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js
> > 
> > 
> > It works well for antd 3.x, but not works in 4.x.
> > Any solutions for 4.x?
> 
> It's the same thing, just replace the `<Icon type="search" />` with `<SearchOutlined />` or the icon of your choice, as Icons have changed in 4.x.

Not the same we don't have a label on Option on 4.x versions

**Comment by coder054** [comment]
This is great:
https://impact.hashnode.dev/how-to-add-a-prefix-icon-to-ant-design-select-component

**Comment by reza-sadeghzadeh** [comment]
Now, here is a trick that you can use to achieve this:
You can use custom placeholders and custom labels for this purpose.

First, in order to avoid repetition, we can create a custom text and icon component.
```jsx
const TextWithIcon = ({ text, icon }: { icon: ReactNode; text: ReactNode }) => (
  <div className='flex items-center justify-start '>
    <div className='flex kustify-center items-center'>{icon}</div>
    {text}
  </div>
)
```
This renders text and an icon together.
Now, you can use the Select component from Antd to achieve a prefix icon-style.
```jsx
const PrefixedSelect = ({
  prefixIcon,
  placeholder,
  ...props
}: SelectProps & { prefixIcon: ReactNode }) => {
  return (
    <Select
      labelRender={({ label }) => <TextWithIcon icon={prefixIcon} text={label} />}
      placeholder={<TextWithIcon icon={prefixIcon} text={placeholder} />}
      {...props}
    />
  )
}
```

You can use this like any select component.
```jsx
<PrefixedSelect prefixIcon={<RandomIcon />} />
```

⚠️For `search` functionality, you should add extra left padding to the search input to prevent it from overlapping with the icon.

**Comment by ouzhou** [comment]
@reza-sadeghzadeh 
maybe they shoud override placeholder when labelRender->label.label is null

so we can do this
```
const labelRender: LabelRender = (props) => {
  const { label, value } = props;

  if (label) {
    return value;
  }
  return <span>my placeholder</span>;
};
```

rather than


```
<Select
      labelRender={...}
      placeholder={
      <>
        <span style={{color:'#000'}}>myicon</span>
        {props.placehoder}
      </>
      }
      {...props}
    />
```

**Comment by ouzhou** [comment]
full code

```
import { Select, SelectProps, Space, Typography } from 'antd';
import styles from './index.module.less';

export interface PrefixSelectProps extends SelectProps {
  prefix?: React.ReactNode;
}

function Prefix(props: { prefix: React.ReactNode; text: React.ReactNode }) {
  const { prefix, text } = props;
  return (
    <Space>
      <span className={styles.prefix}>
        {typeof prefix === 'string' ? (
          <Typography.Text type="secondary">{prefix}</Typography.Text>
        ) : (
          prefix
        )}
      </span>
      <span>{text}</span>
    </Space>
  );
}

function WithPrefix(props: PrefixSelectProps) {
  const { prefix, ...rest } = props;

  return (
    <Select
      {...rest}
      placeholder={<Prefix prefix={prefix} text={rest.placeholder} />}
      labelRender={(label) => {
        return <Prefix prefix={prefix} text={label.label} />;
      }}
    />
  );
}

const PrefixSelect = (props: PrefixSelectProps) => {
  if (props.prefix) {
    return <WithPrefix {...props} prefix={props.prefix} />;
  }

  return <Select {...props} />;
};

export default PrefixSelect;
```

**Comment by anthonyhoegberg** [comment]
> > I have the same problem.
> > Can we make a api for prefix icon?
> 
> https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

I made this component with prefix support based on the above code code, hope it comes in handy for someone

```tsx
import React from 'react';
import { Select, SelectProps } from 'antd';
const { Option, OptGroup } = Select;

interface CustomSelectProps extends SelectProps<any> {
  prefix: React.ReactNode;
}

const CustomSelect: React.FC<CustomSelectProps> = ({ prefix, options, placeholder, ...props }) => {
  const renderOptions = (options: any) => {
    return options.map((option: any) => {
      if (option.options) {
        return (
          <OptGroup key={option.title} label={option.label}>
            {renderOptions(option.options)}
          </OptGroup>
        );
      }
      return (
        <Option
          key={option.value}
          value={option.value}
          label={
            <React.Fragment>
              {prefix}
              &nbsp;
              {option.label}
            </React.Fragment>
          }
        >
          {option.label}
        </Option>
      );
    });
  };

  return (
      <Select
        {...props}
        optionLabelProp="label"
        placeholder={
          <React.Fragment>
            {prefix}
            &nbsp; {placeholder}
          </React.Fragment>
        }
      >
        {renderOptions(options)}
      </Select>
  );
};
export default CustomSelect;
```

**Comment by Closery** [comment]
> I encounter the same issue. My work around is : 1.use the suffixIcon. 2. reset the css for that icon, from "right:11px" to "left: 11px;" and add a margin-left to the input element, all under your .ant-select-selection__rendered.

Thats a pretty good idea, I added arrow icon to the background and suffixIcon now serve as prefix, thanks for tip! 🙏
