### ISSUE TITLE
Pagination Component 'onChange' API don't call when back or fore

### ISSUE THREAD

**Issue by xilixjd** [ant-design/ant-design#5745]
### What problem does this feature solve?
browser back or fore can't call 'onChange' API, so that the page list can't update according to current page

### What does the proposed API look like?
Is that a bug in Pagination Component or anybody can help me with the problem？

**Comment by yesmeck** [comment]
Please use bug template, if you are reporting a bug.

**Comment by afc163** [comment]
similar with https://github.com/react-component/pagination/issues/61
