### ISSUE TITLE
layout="inline" in Form does not work

### ISSUE THREAD

**Issue by tailorsira** [ant-design/ant-design#5749]
### Version
2.9.1

### Environment
win10, chrome56.0.2924.87 (64-bit)

### Reproduction link
[http://codepen.io/anon/pen/WjNaXx?editors=001](http://codepen.io/anon/pen/WjNaXx?editors=001)

### Steps to reproduce
在<Form>标签上加上layout="inline"

### What is expected?
表单布局呈行内排列样式

### What is actually happening?
依然是垂直排列

**Comment by tailorsira** [comment]
sorry, I make a mistake, I use the antd vision is 2.7.4

**Comment by afc163** [comment]
You should close it.
