### ISSUE TITLE
建议Modal支持国际化

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#575]
虽然footer可以自定义，但Modal.xxx()在很多场合更简单，建议增加按钮文字的属性，可以用开发中自己重新定义。谢谢！

**Comment by yiminghe** [comment]
增加属性
```
okText
cancelText
```

**Comment by afc163** [comment]
- [ ] modal 确定 取消 知道了
- [ ] popconfirm 确定 取消
- [ ] table filter 确定 重置

**Comment by benjycui** [comment]
`Table` 中，像下面这样的 `title` 也应改成可配置的。

![image](https://cloud.githubusercontent.com/assets/3580607/11359436/143e2c96-92b7-11e5-8423-ed0277097bc2.png)

打算像 `Datepicker` 一样，增加 `locale` 属性。

```js
locale = {
  sorter: {
    up: '升序排序',
    down: '降序排序'
  },
  filter: {
    title: '筛选',
    confirm: '确定',
    reset: '重置'
  }
};
```

**Comment by afc163** [comment]
#413

**Comment by qingsong81** [comment]
密码，，，

- 没来看了
 

- [ ] 

> 

> 

> #   @@_**`2131`**_

- [ ]

**Comment by qingsong81** [comment]
> 👍

**Comment by jadeOnlyone** [comment]
请问表格的expandedRowRender 点击搜索时怎么关闭
![image](https://user-images.githubusercontent.com/32806550/47279505-24c67800-d604-11e8-8635-bc365b477dd2.png)

**Comment by matinfo** [comment]
Thank to give more instruction in english, example of how! Or doc link be good :-)

**Comment by 1089109** [comment]
可以自定义空数据图片吗？

**Comment by otwayxf** [comment]
自定义空数据文案之后，空数据图片也没了，怎么能做到文案自定义，空数据图片还保留

**Comment by yoyo837** [comment]
@1089109 @otwayxf 开个新issue

**Comment by joesdu** [comment]
> @1089109 @otwayxf 开个新issue

空数据自定义图案的issue有链接吗?

**Comment by yoyo837** [comment]
就用issue模版 写复现即可

**Comment by iViolinSolo** [comment]
需要空数据的这么写，插入node就行
```javascript
locale = {{
    filterConfirm: '确定',
    filterReset: '重置',
    emptyText: <Empty description={"没有数据"}/>,
}}
```

**Comment by joesdu** [comment]
> 需要空数据的这么写，插入node就行
> 
> ```js
> locale = {{
>     filterConfirm: '确定',
>     filterReset: '重置',
>     emptyText: <Empty description={"没有数据"}/>,
> }}
> ```

感谢.

**Comment by otwayxf** [comment]
3Q,了解了解了



在 2020-07-21 22:10:56，"Joe Du" <notifications@github.com> 写道：

需要空数据的这么写，插入node就行

locale={{filterConfirm: '确定',filterReset: '重置',emptyText: <Emptydescription={"没有数据"}/>,}}

感谢.

**Comment by scalerone** [comment]
> 自定义空数据文案之后，空数据图片也没了，怎么能做到文案自定义，空数据图片还保留

我的解决方式：
```
let obj = {
      locale:undefined,
    }
    if(!this.state.Lists.length) {
      view = (
        <div><span>暂无相关数据，请先添加</span> <a onClick={this.goToScoreTab} style={{color:'#1855B3'}}>规则</a></div>
      )
      let temp={
        emptyText:()=>view
      }
      obj.locale=temp;
    }
    
    return (
       <Table
       
            {...obj}
          />
    )
```

**Comment by TEARSUNCLE** [comment]
> > @1089109 @otwayxf 开个新issue
> 
> 空数据自定义图案的issue有链接吗?

locale={{filterConfirm: '确定', filterReset: '重置', emptyText: <Empty image={noData} description={"暂无数据"} />}}，image里就可以自定义图片，用import引入
