### ISSUE TITLE
Popover can not closed when it is in another popover content

### ISSUE THREAD

**Issue by NeverlandForKi** [ant-design/ant-design#5750]
### Version
2.9.1

### Environment
Mac:0.10.5 Chrome:57.0.2987.98

### Reproduction link
[http://codepen.io/SmilePark/pen/ybLRKX?editors=0010](http://codepen.io/SmilePark/pen/ybLRKX?editors=0010)

### Steps to reproduce
1.click the button
2.click the text 'click me'
3.click the body

### What is expected?
all two popover should be closed

### What is actually happening?
the child popover can not be closed

**Comment by afc163** [comment]
`getPopupContainer`

http://codepen.io/anon/pen/RVwqbP?editors=0010

**Comment by NeverlandForKi** [comment]
@afc163 非常感谢。。但是 第二次点击进来的时候  第二个popover会闪一下，然后又消失

**Comment by afc163** [comment]
Seems to be a problem..

**Comment by afc163** [comment]
两个 state 隔离开吧：http://codepen.io/anon/pen/YVxOay?editors=0011
