### ISSUE TITLE
I suggest the table component to add a double-click event for the row click

### ISSUE THREAD

**Issue by yefeng2016** [ant-design/ant-design#5751]
### What problem does this feature solve?
may be some scenes need double-click to row

### What does the proposed API look like?
add a double-click event

**Comment by NE-SmallTown** [comment]
I am not sure what you mean.You can do it just by yourself.

**Comment by afc163** [comment]
`onRowDoubleClick`

**Comment by sitepodmatt** [comment]
Meta:
I'm not sure these requested should be closed so quickly, there's a big discoverability / documentation issue that can easily follow on from here, for example https://ant.design/components/table/ for example makes no mention of onRowDoubleClick.

**Comment by yesmeck** [comment]
@sitepodmatt  Check `onRow`

**Comment by sitepodmatt** [comment]
I cant see it.  How odd. Even curl can't it
➜  ~ curl -s https://ant.design/components/table/ | grep onRowDoubleClick

**Comment by yesmeck** [comment]
I mean `onRow`, `onRowDoubleClick` has been deprecated.
