### ISSUE TITLE
is that possible to dynamically change the css style for <td> in Table Element

### ISSUE THREAD

**Issue by zj1926** [ant-design/ant-design#5756]
### What problem does this feature solve?
Currently, in the column render function, it returns the react elements inside the td element. but td element has a small default padding. I'd like to change the background-color of TD element dynamically based on each row's value.

### What does the proposed API look like?
maybe similar like render function,
render: (value, row, index) => { ...},
cellClass: (value, row, index) => {
  return "{some class name here as string}"
}

**Comment by afc163** [comment]
`rowClassName`

**Comment by alexsinfarosa** [comment]
How to accomplish the same thing as above but using JSX?

`<Column title="xxx" className="xxx" dataIndex="xxx" key="xxx" render={...} />`
