### ISSUE TITLE
Disable weekends for DatePicker

### ISSUE THREAD

**Issue by likhita-palavali** [ant-design/ant-design#5757]
### What problem does this feature solve?
I am trying to disable weekends for the ant-design DatePicker so that the user will not be able to select them for all the months. I have used "https://github.com/ant-design/ant-design/blob/master/components/date-picker/demo/disabled-date.md" to disable future dates. 

Help would be greatly appreciated.

### What does the proposed API look like?
The user should not be able to select the weekend (Saturday and Sunday).

**Comment by afc163** [comment]
`disabledDate` is a function, you can define it for whatever you want.
