### ISSUE TITLE
Could you offer the interface for the TD tag of the table?

### ISSUE THREAD

**Issue by thomaslwq** [ant-design/ant-design#5760]
### What problem does this feature solve?
When we use the table,sometimes we need custom the TD tag, so we need add different class to different TD,but I couldn't find any interface for it?

### What does the proposed API look like?
Maybe there is new property called customClass for the column,it is a function which can recieve  the content of the TD and return the class for it.Like:
customClass:function( item,obect){
   return className
}

**Comment by afc163** [comment]
duplicate #5756

**Comment by thomaslwq** [comment]
Thank you very much! I try it but this will add a class for the tag "TR" not the tag "td".Maybe there is some usage that is hidden?

**Comment by afc163** [comment]
Sorry, I correct my answer it in #5756

**Comment by thomaslwq** [comment]
Thank you very much. I try it but i didn't get the expected result.
In the following code,i want  to add the class "tdtest" to the td tag with content "1". But instead, the content of td for this column all become "1".
        var columns = [{
            title:'序号',
            dataIndex:'index',
            key:'index',
            render:()=>{
                return {
                    props:{
                        className:'tdtest'
                    },
                    children:'1',
                }]
            }

**Comment by afc163** [comment]
@ant-design-bot markdown

**Comment by afc163** [comment]
Because you set it to `1`...

**Comment by thomaslwq** [comment]
I am confused now,if i want add a class called "cellClass" to a td,which content is "1",what should i do?

**Comment by thomaslwq** [comment]
Here i want to add "tdtest" class to the td with text equal 0,but it didn't work
```javascript
        var columns = [{
            title:'序号',
            dataIndex:'index',
            key:'index',
            render:(text,record)=>{
                return {
                    props:{
                        className: text==0?'tdtest':'' //Here i want to add "tdtest" class to the td with text equal 0,but it didn't work
                    },
                    children:text,
                }
            }
        }]
```

**Comment by afc163** [comment]
http://codepen.io/anon/pen/EmaRJL?editors=0110

**Comment by thomaslwq** [comment]
Thank you very much for your reply again! I try it,but it didn't work on my PC.I found your ant version is 2.9.1,but mine is  v2.7.0,I don't know whether if it is the version that affect the result?

**Comment by afc163** [comment]
Just upgrade antd version.
