### ISSUE TITLE
字体图标在ie下不能显示

### ISSUE THREAD

**Issue by zhaobobin** [ant-design/ant-design#5762]
### Version
2.9.1

### Environment
ie11、Edge、react-15.4.2

### Reproduction link
[http://www.metuwang.com/#/jingwu/84](http://www.metuwang.com/#/jingwu/84)
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
在不同的电脑试了ie11和Edge都是这样，然后我发现官网的字体图标也不能显示，什么原因？
之后又试了下font-awesome字体库，都是能显示的。

### What is expected?
有什么有效的解决办法？

### What is actually happening?
该显示字体的地方是一片空白

**Comment by afc163** [comment]
<img width="1126" alt="2017-04-14 11 00 16" src="https://cloud.githubusercontent.com/assets/507615/25031726/9161651a-2101-11e7-8648-350ed2a303d8.png">
<img width="824" alt="2017-04-14 11 00 08" src="https://cloud.githubusercontent.com/assets/507615/25031727/9163687e-2101-11e7-9605-354085d4f001.png">

实测可以，请检查网络环境。

**Comment by zhaobobin** [comment]
还是谢谢了，我再研究一下。

**Comment by RongMine** [comment]
这个问题你解决没，我也遇到相同的问题

**Comment by BorelTung** [comment]
@afc163 是win7下的IE11有问题，win10的没有

**Comment by RongMine** [comment]
使用本地字体可以解决
