### ISSUE TITLE
【ant design 能不能实现将sider彻底隐藏在左侧，而不是只留下图标】

### ISSUE THREAD

**Issue by TracyDa** [ant-design/ant-design#5763]
### What problem does this feature solve?
https://ant.design/components/layout-cn/ 这个链接中实现的sider是触发后会收起一部分留下图标，我希望可以完全收起sider，这个如何实现？

### What does the proposed API look like?
希望可以完全收起sider 类似 http://www.material-ui.com/#/components/drawer 中的drawer一样。

**Comment by afc163** [comment]
`<Sider width={0} />` or `<Sider style={{ display: 'none' }} />`

**Comment by TracyDa** [comment]
找到了，需要设置collapsedWidth	收缩宽度，设置为 0 会出现特殊 trigger。

很明显 afc163 的回答并不是好的方法，应该是设置collapsedWidth={0} 即可。

<Sider style={{overflow: 'auto'}}
                       width={240}
                       collapsible
                       collapsedWidth={0}
                       onCollapse={this.onCollapse}
                       collapsed={this.state.collapsed}>
