### ISSUE TITLE
feature: back-fill of AutoComplete

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#5764]
Just like google's search box.

* <kbd>↑ </kbd> and <kbd>↓</kbd> should fill current focus item back into input field of AutoComplete
* Users can continue change focus.
* Back-fill will not trigger `onChange` or `onSelect` until blur, input more words, or press <kbd> Enter </kbd>.
![](https://cloud.githubusercontent.com/assets/566097/25031471/bde78a44-20ff-11e7-8943-e2aedefac394.png)

references:
 * #5244 
 * https://www.google.com/
 * http://dev.office.com/fabric#/components/pickers
 * https://semantic-ui.com/modules/dropdown.html

**Comment by internet5** [comment]
Nobody solve this issue?

**Comment by benjycui** [comment]
cc @jaredleechn

**Comment by jaredleechn** [comment]
badly need it 😸 

maybe you can export event `onActiveOptionChange` first, so that I can write it manually as a quick solving
