### ISSUE TITLE
select placeholder attribute does not take effect

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#5768]
After the introduction of antd.js, the use of select components if there is set value, placeholder attribute does not take effect

![image](https://cloud.githubusercontent.com/assets/19485727/25036960/24e1a4c2-2129-11e7-9a0e-fb9c53f1aeb7.png)
![image](https://cloud.githubusercontent.com/assets/19485727/25036989/4aaf744a-2129-11e7-9901-e92bb9c50bd8.png)

If I remove value
![image](https://cloud.githubusercontent.com/assets/19485727/25037015/6bcda714-2129-11e7-8622-b3ebd3e0e0c9.png)
![image](https://cloud.githubusercontent.com/assets/19485727/25037026/74ff439c-2129-11e7-9ecb-12630b9401be.png)

**Comment by fikyair** [comment]
why  ?  I have the problem

**Comment by Shadowman4205** [comment]
Me too i i have got same problem, what is going on? When i have value = null placeholder does not work
if i remove value from select props theplaceholder take Effect

**Comment by Shadowman4205** [comment]
ok  @fikyair  try this  value={props.value ? props.value : undefined}
use undefined if value is null

**Comment by enRose** [comment]
Shouldn't the Select component's responsibility to check whether value is empty string if yes then set display block on placeholde div? 

I can't imagine there is a use case where you would want treat empty string as a selected value?

**Comment by lishichao1002** [comment]
why use undefind to show placeholder,  the value types is string

`
string\|string[]\|number\|number[]
`
