### ISSUE TITLE
React 官方去掉 DOM refs 和 ref 赋值字符串的用法了，ant design 的 Input 如何调用 ref？

### ISSUE THREAD

**Issue by coldice945** [ant-design/ant-design#5771]
### Version
2.9.1

### Environment
Win10、Chrome

### Reproduction link
[http://codepen.io/anon/pen/qmEXjq?editors=0011](http://codepen.io/anon/pen/qmEXjq?editors=0011)

### Steps to reproduce
```
function handleSearch() {
  console.log(this.searchInput.value);
  this.searchInput.value = 'XXXXXXXXXXX';
}
```
   
```
 <Input ref={(input) => { this.searchInput = input; }} />
 <Button type="primary" onClick={this.handleSearch.bind(this)}>搜索</Button>
```

### What is expected?
ref 能够通过 函数方法 赋值，而不是还是以前的字符串赋值。

### What is actually happening?
Input 只能用字符串 赋值 ref，input 能用 函数回调赋值。（注意 ant-design 用的是大写，本身的是小些）

**Comment by benjycui** [comment]
Actually, `ref: function` works fine with `antd.Input`. You just cannot `this.searchInput.value`.

**Comment by benjycui** [comment]
`Input` is not `input`
