### ISSUE TITLE
labelInValue combobox同时使用时bug

### ISSUE THREAD

**Issue by acivang** [ant-design/ant-design#5772]
### Version
2.8.1、2.9.1均存在

### Environment
mac OS 10.12.3/chrome 56.0.2924.87 (64-bit)/react 15.4.2

### Reproduction link
[https://github.com/acivang/antd-seed](https://github.com/acivang/antd-seed)

### Steps to reproduce
```javascript
function onSelected(value){
	console.log(value);
}

render(){

	return(
		<Select 
		    labelInValue
		    combobox
		    onSelect={this.onSelected}
		    >
		    <Option key="1">dddd</Option>
		    <Option key="2">dddd2</Option>
		    <Option key="3">dddd3</Option>
		</Select>
	)

}
```

### What is expected?
Object {key: "1", label: "dddd"}

### What is actually happening?
Object {key: "1", label: "1"}

---
提交的重现用的2.9.1版本，存在同样的问题。
应用场景是：用户输入时在onChange里进行远程查询，选中查询的数据后，控件里显示的是key的值，预期应显示label，这是前置bug。在解决前置bug时，在onSelect设置显示值，触发提交的bug。
https://github.com/ant-design/ant-design/issues/3401 与这个bug类似，是没修复么？

**Comment by benjycui** [comment]
Actually, an online demo will be better..

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
labelInValue 和 combobox 不应该同时使用，概念上是冲突的。

**Comment by acivang** [comment]
@afc163 我可以不用labelInValue，但用combobox时，选中后select显示的是key，如何显示label？官网给的demo里，key用的是label值。

**Comment by afc163** [comment]
combobox 模式下，label 和 key 应该是同一个值。

**Comment by acivang** [comment]
@afc163 那如何像普通select那样获取id呢？在另一个issue里有人建议onChange和onSelect配合使用。

**Comment by afc163** [comment]
combobox 是可以自由输入的，本质上是一个 Input 。如果只是希望选择，应该用 `Select[showSearch]`

**Comment by acivang** [comment]
好的，谢谢回复

**Comment by acivang** [comment]
Select[showSearch]似乎并不能满足产生bug的应用场景，因为数据是根据用户输入从远程获取，而filterOption是在已经有了数据的情况下进行过滤。另外，以您的说法，如果combobox本质是个input，似乎应该放到input.search里更合适，因为官网的select combobox demo，让初用者产生这是一个select的错觉

**Comment by afc163** [comment]
1. Select combobox 其实后面封装成了 AutoComplete，语义上更明确。
2. 你可以 `filterOption={false}`，然后用 onSearch 去远程获取新的 option。

**Comment by acivang** [comment]
@afc163 我试试，非常感谢指点

**Comment by acivang** [comment]
@afc163 已解决，谢谢你的指点

**Comment by superlbr** [comment]
这些点最好写进文档里
