### ISSUE TITLE
调用了getFieldDecorator的Switch组件会自动绑定size=large，Switch组件不存在size=large，报错

### ISSUE THREAD

**Issue by flyfinec** [ant-design/ant-design#5774]
### Version
2.8.3

### Environment
win10, chrome 57, rn 15.4.2

### Reproduction link
这个问题应该不需要链接

### Steps to reproduce
调用了getFieldDecorator的Switch组件会自动绑定size=large

### What is expected?
不报错

### What is actually happening?
报错：
Warning: Failed prop type: Invalid prop `size` of value `large` supplied to `Switch`, expected one of ["small","default"].

看文档只支持["small","default"]，但是getFieldDecorator却绑定了large，这个问题已经很多个版本了

**Comment by afc163** [comment]
I believe it was fixed at https://github.com/ant-design/ant-design/issues/5368

**Comment by flyfinec** [comment]
仔细看了下本地版本号，2.8.1
升级到最新版本验证已经修复了，关闭吧，打扰大家了
@afc163
