### ISSUE TITLE
Provide Table.Cell 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5776]
Replace original plain object.

```jsx
const columns = [{
  title: "xxx",
  className: "classNameOfColumn",
  render: () => <Table.Cell className="" onClick={} rowSpan={}>xxx</Table.Cell>,
}]
```

@yesmeck what do you think?

**Comment by yesmeck** [comment]
Looks good to me.

**Comment by plandem** [comment]
depends on final performance.

**Comment by paranoidjk** [comment]
what's the proposal api looks like？

**Comment by yesmeck** [comment]
One problem if we provide `Table.Cell`, consider following situation:

```javascript
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  render: () => <Table.Cell className="foo">xxx</Table.Cell>,
}];

const data = [{
  key: 1,
  name: 'a',
  children: [{
    key: 11,
    name: 'aa',
  }],
}];

<Table
  columns={columns}
  data={data}
/>
```

If use `Table.Cell` in the first column,  we can not insert the expand icon the first column any more.

**Comment by yesmeck** [comment]
现在感觉 Reactabular 这种能自定义  component 的方式灵活性更好 
https://reactabular.js.org/#/table/overriding-default-elements
