### ISSUE TITLE
modal不允许固定高度

### ISSUE THREAD

**Issue by yangguixue** [ant-design/ant-design#5777]
### What problem does this feature solve?
可以使用户规定弹框高度，使其内容在弹框内上下滑动，方便用户点击footer的按钮，不用滚到最下方

### What does the proposed API look like?
我规定一个高度，modal可以就是这个高度，不会随着内容的增大而增大
整个弹框都是固定的

**Comment by NE-SmallTown** [comment]
I am not sure understand your meaning,but IMO the just set `style` option(e.g. `style={{ top: 20 }}`) is ok.

**Comment by afc163** [comment]
http://codepen.io/anon/pen/qmEwQr?editors=0010
