### ISSUE TITLE
when option showSearch is true, select focus event not behaving normally

### ISSUE THREAD

**Issue by amirtgm** [ant-design/ant-design#5778]
### Version
2.9.1

### Environment
react 15.5.4

### Reproduction link
[http://codepen.io/anon/pen/oWgKgb](http://codepen.io/anon/pen/oWgKgb)

### Steps to reproduce
first open the console, and select an item, after you select and the box is closed, focused is called

### What is expected?
when you click on select box it should be focused not after you selecting.

### What is actually happening?
when you click on select box it's not focused but after you selecting an item and the box closed the select will be focused

**Comment by RaoHai** [comment]
ref #5741

**Comment by yesmeck** [comment]
Reinstall node_modules.
