### ISSUE TITLE
希望Timepicker增加一个value属性

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#578]
希望Timepicker增加一个类似于Datepicker的value属性，这样方便获得选择的值。
目前我的获得方法是，通过refs来获得。

**Comment by benjycui** [comment]
监听 `onChange`，不要用 `refs`，参见：https://github.com/ant-design/ant-design/issues/388

**Comment by wuzhao** [comment]
收到，看其他组件好想都是有 value 和 defaultValue 的，周末我去弄一下。
