### ISSUE TITLE
Range Picker: Allow relative ranges

### ISSUE THREAD

**Issue by shanielh** [ant-design/ant-design#5780]
### What problem does this feature solve?
What I'm trying to do is to create relative "calendar" presets (today, this week, this month) and normal relative presets (1 hour, 3 hours, 12 hours, 24 hours, 30 days, 90 days) like in other dashboard applications (e.g. Kibana, Grafana).

### What does the proposed API look like?
I have no proposed API, I guess I'm trying to start a discussion about the API.

What I would like to do is to send to the back end the relative times ("-60m" - "now") so it will be updated every time the user press "refresh".

**Comment by benjycui** [comment]
Similar? https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges

**Comment by benjycui** [comment]
Close for no response.
