### ISSUE TITLE
react@15.5+  变更API（PropTypes，createClass）的兼容问题

### ISSUE THREAD

**Issue by chenshenhai** [ant-design/ant-design#5781]
### Version
2.9.1

### Environment
react@15.5 +

### Reproduction link
<img width="825" alt="2017-04-16 10 22 47" src="https://cloud.githubusercontent.com/assets/8216630/25071865/607ac80c-22f4-11e7-821b-15e729baca5d.png">

[https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

### Steps to reproduce
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### What is expected?
兼容react@15.5+ 的变更的API

### What is actually happening?
兼容react@15.5+ 的变更的API

**Comment by afc163** [comment]
duplicate #5678
