### ISSUE TITLE
为tree增加编辑模式

### ISSUE THREAD

**Issue by yuu2lee4** [ant-design/ant-design#5782]
### What problem does this feature solve?
现在tree有拖拽模式，其实是满足了调整数据之间的关系的一个需求，但其实使用这种场景的时候，是伴随着对数据有修改的需求的，那么就希望增加编辑模式，在这种模式下，能够对节点的名称进行修改，能删除节点，增加节点

### What does the proposed API look like?
增加editable属性，editable为true时，每个节点鼠标点击的时候，右侧出现一排小的图标，分别是编辑（修改节点名字），删除和增加

**Comment by yesmeck** [comment]
编辑模式可以自己实现，右边出现小图标可以参考 http://react-component.github.io/tree/examples/basic.html

**Comment by ycshill** [comment]
+1

**Comment by ityoung** [comment]
> 编辑模式可以自己实现，右边出现小图标可以参考 http://react-component.github.io/tree/examples/basic.html

链接404

**Comment by hudson-dong** [comment]
链接404

**Comment by KangUkG** [comment]
链接404
