### ISSUE TITLE
slider 在改变 marks 后 min 和 max 不起效

### ISSUE THREAD

**Issue by janjon** [ant-design/ant-design#5783]
### Version
15.4.2

### Environment
mac, 55.0.2883.87

### Reproduction link
[http://codepen.io/janjon/pen/xdGzGg?editors=0010](http://codepen.io/janjon/pen/xdGzGg?editors=0010)

### Steps to reproduce
1, 查看demo，
2, 点击改变滑动条后回现实2到5的值
3, marks 显示没问题, 但是值的范围是 0到3. min 和 max 是根据 marks 决定的, 
4, 如果去掉marks 属性 则 min 和 max 正常

### What is expected?
在改变 marks 后 min 和 max 能生效

### What is actually happening?
min 和 max 不生效

**Comment by janjon** [comment]
@benjycui 请问是bug吗

**Comment by benjycui** [comment]
你先升到 antd 最新版试试。

**Comment by janjon** [comment]
@benjycui 我试了 1.11.6 最新 的不行 2.9.1 版本可以但是有下标在 react 15.4.2 下有 跑偏

**Comment by benjycui** [comment]
> 你先升到 antd 最新版试试。

意思就是最新的 2.x，1.x 已经没精力维护了。

> 2.9.1 版本可以但是有下标在 react 15.4.2 下有 跑偏

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by janjon** [comment]
@benjycui http://codepen.io/janjon/pen/xdGzGg?editors=0010

**Comment by janjon** [comment]
@benjycui 增加了复位按钮 
http://codepen.io/janjon/pen/xdGzGg?editors=0010

**Comment by benjycui** [comment]
@janjon actually, you had used slider in wrong way, `marks` is an object after `antd@2.0`, see: https://ant.design/components/slider/#components-slider-demo-mark
