### ISSUE TITLE
建议增加Typescript版本依赖 

### ISSUE THREAD

**Issue by mishengqiang** [ant-design/ant-design#5786]
### What problem does this feature solve?
今天遇到一个事情，一个网友让我解答问题，所有的代码逻辑啊依赖关系都是正确的，但是编译就是无法通过，它的项目是TypeScript写的，使用webpack打包，使用了awesome-typescript-loader@3.0.0模块加载器，antd是2.9.1版本。

通过一步一步排查，最后发现是TypeScript版本低引起的，原来项目中安装的是TypeScript@2.0.3，后来升级为最新版本2.2.2就ok了。

![image](https://cloud.githubusercontent.com/assets/9413032/25085973/84cdca44-2397-11e7-9818-d01a7a1e900d.png)

### What does the proposed API look like?
在通过npm安装antd的时候就提醒我的TypeScript版本过低。

这种非技术性问题能避免就避免，真是太浪费时间了。

**Comment by yesmeck** [comment]
antd 这边不好加，README 里可以写一下需要的 TypeScript 版本。

**Comment by afc163** [comment]
Consider that people maybe not need TypeScript.

**Comment by paranoidjk** [comment]
- devDeps 里面有已经足够了 
    - https://github.com/ant-design/ant-design/blob/master/package.json#L142 -
     - https://github.com/angular/angular/blob/master/package.json#L96
- @mishengqiang 你的问题其实是项目的依赖，与依赖的依赖版本不一致，npm 是树形依赖，这在任何 npm 包都可能会出现。

**Comment by mishengqiang** [comment]
@paranoidjk 好的，感谢。
