### ISSUE TITLE
expose 'onItemClick' in Collapse

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5787]
### What problem does this feature solve?
Click Panel header and get current key 

### What does the proposed API look like?
onItemClick(key)

**Comment by L-x-C** [comment]
@afc163 There is a situation that I need to expand all the panels in Collapse before doing something, Now I set `activeKey` to expand all panels.
But after setting `activeKey`, I can't close a separate panel by clicking the panel header.
So I want a `onItemClick` function to control panel close/open~

**Comment by afc163** [comment]
http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by L-x-C** [comment]
@afc163
I think you may have misunderstood me.
For example:
```
<Collapse  activeKey={this.state.activeKey}>
  <Panel header="a" key="0" >
  <Panel header="b" key="1" >
</Collapse>
```
I click a `Button` to set `this.state.activeKey = ['0', '1']` to expand all the panels.
But after that, If I click panel's header, it can not be closed due to `activeKey` has been set.
So I want a `onItemClick` function that I can set activeKey to control panel close/open manually

**Comment by afc163** [comment]
http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by L-x-C** [comment]
@afc163 
I get it...my bad. THX~

**Comment by afc163** [comment]
http://codepen.io/anon/pen/BRozVz?editors=0010

**Comment by L-x-C** [comment]
@afc163 
Yes, I've understood. My mistake before. Thanks a lot!
