### ISSUE TITLE
Select's onFocus is not properly triggered

### ISSUE THREAD

**Issue by zachguo** [ant-design/ant-design#5792]
### Version
2.9.1

### Environment
MacOS, latest Chrome

### Reproduction link
[http://codepen.io/zachguo/details/NjGxKv/](http://codepen.io/zachguo/details/NjGxKv/)

### Steps to reproduce
click select input area

### What is expected?
onFocus be triggered

### What is actually happening?
onFocus is not triggered

---
onFocus is triggered only when pressing Tab using keyboard or clicking on the border of Select

**Comment by RaoHai** [comment]
There's a confusing `onFocus` flow:

Focus `<Select />`, onFocus trigger.
* `<Trigger/>` focus
* `<div />` focus, 
* `onOuterFocus()` => `props.onFocus()` // Select onFocus callback here
* `setPopupVisible()` =>`Trigger.onPopupVisibleChange()` => `setOpenState(true)`
* `<input />` get focus.

Focus `<input />`, onFocus not trigger
* `<Trigger />` focus
* `<input />` focus,
* `setPopupVisible()` =>`Trigger.onPopupVisibleChange()` => `setOpenState(true)`
* `<input /> ` already focus, do nothing.

If we binding onFocus on `<input />`, pressing <kbd>tab</kbd> will not trigger `onFocus`, Or we create a timeout in `onOuterFocus`, to ensure that `onFocus` calls  once.

@yesmeck

**Comment by RaoHai** [comment]
Select now also have an `onBlur` issue..

**Comment by afc163** [comment]
fixed in 5954

**Comment by yesmeck** [comment]
Reinstall node_modules.
