### ISSUE TITLE
How to only fixed the row selection.

### ISSUE THREAD

**Issue by richardyang0212** [ant-design/ant-design#5793]
### What problem does this feature solve?
When i have many columns, i don't want fixed the other columns, I only want to fixed my row selection.
I must fixed my first column, then the row selection will fixed with it now.

### What does the proposed API look like?
Adding a param for the RowSelection.
rowSelection = {
  fixed:true(default false),
}

**Comment by yesmeck** [comment]
Landed in antd@3.0.0-rc.1, please help use testing it.
