### ISSUE TITLE
react 15.5.0 LazyRenderBox 警告

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#5796]
![qq 20170418163739](https://cloud.githubusercontent.com/assets/6470398/25121765/599b27cc-2455-11e7-9849-4f8cddc5643e.png)
### Version
2.9.1

### Environment
chrome最新版

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
不知名的情况下报这个错误 LazyRenderBox: React.createClass is deprecated and will be removed in version 16

### What is expected?
不要报出警告

### What is actually happening?
报出警告

**Comment by eddyzhang1986** [comment]
默认页就有，很明显的警告

**Comment by bang88** [comment]
trace #5678
