### ISSUE TITLE
react15.5.4配合antd使用会有警告

### ISSUE THREAD

**Issue by mfdefs** [ant-design/ant-design#5798]
### Version
2.9.1

### Environment
react15.5.4

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=0010](http://codepen.io/benjycui/pen/KgPZrE?editors=0010)

### Steps to reproduce
打开页面直接报

### What is expected?
没有告警

### What is actually happening?
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: AnimateChild: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

---
react15.4.2下不会有

**Comment by RaoHai** [comment]
trace #5678
