### ISSUE TITLE
Re-Order Multi-Select

### ISSUE THREAD

**Issue by davidmcooper** [ant-design/ant-design#5799]
### What problem does this feature solve?
It would be nice to be able to re-order the selected options from a multi-select enabled "Select" component.  Frequently multi-select inputs are used to choose groupings, but sometimes the sequence of these groupings is also important.  Ideally, the end-user would be able to drag and drop any selected options (presumably their tags) from a Select control.

There is an example of this implementation here:

http://docs.telerik.com/kendo-ui/controls/editors/multiselect/how-to/reorder-selected-items

### What does the proposed API look like?
`<Select
    mode="tags"
    reorder="true"
    style={{ width: '100%' }}
    onChange={handleChange}
    onReorder={handleReorder}
    tokenSeparators={[',']}
  >
    {children}
  </Select>`

The onReorder property would be triggered when the order was changed.

**Comment by afc163** [comment]
Sorry, we don't have plan for this.
