### ISSUE TITLE
Table 远程模式支持由外界发起请求等操作

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#58]
```js
var dataSource = new Table.DataSource({
  url: 'xxx',
  getParams: function() { ... }
  ...
});

// 重新拉取数据
dataSource.fetch();
```

**Comment by afc163** [comment]
交给逸达。

**Comment by ustccjw** [comment]
远程模式存在的意义是什么？个人觉得组件与 action(fetch data) 最好分开。

**Comment by immkoala** [comment]
同意@ustccjw的观点。 
还有为了远程模式强行依赖jquery感觉有点……

**Comment by yiminghe** [comment]
这个封装是必要的，能够减少大多数场景的数据请求，渲染代码。

**Comment by dqaria** [comment]
https://github.com/ant-design/ant-design/commit/7ba8e08b5a815b4c9f8aac9262440ad8ad57d0ce 已提交

**Comment by afc163** [comment]
cfaabbb825ad71aa9de5c61ebd387819be1e7784
