### ISSUE TITLE
0.9.5的版本怎么才能兼容到react 0.14.3

### ISSUE THREAD

**Issue by xu6658037** [ant-design/ant-design#580]
你好，请问下antd 0.9.5的版本怎么才能兼容到react 0.14.3

**Comment by afc163** [comment]
你好，功能理论上兼容，但是控制栏里会有 React 的报错提示。

**Comment by benjycui** [comment]
兼容不了的，0.9.5 使用了 React [已经 deprecate 的 API](https://github.com/ant-design/ant-design/pull/369/files#diff-95fcad89831c57d54c81a975ccb88cb0L2)

**Comment by afc163** [comment]
上面这个 pick 到 0.9.x 分支上过。
