### ISSUE TITLE
Alert prop banner ignores other props

### ISSUE THREAD

**Issue by Sicria** [ant-design/ant-design#5800]
### Version
2.9.1

### Environment
Chrome

### Reproduction link
[https://ant.design/components/alert/#components-alert-demo-banner](https://ant.design/components/alert/#components-alert-demo-banner)

### Steps to reproduce
View the demo example.

### What is expected?
It's expected that the Alert is styled using the other props but is not when using the banner=true prop.

### What is actually happening?
The alert displays as a warning with the icon.

---
If this is not a bug, can you please add a comment to the docs.

**Comment by benjycui** [comment]
Ref: https://github.com/ant-design/ant-design/pull/2600

It seems that it is by designed.

**Comment by afc163** [comment]
Should allow user to override it.
