### ISSUE TITLE
Modal component not work in my project

### ISSUE THREAD

**Issue by walkerqiao** [ant-design/ant-design#5802]
### Version
2.9.1

### Environment
macbook, chrome, ant-design

### Reproduction link
[https://github.com/walkerqiao/amazeui/blob/master/packages/tsapp/src/components/modal/Modal.tsx](https://github.com/walkerqiao/amazeui/blob/master/packages/tsapp/src/components/modal/Modal.tsx)

### Steps to reproduce
git rep: https://github.com/walkerqiao/amazeui/blob/master/packages/tsapp

I am learning TypeScript, and find ant-design is writing with it. So i clone the ant-design master code to my repo.

I used roadhog for my dev tool, and can run command 'npm run server' to see the demo.

Please keep the file
'https://github.com/walkerqiao/amazeui/blob/master/packages/tsapp/src/components/modal/Modal.tsx' same as ant-design master's, code as:

```
handleCancel = (e) => {
  const onCancel = this.props.onCancel
  if (onCancel) {
    onCancel(e)
  }
}
```
when i run the command, an error was raised:
```
Type '(e: any) => void' is not assignable to type '(()=> void) | undefined. 
```

I search more, and finally read the document: https://www.tslang.cn/docs/handbook/functions.html

I used the following code instead, it works.
```
handleCancel = (e?: any) => {
  const onCancel = this.props.onCancel
  if (onCancel) {
    onCancel(e)
  }
}
```

### What is expected?
Why ant-design can work with the code above, but i can't.

### What is actually happening?
```
Type '(e: any) => void' is not assignable to type '(()=> void) | undefined. 
```

**Comment by benjycui** [comment]
Upgrade your TypeScript first, see: https://github.com/ant-design/ant-design/blob/master/package.json#L142

Then, if you still meet this issue, create a PR for this.

**Comment by walkerqiao** [comment]
My typescript version is 2.2.2, ant it greater than yours.

**Comment by yesmeck** [comment]
`onClose`  has no parameters.

**Comment by walkerqiao** [comment]
I don't understand it. Yes, onClose has no parameters, but the function passed to it was handleCancel, providing a 'e' parameter, that's was the problem for me.

```
handleCancel = (e) => {
  this.props.onCancel(e)
}

...

return (
   <Dialog
      onClose={this.handleCancel}
      .....
   />
)
```

**Comment by yesmeck** [comment]
Please provide a minimal reproduction.

**Comment by walkerqiao** [comment]
Ah, i create a new repo: https://github.com/walkerqiao/tstemp

1. using atool-build cmd: it works and can compile the codes
2. using npm run build cmd: it can't work, due to the error aboving.

when i comment https://github.com/walkerqiao/tstemp/blob/master/src/components/modal/Modal.tsx#L101, and uncomment https://github.com/walkerqiao/tstemp/blob/master/src/components/modal/Modal.tsx#L102, npm run  build can work.

I think it may be the roadhog's bug, not sure.

**Comment by yesmeck** [comment]
It's not a bug of antd, you need figure this out by yourself, if you find any wrong type declaration, feel free to file a PR.

**Comment by walkerqiao** [comment]
Thank you very much, and I will find out the reason later. Yes, it's not a bug for antd. But outof the antd and atool-build, maybe a bug.
