### ISSUE TITLE
DatePicker select month & year will close panel unexpectedly

### ISSUE THREAD

**Issue by GravityMsc** [ant-design/ant-design#5804]
### Version
2.9.1

### Environment
win10最新，chrome最新  react react-dom 15.5.4

### Reproduction link
[http://none](http://none)

### Steps to reproduce
```
import { Button, Form, Input, DatePicker } from 'antd';

const FormItem = Form.Item;
class CptSearch extends React.Component {
    createForm = () => {
        const { getFieldDecorator } = this.props.form;
        const formItemLayout = {
            labelCol: { span: 8 },
            wrapperCol: { span: 15 },
        };
        return [
            <FormItem {...formItemLayout} key="id" label="车号">
                {getFieldDecorator('id', { initialValue: '123456' })(
                    <Input />,
                )}
            </FormItem>,
            <FormItem {...formItemLayout} key="date" label="日期时间">
                {getFieldDecorator('date')(
                    <DatePicker />,
                )}
            </FormItem>,
            <FormItem key="submit" >
                <Button type="primary" htmlType="submit">Submit</Button>
            </FormItem>,
        ];
    }
    handleSearch = (e) => {
        console.log('submit');
    }
    render() {
        return (
            <Form layout="inline" onSubmit={this.handleSearch}>
                {this.createForm()}
            </Form>
        );
    }
}
const SearchForm = Form.create()(CptSearch);
export default SearchForm;
```

### What is expected?

当点击日期选择器的年，面板变成日期选择；
当点击日期选择器的月，面板变成日期选择；

### What is actually happening?
当点击日期选择器的年或月，面板直接退出。

目前2.8.3并没有此现象

---
不好意思，因为版本问题没有办法通过codepen实现，所以我直接创建的issue，十分抱歉

**Comment by ddcat1115** [comment]
复制了这段代码，没能重现 😢

**Comment by GravityMsc** [comment]
@ddcat1115 版本符合么？我换成2.8.3就正常了，最新的2.9.1就不行···

**Comment by afc163** [comment]
codepen 里就是 2.9.1.

**Comment by GravityMsc** [comment]
@afc163 呃，好吧·····至少我换了之后是正常的，先这么用吧那就...打扰了

**Comment by ddcat1115** [comment]
就用的 2.9.1

**Comment by ddcat1115** [comment]
先关了。。。

**Comment by afc163** [comment]
重现了：https://ant.design/components/date-picker-cn/

我刚才重新部署了网站。

**Comment by afc163** [comment]
https://github.com/react-component/trigger/commit/b9bb1608f12a852837416e9735b703601645cf94

`rc-trigger@1.10+` 这里导致了问题。

**Comment by afc163** [comment]
Should affect all 2.x versions.

**Comment by benjycui** [comment]
> 目前2.8.3并没有此现象

@GravityMsc 回滚到 2.8.3 并重装依赖试试，理论上也有 bug

**Comment by huyansheng3** [comment]
2.8.3 and 2.9.1 all have this bug, **when click the year, the panel will close, but the selected date has not be changed.** the offical website demo is the same too! when will the bug be fixed?
![image](https://cloud.githubusercontent.com/assets/11534583/25211082/d59bbe0c-25b5-11e7-9ac4-a3edfb09d036.png)

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by GravityMsc** [comment]
@benjycui 是的，后来也发现2.8.3也有BUG，现在修复了么？我是直接拷贝之前一份正常的node_modules在使用。不过如果我要对你们的源码进行调试，只有从git上下载源码本地编译才可以么，有木有其他的方法···

**Comment by afc163** [comment]
`rm -rf node_modules && npm i`

**Comment by shenqihui** [comment]
2.11.1,2.11.0 版本重现了。

**Comment by shenqihui** [comment]
发现问题，试过 `rm -rf node_modules && yarn` ，最终败在 yarn 上，有一个lock file ，会确定一些版本。所以忽略上面的评论。

Just `rm -rf node_modules && rm yarn.lock && yarn`
