### ISSUE TITLE
input 的 placeholder 能否支持国际化

### ISSUE THREAD

**Issue by bobomanywb** [ant-design/ant-design#5805]
### What problem does this feature solve?
input 的 placeholder 支持国际化

### What does the proposed API look like?
input 的 placeholder 支持国际化

**Comment by ddcat1115** [comment]
https://ant.design/components/locale-provider/#Other-localization-needs

**Comment by ddcat1115** [comment]
Not relate to AntD, closed~

**Comment by bobomanywb** [comment]
好的谢谢
