### ISSUE TITLE
Select All option in table is not selecting all records across pagination

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#5806]
### Version
2.9.1

### Environment
OS : Windows 10, Browser: Chrome v56

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Can be easily reproducible at the ant design demo https://ant.design/components/table/

### What is expected?
On Clicking Select All option coming in dropdown near the select of table, should select all records across pagination.

### What is actually happening?
It is selecting only records of current page.

**Comment by afc163** [comment]
It is by designed. If you want to select all records, you should control `rowSelection.selectedKeys` by yourself.
