### ISSUE TITLE
Modal.confirm can support footer custom？

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#5811]
### What problem does this feature solve?
1、it can order confirm button and cancel button
2、custom button style
3、more button

### What does the proposed API look like?
footer: 'custom code'

**Comment by henryzp** [comment]
我目前想到的方案是基于antd写一个自己的confirm，不知道是否有更好的方案？

**Comment by afc163** [comment]
I suggest you writing your own confirm by Modal.

**Comment by henryzp** [comment]
@afc163 ，嗯嗯，谢谢

**Comment by NE-SmallTown** [comment]
If you look up the [src code](https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx#L54),you will find that it can't.But you can send a pr to add this feature.

But IMO,antd itself is not design for design whatever you want.In my project,I copy a lot of components and change it whatever I want(just keep logic code and based on react-component),you will find that this will be great both for you and antd.

**Comment by henryzp** [comment]
@NE-SmallTown 

thx，I know what you mean。

**Comment by henryzp** [comment]
@afc163 ，我昨晚想了一下，可以这样实现，你看看行不行？

提供一个参数，允许确定和取消按钮，对调位置。。

提供confirm的type参数，允许我注入Button的自定义type，让我修改css。。
