### ISSUE TITLE
凡是有浮层的组件，都可能存在的问题，位置错位！！！

### ISSUE THREAD

**Issue by wuyanwuyan** [ant-design/ant-design#5812]
### 带有浮层的组件，如datepicker，AutoComplete，popover等，都存在可能错位的问题！

      由于这类组件click或focus会显示另一部分的dom元素，而这部分的dom元素的层级是在另一个div上，相对于document原点的位置定位。

      如果组件在一个带有overflow内部有滚动条的元素中，100%会出现组件两部分内容错位现象。

<img width="801" alt="qq20170419-170154 2x" src="https://cloud.githubusercontent.com/assets/4576326/25172331/3e7429a2-2523-11e7-924e-efb94b280c5b.png">

**Comment by benjycui** [comment]
`getPopupContainer`
