### ISSUE TITLE
select组件BUG问题，上一个版本已经修复，这边版本又复现

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design#5813]
### Version
2.9.1

### Environment
macos

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
1.select 选择组件，在点击空白区域时，不能收回。
2.展开按钮太小，当点击 input 区域，展示下拉，并且input 获取当前输入焦点。

### What is expected?
1.select 选择组件，在点击空白区域时，不能收回。
2.展开按钮太小，当点击 input 区域，展示下拉，并且input 获取当前输入焦点。

### What is actually happening?
1.select 选择组件，在点击空白区域时，不能收回。
2.展开按钮太小，当点击 input 区域，展示下拉，并且input 获取当前输入焦点。

**Comment by yesmeck** [comment]
> select 选择组件，在点击空白区域时，不能收回。

重新安装 node_modules

> 展开按钮太小，当点击 input 区域，展示下拉，并且input 获取当前输入焦点

这个没看懂

**Comment by afc163** [comment]
你的 `What is expected?` 和 `What is actually happening?` 内容是一样的？
