### ISSUE TITLE
[Datepicker] Can not pick year and month.

### ISSUE THREAD

**Issue by ladjzero** [ant-design/ant-design#5816]
### Version
2.9.1

### Environment
chrome latest

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
1. active the datepicker
2. click year, select 2010
3. datepicker panel dismisses, 2010 was not picked!

### What is expected?
2010 picked

### What is actually happening?
datepicker panel dismisses, 2010 was not picked!

---
本地使用 antd-init，可以复现，现在官网文档也有这个问题了

**Comment by afc163** [comment]
trace #5816

**Comment by greateidea** [comment]
好的，我已经知道了。

**Comment by cauu** [comment]
+1
