### ISSUE TITLE
.d.ts is wrong, NO `default` in js, so should be NO `default` in .d.ts

### ISSUE THREAD

**Issue by yszou** [ant-design/ant-design#5819]
### Version
2.9.1

### Environment
node version: 6.10.2 ,  tsc version:  2.2.2 

### Reproduction link
[https://segmentfault.com/q/1010000009113867](https://segmentfault.com/q/1010000009113867)

### Steps to reproduce
Example for `Button` component.

If we write TypeScript code:

```typescript
import Button from 'antd/lib/button';
render(Button);
```

Using *tsc* to compile with `module: 'commonjs'`, so we can get:

```javascript
var button_1 = require("antd/lib/button");
render(button_1.default);
```

it's wrong , because there is no `default` in `button_1`. (to check the file `antd/lib/button/index.js`)

### What is expected?
We should write this TypeScript code:

```typescript
import * as Button from 'antd/lib/button';
render(Button)
```

So, the `antd/lib/button/index.d.ts` should be:

```javascript
import Button from './button';
export Button;
// NOT export default Button.
// Because in index.js, no DEFAULT. ( last line:  `module.exports = exports['default']` )
```

### What is actually happening?
Following current `index.d.ts` :

```typescript
import * as Button from 'antd/lib/button';
render(Button)
```

will not be allowed.

---
Relative issue:

- https://segmentfault.com/q/1010000009113867
- http://stackoverflow.com/questions/43399584/using-datepicker-via-typescript-import-and-webpack2

**Comment by benjycui** [comment]
A re-producible repo will be better.

**Comment by yszou** [comment]
@benjycui

 I created a branch .  https://github.com/yszou/issue/tree/ant-design-5819

**Comment by infeng** [comment]
```json
{
    "compilerOptions": {
        "target": "es6",
    }
}
```
Typescript compile target should be `es6` not `es5`.

**Comment by yszou** [comment]
Hi @infeng 

I know there are some way for solving the ERROR.

But I think we should talk about Why?

In another word, it must be `target: "es6"` just because of *AntD* , the wrong we talk about in this issue? That's a real problem.

**Comment by AlbertZheng** [comment]
@yszou you need to add `"allowSyntheticDefaultImports": true` under "compilerOptions".

**Comment by yszou** [comment]
@AlbertZheng 

https://github.com/yszou/issue/blob/ant-design-5819/tsconfig.json#L9

That it is, and this option don't change the result of compiled ( "This does not affect code emit, just typechecking." from TypeScript's document)

**Comment by yszou** [comment]
UPDATE:

why in `antd/lib/tree/index.js` , there is no `module.exports = exports['default']` at last line ? 

WHAT IS THE RULE ??

**Comment by bang88** [comment]
I think this line `module.exports = exports['default']` was added by babel plugins ?

**Comment by yszou** [comment]
@bang88 
It is true, I found `require.resolve('babel-plugin-add-module-exports')` in `atool-build/lib/getBabelCommonConfig.js`.

And, the plugin's project is https://github.com/59naga/babel-plugin-add-module-exports .

**Comment by bang88** [comment]
Ref： https://github.com/Microsoft/TypeScript/issues/2719

This is a problem when we have a default export. Don't use default export so we can remove the `allowSyntheticDefaultImports` config. But this maybe a breaking change, need more time review the existing code base.

Ping  @afc163

**Comment by paranoidjk** [comment]
If we remove default export，does that means uses must use named import？

**Comment by yszou** [comment]
@paranoidjk 
Do you mean 'remove `default` in .d.ts' , and let it become `export Button`?
So, in TypeScript, we should write `import * as Button from antd/lib/button` , and .js are unaffected by this.

**Comment by Bosee** [comment]
I also met this problem and solved it by require but lost type safety.

**Comment by afc163** [comment]
Try `allowSyntheticDefaultImports: true` in tsconfig.js

**Comment by kasztelan** [comment]
We need to reopen this discussion, setting `target: "es6"` is not a solution because it breaks other things like `ts-node`
