### ISSUE TITLE
Component Typescript type define wrong to import 'react'

### ISSUE THREAD

**Issue by snipking** [ant-design/ant-design#5821]
### Version
2.9.1

### Environment
OS: macOS 10.12.4, @types/react: 15.0.21, typescript: 2.2.2

### Reproduction link
[https://github.com/snipking/react-antd-webpack-error](https://github.com/snipking/react-antd-webpack-error)

### Steps to reproduce
in app.tsx, use following code

```
import * as Button from 'antd/lib/button';
```

compile code cause error

```
ERROR in /.../node_modules/antd/lib/button/button.d.ts
(2,8): error TS1192: Module '"/.../node_modules/@types/react/index"' has no default export.
```

And the `@types/react/index.d.ts` is

```
export = React; 
export as namespace React;

declare namespace React {
   ...
}
```

which don't have `export default`.

### What is expected?
in `antd/lib/button/button.d.ts`, the import React should be

```
import * as React from "react";
```

### What is actually happening?
```
import React from 'react';
```

In all component .d.ts

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design#typescript
