### ISSUE TITLE
table 设置scroll.y后theader和tbody的border无法对齐

### ISSUE THREAD

**Issue by IDrinkMoreWater** [ant-design/ant-design#5825]
### Version
2.9.1

### Environment
windows7 64-bit，Chrome  56.0.2924.87 (64-bit)

### Reproduction link
[http://codepen.io/anon/pen/VbeJKx](http://codepen.io/anon/pen/VbeJKx)

### Steps to reproduce
重现代码片段 http://codepen.io/anon/pen/VbeJKx

### What is expected?
table的头部和表格的边框对齐

### What is actually happening?
table的头部和表格的边框无法对齐

---
为什么table的滚动条不采用react-custom-scrollbars这种浮动隐藏式的滚动条，这样能避免滚动条占用空间引起表格列宽带计算出问题的情况

**Comment by IDrinkMoreWater** [comment]
![qq 20170420164243](https://cloud.githubusercontent.com/assets/13063062/25221672/911c2cac-25e8-11e7-87d8-ff3291615823.png)

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-header

<img width="437" alt="image" src="https://cloud.githubusercontent.com/assets/507615/25222366/da5b0788-25ea-11e7-8144-42450b550922.png">

**Comment by IDrinkMoreWater** [comment]
@afc163 我有尝试过，必须每列都设置width都写死（这样总宽度就写死了），但是网页窗口不可能不变化吧，多屏幕的情况呢，而且窗口一变化还是会错位；react-custom-scrollbars的滚动条替代方案是否可行？

**Comment by afc163** [comment]
1. 写成百分比。
2. 留一列自适应。

**Comment by maixing** [comment]
设置scroll.y后，需要设置每列占的比例，百分比。

**Comment by yeyuguo** [comment]
官方例子上的 demo 都是错位有问题的，居然没有人发现吗？只是错位的有点不明显而已， **表头分组** 这个[demo](https://ant.design/components/table-cn/#components-table-demo-grouping-columns) 真是有异常

**Comment by yeyuguo** [comment]
在线等解决方案....

**Comment by Emlw** [comment]
怎么隐藏右侧的滚动条？

**Comment by FgoPan** [comment]
any solution?

**Comment by damiss** [comment]
当设置固定表头、表头分组、左侧列冻结后，即使设置了每个column的宽度，表头和表格内容依旧不能对齐，请问有解决方案吗？

**Comment by syaivin** [comment]
@IDrinkMoreWater    你用这个 react-custom-scrollbars 替换了吗？我替换后表格对不齐，左右固定列也不跟着上下滚动，感觉这表格组件扩充好难啊~

**Comment by embracelong** [comment]
没有滚动条的情况应该是设置的比例超过的限定，根据width调下就能对齐了

**Comment by cike8899** [comment]
2019年了，有什么好的解决方案吗？

**Comment by afc163** [comment]
@cike8899 设 width。

**Comment by cike8899** [comment]
@afc163 设置了没用 

![image](https://user-images.githubusercontent.com/8089971/54013987-12fdff80-41b6-11e9-9b09-e19e3ac5d069.png)

**Comment by embracelong** [comment]
> @afc163 设置了没用
> 
> ![image](https://user-images.githubusercontent.com/8089971/54013987-12fdff80-41b6-11e9-9b09-e19e3ac5d069.png)

scroll x 的也设置下，不然按100%内容会挤到

**Comment by embracelong** [comment]
@cike8899 
scroll x 的也设置下，不然按100%内容会挤到

**Comment by afc163** [comment]
@cike8899 https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by cike8899** [comment]
```
columns={[
  ...
  render: (text, record) => (
    <div style={{ wordWrap: 'break-word', wordBreak: 'break-all' }}>
      {text}
    </div>
  ),
]}
```

按照上面的办法解决了大部分问题，但是还有漏网之鱼

![image](https://user-images.githubusercontent.com/8089971/54021228-9de8f500-41ca-11e9-8a9e-16d7e711c4b5.png)

**居然变窄了，还是不够完美**

**Comment by afc163** [comment]
你给的宽度不够啊，页头的 title 就超过宽度了。

**Comment by cike8899** [comment]
宽度设置大了，但是表格整个宽度又不够了，然后设置了横向滚动，马马虎虎解决了问题

![image](https://user-images.githubusercontent.com/8089971/54022891-7eec6200-41ce-11e9-91b7-760982e84adc.png)

**Comment by YYJay** [comment]
设置css ```  .ant-table-body: scroll  ```, 让滚动条始终显示.然后再设置滚动条样式
```
 ::-webkit-scrollbar-button {
  display: none;
}
::-webkit-scrollbar-thumb {
  min-height: 48px;
  background: #d2d2d2;
  background-clip: padding-box;
  border: 3px solid #fff;
  border-radius: 5px;
}

::-webkit-scrollbar-thumb:active {
  background: #888;
  border-width: 2px;
} 
``` 
达到滚动条背景与表格背景相同的效果,假装没有偏移
![image](https://user-images.githubusercontent.com/28727331/58405265-96ced600-8099-11e9-96cb-00b06478abdc.png)

**Comment by mqliutie** [comment]
设置了scroll.y就错位, 不设置就正常 或者scroll.y=0都正常

**Comment by mqliutie** [comment]
scroll y 不用antd的了, 自己重写样式, 参考https://stackoverflow.com/questions/23989463/how-to-set-tbody-height-with-overflow-scroll

**Comment by mqliutie** [comment]
直接设置 table的样式 table-layout:fixed;

**Comment by jackywq** [comment]
> 直接设置 table的样式 table-layout:fixed;

设置table-layout:fixed; 表格最后几列也会错位的

**Comment by 946629031** [comment]
2021年了，有好的解决办法了吗

**Comment by 946629031** [comment]
实测解决办法：

**Comment by 946629031** [comment]
实测解决办法：
出现这种问题的原因，是因为至少有一列的数据的宽度  是超出你设定的 Column.width，就是因为这个原因 导致其它的 Column 错位。

解决办法：除了这一列 Column.width 不设置 (自适应)，其它的 Column 给定宽度就行。

**Comment by hanx316** [comment]
我的场景是 scroll x y 都有设置，另外 fix left 两列，解决方案：
留一列自适应让 scroll.y 的情况下不会对齐错位，另外需要确保 scroll.x > 设置 column 的宽度和

**Comment by Dzhaolei** [comment]
2022年了，有好的解决办法了吗

**Comment by callcter** [comment]
2023 了，问题被关了都没看明白怎么解决

**Comment by afc163** [comment]
@callcter @Dzhaolei  给我重现我帮你改好

**Comment by qyaaaa** [comment]
固定了header和最右边一列，ant-table-cell-scrollbar 会随着屏幕缩放，但body处的滚动条不会缩放，导致header和body宽度不一致进而错位，有什么好的解决方案吗。

**Comment by danferj** [comment]
2024年了，才碰到这个问题，搜索进来心凉半截。我给2024年打个卡吧！

**Comment by BigRockCandy** [comment]
2024年打卡 同遇到问题

**Comment by yaince** [comment]
好 2024了 这个问题还存在

**Comment by afc163** [comment]
@qyaaaa @danferj @BigRockCandy @yaince 给个重现我帮你改好

**Comment by yaince** [comment]
> @qyaaaa @danferj @BigRockCandy @yaince 给个重现我帮你改好

怎么给你重现啊

**Comment by yaince** [comment]
> > @qyaaaa @danferj @BigRockCandy @yaince 给个重现我帮你改好
我最后是在table外层加了个高度  不让table溢出产生滚动条 然后内部再加scroll

**Comment by afc163** [comment]
@yaince https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F

**Comment by tanggd** [comment]
2024年打卡 同遇到问题，问题未解决

**Comment by HappyBa999** [comment]
> 设置td的宽度就可以对齐了

**Comment by HappyBa999** [comment]
完美解决，Tables属性：
 <Table
      :columns="columns"
      :data-source="reportListData"
      :scroll="{ x: '1500px', y: 'calc(100vh - 210px)' }"
      :pagination="false"
      size="small"
      rowKey="recordID"
      bordered>
</Table>
，设置td固定宽
.ant-table-tbody > tr > td {
    box-sizing: content-box;
    width: 20px;
}

![Uploading 1730342047300.jpg…]()

**Comment by HappyBa999** [comment]
![1730342047300](https://github.com/user-attachments/assets/32653a8c-b71c-482f-8ab0-2b74f9757100)
![1730342133591](https://github.com/user-attachments/assets/3e50baef-222f-4789-9185-7ced91564abd)
![1730342167513](https://github.com/user-attachments/assets/2de6f0d8-8936-4983-a141-a947900d5469)

**Comment by yaince** [comment]
> 设置表格td的宽定死，我刚开始在columns里设置没效果，在样式里设置，再加上box-sizing: content-box; 完美解决 ![1730342047300](https://private-user-images.githubusercontent.com/9279696/381802905-32653a8c-b71c-482f-8ab0-2b74f9757100.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDMxMDUsIm5iZiI6MTczMDM0MjgwNSwicGF0aCI6Ii85Mjc5Njk2LzM4MTgwMjkwNS0zMjY1M2E4Yy1iNzFjLTQ4MmYtOGFiMC0yYjc0Zjk3NTcxMDAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDI0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODIzNjU2YjQzNjZkMzFjNGFjYjNjNzhhOWFkMmEzYTI1ZDU1OTQ1ZmUxYzA3NTZmNDJjYTkyNDFkM2JhMTRiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.t6wLauj6mH4fxYya1nC2_5D24kpvp5BpkmEiOphxx3k) ![1730342133591](https://private-user-images.githubusercontent.com/9279696/381803035-3e50baef-222f-4789-9185-7ced91564abd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDMxMDUsIm5iZiI6MTczMDM0MjgwNSwicGF0aCI6Ii85Mjc5Njk2LzM4MTgwMzAzNS0zZTUwYmFlZi0yMjJmLTQ3ODktOTE4NS03Y2VkOTE1NjRhYmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDI0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFlNzhlNGYyMTdlMzQwZDYyOWE5YjM3ZTljMGE3MTdlMzEzYjkxMjQ4YWM4OTJhYTZjZTQyMjIwZWM5NTM3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qJnTGh8L89IjTowpSOr4nyg4h7EDtmc0Fa5TJ1L_Xo4) ![1730342167513](https://private-user-images.githubusercontent.com/9279696/381803115-2de6f0d8-8936-4983-a141-a947900d5469.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDMxMDUsIm5iZiI6MTczMDM0MjgwNSwicGF0aCI6Ii85Mjc5Njk2LzM4MTgwMzExNS0yZGU2ZjBkOC04OTM2LTQ5ODMtYTE0MS1hOTQ3OTAwZDU0NjkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDI0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhiNmUwYjljMzEwODViOGFiYmUxNWE3MjU0OTJmOWM5OTdhODA3MmU4MTA4YjhhZDgwMmY5MWM5MTRkNjY5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NjZsFRY7AwCmxeXa-3g7t282yNZv7YJzy07v_p1uQmg)

但你这个是滚动条的宽度和antd默认的那个一致 所以才不会错位  我滚动条的宽度就是要比这个小 所以才会导致错位的问题   感觉是里面样式计算哪里写死了 没有做自适应

**Comment by mercurywang** [comment]
2025 还没解决，我留个言，好做证据。

**Comment by Fracizz** [comment]
实测解决
为每一个列设置好width，然后增加样式
.ant-table {
  table-layout: fixed;
}

![Image](https://github.com/user-attachments/assets/fbfbde51-6594-4bbc-8465-986ac66be0f8)

**Comment by xinsin-star** [comment]
2026 还没解决，我留个言，好做证据。
