### ISSUE TITLE
date-picker错误

### ISSUE THREAD

**Issue by longgee555** [ant-design/ant-design#5830]
### Version
2.9.1

### Environment
win10 chrome

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
通过点击年份和月份选择年份和月份，而不是通过左右箭头修改，此时选择后无效。（ps: 为什么不管是date-picker还是range-picker，选择后都会直接关闭pick框？）

### What is expected?
选择后有效，且最好不要关闭pick框

### What is actually happening?
选择后无效

**Comment by afc163** [comment]
fixed in #5804
