### ISSUE TITLE
Select mode=tags with tokenSeparators crashes on 2 consecutive token keypresses

### ISSUE THREAD

**Issue by queimadus** [ant-design/ant-design#5831]
### Version
2.9.1

### Environment
osx 10.11.6, Chrome 57.0.2987.133

### Reproduction link
[http://codepen.io/anon/pen/rmeeab?editors=001](http://codepen.io/anon/pen/rmeeab?editors=001)

### Steps to reproduce
`Select` in `mode="tags"` with `tokenSeparators={[" "]}` set ("space" for example). Pressing the token key (space) twice in a row throws an exception: `"Uncaught Error: must set key for <rc-animate> children"`, and breaks the component.

### What is expected?
Ignore the token keypresses if the current tag value is empty.

### What is actually happening?
An exception is being thrown and the component stops working.

---
Tested this in the demo page: https://ant.design/components/select/#components-select-demo-automatic-tokenization and it displays the same behaviour. The token defined there is ",". Pressing "," twice crashes the component.

**Comment by yesmeck** [comment]
@queimadus Try reinstall node_modules.
