### ISSUE TITLE
Input.Group with inner AutoComplete style bug

### ISSUE THREAD

**Issue by queimadus** [ant-design/ant-design#5832]
### Version
2.9.1

### Environment
osx 10.11.6, Chrome 57.0.2987.133

### Reproduction link
[http://codepen.io/anon/pen/OmNNpz?editors=001](http://codepen.io/anon/pen/OmNNpz?editors=001)

### Steps to reproduce
Set a `<Input>` and a `AutoComplete` inside a `Input.Group`. CSS isn't autocomplete-select aware.

### What is expected?
The `AutoComplete` to display correctly inside a `Input.Group`

### What is actually happening?
The css rules for the `Input.Group` isn't targeting the `AutoComplete` inner input component

**Comment by queimadus** [comment]
`Cascader` component isn't being styled correctly as well.

Updated example:
http://codepen.io/anon/pen/OmNNpz?editors=001

**Comment by benjycui** [comment]
ping @ddcat1115 https://github.com/ant-design/ant-design/issues/5832#issuecomment-296145958

**Comment by afc163** [comment]
ping @ddcat1115
