### ISSUE TITLE
AutoComplete is not being decorated properly within a Form

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#5834]
### Version
2.9.1

### Environment
mac sierra, chrome latest

### Reproduction link
[http://codepen.io/kossel/pen/LyNyvy?editors=001](http://codepen.io/kossel/pen/LyNyvy?editors=001)

### Steps to reproduce
Put AutoComplete into getFieldDecorator and do form validation

### What is expected?
The border color gets decorated correctly just like any input

### What is actually happening?
the border-color style get overwrited by something (still haven't found)

**Comment by benjycui** [comment]
I think that you can fix this @kossel , could you create a PR to fix it? Thanks.

**Comment by kossel** [comment]
I just did a quick look, looks like it is because `.ant-select-auto-complete.ant-select .ant-input` has more specificity than `.has-error .ant-input,`  (3 vs 2) I can PR I think

**Comment by kossel** [comment]
here https://github.com/ant-design/ant-design/pull/6018
