### ISSUE TITLE
getFieldDecorator with nested field format is not allowing arrays of objects to setFieldsValue

### ISSUE THREAD

**Issue by mkrn** [ant-design/ant-design#5835]
### Version
2.9.1

### Environment
Mac OS, chrome, react ^15.4.2

### Reproduction link
[http://codepen.io/ffab00/pen/wdGrVQ](http://codepen.io/ffab00/pen/wdGrVQ)

### Steps to reproduce
When adding a getFieldDecorator for a field inside array of objects it prevents setFieldsValue from saving.
This makes it hard to create repeatable sections.

Open codepen link, 
Click add button multiple times, 
it will not add more section, 
Remove line 36 `{form.getFieldDecorator('pumps[' + index + '].make', { })(<Input />)} `  
And sections will be added

### What is expected?
Expected to be able to add multiple sections of fields in array field.

### What is actually happening?
New objects are not pushed to array by `setFieldsValue` when `getFieldDecorator` for nested field is present in `render`

---
I was trying to create a form with repeatable groups of fields (array of objects).
Would appreciate working examples.
Followed this example initially https://github.com/ant-design/ant-design/blob/master/components/form/demo/dynamic-form-item.md  but extended it to allow multiple fields in each array/object. 

May be related to https://github.com/react-component/form/pull/48

**Comment by mkrn** [comment]
@benjycui Do you know any workarounds or what's causing it? I could help fix it.

**Comment by mkrn** [comment]
I've been able to debug it and the problem is here:
https://github.com/react-component/form/blob/master/src/createBaseForm.js#L372-L374

In setFieldsValue if you're setting a value of array to be an array with an extra element, that element and it's children are not in virtualPaths, therefore their values are never set..

To workaround this problem I do this:


```
    const pumps = getFieldValue('pumps');
    const nextPumps = pumps.concat({});
    // Automatically initialize next object:
    getFieldDecorator(`pumps[${nextPumps.length - 1}]`, { initialValue: {} });

    setFieldsValue({
      pumps: nextPumps,
    });
```

**Comment by mkrn** [comment]
Now removing an item from array doesn't work 
```
remove = (k) => {
    const { form } = this.props;
    const { getFieldValue, setFieldsValue } = form;
    const pumps = getFieldValue('pumps');

    setFieldsValue({
      pumps: pumps.filter((key, index) => k !== index),
    });
  }
```

**Comment by plandem** [comment]
probably same issue:
https://github.com/react-component/form/issues/73

In my case - if custom component works with arrays, then I have to provide **initialValue** manually.

**Comment by FoxxMD** [comment]
I'm experiencing the same problem. I can add new fields using the same method @mkrn supplies but not remove

**Comment by zhongkai** [comment]
这个问题解决了么？或者有什么办法，能让一个数组源的项目能够展示出来，并且可以动态的增删呢？
急~

**Comment by reAsOn2010** [comment]
I am encountering the same issue. Hope to fix~

**Comment by FoxxMD** [comment]
Will there be any work on this for antd-3?

**Comment by FrendKao** [comment]
I got a way to solve this:
 
```
const columns = this.props.form.getFieldValue('columns');
    const newColumns = columns.map((item, idx) => {
      if(idx === index) {
        return Object.assign({}, item, {name: value});
      }

      return item;
    });

    this.props.form.setFieldsValue({
      columns: newColumns,
    });
```

**Comment by iceOolongTea** [comment]
I am encountering the same issue.
antd version 2.11.2
@benjycui  Any advice about this problem?Maybe  use `key${index}` to replace nested field format?

**Comment by benjycui** [comment]
Don't use nested fields feature now, it's a mistake.

**Comment by bkbabydp** [comment]
@mkrn @benjycui  Encountering the same issue 2. Should we fix this?

**Comment by blackcater** [comment]
Anything update?

**Comment by llermaly** [comment]
hey @mkrn could you please attach a complete example for your solution? 

Im getting: Must call `getFieldProps` with valid name string!

Thanks!!

**Comment by Kaijun** [comment]
I am aslo encountering the same issue

**Comment by Kaijun** [comment]
I am aslo encountering the same issue

**Comment by benjycui** [comment]
WIP, trace: https://github.com/react-component/form/pull/112
