### ISSUE TITLE
展示例子中：tree 拖动后顺序出现错误

### ISSUE THREAD

**Issue by wishflyer** [ant-design/ant-design#5837]
### Version
2.9.1

### Environment
window 7 ,chrome 

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
拖动示例 中：
拖动0-0-0-2 到0-0-0-0后面，出现 0-0-0-2跑到0-0-0-0前面了
我发现，只要是拖动到后面的，都会显示到该元素的前面一个位置

展示代码：ar.splice(i, 0, dragObj); 这句需要修改

### What is expected?
正常来说，拖动0-0-0-2 到0-0-0-0后面，应该出现 0-0-0-0 然后是0-0-0-2

### What is actually happening?
拖动0-0-0-2 到0-0-0-0后面，出现 0-0-0-2跑到0-0-0-0前面了，顺序有问题

---
展示代码：ar.splice(i, 0, dragObj); 这句需要修改

另外，是否能判断，是拖动到元素的前面还是拖动到元素的后面位置？

**Comment by twisger** [comment]
You can judge it by info.dropToGap and info.dropPosition.

**Comment by knilink** [comment]
The **dropPosition** was extremely confusing. Apparently it confused the one who wrote the example.
Need more description.
