### ISSUE TITLE
Bug: Small bug with badge page in online docs 

### ISSUE THREAD

**Issue by gudh** [ant-design/ant-design#5838]
First of all, thanks for building antd, I am amazed at how fantastic it is! ✨

Here I found a small bug with [badge page](https://ant.design/components/badge/) in the online docs

The default Switch value is `false`, however the default show value is `true`

![snip20170421_1](https://cloud.githubusercontent.com/assets/3378031/25262503/80bc688e-2626-11e7-9c21-96118853abc4.png)

change default `show` value to `false` will fix it:

```
  state = {
    count: 5,
    show: false, // <- the default value should be false
  }
```

Keep up great work! 🌷

**Comment by yesmeck** [comment]
@gudh Could you open a PR?
