### ISSUE TITLE
When DatePicker is slided up , Can this  show two or more mouths once time ?

### ISSUE THREAD

**Issue by wangzhongquan** [ant-design/ant-design#5841]
### What problem does this feature solve?
When we use DatePicker ,, maybe  we needs Datepicker show two or more mouths once time , it look like datepicker 
 in Jquery UI , like this 
http://jqueryui.com/datepicker/#multiple-calendars

### What does the proposed API look like?
It's a good idea to privide the function  from Datepicker show two or more mouths once time

**Comment by afc163** [comment]
Sorry, we don't plan to support it.
