### ISSUE TITLE
希望Notification 在省略description情况下，message居中

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#5846]
### What problem does this feature solve?
Message 借用 Notification 的展现形式，但是内容上没那么需要显示的详情信息

### What does the proposed API look like?
notification[status].({message, description: false)

**Comment by afc163** [comment]
```jsx
notification.info({
  message: <div style={{ textAlign: 'center' }}>message</div>,
})
```

**Comment by yangbin1994** [comment]
实际上我想说的是垂直居中~

**Comment by afc163** [comment]
notification.info({
  message: <div style={{ textAlign: 'center' }}>message</div>,
})

**Comment by afc163** [comment]
这个之前考虑过，但是多行标题的情况不好搞。

<img width="363" alt="2017-04-21 19 28 36" src="https://cloud.githubusercontent.com/assets/507615/25275613/c3f49214-26c8-11e7-9bb2-f61aa6f596e7.png">

**Comment by yangbin1994** [comment]
我觉得可以使用description为boolean类型来针对

**Comment by yangbin1994** [comment]
我觉得可以description使用boolean类型来针对一下~

**Comment by afc163** [comment]
都是没有 description 的情况，标题对于是否换行的样式不一样，这一点比较麻烦。

**Comment by NE-SmallTown** [comment]
Sorry for that I don't know much about css,so I don't consider it too deeply,probably it's not the best solution.And if I understand correct,if you just want one line and multiple lines can in the middle and just use **one** css class.Yes,you can do that. .e.g. :

```
<div class="ant-notification-notice-with-icon" style="position: relative;">
  <span class="ant-notification-notice-icon" style="top: 50%;position: absolute;transform: translateY(-50%);">
    <i class="anticon anticon-smile-circle" style="color: rgb(16, 142, 233);"></i>
  </span>
  
  <div style="margin-left: 48px;">
  	<div class="ant-notification-notice-message">Notification Title</div>
  	<div class="ant-notification-notice-description">
      This is the content of the notification. This is the content of the notification. This is the content of the notification.
  	</div>
  </div>
</div>
```

![](http://i2.muimg.com/567571/e1dea1a6f194b007.jpg)

![](http://i2.muimg.com/567571/7719152823db3a9c.jpg)

**Comment by yangbin1994** [comment]
target => icon,   thank you for your train of thought and the CSS is very awesome, 3q

**Comment by yangbin1994** [comment]
![image](https://cloud.githubusercontent.com/assets/12080165/25281385/d11fa23c-26df-11e7-9f61-c39f803043e2.png)
effect of multiple lines is not bad, but for me message usually is not too long, nice

**Comment by yangbin1994** [comment]
`.ant-notification-notice-with-icon {
    >i {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
    }
}

.ant-notification-notice-with-icon {
    .ant-notification-notice-message {
        margin-top: 4px;
    }
}`

**Comment by yangbin1994** [comment]
```
.ant-notification-notice-with-icon {
    >i {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
    }
}

.ant-notification-notice-with-icon {
    .ant-notification-notice-message {
        margin-top: 4px;
    }
}
```

**Comment by afc163** [comment]
Icon should not be vertically centered, it is against our design spec.

**Comment by afc163** [comment]
Actually, notification is used to be like @NE-SmallTown described in antd@1.x

http://1x.ant.design/components/notification/

**Comment by NE-SmallTown** [comment]
Ye,sorry for forgoting to say,that't why I don't suggest him to send a pr because I am not sure it is what antd really needs.And I make it by set *style* rather than *class* is because hope that if it is not a good choice for antd,you can just override the *style* to realize your goal.

**Comment by afc163** [comment]
Found a **very tricky** solution inspired by http://stackoverflow.com/a/22901203/3040605 😃 

http://jsfiddle.net/jrfcjhmm/

**Comment by afc163** [comment]
![1](https://cloud.githubusercontent.com/assets/507615/25288620/b984898a-26f8-11e7-9f4f-793979db09fb.gif)

Works like magic and it is a pure css workaround!
