### ISSUE TITLE
Table rows are re-rendered when datasource is strictly equal

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#5856]
### Version
2.9.1

### Environment
osx 10.10.5 with Chrome 57

### Reproduction link
[https://codepen.io/foxxmd/pen/GmqojV](https://codepen.io/foxxmd/pen/GmqojV)

### Steps to reproduce
* Create a `<Table/>` inside a Component `<X>` that receives 
  * a prop for the table `dataSource` (ex, `list`)
  * props not for table
* Update any props for `<X>` that are not `list`

To see what is re-rendered using the provided codepen open the browser console and click "Run" again.

### What is expected?
Since `this.props.list === nextProps.list` I would expect that `<Table>` would not re-render any `<TableRow>` or `<TableCell>` components

### What is actually happening?
All `<TableRow>` and `<TableCell>` components are re-rendered.

---
After reading (google translating) these issues

* https://github.com/ant-design/ant-design/issues/2884
* https://github.com/ant-design/ant-design/issues/2029#issuecomment-233841928
* https://github.com/ant-design/ant-design/issues/2484#issuecomment-234860010
* https://github.com/react-component/table/pull/96

I was under the impression the re-render was due to custom `render` functions in the `columns` properties but the reproduced codepen verifies that the re-render occurs regardless.

This causes a huge performance hit even when not interacting with the table since the table re-renders *any* time props are updated. [These are the performance metrics](https://i.imgur.com/d8Obgai.png) for a 40 row, 6 column table in my app.

[Additionally adding `rowSelection` to the `<Table>` causes *all* checkboxes to have DOM operations performed on them.](https://codepen.io/foxxmd/pen/vmKLgw) I'm not sure if this is related to the re-renders specifically but its also a huge performance hit.

**Comment by yesmeck** [comment]
Hello @FoxxMD , if you don't want table re-render, you should implement `shouldComponentUpdate` in `SubComponent` by yourself.

For the second question you mentioned, it is React's bug, see https://github.com/facebook/react/issues/7290 

Sorry for the delayed response.

**Comment by yesmeck** [comment]
Going to close this since not actions can be token.

**Comment by FoxxMD** [comment]
No problem thanks for the response. Yeah I ended up using `onlyUpdateForKeys` from `recompose` and wrapping the table. Good to know about the checkbox bug,

**Comment by qhxin** [comment]
@FoxxMD how did u use `onlyUpdateForKeys` to wrap the `Table` ? thank u.

**Comment by FoxxMD** [comment]
I did a few things because I found even more props on `Table` were causing the whole component to re-render when I didn't need it to:

* Styled components to emulate DOM wrapping `Table` and `Title` component of `Table`
* So `Title` component is updated separately from `Table` because my scenario has components in `Title` [re-rendering based on row selection](https://i.imgur.com/8ZR5GDj.png) but this didn't require re-rendering every row in `Table` (since data was the same)

```js
import React from 'react';
import { Table, Spin } from 'antd';
import styled from 'styled-components';
import { onlyUpdateForKeys, pure, compose } from 'recompose';
import { omitProps } from '../../../../Sites/new-ff-react/app/utils/HocUtil';

// styled components to emulate Table and title part of Table
const StyledDiv   = styled.div`
// styling
 `;
const StyledTitle = styled.div`
// styling
`;

const enhance = props =>
	<StyledTitle>{props.children}</StyledTitle>;
const Title   = onlyUpdateForKeys( [ 'children' ] )( enhance );

const enhancedWithTitleTable = compose(
	omitProps( [ 'title', 'loading' ] ),
	onlyUpdateForKeys( [ 'dataSource', 'pagination', 'progressingIds', 'loading', 'expandedRows', 'columns', 'rowSelection' ] )
);

const enhancedTable = compose(
	omitProps( [ 'title' ] ),
	onlyUpdateForKeys( [ 'dataSource', 'pagination', 'progressingIds', 'loading', 'expandedRows', 'columns', 'rowSelection' ] )
);

const RealPureTable          = enhancedTable( Table );
const RealPureTableWithTitle = enhancedWithTitleTable( Table );

const PureTable = ( props ) =>{
  if(props.noTitle) {
	return <RealPureTable {...props} />;
  }
  return (<Spin spinning={props.loading}>
	<StyledDiv>
	  <Title>{props.title}</Title>
	  <RealPureTableWithTitle {...props} />
	</StyledDiv>
  </Spin>);
};

export default pure( PureTable );
```
Additionally, when using `PureTable`, I use `createSelector` from [reselect](https://github.com/reduxjs/reselect#createselectorinputselectors--inputselectors-resultfunc) to provide data to  the `columns` prop because it was also causing a re-render of the whole table even when the data was equal (but not the exact same object)

```js
import React from 'react';
import { createSelector } from 'reselect';
import { Input, Tooltip } from 'antd';
import editable from '../components/Editable/EditableInputHOC';
import PureTable from '../components/Table/PureTable';

const EditName = editable()( Input );

class Container extends React.Component {
  construct( props ){
	super( props );
	
	this.columnsSelector = createSelector(
		p => p.lexicon,
		p => p.merchants,
		p => p.canEdit,
		( lexicon, merchants, canEdit ) => [ {
		  title: 'Id',
		  dataIndex: 'id',
		},
		  {
			title: 'Merchant',
			dataIndex: 'merchant.id',
			render: ( id ) =>{
			  const merchant = merchants.find( x => x.id === id );
			  return merchant === undefined ? id : merchant.name;
			},
		  },
		  {
			title: 'Name',
			dataIndex: 'name',
			render: ( name, record ) =>{
			  if(canEdit) {
				return (<EditName editable
								  display={name}
								  defaultValue={name}
								  style={{ width: '80%' }}
								  onChange={val => this.handleSkuNameChange( val, record.id )}/>);
			  }
			  return name;
			},
		  },
		  {
			title: 'Item Count',
			dataIndex: 'productCount',
		  }
		] );
  }
  
  render(){
	return (<PureTable columns={this.columnsSelector( this.props )}/>);
  }
}
```

**Comment by hansololai** [comment]
@FoxxMD Just out of curiosity, you care about performance so much, you must have figured out a way to only rerender to updated row when only one row of the dataSource is updated? I have a table with 200 rows, and it rerenders every time one row is updated. I know just because they called "render()" does not mean the actual DOM is also updated, but it still a little laggy. Do you know how to solve it? Thanks

**Comment by fgiarritiello** [comment]
How did you guys solve the render performance issue? Any help would be greatly appreciated

**Comment by FoxxMD** [comment]
@fgiarritiello I am still using the solution I outlined above and have had acceptable performance in a production environment. Basically, wrapping the `<Table/>` component in a HOC that acts as a "componentShouldUpdate" for the whole component did the trick for me.

**Comment by fgiarritiello** [comment]
@FoxxMD thanks for your answer. I implemented your solution but I don’t notice any improvements when the table has 100+ rows and when I click to expand the row or to select using the checkbox. The lag is often 2 seconds which makes the table unusable

**Comment by PaulPCIO** [comment]
Having the same issue, 100+ records adds about 2 seconds delay.

**Comment by AsuraKev** [comment]
its 2023, performance isssue still present :(
