### ISSUE TITLE
为Input加上一个清空输入的功能

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#5857]
### What problem does this feature solve?
解决清空输入的问题

### What does the proposed API look like?
在Input输入框中输入内容或已经有内容时，当鼠标移动到输入框上时，在输入框末尾显示一个‘x’的图标，点击这个图标实现清除输入框内容的功能。和日期选择框的效果相同

**Comment by afc163** [comment]
https://ant.design/components/input-cn/#components-input-demo-presuffix

**Comment by chj-damon** [comment]
@afc163 上面的这个配置并不是我的需求，我是想要实现DatePicker里面，当输入框有值的情况下，鼠标hover的时候出现一个清除图标，点击清除图标，清空Input输入框中的值。当然，可以通过自己实现的方式处理，但是，Input组件如果能自带这样的效果就最好了。

**Comment by afc163** [comment]
建议用 suffix 自行封装就好。

**Comment by jiechud** [comment]
@afc163 @chj-damon  用 suffix 封装，如果 Input 组件要集成 Form 要怎么做呢？
