### ISSUE TITLE
有没有 ant-disign 大型项目的例子、大型 demo ?

### ISSUE THREAD

**Issue by shenqihui** [ant-design/ant-design#5859]
### What problem does this feature solve?
留意到 ant-disign 和 dva ，觉得非常适合目前我所维护开发的公司的一个大型管理后台。
旧系统是使用 angular 就行开发。
然后鉴于各种需求，觉得 ant 更适合目前系统的发展方向，所以想通过自己业余时间，将系统迁移这套方案上。
不过目前在尝试迁移时，遇到各种进展障碍。

所以希望能够开发一个大型的 demo 例子，带上边侧导航、路由器、多个模块的列表页面/详情页面/更新页面/新建页面 等等，

---

下面是我目前的状况：

目前尝试迁移进度，导航、路由都弄好。但是模块的增删改查之类的没弄好。（后端为基本遵循 restful 形式的 api）

举个模块例子：
目前设计的业务逻辑基本上也是 restful 的操作，列表页面/详情页面/更新页面/新建页面 等等，
teacher 模块举例
```
/teacher/  列表页， 包含一个 delete 的操作按钮。
/teacher/${id} // 详情页面
/teacher/${id}/edit // 修改页面
/teacher/add // 新增页面
```

其中，列表页就存在很多阻碍
包含列表也头部涉及搜索， 例如 [https://ant.design/components/form-cn/#components-form-demo-advanced-search](https://ant.design/components/form-cn/#components-form-demo-advanced-search)。

这样的高级搜索，但是这样的高级搜索例子中，只包含了简单的 antd 例子。

于是我参考[select搜索用户](https://ant.design/components/select-cn/#components-select-demo-select-users)进行了 select 的封装处理，导出并放进 FormItem 里面，设置了 getFieldDecorator 等等，最终通过 form.getFieldsValue() 得到的只是一个 `{name: undefined}` 的对象，请问该如何设置自定义组件供 formItem 使用？

另外，详情页面，涉及 redux 数据等方面数据的处理又是阻碍。（本人为 react 新手）

---

### What does the proposed API look like?
一个大型 demo 例子。包含 边侧导航、路由器、多个模块的列表页面/详情页面/更新页面/新建页面 等等。

其中，模块列表页面，包含外键 select 的头部搜索。详情页面 redux 的数据交互等等。

**Comment by yesmeck** [comment]
参考 #129 #477

**Comment by zjafei** [comment]
https://console.zhgcloud.com/

**Comment by afc163** [comment]
Form
