### ISSUE TITLE
文本域的表单校验无法重置

### ISSUE THREAD

**Issue by whb101** [ant-design/ant-design#586]
文本域的表单校验无法重置

**Comment by afc163** [comment]
http://ant.design/components/validation/#demo-basic

建议按 http://dwz.cn/2dJ2mg 格式报告问题。

**Comment by whb101** [comment]
**问题描述**

文本域的表单校验无法重置

**发生环境**

- antd 版本：0.10
- 操作系统及版本：windows
- 浏览器及版本：谷歌最新版
- 在线演示地址：http://ant.design/components/validation/#demo-basic

**Comment by afc163** [comment]
我这里测试未能重现问题。

**Comment by afc163** [comment]
指的是 textarea 没有重置吗，好的重现了，应该是个 bug。

**Comment by whb101** [comment]
什么时候能发布到npm上面呢

**Comment by simaQ** [comment]
这只 BUG 我看下，至于发布到 npm 上，让偏右老师评估下吧，因为这里大多是 antd 样式的封装，所以我直接抱了antd 的大腿。
