### ISSUE TITLE
Modal对话框能不能增加弹出多个窗口不带底部透明黑色背景，并带有拖动功能啊

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#5865]
### What problem does this feature solve?
我们企业开发有好多需要需要弹出多个窗口来操作，比如，我们一个产品我要打开二或三个窗口来对比一下内容，这里就需要二个或三个弹出窗口，并带有拖动功能，方便操作并对比，还有我们又有另外一个需求，在当前弹出的对话框里我还需要弹出另外一个对话框来选择列表内容并把id带回来，这时也要弹出多个窗口出来，并带有拖动效果，好查看内容，还希望每打开一个窗口我可以传参数过去，关闭的时候能也能带参数回来.

### What does the proposed API look like?
这个你们官方定，希望弹出的窗口有查找带回来的api更好

**Comment by afc163** [comment]
建议自行封装。

**Comment by chendonghai** [comment]
官方在现有的modal上面扩展起来是不是更好,更方便啊
