### ISSUE TITLE
Enable i18n for placeholders and FieldDecorator messages among others

### ISSUE THREAD

**Issue by enzolutions** [ant-design/ant-design#5866]
### Version
2.9.2

### Environment
OS X, Chrome, React Intl

### Reproduction link
[https://github.com/enzolutions/antd-intl-demo](https://github.com/enzolutions/antd-intl-demo)

### Steps to reproduce
```
$ git clone git@github.com:enzolutions/antd-intl-demo.git
$ npm run dev
$ npm run start
```

Open your browser at page **http://127.0.0.1:8000/**

You could see the input have a [object object] text inside as you can see in the following image

<img width="345" alt="antd-intl-incompatibility" src="https://cloud.githubusercontent.com/assets/907914/25319842/003da972-28e5-11e7-838a-57af0bcce05e.png">

### What is expected?
Field decorator message and input placeholder could be translated in the same way the Form Item label is translated

### What is actually happening?
The translation object is not processed and the object type is rendered as string

---
I tried also with another i18n library **https://github.com/vazco/meteor-universe-i18n** with the same behavior.

The Antd library must be objected to enable those elements and similar accept object to enable a full translation

**Comment by afc163** [comment]
https://github.com/yahoo/react-intl/issues/749#issuecomment-265600521

**Comment by enzolutions** [comment]
Hi @afc163 

I don't think so this must be closed because the solution is specific for Intl, would be better if Antd in those properties accept any react object, in that way Ant Design would be compatible with any i18n library.

Another person mentioned that in the issue that you linked.

If you could provide a point of view of an architecture desition, would help users to understand a little bit, about the logic behind.

BTW great work wit antd I loved

**Comment by enzolutions** [comment]
BTW I am asking that because I want to use i18n solution more suitable for meteor applications

**Comment by afc163** [comment]
It is not a antd related problem.

You can't use `<FormattedMessage />` to native input placeholder either.

```jsx
<input placeholder={<FormattedMessage id="xxx" />} /> // broken
<input placeholder={intl.formatMessage({ id: 'xxx' })} /> // good
```

**Comment by enzolutions** [comment]
Hi @afc163 

Thank for your advice , do you have demo to check that, I have been trying for hours but doesn't "compile" for me.

Something in codepen.io would be really helpful. Thanks in advance

Kind regards,

**Comment by guangming21** [comment]
@afc163 

![qq 20170802002348](https://user-images.githubusercontent.com/18028721/28852923-5bf57114-775f-11e7-8572-b44208e11d8e.png)

![qq 20170802002337](https://user-images.githubusercontent.com/18028721/28852915-512693ee-775f-11e7-9713-7e15e639640f.png)
这个错误怎么回事

**Comment by Scharpp** [comment]
Hi @afc163,

To translate all form validation messages, you can create a form with your own desired messages using this property defined in the official documentation:

https://ant.design/components/form/?locale=en-US#Form.create(options)

You just have to define again your own messages like this:

```javascript
export function newMessages() {
  return {
    default: 'Validation error on field %s',
    required: '%s is required',
    enum: '%s must be one of %s',
    whitespace: '%s cannot be empty',
    date: {
      format: '%s date %s is invalid for format %s',
      parse: '%s date could not be parsed, %s is invalid ',
      invalid: '%s date %s is invalid',
    },
    types: {
      string: '%s is not a %s',
      method: '%s is not a %s (function)',
      array: '%s is not an %s',
      object: '%s is not an %s',
      number: '%s is not a %s',
      date: '%s is not a %s',
      boolean: '%s is not a %s',
      integer: '%s is not an %s',
      float: '%s is not a %s',
      regexp: '%s is not a valid %s',
      email: '%s is not a valid %s',
      url: '%s is not a valid %s',
      hex: '%s is not a valid %s',
    },
    string: {
      len: '%s must be exactly %s characters',
      min: '%s must be at least %s characters',
      max: '%s cannot be longer than %s characters',
      range: '%s must be between %s and %s characters',
    },
    number: {
      len: '%s must equal %s',
      min: '%s cannot be less than %s',
      max: '%s cannot be greater than %s',
      range: '%s must be between %s and %s',
    },
    array: {
      len: '%s must be exactly %s in length',
      min: '%s cannot be less than %s in length',
      max: '%s cannot be greater than %s in length',
      range: '%s must be between %s and %s in length',
    },
    pattern: {
      mismatch: '%s value %s does not match pattern %s',
    },
    clone() {
      const cloned = JSON.parse(JSON.stringify(this));
      cloned.clone = this.clone;
      return cloned;
    },
  };
}
```

**Comment by HSin-Tse** [comment]
```
import React from 'react';
import { injectIntl } from 'react-intl';
import { Input} from "antd";

const Input18 = ({ intl}) => {
    console.log(intl);
    return <Input type="text" placeholder={intl.formatMessage({id: 'email'})}/>
};

export default injectIntl(Input18)

```

```
import Input18 from './input';

       <Input18
                    prefix={<UserOutlined/>}
                    size="large"
      

                />
```
