### ISSUE TITLE
input-number 组件的中 step设置为1，value的必须是整数，现在的功能没有了，以前的版本是支持的。

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design#5868]
### Version
2.9.2

### Environment
macos

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
input-number 组件的中 step设置为1，输入的带小数的数值

### What is expected?
step 的为1，只允许 不含小数的正数

### What is actually happening?
step 的为1，小数也可以 输入展示。

**Comment by afc163** [comment]
这是合理的，step 和 value 没关系，1.5 => 2.5，step 也是 1。建议用校验来限制。
