### ISSUE TITLE
TreeSelect希望能够增加是否可选父节点的开关

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#5870]
### What problem does this feature solve?
在TreeSelect的应用场景中，有些业务需求可能会要求只能选择最末级节点，不能只选择父节点的情况，目前该组件没有提供该API,而且如果把父节点设置为disabled,则该父节点的展开收缩功能将失效。

### What does the proposed API look like?
parentVisbaled:true/false

**Comment by afc163** [comment]
Use `value` to control selected value. If it is a parent node, don't set key in value.

**Comment by 0hao** [comment]
带搜索词时，点全选会报错。输入 『c』，选择『computerAAA』，报 `must set key for <rc-animate> children`

demo https://codepen.io/0hao/pen/eWXVJR
