### ISSUE TITLE
Menu highlight disappear after page refresh/goBack

### ISSUE THREAD

**Issue by adamwuyu** [ant-design/ant-design#5871]
### Version
2.9.2

### Environment
MacOS-10.12.4,  Safari-10.1/Chrome-58.0.3029.81

### Reproduction link
[http://47.92.30.98:8000/UIElement/iconfont](http://47.92.30.98:8000/UIElement/iconfont)

### Steps to reproduce
1 open http://47.92.30.98:8000, and login with username 'guest' and password 'guest'
2 open http://47.92.30.98:8000/UIElement/iconfont
(3 click any Menu item, and click the go back button of the browser)

### What is expected?
The corresponding Menu item is highlighted.

### What is actually happening?
The corresponding Menu item is not highlighted.

**Comment by afc163** [comment]
Use `selectedKey` to control your menu state.

**Comment by adamwuyu** [comment]
@afc163 in the scenarios mentioned above, I can not use selectedKeys to manage the menu state.
Refresh the page, for example, how can I know which key is the selected one?

**Comment by adamwuyu** [comment]
Any idea?

**Comment by bang88** [comment]
you can use the route path as the selected key, so when you refresh the page it should work.

**Comment by adamwuyu** [comment]
@bang88 thank you for you advice. It is working now. Here is the code:
```
render() {
    let href=window.location.href.split('/')
    href=href[3]
    const {sysReducer, dataReducer, dispatch} = this.props
    return (
      <Provider store={this.props.store}>
        <Router>
          <Layout>
          <Sider
            breakpoint="lg"
            collapsedWidth="0"
            onCollapse={(collapsed, type) => {
              console.log(collapsed, type);
            }}
          >
            <div className="logo"/>
            <Menu theme="dark" mode="inline" defaultSelectedKeys={['/'+href]} selectedKeys={['/'+href]}>
              <Menu.Item key="/single-data-list">
                <Link to="/single-data-list" className={styles.nav_text}>
                  <Icon type="user"/>
                  <span>Single Data List</span>
                </Link>
              </Menu.Item>
```
