### ISSUE TITLE
RangePicker components used in the Form component error

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/ant-design#5872]
### Version
2.9.2

### Environment
Win10 64、Chrome57.0

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-time-related-controls](https://ant.design/components/form-cn/#components-form-demo-time-related-controls)

### Steps to reproduce
1. Click the RangePicker component select a date
2. Then removed the select date
3. Reselect a date occur error

### What is expected?
no error

### What is actually happening?
```
Uncaught TypeError: Cannot read property 'clone' of undefined
```

**Comment by ladjzero** [comment]
+1
`
Uncaught TypeError: Cannot read property 'clone' of undefined
    at Object.getEndValue (RangeCalendar.js:331)
    at Object.render (RangeCalendar.js:496)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
`

**Comment by cauu** [comment]
+1

**Comment by LeeHarlan** [comment]
Antd team has found the problem before me and has been fixed, so I closed the issue

**Comment by ladjzero** [comment]
When will this patch be released? @afc163

**Comment by afc163** [comment]
@LeeHarlan Not fixed yet.

**Comment by kappa-gooner** [comment]
+1

**Comment by phnessu4** [comment]
2.9.3 有相同的问题

独立使用没问题
`<DatePicker.RangePicker />`

Form用的时候有问题
`getFieldDecorator('date_range', {})(<DatePicker.RangePicker />,)`

报错

> RangeCalendar.js:331 Uncaught TypeError: Cannot read property 'clone' of undefined
>     at Object.getEndValue (RangeCalendar.js:331)
>     at Object.render (RangeCalendar.js:496)
>     at eval (ReactCompositeComponent.js:796)
>     at measureLifeCyclePerf (ReactCompositeComponent.js:75)
>     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
>     at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
>     at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
>     at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
>     at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
>     at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
>

**Comment by weeuwee** [comment]
+1
