### ISSUE TITLE
table sort click area is not big enough ?

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#5873]
### Version
2.9.2

### Environment
mac chrome57

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
click area only arrow。

### What is expected?
click area 整个列能进行排序，因为我们的用户群体比较特殊，一般是中年人（40岁 ）。

### What is actually happening?
只有click小箭头才可以

**Comment by benjycui** [comment]
这个感觉需要你自行处理，监听 thead cell 的 onClick 事件，然后 toggle 排序就好。

因为 antd Table 还有这种形态，不可能点击列就进行排序。

![image](https://cloud.githubusercontent.com/assets/3580607/25331132/82b38244-2914-11e7-8f6c-a6724a3451cb.png)

**Comment by henryzp** [comment]
@benjycui ，

有两个问题，

1，怎么处理thead的click，因为api提供出来的只有onRowClick和onCellClick
2，怎么toggle，看提供出来的[demo](https://ant.design/components/table-cn/#components-table-demo-reset-filter)只实现一个方向，代码如下：

```
this.setState({
      sortedInfo: {
        order: 'descend',
        columnKey: 'age',
      },
    });
```

这里的order值可以写成"toggle"吗？还是要要做一个判断，当是desc的时候，改成asc，反之。。

**Comment by henryzp** [comment]
@benjycui @afc163 

onRowClick和onCellClick并不包含thead，那怎么给thead注册click事件呢？？

**Comment by benjycui** [comment]
ping @yesmeck

**Comment by YDJSZY** [comment]
这个排序小图标很不合理，默认是现在这个样子，但点击后应该根据升序还是降序切换为不同的图标，比如一个向下箭头和向上箭头。

**Comment by jacobweber** [comment]
I agree — these icons are too small, both to see and to click, especially on a mobile device. If you could override the rendering of the table header, including the icons, then we could provide our own sort icons.

**Comment by henrych4** [comment]
Hi all, I just came across similar situation and here may be one of possible solutions.

https://codepen.io/anon/pen/wxaGBp

Now you can click on Age to sort data by ascending/descending order.

**Comment by sirrodgepodge** [comment]
here's a pure CSS way to do it if you're into that :P, idea kernel credit goes to @nkalinov
```
// hacking sorter component
.ant-table-thead > tr > th { // we want the click target to be the whole "th" (column header) element
	position: relative;
}
.ant-table-column-sorter {
	position: static;
	.ant-table-column-sorter-up,
	.ant-table-column-sorter-down {
		position: static;
		&::after {
			top: 0;
			left: 0;
			height: 100%;
			width: 100%;
		}
		&.on::after {
			pointer-events: none;
		}
	}

	// make initial toggle be on "up" arrow
	.ant-table-column-sorter-up.off + .ant-table-column-sorter-down.off::after {
		pointer-events: none
	}
}
```

**Comment by kanweiwei** [comment]
can use `onHeaderCell`
