### ISSUE TITLE
Dropdown组件与Menu组件配合用时出现了选中状态的bug

### ISSUE THREAD

**Issue by QDJobson** [ant-design/ant-design#5875]
### Version
2.9.2

### Environment
windows    Chrome 59.0.3067.6

### Reproduction link
[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce
Dropdown组件配合Menu组件使用时，当鼠标移入下拉，然后点击了menu中某个item之后下拉菜单收回，再次鼠标移入展开下拉菜单时，上一次被点击的那个item依然是选中的状态，正常应该是还原回未选中的状态。

### What is expected?
再次移入展开下拉菜单时，上一次选中的menu.item应该还原回未选中的状态。

### What is actually happening?
再次移入展开下拉菜单时，上一次选中的menu.item仍然为选中的状态。

---
之前用的2.7.0版没有这个问题，现在升级到2.9.2版出现了这个问题。
antd官网Dropdown组件页面里的第一个例子就有这个问题。

**Comment by afc163** [comment]
这是之前版本的一个问题。https://github.com/ant-design/ant-design/issues/5013

Menu 默认是带有选中状态的，你可以设置 `<Menu selectedKeys={[]}>` 强制覆盖选中状态。
