### ISSUE TITLE
antd FormItem 如何设置多个属性的值

### ISSUE THREAD

**Issue by Restry** [ant-design/ant-design#5876]
### What problem does this feature solve?
 在使用form组件时，其中的FormItem用的是Select时一般都会是Key和Value的。
比如这段代码：
```
<FormItem label="组类型：" hasFeedback {...formItemLayout}>
  {getFieldDecorator('GroupTypeID', {
    initialValue: item && item.GroupTypeID,
    rules: [
      {
        required: true,
        message: '组类型未选择',
      },
    ]
  })(
    <Select
      placeholder="请选择组类型"
      onSelect={(a, b) => this.onGroupTypeChanged(a, b)}>
      {groupTypes.map((gt, index) => {
        return (<Option key={gt.id   'GT'} value={gt.id}>
          {gt.GroupTypeName}</Option>);
      })}
    </Select>
    )}
</FormItem>
```

默认情况下只给Item的GroupTypeID对象设置了下面Select组件的value中的值。

但我是想在Item中设置多个值，比如GroupTypeID、GroupTypeName。简单说就是要获取到选中项的多个属性到Item中
有没有一个优雅的办法可以设置？

### What does the proposed API look like?
我不知道期望是什么样，我就想知道现在是否有现成的实现方式，除了自己到value里面拼Key Value

**Comment by yesmeck** [comment]
`labelInValue` https://ant.design/components/select-cn/#Select-props
