### ISSUE TITLE
“BackTop”It can be used in a component ？

### ISSUE THREAD

**Issue by wuyunjiang** [ant-design/ant-design#5879]
### Version
2.9.3

### Environment
无

### Reproduction link
[http://wuyunjiang.cn/message/](http://wuyunjiang.cn/message/)

### Steps to reproduce
无

### What is expected?
在组件内部使用BackTop，而不是针对整个页面

### What is actually happening?
不能在针对组件使用BackTop

**Comment by afc163** [comment]
Try `target`.

**Comment by wuyunjiang** [comment]
@ant-design-bot 嗯好的谢谢

**Comment by wuyunjiang** [comment]
@afc163 怎么使用呢，是加到BackTop属性中吗，我是这样使用的，
```html
<div id="test" className={styles.normal}>
    <BackTop target="test" visibilityHeight="400">UP</BackTop>
    .
    .
    .
<div>
```
但是报错target is not a function

**Comment by benjycui** [comment]
@wuyunjiang 就不能看下文档？ https://ant.design/components/back-top-cn/#API
