### ISSUE TITLE
'QueueAnim' components disappears if navigated too quickly

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#588]
On the QueueAnim React Router example, if you click between the tabs quick enough and then stop, the component is not visible until you navigate to another route again.

http://ant.design/components/queue-anim/#/anim-demo-router?_k=gco0tx
![image](https://cloud.githubusercontent.com/assets/842078/11379455/59d710ca-92e8-11e5-8814-ec2f88d0d207.png)

This also happens on a local example, with the same setup as the example using React Router.

**Comment by kazaff** [comment]
我这边结合react-router，卡顿更严重，一开始以为是绑定变量错误呢，而且一直切换会越来越卡

**Comment by jljsj33** [comment]
很卡？？？？

**Comment by Ehesp** [comment]
Sorry guys I only speak English :flushed:

Going from the translations, it works fine for a period of time - no lag occurs, then all of a sudden if I stop changing tabs the animation to bring the component in never happens until I re-trigger it again.

**Comment by afc163** [comment]
We trace this problem here: https://github.com/react-component/queue-anim/pull/6

**Comment by Ehesp** [comment]
Thanks, I'll close this and keep an eye on the above issue.
