### ISSUE TITLE
Popover中包含Select组件时，切换select选中项会导致Popover关闭

### ISSUE THREAD

**Issue by 624220042** [ant-design/ant-design#5880]
Popover中包含Select组件时，切换select选中项会导致Popover自动关闭......
const content = (
  <Select
        defaultValue="All"
        style={{ width: 100 }}
      >
        <Select.Option value="All">All</Select.Option>
        <Select.Optionvalue="TEST1">TEST1</Select.Option>
      </Select>
);
<Popover content={content} title="Title" trigger="click">
      <Button>Click me</Button>
    </Popover>

**Comment by benjycui** [comment]
`getPopupContainer`, see: https://ant.design/components/select/

**Comment by jeffycai** [comment]
it's right solution
