### ISSUE TITLE
Table: Column's property "filtered" not work.

### ISSUE THREAD

**Issue by kamma-cc** [ant-design/ant-design#5891]
### Version
2.9.3

### Environment
lastest Chrome

### Reproduction link
[http://codepen.io/anon/pen/EmgMJN?editors=001](http://codepen.io/anon/pen/EmgMJN?editors=001)

### Steps to reproduce
1. click name filter icon
2. input something and enter

### What is expected?
the filter icon turns blue

### What is actually happening?
the filtered property not work.

**Comment by afc163** [comment]
try `filterIcon`
