### ISSUE TITLE
table header 不支持点击

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#5892]
### What problem does this feature solve?
由于我们用户是40 的中年人，在排序的时候，他们更习惯点击整个表头列（thead）来触发排序。

### What does the proposed API look like?
column: [{
      theadClick: function(){}
}]

**Comment by henryzp** [comment]
我仔细看了一下rc-table，thead的处理，目前确实没有提供出来click的功能：

```
getHeaderRows(columns, currentRow = 0, rows) {
    rows = rows || [];
    rows[currentRow] = rows[currentRow] || [];

    columns.forEach(column => {
      if (column.rowSpan && rows.length < column.rowSpan) {
        while (rows.length < column.rowSpan) {
          rows.push([]);
        }
      }
      const styleProp = column.align ? { textAlign: column.align } : null;
      const cell = {
        key: column.key,
        className: column.className || '',
        style: styleProp,
        children: column.title,
      };
      if (column.children) {
        this.getHeaderRows(column.children, currentRow + 1, rows);
      }
      if ('colSpan' in column) {
        cell.colSpan = column.colSpan;
      }
      if ('rowSpan' in column) {
        cell.rowSpan = column.rowSpan;
      }
      if (cell.colSpan !== 0) {
        rows[currentRow].push(cell);
      }
    });
    return rows.filter(row => row.length > 0);
  }
```

**Comment by afc163** [comment]
`onHeadClick` is better.

Could you propose a PR for this? @henryzp

**Comment by yesmeck** [comment]
https://github.com/react-component/table/pull/127

This PR is not merged because it's hard to draw the line once we start adding `onHeadClick`, other people may request to add `onHeadDoubleClick`, `onHeadContextMenu`, `onHeadMouseEnter`... Cells also has this problem, we should figure out a better way to archive this, like #5775

**Comment by henryzp** [comment]
@yesmeck 有道理。。

我后来处理的方案是你在另外一个issue上给的，就是给标题加click事件，去做sort的toggle功能

**Comment by benjycui** [comment]
> 我后来处理的方案是你在另外一个issue上给的，就是给标题加click事件，去做sort的toggle功能

这个问题在于 thead cell 内有一定的区域不属于 title..

**Comment by henryzp** [comment]
@benjycui 对，不过我的需求，thead只有标题和排序箭头，个人觉得点击空白区域也没什么意义。所以也不需要太纠结。

**Comment by otakustay** [comment]
既然column中的title可以是一个ReactNode，那么这事情本身就可以自己搞吧：

```js
sortTable() {
    this.setState({sortOrder: revert(this.state.sortOrder)});
}

render() {
    let columns = [
        {
            title: <span onClick={::this.sortTable}>名称</span>,
            sortOrder: this.state.sortOrder,
            ...
        }
    ];

    return <Table columns={columns} ... />
}
```

**Comment by henryzp** [comment]
@otakustay ，你这样写样式的话，那个sort按钮就会有问题了，哈哈～

话说你上面贴的revert函数，你能否帮我看看，我上面的代码，我写的感觉比较low，是否有更优雅的写法？

**Comment by otakustay** [comment]
其实改不到哪里去……

```js
let revert = {ascend: 'descend', descend: 'ascend'};
let {sortInfo = {}} = this.state;
let newOrder = revert[sortInfo.order] || 'descent';
this.setState({sortInfo: {order: newOrder, columnKey: 'age'}});
```

虽然少了几行代码，但直观性到底如何就看你判断了- -

**Comment by henryzp** [comment]
@otakustay ，thx

**Comment by mitjade** [comment]
Some documentation that the title in the column can be a ReactNode, would really be helpful. It took me a long time to find this solution, on how to add a click event to the title as shown below.

```
    let columns = [
        {
            title: <a onClick={...} href="#">Title</a>,
            ...
        }
    ];
```
