### ISSUE TITLE
Notification doesn't support customize style

### ISSUE THREAD

**Issue by lixiaoyang1992** [ant-design/ant-design#5893]
### What problem does this feature solve?
when description is long and with split line, like :  

[WARNING]  
[INFO]  
[INFO] ------------------------------------------------------------------------  
[INFO] Building ***  
[INFO] ------------------------------------------------------------------------  

I want to customize the style.

### What does the proposed API look like?
    notification.success({
      style : { width: 300},
      message: 'my title',
      description: 'a long long string'
    })

**Comment by lixiaoyang1992** [comment]
If you accept the feature, I can PR

**Comment by benjycui** [comment]
And how about `message`? 

And, if we accept this feature, we had better to support `className`, too.

**Comment by lixiaoyang1992** [comment]
According to Notification API, message means title.

And of coerce, we should support className.

**Comment by benjycui** [comment]
The conclusion is that we need to add `style` and `className` to `antd.notification` `antd.message`

**Comment by benjycui** [comment]
@lixiaoyang1992 could you PR to add these features?

**Comment by lixiaoyang1992** [comment]
OK
