### ISSUE TITLE
Setting placement in notification.open affects overwrites the default

### ISSUE THREAD

**Issue by jakubkosinski** [ant-design/ant-design#5894]
### Version
2.9.3

### Environment
macOS, Chrome 58, Safari 10.1

### Reproduction link
[http://codepen.io/anon/pen/JNRqJz](http://codepen.io/anon/pen/JNRqJz)

### Steps to reproduce
1. Set global placement to some value (or leave default `'topRight'`)
2. Open a notification with custom placement
3. All consecutive calls of `notification.open` and other (success, warning, error) uses custom placement that was set in the 2nd step.

### What is expected?
Setting explicit placement in `notification.open` should not overwrite the global placement set in `notification.config`

### What is actually happening?
`placement` option in `notification.open` overwrites the default one set in `notification.config`

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/5895
