### ISSUE TITLE
notifications with custom placement are overlaping

### ISSUE THREAD

**Issue by jakubkosinski** [ant-design/ant-design#5895]
### Version
2.9.3

### Environment
macOS, Chrome 58, Safari 10.1

### Reproduction link
[http://codepen.io/anon/pen/gWwJvw](http://codepen.io/anon/pen/gWwJvw)

### Steps to reproduce
1. Set custom placement for a notification
2. Open a notification with custom placement
3. Open another notification with the same custom placement

### What is expected?
Notifications are not overlaping

### What is actually happening?
Notifications are overlaping

**Comment by benjycui** [comment]
ping @ystarlongzi

**Comment by benjycui** [comment]
But it works fine here https://ant.design/components/notification/#components-notification-demo-placement

**Comment by benjycui** [comment]
@ystarlongzi it works fine with `notification.confg`, but it's broken with `notification.open({ placement: ... })`

**Comment by benjycui** [comment]
Related: https://github.com/ant-design/ant-design/issues/5894

**Comment by ystarlongzi** [comment]
@benjcui Get, i'll fix it.

**Comment by tvrcgo** [comment]
@benjycui @ystarlongzi  关于这个问题还有一个场景：

- A 组件调用 notification.success 不设置 placement，弹窗默认从右上角出
- B 组件调用 notification.success 设置了 placement = bottomRight，弹窗从右下角出
- A 组件再调用 notification.success 不设置 placement，弹窗变成从右下角出，默认 placement 被改了

只要某个地方设置了一次 custom placement，往后的所有 default placement 都会被改变。

这是正常的吗？

---

版本：antd@2.12.4

**Comment by djyde** [comment]
@benjycui Should defaultPlacement be immutable?

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
@ystarlongzi why do you modify the defaultPlacement in [here](https://github.com/ant-design/ant-design/commit/aadf623dc6d39354345c5aee5122eb4940810e1c#diff-68cc50c6ff65322f4544730573f0fc9aR81)

**Comment by afc163** [comment]
@ystarlongzi

**Comment by djyde** [comment]
I am gonna to fix it. Should I?

**Comment by benjycui** [comment]
@djyde yep, thanks.

**Comment by djyde** [comment]
But the `notification.config(options)` is conflict with immutable default placement.

**Comment by benjycui** [comment]
@djyde I will handle this, there are several bugs in `notification`, not just the one which you had pointed it out.
