### ISSUE TITLE
Clear DatePicker current value

### ISSUE THREAD

**Issue by wangzhongquan** [ant-design/ant-design#5896]
### What problem does this feature solve?
As is known to all,    when DatePicker is set defaultValue or  after we choose a date  , there will appear a icon to clear current value in the end , Sometimes maybe we will DIY a button or a link  that to clear current value 。
 Can you give me a method or a suggestion to finish this function?
Thanks.

### What does the proposed API look like?
A method or a suggestion to clear current value

**Comment by benjycui** [comment]
`DatePicker[value]` is a controlled property.

**Comment by wangzhongquan** [comment]
@ant-design-bot  Thanks
