### ISSUE TITLE
为 tooltip 组件提供 位移选项（offset）

### ISSUE THREAD

**Issue by lewis617** [ant-design/ant-design#5899]
### What problem does this feature solve?
可以定制 tooltip 的位置，以满足自家设计师的要求。

### What does the proposed API look like?
直接提供 offset 这个 props。比如：

```js
offset={{top: 10, left: 10}}
```

**Comment by benjycui** [comment]
如果按以上的例子配置了 Tooltip 后，视觉效果是怎样？可以给个截图？

**Comment by lewis617** [comment]
![image](https://cloud.githubusercontent.com/assets/11524612/25414915/0ccc5a98-2a67-11e7-9d72-f30fe6e375d1.png)

"旺旺"这个tooltip会根据 offset 进行位移。我看了默认的 left 位移貌似是 4px，可以使用 offset 进行定制。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/ZKBxBP?editors=001

https://github.com/react-component/trigger

**Comment by benjycui** [comment]
@afc163 需要把 popupAlign 更新到文档。

**Comment by afc163** [comment]
不暴露了，高级选项。解释起来比较复杂。

**Comment by lewis617** [comment]
@afc163 popupAlign 突然不好使了：
http://codepen.io/anon/pen/ZKBxBP?editors=001

**Comment by lewis617** [comment]
当 popupAlign 的 x 值设为负值时（或 y 值设为正值）无效：

https://codepen.io/lewis617/pen/NgKRaj?editors=001

@afc163
