### ISSUE TITLE
Safari浏览器下表格控件闪烁

### ISSUE THREAD

**Issue by luyunfei** [ant-design/ant-design#5902]
![2017-04-26_15-09-05](https://cloud.githubusercontent.com/assets/4887426/25422408/62c00cf2-2a93-11e7-962d-4a12f97eebf5.png)
![2017-04-26_15-06-10](https://cloud.githubusercontent.com/assets/4887426/25422414/66dc4a6c-2a93-11e7-95e6-36512826042d.png)

### Version
2.9.2

### Environment
Macbook， Safari Version 10.1 (12603.1.30.0.34)

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
页面上添加固定头和列的表格控件，表格控件带边框，而且可以上下，或左右scroll。 滚动条左右移动表格，然后有时候屏幕会闪烁。看起来是页面在不停渲染似的。不过chrome没有这个问题

### What is expected?
屏幕不要闪烁

### What is actually happening?
屏幕有时候会闪烁

**Comment by afc163** [comment]
Can't reproduce it, could you please supply more information (like a gif) or dig by your own?

**Comment by afc163** [comment]
close for no response, just reply in here if you can provide more information or give us PR.
