### ISSUE TITLE
chrome Table scroll-x shadow does not work

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#5906]
### Version
2.9.0

### Environment
mac, chrome 57.0.2987.133 (64-bit)

### Steps to reproduce
设置table的scroll x小于当前表格宽度的时候

### What is expected?
chrome下出现阴影或者其他#可以滑动#的提示

### What is actually happening?
chrome不兼容阴影效果

![image](https://cloud.githubusercontent.com/assets/12080165/25416298/ae7cce24-2a6f-11e7-9af0-b009b667b898.png)

**Comment by yangbin1994** [comment]
![image](https://cloud.githubusercontent.com/assets/12080165/25416349/d9c1f262-2a6f-11e7-9e3c-b23cb0cc4733.png)

**Comment by benjycui** [comment]
> 设置table的scroll x小于当前表格宽度的时候

？？？ 这不就意味着不需要滚动么，既然不能滚动，为何还需要视觉暗示？

**Comment by afc163** [comment]
当 `scroll.x` 小于表格宽度时，就没有必要滚动了。
