### ISSUE TITLE
select 多选那种搜索出来内容选择一个之后之前搜索的内容就消失了

### ISSUE THREAD

**Issue by yangguixue** [ant-design/ant-design#5907]
### What problem does this feature solve?
select 多选那种搜索出来内容选择一个之后之前搜索的内容就消失了，选择起来不是很方便，需要重新输入之前搜索的内容重新搜索

### What does the proposed API look like?
我希望在我搜索出来内容选择一个，可以继续选择我搜索出来的其他内容，而不是跳转到第一条

**Comment by benjycui** [comment]
See: https://ant.design/components/select/#components-select-demo-select-users

**Comment by yangguixue** [comment]
上面给出来的答案我并不满意，现在的问题是我搜出来东西之后选择一个，刚刚搜出来的东西就没有了，我又要重新搜索相同的关键字，我想的是搜出来一个列表之后可以连续选择好多个，而不是选择一个，那个刚刚搜索到的列表就没有了

**Comment by benjycui** [comment]
再细看下 demo，只要做少许修改就可以了。

非得别人帮你把细节都写好？？
