### ISSUE TITLE
我的调用组件之后报这个提示

### ISSUE THREAD

**Issue by aiyuekuang** [ant-design/ant-design#5909]
app.js:859 Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
该这么解决

**Comment by henryzp** [comment]
@aiyuekuang ，是这样的，你目前的react版本应该是15.5以上的。。

然后react16会移除createClass，还有一个是type类型。。反正我地方warning了两个，手贱升级，哎～

**Comment by hb-bobo** [comment]
ant是不是等16版出来才升级
