### ISSUE TITLE
对于重型组件的基于功能粒度的拆分能力

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#5910]
### What problem does this feature solve?

在当前版本的antd中，某些重型组件由于提供了丰富的功能，其本身与其它组件的依赖也导致组件体积比较大，我们使用webpack对单个组件进行打包，具体步骤如下：

1. 编写`index.js`，内容如下：

    ```js
    // 使用需要测试的组件替代Select
    import Select from 'antd/lib/select';

    Select; // 避免代码消除
    ```

2. 使用最基本的webpack配置：

    ```js
    let path = require('path');

    module.exports = {
        context: __dirname,
        entry: {
            index: './index.js'
        },
        output: {
            path: path.join(__dirname, 'dist'),
            filename: 'index.js',
        },
        resolve: {
            extensions: ['.js', '.jsx'],
            modules: [path.resolve(__dirname, 'node_modules')],
            mainFields: ['module', 'jsnext:main', 'main']
        }
    };
    ```

3. 运行`webpack`观察构建后文件的大小

以下是3个组件的结果：

- Button: 210 kB
- Select: 1.08 MB
- Table: 1.37 MB

可以看到，`Select`和`Table`因其具备如筛选、选中、分页等功能，依赖了其它的组件，导致体积很大。

而在一些应用中，对这类重型组件的实际功能需求却不是所有的功能，如一个简单的应用只需要最简单的表格显示功能，因此内部的`icon`、`pagination`、`spin`、`SelectionBox`等都是多余的，这些没有用到的功能却很大程度上影响了代码的体积，显得并不十分“精致”

因此，我提议一种对重型组件稍加改造的方式，使其在保持“可现有简单使用全功能”的基础上，对于有精细定制化需求的场景可以提供定制性的使用模式

### What does the proposed API look like?

在实现一个重型组件时，我们可以将它分为2个部分：

1. 基于“依赖”实现功能的组件内核
2. 提供全功能的依赖并组装成全功能组件的组件本身

一个组件的内核定义为一个`dependencies => Component`的函数，比如表格组件可以这么定义：

```js
// makeTable.js
export default dependencies => {
    let {Spin, Icon, Pagination} = dependencies;

    return class Table extends PureComponent {
        render() {
            return (
                // ...
                <Pagination ... />
            );
        }
    }
};
```

在上面的代码中，可以看到`Table`类的实现和antd现有的实现是一样的，唯一的区别就是`import Spin from '../spin'`变成了从`dependencies`参数中获取`Spin`组件。

而一个全功能的组件（即现有的`Table`）可以简单地通过内核来实现：

```js
// Table.js
import Spin from '../spin';
import Icon from '../icon';
import Pagination from '../Pagination';
// 其它一堆import
import makeTable from './makeTable';

let components = {Spin, Icon, Pagination, ...};
export default makeTable(components);
```

对于用户来说，继续使用`import {Table} from 'antd'`可以保持所有功能的一致，这是一个向后兼容的透明地升级

而对于体积敏感的用户而言，则可以将他并不需要的功能替换为空组件，这些功能由于不会使用到（如`pagination`永远为`false`），因此提供一个简单的空实现就行，本身不会被渲染：

```js
// MinimumTable.js
import {Icon, makeTable} from 'antd'; // Icon还是要用的

let Phantom = () => null;
let components = {
    Icon: Icon,
    Pagination: Phantom,
    Spin: Phantom,
    ...
};
export default makeTable(components);
```

这样使用`MinimumTable`组件就可以在享受标准表格和一个图标功能的同时，避免引入其它的依赖组件，有效缩小最后构建产物的体积

而这种手段有另外几个优势：

1. 可以通过相同的接口（props）替换掉某些组件的实现，比如有一个自行实现的复杂的分页器，那么只要保持props是相同结构，就可以替换掉antd默认的`Pagination`组件，实现定制化
2. 基于高阶函数创建组件可用通用的IoC（依赖注入）容器进行管理，这是我当前正在研究和推进的一个话题，使用IoC通过通用的配置去定义不同的组件，使得同一个实现逻辑的组件在不同应用场合可以表现为不同形式

以上是个人的一些想法，望提供反馈和建议

**Comment by benjycui** [comment]
这个之前 rc-slider 也做过一个类似的拆分 https://github.com/react-component/slider#api

不过 antd 的定位主要还是中后台，而且把 Table 拆分成 Table 和 makeTable 后，样式的按需加载也需要相应的调整。

不过觉得这个还是可以发散讨论一下，有兴趣的都可以讨论下。

**Comment by otakustay** [comment]
> 样式的按需加载也需要相应的调整

在我的理解里这并不是一个问题

- 对于内置所有依赖的`antd/lib/Table`，其实就是写一次性的事情，官方提供外部就不感知了
- 对于定制化使用的，其实写的时候只有`import {Spin} from 'antd'`，其它交给`babel-plugin-import`就能完成了

不如说，按需加载是现在antd+babel-import本身就存在的一个能力？

**Comment by benjycui** [comment]
```jsx
import {makeTable} from 'antd';
```

会被 babel-plugin-import 处理成：

```jsx
import makeTable from 'antd/lib/makeTable';
import 'antd/lib/makeTable/style';
```

**Comment by otakustay** [comment]
我确实没想到会存在这个自动处理的问题，这个问题其实在当下的antd中也是有影响的，`import {version} from 'antd'`就会出现问题

我想是不是能有这种解决办法：

1. 通过babel-plugin-import的一些额外配置添加ignore之类的
2. 让plugin判断import name的case，如果是大写开头的才当组件同时引入style

**Comment by bang88** [comment]
可以试试 https://github.com/rollup/rollup 打包你们的代码，看看体积会不会小一些。
我本想尝试看看打包后的大小，由于这段时间很忙也不是很紧急的一个需求。

**Comment by otakustay** [comment]
@bang88 rollup打包会出些小问题，不过我hack了一下给过去了，三个组件大小大致如下：

- Button: 175KB
- Select: 970KB
- Table: 1.2MB

整体大小增长趋势和webpack是相同的，相比于webpack大概就是少了一堆loader自己的东西吧，这个话题讨论的问题还是存在

**Comment by bang88** [comment]
`Button `不应该那么大才对。 😢

**Comment by otakustay** [comment]
还算正常吧，裸奔打包的话react和core-js都在里面啊，没压缩这个大小我还是比较能接受的

**Comment by bang88** [comment]
用 Rollup 吧，看起来效果还是可以的。 😄

**Comment by otakustay** [comment]
其实我的核心问题是我只用Table展示一个普通的表格，不用选择、过滤、排序、分页，却要承受一个1MB多的文件体积……无论是rollup还是webpack都难以解决这个问题就是了

**Comment by bang88** [comment]
你有repo吗 我clone 看看

**Comment by qq645381995** [comment]
这个问题本身就跟压缩没关系 
只是引用的问题

**Comment by otakustay** [comment]
内部项目我还没办法提供……其实很简单，你对着这个代码：

```js
import Table from 'antd/lib/Table';

new Table();
```

来一发构建，看bundle的文件大小就行，无论用webpack还是rollup都行，虽然构建出来的文件肯定是不能运行的但看看大小没有问题

> 这个问题本身就跟压缩没关系
> 只是引用的问题

是的，问题就在于Table**硬编码**引用了很多其它的组件，而这些组件提供的功能未必用得上

**Comment by paranoidjk** [comment]
@otakustay 还是要看业务使用场景，
- 单 Table 来说，应该是使用全功能版的场景会多余仅仅需要纯粹的 Table，保持 all in one 会让 api 简单一些，都通过 props 来声明式的配置，不引入其他概念
- 另外，单组件来看，的确很大，但全景的考虑 PC 的中后台业务，按理说一个应用应该是会用到大部分 antd 常用的组件的，这样考虑下，组件内部之间纵横交错的互相依赖产生的冗余就没那么严重了。

当然，你提的按需加载概念很好，antd-mobile 就会朝这个方向努力。

https://github.com/ant-design/ant-design-mobile/issues/777
https://github.com/ant-design/ant-design-mobile/issues/1176
https://github.com/ant-design/ant-design-mobile/issues/1217

**Comment by paranoidjk** [comment]
cc @warmhug @silentcloud @pingan1927 我们也关注下这个讨论。

**Comment by otakustay** [comment]
如果antd的定位一直是后台业务的话我可以理解，但还是倾向于这样一个优秀的组件库不应该将自己局限在如此狭窄的范围内，因此才提供一个改造成本低且向后兼容对使用者完全无影响的方案

同时针对ant-design-mobile的使用`plugin`属性的方案，其实在react中最简单的方法就是把所有依赖组件通过props提供过去，而我不向你们建议这个更直观的方法的原因有二：

1. props本身是对react的性能有一定的影响的，如`PureComponent#shouldComponentUpdate`的实现就是对props和state进行一次shallowEqual的判断，增加props的属性数量无疑会有一定的负面作用
2. 希望组件的props能更集中在表达组件本身的“体验”上面，体验包括视觉和交互，但不应该将一些程序层面上需要的东西一起放在其中
3. 基于props这样设计，如果我有“全系统的所有Slider都使用固定的TooltipPlugin”这样固化的需求的话，需要的实现成本相对较高，需要使用高阶组件然后对props进行assign（这里又会有新对象生成的成本），这样涉及的概念相对较多，并没有使用`makeX`系列函数来得容易管理
4. 如上面所说，如果有通用的依赖管理的容器的话，使用`makeX`模式因为其本身预柯里化的特性，符合函数式的一贯范式更容易被通用化的管理，而不需要容器为react特有的各种概念做单独的支持

老实说其实我现在也只是用在内部系统，对体积并不是特别敏感，只是出于工程师奇怪的“洁癖”才折腾成这样子……即便antd决定不做这样的支持，这个Issue我想作为纯技术的讨论也是可以的

**Comment by otakustay** [comment]
符一个我对“以函数为单元组织逻辑”的开发模式下的依赖管理的探索和结论，有一些我自己团队相关业务的背景但尽力抽象了一下，应该能看懂

在我的整体计划中，设计和提供一种通用的react的组件间依赖管理模式是蛮大的一个环节，预想中一些复杂的有跨系统复用需求的场景中，整个react的组件的类型都可以交由容器工厂负责生产，以提供集中化配置带来的管理便携性和灵活性

[函数为单元的逻辑组织中IoC及AOP应用探索.pdf](https://github.com/ant-design/ant-design/files/958734/IoC.AOP.pdf)

**Comment by paranoidjk** [comment]
@otakustay 
- slides 里面关于与 antd 结合的那部分，并没有看懂其背后太多的意义？ 把细粒度的，optional 的依赖通过参数注入这没问题，但这要求容器组件具有按需拼装 feature 的能力，这点其实很难，因为 UI 组件的切分基本已经按交互形式和设计等固化下来了。
- 看了一下你们的  https://github.com/ecomfe/uioc ，在应用层面的确是可以天然以 model，view，controller 来切分逻辑，且比较容易抽象出这么一个 **用于渲染的controller**, 给其注入 model， view 等依赖，但纯 ui component 好像用不上？

IMO，上面提的到 https://github.com/react-component/slider#api slider 这样抽象一个 Base Component, 再通过 HOC 扩展逻辑，是我认为比较自然的方式

**Comment by otakustay** [comment]
简单描述一个我曾经真实遇到过的问题：

我们的日历组件年和月的选择都是普通的Select组件，但是有使用方向我表达他们的UE认为12个月用一个Select选择是很差的体验，有时还需要操纵滚动条

因此他们希望让日历组件的月选择部分展开后变成一个4x3的矩阵显示12个月，以便可以快速地选择月份。但同时他们并不希望因为这一变动就要自己写一个日历，毕竟日历中的日期换算、30天表格生成、上一月下一月等功能和交互都是现成的，重写一下就可能是千行代码（那时候还没有react之类的东西，纯手工DOM操作），也就是说，“UI 组件的切分基本已经按交互形式和设计等固化下来了”这样的论断在我们这边一个框架支持数十个产品线的时候其实并不一定成立

我当时思考了很久这个需求，认为其实本质上就是“一个组件的内部其它组件依赖应该是接口而不是具体实现”，可以由使用方提供具体的实现，只要满足预先定义的属性、方法、事件的接口即可（如月份选择能接受`value`并有`change`事件就行），至于具体长什么样，怎么和用户交互，可以由使用方自行定制

这个需求当时被我混着混着就过去了也没给支持，但一直留在我的心里，后期我在对UI组件框架进行设计的时候都会把这个case拿出来思考一下，怎么做能去支持这样确实存在的需求。而对于react为基础的组件，我思考后的结果就是pdf里或者本Issue顶楼中的这个方案，把feature抽象成组件，让组件的类型由外部提供，再通过通用的容器进行管理和创建

在我看来我建议的方式和 https://github.com/react-component/slider#api 这里的方式其实是完全一致的，Slider对Range的依赖就如同Calendar对MonthSelect的依赖、Table对Pagination的依赖。我们可以将这种模式范化一下，如`createSliderWithTooltip`函数不指定Range作为参数类型，而是一个`{Range}`的对象，这样接口的设计显得更具备通用性，也更容易让各种工具或者容器来介入管理

**Comment by paranoidjk** [comment]
@otakustay 
> **一个组件的内部其它组件依赖应该是接口而不是具体实现”，可以由使用方提供具体的实现，只要满足预先定义的属性、方法、事件的接口即可**

这个描绘的前景很好，不如说，组件包含一套自己的插件扩展系统，在base的功能之外，暴露出来一部分扩展的接口，比如， `<Table>`， 可以暴露出来`renderPagination = (current, total) => React.Element` 这样一个props，从而内部可以把对 pagination 组件的依赖抽离出来，你觉得这种如何？事实上 antd 不少地方有提供这种自定义的能力

**Comment by paranoidjk** [comment]
我的基本思路还是 **理想的一个复杂组件由基本 UI 或功能单元组成，如果可轻易切分，则复杂组件可做成插拔可扩展**，至于怎样的机制去实现扩展，倒是可以做出很多不同的细节实现

**Comment by otakustay** [comment]
> 组件包含一套自己的插件扩展系统，在base的功能之外，暴露出来一部分扩展的接口

是的，这样就很不错，我对antd的需求其实是在这个基础上不要强行写一个默认的`renderPagination`实现导致我引用Table就引用了Pagination……

当然另一个角度说（找碴），其实还是往前6楼列的那几点问题，比如对于需要固化某种Pagination的时候，你要写的代码大概是这样的：

```js
import {TableBase} from 'antd';
import {CustomPagination} from 'my-ui';

let MyTable = props => {
    let newProps = {
        ...props,
        renderPagination(props) {
            return <CustomPagination {...props} />
        }
    };
    return <TableBase {...newProps} />
};
```

是的，代码不多，但相比`makeTable({renderPagination: ...})`还是多了些，也多了一个对象（`newProps`）创建的代价，你看对象创建多了垃圾就多了，垃圾多了GC就频繁了……

而且上面这种写法，要用统一的“容器”管理的话，这个容器就必须知道react的这种HoC玩法然后做特殊的支持，相比`dependencies => Component`这样的标准thunk函数式来说缺少一些范用性

这个Issue变成讨论如何做组件的切分和扩展模式我也是相当欢迎的，毕竟面对大型复杂的应用就是我的专项领域😁

**Comment by bang88** [comment]
已然是讨论了。:smile:

**Comment by bang88** [comment]
同意 @otakustay 的观点。  组件的实现可以考虑通过接口的方式来约定有什么功能可以使用，让使用者去实现也方便一些自定义的行为。内部提供一套默认的接口实现即可，现在很多issues其实就是用户想自定义

**Comment by paranoidjk** [comment]
@otakustay 还是以 antd-mobile 的 slider 为例算了，已经基本做到了这种模式
https://github.com/ant-design/ant-design-mobile/blob/master/components/slider/demo/custom-tooltip.md

```js
import { Slider, createTooltip } from 'antd-mobile';

const SliderWithTooltip = createTooltip(Slider);
const SliderWithCustomTooltip = createCustomTooltip(Slider);

const createCustomTooltip = (Component) => {
  return class ComponentWrapper extends React.Component {
    handleWithTooltip = ({ value, dragging, index, className, vertical, offset, ...restProps }) => {
      const style = vertical ? { bottom: `${offset}%` } : { left: `${offset}%` };
      const tipStyle = { textAlign: 'center' };
      return (
        <div key={index}>
          <div {...restProps} className={className} style={style} />
          <div style={tipStyle}>{dragging && `拖动到了${value}` }</div>
        </div>
      );
    }
    render() {
      return <Component {...this.props} handle={this.handleWithTooltip} />;
    }
  };
};


<slider/>
<SliderWithTooltip/>
<SliderWithCustomTooltip/>

```

**Comment by bang88** [comment]
@paranoidjk 这种模式挺好的。

**Comment by paranoidjk** [comment]
@bang88 恩，基本套路就是我们不仅支持 HOC 来扩展逻辑，内部还给你提供一个默认的 HOC，从而把强行依赖抽离变成 optional，让用户按需的调用

**Comment by otakustay** [comment]
@paranoidjk 就是这么回事，`createTooltip`就是一个标准的HOC

> 基本套路就是我们不仅支持 HOC 来扩展逻辑，内部还给你提供一个默认的 HOC，从而把强行依赖抽离变成 optional，让用户按需的调用

就如同`makeTable`是个HOC，`Table`就是默认HOC后的产物，我正是希望antd也干脆做成这个样子

将这一模式扩展到任意复杂的组件中去，其形成的一个标准的模式就是：

> 输入n个必要的组件，产生一个全功能的组件

将这个模式范化成函数的表达，就是：

```js
({Object} components) => {Component}
```

其实和顶楼我说的完全是一样的，这个`createTooltip`在我看来唯一的瑕疵就是`Component`如果变成`{Component}`会具备更好的扩展性和一致性，对于需要多个的时候可以任意往对象里丢

**Comment by bang88** [comment]
要计划到3.0里面吗？ 但是有可能有breaking changes。  😢

**Comment by otakustay** [comment]
> 有可能有breaking changes

我也有种预感，虽然理论上一个HOC+一个输入了默认参数的产物是完全保持兼容性的，但总感觉实际做的时候免不了会有差池- -

**Comment by bang88** [comment]
我们项目会封装一次 `Table`，所以影响不大 😄 ，但是其他用户估计很多都是直接使用了。

**Comment by otakustay** [comment]
理论上只要保证lib/Table是已经用默认实现经过HOC的版本，直接用就不会出问题，细节上暂时也想不全面了

**Comment by NE-SmallTown** [comment]
这么晚了，讨论还很激烈呀～

身体吃不消了哈哈，要早点休息了。说一下自己的一些理解，希望能增进思考。

@paranoidjk 谈到的mobile的例子个人感觉是很亲切的，因为之前写代码大部分也是这么思考，但是最近有了一些新的感受。在封装/抽象类似于工具函数（即与组件无关的函数，其实也不仅仅是工具函数，包括对数据流的封装，框架内部的设计等等），这个时候通过抽象，达到采用多配置或者说自定义程度较高的配置的效果，配合外观模式是非常方便的。

比如JQ中的get,post都是基于ajax，delegate,bind,live都是基于on，antd里面Message.info/success/warning都是基于内部的某个函数。当然还有很多，包括不同的人自己写项目也会有很多这样的例子，就实际来讲基本是没什么问题的。

但是最近在思考，对于组件而言，这样的方式是不是有一些缺陷，因为像
```
<Slider/>
<SliderWithTooltip/>
<SliderWithCustomTooltip/>
```
这样的，会在任何需要定制的地方进行封装，而封装有一个很重要的目的是为了复用，但是按照这样的逻辑封装多了之后，第一，封装的地方分布在不同的文件，不太容易记住哪个封装在什么位置。第二，封装之后的组件的名字也很难记住，导致以后要想继续使用，都无法使用全局搜索找出是在哪里封装的，只能通过“哎，好像之前在写xx的时候封装过xxx”，然后就跑到xx去找，然后才找到xxx。

但是，又没办法把这些统一封装在一个index文件中，因为自己知道自己在封装什么是最符合思维习惯的，比如redux的各个selector会和局部的reducer写在一起。实在要做的话，可以封装之后，把这个添加到index中，比如我在a.js里面封装了SliderWithTooltip，然后import Slider的index里面写`mySliders.xxx=SliderWithTooltip`（在index里面写的应该是`export let mySlider = {}`），然后其他地方import index再对mySliders进行解构就好了，就不用自己去找到底在哪里了，但是是不是感觉有点怪怪的。。

当然还有一些弊端，现在有点困，头有点晕，明天清醒了再想想，见谅见谅。

所以，我现在倾向于对工具函数，或者类似于工具函数的东西（上面提到了类似的一般指哪些），包括组件内部的封装，采用FP的一些思想或者代码来辅助都是挺好的，但是对于开发人员之间的交互，甚至是现在的自己和3个月后的自己的交互而言，这样的方式不是太好。

所以现在即使存在一些模板代码，我觉得也还能接受了，包括antd或者rc里面`<AA withElement={<custom>.....<custom>}></AA>`这样的方式去封装，我觉得也可以多用一些。

最后，最近看到介绍[jsx-generic这个库](http://tolmasky.com/2016/03/24/generalizing-jsx/)的文章，不一定能解决我们讨论的问题，但是感觉思路挺不错的

**Comment by bang88** [comment]
@NE-SmallTown 如果是这个组件在很多地方用到也就不需要单独处理了 😄 。这种方式给一些有特殊需求的用户更合适一点。

**Comment by otakustay** [comment]
昨天比较晚了就没说太多，我整理一下我对组件的组合和复用的完整的观点

## 概念解构

首先我们可以思考一下，一个组件型的组件有哪些部分组成，我得出的结论是：

1. 提供其内部单一功能的片段（segment）
2. 这些片段之间的互动逻辑（coordination）
3. 片段的排列组合方式（skeleton）

## 拆解组件

对于组件的自定义和复用来说，这3者都是会有需求的，我们还是拿一个日期选择组件（DatePicker）来举个例子，很常见的定制需求就是2种：

1. 我需要替换其中月份选择的部分，由一个普通的Select变成一个4x3的Grid，这是典型的segment定制，复用了coordination和skeleton
2. 我不满足于月份选择必须是点击后才展开，我希望[直接在整个日历的右边展示12个月份](https://dev.office.com/fabric#/components/datepicker)，少一次点击就能选择月，这是segment和skeleton同时定制，仅复用coordination

所以我们在设计一个具备强大的定制能力的DatePicker之时，就考虑将这组件分成3部分：

1. segment：`MonthSelect`、`YearSelect`、`Calendar`
2. coordination：
    - `MonthSelect.onChange` => `Calendar.dates`
    - `YearSelect.onChange` => `Calendar.dates`
    - `Calendar.onSelect` => `DatePicker.onChange`
3. skeleton: 默认的布局

基于此，为了实现灵活的复用，我们需要提供每个层级相对应的功能：

1. 一个`coordinateAsDatePicker`函数，作用是传入指定的segment，返回添加了交互逻辑的新segment
2. 一个`datePickerSkeleton`函数，作用是传入指定的segment，返回依照默认布局的DatePicker组件，其内部可以复用`coordinateAsDatePicker`函数

## 代码演示

```js
import {MonthMap} from 'custom-ui';
import {Select, DatePicker} from 'antd';
import {coordinateAsDatePicker, datePickerSkeleton} from 'antd-prototype';

let CustomCalendar = ({dates, selectedDate}) => {
    return (
        <div>
            ...
        </div>
    );
};

// 定义segment
let components = {
    MonthSelect: MonthMap,
    YearSelect: Select,
    Calendar: CustomCalendar
};

// 一切默认的组件
export let DefaultDatePicker = DatePicker;

// 定制segment但保持默认skeleton的组件
export let DatePickerWithCustomizeMonthSelect = datePickerSkeleton(components);

let customDatePickerSkeleton = components => props => {
    let {MonthSelect, YearSelect, Calendar} = coordinateAsDatePicker(components);

    return (
        <div style={{display: 'flex'}}>
            <div style={{flex: 'auto', width: '300px'}}>
                <div
                    年：<YearSelect />
                </div>
                <Calendar />
            </div>
            <MonthSelect style={{flex: 1}} />
        </div>
    );
};

// 定制了segment和skeleton的组件
let DatePicker = customDatePickerSkeleton(components);
```

其中`coordinateAsDatePicker`的作用其实就是通过HOC为对应的组件追加props，其核心的HOC差不多就是这个：

```js
let assignProps = extraProps => Component => props => <Component {...extraProps} {...props} />

let CoordinatedYearSelect = assignProps({onYearChange})(YearSelect);
```

总而言之，这个Issue最初提出的其实只是segment的定制化，但如果涉及到skeleton也同样有定制需求，就需要再分离掉coordination以提供更好的复用，虽然会让概念变得很多对于一般人会晕

**Comment by paranoidjk** [comment]
复杂度太高，普通用户基本没法这么用的。

**Comment by otakustay** [comment]
框架的设计都是分级的，对于普通用户来说永远是`import {Foo} from 'antd'`，只要这句话产生的效果不变，其他增加的扩展性都是不可见的

当然这些设计本身会影响到框架内部的复杂度，这是很难平衡的，我也不怎么建议真做成这德性，理论归理论实际归实际

**Comment by bang88** [comment]
是的。真正使用的时候会很麻烦，如果写代码的不是纯前端，有可能是后台开发人员

**Comment by afc163** [comment]
感觉讨论的有点远了，现在主要问题是 Table 间接依赖了 Pagination、Select、Dropdown、Menu 等组件，额外提供一个不含以上内容的 SimpleTable 应该能缓解这个问题。

**Comment by otakustay** [comment]
> 感觉讨论的有点远了，现在主要问题是 Table 间接依赖了 Pagination、Select、Dropdown、Menu 等组件，额外提供一个不含以上内容的 SimpleTable 应该能缓解这个问题。

但我觉得避免不了会有人需要Table + Pagination，有人需要Table + Select……只说Table + Pagination的话还是很常见的，所以可能要`Table`、`SimpleTable`、`PaginatedTable`？

**Comment by qq645381995** [comment]
这只是个例子 难道要额外每个组件都出个 simple？

**Comment by qq645381995** [comment]
能不能当 Table 用了 Pagination 后 组件才会 import Pagination ？

**Comment by otakustay** [comment]
> 能不能当 Table 用了 Pagination 后 组件才会 import Pagination ？

ES现有的Module模型不会允许你这么做，未来的`import()`是异步的也很难这么做

**Comment by bang88** [comment]
类似
```
get pagination(){
   return require('pagination')
}
```
? 😢

**Comment by qq645381995** [comment]
可以在  Table 里面建立很多 js  Table_Pagination  当有Pagination 才渲染这个js？
这有个问题 imprort 进来 但是不调用 会不会build 到 js 中？

**Comment by otakustay** [comment]
现实的问题就是仅import不调用也会bundle，且无法被tree shaking

如果用require的话也许可行，但好好的es module转到cjs去太蛋疼了吧

**Comment by bang88** [comment]
> 现实的问题就是仅import不调用也会bundle，且无法被tree shaking


这个应该是 bundle的问题 😄

**Comment by qq645381995** [comment]
```
if (props.pagination) {
  module.exports = require('./table)
} else {
  module.exports = require('./table_pagination')
}

```

**Comment by otakustay** [comment]
不觉得是bundle的问题，你的依赖依旧是声明着的，调用不调用是运行期的，你怎么能期待作为构建期工具的bundler可以决定运行期的事情呢……

**Comment by otakustay** [comment]
> if (props.pagination) {
>   module.exports = require('./table)
> } else {
>   module.exports = require('./table_pagination')
> }

请注意Table是个类，在它还是类的时候是没有props的……

**Comment by qq645381995** [comment]
if (!props.pagination) {
  import {Table} form 'Table'；
} else {
  import {Table} form 'TablePagination'；
}

**Comment by qq645381995** [comment]
这个index.js 本身就是个组件！！

**Comment by bang88** [comment]
.... `import`目前为止还不能这样用

**Comment by otakustay** [comment]
> if (!props.pagination) {
> import {Table} form 'Table'；
> } else {
> import {Table} form 'TablePagination'；
> }

你真的理解es的语法吗……

> 这个index.js 本身就是个组件！！

那前提是有table和table_pagination两个模块存在，那select是不是也要2个模块，dropdown是不是也要2个……

**Comment by paranoidjk** [comment]
es6 的 module 是静态的。

**Comment by qq645381995** [comment]
对 还不能这么用，我的想法那就是要Table本身自己有很多配合好的组件，是有点麻烦，但是可以实现效果

**Comment by RaoHai** [comment]
@otakustay 

几个问题讨论。
1. segment 未必是单一组件，有可能有相互依赖。如何处理。
2. coordination 想得太简单。segment 和 coordination 未必一一对应。考虑某组件多处复用同一个 segment constructor， 你是传一个 segment constructor 还是传多个 segment constructor？
3. skeleton 可能和 coordination 有关联。

所以在这个设想里，极端状态下，是不是 segment、coordination、skeleton 都要同时作为依赖？太复杂了吧？

**Comment by otakustay** [comment]
> segment 未必是单一组件，有可能有相互依赖。如何处理。

我的理解里Segment是一个组件的组成的一部分，Segment的切割应该是有明确的分界线的。一个Segment本身可以是一个复杂的组件，内部还有其它Segment，但这是具备封装性的，没啥影响。Segment的相互依赖应该就是Coordination

> coordination 想得太简单。segment 和 coordination 未必一一对应。考虑某组件多处复用同一个 segment constructor， 你是传一个 segment constructor 还是传多个 segment constructor？

Segment是对组件内一个区块的定义，并不是“这个组件依赖的另一个组件”这样的概念，因此除非是真的完全相同的（List中的Item），否则答案是“传多个Segment Component”

> skeleton 可能和 coordination 有关联。

这个我确实没有仔细思考，那啥时候有些实例可能更适合展开讨论

**Comment by brookshi** [comment]
一个简单的问题就是： 灵活的组件必然会带来复杂度和学习成本的上升，如何权衡灵活性和易用性呢。
我觉得还是看产品定位，web端定位后台的话，易用性的权重应该就高些，比如我用antd的话那就代表我可能会用到里面大多数的控件来构建整套系统，component的功能越强大越易用就越好，如果只是想一个简单的table完全可以找单个table的库或自己写。mobile端的定位可能又不一样。根据产品定位来决定代码架构，一套方案不可能满足所有人的要求。

**Comment by otakustay** [comment]
可能主要问题还是来自于我对antd的定位的误解

**Comment by monkindey** [comment]
确实是一个很好的有关组件化的思考, 谢谢 @otakustay , 从中学习了很多。也很赞同@brookshi的看法。最近在想组件化的思路, 我暂时的思路是(也可能只是一种*空谈*): 

* 按功能分
* 按需使用
* 从小颗粒度, 然后慢慢加上功能

比如Table的, 从最简单的是来展示数据到可以支持分页功能到也可以支持多选功能的Table

```js
const Table = [makePagination, makeSelection].reduce((Decorated, feat) => feat(Decorated))
```

**Comment by benjycui** [comment]
Close for no more activities.
