### ISSUE TITLE
datePicker组件，月份由之前的11月变成了十一月，导致样式有问题

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#5912]
### Version
2.9.3

### Environment
mac chrome57

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/3849702/25422799/b44daa56-2a94-11e7-9d6f-78db297995b9.png)

### What is expected?
期望 将“一、二、三”改为之前“1、2、3”，这样一来，样式就不会有问题了

### What is actually happening?
如上图所示

**Comment by benjycui** [comment]
官网正常：

![image](https://cloud.githubusercontent.com/assets/3580607/25424732/085d0d60-2a9c-11e7-8b51-540c305b354c.png)

你们这个已经定制了不少样式了，所以可能还需要对文案变化进行一些调整。

**Comment by henryzp** [comment]
我在MonthPicker下面有找到一个monthCellContentRender方法：

```
<MonthPicker monthCellContentRender={(date, locale)=>{
                        let d = new Date(date._d),
                            month = d.getMonth() + 1;
                        return <span>{month}{locale.month}</span>;
                    }} placeholder="请选择月份" />
```

这样可以实现。。

但是针对datePicker这个组件呢？？也有这样的props么？

**Comment by henryzp** [comment]
其实我还有一个疑惑。。

之前是数字的是1、2、3，是什么想法让你们在新的版本中改成了一、二、三。。

能否解答一下？
