### ISSUE TITLE
希望 Form 的 setFieldsValue 可以设置没有声明的字段

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#5914]
### What problem does this feature solve?
就好比一个增删改查 新增的时候 modal 没有 id 就是新增 但是修改的时候 就有 id  由于 From 表单也不会写上id这个字段 所以 setFieldsValue 的时候 也不会保存 id  那样提交表单的时候 还要用 state 设置一个 id  merge 到 Form 表单中

### What does the proposed API look like?
希望 setFieldsValue 可以设置没有声明的字段

**Comment by afc163** [comment]
Not plan to support, you have to registry field before setFieldsValue.

**Comment by qq645381995** [comment]
@afc163  那我这样做吧
```
                    {getFieldDecorator('id')}
```

**Comment by liuchaofeng1230** [comment]
我的情况类似，form中有些字段是根据某一个字段的变化而改变的，现在这个版本改成了必须先声明就很麻烦了，只能用楼上的方法了。。

**Comment by afc163** [comment]
如果不声明，可以直接用 setState，没必要用 getFieldDecorator 了。

**Comment by chendonghai** [comment]
我也碰到这个问题

**Comment by blackcater** [comment]
我是 `{getFieldDecorator('id')(<Input style={{ display: "none" }} />)}`

**Comment by qq645381995** [comment]
@blackcater  {getFieldDecorator('id')} 就可以了

**Comment by qq645381995** [comment]
@afc163  如果用state  那这个form表单 就需要 {...this.props.form.getFieldValues,...this.state.formValues} 就有点麻烦而已
