### ISSUE TITLE
antd with electron-compile

### ISSUE THREAD

**Issue by q-depot** [ant-design/ant-design#5915]
### Version
2.9.3

### Environment
electron   electron-compile

### Reproduction link
[https://github.com/q-depot/antd-electron-test](https://github.com/q-depot/antd-electron-test)

### Steps to reproduce
clone the git repo;
npm install;
npm start;

### What is expected?
DatePicker element properly rendered

### What is actually happening?
missing css style

---
Hi, 

I'm trying to use antd with electron-compile, but I'm not sure how to properly include the library.
I've installed antd via npm then edited the "electron-compile" .compilerc.
If i set the style option to "css" I get "Invalid or unexpected token" the app try to load the css/less file. If I set the style to "true", the app works but it looks like it doesn't load the styles.

this is my .compilerc file:

{
  "env": {
    "development": {
      "application/javascript": {
        "presets": ["es2016-node5", "react"],
        "plugins": [["import", { "libraryName": "antd", "style": "true" }]],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": ["es2016-node5", "react"],
        "plugins": [["import", { "libraryName": "antd", "style": "true" }]],
        "sourceMaps": false
      }
    }
  }
}

**Comment by afc163** [comment]
```diff
"style": "true"
"style": true
```

**Comment by q-depot** [comment]
Hi,

that doesn't seem to fix it, I get something like this:
Uncaught SyntaxError: Unexpected identifier
/Users/Q/Code/Electron/antd-electron-test/node_modules/antd/lib/style/index.less:1 Uncaught SyntaxError: Invalid or unexpected token

I reckon I'm missing some other steps, no matter what options I pass or method I use(also tried to manually load the css), I can't get it to work.

Is this compatible with electron-compile at all?

thanks.

**Comment by afc163** [comment]
You need less-loader

**Comment by q-depot** [comment]
do I just have to run npm install or does it need some configuration? 
I'm getting a bit confused, I thought electron-compile was already taking care of .less files or at least it works with my other .less files, why do I need an extra dependency for antd?

**Comment by afc163** [comment]
Make sure your less-loader works on `node_modules/antd`
