### ISSUE TITLE
Spinner tip text alignment not horizontally centered when not wrapping a div.

### ISSUE THREAD

**Issue by DanHarman** [ant-design/ant-design#5919]
### Version
2.9.3

### Environment
windows 7, chrome 57.0.2987.133

### Reproduction link
[http://codepen.io/mmph/pen/aWBgyb?editors=0010](http://codepen.io/mmph/pen/aWBgyb?editors=0010)

### Steps to reproduce
See Codepen. Create a spin with a tip that does not have a child. 

### What is expected?
Spinner should align centrally above text of tip.

### What is actually happening?
Both element left justify.

**Comment by afc163** [comment]
```jsx
<Spin />
<p>loading text</p>
```

Don't use tip when Spin has no children
