### ISSUE TITLE
chrome固定列表格显示有问题

### ISSUE THREAD

**Issue by luyunfei** [ant-design/ant-design#5921]
### Version
2.9.2

### Environment
macbook 最新版chrome

### Reproduction link
[http://new-issue.ant.design](http://new-issue.ant.design)
![2017-04-26_14-48-53](https://cloud.githubusercontent.com/assets/4887426/25445959/74822c78-2ae2-11e7-9d5c-8e134dd5d4c2.png)

### Steps to reproduce
见截图

### What is expected?
见截图

### What is actually happening?
见截图

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
close for no re-producible demo
