### ISSUE TITLE
Badge always displaying error status 

### ISSUE THREAD

**Issue by usergit** [ant-design/ant-design#5922]
### Version
2.8.3

### Environment
mac os sierra, chrome 57, react 15.4.2

### Reproduction link
[http://codepen.io/anon/pen/zwNqZW?editors=001](http://codepen.io/anon/pen/zwNqZW?editors=001)

### Steps to reproduce
- import badge component
- have something inside the badge component   <Badge status="processing">something inside</Badge>

### What is expected?
the processing icon should display

### What is actually happening?
the error icon is displaying

**Comment by afc163** [comment]
It is a intented behavious, `status` only works when there is no children.

**Comment by usergit** [comment]
@afc163 I don't know the reasoning behind that but as an example, lets say Im fetching data from a server, I want to display the processing icon while data is being fetched, and return back to the counter icon after successfully fetching data and thats how I came across this issue. Hopefully this use case will be considered for future releases. For now Im overriding the css. But thanks for the feedback
