### ISSUE TITLE
TreeSelect 中 labelInValue设置问题

### ISSUE THREAD

**Issue by jxnuGBk** [ant-design/ant-design#5924]
### Version
2.9.1

### Environment
操作系统：win7-64； 浏览器：版本 54.0.2840.87 m

### Reproduction link
[https://github.com/react-component/tree-select/blob/master/src/Select.jsx](https://github.com/react-component/tree-select/blob/master/src/Select.jsx)

### Steps to reproduce
初始化TreeSelect的时候，labelInValue设置为false。
然后去后台获取一组数据，格式为
```
{label:'北京市', value:'010'}
```
并且同时把labelInValue设置为false。此时期望的结果是在控件里面显示北京。
但并没有，查看过代码后，发现 如果之前labelInValue设置为false，即使是后面设置为true，也会拿上一次的值；
```
componentWillReceiveProps(nextProps) {
...
 if ('value' in nextProps) {
      let value = toArray(nextProps.value);
      value = this.addLabelToValue(nextProps, value);
      value = this.getValue(nextProps, value);
      this.setState({
        value,
      });
      // if (nextProps.combobox) {
      //   this.setState({
      //     inputValue: value.length ? String(value[0].key) : '',
      //   });
      // }
    }
...
}


addLabelToValue(props, value_) {
    let value = value_;
    if (this.isLabelInValue()) {
    //
    }else{
   //
   }
}

isLabelInValue() {
//这里获取的是this当前的属性
    const { treeCheckable, treeCheckStrictly, labelInValue } = this.props;
    if (treeCheckable && treeCheckStrictly) {
      return true;
    }
    return labelInValue || false;
  }
```

### What is expected?
期望的结果是：初始加载时候，labelInValue为false（因为没有得到值），然后获取数据之后，labelInValue设为true,能够正常的显示数据

### What is actually happening?
仍然是按照没有设置labelInValue解析

---
我们是先初始化组件，然后再去后台拿到组件展示的值（{label:,value:}格式的），并且，只是后面设置的labelInVaue无效

**Comment by afc163** [comment]
labelInValue 不应该变化。

初始加载时候，给一个 `{ value: '', label: '' }` 作为初始值。
