### ISSUE TITLE
点击Button组件弹出Modal组件，然后关闭Modal组件，此时被点击过的那个Button组件依然处于被点击的状态

### ISSUE THREAD

**Issue by QDJobson** [ant-design/ant-design#5925]
### Version
2.9.2

### Environment
windows10  Chrome 59.0.3067.6

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
点击Button组件弹出Modal组件，然后关闭Modal组件，此时被点击过的那个Button组件依然处于被点击的状态。antd官网Modal组件页面的例子就能反映这个问题。

### What is expected?
点击Button组件弹出Modal组件，然后关闭Modal组件，此时被点击过的那个Button组件应该处于未点击的状态。

### What is actually happening?
点击Button组件弹出Modal组件，然后关闭Modal组件，此时被点击过的那个Button组件依然处于被点击的状态。

---
之前用的2.7.0版本没有这个问题，升级到2.9.2出现了这个问题，不知道是有意为之还是bug。

**Comment by afc163** [comment]
有意为之，可参看：https://github.com/ant-design/ant-design/pull/5597

**Comment by QDJobson** [comment]
@afc163 不太明白那位外国友人这么改的原因是什么，我们的产品经理反而觉得改成这样是不正常的。如果要想改回以前那样，请问有什么方便一点的办法吗？

**Comment by afc163** [comment]
这是合理的，保证 UI 的 accessibility。bootstrap 也是类似的行为：http://getbootstrap.com/javascript/#modals

**Comment by QDJobson** [comment]
@afc163 我在mac上用safari试了下，关掉Modal后Button并没有处于被点击的状态，是不是浏览器的兼容问题，你发的bootstrap那个倒是正常的。
safari版本：10.0.3（11602.4.8.0.1）

**Comment by afc163** [comment]
兼容性上貌似还有点问题，我晚点看看。

**Comment by afc163** [comment]
1. 点击 Button 后保持 focus 状态是 chrome 的默认逻辑，其他浏览器都没有。可以试试：http://getbootstrap.com/css/#buttons  antd 这里也保持浏览器的默认设定了。
2. 在 bootstrap 里 Modal 关闭后会 focus 触发按钮，这是 bootstrap 里做的。由于实现方式不一样，antd 目前没法和 bootstrap 保持一致。
