### ISSUE TITLE
表格选择有问题？

### ISSUE THREAD

**Issue by LuHugo** [ant-design/ant-design#5930]
表格点击全选，如果间隔有已经disabled的checkbox，并且间隔显示时选择会有问题。比如 一个表格有3行，一行和第三行的checkbox是启用的，第二行checkbox是禁用的，那么点击全选时会勾选第一行和第二行，第三行没有选中。期望的结果是选中第一行和第二行，这个问题怎么解决，antd版本是2.9.3， React版本是15.5.3

**Comment by abigaleypc** [comment]
遇到同样的问题
