### ISSUE TITLE
表格全选bug

### ISSUE THREAD

**Issue by LuHugo** [ant-design/ant-design#5934]
### Version
2.9.3

### Environment
macOS 10.12.4 / Chrome 57.0.2987.133 / react 15.5.3

### Reproduction link
![preview image](https://raw.githubusercontent.com/LuHugo/issuesImages/master/01.png)
[https://github.com/LuHugo/issuesImages/blob/master/01.png](https://github.com/LuHugo/issuesImages/blob/master/01.png)

### Steps to reproduce
表格行选择选择rowSelection 通过设置 getCheckboxProps 条件来确定哪些行可以选择。点击表头全选，如果可选选项中间有diabled 的行，则选择不正确

### What is expected?
全选时，禁用的行不要选中，未禁用的行必须选中

### What is actually happening?
点击表头全选，如果可选行中间有diabled checkbox 的行，则选择不正确

**Comment by infeng** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by LuHugo** [comment]
@infeng 解决了，仔细看了一遍文档，确定是数据源没有设置 key 导致了这个错误。

> 按照 React 的规范，所有的组件数组必须绑定 key。在 Table 中，dataSource 和 columns 里的数据值都需要指定 key 值。对于 dataSource 默认将每列数据的 key 属性作为唯一的标识。
如果你的数据没有这个属性，务必使用 rowKey 来指定数据列的主键。若没有指定，控制台会出现以下的提示，表格组件也会出现各类奇怪的错误。
![image](https://os.alipayobjects.com/rmsportal/luLdLvhPOiRpyss.png)
``` javascript
// 比如你的数据主键是 uid
return <Table rowKey="uid" />;
// 或
return <Table rowKey={record => record.uid} />;
```
