### ISSUE TITLE
同时创建多个InputNumber实例时出现堆栈溢出

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#5936]
### Version
2.8.2

### Environment
360浏览器7.1.1.640, react v15.4.2

### Reproduction link
[http://127.0.0.1](http://127.0.0.1)

### Steps to reproduce
创建2个以上的InputNumber实例
<div>
            <InputNumber key="111111"/>
                <InputNumber key="222222"/>
</div>

### What is expected?
正常显示

### What is actually happening?
出现堆栈溢出，InputNumber组件往后的 HTMLElement =》 input均无法正常输入输出

**Comment by afc163** [comment]
Have you try latest version of antd?

**Comment by afc163** [comment]
Try latest version of antd, which is 2.9.3 now.

**Comment by afc163** [comment]
I believe it has been fixed at https://github.com/ant-design/ant-design/issues/5510

Try antd@2.9.3
