### ISSUE TITLE
When I use loading in Table. The pagination can changed, the means I can change pageIndex when loading

### ISSUE THREAD

**Issue by NsNe** [ant-design/ant-design#5937]
### Version
undefined

### Environment
chrome58.0.3029.81

### Reproduction link
[http://codepen.io/NsNe/pen/mmRKmZ](http://codepen.io/NsNe/pen/mmRKmZ)

### Steps to reproduce
When I use loading in Table. The pagination can changed, the means I can change pageIndex when loading

### What is expected?
When I use loading in Table. I cannot do anything before response.

### What is actually happening?
I can change any pageIndex when loading. 

---
antd version: 2.9.3

**Comment by NsNe** [comment]
Actucally, The problem is I can click pagination to change page When loading.

**Comment by afc163** [comment]
2.x reproduce：https://codepen.io/afc163/pen/YzxrNGa
4.x reproduce：https://codepen.io/afc163/pen/wvqrgzO

ref: https://github.com/ant-design/ant-design/pull/32703
