### ISSUE TITLE
Tree组件激活样式失效

### ISSUE THREAD

**Issue by OwlAford** [ant-design/ant-design#5938]
### Version
2.9.3

### Environment
window10 chrome

### Reproduction link
[https://github.com/halo-design/react-halo-modern](https://github.com/halo-design/react-halo-modern)

### What is expected?
节点有active或者selected激活选中样式

### What is actually happening?
样式无变化

---
经排查，原因在于组件中将旧版a标签替换成了新的span标签，故样式继承无效。望修复。

**Comment by afc163** [comment]
The broken change has been reverted at rc-tree@1.4.8: https://github.com/react-component/tree/commit/5071842db8c61a081c28b0e0255757e80d54ee2b

Try `rm -rf node_modules && npm install`.

**Comment by OwlAford** [comment]
@afc163 我尝试删除node_modules文件夹重新安装npm包，但是问题依旧还在。

**Comment by OwlAford** [comment]
@afc163 I tried to delete this folder, but the problem still exists.

**Comment by afc163** [comment]
看看你本地安装的 rc-tree 的版本。

**Comment by OwlAford** [comment]
@afc163
 "name": "rc-tree",
  "version": "1.4.7"

"name": "rc-tree-select",
  "version": "1.9.4"

不知道这些信息是否足够

**Comment by afc163** [comment]
应该安装 1.4.8 才对的，检查一下你的 npm 网络环境或尝试清除缓存吧。

```
npm cache clean
```

**Comment by OwlAford** [comment]
@afc163 我尝试换了一台设备重新安装，rc-tree版本为 "name": "rc-tree", "version": "1.5.0",恕我直言，问题似乎仅仅在于样式，是否可以检查下less样式是否同步了节点修改。

**Comment by OwlAford** [comment]
@afc163 我这里经过尝试，在chrome里将选中样式的span标签名换为a标签，样式即可正常显示，所以推测问题是不是仅仅只是简单的样式问题。

**Comment by afc163** [comment]
rc-tree@1.4.7 是导致这个问题的错误版本，你只需要重新安装，npm 会更新到 rc-tree@1.4.8 这个正确的版本上。

**Comment by OwlAford** [comment]
我重新安装的时候，并没有安装到1.4.8的版本，而是更高的1.5.0，是否需要强制安装1.4.8

**Comment by afc163** [comment]
我本地试试。

**Comment by afc163** [comment]
我本地安装的是 rc-tree@1.4.8 。你的 npm 版本是多少？

**Comment by OwlAford** [comment]
3.10.10

**Comment by OwlAford** [comment]
补充一句，我在调试样式的时候，发现样式是指向antd/libs/tree/style 的

**Comment by afc163** [comment]
你是用 cnpm 或 tnpm 安装的么？

**Comment by OwlAford** [comment]
是的，使用cnpm安装

**Comment by afc163** [comment]
先用 npm 应该是好的，cnpm 对版本解析有些不同。

**Comment by OwlAford** [comment]
好的，我再重新试试

**Comment by afc163** [comment]
我用 cnpm 也是好的，你试试升级 cnpm 到最新？

```
$ cnpm -v
cnpm@4.5.0 (/usr/local/lib/node_modules/cnpm/parse_argv.js)
npm@3.10.10 (/usr/local/lib/node_modules/cnpm/node_modules/._npm@3.10.10@npm/lib/npm.js)
node@6.7.0 (/usr/local/bin/node)
npminstall@2.29.2 (/usr/local/lib/node_modules/cnpm/node_modules/._npminstall@2.29.2@npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 16.4.0 
registry=https://registry.npm.taobao.org
```

**Comment by OwlAford** [comment]
我的cnpm也是4.5.0版本

**Comment by OwlAford** [comment]
$ cnpm -v
cnpm@4.5.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\parse_argv.js)
npm@3.10.10 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@6.10.0 (C:\Program Files\nodejs\node.exe)
npminstall@2.26.4 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 x64 10.0.14393
registry=https://registry.npm.taobao.org

**Comment by afc163** [comment]
```
🎯   react-halo-modern@1.0.0 git:❨master❩ cat node_modules/antd/node_modules/rc-tree/package.json | grep version
  "version": "1.4.8",
```

**Comment by OwlAford** [comment]
不是很明白，需要将rc-tree强制安装到1.4.8吗，还是指我的配置有问题

**Comment by OwlAford** [comment]
由于网络问题，我这里尝试npm安装失败，所以无法复现，非常抱歉

**Comment by afc163** [comment]
npminstall 版本不太一致，你重新安装 cnpm 再试试。

**Comment by afc163** [comment]
```
cat node_modules/antd/node_modules/rc-tree/package.json | grep version
```

确保这个是 1.4.8 就行（也应该是 1.4.8）。

**Comment by OwlAford** [comment]
```
"name": "rc-tree",
  "version": "1.4.8",
```
强制安装rc-tree后，样式显示正常了，非常感谢 @afc163 
感谢 ant design 团队

**Comment by afc163** [comment]
你还是试试重装 cnpm 比较靠谱...

**Comment by OwlAford** [comment]
好的，我再重新安装cnpm试试

**Comment by OwlAford** [comment]
```
cnpm@4.5.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\parse_argv.js)
npm@3.10.10 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@6.10.0 (C:\Program Files\nodejs\node.exe)
npminstall@2.29.2 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 x64 10.0.14393
registry=https://registry.npm.taobao.org

```
已经重新安装cnpm，并重新安装\node_modules，竟然还是不行

**Comment by afc163** [comment]
先关了。

**Comment by HQidea** [comment]
> 由于网络问题，我这里尝试npm安装失败，所以无法复现，非常抱歉

试一下这样安装：
```
npm install --registry=https://registry.npm.taobao.org
```

**Comment by noonnightstorm** [comment]
我遇到相同的问题，解决了顺便share一下，导致的原因如下：
（1）antd依赖rc-tree了1.4.8的版本 , rc-select-tree依赖了rc-tree了^1.3.0的版本(最新版本)
（2）tnpm/cnpm会安装2个rc-tree的版本，并链接到node_modules的顶部，如图：
![image](https://user-images.githubusercontent.com/1336049/28806154-f3cbec80-76a0-11e7-9633-f52333a5d94f.png)
（3）脚手架构建打包的时候依赖包的读取路径被我修改了。一般来说是从require的当前文件的node_modules开始并往上寻找，我却把他设置为项目的node_modules开始寻找，导致了直接读取了项目顶部的最新的版本导致

解决方法：
检查一下依赖包的读取顺序，并修正一下。

**Comment by afc163** [comment]
https://github.com/react-component/tree-select/commit/29791cedc486674f3178979df104d915d9f25cdd#commitcomment-23452966
