### ISSUE TITLE
Tree树形控件选中样式无效（已删除node_modules并重新安装npm package）

### ISSUE THREAD

**Issue by OwlAford** [ant-design/ant-design#5940]
### Version
2.9.3

### Environment
window10 chrome

### Reproduction link
[https://github.com/ant-design/ant-design/issues/5938](https://github.com/ant-design/ant-design/issues/5938)

### Steps to reproduce
Click the tree component node

### What is expected?
Have the selected style

### What is actually happening?
Nothing happen

---
遵从@afc163提议删除node_modules重新安装所有npm包，并未达到预期效果

**Comment by afc163** [comment]
看看你本地安装的 rc-tree 的版本。

**Comment by afc163** [comment]
trace #5938
