### ISSUE TITLE
Add onPressEnter for select component

### ISSUE THREAD

**Issue by hylin** [ant-design/ant-design#5942]
### What problem does this feature solve?
When we use Select with 'combobox' mode, we usually do some thing when user press Enter, like do a search action.
Hope to support this feature.

### What does the proposed API look like?
```<Select onPressEnter={this.handlePressEnter}>{options}</Select>```

**Comment by afc163** [comment]
https://github.com/react-component/select/blob/59ad5ed6113d8873b20078be58beeaca661ca18b/examples/combobox.js

**Comment by afc163** [comment]
Maybe we should fix `onKeyDown` in `Select[combobox]`? @yesmeck @RaoHai

**Comment by yesmeck** [comment]
@afc163 That example put `onKeyDown` on outer `div`...

**Comment by jaredleechn** [comment]
same feat request, it's very useful to add onPressEnter for Select

**Comment by afc163** [comment]
Try https://ant.design/components/auto-complete/

**Comment by afc163** [comment]
Workaround for now.

1. AutoComplete with input[onKeyDown]: https://codepen.io/afc163/pen/VWRqVo?editors=001
2. Select with onKeyDown in wrapper: https://codepen.io/afc163/pen/NgJeep?editors=001 like @yesmeck said.

---

And we still need to fix Select[combobox][onKeyDown].

**Comment by yesmeck** [comment]
I think a proper name is `onInputKeyDown`?

**Comment by danedavid** [comment]
Hi, I would like to take this one. What is the functionality desired ? Is the props going to be `onPressEnter` or a more general `onInputKeyDown` ? If I'm not mistaken, this is the consolidated TODO:
**Add an `onInputKeyDown` prop to `Select` component, which takes a function of the signature:**
```
onInputKeyDown?: (value: SelectValue, keyCode: number) => any;
```

Lastly, I hope the changes are to be committed only here, and not in `rc-select` right ?

**Comment by yesmeck** [comment]
@danedavid Yes, we should add this prop to `rc-select`.  But this function should have signature like this:

`onInputKeyDown?: (e: React.KeyboardEvent<HTMLTextAreaElement>) => void;`

**Comment by danedavid** [comment]
@yesmeck So shouldn't this issue be closed and re-opened on that repo ?

**Comment by yesmeck** [comment]
It's ok to keep this issue in here.

**Comment by danedavid** [comment]
There is already an `onKeyDown` listener for the `input` element inside the component [#L210](https://github.com/react-component/select/blob/master/src/Select.jsx#L210). So I hope you want to accept any function as a prop to  `Select` component, and pass it down to `SelectTrigger` [here](), without interfering with the keyDown inside ? But there is no `onKeyDown` prop for the `SelectTrigger` component it seems..

**Comment by yesmeck** [comment]
Why pass it down to `SelectTrigger`? I think what we need to to is calling `prop.onInputKeyDown` inside `Select` 's `onInputKeyDown`?

**Comment by danedavid** [comment]
@yesmeck I have raised PR. Pls hav a look. What I've done is pass the `onInputKeyDown` prop to the `chaining()` function inside the input element's `onKeyDown`.

**Comment by danedavid** [comment]
The thing is, it gets fired on every `keyDown` event inside the `Select`, like when we navigate through `Options` using arrow keys... is that desired ? And is this only required in `combobox` mode or all modes ?

**Comment by yesmeck** [comment]
I think it's ok to fire on every `keyDown` event and in all modes. People who want `Enter` event just check `e.keyCode`.

**Comment by tduchars** [comment]
I know this is a very old thread but the solution to using "enter" is to use the 'onSelect' function with its value property.

I used it to scroll down using arrow keys and press enter to redirect to whatever was in the ant design select component options. Like so...

```
    const onSelect = (value) => {
        console.log(value, 'selected')
    }

    return (
        <Select
            value={null}
            showSearch
            style={{ width: searchW, paddingLeft: searchP }}
            dropdownStyle={{ zIndex: 9999 }}
            onSelect={onSelect}
            onFocus={onFocus}
            onBlur={onBlur}
            onSearch={onSearch}
        >
                {searchResults.map((searchResult) => {
                    return (
                            <Option value={searchResult} key={somekey}>
                                    {searchResult}
                            </Option>
                    )
                })}
        </Select>
    )
```

**Comment by bryandandan** [comment]
I made it work like this:

```jsx
<Select
  value={searchValue}
  onChange={value => setSearchValue(value)}
  onInputKeyDown={e => {
    if (e.key === 'Enter') {
      e.stopPropagation() // <-- this is the trick
      setSearchValue(e.target.value)
    }
  }}
/>
```
