### ISSUE TITLE
配置修正： npm run site 后，copy到在本地server上的二级目录下能正确显示

### ISSUE THREAD

**Issue by bert1100** [ant-design/ant-design#5947]
### What problem does this feature solve?
当我将生成的_site/目录下 copy 到  我本地web server的 ant-design后，通过http://my.com/ant-design/ 来访问首页时，出现404。
>以下是我经历的操作：
- 修改 site/bisheng.config.js : 增加 root：’http:://my.com/ant-design/ ‘ 使得生成的静态资源地址正确
- 修改site/theme/index.js :修改path： ’ant-design/ ‘ 
- 再次运行： npm run site  后，报错。

### What does the proposed API look like?
 http://my.com/ant-design/ 能正确访问首页

**Comment by benjycui** [comment]
自行研究 bisheng，事实上你也没有自行部署一个 ant.design 的官网的必要吧。

**Comment by bert1100** [comment]
好的，多谢指点。

**Comment by zhangkai123995** [comment]
@bert1100 最终你是怎么解决的这个问题？我也遇到了同样的情况。困惑
