### ISSUE TITLE
ant-design 基本理念里面描述的功能在API不存在？

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design#5949]
### What problem does this feature solve?
在这里描述的功能：
https://ant.design/docs/spec/feature-cn
字数校验框示例
使用颜色和下划线标注超出的文案，系统即时反应，以便用户进行调整。

### What does the proposed API look like?
增加一个字段可以设置最大字数

**Comment by afc163** [comment]
对，不是所有规范都实现了的。
