### ISSUE TITLE
Table API

### ISSUE THREAD

**Issue by lddfor** [ant-design/ant-design#5950]
### What problem does this feature solve?
table 的 getCheckboxProps 方法 API不够详细.在此方法中的具体参数.

### What does the proposed API look like?
能够具体写getCheckboxProps内的用法,Function(record)  还可以
getCheckboxProps(value){
            return {
            defaultChecked: true,
            disabled: true,
           ...
            }
          },
这两种都是可以的.是选中功能的比较常用的用法.

**Comment by afc163** [comment]
建议用 rowSelection.selectedKeys 代替 getCheckboxProps 里的 defaultChecked，更方便控制。
