### ISSUE TITLE
select onFocus bug 

### ISSUE THREAD

**Issue by 39Er** [ant-design/ant-design#5954]
### Version
2.9.3

### Environment
ubuntu16.04，node4.5

### Reproduction link
[http://codepen.io/39Er/pen/zwZZqx?editors=1011](http://codepen.io/39Er/pen/zwZZqx?editors=1011)

### Steps to reproduce

 \<Select/> doesn't have \<Option />, if it has the "placeholder" property,when I focus the input ,it doesn't trigger the onFoucs function,but if click the arrow,it can trigger the onFocus function.if it doesn't have the "placeholder" property,it will be ok:Wherever I click on the input , it will trigger the onFocus function.
I'm not sure whether this is similar with #5741 or not.

### What is expected?
when \<Select> has the "placeholder" property, wherever I click on the input , it will trigger the onFocus function

### What is actually happening?
when \<Select> has the "placeholder" property,I focus the input ,it doesn't trigger the onFoucs function,but if click the arrow,it will be ok

**Comment by 39Er** [comment]
This bug is still not fixed, when click placeholder ,it trigger onFocus twice ! But when I click the arrow , it only trigger once.

**Comment by yesmeck** [comment]
@39Er Try reinstall node_modules.
