### ISSUE TITLE
Table 设置固定列和头  会导致位置位置错乱

### ISSUE THREAD

**Issue by guoqn** [ant-design/ant-design#5956]
### Version
2.9.3

### Environment
MacBookpro chorme(57.0.2987.133 (64-bit))  antd-2.9.3

### Reproduction link
[http://codepen.io/anon/pen/gWmROa?editors=0010](http://codepen.io/anon/pen/gWmROa?editors=0010)

### Steps to reproduce
const {Table } = antd;

const columns = [
    {
        "key": "endpoint",
        "dataIndex": "endpoint",
        "title": "主机名",
        "hidden": 0
    },
    {
        "key": "sertypes",
        "dataIndex": "sertypes",
        "title": "机器类型",
        "hidden": 0
    },
    {
        "key": "cachegroup_name",
        "dataIndex": "cachegroup_name",
        "title": "cachegroup",
        "hidden": 0
    },
    {
        "key": "note",
        "dataIndex": "note",
        "title": "报警名称",
        "hidden": 0
    },
    {
        "key": "alarmTime",
        "dataIndex": "alarmTime",
        "title": "报警时间",
        "hidden": 0
    },
    {
        "key": "flag_user",
        "dataIndex": "flag_user",
        "title": "操作者",
        "hidden": 0
    },
    {
        "key": "keepTime",
        "dataIndex": "keepTime",
        "title": "持续",
        "fixed":"right",
        "hidden": 0
    }
];
const data = [
    {
        "endpoint": "youchi-beijing-beijing-1-123-123-123-123",
        "key": "1",
        "cachegroup_name":"1",
        "sertypes": "zabbix",
        "note": "gslb检测到本机123.123.123.123已连续3分钟失败率高于25%,当前为53.15%",
        "alarmTime": "2017-04-28 17:57:02",
        "flag_user":"--",
        "keepTime": "7分钟",
    },
{
        "endpoint": "youchi-beijing-beijing-1-123-123-123-123",
        "key": "2",
        "cachegroup_name":"1",
        "sertypes": "zabbix",
        "note": "gslb检测到本机123.123.123.123已连续3分钟失败率高于25%,当前为53.15%",
        "alarmTime": "2017-04-28 17:57:02",
        "flag_user":"--",
        "keepTime": "7分钟",
    },
{
        "endpoint": "youchi-beijing-beijing-1-123-123-123-123",
        "key": "3",
        "cachegroup_name":"1",
        "sertypes": "zabbix",
        "note": "gslb检测到本机123.123.123.123已连续3分钟失败率高于25%,当前为53.15%",
        "alarmTime": "2017-04-28 17:57:02",
        "flag_user":"--",
        "keepTime": "7分钟",
    },
{
        "endpoint": "youchi-beijing-beijing-1-123-123-123-123",
        "key": "4",
        "cachegroup_name":"1",
        "sertypes": "zabbix",
        "note": "gslb检测到本机123.123.123.123已连续3分钟失败率高于25%,当前为53.15%",
        "alarmTime": "2017-04-28 17:57:02",
        "flag_user":"--",
        "keepTime": "7分钟",
    },
{
        "endpoint": "youchi-beijing-beijing-1-123-123-123-123",
        "key": "5",
        "cachegroup_name":"1",
        "sertypes": "zabbix",
        "note": "gslb检测到本机123.123.123.123已连续3分钟失败率高于25%,当前为53.15%",
        "alarmTime": "2017-04-28 17:57:02",
        "flag_user":"--",
        "keepTime": "7分钟",
    }];
ReactDOM.render(
  <div>
    <Table columns={columns} dataSource={data} scroll={{x:1000,y:300}} bordered/>
  </div>
, mountNode);

### What is expected?
table 的body内容和thead表头能够对齐

### What is actually happening?
table 的body内容的单元格和thead 表头  位置错乱

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5825
