### ISSUE TITLE
disable tooltip on select

### ISSUE THREAD

**Issue by codTango** [ant-design/ant-design#5958]
### What problem does this feature solve?
It seems select will show a tooltip to display selection when hover the select for couple seconds. But it seems no way I can turn it off, nor control what to display for the tooltip. So is it possible that expose an API to turn it off, or specify what text will be displayed for tooltip?

### What does the proposed API look like?
tooltip: true/false // to turn on/off tooltip
tooltipContent: string // specify what content will be displayed for tooltip

**Comment by paranoidjk** [comment]
https://ant.design/components/select/#Option-props

user `Option.props.title`

**Comment by zlk89** [comment]
`Option.props.title` cannot turn off the tooltip

**Comment by sherinmarlabs** [comment]
The following worked for me. I added a single space character to the title prop and it stopped showing the tooltip.
`<Option title=" " value="1">A</Option>`

**Comment by sainisagar310** [comment]
On microsoft edge browser, Still showing the tooltip.

**Comment by sainisagar310** [comment]
On microsoft edge browser, Still showing the tooltip.

**Comment by xiaochuankk123** [comment]
@sherinmarlabs hey,bro,it's very nice. And it resolved my problem.

**Comment by rohan-pawar-apprely** [comment]
If you want to disable the default tooltip that appears when hovering over the Ant Design Select component (which shows the selected value), you can use the following code:

const handleMouseEnter = (e) => {
  e.target.removeAttribute('title');
};


<Select
  placeholder="Project"
  onMouseEnter={handleMouseEnter} // Disables the default tooltip on hover
  options={projectList}
/>

The onMouseEnter event handler removes the title attribute from the Select element when the mouse hovers over it. This will disable the default browser tooltip that usually displays the selected value.
