### ISSUE TITLE
展示重复数据只能用table？

### ISSUE THREAD

**Issue by blackmatch** [ant-design/ant-design#5972]
### What problem does this feature solve?
有这样一个需求，从服务器返回多条数据（比如多张图片），希望能把这些数据都展示出来，能否使用类似数据的绑定的方式展示出来，提供的table组件不能满足需求。

### What does the proposed API look like?
类似于angular的ng-repeat功能。

**Comment by afc163** [comment]
这个直接用 React 就行了。

**Comment by blackmatch** [comment]
感谢指导。我刚开始学习react和ant design，有点晕了。。。
