### ISSUE TITLE
能否修改Edit的Icon把下面那个横线去掉？

### ISSUE THREAD

**Issue by dreamcog** [ant-design/ant-design#5976]
### What problem does this feature solve?
在所有Icon中，只有Edit这个Icon在使用过程中，显得和其他的Icon不太统一，主要是下面这个横线造成的

### What does the proposed API look like?
能否考虑去掉，或者提供一个没有横线的这个Icon？

**Comment by paranoidjk** [comment]
https://ant.design/components/icon-cn/#本地部署

可以使用你自己的 iconfont
