### ISSUE TITLE
能否去掉Button的组价，2个字的Button中间一定会强制加一个空格的问题？

### ISSUE THREAD

**Issue by dreamcog** [ant-design/ant-design#5977]
### What problem does this feature solve?
无法定义一个2个字的，中间没有空格的Button

### What does the proposed API look like?
能否去掉这个设定，或者增加一个option选项，允许不在中间插入空格。谢谢。

**Comment by paranoidjk** [comment]
并不会，请提供一个可复现demo。

**Comment by benjycui** [comment]
这个是设计原则规定的，所以代码会自动添加。

**Comment by dreamcog** [comment]
@benjycui 这是什么设计原则规定的？这样很不协调。主要是，能否提供一个能解决这个的方法？

**Comment by dreamcog** [comment]
![image](https://cloud.githubusercontent.com/assets/1401184/25616644/9fef2ec8-2f70-11e7-989c-83ffeeae4c8f.png)

上下很不协调。@paranoidjk

**Comment by afc163** [comment]
只有两个文字的才应该加空格，有图标的不应该加，我试试修复下。

**Comment by paranoidjk** [comment]
@afc163 这个有考虑 css 解决吗？`letter-space`, `word-space` 之类的属性

这么一堆代码去手动加空格有点太勉强的感觉.. https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L13

**Comment by afc163** [comment]
没啥区别，这段代码省不掉，纯 css 判断不了两个汉字。

**Comment by dreamcog** [comment]
@afc163 谢谢。因为这个的确困扰了很久，其他的都能忍的，这个稍微比较麻烦。
其实这个可以让用户自己决定，中间加不加空格其实可以让用户自己来设置，组件强制加一个空格会其实挺难受的。
