### ISSUE TITLE
Select[mode='tags'] with OptGroup has display problem

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#5986]
http://codepen.io/ddcat1115/pen/aWwdgN?editors=0010

need to fix or add a usage demo

**Comment by johnsbassicity** [comment]
Fix it yourself. I quit.


________________________________

**Comment by yesmeck** [comment]
@ddcat1115 codepen 的链接里没有例子，这个具体是什么问题？

**Comment by yesmeck** [comment]
@ddcat1115

**Comment by muzea** [comment]
It is embarrassing that I did not see this in search of the issue.
We can use 'multiple' instead of 'tags' to circumvent this problem,so will this problem be fixed?

**Comment by yesmeck** [comment]
Fixed in rc-select@7.5.1
