### ISSUE TITLE
Use `prop-types` standalone package

### ISSUE THREAD

**Issue by Haroenv** [ant-design/ant-design#5988]
### What problem does this feature solve?
Instead of using `React.PropTypes`, we should use `import PropTypes from 'prop-types'`, which has been changed in React 15.5, and will be a breaking change later

### What does the proposed API look like?
```js
import PropTypes from 'prop-types'

Component.propTypes = {
  someProp: PropTypes.any,
};
```

**Comment by yesmeck** [comment]
Duplicate of #5678

**Comment by Haroenv** [comment]
Ah, sorry, I didn't find that issue while searching
