### ISSUE TITLE
getInitialState was defined on xxx,

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#599]
* 升级到 0.10 之后出现
Warning: getInitialState was defined on AntTable, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
具体的错误如下
![image](https://cloud.githubusercontent.com/assets/7006864/11419619/9c924426-9463-11e5-8dbc-689479cf4347.png)
另外，一直提示我加载了多个react
`npm ls | grep react` 查看发现并没有
![image](https://cloud.githubusercontent.com/assets/7006864/11419666/e2f30572-9463-11e5-9439-0d8f3ee8e252.png)
也没有其它地方加载。

**Comment by afc163** [comment]
加载多个 react ，可以看下是否这个问题：https://github.com/ant-design/ant-design/issues/525#issuecomment-157000158

**Comment by falltodis** [comment]
设为externals 不起作用，正在逐步排查。

**Comment by afc163** [comment]
有问题再开吧。
