### ISSUE TITLE
IE10/11 DatePicker bug

### ISSUE THREAD

**Issue by vinks** [ant-design/ant-design#5991]
### Version
2.9.3

### Environment
IE10, Windows 7 (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), also on early version of IE11(11.9.9600.18537)

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Backspace click on date edit field

### What is expected?
Removing last character in date

### What is actually happening?
We returns to previous page, as we clicked on back browser button

**Comment by afc163** [comment]
similar with #4601

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by sngeth** [comment]
This doesn't seem fixed on IE11 or Firefox. I tested it on ant.design's production site
https://ant.design/components/date-picker/

Click on Select date in the examples box. Hit backspace. It takes me to previous page.

Issue does not occur in Chrome.
