### ISSUE TITLE
页面里的Breadcrumb（面包屑控件）中的 item 过多时，会折行显示

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design#5992]
### Version
2.9.3

### Environment
macOS 10.12.3, Google Chrome 57.0.2987.133, React v15.5.4

### Reproduction link
[http://codepen.io/LinkinZoo/pen/pPwewO](http://codepen.io/LinkinZoo/pen/pPwewO)

### Steps to reproduce
打开codepen即可看到：页面里的Breadcrumb（面包屑控件）中的 item 过多时，会折行显示。
重现机率：必现。

### What is expected?
期望面包屑控件在内容超出宽度时，可以横向滚动或折叠收起，亦或者让后面的item显示全，前面的用...省略；折叠收起效果的图片链接：http://chuantu.biz/t5/77/1493728650x2890174351.png

### What is actually happening?
页面里的Breadcrumb（面包屑控件）中的 item 过多时，会折行显示。

**Comment by afc163** [comment]
Thank you for reporting. But I think it is better for keeping this in a simple way.
