### ISSUE TITLE
ant-transfer checkall button should only control searhed items not all item list (search mode)

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#5993]
### Version
2.9.3

### Environment
ant 2.9.3

### Reproduction link
[https://ant.design/components/transfer-cn/#components-transfer-demo-advanced](https://ant.design/components/transfer-cn/#components-transfer-demo-advanced)

### Steps to reproduce
chose 1 item
input some letter (do not search the chosed item)
click checkall button
click checkall button

### What is expected?
the item chosen before should be chosen

### What is actually happening?
no item is chosen

---
const holder = checkAll ? [] : filteredDataSource.map(item => item.key);
I think [] should include the items not showed in search mode

**Comment by benjycui** [comment]
I don't think that we can find the **right** behavior. You can control the behavior with `selectedKeys `

**Comment by wangtao0101** [comment]
用中文:))
I don't think that we can find the right behavior. 这个没错。
但是这个checkall按钮的行为是不一致的，这个有问题的
例如：搜索模式下 全选会选中当前搜索的条目，但是反选却反选了整个list，行为上至少要一致吧？

**Comment by benjycui** [comment]
> 搜索模式下 全选会选中当前搜索的条目，但是反选却反选了整个list，行为上至少要一致吧？

按我的理解，全选和反选，只要做到 WYSIWYG 就可以了，至于那些没展示出来的数据，是否该被选中或者反选，由业务代码决定。

**Comment by benjycui** [comment]
Table 也是如此。

**Comment by afc163** [comment]
Make sure selection only affect filtered items.
