### ISSUE TITLE
Add support for multi-index in Mention using optGroup-like API

### ISSUE THREAD

**Issue by THook** [ant-design/ant-design#5995]
### What problem does this feature solve?
I am using the Mention component to retrieve data from Algolia. I would like to use option groups inside the suggestion menu, to be able to use multi-indexing. The Select component api is perfect for that kind of need :

     <OptGroup label="Manager">
       <Option value="jack">Jack</Option>
       <Option value="lucy">Lucy</Option>
     </OptGroup>

On end user experience, it would allow me to show different types of suggestion while clearly differentiating them. I can show some real examples if needed

Thanks!

### What does the proposed API look like?
    <NavGroup label="Manager">
       <Nav value={hit.name} data={hit}><span>{hit.name}</span></Nav>
    </NavGroup>

**Comment by afc163** [comment]
Sorry, no plan cause short of hands.
