### ISSUE TITLE
Breadcrumb 添加展示方式

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design#5996]
### What problem does this feature solve?
现象：当Breadcrumb（面包屑控件）中的 item多到无法在一行中显示时，现在会以折行的方式展现；
现象展示：http://codepen.io/LinkinZoo/pen/pPwewO；
期望：在Breadcrumb中的item过多时，希望可以在一行中展示，如横向滚动或折叠收起；
折叠收起效果展示：http://chuantu.biz/t5/77/1493728650x2890174351.png

### What does the proposed API look like?
期望在API中添加参数style，默认为当前效果；添加其他展示方式，如横向滚动或折叠收起；
折叠收起效果：
地址：坚果云 https://www.jianguoyun.com
截图：http://chuantu.biz/t5/77/1493728650x2890174351.png

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/5992
