### ISSUE TITLE
ant-transfer performance problem

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#5997]
### Version
2.9.3

### Environment
codepen， chrome58

### Reproduction link
[http://codepen.io/yuecjnadt/pen/WjOPwL?editors=0010](http://codepen.io/yuecjnadt/pen/WjOPwL?editors=0010)

### Steps to reproduce
I'm optimize the ant transfer performance in our project. And i find the function some is used in many place 
 especially in transfer，but the function is low performance than includes when compare  single value. 
The beachmark is here : http://codepen.io/yuecjnadt/pen/WjOPwL?editors=0010
The below code is low performance when there are hundreds of items.
https://github.com/ant-design/ant-design/blob/master/components/transfer/index.tsx#L92

### What is expected?
use includes

### What is actually happening?
use some

---
Considering the compatibility, you can use polyfill,  import 'core-js/fn/array/includes';

**Comment by benjycui** [comment]
Yep, it seems that you are right.

Could you PR to fix this issue?

**Comment by afc163** [comment]
Maybe https://www.npmjs.com/package/array-includes ?

**Comment by benjycui** [comment]
@afc163 we had recommended users to import es6-shim

**Comment by wangtao0101** [comment]
在我的项目里我用babel-plugin-transform-runtime 和 babel-runtime，然后结合 babel-polyfill导入原型方法，能够非常好的控制包大小

**Comment by wangtao0101** [comment]
我就不PR了，这个你们可能需要考虑下架构上引入哪种polyfill，最好按需的

**Comment by afc163** [comment]
It is user-side decision.

**Comment by wangtao0101** [comment]
OK. I can push a PR without polyfill
