### ISSUE TITLE
InputNumber的step在最近更新的版本中无法使用

### ISSUE THREAD

**Issue by minzhang2** [ant-design/ant-design#5998]
### Version
2.9.3

### Environment
chrome浏览器

### Reproduction link
[http://codepen.io/anon/pen/aWwxVg?editors=001](http://codepen.io/anon/pen/aWwxVg?editors=001)

### Steps to reproduce
输入多余两位小数，多余的小数位不清零

### What is expected?
输入多余两位小数，多余的小数位清零

### What is actually happening?
输入多余两位小数，多余的小数位不清零

**Comment by afc163** [comment]
这是合理的，step 只负责增减数字的大小，不负责格式化。

**Comment by minzhang2** [comment]
![gif](https://cloud.githubusercontent.com/assets/15793061/25796592/a88fea72-340c-11e7-9bdb-c9186ab7b1d0.gif)
之前的版本有这种处理，还是挺好用的，为啥2.93版本之后要去掉呢，让人很难接受啊，我们现在要达到这种效果还要自己处理下，InputNumber如果能加上不是更好嘛

**Comment by minzhang2** [comment]
![gif](https://cloud.githubusercontent.com/assets/15793061/25796682/1b09ab7e-340d-11e7-8307-a69bb25818b1.gif)
之前的版本有这种处理，还是挺好用的，为啥2.93版本之后要去掉呢，让人很难接受啊，我们现在要达到这种效果还要自己处理下，InputNumber如果能加上不是更好嘛 @afc163

**Comment by afc163** [comment]
之前是当成 bug 修复了，我晚点再考虑下。

**Comment by infeng** [comment]
我也希望加上这种处理，或者变成可选项

**Comment by afc163** [comment]
ref #5012

**Comment by afc163** [comment]
https://github.com/react-component/input-number/issues/39

感觉要 PK 一下。@ystarlongzi

**Comment by ybning** [comment]
@afc163 
可以考虑添加一个属性，可以设置保留几位小数

**Comment by minzhang2** [comment]
能不能加一个属性啥的发一个版本，项目要上线啊 @afc163

**Comment by afc163** [comment]
`<InputNumber precision={2} />`

不过新特性要等月底 `2.11` 了。

**Comment by ystarlongzi** [comment]
还是赞同保持目前 step 的这种交互，然后增加个属性 `precision` 可以控制小数位数。

btw，实际上我们在项目中也有对 `<InputNumber />` 又简单了封装下，仅是为了实现可以控制小数位数的功能。
