### ISSUE TITLE
部分输入组件支持三套大小

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#60]
`select`、`datepicker`、`input-number` 支持三套大小：

- 大（32px，用于表单中）
- 中（28px，默认）
- 小（22px，用于小号表格中）

和 input 的三种大小保持一致：http://ant.design/components/form/#code-box-components-form-demo-input-size

**Comment by zhujun24** [comment]
select 和 input-number 中的 input 分别是在 Select.js 和 InputNumber.js 中写固定了的，要实现支持三套大小，可能还需要提供API @yiminghe

**Comment by afc163** [comment]
用样式改如何？

**Comment by yiminghe** [comment]
mixin

**Comment by zhujun24** [comment]
mixin 怎么实现？提供传递 className 的 API 来修改样式可以吗？

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design/blob/master/style/components/inputNumber.less#L45

**Comment by zhujun24** [comment]
mixin 也实现不了吧，得有个 API 来设置 className ，不同的 className 对应不同的样式

**Comment by afc163** [comment]
select 和 input-number 用 mixin 搞不定的。

**Comment by yiminghe** [comment]
select/input-number 组件可以设置 className

**Comment by zhujun24** [comment]
通过修改 prefixCls 来设置 className 么？

**Comment by yiminghe** [comment]
<InputNumber className="" />

**Comment by afc163** [comment]
fixed via #121
