### ISSUE TITLE
Cascader not working on IE9

### ISSUE THREAD

**Issue by pimkle** [ant-design/ant-design#6000]
### Version
2.9.3

### Environment
windows8 IE TESTER IE9 MODE

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
On win8, open IE TESTER, open an IE9 tab, open the Cascader example page, component doesn't seem to work. I'm not using IE's emulator, so I'm sure polyfills would work.

### What is expected?
Cascader component would work beautifully on IE9

### What is actually happening?
Cascader component doesn't work at all on IE9

---
I really would like to know whether the component is working on IE9, if it doesn't work, I would like to know when ant design team will solve the problem. My project needs to support IE9, I can't use this component until it supports IE9.

**Comment by afc163** [comment]
![cascader-ie9](https://cloud.githubusercontent.com/assets/507615/25652076/e97b8994-3018-11e7-9fc3-7029b4947c66.gif)

It works.

**Comment by pimkle** [comment]
Yeah, I'm not using it any more.
