### ISSUE TITLE
表格选择第二页的元素会跳转回第一页

### ISSUE THREAD

**Issue by alili** [ant-design/ant-design#601]
设置rowSelection 
选择第二页的元素 会自动跳回到第一页
单选和多选都有这个问题

**Comment by afc163** [comment]
上具体代码看看吧。

http://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by alili** [comment]
开了排序之后，选择radio之后，排序也会乱跳，晚一点我贴代码

**Comment by afc163** [comment]
看下这个例子的写法能否修复你的问题：http://ant.design/components/table/#demo-ajax

**Comment by mongris** [comment]
这个例子在 safari 9.0.2 下交互不能：
1. 名字过滤不起作用
2. 年龄排序不起作用
3. 分页翻页不起作用

**Comment by afc163** [comment]
请看例子的说明。

**Comment by afc163** [comment]
有问题新开吧。
