### ISSUE TITLE
steps组件首次加载闪烁

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#6010]
### Version
2.9.3

### Environment
macos chrome

### Reproduction link
[https://ant.design/components/steps-cn/](https://ant.design/components/steps-cn/)

### Steps to reproduce
刷新。然后会看到steps组件会慢一拍才加载

### What is expected?
没有白屏等待

### What is actually happening?
其他组件都加载完成了 stpes 组件要慢一拍才显示出来

---
其他页面的组件没有这个问题，都是页面出来 组件就立即加载

**Comment by afc163** [comment]
目前 Steps 由于 title 和 message 的长度不确定，实现上需要使用 js 动态布局，因此会到 componentDidMount 之后才展现，暂时没有好的解决方案。

**Comment by benjycui** [comment]
需要用 flex 布局才能纯样式解决，在放弃 IE9 之前是不可能了。。 http://caniuse.com/#search=flex

**Comment by afc163** [comment]
Fixed in antd@3.0.0
