### ISSUE TITLE
form组件会过滤value为undefined的字段

### ISSUE THREAD

**Issue by iamhanson** [ant-design/ant-design#6011]
### Version
2.9.3

### Environment
mac chrome react

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
1、表单里的下拉框A，设置allowClear={true},
2、点击清楚按钮，情况已选择的选项，此时，A的值是undefined
3、提交表单，后台接受不到A的值，在编辑信息场景中，需要将原来A的值清空，但是这个时候接口没有收到A，所以更新的时候没有更新该字段，导致无法清空

### What is expected?
如重现步骤，希望在清空的时候，A字段也能传到后台

### What is actually happening?
A字段无法传到后台

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by xueqingxiao** [comment]
@iamhanson  你最好理解下undefined是什么。

**Comment by iamhanson** [comment]
@xueqingxiao 我知道undefined是什么，如果你不知道怎么更好的解决问题，可以旁观，但不要装逼。

**Comment by iamhanson** [comment]
@xueqingxiao 我知道undefined是什么，如果你不知道怎么更好的解决问题，可以旁观，但不要装逼。

**Comment by afc163** [comment]
楼主解决这个问题了么？

**Comment by iamhanson** [comment]
@afc163 解决方法有很多种。比如设置getValueFromEvent，或者在提交的时候进行处理。
select的清空会吧值改为undefined，无法传到后台。我开始提这个问题的想法是是否可以在form组件里去处理这种字段，比如加一个配置sendUndefined(boolean)。
这个问题在编辑场景下比较明显，比如我要把原来有值的字段清空，这个时候如果直接点击清空，这个值会变成undefined，后台没有接收到，就不会更新这个字段

**Comment by benjycui** [comment]
其实之前提过，要不要明显区分 `undefined` 和 `null`。

`undefined`: 即使开发者是故意定义，也认为没有定义，忽略。

`null`: 开发者故意设为空。

这样在 Select clear 时就应该把值设为 `null`，也方便 Form 统一处理。
