### ISSUE TITLE
can we add a new feature which helps us customize the inner HTML of <Pagination/>?

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#6013]
### What problem does this feature solve?
Recently I added react-router in my project. In one page there is a table with multi-page data. I want to change the url When jumping to a new page, and also the back or forward buttons in browser works well. Now I have to   change the url by history API once page changes. It's troublesome because of too much code needing to be written every time. However, it can be done perfectly just by < Link /> of react-router, so it's better to customize inner HTML of every button in pagination.

### What does the proposed API look like?

```jsx
<Pagination innerItem={<span className="link">三</span>}>
<Pagination innerItem={(i, pagination) => <Link to=`/list/${i}` />}>
```

**Comment by afc163** [comment]
ref #61

**Comment by leadream** [comment]
@afc163 不是要自定义样式。我想要自定义 <Pagination /> 组件中的 <a> 标签，因为我想让翻页的动作和路由同步，比如目前处于第1页（aaa.com/list），当点击 <Pagination /> 中的第2页按钮时，地址栏就变成 `aaa.com/list/2` ，此时再点击浏览器的向前箭头，就会回到第1页，地址栏变成 `aaa.com/list` 。

**Comment by afc163** [comment]
写错链接。

**Comment by bang88** [comment]
@leadream 使用 `Pagination` 的  `onChange`  方法可以做。

分页切换的时候更新路由，当前页从路由参数里面获取， 不要设置状态。

**Comment by bang88** [comment]
这个不需要修改组件~

**Comment by leadream** [comment]
@bang88 我目前是这么做的，就是感觉如果可以用<Link/>标签会方便一点。你说的不设置状态是指不把页数存在state中，直接onChange时切换路由，路由切换时改变current属性是吗？

**Comment by bang88** [comment]
en .

**Comment by bang88** [comment]
用<Link/>也差不多吧

**Comment by benjycui** [comment]
其实我个人也倾向于把页码 render 为 Link/a，这样应用的状态是可以减少。

**Comment by benjycui** [comment]
@leadream 你综合 rc-pagination 那个 issue，设计下 API 贴到这里，再 PR 吧。

**Comment by bang88** [comment]
不是所有用户都用react-router 吧，用a标签怎么做？

**Comment by benjycui** [comment]
@bang88 类似于 Breadcrumb 的 itemRender，自行决定返回 Link 还是 a，或者默认的 li

**Comment by henryzp** [comment]
@afc163 @benjycui 

我遇到类似的问题，像语言汉包：

```
export default {
  // Options.jsx
  items_per_page: '条/页',
  jump_to: '跳至',
  page: '页',

  // Pagination.jsx
  prev_page: '上一页',
  next_page: '下一页',
  prev_5: '向前 5 页',
  next_5: '向后 5 页',
  prev_3: '向前 3 页',
  next_3: '向后 3 页',
};
```

在我的设计稿里面，jump_to需要翻译成“到第”，是为了和之前的保持统一，而我不知道现在的这个组件将怎样做扩展。

另外，就是input输入框，后面有一个“确定”按钮，当输入数字，也可以点击确定来做跳转。

不知道如何扩展，求方案？

**Comment by wufeng87** [comment]
@benjycui Something like these? Only working for the number button.
```javascript
function defaultItemRender(page) {
  return <a>{page}</a>;
}

const Pager = (props) => {
  const {
    itemRender = defaultItemRender,
  } = this.props;
  const prefixCls = `${props.rootPrefixCls}-item`;
  let cls = `${prefixCls} ${prefixCls}-${props.page}`;

  if (props.active) {
    cls = `${cls} ${prefixCls}-active`;
  }

  if (props.className) {
    cls = `${cls} ${props.className}`;
  }

  return (
    <li
      title={props.showTitle ? props.page : null}
      className={cls}
      onClick={props.onClick}
      onKeyPress={props.onKeyPress}
      tabIndex="0"
    >
      {itemRender(props.page)}
    </li>
  );
};
```

**Comment by benjycui** [comment]
@wufeng87 yep, PR is welcomed. And you should support Prev and Next button.

**Comment by wufeng87** [comment]
@benjycui and the `page` argument should `undefined` if it is Prev or Next button?

By the way, the `<a />` in Prev or Next button are css related:
```css
.rc-pagination-prev a:after, .rc-pagination-next a:after {
    margin-top: -1px;
}

.rc-pagination-prev a:after {
    content: "\2039";
    display: block;
}
```

**Comment by benjycui** [comment]
Nope.. 

If current page is 2, page of prev should be 1, and page of next should be 3

**Comment by wufeng87** [comment]
How to tell user it is Prev or Next button , or it would be like this: 

![image](https://user-images.githubusercontent.com/1686808/27629944-895a491c-5c26-11e7-9d35-398735141de9.png)

**Comment by benjycui** [comment]
How about:

```jsx
function itemRender(page: number, type: 'page' | 'prev' | 'next'): React.ReactNode
```

**Comment by afc163** [comment]
supported in antd@2.12.0
