### ISSUE TITLE
Decimals in InputValue (step property)

### ISSUE THREAD

**Issue by aaronplanell** [ant-design/ant-design#6015]
Hello,

I am using the [InputValue Component](https://ant.design/components/input-number/) and using its property _step_. The documentation says:

> Decimals: A numeric-only input box whose values can be increased or decreased using a decimal step. The number of decimals (also known as precision) is determined by the step prop.

In the example of the web we found: 
```
ReactDOM.render(
  <InputNumber min={0} max={10} step={0.1} onChange={onChange} />
, mountNode);
```

But, you can inform 9.21 for instance. In my humble opinion, this wouldn't be allowed and the value must change to 9.2. What do you think about that?

Best regards,
Aaron Planell

**Comment by benjycui** [comment]
`step` is just for inc/dec, it will not normalize your input. So, just check it by yourself.

**Comment by aaronplanell** [comment]
Hey @benjycui ! What's up? 

OK, it's not a problem. I made it in my project, but I think that the documentation is a little bit confusing when says:

> The number of decimals (also known as precision) is determined by the step prop.

What do you think about that?

Best regards!

**Comment by benjycui** [comment]
Sorry, we are not native speakers. So the documentation maybe a little confusing...

**Comment by benjycui** [comment]
cc @afc163

**Comment by aaronplanell** [comment]
Don't worry, me neither, hehehe. But I think this part is confusing in the documentation because, as you said, `step` only works for `inc/dec`, but actually it didn't define the precision of the number.
