### ISSUE TITLE
ToolTip内容过长显示异常

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#6016]
### Version
2.9.1

### Environment
win7 chrome

### Reproduction link
[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce
tooltip内容超级长都会出现这个问题

### What is expected?
可以换行？

### What is actually happening?
内容超出tooltip的宽度。

**Comment by afc163** [comment]
```
<Tooltip title={<div className="xxx">xxx</div>}></Tooltip>
```

Set styles by youself.
