### ISSUE TITLE
Collapse supports ARIA

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6017]
`antd` 的无障碍访问在推进中，但由于现在人手不够，所以 maintainers 暂时不会投入开发，欢迎 PR。

---

Online demo: https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

![image](https://cloud.githubusercontent.com/assets/3580607/25698827/212e300a-30f3-11e7-9f57-878a6a6f5613.png)

**Comment by yesmeck** [comment]
@ant-design-bot tanslate

**Comment by yesmeck** [comment]
@ant-design-bot translate

**Comment by afc163** [comment]
closed by https://github.com/react-component/collapse/pull/84
