### ISSUE TITLE
表格 树形数据子节点不能默认展开（Table tree children）

### ISSUE THREAD

**Issue by skiffyin** [ant-design/ant-design#6021]
### Version
2.9.3

### Environment
chrome 57.0.2987.110

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
表格 树形数据子节点不能默认展开

### What is expected?
 树形数据子节点能默认展开

### What is actually happening?
 树形数据子节点手动展开

**Comment by yesmeck** [comment]
`defaultExpandedRowKeys` 对异步数据无效，用 `expandedRowKeys` 控制。
