### ISSUE TITLE
Table支持自定义表头么？

### ISSUE THREAD

**Issue by acivang** [ant-design/ant-design#6027]
### What problem does this feature solve?
请问Table是否支持自定义表头，比如增加<a>标签并绑定click，用以实现对此列整列的操作，比如：填充。请问如何做？可否提供文档、指导？非常感谢！

### What does the proposed API look like?
更具灵活性，文档更全面。

**Comment by benjycui** [comment]
`columns[n].title = <span onClick={...}>Title</span>`
