### ISSUE TITLE
Tabs behaves weirdly when using a Component as the TabPane

### ISSUE THREAD

**Issue by goreRatzete** [ant-design/ant-design#6028]
### Version
2.9.3

### Environment
Windows 10, Chrome Version 58.0.3029.96 (64-bit)

### Reproduction link
[http://codepen.io/anon/pen/ybzXpJ?editors=0011](http://codepen.io/anon/pen/ybzXpJ?editors=0011)

### Steps to reproduce
Create Tabs, put in a custom Component that basically returns a TabPane. It should not work as expected. 

### What is expected?
The Tabs should render as when you use TabPane in place, display title and content correctly.

### What is actually happening?
The TabPane title is not showing, the content is also empty.

**Comment by benjycui** [comment]
Yep, Tabs's children must be TabPane, you can search issues for more information.
