### ISSUE TITLE
feat: timePicker / datePicker / rangePicker 添加时分秒置零的开关

### ISSUE THREAD

**Issue by Okiilemon** [ant-design/ant-design#6031]
### What problem does this feature solve?
用户无需手动滚到 00:00:00。
详述：
假设这个开关的参数为 zeroSetting , 当为 false 的时候时分秒默认处于当前时间；当为 true 的时候时分秒默认为 00:00:00。现在我没有办法实现这样的功能，最多是设置 defaultValue = { moment('00:00:00','HH:mm:ss') }。
这样在 timePicker 下还好，但是我是要在 rangePicker 里面用，这样会导致前面的年月日也默认今天，可我并不想赋默认值啊。很多需求都是设置整点的，我希望用户选择时间的时候不需要手动滚到零。

### What does the proposed API look like?
zeroSetting |  boolean  | false

**Comment by benjycui** [comment]
Try `TimePicker[defaultOpenValue]`

另外两个: https://github.com/ant-design/ant-design/issues/5691 https://github.com/ant-design/ant-design/issues/2375

**Comment by Okiilemon** [comment]
`                  <DatePicker
                    allowClear
                    showTime={{
                      defaultValue: moment('00:00:00','HH:mm:ss')
                    }}/>`
没有效果

**Comment by Okiilemon** [comment]
`                  <DatePicker
                    allowClear
                    showTime={{
                      defaultValue: moment('00:00:00','HH:mm:ss')
                    }}`
这样写没有效果，另外没有找到你说的 defaultOpenValue 。

**Comment by Okiilemon** [comment]
在 rc-time-picker 的文档上找到了 defaultOpenValue ，在 timePicker 中使用是没有问题的，但是
`<DatePicker allowClear showTime={{ defaultOpenValue: moment('00:00:00','HH:mm:ss') }}`这样就无效。

**Comment by meowtec** [comment]
showTime 里面设置的 defaultOpenValue，传到 rc-calendar 之后会被覆盖掉

https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L212

**Comment by benjycui** [comment]
> Try TimePicker[defaultOpenValue]
> 
> 另外两个: #5691 #2375

意思是 TimePicker 可以设置，但是 DatePicker 和 RangePicker 里面的还要跟进。
