### ISSUE TITLE
DatePicker cannot open when set property disableDate

### ISSUE THREAD

**Issue by zhuyali** [ant-design/ant-design#6032]
### Version
2.9.1

### Environment
Chrome MacOS React@15.4.2

### Reproduction link
[https://github.com/open-catlog/monitor-view/blob/master/src/pages/default/index.js#L212](https://github.com/open-catlog/monitor-view/blob/master/src/pages/default/index.js#L212)

### Steps to reproduce
- click DatePicker clear button
- click DatePicker

### What is expected?
pop DatePicker

### What is actually happening?
nothing happens

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
An online-demo will be better.

**Comment by xudafeng** [comment]
`// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { LocaleProvider, DatePicker, locales, version } = antd;
moment.locale('en');

const disabledDate = function (current) {
  return current.valueOf() > Date.now() || current.valueOf() < new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
};

ReactDOM.render(
  <div>
    <p className="version">antd version: {version}</p>
    <LocaleProvider locale={locales.en_US}>
      <DatePicker defaultValue={moment()} disabledDate={this.disabledDate} />   
    </LocaleProvider>
  </div>
, mountNode);`

**Comment by zhuyali** [comment]
`// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { LocaleProvider, DatePicker, locales, version } = antd;
moment.locale('en');

const disabledDate = function (current) {
  return current.valueOf() > Date.now() || current.valueOf() < new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
};

ReactDOM.render(
  <div>
    <p className="version">antd version: {version}</p>
    <LocaleProvider locale={locales.en_US}>
      <DatePicker defaultValue={moment()} disabledDate={this.disabledDate} />   
    </LocaleProvider>
  </div>
, mountNode);`

**Comment by zhuyali** [comment]
Run above code in  http://codepen.io/benjycui/pen/KgPZrE?editors=001，then clear the field, you wil find the problem.

**Comment by benjycui** [comment]
It works fine..

<img src="http://g.recordit.co/tsA8DlBmZv.gif" />

**Comment by benjycui** [comment]
Rewrite your `disabledDate`:

```jsx
const disabledDate = function (current) {
  return false;
};
```

Then, it will works fine. So, it is not a bug of antd, it's your own issue.

**Comment by xbrave** [comment]
I have met this problem too. when I add ***current*** in the begin of return, It works fine
```
return current && (current.valueOf() > Date.now() || current.valueOf() < new Date(Date.now() - 7 * 24 * 60 * 60 * 1000));
```
