### ISSUE TITLE
Range-picker chould not set default selected value while rc-calander can

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#6033]
### Version
2.9.3

### Environment
codepen环境

### Reproduction link
[http://codepen.io/yuecjnadt/pen/jmGYym?editors=0010](http://codepen.io/yuecjnadt/pen/jmGYym?editors=0010)

### Steps to reproduce
open http://codepen.io/yuecjnadt/pen/jmGYym?editors=0010
click calander input

### What is expected?
left panel show Fer
right panel show Mar

### What is actually happening?
left panel show May
right panel show May

**Comment by benjycui** [comment]
@wangtao0101 we should pass value to [RangeCalendar](https://github.com/ant-design/ant-design/blob/83a322f2d3280625dbba6162b1e46ee0d9a1d033/components/date-picker/RangePicker.tsx#L170-L187).

Could you try to PR to fix it?

**Comment by wangtao0101** [comment]
@benjycui I will try

**Comment by benjycui** [comment]
It seems that https://github.com/ant-design/ant-design/commit/43bf6c48464f93795ce4cdfe6dd41a1604106349 and its relative commit fix this.
