### ISSUE TITLE
Notification 并不不支持getContainer属性配置

### ISSUE THREAD

**Issue by hardfist** [ant-design/ant-design#6036]
### Version
2.10.0

### Environment
chrome58

### Reproduction link
[http://codepen.io/hardfist/pen/JNrpXo?editors=1111](http://codepen.io/hardfist/pen/JNrpXo?editors=1111)

### Steps to reproduce
点击按钮，出现notification

### What is expected?
notification应该渲染在指定的container1节点中

### What is actually happening?
notification渲染在body里

---
读了notifcation的源码，其使用了rc-notification,而getContainer是其Notification.newInstance的配置项，每一个insgtance可以指定其渲染container，其中所有的notice都是渲染在该container里，而antd的notification只有一个全局的instance，且其初始化instance时并未使用getContainer配置项，这导致getContainer配置无效。所以当前实现只能支持全局的config里的getContainer配置，并不支持每个notice的getContainer配置。所以API应该有误。

**Comment by NE-SmallTown** [comment]
据我了解，所有全局的组件，无论是Message，Notification，Modal或者任何基于window定位的，放在body下是最保险的，就像你在自己组件里用Modal一样，依旧是渲染在body下面，提供<Modal/>的用法只是为了与react结合，看起来更舒服。老的像easy-ui,jquery-ui这样的ui库没有试过，不过在bootstrap里也是都放在body下的，至于为什么，确实研究这个是很早以前了，当初自己造轮子的时候还试过不放在body里，最近貌似还读过一篇专门将这个的文章，原谅我实在是记不起来了到底有哪些坑了。。。

所以我觉得getContainer是一种为了未来而设计的api（可能这些坑随着发展不管是用css还是js慢慢都能解决了），即使你改了api让它render到指定节点，我觉得肯定会慢慢发现很多坑，没有必要 :smile:

**Comment by benjycui** [comment]
@hardfist 看了源码，全局 config 的 `getContainer` 也是无效的。

你来个 PR 修一下吧，把 `getContainer` 挪到全局 config，事实上单独的 `notification.xxx` 里面的 `getContainer` 会有坑，因为弹出的多个 notification 如果是挂到不同的节点，难以保证他们不会重叠。

**Comment by benjycui** [comment]
cc @afc163
