### ISSUE TITLE
ValidateFieldsAndScroll is invalid when it  included in Layout Component

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#6037]
### Version
2.10.0

### Environment
windows chrome

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
just like this

```javascript
<Layout>
    <Form>
    ......
    </Form>
</Layout>
```

When i use validateFieldsAndScroll api，The page does not scroll to the wrong FormItem;
If I removed the Layout Component,it working properly

### What is expected?
when a From Component  included in Layout Component ,
the api validateFieldsAndScroll  able to work properly

### What is actually happening?
When I use validateFieldsAndScroll api，The page does not scroll to the wrong FormItem;

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by buxuku** [comment]
OK,It is invalid just like this:

http://codepen.io/anon/pen/aWVgmN?editors=1111

however，I just rename the Layout componet from `Layout` to `div` ,It working properly just like this:

http://codepen.io/anon/pen/XRzLRX?editors=1111

**Comment by buxuku** [comment]
Similarly, this bug will also appear in this case:

if the Form component's container has ths style of overflow and the value is `auto`;

like this 
https://codepen.io/anon/pen/MmBeWp?editors=1111

if change the value to `hidden`,It working properly

@ddcat1115 @benjycui

**Comment by benjycui** [comment]
@buxuku it seems that rc-form works fine with an `overflow: auto` container http://react-component.github.io/form/examples/modal.html

**Comment by akecn** [comment]
this another demo for this issue: https://codepen.io/wuake/pen/mMLXEp

if remove `<Sider>test</Sider>`, it works fine.

**Comment by afc163** [comment]
It is weired, `overflow-x` will affect `overflowY`'s value.

https://codepen.io/anon/pen/rzvdwG?editors=1010
