### ISSUE TITLE
一个Form.Item里有两个组件，这两个组件只决定一个表单项的值需要怎么做

### ISSUE THREAD

**Issue by internet5** [ant-design/ant-design#6047]
### What problem does this feature solve?
如题，我看到可以setFieldsValue可以设置，但是提示需要绑定，绑定里面是两个组件啊，没法绑定，该怎么做呢？求问

### What does the proposed API look like?
能灵活的控制Form.Item里的内容跟Field的关系

**Comment by xueqingxiao** [comment]
建议先使用两个值，然后发请求前拼成一个值。

**Comment by ybning** [comment]
建议自定义表单组件：
[https://ant.design/components/form-cn/#components-form-demo-customized-form-controls](url)
@internet5
