### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by babizhu** [ant-design/ant-design#605]
http://ant.design/components/badge/，此页用ie11来模拟ie9报错，
在自己的html中加上media.match.min.js之后，报错消失，但是数字显示有问题

**Comment by afc163** [comment]
感谢反馈，这里补充了 media.match 的 polyfil 。http://ant.design/docs/getting-started#%E5%85%BC%E5%AE%B9%E6%80%A7 

另外修复了 badge 在 IE8/9 下始终是 0 的问题。
