### ISSUE TITLE
Cascader 在options中匹配不到数据时，显示为空

### ISSUE THREAD

**Issue by icbcsdc2008** [ant-design/ant-design#6050]
### Version
2.10.0

### Environment
chrome

### Reproduction link
[http://codepen.io/anon/pen/zwPyOz?editors=001](http://codepen.io/anon/pen/zwPyOz?editors=001)

### Steps to reproduce
中国的省市区，尤其是区经常变动，像高新区、区域合并、区域撤销等。现在Cascader  在指定初始值时，如果初始值在数据列表里面不存在，则显示为空？ 

### What is expected?
不论初始值是否在列表项中，默认显示初始值，当用户点击修改时，重新按列表值选择赋值显示

### What is actually happening?
现如果初始值，不在列表项中，显示为空

**Comment by ybning** [comment]
@icbcsdc2008 
请贴代码
[http://codepen.io/anon/pen/zwPyOz?editors=001](http://codepen.io/anon/pen/zwPyOz?editors=001)

**Comment by icbcsdc2008** [comment]
有代码的，感觉应该显示“浙江省 杭州市 高新区”  现在只显示“浙江省 杭州市”

**Comment by ybning** [comment]
@icbcsdc2008 
defaultValue={['浙江省', '杭州市', '高新区']}
而浙江的children下没有高新区。

**Comment by icbcsdc2008** [comment]
是的，因为现在全国省市区的数据，尤其是区的信息经常变动，即使淘宝上面的地址库也不是最新的，所以如果默认值是新的省市区或者跟options数据不完全匹配的话，用这个组件，会显示不全或者直接显示为空。不过我已经用另外一个变通的方法实现了。  <Cascader><Input value="浙江省 杭州市 高新区"/></Cascader>

**Comment by qq645381995** [comment]
京东 选地址 都不让选区 直接让你写 省了老维护地区了

**Comment by afc163** [comment]
这种需求作为基础组件库不好做的，组件应该精确，做太多猜测和容错性不一定是好的决定。就按你现在的方式自行封装吧。
