### ISSUE TITLE
Button组件的shape属性设置成circle后，圆形不能完全包住文字

### ISSUE THREAD

**Issue by blackmatch** [ant-design/ant-design#6051]
### Version
2.10.0

### Environment
MacOS10.12.4 、chrome58.0.3029.96 (64-bit)、react latest

### Reproduction link
[http://codepen.io/blackmatch/pen/XRzoaV](http://codepen.io/blackmatch/pen/XRzoaV)

### Steps to reproduce
将Button的shape设置成circle，内容超过三个字圆形就无法包住内容。

### What is expected?
原型按钮能够完整包住文字

### What is actually happening?
圆形按钮不能完整包住文字

**Comment by yesmeck** [comment]
圆形按钮的使用场景一般就是图标，不建议用文字。
