### ISSUE TITLE
请升级 rc-input-number 到最新版本

### ISSUE THREAD

**Issue by KennyLisc** [ant-design/ant-design#6052]
toNumberWhenUserInput 应该处理正在输入 3.2003 -> 3.200 的情况!

**Comment by KennyLisc** [comment]
http://codepen.io/kenny_lisc/pen/qmNbMv

Line 1. no formatter && parser && form: type in 9993.2003 is ok.
Line 2. has formatter && parser && form: can't type in 9993.2003 is fail.
Line 3. has formatter && parser && no form: type in 9993.2003 is ok.

**Comment by yesmeck** [comment]
Reinstall node_modules will install latest version of rc-input-number.
