### ISSUE TITLE
Request add onMouseDown event to Button props

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#6054]
### What problem does this feature solve?
An onMouseDown event handler is required for Button component in our use case.  Before updating typescript to 2.3.2, we can pass undeclared prop to button, but it doesn't work in new release of typescript.

### What does the proposed API look like?
export interface ButtonProps {
  ...
  onMouseUp?: React.FormEventHandler<any>;
  onMouseDown?: React.FormEventHandler<any>;
  ...
}

**Comment by benjycui** [comment]
Just extends `HTMLButtonElement` [here](https://github.com/ant-design/ant-design/blob/83a322f2d3280625dbba6162b1e46ee0d9a1d033/components/button/button.tsx#L39)

**Comment by lulut** [comment]
Below code eligible to  [Type Compatibility ](https://www.typescriptlang.org/docs/handbook/type-compatibility.html).  Just wondering is it a good solution for this kind of requirement.

const {onMouseDown, ...others} = this.props;
        let obj = {...others};
        if (onMouseDown) {
            obj["onMouseDown"] = onMouseDown;
        }

**Comment by benjycui** [comment]
@lulut I don't understand, could provide more information？

**Comment by benjycui** [comment]
And I think it's enough if `Button` extends `HTMLButtonElement`

**Comment by yqwoe** [comment]
@benjycui

**Comment by benjycui** [comment]
@yqwoe ？？

**Comment by benjycui** [comment]
It seems that we can not extend from `HTMLButtonElement` now, or `HTMLInputElement` and also`HTMLTextareaElement` cc @afc163 

```typescript
interface HTMLButtonElement extends HTMLElement {
    // autofocus and disabled and all the properties are required!
    autofocus: boolean;
    disabled: boolean;
    ...
}
```

I don't understand, why? I thinks these properties should be optional.

@bang88 @infeng @yesmeck

**Comment by benjycui** [comment]
OK, I think I make a mistake, we can work around with this issue...

**Comment by bang88** [comment]
```ts
React.HTMLProps<HTMLButtonElement>
```

**Comment by bang88** [comment]
should extend from `React.HTMLProps` instead of `HTMLXxxElement` ,here `HTMLXxxElement` is T

**Comment by benjycui** [comment]
I found it is difficult to extend from `React.HTMLProps<HTMLButtonElement>`, for `Button[size]` has conflict with `button[size]`. Actually, all the size properties in antd have conflict with `React.HTMLProps<HTMLElement>`'s size properties.

So this PR https://github.com/ant-design/ant-design/pull/5990 should be reverted.
