### ISSUE TITLE
Select选中项or initialvalue无法清除

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#6056]
### Version
2.10.0

### Environment
win7 chrome

### Reproduction link
[http://codepen.io/anon/pen/bWYOap?editors=0011](http://codepen.io/anon/pen/bWYOap?editors=0011)

### Steps to reproduce
先第一个选择框选择 北京-京东  第二个选择框 选择B 
然后选择第一个选择框选择 上海-京东  此时，应该initvalue为空，但是显示了上次选择的B的id 2345

### What is expected?
希望，第二次选择时，第二个选择框应该不选中任何内容。

### What is actually happening?
显示了上次选择的B的id 2345
如果仅仅从initialvalue只初始化一次这个角度来看的话也不对，initial默认初始化为undefined 则第二次应该也为空才对，
我觉得这里肯定不是initialvalue只初始化一次的问题。

---
或者能否指导一下，怎么实现这种联动的效果。

**Comment by forever4313** [comment]
@yesmeck

**Comment by ybning** [comment]
@forever4313 
给Cascader组件绑定onChang事件
然后在调用表单的setFieldsValue方法

**Comment by forever4313** [comment]
@ybning  但是onchange的同时不是会造成 view重绘？导致，setfieldsvalue方法会报错，好像是 跟getFieldDecorator 的先后问题。

**Comment by benjycui** [comment]
这个是你代码控制的，你对 API 的理解错了。

**Comment by forever4313** [comment]
就这么给关了？我怎么理解错了？？？
@benjycui

**Comment by afc163** [comment]
如果使用了 getFieldDecorator 来绑定表单组件，就不需要用 onChange 再去 setState 了，本身就已经是双向绑定了。

**Comment by forever4313** [comment]
http://codepen.io/anon/pen/bWYOap?editors=0011
@afc163  我把onchange去掉了，发现第二个里的内容没有变。求问这是代码问题，还是select的bug

**Comment by afc163** [comment]
你最好 fork 一个新的 codepen，不要修改你原来的代码。我再看看你第一个例子。

**Comment by forever4313** [comment]
http://codepen.io/anon/pen/XRZMdN?editors=0011


@afc163  这个是原问题的代码。没有使用onchange

**Comment by afc163** [comment]
你把有 onChange 的搞回来。

**Comment by forever4313** [comment]
@afc163 
http://codepen.io/anon/pen/WjMpGV?editors=0011   有onchange方法
http://codepen.io/anon/pen/bWYOap?editors=0011   无onchange方法

**Comment by afc163** [comment]
>  http://codepen.io/anon/pen/WjMpGV?editors=0011 有onchange方法

我试了一下这个，应该是满足楼顶的期望行为的。

**Comment by forever4313** [comment]
@afc163 第一种方法为什么不行，我的理解是，会重新render一次这个select控件，应该会重新initial的吧？还是我理解错了？劳烦给解解惑

**Comment by afc163** [comment]
initialValue 和 defaultValue 一样，只会在第一次 render 的时候生效，后面的 re-render 都不再生效。

**Comment by forever4313** [comment]
ok  谢谢。

**Comment by hbrls** [comment]
@forever4313 这个问题的解决方案是什么？
