### ISSUE TITLE
AutoComplete in Input.Group css bug

### ISSUE THREAD

**Issue by queimadus** [ant-design/ant-design#6058]
### Version
2.10.0

### Environment
osx 10.11.6, Chrome 57.0.2987.133

### Reproduction link
[http://codepen.io/anon/pen/NjXrOV?editors=001](http://codepen.io/anon/pen/NjXrOV?editors=001)

### Steps to reproduce
Create an `Input.Group` with a nested `Select` and a `AutoComplete`.
Also occurs in the example page https://ant.design/components/input/#components-input-demo-group

### What is expected?
The Select and AutoComplete to have the same height

### What is actually happening?
The `AutoComplete` height is inferior to the `Select`'s

![screen shot 2017-05-08 at 17 59 30](https://cloud.githubusercontent.com/assets/1107697/25815391/1dac34d6-3418-11e7-8ae4-1541297375af.png)

**Comment by TangMonk** [comment]
Actually, In official documentation is problem too, https://ant.design/components/input/
![image](https://cloud.githubusercontent.com/assets/3498786/25831382/3158df92-3496-11e7-8f5b-c91caef56c74.png)
