### ISSUE TITLE
Datepicker 今天被disabled以后，『今天』 按钮状态表达不明确。 

### ISSUE THREAD

**Issue by yueyao** [ant-design/ant-design#606]
`disabledDate `里面设定今天也被disabled,  `Datepicker` 面板中，『今天』 按钮表达不够明确。

希望可以加个配置项，来配置是否显示底部面板。

thks

**Comment by afc163** [comment]
这块样式缺失，不可选择时，今天应该置灰。

![](https://os.alipayobjects.com/rmsportal/ZkyoZSSbBWstTmY.png)

**Comment by qiaolb** [comment]
disable还不如不显示，我在实际使用中通过修改样式将Today栏隐藏，并通过修改样式取消今天的不同样式。有时候，我们需要一个Datepicker，但不需要有今天。

**Comment by liekkas** [comment]
支持“今天”这个底部状态栏可选， +1
