### ISSUE TITLE
RangePicker在360浏览器极速模式下placeholder显示错位

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/ant-design#6061]
### Version
2.10.0

### Environment
360浏览器极速模式8.1.1版本

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
No

### What is expected?
正常显示

### What is actually happening?
placeholder显示错位

**Comment by afc163** [comment]
broken by #5718
