### ISSUE TITLE
SubMenu title always keep highlight when hover disabled Menu.SubMenu,

### ISSUE THREAD

**Issue by pinggod** [ant-design/ant-design#6062]
### Version
2.10.0

### Environment
macOS, Chrome 58

### Reproduction link
[http://codepen.io/pinggod/pen/rmppJG?editors=0110](http://codepen.io/pinggod/pen/rmppJG?editors=0110)

### Steps to reproduce
http://codepen.io/pinggod/pen/rmppJG?editors=0110

Hover disabled Menu.SubMenu.

### What is expected?
Disabled Menu.SubMenu

### What is actually happening?
Highlight Menu.SubMenu

**Comment by benjycui** [comment]
Just fix it @pinggod , you are one of maintainers.
