### ISSUE TITLE
Select  combobox 模式显示不正确 

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design#6065]
### Version
2.9.3

### Environment
win10, chrome

### Reproduction link
[http://codepen.io/anon/pen/JNMLmW?editors=001](http://codepen.io/anon/pen/JNMLmW?editors=001)

### Steps to reproduce
移步到   http://codepen.io/anon/pen/JNMLmW?editors=001 即可看到

### What is expected?
选择选项之后，看到的是 option 的 lable 或者 title 的 内容，而不是 value 的值

### What is actually happening?
显示 option 的  value

**Comment by yesmeck** [comment]
`combobox` 的设计就认为 label 和 value 是一样的，你需要的可能只是搜索。

**Comment by qq645381995** [comment]
用 search

**Comment by zjxpcyc** [comment]
@yesmeck 我需要的不是搜索，是可编辑。就是当列表存在的时候，选择列表中内容，如果不存在，我就新增。
另外，即使是 label 和 value 是一样的，也应该是显示 label 啊
我真的是理解有问题？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5772

**Comment by zjxpcyc** [comment]
@afc163 谢谢，看来真是概念上的冲突了。
只能自己去封装一个可编辑的 select 了

**Comment by afc163** [comment]
Try `mode="tags"`?

**Comment by zjxpcyc** [comment]
@afc163 谢谢，这个可以

**Comment by chendonghai** [comment]
mode="tags" 是多选功能啊，我又不想要多选功能，真奇怪为什么这个设计要这样啊

**Comment by icuke** [comment]
value={1}  换成 key={1} 就行了
