### ISSUE TITLE
AutoComplete didn't filter  automatically

### ISSUE THREAD

**Issue by czjxy881** [ant-design/ant-design#6067]
### Version
2.10.0

### Environment
macOS 10.12.4 chrome

### Reproduction link
[http://codepen.io/anon/pen/dWJerr](http://codepen.io/anon/pen/dWJerr)

### Steps to reproduce
type any letter,but no filter

### What is expected?
auto filter by the letter typed in

### What is actually happening?
no filter

**Comment by yesmeck** [comment]
You need pass `filterOption` to AutoComplete.

**Comment by afc163** [comment]
It is a intended behavious: https://github.com/ant-design/ant-design/issues/5860
