### ISSUE TITLE
Tabs 在 2.9.2 以后 type!="line"，TabPanel的切换动画会失效

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#6070]
### Version
2.10.0

### Environment
react@15.5.4

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
type="card" 或者 type="editable-card" TabPanel的切换动画会失效

### What is expected?
恢复切换过度动画

### What is actually happening?
简单的切换，没有过度动画

---
从2.9.2版本以后出现该问题，2.9.1正常

**Comment by afc163** [comment]
设计上就不应该有切换动画的。

**Comment by 303394539** [comment]
是点击tab的时候，TabPanel之间的过度动画，原来有淡入淡出，现在没了，有的话是会体验好一些平滑得多。而且也应该有参数控制开关和编写自定义动画

**Comment by 303394539** [comment]
@afc163 这个问题要解决不？之前有动画，现在没有了，是属于升级bug？还是说你们改设计了？以后是不是都没动画了？

**Comment by afc163** [comment]
原来就不应该有动画。

**Comment by 303394539** [comment]
@afc163 想在新版本的type="card" 或者 type="editable-card"实现动画，有没有解决方案？现在type="line"有动画的

**Comment by afc163** [comment]
现在是写死的，我看看能不能允许用户覆盖。

**Comment by afc163** [comment]
这样可以用 `<Tabs type="card" animated />` 来覆盖默认值。

**Comment by 303394539** [comment]
@afc163 不得行，这个属性是打开动画，但是现在的情况是动画都没生效

**Comment by afc163** [comment]
先试试最新版本如何？

**Comment by 303394539** [comment]
@afc163  我试了2.10.1这样做生效了
