### ISSUE TITLE
Select a father node in TreeSelect's search result won't select it's children nodes

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6071]
### Version
2.10.0

### Environment
OSX, Chrome 57

### Reproduction link
[http://codepen.io/superlxc/pen/oWpMVG](http://codepen.io/superlxc/pen/oWpMVG)

### Steps to reproduce
![treeselect](https://cloud.githubusercontent.com/assets/4329120/25844034/d260fa06-34db-11e7-9fc7-ed06f1cf8618.gif)
Search 'computer', then select the father node 'computerAAA'

### What is expected?
All the children node of 'computerAAA' in result should be selected

### What is actually happening?
the children node of 'computerAAA' in result did not be selected

**Comment by yarnball** [comment]
Pretty sure that's a `prop` you can select

```
      multiple: true,
      treeCheckable: true,
```

**Comment by yesmeck** [comment]
Children nodes do have be selected, because you are using `SHOW_PARENT` strategy, so only parent node shows.

**Comment by yesmeck** [comment]
@warmhug Do you remember why set `checkStrictly` to `true` here https://github.com/react-component/tree-select/blob/master/src/SelectTrigger.jsx#L182-L185 ?

**Comment by warmhug** [comment]
ref https://github.com/ant-design/ant-design/issues/3724#issuecomment-259071769  / https://github.com/react-component/tree-select/issues/31#issuecomment-234715081

**Comment by zombieJ** [comment]
Since `v2.13.10` and above version is fixed this. Close the issue.
