### ISSUE TITLE
打开modal对话框，背景全部是灰色

### ISSUE THREAD

**Issue by Zuckjet** [ant-design/ant-design#6072]
### Version
2.8.2

### Environment
win7  chrome最新版

### Reproduction link
[https://github.com/Zuckjet/antdebugCode/blob/master/modal.js](https://github.com/Zuckjet/antdebugCode/blob/master/modal.js)

### Steps to reproduce
点击modal对话框

### What is expected?
弹出对话框，同时可以看到背景内容

### What is actually happening?
弹出对话框，无法看到背景内容（对话框后面全部是灰色）

**Comment by Zuckjet** [comment]
![t 28v c ghh rt_ntrnh n](https://cloud.githubusercontent.com/assets/17976139/25846580/e574abac-34e4-11e7-91c2-dadc87f54485.png)

**Comment by yesmeck** [comment]
请提供一个能运行的 demo。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
Close for no response
