### ISSUE TITLE
could not sort targetKeys by set sorted targetKeys in Transfer

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#6075]
### Version
当前master分支

### Environment
当前master分支

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/transfer/index.tsx#L142-L151](https://github.com/ant-design/ant-design/blob/master/components/transfer/index.tsx#L142-L151)

### Steps to reproduce
we could not sort targetKeys by set sorted targetKeys in Transfer.
It caused by my PR #6001

### What is expected?
 sort targetKeys

### What is actually happening?
 could not sort targetKeys

**Comment by benjycui** [comment]
Could you fix it?

**Comment by wangtao0101** [comment]
I'll try, I have found a fast algorithm.

**Comment by wangtao0101** [comment]
最新需要处理几千个数据的transfer，无奈只能自己用virtualized重新实现了一个仿antd的，如果你们将来用virtualized，可以贡献给你们。https://github.com/wangtao0101/react-virtualized-transfer

**Comment by benjycui** [comment]
virtualized 之前讨论过 https://github.com/ant-design/ant-design/issues/3789

如果能保证兼容 `Transfer[lazy.onContentVisible]`，我觉得你现在就可以 PR 过来了。

cc @afc163

**Comment by benjycui** [comment]
`ReactVirtualizedTransfer[rowHeight]` 可以适配为 `Transfer[lazy.height]`，其它 API 也可以用类似的思路适配，应该能做到兼容已有的 Transfer 的 API，可以进一步讨论。

**Comment by yesmeck** [comment]
这个 Bug 修复了，issue 先关了，virtualized 另外开 issue 或者直接 PR 讨论吧。
