### ISSUE TITLE
In Table, if data's children is an empty array, it shouldn't show expand icon

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6077]
### Version
2.10.0

### Environment
OSX, Chrome 57

### Reproduction link
[http://codepen.io/superlxc/pen/oWEYOg](http://codepen.io/superlxc/pen/oWEYOg)

### Steps to reproduce
![expand](https://cloud.githubusercontent.com/assets/4329120/25880199/86b507a4-3568-11e7-9af6-4c02341c004c.gif)
Click the expand icon in first row

### What is expected?
no expand icon

### What is actually happening?
has an expand icon and showing nothing after clicking

**Comment by afc163** [comment]
The icon is reserved for async situation, we can load data and insert it to children when user click icon. If you want to hide icon when children is empty, you should clear data by yourself.
