### ISSUE TITLE
React组件不可以单独引用单独组件的样式表吗？

### ISSUE THREAD

**Issue by wefiy** [ant-design/ant-design#608]
组件还是直接引用的一个总的样式表，为什么没考虑单独引用组件样式呢？这样可以方便生成全局唯一的样式名称。

**Comment by afc163** [comment]
不推荐，组件的样式都有千丝万缕的关联。

**Comment by jasonperk** [comment]
是不是也不支持提取出来自己定义？？？（目前）

**Comment by afc163** [comment]
可以自行覆盖。

**Comment by jasonperk** [comment]
目前编译会报这样的错误
RROR in ./~/antd/lib/index.css
Module parse failed: /Users/Raven/IdeaProjects/qmcrm/boss-web/src/main/webapp/WEB-INF/src/node_modules/antd/lib/index.css Line 2: Unexpected token {
You may need an appropriate loader to handle this file type.
| /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
| html {
|   font-family: sans-serif;
|   -ms-text-size-adjust: 100%;
 @ ./~/antd/lib/index.js 9:0-22

尝试想把index.css抽取出来 所以把webpack.config.js中的
{test: /\.css$/, loader: "style-loader!css-loader"}去掉
入口文件的import 'antd/lib/index.css'; 也去掉了 

但是编译的时候就报上面的错误

**Comment by afc163** [comment]
试试调整 webpack 的配置。

https://github.com/ant-tool/atool-build/blob/5ffdae09761b3220894711ab57c26b8a7a8df262/src/getWebpackCommonConfig.js#L60-L74

**Comment by jasonperk** [comment]
webpack我只配置了{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"}
入口去掉了import 'antd/lib/index.css';
less文件和css文件提取出来了   在框架页面直接 link调用的
现在编译还是报错
ERROR in ./~/antd/lib/index.css
Module parse failed: /Users/Raven/IdeaProjects/qmcrm/boss-web/src/main/webapp/WEB-INF/src/node_modules/antd/lib/index.css Line 2: Unexpected token {
You may need an appropriate loader to handle this file type.
| /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
| html {
|   font-family: sans-serif;
|   -ms-text-size-adjust: 100%;
 @ ./~/antd/lib/index.js 9:0-22


必须要配置嘛  组件内部 做了css的引用？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#usage-example
