### ISSUE TITLE
2.10.0表单DatePicker控件验证状态图标错位（附图）

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design#6081]
### Version
2.10.0

### Environment
windows10,chrome 59,react 15.5.4

### Reproduction link
[https://chinacoolboyzz.github.io/antd-bug](https://chinacoolboyzz.github.io/antd-bug)

### Steps to reproduce
![Aaron Swartz](https://github.com/chinacoolboyzz/antd-bug/blob/master/images/form_DatePicker_bug.png?raw=true)

### What is expected?
图标不错位

### What is actually happening?
图标错位

**Comment by afc163** [comment]
```jsx
<DatePicker style={{ width: '100%' }} />
```
