### ISSUE TITLE
feat: make validation's message under the control of LocaleProvider?

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6082]
@enzolutions

> @ginodeis
> Thanks for your contribution, with the new version 2.10.0 now the calendar is working in Spanish.
> But, I have a concern about the basic label like validation "% is required" is not in Spanish despite it's inside a Local Provider.
> Any suggestions?
> Buen trabajo.

@benjycui

> @enzolutions validation's locales are not under the control of LocaleProvider, more: https://github.com/yiminghe/async-validator/

@enzolutions 

> @benjycui
> Thank for your response.
> but "% is required" and other are inside antd code, should be possible to contribute a translation of that standard message?
> Any ideas?

**Comment by paranoidjk** [comment]
we can make https://github.com/yiminghe/async-validator/blob/master/src/messages.js work with locale setting

**Comment by enzolutions** [comment]
Could be, but that will force users to have an async process, IMHO should be more transparent for developers

**Comment by afc163** [comment]
We can do it ConfigProvider now~

**Comment by hengkx** [comment]
I didn't understand the mistake.same as #23165,#23369?

**Comment by afc163** [comment]
trace #23369
