### ISSUE TITLE
select组件在mode为multiple或者tags的时候，删除选择项的显示问题

### ISSUE THREAD

**Issue by excellnn** [ant-design/ant-design#6085]
### Version
2.10.0

### Environment
linux、chrome 54

### Reproduction link
[http://codepen.io/liuniannan/pen/wdydZq](http://codepen.io/liuniannan/pen/wdydZq)

### Steps to reproduce
当select存在焦点，并选择选项超过一行，再删除到剩余一行的时候

### What is expected?
下拉菜单位置跟随select框的高度改变

### What is actually happening?
未改变

**Comment by ybning** [comment]
+1

**Comment by benjycui** [comment]
fixed, `rm -rf node_modules && npm i`
