### ISSUE TITLE
Select/autocomplete to be case sensitive

### ISSUE THREAD

**Issue by yarnball** [ant-design/ant-design#6086]
### Version
2.10.0

### Environment
browser

### Reproduction link
[https://codesandbox.io/s/ElKon05Ok](https://codesandbox.io/s/ElKon05Ok)

### Steps to reproduce
In the search bar, search for "red"

### What is expected?
It should treat "red" and "Red" the same,

### What is actually happening?
1. Search for a value (eg "red")
2. It will create a new value for "red", instead of just replacing "Red"

---
Great work on this repo. Would also be great if it put priority on already existing values (for auto-complete) rather than a newly created value. EG- if I search for "Re" it should focus "Red" first, not the optoin to create a new value called "Re". Thanks

**Comment by afc163** [comment]
Try `filterOption`

**Comment by yarnball** [comment]
As you'll see in my codesandbox, I have used that doing the following:

`{(inputValue, option) => option.props.value.toUpperCase().indexOf(inputValue.toUpperCase()) !== -1}`

**Comment by yarnball** [comment]
I have created a screenshot to show the issue:

![screen shot 2017-05-10 at 6 09 56 pm](https://cloud.githubusercontent.com/assets/13043067/25889122/0c239cb4-35ac-11e7-985a-011c9851e145.jpg)

**Comment by yarnball** [comment]
@yesmeck so has this been integrated into the latest version?

**Comment by yesmeck** [comment]
@yarnball Not yet, will release soon..

**Comment by yesmeck** [comment]
A new version of rc-select has released.

**Comment by yarnball** [comment]
Could you please clarify- do I need to npm install a specific version of antd?

**Comment by yesmeck** [comment]
`rm -rf node_modules && npm install`

**Comment by yarnball** [comment]
Nope, still not workign for me. I created an example in this CodeSandbox. https://codesandbox.io/s/nZVoVNjxl

Another issue is also that it will not let me add/create new values. Is there a trick to it? Thanks

**Comment by yesmeck** [comment]
You are using `TreeSelect` in above example, but we are talking `Select` in this issue.
