### ISSUE TITLE
Cant get modular components and style working

### ISSUE THREAD

**Issue by kdma** [ant-design/ant-design#6089]
### Version
2.10.0

### Environment
Win 10, Chrome 58.0.3029.96 (64-bit)

### Reproduction link
[https://github.com/kdma/ant-css-minimal](https://github.com/kdma/ant-css-minimal)

### Steps to reproduce
I followed https://ant.design/docs/react/introduce
 and added ant to my react/ts/webpack webapp
For linked repository just clone repo && npm install

### What is expected?
I expected to be able to have a modularized bundle that doesnt load all components at once and to see them with their CSS

### What is actually happening?
I have a 14 mb bundle and styles are not applied.

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/113#issuecomment-299119261

**Comment by kdma** [comment]
Thanks @afc163 
For anyone interested the solution is in whyming comment in the linked issue.
I suggest to update the getting started in the website.
