### ISSUE TITLE
你好，我想问一下怎么样覆盖样式表？

### ISSUE THREAD

**Issue by wefiy** [ant-design/ant-design#609]
我应该写在哪里才可以避免升级ant版本的时候，把自己的样式覆盖掉。

**Comment by jasonperk** [comment]
你是怎么解决样式自定的问题的？
我把入口文件的import 'antd/lib/index.css'; 去掉也没有用啊

**Comment by wefiy** [comment]
我是直接在 node_modules\antd\style\index.less 直接导入了一个我自己的less文件，编译的时候覆盖变量用的
