### ISSUE TITLE
自定义主题情况下, 升级 2.10.0后, tree组件拖拽的css丢失了.切换回2.9.3拖拽部分效果正常.

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#6092]
### Version
2.10.0

### Environment
ubuntu16.10,chrome58,antd2.10.0

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
在使用自定义主题时,tree组建拖拽时css丢失了.  但是官方demo是正确的. 所以估计是自定义主题造成的. 

### What is expected?
tree组建拖拽时 有自定义主题的情况下, 能正常显示拖拽时的提示色块,标识线等等

### What is actually happening?
切换回2.9.3 就都是正常的.

**Comment by benjycui** [comment]
建议你先确认是自定义主题导致的问题，然后再确认是修改了哪几个变量导致的。毕竟你现在的信息，我们也无法判断问题。

**Comment by yesmeck** [comment]
tree 的结构有调整 https://github.com/react-component/tree/pull/86 自己检查下吧。

**Comment by afc163** [comment]
@yesmeck 这个会影响用户？

**Comment by yesmeck** [comment]
改了 DOM 结构，如果依赖了这个结构来覆盖样式就会的。
