### ISSUE TITLE
This word (colume) may be misspelled

### ISSUE THREAD

**Issue by hybefortis** [ant-design/ant-design#6095]
### Version
2.10.0

### Environment
macOS Sierra Chrome

### Reproduction link
[https://ant.design/docs/spec/layout-cn](https://ant.design/docs/spec/layout-cn)

### Steps to reproduce
设计原则=>布局=>colume

### What is expected?
column

### What is actually happening?
colume

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/fc8189303dabebb05e025cc8cbb95e9f5649eb99

**Comment by hybefortis** [comment]
not fixed yet. 

> 注：图中灰色部分为栅格的列，定义为『Colume』，白色部分为栅格的间隔，定义为『Gutter』
