### ISSUE TITLE
form表单在有select下拉框的时候会显示错乱

### ISSUE THREAD

**Issue by iceking112** [ant-design/ant-design#6097]
### Version
2.10.0

### Environment
window 10，chrome 58

### Reproduction link
[http://codepen.io/mile112/pen/NjYPLK](http://codepen.io/mile112/pen/NjYPLK)

### Steps to reproduce
点击collapse后可以看见下拉框下面的表单被挤走了，点击搜索后因出现提示语导致表单位置又一次变动

### What is expected?
表单排序正常

### What is actually happening?
在存在select下拉框的情况下表单显示错位

**Comment by yesmeck** [comment]
没看出来有什么错位啊？来个截图？

**Comment by iceking112** [comment]
![1494479197](https://cloud.githubusercontent.com/assets/7720312/25934450/70a59364-3650-11e7-8b47-f212288c1689.png)
select下拉框下面的inpu被挤走了

**Comment by afc163** [comment]
给个重现的步骤。

**Comment by iceking112** [comment]
抱歉，经过多次测试发现是Windows缩放的原因，本机屏幕分辨率是1080p，缩放开了125%，所以出现了这种情况，在edge下显示正常，chrome和Firefox下显示均异常

**Comment by afc163** [comment]
貌似有点问题，我晚点看看

**Comment by ybning** [comment]
@afc163 貌似重现不了 @iceking112 所述的问题

**Comment by afc163** [comment]
我重现了，正在想办法修复。

**Comment by ybning** [comment]
![](http://images.cnblogs.com/cnblogs_com/ningyanbo/1000681/o_6097.png)
貌似被挤开了

**Comment by afc163** [comment]
这种没办法，高级搜索不应该做校验。

**Comment by iceking112** [comment]
@afc163 校验这个是一种情况，还有就是开启windows系统缩放后导致的select下面一排的input被挤走了，这个有修复方案吗？

**Comment by afc163** [comment]
我上面不是已经修复了：https://github.com/ant-design/ant-design/commit/9089674a6f01564e48f5a4b3068e1251d9a79756
