### ISSUE TITLE
Hi, 考虑把css部分独立出去吗？ 

### ISSUE THREAD

**Issue by leeluolee** [ant-design/ant-design#61]
感觉比bootstrap 清爽，  如果独立出来， 可以方便不适用React的用户

**Comment by afc163** [comment]
Ant Design 首先是一个设计规范，长远看我们希望能有不同技术栈的实现，所以后续这样的需求我们自己也会有。但目前仍在组件开发阶段，这个目标优先级不高，欢迎贡献和继续关注。

**Comment by afc163** [comment]
目前原始的 dom 结构由于有 React 这层封装，会有一些丑陋和不统一。

**Comment by leeluolee** [comment]
了解。。。  期待你们最终完成的结果，  虽然现在看起来已经很完整了

**Comment by afc163** [comment]
关闭先。
