### ISSUE TITLE
rc-form 适配

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#610]
所有输入组件需要能够配合 rc-form 使用，包括 reset：

例如：

```js
import {Form, FormItem, Input} from 'antd';
let Test = React.createClass({
  render() {
    return <FormItem form={this.props.form} name="xx" options={validate:[{rules:}] }>
      <Input /> 
    </FormItem>
 };
});

Test = Form.createForm()(Test);
```

**Comment by afc163** [comment]
```
<FormValidatorItem>
   <input />
</FormValidatorItem>
```

还是这个看上去优雅一点。

**Comment by afc163** [comment]
https://github.com/react-component/form

**Comment by yiminghe** [comment]
所有输入组件需要能够配合 rc-form 使用，包括 reset：

http://react-component.github.io/form/examples/overview.html

**Comment by warmhug** [comment]
antd里封装 `VerifiableInput` `VerifiableSelect` `VerifiableDatepicker ` `VerifiableTreeSelect` 成这样？附带 错误提示信息

**Comment by benjycui** [comment]
See: https://github.com/react-component/form/issues/7#issuecomment-171516401

**Comment by luolonghao** [comment]
支持这个API
```jsx
<FormItem form={this.props.form} name="xx" options={validate:[{rules:}] }>
   <Input />
</FormItem>
```

**Comment by benjycui** [comment]
存在嵌套使用 `Form` 的场景么？没有的话可以这样：

```jsx
<Form form={this.props.form} >
  <FormItem name="xx" options={validate:[{rules:}] }>
    <Input />
  </FormItem>
</Form>
```

**Comment by yiminghe** [comment]
默认用 context 实现可以 FormItem 不设置 form 属性，如果 FormItem 设置了就用设置的

**Comment by benjycui** [comment]
总结一下，和 rc-form 适配后的 `Form` 的使用方式如下：

1. `Form` 增加 `form` 属性，传入 rc-form 提供的 `this.props.form`，如不传入 `form`，则行为与 0.11.x 一致
1. `Form` 得到 `form` 后，通过 [context](https://facebook.github.io/react/docs/context.html) 传给后代的 `FormItem`
1. `FormItem` 增加 `name` 和 `options` 属性，分别对应 rc-form `getFieldProps` 的两个参数，如不传入，则行为与 0.11.x 版本一致
1. `FormItem` 把 `name` 和 `options` 属性传给 `this.props.form.getFieldProps` (`form` 由 context 传入或 `props` 传入)，并把计算后的返回值传给自己的 child，所以改版后的 `FormItem` **只能有一个 child**
1. `FormItem` 根据 `name` 和 `options` 可以计算出 `required` `validateStatus` `help` 的值，但会优先使用用户传入的值
 
```jsx
<Form form={this.props.form} >
  <FormItem name="xx" options={validate:[{rules:}] }>
    <Input />
  </FormItem>
</Form>
```

如果没意见的话，我下周就按这个方案写了。

**Comment by yiminghe** [comment]
:+1:

**Comment by afc163** [comment]
:+1:

**Comment by luolonghao** [comment]
:+1:

**Comment by ioldfish** [comment]
:+1:
