### ISSUE TITLE
scroll by wheel for tab bar

### ISSUE THREAD

**Issue by brookshi** [ant-design/ant-design#6100]
### What problem does this feature solve?
If there are lots of tab panels, prev/next is not quick and easy enough to find a tab.
For this context, scroll by using wheel for tab bar is a better way, just like VS Code.

### What does the proposed API look like?
tabScrollType="scroll" | "button"

**Comment by benjycui** [comment]
The UX should be:
1. hover on tabbar 
2. scroll

Right?

The problem is.. how to implement?

**Comment by benjycui** [comment]
I think this will be ugly.
1. If we don't show scrollbar, it will be confusing.
1. If we show scrollbar, it will be ugly in Windows.
