### ISSUE TITLE
Arrows on the submenu not adhering to Menu `mode` when used in a Dropdown

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#6101]
### Version
2.10.0

### Environment
Mac, Chrome 58.0.3029.96

### Reproduction link
[https://codepen.io/sk_tectus/pen/OmvMMo](https://codepen.io/sk_tectus/pen/OmvMMo)

### Steps to reproduce
1. Add a ant dropdown
2. Pass down a `Menu` as an `overlay` prop
3. Ensure that the `Menu` includes a `SubMenu` 
4. Set the `mode` on the menu to be `inline`
4. Click on the dropdown button

### What is expected?
The arrows on  SubMenu should be 'Vertical', because the mode has been set to `inline`

### What is actually happening?
The arrows are still horizontal.
![image](https://cloud.githubusercontent.com/assets/12829747/25935653/c6e8eec8-3656-11e7-8db2-733d4104af74.png)
They should however be vertical.

**Comment by afc163** [comment]
Menu which is used in Dropdown should not set mode to other value than 'vertical', I just fixed it in  10a2d82.

**Comment by kappa-gooner** [comment]
^^ @afc163 That's a breaking change and should've called for a major version release. Please take backward compatibility into view next time around. 

Thanks for all the support.

**Comment by afc163** [comment]
Noop, it was unsupported in first place.
