### ISSUE TITLE
DatePicker失去焦点时能否触发一个事件

### ISSUE THREAD

**Issue by zyw00001** [ant-design/ant-design#6102]
### What problem does this feature solve?
组件失去焦点时需要做一些其他事情

### What does the proposed API look like?
DatePicker中增加一个onBlur回调

**Comment by afc163** [comment]
onOpenChange?

**Comment by zyw00001** [comment]
不是onOpenChange。通过js设置DatePicker有焦点后，此时鼠标点击其他地方时，是无法接收到任何事件的

**Comment by afc163** [comment]
你的使用场景是？

**Comment by zyw00001** [comment]
场景：时间是一个必填项，点提交按钮时，如果未填时间会将焦点定位到DatePicker，并出现红色边框，用户如果仍然不对DatePicker进行操作，而是鼠标点击其他地方，此时希望DatePicker的红色边框消失，即希望DatePicker触发一个onBlur事件

**Comment by afc163** [comment]
可以来个 PR ~

**Comment by benjycui** [comment]
> 场景：时间是一个必填项，点提交按钮时，如果未填时间会将焦点定位到DatePicker，并出现红色边框，用户如果仍然不对DatePicker进行操作，而是鼠标点击其他地方，此时希望DatePicker的红色边框消失，即希望DatePicker触发一个onBlur事件

这个场景还是用 `onOpenChange` 就可以了，因为你点击其他地方，DatePicker 就会关闭。

主要是，我觉得 DatePicker 的 `onBlur` 事件有点不好理解吧，而且有可能和选择日期的行为还有 onOpenChange 有冲突。。

**Comment by benjycui** [comment]
> 而且有可能和选择日期的行为还有 onOpenChange 有冲突。。

主要是，选择日期和 onOpenChange 时也会触发 onBlur，不排除会有时序问题。

**Comment by zyw00001** [comment]
@benjycui 由于设置焦点是通过代码(而不是用户点击)设置的，用户点击其他地方时DatePicker没有发出任何事件

**Comment by benjycui** [comment]
> 如果未填时间会将焦点定位到DatePicker，并出现红色边框

这里直接通过 open 属性把浮层弹出如何？

**Comment by zyw00001** [comment]
这个完全可以，确实有效果

**Comment by zyw00001** [comment]
通过在DataPicker的父标签上设置onBlur事件，利用事件冒泡捕获到了DataPicker失去焦点的事件

**Comment by benjycui** [comment]
这个 feature 能不加就不加，同一个时机触发两个不同的事件，终究会使开发者感到困惑。
