### ISSUE TITLE
DatePicker中文版界面问题

### ISSUE THREAD

**Issue by zyw00001** [ant-design/ant-design#6104]
### Version
2.10.0

### Environment
FireFox或Chrome

### Reproduction link
[http://codepen.io/anon/pen/eWMZXj?editors=001](http://codepen.io/anon/pen/eWMZXj?editors=001)

### Steps to reproduce
为（中文版）DatePicker设置value值，如果不设置value值，界面是正常的

### What is expected?
（中文版）正常的中文界面

### What is actually happening?
Bug1：为value设置无效值时，界面全是乱七八糟的字符
Bug2：为value设置有效的日期时，界面上月份是英文

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/4972
