### ISSUE TITLE
希望popover组件也可以像tooltip那样调整和目标元素的距离。

### ISSUE THREAD

**Issue by cyyyu** [ant-design/ant-design#6105]
### What problem does this feature solve?
注意到default theme里有@tooltip-distance，可以调整tooltip和目标元素的距离。但popover组件(和tooltip很相似)没有。
考虑加上吗？

### What does the proposed API look like?
@popover-distance

**Comment by benjycui** [comment]
popover 是基于 tooltip 实现的，理论上那个变量对 popover 也会生效，先试试吧你。

**Comment by afc163** [comment]
Added.

**Comment by cyyyu** [comment]
@afc163 赞~  谢谢
