### ISSUE TITLE
DatePicker - clear button callback.

### ISSUE THREAD

**Issue by Koziar** [ant-design/ant-design#6108]
### What problem does this feature solve?
My feature request is about adding a possibility to pass a callback function to the Clear Button in the DatePicker component.

In my app date comes from the store and on change I update that store with changed data (whenever user choses a different date then the one that was there before). Unfortunately a Clear Button doesn't work when I save date in the store, obviously it can't clear my store.
In the case of my app, user can go and chose a date optionally, date is saved in the store, but then he can change his mind and decide to remove that date if he doesn't need it, then clear button should clear also date data from my app's store.

Maybe there is no need of creating a new feature but perhaps I don't know how to handle that problem. I would appreciate with that problem.

### What does the proposed API look like?
It would be a callback function for the clear button so user could clear a store data.

**Comment by benjycui** [comment]
You can just use `onChange` to sync value.
