### ISSUE TITLE
The callback was already called 错误

### ISSUE THREAD

**Issue by wefiy** [ant-design/ant-design#611]
有没有人和我一样遇到，在使用import { Datepicker } from 'antd';这种用法的时候，webpack报The callback was already called错误。webpack-core\lib\NormalModuleMixin.js:143:11。我使用的是配置文件加webpack构建的。

**Comment by afc163** [comment]
没人碰到就先关了。

**Comment by wefiy** [comment]
应该是babel6版本有问题，我下次准备切换到5
