### ISSUE TITLE
Cannot change Button disabled prop dynamically

### ISSUE THREAD

**Issue by nlazarov** [ant-design/ant-design#6110]
### Version
2.10.0

### Environment
Mac osx, Chrome

### Reproduction link
[http://codepen.io/nlazarov/pen/ZKxrva](http://codepen.io/nlazarov/pen/ZKxrva)

### Steps to reproduce
In the provided sample click the Toggle button.

### What is expected?
The first button gets disabled and enabled again after subsequent toggle clicks.

### What is actually happening?
The state of the first button does not change.

---
Using the ugly workaround from the second button the button can be disabled. Unfortunately this second approach does not reflect React best practices.

**Comment by benjycui** [comment]
You make a mistake:

```diff
toggle() {
  this.setState({
-   disabled: this.state.disabled
+   disabled: !this.state.disabled
  });
}
```
