### ISSUE TITLE
[Feature request] Props for horizontal alignment of Menu Items

### ISSUE THREAD

**Issue by HoumanKml** [ant-design/ant-design#6111]
### What problem does this feature solve?
Separating the menu items into those corresponding to navigation of the public resources [typically on the left] and those corresponding to the navigation of private items [typically on the right] is a common practice. Having props to specify the alignments could be quite useful.

### What does the proposed API look like?
<Menu.Item >Option 1</Menu.Item> // renders on the left by default for language set to ltr
<Menu.Item right>Option 1</Menu.Item> // renders on the right provided with the 'right' prop

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/4051 ??

**Comment by HoumanKml** [comment]
language direction support is simply an optional support for the proposed prop. It is just that for the same of simplicity instead of having 

`<Menu.Item location='right'>Option 1</Menu.Item>`

and 

`<Menu.Item location='left'>Option 1</Menu.Item>`

we could assume that by default the menu item will be located on the left.

**Comment by benjycui** [comment]
If you just want to set `text-align`, you can override style with CSS.

**Comment by HoumanKml** [comment]
That along with putting the menu items inside a flex container and then using justify-content set to space-between should solve it.  Perhaps it is better not to unnecessary add another prop.
