### ISSUE TITLE
SubMenu不能正常打开问题

### ISSUE THREAD

**Issue by yqwoe** [ant-design/ant-design#6114]
### Version
2.10.0

### Environment
ubuntu 16.04,浏览器是chrome,react 15.4.0

### Reproduction link
[http://codepen.io/anon/pen/BRrvxM?editors=1010](http://codepen.io/anon/pen/BRrvxM?editors=1010)

### Steps to reproduce
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { Menu, Icon } = antd;
const SubMenu = Menu.SubMenu;
class App extends React.Component {
  constructor(props) {
    super(props);
    
    this.state = {
    current: '1',
    openKeys: [],
  }
  }
  
  handleClick (e)  {
    console.log('Clicked: ', e);
    this.setState({ current: e.key });
  }
  onOpenChange (openKeys) {
    const state = this.state;
    const latestOpenKey = openKeys.find(key => !(state.openKeys.indexOf(key) > -1));
    const latestCloseKey = state.openKeys.find(key => !(openKeys.indexOf(key) > -1));

    let nextOpenKeys = [];
    if (latestOpenKey) {
      nextOpenKeys = this.getAncestorKeys(latestOpenKey).concat(latestOpenKey);
    }
    if (latestCloseKey) {
      nextOpenKeys = this.getAncestorKeys(latestCloseKey);
    }
    this.setState({ openKeys: nextOpenKeys });
  }
  getAncestorKeys (key) {
    const map = {
      sub3: ['/sub2'],
    };
    return map[key] || [];
  }
  
  render() {
    return (
      <Menu
        mode="inline"
        openKeys={this.state.openKeys}
        selectedKeys={[this.state.current]}
        style={{ width: 240 }}
        onOpenChange={this.onOpenChange.bind(this)}
        onClick={this.handleClick.bind(this)}
      >
        <SubMenu key="/sub1" title={<span><Icon type="mail" /><span>Navigation One</span></span>}>
          <Menu.Item key="/sub1/1">Option 1</Menu.Item>
          <Menu.Item key="/sub1/2">Option 2</Menu.Item>
          <Menu.Item key="/sub1/3">Option 3</Menu.Item>
          <Menu.Item key="/sub1/4">Option 4</Menu.Item>
        </SubMenu>
        <SubMenu key="/sub2" title={<span><Icon type="appstore" /><span>Navigation Two</span></span>}>
          <Menu.Item key="/sub2/5">Option 5</Menu.Item>
          <Menu.Item key="/sub2/6">Option 6</Menu.Item>
          <SubMenu key="/sub2/sub3" title="Submenu">
            <Menu.Item key="/sub2/sub3/7">Option 7</Menu.Item>
            <Menu.Item key="/sub2/sub3/8">Option 8</Menu.Item>
          </SubMenu>
        </SubMenu>
        <SubMenu key="/sub4" title={<span><Icon type="setting" /><span>Navigation Three</span></span>}>
          <Menu.Item key="/sub4/9">Option 9</Menu.Item>
          <Menu.Item key="/sub4/10">Option 10</Menu.Item>
          <Menu.Item key="/sub4/11">Option 11</Menu.Item>
          <Menu.Item key="/sub4/12">Option 12</Menu.Item>
        </SubMenu>
      </Menu>
    );
  }
};

ReactDOM.render(<App/>, mountNode);

### What is expected?
我期望的结果是点击submenu 父级menu和submenu同时展开

### What is actually happening?
点击submenu的时候，父级会关闭

**Comment by afc163** [comment]
https://ant.design/components/menu/#components-menu-demo-sider-current

**Comment by yqwoe** [comment]
@afc163 示例是一样的，我就是拷贝了示例代码在codepen中还原了我的问题。

**Comment by yesmeck** [comment]
官网和你给的例子都没重现你说的问题。

**Comment by yqwoe** [comment]
@yesmeck  不好意思，我把key给替换了，现在尝试一下。http://codepen.io/anon/pen/BRrvxM?editors=1010

**Comment by yesmeck** [comment]
你把 `key` 换了，但是不改 `handleClick`  的逻辑，当然会有问题。

**Comment by yqwoe** [comment]
@yesmeck 我不太明白你说的意思，能否说的更详细呢？多谢了。

**Comment by yqwoe** [comment]
@yesmeck  你说的是onOpenChange的逻辑对吗？

**Comment by yesmeck** [comment]
是的 `onOpenChange `

**Comment by yqwoe** [comment]
@yesmeck  多谢，问题已经改正。
