### ISSUE TITLE
Mention 组件受控模式异常 仍然存在

### ISSUE THREAD

**Issue by skordyr** [ant-design/ant-design#6115]
### Version
2.10.0

### Environment
OS: win10 教育版 1703 Chrome: 版本 58.0.3029.110（正式版本） （64 位）

### Reproduction link
[http://codepen.io/skordyr/pen/rmVQXQ?editors=0110](http://codepen.io/skordyr/pen/rmVQXQ?editors=0110)

### Steps to reproduce
Mention组件 value prop 传入非空字符串 onChange 传入 () => {} 函数时输入内容依然会被渲染到 Mention 组件内且无法删除

### What is expected?
此时输入内容不被渲染到组件

### What is actually happening?
内容渲染到组件且无法删除

---
相关issue #5788

**Comment by afc163** [comment]
Why close it?

**Comment by skordyr** [comment]
不好意思，由于看不到此issue的任何进展，我当时可能考虑不当自己这么觉得“如果没人管那就关掉吧”，如果贵团队有计划或者在修复中我很乐意reopen它，最后感谢贵团队开源了这么好的项目。

**Comment by afc163** [comment]
如果确实有问题就 reopen 吧，不过人手确实不足，强烈欢迎 PR 帮助我们修复。
