### ISSUE TITLE
动态修改from表单中日期选择器的类型会导致控件无法使用

### ISSUE THREAD

**Issue by iceking112** [ant-design/ant-design#6117]
### Version
2.10.0

### Environment
window 10，chrome 58

### Reproduction link
[http://codepen.io/mile112/pen/ybKZPb](http://codepen.io/mile112/pen/ybKZPb)

### Steps to reproduce
报表类型选择‘月报‘，日期选择器会切换到<MonthPicker>，但是无法选择日期，会报错

### What is expected?
选择报表类型后日期选择器会随之变化

### What is actually happening?
变化类型后的日期控件无法使用

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/4460

**Comment by benjycui** [comment]
这个不好改，而且也不是很有必要。

**Comment by ybning** [comment]
这种应用场景还是有的。

**Comment by iceking112** [comment]
@benjycui 真心挺有必要的，经常会出现要求根据报表类型来确定时间选择器精度的，时间控件精度变化还是蛮多的

**Comment by benjycui** [comment]
不是否认你们的业务场景，而是说技术上共用一个 field name 的必要性。

当然，如果能有 PR 修复，也是可以的。

主要是最近没什么时间看 rc-form、、
