### ISSUE TITLE
I want antd component css to not interfer with other elements

### ISSUE THREAD

**Issue by bochen2014** [ant-design/ant-design#6118]
### What problem does this feature solve?
I'm interested in using antd date-picker, but after I referenced that component along with its css (modularized version, i.e. only  ` import 'antd/lib/date-picker/style' `), my entire website has got the antd styles,  like font-size, color..etc. This is not acceptable for a commercial website.

is it possible to limit antd component css/less to the component itself?

### What does the proposed API look like?
here is an example that won't have a global css impact  
https://github.com/Hacker0x01/react-datepicker

**Comment by bochen2014** [comment]
an alternative is to provide the css for `date-picker` myself but that would involve a lot of work.

again, why can't we limit the css to the component itself?

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/4331
