### ISSUE TITLE
Modal.success 不可以调用方法关闭

### ISSUE THREAD

**Issue by zhengqingxin** [ant-design/ant-design#6121]
### What problem does this feature solve?
我的场景是这样的：当用户提交一个表单，成功后 Modal.success 弹出成功信息，这个信息里包括了一个链接，可以跳到其他页面（方便指引用户）。但是发现点击链接跳到对应页面以后，Modal.success的弹窗还在，用户只能在新页面点击确认按钮才能关闭，所以实际场景中可能需要一个可以手动调用关闭的方法（当点击链接的时候关闭弹窗）。

### What does the proposed API look like?
将关闭弹窗的方法暴露出来即可

**Comment by excellnn** [comment]
可以改用Modal组件，给链接绑定一个click事件控制Modal的关闭就行了．

**Comment by benjycui** [comment]
这里不是有个 [destroy](https://github.com/ant-design/ant-design/blob/9089674a6f01564e48f5a4b3068e1251d9a79756/components/modal/confirm.tsx#L99) 么？

**Comment by afc163** [comment]
Documentation should be fixed.

**Comment by afc163** [comment]
It is undocumented now.

**Comment by benjycui** [comment]
这种用法之前是有个 [示例](https://github.com/ant-design/ant-design/commit/f9319e244bea02bafabb666b3f93ae1bf7aec565#diff-0e6acd554c4d9c32f25f2380fdb2398c) 的，为什么把它隐藏起来了？ @afc163

**Comment by afc163** [comment]
忘了
