### ISSUE TITLE
Add renderFooter prop to datePicker

### ISSUE THREAD

**Issue by albertvazquezm** [ant-design/ant-design#6122]
### What problem does this feature solve?
It will allow the developer to add a footer to the calendar inside the date-picker. An use case would be to place buttons with tenors (This month, Last week, D-1, D-2...).

Now it's impossible to add a footer to the calendar inside the date picker unless you do your custom date-picker.

RcCalendar already has this API, so it's just about passing the prop downwards. 

I'm eager to raise a PR for implementing this feature.

### What does the proposed API look like?
`<DatePicker renderFooter={() => <div>MyFooter</div>}>`

**Comment by afc163** [comment]
similar with https://github.com/ant-design/ant-design/issues/5188

**Comment by setshaft** [comment]
@afc163 @albertvazquezm  I want to add buttons in the renderFooter like "This Month", "Last Week". On clicking those buttons I need to select the particular dates in the RangePicker. Can you give a example of how to achieve that?
