### ISSUE TITLE
TreeSelect 无法完全控制要打开的节点

### ISSUE THREAD

**Issue by MedusaLeee** [ant-design/ant-design#6123]
### What problem does this feature solve?
我们动态的改变表单中的TreeSelect的treeData（上下联动），第一次会自动打开树节点，动态改变treeData后，无法自动打开树节点。

### What does the proposed API look like?
期望和Tree组件一样提供expandedKeys属性来完全控制打开节点

**Comment by ybning** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: 
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

(A good and minimum codpen will save a lot of time :smiley:)

**Comment by yesmeck** [comment]
@MedusaLeee If you're reporting a bug, plz use bug issue template.

**Comment by yesmeck** [comment]
let us know in a comment if you can provide a online demo, and we'll reopen it.
