### ISSUE TITLE
Input.Group vertical compact

### ISSUE THREAD

**Issue by Xuhao** [ant-design/ant-design#6126]
### What problem does this feature solve?
Inputs Group compact via vertical way

### What does the proposed API look like?
```javascript
<Input.Group compact="vertical/horizontal">
  <Input type="textarea" />
  <Input type="textarea" />
</Input.Group>
```

Default value of compact is `horizontal`

**Comment by ybning** [comment]
@Xuhao 
[https://ant.design/components/input-cn/#components-input-demo-group](https://ant.design/components/input-cn/#components-input-demo-group)

**Comment by afc163** [comment]
I don't see any usages of vertical compact way.

**Comment by Xuhao** [comment]
@ybning Sorry I did get any vertical compact example in those demo.

**Comment by Xuhao** [comment]
<img width="423" alt="2017-05-14 am 10 44 49" src="https://cloud.githubusercontent.com/assets/324973/26030855/9989ac18-3892-11e7-864b-e3f3a1af04d5.png">

这是我现在需要的垂直组合。也许我这种需求比较特别吧。

**Comment by afc163** [comment]
自行书写样式组合吧。
