### ISSUE TITLE
Popover Content Data Type / Rendering Issue

### ISSUE THREAD

**Issue by davidmcooper** [ant-design/ant-design#6127]
### Version
2.10.0

### Environment
OSX 10.12.4, Chrome Version 58.0.3029.110 (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/pPVemJ?editors=001](https://codepen.io/anon/pen/pPVemJ?editors=001)

### Steps to reproduce
Hover mouse over button included in the Codepen demo.

### What is expected?
I would expect the popup to show the formatted HTML content with the HTML tags.

### What is actually happening?
The HTML tags are being included in the output, despite the type for the content field expected to be a string.

---
It's unclear to me how to use a dynamic value for a popover.  I'm referencing a field in my store which is a string, but it's being displayed with the tags rather than as a formatted popover.

**Comment by NE-SmallTown** [comment]
string is just string,not react element.if you want to display formatted content,your code should like `let myContent = <div><p>abc</p></div>`

**Comment by yesmeck** [comment]
If you want insert HTML string to react element, you can use dangerouslySetInnerHTML https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by davidmcooper** [comment]
Thanks.  I was able to achieve what I wanted by using the .ant-popover-inner-content style and avoiding the use of dangerouslySetInnerHTML.

```
.ant-popover-inner-content
{
    display: block;
    font-family: monospace;
    white-space: pre;
}

```
