### ISSUE TITLE
能把antd弄成简单的ui框架吗? 

### ISSUE THREAD

**Issue by sinyat** [ant-design/ant-design#6128]
### What problem does this feature solve?
can be used directly on HTML.

### What does the proposed API look like?
I'm a Java programmer,for React, i can't use it.I just want a UI that can be used directly on HTML.

**Comment by NE-SmallTown** [comment]
First,please change your title to English.And then,there is a lot of dynamic css,it's based on a library/framework,so you can't make it word by just extract the css.

So,if you just want the theme of antd,you can just copy the css in the official site by finding the index.css file or clone it and compile the corresponding .less file which you want to extract.

**Comment by sinyat** [comment]
ok,thanks!
