### ISSUE TITLE
设置webpack.config.merge.js output之后不生效

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#613]
![image](https://cloud.githubusercontent.com/assets/7006864/11467872/19ba81c8-9786-11e5-9819-c74a7705ca40.png)

设置了输出目录是dist，但是http://localhost:8001/dist/all.js 拿不到js

**Comment by sorrycc** [comment]
对 webpack 不熟的建议不要修改配置了，`filename` 不应该这样配的，http://webpack.github.io/docs/configuration.html#output-filename

另外，如果是启 server 的话，访问的路径应该是 http://localhost:8001/all.js，不需要加 `dist` 的。
