### ISSUE TITLE
多个modal之间通信

### ISSUE THREAD

**Issue by Zuckjet** [ant-design/ant-design#6130]
### What problem does this feature solve?
应用场景：有个打开状态的Modal(暂且命名为modal1),在点击modal1中的某个按钮后，会弹出另一个Modal(暂且命名为modal2)。
功能需求：在modal2中进行一系列操作，关闭modal2以后，希望modal1能根据modal2中一些操作产生的数据，进行内容上的更新（比如，操作modal2并关闭以后，希望modal1中能多出几个按钮之类的）。
疑问：本人注意到，尽管操作modal2会产生一些数据，但是因为modal1在这个过程中一直是开启状态，即便我把modal2中产生的数据存放在state中，modal1也不会重新渲染更新界面内容。

### What does the proposed API look like?
暂无

**Comment by ybning** [comment]
@Zuckjet 
Could you provide a re-producible demo to help us, by forking and editing this codepen:
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

(A good and minimum codpen will save a lot of time :smiley:)

**Comment by Zuckjet** [comment]
I am grateful for your reply. In my opinion ,the question that I asked  is a solution about one type problems not a concrete question. What's more,I have described the question  in detail above.So i don't think it useful to provide concrete code.
Thank you all the same!
