### ISSUE TITLE
[Bug] Button in collapsed Sider is still visible

### ISSUE THREAD

**Issue by topvis** [ant-design/ant-design#6131]
### Version
2.10.0

### Environment
Windows 7, Chrome 58 or IE 11

### Reproduction link
[http://codepen.io/topvis/pen/XRqQyd](http://codepen.io/topvis/pen/XRqQyd)

### Steps to reproduce
Click the the default Sider collapse button to collapse Sider.
![image](https://cloud.githubusercontent.com/assets/5996531/26031226/95dfd852-3839-11e7-9d23-9dd3ba3478ae.png)

### What is expected?
The Button (a child of the Sider) should be invisible when Sider is collapsed.

### What is actually happening?
The Button (a child of the Sider) is still visible when Sider is collapsed.
![image](https://cloud.githubusercontent.com/assets/5996531/26031227/a4af7892-3839-11e7-88c2-ee2c1cb28d33.png)

**Comment by Zuckjet** [comment]
修改js文件：<Button className="nav-text">I'm a Button in Sider</Button>
修改css文件：增加一个样式，
.ant-layout-sider-collapsed .nav-text {
   display:none;
}

**Comment by topvis** [comment]
@Zuckjet Thanks. That's a workaround. It would be good to fix it in the antd library. All children components of a collapsed Sider should be invisible.

**Comment by benjycui** [comment]
@ddcat1115 就使用场景而言，设置 `overflow-x: hidden; overflow-y: auto` 应该就可以了？

**Comment by ddcat1115** [comment]
We can't add `overflow-x: hidden` for Sider because sometimes some children should be visible, for example: the tigger out side of the Sider, a Tooltip which has set `getPopupContainer ` to its trigger and etc.

So I suggest leave it as it is now, let users to add their own styles. @benjycui

**Comment by topvis** [comment]
@ddcat1115, Shouldn't it be that hidden is the default and visible is the exception? Anyway it's your call.

Besides @Zuckjet's workaround, I found I can also resolve it by wrapping the Button component in a <div>. Anything inside a div in Sider will be hidden when the Sider is collapsed.

By the way, antd is an amazing library and you guys have done a great job!

**Comment by benjycui** [comment]
[A line of magic code](https://github.com/ant-design/ant-design/commit/67c38fa3b49d6631ead07e7c73cb34c268be6c93#diff-9145aebe539b05b82e4bbf607260c9eeR171) fix this issue, no extra CSS rules @dd
