### ISSUE TITLE
升级antd2.10.1后，树选择组件，下拉选项中，鼠标放置选项上，鼠标样式变成输入图标，此图标显示错误

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#6137]
### Version
2.10.1

### Environment
Win7、64位、Chrome浏览器

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
在官网进入treeSelect组件，并在提供的示例中，下拉展开选项，将鼠标放置选项上，查看鼠标呈现的图标样式

### What is expected?
鼠标样式为手势图标，链接为预期结果图片链接
https://files.gitter.im/ant-design/ant-design/BwaE/blob

### What is actually happening?
鼠标样式变成输入图标，链接为实际结果图片链接
https://files.gitter.im/ant-design/ant-design/opEY/blob

---
旧版本v2.9.3鼠标样式为手势图标，无此问题，是升级之后才有这个问题的，请修复该问题

**Comment by 22ricky** [comment]
2.10.4 之前的样式改过之后 树节点禁用的样式也变成手型了
https://codepen.io/22ricky/pen/rwBBLX
