### ISSUE TITLE
All the components should tell the differences of `undefined` and `null`

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6139]
It is confusing now, some components need `undefined` when we want to clear value of a property, but others need `null`.

We should unify the behaviors of all the components, and they should:
1. Treat `undefined` as undefined, even if developers pass `undefined` to components explicit
1. Treat `null` as defined, and it means clear the value of a property

This will be a breaking change, so we should do this in next major version.

cc @warmhug

**Comment by paranoidjk** [comment]
+1 for this

**Comment by otakustay** [comment]
+1, `undefined` should mean "a unintentional empty value" so it could be a hint of a future error, leave `null` as the behavior of intentional clear value

**Comment by afc163** [comment]
It is been reolved in antd v4.
