### ISSUE TITLE
 Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.

### ISSUE THREAD

**Issue by xiyouzhang** [ant-design/ant-design#6142]
![r4jd1q1yh8gpv0j7q98c s](https://cloud.githubusercontent.com/assets/18208901/26048243/dd1b352c-3988-11e7-967d-d9800bbb25ae.png)

**Comment by NE-SmallTown** [comment]
Please seriously read the [doc](https://ant.design/components/form/#Form.create(options)) 

> Note: Before using getFieldsValue getFieldValue setFieldsValue and so on, please make sure that corresponding field had been registered with getFieldDecorator

**Comment by acomito** [comment]
@NE-SmallTown is there a code example of how to use getFieldDecorator to see if the field registered yet?
