### ISSUE TITLE
为 Input 设置样式

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#6143]
### What problem does this feature solve?
可以自定义某一个input组件的宽高，而不全部应用。避免在项目入口文件单独写css控制. 现在在Input上的style只能控制宽度，改变高度，输入框并不会变高，只是input外面的span高会增高

### What does the proposed API look like?
直接通过 Input 的Props控制 Input的样式

**Comment by yesmeck** [comment]
You are free to pass `style` or `className` to `Input`.

**Comment by changyijie** [comment]
http://codepen.io/anon/pen/JNZJGm?editors=0110   这个是重现代码  用前缀后缀的 无法改变输入框的高度

**Comment by yesmeck** [comment]
Try `className`.

https://github.com/ant-design/ant-design/issues/4540
