### ISSUE TITLE
Input前缀后缀的 无法通过style或className改变高度

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#6144]
### Version
2.10.1

### Environment
win7  chrome版本 59.0.3043.0  

### Reproduction link
[http://codepen.io/anon/pen/JNZJGm?editors=0110 ](http://codepen.io/anon/pen/JNZJGm?editors=0110 )

### Steps to reproduce
Input前缀后缀的 无法通过style或className改变高度

### What is expected?
Input前缀后缀的 通过style或className可以改变高度

### What is actually happening?
Input前缀后缀的 无法通过style或className改变高度

**Comment by afc163** [comment]
Just resolved the `style` problem, `className` is hard to deal with.
