### ISSUE TITLE
DatePicker & MonthPicker should not use selected style when user haven't selected value

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6146]
Current style is wrong:

![image](https://cloud.githubusercontent.com/assets/3580607/26052048/d057e0ac-3996-11e7-881f-6d1033411517.png)

This is right:

![image](https://cloud.githubusercontent.com/assets/3580607/26052128/052a6066-3997-11e7-8472-9f09c60ee00b.png)

**Comment by infeng** [comment]
rel #4071

**Comment by benjycui** [comment]
这个不一样的吧，真正的问题是，用户没选择之前，今天那个 cell 不应该有 `ant-calendar-selected-day` 这个样式。

**Comment by infeng** [comment]
那就是『键盘操作的当前日期』和『选中日期』的样式要分开

**Comment by benjycui** [comment]
关联内部 ued/ant-design#202 ，还需讨论，先 pending

**Comment by afc163** [comment]
It is not selected date, it is a `keyboard-active` date.

**Comment by afc163** [comment]
Discussed this before: https://github.com/react-component/calendar/issues/30

**Comment by benjycui** [comment]
![image](https://user-images.githubusercontent.com/3580607/27266967-bb615b7c-54d7-11e7-825c-d7eddeee40b8.png)

Blue font and white background means today, white font and blue background means active.

So, no special style for selected date?

**Comment by afc163** [comment]
Yes, we need one more style for selected date or new active style.

**Comment by supra28** [comment]
shouldn't active and selected represent the same thing?

**Comment by xiaoqing-tan** [comment]
The issue still exists when I use DatePicker set showTime as true, then I click 'OK' nothing was changed in input box.
