### ISSUE TITLE
datePicker 选择日期时候的问题

### ISSUE THREAD

**Issue by varrant** [ant-design/ant-design#6147]
### Version
2.10.1

### Environment
https://ant.design/components/date-picker-cn/

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
rangePicker中 存在翻下一页，startdate被清空的问题

### What is expected?
rangePicker中 存在翻下一页，startdate不被清空的问题

### What is actually happening?
rangePicker中 存在翻下一页，startdate被清空的问题

**Comment by afc163** [comment]
It is better if you write issue in English.

**Comment by ybning** [comment]
@varrant 
Could you provide a re-producible demo to help us, by forking and editing this codepen:
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

(A good and minimum codpen will save a lot of time :smiley:)

**Comment by benjycui** [comment]
I understand what you said @varrant , you can try to PR to fix it, or I will do it later.

And you can also provide a re-producible demo and steps, so others may understand this issue, and then they can try to fix this issue, too.

**Comment by benjycui** [comment]
这个问题的原因在于：
1. 选择 range 第一天时，选中状态是存在 RangeCalendar，此时没有触发 onSelect 事件，所以也没办法把值同步到 RangePicker
1. 切换切换月份或年份，触发了 onValueChange，并把值同步到 RangePicker，然后触发 re-render
1. 此次 re-render 时，RangePicker 内的 selectedValue 还是 []，所以把 RangeCalendar 内的值重置，所以视觉上就是一开始选中的值被清空

几个功能捆绑在一起，同时也由于 antd.DatePicker.RangePicker 与 rc-calendar.RangeCalendar 的 state 互相隔离，这个 bug 不是特别好修复。。

**Comment by benjycui** [comment]
想到个解法，需要 https://github.com/react-component/calendar/issues/223 完成。

**Comment by benjycui** [comment]
@varrant 现在的交互：

<img src="http://g.recordit.co/ge9z265Gnu.gif" />
