### ISSUE TITLE
Request for time range picker 提供时间段选择器

### ISSUE THREAD

**Issue by meowtec** [ant-design/ant-design#6148]
### What problem does this feature solve?
For business need, we need the time range picker to select shop business hours such as

`06:00 ~ 18:00`
`15:00 ~ 24:00`

I found that `RangePicker` is available from `DatePicker` component, but TimePicker not.
My solution is combining two TimePicker to my *TimeRangePicker*. I did that success but with a defect:

**I can not choose 24:00 as the end time.**

My hack fix is using 00:00 to act as 24:00 in end TimePicker. But that is terrible.

Want:

In a word: We need a time range picker that support select 24:00 as end time.

-------------

我们的业务需要这样的时间段选择组件，能够选择营业时间（或者其他的一天内的时间段选择需求）：

`06:00 ~ 18:00`
`15:00 ~ 24:00`

目前 Antd 的 time-picker 组件没有提供时间段选择，我的解决办法是把两个 time-picker 封装成一个时间段选择器，但是面临一个问题：

**无法选择 24:00**

我现在的 hack 办法是对结束框使用 00:00 替代 24:00，但是这样很不友好。

Want:

简单说，就是希望提供一个时间段选择器，能够选择 24:00 结尾。

### What does the proposed API look like?
Similar to RangePicker and TimePicker

**Comment by afc163** [comment]
看了一下市面上的 TimePicker ，都没有提供 24:00 这样的时间格式，这个都不能算合法的时间格式串。理论上应该是 `15:00 ~ 23:59`。

**Comment by afc163** [comment]
如果从 Moment 的 format 日期格式来看：

<img width="352" alt="image" src="https://cloud.githubusercontent.com/assets/507615/26057865/f4b056b6-39ad-11e7-9f05-1f99354cef1c.png">

如果使用 `kk` 来代替默认的 `HH` 的话，00 会展示成 24 。但是 `00:30 ~ 06:30` 这种就会变成 `24:30 ~ 06:30` 这种，感觉更奇怪。

**Comment by afc163** [comment]
感觉没有合理的解决方案。

**Comment by afc163** [comment]
感觉找不到合理的解决方式。

**Comment by afc163** [comment]
建议让用户选择 `23:59` 吧。

**Comment by benjycui** [comment]
这个组件层面还是不做修改，但是业务代码可以这样写，就你当前业务场景而言，足矣：

```jsx
From: <TimePicker format="HH:mm:ss" />
To: <TimePicker format="KK:mm:ss" />
```

RangeTimePicker 或者 RangeMonthPicker 在这个 https://github.com/ant-design/ant-design/issues/5190 feature 做完之后，可以在业务代码中实现：

```jsx
// RangeTimePicker
<RangePicker format="HH:mm:ss" showPanels={['time', 'time']}} />
```

**Comment by meowtec** [comment]
@benjycui 这个看上去挺不错的

**Comment by meowtec** [comment]
因为我们只能选择整点或者半整点，结束时间搞个 59 挺突兀的。

**Comment by mengxingshike2012** [comment]
`<TimePicker format="kk:mm" />` 好像并没有被支持吧，看了下代码：
```javascript
<RcTimePicker
        showHour={format.indexOf('HH') > -1 || format.indexOf('h') > -1}
        showMinute={format.indexOf('mm') > -1}
````
下拉选择时间会有问题

**Comment by benjycui** [comment]
@mengxingshike2012 的确，对于 kk 这种格式支持的确不好，包括 https://github.com/react-component/time-picker/blob/227e6ec28c733bba0a4b56e0583058489c0684a6/src/Panel.jsx#L101 生成的也只是 `[0 ... 23]`

如果你有需要，可以考虑 PR，谢谢。

**Comment by steveleeh** [comment]
这个需求确实是有的，最近在做全天排班。针对开发而言23:59:59是一天的结束时间这没有疑问，但是面向于用户并不理解这个时间，实际上你说24:00他一下就明白了，这是今天的结束时间，实际上我们也不提供到秒的选择，变相增加用户心智负担。最后的解决方案是改了rc-timepicker的源码，实现了24点的功能，提交到后台转化成了23:59:59秒。这也引发了一个思考，23:59:59秒其实是程序员的角度，不符合实际的用户思维，rc-component作为基础组件很多地方设计的拓展性完全不够，很多组件设计的耦合性太高，作为基础层不够抽象。

**Comment by frank-liu** [comment]
24:00 本身就是不合法的定义，不存在。问题出在思维方式，我们习惯叫24点，但是其实是midnight (00:00).
