### ISSUE TITLE
IE8下大部分组件不能用，会报Function.prototype.apply: 缺少 Array 或 arguments 对象

### ISSUE THREAD

**Issue by wishflyer** [ant-design/ant-design#615]
IE8下大部分组件不能用，会报Function.prototype.apply: 缺少 Array 或 arguments 对象，已经按说明引入了相关的js文件

IE9及以上以及其他现代浏览器，都正常。麻烦看下哩~~谢谢~~

**Comment by afc163** [comment]
https://github.com/react-component/time-picker/issues/2

**Comment by afc163** [comment]
重新安装 antd@0.10 即可，在依赖的 rc-time-picker@0.7.2 里修复了。

**Comment by wishflyer** [comment]
经测试，只使用最简单的Button组件，IE8直接假死。
