### ISSUE TITLE
Tree组件的loadData设计无法通过redux合理控制子节点数据加载状态

### ISSUE THREAD

**Issue by Liuthx** [ant-design/ant-design#6150]
### What problem does this feature solve?
Tree组件在异步数据加载时是使用loadData属性来控制加载进度(转圈圈)的, 
这个组件目前需要传入一个返回值为promise对象的方法, 内部API通过调用promise对象的then方法来内部控制圈圈的显示与否. 
目前遇到的问题是: 按照这种设计的话, Tree组件的dataSource只能在loadData方法中修改, 即dataSource只能在组件内部维护,  如果使用redux来控制dataSource, 处理这个问题就很麻烦. 

### What does the proposed API look like?
在TreeNode props中增加loading属性, 直接通过更改数据源来改变节点的加载状态,
如果能对外暴露TreeNode的render方法更好.

**Comment by ybning** [comment]
@Liuthx 
Could you provide a re-producible demo to help us, by forking and editing this codepen:
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

(A good and minimum codpen will save a lot of time :smiley:)

**Comment by HengCC** [comment]
@ybning 
我现在的解决方案是写成这样
```
  const onLoadData = (treeNode) => {
    return new Promise((resolve) => {
      dispatch({
        type: "displayCategory/getChildTreeData",
        payload: treeNode
      })
      resolve();
    });
  }
```
只是这样就无法将loading状态交给redux来控制. 也就是当onLoadData被执行的时候,立马就resolve了. 也就是加载完成了. 实际可能还没有加载完成.

**Comment by warmhug** [comment]
@HengCC  把 resolve 或 reject 传过去
```js
dispatch({
  type: "displayCategory/getChildTreeData",
  payload: treeNode,
  complete: resolve
})
```
