### ISSUE TITLE
AutoComplete filtering not working

### ISSUE THREAD

**Issue by queimadus** [ant-design/ant-design#6152]
### Version
2.10.1

### Environment
osx 10.11.6, Chrome 57.0.2987.133

### Reproduction link
[http://codepen.io/anon/pen/Lyrgrd?editors=001](http://codepen.io/anon/pen/Lyrgrd?editors=001)

### Steps to reproduce
Type anything in the input, the dropdown input won't get progressively filtered

### What is expected?
For the output to be filtered based on what's written

### What is actually happening?
No filtering is happening

**Comment by ybning** [comment]
@queimadus 
```
filterOption={(inputValue, option) => option.props.children.toUpperCase().indexOf(inputValue.toUpperCase()) !== -1}
```
[https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-non-case-sensitive](https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-non-case-sensitive)

**Comment by yesmeck** [comment]
You need pass `filterOption` to `AutoComplete`, or handle user search by `onSearch`.

**Comment by queimadus** [comment]
Thanks, didn't realise the default behaviour had changed.
