### ISSUE TITLE
typescript 按需加载没有样式

### ISSUE THREAD

**Issue by QuietWind** [ant-design/ant-design#6153]
tsconfig.json

`    // https://github.com/ant-design/ant-design
    "moduleResolution": "node",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "target": "es5",
`

打包过后，antd的js代码有引用到。但是，样式没有拿到。` babel-plugin-import` 对js jsx 支持很好！

谁能贴一下 个人 typescript的解决办法？

**Comment by lansefengxinzi** [comment]
你有解决了吗？ 你按需加载是怎么写的 我这边没有反应。求解。谢谢

**Comment by QuietWind** [comment]
sorry. 没有解决 @lansefengxinzi

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以非常方便的做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 更简洁，性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；

**Comment by NAMANANAS** [comment]
请问解决了吗，感谢！
