### ISSUE TITLE
构建出来的样式有一个地方每添加一个组件就重复一次

### ISSUE THREAD

**Issue by ok111net** [ant-design/ant-design#6156]
Version

2.9.0

What is expected?

构建出来的样式有一个地方每添加一个组件就重复一次：
@font-face {
    font-family: Helvetica Neue For Number;
    src: local("Helvetica Neue");
    unicode-range: u+30-39
}

What is actually happening?

构建出来的样式有一个地方每添加一个组件就重复一次：
@font-face {
    font-family: Helvetica Neue For Number;
    src: local("Helvetica Neue");
    unicode-range: u+30-39
}

我去检查了一下，发现是每次引入组件都会引入antd\lib\style\themes\default.less中都有此样式，应该把此段样式移到公共样式文件里比如antd\lib\style\core\base.less就不会重复。

**Comment by afc163** [comment]
来个 PR 如何~

**Comment by luohow** [comment]
可以做个全局组件，不要放在render去创建，怎么的话就不会重新构建了

**Comment by yszou** [comment]
这问题没有解决吧，怎么就是 close 了呢？
