### ISSUE TITLE
Slider issue Moment Locale Error with React Boilerplate

### ISSUE THREAD

**Issue by ranvirgorai** [ant-design/ant-design#6159]
i installed  antd when i importing Slider from antd in my react boiler plate app getting `error` 

`WARNING in ./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/ranvir/wslab/railx-web-app/node_modules/moment/src/lib/locale'
 @ ./~/moment/src/lib/locale/locales.js 55:12-39
 @ ./~/moment/src/lib/locale/locale.js
 @ ./~/moment/src/moment.js
 @ ./~/antd/lib/calendar/index.js
 @ ./~/antd/lib/index.js`

i am using react boilerplate [https://github.com/react-boilerplate/react-boilerplate]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4491#issuecomment-270887624
