### ISSUE TITLE
能支持用Bower来进行安装 ant-design吗

### ISSUE THREAD

**Issue by kingslay** [ant-design/ant-design#616]
能支持用Bower来进行安装 ant-design吗？

**Comment by afc163** [comment]
不支持，bower 差不多快挂了。

**Comment by kingslay** [comment]
@afc163 那请问一下。如果我只是要在前端页面用ant-design,不使用nodejs。要怎么处理呢？我是用spring boot框架来开发web应用。谢谢！

**Comment by afc163** [comment]
不支持，React 官方推荐使用打包工具进行开发构建。
