### ISSUE TITLE
Default typography of Ant Design is not so well

### ISSUE THREAD

**Issue by onlyice** [ant-design/ant-design#6162]
### Version
2.10.0

### Environment
Windows 7, Chrome 57.0.2987.133 (64-bit)

### Reproduction link
[http://codepen.io/onlyice/pen/oWMXad](http://codepen.io/onlyice/pen/oWMXad)

### Steps to reproduce
See the Codepen link above.

看 Codepen 的链接。

### What is expected?
Should have similar rendering like [bootstrap](http://getbootstrap.com/css/#type) or [typo.css](https://typo.sofi.sh/).

能有类似 [Bootstrap](http://getbootstrap.com/css/#type) 或 [typo.css](https://typo.sofi.sh/) 的展示效果。

### What is actually happening?
The space between headers, paragraphs are not optimal. And the `list-style` of `<li>` is set to `none` that cause the dot / number is not displaying.

Headers、各个 `<p>` 之间间距不佳；对于 `<ul>` `<ol>` 的 `<li>`，前面的小圆点和数字直接没有了。

**Comment by RaoHai** [comment]
@Chinglik

**Comment by benjycui** [comment]
We had notice this issue, and we upgrade our Ant Design Specification in the future.

**Comment by eric-muyser-hs** [comment]
+1 There should be a "Typography" section like all of the best WordPress themes: 
http://bridgelanding.qodeinteractive.com/bridge-elements/typography/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4331#issuecomment-331089741
