### ISSUE TITLE
IE: Input/Select[Combo] in Modal, enter key pressed while typing will close dialog

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#6166]
### Version
2.10.0

### Environment
IE 11, Win 10

### Reproduction link
[http://codepen.io/FrankLuLei/pen/BRPzWo?editors=0011](http://codepen.io/FrankLuLei/pen/BRPzWo?editors=0011)

### Steps to reproduce
1. open a Modal dialog
2. any typing in Input or Combobox of Select
3. press Enter key
4. The dialog will be closed

### What is expected?
The dialog will keep opening after enter key pressed

### What is actually happening?
The dialog closed after enter key pressed

---
The scenario coded in codepen.io cannot run in IE which works in Chrome.

**Comment by afc163** [comment]
<img width="1016" alt="image" src="https://cloud.githubusercontent.com/assets/507615/26102038/f44d2c68-3a65-11e7-85fe-6353ffbbb1f2.png">

I can't reproduce it in IE11.

**Comment by lulut** [comment]
can you try a normal Modal with onCancel and onOk props specified with change visible state of Modal.  We can reproduce in various machines with IE.

**Comment by afc163** [comment]
I are using the code you provide in codepen.

**Comment by lulut** [comment]
Sorry, that's my fault.  The code illustrate as the following doesn't work in codepen.  The run result is totally empty with no error in console.  So I have to use Modal.confirm in click event, and finally found codepen cannot work in IE.

`<LocaleProvider locale={locales.en_US}>
      <Button onClick={()=>openDialog()}>Open Dialog</Button>
      <Modal visible><Input/></Modal>
    </LocaleProvider>`

**Comment by lulut** [comment]
Dear @afc163 , do you have any progress on this bug?

**Comment by afc163** [comment]
I will check it if you can provide a re-producible demo.

**Comment by afc163** [comment]
Close for no reponse.
