### ISSUE TITLE
filteredValue on Table default filters is not working

### ISSUE THREAD

**Issue by manjitkumar** [ant-design/ant-design#6168]
### Version
2.10.1

### Environment
Mac OS X, Firefox 53.0

### Reproduction link
[https://vid.me/ECKy](https://vid.me/ECKy)

### Steps to reproduce
Use a column in table with default filtered Value and try to use that filter.
```javascript
    {
        title: "Environment",
        key: "env",
        dataIndex: "env",
        width: 100,
        filters: [
            {
                text: "prod",
                value: "prod"
            },
            {
                text: "stage",
                value: "stage"
            },
            {
                text: "test",
                value: "test"
            }
        ],
        filteredValue: ["test", ]
    },
```

### What is expected?
I should be able to override the default values from UI.

### What is actually happening?
Whenever I update my filters it goes back to default filteredValue, on overriding it shouldn't do that or I should have a flag to define when to do so.

---
https://vid.me/ECKy

**Comment by yesmeck** [comment]
`filteredValue` doesn't mean default value, it works like `input`'s `value`, maybe we can introduce a new prop called `defaultFilterValue` 🤔

**Comment by manjitkumar** [comment]
Ah, I misinterpreted it then but clearly having something like `defaultFilterValue` will be very useful. Keep this issue to discuss more about it or feel free to close it. Thanks much.

**Comment by afc163** [comment]
Like @yesmeck said, use  `onChange` to control your `filteredValue`: https://ant.design/components/table/#components-table-demo-reset-filter
