### ISSUE TITLE
Autocomplete's filtering

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#6170]
### What problem does this feature solve?
There may already be some solution to this, but I couldn't figure out anything.
The problem is with automplete's filtering. When there is a value filtered and user opens the dropdown up, only the filtered option is shown. This may give an impression to user that this is the only option. He must manually delete the value in order to see all the available options again.

### What does the proposed API look like?
I was trying to improve this default funcionality by deleting the value on focus, so every time the dropdown opens up all values appears again. Problem is that `onFocus` event is called not only when user wants to change the value (focusing by tab key).
Then I thought to have an event, kind of `onOpen` which would delete the value and show all the options. `onFocus` in this case would not do anything.
What do you think? Is there a solution to this already?
Thank you very much!

**Comment by ybning** [comment]
@froston 
Could you provide a re-producible demo to help us, by forking and editing this codepen:
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

(A good and minimum codpen will save a lot of time 😃)

**Comment by benjycui** [comment]
> The problem is with automplete's filtering. When there is a value filtered and user opens the dropdown up, only the filtered option is shown.

It's designed behavior of AutoComplete.

**Comment by yesmeck** [comment]
If you want to keep all options showing, you can disable `filterOption`, then do searching by `onSearch`, see this example https://codesandbox.io/s/k2wA48m6.
