### ISSUE TITLE
Deprecate filterDropdown and relative APi of Table to simplify Table?

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6172]
I consider sorting and filtering are sub-functions of Table, but I don't think it is necessary. Because we can implement sorting and filtering easily with Table and Icon and Popover.

```jsx
const columns = [{
  title: (
    <span>
      Title
      <Table.SortButton onChange={...} sort={this.state.sortStatus} /> 
      <Popover overlay={...}><Icon type="filter" /></Popover>
    </span>
  )
}]
<Table columns={columns} />
```

Now, sorting and filtering are sub-functions of Table, this will not only make Table complicated, and it's seems that it is hard to make sorting and filtering flexible enough, such as https://github.com/ant-design/ant-design/issues/6168 and a long list about [Table[columns[n].filterDropdown]](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+Table+filterDropdown+is%3Aclosed) and another long list about [Table[columns[n].sorter]](https://github.com/ant-design/ant-design/issues?utf8=%E2%9C%93&q=is%3Aissue%20Table%20sorter%20is%3Aclosed%20)

**Comment by benjycui** [comment]
cc @jaredleechn

**Comment by benjycui** [comment]
We can still keep sorting's and filtering's code in antd's codebase, and write some unite test to make sure that they works fine in the future. But I don't think we should encourage developers to use them, and should not add more features about sorting and filtering to Table. It's so complicated..

**Comment by afc163** [comment]
It is not simple to implement whole function for people.

**Comment by jaredleechn** [comment]
At least, it's necessary to export input filter as a easy interface instead of a lot of code I think.

That's a very popular feature https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel

![image](https://cloud.githubusercontent.com/assets/5318333/26139909/4a73699a-3b06-11e7-8e35-a02f2935dd4e.png)

**Comment by benjycui** [comment]
> We can still keep sorting's and filtering's code in antd's codebase, and write some unite test to make sure that they works fine in the future. But I don't think we should encourage developers to use them, and should not add more features about sorting and filtering to Table. It's so complicated, and not flexible enough.

@afc163 so, I said we can keep current behavior, but don't add more features about sorting and filtering in the future.

For simple use case, it is convenient to use integrated sorting and filtering, but for complicate use case(such as @jaredleechn 's use case), use Popover will be better.

See: https://github.com/ant-design/ant-design/pull/6182

**Comment by yesmeck** [comment]
Actually, I'm rewriting rc-table from scratch... As discussed in #5910, I want to make table to be plugin-able:

```javascript
import Table from 'rc-table';
import exd from 'rc-table/lib/plugins/pagination'

<Table plugins={[pagination(options)]} />
```

Maybe we can extract features like filter and sort to a separate package in antd 3?

**Comment by benjycui** [comment]
I agree that the simplest use case should be kept.

```jsx
const columns = [{
  ...
  filters: [
    { text: 'Joe', value: 'Joe' },
    { text: 'Jim', value: 'Jim' },
  ],
  ...
}]
```

But complicated use case, such as #6182 , `filterDropdown` won't simplify this use case, it just make Table complicated.

**Comment by benjycui** [comment]
I think this title should be **Deprecate filterDropdown and relative APi of Table to simplify Table**

**Comment by plandem** [comment]
+1. in our application we don't use built-in filters. To filter we are using own component that provide the "Advanced Search", because in real world it's quite annoying to use build-in filters.

**Comment by abenhamdine** [comment]
@plandem Would you be kind enough to share your implementation ? Looks like a common feature, and I wonder how to implement it in the cleanest way.

**Comment by yesmeck** [comment]
Closing due to inactive.
