### ISSUE TITLE
可否提供右键菜单组件

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#6176]
### What problem does this feature solve?
可以实现在table，tree和其他有右键菜单需求的组件上快速实现右键功能；

### What does the proposed API look like?
onClick: 点击右键菜单；
title：右键菜单标题；
dataSource: 右键菜单数据源；

**Comment by afc163** [comment]
https://github.com/vkbansal/react-contextmenu

**Comment by chj-damon** [comment]
@afc163 所以antd是不打算集成到下一个版本吗？

**Comment by benjycui** [comment]
这个感觉不是很有必要。

**Comment by afc163** [comment]
暂时没有这个需求，建议先使用社区组件。

**Comment by chj-damon** [comment]
@afc163 谢谢你的回复！
