### ISSUE TITLE
当从一个页面调到另外一页面，怎会再次执行最后执行的reducers

### ISSUE THREAD

**Issue by luohow** [ant-design/ant-design#6177]
### Version
2.10.1

### Environment
mac/谷歌

### Reproduction link
[http://zuiidea.com/antd-admin/](http://zuiidea.com/antd-admin/)

### Steps to reproduce
1、页面1，执行modal > effects > reducer
2、页面unmout，跳转到另外一个页面，怎么多执行reducer一次

### What is expected?
当页面unmout的时候不应该多重复执行reducer

### What is actually happening?
会重复最后一次reducer

**Comment by afc163** [comment]
It is not a antd related problem.
