### ISSUE TITLE
Collapse does not work when Panel is inside another component

### ISSUE THREAD

**Issue by oluckyman** [ant-design/ant-design#6180]
### Version
2.10.0

### Environment
osx Chrome 58

### Reproduction link
[http://codepen.io/anon/pen/OmwYeG?editors=001](http://codepen.io/anon/pen/OmwYeG?editors=001)

### Steps to reproduce
use Panel inside another component

### What is expected?
Collapse should work

### What is actually happening?
it makes broken HTML

---
Example:
```
<Collapse>
  { items.map(item => <Item name={item.name} />) }
</Collapse>
```
```
const Item = ({ name }) => <Panel header={name} key={name}>...</Panel>;
```
It does not work.
It produces this HTML:
![image](https://cloud.githubusercontent.com/assets/642673/26142386/f6feb4f8-3ae8-11e7-91d0-510717aded38.png)  

So it’s impossible to separate concerns between List component and List item components.

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/4853
