### ISSUE TITLE
Can you add a new kind of picker "YearPicker",besides can RangePicker performance like two MonthPicker?

### ISSUE THREAD

**Issue by ueedon** [ant-design/ant-design#6181]
### What problem does this feature solve?
Year Picker, RangePicker performance like two YearPicker
        Sometimes the user only want to choose year from the DatePicker or the MonthPicker. For an example,it is no need to care about the month or day when statistics data between 2013 and 2016 and the data are grouped by year .
RangePicker performance like two MonthPicker
        For an example,it is no need to care about the day when statistics data between 2017-01 and 2017-05 and the data are grouped by year .

### What does the proposed API look like?
YearPicker just like the Month Picker;

RangePicker may add a property like "displayStyle"(Y:YearPicker; M:MonthPicker; D:DatePicker) to control the display style when choose a range of date.

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/5190
