### ISSUE TITLE
Modal cannot be rejected

### ISSUE THREAD

**Issue by lsycxyj** [ant-design/ant-design#6183]
### Version
2.10.1

### Environment
Any

### Reproduction link
[http://codepen.io/anon/pen/aWaoGp](http://codepen.io/anon/pen/aWaoGp)

### Steps to reproduce
Call reject of a Promise in "onOK"

### What is expected?
The loading should stop

### What is actually happening?
Endless loading

**Comment by benjycui** [comment]
Try this https://ant.design/components/modal/#components-modal-demo-confirm-promise

**Comment by lsycxyj** [comment]
@benjycui How should I try it? Is there an online demo?

**Comment by benjycui** [comment]
> Try this https://ant.design/components/modal/#components-modal-demo-confirm-promise

Try to handle rejected promise with solution in the demo.

**Comment by lsycxyj** [comment]
Well... It's difficult for me to change the code in the demo to test more cases.

**Comment by benjycui** [comment]
Just copy the demo to CodePen. It is simple enough, just handle `reject` before returning the promise.

Close now.

**Comment by lsycxyj** [comment]
@benjycui 
1. Even if I copy the demo to CodePen, and how could I refer the library containing your modifications?
2. I've reviewed your code. You just close the modal when the Promise is rejected, which means there's no way to stop the closing and let the user retry. There's nothing between resolve and reject. I think it's a bad design.

Close as your pleasure, I don't think it's solved though.

**Comment by benjycui** [comment]
Oops, I make a mistake. I treat @lsycxyj and @WJane as one person.

Actually, @WJane 's PR doesn't solve any problem.

**Comment by benjycui** [comment]
@lsycxyj so, what's your advice.

**Comment by lsycxyj** [comment]
Close the modal when the Promise is resolved and don;t close it when the Promise is rejected.

**Comment by benjycui** [comment]
> Close the modal when the Promise is resolved and don;t close it when the Promise is rejected.

This will change the current behavior, no matter the current behavior is right or wrong, others may depend on it.

We had better be compatible with current behavior and support you expected behavior with some new API and so on.

Actually, you can use Modal, for Modal.method is just for convenient.

**Comment by lsycxyj** [comment]
@benjycui I don't think it will change the behavior because the original behavior is an endless loading when the Promise is rejected.

**Comment by lsycxyj** [comment]
@benjycui Thank you for your fix. I have to wait for the next release to get this fix on npm however.
