### ISSUE TITLE
expand row shows multiple columns instead of single column

### ISSUE THREAD

**Issue by alexsinfarosa** [ant-design/ant-design#6185]
### Version
2.10.1

### Environment
OS X 10.11.6

### Reproduction link
[https://alexsinfarosa.github.io/beet-model-new/](https://alexsinfarosa.github.io/beet-model-new/)

### Steps to reproduce
click on the plus button on any row

### What is expected?
the expanded row should have only one column spanning the entire width of the table

### What is actually happening?
when clicking on the plus button the expanded row has multiple columns

**Comment by yesmeck** [comment]
@alexsinfarosa Your link shows a empty page.
![wx20170517-214929](https://cloud.githubusercontent.com/assets/465125/26157037/b2b34a72-3b4a-11e7-8fa7-d995db045f59.png)

**Comment by alexsinfarosa** [comment]
this should work. Thanks!

https://alexsinfarosa.github.io/beet-model-new/ <https://alexsinfarosa.github.io/beet-model-new/>
—Alex

**Comment by alexsinfarosa** [comment]
Sorry, select something from the dropdown on the left
—Alex

**Comment by yesmeck** [comment]
No, I don't see table on your page.

**Comment by alexsinfarosa** [comment]
Even after you selected State, Station and Date?
—Alex

**Comment by yesmeck** [comment]
I see the table now, could you provide a minimal reproduction? It's hard to read the code of your whole project.

**Comment by alexsinfarosa** [comment]
If you click on the plus button the expanded row has two columns. I would like to have the expanded row in one single column.


—Alex

**Comment by yesmeck** [comment]
Ok...expand row should not use with fixed column.

**Comment by alexsinfarosa** [comment]
I had no idea. THANKS A LOT!
—Alex
