### ISSUE TITLE
Built antd.css contains duplicated CSS

### ISSUE THREAD

**Issue by nhusher** [ant-design/ant-design#6186]
### Version
2.10.1

### Environment
All versions, all environments

### Reproduction link
[https://unpkg.com/antd@2.10.1/dist/antd.css](https://unpkg.com/antd@2.10.1/dist/antd.css)

### Steps to reproduce
1. Open the `antd.css` file for antd 2.10.1
2. Search for `/*! normalize.css`
3. Notice that there are two instances of that line, and the lines that follow

### What is expected?
I expect normalizing css to be included once and only once.

### What is actually happening?
Normalizing css is being included twice.

---
I believe normalize.less is being transitively included twice via base.less. 

The duplicated code appeared in 2.9.2 -- https://unpkg.com/antd@2.9.2/dist/antd.css
It is not in 2.9.1 -- https://unpkg.com/antd@2.9.1/dist/antd.css

There is nothing in the release notes that suggests a change to how the CSS is being built.

I discovered this bug while trying to debug some CSS in a component and realizing that a lot of styles in the cascade were being duplicated.

**Comment by afc163** [comment]
break by #5713
