### ISSUE TITLE
Throw Check the render method of `Select` Error for the antd AutoComplete standard element.

### ISSUE THREAD

**Issue by ilyaLibin** [ant-design/ant-design#6188]
### Version
2.10.1

### Environment
Chrome, babel, react

### Reproduction link
[http://codepen.io/anon/pen/dWjLWo?editors=0011](http://codepen.io/anon/pen/dWjLWo?editors=0011)

### Steps to reproduce
Don't know it works good when I try it in another environment.

### What is expected?
It should render the  Autocomplete Element

### What is actually happening?
For some weird reason and won't render and I'm getting this error:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of Select

It's clear for me that this error message more related to React then antd. but, When I delete those elements from the page while using other antd elements everything works. I wasn't able to distinguish the difference of mentioned beyond elements and other antd elements.

Usually the reason of this error is when I import default element like that import {El} from 'somelib' instead of import El from 'somelib'
But in this case I'm following the API in exact way.

My package js file:

**Comment by ilyaLibin** [comment]
```
 "devDependencies": {
    "babel-core": "6.23.1",
    "babel-loader": "6.3.2",
    "babel-plugin-import": "1.1.1",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-es2015": "6.24.0",
    "babel-preset-react": "6.23.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-2": "6.22.0",
    "babel-register": "6.23.0",
    "css-loader": "0.26.1",
    "expose-loader": "0.7.3",
    "express": "4.14.1",
    "extract-text-webpack-plugin": "2.0.0",
    "grunt": "~0.4.5",
    "grunt-contrib-handlebars": "~0.8.0",
    "grunt-contrib-nodeunit": "~0.2.0",
    "grunt-contrib-watch": "~0.6.1",
    "html-webpack-plugin": "2.28.0",
    "immutable": "3.8.1",
    "less": "2.7.2",
    "less-loader": "2.2.3",
    "loader-utils": "1.0.2",
    "node-sass": "4.5.0",
    "progress-bar-webpack-plugin": "1.9.3",
    "raw-loader": "0.5.1",
    "react-hot-loader": "next",
    "react-transform-catch-errors": "1.0.2",
    "redbox-react": "1.3.4",
    "redux-devtools-log-monitor": "1.2.0",
    "rimraf": "2.6.0",
    "sass-loader": "6.0.0",
    "style-loader": "0.13.1",
    "webpack": "2.1.0-beta.25",
    "webpack-dev-middleware": "1.10.0",
    "webpack-dev-server": "2.1.0-beta.2",
    "webpack-hot-middleware": "2.17.0"
  },
  "dependencies": {
    "antd": "2.10.0",
    "babel-preset-modern-browsers": "^9.0.2",
    "classnames": "2.2.5",
    "es6-promise": "4.0.5",
    "isomorphic-fetch": "2.2.1",
    "json-loader": "0.5.4",
    "moment": "2.17.1",
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "react-dragula": "1.1.17",
    "react-redux": "5.0.2",
    "react-router": "3.0.2",
    "redux": "3.6.0",
    "redux-thunk": "2.2.0"
  }
```

**Comment by benjycui** [comment]
It works fine in your CodePen.

**Comment by ilyaLibin** [comment]
@benjycui
I know. But it suddenly started to throw this error after running yarn install on my project

**Comment by benjycui** [comment]
If you cannot provide a re-producible outside of you project, we cannot tell it is a problem of antd.

**Comment by ilyaLibin** [comment]
@benjycui May be this issue should be open for a while to see if other people starting to face same thing. and we can get more data and understand where it comes from.
May be you can share your webpack configs?

**Comment by ilyaLibin** [comment]
THis is the error screenshot. I am not using Select element straightly but AutoComplete element.
![image](https://cloud.githubusercontent.com/assets/12880486/26188611/e2615a30-3ba8-11e7-94d3-bbd1c9f4ec75.png)

**Comment by ilyaLibin** [comment]
This is my component code
![image](https://cloud.githubusercontent.com/assets/12880486/26188651/1be60210-3ba9-11e7-9b02-378448a8d367.png)

**Comment by ilyaLibin** [comment]
It's Object indeed. May be babel don't build it correctly. 
![image](https://cloud.githubusercontent.com/assets/12880486/26189130/9e71eaf8-3bab-11e7-92eb-dd7136c13e88.png)

**Comment by benjycui** [comment]
I think the problem is in your build config.

**Comment by ilyaLibin** [comment]
the problem disappear once I update webpack from 2.1.5 to 2.5.1 and babel to the latest version.
