### ISSUE TITLE
Get Ref of Buttons

### ISSUE THREAD

**Issue by gaastonsr** [ant-design/ant-design#6189]
### What problem does this feature solve?
For some reason I need to access to the DOM element from the button but currently I don't think it's possible with ant.

### What does the proposed API look like?
`<Button ref={(ref) => { this.buttonRef = ref; }) />`

**Comment by benjycui** [comment]
How about: https://github.com/ant-design/ant-design/issues/5489

```jsx
<Button innerRef={ref => this.buttonRef = ref} />
```

**Comment by gaastonsr** [comment]
yeah that would work too.

**Comment by benjycui** [comment]
But first, what is your use case?

**Comment by paranoidjk** [comment]
React call this as [Exposing DOM Refs to Parent Components](https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components), and they advise against exposing DOM nodes.

do we really need to add this api?

**Comment by benjycui** [comment]
@paranoidjk for Input and Mention and other form controls, we should.

But for Button and Alert and so on, we need more use cases to determine, and I think most of them should not expose refs.

**Comment by yesmeck** [comment]
Why Input and Mention need to expose inner ref, Input already has a `focus` function, any other reasons to access inner DOM?

We can use findDOMNode to access inner DOM node:

```javascript
class App extends React.Component {  
  render() {
    return (
      <Button ref={node => (this.button = ReactDOM.findDOMNode(node))} type="primary">Button</Button>
    );
  }
}
```

**Comment by benjycui** [comment]
Actually, `innerRef` is better than `ref`, even if they have the same behavior.

Because we can keep `innerRef` stable, it will always refer to the same node, even if we had wrap it with several HOC after refactoring, see: https://github.com/ant-design/ant-design/issues/5103

**Comment by benjycui** [comment]
And if you had read the source code of Form.create, you will find `innerRef` is better than `Form.create(option.withRef)`, too.

**Comment by gaastonsr** [comment]
I want to use [clipboard.js](https://github.com/zenorocha/clipboard.js) and do something like [this](http://codepen.io/fibo/pen/wWKGNK?editors=0010).

**Comment by afc163** [comment]
https://github.com/nkbt/react-copy-to-clipboard

**Comment by benjycui** [comment]
So, we don't need to add ref to Button.

**Comment by civet** [comment]
Hey, @gaastonsr I also want to use clipboard.js with antd components. But have the same issue.
Finally, I make it work by adding className on them:

```
<Input className="clipboard-target" value={props.value} readOnly />
<Button className="btn-copy">{props.label}</Button>
```

```
componentDidMount () {
    const input = document.querySelector('.ant-input.clipboard-target');
    const button = document.querySelector('.ant-btn.btn-copy');
    this.clipboard = new Clipboard(button, {
        target: () => input
    });
}
```

**Comment by gaastonsr** [comment]
I did something similar but I thought using refs was a cleaner implentation that's why I opened this issue :)

By the way you can just do ;)

```jsx
<Input value={props.value} readOnly />
<Button className="btn-copy">{props.label}</Button>
```

```js
componentDidMount () {
    this.clipboard = new Clipboard('.ant-btn.btn-copy', {
      text: () => this.props.value
    });
}
```
