### ISSUE TITLE
RangePicker error

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#6191]
http://codepen.io/anon/pen/EmeLXr?editors=0010

1. click button
2. click RangePicker

The console has error logs: `value is null`.

**Comment by benjycui** [comment]
我不懂这个使用场景。

**Comment by ybning** [comment]
@benjycui 

@afc163 的使用场景：
```
click button
click RangePicker
The console has error logs: value is null.
```
:smiley:

**Comment by benjycui** [comment]
@ybning 那不是使用场景，那是重现步骤。

使用 `type="start|end"` 即可 http://react-component.github.io/calendar/examples/start-end-range.html

**Comment by afc163** [comment]
预填一个业务初始值？

**Comment by benjycui** [comment]
这样一开始设置 type=start，等用户选择了之后，再修改为 type=both
