### ISSUE TITLE
input输入框rules校验无法使用

### ISSUE THREAD

**Issue by iceking112** [ant-design/ant-design#6194]
### Version
2.10.1

### Environment
window 10，chrome 58

### Reproduction link
[http://codepen.io/mile112/pen/KmxemE](http://codepen.io/mile112/pen/KmxemE)

### Steps to reproduce
在输入框输入数字显示校验错误

### What is expected?
输入内容校验正确

### What is actually happening?
定义规则为const rangeConfig = {
      rules: [{ type: 'number', required: true, message: 'Please input number!' }],
    };
但是输入数字校验失败

---
目前测试email和string校验正常，number、integer、boolean等校验均出错

**Comment by benjycui** [comment]
因为 input 的值本身就是 string 类型，除非你先用 getValueFromEvent 转换。
