### ISSUE TITLE
AutoComplete option alposition in Modal（AutoComplete option 在Modal 错位）

### ISSUE THREAD

**Issue by CoderChow1994** [ant-design/ant-design#6195]
AutoComplete option alposition in Modal.
if the Modal's height is too high, it will  in this way.
AutoComplete option 在Modal 错位。我用的DVA
如果Modal高度很高，出现滚动条，然后一拉滚动条就这样了。
![1495079630 1](https://cloud.githubusercontent.com/assets/23169397/26185963/d6fece76-3bc0-11e7-9d98-abf7c1409127.jpg)
![1495079651 1](https://cloud.githubusercontent.com/assets/23169397/26185965/dacb5696-3bc0-11e7-9715-b6aa754c8369.jpg)
![image](https://cloud.githubusercontent.com/assets/23169397/26185996/098e5726-3bc1-11e7-99db-b54786672945.png)

**Comment by benjycui** [comment]
Use AutoComplete[getPopupContainer]
