### ISSUE TITLE
TreeSelect进行搜索时的高亮问题

### ISSUE THREAD

**Issue by 3610cn** [ant-design/ant-design#6198]
### What problem does this feature solve?
TreeSelect 在搜索时，对命中选项进行整体高亮，是否可以增加高亮选项中命中的关键字？

### What does the proposed API look like?
可以添加一个配置项，如highlightKeyword, 类型为boolean，默认值为false（向前兼容）

**Comment by yesmeck** [comment]
自己用 `onSearch` 实现以下也很简单的。

**Comment by 3610cn** [comment]
onSearch改变传入的treeData? 感觉有点绕

**Comment by yesmeck** [comment]
如果有自定义的 `filterTreeNode` 的话组件内部也不好处理，建议自己搞吧：

https://codesandbox.io/s/XDmBON8B8
