### ISSUE TITLE
`cursor: not-allowed` 与 `pointer-events: none` 冲突

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#620]
当 Select 或其 Option 设置为 disabled 时，CSS 会相应设置 `cursor: not-allowed`，但同时也设置了 `pointer-events: none`。所以当鼠标 hover 到 disabled 的元素上面时，cursor 的外观并没有发生变化。See: https://github.com/twbs/bootstrap/issues/16088#issuecomment-82335741

考虑到 [`pointer-events` 的兼容性](http://caniuse.com/#search=pointer-events) 并不好，是不是应该将其移除？

真需要 suppress 鼠标事件时，或者可以考虑把对应的事件 handler 改为 `(e) => { e.preventDefault(); }` 之类。

@warmhug

**Comment by afc163** [comment]
https://github.com/react-component/select/pull/35

**Comment by benjycui** [comment]
居然没有自动  Close。。。。
