### ISSUE TITLE
[Form] validateFields only triggers once

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#6203]
### Version
2.10.1

### Environment
Chrome 58

### Steps to reproduce
I've got a Select and Input box, where the input box should validate on every change. Also when the Select value changes I'm trying to revalidate the input box.
```
 <Select
    defaultValue="1"
    onChange={this.handleDomainChange}
>
  <Option value="1">Option 1</Option>
  <Option value="2">Option 2</Option>
</Select>
...
handleDomainChange(value) {
  this.props.form.validateFields(['hash']);
}
```

Then my hash input value:

```
{getFieldDecorator('hash', {
     rules: [{
       message: 'Hash is already in use',
       validator(rule, value, callback) {
          // Some async check
          callback();
       }
     }],
 })(
<Input placeholder="ClickMe" />
)}
```

### What is expected?
Every time the Select value changes, the input hash value runs through the validation async check again.

### What is actually happening?
It's revalidating once, but subsequent changes to the select do nothing.

**Comment by benjycui** [comment]
`this.props.form.validateFields({ force: true }, () => {})`
