### ISSUE TITLE
Fixed dropdown

### ISSUE THREAD

**Issue by ghoshnirmalya** [ant-design/ant-design#6204]
### What problem does this feature solve?
If I want to add a dropdown to a navigation which will be fixed to the top of the layout, then it would be good to stop the dropdown from scrolling on page scroll.

### What does the proposed API look like?
I would like to add a boolean prop (`fixed`) to the `Menu.Item` component. If this props is `true`, the dropdown will be fixed, otherwise it will behave how it behaves at present.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3487#issuecomment-254766673
