### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by yiranlee** [ant-design/ant-design#6206]
### What problem does this feature solve?
upload only show the file list , hide the button

### What does the proposed API look like?
add an API to hide the button and show the file list

**Comment by yesmeck** [comment]
If no button, how can user select files?

**Comment by yiranlee** [comment]
in some cases, i can get the files list from the backend, we just want to show the file list and hide the button ,so i mean  the upload can divide two parts -- button and list

**Comment by yesmeck** [comment]
Then you can hide button by yourself.

```javascript
<Upload {...props}>
    {files.lenght <= 0 && <Button>Upload</Button>}
</Upload>
```
