### ISSUE TITLE
select multiple模式 options由输入值异步渲染，下拉选项展示逻辑问题

### ISSUE THREAD

**Issue by icewind7030** [ant-design/ant-design#6210]
### Version
1.11.6

### Environment
windows7 chrome50

### Reproduction link
[https://codepen.io/anon/pen/KmGoxz?editors=1111](https://codepen.io/anon/pen/KmGoxz?editors=1111)

### Steps to reproduce
在select的输入框中输入“测试”，select获取到输入值变化，向服务端请求以“测试”开头的数据，返回后更新state,从而更新select 下拉选项

但是这时select的下拉选项并不展示，我再backspace清空输入框，服务端返回所有的数据，这时下拉选项才开始展示，请问这是我的使用问题吗？

### What is expected?
通过输入值异步渲染下拉选项，选中则添加一个tag

### What is actually happening?
无法完成根据输入值异步渲染下拉选项的功能，根据输入值渲染的下拉选项不展示

---

**Comment by ybning** [comment]
@icewind7030 
[https://ant.design/components/select-cn/#components-select-demo-select-users](https://ant.design/components/select-cn/#components-select-demo-select-users)
