### ISSUE TITLE
请问当官网提供的定制主题不能满足我们的需求时，该如何修改组件的样式比较合理呢？

### ISSUE THREAD

**Issue by echo0813** [ant-design/ant-design#6211]
### What problem does this feature solve?
我们目前使用的方式是覆盖原有的样式，可是是有问题存在的，比如我们需要两种不同样式风格的组件，一种样式总是被另一种覆盖掉，请问该怎么解决？

### What does the proposed API look like?
希望api的说明能更详细一点，比如Select组件的dropdownStyle，不知道里面都可以设置什么？

**Comment by yesmeck** [comment]
大部分组件都支持 `className`，然后自己用 css 覆盖样式。
