### ISSUE TITLE
Can't get value of select

### ISSUE THREAD

**Issue by Twisterking** [ant-design/ant-design#6212]
### Version
2.10.1

### Environment
Chrome Mac OS

### Reproduction link
[http://codepen.io/anon/pen/WjaJxo?editors=0010](http://codepen.io/anon/pen/WjaJxo?editors=0010)

### Steps to reproduce
I would like to somehow retrieve the current value of my (multiple) select but I have no idea how.

### What is expected?
Shouldn't `mySelectRef(.props).value` be defined?

### What is actually happening?
undefined. No idea how to get the current value of a select

**Comment by ybning** [comment]
@Twisterking 
[http://codepen.io/anon/pen/WjaJxo?editors=0010](http://codepen.io/anon/pen/WjaJxo?editors=0010)
The examples you provide are problematic，that could be the cause of the problem.

**Comment by Twisterking** [comment]
I couldn't get it to work in codepen but you get the idea of what I am trying to achieve. I just need a way to get the current value of a select. that's all.
