### ISSUE TITLE
select: onSelect/onDeselect should be able to prevent (de-)selection

### ISSUE THREAD

**Issue by Twisterking** [ant-design/ant-design#6213]
### What problem does this feature solve?
one could prevent the (de-)selection of an item. e.g. if the user deselects an item a confirm box pops up - if the user decides NOT to (de-select) it, nothing happens.

### What does the proposed API look like?
If the onSelect/onDeselect cb function returns false, nothing happens. the (de-)selection only happens when the cb function returns a truthy value

**Comment by benjycui** [comment]
`Select[value]` is a controlled property.

**Comment by JonasJonny** [comment]
@Twisterking Hi Patrick, did you found any solution?

@benjycui Is there any example how to control `Select.Option` or Add extra style or hide remove cross? 
http://react-component.github.io/select/examples/multiple.html The cross is removed when option is disabled but not in AntD.
