### ISSUE TITLE
 'up to now' feature in DatePicker/MonthPicker/TimerPicker

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6219]
### What problem does this feature solve?
 'up to now' doesn't mean today.
eg: I want users to choose the period of their career experience, if they are still on the job in current company, the period should end with 'up to now' not 'today'

### What does the proposed API look like?
`showUpToNow` just like `showToday`, and the value can be empty string or something special, and in the input area should show 'up to now' instead of a specific time

**Comment by benjycui** [comment]
What is the expected UI and UX of **Up to now**?

**Comment by L-x-C** [comment]
![a](https://cloud.githubusercontent.com/assets/4329120/26295867/b36872aa-3efe-11e7-93cb-5c540f3762f4.png)
![b](https://cloud.githubusercontent.com/assets/4329120/26295907/e40d0510-3efe-11e7-9a5a-c4f94d96ea58.png)

maybe like this?

**Comment by benjycui** [comment]
> What is the expected UI and UX of Up to now?

I asked this question, because I think it's hard to show 'Up to now' status with DatePicker.

And, you advice is confusing(which is under my expectation).

**Comment by L-x-C** [comment]
![datepicker2](https://cloud.githubusercontent.com/assets/4329120/26305778/4f04788e-3f23-11e7-9e9d-cd3858f983dc.gif)

也许是我前面表达的不清楚啊，就是希望有个按钮，能点完变成至今，value就是空应该就行

**Comment by afc163** [comment]
I think it could be resolved with #6122

**Comment by L-x-C** [comment]
Indeed it's a little tricky here, maybe I will do as LinkedIn did.

![linkedin](https://cloud.githubusercontent.com/assets/4329120/26337025/9990404c-3fa8-11e7-8f09-c074da3fc90d.gif)

**Comment by benjycui** [comment]
Close now.

Supporting invalid date string will break current behavior of DatePicker.

And I think LinkedIn's solution works fine.
