### ISSUE TITLE
table组件实现 合并单元格 并且 可分页？

### ISSUE THREAD

**Issue by zhengqingxin** [ant-design/ant-design#6222]
### What problem does this feature solve?
描述一下场景：需求是一个table，可以合并单元格（每大条数据包含若干小条，数量不一定），同时要可以分页，每页 10 大条数据。
困惑：
1.因为 table 显示的条数和 pageSize 一致，所以 pageSize 应该是小条的数量；
2.如果 pageSize 等于小条的数量，而要求每页显示 10 大条数据，那么每页小条的数量（pageSize）则是个不定值，则计算出的总页数会不对。

### What does the proposed API look like?
理想情况是Table暴露个属性？或者分页组件可以指定总页数？

**Comment by yesmeck** [comment]
> 或者分页组件可以指定总条数？

`<Table  pagination={{ total: 100 }} />`

**Comment by zhengqingxin** [comment]
@yesmeck 是总页数，我描述错误

**Comment by buxuku** [comment]
这个需求的确可能会用到，我在我的项目中也遇到过这样的需求。一条大数据可能会有不定条数的小数据。这个时候不能用小数据的条数来分页，

目前的解决的方法是不用表格的pagination API，使用<Pagination/>组件来实现分页功能。

**Comment by benjycui** [comment]
antd.Table 对这种场景的支持的确不友好。

或者你们可以考虑这种交互 https://ant.design/components/table/#components-table-demo-nested-table

**Comment by zhengqingxin** [comment]
感谢 @buxuku 的提示。其实用分页组件和禁掉分页的 Table 是可以实现的，也不算复杂。 

@benjycui 但这种实现方式最好能够在文档中简单提示一下，不然可能会想不到。还有根据我对 antd 的使用经验来看，针对 Table 组件的涉及“合并单元格”场景，有时会让使用者感到不方便，除了分页，还有列选择等类似涉及“大条”的操作，可能都需要使用者做一些 hack 才能实现。

一点小意见，希望 antd 越来越强大。💪💪💪

**Comment by yesmeck** [comment]
自行处理吧，issue 关了。
