### ISSUE TITLE
Select  组件 在页面滚动的时候

### ISSUE THREAD

**Issue by mimimi1227** [ant-design/ant-design#6223]
### What problem does this feature solve?
在用户想要继续浏览的时候 必须手动收回 select 这样影响体验。

### What does the proposed API look like?
希望增加参数

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3487#issuecomment-254766673

**Comment by mimimi1227** [comment]
@afc163  了解 多谢
