### ISSUE TITLE
Cannot style some data entry components such as Input and Select with glamor library

### ISSUE THREAD

**Issue by vamsiampolu** [ant-design/ant-design#6226]
### Version
2.10.1

### Environment
react 15.x

### Reproduction link
[https://www.webpackbin.com/bins/-KklHupM3rSwLRz4I0vA](https://www.webpackbin.com/bins/-KklHupM3rSwLRz4I0vA)

### Steps to reproduce
Style a form control such as Input, Select or Radio with glamor css-in-js solution as I have in the minimal example with className, style and object spread operator

### What is expected?
I would expected that all three would exactly the same way allowing me to provide option for form customization by using either the className or style prop. The checkbox and the switch widget are examples of widgets that work correctly when styled with className using glamor.

### What is actually happening?
The className and the style prop are ignored by the components, this could be because glamor passes in an object instead of a string passed in by libraries such as styled components. I need to use a className prop to style the components from a configuration, I had no option but to resort to using global css and css modules in order to scope my styles instead.

---
Please test ant-design with all the important css libraries such as glamor, aphrodite, jss and so on and document the level of support for them for each component.

**Comment by benjycui** [comment]
> Please test ant-design with all the important css libraries such as glamor, aphrodite, jss and so on and document the level of support for them for each component.

Sorry, we don't use these solutions in our projects. But any reasonable improvement to antd is welcomed.

So, you can PR if you find any issue, thanks.

**Comment by vamsiampolu** [comment]
I did further investigation on this issue, I noticed that you are using `classNames` library with css classes. When I provide the `className` prop to the `Input` component, this code is called:

```js
const inputClassName = classNames(prefixCls, {
      [`${prefixCls}-sm`]: props.size === 'small',
      [`${prefixCls}-lg`]: props.size === 'large',
    }, props.className);
```

So, I decided to find out if `classNames` were playing well together which showed me that when using `glamor` with `classNames` as-is:

```js
const myClassNames = classNames('a', 'b', glam)
```
will only add the className `a b` to the component

while using the glamor css with `toString` adds the glamor className along with `a` and `b`:

```js
const myClassNames2 = classNames('a','b', glam.toString())
```

 I created a webpack bin:

https://www.webpackbin.com/bins/-KkreFZUEH8E1__aU2r9

This workaround is just fine unless there are hidden implications of calling `toString` manually on a css object created with glamor.

**Comment by benjycui** [comment]
@vamsiampolu cool, and I think you can/should PR to `classnames`
