### ISSUE TITLE
DatePicker.RangePicker组件存在的Bug

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#6228]
### Version
2.10.1

### Environment
Chrome 58.0.3027.110(64-bit)

### Reproduction link
[http://127.0.0.1:8080](http://127.0.0.1:8080)

### Steps to reproduce
使用RangePicker的range属性

设置快捷时间如下    

    range: {
        'one week from today': [moment(), moment().add(1,'w')]
    }    

选择时间范围的时候先只选开始的日期，不选择结束的日期。（这是最重要的步骤）    

此时点击快捷range   ['one week from today'] 

值改变了，但是日期选中面板没有改变。

eg： 今天为5.23日

只选择开始 日期： 5.10日

此时点击 'one week from today'

日期范围的值改变了。但是日期面板 此时 仍是 选择 5.10日，没有选择结束日期，面板内的提示记录是上一次的。

### What is expected?
日期面板此时日期 应该选中的是 5.23【@primary-color背景】5.30【@primary-color背景】，中间的日期均为@primary-color边框。原先的选中开始日期的操作，以及与操作相关的记录失效。

### What is actually happening?
日期范围的值改变了。但是日期面板 面板内的提示记录是上一次的。

**Comment by afc163** [comment]
Your reproduction link is not reproducible for people.

**Comment by benjycui** [comment]
This works fine in official demo https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges

**Comment by xyy94813** [comment]
i has upgrade the lastest version of antd.

i found every thing is ok, 

so , the bug has been resolved in the lastest version (2.10.2).
