### ISSUE TITLE
Add New for TreeSelect

### ISSUE THREAD

**Issue by yarnball** [ant-design/ant-design#6229]
### What problem does this feature solve?
Allows user to use new values using TreeSelect . I think this would be a big enhancement for an already great project.

### What does the proposed API look like?
Instead of `Not Found`, it would allow the user to create a new value in the tree. It could go under a generic 'none' heading, or even better, it could be added under a node of choice. Screenshot provided.

![screen shot 2017-05-23 at 1 19 50 pm](https://cloud.githubusercontent.com/assets/13043067/26337229/a030d1ac-3fba-11e7-8d36-ba6afbab49e5.jpg)

**Comment by benjycui** [comment]
I can understand if you want to add nodes to Tree dynamically.

But I don't understand why you need to add nodes to TreeSelect.

**Comment by yarnball** [comment]
What I mean, is to add it `inside` that node. Here it is another screenshot to explain:
![screen shot 2017-05-23 at 7 58 34 pm](https://cloud.githubusercontent.com/assets/13043067/26349141/47ea9cac-3ff2-11e7-85bb-28cbedbc64c1.jpg)

**Comment by benjycui** [comment]
> But I don't understand why you need to add nodes to TreeSelect.

**Comment by afc163** [comment]
It is way out of TreeSelect's job, I am afraid we won't do it.

**Comment by yarnball** [comment]
How about just "Adding" in general (ie not with the custom Node levels?
