### ISSUE TITLE
Can Cascader options label definition support React Node for search?

### ISSUE THREAD

**Issue by dlut-chong** [ant-design/ant-design#6231]
### What problem does this feature solve?
When using Cascader and expect the Cascader label can display more than just a string type text(e.g. a ToolTip to show more info about this label option), then we also expect the Cascader can support the showSearch function as same as when using the string type text as the label definition.

### What does the proposed API look like?
We expect when using the showSearch function of Cascader, it can extract one agreed prop(e.g. labelValue) of the React Node as the label value.
```javascript
const options = [
    {
        value: 'someValue',
        label: <ToolTip labelValue='labelValue' />,
    }
]
return <Cascader options={options} showSearch />
```

**Comment by benjycui** [comment]
What is your use case?

It's weirdo to show a Tooltip in Cascader

**Comment by dlut-chong** [comment]
We are using Cascader to show the feature's cn_name from different categories, and when hovering on the Cascader option, we expect a Tooltip showing feature's en_name and its data_type. The options looks like as below
```javascript
const options = [
    {
        value: 'category_1',
        label: '特征分类一',
        children: [
            {
                 value: 'en_name',
                 label: <Tooltip trigger={['hover']} title={en_name + ' | ' + data_type}>
                            {cn_name}
                        </Tooltip>
            },
            ...
        ]
    },
    ...
]
```
Currently I have overridden the filter and render function of showSearch props to implement our expected style. And I am also considering whether this requirement is a high-frequency one. Nevertheless, looking forward to your viewpoints about this kind of use case requirement.

**Comment by benjycui** [comment]
This should work, but you need to customized `showSearch.filter|render|sort`

```jsx
import { Cascader } from 'antd';

const options = [{
  label: <span>Hello</span>,
  value: 'hello'
}];

function filter(inputValue, path) {
  return true;
}

function render(inputValue, path) {
  return path[0];
}

function sort() {
  return 0;
}

function displayRender(label) {
  return label[0];
}

ReactDOM.render(
  <Cascader
    displayRender={displayRender}
    showSearch={{ filter, render, sort }}
    options={options}
  />,
  mountNode
);
```
