### ISSUE TITLE
BackTop 无法使用

### ISSUE THREAD

**Issue by icowan** [ant-design/ant-design#6234]
# BackTop无法使用

部份代码:

```
import {BackTop} from 'antd'
render(){
return (
            <span>
                
                <div>
                    Hello async
                    <BackTop />
                </div>
            </span>
        );
}
```
页面比较长屏幕已滚到底，就是没有显示

**Comment by icowan** [comment]
![](http://source.lattecake.com/images/2017/05/36/3e/09/42/20170523-456f4e977c0899c406be87203ed88fc842a368d6.jpeg?imageView2/2/w/1280)
并没有显示 也没有报错。

**Comment by duzitengg** [comment]
target={() => document.getElementById('backTop')
加上这个属性，但是react 16.1.0会报警告，不知道为什么，我也提出了这个问题，目前还没人解决！

**Comment by afc163** [comment]
@duzitengg trace https://github.com/ant-design/ant-design/issues/5377

**Comment by mudenglong** [comment]
如果页面中没有加入 backTop相关dom元素，可能是默认插入的节点问题，可以如 @duzitengg 说的， 找一个可以出滚动的dom节点， target 指向那个dom id。
<BackTop target={() => document.getElementById('backWrapId')} />

**Comment by wx1993** [comment]
> target={() => document.getElementById('backTop')

少了右括号：target={() => document.getElementById('backTop')}

**Comment by duzitengg** [comment]
> > target={() => document.getElementById('backTop')
> 
> 少了右括号：target={() => document.getElementById('backTop')}

应是我复制的问题，这种明显的错误编辑器都能提示
