### ISSUE TITLE
日期选择框点击此刻返回moment对象中的时间多加了8个小时

### ISSUE THREAD

**Issue by collinsyu** [ant-design/ant-design#6236]
### Version
2.10.2

### Environment
谷歌浏览器，你们antd官网上面就是

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
打开ant.design官网→→再打开组件→→再点击DAtePicker组件→→再点击第二例第二个例子中的第一个框（呼出调试）→→点击此刻，打印出日期发现多了8个小时。

### What is expected?
希望点击此刻的时候返回的moment对象中的时间不要多加8个小时

### What is actually happening?
点击此刻的时候返回的moment对象中的时间多加8个小时

---
虽然你们封装了返回格式化后字符串，这个是准确的，但是  放在form表单的时候，我如果用了form.getca****等方法的时候回调能取到的是value,我在格式化value，也不能兼容  点击此刻，和直接点击日期，一个返回多8个小时，一个返回准确，时区不同吧估计是，我开始解决想的是减掉8个时区，结果点击此刻正常了，再直点日期的时候也减少了8小时，不正常！最后此路不通，只能是每个日期组件绑了onchange设置了state！

重现连接不需要，你们打开ant页面官网，就能发现，去看DAtepicker组件的第四个例子的第一个框，点此刻试试吧

**Comment by benjycui** [comment]
你所在的时区是？

**Comment by collinsyu** [comment]
@benjycui   我开始是这样修改的
 obj.startTime = moment(obj.startTime._d).utc().utcOffset(0).format('YYYY-MM-DD HH:mm')，这个时候点击此刻正常了，但是直接点击日期确定，之后 时间减少了8小时

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
官网例子我没看到有问题，请提供可重现 demo

**Comment by benjycui** [comment]
这个问题的根本原因在于时区的设置，我这边是北京时间，没问题。

**Comment by collinsyu** [comment]
@benjycui        https://riddle.alibaba-inc.com/riddles/df478238

**Comment by afc163** [comment]
感觉确实有问题。

@collinsyu 尽量不要贴内网链接，可以用 codepen 来重现。

**Comment by benjycui** [comment]
[捂脸] 我这边这的无法重现

**Comment by afc163** [comment]
http://codepen.io/anon/pen/GmzvKB?editors=0010

**Comment by afc163** [comment]
@collinsyu ?

**Comment by ansenAC** [comment]
昨天发现的问题，日期选择24 26 然后用 date[1].diff(date[0], 'days')返回1 跟了一下代码发现两个时间戳相差 172799（2 * 24 * 60 * 60 两天的标准时间差是172800），然后内部又执行了Math.floor(1.99)就变成了一天。 地点：北京

**Comment by benjycui** [comment]
@ansenAC 在线 demo 和重现步骤

**Comment by benjycui** [comment]
ping @ansenAC @collinsyu

**Comment by warmhug** [comment]
貌似 “此刻” 的计算方式不对？加了 `_offset: 480` 时区差？

**Comment by afc163** [comment]
https://github.com/react-component/calendar/blob/8d589b7a72b32056f3366aea3cc34f900152a60f/src/util/index.js#L17

**Comment by benjycui** [comment]
@afc163 你 CodePen 中的使用方式有问题吧：

```jsx
moment(fieldsValue.datePicker._d).format('YYYY-MM-DD HH:mm')
```

这样把时区给丢了，格式化后的时间不对也正常。

**Comment by afc163** [comment]
为啥两个时间会有区别呢？

**Comment by benjycui** [comment]
简单总结为：

1. 因为点击 今天/现在 那个按钮时，moment 对象会经过 [getTodayTime](https://github.com/react-component/calendar/blob/8c63907d9fbbe39bf7e1bc148b502d105f3fb014/src/util/index.js#L17) 设置了 `utcOffset`
1. `utcOffset` 会把 moment 对象的 `_isUTC` 设为 `true` 并设置 `_offset`

而点击日期面板时的 moment 对象没有经过类似的处理，所以其实点击日期面板和 今天/现在 按钮时得到的 moment 对象其实是略有不同的。

```jsx
// 日期面板 moment 对象
{
  _isUTC: false,
}

// 现在、今天按钮的 moment 对象
{
  _isUTC: true,
  _offset: 480,
}
```

**Comment by benjycui** [comment]
所以 @afc163 的 CodePen 中的用法，把时区扔了，最终的值自然不一样。

技术上可以做到保证日期面板中的 moment 对象也是 `_isUTC: true`，但是感觉没必要，毕竟 @afc163 在 CodePen 中的用法为 invalid。

如果除了 @afc163 的用法外，没有其他合理的使用场景并能重现该问题的话，我觉得还是可以忽略这个 issue 了。毕竟这两种不同的 moment 对象之间运算、格式化等操作时，moment 自身会去处理差异，我们不用关心。

**Comment by afc163** [comment]
确实 codepen 里的用法很奇怪。

直接如下就没有问题了：

```diff
- alert(moment(fieldsValue.datePicker._d).format('YYYY-MM-DD HH:mm'))
+ alert(fieldsValue.datePicker.format('YYYY-MM-DD HH:mm'))
```

@collinsyu

**Comment by collinsyu** [comment]
原来，谢谢，我这样使用就好了
