### ISSUE TITLE
tabs标签页切换时被隐藏的为什么不用display=none

### ISSUE THREAD

**Issue by iceking112** [ant-design/ant-design#6237]
### Version
2.10.2

### Environment
window 10，chrome 58

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
如果tabpanel中的元素存在    position: fixed   的情况，当切换标签页后该元素实际上并没有被隐藏，在当前tab页面仍然可以点击到。

### What is expected?
切换标签页后，其他标签页彻底隐藏

### What is actually happening?
其他标签页中的内容仍然能被点击

**Comment by afc163** [comment]
> tabs标签页切换时被隐藏的为什么不用display=none

因为有动画效果。

> tabpanel中的元素存在 position: fixed

感觉不合理。`position: fixed` 的元素应该放到 Tabs 容器外。

**Comment by iceking112** [comment]
https://ant.design/components/tabs-cn/#components-tabs-demo-card
卡片式标签是没有动画的
关于position:_ fixed 的元素应该放到 Tabs 容器外
是因为在做后台管理系统，用tab来保存多页面展示的，每一个tab中存放的是整个route页面，很难限制里面一定不能用position: fixed

**Comment by afc163** [comment]
Card 会隐藏的。http://codepen.io/anon/pen/OmrajE?editors=0010

**Comment by iceking112** [comment]
@afc163 
http://codepen.io/mile112/pen/EmGGjm?editors=0010
我做了一点修改，把fix内容换成了button，添加了css  cursor:'pointer'，可以看到即使我进入别的tab，把鼠标移过去任何会出现小手的

**Comment by benjycui** [comment]
@afc163 或者我们可以把不展示的 TabPane 设置为 `visibility: hidden;`?

@iceking112 测试下你的场景这样能否解决问题，可以的话来个 PR

**Comment by afc163** [comment]
d6da30573bddc8695370671c95717e9bf9bba40c 已经足够了。

**Comment by iceking112** [comment]
visibility: hidden;
point-event: none
都可以解决
