### ISSUE TITLE
官网demo部署后页面indexpage的图片请求不到

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#6238]
### Version
2.10.2

### Environment
mac

### Reproduction link
[http://120.76.194.221/testdemo/#/?_k=1f8725](http://120.76.194.221/testdemo/#/?_k=1f8725)

### Steps to reproduce
http://120.76.194.221/testdemo/#/?_k=1f8725

### What is expected?
图片可以看见

### What is actually happening?
看不见

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/26343672/76e4bba0-3fcf-11e7-8234-0b9b647f5b32.png)

**Comment by SynChron1zed** [comment]
请求yay.图片地址 static前面应该有根目录

**Comment by SynChron1zed** [comment]
这个是项目搭建好 后直接打包的 没有任何更改 以前都没有问题

**Comment by SynChron1zed** [comment]
图片不管是放在assest里面 还是 public里面 都会这样 会少根目录 但是 css js文件并没有少

**Comment by yesmeck** [comment]
https://github.com/dvajs/dva-cli/issues
