### ISSUE TITLE
Layout component:  Sider is showing unnecessary icons beside the menu item icons when collapsed

### ISSUE THREAD

**Issue by whizkidwwe1217** [ant-design/ant-design#6240]
### Version
2.10.2

### Environment
Chrome, Edge

### Reproduction link
[http://codepen.io/whizkidwwe1217/pen/JNweVJ?editors=0010](http://codepen.io/whizkidwwe1217/pen/JNweVJ?editors=0010)

### Steps to reproduce
I used the sample in the Layout component section: [https://ant.design/components/layout/#components-layout-demo-side](https://ant.design/components/layout/#components-layout-demo-side)

### What is expected?
There should be no extra icons on the right side of the menu item's icon when the Sider is collapsed as demoed on the documentation.

### What is actually happening?
There's an angle bracket icon (>) and ellipsis (...) icon showing beside the Sider menu item icon when the Sider is collapsed. See image below:
![https://c1.staticflickr.com/5/4270/34677258902_8710672380_z.jpg](https://c1.staticflickr.com/5/4270/34677258902_8710672380_z.jpg)

**Comment by benjycui** [comment]
You should remove text while collapse:

```diff
title={
  <span>
    <Icon type="user" />
-  <span className="nav-text">User</span>
  </span>
}
```

**Comment by TracyDa** [comment]
You need read the demo from the [this](https://ant.design/components/layout/), maybe you can use css to do this trick:


```
.ant-layout-sider-collapsed .nav-text {
    display: none;
}

.ant-layout-sider-collapsed .ant-menu-submenu-vertical > .ant-menu-submenu-title:after {
    display: none;
}
```

**Comment by pradipkakade** [comment]
getting some unnecessary text or ... while collapsing antd sider layout
