### ISSUE TITLE
校验规则能否根据业务需求来

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#6241]
### What problem does this feature solve?
在form中 有的选项会肯定用户选择的值来显示与隐藏。希望有的选项在显示的时候 进行校验，隐藏的时候就不进行校验了。灵活一点

### What does the proposed API look like?
if(满足条件){//some code}else{//什么都不做 可以跳过校验}

**Comment by benjycui** [comment]
See: https://ant.design/components/form/#components-form-demo-dynamic-rule
