### ISSUE TITLE
mapPropsToFields方法导致验证出错

### ISSUE THREAD

**Issue by qianduanMortal** [ant-design/ant-design#6242]
### Version
2.10.2

### Environment
系统win7,浏览器最新版chrome

### Reproduction link
[http://codepen.io/504236694/pen/XRoOJY?editors=1111](http://codepen.io/504236694/pen/XRoOJY?editors=1111)

### Steps to reproduce
按照官方文档第一个登录示例验证表单。
当input中的字段是从state中获取的时候（mapPropsToFields联动input和state），验证失效，捕获到的错误信息为undefined。

### What is expected?
期望能正常验证。

### What is actually happening?
验证失效。

**Comment by qianduanMortal** [comment]
实际上， state改变=》props改变=》value改变，会导致整个表单重置，这个是为什么呢？

**Comment by benjycui** [comment]
See: https://ant.design/components/form/#components-form-demo-global-state

`field` 和 `value` 是两个不同的概念。
