### ISSUE TITLE
When filter is taller than table, filter is cropped

### ISSUE THREAD

**Issue by TsuryKnox** [ant-design/ant-design#6245]
### Version
2.10.2

### Environment
OS X

### Reproduction link
[https://i.imgur.com/gHQuBCE.png](https://i.imgur.com/gHQuBCE.png)

### Steps to reproduce
Create a table with items
Create a big filter with many items
Filter the table such that there will be no items shown and the table will be less tall than the filter itself

### What is expected?
The filter window is fully shown

### What is actually happening?
The filter window is cropped and you cannot reset the filter
See example here: https://i.imgur.com/gHQuBCE.png

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/commit/42c36655175ca7facdedbde7daff033c58dab2ea

@afc163 @yesmeck we can expose `columns[n].getFilterDropdownContainer` to solve this issue.

Or encourage user to implement their own filterDropdown in edge case: https://github.com/ant-design/ant-design/issues/6172

**Comment by afc163** [comment]
The reason is that `.ant-table` has `overflow: hidden`.

**Comment by TsuryKnox** [comment]
The fix only partially works. When the filter is tall enough it is cut yet again.
https://i.imgur.com/MOCRhcx.png
