### ISSUE TITLE
get info of the checked treenodes

### ISSUE THREAD

**Issue by iamhanson** [ant-design/ant-design#6246]
### What problem does this feature solve?
A lot of source data is more complex, nested child nodes (such as the provincial, city, district), at the time of initialization only gives the node id, this time if you want to obtain the title of the selected node is difficult, although can be obtained by traversing, but if the component provides a method for selecting node id and the title is very convenient.

### What does the proposed API look like?
1、Tree.getCheckedNodes()
2、onLoaded=()=>{...}

**Comment by benjycui** [comment]
You can just flatten your tree to:

```jsx
const map = {
  [key]: title
};
```

**Comment by benjycui** [comment]
`antd` focus on UI, not data.
