### ISSUE TITLE
TreeSelect 选择框的内容可以开放出来吗？

### ISSUE THREAD

**Issue by PWDream** [ant-design/ant-design#6249]
### What problem does this feature solve?
因为我们的场景是要求文本框显示的节点和树上显示的节点样式和文本都不一样，文本框的节点要求我们自定义

### What does the proposed API look like?
你们自定义，开放出来就好

**Comment by benjycui** [comment]
只是样式的话，用 CSS 覆盖就好。

**Comment by PWDream** [comment]
@benjycui 我们的设计是这样的
![Uploading image.png…](),但是我去改变选择框中的值得时候，下面树节点的值也跟着改变了
![Uploading image.png…]()，有没有只改变选择框中的值，而树的节点不改变呢？谢谢

**Comment by PWDream** [comment]
@benjycui 我们的设计是这样的
![qq20170524-140330](https://cloud.githubusercontent.com/assets/4903755/26388976/1b679534-408a-11e7-9c5c-5b6a94265d67.png)


但是我去改变选择框中的值得时候，下面树节点的值也
跟着改变了
![qq20170524-140225](https://cloud.githubusercontent.com/assets/4903755/26388985/27ecd062-408a-11e7-9176-b17ad8418f48.png)

有没有只改变选择框中的值，而树的节点不改变呢？谢谢

**Comment by warmhug** [comment]
不太确定、好像记得支持，仔细看下 rc 组件 demo

**Comment by benjycui** [comment]
Try [treeNodeLabelProp](https://ant.design/components/tree-select/#Tree-props)

**Comment by PWDream** [comment]
I have try it , but not work

**Comment by PWDream** [comment]
@warmhug 我已经仔细看过了，还是改不掉，能不能把选择框中的值开放出来我们自定义？

**Comment by yesmeck** [comment]
可以哦 https://codesandbox.io/s/W7yV82A9n 选 `parent 1-0`。
