### ISSUE TITLE
Table filter research when not result can't show 确认&重置 button

### ISSUE THREAD

**Issue by qiaolevip** [ant-design/ant-design#6251]
### Version
2.10.2

### Environment
 browser version

### Reproduction link
[https://cloud.githubusercontent.com/assets/996755/26386003/3d2b62d0-4009-11e7-8075-83707ba303cd.png](https://cloud.githubusercontent.com/assets/996755/26386003/3d2b62d0-4009-11e7-8075-83707ba303cd.png)

### Steps to reproduce
1,Load table data
2,Filter on column without any data
3,Re-filter column can't show bottom button.

### What is expected?
When no result show function button on table filter.

### What is actually happening?
No result can't click function button on table filter.

---
Preview Bug on：
https://cloud.githubusercontent.com/assets/996755/26386003/3d2b62d0-4009-11e7-8075-83707ba303cd.png

Solved method:
1,Up filter index
2,Set long table height

**Comment by qiaolevip** [comment]
![screenshot from 2017-05-24 11-39-00](https://cloud.githubusercontent.com/assets/996755/26386003/3d2b62d0-4009-11e7-8075-83707ba303cd.png)

**Comment by yesmeck** [comment]
Duplicated of #6245
