### ISSUE TITLE
Select mode=‘multiple’   showSearch={false} is failure

### ISSUE THREAD

**Issue by LOVECYF** [ant-design/ant-design#6253]
### Version
2.9.0

### Environment
win7 chrome

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
<Select
      mode={'multiple'}
     allowClear
      showSearch={false}
      >
     {this.props.schoolTypes.map((value, index) => {
                                            return <Option key={value.id}>{value.name}</Option>
     })}
 </Select>

### What is expected?
select is multiple and is can not enter

### What is actually happening?
select is multiple but can enter

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/26391693/4e3f4b30-4096-11e7-9425-ed2d626c99f6.png)

**Comment by LOVECYF** [comment]
我知道这个配置是默认的false  但为什么select设置为多选时 还是可以输入值？ 没有配置项可以让它变成类似单选时的那种不可输入状态嘛？

**Comment by LOVECYF** [comment]
查看了源码   showSearch 这个配置只在单选时才会去判断，多选时react-component中select没判断showSearch这个配置。  确认后 没问题的话 antd的文档说明应该补充下啊。

**Comment by benjycui** [comment]
我之前理解错了。

@warmhug @yiminghe 这个需要统一下么？

**Comment by warmhug** [comment]
antd 里英文文档描述是对的、中文不对。。
不过这个也算是功能缺失，tree-select 也碰到过类似需求，只能比较 hack 地在多选下 ref 到 input 设置 disabled 、来禁止多选搜索 https://github.com/react-component/tree-select/commit/c6880b874dc5e469580179aa6591c835ed90e090

**Comment by afc163** [comment]
先按英文描述统一。

**Comment by qingfengmy** [comment]
多选禁止输入怎么处理？强行设置input为disabled会有select无法失焦的问题，select收起貌似是在失焦时处理的，最后导致select无法收起

**Comment by belief-cyf** [comment]
handleOnFocus () {
        document.getElementsByClassName('hide-searchSelect')[0].getElementsByClassName('ant-select-search__field')[0].setAttribute('readOnly', 'readOnly');
    }

![image](https://user-images.githubusercontent.com/19991842/28659355-bfff01f2-72e1-11e7-8dd2-99575dd1e1cd.png)

这是我目前采用的笨方法

**Comment by belief-cyf** [comment]
@qingfengmy

**Comment by superopengl** [comment]
> handleOnFocus () {
> document.getElementsByClassName('hide-searchSelect')[0].getElementsByClassName('ant-select-search__field')[0].setAttribute('readOnly', 'readOnly');
> }
> 
> ![image](https://user-images.githubusercontent.com/19991842/28659355-bfff01f2-72e1-11e7-8dd2-99575dd1e1cd.png)
> 
> 这是我目前采用的笨方法 @qingfengmy

The keyboard still pops up when the first time it gets focus. My workaround is a little bit more verbose, but working as expected.

```js
constructor(props) {
    super(props);
    this.hasHackedSelect = false;
}

componentDidUpdate() {
    if(this.hasHackedSelect) return;
    const filterNode = document.getElementById('statusFilter'); // Use ID to label the target component.
    if(filterNode) {
        const inputs = filterNode.getElementsByClassName('ant-select-search__field');
        if(inputs && inputs.length) {
            inputs[0].setAttribute('readOnly', 'readOnly')
            this.hasHackedSelect = true;
        }
    }
}
```

**Comment by pandaomeng** [comment]
> handleOnFocus () {
> document.getElementsByClassName('hide-searchSelect')[0].getElementsByClassName('ant-select-search__field')[0].setAttribute('readOnly', 'readOnly');
> }
> 
> ![image](https://user-images.githubusercontent.com/19991842/28659355-bfff01f2-72e1-11e7-8dd2-99575dd1e1cd.png)
> 
> 这是我目前采用的笨方法 @qingfengmy

多谢，刚好有需要的场景
