### ISSUE TITLE
Component Transfer use Array.prototype.includes method, throw exception in 360 browser

### ISSUE THREAD

**Issue by akecn** [ant-design/ant-design#6254]
### Version
2.10.2

### Environment
windows、360 browser latest version（最新的360浏览器极速版）

### Reproduction link
[http://codepen.io/wuake/details/BRMVZz/](http://codepen.io/wuake/details/BRMVZz/)

### Steps to reproduce
使用 极速版 360 浏览器 访问上述提供的重现链接，打开控制台可见。

### What is expected?
component available

### What is actually happening?
throw exception：xx.includes is not function，component unavailable.

---
目前 360浏览器最新版本内核是 chrome 45，不支持 array.prototype.includes。
所以我的理解 2.10.0 升级到 2.10.1/2 是不兼容的升级。。。。。

**Comment by benjycui** [comment]
https://ant.design/docs/react/getting-started-cn#兼容性
