### ISSUE TITLE
date-picker  不能重置样式？

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#6256]
### Version
2.10.2

### Environment
浏览器

### Reproduction link
[https://github.com/qq645381995/antdDemo](https://github.com/qq645381995/antdDemo)

### Steps to reproduce
git clone 后 yarn  下载依赖  然后 yarn start 启动服务

### What is expected?
重置能重置所有组件的样式

### What is actually happening?
button样式修改了 但是 date-picker 没有改变 还是原来的样式

**Comment by afc163** [comment]
啥样式没改？

<img width="363" alt="image" src="https://cloud.githubusercontent.com/assets/507615/26402373/ab60cb4c-40bc-11e7-8fe2-f2335269b088.png">
