### ISSUE TITLE
 table 指定expandedRowKeys后会导致其他的折叠按钮无法展开与回缩

### ISSUE THREAD

**Issue by Jaware** [ant-design/ant-design#6257]
ant 2.10.2

table 指定expandedRowKeys后会导致其他的折叠按钮无法展开与回缩，然后我们试了defaultExpandedRowKeys也只会在首次加载起作用，后续修改该属性的state也没用，
这两个地方是bug吗，我们想实现添加一个子节点后自动展开的效果

**Comment by yesmeck** [comment]
According to you question, you need use `onExpand` to change the `expandedRowKeys` like input's value.

**Comment by Jaware** [comment]
not bug? 能不能让 表格设置了expandedRowKeys后可以折叠与展开呢，这个体验感觉好些  @yesmeck

**Comment by afc163** [comment]
自行研习受控组件概念：http://facebook.github.io/react/docs/forms.html#controlled-components
