### ISSUE TITLE
Tabs中更新state

### ISSUE THREAD

**Issue by Sunny-L** [ant-design/ant-design#626]
callback:function(){
        console.log('tab被点了...')
        this.setState({
            tabId:'1'
        })
    },
    render:function(){
        return (
            <div>
                <Tabs defaultActiveKey="1" onTabClick={this.callback}>
                    <TabPane tab="选项卡一" key="1">选项卡一内容</TabPane>
                    <TabPane tab="选项卡二" key="2">选项卡二内容</TabPane>
                    <TabPane tab="选项卡三" key="3">选项卡三内容</TabPane>
                </Tabs>
            </div>
        )
    }

版本号0.10.4  调用onTabClick或者onChange更新state都会失效，需要加一个异步操作 setTimeout才能hack

**Comment by benjycui** [comment]
如果你是说，`onTabClick` `onChange` 调用后，`state` 没有立刻更新的话，你可以看一下这 [文章](http://zhuanlan.zhihu.com/purerender/20328570)。

另外，`this.callback` 不应该手动调用的吧。

**Comment by Sunny-L** [comment]
我的意思是在onTabClick或者onChange方法中调用setState方法后组件tab不能移动，把setState放在setTimeout里才ok

**Comment by benjycui** [comment]
上具体代码看看吧。Fork 下面这个代码进行重现。

http://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by Sunny-L** [comment]
重现：
http://jsfiddle.net/sunny303/6mhg6jt3/6/

**Comment by benjycui** [comment]
一开始时是这样的：

![image](https://cloud.githubusercontent.com/assets/3580607/11555077/769ee358-99d8-11e5-8f1f-33a14ae9e25a.png)

然后点击一下 “选项卡二”，这时 `Tabs` 内部已经调用了 `setState({activeKey: '2'})`，同时触发了 `Hello` 的 `onTabClick` / `onChange` 事件，但 React 并 [不会立刻更新](http://zhuanlan.zhihu.com/purerender/20328570) `Tabs` 的 `state`。

也就是说，在 `Tabs` 的 `state` 更新之前，就触发了 `Hello` 的 `onTabClick` / `onChange` 事件，并调用了 `Hello` 的 `setState`，并触发了 `Hello` 的 re-render，进而触发了 `Tabs` 的 re-render，但这个时候 `Tabs` 的 `state` 还是 `{activeKey: '1'}`，所以看起来就像是不动。

以上。应该是这样吧 @yiminghe :b

**Comment by benjycui** [comment]
说白了就是在 ownee 里触发 owner 的 `setState` 会有坑，真要这么做的话，可以参考这个 [例子](https://github.com/react-component/tabs/blob/master/examples/activeKey.js#L65)，owner 传递新的属性值给 ownee。

**Comment by yiminghe** [comment]
fixed: https://github.com/react-component/tabs/commit/cf4f040ec8a0df64c6a349379a72b14586e22df6

清缓存刷新：
http://jsfiddle.net/yiminghe/atk6p31u/
