### ISSUE TITLE
setFieldsValue没法设置Switch，单复选框，有值但是样式没有改变

### ISSUE THREAD

**Issue by walkinMrwang** [ant-design/ant-design#6261]

**Comment by walkinMrwang** [comment]
handleClick() {
        const data = {'aaa': true,'bbb': true,}
        this.props.form.setFieldsValue(data)
    }
    render() {
        const { getFieldDecorator } = this.props.form
        return (
            <Form onSubmit={this.handleSubmit.bind(this)}>
                <FormItem  >
                    {getFieldDecorator('aaa')(<Switch />)}
                </FormItem>
                <FormItem>
                    {getFieldDecorator('bbb')(<Checkbox>是</Checkbox>)}
                </FormItem>
                <input type='submit' value='提交' />
                <button onClick={this.handleClick.bind(this)}>填值</button>
            </Form>
        );
    }

**Comment by yesmeck** [comment]
文档搜 `valuePropName`
