### ISSUE TITLE
Upgrade TypeScript to 2.3.x

### ISSUE THREAD

**Issue by w567675** [ant-design/ant-design#6263]
### Version
2.10.2

### Environment
win10  typescript@2.3.3   antd@2.10.2

### Reproduction link
[http://codepen.io/](http://codepen.io/)

### Steps to reproduce
open antd\lib\mention\index.d.ts

### What is expected?
```
export interface MentionProps {
    ...
    suggestions: Array<any>;
    ...
}
```
suggestions is required

### What is actually happening?
```
(28,22): error TS2415: Class 'Mention' incorrectly extends base class 'Component<MentionProps, MentionState>'.
  Types of property 'componentWillReceiveProps' are incompatible.
    Type '({suggestions}: { suggestions: any; }) => void' is not assignable to type '(nextProps: Readonly<MentionProps>, nextContext: any) => void'.
      Types of parameters '__0' and 'nextProps' are incompatible.
        Type 'Readonly<MentionProps>' is not assignable to type '{ suggestions: any; }'.
          Property 'suggestions' is optional in type 'Readonly<MentionProps>' but required in type '{ suggestions: any; }'.
```

the suggestions optional

**Comment by benjycui** [comment]
I can re-produce this locally when upgrade TypeScript to `2.3.x`

**Comment by benjycui** [comment]
```bash
components/mention/index.tsx(34,22): error TS2415: Class 'Mention' incorrectly extends base class 'Component<MentionProps, MentionState>'.
  Types of property 'componentWillReceiveProps' are incompatible.
    Type '({suggestions}: { suggestions: any; }) => void' is not assignable to type '((nextProps: Readonly<MentionProps>, nextContext: any) => void) | undefined'.
      Type '({suggestions}: { suggestions: any; }) => void' is not assignable to type '(nextProps: Readonly<MentionProps>, nextContext: any) => void'.
        Types of parameters '__0' and 'nextProps' are incompatible.
          Type 'Readonly<MentionProps>' is not assignable to type '{ suggestions: any; }'.
            Property 'suggestions' is optional in type 'Readonly<MentionProps>' but required in type '{ suggestions: any; }'.
components/upload/UploadList.tsx(160,20): error TS2322: Type '{ title: any; children: Element[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Tooltip> & Readonly<{ children?: ReactNode; }> & R...'.
  Type '{ title: any; children: Element[]; }' is not assignable to type 'Readonly<TooltipProps>'.
    Types of property 'children' are incompatible.
      Type 'Element[]' is not assignable to type 'ReactElement<any> | undefined'.
        Type 'Element[]' is not assignable to type 'ReactElement<any>'.
          Property 'type' is missing in type 'Element[]'.
```

**Comment by benjycui** [comment]
The problem can be re-produce in TypeScript@2.x

**Comment by snipking** [comment]
Actually it happens with @types/react@15.0.25.

Currently we back to @types/react@15.0.24 as a workaround.

**Comment by chj-damon** [comment]
this is not just happen with @types/react@15.0.25.
I'm using "@types/react": "^15.0.24" in my project and my typescript version is '2.3.2'.
here is my tsconfig.json:
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "jsx": "preserve",
        "allowSyntheticDefaultImports": true,
        "target": "es5"
    },
    "include": [
        "./**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}

I got the same error when I run the script 'webpack' and then got the same error:
`ERROR in [at-loader] ./node_modules/.2.10.2@antd/lib/mention/index.d.ts:28:22
    TS2415: Class 'Mention' incorrectly extends base class 'Component<MentionProps, MentionState>'.
  Types of property 'componentWillReceiveProps' are incompatible.
    Type '({suggestions}: { suggestions: any; }) => void' is not assignable to type '(nextProps: Readonly<MentionProps>, nextContext: any) => void'.
      Types of parameters '__0' and 'nextProps' are incompatible.
        Type 'Readonly<MentionProps>' is not assignable to type '{ suggestions: any; }'.
          Property 'suggestions' is optional in type 'Readonly<MentionProps>' but required in type '{ suggestions: any; }'.`

**Comment by snipking** [comment]
@chj-damon `^15.0.24` means any version upper `15.0.24`

Just change `^15.0.24` to `15.0.24` in your package.json and `npm remove @types/react` and `npm install`

**Comment by chj-damon** [comment]
@snipking thanks for your reply. I'll try later and tell you the result.

**Comment by mitchelldemler** [comment]
@chj-damon you can set skipLibCheck to true in your tsconfig so that your compile doesn't break on *.d.ts files.

**Comment by luanped** [comment]
Is there any reason why we can't update the typings of Mention? we just need this line instead of what is currently there `componentWillReceiveProps(props: MentionProps): void;`

**Comment by afc163** [comment]
@luanped PR is welcome~

**Comment by martinnov92** [comment]
any updates on this?
