### ISSUE TITLE
Cascader ShowSearchType api add transform function

### ISSUE THREAD

**Issue by wangking873** [ant-design/ant-design#6264]
### What problem does this feature solve?
筛选时能够根据path[]控制数据结构,从而影响界面表现。

### What does the proposed API look like?
Cascader 组件 ShowSearchType  参数增加map参数替代
https://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L243

**Comment by wangking873** [comment]
lhttps://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L243

**Comment by wangking873** [comment]
最终效果：搜索后结果 和 不搜索 界面表现一致
![1111](https://cloud.githubusercontent.com/assets/3817037/26440687/0e10c9d8-4160-11e7-9991-3b26220b7796.png)

**Comment by benjycui** [comment]
不懂你的使用场景，请详细描述。

**Comment by wangking873** [comment]
ShowSearchType 默认的搜索窗口是这样的：
![image](https://cloud.githubusercontent.com/assets/3817037/26477633/9dd14c16-41f9-11e7-9ad3-9cd628602087.png)

**Comment by benjycui** [comment]
> ShowSearchType 默认的搜索窗口是这样的：

设计如此。





> 不懂你的使用场景，请详细描述。

这个问题没有回复。

**Comment by wangking873** [comment]
使用场景：
默认map会多级筛选，我需要单独筛选一级菜单，而且下一级能选择。
如果开放map就能实现这个效果
上面2张贴图就是前后效果演示

**Comment by benjycui** [comment]
如果你的数据是 lazyLoad 的话，这个搜索是没办法做到的。

如果你是要改 Cascader 的交互甚至视觉了的话，可以自行封装 rc-cascader。

**Comment by wangking873** [comment]
@benjycui 
不改交互和视觉，只是希望map能像filter，render，sort能够自定义 就好啦。

**Comment by benjycui** [comment]
按我的理解就是改了交互，麻烦详细描述你的需求。

**Comment by wangking873** [comment]
需求是 增加一个map参数 
https://github.com/wangking873/ant-design/commit/6fc748f235de8468986dcf5570aaa07d3ca7dccb

**Comment by benjycui** [comment]
还是无法理解你的场景。

> 用户能对筛选后的数据做一些处理

这个目的是什么？
1. 如果是为了修改 onChange 拿到的值，其实完全可以在 onChange 时再做 transform，没必要提前 transform。
1. 如果是为了修改筛选后的列表的渲染行为，用 showSearch.render 就可以了。

无法理解的业务场景，即使 PR 了也不会接受，因为后面完全不知道该怎么维护。

**Comment by wangking873** [comment]
@benjycui 
目的是你说的第二点：
showSearch.render 是针对单行cascader-menu li里面的表现，无法定制数据结构，控制cascader-menu li 的行为，我的使用方法如下：
    const showSearch = {
      matchInputWidth: false,
      filter: (inputValue, path) => {
        return path[0].label.indexOf(inputValue) > -1;
      },
      render: (inputValue, path, prefixCls) => {
        return path[0].label;
      },
      transform: (option) => {
        return option.path[0];
      },
    };

**Comment by benjycui** [comment]
> 虽然官方文档说 loadData 不能和showSearch 同时使用(因为默认筛选展示整颗数的数据)，但是我只筛选第一级的数据，下一级只能根据筛选后的数据点击加载后选择,上面贴图就是前后对比效果。

所以就是修改了 Cascader 的交互了啊。。。

**Comment by benjycui** [comment]
和官方交互差异太大需求，自行基于底层的 rc-cascader 封装即可。

**Comment by wangking873** [comment]
import React from 'react';
import { connect } from 'dva';
import { Cascader } from 'antd';

class CustomerCascader extends Cascader {
  constructor(props) {
    super(props);

  }

  generateFilteredOptions(prefixCls) {
    const options = super.generateFilteredOptions(prefixCls);
    if (options.some(item => item.value === 'ANT_CASCADER_NOT_FOUND')) {
      return options;
    }
    return options.map(item => item.path[0]);
  }
}

export default CustomerCascader;

继承解决

**Comment by benjycui** [comment]
这样只要 antd 实现改了，你的系统就挂了。

**Comment by wangking873** [comment]
确实是这样，所以希望官方能提供 transform 特性。

**Comment by ibcLee** [comment]
@wangking873 您好 想问一下 只筛选第一级的数据，下一级只能根据筛选后的数据点击加载后选择, 最后是怎么解决的，因为最近也碰见了这个问题
