### ISSUE TITLE
Autocomplete connot UN-trigger the input change

### ISSUE THREAD

**Issue by swim1986** [ant-design/ant-design#6265]
### What problem does this feature solve?
I defined autocomplete options as search results, when I select the option, I don't want the input value change, but I can't achieve it by the APIs currently supplied.

### What does the proposed API look like?
Add an attribute tag which accept boolean to indicates whether the input value should change, or use the onSelect call back function, if it return false, then the input value shouldn't change.

**Comment by benjycui** [comment]
[`AutoComplete[value]`](https://ant.design/components/auto-complete/#API) is a controlled property, you can use it to clear inputed value

**Comment by swim1986** [comment]
@benjycui If I change value in onSelect call back, the input value will change to the option value first, then change to the given value, it's just not that soomthly.

**Comment by benjycui** [comment]
> AutoComplete[value] is a **controlled** property
