### ISSUE TITLE
Missing `name` property in checkbox and input-number Typescript definition

### ISSUE THREAD

**Issue by panjiesw** [ant-design/ant-design#6266]
### Version
2.10.2

### Environment
LinuxMint@18.1 React@15.5.4 Typescript@2.3.2

### Reproduction link
[http://codepen.io/panjiesw/pen/WjmZZo?editors=0010](http://codepen.io/panjiesw/pen/WjmZZo?editors=0010)

### Steps to reproduce
- import Checkbox or InputNumber from antd in a typescript source
- use it in a component

### What is expected?
Typescript user should be able to pass down name prop and other possible input props from antd input-related components (Checkbox, InputNumber, etc...)

### What is actually happening?
Can't add name property to Checkbox and InputNumber as it's not defined in typescript definition.

---
name property should be added to input-related component definition. The rc-checkbox and rc-input-number components as well as plain javascript components are also allowed to pass down input props as seen in Codepen link above.

This is required to use multiple inputs handling mentioned [here](https://facebook.github.io/react/docs/forms.html) when dealing with form manually.

**Comment by benjycui** [comment]
PR is welcomed.

**Comment by panjiesw** [comment]
PR submitted
