### ISSUE TITLE
Layout布局在IE9下样式异常

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#6267]
官方例子就会出现如题的问题：
https://ant.design/components/layout-cn/#components-layout-demo-side
![layout](https://cloud.githubusercontent.com/assets/4525647/26442630/e89d7b30-4167-11e7-8a68-a872d889a03b.png)

**Comment by benjycui** [comment]
https://ant.design/components/layout/#Component-Overview

**Comment by BorelTung** [comment]
@benjycui why not fix?
How dare you said `supports all the modern browsers and IE9+`.
https://ant.design/docs/react/getting-started#Compatibility

**Comment by benjycui** [comment]
![image](https://user-images.githubusercontent.com/3580607/29560070-72ed9eb4-8763-11e7-8938-e9bb3f371fce.png)

**Comment by BorelTung** [comment]
thx

**Comment by chengwangping** [comment]
@BorelTung  @benjycui 
ie9 兼容layout 布局

![image](https://user-images.githubusercontent.com/5220595/29657673-ebb78304-88ea-11e7-92b2-9b04df7e22a1.png)
