### ISSUE TITLE
上传组件在pc safari中不能上传，在手机，ipad中是好的？why

### ISSUE THREAD

**Issue by Jessie-D** [ant-design/ant-design#627]

**Comment by benjycui** [comment]
不提供重现步骤的 issue 都是耍流氓 😂

**Comment by Jessie-D** [comment]
上传组件Upload在pc(我的系统是window7) safari（版本5.1.7）浏览器中不能上传
 重现步骤：
1.打开pc safari（5.1.7）输入官网upload演示地址http://ant.design/components/upload/
2.点击上传组件按钮 没有反应
不过在手机、 ipad及其他浏览器上是好的

**Comment by afc163** [comment]
windows 下的 safari 苹果官方早就放弃支持了。现在 safari 本身都 9.0 了，这么早的版本我们不可能做支持的。
