### ISSUE TITLE
table组件每行可以有hover事件嘛, 鼠标移上去触发某些事件

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6270]
### What problem does this feature solve?
表格最后一列编辑按钮/下拉默认不展示, 当鼠标移动到该行时, 编辑按钮出现, 让界面更加简洁

### What does the proposed API look like?
就是 onHover 之类的吧

**Comment by yesmeck** [comment]
https://github.com/react-component/table/commit/0db582a75dfa119715eb4db8a59eacfca744c5a0 下个版本会有。

**Comment by PeaFull** [comment]
想问下这个默认的hover效果怎么去掉

**Comment by LC-shao** [comment]
如果官方没有提供接口的话. 自己改代码吧. :p


开 10 October 2017 在 10:52:55 AM, 猷 (notifications@github.com) 写到:

想问下这个默认的hover效果怎么去掉
