### ISSUE TITLE
希望新增全局loading效果，和指定组件loading效果

### ISSUE THREAD

**Issue by kevinlvhsl** [ant-design/ant-design#6271]
### What problem does this feature solve?
方便在接口请求时提醒用户是在加载中，并且在某些情况下可以禁止用户操作某些控件。
loading最好是可以分全局和局部。适用多个场景

### What does the proposed API look like?
可以单独拎出来Loading组件，可以设置状态、提示文字、和icon。
或者是可以附加在其他控件上 设置状态和icon

**Comment by afc163** [comment]
http://ant.design/components/spin/
