### ISSUE TITLE
Chrome Button inside Group doesn't lose focus

### ISSUE THREAD

**Issue by ihorml** [ant-design/ant-design#6272]
### Version
2.10.2

### Environment
MacOS Chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
1. Go to https://ant.design/components/button/
2. Click on some button inside the Button.Group
3. Move cursor out of button

We see that button is colored like light blue and has :focus style. Button doesn't lose focus after click. To make it looks normal we should click somewhere to make it lose focus.

Video (dropbox): https://goo.gl/0xVTnk

### What is expected?
1. Go to https://ant.design/components/button/
2. 2. Click on some button inside the Button.Group
3. Move cursor out of button

It should looks like default style (non :focus or :hover)

Video on Safari where it looks as expected (dropbox): https://goo.gl/RB7eVY

### What is actually happening?
In chrome Button inside Button.Group doesn't lose focus after click so it looks not normal because it has `:focus` class with light blue background.

**Comment by benjycui** [comment]
see: https://github.com/ant-design/ant-design/pull/5597
