### ISSUE TITLE
Documentation for ant tabs doesn't show how to use slide option

### ISSUE THREAD

**Issue by damiangreen** [ant-design/ant-design#6275]
### Version
2.10.2

### Environment
all

### Reproduction link
[https://github.com/ant-design/ant-design/blob/0a2fb1817f565cc79443e0bf03e893f815cab018/components/tabs/demo/slide.md](https://github.com/ant-design/ant-design/blob/0a2fb1817f565cc79443e0bf03e893f815cab018/components/tabs/demo/slide.md)

### Steps to reproduce
the demo shows left   right arrows but the code doesn't show how to achieve this

### What is expected?
some working code that shows arrows on tabs

### What is actually happening?
no code

**Comment by benjycui** [comment]
Arrows are generate automatically.
