### ISSUE TITLE
`key` prop doesn't work when there is `value` prop in Select's Option

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6278]
### Version
2.10.2

### Environment
OSX, Chrome 57

### Reproduction link
[https://codepen.io/superlxc/pen/qmwgxK](https://codepen.io/superlxc/pen/qmwgxK)

### Steps to reproduce
Click Select

### What is expected?
![6b0685bc-56fe-4614-a1b1-9d80137a388f](https://cloud.githubusercontent.com/assets/4329120/26517441/3c004fe6-42cb-11e7-98b4-9fde2325814a.png)
![bf367941-55cd-48c9-bb0b-c2913a076b8b](https://cloud.githubusercontent.com/assets/4329120/26517442/3f672092-42cb-11e7-94a6-b3ab09f47c30.png)

Both America and Canada options

### What is actually happening?
![a](https://cloud.githubusercontent.com/assets/4329120/26517444/43a0c06e-42cb-11e7-8fde-5823b36fe928.png)

Only America

**Comment by yesmeck** [comment]
It's a intended behavior.

#5242
