### ISSUE TITLE
Tabs标签页 Modal 里面表单submit 会自动跳转的问题 

### ISSUE THREAD

**Issue by shuzipeng** [ant-design/ant-design#6280]
### Version
2.10.2

### Environment
Mac os chrome

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
Tabs标签页 Modal 里面表单自带的submit ，提交后，页面会自动跳转 

### What is expected?
不自动跳转

### What is actually happening?
自动跳转到默认到页卡

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Close for can't re-produce it.
