### ISSUE TITLE
Modal中的TreeSelect组件的数据未同步更新, 但是外层TableTreeList的数据更新了, 同样都是将state设置到了prop

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6281]
### Version
2.10.2

### Environment
macos 10.12.4, yarn , webstorm2017.1.3

### Reproduction link
[http://git.oschina.net/james.yue/antd-bug1](http://git.oschina.net/james.yue/antd-bug1)

### Steps to reproduce
详细的在我这个git仓库中, 将核心部分复制到了下面:

外层的table tree中数据更新了, 即菜单管理下出现了"更新菜单"
但是点击"新建"并保存后, 在Modal中的"父级菜单"中数据没更新, 没发现有"更新菜单"这个新的节点

### What is expected?
treeselect组件中的数据更新了, 即出现"更新菜单"这个节点

### What is actually happening?
treeselect组件中的数据未更新

---
index.js是该模块入口, 包含state, 其他均为pure component, 应该不会有状态保存的啊, 在CreateModal中console.log数据是最新数据但是咋就不更新呢

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by justkuai** [comment]
就上面的的 oschina git的连接啊, 我这个需要编译的啊, 已经最小化代码量了, 给您整理了

**Comment by justkuai** [comment]
@benjycui  就上面的的 oschina git的连接啊, 我这个需要编译的啊, 已经最小化代码量了, 给您整理了

**Comment by benjycui** [comment]
构建无关的话，直接提供在线 demo 好点。

**Comment by benjycui** [comment]
尽可能的降低重现成本，才会有更多的人帮你。

**Comment by justkuai** [comment]
@benjycui   将所有代码都copy到了一个文件中了
https://codepen.io/yuechen323/pen/EmzYOE?editors=0110

**Comment by afc163** [comment]
https://codepen.io/anon/pen/YVbVdB?editors=0010

Make your new state is immutable.

```diff
-            let menusData = this.state.menus;
+            let menusData = [...this.state.menus];
```

**Comment by justkuai** [comment]
@afc163 thank you very much, i got it

**Comment by justkuai** [comment]
@afc163 but why table changed , as you said, table could not be changed, but not

**Comment by afc163** [comment]
For some compatible reason, Table have not been implemented so strictly.

**Comment by justkuai** [comment]
@afc163 tku
