### ISSUE TITLE
consider Rollup as library packer

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#6284]
### What problem does this feature solve?
Looks like Rollup fits better as packer for library. I would suggest to compare results and consider rollup as library packer.

Here are some thoughts:
https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

### What does the proposed API look like?
need to create config for rollup

**Comment by paranoidjk** [comment]
PR is welcome.

But please aware that we need more detail info such as build time, bundle size in order to make decision.

If the result shows that rollup is better for ant-design, we will consider replace webpack.

**Comment by afc163** [comment]
+1

**Comment by dsanders1234** [comment]
One will be able to do:

import { Button } from 'antd';

without requiring "babel-plugin-import" and not bring in the whole antd, since rollup facilitates tree-shaking?

**Comment by yesmeck** [comment]
We don't recommend using bundle version of antd, so I think Rollup won't reduce bundle size for projects which use antd.

**Comment by dsanders1234** [comment]
Well perhaps I gave a bad example.  It would probably be more like:

import { Button } from 'antd-button';

Or something like that.  Rollup is a bundler, so it affects how you bundle.

**Comment by yesmeck** [comment]
We don't publish separate component neither. If you are using webpack 3, you are already using tree shaking with `import { Button } from 'antd';`. The only reason we still use `babel-plugin-import` is loading style automatically.

**Comment by dsanders1234** [comment]
Well perhaps I gave a bad example.  Rollup is a bundler, so it affects how you bundle.

**Comment by jstano** [comment]
I notice when using IntelliJ that the components import from either the es or lib folder, and not the ‘antd’ file as shown above. Is that normal or am I missing something in a config somewhere?

**Comment by yesmeck** [comment]
It's a expected behavior,  I guess IntelliJ is intelligent enough to find the right file from [here](https://github.com/ant-design/ant-design/blob/master/package.json#L28-L29).

**Comment by yesmeck** [comment]
Closing since inactive.

**Comment by hosembafer** [comment]
Any updates here?
Most important thing right now is Customize Theme with new create-react-app.

I can't add "theme" property to package.json on override variables... it not working.

I think you can add simple example of how to customize theme with new React App, because right now there are no wat to build new react app with antd custom theme.

**Comment by yesmeck** [comment]
@hosembafer You can refer to https://ant.design/docs/react/use-with-create-react-app#Customize-Theme

**Comment by chalecao** [comment]
actually, i cloned ant design mobile, and change it by using rollup re-compile, you can see here: https://github.com/chalecao/preact-h5-ui (change some dynamic to make it act normal for es module import)

**Comment by cfancc** [comment]
@yesmeck actually,I'm using webpack4, and` import { Button } from 'antd';`,there's still a whole package in my bundle.js.
