### ISSUE TITLE
hasFeedback with InputNumber misplaced validated icon

### ISSUE THREAD

**Issue by shgitns** [ant-design/ant-design#6289]
### Version
2.10.2

### Environment
Windows 10, Chrome 58.0.3029.110, react 15.5.4

### Reproduction link
[https://codepen.io/anon/pen/XRwevV?editors=0011](https://codepen.io/anon/pen/XRwevV?editors=0011)

### Steps to reproduce
fill any number in InputNumber field

### What is expected?
The validated icon (green circle with V) shouldn't hide the arrows of the picker.

### What is actually happening?
The validated icon placed over the picker arrows and hides them.

---
Works OK in Select element (included in the minimal reproduction).
The width style intentionally defined as 100% because i want the field to stretch to full width.

**Comment by afc163** [comment]
It is hard to find a perfect solution, just don't use feedback for InputNumber.
