### ISSUE TITLE
建议：Calendar的showClear属性设置为用户自己设置

### ISSUE THREAD

**Issue by Xiu-Lan** [ant-design/ant-design#629]
showClear在rc-calendar脚本中，已经默认始终为true，而在datepicker脚本中，调用calendar时，又传递showClear值，且为true。
可不可以优化为在调用时增加属性showClear，根据需要设置是否可以清除？

**Comment by afc163** [comment]
为保证上层配置尽可能少和精，以及 UI 规范的一定程度上的统一性，这个属性不予开放。

若需要配置，可直接使用 rc-calendar 。
