### ISSUE TITLE
Is it possible to display a message without any icons?

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#6293]
### What problem does this feature solve?
Is it possible to display a message without any added icons? When using info/success/warning/error/loading it always adds some kind of icon on the left, and I don't want any icon; I want to be able to completely control the content of the message.

### What does the proposed API look like?
Just add a message.custom(...)

**Comment by paranoidjk** [comment]
LGTM. I will +1 for this

**Comment by benjycui** [comment]
I think this should be designer's decision..

**Comment by afc163** [comment]
I think that is our design pattern, you have to follow it.
