### ISSUE TITLE
表单如radio的值必须是字符串吗?从后端获取的对象属性是数字要如何处理呢?

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6298]
### What problem does this feature solve?
处于性能考虑mysql表内一些标识字段采用tinyint unsigned, 后端java用Integer, 当数据到了前端后也是数字, 当设置radio默认值的时候就出现设置不上的问题,  我现在对后端java的接口返回值做了处理, 声明为string类型, 感觉不太优雅, 因为好多地方都要改, 请问antd有没有参数或者我需要如何做才能解决这个问题呢

### What does the proposed API look like?
自动处理, 没api

**Comment by paranoidjk** [comment]
duplicate https://github.com/ant-design/ant-design/issues/2857
