### ISSUE TITLE
Make the dev server configurable to allow custom routes

### ISSUE THREAD

**Issue by larrxu** [ant-design/ant-design#630]
Use scenario:

(TL;DR)
1. Use Antd to create a React component.
2. In the component, have some ajax call to '/api/something'.
3. The web server can be configured to forward the URL to a separate server that handles the RESTful request.  This provides ease of development without breaking the cross-domain restrictions.

(Long version)
I want to call a RESTful API from a React component built with Antd on the dev server without violating cross-domain restrictions.  It looks like antd uses nico as the dev server, which doesn't seem to be configurable.  It would be nice if we can use an express server so that we can customize the routes to forward /api URLs to a separate RESTful server to achieve the cross-domain call on the server side.  

I can always do a 'npm build' and generate js files in dist folder, then copy the files to the RESTful server and test it there.  However, it would be nice if we can test them on-the-fly without building and deploying to the real server.

**Comment by afc163** [comment]
`nico` provide a dev server just for components development, not a dev server for buissness.

You can use [antd-bin](https://github.com/ant-tool/xtool) or [webpack-dev-server](https://github.com/webpack/webpack-dev-server/) as development tool in this situation.

**Comment by larrxu** [comment]
Thanks for replying.  It seems antd-server is using Koa as the server.  Is there an easy way to configure Koa in antd-bin from the project source code, without having to change the 'dev' script to point to my own server?

**Comment by larrxu** [comment]
It seems I can provide --proxy [rootDir] to plug in a custom rule for proxy.
