### ISSUE TITLE
Table组件的placeholder能否增加自定义功能

### ISSUE THREAD

**Issue by briefguo** [ant-design/ant-design#6300]
### What problem does this feature solve?
自己定义无数据状态，搜索结果无数据与默认无数据的呈现可以区分开

比如现在有个可拖拽上传的面板，要结合着Table组件来实现，
默认，placeholder呈现无数据状态，
拖拽到面板dragover时，希望placeholder呈现指示的拖拽区域
拖拽到面板drop后，希望placeholder呈现上传及解析的进度

### What does the proposed API look like?
<Table placeholder={string|Node}/>
比如placeholder=false, 可以不显示

虽然说，placeholder是组件的填充的默认提示语，这里让placeholder状态能改变，违背了placeholder的含义，
这里所以placeholder是借用现有组件的实现的名称，可能不准确，所以可能名称待商榷

**Comment by afc163** [comment]
1. There is no `placeholder` prop in Table.
2. You can use `<Table locale={{ emptyText: <div>empty data</div> }}` /> to set the empty text.

**Comment by briefguo** [comment]
Thanks
