### ISSUE TITLE
Transfer组件在ie9和chrome（46.0.2490.86 (64-bit)）版本中不能选中数据，报错

### ISSUE THREAD

**Issue by MrLiandMissLi** [ant-design/ant-design#6303]
### Version
2.10.2

### Environment
win7 浏览器：chrome（46.0.2490.86 (64-bit)）React：4.6.1

### Reproduction link
[https://codepen.io/madaos/pen/YVmXYY](https://codepen.io/madaos/pen/YVmXYY)

### Steps to reproduce
搭建完环境，在官网直接复制的穿梭框组件，报错。

### What is expected?
在ie9里面也可以实现穿梭框功能

### What is actually happening?
报错

**Comment by benjycui** [comment]
https://ant.design/docs/react/getting-started#Compatibility
