### ISSUE TITLE
form的hidden隐藏项如何设置呢, 用于设置编辑页的id属性

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6306]
### What problem does this feature solve?
以前用jq开发的时候, 表单都有一个hidden项用于存要编辑的数据的id, 用这个id的有无来判断是新建还是编辑, antd好像没有这个东西了啊, 那这个id存哪呢, 存state中?  setState看网上说是异步的, 也就是不能立即生效, 当Modal弹出后, 立即点 save 按钮, 那么id有可能还没set进去, 也就误认为是新建而不是更新了, 如何解决

### What does the proposed API look like?
自动

**Comment by yesmeck** [comment]
React 里 hidden input 没啥意义，把这个标记记载一个变量（或状态）里就可以了。
