### ISSUE TITLE
Error while building with latest 2.10.3

### ISSUE THREAD

**Issue by bkniffler** [ant-design/ant-design#6310]
### Version
2.10.3

### Environment
Mac OS

### Reproduction link
[none](None)

### Steps to reproduce
Install 2.10.3

### What is expected?
Should build without errors

### What is actually happening?
Throws errors while building

Module not found: Error: Can't resolve 'rc-util/es/KeyCode' in '/Users/xxx/node_modules/rc-calendar/es'
resolve 'rc-util/es/KeyCode' in '/Users/xxx/node_modules/rc-calendar/es'
There's a few more, but all are seeking for rc-util/es/xxx.

---
Did you guys forget to bump rc-utils dependency maybe? Or wrong references?

**Comment by paranoidjk** [comment]
have you tried upgrade your node_modules?

**Comment by paranoidjk** [comment]
https://unpkg.com/rc-util@4.0.4/es/KeyCode.js

**Comment by bkniffler** [comment]
I cleared it completely and reinstalled, still didn't work. Installed latest rc-util manually, now it works. Sure you got the right version in the package.json?

**Comment by paranoidjk** [comment]
have you used yarn to lock dep version?

**Comment by bkniffler** [comment]
https://unpkg.com/rc-util@4.0.1/es/KeyCode.js

Package.json has minimum 4.0.1

**Comment by Grmiade** [comment]
My build fails too when update to 2.10.3 :/

```
Module parse failed: /Users/xxx/Development/xxx/node_modules/antd/es/calendar/index.js Unterminated string constant (106:110)
You may need an appropriate loader to handle this file type.
|         var value = props.value || props.defaultValue || moment();
|         if (!moment.isMoment(value)) {
|             throw new Error('The value/defaultValue of Calendar must be a moment object after `antd@2.0`, ' + 'see: http:        }
|         _this.state = {
|             value: value,
```

There is a syntax error in the file:
```typescript
var value = props.value || props.defaultValue || moment();
if (!moment.isMoment(value)) {
    throw new Error('The value/defaultValue of Calendar must be a moment object after `antd@2.0`, ' + 'see: http:        }
_this.state = {
    value: value,
    mode: props.mode
};
return _this;
```

**Comment by bkniffler** [comment]
Can confirm @Grmiade, the es version compared to lib has an issue. Seems to be a transpilation issue, since the original looks fine. Maybe it doesn't get along with the ` characters in the string?

**Comment by catcxj** [comment]
解决rc-util版本过低导致出现“Module not found: Error: Can't resolve 'rc-util/es/createChainedFunction'”的问题。
但是下载ant design源码不会出现该问题，因为在 package.json 里面使用的是 “^4.0.1”，能获取到最近的小版本“4.0.4”。
所以各位大神没发现这个问题。

我自身项目使用的yarn管理依赖包，所以使用了一个临时解决方案：
直接修改 yarn.lock 文件内部的 rc-util 版本解决。

**Comment by bkniffler** [comment]
That should be fixed as soon as new version is published. For now, just install rc-util@latest manually @catcxj

**Comment by bkniffler** [comment]
Yes, but take care, this might get overwritten again anytime you install something!

**Comment by yesmeck** [comment]
antd@2.10.4 has released, please help us test it, thanks.

**Comment by MayasHaddad** [comment]
@yesmeck fixed 👍

**Comment by Grmiade** [comment]
@yesmeck it works for me, thanks 💪

**Comment by bkniffler** [comment]
Thanks, seems like everything discussed here is fixed!
