### ISSUE TITLE
Table: Possibility to disable expandable row per-register

### ISSUE THREAD

**Issue by lucasjsoliveira** [ant-design/ant-design#6312]
### What problem does this feature solve?
Is it possible to control wether or not the ' ' button to expand a row on a Table, controlled per item in the dataSource? if not, that would be a really nice feature and would help me in a use case.

(I have a table which have expandable rows that show another table inside of it, and one of the registers in the parent table can't have sub-items. This feature would be perfect for this case.)

### What does the proposed API look like?
I've imagined something like this in the Table API:

`<Table canExpand={(index, item) => return true; // this item can be expanded}/>`

**Comment by afc163** [comment]
I think `expandedRowKeys` is a better API and conform to react's philosophy.
