### ISSUE TITLE
error TS2304: Cannot find name 'T'

### ISSUE THREAD

**Issue by danprime** [ant-design/ant-design#6313]
### Version
2.10.4

### Environment
Windows 10, Chrome 58.0, "react": "^15.5.4", "react-scripts-ts": "2.2.0", typescript: 2.3.2

### Reproduction link
[https://github.com/danprime/antdtypescript](https://github.com/danprime/antdtypescript)

### Steps to reproduce
1. Setup A ReactJS Project: `create-react-app antdsample --scripts-version=react-scripts-ts`
2. Add ANTD `yarn add antd --save`
3. Import a Button into App.tsx `import {Button} from 'antd';`
4. Add `<Button>Test Button</Button>` within render() function.

ref: https://github.com/Microsoft/TypeScript-React-Starter

Or clone reproduction link, type npm install, then npm start.

### What is expected?
Should render the basic Create React App page with a Button labeled "Test button"

### What is actually happening?
I get a screen with the error:

Failed to compile
/mnt/c/Users/danpr/workspace/ts2/node_modules/antd/lib/table/Column.d.ts
(29,61): error TS2304: Cannot find name 'T'.
This error occurred during the build time and cannot be dismissed.

---
Here's my tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "es6",
    "target": "es6",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}
```

package.json

```json
{
  "name": "ts2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "^19.2.3",
    "@types/node": "^7.0.22",
    "@types/react": "^15.0.25",
    "@types/react-dom": "^15.5.0",
    "antd": "^2.10.4",
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "react-scripts-ts": "2.2.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  }
}
```

**Comment by jch254** [comment]
I'm getting this too after upgrading to antd 2.10.4. It wasn't happening with antd 2.10.1.

The default export in the lib/table/Column.d.ts file has changed which TS complains about.

2.10.1

```
export default class Column<T> extends React.Component<ColumnProps<T>, React.ComponentState> {}
```

2.10.4
```
declare const Column_base: React.ComponentClass<ColumnProps<T>>;
export default class Column<T> extends Column_base {}
```

**Comment by benjycui** [comment]
We haven't change [the default export of column](https://github.com/ant-design/ant-design/blob/f4312895d66c168407323824c5ee4566c70ec0b4/components/table/Column.tsx#L27).

But we had upgrade TypeScript to 2.3.x, so could you try to upgrade TS to 2.3.x?

**Comment by danprime** [comment]
Already was using Typescript 2.3.2

**Comment by danprime** [comment]
Just upgraded to typescript 2.3.4 and still have the same problem.

**Comment by benjycui** [comment]
It's TypeScript's issue, I try to downgrade TypeScript ot 2.2.x, the compiled result:

```jsx
export default class Column<T> extends React.Component<ColumnProps<T>, React.ComponentState> {
}
```

**Comment by benjycui** [comment]
I will try to find more info. But if we cannot solve this issue, I think we need to downgrade to TypeScript@2.2.x

**Comment by benjycui** [comment]
@yesmeck

**Comment by manweill** [comment]
@benjycui  I have same problem whatever in  typescript@2.2.x or  antd@2.10.1

**Comment by albertvazquezm** [comment]
Having the same problem. Right after upgrading from antd@2.10.0 to antd@2.10.4. Not working for me with neither TS@2.2.2 and TS@2.3.4

**Comment by benjycui** [comment]
A patch version will be released today.

**Comment by abramobagnara** [comment]
It seems that the issue has been closed by mistake.

**Comment by yesmeck** [comment]
> It seems that the issue has been closed by mistake.

This issue has been fixed, will be released soon.

**Comment by antonmedv** [comment]
Please, release.

**Comment by panjiesw** [comment]
Alternatively, while waiting the fix to be released, you can temporarily set `"skipLibCheck": true` in `tsconfig.json`.

**Comment by Forestdev** [comment]
Can confirm. I'm experiencing same issue in certain environments.

Runs fine on MacOS. Fails on CentOS docker image.

**Comment by LanGuoguo** [comment]
same issue, when to release?

**Comment by benjycui** [comment]
You can subscribe our release RSS https://github.com/ant-design/ant-design/releases.atom

**Comment by antonmedv** [comment]
In 2.11.0 no fix. =(

**Comment by yesmeck** [comment]
@antonmedv Weird, could you confirm the antd vesion?

**Comment by antonmedv** [comment]
"antd": "^2.11.0",

**Comment by antonmedv** [comment]
Sorry, it is fixed. Need to change to `"module": "es6",` as well.

**Comment by benjycui** [comment]
@antonmedv do you mean that change this following config?

```diff
// tsconfig.json
{
  "compilerOptions": {
-   "moduleResolution": "node",
+   "moduleResolution": "es6",
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true
  }
}
```

ref: https://github.com/ant-design/ant-design#typescript

**Comment by antonmedv** [comment]
Yes.
