### ISSUE TITLE
Dropdown allows multiple click before close

### ISSUE THREAD

**Issue by 0x7b1** [ant-design/ant-design#6314]
### Version
2.10.4

### Environment
browser version

### Reproduction link
[https://ant.design/components/dropdown/#components-dropdown-demo-event](https://ant.design/components/dropdown/#components-dropdown-demo-event)

### Steps to reproduce
When mouse is hover in the dropdown example inside 'Click event' section, it is possible to click more than once a single option before this get close. In that example clicking twice fastly "1st menu item" ends showing two messages.

### What is expected?
One action by clicking a single option

### What is actually happening?
Multiple clicks by option before dropdown dimming

---
This is annoying because it potentially let make multiple actions accidentally or purposely.

**Comment by benjycui** [comment]
@afc163 maybe we can add `pointer-events: none` to animating elements.

**Comment by afc163** [comment]
That works.

**Comment by benjycui** [comment]
@0x7b1 could you try to PR?
