### ISSUE TITLE
table没有智能添加数据的单位，只能在数据上一个一个的写单位

### ISSUE THREAD

**Issue by langwuzhe** [ant-design/ant-design#6315]
### What problem does this feature solve?
如：我在table显示了 一组数据 ！小明身高：170，小红身高：160。但是我想在  170、160 后面加个单位：cm。但是查阅api貌似只能在数据里面加上 这个cm。不能直接在columns的配置项里面加一个cm，一劳永逸！

### What does the proposed API look like?
 const columns = [ {
            title: '身高',
            dataIndex: 'sg',
            key:"sg",
            unit:"cm"
        }]

**Comment by afc163** [comment]
Use `column[].render`.
