### ISSUE TITLE
Cannot find module 'enquire.js' from 'slider.js'

### ISSUE THREAD

**Issue by madHEYsia** [ant-design/ant-design#6317]
I am using Antd with React, Jest and Enzyme. While testing simple shallow rendering I am getting error 
"Cannot find module 'enquire.js' from 'slider.js'"
      at Resolver.resolveModule (node_modules\jest-resolve\build\index.js:151:17)
      at Object.<anonymous> (node_modules\react-slick\lib\slider.js:37:38)
      at Object.<anonymous> (node_modules\react-slick\lib\index.js:3:18)
![capture](https://cloud.githubusercontent.com/assets/15910703/26666736/28b66aea-46bf-11e7-8d23-593711f22c3d.JPG)
![capture](https://cloud.githubusercontent.com/assets/15910703/26666774/60139990-46bf-11e7-90e5-3ac580a04583.JPG)
![capture](https://cloud.githubusercontent.com/assets/15910703/26666788/774a3560-46bf-11e7-920e-0916ecd4b78d.JPG)

**Comment by yesmeck** [comment]
![npm](https://cloud.githubusercontent.com/assets/465125/26667345/4bcc8f10-46d7-11e7-8c72-32a0c68ea7ca.jpg)

**Comment by paranoidjk** [comment]
@yesmeck  给 ant-design-bot加一个 `upgrade_deps` 的label吧，就回复这张图 😄

**Comment by paranoidjk** [comment]
我来 PR 一个

**Comment by madHEYsia** [comment]
@yesmeck Thanks man. It worked.
