### ISSUE TITLE
`firstActiveValue` in Select

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6318]
### What problem does this feature solve?
I want to have a default value to scroll into view when there hasn't been selected anything

eg: https://codepen.io/superlxc/pen/xdeoYN
![1](https://cloud.githubusercontent.com/assets/4329120/26666907/0c17420e-46d5-11e7-93e6-4b7332d302f9.png)
When you click the Select, now it will make the first option to scroll into view.
But what i want is to make '2017' to be the first option to scroll info view.
like this:
![2](https://cloud.githubusercontent.com/assets/4329120/26666952/4eba8b2a-46d5-11e7-90fc-b20357291e21.png)
 

### What does the proposed API look like?
firstActiveValue is a value, Select will make the option which value is equal to this to scroll into view when there hasn't been selected anything

**Comment by L-x-C** [comment]
#5190 this will meet my needs

**Comment by yesmeck** [comment]
Has been released in 2.13.0
