### ISSUE TITLE
Can't override default onKeyDown event of Switch component

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#6324]
### Version
2.9.3

### Environment
All browsers

### Reproduction link
[https://codepen.io/froston/pen/NgKgox?editors=0010](https://codepen.io/froston/pen/NgKgox?editors=0010)

### Steps to reproduce
Apply onKeyDown event to Switch component

### What is expected?
Being able to override default event by my custom event.

### What is actually happening?
Can add onKeyUp event but can't override onKeyDown event.

**Comment by afc163** [comment]
What is your scene?

**Comment by froston** [comment]
I'd like to check/uncheck the Switch on pressing Enter. Now the default beahviour is right/left arrows.

**Comment by afc163** [comment]
Maybe we should implement it inside Switch.

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/26768026/6c1a0358-49d7-11e7-92cc-d41b41e829c6.png)

**Comment by benjycui** [comment]
@froston could you try to PR? Actually, I think what you want to do is make Switch support ARIA.

**Comment by yesmeck** [comment]
Keyboard has been supported in antd 3.
