### ISSUE TITLE
在Tooltip中使用Select出现问题

### ISSUE THREAD

**Issue by shenck215** [ant-design/ant-design#6329]
### Version
2.10.4

### Environment
win10，谷歌56.0.2924.87

### Reproduction link
[https://codepen.io/anon/pen/YQKvRx?editors=0010](https://codepen.io/anon/pen/YQKvRx?editors=0010)

### Steps to reproduce
在Tooltip中使用Select，选择Option时，Tooltip关闭

### What is expected?
在Tooltip中使用Select，选择Option时，Tooltip不关闭

### What is actually happening?
在Tooltip中使用Select，选择Option时，Tooltip关闭

**Comment by afc163** [comment]
https://codepen.io/anon/pen/gRYKNK?editors=0010

https://github.com/ant-design/ant-design/issues/3448
