### ISSUE TITLE
table 树形数据父子数据递归关联选择，列宽调整，列顺序拖动，行拖动

### ISSUE THREAD

**Issue by NexxLuo** [ant-design/ant-design#6333]
### What problem does this feature solve?
树形数据表格父子数据递归关联选择；
td内数据量太多时，经常会有看不完的情况，需要拖动列宽进行调整；
表格数据当列太多时需要像excel那样通过拖动列的顺序，把自己想看的数据列放置到前面显示；
行拖动主要是为了进行数据列表排序

### What does the proposed API look like?
table: {
    rowDraggable: true,
    columns: [
        {
            resizable: true,
            draggable: true
        }
    ]
}

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/4918
