### ISSUE TITLE
RangePicker render时即报错

### ISSUE THREAD

**Issue by JrIdeA** [ant-design/ant-design#6334]
### Version
2.10.4

### Environment
操作系统: macOS Sierra 10.12.5 ，操作系统语言：英文 ，浏览器版本: Chrome 58.0.3029.110 (Official Build) (64-bit)

### Reproduction link
[https://github.com/JrIdeA/antd-rangepicker-bug](https://github.com/JrIdeA/antd-rangepicker-bug)

### Steps to reproduce
打开页面即报错：
> TypeError: Cannot read property '0' of undefined
```js
  189 | } else {
  190 |     calendarHandler = {};
  191 | }
>192 | var startPlaceholder = 'placeholder' in props ? props.placeholder[0] : locale.lang.rangePlaceholder[0];
  193 | var endPlaceholder = 'placeholder' in props ? props.placeholder[1] : locale.lang.rangePlaceholder[1];
```

locale.lang 为 `undefined`

### What is expected?
页面正常显示并且 RangePicker 能够正常操作

### What is actually happening?
打开页面即报错，无法操作

---
codepen 无法复现，使用 create-react-app 创建了一个项目进行复现 https://github.com/JrIdeA/antd-rangepicker-bug，复现代码：
https://github.com/JrIdeA/antd-rangepicker-bug/commit/61db6db254341fe290debbddae2ee7441b6bfed4

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/commit/1b607baddc8996ed6f04253e28307395bf7d3d09

**Comment by benjycui** [comment]
You can use [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) to avoid this issue now.
