### ISSUE TITLE
TimePicker has unwanted default values(时间选择组件选择时带有不希望的默认值)

### ISSUE THREAD

**Issue by walking11** [ant-design/ant-design#6336]
### Version
2.10.4

### Environment
win10   Chrome58

### Reproduction link
官网的demo就是这样的 https://ant.design/components/time-picker-cn/

### Steps to reproduce
1.清空TimePicker的时间；
2.选择时间时，会有默认的选中时间,而且是11：24这种奇怪的时间（可参考下方的gif图），而非0：00这种

### What is expected?
没有默认选中的时间或者可以自定义默认选中时间

### What is actually happening?
选择时间时，会有默认的选中时间

**Comment by walking11** [comment]
![default](https://cloud.githubusercontent.com/assets/14257970/26712189/2614654c-4798-11e7-80c4-7029d343eb9b.gif)

**Comment by benjycui** [comment]
It's by design, just use TimePicker[defaultOpenValue].
