### ISSUE TITLE
Progress looks like not enough border-radius when the percent value is too small

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#6337]
### Version
2.10.4

### Environment
Win8、Chrome 57.0.2987.74

### Reproduction link
[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce
`<div style={{width:100}}><Progress percent={5} showInfo={false} /></div>`
As you see, when the width of the parent div is not so big, just 100px, and the Progress's value is just 5%, then the blue bar displays not so good, seems no border-radius or not enough radius.

### What is expected?
The blue bar has a good style just like normal conditions, with enough border-radius.

### What is actually happening?
The blue bar doesn't has enough border-radius.

**Comment by benjycui** [comment]
So, what's your expected behavior when progress's length is smaller than border-radius.

**Comment by chairui2001** [comment]
Maybe we can use a mask, just update the width of the mask, the blue bar is used only as a background. Which will be more complex, but has a better effect.

**Comment by chairui2001** [comment]
Mask is a standard rectangle, progress bar has border-radius. When progress's length is smaller the border-radius, just show a shape less than a semicircle.

**Comment by chairui2001** [comment]
Try to keep the left border-radius, but give up the right border-radius, when the percent is too small

**Comment by afc163** [comment]
Hard to find a perfect solution, I think it is better for keeping it this way now. Feel free to propose a PR if you have any good idea, Thx~
