### ISSUE TITLE
禁用 moment 的部分 locale，以减少打包大小

### ISSUE THREAD

**Issue by lewis617** [ant-design/ant-design#6338]
### What problem does this feature solve?
当我使用 DatePicker 组件时，antd 加载了 moment，我的打包大小瞬间增加了455.5k，通过可视化分析，我发现这 455.5k中有326.9k都是多余的语言包，所以我希望能够提供接口来禁用部分语言包，或指定只加载部分语言包，来减少打包大小。

![image](https://cloud.githubusercontent.com/assets/11524612/26713364/e3426b5e-479e-11e7-8294-70b254cefe82.png)

### What does the proposed API look like?
类似于：
```
import enUS from 'antd/lib/locale-provider/en_US';

return (
  <LocaleProvider locale={enUS}>
    <App />
  </LocaleProvider>
);
```

**Comment by afc163** [comment]
It is a webpack issue, not antd's.

https://ant.design/docs/react/use-with-create-react-app-cn#%E6%BA%90%E7%A0%81%E5%92%8C%E5%85%B6%E4%BB%96%E8%84%9A%E6%89%8B%E6%9E%B6

**Comment by lewis617** [comment]
Thanks, It really works. @afc163
