### ISSUE TITLE
the width of input in simple Pagination won't change when the number change

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6339]
### Version
2.10.4

### Environment
OSX, Chrome 57

### Reproduction link
[https://codepen.io/superlxc/pen/XgryzM](https://codepen.io/superlxc/pen/XgryzM)

### Steps to reproduce
change the number

### What is expected?
show whole number

### What is actually happening?
show part of the number
![123](https://cloud.githubusercontent.com/assets/4329120/26716221/325e3d74-47ab-11e7-8ff9-d5dee75e6481.png)

**Comment by benjycui** [comment]
Actually, we must set max width of the input.

The problem is: how much does the width should be.

**Comment by L-x-C** [comment]
How about not use <input> at all, could it be an <p> with contenteditable?

**Comment by afc163** [comment]
Set the input width to 3 digits width simply.

**Comment by benjycui** [comment]
How about `input=[size=3]`? See: https://stackoverflow.com/questions/1480588/input-size-vs-width

**Comment by afc163** [comment]
That is what I did.

**Comment by L-x-C** [comment]
It's not a perfect way, `size` basicly fix the width of the input, I can just override the CSS to achieve the same effect.

![image](https://cloud.githubusercontent.com/assets/4329120/26719564/a2bd9dc4-47b7-11e7-8e49-9469785dff82.png)

![image](https://cloud.githubusercontent.com/assets/4329120/26719552/965735c2-47b7-11e7-8532-db5c7f777dbf.png)

But it's not important, if it's inconvenient, just ignore the issue~
