### ISSUE TITLE
Table 中字段的 render 函数不可以返回字符串值

### ISSUE THREAD

**Issue by TheWaWaR** [ant-design/ant-design#634]
### 错误内容
```
Uncaught TypeError: Cannot read property '_currentElement' of null
```

### 具体症状
+ 数据无法渲染
+ react-router 失效
+ React Chrome dev-tool 失效(见下图), 点击 `click here` 毫无反应

* * * * *

![image](https://cloud.githubusercontent.com/assets/1160419/11589696/67dc8ed6-9ac5-11e5-87c5-4358edc112f8.png)

**Comment by TheWaWaR** [comment]
找到原因了，字段的 `render` 函数中不可以返回字符串值。

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/18

这里已修复，请重新安装 antd，rc-table 更新到 3.6.2 即可。

**Comment by TheWaWaR** [comment]
OK!

**Comment by TheWaWaR** [comment]
更新了，好像还是出错。
