### ISSUE TITLE
textarea return ↵

### ISSUE THREAD

**Issue by acwong00** [ant-design/ant-design#6340]
### Version
2.6.4

### Environment
chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/KqPJaG?editors=0011](https://codepen.io/anon/pen/KqPJaG?editors=0011)

### Steps to reproduce
Input some text and hit ENTER then click submit. The console value will include "↵"

### What is expected?
replace "↵" to "\n"

### What is actually happening?
 "↵"

**Comment by benjycui** [comment]
Just `JSON.stringify(value)`.

**Comment by yangxiaolin** [comment]
use css `white-space: pre-line;` may help you
