### ISSUE TITLE
Radio in checked state renders wrong on retina 

### ISSUE THREAD

**Issue by message** [ant-design/ant-design#6343]
### Version
2.10.4

### Environment
Chrome 55.0.2883.87. Ubuntu 16.04.2 LTS

### Reproduction link
[https://ant.design/components/radio/](https://ant.design/components/radio/)

### Steps to reproduce
Open https://ant.design/components/radio/

### What is expected?
Render correctly

### What is actually happening?
![screenshot from 2017-06-02 21-13-36](https://cloud.githubusercontent.com/assets/492026/26727406/61542dc6-476c-11e7-866c-ded9038112f3.png)

**Comment by afc163** [comment]
Could you PR to fix it, we don't have your environment and everything seems to be alright in my browser.

**Comment by message** [comment]
It was webkit rendering bug. Already fixed in latest Chrome
