### ISSUE TITLE
加入正则表达式之后,min:4,max:20失效没有起作用

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#6346]
### Version
2.10.4

### Environment
window

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
{required: true,min:4,max:20,pattern:/^[0-9a-zA-Z]*$/g,whitespace:true, message: '请输入4-20位数字加字母组合的菜单代码!'}

加入正则表达式之后,min:4,max:20失效没有起作用

### What is expected?
希望都有效果

### What is actually happening?
{required: true,min:4,max:20,pattern:/^[0-9a-zA-Z]*$/g,whitespace:true, message: '请输入4-20位数字加字母组合的菜单代码!'}

加入正则表达式之后,min:4,max:20失效没有起作用

**Comment by afc163** [comment]
Yes, if you use `pattern`, other validation terms would be not working.
