### ISSUE TITLE
Sider expand/collapse transition not working in IE11

### ISSUE THREAD

**Issue by topvis** [ant-design/ant-design#6349]
### Version
2.10.4

### Environment
Windows 7, IE 11

### Reproduction link
[https://codepen.io/topvis/pen/dRyQRV](https://codepen.io/topvis/pen/dRyQRV)

### Steps to reproduce
Run the codepen reproduction in IE11.
Expand and collapse the Sider by clicking on the button as shown in the screenshot.
![image](https://cloud.githubusercontent.com/assets/5996531/26759409/da6cdc12-48ca-11e7-8a39-bd8369ad73e7.png)

### What is expected?
The Sider expands and collapses with transition effect. This works in Chrome or Firefox.

### What is actually happening?
There is no transition in IE 11.

**Comment by benjycui** [comment]
It should work, see: http://caniuse.com/#search=transition

But it doesn't doesn't work actually, https://ant.design/components/layout/#components-layout-demo-side

ref: https://www.google.com/search?q=IE+11+width+transition+doesn%27t+work&oq=IE+11+width+transition+doesn%27t+work&gs_l=serp.3..30i10k1.1002.4034.0.4328.13.10.0.0.0.0.412.1740.2-2j1j2.5.0....0...1.1.64.serp..8.5.1740.oIXYbcvlos4

But we haven't use any `calc` in layout's styles

**Comment by afc163** [comment]
https://stackoverflow.com/a/21381301/3040605

**Comment by afc163** [comment]
Transition is not working when `flex-basis` is set to numberic px value in IE11.
