### ISSUE TITLE
是否可以考虑做一个兼容react-jsonschema-form(rjsf)的表单支持，该表单符合ietf jsonschema标准

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#6351]
### What problem does this feature solve?
rjsf :https://github.com/mozilla-services/react-jsonschema-form
jsonschema:http://json-schema.org

### What does the proposed API look like?
增加对这个表单编辑的功能支持.

**Comment by yesmeck** [comment]
Duplicate of #6352.
