### ISSUE TITLE
Conside make a support for rjsf (a form builder base on IETF  JSONSchema)

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#6352]
### What problem does this feature solve?
rjsf :https://github.com/mozilla-services/react-jsonschema-form
jsonschema:http://json-schema.org

### What does the proposed API look like?
suport the IETF standard JSONSchema  form builder
maybe just  base on this project "rjsf" (:https://github.com/mozilla-services/react-jsonschema-form)

**Comment by yesmeck** [comment]
Hello @eddyzhang1986 I'm afraid we won't do this in antd, but I'm happy to see someone create a library antd-jsonschema-form 😄 .

**Comment by eddyzhang1986** [comment]
ok, let me try do this.
