### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by BrodaNoel** [ant-design/ant-design#6353]
### What problem does this feature solve?
We need a countdown. Something like: "Time remaining: 5 minutes, 13 second". (where you can specify a format).
The Countdown should show the Spin component (or something like that)

### What does the proposed API look like?
For Time countdown:
```jsx
<Countdown start={this.state.someMilisecondsVar} format="Time remaining: %hh:%mm and %ss miliseconds" paused={false}></Countdown>
```

**Comment by afc163** [comment]
Try https://github.com/StevenIseki/react-count-down or https://github.com/uken/react-countdown-timer
