### ISSUE TITLE
Method to get all fields' value when form is changing.

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#6355]
### What problem does this feature solve?
I want to add a preview feature to my app, once I update the form / change any field of the form, the values will be mapped into a table automatically. (Don't have to trigger a button, detect `blur` event and so on, the entire process flows reactively)

At present, the solution is two:

1. Making use of the `onValuesChange` option within `Form.create`.

In parent component,` onValuesChange` only pass the single value which is changed, I have to carefully setState / update state (the filed's name as the key, value as the value). If some api provide me all the values in form fields when trigger `onValuesChange` event, can save my life.

2. Making use of the `onValuesChange` option, too. But this event only triggers a child form's method which collects all values through the `form` prop.

To complete this process:
1. One way is use `ref`, the original form, which isn't be wrapped by From.create, has the `form` prop to collects all fields' value, but how to add `ref` to the original form and access it? The HOC component wrapped by Form.create cut off the link to access ref directly.
2. Another way is use map parent state, which will be re-setStated through `onValuesChange`, as child's props. And the child do collection work in `componentWillReceiveProps` or in other life cycles and then notify its parent.

The first solution seems complex and the second solution mixed many interactive between parent and child seems weird and ugly. Any alternative suggestions or useful form api can handle this requirement?

### What does the proposed API look like?
**Suggestion: Add `allValues` as the third argument to `onValuesChange`**

**Comment by zheeeng** [comment]
I find another solution is in original form, attach onChanges event on every field, it collects all fields value and passes up via func type prop to its parent. But there are still a lot of redundant event attachments. May an elegant method saves my life, plz.

**Comment by benjycui** [comment]
You can just can `this.props.form.getFieldsValue` in `onValuesChange`.

**Comment by zheeeng** [comment]
@benjycui `onValuesChange` is an option of Form.create, what I can access is only `props` and `values` and the 'props' is which passed to the HOC. I can neither access `form` prop in Form.create option or attach `onValuesChagne` on original form.

**Comment by zheeeng** [comment]
@benjycui in `<Antd-Form>` there is no `onValuesChange`, in `onValuesChange` there is no `props.form`.

**Comment by benjycui** [comment]
```jsx
const YourForm = Form.create({
  onValuesChange(props, values) { props.onValuesChange(values) }
})(xxx);

render() {
  return (
    <YourForm
      ref="form"
      onValuesChange={(values) => console.log({...this.refs.form.getFieldsValue(), ...values})}
    />
  );
}
```

**Comment by zheeeng** [comment]
@benjycui Thank you very much! I can access the form methods through directly and my problem is solved. But some not that good things are using `ref` seems a little anti-pattern and generally ppl don't know which methods (within Component and no doc mentioned) they can manipulate through `ref`.

**Comment by zheeeng** [comment]
@benjycui A little problem, must use setTimeout deffer 0ms make sure get correct input, otherwise, the got values is old.

```
const YourForm = Form.create({
  onValuesChange(props, values) { props.onValuesChange(values) }
})(xxx);

render() {
  return (
    <YourForm
      ref="form"
      onValuesChange={
        (values) => {
            setTimeout(() => {console.log({...this.refs.form.getFieldsValue(), ...values})}, 0)
        }
     }
    />
  );
}
```

**Comment by CallMeXYZ** [comment]
@benjycui `onValuesChange ` is fine. But  is there any solution or hack to handle `onValuesChange` inside `YourForm`? so that the users of `YourForm` could know less detail about it

**Comment by benjycui** [comment]
@CallMeXYZ `this.props.form.getFieldsValue`

**Comment by CallMeXYZ** [comment]
@benjycui ok, that's what i did now: manually record the values and compare every time.
