### ISSUE TITLE
Error occurs when using Timeline.Item

### ISSUE THREAD

**Issue by mixj93** [ant-design/ant-design#6356]
### Version
2.10.0

### Environment
React 15.5.4, antd 2.10.0, Typescript 2.3.4

### Reproduction link
[https://files.gitter.im/ant-design/ant-design/h5se/image.png](https://files.gitter.im/ant-design/ant-design/h5se/image.png)

### Steps to reproduce
```
import { Timeline } from 'antd'

<Timeline>
    <Timeline.Item>Create a services site 2015-09-01</Timeline.Item>
    <Timeline.Item>Solve initial network problems 2015-09-01</Timeline.Item>
    <Timeline.Item>Technical testing 2015-09-01</Timeline.Item>
    <Timeline.Item>Network problems being solved 2015-09-01</Timeline.Item>
</Timeline>
```
![](https://files.gitter.im/ant-design/ant-design/h5se/image.png)

### What is expected?
No error.

### What is actually happening?
error TS2604: JSX element type 'Timeline.Item' does not have any construct or call signatures.

---
Maybe I use it in a wrong way, but when I change `static Item: React.ReactNode;` to `static Item: any;` in `node_modules/antd/lib/timeline/Timeline.d.ts` error fixed, everything is fine.

Looking forward to your reply.

**Comment by afc163** [comment]
Have you try `@type/react@15.0.26` and `antd@2.10.4`?

**Comment by mixj93** [comment]
antd 2.10.4 has errors:
```
error TS2304: Cannot find name 'T'.

error TS2604: JSX element type 'Timeline.Item' does not have any construct or call signatures.
```

**Comment by mixj93** [comment]
So how to fix this？ @afc163

**Comment by afc163** [comment]
wait for next release.

**Comment by JamDeezy** [comment]
It's a mistype issue,
here's a workaround without editing the modules folder (which is a bad idea):

````
import { Icon, Modal, Button, Timeline } from "antd";
const TimelineItem = Timeline.Item as any

<Timeline>
    <TimelineItem>Create a services site 2015-09-01</TimelineItem>
    <TimelineItem>Solve initial network problems 2015-09-01</TimelineItem>
    <TimelineItem>Technical testing 2015-09-01</TimelineItem>
    <TimelineItem>Network problems being solved 2015-09-01</TimelineItem>
</Timeline>
````

**Comment by mixj93** [comment]
@JamDeezy thanks a lot 👍
