### ISSUE TITLE
日期选择期选中后的显示问题

### ISSUE THREAD

**Issue by 690465348** [ant-design/ant-design#6357]
### Version
2.10.4

### Environment
os10.11.6、safari10.0.1 (11602.2.14.0.7)

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
选择日期

### What is expected?
日期选择框中显示选中的日期，默认提示文字消失

### What is actually happening?
日期选择框中显示选中的日期，默认提示文字没有消失

**Comment by afc163** [comment]
duplicate #4782
