### ISSUE TITLE
tree增加自动展开勾选节点(Tree add a api for automatic expand checked keys)

### ISSUE THREAD

**Issue by 282159468** [ant-design/ant-design#6358]
### What problem does this feature solve?
tree组件当传入checkedKeys时，是否考虑支持传入一个参数如
autoExpandChecked自动展开选中的节点
auto expand checked keys
现在的做法是通过expandedKeys和autoExpandParent来做的，感觉好麻烦

### What does the proposed API look like?
autoExpandChecked

**Comment by benjycui** [comment]
新增一个属性和你现在用的方案代码量不会有太大区别，还是保持组件精简吧。
