### ISSUE TITLE
setFieldsValue 在 2.6.0 之后的版本只能对已经注册过的 FormItem 设置 value

### ISSUE THREAD

**Issue by cnzsb** [ant-design/ant-design#6360]
### Version
2.10.4

### Environment
^antd 2.6.0

### Reproduction link
[https://codepen.io/cnzsb/pen/awzORb](https://codepen.io/cnzsb/pen/awzORb)

### Steps to reproduce
componentDidMount 中进行 setFieldsValue 时，需要手动对有前置依赖的 FormItem 二次设置 value

### What is expected?
Form 应该在视图 render 之后继续监测是否有新的 FormItem 需要更新

### What is actually happening?
setFieldsValue 只能对 getFieldDecorator 注册过的 FormItem 设置 value

---
2.5.3 之前的版本可正常使用

**Comment by afc163** [comment]
这是合理的，getFieldDecorator 是一种双向绑定，未绑定过的数据不能 set 和 get。若允许的话，那么不如直接用 setState。

> 2.5.3 之前的版本可正常使用

这个属于前面版本的问题，不应该能正常使用，例子里也修正了。
