### ISSUE TITLE
webpack antd 2.10.4 is different from 2.8.1

### ISSUE THREAD

**Issue by acivang** [ant-design/ant-design#6362]
### Version
2.10.4

### Environment
mac OS 10.12.3/chrome 56.0.2924.87 (64-bit)/react 15.4.2/webpack 2.6.1

### result code:

```javascript
// version 2.8.1 : this local object have timePickerLocale
var locale = (0, _getLocale.getComponentLocale)(props, this.context, 'DatePicker', function () {
      return __webpack_require__(193);
});
```
```javascript
// version 2.10.4 : this local object have default.timePickerLocale and it resulting in a error.
var locale = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_11__util_getLocale__["b" /* getComponentLocale */])(props, this.context, 'DatePicker', function () {
        return __webpack_require__(195);
});
// there throw a error for local.timePickerLocale is undefined.
var timePicker = props.showTime ? __WEBPACK_IMPORTED_MODULE_6_react___default.a.createElement(__WEBPACK_IMPORTED_MODULE_8_rc_time_picker_es_Panel__["a" /* default */], __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_extends___default()({}, rcTimePickerProps, props.showTime, { prefixCls: prefixCls + '-time-picker', className: timePickerCls, placeholder: locale.timePickerLocale.placeholder, transitionName: 'slide-up' })) : null;
```

### Steps to reproduce
webpack 2.6.1 package antd lib of 2.10.4 and 2.8.1,and see the wrapPicker.js code in browse.

### What is expected?
webpack result is same.

### What is actually happening?
they are different

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/6334

**Comment by acivang** [comment]
@benjycui Thank you for reply! and i use balel-plugin-import and config like [https://github.com/ant-design/babel-plugin-import](url) but it is not helpful, the problem is still exist.if you had any document for update from antd 2.8.x to 2.10.x ? thank you very much!
