### ISSUE TITLE
Close DatePicker panel without animation

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#6364]
https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges

1. First Demo
2. click preset range link
3. The panel is closing without closing animation, which is expected.

**Comment by benjycui** [comment]
好像和其他的例子行为一致？感觉就是动画有点快。

**Comment by afc163** [comment]
Only happen in Firefox.

**Comment by benjycui** [comment]
通过受控模式直接关闭会有这种情况。

https://github.com/ant-design/ant-design/commit/7841386fcd46a882ff70b99fe0e7c003000de59a 之后，两个例子都有这个问题了。
