### ISSUE TITLE
Mention配合Form，提交时，getFieldValue取值为 object，如何取到mention输入的值呢？

### ISSUE THREAD

**Issue by Autumnwater** [ant-design/ant-design#6365]
### Version
2.10.4

### Environment
win7 chrome  

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)
[https://codepen.io/hehelink/pen/QgwKzp?editors=1111](https://codepen.io/hehelink/pen/QgwKzp?editors=1111)(就是官方的拿来用了)

### Steps to reproduce
官方案例：“受控模式，例如配合 Form 使用” 你输入任何字符，当你Submit的时候， console为Object {mention: t}

Official case：“Controlled mode, for example, to work with Form.”，you input some into mention，when you Submit , console restule is : Object {mention: t}

### What is expected?
如何取得mention输入的值

 how to get mention 's  value by form ?

### What is actually happening?
Mention配合Form，提交时，this.props.form.validateFields和this.props.form.getFieldValue取值为 object，如何取到mention输入的值呢？
官方案例：“受控模式，例如配合 Form 使用” console为Object {mention: t}
自己写的案例为           
 const projectData = this.props.form.getFieldsValue()                           
console出来projectData Object {mention1: ContentState}

**Comment by ybning** [comment]
#6115

**Comment by Autumnwater** [comment]
console.log('Submit!!! ',toString(values.mention));
hehe

**Comment by benjycui** [comment]
需要更新下 demo

**Comment by benjycui** [comment]
看了下 Mention 的 demo，感觉很明显啊 😢

**Comment by Autumnwater** [comment]
只看了有 Submit的官方案例 ：“受控模式，例如配合 Form 使用” 
没仔细看全部demo。。。 @benjycui
