### ISSUE TITLE
Backtop target is invalid

### ISSUE THREAD

**Issue by cnchore** [ant-design/ant-design#6366]
### Version
2.10.4

### Environment
mac ox 10.11.6、chrome 58.0.3029.110、antd 2.10.4

### Reproduction link
[https://codepen.io/cnchore/pen/KqwNjr](https://codepen.io/cnchore/pen/KqwNjr)

### Steps to reproduce
1. backtop target 绑定div ；
2. 滚动 div，backtop可见，点击可返回顶部；

### What is expected?
滚动 div，backtop可见，点击可返回顶部；

### What is actually happening?
滚动 div，backtop不可见

**Comment by afc163** [comment]
The `div` in your codepen is not even scrollable!

https://codepen.io/anon/pen/yXyZqq?editors=0010

**Comment by duzitengg** [comment]
react update 16.1.0
  <BackToptarget={() => document.getElementById('backTop')}>
          <div>
            <Icon type="arrow-up" className='backTop' />
          </div>
        </BackTop>

warning.js:33 Warning: Invalid value for prop `target` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in div (created by BackTop)
    in AnimateChild (created by Animate)
    in Animate (created by BackTop)
    in BackTop (created by Product)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by Product)
    in Product
    in Unknown (created by Form(WrappedComponent))
    in Form(WrappedComponent) (created by RouterContext)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by FirstPage)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by FirstPage)
    in div (created by FirstPage)
    in FirstPage (created by Connect(FirstPage))
    in Connect(FirstPage) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

what's happend?

**Comment by bochen2014** [comment]
got the same warning
![image](https://user-images.githubusercontent.com/8207081/37132976-bfe1da92-22e4-11e8-8720-f3c80c9bc11a.png)

seems to me that `target` should be renamed to `data-target` to better fit customer attribute naming convention. 
the component works as expected though
