### ISSUE TITLE
some icons not working without importing antd/dist/antd.css?

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#6368]
### Version
2.10.4

### Environment
"antd": "^2.10.4",  "react": "^15.4.2",

### Reproduction link
[https://codepen.io/anon/pen/mwyLxY?editors=001](https://codepen.io/anon/pen/mwyLxY?editors=001)

### Steps to reproduce
I typically have one less file where I do this:

@import '{}/node_modules/antd/dist/antd.less';

This seems to import everything I need. However some icons don't work unless I use this in the component that needs the <Icon />:

import 'antd/dist/antd.css';

But then all my custom styles from my less file get overridden....

### What is expected?
expect all icons to work

### What is actually happening?
no icon will show up

**Comment by afc163** [comment]
Please provide a reproducible repository.

**Comment by yesmeck** [comment]
@acomito

**Comment by acomito** [comment]
working on it now, will have something in a minute @afc163 @yesmeck

**Comment by acomito** [comment]
Okay, so here is a relatively close setup to the one I am having problems with.... it uses meteor, so no webpack for the build.

https://github.com/acomito/antd-icon-issue-example


There's  [a babel file:](https://github.com/acomito/antd-icon-issue-example/blob/master/.babelrc)
```
{
  "plugins": [
    ["transform-class-properties", "import", {"libraryName": "antd"}]
  ]
}
```

[a single less file](https://github.com/acomito/antd-icon-issue-example/blob/master/client/theme.less)

When I run the app as is, I see this on the home page:

![screen shot 2017-06-12 at 10 41 03 am](https://user-images.githubusercontent.com/12701635/27039334-aed3bf48-4f5b-11e7-8d75-d90d6900df7d.png)


which is this code here:

[link to index.js](https://github.com/acomito/antd-icon-issue-example/blob/master/imports/ui/pages/index.js)
```
// TOP LEVEL
import React from 'react';
// ANTD
import Icon from 'antd/lib/icon';
import Card from 'antd/lib/card';
// MODULES
import { handleLogin } from '/imports/modules/helpers'

class LoginPage extends React.Component {

	render(){
		return (
			<div>
				<Card>
					<Icon type='tool' />
				</Card>
				<Card>
					<Icon type='user' />
				</Card>
			</div>
			
		)
	}
}


export default LoginPage;
```

Given my current setup, the user icon shows up fine. But the tools icon doesn't... I am currently just importing the antd.less inside my theme.less file (mentioned earlier in this comment).

Now, if I add this css import to the index file, I can see the icon:

// TOP LEVEL
import React from 'react';
// ANTD
import Icon from 'antd/lib/icon';
import Card from 'antd/lib/card';
// MODULES
import { handleLogin } from '/imports/modules/helpers'
import 'antd/dist/antd.css'; // new line of code

class LoginPage extends React.Component {

	render(){
		return (
			<div>
				<Card>
					<Icon type='tool' />
				</Card>
				<Card>
					<Icon type='user' />
				</Card>
			</div>
			
		)
	}
}


export default LoginPage;


![screen shot 2017-06-12 at 10 42 44 am](https://user-images.githubusercontent.com/12701635/27039438-f059252a-4f5b-11e7-8361-cc15678c9911.png)


However by doing this, the styling rules in my theme.less are being overwritten....

It is odd that I can all the styling I need (and most of the icons) by just importing the less file. But there are some icons now showing up (one of which is the tool icon from this example).

**Comment by acomito** [comment]
I think maybe there is a missing less file for the icon folder in the lib folder.

I ended up just copy-pasting the font-face declaration into my theme.less, which is okay until the url changes:
```

@font-face {
  font-family: 'anticon';
  src: url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot');
  /* IE9*/
  src: url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot?#iefix') format('embedded-opentype'), /* chrome、firefox */ url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff') format('woff'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/ url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.ttf') format('truetype'), /* iOS 4.1- */ url('https://at.alicdn.com/t/font_zck90zmlh7hf47vi.svg#iconfont') format('svg');
}

```
