### ISSUE TITLE
Improve documentation about how to implement `antd` in `create-react-app`

### ISSUE THREAD

**Issue by BrodaNoel** [ant-design/ant-design#6371]
### What problem does this feature solve?
We should avoid ejecting `create-react-app` while implementing `antd`.
What we should do?
In [this](https://ant.design/docs/react/use-with-create-react-app) documentation, we should purpose to include components on-demand (as it is described [here](https://ant.design/docs/react/getting-started#Import-on-Demand)), and purpose eject `create-react-app` as the last option.

This discussion started in `create-react-app` repo in [this](https://github.com/facebookincubator/create-react-app/issues/2463) issue.

Proposal to fix:
Recommend to do `import`s of all styles in `App.js` component, and import the proper component inside each container that it will be used. Example:

In `App.js`:
```js
import React from 'react';
// ...
import 'antd/lib/button/style'; // or antd/lib/button/style/css'
import 'antd/lib/progress/style'; // or antd/lib/progress/style/css'
import 'antd/lib/checkbox/style'; // or antd/lib/checkbox/style/css'
```

In `MyContainer.js`:
```js
import Button from 'antd/lib/button';
```

### What does the proposed API look like?
Just improve the documentation, adding that information.

**Comment by BrodaNoel** [comment]
If you are busy guys, I can send a PR in these next days.
Let me know if you need my help

**Comment by cr101** [comment]
@BrodaNoel Is there a reason why you couldn't/shouldn't `import` a component's style in `MyContainer.js` as well?

In `MyContainer.js`:

```
import 'antd/lib/button/style'; // or antd/lib/button/style/css'
import Button from 'antd/lib/button';
```

**Comment by afc163** [comment]
https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides

I think documentation is quite clear for this.

**Comment by BrodaNoel** [comment]
@cr101 just to avoid repeat same `import` in different places, while we know it is included only one time.

**Comment by BrodaNoel** [comment]
@afc163 I agree the documentation is clear, but I guess we should purpose to include component on-demand as first option. Then, recommend `eject` only if the developer can't implement it on-demand.
That proposal will be a win-win for Ant and create-react-app

**Comment by afc163** [comment]
We can use `import Button from 'antd/lib/button';` in first place, PR is welcome~
