### ISSUE TITLE
Switch与Popconfirm该如何结合使用？

### ISSUE THREAD

**Issue by flicker85** [ant-design/ant-design#6373]
### What problem does this feature solve?
当Switch切换时，我想先弹出Popconfirm确认框，点确定后Swtich切换状态，否则状态不变，
官方文档中说Popconfirm只支持“onMouseEnter、onMouseLeave、onFocus、onClick”事件，
请问在Swtich切换时该如何触发Popconfirm显示？

### What does the proposed API look like?
期望：给Switch添加onClick事件？

**Comment by afc163** [comment]
You can implement it for now: https://codepen.io/anon/pen/gRbqvL?editors=001

We should add `onClick` for Switch.

**Comment by flicker85** [comment]
@afc163 ok, thx~
![image](https://cloud.githubusercontent.com/assets/5960708/26812279/60d1b892-4aa9-11e7-9afa-2cf1053d1e4d.png)
![image](https://cloud.githubusercontent.com/assets/5960708/26812300/918b2626-4aa9-11e7-913c-6e5f78fcbdff.png)

**Comment by benjycui** [comment]
A weird UX... see: https://ant.design/components/switch/#When-To-Use
