### ISSUE TITLE
当语言为中文时，时间选择器选择时间，标题处时间显示语言混乱

### ISSUE THREAD

**Issue by JohnsenZhou** [ant-design/ant-design#6377]
### Version
2.10.4

### Environment
所有浏览器

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
![ant design issue img](https://raw.githubusercontent.com/JohnsenZhou/NodeApp-Deploy/img/6637247A-077E-4BE8-903C-70225B8EE220.png)

### What is expected?
期望显示为：2017 年 6 月 6 日

### What is actually happening?
2017 年 六 月 6 日

**Comment by benjycui** [comment]
ref: https://github.com/react-component/calendar/issues/224

**Comment by benjycui** [comment]
It's hard to make those two ideas work together..

**Comment by walking11** [comment]
![image](https://user-images.githubusercontent.com/14257970/26866814-6cac573e-4b95-11e7-9eef-707a3ab1a7ed.png)
这里还出现了中英文混合的情况

**Comment by benjycui** [comment]
@walking11 请确认你的 LocaleProvider 与 moment.locale 设置的是同一种语言。

**Comment by afc163** [comment]
So change it back? ..

**Comment by afc163** [comment]
在 header 区域统一用 monthsShort 好了。https://github.com/ant-design/ant-design/issues/6377

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`
