### ISSUE TITLE
setting width to 100% isn't effective on Input component with addon in Form.Item

### ISSUE THREAD

**Issue by GHL-Candy** [ant-design/ant-design#6379]
### Version
2.10.4

### Environment
In the latest version of antd, Chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://codepen.io/candy_ghl/pen/BZyeXm?editors=0010](https://codepen.io/candy_ghl/pen/BZyeXm?editors=0010)

### Steps to reproduce
As described in CodePen

### What is expected?
When setting width to '100%', the width of addon-Input can be as wide as form item

### What is actually happening?
Width of the addon-Input is limited by the style of ant-input-group-wrapper

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/920adb9a8a8e7b5953947574503efa9963b88ee3, wait for next release.
