### ISSUE TITLE
Tree 功能增强

### ISSUE THREAD

**Issue by zhaotoday** [ant-design/ant-design#638]
Tree 组件是否考虑增加拖拽节点功能？

**Comment by warmhug** [comment]
可以考虑放到 0.12 版本里，磊哥来做或我来做。 @afc163

**Comment by afc163** [comment]
#708

**Comment by Liyuk** [comment]
tree组件是否考虑增加 `手动重置选中项` 的功能？

**Comment by Liyuk** [comment]
补充：`手动重置功能`指在周期刷新的时候设置参数，而不仅仅是通过`defaultCheckedKeys`；`defaultCheckedKeys`这个接口仅能在`Mount`时设置参数，并不能够实时刷新

**Comment by warmhug** [comment]
@Liyuk 会支持的
