### ISSUE TITLE
ie9 transfer 筛选总数计数错误(the total count is wrong display when type in search box)

### ISSUE THREAD

**Issue by Restry** [ant-design/ant-design#6381]
### Version
2.10.4

### Environment
win7 ie9.0.8112.16421  64bit

### Reproduction link
[https://codepen.io/restry/pen/weavGm?editors=001](https://codepen.io/restry/pen/weavGm?editors=001)

### Steps to reproduce
`
  <Transfer
          dataSource={modalUsers}
          showSearch
          filterOption={filterOption}
          ref={c => this.members = c}
          render={(item) => item.title} />
`

> 筛选框输入 搜索值后，列表显示筛选内容正确，但是上方筛选总数显示错误。当筛选数据为空时还显示1或其它错误
> (in english description) the total count is wrong display when type in search box if result is empty .

### What is expected?
right total count

### What is actually happening?
you know that was wrong..

**Comment by Restry** [comment]
ie9小版本号：8112.16421  64位版本

**Comment by benjycui** [comment]
Make sure that you had imported polyfill, see: https://ant.design/docs/react/getting-started-cn#兼容性

**Comment by Restry** [comment]
请问这几个是动态生成的吗？因为我的环境在内网，能否下载下来引用

**Comment by benjycui** [comment]
直接用文档中的链接即可， CDN 会更好。
