### ISSUE TITLE
When I set a new key to Modal and changed the value of component in Modal ,some error happend

### ISSUE THREAD

**Issue by FatFatFox** [ant-design/ant-design#6387]
### Version
2.10.4

### Environment
Macbook chrome 58.0

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
Step 1.
`<Modal {...modalOpts} >
      <Form layout="horizontal">
        <FormItem label="实例名称" hasFeedback {...formItemLayout}>
          {getFieldDecorator('name', {
            initialValue: item.name,
            rules: [
              {
                required: true,
              },
            ],
          })(<Input />)}
        </FormItem>
<Modal>`
Step 2.
Open this Modal and input some value in component, and cancel it
Step 3.
open this Modal again, and type some letters in <Input />

### What is expected?
no error in console

### What is actually happening?
createBaseForm.js?b85e:98 Uncaught TypeError: Cannot read property 'onChange' of undefined
    at Object.onCollectCommon (eval at 1643 (http://localhost:8000/4.async.js:111:2), <anonymous>:98:23)
    at Object.onCollectValidate (eval at 1643 (http://localhost:8000/4.async.js:111:2), <anonymous>:138:38)
    at Object.executeOnChange (eval at <anonymous> (http://localhost:8000/index.js:1932:2), <anonymous>:132:34)

---
I can make sure that the key changed when I open this modal

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close for no response.
