### ISSUE TITLE
Breadcrumb 不支持 IndexRoute

### ISSUE THREAD

**Issue by mongris** [ant-design/ant-design#639]
场景：Breadcrumb与React Router
条件：在routes中配置了IndexRouter
问题：Cannot call method 'indexOf' of undefined ...
相关代码位置：https://github.com/ant-design/ant-design/blob/16ce16ebd392a8f078830d21b57d3a1b5456955d/components/breadcrumb/index.jsx#L36

IndexRoute的route没有.path属性

**Comment by afc163** [comment]
不要在 IndexRoute 上绑定 breadcrumbName。在 Router 上绑定即可。

```jsx
<Router>
  <Route breadcrumbName="Home" path="/" component={App}>
    <IndexRoute component={Home} />
    <Route breadcrumbName="Accounts" path="accounts" component={Accounts}/>
    <Route breadcrumbName="Statements" path="statements" component={Statements}/>
  </Route>
</Router>
```

https://github.com/rackt/react-router/blob/0969da8b08db6b4286127aefd0640b4661994baa/docs/guides/basics/IndexRoutes.md#index-routes
