### ISSUE TITLE
Uncaught TypeError: (0 , _domAlign2.default) is not a function

### ISSUE THREAD

**Issue by 91ranjan** [ant-design/ant-design#6390]
### Version
2.10.4

### Environment
Development

### Reproduction link
[https://codepen.io/91ranjan/pen/pwJKBK?editors=001](https://codepen.io/91ranjan/pen/pwJKBK?editors=001)

### Steps to reproduce
Add antd select to the https://github.com/nicksp/redux-webpack-es6-boilerplate boilerplate and open the options of the select.

### What is expected?
It should open without any errors

### What is actually happening?
Align.js?f454:77 Uncaught TypeError: (0 , _domAlign2.default) is not a function
    at Align._this.forceAlign (eval at <anonymous> (application.js:6702), <anonymous>:77:57)
    at Align.componentDidMount (eval at <anonymous> (application.js:6702), <anonymous>:85:10)

**Comment by afc163** [comment]
> Add antd select to the https://github.com/nicksp/redux-webpack-es6-boilerplate boilerplate and open the options of the select.

Could you please provide a reproducible repository?

**Comment by yesmeck** [comment]
@91ranjan

**Comment by 91ranjan** [comment]
Hi,
The issue was resolved as I was using older version of the babel. Needed to update it.

From:  偏右
Reply-To:  ant-design/ant-design
Date:  Wednesday, June 7, 2017 at 11:01 AM
To:  ant-design/ant-design
Cc:  Ritesh Ranjan, Author
Subject:  Re: [ant-design/ant-design] Uncaught TypeError: (0 , _domAlign2.default) is not a function (#6390)


Add antd select to the https://github.com/nicksp/redux-webpack-es6-boilerplate boilerplate and open the options of the select.

Could you please provide a reproducible repository?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-design","title":"ant-design/ant-design","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-design"}},"updates":{"snippets":[{"icon":"PERSON","message":"@afc163 in #6390: \u003e Add antd select to the https://github.com/nicksp/redux-webpack-es6-boilerplate boilerplate and open the options of the select.\r\n\r\nCould you please provide a reproducible repository?"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-design/issues/6390#issuecomment-306690941"}}}

**Comment by HipsterZipster** [comment]
@91ranjan Which version of babel did you upgrade to? Do you mind sharing your package.json for the rest of us that are experiencing the same issue?

**Comment by 91ranjan** [comment]
@Hipster 
This is the striped down version of my package.json 

"devDependencies": {
    "babel-cli": "6.24.1",
    "babel-core": "6.24.0",
    "babel-eslint": "7.2.3",
    "babel-loader": "7.0.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-flow-strip-types": "6.22.0",
    "babel-plugin-transform-react-constant-elements": "6.23.0",
    "babel-plugin-transform-react-remove-prop-types": "0.4.5",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "copy-webpack-plugin": "4.0.1",
    "cross-env": "2.0.1",
    "eslint": "3.19.0",
    "eslint-plugin-flowtype": "2.34.0",
    "eslint-plugin-react": "7.0.1",
    "extract-text-webpack-plugin": "2.1.0",

    "rimraf": "2.6.1",
    "webpack": "2.6.1",
    "webpack-bundle-analyzer": "2.8.3",
    "webpack-dashboard": "0.4.0",
    "webpack-dev-middleware": "1.10.2",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0"
  },
  "dependencies": {
    "antd": "^2.10.4",
    "autoprefixer": "6.4.1",
    "babel-plugin-import": "^1.2.1",
    "babel-polyfill": "^6.23.0",
    "babel-runtime": "6.23.0",
  }


Hope it helps :)
