### ISSUE TITLE
在table中自定义筛选项时，dropdownmenu里使用RangePicker，选择了开始时间之后，鼠标移动，RangePicker会跑到页面左上角

### ISSUE THREAD

**Issue by zidoshare** [ant-design/ant-design#6393]
### Version
2.10.4

### Environment
windows10,chome 58,react 15.5

### Reproduction link
[https://codepen.io/zidoshare/pen/xrGQJV?editors=001](https://codepen.io/zidoshare/pen/xrGQJV?editors=001)

### Steps to reproduce
在Table组件中自定义筛选项，filterDropdown里使用RangePicker.

### What is expected?
正常使用

### What is actually happening?
选择开始时间后，移动鼠标，RangePicker跑到了页面左上角

**Comment by benjycui** [comment]
Try to use `RangePicker[getCalendarContainer]` to mount node to `filterDropdown` first.

**Comment by zidoshare** [comment]
I got it! think you~

**Comment by afc163** [comment]
Seem still to be a bug.

**Comment by zidoshare** [comment]
why? I have solved it.I have been able to use it now

**Comment by benjycui** [comment]
@zidoshare you don't need to worry about it. This issue keep opening is just for reminding me.

**Comment by benjycui** [comment]
@zidoshare 你可以把 `RangePicker[getCalendarContainer]` 去掉，然后重装依赖测试一下么？

有理由相信 https://github.com/yiminghe/dom-align/commit/1dac9d859390a8f7efc209ea4fe1bd44c443b7a6 已经把问题修复了。

因为我试了 antd@2.9.x 是没问题的，所以应该是 dom-align@1.6.0 引进来的问题。

**Comment by hling51325** [comment]
version 2.11.1
environment  window7 chrome58 react 15.5.4

I got same issue, 

`<div class="ant-calendar-picker-container ant-calendar-picker-container-placement-bottomLeft" style="left: 930px; top: 111px;">`

It's all right ,but when I move the mouse , the style will change to 

`<div class="ant-calendar-picker-container ant-calendar-picker-container-placement-bottomLeft" style="left: 0px; top: -3px;">`

anything help?

**Comment by zidoshare** [comment]
@benjycui  对不起，前几天太忙了，没时间回应，实在不好意思，我测试了一下。。。2.11.x版本，仍然有问题。

**Comment by zidoshare** [comment]
@benjycui ，确实仍然有问题，无论是codepen上面还是本地都是有问题的。但是我注意到，现在的问题是第一次选择不会有这样的问题，但是第二次选择时又会重现

**Comment by benjycui** [comment]
业务代码问题。

因为 RangePicker 渲染的 DOM 没有在 Table 的 filterDropdown 里面，所以点击 RangePicker 后，filterDropdown visible 变为 false，虽然 RangePicker 还在，但是它参考的对象已经消失了。

然后再 hover（点击不会触发 RangePicker re-render，hover 会）触发 re-render，由于没有参考对象，直接定位在左上角。

**Comment by benjycui** [comment]
所以修改 RangePicker 的 getContainer 渲染进 filterDropdown 能解决问题。

又或者手动控制 filterDropdownVisible

**Comment by zidoshare** [comment]
@benjycui 好的，了解啦～谢谢

**Comment by GxvgiuU** [comment]
#4815

**Comment by GxvgiuU** [comment]
#4815
