### ISSUE TITLE
wrong rowIndex on expanded row

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#6395]
### Version
2.10.4

### Environment
latest chrome

### Reproduction link
[https://codepen.io/anon/pen/ZyGwEJ?editors=001](https://codepen.io/anon/pen/ZyGwEJ?editors=001)

### Steps to reproduce
just run code pen 

### What is expected?
row bla and row bla bla have different indexes

### What is actually happening?
row bla and row bla bla have 0 as index

---
also would be fine if there would be one more param in column render function called "expandable" so user can differently render column for expanded row and header row

**Comment by benjycui** [comment]
You should not use array index as key.

**Comment by vorlov** [comment]
@benjycui what to use then in that case? if I have for example Checkbox there and no text to use as a key
