### ISSUE TITLE
why the antd 2.10.4 default libraryDirectory is es?

### ISSUE THREAD

**Issue by acivang** [ant-design/ant-design#6396]
### What problem does this feature solve?
if did not use babel-plugin-import,the webpack build antd lib use es,but why it still was es after use babel-plugin-import? i saw config options's libraryDirectory default is lib, but it dit not work.

### What does the proposed API look like?
文档齐全

**Comment by paranoidjk** [comment]
> but why it still was es after use babel-plugin-import?  i saw config options's libraryDirectory default is lib, but it dit not work.

@yesmeck is it by design?

**Comment by yesmeck** [comment]
@acivang Please provide a reproduction repo.

**Comment by acivang** [comment]
@paranoidjk @yesmeck thank u for reply very much! i solved this problem by [https://github.com/amireh/happypack/blob/master/examples/babel-loader--webpack2/webpack.config.js#L18](webpack2 happypack babel-plugin-import config), hope it is useful for other guys.but,i still have a question, if antd 2.10.4 is not must use babel-plugin-import,why the labraryDirectory default is es? is it by design? thank u very much again!

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/blob/d8e4ab716b23c34d171517abd95bf87453eb5289/src/Plugin.js#L30-L31

@acivang It is not.

**Comment by benjycui** [comment]
it's weird, please provide a re-producible repo @acivang

**Comment by yesmeck** [comment]
@acivang

**Comment by afc163** [comment]
close for no response

**Comment by acivang** [comment]
i am sorry for reply late，It was solved at 2.11.1。
