### ISSUE TITLE
组件代码统一

### ISSUE THREAD

**Issue by ustccjw** [ant-design/ant-design#64]
1. remove 'use strict'
    https://github.com/ant-design/ant-design/pull/63

2. use ES6 module (import / export)
    https://github.com/ant-design/ant-design/pull/66

3. use ES6 Classes (React v0.13+) or React.createClass (support mixin) ?

**Comment by ustccjw** [comment]
应该指定支持的 React 版本

**Comment by yiminghe** [comment]
应该都没问题了
