### ISSUE TITLE
当Form中的Input加上addonBefore属性的时候，此Input就会和其他元素对不齐

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#6403]
https://codepen.io/anon/pen/weKqrO?editors=1010

**Comment by ImJoeHs** [comment]
@afc163 
With addonBefore,  class 'ant-input-group-wrapper' has no width setting while 'ant-input' set width to 100%, which leads to difference apperance. Is it by design?

**Comment by afc163** [comment]
https://codepen.io/anon/pen/bRqPzZ?editors=001

What is the problem?

**Comment by ImJoeHs** [comment]
Have to manually add `style={{ width: '100%' }}` every time. 
The inconsistency is a bit strange for me, but, ok, nevermind. Thanks for reply.

**Comment by zhangchao828** [comment]
没升级到2.11.0之前，input宽度默认是父容器的100%，现在需要加style={{ width: '100%' }}，不过我觉得这个不是问题，
