### ISSUE TITLE
Pagination needs i18n

### ISSUE THREAD

**Issue by youngclean** [ant-design/ant-design#6404]
### What problem does this feature solve?
when pages is in english,the pages are displayed in Chinese, rc-pagination is introduced in the source code, which supports other languages, and can be added to the i18n interface based on this?

### What does the proposed API look like?
 pagination adds a  props like locale，such as ` <Pagination locale="en" /> `

**Comment by afc163** [comment]
http://ant.design/components/locale-provider/
