### ISSUE TITLE
鼠标在表格的行列移动，表格会重新渲染

### ISSUE THREAD

**Issue by bobomanywb** [ant-design/ant-design#6405]
### Version
2.10.4

### Environment
 "react": "^15.4.2","react-dom": "^15.4.2"

### Reproduction link
[https://codepen.io/anon/pen/bRVYWa?editors=0012](https://codepen.io/anon/pen/bRVYWa?editors=0012)

### Steps to reproduce
鼠标在表格的行列移动，表格会重新渲染

### What is expected?
鼠标在表格的行列移动，表格不会重新渲染

### What is actually happening?
鼠标在表格的行列移动，表格会重新渲染

**Comment by yesmeck** [comment]
只有 hover 的那行会重新 render，这是正常的。

**Comment by bobomanywb** [comment]
这个是一直都是这样的吗

**Comment by yesmeck** [comment]
是的。

**Comment by bobomanywb** [comment]
这是出于什么场景要这样设计呢

**Comment by yesmeck** [comment]
固定列的时候左右两个表格要同步 hover 状态。

**Comment by bobomanywb** [comment]
好的，谢谢，解答
