### ISSUE TITLE
Form can't getFieldsValue in Modal when rc-form is @1.3.3

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#6406]
### Version
2.10.4

### Environment
OSX, Chrome 57

### Reproduction link
[https://codepen.io/superlxc/pen/BZowMQ](https://codepen.io/superlxc/pen/BZowMQ)

### Steps to reproduce
rc-form update to @1.3.3 a day ago, when use Form in Modal, it will show 'form.getFieldsValue is not a function'.
I deleted rc-form@1.3.3 in node_modules and reinstall rc-form@1.3.2, nothing wrong happens.
The reproduce link works fine because antd is still @2.10.4,  so it won't reinstall rc-form which releases a day ago.
Plz delete your local node_modules and reinstall to reproduce that.

### What is expected?
nothing wrong

### What is actually happening?
![image](https://user-images.githubusercontent.com/4329120/26915023-d6b56e88-4c56-11e7-8529-2cfc52048dd5.png)

![image](https://user-images.githubusercontent.com/4329120/26915011-c88d411e-4c56-11e7-8d0d-1eb38e3fba80.png)

**Comment by benjycui** [comment]
It's works fine in you CodePen, and http://react-component.github.io/form/examples/input-array.html

And I had tried to upgrade local ant-design to rc-form@1.3.3, and try http://127.0.0.1:8001/components/form/#components-form-demo-form-in-modal , it works fine, too.

Please provide re-producible demo and steps.

**Comment by L-x-C** [comment]
@benjycui  you should add `console.log(form.getFieldsValue())` to your local demo, it only has error when you use `getFieldsValue`

**Comment by benjycui** [comment]
ref: https://github.com/react-component/form/pull/84

Need to add `innerRef` to wrapped component.

**Comment by benjycui** [comment]
等下我把抽取到 createFieldsStore 的方法都补回来然后发个 path 吧。

这个问题的影响面不小。 😢

**Comment by L-x-C** [comment]
谢谢~

**Comment by benjycui** [comment]
+ rc-form@1.3.4

重装依赖 `rm -rf node_modules && npm i`

**Comment by benjycui** [comment]
`innerRef` 还是要做，所以这个 issue 保持打开。

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/form/pull/87
