### ISSUE TITLE
Pagination 分页跳转允许输入浮点数

### ISSUE THREAD

**Issue by sunas** [ant-design/ant-design#6407]
### Version
2.10.4

### Environment
浏览器环境

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
在分页的跳转输入框输入浮动数以后，分页的UI会做出反映

### What is expected?
对输入的数字进行取整处理

### What is actually happening?
分页的UI做出了小数的计算反应。

**Comment by benjycui** [comment]
直接不允许输入小数会更好。
