### ISSUE TITLE
Module not found error for rc-* components when importing from es directory

### ISSUE THREAD

**Issue by panjiesw** [ant-design/ant-design#6412]
### Version
2.10.4

### Environment
React 15.5.4. Typescript 2.3.3

### Reproduction link
[None](./None)

### Steps to reproduce
import TimePicker, DatePicker, Tooltip, Pagination, or Form from `antd` root package. 

```typescript
import {TimePicker, DatePicker, Tooltip, Pagination, Form} from 'antd';
```

### What is expected?
With webpack as bundler, it will resolve to `es` dir specified in `module` field of antd package.json (use tree-shaking). All transitive dependencies should also resolved correctly if used in importing module.

### What is actually happening?
Webpack can't resolve bunch of `rc-*` components because in antd it imports from `es` directory of said package, but the directory doesn't exist.

```
ERROR in ./~/antd/es/time-picker/index.js
Module not found: Error: Can't resolve 'rc-time-picker/es/TimePicker' in '...'

ERROR in ./~/antd/es/date-picker/wrapPicker.js
Module not found: Error: Can't resolve 'rc-time-picker/es/Panel' in '...'

ERROR in ./~/antd/es/tooltip/placements.js
Module not found: Error: Can't resolve 'rc-tooltip/es/placements' in '...'

ERROR in ./~/antd/es/pagination/Pagination.js
Module not found: Error: Can't resolve 'rc-pagination/es/locale/zh_CN' in '...'

ERROR in ./~/antd/es/form/Form.js
Module not found: Error: Can't resolve 'rc-form/es/createDOMForm' in '...'
```

---

This is similar to #6310

I can see the `rc-*` components used in antd above has already included the `es` directory, maybe you guys should update those dependencies?

For example:

- [rc-time-picker](https://github.com/react-component/time-picker) is now at `2.4.1` which includes `es` directory. `antd@2.10.4` is still using `2.4.0`.

EDIT: additional notes
I'm trying to use typescript only and fully depends on webpack 2 to reduce bundle size with tree-shaking. So I'm not using `babel` and with that also without `babel-plugin-import`.

**Comment by benjycui** [comment]
It's weird...

**Comment by benjycui** [comment]
I try to upgrade patch in 109afc5 , just like rc-util. Hope this work..

**Comment by benjycui** [comment]
We will publish 2.11.0 in this week, please try to install your dependencies.

**Comment by kingqi** [comment]
@benjycui  Hey guy, i got the same error in lastest version + typescript@2.5.3
