### ISSUE TITLE
allow partial input in RangePicker (only either start date or end date)

### ISSUE THREAD

**Issue by zachguo** [ant-design/ant-design#6413]
### What problem does this feature solve?
Many times, users don't know the exact range, they simply want to query something like 
- `get all results before 2014 Jan 1st`, or
- `get all results after 2015 Jan 1st`.

### What does the proposed API look like?
I don't really know, maybe `ranges` prop can be extended into a function which receives user selected date as argument, so that we can dynamically generate quick links like `After 2015-01-01` and `Before 2015-01-01` if user selects `2015-01-01`.

Or, an icon button (i.e '`|<`') for selecting earliest/latest possible date can be added. But this may complicate UX flow.

**Comment by benjycui** [comment]
In your use case, just use two DatePicker will be better.

**Comment by zachguo** [comment]
For implementing this single functionality, yes I agree, two DatePicker will be better.
But we'll lose the most useful feature of `RangePicker`, which is defining preset ranges for quick selection...
