### ISSUE TITLE
请问想在notication和progress结合使用，请问怎么实现

### ISSUE THREAD

**Issue by jinchaoxiang** [ant-design/ant-design#6414]
### What problem does this feature solve?
在上传大文件进度展现的时候使用

### What does the proposed API look like?
notification.open({
                message: '文件上传',
                description:  <Progress percent={xx} />,
                duration:null,//不自动关闭
                style: {
                    width: 600,
                    marginLeft: 335 - 600,
                },
            });

**Comment by benjycui** [comment]
> 在上传大文件进度展现的时候使用

这个还是把进度条放在 Upload 控件附近比较好。

试想一下你是 User，弹出了一个 Notification，十分钟后你都不关的可能性？

**Comment by benjycui** [comment]
User 不会等到进度条跑完才去关 Notification 的，关掉后你怎么展示进度？

**Comment by jinchaoxiang** [comment]
因为我看微信图文素材传图片就是这么展现的

**Comment by benjycui** [comment]
> 因为我看微信图文素材传图片就是这么展现的

还是不建议，然后现在像 message notification Modal.method 之类的都只是 alert 的升级版而已，弹出后再去更新是做不到的。

**Comment by liuchaofeng1230** [comment]
同样的需求，想在提交完任务后将进度显示在notification上。如果用户隐藏了提示。在任务完成后，还是会通过notification提示任务完成。
