### ISSUE TITLE
Searchable Tree should scroll to  location of the node automatically

### ISSUE THREAD

**Issue by oldashes** [ant-design/ant-design#6417]
### What problem does this feature solve?
I have a tree list with a lot of  root tree nodes, when i use the search bar to  search a node what at the tail of the tree list, the list will expand the related node , but if i want to find the node i searched,  i have to scroll the list to the  tail of the tree list . So in my opinion, the tree list should scroll to  location of the node automatically, if the search results are multiple, maybe it could scroll to the first result node .

### What does the proposed API look like?
 no extra api will be added.

**Comment by benjycui** [comment]
It will be confusing, if the tree list is too long. Because input box will be scroll out of viewport.

**Comment by oldashes** [comment]
@benjycui you mean the search input box will be scroll out of viewport ? The <Search/> is an independent part , and the <Tree/> just need to receive  the search results , then scroll to the first of the results' DOM node. Maybe you can add a property of <Tree/> (like 'resultKeys' or any others) as an anchor to located.

**Comment by yesmeck** [comment]
As you said, the `<Search />` is an independent part, so I don't think include this feature in `<Tree />` is a good propose, I'd recommend you implementing this by yourself.
