### ISSUE TITLE
Mention配合Form控制，然后光标各种乱跑以及初始化问题

### ISSUE THREAD

**Issue by Autumnwater** [ant-design/ant-design#6418]
### Version
2.10.4

### Environment
chroem

### Reproduction link
[https://ant.design/components/mention-cn/ (官方demo配合 Form 使用)](https://ant.design/components/mention-cn/ (官方demo配合 Form 使用))

### Steps to reproduce
1.在官方栗子上面 配合 Form 使用，有时一开始，@输入在初始会失效，无法唤醒，然后经常会遇到  输入后光标跑到最前面
2，实际开发中遇到 当设置initialValue的时候，就会 在初始时无法 触发 @，并且光标失灵：
{getFieldDecorator('mention',{
                       initialValue: this.state.medata,
                    })(
或者单独拿出来不放入from内，设置Mention的 value后
### What is expected?
光标不会自动到最前面
初始时能够唤醒 @

### What is actually happening?
1.在官方栗子上面 配合 Form 使用，@输入在初始会失效，然后经常会遇到  输入后光标跑到最前面
2，实际开发中遇到 当设置initialValue的时候，就会 在初始时无法 触发 @，并且光标失灵。
而当我不使用form的时候，直接修改 value来控制，依然不行

**Comment by Autumnwater** [comment]
感觉加了 onSearchChange
光标就乱跑

**Comment by Autumnwater** [comment]
解决了，内置div的高度和外置的不一样的问题

**Comment by benjycui** [comment]
> 解决了，内置div的高度和外置的不一样的问题
> 帮我关了吧

你可以自行关闭的。

**Comment by JonasJonny** [comment]
Is there any solution?
