### ISSUE TITLE
当使用FormItem装饰TreeSelect之后，使用resetFields函数无法将输入的搜索文字清空，只能清空value的部分

### ISSUE THREAD

**Issue by weihong1028** [ant-design/ant-design#6419]
### Version
2.10.4

### Environment
macos 10.12.5 / chrome 57

### Reproduction link
[https://codepen.io/weihong1028/pen/zzroYz](https://codepen.io/weihong1028/pen/zzroYz)

### Steps to reproduce
1、展开下拉框并选中其中一至两项
2、输入随意搜索文字
3、点击清空

### What is expected?
值和搜索文字都被清空

### What is actually happening?
值的部分被清空，搜索文字仍然存在

---
希望提供像Select组件一样的失去焦点就自动清空搜索文字的功能

**Comment by benjycui** [comment]
从设计的角度而言，Form 是通用组件，只考虑 value，不考虑每个组件自生特殊的交互。

所以问题在于，TreeSelect 是否准备暴露用于控制搜索值的能力 @warmhug

**Comment by yesmeck** [comment]
`inputValue`

**Comment by weihong1028** [comment]
@yesmeck 可以具体点吗，我试了下直接传`inputValue`属性，不过没有作用。也尝试下获取 TreeSelect 组件实例去查看有没有这个`inputValue`属性，没发现有。

**Comment by yesmeck** [comment]
https://codepen.io/yesmeck/pen/XgdYaM?editors=1010
