### ISSUE TITLE
1.x update 2.10.4 form.setFieldsValue can not set form value when React.element not render in first time 

### ISSUE THREAD

**Issue by linjieAda** [ant-design/ant-design#6421]
### Version
2.10.4

### Environment
chrome 58

### Reproduction link
[https://codepen.io/linmowang/pen/LLGbEd?editors=0011](https://codepen.io/linmowang/pen/LLGbEd?editors=0011)

### Steps to reproduce
这里表单中的 ’所属城市 ‘依赖 ’账号类型‘ 去判断是否显示， 但是’账号类型‘的initialValue 默认为1， 不显示 ‘所属城市’这个FormItem。 
当我在componentDidMount中设置数据为 data = {accountType: '0', cityCode: '300100'} 不能赋值所选城市。
原来1.11.0的版本没有这个问题，如果我把 ’账号类型‘的initialValue 默认为0，就可以赋值杭州

### What is expected?
在’账号类型‘的initialValue 默认为1时，也能正确赋值杭州

### What is actually happening?
在’账号类型‘的initialValue 默认为1时，‘所属城市’没有被赋值上

---
这个场景一般发生在： 编辑表单时 后面FormItem依赖前面的 FormItem的不同判断来展示不同结果

**Comment by magicdawn** [comment]
同, 貌似会把 DOM 中不存在的控件值给清了...
简单起见还是手动加 value / onChange

**Comment by benjycui** [comment]
是的，没有注册的表单域无法 setFieldsValue。

**Comment by linjieAda** [comment]
那这种方式有没有好的写法

**Comment by magicdawn** [comment]
问个问题哈

在我看来, getFieldProps 主要做了两件事

- 双向绑定, value/onChange 这个好办, 我们可以从state 取值 / 更新到 state
- validate 这个, 不知有没有简单点的 api

**Comment by linjieAda** [comment]
@magicdawn 

...getFieldProps('clientName', {
                initialValue: '',
                rules: [{ message: '请输入客户姓名', required: true }]
              })}

this.props.form. validateFields((errors, values) => {
      if (!!errors) {
        return
      }
}

antd的validate 已经非常厉害了
https://ant.design/components/form-cn/

**Comment by linjieAda** [comment]
最后用display: none, 让一开始就全部被form表单获取到, 需要时display: block
