### ISSUE TITLE
Control the text color in the table rows.

### ISSUE THREAD

**Issue by nmgwddj** [ant-design/ant-design#6422]
### What problem does this feature solve?
Just like https://xueqiu.com/hq, the rise data text is green, fall data text is red.

### What does the proposed API look like?
Use columns `render()` function return the text color.

**Comment by afc163** [comment]
```
render(text, record) {
  return <span className="xxx">{text}</span>;
}
```

**Comment by LennyLip** [comment]
@afc163 can you give an example, how to change style(or add className) of whole row, depending of any value in record?

thaks.

**Comment by LennyLip** [comment]
sorry, found it 
`rowClassName={(record, index) => index === 0 ? 'your-class-name' : '' }`

**Comment by jacky-ew** [comment]
how about the header cells?
i want to style the header cells according to different datasets.

**Comment by AliZeynalov** [comment]
why I can't change or set the border of row based on value in record? I tried to to it by `rowClassName`, I could set any other style prop like color, height, but I could not set border attributes.

**Comment by wsergent** [comment]
> why I can't change or set the border of row based on value in record? I tried to to it by `rowClassName`, I could set any other style prop like color, height, but I could not set border attributes. @afc163

Table ROWs do not have borders.
You can set a class to your table row, as per the examples given above, but you will need to use css to update the borders on the <th> or <td> within the row.

i.e. 
```
tr.your-class th, tr.your-class td {
    border: 1px solid lime;
}
```

**Comment by npayton2020** [comment]
> sorry, found it
> `rowClassName={(record, index) => index === 0 ? 'your-class-name' : '' }`

Great! this works for me. Thanks

**Comment by patricktunez123** [comment]
> sorry, found it
> `rowClassName={(record, index) => index === 0 ? 'your-class-name' : '' }`

Great! this works for me. Thanks!

**Comment by freya0608** [comment]
if I want to change td's color, what I should do?
