### ISSUE TITLE
[AutoComplete] Trigger option not working with required rule

### ISSUE THREAD

**Issue by WaldoJeffers** [ant-design/ant-design#6425]
### Version
2.11.0

### Environment
Chrome 58.0.3029.110 (64-bit) on Windows 10

### Reproduction link
[https://codepen.io/anon/pen/gRPojd?editors=0010](https://codepen.io/anon/pen/gRPojd?editors=0010)

### Steps to reproduce
1. Type something in the AutoComplete field
2. Observe the field's value change as you type
3. (Optional: remove the `required` rule, and observe that the value does not change as you type)

### What is expected?
The AutoComplete's value should only change when an option is selected from the dropdown suggestion box because I set the `trigger` option to `onSelect` in `getFieldDecorator`'s options.

### What is actually happening?
The value changes as soon as the user types something. But if you remove the `required` rule, it works as intended.

**Comment by benjycui** [comment]
```diff
form.getFieldDecorator('name', {
  trigger: 'onSelect',
+ validateTrigger: 'onSelect',
  rules: [{required: true}]
})
```

**Comment by benjycui** [comment]
It maybe confusing, but the default `validateTrigger` is `onChange`. When you set rules, Form will listen to `onChange` and validate it while value is changing.

**Comment by WaldoJeffers** [comment]
Thanks for your reply @benjycui, the workaround does work. I didn't expect the value to be validated unless it has already been collected. Maybe `validateTrigger` should default to `trigger`'s value if it is not set by the user (which itself defaults to `onChange`). What do you think?

**Comment by WaldoJeffers** [comment]
@benjycui I have trouble understanding how the `validateTrigger` really works. I set up [this codepen](https://codepen.io/anon/pen/awmVjK?editors=0010) where I just have two inputs which I *don't* want to be validated as the user types. I want to validate them later: `onBlur`, or manually with a `validateFields()` call. But the `validateTrigger` option does not seem to make any difference. The inputs seem to be validated as soon as the user types (green mark appearing on the right). Is there something I don't understand, or is this a bug (should I open another issue)? I've read the docs both on Ant's website, and rc-form's GitHub page but I can't seem to understand.

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/6425#issuecomment-308444899

IMO, your CodePen works fine.

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`, then you can remove `validateTrigger: 'onSelect'`.

**Comment by WaldoJeffers** [comment]
@benjycui Thanks, but as soon as you start typing in one of the inputs [on this CodePen](https://codepen.io/anon/pen/awmVjK?editors=0010), you do see the green valid mark appearing on the right, don't you?

**Comment by benjycui** [comment]
@WaldoJeffers  you should file a new issue, for you are reporting another bug, thanks.

**Comment by WaldoJeffers** [comment]
With pleasure: https://github.com/ant-design/ant-design/issues/6538, thanks.
