### ISSUE TITLE
Website Docs:Colors is broken

### ISSUE THREAD

**Issue by BrodaNoel** [ant-design/ant-design#6426]
### Version
n/a

### Environment
n/a

### Reproduction link
n/a

### Steps to reproduce
n/a

### What is expected?
n/a

### What is actually happening?
Try to open the Color Pallet in https://ant.design/docs/spec/colors, and you won't see anything.

**Comment by afc163** [comment]
@benjycui

**Comment by afc163** [comment]
Thx for reporting.
