### ISSUE TITLE
是否可以将action设置为可选项

### ISSUE THREAD

**Issue by zhu1033527427** [ant-design/ant-design#6427]
### What problem does this feature solve?
关于upload组件，比如我有一个表单，我想点“确定”的时候再整体提交表单，这样可定制性更强，可以参考一下这个组件https://github.com/okonet/react-dropzone

### What does the proposed API look like?
设置action 为可选项，不触发请求

**Comment by yesmeck** [comment]
`beforeUpload` 返回  `false` 即可。

**Comment by afc163** [comment]
@yesmeck Maybe we should add a demo.

**Comment by dengfuping** [comment]
@zhu1033527427 Please refer to the demo https://ant.design/components/upload/#components-upload-demo-upload-manually.
