### ISSUE TITLE
Enable Upload component to be usable for Meteor/NodeJs applications

### ISSUE THREAD

**Issue by enzolutions** [ant-design/ant-design#6430]
### What problem does this feature solve?
Currently, the upload component requires an action URL to process the upload, this approach doesn't work well with NodeJs implementation like NodeJs.

The NodeJS implementation doesn't need external endpoints to process the forms, in the code listed below you could see an example without react or antd , but you could notice how the files/images are process inline and send to internal collections like MongoDB.

```
<input type=”file” name=”…” class=”myFileInput”>
```

And handle the event as follow:
```
Template.Profile.events({
   ‘change .myFileInput’: function(event, template) {
      FS.Utility.eachFile(event, function(file) {
        Images.insert(file, function (err, fileObj) {
          if (err){
             // handle error
          } else {
             // handle success depending what you need to do
            var userId = Meteor.userId();
            var imagesURL = {
              “profile.image”: “/cfs/files/images/“   fileObj._id
            };
            Meteor.users.update(userId, {$set: imagesURL});
          }
        });
     });
   },
```

I don't know if a specific version of this component could create or maybe change the API.

Thanks in advance for taking in consideration this change

### What does the proposed API look like?
- action	Optional Uploading URL	string
- customUploadMethod	override for the default xhr behavior allowing for additional customization and ability to implement your own NodeJS Function	-

**Comment by benjycui** [comment]
You can set `beforeUpload(): false`, so that antd.Upload will not upload file automatically.

**Comment by enzolutions** [comment]
Hi @benjycui,

Thanks for your recommendation, I tried what you said, but false is not possible because looks like the definition expect for a function check the following error.

<img width="515" alt="screen shot 2017-06-12 at 1 55 38 pm" src="https://user-images.githubusercontent.com/907914/27018844-e5324c92-4f76-11e7-8bb1-490389dd0f82.png">

*Warning: Failed prop type: Invalid prop `beforeUpload` of type `boolean` supplied to `Upload`, expected `function`.*

I tried assigning a function that returns false, but that disable the whole upload process as you could see below.

```
const props = {
    name: 'file',
    multiple: true,
    showUploadList: true,
    beforeUpload: function () {return false},
    action: '',
    onChange(info) {
        console.log(info);
        console.log(info.file);
        const status = info.file.status;
        if (status !== 'uploading') {
            console.log(info.file, info.fileList);
        }
        if (status === 'done') {
            message.success(`${info.file.name} file uploaded successfully.`);
        } else if (status === 'error') {
            console.log('error');
            message.error(`${info.file.name} file upload failed.`);
        }
    },
};

<FormItem
    wrapperCol={{ span: 24, offset: 0 }}
>
{<Dragger {...props}>
    <p className="ant-upload-drag-icon">
        <Icon type="inbox" />
    </p>
    <p className="ant-upload-text">Click or drag file to this area to upload</p>
    <p className="ant-upload-hint">Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files</p>
</Dragger>}
</FormItem>
```

Any further recommended would be really appreciated.

**Comment by benjycui** [comment]
Yep, just upload files manually.

**Comment by enzolutions** [comment]
@benjycui but the problem is the files are not queued, so I can't process manually 😢 

I hope you could consider to re-open.

**Comment by benjycui** [comment]
I don't understand, I think this is just a usage question, because Upload works fine with your use case without adding any new API.

**Comment by enzolutions** [comment]
Not really.

Just in case someone else faces this problem. I could use this component in Meteor https://github.com/okonet/react-dropzone

I am still in love with Ant Design.

**Comment by benjycui** [comment]
Pseudo-code:

```jsx
const queue = [];
<Upload beforeUpload={(file) => {
  queue.push(file);
  return false;
}}>

<Button onClick={() => upload(queue)} />
```
