### ISSUE TITLE
Tabs component nested could not operate

### ISSUE THREAD

**Issue by sadmark** [ant-design/ant-design#6431]
### Version
2.11.0

### Environment
windows/mac/antd 2.11.0/chrome/firefox

### Reproduction link
[https://codepen.io/sadmark/pen/KqzNqV](https://codepen.io/sadmark/pen/KqzNqV)

### Steps to reproduce
tabs组件嵌套在一个tabPane中，当被嵌套的tabs组件有很多tabsPane或者tab name很长，而导致宽度很长了以后（超出屏幕范围），被嵌套的tabs组件不能操作。

### What is expected?
被嵌套的tabs组件能够正常操作

### What is actually happening?
被嵌套的tabs组件不能操作

**Comment by benjycui** [comment]
样式问题。
