### ISSUE TITLE
Timeline timestamps

### ISSUE THREAD

**Issue by Sicria** [ant-design/ant-design#6433]
### What problem does this feature solve?
Currently to display a timestamp for a timeline item you need to add it as the content or put it into a tooltip to make it a bit cleaner. It would look nicer and be easier to follow if on the left of the timeline dots it listed the time of the event. You could maybe supply it via a moment object or a string.

### What does the proposed API look like?
``<Timeline.Item date={moment()}>Email sent</Timeline.Item>``

**Comment by benjycui** [comment]
Nope, current API is simple enough, and more flexible than your recommended API.

Anyway, thank you for your advice.
