### ISSUE TITLE
Table components in the pull when the horizontal scroll bar, the header and the table can not be aligned with the situation. There will be animation delay effect

### ISSUE THREAD

**Issue by leesx** [ant-design/ant-design#6439]
### What problem does this feature solve?
In the ipad will appear on this situation, is there any good solution?

### What does the proposed API look like?
Hope that the head and the table as a whole, so that users can not see

**Comment by yesmeck** [comment]
If you're reporting a bug, please use bug template.

**Comment by yesmeck** [comment]
@leesx
