### ISSUE TITLE
Timepicker的时区bug

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#644]
如果浏览器所在的时区不是北京时区，TimePicker取值就不对。例如，我将本机时区修改为New York（EST）时区，通过onChange获得的时间就会有问题。如下：

![image](https://cloud.githubusercontent.com/assets/8615816/11631399/da844350-9ccf-11e5-958b-30be0dde7288.png)

结果显示：11:08:23

设置1:00:00结果获得得值为12:00。目前我只能通过计算当前时区和北京时区差值来重新计算这个时间。

我建议，应该有一个文本值，直接可以获得Timepicker中选择的字符串，这样方便后期处理，也避免了时区问题。

**Comment by mongris** [comment]
我也遇到时区问题，可以通过locale来解决：

```
const timezoneOffset = -(new Date().getTimezoneOffset())

export default React.createClass({
  render() {
    return (
      <Timepicker locale={{timezoneOffset}} />
    )
  },
})
```

如此将按照计算机时间所在时区来进行显示和获值

**Comment by qiaolb** [comment]
@mongris 没有看到Timepicker有locale属性，我试试

**Comment by afc163** [comment]
我修改了时区后，发现输出的和显示的仍然是一致的。

是不是我漏掉了什么？

**Comment by qiaolb** [comment]
@afc163 你可以修改时区后看看这个： http://ant.design/components/timepicker/
基本例子的Console输出。

**Comment by afc163** [comment]
可以使用类似 http://ant.design/components/datepicker/#demo-locale 的 locale 属性来配置时区。

**Comment by qiaolb** [comment]
我测试了，可以使用locale，谢谢。也请更新API文档

**Comment by afc163** [comment]
在 0.11.0 分支上。

**Comment by afc163** [comment]
在 0.11.0 分支上。

**Comment by afc163** [comment]
在 0.11.0 分支上。
