### ISSUE TITLE
DatePicker rangePicker's showTime defaultValue won't work well when reopen it 

### ISSUE THREAD

**Issue by huanhuan129129** [ant-design/ant-design#6440]
### Version
2.11.0

### Environment
crmhome 58.0

### Reproduction link
[https://codepen.io/anon/pen/LLNged?editors=0010](https://codepen.io/anon/pen/LLNged?editors=0010)

### Steps to reproduce
1. open rangepicker ant choose a date
2. reopen rangepicker 
3. choose 2017-6-12 first and choose 2017-6-10

### What is expected?
I get  2017-06-10 00:00:00  2017-06-12 11:59:59

### What is actually happening?
I get  2017-06-10 00:00:00  2017-06-12 00:00:00

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`.
