### ISSUE TITLE
lodash暴露了全局变量_

### ISSUE THREAD

**Issue by zhaozailin** [ant-design/ant-design#6442]
由于客观原因，我的项目里同时使用了backbone和antd，因为backbone依赖underscore，underscore的全局变量为_，引入antd后，由于antd依赖了lodash，导致将原来的_覆盖掉了，lodash和underscore的API并不完全兼容。希望antd在使用lodash时，使用lodash提供的API：_.noConflict()删掉全局变量_，避免与其他插件冲突。
而且我发现antd的package.json申明的不够明确，明明只依赖了lodash.debounce，实际代码却使用了整个lodash插件，是不是这样？

**Comment by afc163** [comment]
No, we don't expose `lodash` to window.

**Comment by zhaozailin** [comment]
如果antd内部没有执行_.noConflict()，那就会暴露出来的，lodash默认会暴露的，实际情况中控制台里也能打印出来，我们打包用的是webpack，跟打包插件有关系吗？

**Comment by afc163** [comment]
#6443
