### ISSUE TITLE
lodash暴露全局变量

### ISSUE THREAD

**Issue by zhaozailin** [ant-design/ant-design#6443]
### Version
2.9.3

### Environment
chrome

### Reproduction link
[http://xxxxx.xxx](http://xxxxx.xxx)

### Steps to reproduce
由于客观原因，我的项目里同时使用了backbone和antd，因为backbone依赖underscore，underscore的全局变量为_，引入antd后，由于antd依赖了lodash，导致将原来的_覆盖掉了，lodash和underscore的API并不完全兼容。希望antd在使用lodash时，使用lodash提供的API：.noConflict()删掉全局变量，避免与其他插件冲突。
而且我发现antd的package.json申明的不够明确，明明只依赖了lodash.debounce，实际代码却使用了整个lodash插件，是不是这样？

### What is expected?
使用lodash提供的API：.noConflict()删掉全局变量，避免与其他插件冲突。

### What is actually happening?
暴露了全局变量

---
虽然你们没有手动暴露全局变量，但是lodash默认会暴露的！

**Comment by yesmeck** [comment]
讲道理  window 上的变量是影响不到 antd 里的变量的，都是在模块里的。

**Comment by yesmeck** [comment]
> 而且我发现antd的package.json申明的不够明确，明明只依赖了lodash.debounce，实际代码却使用了整个lodash插件，是不是这样？

并不是。

建议再排查下别的原因吧。

**Comment by zhaozailin** [comment]
我写了个demo，只引用了lodash4.x的，用webpack打包后，在控制台都能打印出_，这说明lodash默认就会暴露出全局变量啊，如果antd没有执行noConflict()就会暴露出来啊，而且这个API就是为了解决这个问题的，不然为什么会有这个API呢？你问下你们的核心开发吧

**Comment by yesmeck** [comment]
https://unpkg.com/lodash.debounce@4.0.8 不会全局暴露的。

**Comment by henryzp** [comment]
@yesmeck ，我看dist目录下面的antd.js，里面确实能搜索到

```
root._
```

**Comment by yesmeck** [comment]
确实有组件引了整个 lodash.

**Comment by henryzp** [comment]
@yesmeck ，能不能修改成"lodash/xxx"的形式？

感觉工具类的方法一般用到的也不会太多吧？

**Comment by afc163** [comment]
...机器人怎么会说这样的话的。

**Comment by yesmeck** [comment]
我回错邮箱了。。。

**Comment by afc163** [comment]
厉害了，AI 道歉了。

**Comment by henryzp** [comment]
@afc163 ,哈哈～～

我觉得当每个人提issue，可以先由AI发一份邮箱：问题正在排队中，请耐心等待...

**Comment by xueqingxiao** [comment]
哈哈哈，机器人好萌。不过的确应该按需引用。

**Comment by afc163** [comment]
Fixed, try reinstall node_modules.

**Comment by zhaozailin** [comment]
3Q
