### ISSUE TITLE
为什么关掉我的issue，你不解决我一直会提的，请端正好态度好吗？

### ISSUE THREAD

**Issue by zhaozailin** [ant-design/ant-design#6446]
### Version
2.9.3

### Environment
chrome

### Reproduction link
[http://xxxx.xxx](http://xxxx.xxx)

### Steps to reproduce
由于客观原因，我的项目里同时使用了backbone和antd，因为backbone依赖underscore，underscore的全局变量为_，引入antd后，由于antd依赖了lodash，导致将原来的_覆盖掉了，lodash和underscore的API并不完全兼容。希望antd在使用lodash时，使用lodash提供的API：.noConflict()删掉全局变量，避免与其他插件冲突。

### What is expected?
.noConflict()删掉全局变量

### What is actually happening?
冲掉了underscore的全局变量

**Comment by yesmeck** [comment]
不要做 spammer 哦。

**Comment by afc163** [comment]
不要和机器人置气..

**Comment by bang88** [comment]
😭

**Comment by afc163** [comment]
#6443
