### ISSUE TITLE
离线使用Icon资源

### ISSUE THREAD

**Issue by sunxfancy** [ant-design/ant-design#645]
请问这里面的字体图标能否离线使用,我在开发桌面应用的时候发现引入css后无法连接到您的cdn,能否告诉我们将资源全部本地化的方法.

**Comment by afc163** [comment]
下载到本地自行部署即可。

https://github.com/ant-design/ant-design/blob/b1773502803ba7404d8162c98b80db1bd2658e24/style/core/iconfont.less#L3-L12

**Comment by builden** [comment]
完美解决在webpack打包，离线iconfont的问题
https://github.com/builden/antd-iconfont
