### ISSUE TITLE
Popover arrow is not centered by using 'arrowPointAtCenter'

### ISSUE THREAD

**Issue by cyyyu** [ant-design/ant-design#6452]
### Version
2.11.0

### Environment
chrome

### Reproduction link
[https://codepen.io/cyyyu/pen/MoevoZ?editors=0010](https://codepen.io/cyyyu/pen/MoevoZ?editors=0010)

### Steps to reproduce
Check out the pen

### What is expected?
should be centered

### What is actually happening?
not

**Comment by afc163** [comment]
It has been fixed in dom-align@1.6.2: https://github.com/yiminghe/dom-align/commit/1dac9d859390a8f7efc209ea4fe1bd44c443b7a6

Try remove `node_modules` and reinstall it.

**Comment by cyyyu** [comment]
@afc163 Great! thx!
