### ISSUE TITLE
Add Tabs RightClick interface?

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#6453]
### What problem does this feature solve?
Want to do 'close all', 'close others' actions when user click the context menuitem showed when mouse right click.

### What does the proposed API look like?
<Tabs onRightClick={this.onTabRightClick} ...

**Comment by benjycui** [comment]
```jsx
<div onRightClick={...}>
  <Tabs />
</div>
```

**Comment by wufeng87** [comment]
` <div onRightClick={...}>`

@benjycui  How do I know which tabItem I clicked?

**Comment by benjycui** [comment]
If you want to do something when right click on tabs' title:

```jsx
<Tabs>
  <Tabs.TabPane tab={<span onRightClick={...} />}>
</Tabs>
```
