### ISSUE TITLE
How to use Breadcrumb with react-router@4

### ISSUE THREAD

**Issue by sundayha** [ant-design/ant-design#6455]
#### Version

2.10.4

#### Environment

mac os chrome 50

**Comment by sundayha** [comment]
@afc163 Is there another way

**Comment by fgiarritiello** [comment]
I understand the example of the breadcrumb with router v4 but how would that work with routes such as this /users/:id/details?

Thanks

**Comment by afc163** [comment]
I think we can try better way: https://stackoverflow.com/a/42773538/3040605

@benjycui

**Comment by FoxxMD** [comment]
I believe https://github.com/svenanders/react-breadcrumbs can be used with Breadcrumb component

**Comment by afc163** [comment]
https://ant.design/components/breadcrumb-cn/#components-breadcrumb-demo-router-4

**Comment by putrairawan992** [comment]
> @fgiarritiello Have a try...
> 
> ```
>     const { location } = this.props;
>     const pathSnippets = location.pathname.split('/').filter(i => i);
>     const extraBreadcrumbItems = [];
>     pathSnippets.forEach((_, index) => {
>       const url = `/${pathSnippets.slice(0, index + 1).join('/')}`;
>       Object.keys(breadcrumbNameMap).forEach((item) => {
>         if (pathToRegexp(item).test(url)) {
>           extraBreadcrumbItems.push(<Breadcrumb.Item key={url}>
>             <Link to={url}>
>               {breadcrumbNameMap[item]}
>             </Link>
>           </Breadcrumb.Item>);
>         }
>       });
>     });
>     const breadcrumbItems = [(
>       <Breadcrumb.Item key="/">
>         <Link to="/">Home</Link>
>       </Breadcrumb.Item>
>     )].concat(extraBreadcrumbItems);
> ```

Where does this breadcrumbs Name Map come from?

**Comment by FoxxMD** [comment]
As a zombie followup for anyone finding this in the future:

* react-router v4/v5 https://github.com/icd2k3/react-router-breadcrumbs-hoc
* react-router v6 https://github.com/icd2k3/use-react-router-breadcrumbs

Minimal setup required (uses hooks) and requires building your own render function so it can be built up with antd breadcrumb components
