### ISSUE TITLE
Input cannot change with redux after input by manual

### ISSUE THREAD

**Issue by luyunfei** [ant-design/ant-design#6458]
### Version
2.11.0

### Environment
chrome

### Reproduction link
[http://no-url.com](http://no-url.com)

### Steps to reproduce
1.
```jsx
<FormItem labelCol={{span: 8}} wrapperCol={{span: 16}} label='sku' colon={false}>
                            {getFieldDecorator('skuCode', {
                                initialValue: filter.skuCode
                            })(
                                <Input onPressEnter={handleSkuCodeListener}  id="skuCode"/>
                            )}
                        </FormItem>
```

2. I input some value
3. I change filter.skuCode in redux  
4. The input value will not be changed

### What is expected?
The input value that show will changed

### What is actually happening?
The input value will not be changed

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
#3311
