### ISSUE TITLE
使用Tabs时，如何在Tabs挂载时自动挂载所有Tab内的内容？

### ISSUE THREAD

**Issue by miaojiuchen** [ant-design/ant-design#6459]
### What problem does this feature solve?
我需要获取子Tab下面一些组件的ref用来在父节点中使用，但是Tabs的Tab是延迟加载的，所有的getref函数只有在组件挂载时才会被调用，所以有什么办法可以让Tabs直接渲染出所有的Tab呢？（这里不需要考虑性能问题）

### What does the proposed API look like?
略

**Comment by miaojiuchen** [comment]
Update：
 I want to gather some children nodes' ref in a parent node, as Tabs' child Pane's render process is lazy load ( when you click one tab, the corresponding TabPane render ) , so the ref function will not be invoked, like "ref={ el => this.xxx = el }", so when you access this.xxx, it's undefined.

I want to know is there some solution that I can render these child Panes in advance?

**Comment by benjycui** [comment]
Try [Tabs.TabPane[forceRender]](https://github.com/react-component/tabs#tabpane).

**Comment by jasonslyvia** [comment]
@benjycui Good one, I believe this should be documented.
