### ISSUE TITLE
Form的textarea无法输入？？

### ISSUE THREAD

**Issue by bryant513** [ant-design/ant-design#646]
**问题描述**

页面中使用了<Input type="textarea" />，但是渲染出来的页面文本域无法输入，在http://ant.design/components/form/ 也无法使用。

**发生环境**

- antd 版本：0.10.4
- 操作系统及版本：OS X EI Capitan
- 浏览器及版本：Chromen Version 47.0.2526.73 (64-bit)
- 在线演示地址：
http://ant.design/components/form/
**重现步骤**

1. http://ant.design/components/form/ 中的文本域一栏输入任何字符

**线上重现演示**

http://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by afc163** [comment]
#589 的改动导致了这个问题。

**Comment by afc163** [comment]
可以先使用 value + onChange 来解决：http://ant.design/components/form/#demo-horizontal-form
