### ISSUE TITLE
Table组件固定列不能动态控制size

### ISSUE THREAD

**Issue by HuMoran** [ant-design/ant-design#6462]
### Version
2.11.0

### Environment
ubuntu 16.04 chrom 版本 51.0.2704.84 (64-bit)

### Reproduction link
[https://codepen.io/HuMoran/pen/GEjNNQ?editors=0011](https://codepen.io/HuMoran/pen/GEjNNQ?editors=0011)

### Steps to reproduce
1、打开提供的代码链接，RUN
2、点击生成的网页中的Small、Middle、Default
3、观察表格Action列的变化

### What is expected?
表格Action列会随着点击动态改变行大小

### What is actually happening?
没有改变

**Comment by yesmeck** [comment]
因为 transition 的原因，导致右边表格同步高度的时候，同步到的是旧的高度，你们业务中有切换表格大小的需求吗？这个不大好修，应该是不常用的场景。

**Comment by benjycui** [comment]
@HuMoran 如果真的有动态修改 size 的需求，如下：

```jsx
<Table key={size} size={size} />
```

**Comment by benjycui** [comment]
> 因为 transition 的原因，导致右边表格同步高度的时候，同步到的是旧的高度，你们业务中有切换表格大小的需求吗？这个不大好修，应该是不常用的场景。

👍

**Comment by benjycui** [comment]
极端场景，还是别搞这么复杂了。

**Comment by afc163** [comment]
```diff
td {
-  transition: all .3s;
+  transition: background .3s;
}
```

**Comment by yesmeck** [comment]
这样就相当于把动画去掉了。

**Comment by afc163** [comment]
或者这里，如果在 transition 的过程中，就去拿 offsetHeight? 

https://github.com/react-component/table/blob/ccd57f677e5bdc4b0b66c8bfad25b342b959a101/src/Table.jsx#L633

**Comment by HuMoran** [comment]
我们现在是直接使用的Small，动态切换的意义也不是特别大
