### ISSUE TITLE
How to set the SubMenu and SubMenu in the option can be selected？

### ISSUE THREAD

**Issue by frankyLHJ** [ant-design/ant-design#6463]
### What problem does this feature solve?
 SubMenu optional

### What does the proposed API look like?
```jsx
<SubMenu onSelected={this.onSelected} key="sub1" title={<span><Icon type="mail" /><span>Navigation One</span></span>}>
          <Menu.Item key="1">Option 1</Menu.Item>
          <Menu.Item key="2">Option 2</Menu.Item>
          <Menu.Item key="3">Option 3</Menu.Item>
          <Menu.Item key="4">Option 4</Menu.Item>
</SubMenu>
```

**Comment by benjycui** [comment]
I don't understand, please provide more information. And what is your use case?

**Comment by frankyLHJ** [comment]
![menu](https://user-images.githubusercontent.com/17977044/27164987-a862fb0a-51c3-11e7-9a67-9c5a90601960.png)
I want the “Submenu” in the figure to look like the “option7” is selected,what should I do？

**Comment by frankyLHJ** [comment]
click "Submenu" to keep the selected state

**Comment by benjycui** [comment]
Why?

Could you show me any other UI library support this feature?

**Comment by frankyLHJ** [comment]
Okay, I know！

**Comment by mhjey** [comment]
Actually there is quiet a lot of use cases for this. 

For example, if you sell different kind of furniture, you have

- Sideboards
-- Highboards
-- Lowboards
-- Sideboards
- Couches
-- 2-Seater
-- 3-Seater
-- L-Couch

and you obviously want to be able to select all the sideboards or all the couches and not just the deepest level

**Comment by yuribit** [comment]
@benjycui, I have a scenario similar to the one described in the [comment above](https://github.com/ant-design/ant-design/issues/6463#issuecomment-387791766), should I open a new issue?
