### ISSUE TITLE
设置scroll属性的Table，header和content的cell无法对齐，有的时候header和content不同步滚动

### ISSUE THREAD

**Issue by DDDBear** [ant-design/ant-design#6464]
### Version
2.11.0

### Environment
Mac  Chrome  58.0.3029.110 (64-bit）react 15.5.4

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=0010](https://codepen.io/benjycui/pen/KgPZrE?editors=0010)

### Steps to reproduce
基本场景就是：
1. 一个有很多cell的table，每个cell都设置了固定宽度，没有fixed的cell
2. table的scroll.x小于所有cell的宽度总和
3. table放置在一个grid容器中

### What is expected?
基本期望：不会出现题目中描述的异常。

长远期望：设置宽度了的table cell就固定所设置的宽度，如果实际容器宽度小于table cell的宽度总和，则出现滚动条。不必设置scroll的具体值。

### What is actually happening?
scroll的x值基本靠懵，header和content的cell无法对齐，有的时候header和content不同步滚动。设置的宽度看起来并没有起到什么实际作用。

---
codepen上很难重现，可能是环境太单纯。。。

**Comment by yesmeck** [comment]
Reproduction link 里面没内容哦。

**Comment by yesmeck** [comment]
After you provide online demo, feel free to reopen this issue.

**Comment by afc163** [comment]
> Tip: user can not reopen issue if administrator close it.

**Comment by yesmeck** [comment]
let us know in a comment if you can provide a online demo, and we'll reopen it. 😄
