### ISSUE TITLE
Compatibility bug

### ISSUE THREAD

**Issue by chengzhenping** [ant-design/ant-design#6471]
### Version
2.10.1

### Environment
windows10  firefox

### Reproduction link
[https://codepen.io/chengzhenping/pen/VWKzJm](https://codepen.io/chengzhenping/pen/VWKzJm)

### Steps to reproduce
use Button Component include Checkbox Component,
in firefox , the checkbox is unclickable

### What is expected?
checkbox in firefox is clickable

### What is actually happening?
unclickable

**Comment by afc163** [comment]
You shouldn't use checkbox inside a button, it is a invalid usage for html: https://stackoverflow.com/questions/31092439/click-on-checkbox-inside-a-button-element-firefox-issue
