### ISSUE TITLE
Anchor Link不能高亮（被选中）

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#6473]
### Version
2.11.0

### Environment
win7 chrome

### Reproduction link
[https://codepen.io/anon/pen/VWKQKb?editors=0010](https://codepen.io/anon/pen/VWKQKb?editors=0010)

### Steps to reproduce
当右侧的可滚动内容在同一页中的时候，点击link，不是active状态。

### What is expected?
希望是active状态，可以不滚动，但是应该要选中吧?

### What is actually happening?
实际没有选中

---
由于codepen中不知道怎么使用anchor，只是简单的描述了下问题的样子，实际点击时不会自动滚动

**Comment by RaoHai** [comment]
https://ant.design/components/anchor-cn/#components-anchor-demo-basic 

demo 里似乎是好的。Anchor 只能对整页生效。

**Comment by forever4313** [comment]
@RaoHai 你看demo整个页面的高度被撑高超过了一屏幕，也超过了 anchor所链接的部分的高度，所以，会有滚动，并选中，
但是，如果跟codepen中的一样，页面没有滚动（左右两部分都没有超过屏幕高度），点击不同的link的话，不滚动是对的，但是对应的link应该高亮才对。目前不会高亮，

**Comment by forever4313** [comment]
能初始化谁被选中最好了~~~~

**Comment by benjycui** [comment]
这个问题可以被修复的，我空了搞下吧。。

**Comment by forever4313** [comment]
@benjycui  求大神修复~~~公司发版比较急。。。

**Comment by benjycui** [comment]
这周可能也没时间做这事，需要大幅度重构，先把想法写成伪代码，空了在做。。

Anchor:

```jsx
class Anchor {
  childContext: {
    registerLink(link) {
      this.links.add(link);
    }
    unregisterLink(link) {
      this.link.remove(link);
    }
    activeLink,
    scrollTo(link) {
      // scroll
      ...
      // onEnd
      activeLink = link
    }
  }
  handleScroll() {
    update(this.activeLink)
  }
}
```

Anchor.Link

```jsx
class Link {
  didMount() {
    this.context.registerLink(this.props.href)
  }
  willUnmount() {
    this.context.unregisterLink(this.props.href)
  }
  render() {
    return <a onClick={this.context.scrollTo(href)} active={this.context.activeLink === href} />
  }
}
```
