### ISSUE TITLE
'./rule/' does not contain an export named 'error'.

### ISSUE THREAD

**Issue by pot-code** [ant-design/ant-design#6474]
### Version
2.11.0

### Environment
win7/58.0.3029.81/react @15.6.1

### Reproduction link
[localhost:3000](localhost:3000)

### Steps to reproduce
```js
import { Button, Form } from "antd";

const FormItem = Form.Item;//bang
```
---
```
./~/async-validator/es/index.js
104:20-25 './rule/' does not contain an export named 'error'.
```

### What is expected?
Compile successfully

### What is actually happening?
Failed to compile

---
Should I post the issue to async-validator but here?

**Comment by benjycui** [comment]
A re-producible repo will be better.

**Comment by pot-code** [comment]
@benjycui https://github.com/pot-code/redux-demo
Having dived into the node_modules/async-validator, noticed that it does NOT include the 'error' export indeed.

**Comment by benjycui** [comment]
I clone your repo and start and view it locally, it works fine:

```bash
git clone git@github.com:pot-code/redux-demo.git
npm i && npm  start
```

Please provide a re-producible steps.

**Comment by pot-code** [comment]
@benjycui I have updated antd by using `yarn --update-interactive` before, having reinstalled antd, everything works fine now, strange though.
