### ISSUE TITLE
Form包装的A组件的form对象 如何在B组件中获取

### ISSUE THREAD

**Issue by aimaodeyuer** [ant-design/ant-design#6476]
### What problem does this feature solve?
跨组件之间的form对象传递

### What does the proposed API look like?
能够跨组件实现获取注册过表单控件的form对象

**Comment by afc163** [comment]
http://react-component.github.io/form/examples/redux.html

使用 redux 结合 mapPropsToFields 把状态保存到全局 store 里。

**Comment by aimaodeyuer** [comment]
@afc163 dva有封装实现这种操作吗?
感谢。

**Comment by afc163** [comment]
dva 和 redux 没啥区别，都一样。

**Comment by aimaodeyuer** [comment]
好的，我试下，谢谢您！
