### ISSUE TITLE
Autocomplete insert result rather then replace the entire field with the result

### ISSUE THREAD

**Issue by edencorbin** [ant-design/ant-design#6478]
### What problem does this feature solve?
This solves snippet style insertion of preset data values into input and text areas.

### What does the proposed API look like?

```
<AutoComplete dataSource={dataSource} insertResult: true/>
```

**Comment by afc163** [comment]
https://ant.design/components/mention

**Comment by edencorbin** [comment]
Perfect I overlooked this, and yes, just perfect.
