### ISSUE TITLE
integrating ant design with typescript. 

### ISSUE THREAD

**Issue by colinshen** [ant-design/ant-design#6480]
### Version
2.11.0

### Environment
windows10, chrome

### Reproduction link
[https://github.com/wmonk/create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript)

### Steps to reproduce
I'm trying to working on how to integrate ant with typescript, and using create-react-app-typescript to create the app.
several things I did:
1. edit webpack.dev.js
```
{
        test: /\.(ts|tsx)$/,
        include: paths.appSrc,
        loader: require.resolve('ts-loader'),
        options: {
          plugins: [
            ['import', { libraryName: 'antd', style: true }]
          ]
        }
      },
```
2. following the documentation of customize them to configure less in webpack.dev.js
3. configure tsconfig.js
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}
```
with the config above, I also need to ``` @import '~antd/dist/antd.css';``` in app.css because it seems like import loader doesn't work, and I also got the warning:```You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.```
however, If I follow the docs, change ts-config
```
"jsx": "preserve"
```
I got compile error
```
Failed to compile.

./src/index.tsx
Module parse failed: D:\codes\uhccj\uhccj-dashboard\node_modules\ts-loader\index.js??ref--4!D:\codes\uhccj\uhccj-dashboard\node_modules\tslint-loader\index.js!D:\codes\uhccj\uhccj-dashboard\src\index.tsx Unexpected token (8:16)
You may need an appropriate loader to handle this file type.
| var registerServiceWorker_1 = require("./registerServiceWorker");
| require("./index.css");
| ReactDOM.render(<App_1.default />, document.getElementById('root'));
| registerServiceWorker_1.default();
```

### What is expected?
any other suggestions that integrates ant with typescript?

### What is actually happening?
something wrong with babel-plugin-import that can not load css or less style.

**Comment by afc163** [comment]
Is this document helpful? https://github.com/ant-design/ant-design/pull/6193/files

**Comment by colinshen** [comment]
@afc163
got this error
```
multi ./~/react-dev-utils/webpackHotDevClient.js ./config/polyfills.js ./~/react-error-overlay/lib/index.js ./src/index.tsx
Module not found: Can't resolve 'ts' in 'D:\codes\uhccj\uhccj-dashboard'
```

**Comment by colinshen** [comment]
I found the solution, after doing [this ](https://github.com/ant-design/ant-design/pull/6193/files)
we also need to add babel-loader
```
 {
        test: /\.(ts|tsx)$/,
        include: paths.appSrc,
        loader:  [require.resolve('babel-loader'), require.resolve('ts-loader')]
      },
```

**Comment by colinshen** [comment]
@afc163 突然发现新的问题,会出现warnning,初创的项目是不存在的。不import ant也会出现这样的问题，你能帮忙看看是不是webpack或者其他的配置导致的?
```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

**Comment by benjycui** [comment]
@colinshen 你按 https://github.com/ant-design/ant-design/pull/6193 操作时，碰到坑的话，建议到那个 PR 下面回复一下，方便我们更新。

**Comment by benjycui** [comment]
warning 的问题，麻烦提供可重现 repo。

**Comment by colinshen** [comment]
@benjycui 配置基本就是按照文档，但是如果用 babel!ts会报错.
```
multi ./~/react-dev-utils/webpackHotDevClient.js ./config/polyfills.js ./~/react-error-overlay/lib/index.js ./src/index.tsx
Module not found: Can't resolve 'ts' 
```
所以我用的是babel-loader和ts-loader。我也不确定到底是那里导致warning的问题，不import button也会抛出warnning。。但是希望你们给看看，如果能解决的话完善一下文档，我想应该会更好。

**Comment by benjycui** [comment]
> warning 的问题，麻烦提供可重现 repo。

下面这个明显不是你碰到 warngin 的问题的重现 repo

> https://github.com/wmonk/create-react-app-typescript
