### ISSUE TITLE
图标字体为什么是引用的在线版？

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design#6481]
### Version
2.11.0

### Environment
chrome latest

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
webpack打包后，访问项目首页，会请求https://at.alicdn.com/t/font_0qcp222wvwijm7vi.woff

### What is expected?
希望能使用本地版的字体文件

### What is actually happening?
系统部署在院内的，怎么办？

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started-cn#%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98%E5%92%8C%E5%AD%97%E4%BD%93

RTFM
