### ISSUE TITLE
当menu组件的submenu树由方法生成时，defaultOpenKeys属性失效

### ISSUE THREAD

**Issue by Cnax** [ant-design/ant-design#6485]
### Version
2.10.4

### Environment
系统：macOS Sierra 10.12.5       浏览器版本：  58.0.3029.110 (64-bit)

### Reproduction link
[https://github.com/Cnax/antd-menu.git](https://github.com/Cnax/antd-menu.git)

### Steps to reproduce
App.js 中menu的子元素由getMenus(menuConfig)生成和直接写在里面的区分查看代码在页面中的表现

### What is expected?
由getMenus(menuConfig)生成的子元素和直接写在里面的子元素，defaultOpenKeys属性应该都有效

### What is actually happening?
由getMenus(menuConfig)生成的子元素时，defaultOpenKeys属性失效

**Comment by yesmeck** [comment]
因为你生成的 key 是 `/sub2`。
