### ISSUE TITLE
Incorrect Menu documentation

### ISSUE THREAD

**Issue by nvana** [ant-design/ant-design#6488]
### Version
2.11.0

### Environment
Documentation

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/menu/index.en-US.md](https://github.com/ant-design/ant-design/blob/master/components/menu/index.en-US.md)

### Steps to reproduce
Nothing

### What is expected?
Change eventKey by key

### What is actually happening?
In the documentation : https://ant.design/components/menu/#Menu.SubMenu-props
The Menu.SubMenu props have an error in onTitleClick parameter, it's key and not eventKey.

---
Thanks for your work

**Comment by paranoidjk** [comment]
Would you like to give us a PR？

**Comment by nvana** [comment]
It's done
