### ISSUE TITLE
Remove prefix when selecting an option from mention

### ISSUE THREAD

**Issue by edencorbin** [ant-design/ant-design#6491]
### What problem does this feature solve?
The api does not support removing the prefix typed to be presented with mention options. In the use case of snippet style entries, the preceding prefix would not be wanted in the outputted text. This option, if added, should default to false.

### What does the proposed API look like?
```
<Mention removePrefix: true/>
```

**Comment by benjycui** [comment]
This is Mention... Not an Editor

**Comment by benjycui** [comment]
cc @RaoHai

**Comment by edencorbin** [comment]
Perhaps there is an alternate approach I'm not considering, what I would like to achieve is nearly identical to mention, with the single exception being that I would like to remove the prefix / characters used to bring up the mention options / data source. Is there a way to refer to the inner contents of the Mention element on the onSelect callback, so that I could manually scan for the characters and remove them?

**Comment by RaoHai** [comment]
`<Mention />` currently use a space letter and a prefix to mark a mention trigger, so if we remove prefix after select, the word you just selected will be identify as a plain text.

**Comment by afc163** [comment]
Try `prefix=""`?

**Comment by edencorbin** [comment]
@afc163 the problem is I don't want to show the options without the prefix, having "" works but will always show the options upon a space entry. @RaoHai I'm not sure I understand, removing prefix after selected is exactly what I want. Is there any way to reference/modify the <Mention /> contents manually?

**Comment by afc163** [comment]
That is a strange requirement..

**Comment by edencorbin** [comment]
@afc163 the use case is to provide a library of quick entry snippets. We allow the user to type a short code, the prefix followed by a user supplied shortcode and a larger snippet is inserted in place of this code. It works almost perfectly with mention, setup similar to the Customize Suggestion example, as the output can be different then the input, only issue I have is removing the prefix. Does this requirement make more sense with this explanation?

**Comment by benjycui** [comment]
@edencorbin maybe you should use a code editor, something like https://github.com/Microsoft/monaco-editor

**Comment by edencorbin** [comment]
I'll look into that. One question I'm still unclear on, how can I access and modify the contents of a mention input directly via code/api? Perhaps if I implement it as Controlled Form element that will be possible. We can close this thread, thank you.

**Comment by benjycui** [comment]
Close now, for this feature doesn't belong to Mention.
