### ISSUE TITLE
TypeError: Cannot read property 'getFieldDecorator' of undefined

### ISSUE THREAD

**Issue by devalexandre** [ant-design/ant-design#6493]
### Version
2.11.0

### Environment
"antd": "^2.11.0",     "react": "^15.6.1",

### Reproduction link
[https://gist.github.com/devalexandre/e9da23a6f0cfa231e852fef5842e30b4](https://gist.github.com/devalexandre/e9da23a6f0cfa231e852fef5842e30b4)

### Steps to reproduce
trying use a form

### What is expected?
trying use a form

### What is actually happening?
trying use a form, but don't work

---
TypeError: Cannot read property 'getFieldDecorator' of undefined

**Comment by hansnow** [comment]
component `Contato` should be wrapped by `Form.create()()`, so change L53 to `export default Form.create()(Contato)`
