### ISSUE TITLE
Form初始化数据的时候，不能根据数据内容显示隐藏响应的字段，必须手动触发

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#6496]
### Version
2.11.0

### Environment
Chrome

### Reproduction link
[https://codepen.io/Midqiu/pen/GENdPj?editors=0011](https://codepen.io/Midqiu/pen/GENdPj?editors=0011)

### Steps to reproduce
重现链接里面的的表单逻辑：当age大于18的时候，显示name字段。
但是初始化的时候，age是22，理论上应该直接就显示name字段的，但是没有。

### What is expected?
刚开始，当age大于18的时候直接显示name字段。

### What is actually happening?
必须手动，修改age字段，先改成其他，再改成22，name字段就可以显示了？！

**Comment by Midqiu** [comment]
需求还得完成，暂时先这么hack掉了……

![image](https://user-images.githubusercontent.com/5728399/27220638-7027a8e4-52b8-11e7-84df-116a37e97be6.png)

**Comment by afc163** [comment]
也可以这么解决：https://codepen.io/anon/pen/JJbwaq?editors=0011

**Comment by afc163** [comment]
很难说这算不算 bug，未经 getFieldDecorator 绑定过的表单项是拿不到值的，初次取值应该直接从 props 里取。先关了。

**Comment by yesmeck** [comment]
`getFieldValue('age')` 是能拿到的。

**Comment by afc163** [comment]
https://github.com/react-component/form/issues/38 

理论上也不应该拿到。

**Comment by benjycui** [comment]
只要保证 `getFieldValue` 在 `getFieldDecorator` 之后调用就可以了：

```bash
<Form >
  <FormItem label="年龄" hasFeedback >
    {getFieldDecorator('age' ,{})(<Input type="number" />)}
  </FormItem>
        
  {getFieldValue('age')>18 ? <FormItem label="用户名" hasFeedback >
    {getFieldDecorator('name', {})(
      <Input placeholder="最少2位" />
     )}
  </FormItem>:""}
</Form>
```

**Comment by benjycui** [comment]
虽然在编写代码时，会觉得没有 `getFieldDecoraltor` 就不能 `getFieldValue` `setFieldsValue` 这限制没必要。

但是稍微思考一下，一个变量没被定义，本来就无法被赋值或者读取的，从理性角度判断，现在的行为是合理的。
