### ISSUE TITLE
Test `onBlur` using enzyme with `Select` component

### ISSUE THREAD

**Issue by vamsiampolu** [ant-design/ant-design#6497]
### Version
2.11.0

### Environment
jest

### Reproduction link
[https://stackoverflow.com/questions/44579303/need-to-test-that-a-handler-prop-is-called-by-a-composite-react-component](https://stackoverflow.com/questions/44579303/need-to-test-that-a-handler-prop-is-called-by-a-composite-react-component)

### Steps to reproduce
Hey, I want to test that onBlur function is invoked on Select component, to look at a similar problem that I was trying to discuss, look at:
https://stackoverflow.com/questions/44579303/need-to-test-that-a-handler-prop-is-called-by-a-composite-react-component
My component actually looks like:

```js
  import {Select} from 'antd'

class MyComponent extends React.Component {
   onInputBlur = () => {
        this.props.onBlur()
   }

render() { 
   return (<Select onBlur={onBlur} {...rest} />)
}
```

I have simplified the code for just showing the problem. I tested the onChange using a props of the Select only. I need to trigger a blur on the component. How can I do that using the current implementation of rc-select.
Thanks?

### What is expected?
I expect to be able to blur the `select` and test that onBlur was called

### What is actually happening?
I don't have access to the `select` or something similar, how can I test that?

**Comment by yesmeck** [comment]
See https://github.com/react-component/select/blob/master/tests/Select.spec.js#L323

**Comment by vamsiampolu** [comment]
I solved this in a conversation with @ljharb from airbnb on the enzyme gitter channel. The answer looks like:

https://github.com/airbnb/enzyme/issues/208
