### ISSUE TITLE
Some parts can't be internationalized in RangePicker and DatePicker.

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#6502]
### Version
2.11.0

### Environment
macOS 10.12.4 (16E195), Chrome 59.0.3071.86, react 15.4.2

### Reproduction link
[https://codepen.io/leadream/pen/LLbozN](https://codepen.io/leadream/pen/LLbozN)

### Steps to reproduce
Just click the pickers.
In the picker panel, the week and month are not translated.

![image](https://user-images.githubusercontent.com/12868055/27228408-143566e4-52da-11e7-9ae0-b0167b1d12d1.png)

### What is expected?
The contents are internationalized correctly.

### What is actually happening?

The week and month are displayed in Russian while the locale is set to jp.
In my own project, I set the locale to en but it's displayed in zh.

---

**Comment by benjycui** [comment]
See: https://ant.design/components/date-picker/#API

Sorry, I knew it's confusing..

**Comment by leadream** [comment]
Yeah, solved it just by setting the moment locale at first. Thanks!
