### ISSUE TITLE
Select should cache the selected option to prevent option value exposed

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#6505]
##### Here's the scene:

I created a search select component.
Searched result is the option items data source.

![image](https://user-images.githubusercontent.com/9346008/27250297-239b531c-535e-11e7-8701-127970443bd3.png)

![image](https://user-images.githubusercontent.com/9346008/27250336-52f0a378-535f-11e7-9974-c93b3c949111.png)

But after selected an option, and input another keywords, get the new result that doesn't contain the previous selected item.

![image](https://user-images.githubusercontent.com/9346008/27250300-3857d2e4-535e-11e7-85d3-dbd9e809fdf5.png)

**Then I delete all the input, it still fetching the new data with empty keyword.
But at this moment, rendered options are still come from the previous result, until we get result that contains the selected item.**

![image](https://user-images.githubusercontent.com/9346008/27250316-9011ac9e-535e-11e7-88c3-da5e0a034bd7.png)

So the Select component shows the selected option value barely, rather than the original Option component.

##### Online demo:
[http://jsfiddle.net/SebastianBlade/3nr3wwug/52/](http://jsfiddle.net/SebastianBlade/3nr3wwug/52/)

### What does the proposed API look like?
I think there is a way to cache the selected item data to prevent the above situation.

**Comment by yesmeck** [comment]
![select mov](https://user-images.githubusercontent.com/465125/27250529-ffbae82a-5364-11e7-9f48-19576edde393.gif)

I think's it works correctly?

**Comment by blade254353074** [comment]
I think display value directly is not perfect.

**Comment by yesmeck** [comment]
It's a intended behavior, value only change after you select other option. I you want clean the selected value, you can set `value` to a empty string after user empty the input.

**Comment by yesmeck** [comment]
```javascript
  onSearch = q => {
    if(q === '') { this.setState({ value: '' }) }
    this.getData(q)
  }
```

**Comment by blade254353074** [comment]
...This method can't resolve the problem in these state:

1. Slow network
    1. Search `Safari` & select the `Safari`.
    2. Search `Chrome` & delete the input.
    3. Submit form quickly before empty keyword searching request response.

2. API server only return limited data (common)
    1. Search `Safari` & select the `Safari`.
    2. Search `Chrome` & delete the input.
    3. But with empty keyword, api server just return 10 item, and doesn't contain `Safari`

🙂

**Comment by blade254353074** [comment]
I just came up with a new solution: [http://jsfiddle.net/SebastianBlade/bs6bq3jz/1/](http://jsfiddle.net/SebastianBlade/bs6bq3jz/1/)

![image](https://user-images.githubusercontent.com/9346008/27254242-60ff4d90-53b7-11e7-8544-95cf9d0b9e07.png)

```javascript
onSearch = q => {
  if(q === '') this.onChange(null)
  this.getData(q)
}
```

However, I don't know this solution is conformed with the UX of the ant-design.
We can discuss it~

**Comment by blade254353074** [comment]
Any ideas?

**Comment by benjycui** [comment]
No special idea. According to me, both of your CodePens works fine..

**Comment by yesmeck** [comment]
Close since this issue is inactive for a long time, ping me if you have further thoughts can improve this behavior.
