### ISSUE TITLE
zebra-striped of table

### ISSUE THREAD

**Issue by luyunfei** [ant-design/ant-design#6506]
### What problem does this feature solve?
Would you support zebra-striped of table? which means different backgroud color between two lines

### What does the proposed API look like?
please see the attach file

![2017-06-17_23-09-00](https://user-images.githubusercontent.com/4887426/27254020-12e64bd6-53b2-11e7-9e2b-2d22dea59789.png)

**Comment by afc163** [comment]
No plan for this, you can use `rowClassName` to do it.
