### ISSUE TITLE
使用 koala 编译 less 出错 ，提示 变量@#ffc0cb-6 未定义

### ISSUE THREAD

**Issue by lanten** [ant-design/ant-design#6509]
### Version
2.11.0

### Environment
win10 ， electron

### Reproduction link
[https://github.com/lanten/electron-antd/blob/master/theme/less/antd.less](https://github.com/lanten/electron-antd/blob/master/theme/less/antd.less)

### Steps to reproduce
使用 koala 编译时报错

提示 `\lib\tag\style\index.less` 中的变量 ` @#ffc0cb-6` 未定义

详细内容：
```
SyntaxError: variable @#ffc0cb-6 is undefined in D:\desktop\GitHub\electron-react-redux-boilerplate\node_modules\antd\lib\tag\style\index.less:119:2
118 
119   .make-color-classes();
120 }
```

我试过删除第 119 行代码，编译可以成功

### What is expected?
可以使用 koala 工具成功编译less
因为某些原因我不想使用webpack，koala 可以帮助我定制多个主题

### What is actually happening?
编译失败

**Comment by afc163** [comment]
Maybe you should report this to koala tool?

**Comment by lanten** [comment]
看样子是我错了，我本以为这和工具没有关系，毕竟它一直工作良好，直到我刚刚用命令行编译了一下，编译很顺畅，
但是我觉得 `\lib\tag\style\index.less` 里面或许有某处不规范的地方，

很抱歉打扰到您

**Comment by afc163** [comment]
> 或许有某处不规范的地方

能帮我们看看么，我们对 koala 工具不是很了解。

**Comment by lanten** [comment]
我仔细察看后发现这不是antd的问题

这个工具默认是使用ruby编译的，编译结果可能有些差异，我设置成lessc编译器后问题解决了

请关闭这个lssues吧~
