### ISSUE TITLE
Please add `disabled` to the property table of Radio.Group component

### ISSUE THREAD

**Issue by vamsiampolu** [ant-design/ant-design#6510]
### What problem does this feature solve?
I found that the antd Radio.Group component has an interface that extends the following interface:

```js
export interface AbstractCheckboxGroupProps {
  prefixCls?: string;
  className?: string;
  options?: Array<CheckboxOptionType | string>;
  disabled?: boolean;
  style?: React.CSSProperties;
}
```

like this:

```js
export interface RadioGroupProps extends AbstractCheckboxGroupProps {
  defaultValue?: string | number;
  value?: string | number;
  onChange?: React.FormEventHandler<any>;
  size?: 'large' | 'default' | 'small';
  onMouseEnter?: React.FormEventHandler<any>;
  onMouseLeave?: React.FormEventHandler<any>;
}
```

I did not find this information in the documentation of RadioGroup or CheckboxGroup, please update the docs to reflect the existence of this property. I am happy to do a PR if you can help me understand how you generate the docs.

### What does the proposed API look like?
Documentation update

**Comment by benjycui** [comment]
Thanks!
