### ISSUE TITLE
IE9 下 Spin 组件报错

### ISSUE THREAD

**Issue by xpal7512** [ant-design/ant-design#6512]
### Version
2.11.1

### Environment
Win7、IE9、React@15.5.4

### Reproduction link
[https://codepen.io/anon/pen/ZyeYVr?editors=001](https://codepen.io/anon/pen/ZyeYVr?editors=001)

### Steps to reproduce
```javascript
const { Spin } = antd;

ReactDOM.render(
  <div>
    <Spin spining={true}>测试文字</Spin>
  </div>
, document.getElementById('app'));
```

### What is expected?
兼容 IE9

### What is actually happening?
Spin 组件在 IE9 下报错，报错信息：无法获取未定义或 null 引用的属性“children”

**Comment by afc163** [comment]
It works.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/507615/27273248-c43514ea-5500-11e7-9c44-c243cd8d89e9.png">

**Comment by xpal7512** [comment]
@afc163 官网的我在 IE9 里打开也是正常的。但是自己项目中却不行，IE10、IE11 不报错。antd 官网里的各种 polyfill 也已经添加了。

**Comment by afc163** [comment]
给个本地文件包或者在线地址？

**Comment by xpal7512** [comment]
@afc163 https://xpal7512.github.io/test/ 打了个包放到线上了

**Comment by afc163** [comment]
把源码包整个给出来吧，看不出问题在哪。

**Comment by xpal7512** [comment]
@afc163 经过排除，我将下面 html 模板中的 polyfill 代码去掉之后，BUG 解决，具体原因不明

`
    
    <script src="https://as.alipayobjects.com/g/component/??es6-shim/0.35.1/es6-sham.min.js,es6-shim/0.35.1/es6-shim.min.js"></script>`

**Comment by afc163** [comment]
是否还使用了 babel-runtime 或者 babel-polyfill ?

**Comment by xpal7512** [comment]
有 babel-polyfill ，是否是重复引用的问题？

**Comment by afc163** [comment]
@kdepp 来个 PR 优化下文档如何？

**Comment by SynChron1zed** [comment]
@xpal7512  hello 你的 babel-polyfill 是这样配置的吗？"entry": ["babel-polyfill","src/index.js"]？ 我的提示"Promise"未定义 有遇到吗

**Comment by xpal7512** [comment]
@SynChron1zed 试试
entry: {
    polyfill: 'babel-polyfill',
    app: 'src/index.js'
}

**Comment by SynChron1zed** [comment]
@xpal7512  貌似不行  加引号不加引号我都试了  编译都报错  "Promise"未定义 这个问题 我找到了大概是什么原因 应该是fetch 引起的  
![image](https://user-images.githubusercontent.com/18717051/34161387-704eafda-e50b-11e7-8235-afb407e38468.png)
这样可以解决 但是进去页面后 导航栏切换 出现了find属性对象不支持

**Comment by whenTheMorningDark** [comment]
![image](https://user-images.githubusercontent.com/30688843/71083241-84e78880-21cd-11ea-808e-b2f14d32b33c.png)
我在ie11版本下遇到这个问题 ie打不开 有大哥能解决的吗？
