### ISSUE TITLE
mapPropsToFields 不能传递数组

### ISSUE THREAD

**Issue by littlee** [ant-design/ant-design#6513]
### Version
2.11.0

### Environment
macOS 10.12.5     Chrom 59

### Reproduction link
[https://codepen.io/littlee/pen/gRmpZG](https://codepen.io/littlee/pen/gRmpZG)

### Steps to reproduce
请看codepen链接，我直接进行渲染，无需任何步骤

### What is expected?
input 可以被赋值

### What is actually happening?
input 没有被赋值

**Comment by xueqingxiao** [comment]
```js
const { getFieldValue } = this.props.form;
getFieldValue('links');
```

**Comment by yeluolei** [comment]
同样遇到这个问题，rc-form已经支持这样嵌套了，getFieldDecorator不支持，感觉很不方便

**Comment by kennylbj** [comment]
Can be resolved by
```js
return fields.reduce((all, field) => ({...all, ...field}), {})
```

**Comment by benjycui** [comment]
嵌套是支持 name 嵌套(`user.name`)，而非可以从某个 field 中读取一部分。
