### ISSUE TITLE
checkboxGroup options添加自定义属性的问题

### ISSUE THREAD

**Issue by biuge** [ant-design/ant-design#6514]
### What problem does this feature solve?
在用到checkboxGroup时，会遇到选项的值 关联别的数据 options中只有label和value两个值不够用  需要加上一些自己定义的属性

### What does the proposed API look like?
比如options={label:'苹果',value:'1',type:'水果'} 我想在checkGroup onchange事件里获取当前选项的type 来做另外一些操作

**Comment by xueqingxiao** [comment]
```js
const options = [{label:'苹果',value:'1',type:'水果'},{label:'梨子',value:'2',type:'水果'}];

onChange = (options) => value ={
  var opt = options.filter(opt => opt.value === value)[0];
  // do you work
}

<CheckboxGroup options={options} defaultValue={['1']} onChange={onChange(options)} />
```
