### ISSUE TITLE
Something wrong with fixed columns and header

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6515]
Ref: https://ant.design/components/table/#components-table-demo-fixed-columns-header

![image](https://user-images.githubusercontent.com/3580607/27273758-12468e96-5503-11e7-92b7-1438b035d2b6.png)

![image](https://user-images.githubusercontent.com/3580607/27273773-202ab7a8-5503-11e7-8ee5-05ca857e3d07.png)

OS: Mac OS

Browser: 

![image](https://user-images.githubusercontent.com/3580607/27273823-44ec0f7e-5503-11e7-9c0c-5db5ca27fb7b.png)

Only can re-produce in Dell screen which is connected to Mac. If we view the same demo in the same machine but with Mac's own screen, it works fine.

**Comment by benjycui** [comment]
I try to resize browser, it seems that it is not relative to browser's width.

**Comment by yesmeck** [comment]
@benjycui 是说滚动条的位置不对？

**Comment by benjycui** [comment]
上下出现了两个滚动条，并且这个是要在特定显示屏才能看的到。

上班后再当面看吧，也是个诡异的问题。

**Comment by ApacheEx** [comment]
The same issue here. I can reproduce it with this example:
https://codesandbox.io/s/38rjlrl006

A table with rowSelection + fixed header / columns.

My browser version:
![image](https://user-images.githubusercontent.com/1918108/36366568-6a349fac-1557-11e8-9c78-7a00e31c286e.png)

**Comment by zhengqingxin** [comment]
有解决方案了吗？

**Comment by AngusFu** [comment]
Seems this issue is still not resolved, since more than one year ago.
May be i should just try something like [react-virtualized](https://bvaughn.github.io/react-virtualized/)?  The migration work is not easy however.

**Comment by afc163** [comment]
@zombieJ Weird and nice workaround!

**Comment by AngusFu** [comment]
V3.9.2 fixed the extra scrollbar in table header.

But seems the left fixed column(s)  (`.ant-table-fixed-left > .ant-table-body-outer`) was still not fixed as described in #12139.

May be you should checkout the demo given in #12139: https://codepen.io/AngusFu/pen/yxPgXY

![image](https://user-images.githubusercontent.com/8180186/45271417-6a5a3600-b4d9-11e8-87f2-b5358d073241.png)

**Comment by afc163** [comment]
@andriijas You can test it and send us PR.

**Comment by sjdeak** [comment]
@afc163 coming from #13421, this problem still exists in the 3.11.0 official demo, even if i try the workaround(opacity: 0.9999), anyone can give a hand?

![image](https://user-images.githubusercontent.com/8575264/49484891-a5b79700-f873-11e8-9705-e38dc51df81b.png)

**Comment by ethanysc** [comment]
`.ant-table-fixed-header .ant-table-scroll .ant-table-header {
    overflow: hidden !important;
}`

**Comment by sashiksu** [comment]
I am encountering a similar issue with version "antd": "^4.20.4". However, the behavior seems slightly different on my end. When viewing on small screen sizes, particularly with a resolution of 1920x1080 and a scale of 125%, an additional scrollbar appears.

This additional scrollbar manifests between the table body (above the rows), and as I scroll down, it remains fixed at the bottom of the table until I scroll back up. Please refer to the attached image for a visual reference.
Check the below image.
![image](https://github.com/ant-design/ant-design/assets/20171631/fa23adf6-dcac-49dc-b6de-78de100cb0f9)

Additionally, the second scrollbar at the bottom becomes unresponsive, and I can only scroll using the top scrollbar. Interestingly, when I click on either of these scrollbars, the second scrollbar disappears, and the table view returns to normal functionality.

**Comment by dskiba** [comment]
> I am encountering a similar issue with version `"antd": "^4.20.4"`. However, the behavior seems slightly different on my end. When viewing on small screen sizes, particularly with a resolution of 1920x1080 and a scale of 125%, an additional scrollbar appears.
> 
> This additional scrollbar manifests between the table body (above the rows), and as I scroll down, it remains fixed at the bottom of the table until I scroll back up. Please refer to the attached image for a visual reference. Check the below image. ![image](https://private-user-images.githubusercontent.com/20171631/338476569-fa23adf6-dcac-49dc-b6de-78de100cb0f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzAyOTYsIm5iZiI6MTcyODU2OTk5NiwicGF0aCI6Ii8yMDE3MTYzMS8zMzg0NzY1NjktZmEyM2FkZjYtZGNhYy00OWRjLWI2ZGUtNzhkZTEwMGNiMGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE0MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNzNiZGQ4ZWJhNDNlN2RhMjA5YTQ0NDIxMmQ1ZTNmYmU1OTQ3MjRlYjdlMGMwNWRiNDk5MThmYjVjNWJjOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jFT_dxkoe22W3mjY-u11KxdBur-SUczQXJaER4X4lkA)
> 
> Additionally, the second scrollbar at the bottom becomes unresponsive, and I can only scroll using the top scrollbar. Interestingly, when I click on either of these scrollbars, the second scrollbar disappears, and the table view returns to normal functionality.

Temp fix for that is 
```
.ant-table-sticky-scroll {
  display: none !important;
}
```
and I use 
```
...
  scroll: { x: 'max-content' },
  ...
  ```
