### ISSUE TITLE
0.9.x 升级到 0.10.x 使用新的打包工具打包完成后访问报Uncaught ReferenceError: antd is not defined

### ISSUE THREAD

**Issue by light-night** [ant-design/ant-design#652]
使用新的打包工具atool-build打包完成后生成common.js & main.js，依次引入，报antd未定义，怎么解决此问题

**Comment by afc163** [comment]
请给出重现步骤。是否是按照 http://ant.design/docs/introduce 的方式进行开发？

**Comment by light-night** [comment]
0.9.x的写法
var Validation = antd.Validation;

0.10.x的写法
import { Datepicker } from 'antd';

是否升级写法才能被新的打包工具所识别

**Comment by afc163** [comment]
不要用全局变量的方式。

用 ES2015 的方式书写，webpack 进行打包引用。

**Comment by light-night** [comment]
0.9.x会在header中引入编译完的antd文件
