### ISSUE TITLE
Table的data值出现null，会影响整个表格的数据显示

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#6520]
**Version**

2.11.0

**Environment**

Windows 10 专业版 64位，chrom 版本 58.0.3029.110 (64-bit)

**Reproduction link**

https://codepen.io/anon/pen/PjpNRj?editors=0010

**Steps to reproduce**

1、打开提供的代码链接，Run
2、修改 data的address的值为null
3、观察表格是否显示

**What is expected?**

表格能显示

**What is actually happening?**

不显示

**Comment by ybning** [comment]
I don't think it's the problem here
```
{
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
  render: (text, record)=>{
    return text.intro;         
  }
}
```

**Comment by benjycui** [comment]
Actually, the problem **is**  here: 

```jsx
{
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
  render: (text, record)=>{
    return text.intro;         
  }
}
```

**Comment by ybning** [comment]
```
{
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
  render: (text, record)=>{
    return text.intro;         
  }
}
```
If the value is null, the console displays  errors.
But no errors, the table is hidden.

**Comment by afc163** [comment]
```diff
- text.intro 
+ text && text.intro
```

**Comment by ybning** [comment]
I accept your answer
But it's not perfect.
