### ISSUE TITLE
progress cann`t show background color when percent is 100%

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#6523]
### Version
2.10.0

### Environment
windows7  chrome：58.0.3029.110

### Reproduction link
[https://codepen.io/anon/pen/pwebmj?editors=001](https://codepen.io/anon/pen/pwebmj?editors=001)
This link is not accuracy, in fact, percent is dynamic increased with file upload.
### Steps to reproduce
I didn`t find for the moment

### What is expected?
show background color

### What is actually happening?
no background color

---
Effect pictures are follow:
I found the style in div was right, but chrome debugger showed "div.ant-progress-bg"`s width is 0
![bug_1](https://user-images.githubusercontent.com/16114101/27280454-8cf89b22-551a-11e7-90e8-e4b6865478fa.PNG)
![bug_2](https://user-images.githubusercontent.com/16114101/27280453-8cf85644-551a-11e7-89b7-b2d014ee1a10.PNG)

**Comment by afc163** [comment]
The codepen you provide is not the situation you describle.

**Comment by kwzm** [comment]
@afc163 yes, I can`t provide the situation, it is a upload situation

**Comment by benjycui** [comment]
@kwzm you can use `setInterval` or something like that to mock uploading.

**Comment by benjycui** [comment]
Anyway, it works fine in demo https://ant.design/components/progress/#components-progress-demo-dynamic

**Comment by kwzm** [comment]
@benjycui Thanks, it seems you didn`t experienced the same situation, I will try some other ways to resolve the problem.
PS: Can i delay close the issue, maybe there ara someone-else know that.

**Comment by benjycui** [comment]
> PS: Can i delay close the issue, maybe there ara someone-else know that.

Yep, but you had better to provide re-producible demo in this week.

**Comment by kwzm** [comment]
@benjycui OK

**Comment by benjycui** [comment]
@kwzm ping~
