### ISSUE TITLE
Drag and drop Zone

### ISSUE THREAD

**Issue by nvana** [ant-design/ant-design#6525]
### What problem does this feature solve?
It would be really useful to have a drag and drop zone where i could keep doing normal thing. For now, when i click wherever in the zone, it directly open the upload folder.
The drag and drop zone currently doesn't allow me to put my dragger component above others components, or i can't click/type, it open the upload file folder. 

### What does the proposed API look like?
We could have a parameter in the Dragger component : disableUploadOnclick something like that.

**Comment by benjycui** [comment]
Why?

**Comment by benjycui** [comment]
Could you describe more? I don't understand why you have to disable the click behavior of `Upload.Dragger`

**Comment by nvana** [comment]
So i could for example, make a fullscreen drag and drop zone.

**Comment by benjycui** [comment]
And you will add some components, such as Table and Form in this drop zone?

**Comment by nvana** [comment]
Exactly

**Comment by afc163** [comment]
You can try https://github.com/okonet/react-dropzone

**Comment by nvana** [comment]
Yes i saw that, but it would be awesome if we could have this in antd API.

**Comment by afc163** [comment]
According to https://ant.design/docs/react/recommendation, we will not duplicate everything and I don't think we can do better than react-dropzone.

**Comment by prionkor** [comment]
I am creating a remote file manager using antd. Where I needed to make a dropzone on a full table. I could use the antd api if there was an option to disable click-open popup for file select. Looking into dropzone now as advised here.

**Comment by Whoaa512** [comment]
@prionkor @nvana Looks like this feature was added in https://github.com/ant-design/ant-design/pull/12347

**Comment by nvana** [comment]
Awesome 🚀
