### ISSUE TITLE
How to set callback when use customRequest ?

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design#6529]
### What problem does this feature solve?
I use fetch  API to rewrite  customRequest , but when the upload  successed ,the file.status  in onChange method is still "uploading" 
how should i do when the fetch method return ?

customRequest = (info) => {
    let formData = new FormData();
    formData.append('HeaderId',this.state.headerId);
    formData.append('file', info.file)
    console.log(info.file);
    fetch(info.action, {
    credentials: 'include',
    method: 'post',
    body: formData
  }).then(response => response.json())
    .then((body) => {
   how should i do when the fetch method return ?
    });
  }

### What does the proposed API look like?
none

**Comment by afc163** [comment]
Please chose bug report template if you want to report a bug.
