### ISSUE TITLE
Please support conditional rendering in some child-related components.

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#6530]
### What problem does this feature solve?
According react specification <https://facebook.github.io/react/docs/conditional-rendering.html>, we can use conditional render and if the expression eval as falsely value, it won't be rendered.

In some Antd child-related components like `<Select><Select.Option /></Select>`, `<Timeline><Timeline.Item /><Timeline>`, `<RadioGroup><Radio></RadioGroup>` and so on, they don't allow pass the falsly value like false, '', 0, null as the children compoent.

example:
```
// console print "Cannot read property 'props' of null" and no guide tell users not to use like that in Antd docs.
<Timeline>
  {null}
  <Timeline.Item>2017<Timeline.Item>
</Timeline>
```

Of course, we can filter out falsely values and pass a timeline array to solve this console.error, but IMO it's better to filter out falsely values by these components which inspected its children. Developer just write and use component according to React official guide.

### What does the proposed API look like?
no api proposed

**Comment by RaoHai** [comment]
+ 6534

**Comment by sorousht** [comment]
@RaoHai Is it up for grab?

**Comment by afc163** [comment]
Also `Tree` in #7025

**Comment by afc163** [comment]
- [ ] Select https://github.com/react-component/select/issues/216
- [ ] Menu
- [ ] Tree
- [ ] TreeSelect
- [ ] Timeline
- [ ] RadioGroup
- [ ] CheckGroup

**Comment by zlh314159** [comment]
#6534

**Comment by afc163** [comment]
I believe all falsy children rendering have been resolved, try latest `antd` and reinstall node_modules. Just comment here if you guys find any problems and I will reopen it.

**Comment by afc163** [comment]
- [ ] Steps
