### ISSUE TITLE
when I use AutoComplete, use children with Input to custom, add autoFucos，it throw error

### ISSUE THREAD

**Issue by lucienthink** [ant-design/ant-design#6531]
### Version
2.11.1

### Environment
Mac Chrome 59.0.3071.104 (64-bit）react 15.4.1

### Reproduction link
[https://codepen.io/lucienxu/pen/QgpoVR?editors=001](https://codepen.io/lucienxu/pen/QgpoVR?editors=001)

you shoud open dev-tool, then click "Run"

### Steps to reproduce
when I use AutoComplete, use children with Input to custom, add autoFucos，it throw erro

index.js:44 Uncaught Error: A DOM element reference is required
    at new ClassList (index.js:44)
    at module.exports (index.js:32)
    at Object.updateFocusClassName (Select.js:628)
    at Object.onOuterFocus (Select.js:351)
    at Object.fireEvents (index.js:456)
    at Object.onFocus (index.js:226)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:70)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:108)
    at executeDispatchesAndRelease (EventPluginHub.js:43)

### What is expected?
no error

### What is actually happening?
error

**Comment by benjycui** [comment]
The problem is `Input[autoFocus]`  trigger [here](https://github.com/react-component/select/blob/8028d551c0bd3ce1d5f2e7b0297e3ee89857f792/src/Select.jsx#L581-L589), but at that time, Select is not mounted, so `this.refs.root` is undefined.

**Comment by benjycui** [comment]
@lucienthink you can remove `autoFocus` and call `Input`'s focus after AutoComplete is mounted to avoid this warning.

**Comment by Narutuffy** [comment]
How do you do that?

**Comment by yesmeck** [comment]
Put `autoFocus` on `AutoComplete` https://codesandbox.io/s/pmmv1yl4j0

**Comment by anming-john** [comment]
i just met the same issue , but  here  https://ant.design/components/input/#FAQ   can not fix my issue , my  suffix is not dynamic comp , such as 
`const suffix = <span className={styles['modal-suffix-text']} >add</span> ` 
why i still emit this warning 
`When Input is focused, dynamic add or remove prefix / suffix will make it lose focus caused by dom structure change`
below is my code 
`<AutoComplete
              autoFocus={true}
              style={{ width: 292 }}
              dataSource={this.state.result}
              onSearch={this.handleSearch}
            >
              <Input
                placeholder="请输入"
                suffix={suffix}
                ></Input>
            </AutoComplete>`
