### ISSUE TITLE
typo & :bug:

### ISSUE THREAD

**Issue by xgqfrms-gildata** [ant-design/ant-design#6532]
https://ant.design/components/menu-cn/#components-menu-demo-sider-current

https://github.com/ant-design/ant-design/blob/master/components/menu/demo/sider-current.md

```js

  state = {
    current: '1',
    openKeys: [],
  }
````

!==

```js
  state = {
    current: '1',
    openKeys: []
  }
```

**Comment by xgqfrms-gildata** [comment]
:bug: :beetle:

**Comment by xgqfrms-GitHub** [comment]
https://stackoverflow.com/questions/44711549/how-to-prevent-react-component-click-event-bubble-to-document

#  ant bugs

> ` mode="horizontal"`

https://codepen.io/pen/?editors=0010

![ant-h-bug](https://user-images.githubusercontent.com/18028768/28076440-523f19b0-6691-11e7-83fe-11522fcd3e63.gif)
