### ISSUE TITLE
anted select option can not be null or undefined

### ISSUE THREAD

**Issue by yt1520406335** [ant-design/ant-design#6534]
### Version
2.11.1

### Environment
Mac 10.12.1 (16B2555)

### Reproduction link
[https://codepen.io/fqy2016/post/antd-select-can-not-be-null-or-undefined](https://codepen.io/fqy2016/post/antd-select-can-not-be-null-or-undefined)

### Steps to reproduce
someFlag  == false

### What is expected?
option 为null 或者undefined时，不报错

### What is actually happening?
error: type not is string

**Comment by RaoHai** [comment]
```jsx
{someflag ? <Option /> : null}
```

and use `Select.Option`, do not use native `option` directly.

**Comment by RaoHai** [comment]
+ #6530

**Comment by yt1520406335** [comment]
thank you, l am waiting for the answer;
 l used Select.Option,l think it related to 'null';
same as #6530
