### ISSUE TITLE
Pagination分页 的点击页数的时候，showQuickJumper  数字没有跟着改变

### ISSUE THREAD

**Issue by yellowfrogCN** [ant-design/ant-design#6535]
### Version
2.11.1

### Environment
windows 7 / chrome/ "react": "15.5.3",

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
直接在你们官网上点击就可以看到效果！
https://ant.design/components/pagination-cn/

### What is expected?
点击页数的时候，showQuickJumper  数字跟着改变

### What is actually happening?
点击页数的时候，showQuickJumper  数字没有跟着改变

**Comment by afc163** [comment]
I don't realy understand, what is exactly the problem? Maybe you can record a gif.

**Comment by zhangchao828** [comment]
![2ee49e5b-6b91-4fee-80af-a8a2fdaece2c](https://user-images.githubusercontent.com/15683846/27373795-37e82eda-569c-11e7-92c3-acc6fc68243e.png)
他的意思是当前点击的页数是第三页，但是后面goto后面的数字还是1，他希望也是3

**Comment by afc163** [comment]
这个不太合理，Goto 输入框不指向当前值。

**Comment by infeng** [comment]
Maybe clear `Goto input` after jump to a page will be better.

**Comment by afc163** [comment]
@infeng That will be better.

**Comment by sisiea** [comment]
@infeng how can i clear Goto input

**Comment by infeng** [comment]
@sisiea Do you want clear `Goto` input manually？

**Comment by sisiea** [comment]
@infeng when I use the  pagination component,the Goto input is always 1.

**Comment by infeng** [comment]
@sisiea Can you provide a reproduction?
