### ISSUE TITLE
[Form] validateTrigger not working with values other than onChange

### ISSUE THREAD

**Issue by WaldoJeffers** [ant-design/ant-design#6538]
### Version
2.11.1

### Environment
Chrome 59.0.3071.104 / Windows 10 64-bits

### Reproduction link
[https://codepen.io/anon/pen/awmVjK?editors=0010](https://codepen.io/anon/pen/awmVjK?editors=0010)

### Steps to reproduce
1. Type something in both inputs
2. Observe the green mark appearing **as you type** on the right-hand side of the inputs

### What is expected?
The inputs should not be validated until a `blur` event happens for the first input, while the other should never be validated (the `validateTrigger` option's values are `onBlur` and `false`, respectively).

### What is actually happening?
Both inputs are validated as you type, as if the value for the `validateTrigger` option was the default `onChange`.

Weirdly, if you type something in the first input, then delete everything you've just typed and unfocus the input, it will start working properly (the input will only be validated as you blur).

---
I'm trying to setup a form that only displays errors/valid marks when the users clicks on the submit button, not as the user types.

**Comment by benjycui** [comment]
Actually, this is an issue about `Form.Item`, you can use `Form.Item[validateStatus]` to avoid this issue. See: https://ant.design/components/form/#components-form-demo-validate-static

**Comment by jaredleechn** [comment]
Do u mean that i should MANUALLY validate fields at correct time and change state to control Form.Item[validateStatus]?

cc @Ariel-Cheng

**Comment by WaldoJeffers** [comment]
Thank you for your replies.
@jaredleechn it's also my understanding. But I don't want to track manually the status of all my inputs, and what's the point of having a `validateTrigger` if you can not pass anything else than the default value?

**Comment by supra28** [comment]
I think the validation for required is messed up, other validations fire as intended(onBlur).
for example 
`<FormItem hasFeedback>
          {getFieldDecorator("email", {
            validateTrigger: "onBlur",
            rules: [
              {
                type: "email",
                message: "Please enter a valid E-mail!"
              },
              {
                required: true,
                message: "Please enter your E-mail!"
              }
            ]
          })(
            <Input
              prefix={<Icon type="mail" style={{ fontSize: 13 }} />}
              placeholder="Email"
            />
          )}
        </FormItem>`

shows a green tick as soon as you type but if you do not enter a valid email address it will only trigger the error onBlur.

**Comment by acomito** [comment]
It would be nice to be able to add it per rule:

```
{getFieldDecorator('email', {
  rules: [
	{ required: true, message: 'Input your Email!', validationTrigger: 'onBlur', },
	{ type: 'email', message: 'The input is not valid E-mail!', validationTrigger: 'onChange',},
        { max: 100, message: 'Must be no more than 100 characters!', validationTrigger: 'onKeyUp', }
 ],
})(
   <Input prefix={<Icon type="mail" />} placeholder="Email" />
)}
```

**Comment by LironErman** [comment]
@acomito You can try [this example](http://react-component.github.io/form/examples/validateTrigger.html)

**Comment by dbx834** [comment]
Is there any update regarding this in v3.x?

Thanks

**Comment by Nuoky** [comment]
@acomito Try this, it works for me
```
{getFieldDecorator('email', {
  validate: [{
    trigger: 'onBlur',
    rules: [
        { required: true, message: 'Input your Email!' },
    ],
  }, {
    trigger: 'onChange',
    rules: [
        { type: 'email', message: 'The input is not valid E-mail!' },
    ],
  }],            
}
```

**Comment by hemisu** [comment]
> @acomito Try this, it works for me
> 
> ```
> {getFieldDecorator('email', {
>   validate: [{
>     trigger: 'onBlur',
>     rules: [
>         { required: true, message: 'Input your Email!' },
>     ],
>   }, {
>     trigger: 'onChange',
>     rules: [
>         { type: 'email', message: 'The input is not valid E-mail!' },
>     ],
>   }],            
> }
> ```

it works for me. where did you find this API ?

**Comment by dim912** [comment]
@Nuoky Just beautiful

**Comment by aleksey-pro** [comment]
how about antd v4?

**Comment by minki607** [comment]
> how about antd v4?

This should do.

```jsx
<Form.Item
    name="email"
    rules={[
          {
            required: true,
            message: 'cannot be empty',
          },
          {
            type: 'email',
            message: 'not a valid email address',
            validateTrigger: 'onSubmit'
          }
        ]}
      >
```

**Comment by Ladvace** [comment]
I got this problem with the ProForm.Item but not the Form.Item
