### ISSUE TITLE
DatePicker 内建的TimePicker 能否支持自动打开？

### ISSUE THREAD

**Issue by mayichaocc** [ant-design/ant-design#6539]
### What problem does this feature solve?
日期弹出的同时，时间选择也一并弹出，用样式控制 两个选择器并列展示，并且不影响切换月份，这样用户操作时只关注选择日期和时间不用手动去切换选择日期、选择时间。

### What does the proposed API look like?
showTime={{ defaultOpen: true, handoverMonth:true }}

**Comment by mayichaocc** [comment]
Sorry. My English so

**Comment by afc163** [comment]
目前的交互是考虑了 `RangePicker[showTime]` 的情况，同时展开占据太多空间了。

暂时不会做这方面的改动，感谢反馈。

**Comment by afc163** [comment]
http://uxcore.coding.me/components/calendar/#code-box-components-calendar-demo-time

**Comment by mayichaocc** [comment]
非常感谢！

**Comment by benjycui** [comment]
> http://uxcore.coding.me/components/calendar/#code-box-components-calendar-demo-time

It is cool for DatePicker, but terrible for RangePicker...

**Comment by ybning** [comment]
looking forward！

**Comment by afc163** [comment]
```jsx
<DatePicker
  mode="time"
  showTime
  onPanelChange={}
/>
```
