### ISSUE TITLE
控制 TreeSelect 组件的 inputValue 属性，使用 resetFields 函数清空了 value 和 inputValue 后，TreeSelect check 标志没有清除

### ISSUE THREAD

**Issue by weihong1028** [ant-design/ant-design#6540]
### Version
2.11.1

### Environment
chrome 56.0.2924.87 / macOS 10.12.4

### Reproduction link
[https://codepen.io/yesmeck/pen/XgdYaM?editors=1010](https://codepen.io/yesmeck/pen/XgdYaM?editors=1010)

### Steps to reproduce
1. 选中一至两个节点
1. 输入随意搜索文字
1. 点击清空

### What is expected?
1. value / inputValue 清空
1. 选中节点 check 标志恢复为未选中状态

### What is actually happening?
1. value / inputValue 清空
1. 选中节点 check 标志仍然显示选中

---
此 bug 源于上一个已 fix 的问题 #6419

**Comment by benjycui** [comment]
看起来是 value 被 inputValue 干扰了。

**Comment by lucienthink** [comment]
It is same to me. Pleace fix it quickly.

**Comment by weihong1028** [comment]
@yesmeck 还是同一个 Reproduction link，另一个bug是当选择某些节点后再随意输入一些文字，点 TreeSelect 框右边的清除图标是清不掉 value / inputValue 的

**Comment by weihong1028** [comment]
@gx761 同是这个组件 Demo 的问题？不是的话建议另建 issue

**Comment by yesmeck** [comment]
Should be fixed, try reinstall antd.
