### ISSUE TITLE
使用jsx文件使用form时 warning

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#6542]
### Version
2.11.1

### Environment
win10

### Reproduction link
[http://test.com](http://test.com)

### Steps to reproduce
使用jsx加载form的时候

### What is expected?
正常

### What is actually happening?
Warning: Unknown DOM property Form. Did you mean form?
    in form (created by Form)
    in Form (created by UserEdit)
    in div (created by Dialog)
    in div (created by Dialog)
    in div (created by LazyRenderBox)
    in LazyRenderBox (created by Dialog)
    in AnimateChild (created by Animate)
    in Animate (created by Dialog)
    in div (created by Dialog)
    in div (created by Dialog)
    in Dialog

**Comment by afc163** [comment]
Please provide a reproduction link or more infomation or we have to close it.

**Comment by WinterWoods** [comment]
not add jsx file

**Comment by afc163** [comment]
close for no reproducible demo.

**Comment by WinterWoods** [comment]
Codepen cannot use the JSX file and cannot be written back

**Comment by afc163** [comment]
So please provide a repository for your problem.

**Comment by WinterWoods** [comment]
https://github.com/WinterWoods/formforjsx
npm install
npm start 
seel f12 console
click button

**Comment by afc163** [comment]
https://github.com/WinterWoods/formforjsx/blob/ab38b8c3dadf22a67b793632a363c1bf38221e39/src/routes/form.jsx#L45

I don't think we need this `Form` prop. Please follow the offical demo.

**Comment by WinterWoods** [comment]
The past version needs to be used and has not been deleted, thanks!

**Comment by afc163** [comment]
That should be `form` not `Form` though.

**Comment by WinterWoods** [comment]
@afc163 
A redundant value is set to warn
Warning: Cannot usesetFieldsValueuntil you usegetFieldDecoratororgetFieldPropsto register it.

I used only Name in form
showModal = () => { this.setState({ visible: true, formData: { test: "多余的", Name: "正常值" } }); }
componentDidMount() { this.props.form.setFieldsValue(this.props.formData); }
