### ISSUE TITLE
Select 组件在设置 value 属性后，placeholder 属性就再也不显示了

### ISSUE THREAD

**Issue by yizao** [ant-design/ant-design#6543]
### What problem does this feature solve?
初始化的时候，value 还未确定值时（即为空时）可以显示 placeholder 以体现提示

### What does the proposed API look like?
value 值为空或者 false 展示 placeholder 的值

**Comment by afc163** [comment]
Falsy `value` don't mean unselected status, think about the situation below:

```jsx
<Select value="">
  <Option value="">未选择</Option>
  <Option value="male">男</Option>
  <Option value="female">女</Option>
</Select>
```

**Comment by afc163** [comment]
https://codepen.io/anon/pen/wedmKp?editors=001

Try `undefined` which is more accurate.

**Comment by xieyihao** [comment]
使用 undefined

**Comment by yizao** [comment]
@afc163 thx
