### ISSUE TITLE
[Form] use the wrappedComponentRef to get instance is different from withRef

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#6544]
ant-design: 2.11.1
rc-form: 1.4.3
chrome : 58.0.3029.110 (64-bit)

通过使用wrappedComponentRef方法获得的实例，与使用旧方法withRef获得的实例不一样。使用withRef可以得到绑定在实例上的属性，使用wrappedComponentRef则不行。

look [demo](https://codepen.io/xieyihao/pen/weJVKb/)
请看console：在Form1和Form2的constructor里都新增了func属性，使用withRef得到的实例可以找到func属性；但使用wrappedComponentRef方法找不到。

是不是wrappedComponentRef获取的实例不对？

**Comment by cuiyajie** [comment]
Update to 2.12.6 fixed.
