### ISSUE TITLE
[Form] use the wrappedComponentRef to get instance is different from withRef

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#6545]
### Version
2.11.1

### Environment
rc-form: 1.4.3 chrome : 58.0.3029.110 (64-bit)

### Reproduction link
[https://codepen.io/xieyihao/pen/weJVKb/](https://codepen.io/xieyihao/pen/weJVKb/)

### Steps to reproduce
在DEMO里，在Form1和Form2的constructor里都新增了func属性，使用withRef得到的实例可以找到func属性；但使用wrappedComponentRef方法找不到。

### What is expected?
通过wrappedComponentRef得到的实例与withRef方法得到的一样

### What is actually happening?
不一样

---
look [demo](https://codepen.io/xieyihao/pen/weJVKb/)

请看console：在Form1和Form2的constructor里都新增了func属性，使用withRef得到的实例可以找到func属性；但使用wrappedComponentRef方法找不到。

是不是wrappedComponentRef获取的实例不对？

**Comment by benjycui** [comment]
两个不同的 API，新用法见：https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140

**Comment by xieyihao** [comment]
@benjycui   Demo是新旧用法的对比，显然新用法得到的实例与旧用法不一样。

**Comment by benjycui** [comment]
> 两个不同的 API

两个不同的 API，为什么要行为一致？

**Comment by whx76** [comment]
@xieyihao 后面你怎么取的引用对象方法？

**Comment by xieyihao** [comment]
@whx76  还没找到方法替代，所以console很多warning。。。

**Comment by kimown** [comment]
@benjycui 

withRef 这个API在将来的新版本会彻底移除吗，如果移除的话，推荐的新wrappedComponentRef API好像不能完全代替withRef现有功能，例如调用form实例内部的function,问题[issue](https://github.com/ant-design/ant-design/issues/3509)，虽然里面推荐使用自定义事件来完成这个功能，但是我想使用refs的优点是为了封装，保证大部分可以封装的方法都在同一个组件里面，然后父组件只要调用一个函数即可。

**Comment by xieyihao** [comment]
@benjycui

如果wrappedComponentRef 是为了顶替 withRef 这个API，我也建议实现成可以完全代替withRef现有功能，
#3509
#3352
这些老的问题又会出现。

**Comment by benjycui** [comment]
> 如果wrappedComponentRef 是为了顶替 withRef 这个API，我也建议实现成可以完全代替withRef现有功能，

已经是这样。

**Comment by whx76** [comment]
@benjycui  @xieyihao  新版本可以访问function了吗？我用xieyihao的demo似乎还是不行

**Comment by benjycui** [comment]
My bad, 忘了在 antd 这层适配了。

**Comment by xieyihao** [comment]
可以移除Usage这个label？ 😳

**Comment by schwanncheung** [comment]
使用了 `wrappedComponentRef` 后，依然没法用内置的`validateFields`等函数，如：

`<MyForm wrappedComponentRef={(inst) => this.myForm = inst} />`

当 `this.myForm.validateFields ` 时，提示函数 undefined.

**Comment by jndxzqc** [comment]
用wrappedComponentRef之后可以用这种方式获取form示例：
<MyForm wrappedComponentRef={(inst) => this.myForm = inst.props.form} />
