### ISSUE TITLE
[功能新增] 在穿梭框Transfer组件中, 希望可以增加一个属性, 用于设置dataSource和target是左右格式还是右左格式

### ISSUE THREAD

**Issue by SerAaron** [ant-design/ant-design#6547]
### What problem does this feature solve?
现状: dataSource只能在左边, target只能在右边
需求: 可以选中dataSource框和target框是左右还是又左
附加需求: 在dataSource数据列表中, 可以加一个字段控制当前的这一条数据显示还是隐藏.

### What does the proposed API look like?
const dataSource = [{
  xxx.....,
  控制显示或者隐藏的属性: true或者false,
}];
<Transfer ...{其它属性} 控制格式=XXX dataSource={dataSouce}/>

**Comment by yesmeck** [comment]
要调换左右，设置成全选就可以了。要隐藏，把数据从 `dataSource` 里去掉就可以了。

**Comment by Manweill** [comment]
@yesmeck 这样设置，你的API定义起来还有意义吗
