### ISSUE TITLE
a bug when selecting one page's table row one by one in official demo

### ISSUE THREAD

**Issue by lyk248** [ant-design/ant-design#6550]
### Version
2.11.1

### Environment
all

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-row-selection-custom](https://ant.design/components/table-cn/#components-table-demo-row-selection-custom)

### Steps to reproduce
Config 'Select All Data' in rowSelection, then select table row one by one until the current page's all rows has been selected, then all data has been selected automatically.
在 Table 组件中配置全选为“选中全部数据”后逐行选择直到当前页都选中后，会自动选中所有数据。

### What is expected?
All data hasn't been selected automatically, and the thead icon is showing like partial selected rather than all selected (or can be controlled by user).
不会自动选中所有数据，且表头中的选中展示可让用户配置。

### What is actually happening?
All data hasn't been selected automatically, and the thead icon is showing like all selected.

**Comment by afc163** [comment]
I think you can create your own column with Checkboxs, which is a better solution.

**Comment by benjycui** [comment]
Actually, this is expected behavior..
