### ISSUE TITLE
form表单控件：hasFeedback并不随着validateTrigger的触发时机而变化

### ISSUE THREAD

**Issue by Ariel-Cheng** [ant-design/ant-design#6551]
### Version
2.11.1

### Environment
无影响

### Reproduction link
[riddle://46f6c101](riddle://46f6c101)

### Steps to reproduce
输入一个长度不大于10的字符串

### What is expected?
* 在我输入结束之后，输入框失去焦点onblur时，校验并feedback

### What is actually happening?
* 第一次输入还没有结束更没有失去焦点时，就有feedback，绿色成功标志

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/6538
