### ISSUE TITLE
add a choice to remove step icon for InputNumber

### ISSUE THREAD

**Issue by luyunfei** [ant-design/ant-design#6552]
### What problem does this feature solve?
Please add a choice to remove step icon for InputNumber

### What does the proposed API look like?
see the screenshot

![2017-06-20_23-03-06](https://user-images.githubusercontent.com/4887426/27340550-554175a2-560d-11e7-8c69-9fa9d62c51ca.png)

![2017-06-20_23-06-25](https://user-images.githubusercontent.com/4887426/27340594-6c145984-560d-11e7-8c5b-cc92076d3b2e.png)

**Comment by RaoHai** [comment]
How will you identify it as an InputNumber while step icons got removed?

Or you can hide it by override `.ant-input-number-handler-wrap` stylesheet.
