### ISSUE TITLE
mapPropsToFields breaks validation if not using onFieldsChange

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#6553]
### Version
2.11.1

### Environment
Mac Sierra Latest, Chrome Latest

### Reproduction link
[https://codepen.io/kossel/pen/yXbJXr?editors=001](https://codepen.io/kossel/pen/yXbJXr?editors=001)

### Steps to reproduce
I want to use `mapPropsToFields` conjunction with `onValuesChange` only.
Doing this the field stops the validation because when using mapPropsToFields, looks like the `errors` array needs to also to be present in the return object. from the codepen.io link you can try to uncomment line 14 or 15. the problem is, if I use onValuesChange, I will not get the errors object and if I use `onFieldsChange` that function will be trigger twice because of the validation state :S

not sure if counts as a bug or thats intentional and for my scenario I should use `onFieldsChange`.

### What is expected?
the validation should work

### What is actually happening?
because errors[] array is missing, the validation doesn't show feedback

**Comment by benjycui** [comment]
Nope, `onValuesChange` is just for convenient. 

If you want to use `mapPropsToFields` you must use `onFieldsChange`.

**fields** and **values** are different.
