### ISSUE TITLE
Question about configuring webpack config (create-react-app)

### ISSUE THREAD

**Issue by ffxsam** [ant-design/ant-design#6554]
### Version
2.11.1

### Environment
ReactJS

### Reproduction link
[https://github.com/](https://github.com/)

### Steps to reproduce
This is actually a question about configuring webpack in `create-react-app`:

https://ant.design/docs/react/use-with-create-react-app

The documentation says to edit `config/webpack.config.dev.js`, which I've done, and it works. Don't we also need to add the same plugin config to `config/webpack.config.prod.js` as well?

### What is expected?
N/A

### What is actually happening?
N/A

**Comment by afc163** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/507615/27364282-3a398d8a-566c-11e7-95f0-b93c825fd908.png">
