### ISSUE TITLE
table showHeader={false} not work in Firefox

### ISSUE THREAD

**Issue by whyuan1976** [ant-design/ant-design#6558]
### Version
2.11.0

### Environment
Win10, Firefox 53.0.3.6347 

### Reproduction link
[https://codepen.io/anon/pen/OgmVmR?editors=001](https://codepen.io/anon/pen/OgmVmR?editors=001)

### Steps to reproduce
It works under Chrome.

### What is expected?
Not show header in the table.

### What is actually happening?
The header of table is still displayed.

**Comment by yesmeck** [comment]
Reinstall node_modules.
