### ISSUE TITLE
use component in Table column, when delete one row component will render double

### ISSUE THREAD

**Issue by 282159468** [ant-design/ant-design#6559]
### Version
2.11.1

### Environment
chrome

### Reproduction link
[https://codepen.io/282159468/pen/pwPLdY](https://codepen.io/282159468/pen/pwPLdY)

### Steps to reproduce
click delete will get two "console.log('A');"

### What is expected?
点击删除的时候this.setState({dataSource: newList}），这个时候表格只有一行了，然后重新render，按理A组件也只render一次，

### What is actually happening?
A组件也只render一次

**Comment by 282159468** [comment]
it's ok without Table
[https://codepen.io/282159468/pen/gRWeje](url)

**Comment by yesmeck** [comment]
https://github.com/react-component/table/blob/4eefde1ffc2244b3952fce80b064834bdb4cfcba/src/Table.jsx#L169-L182
是因为删除 row 的时候去更新了 `state.expandedRowKeys`

**Comment by yesmeck** [comment]
Fixed in https://github.com/react-component/table/pull/169 will be released soon.
