### ISSUE TITLE
Datepicker 的showTime属性

### ISSUE THREAD

**Issue by likezero** [ant-design/ant-design#656]
0.9.x 有的showTime，可以在选择时间
在0.10版本文档中没有此配置了，但是还是有效。
我想知道这个是否会保留？毕竟在同一个界面选择日期+时间比较方便。

**Comment by afc163** [comment]
应该会保留，日期面板的时间选择正在重构，0.11.0 版本里会加回来。

**Comment by xiamidaxia** [comment]
可否showTime的时候, 这日期和时间两个组件捆绑出来，给人的感觉依然是整体调用，这样可以简化开发

**Comment by yiminghe** [comment]
http://react-component.github.io/calendar/examples/antd-calendar.html
