### ISSUE TITLE
matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by qinyang1980** [ant-design/ant-design#6560]
### Version
2.11.1

### Environment
win10, chrome 59, react 15.5.4

### Reproduction link
[https://github.com/ant-design/create-react-app-antd](https://github.com/ant-design/create-react-app-antd)

### Steps to reproduce
1. download this repository:
https://github.com/ant-design/create-react-app-antd

2. type "yarn" to install all dependences.
3. type "yarn run test"

4. the error will pops up.

### What is expected?
the test passed

### What is actually happening?
Error: matchMedia not present, legacy browsers require a polyfill

---
在最新版本2.11.1中还是没有解决这个问题。

我现在只能手动patch这个文件：
node_modules/antd/lib/carousel/index.js

把如下这段代码：
window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};

放在require('react-slick')前面，就可以解决这个问题。

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started#Compatibility

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3308#issuecomment-325182753

**Comment by bytewiz** [comment]
@afc163 is it correct to assume this fix has not been released yet?

**Comment by yesmeck** [comment]
It has been released.

**Comment by zernabhussain** [comment]
check this: https://github.com/akiran/react-slick/issues/742#issuecomment-557793922
