### ISSUE TITLE
Row Selection props in Table

### ISSUE THREAD

**Issue by prillymonials** [ant-design/ant-design#6562]
### What problem does this feature solve?
I want to resize the Row Selection and I want to fixed the row selection to the left.

### What does the proposed API look like?
Add new props in row selection (?)

**Comment by benjycui** [comment]
> I want to resize the Row Selection

Just override with CSS



> I want to fixed the row selection to the left.

Duplicated: https://github.com/ant-design/ant-design/issues/5793
