### ISSUE TITLE
Datepick disabledDate wrong when set initialValue

### ISSUE THREAD

**Issue by lydiafork** [ant-design/ant-design#6563]
### Version
2.8.3

### Environment
Mac OS10.12.3, chrome: 58.0.3029.110 (64-bit),  react: 15.4.0,

### Reproduction link
[https://codepen.io/linforcodepen/pen/RgVJEa?editors=0010](https://codepen.io/linforcodepen/pen/RgVJEa?editors=0010)

### Steps to reproduce
when choose 2010/01/01 , find it is disabled, but , another datepicker not set initialValue, it can be 2010/01/01 choosed

### What is expected?
2010/01/01 can be choosed after set initialValue

### What is actually happening?
2010/01/01 is disabled

**Comment by benjycui** [comment]
```jsx
function disabledDate(current) {
  return (current && current.valueOf() < moment('2010-01-01').valueOf()) ||
    (current && current.valueOf()  > moment('2018-12-31').getTime());
}
```

**Comment by benjycui** [comment]
Don't mix Date and moment together, they are different.

**Comment by lydiafork** [comment]
Thanks.

**Comment by lydiafork** [comment]
Sorry, I still have questions, `moment('2018-12-31').getTime()`is not working in my code, when i use ```
return (current && current.valueOf() < moment('2010-01-01').valueOf()) ||
    (current && current.valueOf()  > moment('2018-12-31').valueOf());
```
it happens same question in 2018-12-21

**Comment by lydiafork** [comment]
已修改成
`
return (current && current.valueOf() < moment('2010-01-01').valueOf()) ||
    (current && current.valueOf() > moment().add(1, 'years').valueOf());
`
