### ISSUE TITLE
isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#6565]
### Version
2.11.1

### Environment
"react": "^15.6.1","react-dom": "^15.6.1"

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
我升级了react版本为："react": "^15.6.1","react-dom": "^15.6.1"，然后所有动画组件都显示这个问题：isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

### What is expected?
不要显示好多这些红色警告错误

### What is actually happening?
显示好多这些红色警告错误：isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by benjycui** [comment]
本地升级后没重现，然后 rc-animate 已经没有使用 isMounted 了。

建议先更新依赖试试。

**Comment by chendonghai** [comment]
我更新了rc-animate动画库还是报这个警告错误：Popup: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.你说的更新依赖是指那个啊，

**Comment by afc163** [comment]
Please provide a reproducible repository.

**Comment by chendonghai** [comment]
还是没有搞懂什么意思

**Comment by chendonghai** [comment]
已经解决了

**Comment by benjycui** [comment]
@chendonghai  最好能提供重现方式，如果你已经解决，希望能把问题总结下并把解决方案贴出来，以便后边碰到相似问题的人可以参考，谢谢。

**Comment by chendonghai** [comment]
哎，后面看了一下发现还是没有解决，不知道什么原因，这次主要是升级了一下react, ant desig就出现这个问题

**Comment by afc163** [comment]
Please provide a reproducible repository.

**Comment by han88829** [comment]
我也是，一直提示MenuItem: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

请问解决了吗？

**Comment by GitHubJiKe** [comment]
i have a problem about this waring too , anyone knows how to solve this problem?

**Comment by gitbu** [comment]
@chendonghai 我也遇到这样的问题
![image](https://user-images.githubusercontent.com/14817184/28603983-25ffd816-71fa-11e7-9b72-94a0d81355a1.png)

**Comment by muzea** [comment]
@gitbu 我也遇到了，看了一下是老版本react-component/trigger的问题，更新一下依赖就好了

**Comment by 7kr** [comment]
我现在也遇到了这样的问题，请问各位大神，这个问题的原因是什么，怎么解决了

**Comment by Bossmmh** [comment]
请问解决了吗
