### ISSUE TITLE
AutoComplete ref focus doesn't work

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#6568]
### Version
2.11.1

### Environment
Google Chrome 58.0.3029.110

### Reproduction link
[https://codepen.io/froston/pen/bRWPmx](https://codepen.io/froston/pen/bRWPmx)

### Steps to reproduce
Call `focus()` on AutoComplete or Input object set in `ref` function.

### What is expected?
To be able to focus AutoComplete by `ref` property.

### What is actually happening?
Throws error in console `... .focus is not a function`

**Comment by benjycui** [comment]
Yep, not all of antd's components support `.focus`.

Trace: https://github.com/ant-design/ant-design/issues/3790
