### ISSUE TITLE
动态改变formitem位置提示'onChange'undefined

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#6571]
### Version
2.8.3

### Environment
Mac上，chrome浏览器

### Reproduction link
[https://codepen.io/anon/pen/dRRvwj?editors=0010](https://codepen.io/anon/pen/dRRvwj?editors=0010)

### Steps to reproduce
点击添加按钮生成一条新的formitem，下拉选择后点击向上向下图标来更换位置，更换位置后再次选择下拉，这时候就提示Cannot read property 'onChange' of undefined

### What is expected?
能够正常使用

### What is actually happening?
位置发生交换后提示Cannot read property 'onChange' of undefined

**Comment by afc163** [comment]
https://codepen.io/anon/pen/VWWbKR?editors=0010

You bind the key in wrong place, please check the console error log in your codepen.

**Comment by aw6658913** [comment]
thanks,it's my fault
