### ISSUE TITLE
Warning: Unknown prop `prefixCls` on XXXX tag

### ISSUE THREAD

**Issue by vincent-louis** [ant-design/ant-design#6572]
### What problem does this feature solve?
While using custom component on Dropdown component via overlay attr, there is an unknown props warning (prefixCls), for example using `<ul>` tag.

Request to use data-prefixCls or some other attr that won't cause this warning.

If to use Menu component from Antd, there is too much styling to override it and not supported className attr.

### What does the proposed API look like?
Sorry couldn't provide a proper API.

**Comment by afc163** [comment]
If you want to report a bug, please follow the bug template.

**Comment by afc163** [comment]
#6575
