### ISSUE TITLE
AutoComplete doesn't filter options when explicitly setting filterOption to true

### ISSUE THREAD

**Issue by kagd** [ant-design/ant-design#6573]
### Version
2.11.1

### Environment
OSX 10.11.6, Chrome 58

### Reproduction link
[https://codepen.io/gklinsing/pen/MooJJZ](https://codepen.io/gklinsing/pen/MooJJZ)

### Steps to reproduce
Render AutoComplete with "filterOption={true}" prop.

### What is expected?
When the user starts typing, the result set should narrow.

### What is actually happening?
When the user starts typing, the result set doesn't change.

**Comment by kagd** [comment]
This issue should be resolved with this PR react-component/select#202

**Comment by yesmeck** [comment]
Hello @kagd , a patch version of rc-select has been released, try re-install node_modules. Thanks for you PR.
