### ISSUE TITLE
Add change primary color button in footer 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#6574]
1. compile new style code with a now.sh service and inject styles into document.
2. use [react-color](https://www.npmjs.com/package/react-color) and preset colors in https://ant.design/docs/spec/colors-cn

**Comment by yesmeck** [comment]
编译很慢。。。

```bash
curl -X "POST" "https://ant-design-less.now.sh/compile" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "variables": {
    "@primary-color": "#ffffff"
  }
}'
```

**Comment by afc163** [comment]
缓存一下？
