### ISSUE TITLE
Input textarea 横向滚动问题 （可能是因为没有场景，所以没有考虑全）

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#6577]
### Version
2.11.1

### Environment
mac chrome58

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```
<Input type="textarea" autosize={{ minRows: 8, maxRows: 26 }} wrap="off" />
```

往textarea写值时，当没有手动enter的时候，文本是在一行的，但是当一行文本过长，会影响到高度值，其实这个高度值应该是不变的（或者以minRows的高度显示）

### What is expected?
一行文本过长，高度是minRows

### What is actually happening?
一行文本过长，高度是maxRows

---
在`calculateNodeHeight.tsx`源码中：

```js
 if (!hiddenTextarea) {
    hiddenTextarea = document.createElement('textarea');
    document.body.appendChild(hiddenTextarea);
  }
```

没有考虑wrap="off" 的情况下。

或者能不能考虑新增一个属性api？

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by henryzp** [comment]
@benjycui 

图1：

![image](https://user-images.githubusercontent.com/3849702/27465781-434c7868-5808-11e7-92b2-dc1e33e9b09c.png)

当我点击上传文件时，因为我设置了textarea的warp off属性

![image](https://user-images.githubusercontent.com/3849702/27465800-626a2344-5808-11e7-8e95-e603353633e4.png)

高度被撑开了，然而我期望的是高度不被撑开，还是同一张图所示。。

因为你们那个js计算高度的时候，是先把内容往textarea里面塞，然后计算textarea的高度，但没有考虑wrap off的情况，导致高度会严重拉高

**Comment by benjycui** [comment]
`white-space: nowrap;` will cause the same issue.

**Comment by benjycui** [comment]
I don't think this is a bug. You can just turn `autoSize` off

**Comment by henryzp** [comment]
@benjycui ,

```
 <Input type="textarea" autosize={{ minRows: 8, maxRows: 26 }} autosize="off" />
```

这样不对吧？

像notepad++，一行输入，默认是不换行的，只有用户手动换行，才会换行处理的。

因此我这边有这样的一个需求，只有碰到"\n"才会被折行，默认是一行，即过长的话，出现横向滚动条

**Comment by afc163** [comment]
@benjycui 的建议是不要设置 `autosize`。

**Comment by henryzp** [comment]
@afc163 ，我并没有加autosize，而是这样写的：

```
 <Input type="textarea" autosize={{ minRows: 8, maxRows: 26 }} wrap="off" />
```

因为这是我的需求：只有碰到"\n"才会被折行，默认是一行，即过长的话，出现横向滚动条。

但我翻`calculateNodeHeight.tsx`源码时，看到计算textarea的高度，并没有考虑这样的场景啊，

而是创建一个普通的textarea，一行排不下来了，就往下挤这种，计算出来的高度肯定是不对的呀。。

这个不是bug吗？

**Comment by afc163** [comment]
<img width="565" alt="dingtalk20170623145655" src="https://user-images.githubusercontent.com/507615/27469917-2e26cddc-5824-11e7-99ae-c71f944fcbff.png">

矛盾啊...

**Comment by afc163** [comment]
https://codepen.io/anon/pen/ZyJWRa?editors=0010

**Comment by henryzp** [comment]
@afc163 ，我懂你的意思了

然后我想确定一下，加了wrap="off"，就没办法实现textarea自适应高度了吗？

**Comment by afc163** [comment]
@benjycui 的意思是如果加了 `white-space: nowrap;` 也会导致一样的问题，可能不容易完美解决。

我觉得如果只考虑 `wrap` 属性是可以优化一下的，我来试试。

**Comment by henryzp** [comment]
@afc163 ,谢谢。。

**Comment by henryzp** [comment]
@afc163 新版本什么时候发布？

**Comment by afc163** [comment]
每周末。

**Comment by AirmaZ** [comment]
这个hiddenTextarea不销毁吗？ 我的项目出现了重复的hiddenTextarea
