### ISSUE TITLE
Tab 垂直模式样式错乱

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design#6578]
### Version
2.11.1

### Environment
chrome浏览器

### Reproduction link
[https://codepen.io/anon/pen/owwGGV?editors=001](https://codepen.io/anon/pen/owwGGV?editors=001)

### Steps to reproduce
参考 https://codepen.io/anon/pen/owwGGV?editors=001

### What is expected?
Tabs 垂直模式的时候, 新增以及附加内容都是垂直的。
另外，TabPane 标题很长的时候，应该有个 max-width 限制或者提供一个入口来限制

### What is actually happening?
样式错乱

**Comment by afc163** [comment]
Vertical mode is not supported in editable-card Tabs yet.

**Comment by benjycui** [comment]
And...

![image](https://user-images.githubusercontent.com/3580607/27469388-e0c55cae-5821-11e7-8e02-07f5b4bfc63f.png)

**Comment by benjycui** [comment]
其实这个问题，因该是垂直模式时，extraContent 的位置有问题。

**Comment by afc163** [comment]
1. 标题很长的问题。

```jsx
<TabPane title={<span style={{ maxWidth: 200, display: 'inline-block', overflow: 'hidden' }}>标题很长标题很长标题很长标题很长标题很长</span>}>
```

2. tabBarExtraContent 错位的问题，在 #7090 里修复。
