### ISSUE TITLE
modal 配合表单时，表单验证无效

### ISSUE THREAD

**Issue by JiangJun1994** [ant-design/ant-design#6579]
### Version
1.11.4

### Environment
浏览器：Google

### Reproduction link
[no](no)

### Steps to reproduce
  onAddOk() {
    this.props.form.validateFields((errors, values) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        return;
      }
      else{
        AppActions.saveAgentCollector.triggerAsync()
            .then(() => {
              AppActions.clearCurrentAgentCollector()
              return AppActions.listAgentCollector()
            })
            .catch(err => {
              console.log(err)
            })
          AppActions.setAgentCollectorAddModalVisible(false)
    }
    });

render() {
 const { getFieldProps, getFieldError, isFieldValidating } = this.props.form;

    const descProps = getFieldProps('desc', {
      rules: [
        { required: true, message: '真的不打算写点什么吗？' },
         {
          validator: (rule, value, callback) => {
            const {getFieldValue} = this.props.form;
            console.log('in validating', value, rule)
            if (!value) {
              callback('No value provided！');
            } else {
              callback();
            }
          }
        }
      ],
    });

// add agentCollector
    let antdFormAdd = <Form horizonal form = {this.props.form}>
      <FormItem
        {...formItemLayout}
        label="Description"
      >
        <Input {...descProps} placeholder="随便写" id="desc" name="desc" />
      </FormItem>
 </Form>

   return (
      <div className = "container">
        <Modal
          title = "Add AgentCollector"
          visible = {this.props.appStore.agentCollectorAddModalVisible}
          onOk = {this.onAddOk.bind(this)}
          onCancel = {this.onAddCancel}
        >
          {antdFormAdd}
        </Modal>

       

        <div className = "row clbody addAgentCollector">
          <div className = "ant-col-sm24 p-t-10 addAgentCollector">
            <Button type = "primary" icon = "plus-circle-o" onClick = {this.onItemAdd}/>
          </div>
        </div>

        <div className = "row clbody tableAgentCollector">
          <div className = "ant-col-sm-24 p-t-10 ">
            { antdTable }
          </div>
        </div>

      </div>
    )
}

### What is expected?
modal 配合form 使用时，提交时能验证输入的内容，如果有错误不能提交，如果无误再提交。

### What is actually happening?
modal 配合form 使用时，不能判断错误。

**Comment by benjycui** [comment]
See: https://ant.design/components/form/#components-form-demo-form-in-modal
