### ISSUE TITLE
When sorting in a table, can set some row prohibit sorting?

### ISSUE THREAD

**Issue by lanyulin** [ant-design/ant-design#6581]
### What problem does this feature solve?
The totals in the report do not require sorting（例如，报表中的’合计‘这项，不需要参与排序）

### What does the proposed API look like?
The sorter function In Column, forbid index value of dataSource；
Can also automatic call filter function.

**Comment by benjycui** [comment]
I don't understand your issue.

> The totals in the report do not require sorting（例如，报表中的’合计‘这项，不需要参与排序）

Just don't enable sorter for that column.

> The sorter function In Column, forbid index value of dataSource；
> Can also automatic call filter function.

Sorting and filtering are two different features, you can use them separately.

**Comment by yesmeck** [comment]
You can implement this feature by implementing the `sorter` function, and always return `1` for the row you want show in the bottom.
