### ISSUE TITLE
Localize month names in DatePicker

### ISSUE THREAD

**Issue by thj-dk** [ant-design/ant-design#6583]
Is it possible to translate month names in the DatePicker?
Moment is set to my current locale da_DK, but that doesn't change the names, and I've looked at the [localization example](https://github.com/ant-design/ant-design/blob/master/components/date-picker/locale/example.json), but no month names are included.

Is it possible?

**Comment by artem-solovev** [comment]
It's actually a good one. Give us some tips because we're not the first who trying to solve this bug

**Comment by artem-solovev** [comment]
@thj-dk Hi Tom, did you fix this?
