### ISSUE TITLE
Create react app customizing theme not working (via overriding less)

### ISSUE THREAD

**Issue by stefensuhat** [ant-design/ant-design#6585]
### Version
2.11.1

### Environment
windows 10, Latest chrome, react 15.6.,1

### Reproduction link
[http://imgur.com/a/X0kDp](http://imgur.com/a/X0kDp)

### Steps to reproduce
I make App.less contain  this 2 import: 

@import "~antd/dist/antd.less";
@import "vars.less";

vars.less is supposed to overwrite default ant variables.

For example on my vars.less I change the default font to:
@font-family            : "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
@primary-color; #fb6542;

### What is expected?
My value should overwrite the default value

### What is actually happening?
When I compiled it, my value is got overwrite by default font.  Here is the image that my value got overwritten my default less. Here is the image:  http://imgur.com/a/X0kDp

The primary color is not working.

---
If I set the variables from webpack.config.dev it's working properly.

**Comment by afc163** [comment]
Could you provide a re-producible repo?

**Comment by stefensuhat** [comment]
@afc163 https://github.com/stefensuhat/berr-ant here is repo for the problem

**Comment by afc163** [comment]
```
berr-ant@0.1.0 git:❨master❩ tnpm start

> dashboard@0.1.0 start /Users/afc163/Projects/berr-ant
> node scripts/start.js

/Users/afc163/Projects/berr-ant/scripts/start.js:66
        );
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

**Comment by stefensuhat** [comment]
can you try use `yarn start`? @afc163 
I've tried clone it and it's working properly

**Comment by afc163** [comment]
https://github.com/stefensuhat/berr-ant/pull/1

https://ant.design/docs/react/customize-theme-cn#2)-less

Please follow the documentation.
