### ISSUE TITLE
Form validation does not work for input values being set by ReactDOM.findDOMNode(this.refs.x).value = y

### ISSUE THREAD

**Issue by ssmlee04** [ant-design/ant-design#6586]
### What problem does this feature solve?
we have a button when you click on it it will generate a string and insert the string to the input textbox. But when we're doing form validation it appears the input is still clean and we cannot submit the form at all.

### What does the proposed API look like?
We should be able to submit the form.

**Comment by benjycui** [comment]
Yep, it's by designed.

And you should not set DOM node's attributes directly, just think in React.
