### ISSUE TITLE
组件Layout的Content中的直接自对象指定height:100%无效

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#6588]
### Version
2.11.0

### Environment
操作系统：win7/macOS，浏览器：chrome/ie11

### Reproduction link
[https://codepen.io/vipcxj/pen/zzdrao](https://codepen.io/vipcxj/pen/zzdrao)

### Steps to reproduce
在Layout的Content中放一个div，指定height:100%

### What is expected?
这个div高度占满父对象，也就是Content

### What is actually happening?
height:100%没起作用

---
我试过使用react-sizeme，但获取到的height仍旧是0。之后利用ref属性获取原生node，根据父对象的高度，直接指定height，这次成功了，但有引入新问题。我在div中放有一个antd的table，当table高度很高，超出div范围，它并没有撑大div，也没有在div中显示滚动条。它直接再div的父对象，也就是Content中显示了滚动条，并且溢出了div，我感觉已经没救了，所以来提了这个issure

**Comment by benjycui** [comment]
https://stackoverflow.com/questions/15381172/how-to-make-flexbox-children-100-height-of-their-parent
