### ISSUE TITLE
Layout.Sider 设置overflow-y: auto; 时，Menu模式为vertical时 弹出的二级菜单看不到

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design#6589]
### Version
2.11.1

### Environment
window7\chrome 57.0.2987.98 (64-bit)、

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
Layout.Sider 布局里有一个Menu组件，当收缩时Menu的模式改为vertical。
当Menu外包了一层div设置css overflow-y: auto;时，Menu的二级菜单 absolute定位的元素看不到。

### What is expected?
Layout.Sider 可以实现纵向滚动，Menu为vertical模式，鼠标移上菜单时可以显示浮动的二级菜单

### What is actually happening?
Layout.Sider 可以实现纵向滚动，Menu为vertical模式，鼠标移上菜单时看不到浮动的二级菜单

---
overflow设置隐藏时子元素如果是绝对定位会看不到。

**Comment by small752** [comment]
@ant-design-bot  hello, I make a demo, https://codepen.io/anon/pen/yXoOOV?editors=0110

thank you

**Comment by afc163** [comment]
https://github.com/react-component/menu/issues/19

**Comment by small752** [comment]
@afc163  自主用rc-trigger来显示二级菜单吗，能不能给一个demo代码， 我试了，实现不了原来菜单悬浮的效果

**Comment by afc163** [comment]
目前仍然没解决。

**Comment by small752** [comment]
哦，加油  我另外想办法显示。

**Comment by afc163** [comment]
trace #5586

**Comment by zachguo** [comment]
@small752 请问你目前如何解决的这个问题？

**Comment by zachguo** [comment]
@afc163 感觉这个和#5586不是一个问题。假如给`Sider`设一个宽一点的`collapsedWidth`，是可以看见浮动的二级菜单成功被激活，只是被右边的`Layout`遮挡了，也就是一个样式的问题。

**Comment by zachguo** [comment]
@afc163 Can this issue be reopened? This bug is still there, and blocked by react-component/menu#19.

**Comment by afc163** [comment]
trace #5586

**Comment by zachguo** [comment]
but #5586 is an `enhancement`, not as prioritized as `bug`...

**Comment by afc163** [comment]
It is a same problem.
