### ISSUE TITLE
sider 能否固定左侧

### ISSUE THREAD

**Issue by TracyDa** [ant-design/ant-design#6590]
### What problem does this feature solve?
sider 能否固定左侧

### What does the proposed API look like?
大多数框架都支持siderbar固定在左侧，然而https://ant.design/components/layout/ 中所用的固定的方案实在用起来和以往方式大相径庭，content内部出现了滚动条，看起来体验很差，有没有其它方法可以实现？

**Comment by afc163** [comment]
https://ant.design/components/layout/#components-layout-demo-fixed-sider
