### ISSUE TITLE
Select focus is not a function with ref

### ISSUE THREAD

**Issue by acivang** [ant-design/ant-design#6591]
### Version
2.11.1

### Environment
macOS 10.12.5; chrome 58.0.3029.110; react 15.6.1

### Reproduction link
[https://codepen.io/anon/pen/EXvyXJ?editors=0010](https://codepen.io/anon/pen/EXvyXJ?editors=0010)

### Steps to reproduce
i want to use ref of Select focus it, but it threw err: focus is not a function.
with findDOMNode, it is fine. but not focus Select component. test click  function, it's fine.
if focus is not support ref and by findDOMNode could not be focused?

### What is expected?
findDOMNode dom's focus function is fine, and support get dom by ref.

### What is actually happening?
not working and threw error.

**Comment by afc163** [comment]
trace #3790
