### ISSUE TITLE
How to ignore disabled Form field  when form.validateFields called?

### ISSUE THREAD

**Issue by zhengying** [ant-design/ant-design#6592]
### What problem does this feature solve?
I have a Form, I want to disable some form field, but when I call form.validateFields all form item do the validate include disabled field.  how to ignore these disabled field when form.validateFields called?  

### What does the proposed API look like?
form should ignore disable field  when form.validateFields called.

**Comment by afc163** [comment]
@benjycui Could we add a disabled option for `getFieldDecorator`?

**Comment by benjycui** [comment]
Just try `getFieldDecorator(name: { hidde: true })`

**Comment by tianlizhao** [comment]
There is no hidde option

**Comment by andreek** [comment]
@tianlizhao it's a typo. 'hidden' works for me.

**Comment by ab-mannan** [comment]
I would like to ask the relevant question here.

I just faced an issue and I was expecting Ant Design to handle it out of the box but unfortunately it didn't.

I have marked the field required on the basis of a flag (that sets on a toggle button). Toggle is active so the fields are required. I have added some text in the field and then removed that text from the field. Error message appears just below the field. I then toggle the button again(flag sets to inactive). The fields are not required any more but the Error message didn't get removed. Can anyone suggest a way to remove these error messages or is there any sort of configuration I am missing. I have also tried adding `hidden: true`.

Any help will be appreciated.

**Comment by dragondgold** [comment]
How do you disable a Form.Item field? I want to do just that but can't find the way!

**Comment by prakashjaw** [comment]
@dragondgold 
you could disable a Form.Item field just by adding boolean states into disabled props and in a stateless component by using useState(false)!

**Comment by Ahmad129096** [comment]
hello, can you please let me know how do i disable all the form fields at once except for one field which will allow me to enable fields on change of that particular field

**Comment by Ahmad129096** [comment]
@Al-AminDolar use state to check if there is an error and than pass the state to ant d button against disabled
