### ISSUE TITLE
[Feature Request] Export Props interface definition in all component index.d.ts files

### ISSUE THREAD

**Issue by newraina** [ant-design/ant-design#6593]
### What problem does this feature solve?
Having standard Props interface defined as public makes it possible to reuse the Props definition when creating my own custom version of the component.

### What does the proposed API look like?
For example, when creating my Login Component, I must:

```tsx
import { FormComponentProps } from 'antd/lib/form/Form'

class Login extends React.Component<{} & FormComponentProps, {}> {
  render() {
    // some render code
  }
}
```

But following maybe better:

```tsx
import { FormComponentProps } from 'antd'

class Login extends React.Component<{} & FormComponentProps, {}> {
  render() {
    // some render code
  }
}
```

At least:

```tsx
import { FormComponentProps } from 'antd/lib/form'

class Login extends React.Component<{} & FormComponentProps, {}> {
  render() {
    // some render code
  }
}
```

Just like this TS based UI package does: [blueprint](https://github.com/palantir/blueprint/blob/master/packages/core/src/index.ts)

**Comment by benjycui** [comment]
I think the following is good enough:

```jsx
import { FormComponentProps } from 'antd/lib/form'

class Login extends React.Component<{} & FormComponentProps, {}> {
  render() {
    // some render code
  }
}
```

**Comment by newraina** [comment]
I think the first one is better.

Choosing the second way may be because the first one exposure too may interfaces, but these interfaces are very useful when using TypeScript, those who do not use TS simply do not see them.

Many of the frameworks written in TS will expose the interface to the outermost, and do not find any problems.

Of course, the second way can meet the needs. **The purpose of this ISSUE is to unify the exposed location of the interface**. The current situation is that the location of the interface is unpredictable in the `lib/[component name]/` folder.

But I still hope that the first can be adopted, thanks.

**Comment by DavidNorena** [comment]
Hi, im trying to figure out why is not working for me but, i have this error node_modules/antd/lib/form/index"' has no exported member 'FormComponentProps'.

**Comment by DavidNorena** [comment]
my workaround was import { FormComponentProps } from 'antd/lib/form/Form';

What im doing wrong ?

**Comment by newraina** [comment]
@DavidNorena 

Do you mean you try this: `import { FormComponentProps } from 'antd/lib/form`, but  get an error?

of course it's an error, because`FormComponentProps` doesn't exposed in `lib/form` dir now, that's why I submit this issue :)

**Comment by DavidNorena** [comment]
@newraina ahhhh now I get it ! :D sorry, so meanwhile i'll use import { FormComponentProps } from 'antd/lib/form/Form'; ok ?

**Comment by newraina** [comment]
@DavidNorena Yes

**Comment by afc163** [comment]
You can help us for this.

**Comment by Marlinekhavele** [comment]
All of the above solutions don't work for me I don't know why

**Comment by DanyloHepner** [comment]
s
