### ISSUE TITLE
babel-runtime should be peerDeps instead of deps

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#6594]
https://github.com/ant-design/ant-design/blob/master/package.json#L39

deps on babel-runtime may cause repeat packing with the deps in app, I think it should be peerDeps

**Comment by afc163** [comment]
antd lib files depend on it so I think it should be in `dependencies`.

> cause repeat packing

Could you provider example for this?

**Comment by yesmeck** [comment]
> cause repeat packing

Only when host project depends other versions of babel-runtime then `6.x`.

**Comment by jaredleechn** [comment]
yes, once any versions of babel-runtime existed on the deps chain not the same, they  will be installed all, and packed all.

one example is g2-react and g2, if g2-react deps on g2, the apps which use g2-react also deps on g2, if the version of g2 not the same, g2 will be packed for 2 times

another as follows, the babel-runtime will be packed for 3 times
```
a
|-- babel-runtime@6.0
|-- b
   |-- babel-runtime@6.1
|-- c
   | -- babel-runtime@5
```

so the best way is application use deps and any other libraries use peerDeps, but indeed it's not friendly enough for fresh guys to config

**Comment by afc163** [comment]
It is not the same, people shouldn't care about `babel-runtime` when they are using `antd`.

**Comment by yesmeck** [comment]
6.x 的依赖足够宽松了，大部分时候依赖都会被打平的。
