### ISSUE TITLE
切换月份的时候，视觉上会默认选中当前时间值的日，但是实际上没有选中

### ISSUE THREAD

**Issue by ttshangxiang** [ant-design/ant-design#6596]
### Version
2.11.1

### Environment
无

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
无

### What is expected?
在可以选时间的模式，切换月份时，不要默认选中当前时间是日期，只是视觉上的选中，会造成误导。或者可以用其他样式区分，选中和当前日期提示

### What is actually happening?
在可以选时间的模式，切换月份时，会默认选中当前时间是日期

**Comment by afc163** [comment]
trace #6146
