### ISSUE TITLE
table 希望能添加将数据导出为 CSV 或 Excel 等格式的文件

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#6598]
### What problem does this feature solve?
table数据导出成表格文件，供运营财务等部分人员使用

### What does the proposed API look like?
将table组件中显示的数据全部或可选择的部分导出

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1977

**Comment by dongxiaoyun123** [comment]
表格导出有没有比较复杂的形式呢，比如上面显示固定内容，下面显示列表？
