### ISSUE TITLE
AutoComplete: Re-renders cause the dropdown popup to appear by itself.

### ISSUE THREAD

**Issue by orzarchi** [ant-design/ant-design#6600]
### Version
2.11.1

### Environment
macOS Sierra, Chrome 58.0.3029.

### Reproduction link
[https://codepen.io/anon/pen/MovVQq](https://codepen.io/anon/pen/MovVQq)

### Steps to reproduce
Create an AutoComplete component whose value is changed as a result of an "onSelect" callback. 
Try it again with a longer callback.

### What is expected?
The AutoComplete value will be immediately set. After the onSelect callback and the delay, nothing will change even if there are re-renders.

### What is actually happening?
The AutoComplete component will re-show its popup.

---
Please look at the reproduction to make things more clear.
I've included a workaround that solves the problem. 
The workaround proves that if the component does not re-render, the popup does not reappear.

**Comment by afc163** [comment]
https://github.com/react-component/select/commit/48eb3fd071076c12f4709dbb49973bb8167d1ad1

**Comment by afc163** [comment]
#2975 #3958 #6600 这三个 issue 要一起考虑。
