### ISSUE TITLE
Antd Antd-Mobild 官网首页能否把顶部的菜单栏固定住，方便使用搜索框快速查看API

### ISSUE THREAD

**Issue by Manweill** [ant-design/ant-design#6604]
### What problem does this feature solve?
Antd Antd-Mobild 官网首页能否把顶部的菜单栏固定住，方便使用搜索框快速查看API

### What does the proposed API look like?
Antd Antd-Mobild 官网首页能否把顶部的菜单栏固定住，方便使用搜索框快速查看API

**Comment by paranoidjk** [comment]
+1

**Comment by afc163** [comment]
这样太浪费屏幕空间了，还是不固定的好。

**Comment by Manweill** [comment]
我还是觉得有很大一部分人有这方面的需求的，或者加个按扭来选择固定还是不固定可好？

**Comment by paranoidjk** [comment]
加按钮来设置 ui 就有点矫枉过正了..

要么加个 back to top

或者做一个键盘快捷键

**Comment by benjycui** [comment]
> 要么加个 back to top

这个会和 https://ant.design/components/back-top/ 冲突的。。

**Comment by benjycui** [comment]
像 GitHub 这样，按 `s` 自动滚动到顶部并 focus 搜索框即可。

**Comment by benjycui** [comment]
@Manweill 来个 PR

**Comment by benjycui** [comment]
突然想起 Select 无法 `.focus` 。。。

**Comment by Manweill** [comment]
@benjycui 换成autocomplate？

**Comment by benjycui** [comment]
> @benjycui 换成autocomplate？

AutoComplete 就是用 Select 做的。。

**Comment by afc163** [comment]
```
<AutoComplete>
  <Input />
</AutoComplete>
```

**Comment by afc163** [comment]
@Manweill

**Comment by jljsj33** [comment]
文档区把 backTop 加上啊，，，太长的页面像 Layout 滚到最下面了，，，想回到导航，，，滚死我了。。。

**Comment by paranoidjk** [comment]
> 要么加个 back to top
这个会和 https://ant.design/components/back-top/ 冲突的。。

@benjycui  特殊解决一下好了，没必要因为和组件 demo 冲突就整个网站不能加 back to top

**Comment by benjycui** [comment]
> @benjycui 特殊解决一下好了，没必要因为和组件 demo 冲突就整个网站不能加 back to top

这个是认知成本的问题，试想你是对 BackTop 这个组件一无所知的用户。

**Comment by jljsj33** [comment]
这年头还有对 backTop 一无所知的用户????真当用户是什么？？？？

**Comment by benjycui** [comment]
> 这年头还有对 backTop 一无所知的用户????真当用户是什么？？？？

对 antd.BackTop 这个组件的用法及对应的行为。

**Comment by afc163** [comment]
@Manweill

**Comment by Manweill** [comment]
什么？ @afc163

**Comment by afc163** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/507615/28742876-1d82236c-746e-11e7-9ad5-10dfa6055436.png">

**Comment by Manweill** [comment]
https://github.com/ant-design/ant-design/pull/7007
