### ISSUE TITLE
为输入框增加label属性

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#6606]
### What problem does this feature solve?
现在像DatePicker, Select, Input等用户输入组件都没有label属性，用来表示组件前面的文字说明。需要手工自己实现，但是会写很多额外的样式，如果组件内部默认支持label文本的话，会很大程度地方便样式的统一。

### What does the proposed API look like?
label：标签文本 string|boolean; default: boolean false表示无标签文本；如果有字符串，则表示显示标签文本；

**Comment by yesmeck** [comment]
Use `Form.Item[label]`.
