### ISSUE TITLE
贵项目网站首页的'ANT'字样看不清

### ISSUE THREAD

**Issue by sduworm** [ant-design/ant-design#6608]
### Version
2.11.2

### Environment
chrome58

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
打开贵项目网站首页https://ant.design/index-cn。
中间位置只有大写的红色DESIGN尴尬地漂在那里，下方一行小字‘一个UI设计语言’。
而ANT三个字母需要按ctrl-A才可见。
囧。

### What is expected?
期望贵公司的UI同事请大家喝个饮料吧

### What is actually happening?
好歹把项目名字写清楚

---
我开了别的浏览器，结果也一样。也可能是我眼神不大好吧。

**Comment by afc163** [comment]
Fixed, Thx!
