### ISSUE TITLE
Input textarea 自适应的bug

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#6609]
### Version
2.11.2

### Environment
window chrome 

### Reproduction link
[https://codepen.io/henryzp/pen/wermzW](https://codepen.io/henryzp/pen/wermzW)

### Steps to reproduce
当高度不够时，先会出现滚动条，然后再让其自适应。。造成的结果是一闪一闪的。。特别是在window下，特别明显

### What is expected?
未达到最大高度时，期间不出现滚动条

### What is actually happening?
会出现滚动条，一闪一闪的（不得不承认，我们组的测试妹子，这都会关注？）

---
看了一下源码，事件绑定在onChange上。

这样一来，结果是内容先加进去，出现滚动条，再触发resize height，重新设置高度。。

对比其他插件，它们是绑定在keyUp或者keyDown事件上的

**Comment by afc163** [comment]
PR is welcome~

**Comment by henryzp** [comment]
@afc163 ，你空了改一下吧。。

我考虑的场景可能会仅限于textarea。。orz..

**Comment by afc163** [comment]
你们的测试妹子肯定想不到自己给开源项目做了贡献

**Comment by henryzp** [comment]
@afc163 ，哈哈。。。
