### ISSUE TITLE
Modal.confirm 中 confirmLoading 属性失效

### ISSUE THREAD

**Issue by zhangxianggui** [ant-design/ant-design#661]
代码如下:
import {Modal, Message} from '../../components/Antd';
const confirm = Modal.confirm;
handleOnClick(e, type) {
    e.preventDefault();
    const {actions, record} = this.props;
    let loading = false;
    confirm({
      title: '你确定此操作？',
      confirmLoading: loading,
      onOk: async function() {
        loading = true;
        const {error, payload} = await actions.rejectApplyfor(record.id);
        if (error) return;
        loading = false;
      }
    });
  }
点击确定后,并没有loading的效果, 求解

**Comment by afc163** [comment]
文档中 `Modal.confirm` 没有 `confirmLoading` 这个参数吧？

**Comment by zhangxianggui** [comment]
参数 | 说明 | 类型 | 默认值
------------ | ------------- | ------------- | ------------
visible | 对话框是否可见 | Boolean | 无
confirmLoading | 确定按钮 loading | Boolean | 无
... | ... | ... | ...
## Modal.xxx()

包括:

- `Modal.info`
- `Modal.success`
- `Modal.error`
- `Modal.confirm`

**Comment by kennylbj** [comment]
给```Modal.confirm```提供一个```confirmLoading```参数是不是会比较好呢？
有些场景直接用```Promise```不是很好解决，比如使用```redux-thunk```来处理异步，这个时候还是需要confirmLoading来表示加载状态。
这种情况下我只能使用```Modal + visible```来表达，缺点是缺少```Modal.confirm```的样式和简洁性。
