### ISSUE TITLE
Tree的defaultExpandedKeys 这个属性，在初始化页面进来以后不能默认展开指定的节点，但是切换路由以后再进来就可以展开了

### ISSUE THREAD

**Issue by langwuzhe** [ant-design/ant-design#6612]
### Version
2.11.2

### Environment
win7  谷歌58.0.3029.110 react 15.4.1

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
在初始化页面进来以后不能默认展开指定的节点，但是切换路由以后再进来就可以展开了

### What is expected?
页面初始化就可以展开树节点

### What is actually happening?
在初始化页面进来以后不能默认展开指定的节点，但是切换路由以后再进来就可以展开了

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by langwuzhe** [comment]
@afc163 不好意思， 是因我书写代码不规范，造成的bug。也希望antd可以兼容这种写法
 <Tree className="myCls" showLine checkable
                      defaultExpandedKeys={this.state.defaultExpandedKeys}
                      defaultSelectedKeys={this.state.defaultSelectedKeys}
                      defaultCheckedKeys={this.state.defaultCheckedKeys}
                      onSelect={this.onSelect} onCheck={this.onCheck}
                >
                        <TreeNode title="北京市" key="0" >//如果多了这个node节点,defaultExpandedKeys、defaultSelectedKeys这些属性就有可能会失效:
                            {loop(outerData)}
                        </TreeNode>
                </Tree>

**Comment by langwuzhe** [comment]
@afc163 @afc163 不好意思， 是因我书写代码不规范，造成的bug。也希望antd可以兼容这种写法

```
 <Tree className="myCls" showLine checkable
                      defaultExpandedKeys={this.state.defaultExpandedKeys}
                      defaultSelectedKeys={this.state.defaultSelectedKeys}
                      defaultCheckedKeys={this.state.defaultCheckedKeys}
                      onSelect={this.onSelect} onCheck={this.onCheck}
                >
                        <TreeNode title="北京市" key="0" >//如果多了这个node节点,defaultExpandedKeys、defaultSelectedKeys这些属性就有可能会失效:
                            {loop(outerData)}   
                        </TreeNode>
                </Tree>
```

**Comment by afc163** [comment]
Still can not understand your problem.

**Comment by langwuzhe** [comment]
@afc163 唉，好吧！我这个问题是异步加载node 的时候发生的。你把问题关闭吧，如果后人遇到这样的问题，我想他们看了我上面的代码和注释就会明白了。Thank you for your answer

**Comment by ITGraves** [comment]
@langwuzhe 我也遇到了这个问题，请问您是如何解决的

**Comment by langwuzhe** [comment]
@ITGraves 不要用这个属性 defaultExpandedKeys  用这个 expandedKeys 属性，用状态去控制他。defaultExpandedKeys  这个不好使

**Comment by ITGraves** [comment]
@langwuzhe 好的，感谢您百忙之中的回信，人海茫茫没想到您能回信。刚刚我发现这个default属性的设置在第一次无数据渲染后异步请求到数据的第二次渲染时已经失效，所以我将其判空，在获取到数据再进行渲染，从而解决了这个问题。在此再次感谢您的帮助！

**Comment by langwuzhe** [comment]
@ITGraves 他这个属性似乎只有第一次用的时候才有效。时间太长了，我忘了当时是怎么用的了，我看下项目稍后回复你

**Comment by ITGraves** [comment]
@langwuzhe 不用麻烦了，我已经差不多知道怎么做了，不用劳烦您了，非常感谢！

**Comment by elvin-gogo** [comment]
是 因为第一次初始的时候数据是空的  而defaultExpandAll 只会执行一次  当有数据的时候 就不展开了
这个做个判断就好了  当数据加载成功之后 再渲染Tree组件

**Comment by SynChron1zed** [comment]
@ITGraves hi 这个问题你是怎么解决的

**Comment by jsdocker** [comment]
because your tree are controlled component, so when you use `defaultExpandedKeys`, it is not worked. you can use `expandedKeys` to set the init value.

**Comment by ShawLyon** [comment]
> 是 因为第一次初始的时候数据是空的 而defaultExpandAll 只会执行一次 当有数据的时候 就不展开了
> 这个做个判断就好了 当数据加载成功之后 再渲染Tree组件

你这个方法比用 expandedKeys 列出所有的节点好

**Comment by ThomasHang** [comment]
![image](https://user-images.githubusercontent.com/38105618/98643468-00b06d80-236a-11eb-8612-e09f5990dde1.png)
这样就可以了，最外层判断一下是否有值
