### ISSUE TITLE
rowSelection 分页 页面跳转时把前一页选中的行 改成未选中状态

### ISSUE THREAD

**Issue by zhaoxuedui** [ant-design/ant-design#6613]

**Comment by SpringLv** [comment]
怎么关了，遇到同样的问题了

**Comment by yesmeck** [comment]
自己通过 `selectedRowKeys` 控制。

**Comment by zhaoxuedui** [comment]
你这个是怎么控制的   能给的示例吗  第一次搞这个
发件人: Wei Zhu <notifications@github.com<mailto:notifications@github.com>>
答复: ant-design/ant-design <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年7月3日 星期一 下午6:43
至: ant-design/ant-design <ant-design@noreply.github.com<mailto:ant-design@noreply.github.com>>
抄送: didi <zhaoxuedui@didichuxing.com<mailto:zhaoxuedui@didichuxing.com>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: Re: [ant-design/ant-design] rowSelection 分页 页面跳转时把前一页选中的行 改成未选中状态 (#6613)


自己通过 selectedRowKeys 控制。

**Comment by zhongjie-chen** [comment]
When rendering, recalculate selectedRowKeys.
