### ISSUE TITLE
how to clean selectedRows when page trun

### ISSUE THREAD

**Issue by zhaoxuedui** [ant-design/ant-design#6620]
### What problem does this feature solve?
can clean selectedRows  when page truned 

### What does the proposed API look like?
can provided the api to clean selectedRows when page turned

**Comment by ddcat1115** [comment]
By setting `rowSelection.selectedRowKeys` you can handle this. Just like [demo](https://ant.design/components/table-cn/#components-table-demo-row-selection-and-operation)
