### ISSUE TITLE
Select props dropdownStyle set left/top failure

### ISSUE THREAD

**Issue by kunsam** [ant-design/ant-design#6624]
### Environment
antd 2.11.2

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe(我暂时无法提供 Link to minimal reproduction选项的Url，因此挂载上了默认提供的一个Url))

### Steps to reproduce
```
            <Select
              mode='multiple'
              notFoundContent={NOT_FOUNT_TEXT}
              dropdownMatchSelectWidth={false}
              onFocus={this.handleFocus.bind(this)}
              onSelect={this.handleSelect.bind(this)}
              onDeselect={this.handleDeslect.bind(this)}
              onSearch={this.handleSearch.bind(this)}
              getPopupContainer={() => document.getElementById('drop-down-area')}
              ***dropdownStyle={{ left: inputLeft, display: showDropDown ? '' : 'none' }}***
              dropdownClassName='my-drop-down'
            >
              {
                renderTags.map((d, i) => (<Option key={d.value}>{d.value}</Option>))
              }
            </Select>
```

### What is expected?
I want to use  dropdownStyle to control dropdown menu's left/top i.e. its position params

### What is actually happening?
The  left/top params will be coverd by components params。
传入的style参数并不生效

**Comment by yesmeck** [comment]
为什么要改下拉菜单的位置？

**Comment by kunsam** [comment]
@yesmeck  有这个业务需求，下拉菜单不是100%宽度，而是一个定宽，跟随输入光标的位置展开的

**Comment by kunsam** [comment]
@yesmeck 我现在用另一种方法解决的，使用getPopupContainer让菜单渲染在另一个节点下，然后控制这个容器节点的位置。反正是可以实现的，只不过dropdownStyle就失去了部分其包含的含义

**Comment by yesmeck** [comment]
`left` 比较特殊，因为 dropdown 的位置是动态计算的。解决了的话就先这样吧。

**Comment by alexandrduduka** [comment]
Hey, I can't read answers in Chinese, so maybe it is explained there, but I try to set dropdownClassName or dropdownStyle to change width and left in my select and it gives no effect - styles are not applied.
Could you help me @yesmeck?

**Comment by yesmeck** [comment]
`left` is a special value in the dropdown, you can use `getPopupContainer` to render dropdown to another container, then give that container a position you want.

**Comment by alexandrduduka** [comment]
@yesmeck it doesn't make a trick for me. Style.left on the dropdown set itself to whatever number to be right under select.
Here is my code:
`
        <Select
          mode="multiple"
          style={{ width: 60 }}
          // dropdownMatchSelectWidth={false}
          // dropdownStyle={{left: 1100, width: 160}}  - doesn't work
          getPopupContainer={() => document.getElementById('sssss')}
          placeholder="Visible columns"
          defaultValue={getColumnsVisibleByDefault(loanPage)}
          onChange={onChangeHandler}
        >
          <OptGroup label="Visible columns">
            {getColumnsAvailable(loanPage).map(columnType => (
              <Option key={columnType}>{columnsByType[columnType].title}</Option>
            ))}
          </OptGroup>
        </Select>
        <div id="sssss" style={{ position: 'absolute', left: -11111, margin: -100 }} /> 
`

**Comment by yesmeck** [comment]
You can not set `left` for the dropdown, but you can set the position of the container.

**Comment by alexandrduduka** [comment]
@yesmeck

**Comment by alexandrduduka** [comment]
@yesmeck could you give me a hand with it? should I consider it bug?

**Comment by yesmeck** [comment]
Could you demonstrate your issue on https://codesandebox.io?

**Comment by alexandrduduka** [comment]
Ok, here is example of what I am trying to achieve - dropdown, should be more on the left relatively to select itself:
![select_ant](https://user-images.githubusercontent.com/12681928/37657555-a2e4b6b0-2c4b-11e8-974e-ae48d5ff261c.png)

With popupContainer I try to move it left this way: https://codesandbox.io/s/jj3zm9roww

I suspect that popupContainer was made for other issues.

**Comment by yesmeck** [comment]
@alexandrduduka Try `align` https://codesandbox.io/s/7wjz23n3rj

**Comment by alexandrduduka** [comment]
@yesmeck, thank you for your response, however Menu&Dropdown is completely different component, so in this case all selection logic should be written by developer. In case Select doesn't provide expected behavior should I create an issue for it?

**Comment by yesmeck** [comment]
Dropdown and Select are all based on `rc-trigger`, In Select, it's called `dropdownAlign`.

https://codesandbox.io/s/ov56m6zk25

**Comment by alexandrduduka** [comment]
Oh, now I see! Thanks a lot :-)

**Comment by Stupidism** [comment]
For anyone who is looking for the document, too:
dependency chain:
`Select.dropdownAlign` => `rc-select.dropdownAlign` => `rc-trigger. popupAlign` => `dom-align.alignConfig`

[rc-select](https://www.npmjs.com/package/rc-select)
[rc-trigger](https://www.npmjs.com/package/rc-trigger)
[dom-align](https://github.com/yiminghe/dom-align)

**Comment by zooeyking** [comment]
我试了dropdownAlign这个属性，但是还是不能解决我的问题。因为dropdownAlign={{offset: [x, y]}}中的x y 是相对于你计算出来的top left偏移的，由于你计算出来的top,left值是变化的 导致我无法确定偏移量x,y 要设为多少。
我的理解是 当我设置了dropdownStyle 后，当 dropdownStyle中有top,left属性的时候，你就不需要计算top，left值了，直接使用我dropdownStyle中设置的top,left值。现在是你用计算出来的top,left值 把我dropdownStyle中的top, left覆盖掉了。这显然是不合理的吧。

**Comment by babycannotsay** [comment]
附议楼上

**Comment by tomapoo** [comment]
可以计算select节点的位置，用你的left减去select节点其实位置得到dropdownAlign中的x
