### ISSUE TITLE
How to disable Tooltip's `autoAdjustOverflow` feature

### ISSUE THREAD

**Issue by jdz321** [ant-design/ant-design#6625]
### What problem does this feature solve?
Tooltip sets align prop of Trigger with `autoAdjustOverflow` feature by default. 
see https://github.com/react-component/tooltip/blob/master/src/placements.js#L1

However,  it leads to Issues sometimes. I've resolved it by a private way.

```javascript
const align = {
  points: ['tc', 'bc'],
  offset: [0, -4],
  targetOffset: [0, 0],
  overflow: { adjustY: 0 },
};
<Tooltip popupAlign={align} />
```

Could it provide a shortcut option like `autoAdjustOverflow` to disable this feature, or document `popupAlign` prop definitely?

### What does the proposed API look like?
```javascript
<Tooltip autoAdjustOverflow={false} />
```

or

```javascript
const align = {
  points: ['tc', 'bc'],
  offset: [0, -4],
  targetOffset: [0, 0],
  overflow: { adjustY: 0 },
};
// document it definitely.
<Tooltip popupAlign={align} />
```

**Comment by afc163** [comment]
I think `autoAdjustOverflow` will be great.

**Comment by jdz321** [comment]
Great minds think alike.😁     I'll create a PR later.
