### ISSUE TITLE
Select : why there's no  max / min prop which I can control the length of selected items.

### ISSUE THREAD

**Issue by magnnus** [ant-design/ant-design#6626]
### What problem does this feature solve?
when i use the Select Component, and use mode="Multiple" , I want to limit the length of selected items.  There is no convenient method/props I can use.

### What does the proposed API look like?
min={1} max={5}

**Comment by yesmeck** [comment]
You can control select items by `value`.

**Comment by oc-shady** [comment]
yes i control items by value[disable], in my project, 
before round(),  check the length of selected value, if it's over the limit, put the others value disable
it's worded
but
i recommend that the Multiple Select support max/min

**Comment by bodaz** [comment]
Agreed. API like `min={}` and `max={}` would really be helpful in many scenarios, and the approach of setting all the rest options to `disabled` when the limit is reached looks unfriendly in a large list of options. A good example of this is StackOverflow's tags are limited to 5 when asking a question.

**Comment by bodaz** [comment]
Extending on my answer, I am currently limiting Select items using `getFieldDecorator`.

```js
<FormItem label="Tags (up to 5)">
  {getFieldDecorator("tags", {
    rules: [
      {
        required: true,
        message: "Please select at least one tag!"
      },
      {
        validator: (rule, value, callback) => {
          if (value) {
            if (value.length > 5) {
              callback("No more than 5 tags");
            } else if (value.length <= 5) {
              callback();
            }
          }
          return;
        }
      }
    ]
  })(
    <Select
      mode="multiple"
      placeholder="Select Tags"
    >
        <Option value="1">One</Option>
        <Option value="2">Two</Option>
        <Option value="3">Three</Option>
        <Option value="4">Four</Option>
        <Option value="5">Five</Option>
        <Option value="6">Six</Option>
        <Option value="7">Seven</Option>
    </Select>
  )}
</FormItem>
```
Feedbacks on this code are welcome!

**Comment by fgiarritiello** [comment]
Is there a way to make the Select in tags mode behave like a combobox where I can only have one tag selected and am also able to create a new one is it's not in the list?

Any code example would be much appreciated.

**Comment by lezan** [comment]
Is it still an issue, right?

**Comment by rightroad** [comment]
@lezan , yeah I think so, In my case I only trigger the validator to prevent the user from entering X tags.

` <Form.Item
                  name={["tags"]}
                  label="Tags"
                  rules={[
                    {
                      required: true,
                    },
                    {
                      validator: (rule, value) => {
                        if (!!value && value.length > 1)
                          return Promise.reject("One tag only allowed.");
                        return Promise.resolve();
                      },
                    },
                  ]}
                >
                  <Select mode="tags">
                    <Option key={"tag1"}>Tag 1</Option>
                    <Option key={"tag2"}>Tag 2</Option>
                    <Option key={"tag3"}>Tag 3</Option>
                  </Select>
                </Form.Item>`

**Comment by doantientai** [comment]
I think it is very important to add min/max option to select multiple because validation only work when the select is in a form. Also, I think using value[disable] won't work correctly. If the user remove one selection, the select must be enabled again.

**Comment by paschaldev** [comment]
This is actually important. Searched on github looking for a way

**Comment by doantientai** [comment]
Please reopen the issue

**Comment by Haqverdi** [comment]
Reopen

**Comment by eastmaels** [comment]
Would like to have this feature as well.

**Comment by artdiev** [comment]
Still a pain to deal with

**Comment by MassoudSharifi** [comment]
Reopen

**Comment by simon-marcus** [comment]
Agreed it would be great to reopen this issue and to implement the `min={1}`, `max={5}` approach familiar in Ant that others have mentioned.

**Comment by GaboMendez** [comment]
reopen pls 😭

**Comment by rsbh** [comment]
reopen

**Comment by adrienpsl** [comment]
Hi, I've found a solution based on https://github.com/ant-design/ant-design/issues/8215 

``` tsx
<Select
        mode="tags"
        onChange={value => {
          if (value?.length > 1) {
            // if you want only one element :).
            value.pop();
          }
        }}
      >
```

**Comment by veigastom** [comment]
I had to make a workaround to achieve the same.
`<FormItem
          label="Participant"
          name="participant"
          rules={[
            {
              validator: (rule, value, callback, ...rest) => {
                if (value.length > 2) {
                   value.pop();
                   form.resetFields(['participant'])
                  form.setFieldsValue({
                    participant: value,
                  });
                   callback("error ");
                  message.error("No more then two members are allowed.");
                } else if (value.length < 2) {
                  message.error("No less then two members are allowed.");
                }
              },
            },
          ]}
        >
          <Select mode="multiple" options={options}>
            {members &
              members
                .sort((a, b) => (a["first_name"] > b["first_name"] ? 1 : -1))
                .map((item) => {
                  return (
                    <Select.Option>
                      {item["first_name"] + " " + item["last_name"]}
                    </Select.Option>
                  );
                })}
          </Select>
        </FormItem>`

**Comment by veigastom** [comment]
made a workaround to achieve the same.
<FormItem
          label="Participant"
          name="participant"
          rules={[
            {
              validator: (rule, value, callback, ...rest) => {
                if (value.length > 2) {
                   value.pop();
                   form.resetFields(['participant'])
                  form.setFieldsValue({
                    participant: value,
                  });
                   callback("error ");
                  message.error("No more then two members are allowed.");
                } else if (value.length < 2) {
                  message.error("No less then two members are allowed.");
                }
              },
            },
          ]}
        >
          <Select mode="multiple" options={options}>
            {members &
              members
                .sort((a, b) => (a["first_name"] > b["first_name"] ? 1 : -1))
                .map((item) => {
                  return (
                    <Select.Option>
                      {item["first_name"] + " " + item["last_name"]}
                    </Select.Option>
                  );
                })}
          </Select>
        </FormItem>

**Comment by veigastom** [comment]
<FormItem
          label="Participant"
          name="participant"
          rules={[
            {
              validator: (rule, value, callback, ...rest) => {
                if (value.length > 2) {
                   value.pop();
                   form.resetFields(['participant'])
                  form.setFieldsValue({
                    participant: value,
                  });
                   callback("error ");
                  message.error("No more then two members are allowed.");
                } else if (value.length < 2) {
                  message.error("No less then two members are allowed.");
                }
              },
            },
          ]}
        >
          <Select mode="multiple" options={options}>
            {members &
              members
                .sort((a, b) => (a["first_name"] > b["first_name"] ? 1 : -1))
                .map((item) => {
                  return (
                    <Select.Option>
                      {item["first_name"] + " " + item["last_name"]}
                    </Select.Option>
                  );
                })}
          </Select>
        </FormItem>

**Comment by veigastom** [comment]
A workaround to achieve the same.

 ```javascript
 <FormItem
          label="Participant"
          name="participant"
          rules={[
            {
              validator: (rule, value, callback, ...rest) => {
                if (value.length > 2) {
                   value.pop();
                   form.resetFields(['participant'])
                  form.setFieldsValue({
                    participant: value,
                  });
                   callback("error ");
                  message.error("No more then two members are allowed.");
                } else if (value.length < 2) {
                  message.error("No less then two members are allowed.");
                }
              },
            },
          ]}
        >
          <Select mode="multiple" options={options}>
            {members &
              members
                .sort((a, b) => (a["first_name"] > b["first_name"] ? 1 : -1))
                .map((item) => {
                  return (
                    <Select.Option>
                      {item["first_name"] + " " + item["last_name"]}
                    </Select.Option>
                  );
                })}
          </Select>
        </FormItem>
```

**Comment by mrlubos** [comment]
Ah 😔

**Comment by guoenyue** [comment]
rererererererereopen

**Comment by migokcek** [comment]
We definitely need that min/max please reopen

**Comment by dallen-baldwin-horrocks** [comment]
I'd really appreciate this as well. I'm looking for a way to enforce _at least one_ selection and due to the decisions of previous teammates... I can't use a form item and set a rule up to achieve that. We shouldn't have to use form items to get a min/max functionality

**Comment by JPM709** [comment]
Please reopen! I have a similar problem. using the tags selector, I want the user to select one from the list or create only one tag to ship to API. I can limit the number in my dispatch method, but the user can still select and make as many tags as they want in the component. min max props would be ideal.
![image](https://user-images.githubusercontent.com/72175425/166749324-e654825c-7d86-4232-b69f-0531e93a8f7f.png)

**Comment by jansila** [comment]
You can use my code here. It does not allow more than 2 tags selected. 
Just return a Promise.reject:

```js
<Form.Item name="kegBeerVolumes" label="Dostupné objemy" rules={[{
            required: true,
            message: "Please select at least one tag!"
        }, , {
            validator: tagSizeValidator
        }]}>
<Select multiple mode="tags">...Options here ....</Select>
</Form.Item>
```
then the validator itself
```js
const tagSizeValidator = async (rule, value, callback) => {
    if (value) {
        if (value.length > 2) {
            return Promise.reject("Cannot have more than 2 tags")

        } else if (value.length <= 2) {
            return Promise.resolve()
        }
    }
    return
}

**Comment by ayrosochang** [comment]
Please reopen

**Comment by vishnu-dev** [comment]
Ant design be like

![image](https://user-images.githubusercontent.com/21088161/227286132-b3586b26-8f48-4993-a109-189c72f0d263.png)

**Comment by minhtrung0110** [comment]
Thanks. That's a good idea.

**Comment by rushi-ladke** [comment]
Please Reopen, I need it too

**Comment by gidgudgod** [comment]
Please reopen, this would be an essential prop!

**Comment by jzthacoder** [comment]
please reopen!

**Comment by evgeniyworkbel** [comment]
reopen please

**Comment by li-jia-nan** [comment]
I think it's a good idea

**Comment by ChangJin0520** [comment]
reopen please

**Comment by MadCcc** [comment]
Should support `maxCount` prop.

**Comment by Wxh16144** [comment]
In tags and multiple modes, whether to truncate or allow pastes that exceed the maximum number of counts. 🤔
https://ant.design/components/select#select-demo-automatic-tokenization

https://github.com/ant-design/ant-design/assets/32004925/650e3026-bd09-4868-a5d2-891e9fef1a2e

**Comment by Amin-create** [comment]
> yes i control items by value[disable], in my project, before round(), check the length of selected value, if it's over the limit, put the others value disable it's worded but i recommend that the Multiple Select support max/min

maxCount prop is now available:
https://ant.design/components/select

**Comment by sugionosihuahua** [comment]
not available for vue js yet?
