### ISSUE TITLE
CheckBox: like Radio.RadioButton,  Is there a similar components in CheckBox. 

### ISSUE THREAD

**Issue by magnnus** [ant-design/ant-design#6627]
### What problem does this feature solve?
In some case , the UI don't want to be the default style but a button style(like RadioButton), when use the checkbox, 

### What does the proposed API look like?
CheckBoxButton

**Comment by afc163** [comment]
Don't have plan for it now. You can use `Button.Group` or `CheckableTag`: https://ant.design/components/tag/#components-tag-demo-hot-tags now.
