### ISSUE TITLE
使用表格和modal.confirm样式错乱，Popconfirm不显示

### ISSUE THREAD

**Issue by goodchax** [ant-design/ant-design#6629]
### Version
2.11.2

###  #Environment
浏览器版本

### Reproduction link
[https://github.com/goodchax/test.git](https://github.com/goodchax/test.git)

### Steps to reproduce
同时使用table，modal.confirm的遮罩背影旋转。popconfirm不显示

### What is expected?
modal.confirm的遮罩背影不旋转。popconfirm显示

### What is actually happening?
modal.confirm的遮罩背影旋转。popconfirm不显示
![qq20170627-181040-hd](https://user-images.githubusercontent.com/16410518/27582611-15476a54-5b64-11e7-8f10-b0a063a1557e.gif)

**Comment by yesmeck** [comment]
有了留言下吧，我再打开。

**Comment by goodchax** [comment]
什么意思？

**Comment by yesmeck** [comment]
> http://baidu.com/暂时没有

**Comment by goodchax** [comment]
哦哦，你看一下gif，出现这种情况是为什么？

**Comment by yesmeck** [comment]
看不出来，提供下再现吧。

**Comment by goodchax** [comment]
现在环境报错了，我弄好了。发个版本。

**Comment by goodchax** [comment]
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'history/createBrowserHistory' in '/Users/c/Code/node-test/test/src'
这个问题怎么解决？

**Comment by goodchax** [comment]
https://github.com/goodchax/test.git
url:http://localhost:8041/index
点击第二个删除，出现弹出框，点击取消就可以看到效果

**Comment by yesmeck** [comment]
你的项目跑不起来，请提供一个最小的可重现在线 demo。

**Comment by goodchax** [comment]
已经更新代码，npm install 然后npm start;
环境配置有点问题，现在已经解决，辛苦看一下

**Comment by benjycui** [comment]
@goodchax 重现步骤？

**Comment by benjycui** [comment]
ant-design 仓库里面把 `Modal.confirm` 和 `Table` 放在一起是没问题的。

**Comment by yesmeck** [comment]
原因是用了 cssnano 后  Modal 的动画跟 Spin 的动画串掉了，见 https://github.com/ben-eb/cssnano/issues/247
