### ISSUE TITLE
`rcUtil.classSet()` is deprecated

### ISSUE THREAD

**Issue by MarshallChen** [ant-design/ant-design#663]
console warning this when I use `{ message } from 'antd'`

`rcUtil.classSet()` is deprecated, use `classNames()` by `require('classnames')` instead

How can I prevent this warning message?

**Comment by benjycui** [comment]
see: https://github.com/react-component/notification/pull/6

**Comment by benjycui** [comment]
`npm uninstall rc-notification && npm install`
