### ISSUE TITLE
Can Select accept options prop?

### ISSUE THREAD

**Issue by newraina** [ant-design/ant-design#6630]
### What problem does this feature solve?
Currently, select component requires the options to be supplied separate as Option child component. This is not convenient when using dynamic components. 

### What does the proposed API look like?
Just like the [react-select](https://github.com/JedWatson/react-select#usage) or [antd/Radio.Group](https://ant.design/components/radio-cn/#RadioGroup) does:

```tsx
<Select options={[{ label, value }]} />
```

**Comment by afc163** [comment]
You can create a HOC component for it. We don't have plan for it.
