### ISSUE TITLE
Table need some props to define event when th clicked or some props to start sort when th clicked.

### ISSUE THREAD

**Issue by blankzust** [ant-design/ant-design#6633]
### What problem does this feature solve?
I need this because I want to start sort when th clicked.But Table just offer little sort button for me to start sort and sort button is a little small.

### What does the proposed API look like?
```<Column onThClicked={() => {}}/> ```

or 

```<Column isSortedByTh={ true }/>```(I like this)

**Comment by blankzust** [comment]
like this
![qq20170629-111536-hd](https://user-images.githubusercontent.com/8541906/27669976-85b6bb56-5cbc-11e7-8ea0-325cfd24937a.gif)

**Comment by benjycui** [comment]
How about:

```jsx
const columns = [{
  title: <span onClick={...} />
}]
```

**Comment by blankzust** [comment]
It can solve my problem. But it adds many functions and looks tedious.

**Comment by blankzust** [comment]
@benjycui

**Comment by benjycui** [comment]
> But it adds many functions and looks tedious.

It's better to do this in your own code, instead integrate them into antd
