### ISSUE TITLE
AutoComplete 搜索渲染下拉列表异常

### ISSUE THREAD

**Issue by yezihaohao** [ant-design/ant-design#6634]
### Version
2.10.4

### Environment
chrome 59.0.3071.86

### Reproduction link
[https://codepen.io/yezihaohao/pen/vZWqoE](https://codepen.io/yezihaohao/pen/vZWqoE)

### Steps to reproduce
版本： 2.10.4

数据：dataSource: [{
title: '歌曲',
children: [{"songName":"我说我爱你","songId":5348},{"songName":"我爱你","songId":6867},{"songName":"我爱你","songId":8685},{"songName":"我爱你","songId":1266}],
}]

不知道是我没用对还是bug，我用的文档上面的autocomplete查询模式 - 确定类目

渲染之后报错：Warning: flattenChildren(...): Encountered two children with the same key, .$我爱你. Child keys must be unique; when two children share a key, only the first child will be used

并且只渲染出了两条数据，我的目的是4条数据。而且不知道这个key是从哪里来的。我已经设置了option的key，是songId，唯一的。正常来说不应该报这个错。

### What is expected?
我的目的是4条数据

### What is actually happening?
只渲染了两条，并且报错

---
搜索需要，在线急等～～

**Comment by yesmeck** [comment]
`value` 不能有相同的，你有三个 “我爱你”。

**Comment by yezihaohao** [comment]
那这个是不是不太满足需求？如果我设置value为id的话，选择某一项的时候，输入框显示的是ID，而需求是显示对应的名称。。 @yesmeck

**Comment by yesmeck** [comment]
`value` 应该是唯一的，不然组件不知道应该选哪个。

**Comment by yezihaohao** [comment]
那有没有办法让value设置成ID，选择后input显示对应的名称字段？我设置了value = songName + songId。。但是感觉这种方式比较另类。删除输入框值的过程中，会带上这个ID进行搜索

**Comment by yesmeck** [comment]
补全为什么要补三个一样的值？

**Comment by yesmeck** [comment]
试试 `optionLabelProp`

**Comment by Evan-Leee** [comment]
那设置这个 `key` 有什么用呢，已经给了key唯一的值，最后又被value的值复写了

**Comment by abellee** [comment]
匪夷所思的逻辑，要确定唯一有千万种方法，拿这种label性质的字段来做唯一性 你让那些key, id作何感想？

**Comment by yesmeck** [comment]
如果觉得这个逻辑有问题，那么你需要的很可能是 `<Select showSearch />`。
