### ISSUE TITLE
Scrolling on antd table does not work if we customise the header of table

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#6635]
### Version
2.9.1

### Environment
OS: Windows 10 , Broswer: Chrome, react: v15

### Reproduction link
[https://codepen.io/anon/pen/dRZBLx?editors=0010](https://codepen.io/anon/pen/dRZBLx?editors=0010)

### Steps to reproduce
Please execute the provided codepen

### What is expected?
Header of table should be aligned with the rows of table

### What is actually happening?
Header and rows are not aligned.

**Comment by KalpanaPagariya** [comment]
I cannot set the width of the column. We want it should be auto.

**Comment by afc163** [comment]
Your codepen is not available.

**Comment by afc163** [comment]
> I cannot set the width of the column. We want it should be auto.

You have to. There is not a perfect solution now.
