### ISSUE TITLE
Form.resetFields and onChange event

### ISSUE THREAD

**Issue by callmemb** [ant-design/ant-design#6636]
### What problem does this feature solve?
This feature would help alot while building dynamic forms (fields showing/hiding depends on previous picks).
Currently its hard to fully reset form when form contains children components with own state edited by select onChange.

### What does the proposed API look like?
'this.props.form.resetFields( {} , {triggerOnChange:true} )` or made onChange trigger as default.

**Comment by benjycui** [comment]
I don't understand, please provide more information.

**Comment by callmemb** [comment]
lets say we got a react component 

```
class roleItems extends Component {

  constructor(props) {
    super(props);
    
    this.state = {
      hideSelection: true
    };
  }
  
  onChange(type){
    if(type){
      this.setState({
        hideSelection: false
      });
    }else{
      this.setState({
        hideSelection: true
      });
   }
  }

  render() {

    const {getFieldDecorator} = this.props.form;

    return (
      <div>
    
        <FormItem
        label='select1' />}
          >
          {getFieldDecorator('select1', {
          })(
          <Select
            placeholder = 'select1'
            onChange={this.onChange}
            >
            // select options here
          )}
          </Select>
          )}
        </FormItem>
        
        
        {!this.state.hideSelection?
        <FormItem
          label='select2'
          >
          {getFieldDecorator('select2', {
          })(
          <Select
            placeholder = 'select2'
            >
            // options again
          )}
          </Select>
          )}
        </FormItem>:null}
        
      </div>
      
      );
  }
};
```
and it is part of biger form component. I would like to know when to hide select2 element on clearing select1 value, but as far as i know there is no event triggered by form.resetFields function

i would like onChange event (placed on select1) to be triggered when reseting form.

**Comment by benjycui** [comment]
It's weird.

You can trigger customized event:

```jsx
form.resetFields();
trigger('clearSelect1');

on('clearSelect1', () => {
  // hide select2
});
```

**Comment by GravityMsc** [comment]
@benjycui 我现在也碰到这种情况： 组件1 联动控制 组件2。 我在组件1加载完成后用setFields预填了内容，我期望setFields可以触发其onChange事件，进而影响到组件2，事实上并不如此。

或许我们可以在api上加上触发onChange的可选项？

**Comment by bennik88** [comment]
> It's weird.
> 
> You can trigger customized event:
> 
> ```js
> form.resetFields();
> trigger('clearSelect1');
> 
> on('clearSelect1', () => {
>   // hide select2
> });
> ```
How would you trigger a custom event in react if its considered bad practice to pass up events from child components. [Link](https://stackoverflow.com/questions/21951734/react-js-custom-events-for-communicating-with-parent-nodes)
And using useImperativeHandle() for every field to update it's value would be insane.
I don't see how you want to trigger an onChange update from form.resetFields() to the onChange state in the child component.
