### ISSUE TITLE
Datepicker没有value属性

### ISSUE THREAD

**Issue by JiangAmber** [ant-design/ant-design#664]
我在使用ant的datepicker的时候没有发现value属性 只有defaultvalue属性  但是我要做一个数据的修改功能  这个功能是将table离的数据展示在下面的form中 可是datepicker没有value属性  这个应该怎么实现呢

**Comment by afc163** [comment]
datepicker 有 value 属性。

**Comment by afc163** [comment]
datepicker 有 value 属性。

**Comment by afc163** [comment]
datepicker 有 value 属性。

**Comment by JiangAmber** [comment]
哦 谢谢
