### ISSUE TITLE
IE10 TreeSelect.TreeNode is undefined

### ISSUE THREAD

**Issue by Syzmex** [ant-design/ant-design#6640]
**IE10 TreeSelect.TreeNode is undefined.**

So I use Tree.TreeNode instead. lucky! It works .

**Comment by benjycui** [comment]
It works fine https://ant.design/components/tree-select/

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
https://www.npmjs.com/package/babel-preset-es2015-ie

https://github.com/ant-tool/atool-build/issues/126#issuecomment-215307162

**Comment by Syzmex** [comment]
thank you !! Now it works fine.

```js
babelOptions.plugins.push( 'transform-class-properties' );
babelOptions.plugins.push([ 'transform-es2015-classes', { loose: true }]);
babelOptions.plugins.push( 'transform-proto-to-assign' );
babelOptions.plugins.push( 'transform-decorators-legacy' );
babelOptions.plugins.push( 'transform-runtime' );
babelOptions.plugins.push( 'dva-hmr' );
babelOptions.plugins.push([ 'import', { libraryName: 'antd', style: true }]);
```
