### ISSUE TITLE
InputNumber is missing events

### ISSUE THREAD

**Issue by drcmda** [ant-design/ant-design#6644]
### Version
2.11.2

### Environment
MacOS

### Reproduction link
[https://codepen.io/drcmdaa/pen/yXpNJm](https://codepen.io/drcmdaa/pen/yXpNJm)

### Steps to reproduce
Input and many other controls allow for onKeyPress, for instance to receive enter/return. InputNumber doesn't seem to do that, i see no way to react to the enter event anymore. 

### What is expected?

```js
<Input onKeyPress={() => alert("it works")}/>
<InputNumber onKeyPress={() => alert("it doesn't work")}/>
```

It should expose a similar interface as Input

### What is actually happening?
It doesn't

---
Thank you all for your time!

**Comment by afc163** [comment]
What `onKeyPress` is used for?

**Comment by drcmda** [comment]
You can use onKeyPress={e => e.key === 'Enter' && ... } for instance.

If there's a better way to test for `enter` in input fields i take it, but until now i've been using that with regular Input controls. Recently we switched to InputValue but they don't share the event, so we can't react when user presses enter.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/mwpEpN

You can use `onKeyDown` or `onKeyUp` for it. https://github.com/ant-design/ant-design/issues/4717

I know `onKeyPress` is not supported now, but we won't fix it until we have to for now.

**Comment by hco** [comment]
@afc163: Does onKeyDown really exist on InputNumber? At least from the typescript typings it seems to me like it's missing.

**Comment by afc163** [comment]
You can propose a PR to fix it.
