### ISSUE TITLE
Why time-picker dropdown has a blank on the bottom?

### ISSUE THREAD

**Issue by wxt2005** [ant-design/ant-design#6648]
### Version
2.11.2

### Environment
MacOS 10.12.5, Chrome 59

### Reproduction link
[https://ant.design/components/time-picker/](https://ant.design/components/time-picker/)

### Steps to reproduce
Open time-picker, scroll down to the bottom (23:59:59), there's a 120px padding on the bottom. 

### What is expected?
No padding on the dropdown selector of time-picker.

### What is actually happening?
A 120px padding on the bottom.

---
I wonder why it's exist, because [rc-time-picker](http://react-component.github.io/time-picker/) doesn't have this padding.
I found a related [issue](https://github.com/ant-design/ant-design/issues/3793), but still not able to understand the reason.

**Comment by afc163** [comment]
<img width="217" alt="image" src="https://user-images.githubusercontent.com/507615/27637247-a6140d02-5c41-11e7-8c9f-bf39c0080c36.png">

Avoid this situation. It is by designed, the selected value should be vertically aligned.

**Comment by Guruprasanth98** [comment]
![Screenshot 2024-01-19 171149](https://github.com/ant-design/ant-design/assets/149993793/dc9a73f0-d6d8-4663-b2cf-d3db198648a9)
can anyone help me to fix this issue?

**Comment by Muhammadbilalhaider** [comment]
This might works for it 

.ant-picker-time-panel-column {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
}
