### ISSUE TITLE
timepicker组件是否新增了value属性，value属性的参数是什么格式？

### ISSUE THREAD

**Issue by taoweiho** [ant-design/ant-design#665]
timepicker 是否新增了value属性，value属性的参数是什么格式？

**Comment by JiangAmber** [comment]
timepicker现在好像没有value属性

**Comment by JiangAmber** [comment]
刚才我使用timepicker的时候好像用value报错了

**Comment by JiangAmber** [comment]
timepicker什么时候支持value属性

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/578
