### ISSUE TITLE
tree控件的checkbox功能, 能否实现UI上勾选了所有节点, 而实际获取已选节点只有顶级节点的功能, 来减少设置用户对部门的管理关系的传输数据量

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6656]
### What problem does this feature solve?
antd中tree的checkbox功能, 我知道有级联选择和非级联选择的功能, 比如勾选了顶级节点, 在获取所选节点的时候, 前者得到的[]中会有所有节点, 如果有2w个部门那么这个数据量是很大的, 而后者的[]中只有一个勾选的节点, 如果加上异步加载的话, 那勾选的数据就明显不对了, 因为有的数据还未加载, 
因此我希望在UI上面展示是勾选了所有节点, 但是实际获取的[]只有顶级节点这一个节点, 请问如何实现

### What does the proposed API look like?
这个随意

**Comment by benjycui** [comment]
> 减少设置用户对部门的管理关系的传输数据量

这个在拿到 Tree 返回的值时，再自行处理即可。

**Comment by justkuai** [comment]
@benjycui 我不用这个tree的checkbox了, 自己开发了一个左侧是tree, 右侧是已选节点的控件, 单击那个就移动到右侧, 且不能重复添加, 呵呵,  就像穿梭框一样, 完美实现
