### ISSUE TITLE
嵌套表格  父表格设置scroll属性后 嵌套表格显示问题

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#6657]
### Version
2.11.2

### Environment
win7  chrome版本 59.0.3043.0  

### Reproduction link
[https://codepen.io/anon/pen/JNZJGm?editors=0111](https://codepen.io/anon/pen/JNZJGm?editors=0111)

### Steps to reproduce
复制 https://ant.design/components/table-cn/#components-table-demo-nested-table 网址上的代码 ，在表格中加入scroll属性

### What is expected?
表格有scroll属性，鼠标移动上去后，嵌套表格也是有背景颜色的

### What is actually happening?
鼠标移动上去后，嵌套表格没有背景颜色

**Comment by afc163** [comment]
> https://codepen.io/anon/pen/JNZJGm?editors=0111

You codepen is not relevent.

**Comment by changyijie** [comment]
Sorry, that link was copied wrong. This is new  [https://codepen.io/anon/pen/RgQZXo?editors=1111.](url)    This Table is added to the scroll attribute.
