### ISSUE TITLE
Localized iconfont still requests cdn resources

### ISSUE THREAD

**Issue by SecMao** [ant-design/ant-design#6658]
### Version
2.11.2

### Environment
Windows 10/ Chrome 58/ react 15.4.0

### Reproduction link
[https://github.com/SecMao/antd-iconfont-issue](https://github.com/SecMao/antd-iconfont-issue)

### Steps to reproduce
1. install and start antd-iconfont-issue
2. disconnect the network
3. open chrome development tools
4. clean browser cache and reload page
5. go to the "Network" tab in development tools

### What is expected?
load icon resources from current server and never try to visit the CDN resources while localization config is found.

### What is actually happening?
After disconnecting the network, antd load icon from localhost successfully, but there are two requests still try to load icon from CND resources. Pages loading process are slowed down by these useless tries.
![tim 20170629092018](https://user-images.githubusercontent.com/26298277/27673102-7e1a3c8c-5cd1-11e7-92d8-c3b9c3ab9574.png)

![tim 20170629093344](https://user-images.githubusercontent.com/26298277/27673085-67ef3c1e-5cd1-11e7-9b10-199a0d83ac68.png)

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by SecMao** [comment]
使用该方案存在同样的问题 @afc163

**Comment by afc163** [comment]
> 使用该方案存在同样的问题

Please provide repository.

**Comment by SecMao** [comment]
follows the suggestions in local-iconfont:
https://github.com/SecMao/antd-iconfont-issue/tree/iconUrlTry

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5739#issuecomment-293810981

https://github.com/ant-design/ant-design/issues/6585

**Comment by SecMao** [comment]
I‘m sorry to create a duplicate issue.
Now I have add `theme ` in .roadhogrc
```
"theme": {
    "@icon-url": "'/iconfont/iconfont'"
  }
```

It works well in development environment.
Then what should I do after building project into a production environment ?
There is no any ant design css generated in the dist directory.
Should I use the `ant.min.css` in my project and change the `font-face` myself ?
