### ISSUE TITLE
There is no any antd css files in dist directory after building

### ISSUE THREAD

**Issue by SecMao** [ant-design/ant-design#6662]
### Version
2.11.2

### Environment
Windows 10/ Chrome 58/ react 15.4.0

### Reproduction link
[https://github.com/SecMao/antd-iconfont-issue/tree/noCssInDist](https://github.com/SecMao/antd-iconfont-issue/tree/noCssInDist)

### Steps to reproduce
1. install and build antd-iconfont-issue
2. look into dist directory

### What is expected?
css on demand or full css are both OK.
Since I have config the localization ` icon-url`  in .roadhogrc, the built css file should write the `font-face` to my path

### What is actually happening?
There is no any antd css files in dist directory after building

**Comment by afc163** [comment]
```diff
{
  "entry": "src/index.js",
  "theme": {
    "@icon-url": "'/iconfont/iconfont'"
  },
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", [{ "libraryName": "antd", "style": true }]]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
+      ["import", [{ "libraryName": "antd", "style": true }]]
      ]
    }
  }
}
```

**Comment by SecMao** [comment]
This suggestion only fixed my first problem: no css in dist.
The new built css file generated in dist still has the second problem: `font-face` url direct to my configuration `@icon-url` path, like `/iconfont/iconfont`, which forget the `publicPath` 
```
"publicPath": "/my-app/static/js/modules/issues/",
  "theme": {
    "@icon-url": "'/iconfont/iconfont'"
  }
```

![tim 20170630140123](https://user-images.githubusercontent.com/26298277/27722901-d9a0db26-5d9c-11e7-9e3d-ee72c135104a.png)

In my opinion,  it should be `'/my-app/static/js/modules/issues/iconfont/iconfont.eot'` where the files will be placed in my JavaEE project.
