### ISSUE TITLE
`placement` support for Mention Component

### ISSUE THREAD

**Issue by ladjzero** [ant-design/ant-design#6663]
### What problem does this feature solve?
It allows to push suggestion above @ when the mention component is near window bottom.

### What does the proposed API look like?
<Mention placement="topCenter" {...otherProps} />

**Comment by afc163** [comment]
I don't think we need this, it is strange for Mention component that there are placements other than `bottomLeft`.

**Comment by ladjzero** [comment]
@afc163 There is one use case, Slack. Please take into account. ;)

![selection_647](https://user-images.githubusercontent.com/4110311/27775284-46a067fe-5fd3-11e7-9de8-177af8ce4a1c.png)

**Comment by afc163** [comment]
`topLeft`

**Comment by afc163** [comment]
Although it is more like a AutoComplete: https://ant.design/components/auto-complete/

**Comment by ladjzero** [comment]
`draft.js mention plugin` provides `positionSuggestions`, pretty powerful and flexible.
See https://www.draft-js-plugins.com/plugin/mention

**Comment by afc163** [comment]
Could you help us to implement this feature? Cause we don't have enough hands lately.

**Comment by MrPeak** [comment]
@ladjzero We will provide two forms of suggestion's expansion, they‘re `top` and `bottom` by default.

However, "positionSuggestions" function is over flexible for AntD's most users 🤖

**Comment by ladjzero** [comment]
@MrPeak Cool！

**Comment by yesmeck** [comment]
Supported in antd 3.
