### ISSUE TITLE
All date cells rendered when one of them was clicked

### ISSUE THREAD

**Issue by airycanon** [ant-design/ant-design#6664]
### Version
2.11.2

### Environment
Chromium 58.0.3029.110 Ubuntu 17.04 (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/NgXVOJ](https://codepen.io/anon/pen/NgXVOJ)

### Steps to reproduce
Open console tab in dev tools,click one date cell,console.log(1111111) run 42 times.

### What is expected?
Only clicked target rendered.

### What is actually happening?
All date cells rendered.

**Comment by afc163** [comment]
It is a expected behavious in react world.
