### ISSUE TITLE
Style of Slider is abnormal when the wrapper's background color is not white.

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#6665]
### Version
2.11.2

### Environment
chrome 59

### Reproduction link
[https://codepen.io/twisger/pen/MordNK](https://codepen.io/twisger/pen/MordNK)

### Steps to reproduce
use Slider in a wrapper which the background color is not white

### What is expected?
the style is normal.

### What is actually happening?
the style is abnormal.

---
I tried to solve the problem by change style of ant-slider,which cause the case is the border-color property of ant-slider is set to white.I use outline property substituted for border property, change height and margin, then it's normal.

**Comment by twisger** [comment]
@benjycui  The style is still abnormal when the slider is **disabled**, view  https://ant.design/components/slider-cn/.

**Comment by benjycui** [comment]
![image](https://user-images.githubusercontent.com/3580607/28397509-aa31e07c-6d34-11e7-8154-aad79020fb40.png)

**Comment by twisger** [comment]
removing the background-color of .ant-slider-disabled seems can fixed it, what's the usage of it?
