### ISSUE TITLE
getFieldDecorator(id, options) id含有.(小数点)，但id只是个字符串时怎么处理？

### ISSUE THREAD

**Issue by hatunet** [ant-design/ant-design#6668]
### Version
2.11.2

### Environment
Chrome

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
getFieldDecorator(id, options) id含有.(小数点)，但id只是个字符串时怎么处理？

### What is expected?
id只是字符串，不要分割成object,如 getFieldDecorator("center.id", options)  不希望变成{center:{id:123}} 期望 {"center.id":123}

### What is actually happening?
{center:{id:123}}

**Comment by afc163** [comment]
You have to convert it by yourself.
