### ISSUE TITLE
使用webpack打包后，文件很大 

### ISSUE THREAD

**Issue by jiayaoaaa** [ant-design/ant-design#667]
一个文件要3-5M了。能接受吗？

**Comment by afc163** [comment]
You can use https://github.com/ant-design/babel-plugin-antd to reduce size.

**Comment by smilingpoplar** [comment]
webpack中加UglifyJsPlugin后3M能压到1M

**Comment by jtHwong** [comment]
可以用webpack.optimize.CommonChunksPlugin提取公用的webpack chunks部分。
然后再webpack.optimize.UglifyJsPlugin优化压缩。

**Comment by Ben07** [comment]
webpack.config.js中有devtool: 'eval-cheap-module-source-map', 这个嘛？有的话把它改成devtool:false
