### ISSUE TITLE
Form.Item loosing focus after first input in some situation

### ISSUE THREAD

**Issue by amio** [ant-design/ant-design#6670]
### Version
2.11.2

### Environment
MacOS 10.12, Chrome 61, 

### Reproduction link
[https://www.webpackbin.com/bins/-Knn-CzcjkBQnJ5TjZLt](https://www.webpackbin.com/bins/-Knn-CzcjkBQnJ5TjZLt)

### Steps to reproduce
Use Form.Item like this:
```
    const FormItem = props => <Form.Item {...props} labelCol={{span: 5}} wrapperCol={{span: 10}} />
    return (
      <FormItem label={'BAD:'}>
        <Input value={this.state.filterRID} onChange={this.setFilter('filterRID')} />
      </FormItem>
    )
```

Then, type chars in the input element.

### What is expected?
On the "GOOD" input, continue type more than one characters.

### What is actually happening?
On the "BAD" input, the element loosing focus after first character.

**Comment by afc163** [comment]
https://www.webpackbin.com/bins/-KnqvPNIGuq5yMrrZpsZ

`FormItem2` is a new variable at every time it's parent rendering.

**Comment by amio** [comment]
Oops, my mistake. Thanks!
