### ISSUE TITLE
About the :focus style for Button can't be modify

### ISSUE THREAD

**Issue by lvren** [ant-design/ant-design#6671]
### What problem does this feature solve?
**Button Component**
Now, I can build my personal theme for button except for `defult:hover`. like `danger`, I can change it by modify less variate in theme.less, but `default:hover``s style is writing  in sound code, it doesn`t being controlled by variate, sor I can't modify it by theme`s variate
```
// default button style
.btn-default() {
  .button-variant-other(@btn-default-color; @btn-default-bg; @btn-default-border);
  &:hover,
  &:focus,
  &:active,
  &.active {
    background: #fff;
  }
}
```
### What does the proposed API look like?
I can modify the `default:hover``s style by less`s variate in theme.less

and finally, I'm so sorry for my poor English..............T_T

**问题组件，Button**
   > 目前Button组件除了default，其他的:hover样式都一个通过设置相应的变量配置，包括default的背景样式其实也是可以通过变量设置的，只有default的:hover样式，是写死在代码中的，不受变量控制。
   > 目前的应用场景中，因为使用了黑色默认按钮颜色，每次都要修改源码来修改default的:hover样式；
相关代码在`button>sytle>mixin.less 204行`，如下
```
// default button style
.btn-default() {
  .button-variant-other(@btn-default-color; @btn-default-bg; @btn-default-border);
  &:hover,
  &:focus,
  &:active,
  &.active {
    background: #fff;
  }
}
```

### What does the proposed API look like?
期望将:hover的背景色可以通过变量控制

**Comment by afc163** [comment]
PR is welcome~

**Comment by afc163** [comment]
@lvren

**Comment by afc163** [comment]
close for no response
