### ISSUE TITLE
[Google Chrome only] Table filters do not checkmark if table rendering

### ISSUE THREAD

**Issue by vans163** [ant-design/ant-design#6672]
Sorry but that webpage to submit issues is annoying,

On google chrome table filter do not checkmark if a table is rendering often.

Example, 10,000 entry table updating every 10-100ms.

On firefox this issue does not happen.

<img src="http://i.makeagif.com/media/6-30-2017/GgX-zT.gif"/>

**Comment by yesmeck** [comment]
Hello @vans163 let us know in a comment if you can provide a online demo and steps to reproduce your issue, and we'll reopen it
