### ISSUE TITLE
Cascader级联可以支持多选吗？

### ISSUE THREAD

**Issue by chenxia123** [ant-design/ant-design#6674]
### What problem does this feature solve?
现在有一个需求，如：希望可以选择浙江省所有市区的地址（除杭州市外）。那么我希望做到：第一级选择了浙江省，第二级、第三级会默认选中全部市、区，杭州市和其下属的区都disabled。

### What does the proposed API look like?
望得到优化

**Comment by chenxia123** [comment]
用treeSelect可以实现，但是由于子集数量较多，现有的treeSelect样式上无法满足需要

**Comment by benjycui** [comment]
诡异的需求，诡异的交互，麻烦提供更多的背景信息。

**Comment by zhongjie-chen** [comment]
用tree或者自己写个

**Comment by afc163** [comment]
> 希望可以选择浙江省所有市区的地址

试试 https://ant.design/components/cascader-cn/#components-cascader-demo-change-on-select 或在选项中自行添加 `选择全部` 这样的选项。

> 除杭州市外

目前没有计划支持多选，建议用其他组件代替或自行实现。

**Comment by Charming2015** [comment]
可以试一下这个：https://github.com/Charming2015/el-cascader-multi

**Comment by chennng** [comment]
> 可以试一下这个：https://github.com/Charming2015/el-cascader-multi

有react版本吗。。

**Comment by Charming2015** [comment]
> > 可以试一下这个：https://github.com/Charming2015/el-cascader-multi
> 
> 有react版本吗。。

emmm 没有

**Comment by wt5wt** [comment]
> 
> 
> 诡异的需求，诡异的交互，麻烦提供更多的背景信息。

这个场景很多吧，比如 组织机构（部门），有很多级，可以多选不同级别的部门，进行查询筛选什么的；

**Comment by HelKyle** [comment]
我也有同样的需求，尝试自己实现了一个简单版的 React 级联多选，欢迎试用

代码在这 😃：https://github.com/HelKyle/antd-multi-cascader
这是如何实现的文章📝：https://juejin.cn/post/6914994241940750343

**Comment by tangdonglin** [comment]
> 可以试一下这个：https://github.com/Charming2015/el-cascader-multi
可以父子不关联吗

**Comment by yoyo837** [comment]
个人感觉大家在难为“级联”这个组件，特别是楼上，不关联的根本不应该用级联来实现。

**Comment by 1791139638** [comment]
> 

一个工作人员管理多个地区的求助请求, 一个办事处管理多个街区的材料申请 这种需求很诡异吗? 你连这种场景都无法想象吗?

**Comment by afc163** [comment]
现在应该已经有了：https://ant.design/components/cascader-cn#components-cascader-demo-multiple

**Comment by xiangshu233** [comment]
@afc163 这个好像不支持显示所有节点，节点回填不能 show-all
![image](https://github.com/ant-design/ant-design/assets/49575330/0221ce15-b648-48bd-863d-22d331aa77aa)
