### ISSUE TITLE
table的expandedRowRender无法异步展示

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#6675]
### What problem does this feature solve?
现有的expandedRowRender只能在table的header是知道的情况下才会正常，如果是需要点击展开，然后异步从拉取数据来show table是做不到的

### What does the proposed API look like?
希望解决expandedRowRender在当前table是异步加载出来，然后点击扩展并异步show一个扩展的表格

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by Hughen** [comment]
i think the expandedRowRender only updated to support bind in parent table init timing but the parent table no header (there is said to columns).
like this:
```javascript
expandedFunc = () => {
    return (
        <Table />
    );
};

const cols = [];

<Table
    columns={cols}
    expandedRowRender={expandedFunc}
    // ...
    />
```

**Comment by afc163** [comment]
I don't realy understand what are you talking about, but the API you described is nothing different with the current `expandedRowRender` API.

**Comment by Hughen** [comment]
no
current expandedRowRender API will not be working when columns has not any angthing.
like the above example, the columns is empty array.

Another a question:
i create a table by expanded function, how can i unmount this component when row data has been updated?

**Comment by rp492262097** [comment]
无法异步加载，或者expandedRowRender能否支持只打开一个扩展列表？能否提供这样的API

**Comment by ywzhaiqi** [comment]
`expandedRowRender` is a function, not a React Component. If `expandedRowRender` is a React Component, async fetch will do well.

**Comment by yesmeck** [comment]
> the columns is empty array.

看不懂，`columnds` 是空的话，表格还有什么意义。

**Comment by Hughen** [comment]
@rp492262097 @ywzhaiqi 
I found a way to solve the problem that the expandedRowRender can not be used asynchronously.
In my project, I need to nest the form of this way, but the inner form is asynchronous from the background to extract the data and show it.
The key point is that in the component returned by the expandedRowRender, the fetch function is implemented for componentWillMount, so that you can load all the things you want asynchronously.
I found that antd is based on RcTable, so I went to look up RcTable official documents, and then drafted a program, and has been implemented in my project.

hope to help you.

**Comment by Hughen** [comment]
@yesmeck 
of course, the table data is asynchronous from the background pulled, the initialization will choose to use empty array

**Comment by ywzhaiqi** [comment]
Thanks，I see. Here is a example
https://codepen.io/ywzhaiqi/pen/gRzKwM?editors=0010
