### ISSUE TITLE
文档中说支持ie8，但是用ie8打开ant.design,报错

### ISSUE THREAD

**Issue by dxtiger** [ant-design/ant-design#668]
网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Win64; x64; Trident/4.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
时间戳: Mon, 14 Dec 2015 08:39:47 UTC

消息: 缺少标识符
行: 25113
字符: 14
代码: 0
URI: http://ant.design/dist/demo.js

消息: 缺少对象
行: 611
字符: 1
代码: 0
URI: http://ant.design/components/checkbox/

消息: 缺少对象
行: 648
字符: 1
代码: 0
URI: http://ant.design/components/checkbox/

消息: 缺少对象
行: 776
字符: 1
代码: 0
URI: http://ant.design/components/checkbox/

我用antd-init 创建一个项目，运行后，ie8也不支持

**Comment by Carrotzpc** [comment]
官网对兼容ie8有相关说明[http://ant.design/docs/getting-started#兼容性](http://ant.design/docs/getting-started#兼容性)

**Comment by dxtiger** [comment]
@Carrotzpc 多谢。 init生成的页面中少加载了 media.match.min.js这个js，所以一直报错。 没有这个js，我用别的方法编译过了。

**Comment by liaohui1080** [comment]
@Carrotzpc 连接地址已经404

**Comment by benjycui** [comment]
> 官网对兼容ie8有相关说明http://ant.design/docs/getting-started#兼容性

Should be https://ant.design/docs/react/getting-started#Compatibility now.
