### ISSUE TITLE
icon-url doesn't direct to public path in roadhogrc configuration

### ISSUE THREAD

**Issue by SecMao** [ant-design/ant-design#6680]
### Version
2.11.2

### Environment
Windows 10/ Chrome 58/ react 15.4.0

### Reproduction link
[https://github.com/SecMao/antd-iconfont-issue/tree/cssWrongPath](https://github.com/SecMao/antd-iconfont-issue/tree/cssWrongPath)

### Steps to reproduce
1. install and build antd-iconfont-issue
2. look into the `index.css` file in dist directory

### What is expected?
The new built css file generated in dist still has the problem: `font-face` url direct to my configuration `@icon-url` path, like `/iconfont/iconfont`, which forget the `publicPath`
```
"publicPath": "/my-app/static/js/modules/issues/",
  "theme": {
    "@icon-url": "'/iconfont/iconfont'"
  }
```

![tim 20170630140123](https://user-images.githubusercontent.com/26298277/27725536-599b0fde-5da9-11e7-9f46-155f56051715.png)

In my opinion, it should be `'/my-app/static/js/modules/issues/iconfont/iconfont.eot'` where the files will be placed in my JavaEE project.

### What is actually happening?
`font-face` direct to the configuration `@icon-url` path but forget the `publicPath`

**Comment by afc163** [comment]
No, it is a web project, icon url should not point ot your local path.

**Comment by SecMao** [comment]
Hi @afc163 ,
This is not a local path. It's a deployment path. While my page loading, it will request the url like `ip:port/my-app/static/js/modules/issues/iconfont/iconfont.eot`. For now, the built css file requests the resource path like `ip:port/iconfont/iconfont.eot` which ignores my configuration public path. Meanwhile, in case of my multiple pages project, the `common.js` replaces its info to `*.async.js` files using public path.

**Comment by afc163** [comment]
The `theme` property just handle the variables replacement. You can add your public path to the value whatever you want.

**Comment by SecMao** [comment]
But how could I give a variable two values? In front-end project, the `iconfont` resources is placed in `public ` directory, because the `.roadhogrc` doesn't recognize other root paths. In back-end project, all the built files will be copied to the path which is configured in `publicPath`. While building, all the files in `public ` directory just show what they are. 
Then we will get the results:
the `common.js` requests different url:
origin project:  `ip:port/10.async.js`
back-end project: `newIP:newPort/the-public-path-in-configuration/10.async.js`
the `font-face` should know the resources it needs are changed to different location:
origin project:  `ip:port/iconfont/iconfont.eot`
back-end project: `newIP:newPort/the-public-path-in-configuration/iconfont/iconfont.eot`

Doesn't it? @afc163

**Comment by afc163** [comment]
```json
{
  "env": {
    "development": {
      "theme": { ... }
    },
    "production": {
      "theme": { ... }
    }
  }
}
```

**Comment by SecMao** [comment]
Thanks, fixed perfectly.

**Comment by chj-damon** [comment]
{
  "env": {
    "development": {
      "theme": { ... }
    },
    "production": {
      "theme": { ... }
    }
  }
}

@afc163 where should I put these code?

**Comment by SecMao** [comment]
@SanPy 我并没有创建theme.js，而是使用在.roadhog中修改公共参数的方式修改图标路径和色彩值来进行测试，在实际工程中也没有采用这种方式，因为这种方式只能在不同的环境编译出不同的代码，并不能实现动态切换皮肤的要求
