### ISSUE TITLE
Select跟随浏览器移动

### ISSUE THREAD

**Issue by taojianghe** [ant-design/ant-design#6681]
### Version
2.11.2

### Environment
谷歌最新版

### Reproduction link
[http://operation.shenjing.com/#/COMMON_COMPANY_MANAGE?_k=5zawea](http://operation.shenjing.com/#/COMMON_COMPANY_MANAGE?_k=5zawea)

### Steps to reproduce
如果页面有滚动条的情况下，点击张开下拉选择框，在滚动滚动条的时候，下拉框会跟随浏览器移动，

### What is expected?
不要跟随浏览器移动

### What is actually happening?
跟随浏览器移动

---
因为下拉框添加的绝对定位

**Comment by benjycui** [comment]
你那个连接还要注册才能访问，还是用 CodePend 提供重现 demo 吧。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
RTFM and https://github.com/ant-design/ant-design/issues/3487
