### ISSUE TITLE
Warning message when using getFieldDecorator with customized component

### ISSUE THREAD

**Issue by knightuniverse** [ant-design/ant-design#6683]
### Version
2.10.1

### Environment
"react":·"^15.5.4"

### Reproduction link
[https://gist.github.com/knightuniverse/f8d4a8222835cbc4ccec115145996118](https://gist.github.com/knightuniverse/f8d4a8222835cbc4ccec115145996118)

### Steps to reproduce
1. Customize a form input component
2. set the value prop type to `isRequired`
3. use `getFieldDecorator`，neither assign `initialValue` or not do not affect the result
4. when running this component there is warning: The prop `value` is marked as required in `StudentSearchInput`, but its value is `undefined`.

### What is expected?
No warning messages.

### What is actually happening?
there is warning: The prop `value` is marked as required in `StudentSearchInput`, but its value is `undefined`.

---
if `value` prop is not `isRequired`, then it will be the same situation to issue [#3976](https://github.com/facebook/react/issues/3163). 

But if the `value` prop is set to `isRequired`，the this component could not pass React's prop validation.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
close for no response.
