### ISSUE TITLE
Tree Component Errors.

### ISSUE THREAD

**Issue by denglingbo** [ant-design/ant-design#6684]
### Version
2.11.2

### Environment
Mac, Chrome58

### Reproduction link
[http://debug version](http://debug version)

### Steps to reproduce
Code

<Tree
    draggable
    className="draggable-tree"
    onDrop={handleDrop}
    expandedKeys={expandedKeys}
    autoExpandParent={false}
    onExpand={this.handleExpand}
>

defaultProps = {
    expandedKeys: []
}

use props:
draggable
expandedKeys=[this.state.expandedKeys]

1. default expandedKeys value is <Array> empty []
2. drag item and drop
3. Now,,,, Error

I found the error code in 'rc-tree/lib/Tree.js'
line: 31,
function: _toConsumableArray(arr) { ... }
Reason: arr is undefined, not to validate ${arr} typeof

```
if (Array.isArray(arr)) {...}
else { return Array.from(arr); } --> param value is undefined, so,,,,, boommmmmm. ^.^
```

```
if ('expandedKeys' in this.props) {
      res.rawExpandedKeys = [].concat(_toConsumableArray(this._rawExpandedKeys)) || [].concat(_toConsumableArray(this.state.expandedKeys));
    }
```
but this._rawExpandedKeys is undefined.......

Now i change the code like this:
res.rawExpandedKeys = [].concat(_toConsumableArray(this._rawExpandedKeys || [])) || [].concat(_toConsumableArray(this.state.expandedKeys));

or change the function _toConsumableArray

### What is expected?
Please validate the value type

### What is actually happening?
No error

---
My english bad,,,,, can email me: denglingbo@126.com

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
close for no response
