### ISSUE TITLE
Width will be changed when a Tab componment is included in the Layout component

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#6685]
### Version
2.11.2

### Environment
windows chrome

### Reproduction link
[https://codepen.io/anon/pen/jwZKaX?editors=0010](https://codepen.io/anon/pen/jwZKaX?editors=0010)

### Steps to reproduce
1.click the tab2 ,see the tabBarExtraContent

2.click the tab3 ,see the tabBarExtraContent

3.click the tab4 ,see the tabBarExtraContent

### What is expected?
the width of the Tab componment should be nomal always

### What is actually happening?
the width of the Tab componment wil be changed when click the tab

---
it will be reappear when these conditions must be met at the same time

1:has Layout componment

2:has Sider componment

3.the children of TabPanel has a width attribute

**Comment by afc163** [comment]
Use `Content` with `Sider`: https://codepen.io/anon/pen/WOzdmE?editors=0010
