### ISSUE TITLE
AutoComplete does not provides `event` in `onFocus` callback

### ISSUE THREAD

**Issue by oluckyman** [ant-design/ant-design#6690]
### Version
2.11.2

### Environment
osx Version 59.0.3071.115 (Official Build) (64-bit) 

### Reproduction link
[https://codepen.io/anon/pen/JJpQVv?editors=001](https://codepen.io/anon/pen/JJpQVv?editors=001)

### Steps to reproduce
focus on input

### What is expected?
`event` object with input node as a `target`

### What is actually happening?
it will show alert with undefined.
should show event

---
Use Case: I need to select text in the autocompleter when it’s focused:
```
<AutoComplete onFocus={ (e) => e.target.select(); } />
```

**Comment by afc163** [comment]
```
<AutoComplete>
  <Input onFocus={(event) => alertOnce(event)} />
</AutoComplete>
```
