### ISSUE TITLE
npm run site error,bisheng build --ssr -c ./site/bisheng.config.js

### ISSUE THREAD

**Issue by LiZoRN** [ant-design/ant-design#6692]
### Version
2.11.2

### Environment
win10

### Steps to reproduce
npm run site

### What is expected?
no error

### What is actually happening?
> antd@2.11.2 site G:\Projects\ng2\home
> bisheng build --ssr -c ./site/bisheng.config.js

ts-loader: Using typescript@2.3.4 and G:\Projects\ng2\home\tsconfig.json
ts-loader: Using typescript@2.3.4 and G:\Projects\ng2\home\tsconfig.json
G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1
(function (exports, require, module, __filename, __dirname) { exports.ssr=function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={exports:{},id:r,loaded:!1};return e[r].call(o.exports,o,o.exports,t),o.loaded=!0,o.exports}var n={};return t.m=e,t.c=n,t.p="/",t(0)}([function(e,t,n){"use strict";var r=Object.assign||function(e){for(var t=1;t<arguments.length;t  ){var n=arguments[t];for(var r in n)Object.prototype.hasOwnProperty.call(n,r)&&(e[r]=n[r])}return e};n(577);var o=n(1),i=n(1585),a=n(542),s=n(694),l=n(594),u=n(!function(){var e=new Error('Cannot find module "G:Projects\ng2home\node_modules\bisheng\tmp\routes.index.js"');throw e.code="MODULE_NOT_FOUND",e}())(l);e.exports=function(e,t){a.match({routes:u,location:e},function(e,n,l){if(e)t("");else if(n)t("");else if(l){var u=i.renderToString(o.createElement(a.RouterContext,r({},l,{createElement:s})));t(u)}else t("")})}},function(e,t,n){"use strict";e.exports=n(111)},function(e,t){"use s

Error: Cannot find module "G:Projects
g2home
outes.index.js"g        mp
    at G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1:549
    at Object.<anonymous> (G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1:677)
    at t (G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1:180)
    at exports.ssr.Object.assign.t (G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1:268)
    at Object.<anonymous> (G:\Projects\ng2\home\node_modules\bisheng\tmp\index-ssr.js:1:273)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by afc163** [comment]
You should report this to bisheng repository.
