### ISSUE TITLE
table组件固定头和列时每次hover表格时底层组件都会进入componentWillReceiveProps

### ISSUE THREAD

**Issue by cc616** [ant-design/ant-design#6696]
### Version
2.11.2

### Environment
Mac:10.11.6，Chrome:59.0.3071.115

### Reproduction link
[https://codepen.io/licuicui/pen/ZyxZYe?editors=0111](https://codepen.io/licuicui/pen/ZyxZYe?editors=0111)

### Steps to reproduce
1.使用table组件并固定头和列
2.在设置table的columns时将其中的某一列设置render参数，该render调用另一个组件
3.在底层组件的componentWillReceiveProps函数中输出
4.使用鼠标hover渲染出来的Table

### What is expected?
鼠标hover渲染出来的Table不会触发底层组件componentWillReceiveProps函数

### What is actually happening?
鼠标每hover一次渲染出来的Table就会触发底层组件componentWillReceiveProps函数

**Comment by yesmeck** [comment]
Table 目前的实现就是如此。
