### ISSUE TITLE
resetFields does not empty the thumbnails of upload component.

### ISSUE THREAD

**Issue by gx761** [ant-design/ant-design#6699]
### Version
2.11.2

### Environment
any environment

### Reproduction link
[https://codepen.io/gx761/pen/zzWXVM](https://codepen.io/gx761/pen/zzWXVM)

### Steps to reproduce
Note: a condition is added to display logic of upload button that only when fileList is empty, will the button be displayed.
1. upload a image.
2. click on reset to reset the form.
3. you will see filelist is emptyed, the upload button is displayed, but the thumbails(preview images) are still there.

### What is expected?
the thumbnails should have gone after clicking on reset button.

### What is actually happening?
you will see filelist is emptyed, the upload button is displayed, but the thumbails(preview images) are still there.

**Comment by benjycui** [comment]
see: https://ant.design/components/form/#components-form-demo-validate-other

```diff
getFieldDecorator('upload', {
+ valuePropName: 'fileList',
})
```
