### ISSUE TITLE
建议新增列排列

### ISSUE THREAD

**Issue by pikeCol** [ant-design/ant-design#6701]
### What problem does this feature solve?
大部分的表头是横向排列的，但是也有表头是竖直排列的时候

### What does the proposed API look like?
 可以新增个属性vertical属性，如果有这个属性则，表格会变成竖直排列 <Table columns={columns} dataSource={data} size="middle" vertical="true" />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4312
