### ISSUE TITLE
In Safari 11.0, use the table component, the page first loaded isn’t as smooth

### ISSUE THREAD

**Issue by TDiDa** [ant-design/ant-design#6703]
### Version
2.11.2

### Environment
macOS High Sierra 10.13 Beta (17A291m)、Safari 11.0 (13604.1.25.3.3)

### Reproduction link
[https://ant.design/components/table-cn/#](https://ant.design/components/table-cn/#)

### Steps to reproduce
The web page use the table component, the page first loaded isn’t as smooth, which won't be in chrome

### What is expected?
The page use the table component to be fluent

### What is actually happening?
The web page use the table component, the page first loaded isn’t as smooth

**Comment by benjycui** [comment]
I don't understand, could you provide more information?

**Comment by TDiDa** [comment]
For example，In Safari 11.0，Loading for the first time will be very caton at https://ant.design/components/table-cn/#，The page slide will be very caton

**Comment by afc163** [comment]
I think caton => lag 

....chinglish

**Comment by benjycui** [comment]
@TDiDa can you provide a GIF? According to me, it works fine now.

**Comment by hkongm** [comment]
blame new safari ...

**Comment by afc163** [comment]
It works fine on my `12603.2.4` safari too. We don't have your enviorment so it will be great if you can help us find out what is the problem?

**Comment by afc163** [comment]
@TDiDa

**Comment by afc163** [comment]
close for can not reproduce it.
