### ISSUE TITLE
when click the wrapped by Popover action in the table with fixed colums，render two components, How to solve it ? 

### ISSUE THREAD

**Issue by liuqisakuya** [ant-design/ant-design#6704]
### Version
2.10.2

### Environment
OSX10.12.5 chrome59.0.3071.115

### Reproduction link
[https://codepen.io/liuqisakuya/pen/OgveqG](https://codepen.io/liuqisakuya/pen/OgveqG)
[](url)
### Steps to reproduce
1. To fix action columns and use Popover wrap the action;
2. set 'visible' attribute in Popover;
3. click the action tag

### What is expected?
only one component is rendered when click the action

### What is actually happening?
two component is rendered when click the action

---
I use 'show' and 'rowkey' as a judge whether to show this component, but the  fixed colums implementation is an additional rendering of a column, and position the table above, fixed column and the original column has the same props, when I click the action, two component is rendered;
if i don't set 'visible', this will not happen, can you tell me why this happens ？ please；

**Comment by benjycui** [comment]
cc @afc163 @yesmeck

**Comment by afc163** [comment]
We can set `pointer-events: none;` to fixed duplicated columns in body table.

**Comment by afc163** [comment]
Make the left-fixed in the front of columns array: https://codepen.io/afc163/pen/KvVwqa?editors=0010

**Comment by babycannotsay** [comment]
> Make the left-fixed in the front of columns array: https://codepen.io/afc163/pen/KvVwqa?editors=0010

实际上还是渲染了两个Popover，有没有办法只渲染一个？

**Comment by babycannotsay** [comment]
当然4.0用sticky改变了表格实现是没问题的。。只会渲染一个，主要是4以下的版本
