### ISSUE TITLE
 ExpandedRowRender API does not support configuration only a sub list of open

### ISSUE THREAD

**Issue by rp492262097** [ant-design/ant-design#6706]
ExpandedRowRender API does not support configuration only a sub list of open, abnormal loading time, and opened 2 sub list, will lead to the first open sub list, to be re loaded into second sub list data, resulting in data confusion。
![dh xsyfy38fu8g13tal nke](https://user-images.githubusercontent.com/8969012/27784953-9b6f1fd8-600e-11e7-899c-61506bf233b3.png)
![bv 5 h8q ly7 0mw_v66](https://user-images.githubusercontent.com/8969012/27784980-b3a430ca-600e-11e7-8039-0384cf19d43d.png)

![loq292yk rtfcpqj__276 0](https://user-images.githubusercontent.com/8969012/27784981-b3ad6f3c-600e-11e7-8623-fb6555e6abde.png)

**Comment by rp492262097** [comment]
![ffiiml o89l pvnlmx e701](https://user-images.githubusercontent.com/8969012/27785025-d4077cbe-600e-11e7-8569-ad62692a4723.png)

**Comment by afc163** [comment]
使用 expandedKeys 自行控制。

**Comment by OneAndOnly1111** [comment]
遇到同样的问题，楼主解决了吗？
