### ISSUE TITLE
Input onKeyPress won't trigger when wrapper cascader is open

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#6717]
demo: https://codepen.io/paranoidjk/pen/VWxVKb?editors=0010

**Comment by benjycui** [comment]
ref: https://github.com/react-component/cascader/commit/393f6b4d265d872d2384a9bc99291e6687ffeadc

**Comment by benjycui** [comment]
@afc163 问题应该在于 [这里](https://github.com/react-component/cascader/blob/74bf59661d005fe17b9c67716da65911f598a6cd/src/Cascader.jsx#L215) 阻止了默认行为，所以 `onKeyPress` 没有被触发。手动调用 `onKeyDown` 应该是解决不了问题的。
