### ISSUE TITLE
 sider.js   Object does not support this property or method “assign” in IE11

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#6718]
### Version
2.11.2

### Environment
Win7 IE11

### Reproduction link
[https://codepen.io/anon/pen/JJveRK?editors=001](https://codepen.io/anon/pen/JJveRK?editors=001)

### Steps to reproduce
run  this code in IE11, then throw an error in sider.js in line 190 Object does not support this property or method “assign” 

```
import React, { Component, PropTypes } from 'react';
import { connect } from 'dva';
import { Link } from 'dva/router';
import styles from './IndexPage.css';

import { Layout} from 'antd';

const { Sider } = Layout;

class App extends Component {
  constructor(props){
    super(props)
  }
  render(){
    return(  
      <Layout>
     <Sider>
      // sider.js  line190  Object does not support this property or method “assign” in IE11
    </Sider>
     </Layout>
    )
  }
}
export default connect()(App) ;

```
### What is expected?
resolve it

### What is actually happening?
now it has an error

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7
