### ISSUE TITLE
Can Pagination acts like Link to play nice with SEO

### ISSUE THREAD

**Issue by kooinam** [ant-design/ant-design#6719]
### What problem does this feature solve?
I was worried that because Ant Design Pagination essentially acts like a Button instead of <a> tag and therefore would be ignored by SEO Crawler ( I might be wrong ). What do I need to do for Pagination to acts like Link( with href tag ) instead of click callback to play nice with SEO?

### What does the proposed API look like?
<Pagination href={ path } >

**Comment by afc163** [comment]
duplicate https://github.com/ant-design/ant-design/issues/6013
