### ISSUE TITLE
The modal's mask should overlay the popover 

### ISSUE THREAD

**Issue by Alex1990** [ant-design/ant-design#6722]
### Version
2.11.2

### Environment
macOS 10.12.5, Chrome 59

### Reproduction link
[https://codepen.io/Alex1990/pen/yXjwrN?editors=001](https://codepen.io/Alex1990/pen/yXjwrN?editors=001)

### Steps to reproduce
1. There is a link or some text in the page. When you click it, a popover menu will be opened.
2. In the popover menu, there is a button. When you click it, a modal will be opened.

You can see it in the reproduction link.

### What is expected?
The mask of modal should overlay the popover.

### What is actually happening?
The mask of modal doesn't overlay the popover.

**Comment by benjycui** [comment]
It is impossible to make the default `z-index` work fine in all the use case.

But we can expose `zIndex` to `Modal.method`.

**Comment by benjycui** [comment]
@Alex1990 could you try to PR to add this feature?

See: https://github.com/react-component/dialog#rc-dialogweb

Just add zIndex here https://github.com/ant-design/ant-design/blob/ad4b49f84372675ce647784255ea29d90b2cfb4d/components/modal/confirm.tsx#L83-L92

**Comment by Alex1990** [comment]
@benjycui It doesn't work. Because the modal's container element is not the `document.body` but the popover's container element is the `document.body`, so setting the `z-index` doesn't work. If I pass the `getContainer={() => document.body}` to `Modal`, it still doesn't work and the below warning is shown in console:

> Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.

Also, the document says the `getContainer` default is `() => document.body`, but it isn't.

You can check it in this demo: https://codepen.io/Alex1990/pen/weXqQa?editors=001

**Comment by benjycui** [comment]
> Because the modal's container element is not the document.body but the popover's container element is the document.body, so setting the z-index doesn't work.

You make a mistake, it works.

![image](https://user-images.githubusercontent.com/3580607/27851915-7e6cecda-618f-11e7-8494-e8541bbf282b.png)

**Comment by Alex1990** [comment]
Can you tell me how do you make the above demo in your screenshot? Are you modifying the style in the browser devtools?

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/MoXrey?editors=001

**Comment by Alex1990** [comment]
Oh, thanks! The `zIndex` must not be less than the `z-index` of popover container which is 1030.

**Comment by Alex1990** [comment]
I will create a PR later.

**Comment by WinterWoods** [comment]
@

**Comment by afc163** [comment]
@Alex1990
