### ISSUE TITLE
在表单里面，Input使用前置标签时存在样式问题

### ISSUE THREAD

**Issue by excellnn** [ant-design/ant-design#6723]
### Version
2.11.2

### Environment
macOS chrome 59 

### Reproduction link
[https://codepen.io/liuniannan/pen/EXLJgv?editors=1010](https://codepen.io/liuniannan/pen/EXLJgv?editors=1010)

### Steps to reproduce
在input框内输入内容

### What is expected?
前缀的文字保持完整

### What is actually happening?
前缀的文字被省略了

---
去掉Form.Item的hasFeedback就不会出现问题。
form .has-feedback .ant-select-selection-selected-value
form .has-feedback .ant-select-arrow
这两个样式影响了

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/commit/fb6858c3cc9af9ebef3e1b39d4c373af16158236#diff-51de536edf29809d26f0ccfab96f81fcR148

**Comment by benjycui** [comment]
@excellnn how about a PR? Just make this CSS rule(https://github.com/ant-design/ant-design/commit/fb6858c3cc9af9ebef3e1b39d4c373af16158236#diff-51de536edf29809d26f0ccfab96f81fcR148) don't work for Select in Input?

**Comment by afc163** [comment]
@excellnn ping~

**Comment by excellnn** [comment]
ok.I will try

**Comment by afc163** [comment]
It is fixed in  4419d4c ...
