### ISSUE TITLE
how to setting the RangePicke's icon to the left of input ?

### ISSUE THREAD

**Issue by xgqfrms-gildata** [ant-design/ant-design#6724]
### Version
2.11.1

### Environment
Windows 7 x64 & Chrome 59.0.3071.115（正式版本） （64 位）

### Reproduction link
[https://user-images.githubusercontent.com/29531779/27829291-82255264-60f3-11e7-9e9c-3e503f1e6d6c.png](https://user-images.githubusercontent.com/29531779/27829291-82255264-60f3-11e7-9e9c-3e503f1e6d6c.png)

### Steps to reproduce
# see the screentcut!

https://user-images.githubusercontent.com/29531779/27829291-82255264-60f3-11e7-9e9c-3e503f1e6d6c.png

### What is expected?
just keep the icons all in the left of input!

### What is actually happening?
RangePicke's icon in the right of input!

---
none!

**Comment by afc163** [comment]
You have to override the css by yourself.

**Comment by xgqfrms-gildata** [comment]
holy shit!

**Comment by afc163** [comment]
:smiley:
