### ISSUE TITLE
Modal的宽度如何随子元素的宽度自适应，高度可以，宽度好像会溢出

### ISSUE THREAD

**Issue by feng1lang** [ant-design/ant-design#6725]
代码示例：
<Modal title="原图展示" visible={this.state.visible} onCancel={this.handleCancel.bind(this)} onOk={this.handleOk.bind(this)}>
      <img src={xxx}></img>          
</Modal>

结果：
![image](https://user-images.githubusercontent.com/29892750/27831200-361e9066-60fc-11e7-918f-d262025ab04b.png)

试了在style属性里面添加overfolw-x，会报错，添加overflow属性不管用。看了下width好像xian'za现在是固定成520px；请问如何设置属性使得宽度能够随着子元素宽度自适应

**Comment by benjycui** [comment]
这种场景一般都是让内容跟随容器的宽度。

**Comment by hyl1374961656** [comment]
需要用modal来实现图片点击放大，但是宽度好像是固定的
