### ISSUE TITLE
Add support for more `rc-progress` props for a circular progress bar

### ISSUE THREAD

**Issue by hargasinski** [ant-design/ant-design#6728]
### What problem does this feature solve?
`rc-progress` has a few useful `props` for styling a circular progress bar, such as `strokeLinecap`, `gapDegree`, `gapPosition`, `strokeColor`, etc..., which aren't exposed through the `Progress` component. Currently, to style these, the style on the SVG that `Progress` creates has to be overwritten in a separate stylesheet. It would be easier to style the progress bar if these props were exposed directly on `Progress`.

### What does the proposed API look like?
```jsx
<Progress
  // currently supported props
  type="circle" 
  percent={75}
  showInfo={false}

  // new props
  strokeLinecap="square"
  gapPosition="bottom"
/>
```

**Comment by hargasinski** [comment]
After looking through the code, it appears only `strokeLinecap` isn't supported. Should the docs be updated to indicate that props like `gapPosition` are supported? https://ant.design/components/progress/

**Comment by ddcat1115** [comment]
Thanks and we will update the docs as soon as possible ~
