### ISSUE TITLE
Table tr style setting

### ISSUE THREAD

**Issue by jun0205** [ant-design/ant-design#6730]
### What problem does this feature solve?
dynamic tr style setting

### What does the proposed API look like?
rowStyle={(record, index) => string}

**Comment by yesmeck** [comment]
You can set `rowClassName` dynamically.

**Comment by jun0205** [comment]
I need bind the fields
For eg.
{(record, index) => ({backgroundColor: record.color})}

**Comment by yesmeck** [comment]
`rowClassName={(record, index) => { ... }}`

**Comment by jun0205** [comment]
rowClassName is <tr class="...">
I need <tr style="...">, style the bind API fields.
For eg.
<table>
<tr style="background-color: red;"><td>red</td></tr>
<tr style="background-color: white;"><td>white</td></tr>
</table>

**Comment by afc163** [comment]
I think rowClassName can do same thing in this situation.

**Comment by jun0205** [comment]
@afc163 
Help me, Thank you.
https://jsfiddle.net/q78aaqvb/8/
color field bind to tr background-color style

**Comment by afc163** [comment]
https://jsfiddle.net/2b2376a4/ or https://jsfiddle.net/qmnu2jbr/

**Comment by jun0205** [comment]
@afc163 Thank you,
If data count is 1000 or more, Color is not the same, this okay?
Color value is ColorPicker, Can not use classname

**Comment by afc163** [comment]
Second one.

**Comment by jun0205** [comment]
I now also use the first one
Too many columns, add row attribute best

**Comment by jun0205** [comment]
https://github.com/react-component/table/pull/149

**Comment by TENsaga** [comment]
> https://jsfiddle.net/2b2376a4/ or https://jsfiddle.net/scs07x52/

Is there a way to style expanded row column with the +/- sign? Example:

https://jsfiddle.net/scs07x52/87/

**Comment by Flynamic** [comment]
There are situations where rowClassName is not enough, though. Example: dynamically configurable row styles. I want to make the whole row bold or green depending on a condition. But the specific style _is only known at runtime_. Classes would obviously restrict me to pre-defined styles.

**Comment by afc163** [comment]
```jsx
<Table
  onRow={(record) => ({
    style: { backgroundColor: '#000' },
  })}
/>
```

**Comment by yyyyffqqqq** [comment]
> ```js
> <Table
>   onRow={(record) => ({
>     style: { backgroundColor: '#000' },
>   })}
> />
> ```

第二种颜色设置是有效果，但也会遮挡住高亮颜色
