### ISSUE TITLE
Mention does not support server-side rendering [SSR]

### ISSUE THREAD

**Issue by Sicria** [ant-design/ant-design#6733]
### Version
2.11.0

### Environment
OSX, Chrome Latest

### Reproduction link
[https://ant.design/components/mention/](https://ant.design/components/mention/)

### Steps to reproduce
Sorry, can't provide a link to a Codepen but here's a snippet of the code.
```
<Form.Item
  hasFeedback
  colon={false}
  label="Subject"
>
  {getFieldDecorator('subject', {
    initialValue: toContentState('Any value here @test'),
    onChange: this.handleSubjectChange,
  })(
    <Mention
      notFoundContent="Sorry, couldn't find that attribute"
      getSuggestionContainer={this.getMentionContainer}
      onSearchChange={this.handleSearchChange}
      suggestions={this.getSuggestions}
      placeholder="Subject"
    />,
  )}
</Form.Item>
```
If you need any of the other functions mentioned in the above snippet let me know.

When using the ``Mention`` component in an environment which uses SSR it throws a warning.

### What is expected?
For the component to not throw warnings and work nicely with SSR

### What is actually happening?
```
Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op. Please check the code for the EditorCore component.
```

That message is displayed on the server and in the client and also the SSR is thrown away since it's different from what was rendered on the server vs the client.

**Comment by yesmeck** [comment]
Hello @Sicria, could you provide a reproduction repo?

**Comment by benjycui** [comment]
Close for no response.
