### ISSUE TITLE
SubMenu style={{display:'none'}} doesn't work

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#6734]
### Version
2.11.2

### Environment
win10

### Reproduction link
[http://11.com](http://11.com)

### Steps to reproduce
..

### What is expected?
想要通过设置 SubMenu 的 display 不让指定的菜单栏显示。

### What is actually happening?
style={{display:'none'}} 无效

**Comment by yesmeck** [comment]
SubMenu 没有 style。

`{condition && <SubMenu>...</SubMenu>}`
