### ISSUE TITLE
Component cannot re-render correctly on history back

### ISSUE THREAD

**Issue by amio** [ant-design/ant-design#6736]
### Version
2.11.2

### Environment
macOS, Chrome 61, react 15

### Reproduction link
[https://www.webpackbin.com/bins/-KoC9_3x-y6tIEj9tXev](https://www.webpackbin.com/bins/-KoC9_3x-y6tIEj9tXev)

### Steps to reproduce
1. Click "B Menu", then "A Menu", then "B Menu"
2. Click back button

### What is expected?
A Menu should have a underline highlight.

### What is actually happening?
Menu highlight state couldn't update on re-render.

**Comment by benjycui** [comment]
You should use `selectedKeys` to control it.

**Comment by amio** [comment]
Thanks. I thought it was a bug rather than usage problem.
