### ISSUE TITLE
The select component cannot change with the location of the parent component

### ISSUE THREAD

**Issue by JustDo** [ant-design/ant-design#6737]
### Version
2.11.2

### Environment
macOS 10.12.4 Chrome 58.0.3029.110 react 15.5.4

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
I added a set of data on the table, there is a select component in every line of table, then click Select, then scroll the page, I used the "getPopupContainer" function of select to follow the entire page scrolling, but when the table data is more, Scroll table, and the select component cannot scroll along with the table

### What is expected?
Select components can scroll through pages and tables, respectively

### What is actually happening?
The select component can only scroll along with the page and cannot scroll along with the table

**Comment by afc163** [comment]
> Reproduction link
> http://new-issue.ant.design/

????????

**Comment by afc163** [comment]
#3438

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001
