### ISSUE TITLE
The selection component cannot move with the scroll up and down table

### ISSUE THREAD

**Issue by JustDo** [ant-design/ant-design#6741]
### Version
2.10.4

### Environment
macOS 10.12.4 Chrome 58.0.3029.110 react 15.5.4

### Reproduction link
[https://codepen.io/JustDoGit/pen/owMzVM](https://codepen.io/JustDoGit/pen/owMzVM)

### Steps to reproduce
I added a set of data on the table, there is a select component in every line of table, then click Select, then scroll the page, I used the "getPopupContainer" function of select to follow the entire page scrolling, but when the table data is more, Scroll up and down table, and the select component cannot scroll along with the table

### What is expected?
Select components can scroll through pages and tables, respectively

### What is actually happening?
The select component can only scroll along with the page and cannot scroll along with the table

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/OgwbMP

You did not understand this API.
