### ISSUE TITLE
Input一开始进来设置有defaultValue默认值，修改后setState，之后不更新，因为defaultValue只执行一次，但是我设置value又不能修改 <Input defaultValue={text} **placeholder="采购数量"/>**，求帮助

### ISSUE THREAD

**Issue by lcgyh** [ant-design/ant-design#6742]
Input一开始进来设置有defaultValue默认值，修改后setState，之后不更新，因为defaultValue只执行一次，但是我设置value又不能修改 <Input defaultValue={text} **placeholder="采购数量"/>**，求帮助

**Comment by TsangTszKin** [comment]
if you set the key(this key is uuid) for the Input, then then defaultVaule will be changed. I haved tried it.

**Comment by TsangTszKin** [comment]
man, if you set the key(this key is uuid) for the Input, then the defaultVaule will be changed. I haved tried it  just now .
