### ISSUE TITLE
tree组件能不能提供一个右键菜单的功能

### ISSUE THREAD

**Issue by nicelj** [ant-design/ant-design#6743]
### What problem does this feature solve?
个人觉得tree组件不应该只是展示作用

### What does the proposed API look like?
能够右键节点进行编辑删除之类的操作

**Comment by Slardar888** [comment]
Right mouse button, you can use contentMenu implementation, react-contentMenu this project you can look at

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6176

https://github.com/ant-design/ant-design/issues/5151
