### ISSUE TITLE
Ie11, the scroll bar of table component width checkboxes is not smooth

### ISSUE THREAD

**Issue by zhjin024399** [ant-design/ant-design#6750]
### Version
2.11.2

### Environment
win10、IE11，Antd2.11.2

### Reproduction link
[https://github.com/zhjin024399/table-demo.git](https://github.com/zhjin024399/table-demo.git)

### Steps to reproduce
10 of the data, with a check box of the table components of the scroll bar in IE11 work very well.
When the data is increased, the scroll bar is getting less and less smooth, to reach 50 data, Scrolling is unbearable

### What is expected?
smooth

### What is actually happening?
less smooth

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/benjycui/pen/KgPZrE?editors=001

Please provide a reproducible demo   http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zhjin024399** [comment]
reproducible demo : https://codepen.io/zhjin024399/pen/RgYRGa?editors=0010

**Comment by zhjin024399** [comment]
@ddcat1115  reproducible demo : https://codepen.io/zhjin024399/pen/RgYRGa?editors=0010

**Comment by maxkan** [comment]
We also had very poor performance in IE11. 
Try this:
.ant-table {
  border-radius: 0 !important;
}
