### ISSUE TITLE
Cascader的 loadData 如何设置默认值

### ISSUE THREAD

**Issue by zhanzl1** [ant-design/ant-design#6761]
### What problem does this feature solve?
比如我用Cascader级联选择了地区 数据是loadData 加载 ，那我编辑进来要显示之前选的地区要怎么处理？defaultValue只能设置一级

### What does the proposed API look like?
传入defaultValue，可以loadData相应的数据回显出来

**Comment by bang88** [comment]
Please see https://ant.design/components/cascader-cn/#API 

```js
defaultValue: ['one','two','three']
```

**Comment by zzsoszz** [comment]
i got the same problem,defaultValue doesn't working with loadData props. 
only fist level can be set to selected.

**Comment by jiaoyilun** [comment]
+1 Having the exact same issue.

**Comment by theprimone** [comment]
I have the same issue, but here is no solution.

Finally, I got Inspired by the api `displayRender`, here is my solution.

```js
render() {
  const { value } = this.props;

  function displayRender(label /* , selectedOptions */) {
    if (!label.length) {
      return value;
    }
    return label[label.length - 1];
  }

  // `Cascader`'s value controled by `Form.Item`
  return (
    <CustomCascader
      options={customOptioins}
      onChange={this.handleChange}
      loadData={this.loadData}
      value={value}
      displayRender={displayRender}
      {...rest}
    />
  );
}
```

**Comment by hilads** [comment]
有解决了的 大佬没 求支招

**Comment by theprimone** [comment]
@hilads 我用粗糙的英文给了个在你楼上的方案啊 :sweat_smile: 阔以试一下。

**Comment by hilads** [comment]
> @hilads 我用粗糙的英文给了个在你楼上的方案啊 😅 阔以试一下。

额 试了   大佬 有没有完整的 例子

**Comment by hilads** [comment]
@theprimone

**Comment by hilads** [comment]
@theprimone  Do you have a complete example?   i want see see

**Comment by hilads** [comment]
Because I use Vue

**Comment by theprimone** [comment]
关键就是那个 `displayRender` 啊，没有 label 的时候就渲染 value 。看看官方这个接口的说明吧。

**Comment by zhaijiamei** [comment]
请问楼主是怎么解决的？

**Comment by yuuk** [comment]
displayRender 处理后，会出现如下问题：
1、placehoder的逻辑需要单独处理
2、props的value和onChange的value需要处理兼容
