### ISSUE TITLE
react中使用DatePicker发现两个问题，需要大神指点迷津

### ISSUE THREAD

**Issue by front-end-john** [ant-design/ant-design#6762]
**react中使用DatePicker发现两个问题：**
一：清空输入框内的值在API找不到可以调用的函数，需要移动的输入框点击按钮才能清空值；
二：DatePicker的showTime为true时，时间选择不可控制，比如：时间间隔，关闭时间毫秒的选择等等。
第一次使用antd，感觉是挺好用的，只是功能上有些不足！

**Comment by songbenchuan** [comment]
请问第一个问题有好的解决办法吗，我现在也需要自动清空输入框内的值，但是找不到接口

**Comment by yesmeck** [comment]
@songbenchuan `value` 设置成 `null` 就是清空。

**Comment by songbenchuan** [comment]
好的，感谢。

Wei Zhu <notifications@github.com> 于 2017年12月26日 下午3:17写道：


@songbenchuan<https://github.com/songbenchuan> value 设置成 null 就是清空。

―
