### ISSUE TITLE
Some of the user experience questions about DatePicker

### ISSUE THREAD

**Issue by raisezhang** [ant-design/ant-design#6764]
### What problem does this feature solve?
So that users can enjoy the convenience of DatePicker

### What does the proposed API look like?
**1、DatePicker  showTime  的体验问题**

![image](https://user-images.githubusercontent.com/1481983/27953232-a773e386-633d-11e7-8134-39f63ec46f3c.png)

如上图，showTime 的控件， 根据@RaoHai的 [优化建议](https://github.com/ant-design/ant-design/pull/2416)， 选中日期后的背景为主色调，当天的边框为主色调。效果图中看到是背景色为主色调，点击确认后发现没有选中日期及时间。

优化的方案我建议有以下几种：
- 将默认选中效果去掉，让用户认为当前是没有选中日期
- 点击 ok 后直接选中当前日期及时间。 本身 ok 的交互就是认可当前的日期
- showTime的控件，点击日期后自动切换到默认的时间面板，用户如果认可默认时间，直接ok 即可

我个人不建议第一种，更倾向于第二种解决方案，第三种交互的改动稍微比较大

**2、RangePicker 本月面板显示相邻月份日期的体验问题**

![image](https://user-images.githubusercontent.com/1481983/27953289-d36525e0-633d-11e7-8681-c5657d6c883e.png)

如上图，在选择范围的日期的控件，额外显示相邻月份日期的效果会让效果很杂乱，影响用户选择。范围的控件不像是单个 DatePicker 日期的选择，那种情况会更加方便。最终效果如下：

![image](https://user-images.githubusercontent.com/1481983/27953154-596cb9ec-633d-11e7-8f13-3b15f2f101fd.png)

**3、RangePicker  默认选中面板的体验问题**

![image](https://user-images.githubusercontent.com/1481983/27953116-356c2816-633d-11e7-9307-38fcbab185e2.png)

如上图，当前选中的日期为  2017-06-06 ~ 2017-07-07，面板是不是应该选中到 6月和7月的面板。如下图效果：

![image](https://user-images.githubusercontent.com/1481983/27953442-68d72aec-633e-11e7-998e-29ea92411b55.png)

**Antd：2.11.2**

**Comment by vipcxj** [comment]
DateRange中，2个日期不能选择同月份的怎么破？比如开始时间选3月，结束时间强行4月，3月灰的不给选。这个是bug吧，还是我参数有问题？

**Comment by benjycui** [comment]
第一点 trace: https://github.com/ant-design/ant-design/issues/6146

第二点是个主观的问题，感觉更多的是个人偏好了。。

第三点是 bug

**Comment by benjycui** [comment]
然后以后不要提这种 all in one 的 issue，很容易搞混。

**Comment by raisezhang** [comment]
第一点： 所以方案是你们会再加一种选中的样式？   建议还是不要了，三种高亮样式用户理解成本会很高！   还有貌似跟我这个问题不太一样，我的情况是在有 showTime 的情况下操作麻烦的问题，没有showTime的情况都没有 ok 按钮的。

第二点：我让产品及设计都体验了一把，觉得这种方案真的是很舒服，没有太多的干扰（尤其在选相邻月份的情况，有些天是显示重复的）。希望你们可以考虑下，在 RangePicker 加一个配置参数，是否额外显示相邻月份的天 

Thanks  ~      关于  all in one  后面注意 ！

**Comment by raisezhang** [comment]
closed?     所以结论是？

**Comment by benjycui** [comment]
第三点修复，第一点你到之前的 issue 继续讨论，第二点这个太主观了，如无更多证据证明你的交互更优，保持现状。

**Comment by martinnov92** [comment]
Hello, what about selected day by user and the selected day on arrow click? Is it solved? We need the user´s selected date to look different then the other one selected by arrow click... Currently it is not possible to see the difference. Thank you
