### ISSUE TITLE
Uncaught ReferenceError: Menu is not defined

### ISSUE THREAD

**Issue by brucecham** [ant-design/ant-design#6767]
webpack 进行打包，引用了 babel-plugins-import 
```
import { Layout, Menu, Icon } from 'antd'
```
打包之后，Button Layout Icon都正常，但Menu找不到

**Comment by brucecham** [comment]
@ant-design-bot @afc163 应该是组件的问题，抽空看下吧

**Comment by bang88** [comment]
@brucecham 请提供一个可重现的demo 方便查看。

**Comment by kwzm** [comment]
@BruceCham 你好，我也遇到了类似问题，你解决了吗？

**Comment by BruceCham** [comment]
@kwzm @bang88 
将menu的子级解析出来，不要直接用。
```js
const MenuItem = Menu.Item
```
```html
<Menu>
        <MenuItem>xxxx</MenuItem>
</Menu>
```
不知道他们现在修复了没有，很久不用了

**Comment by kwzm** [comment]
@BruceCham 我也是采用了这种方法，我今天找到了问题的原因了，不是ant-design的问题，是我的脚手架babel使用了react-optimize
`env.production.presets=["react-optimize"]`
我试了下取消就好了，但是不知道具体是这个包里面的哪个地方出了问题

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/5060
