### ISSUE TITLE
Keep CheckboxGroup's value type same as RadioGroup 

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#6768]
https://github.com/ant-design/ant-design/blob/919cb22eb7372f8907e257171f77bbd7abbf6348/components/checkbox/Group.tsx#L9-L23

`Checkbox` only accept `string` value, but `Radio` does support ` string | number`.  

 any thoughts ?

**Comment by bang88** [comment]
...

**Comment by afc163** [comment]
@yesmeck 把这几位都加到白名单里...

**Comment by bang88** [comment]
现在好像是判断了 Team Member

**Comment by afc163** [comment]
> Checkbox only accept string value, but Radio does support string | number.

We should unify it to `string | number`.

**Comment by bang88** [comment]
Yep

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-bot/blob/master/src/github.js#L53

现在是获取的 ant-design-team 成员： https://github.com/orgs/ant-design/teams/ant-design-team/members
