### ISSUE TITLE
npm can not found antd2.12.0

### ISSUE THREAD

**Issue by tailorsira** [ant-design/ant-design#6773]
### Version
2.12.0

### Environment
windows10

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
npm i antd@2.12.0 --save

### What is expected?
update version

### What is actually happening?
error "no compatiable version"

**Comment by paranoidjk** [comment]
https://unpkg.com/antd@2.12.0

https://www.npmjs.com/package/antd

**Comment by tailorsira** [comment]
@paranoidjk use npm install can only install antd2.11.2

**Comment by paranoidjk** [comment]
works fine at my computer, please check your npm registry
