### ISSUE TITLE
Textarea Component save pre render value

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#6776]
### Version
2.12.0

### Environment
mac 10.12.5  , chrome  59.0.3071.115(64)

### Reproduction link
[http://runjs.cn/code/p8pz610z](http://runjs.cn/code/p8pz610z)

### Steps to reproduce
实现一个变长组件，修改内容的时候发现数据遗留问题

### What is expected?
Textarea的值不要保留

### What is actually happening?
Textarea的值保留

**Comment by yangbin1994** [comment]
![Uploading test.gif…]()

**Comment by yangbin1994** [comment]
![test](https://user-images.githubusercontent.com/12080165/27992449-208c232a-64c7-11e7-897a-c30375b23a09.gif)

**Comment by yangbin1994** [comment]
使用默认类型的`Input`组件，就一切ok

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
@yangbin1994

**Comment by bow3nwang** [comment]
@afc163
 textarea get warning ` "value" prop on "textarea" should not be null.`
 i don't think make any sense. It's complex to set default value~

**Comment by aegisho** [comment]
same problem

when set `Input.TextArea`  `initialValue`  to `undefined`, it's not clear value  
see [https://codepen.io/aegisho/pen/eRXoyy?editors=0010](https://codepen.io/aegisho/pen/eRXoyy?editors=0010)

**Comment by yangbin1994** [comment]
@aegisho nice positioning
