### ISSUE TITLE
运行npm install报错：missing ) after argument list

### ISSUE THREAD

**Issue by chua1989** [ant-design/ant-design#6777]
### Version
2.12.0

### Environment
windows 7

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
我是用nvm安装了最新的node 8.1.3，然后用这个版本的node
$ git clone git@github.com:ant-design/ant-design.git
定位到ant-design目录
$ npm install
$ npm start

### What is expected?
使用npm start运行的时候能够正常运行

### What is actually happening?
log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle antd@2.12.0~prestart: antd@2.12.0
6 silly lifecycle antd@2.12.0~prestart: no script for prestart, continuing
7 info lifecycle antd@2.12.0~start: antd@2.12.0
8 verbose lifecycle antd@2.12.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle antd@2.12.0~start: PATH: C:\nvm\v8.1.3\node_modules\npm\bin\node-gyp-bin;D:\github\ant-design\node_modules\.bin;C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Python27;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_51\bin;C:\Program Files\Java\jdk1.8.0_51\jre\bin;D:\tools\apache-maven-3.3.3\bin;C:\Program Files\Git\cmd;D:\tools\apache-maven-3.3.3\bin;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\Apache-Subversion-1.9.5\bin;C:\nvm;C:\Program Files\nodejs;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle antd@2.12.0~start: CWD: D:\github\ant-design
11 silly lifecycle antd@2.12.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'bisheng start -c ./site/bisheng.config.js --no-livereload' ]
12 silly lifecycle antd@2.12.0~start: Returned: code: 1  signal: null
13 info lifecycle antd@2.12.0~start: Failed to exec start script
14 verbose stack Error: antd@2.12.0 start: `bisheng start -c ./site/bisheng.config.js --no-livereload`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\nvm\v8.1.3\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\nvm\v8.1.3\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid antd@2.12.0
16 verbose cwd D:\github\ant-design
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error antd@2.12.0 start: `bisheng start -c ./site/bisheng.config.js --no-livereload`
23 error Exit status 1
24 error Failed at the antd@2.12.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by afc163** [comment]
Feel free to dig into it and give us PR directly.

**Comment by sunchenguang** [comment]
try `cnpm`, i think it's just work and fast
