### ISSUE TITLE
Do not know the total number of tables.

### ISSUE THREAD

**Issue by onweer** [ant-design/ant-design#6780]
### What problem does this feature solve?
请求的后台数据永远只有一页数据（分页），每次点击Table 右下角的页码重新请求数据。后台数据库返回请求的数据，但是不会返回数据的总数目（出于数据库性能考虑和数据安全考虑）。如何做到跳转到最后一页？或者输入指定跳转的页数？

### What does the proposed API look like?
|参数|说明|类型|默认值|
-------|-------|----|----
showLastPageButton | 是否显示最后一页按钮   | Boolean  |  'false' |

**Comment by afc163** [comment]
<img width="434" alt="xx2" src="https://user-images.githubusercontent.com/507615/28003833-239ed0d8-6573-11e7-94fd-b81f5a3abf10.png">

<img width="456" alt="xx1" src="https://user-images.githubusercontent.com/507615/28003834-23b27d68-6573-11e7-85c1-0f58f00c7375.png">

http://ant.design/components/pagination

I believe this is what you need.

**Comment by afc163** [comment]
> 但是不会返回数据的总数目

如果是这样，那前端是不可能解决的。

**Comment by onweer** [comment]
@afc163 我看淘宝，京东商城的都是假数据，写的有100页，但是翻到80页左右就没有数据了。 如果数据量大了，计算这个总 count 是不是非常消耗数据库性能呢？

**Comment by bang88** [comment]
这个没有什么问题的。 让后台给你返回一个总条数就好了。。  都有缓存服务的
