### ISSUE TITLE
Radio and RadioGroup  need to support attribute name

### ISSUE THREAD

**Issue by DavidHe1127** [ant-design/ant-design#6781]
### What problem does this feature solve?
No idea what the question is. Does not make sense to me.

### What does the proposed API look like?
<RadioGroup name={name} />
<Radio name={name} />

**Comment by bang88** [comment]
`Radio` has support name attribute already,
Do you mean `RadioGroup` needs name attribute ? i think this is unnecessary, you can use Radio name instead.

**Comment by DavidHe1127** [comment]
Thanks for your quick reply. In which version does it support? I am using `2.6.0` which does not seem to work. I print out `e` from `onChange` set on `<RadioGroup>` as follow.
```
{"target":{"className":"radioStyle__app-components-RepaymentCalculator-NewLoanDetailsForm-style__2Kai5","value":true,"children":null,"prefixCls":"ant-radio","checked":true,"disabled":false,"style":null,"type":"radio","defaultChecked":false}}
```
There is no `name` attribute.

My component looks like this
```
          <RadioGroup onChange={onInterestOnlyToggle} value={interestOnly}>
            <Radio className={style.radioStyle} name='xxx' value={false}>
              Principal and interest
            </Radio>
            <Radio className={style.radioStyle} value={true}>
              Interest only
            </Radio>
          </RadioGroup>
```
Please advice on how to access name attribute?

**Comment by bang88** [comment]
Whats your use case , IMO, its no need a name attribute here, you can store your value in state and then listen radio change event, if the value has changed you can get what you need, and radio group   always have a same name. Please see the documentation for more examples, i think its very clear for this situation.

**Comment by DavidHe1127** [comment]
Thanks for your clarifications. I deleted the comment since I know the solution.
