### ISSUE TITLE
想要获取table组件使用filter后的datasource数据

### ISSUE THREAD

**Issue by javaforlife** [ant-design/ant-design#6783]
### What problem does this feature solve?
场景：
业务场景要求table合并相同单元格，没有过滤前的处理是循环遍历dataSource然后计算出当前列每行对应的rowspan值，但是使用filter后无法获取过滤后的datasource，也就无法计算出rowspan值，希望提供接口能够获取filter后的datasource数组值。
PS:调试时发现Table组件的下层组件有个key为table的子组件，其下props中有一个data属性保存了过滤后的datasource，但是目前没有api可以拿出来？

### What does the proposed API look like?
希望在onchang中可以返回过滤后的datasource，或者Table组件中增加api可以获取到。

**Comment by paranoidjk** [comment]
I don't get it.  I think you can get filtered data through `onChange: Function(pagination, filters, sorter)`

https://ant.design/components/table-cn/#components-table-demo-head

**Comment by javaforlife** [comment]
@paranoidjk onChange: Function(pagination, filters, sorter) ，this method can't fetch!

**Comment by yesmeck** [comment]
用 `onChange` 配合 `onFilter` 自己做下过滤吧。`onFilter` 全部返回 `true`，然后根据 `onChange` 里拿到的 `filters` 是过滤数据。

**Comment by Lizhooh** [comment]
使用了 Redux，使用 Table 自带的排序功能后，希望能拿到排序后的数据源，更新 Store。
```js
<Table
    columns={columns} dataSource={data}
    onChange={(pagination, filters, sorter) => {
        console.log({ pagination, filters, sorter });
        /*
        {
            pagination: {},
            filters: {},
            sorter: {
                columnKey: "name",
                field : "name",
                order: "descend",
            },
        }
        */
    }}
    />
```
按照上面的说法，在 onChange 里拿到排序的信息之后还需要写一个排序的 Action。
```js
// action
data.sort((a, b) => {
    if (sorter.order === 'descend') {
        return b[sorter.field] - a[sorter.field];
    }
    else {
        return a[sorter.field] - b[sorter.field];
    }
});
```

显得有点多此一举。如果，能提供排序后的数据，那么 Action 只是一个赋值操作。

**Comment by qzjgithub** [comment]
里面的table中的data也不是过滤后的数据，是过滤后当前页的数据。不过我也不知道怎么拿出来。

**Comment by Pysics** [comment]
这个需求是很需要的
table展示的是排序后的数据，只能拿到排序后的索引
如果要更新store中未排序的数据，就很麻烦
希望能提供排序前后数据索引的映射接口

**Comment by atzcl** [comment]
有同样的需求

**Comment by CJanF** [comment]
we need a API that can return the data after sort

**Comment by dadawanan** [comment]
we need a API that can return the data after sort

**Comment by w6fux5** [comment]
we need a API that can return the data after sort

**Comment by Simons-Maddy** [comment]
we need a API that can return the data after sort

**Comment by Simons-Maddy** [comment]
> 

可以在<Table summary={(pageData)=>{}}>里面拿到当前页的数据
