### ISSUE TITLE
Programatically show validation status

### ISSUE THREAD

**Issue by gavinrobertszeco** [ant-design/ant-design#6784]
### What problem does this feature solve?
After validating my local form and submitting the data, my server may return an 422 error stating that one or more fields is invalid. 

To ensure that my form handles server side validation as well as client side, I need to be able to display the validation error message as the form would display client side errors.

Is this possible and if not, can it be added? Are there any potential work arounds other than creating states and showing messages beneath the form items?

### What does the proposed API look like?

To be discussed if required at a future point.

**Comment by bang88** [comment]
I think this should handle it on the client side , keep a  same validation rule as server side it is. if these rules are different then maybe you should handle it in another way, because before you submit the form it has pass the validation.

**Comment by gavinrobertszeco** [comment]
Hey @bang88 -

We have client side validation but we also carry out the same validation on the server side just in case and report back an array of field names and associated error messages.

We wanted to avoid having to display errors using states, if we could simply reference the input that failed validation and tell it to display an error beneath it, as if it had failed client side validation.

If this isn't possible, is it not something that others would find useful? If not, not to worry, I will use the state to determine whether to show/hide the error etc.

Many thanks

**Comment by bang88** [comment]
You are welcome, finally find something you need it https://github.com/react-component/form/blob/3b9959b57ab30b41d8890ff30c79a7e7c383cad3/examples/server-validate.js#L74-L79

You can use `this.props.form.setFields` set value or error , could you have a try, it should work.

**Comment by gavinrobertszeco** [comment]
@bang88 -

This looks like an ideal candidate! 

I'll double check and report back as soon as I can.

Thank you for your help :smile:

**Comment by gavinrobertszeco** [comment]
As you suggested, that works perfectly, thank you!

**Comment by saeidalidadi** [comment]
I am using redux to store server errors so  I need to show them after response to user.
when I use `setFields` inside `render` or inside updating lifecycle hooks  I get this error.
```
uncaught at _callee RangeError: Maximum call stack size exceeded
```

**Comment by jasnoponjatno** [comment]
@saeidalidadi same problem for me. Did you found any solution to use form.setFields with errors in props?

**Comment by sureshokp** [comment]
how to use login page with ant design in server side rendering ?

**Comment by yaznayka** [comment]
@saeidalidadi @jasnoponjatno I've used this approach https://stackoverflow.com/a/54187258/2958918 instead of setFields

**Comment by sandalwoodbox** [comment]
It turns out antd uses rc-fields-form under the hood, which documents how to set validation errors here: https://field-form-react-component.vercel.app/demo/reset

**Comment by anaselbahrawy** [comment]
```
import React, { useState } from 'react';
import { Form, Input } from 'antd';

const YourComponent = () => {
    const [errorFields, setErrorFields] = useState({});

    // Assuming error is an object containing data
    const handleError = (error) => {
        setErrorFields(error?.data?.errors || {});
    };

    return (
        <Form>
            <Form.Item
                name="name"
                label="Continents"
                help={errorFields?.name}
                validateStatus={errorFields?.name ? 'error' : ''}
                rules={[{ required: true, message: 'plz enter Continents' }]}
            >
                <Input placeholder="Continents" />
            </Form.Item>
        </Form>
    );
};

export default YourComponent;
```
