### ISSUE TITLE
Ant Design中table如何分层级

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#679]
![default](https://cloud.githubusercontent.com/assets/11780264/11806646/7f9e0dd2-a34f-11e5-982d-486d8db926a5.png)

**Comment by afc163** [comment]
Try this: http://ant.design/components/table/#demo-expand

**Comment by XUGAOBO** [comment]
我试过这个了,我感觉调整table这个层级,需要调整css
