### ISSUE TITLE
Spin组件增加【minHeight】或【height】属性控制

### ISSUE THREAD

**Issue by handycode** [ant-design/ant-design#6795]
### What problem does this feature solve?
当内部元素未渲染，spinning为true时，Spin高度只是内部转菊花的高度，现在每次使用Spin组件 都要手动加style={{minHeight: value}}

### What does the proposed API look like?
<Spin spinning={this.state.loading} minHeight={200} />

**Comment by afc163** [comment]
能用 `style={{minHeight: value}}` 控制的话，没必要单独添加属性。

**Comment by handycode** [comment]
问题是目前minHeight属性只会附加在内部元素.ant-spin-spinning上, 它的position是absolute。 如果这个Spin组件下边还有其它元素， 效果就跟未加minHeight一样。

**Comment by handycode** [comment]
我现在是这样解决
```
<div style={{ minHeight: 140 }}>
     <Spin spinning={!this.state.loaded} delay={200} style={{ minHeight: 140 }}>
       ...
     </Spin>
</div>
```

**Comment by afc163** [comment]
```jsx
<Spin spinning={!this.state.loaded} delay={200}>
  {this.state.loaded ? <Component /> : <div style={{ height: 140 }} />}
</Spin>
```

这样放一个占位符更简单一些。

**Comment by afc163** [comment]
> 目前minHeight属性只会附加在内部元素.ant-spin-spinning上

这个设计的目的是和 `<Spin style={{ ... }} />` 保持统一。
