### ISSUE TITLE
生产环境编译后 现UglifyJs警告 无法去除

### ISSUE THREAD

**Issue by mayichaocc** [ant-design/ant-design#6796]
### Version
2.12.0

### Environment
chrome最新版本

### Reproduction link
[http://www.zanwulianjie.sorry](http://www.zanwulianjie.sorry)

### Steps to reproduce
生产环境压缩编译

### What is expected?
去除警告

### What is actually happening?
WARNING in js/vendor.9003b.js from UglifyJs
Dropping unreachable code [./~/._antd@2.12.0@antd/lib/locale-provider/injectLocale.js:56,0]
Declarations in unreachable code! [./~/._antd@2.12.0@antd/lib/locale-provider/injectLocale.js:56,0]
Dropping unreachable code [./~/._antd@2.12.0@antd/lib/date-picker/createPicker.js:193,0]
Declarations in unreachable code! [./~/._antd@2.12.0@antd/lib/date-picker/createPicker.js:193,0]
Dropping unreachable code [./~/._antd@2.12.0@antd/lib/date-picker/wrapPicker.js:140,0]
Declarations in unreachable code! [./~/._antd@2.12.0@antd/lib/date-picker/wrapPicker.js:140,0]

**Comment by afc163** [comment]
Just ignore the UglifyJs warning.
