### ISSUE TITLE
TimePicker能不能让开发者控制时间刻度

### ISSUE THREAD

**Issue by chakhsu** [ant-design/ant-design#6797]
### What problem does this feature solve?
目前 TimePicker 还不能让开发者自定义时分秒刻度
例如只能让用户选择间隔是每5分钟的时间点，也就是用户只能选择0分钟、5分钟、10分钟等等

### What does the proposed API look like?
提供一个可选的时间刻度间隔属性，例如我设置这个属性值为5，那么用户只能按照每5分钟的时刻去选择时间，不会出现 3分钟 4分钟 等间隔中间时刻的选项

**Comment by afc163** [comment]
https://ant.design/components/time-picker-cn/#components-time-picker-demo-disable-options
