### ISSUE TITLE
Hope that the cascader can choose a level menu or a two-level menu

### ISSUE THREAD

**Issue by yzfdjzwl** [ant-design/ant-design#6798]
### What problem does this feature solve?
For example, I have 3 menus, such as China 's Chengdu City, Sichuan Province, so If I choose a menu, I must choose Chengdu. But I just want to choose China or SiChuan, just doble click on it. This feature has been encountered in many of the projects I have encountered, maybe I did not make it clear. Strongly hope to develop this function.

### What does the proposed API look like?
``` 
<Cascader 
  options={options} 
  onChange={onChange} 
  placeholder="Please select" 
  onDoubleClick={dosomething} 
/>
```

**Comment by afc163** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-change-on-select

**Comment by yzfdjzwl** [comment]
Thanks for your replying , but maybe you don't understant what's my meaning. I just want to say that if there are three levels,  how can i choose the first level? I don't want to choose the last level.

**Comment by yesmeck** [comment]
The demo is clear.

**Comment by yzfdjzwl** [comment]
sorry, my fault, I didn't notice the demo.
