### ISSUE TITLE
Add tooltip options for table

### ISSUE THREAD

**Issue by Sergeytroinin** [ant-design/ant-design#6799]
### What problem does this feature solve?
I've faced with case, where I need to put as much column as possible in the one screen. And in the same time column names are really long. I've put names vertically and cut them. It would be greate to have options to enable tooltips in such cases. Maybe it makes sense to implement renderHeader method for column to make more general solution. 

### What does the proposed API look like?
Implement for column `renderHeader()` that have the similar interface to `render()` - `Function(text, record) {}`

**Comment by afc163** [comment]
```jsx
title: <Tooltip><span>xxx</span><Tooltip>
```
