### ISSUE TITLE
Slider组件 Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by shelwei** [ant-design/ant-design#680]
使用Slider组件，设置 onChange事件：
```javascript
        this.setState({
            sliderValue: value
        });
```
会有报错：
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
```
- antd 版本：^0.10.0-beta30
- 操作系统及版本：Mac OS X 10.11.1、centos 6.5
- 浏览器及版本：chrome 47.0.2526.73 
- 在线演示地址：http://jsfiddle.net/zz74n3ny/2/

**Comment by afc163** [comment]
Try `0.10.4` first.

**Comment by benjycui** [comment]
https://github.com/react-component/slider/issues/57

**Comment by shelwei** [comment]
@afc163 0.10.4 同样如此
@benjycui  只要 加上
```javascript
this.setState()
```
就会报错，而且其它点击事件均为报这个错
```
Uncaught TypeError: Cannot read property 'toFixed' of undefined
```

**Comment by benjycui** [comment]
@shelwei 发布了 rc-slider@3.1.5，重新安装一下就行。

`npm uninstall rc-slider && npm install`

先关，还有问题再开。

**Comment by jeffie** [comment]
依然存在这问题啊，"antd-mobile": "^1.7.2"版本

**Comment by harunurhan** [comment]
In case anyone has this issue in the feature, try giving a width to slider

`<Slider style={{ width: 140 }}...`
