### ISSUE TITLE
scroll bar shows at any time

### ISSUE THREAD

**Issue by initialdmg** [ant-design/ant-design#6800]
### Version
2.12.0

### Environment
windows 7 , chrome 50

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-header](https://ant.design/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce
use fixed header table

### What is expected?
donot show the gray arrows and scroll bar

### What is actually happening?
scroll-y shows as long as using fixed header

---
workaroud i used https://github.com/initialdmg/ant-design/commit/d3beb3eaee4eecd72db16f60ebbf508123fd17db

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/4637

试过四种方式解决头部多余的 scrollbar，但是都会影响列的对齐。

**Comment by initialdmg** [comment]
谢谢

**Comment by mfaradzh** [comment]
You also want when changing styles of overflow to hidden to changes margin. This resolves issue of the table hiding part of the table.
`        .ant-table-fixed-header .ant-table-scroll .ant-table-header{
                overflow: hidden !important;
                margin-bottom: 0px !important;
        }`
