### ISSUE TITLE
Unable to load locale with Typescript

### ISSUE THREAD

**Issue by gRoberts84** [ant-design/ant-design#6801]
### Version
2.12.0

### Environment
Chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://github.com/gRoberts84/AntD-Locale-Bug](https://github.com/gRoberts84/AntD-Locale-Bug)

### Steps to reproduce
1. git clone https://github.com/gRoberts84/AntD-Locale-Bug
2. cd AntD-Locale-Bug
3. yarn install
4. yarn start

### What is expected?
Table's `No Data` message should be in English.

### What is actually happening?
The locale import fails to return anything, causing the LocaleProvider to return to default.

---
When using the CodePen sample to replicate the issue, it works fine. https://codepen.io/gRoberts84/pen/eRQwjM

**Comment by afc163** [comment]
https://github.com/gRoberts84/AntD-Locale-Bug/pull/1

And here is something maybe helpful: https://github.com/ant-design/ant-design/pull/6193/

**Comment by gRoberts84** [comment]
Hi @afc163 -

Thank you for getting back to me and for the fix! 

Many thanks :smile:
