### ISSUE TITLE
Submenu title lost selected style on collapsed Sider when its child is selected

### ISSUE THREAD

**Issue by ericshao** [ant-design/ant-design#6803]
### Version
2.12.0

### Environment
MacOS,Chrome 59

### Reproduction link
[https://codepen.io/anon/pen/bROgmw/](https://codepen.io/anon/pen/bROgmw/)

### Steps to reproduce
As codepen illustrated

### What is expected?
Submenu should be in different background color when it has selected child menu item

### What is actually happening?
Submenu appears nothing different whether its child menu item is selected or not

**Comment by benjycui** [comment]
I think it works fine, the style of title of SubMenu won't be changed even it is not in Collapse:

![image](https://user-images.githubusercontent.com/3580607/28100299-baef9d6a-66f3-11e7-8dfe-1b95e5aa6ecd.png)

**Comment by benjycui** [comment]
And the UX in your CodePen it weird.
