### ISSUE TITLE
Add elegant fallback for Avatar background loading fail

### ISSUE THREAD

**Issue by neekey** [ant-design/ant-design#6804]
### What problem does this feature solve?
Currently If I use Avatar with an image, an ugly broken browser default icon will show up if the loading fails. I would suggest if Avatar detects the error, it should just not render the image. 

This will be perfect if people use the image from Gravatar, because for every given email, we can not tell if the email has an associated image uploaded to Gravatar, but we can still create the URL and set it to the Avatar component as well as send user's name to it. So if the image exists, the avatar will just show the image, if not, the name will show up.

### What does the proposed API look like?
API does not need to be change, just dont render the image if it fails to be loaded.

**Comment by benjycui** [comment]
We can make `Avater[children]` to be required @ddcat1115 

```jsx
<Avatar src="...">Benjy</Avatar>
```

If we cannot load image, just show `Avatar[children]`?

**Comment by neekey** [comment]
by the way, you can see the broken image example here https://codepen.io/neekey/pen/yXGbRN (open it with chrome)

**Comment by benjycui** [comment]
Fixed in b45bf6d

It is not perfect, but works fine in many use case.
