### ISSUE TITLE
Change scroll not working in Table

### ISSUE THREAD

**Issue by prillymonials** [ant-design/ant-design#6805]
### Version
2.12.0

### Environment
All Browser, React, React Native

### Reproduction link
[https://codepen.io/prillymonials/pen/rwomEj](https://codepen.io/prillymonials/pen/rwomEj)

### Steps to reproduce
1. Set state scroll to 300
2. Make button to change the scroll height
3. Click the button

### What is expected?
Scroll is 200 instead 300

### What is actually happening?
Still 300

**Comment by afc163** [comment]
```diff
- this.onClear
+ this.onResize
```
