### ISSUE TITLE
Maybe a better way of doing theming?

### ISSUE THREAD

**Issue by neekey** [ant-design/ant-design#6807]
### What problem does this feature solve?
Hi I just started to try to get Ant Design working in my project, and spent quite a lot time making the theming work.

My project is react/webpack based, so at first I tried to use the recommended way of using `modifyVars` option in `less-loader`, it worked, but the main problem about this approach is that I have to restart webpack to update my customised variables, for a large project, it will be a nightmare.

So I turned to the alternative way of using less variable override. It worked as well, but just like the documentation pointed out, it is not perfect:

> This way will load the styles of all components, regardless of your demand, which cause style option of babel-plugin-import not working.

So the issues with the alternative way seem to me are:
- it will load everything
- if I use the alternative less-variable-override way together with `babel-plugin-import`, the style may be loaded twice (correct me if I am wrong)

------

So somehow, I checked out the source code of `babel-plugin-import`, it looks like, it will try to import style files together with every module, then I looked through the source codes of ant design components, and found that for every component entry file, there is a style entry file aside, like `antd/lib/components/table/style/index.less`. And in every style entry file, it imported the `themes/default.less` file.

So if that is the case, the better way of doing theming and still having the advantage of `babel-plugin-import` is that we somehow manage to replace the `themes/default.less` with our own theme file.

Here comes another less plugin [less-plugin-rewrite-import](https://github.com/webuni/less-plugin-rewrite-import) that can solve this problem, I have used it before for the theming of `semgntic-ui-react`.

So what one need to do is:

1. Create a theming file, like `antd.theme.less` in his own project.
2. In the theming file, include the default theming file:

```
@import "antd/lib/style/themes/default.less";
```
3. Add the plugin to less loader (notice `'../../style/themes/default'` is the path that used in every component style entry file:

```js
loader: 'less-loader',
  options: {
    paths: [
      srcPath,
      nodeModulePath,
    ],
    plugins: [
      new RewriteImportPlugin({
        paths: {
          '../../style/themes/default': __dirname   '/ant-theme-vars',
        },
      }),
    ],
  }
```

For less loader to use its own resolver, you need to manually provide path to it (otherwise it will use webpack's resolver and the plugin will be bypassed)

And done. Now we can use less variable to do theming and also have the benefit of only load what we use.

### What does the proposed API look like?
No, this is just a discussion.

**Comment by benjycui** [comment]
trace: https://github.com/ant-design/ant-design/issues/5656
