### ISSUE TITLE
checkbox样式问题

### ISSUE THREAD

**Issue by chuhanan** [ant-design/ant-design#6808]
### Version
2.8.3

### Environment
any

### Reproduction link
[https://ant.design/components/checkbox-cn/](https://ant.design/components/checkbox-cn/)

### Steps to reproduce
选中checkbox之后,点击取消选中,checkbox还是有border,需要再次点击border才会消失, 

### What is expected?
取消选中后border的颜色会自动去掉? (focus时样式在取消时还是存在)

### What is actually happening?
选中checkbox之后,点击取消选中,checkbox还是有border,需要再次点击border才会消失, 

---
checkbox取消选中时 颜色可以被自定义

**Comment by afc163** [comment]
It is for accessibility (tab to focus, keyboard support), hard to find a perfect solution.

https://semantic-ui.com/modules/checkbox.html have same behavious.
