### ISSUE TITLE
the className of input.search should reside on outer element

### ISSUE THREAD

**Issue by huangbinjie** [ant-design/ant-design#6809]
### What problem does this feature solve?
when i set className to the Input.Search, the class was't  set to the input element.

### What does the proposed API look like?
I expected that the className can be set to the wrapper element:
```
<span className={myClassName}>
   <input />
</span>
```

**Comment by afc163** [comment]
Nope, if the className is in the input, then we can't customize the search icon style of `Input.Search`.
