### ISSUE TITLE
希望InputNumber可以自动处理科学计数法

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#681]
当前InputNumber会直接展示科学计数法，而实际上我们希望看到原本的数字。
如：我想看到“0.000000000001”，而不是“1e-12”。另外step接收值为number类型，出现科学计数法会导致异常；step传string类型能正常工作，但会有警告。
现在我自己想办法把科学计数法转换成字符串，希望控件可以支持一下。
![d0f5e45b-a338-44dc-b567-30d333aa6c7a](https://cloud.githubusercontent.com/assets/2247780/11807603/bec887a2-a355-11e5-88bc-45e3e5ec5932.png)

**Comment by afc163** [comment]
科学计数法比较麻烦，20位以上大数和10位小数目前都会出现这个问题。

> PS 额外发现了一个计算精度的问题。

**Comment by afc163** [comment]
暂不支持更大数字的支持，当然欢迎 PR ~

**Comment by kpaxqin** [comment]
这儿我觉得行为还是应该向原生input[type="number"]看齐
1. 使用string类型的值，这样可以更好规避大数、丢精度等问题
2. 对非法输入（非数字），抛出空值

现在的InputNumber，onchange给的是number类型，但如果用onBlur等e.target.value去拿，其实还是string，正常来讲要么全包，要么全不包，各种方式拿到的value应该有一致性。
甚至同样的onchange事件，在清空值并移开光标时onchange触发了两次（第二次是blur触发的），值的类型还不一样，看着非常怪异，如下图
![image](https://user-images.githubusercontent.com/6220685/86448280-1e7d1e80-bd49-11ea-8868-d80d9fc8ed6e.png)

总的来说最大的价值应该是保证不同浏览器平台、地区的一致性（不同region、不同浏览器下，原生input[type="number"]的行为有差异，且IE系列很坑）
