### ISSUE TITLE
PropTypes ColProp for shape of labelCol and wrapperCol Props for grid

### ISSUE THREAD

**Issue by richardjboothe** [ant-design/ant-design#6810]
### What problem does this feature solve?
My team is using a linter that disallows the use of `PropTypes.object`. Because there are multiple instances where a shape can be formed, for these particular props (`wrapperCol` and `labelCol`) I would like to avoid writing the shape in each file or creating my own by copying/pasting with modification from the typescript file. I was hoping a readily made ColProps was available. After looking at the source code I see in `ant-design/components/grid/col.tsx` that there is a ColProps object that would be perfect to use, but is unavailable from the node_module version my team has. Is ColProps accessible anywhere in the current version?

### What does the proposed API look like?
It would be nice to have ColProps available in some format like: 
```
import React from 'react';
import PropTypes from 'prop-types';
import { Col } from 'antd';

const ColProps = Col.PropShape;
const propTypes = {
   layout = PropTypes.shape({
     labelCol: ColProps,
     wrapperCol: ColProps,
  }),
};

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by benjycui** [comment]
PR is welcomed @richardjboothe

**Comment by afc163** [comment]
ping~

**Comment by afc163** [comment]
You can try this:

```js
PropTypes.shape(Col.propTypes);
```
