### ISSUE TITLE
How do I set the default value for lazy loading cascading loader?

### ISSUE THREAD

**Issue by zhanzl1** [ant-design/ant-design#6811]
### What problem does this feature solve?
The default setting is only the first level, and level third and level second are not loaded

### What does the proposed API look like?
All default values are loaded

**Comment by afc163** [comment]
Use `value` and `onChange` to control it.

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by zhanzl1** [comment]
How does the Cascader component work out?
The loadData of the Cascader component will not be active

**Comment by zomars** [comment]
I'm having this exact issue, this the proposed solution doesn't solve lazy loaded data

**Comment by JeffJankowski** [comment]
Please re-open this issue. It does not seem possible to set a default value that is deeper than the first level of the hierarchy if we are lazy loading data.

**Comment by JeffJankowski** [comment]
@zomars and anyone else dealing with this: My workaround was to wrap the `Cascader` in another component that accepts an `initialValue` prop in the array format the `Cascader` accepts. I can use length and array elements to load the necessary data for options on mount, and then set the `value` with the `initialValue`.

**Comment by zomars** [comment]
@JeffJankowski do you have a working example? I kinda get it, but I think you can't set initialValue when you're using `getFieldDecorator` .

**Comment by JeffJankowski** [comment]
@zomars Unfortunately, antd's form functionality wasn't sufficient for my use-case, so I switched to Formik for binding and validation. However I don't see why couldn't do something like this:

```
function WrappedCascader({initialValue, ...props}) {
	[options, setOptions] = useState([]);
	useEffect(() => /*load data and setOptions*/, [initialValue])
	return getFieldDecorator('fieldName', {initialValue: initialValue})(
    <Cascader options={options} disabled={!options} {...props}/>
  );
}
```

I haven't tested it, but I assume you can load the options at mount using `useEffect` before attaching the `getFieldDecorator` binding.
