### ISSUE TITLE
ref missing in AutoComplete children

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#6814]
```jsx
<AutoComplete>
  <input ref={(node) => { this.input = node; } } />
</AutoComplete>
```

codepen: https://codepen.io/afc163/pen/YQBGBq?editors=0010

**Comment by benjycui** [comment]
这里处理下冲突就可以了

https://github.com/react-component/select/blob/bdddb40b0b4a29bff48b20246ae0dbcc6db26aac/src/Select.jsx#L520
