### ISSUE TITLE
请问，表格中怎么实现选中某一行然后变色

### ISSUE THREAD

**Issue by yuyc** [ant-design/ant-design#6815]
### What problem does this feature solve?
现在鼠标放在table的某一行上会变色，但是移动走就不会变色，我想实现一个鼠标点击按钮就标示某一行，如果通过单个字段渲染北京的话，只是渲染了单个表格中间的一部分，背景色无法覆盖整个单元格，请问有什么办法解决吗？

### What does the proposed API look like?
给一个状态位就可以了

**Comment by benjycui** [comment]
Try `rowClassName`
