### ISSUE TITLE
TreeView: autoExpandParent not honored when controlled selectedKeys are set

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#6816]
### Version
2.12.0

### Environment
MacOS, Chrome

### Reproduction link
[https://codepen.io/sk_tectus/pen/xrMqZQ?editors=0110](https://codepen.io/sk_tectus/pen/xrMqZQ?editors=0110)

### Steps to reproduce
- Set up a nested tree view as illustrated in the example
![image](https://user-images.githubusercontent.com/12829747/28154346-559e2460-67dc-11e7-9af9-0dcfed7cf905.png)

- Set up a button to modify the `selectedKeys` prop that's passed in to the Tree

### What is expected?
When clicking the button to modify the prop, the node is selected and it's parents should be expanded.
![image](https://user-images.githubusercontent.com/12829747/28154366-65b84d8a-67dc-11e7-82a5-65e04a4f28e5.png)

### What is actually happening?
Currently, the node is selected but the parent nodes are **not** expanded

**Comment by kappa-gooner** [comment]
Guys, any update on this? 
If you are busy, I'll be happy to help with a PR for this. Please lemme know.

@yesmeck @afc163

**Comment by benjycui** [comment]
> If you are busy, I'll be happy to help with a PR for this. Please lemme know.

Just try, we are busy recently, sorry.

**Comment by benjycui** [comment]
I read this issue again.

Why should autoExpandParent honor selectedKeys? It just need to honor expandedKeys.

**Comment by kappa-gooner** [comment]
@benjycui,  Missed out on this!
Well, if you're passing `selectedKeys`; it implies you want the node to be selected.
How does it help if the node is hidden, nested somewhere deep? We should expand it and show exactly what has been selected, right?

**Comment by benjycui** [comment]
Nope, select is different from expand.

Just update expandedKeys as you want.
