### ISSUE TITLE
Anchor锚点在Layout固定侧边栏布局中无效

### ISSUE THREAD

**Issue by huangyaao** [ant-design/ant-design#6817]
### Version
2.12.0

### Environment
win7 ， Google Chrome ， react@15.4.1

### Reproduction link
[https://codepen.io/huangyaao/pen/Ngopgj](https://codepen.io/huangyaao/pen/Ngopgj)

### Steps to reproduce
将锚点写在<Layout style={{ height: '100vh' }}>中会无效,去掉height无法固定侧边栏和顶部导航栏

### What is expected?
点击锚点跳到相应的内容

### What is actually happening?
锚点无效

**Comment by afc163** [comment]
`<Layout style={{ height: '100vh' }}>` 做滚动布局是有坑的，原来的 demo 代码有问题。改成 22e14970ec8cec1fbdab9f28ed9afebe4e797f83 里的写法，滚动区域变成 body，这样不会影响 Anchor 和 BackTop。

https://ant.design/components/layout-cn/#components-layout-demo-fixed-sider

**Comment by huangyaao** [comment]
@afc163 
嗯，谢谢，问题解决了。但是我还是认为这是Anchor的bug。在出错的场景下自己写个描点是没有问题的。

**Comment by afc163** [comment]
不是 bug，Anchor 默认监听的是 body 的滚动。`<Layout style={{ height: '100vh' }}>` 的例子里滚动的不是 body 是 Layout ，Anchor 自然监听不到。实际上，Anchor 还有一个 undocumented 的属性 [target](https://github.com/ant-design/ant-design/blob/91707b89d80972d269ec14cfbe6f2c5bed50d25c/components/anchor/index.tsx#L10) 用于指定滚动监听节点，可能有坑不推荐使用。https://github.com/ant-design/ant-design/pull/3399

**Comment by benjycui** [comment]
> why remove the 'overflow: auto' css props ? It crash my page layout

Please file a new issue.

**Comment by davidctj** [comment]
I agree with @Roy9102 , also breaks my app.
I raise a issue https://github.com/ant-design/ant-design/issues/7256, but without codepen example, BTW
