### ISSUE TITLE
[Bug]Upload component doesn't handle some error scenarios which response is not a string

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#6818]
### Version
2.12.0

### Environment
windows chrome-canary-61.0.3155.0

### Reproduction link
[https://codepen.io/anon/pen/zzeZae?editors=0010](https://codepen.io/anon/pen/zzeZae?editors=0010)

### Steps to reproduce
1. Press F12 to open the devtools, and then click the upload button and post any file

2. Wait for upload failure, and then **hover** the file name 

3. Watch the console,there will appear some info like

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {success, errors,
payload, status}). If you meant to render a collection of children, use an array instead or wrap
the object using createFragment(object) from the React add-ons.
```

The reason is that [UploadList.tsx#L158](https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx#L158) doesn't think about response normally is an object rather than string, when it is an object, we pass it to [Tooltip.jsx#L50](https://github.com/react-component/tooltip/blob/master/src/Tooltip.jsx#L50), but apparently it's a javascript object rather than React element(node), so that's why the error says ` Objects are not valid as a React child......`

So the **alternative** solutions:
- Just use `locale.uploadError` at [UploadList.tsx#L158](https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx#L158)

or 

- Add a prop maybe called `responseErrorKey`,its value represent the error info which would be displayd(i.e. the `title` which be passed to `Tooltip`). e.g `a.b` represent we get `response.a.b` and pass it as `title` to `Tooltip`

or

- Just make we can cover `title`(e.g. use `<Tooltip title={props.tooltipErrorTitle && message}>`)

### What is expected?
No Error

### What is actually happening?
Error happened

**Comment by NE-SmallTown** [comment]
Is there any thought about this?If it has been solved, I think it would be better to close it

**Comment by NE-SmallTown** [comment]
close for no response

**Comment by afc163** [comment]
Sorry for late response.

**Comment by NE-SmallTown** [comment]
Thanks for your reply. just one question, we use `file.response && React.isValidElement(file.response)` but there is no possible `React.isValidElement(file.response)` return `true` because `React.isValidElement(foo)` return `true` only when `foo` is your own React component(e.g `<Foo/>`) or dom element(e.g `<a>bar</a>`), but `file.response` can't be them.

So I suggest use `file.response && lodash.isString(file.response)` instead.

**Comment by afc163** [comment]
You are right.

**Comment by afc163** [comment]
Next time you can PR to us instead of closing issue for no response.

**Comment by NE-SmallTown** [comment]
ahh, ok, I will try. The main reason is that I am not sure whether my thought is right, so I want to confirm first to avoid unnecessary pr :smile:
