### ISSUE TITLE
Table组件中配置选择框的默认属性(disabled)

### ISSUE THREAD

**Issue by zhangxianggui** [ant-design/ant-design#682]
代码如下：
```
const rowSelection = {
	getCheckboxProps: record => {
		return {
			disabled: true
		}
	},
	onSelect: (record, selected, selectedRows) => {
		console.log(record, selected, selectedRows);
	},
	onSelectAll: (selected, selectedRows) => {
		console.log(selected, selectedRows);
	}
}
```
UI如下图：
<img width="1280" alt="screen shot 2015-12-16 at 01 12 25" src="https://cloud.githubusercontent.com/assets/15868425/11818046/11a93d4e-a393-11e5-8885-597649a778b2.png">

当前页所有checkbox设置为disabled是，全选的checkbox被勾选中？

**Comment by JoeBBChen** [comment]
请问一下，最左边那列选中框，怎么才能弄到最右边？
