### ISSUE TITLE
Icon button with loading state displays incorrectly.

### ISSUE THREAD

**Issue by gRoberts84** [ant-design/ant-design#6822]
### Version
2.12.0

### Environment
Chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://codepen.io/gRoberts84/pen/gRqxJW?editors=001](https://codepen.io/gRoberts84/pen/gRqxJW?editors=001)

### Steps to reproduce
1. Add `loading={true}` or `loading={this.state.loading}` to a button.
2. Render
3. Notice button shrinks and loading icon appears outside.

### What is expected?
Loading icon should remain within the button.

### What is actually happening?
Loading icon appears outside the button.

---
`.ant-btn.ant-btn-loading:not(.ant-btn-circle):not(.ant-btn-circle-outline) .anticon` contains a -14px margin that when disabled, works fine.

**Comment by jdz321** [comment]
It is because `padding` in Button.Group & icon-only button has changed.    I fixed it by reseting the padding.

**Comment by gRoberts84** [comment]
Hey @jdz321 / @benjycui 

Just so I can plan ahead, when is the next planned release?

**Comment by benjycui** [comment]
@gRoberts84 2.12.1 had been published.
