### ISSUE TITLE
The animation of Menu Component not play when collpase/expand SubMenu

### ISSUE THREAD

**Issue by ding-js** [ant-design/ant-design#6825]
### Version
2.12.0

### Environment
Windows 10 & Chrome  59.0.3071.115/ Edge

### Reproduction link
[https://codepen.io/dingjs/pen/owmdpK?editors=0010](https://codepen.io/dingjs/pen/owmdpK?editors=0010)

### Steps to reproduce
Click the menu element which has submenu.

### What is expected?
SubMenu show/hide with animation

### What is actually happening?
The animation not play

---
The height property of `.ant-menu-inline` has changed at once when i click the menu.
So i change transition property of `.ant-menu-inline` element from `width` to `width,height`,it works.

**Comment by afc163** [comment]
Fixed in 516ce2d8211797ed3d048bee499c85004439f105, wait for next release.
