### ISSUE TITLE
Tooltip can't align edge

### ISSUE THREAD

**Issue by ibyh** [ant-design/ant-design#6830]
### Version
2.12.0

### Environment
WIN10 X64、Chrome 59、React 15.6.1

### Reproduction link
[https://codepen.io/ibyh/pen/OgqJVa?&editors=001](https://codepen.io/ibyh/pen/OgqJVa?&editors=001)

### Steps to reproduce
```` javascript
<Tooltip placement="topLeft" title="Prompt Text">
      <Button>Align edge / 边缘对齐</Button>
</Tooltip>
````

在网页中查看运行结果并不是左上边缘对齐，差不多是中间对齐。
when i browse the page,the tooltip not align topLeft,but amost center

### What is expected?
the tooltip is align topLeft

### What is actually happening?
the tooltip align amost center

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/commit/9dcc28e218376d6c9d282bbe1349e26177e004f0

**Comment by afc163** [comment]
Thx for reporting it!
