### ISSUE TITLE
ant Design 子表格嵌套实例，让每行展开的数据不一致

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#6831]
### What problem does this feature solve?
开发中，每个展开的行下数据是不一致的

### What does the proposed API look like?
易上手

**Comment by yesmeck** [comment]
请详细描述你的应用场景和希望我们改进的地方，更新后@我来重新打开。

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
