### ISSUE TITLE
When the header is too long in Collapse.Panel

### ISSUE THREAD

**Issue by cnLGMing** [ant-design/ant-design#6832]
### Version
2.12.0

### Environment
Windows 10(x64) / Chrome:59.0.3071.86(x64) / react: 15.6.1 

### Reproduction link
[https://codepen.io/cnLGMing/pen/KqEwVW?editors=0010](https://codepen.io/cnLGMing/pen/KqEwVW?editors=0010)

### Steps to reproduce
1. Set a long text to header 
2. Render

### What is expected?
I think when the header is too long, the layout should automatically increase, and the word line.

### What is actually happening?
Now, when the header is too long, the layout does not change, just wrap it

**Comment by afc163** [comment]
PR is welcome~
