### ISSUE TITLE
使用card组件时，发现里面有个body样式是margin:-0.5px,这时候鼠标移上去会出现这个滚动条，这个怎么解决呢？

### ISSUE THREAD

**Issue by jiangyijoin** [ant-design/ant-design#6833]
![image](https://user-images.githubusercontent.com/7486560/28199704-51951284-689a-11e7-850c-ed3097998dc9.png)

**Comment by afc163** [comment]
把类似下面的针对 Card 的定制样式去掉：

<img width="174" alt="image" src="https://user-images.githubusercontent.com/507615/28199777-d59ec732-689a-11e7-9b08-e38359df4e8d.png">

**Comment by afc163** [comment]
我猜你用的是这个 https://github.com/zuiidea/antd-admin/pull/413

**Comment by jiangyijoin** [comment]
已经发现问题了哦，原来是他这个项目对样式进行修改了。
