### ISSUE TITLE
Allow to set type of Popconfirm OK button

### ISSUE THREAD

**Issue by oluckyman** [ant-design/ant-design#6840]
### What problem does this feature solve?
UX guidelines suggest to make Delete button de-emphasized to not draw attention, so in forms Delete button should be made as a link or as a button with type 'dashed'.
When the button is pressed, the confirmation popover appears. And in that popover the delete button should be marked as danger, rather than primary.
![image](https://user-images.githubusercontent.com/642673/28211038-d9d7cdf8-689a-11e7-9fec-d6e58ce7de26.png)

### What does the proposed API look like?
```
<Popconfirm
  okText="Delete"
  okType="danger"
/>
```

**Comment by afc163** [comment]
That will be useful, could you help us by sending a PR to `feature-2.13`?

**Comment by benjycui** [comment]
Close in https://github.com/ant-design/ant-design/pull/6848
