### ISSUE TITLE
Form表单中单个formitem包含多个input时的处理

### ISSUE THREAD

**Issue by leicj** [ant-design/ant-design#6841]
### What problem does this feature solve?
在编写form表单时候, 出现单个formitem中包含多个input的情况:
```
          <FormItem label="输出:" {...itemLayout}>
            {getFieldDecorator('output_exp', {
              rules: [{ required: true, message: '输出不可为空!'}]
            })(
              <Input />
              <Input />
            )}
          </FormItem>
```

这时候, 如果获取, 则只会读取到第一个input的值.
有什么好的解决办法不? 因为给每个input设置onchange事件不太妥当, 毕竟实际处理中我是动态新增/删除input的操作的.

### What does the proposed API look like?
如果设置多个input, 至少在form.validateFields中获取一个数组的格式, 而非单个input的值.

**Comment by afc163** [comment]
不要这么做，一个 getFieldDecorator 只能关联一个输入组件。

**Comment by leicj** [comment]
当一个name对应多个input的情况怎么办?
如果一个getFieldDecorator对应一个输入组件, 但是多个getFieldDecorator的name又相同,  这在antd上貌似不合法吧. 类似图中的输入源, 一个name对应多个input, 而且是动态新增/删除的.

![1](https://user-images.githubusercontent.com/11996781/28212915-4d5470fc-68d6-11e7-8cb1-2b76f4685423.png)

**Comment by afc163** [comment]
参照 https://ant.design/components/form/#components-form-demo-dynamic-form-item 提交的时候统一处理。

**Comment by leicj** [comment]
谢谢.
antd很是不错, 让我这个不会html/css的人, 也可以写出一个好看的页面.

**Comment by dmwin72015** [comment]
> 不要这么做，一个 getFieldDecorator 只能关联一个输入组件。

不理解？这种使用场景太常见了，尤其是在输入范围的时候，时间选择器不就是么

**Comment by afc163** [comment]
@dmwin72015 https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by yoyo837** [comment]
>不理解？这种使用场景太常见了，尤其是在输入范围的时候，时间选择器不就是么

那只是视觉上的，代码里还是各自一个字段。

**Comment by dmwin72015** [comment]
> > 不理解？这种使用场景太常见了，尤其是在输入范围的时候，时间选择器不就是么
> 
> 那只是视觉上的，只是排版而已，代码里还是各自一个字段。

明白了

**Comment by DualWield** [comment]
> @dmwin72015 https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

4.x.x 的form price的例子有问题，PriceInput没有用传进来的values作为初始值

**Comment by cooper1x** [comment]
意思是每个表单组件都要外面套一层form item么，这个默认样式怎么去掉呢

**Comment by ALKAOUA720** [comment]
再提供一个思路：自定义表单控件
https://ant.design/components/form-cn#components-form-demo-customized-form-controls
