### ISSUE TITLE
Popover 手动控制 visible 后点击非浮层区域无法关闭

### ISSUE THREAD

**Issue by sandywk** [ant-design/ant-design#6850]
### Version
2.12.0

### Environment
1111

### Reproduction link
[http://www.test.com](http://www.test.com)

### Steps to reproduce
Popover 手动控制 visible 后点击非浮层区域无法关闭

### What is expected?
提供解决方法

### What is actually happening?
Popover 手动控制 visible 后点击非浮层区域无法关闭

**Comment by sandywk** [comment]
我是中国人，我只用中文！
要么就别让中国人用！

**Comment by afc163** [comment]
Contoll it like this: https://ant.design/components/popover/#components-popover-demo-control

---

PS: I suggest you give up antd if you have issue with this problem so much. 😃
