### ISSUE TITLE
Tests failing due to non presence of antd/lib/antd-radio/style/css

### ISSUE THREAD

**Issue by vamsiampolu** [ant-design/ant-design#6851]
### Version
2.10.2

### Environment
node

### Reproduction link
[https://hastebin.com/wunegufonu.js](https://hastebin.com/wunegufonu.js)

### Steps to reproduce
I run my tests on the Radio component, the tests look like this:

import MyComponent from './index'
import {Radio as AntdRadio} from 'antd'

import 'jest-styled-components'
import renderer from 'react-test-renderer'

const {Group: AntdRadioGroup} = AntdRadio

### What is expected?
I expect that all my tests will pass without issue because I am using create-react-app as my boilerplate which mocks out css correctly as suggested in the jest documentation.

### What is actually happening?
I find that because the file was not found, my tests are failing.

 FAIL  src/form-schema/widgets/Choice/index.spec.js
  ● Test suite failed to run

    Cannot find module 'antd/lib/antd-radio/style/css' from 'index.spec.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/form-schema/widgets/Choice/index.spec.js:1:140)

 FAIL  src/form-schema/widgets/Radio/index.spec.js
  ● Test suite failed to run

    Cannot find module 'antd/lib/antd-radio/style/css' from 'index.spec.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/form-schema/widgets/Radio/index.spec.js:1:140)

**Comment by afc163** [comment]
Try

```
 import { Radio } from 'antd';
```

**Comment by benjycui** [comment]
cc @sorrycc , it seems that it is an issue of `babel-plugin-import`.

**Comment by yesmeck** [comment]
Config `babel-plugin-import` don't load css or use [moduleNameMapper](http://facebook.github.io/jest/docs/en/configuration.html#modulenamemapper-object-string-string) ignore css.

**Comment by vamsiampolu** [comment]
@yesmech Sorry for the delayed response, I use the following config for jest based on `create-react-app`:

```json
"jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>[/\\\\](build|docs|node_modules|scripts)[/\\\\]"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    }
  }
```

So, any existing css files are handled, the problem here seems to be that the files:

`antd/lib/antd-radio/style/css` must be `antd/lib/radio/style/css`
`antd/lib/autocomplete/style/css` must be `antd/lib/auto-complete/style/css`

**Comment by vamsiampolu** [comment]
@yesmeck Can you reply on the status of this issue, I have tried the fixes that you provided in your post above, however I have found that they are not fixing my problem. Meanwhile I find that this issue is blocking

I cannot use @storybook/storyshots to create automatic storybook based snapshots because of failures in my tests due to the non presence of  these css files. I cannot create any new tests for autocomplete based components due to this issue.

**Comment by yesmeck** [comment]
It's not related to antd, and I think the error message is clear, all you need to do is digging into `node_modules/styled-components/lib/constructors/constructWithOptions.js` to see why `css.apply` is not a function.

**Comment by vamsiampolu** [comment]
Another issue just popped up with the plugin, I updated the antd to `2.12.5` and it now throws a new error in addition to the existing ones

FAIL  src/Storyshots.test.js
  ● Test suite failed to run

    Cannot find module 'antd/lib/antd-form/style/css' from 'Form.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/form-schema/Form.js:1:339)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.863s
Ran all test suites related to changed files.

When I try to look up the directory in node_modules:

~/antd-forms/node_modules/antd/lib story-refactor*
❯ cd antd-form
cd: no such file or directory: antd-form

I cannot find the directory. If I cannot find the module, how can we require the module. I do not understand why the modules are failing in test mode.

**Comment by vamsiampolu** [comment]
Two steps helped me fix this:

1. aliasing of named exports either in the test file or the code file does not work

2. within the jest config create-react-app uses a `transform` to convert `css` imports, instead use `moduleNameMapper`

Now, the code works when I run my tests using jest as long as I dont include the --coverage flag.
The coverage flag breaks all my tests but gives me a coverage report which might now be inaccurate.

The command that I run:

`   jest --no-cache --env=jsdom --coverage`


The config has been slightly tweaked based on the item above:

```
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/config/jest/test_setup_file.js",
    "testPathIgnorePatterns": [
      "<rootDir>[/\\\\](build|docs|node_modules|scripts)[/\\\\]"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```


The error looks like:

```
 FAIL  src/form-schema/widgets/Radio/index.spec.js
  ● Test suite failed to run

    ReferenceError: Radio is not defined

      at Object.<anonymous> (src/form-schema/widgets/Radio/index.js:7:81)
      at Object.<anonymous> (src/form-schema/widgets/Radio/index.spec.js:5:40)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at process.nextTick (internal/child_process.js:755:12)
      at _combinedTickCallback (internal/process/next_tick.js:95:7)
      at process._tickCallback (internal/process/next_tick.js:161:9)
```

The error refers to the following line of code:

```
import {Radio} from 'antd'
// where the error occurs, this is because `Radio` could be undefined.
let {Group: RadioGroup, Button: RadioButton} = Radio
```

**Comment by 1yzz** [comment]
jest有提到这个问题
https://github.com/facebook/jest/issues/7957
https://github.com/facebook/jest/issues/7957#issuecomment-584643466
