### ISSUE TITLE
鼠标移动到右边的复制代码icon上，右侧的导航会上下抖动

### ISSUE THREAD

**Issue by demohang** [ant-design/ant-design#6852]
### Version
2.12.1

### Environment
谷歌浏览器

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
点击show code按钮出现代码块，代码块最上边有复制代码icon，鼠标移动到上边右上侧导航会上下抖动

### What is expected?
不抖动

### What is actually happening?
抖动

**Comment by benjycui** [comment]
无法重现:

![image](https://user-images.githubusercontent.com/3580607/28255288-b7f234fe-6ae7-11e7-9401-14ba09db85b2.png)

**Comment by afc163** [comment]
请提供 Chrome 的版本以及问题 Gif 的截图。

**Comment by afc163** [comment]
I will reopen it if you provide more information.
