### ISSUE TITLE
Exposing interface

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#6861]
### What problem does this feature solve?
Interfaces should be exposed. For example, I have no way to import the `option` interface in `getFieldDecorator(id, option)`, which was declared in `Form.d.ts` (`WrappedFormUtils`). It should be exposed so that I could import it through `import { WrappedFormUtils } from 'antd'`.

### What does the proposed API look like?
FYI

**Comment by djyde** [comment]
Real world example: https://github.com/mobxjs/mobx/blob/master/src/mobx.ts

**Comment by afc163** [comment]
Duplicate of #6593
