### ISSUE TITLE
I hope you can add a function that can add, delete, and at the same level nodes and sub - level nodes, thank you

### ISSUE THREAD

**Issue by zhouhaipeng623** [ant-design/ant-design#6864]
### What problem does this feature solve?
没到题目都分为好多级知识点，在录入每道题的解析的时候都会添加一级知识点，二级知识点，二操作人员有时候也会填错，需要删除重新填写，所以催生了这么一个需求，而现在antd还不支持这个功能，所以我还需要引入其他的库来解决，希望antd可以支持这个需求。

### What does the proposed API look like?
鼠标滑过的时候显示添加和删除的标签

**Comment by afc163** [comment]
You can create the High order component from TreeNode for customized needs, it is not appropriate to do it in antd. http://react-component.github.io/tree/examples/basic.html
