### ISSUE TITLE
应该没有Table的树组件吧，就是可以显示表格层级的组件。

### ISSUE THREAD

**Issue by wefiy** [ant-design/ant-design#687]
应该没有Table的树组件吧，就是可以显示表格层级的组件。希望增加上

**Comment by XUGAOBO** [comment]
我现在也发愁,我做了个测试,table组件能识别树形的数据,会自动分好级,但是没有层次感

**Comment by wefiy** [comment]
就是啊，为嘛没做出来层次啊

**Comment by benjycui** [comment]
等 0.11.x 发布就可以用了 https://github.com/ant-design/ant-design/commit/9ef865e25e44f61f76e36ab3d52073b43cd76cde
