### ISSUE TITLE
Add Feature to auto focus/open dropdown & Select options

### ISSUE THREAD

**Issue by taqimustafa** [ant-design/ant-design#6873]
### What problem does this feature solve?
Most of the time we need to display the dropdown/Select option to be auto focused. But there is no option to achieve that.

https://github.com/JedWatson/react-select

Similar to this one, see autofocus & openOnFocus property.

### What does the proposed API look like?
```
<Select
  allowClear={this.props.allowClear}
  value={this.props.value}
  autofocus
  openOnFocus
  ...
>
   ...       
</Select>
```

**Comment by afc163** [comment]
trace #3790

**Comment by MiroslavPetrik** [comment]
Ant uses rc-select underneath. You can use `showAction="focus"` prop to open the select when it gain's focus.

**Comment by zakangelle** [comment]
@MiroslavPetrik Thanks for pointing this out. I'm curious why this `showAction` prop isn't documented in the [Ant Select documentation](https://ant.design/components/select/). Are some props of rc-select not officially supported by Ant Select?

I'm not sure if this is already documented somewhere in the Ant documentation, but I think at the very least an indication that rc-select is the component used under the hood (with a link to rc-select docs) would be useful. Thoughts?

**Comment by divyanshu013** [comment]
I think this should definitely be added to the docs.

**Comment by dogahasdemir** [comment]
I wanted to use this feature to enable typing into a select field when moving between fields in a for with Tab button.In fact worked but using mouse  click instead of Tab started not working properly(hardly you can find a space in select box that enables you type otherwise you can not type into the field).
Is there any solution for this that anyone came up?

**Comment by mti5914** [comment]
`<Select showSearch showAction={['focus', 'click']} />`
In IE 11, the **Select** cannot be closed when it get focus. If I remove '**focus**', it works correctly.
Is there any ideas on this?

**Comment by ChuckJonas** [comment]
If I try to use the `showAction the behavior gets really inconsistent. It sometimes opens when I click the arrow and sometimes it flashes and then closes immediately

**Comment by adams-family** [comment]
Very interesting! I like this feature, however, I don't find it documented anywhere. Isn't it supported?
