### ISSUE TITLE
如何在输入input表单时，自动把首尾空格去除?

### ISSUE THREAD

**Issue by deepred5** [ant-design/ant-design#6875]
input默认会把首尾空格也算在内，需求希望把首尾空格去除后再传到后台。
现在想到的方法是：在最后提交数据的时候，手动把每个字符串tirm()一下，然后再提交，感觉这样很麻烦，官方文档好像也没提供接口，可以在用户输入表单的时候，先对表单的值进行加工，然后再保存

**Comment by chenchong0215** [comment]
I solved it like this       https://www.cnblogs.com/97Coding/p/14875100.html
