### ISSUE TITLE
Compressed js files contains Chinese characters After bundling js files with webpack2

### ISSUE THREAD

**Issue by wwgc** [ant-design/ant-design#6876]
### Version
2.12.1

### Environment
webpack2

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/modal/locale.tsx](https://github.com/ant-design/ant-design/blob/master/components/modal/locale.tsx)

### Steps to reproduce
Set default language to en_US with LocaleProvider tag .
After bundling js files with webpack2, found some Chinese characters in Compressed js files:
```
   function o(e) {
        u = e ? (0, l.default)({}, u, e) : (0, l.default)({}, s)
    }

    function r() {
        return u
    }

    Object.defineProperty(t, "__esModule", {value: !0});
    var i = n(1), l = a(i);
    t.changeConfirmLocale = o, t.getConfirmLocale = r;
    var s = {okText: "确定", cancelText: "取消", justOkText: "知道了"}, u = (0, l.default)({}, s)
}
```

### What is expected?
Compressed js files just contain language characters, setting in LocaleProvider.

### What is actually happening?
file: components/modal/locale.tsx 
desc: defaultLocale is set to Chinese characters.
```
const defaultLocale = {
  okText: '确定',
  cancelText: '取消',
  justOkText: '知道了',
};
```

**Comment by afc163** [comment]
You don't show any real question in this issu. What the problem?

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us.

**Comment by benjycui** [comment]
Chinese is the default language now, so it must be included in built file.

**Comment by hoorace** [comment]
bad message that use Chinese to default language
