### ISSUE TITLE
带addonBefore或addonAfter或prefix或suffix的Input或导致某些样式出错

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#6877]
### Version
2.12.1

### Environment
测试使用的是chrome

### Reproduction link
[https://codepen.io/vipcxj/pen/owRWeK?editors=001](https://codepen.io/vipcxj/pen/owRWeK?editors=001)

### Steps to reproduce
见重现链接

### What is expected?
重现链接中的代码基本复制于官方Input的输入框组合Demo中第7个，官方demo通过设置style，隐藏了第二个组件的左右边框，直接照搬官方demo也确实是这个效果。然而一旦为任意一个Input加上addonBefore或addonAfter或prefix或suffix属性，官方demo中的样式设置就无效了。

### What is actually happening?
有中间那条竖线

---
经过浏览器调试，基本查明原因。一旦带addonBefore或addonAfter或prefix或suffix属性后，Input组件实际渲染结果会在input标签外包一层span标签，所有传给Input的style直接体现在span上，而input上的style为空，强行给input加上style，就可以修复这个bug

**Comment by afc163** [comment]
这个只能自行定制了，没有完美的解决方案，style 应该加到最外层的容器上。不然宽度、边距之类的设定会有问题。
