### ISSUE TITLE
Property 'value' does not exist on type 'EventTarget'.

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#6879]
### Version
2.12.1

### Environment
macOS 10.12.5

### Reproduction link
[https://github.com/tylerlong/react-antd-ts-test](https://github.com/tylerlong/react-antd-ts-test)

### Steps to reproduce
git clone https://github.com/tylerlong/react-antd-ts-test

yarn install

yarn build

### What is expected?
It should build without issue

### What is actually happening?
➜  react-antd-ts-test git:(master) ✗ yarn build
yarn build v0.27.5
$ webpack

[at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /Users/tyler.liu/src/ts/react-antd-ts-test/tsconfig.json.

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
Hash: 4597b17976d62492738d
Version: webpack 3.3.0
Time: 9341ms
        Asset     Size  Chunks                    Chunk Names
    bundle.js  3.67 MB       0  [emitted]  [big]  main
bundle.js.map  3.83 MB       0  [emitted]         main
  [28] (webpack)/buildin/global.js 509 bytes {0} [built]
 [120] (webpack)/buildin/module.js 517 bytes {0} [built]
 [396] ./src/index.tsx 334 bytes {0} [built]
 [503] ./node_modules/moment/locale ^\.\/.*$ 2.79 kB {0} [optional] [built]
 [790] (webpack)/buildin/amd-options.js 82 bytes {0} [built]
      909 hidden modules

ERROR in [at-loader] ./src/components/Hello.tsx:15:78
    TS2339: Property 'value' does not exist on type 'EventTarget'.
error Command failed with exit code 2.

---
When I am writing an app in JS, there is no problem. But it doesn't work if I change the project to TS.

```
<Input onChange={(event) =>  this.setState({ value: event.target.value })}/>
```

The error says `event.target` doesn't have a property named `value`, which is weird.

**Comment by benjycui** [comment]
How about:

```tsx
<Input onChange={(event: Event) =>  this.setState({ value: event.target.value })}/>
```

**Comment by tylerlong** [comment]
@benjycui  It already auto figures out the type, so I don't think it is necessary to specify the type.

I can specify the type as `any` to eliminate the error. But then what's the point of TS?

**Comment by infeng** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12239

**Comment by tylerlong** [comment]
@infeng, I am confused.

According to https://github.com/facebook/react/pull/9279 there is no problem using `event.target.value`.

According to this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14028 types issues has already been fixed in upstream.

Could it be antd's bug?

**Comment by tylerlong** [comment]
This does NOT work:

```
<Input onChange={(event) =>  this.setState({ value: event.target.value })}/>
```

This DOES work:

```
<input onChange={(event) =>  this.setState({ value: event.target.value })}/>
```

Could we change antd Input component so it behaves similarly to React input ?

**Comment by R4TT400** [comment]
A possible solution that worked for me was this.

**text: string = (<HTMLInputElement>var.target).value;**

**Comment by sarink** [comment]
Do you just need to use `currentTarget` instead of `target`?

**Comment by gh-scloutier** [comment]
For my part, only the latter works:

**Comment by kmvan** [comment]
As same as @R4TT400 's code:
`<textarea onChange={({ target }) => this.setState({ value: (target as HTMLTextAreaElement).value })} />` works for `textarea`.

**Comment by viethocle** [comment]
```
reader.onload = (event) => {
        this.url = event.currentTarget;
        this.url = this.url.result
      }
```
this is a tip. but it work! i hope that can help! make live is easyer!

**Comment by rahulii** [comment]
@viethocle thank you.
it works

**Comment by postbird** [comment]
```jsx
    <div>
      <input type="text" value={val} onChange={handleChange} />
      <button onClick={handleClick}>add + </button>
    </div>
```

```javascript
  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setVal(trim(event.target.value));
  };
```

**Comment by manavsharmaprog** [comment]
Good explanation here...
[(https://youtrack.jetbrains.com/issue/WEB-39140)]

**Comment by manavsharmaprog** [comment]
Some more answers here ...
[Link](https://github.com/angular/angular/issues/35293)
