### ISSUE TITLE
`Input` 控件 `autoFocus` 失效

### ISSUE THREAD

**Issue by wuzeru** [ant-design/ant-design#688]

**Comment by benjycui** [comment]
单独使用 `Input` 时，`autoFocus` 是有效的。

但是放进 `Form` 里面的时候，就会先 focus 然后立刻 blur，应该是 re-render 了。

**Comment by wuzeru** [comment]
@benjycui  有解决的方法吗

**Comment by benjycui** [comment]
@wuzeru 你先用着先吧，简单的用例没问题。

不过在 [demo](http://ant.design/components/form/) 中试了下是不行的，还需要时间才能排查出来。

**Comment by benjycui** [comment]
重现不了。。。囧，先关了，有问题再开吧

**Comment by CallMeXYZ** [comment]
Form里autoFocus还是不行啊，虽然可以自己简单实现

**Comment by afc163** [comment]
@CallMeXYZ 能给个重现么

**Comment by CallMeXYZ** [comment]
http://codepen.io/CallMeXYZ/pen/PpvMjq

**Comment by yesmeck** [comment]
`autoFocus`.

**Comment by CallMeXYZ** [comment]
..嗯

**Comment by benjycui** [comment]
@CallMeXYZ actually, your CodePen works fine in Chrome

**Comment by CallMeXYZ** [comment]
@benjycui as @yesmeck  mentioned, `autoFocus` was mispelled as `autofocus`，sry

**Comment by motorguo** [comment]
`autoFocus` 在 CodePen 测试就没问题，在自己环境使用就不行。

郁闷，只能这样：[stackoverflow](http://stackoverflow.com/questions/28889826/react-set-focus-on-input-after-render)
```
componentDidMount() {
   this.nameInput.focus(); 
}

<Input ref={input => this.nameInput = input} />
```

**Comment by CallMeXYZ** [comment]
@motorguo 应该是你的代码问题把，我使用一切正常
