### ISSUE TITLE
when i fold the menu 

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#6882]
### What problem does this feature solve?
when i fold the menu from 'inline' to 'vertical',it always show automaticly,how do i prevent it.and when i unfold the menu from 'vertical' to 'inline',how do i drop the menu automaticly.

### What does the proposed API look like?
no idea

**Comment by benjycui** [comment]
Similar? https://github.com/ant-design/ant-design/issues/5124 https://github.com/ant-design/ant-design/issues/4876

**Comment by afc163** [comment]
Use `inlineCollapsed`: https://ant.design/components/menu/#components-menu-demo-inline-collapsed

**Comment by nai6514531** [comment]
@afc163 the example when it's mode equals  'vertical' ,no style on the icon.and when u choose a sub menu and fold it.'inlnie' mode no change

**Comment by nai6514531** [comment]
@afc163 或者我如何在inline模式下得到openkeys是通过onOpenChange方法得到吗。但是这个方法在失去焦点的时候回openkeys会是空的。并不符合预期

**Comment by afc163** [comment]
可以描述具体点，并给出 codepen。

**Comment by nai6514531** [comment]
我觉得官网可以给出一个更加详细的菜单的例子。比如我现在的需求是
![image](https://user-images.githubusercontent.com/13310359/28346819-e55bc58e-6c65-11e7-8514-c043b65bd562.png)这样的。菜单是只展开父级的。然后折叠的时候第一次是希望不弹出的。
![image](https://user-images.githubusercontent.com/13310359/28346853-1f02295e-6c66-11e7-9f85-d1ac5ca6bbe4.png)而且上图父菜单没有active的样式。然后再次展开菜单的时候是希望自动展开和上次折叠操作同样的。
