### ISSUE TITLE
TreeSelect搜索问题

### ISSUE THREAD

**Issue by linhanyang** [ant-design/ant-design#6886]
在使用 TreeSelect 组件时，开启搜索功能，当搜索匹配到元素时，清空搜索项，因为父节点是disabled状态，所以很多自动合上的项目就展不开了，这个怎么处理。
![image](https://user-images.githubusercontent.com/7603016/28312140-a481be1e-6be4-11e7-8c18-b526eaddf931.png)

**Comment by valleykid** [comment]
Similar to the [issue](https://github.com/react-component/tree/issues/143).

**Comment by valleykid** [comment]
Fixed by [antd@3.3.0](https://github.com/ant-design/ant-design/releases/tag/3.3.0).
