### ISSUE TITLE
TreeView: Disabled TreeNode and its children must not be checked when it's parent is checked

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#6891]
### Version
2.12.1

### Environment
MacOS, Chrome

### Reproduction link
[https://codepen.io/sk_tectus/pen/OgeyLm?editors=0110](https://codepen.io/sk_tectus/pen/OgeyLm?editors=0110)

### Steps to reproduce
-> Build a simple Tree, with some nested TreeNodes
-> Mark one of the child `TreeNodes` with `disabled` and `disableCheckBox`
![image](https://user-images.githubusercontent.com/12829747/28346039-e15e8b74-6c60-11e7-9af4-4f8e689b141e.png)

-> Now, check the parent of this particular TreeNode (in this case, `0-1`)

### What is expected?
Since, the `TreeNode` is disabled, it should not be checked along with all of it's children

### What is actually happening?
The `TreeNode` is checked despite it being set to `disabled`
![image](https://user-images.githubusercontent.com/12829747/28346059-fb362f20-6c60-11e7-9d9d-0d42a2d5fbe9.png)

### Any additional comments?
Please let me know if you need help with any of these TreeView related issues. I'm trying to use it for our application and would be glad to help you guys with a PR.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/LLKGPy?editors=0110

There are something wrong with checkedKeys.

**Comment by afc163** [comment]
Need upgrade dep to `rc-tree@1.6.0`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/455ea58b1076853302abafa20e6d1c2226ff5c8f

**Comment by vryzhova** [comment]
Can I create behavior like **actually happening**  in issue? 
I need **The TreeNode is checked despite it being set to disabled**
