### ISSUE TITLE
表格的横向滚动 新版本没有滚动条

### ISSUE THREAD

**Issue by edwardxyt** [ant-design/ant-design#6892]
### Version
2.12.1

### Environment
chorome

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
npm i 后版本提升就不好使了

### What is expected?
好使啊

### What is actually happening?
不好使啊

**Comment by afc163** [comment]
Please supply enough information. 

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by afc163** [comment]
I will reopen if you provide effective information.
