### ISSUE TITLE
u.ant.design supports https

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#6893]
Then we need to update links in code

**Comment by paranoidjk** [comment]
@benjycui 我们还搞了短链服务么... 我直接用了 google 的 https://github.com/ant-design/ant-design-mobile/commit/7345d803b54d0268f4c0de9438e3ef0715d3fe3c

**Comment by fengmk2** [comment]
可以跟 mobile.ant.design 一样的过程，实现 https://u.ant.design

**Comment by fengmk2** [comment]
已经支持 https，可以 close
