### ISSUE TITLE
是否有可能为Table组件增加属性作用于额外展开行

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#6895]
Version

2.12.1

Environment

chorome

What is expected?

Table组件的expandedRowRender属性用来显示额外的展开行来描诉额外信息，此时是否可以多个属性来隐藏最前面的点击展开的那个+号，然后再多个属性来控制额外信息的位置(在行的上面或者下面)

What is actually happening?
比如想以下图的方式展示一行的额外信息
可以
<Table
    expandedPosition="top"
    showExpanedOperation={false}
   {...otherProps}
/>
![9fbcaaad-6821-4ede-b7c9-a705b940ff2a](https://user-images.githubusercontent.com/15683846/28353657-4c94f8fa-6c8f-11e7-93be-2ae7ecdb2a85.png)

**Comment by afc163** [comment]
Duplicate of #15630
