### ISSUE TITLE
是否有可能为Table组件增加属性作用于额外展开行

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#6896]
### What problem does this feature solve?
Table组件的expandedRowRender属性用来显示额外的展开行来描诉额外信息，此时是否可以多个属性来隐藏最前面的点击展开的那个 号，然后再多个属性来控制额外信息的位置(在行的上面或者下面)

### What does the proposed API look like?
 expandedPosition="top"和 showExpanedOperation={false}属性来控制如下图展示

![9fbcaaad-6821-4ede-b7c9-a705b940ff2a](https://user-images.githubusercontent.com/15683846/28354185-61d74e78-6c91-11e7-8f51-b43ba8e242f1.png)

**Comment by yesmeck** [comment]
你这个看起来就是合并列。

**Comment by zhangchao828** [comment]
@yesmeck 合并列的话第一写起来麻烦，第二这是一行中数据要拆成两行来显示，上面一行合并列，就是非常麻烦，如果能用展开行来做的话会简便很多

**Comment by afc163** [comment]
建议使用合并列来做。

**Comment by yesmeck** [comment]
目前可以用 custom element 来实现 https://codesandbox.io/s/v8ymrynm6y

**Comment by yesmeck** [comment]
用自定义 `components` 实现的例子： https://codesandbox.io/s/xo4j1qk044
