### ISSUE TITLE
Failed prop type: The prop `overlay` is marked as required in `Tooltip`, but its value is `undefined`.

### ISSUE THREAD

**Issue by manjitkumar** [ant-design/ant-design#6897]
### Version
2.12.1

### Environment
Mac OS X, Firefox 54.0.1 64bit, 

### Reproduction link
[http://imgur.com/a/Nxeua](http://imgur.com/a/Nxeua)

### Steps to reproduce
<Tooltip placement="left" title={toolTipText}>
    <Search
        disabled={disableSearch}
        className="top-nav-bar-items"
        placeholder={searchPlaceholder}
        style={{ width: 300 }}
        onSearch={query => console.log(query)}
    />
</Tooltip>

### What is expected?
Tooltip should be apprearing with no warnings.

### What is actually happening?
Tooltip isn't appearing and overlay required prop warning is coming in console where as docs doesn't mention about this prop.

**Comment by manjitkumar** [comment]
I found out the cause of my issue. An `undefined` value was passed into prop `title` but the warning message displayed some other prop name.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by vydimitrov** [comment]
I came across the same issue. Just by adding the `title` prop it solved the problem. Thanks for sharing.

**Comment by aprilandjan** [comment]
Same issue too. The warning message is confusing.
