### ISSUE TITLE
Property 'TreeNode' does not exist on type 'ComponentClass<TreeSelectProps>'

### ISSUE THREAD

**Issue by gRoberts84** [ant-design/ant-design#6898]
### Version
2.12.1

### Environment
Chrome 58.0.3029.110 (64-bit)

### Reproduction link
[https://github.com/gRoberts84/AntD-Locale-Bug](https://github.com/gRoberts84/AntD-Locale-Bug)

### Steps to reproduce
1. git clone https://github.com/gRoberts84/AntD-Locale-Bug
2. cd AntD-Locale-Bug
3. yarn install
4. yarn start

### What is expected?
Code should successfully compile.

### What is actually happening?
Compiler fails with error: `Property 'TreeNode' does not exist on type 'ComponentClass<TreeSelectProps>'`

---
Highly suspect it may be my TypeScript configuration, if so, please advise.

**Comment by bang88** [comment]
Please see https://github.com/ant-design/ant-design/pull/6193 , if not resolve your problem we will have a look.

**Comment by gRoberts84** [comment]
Hey @bang88 

Thanks. Trying to avoid ejecting my CRA based project for simple things like this, however at some point I suppose I will need to (CSS.)

Are there any plans from CRA that you're aware of to support custom babel integrations without having to eject the whole lot?

**Comment by bang88** [comment]
I don't know what do you mean use CSS?

**Comment by gRoberts84** [comment]
@bang88, Sorry, referring to Ant automagically importing CSS for components you're using rather than importing the whole `~antd/dist/antd.min.css` file.

https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import

**Comment by bang88** [comment]
This is an know issue of CRA. don't have a good solution this moment.
