### ISSUE TITLE
Table列下子项问题

### ISSUE THREAD

**Issue by CoderChow1994** [ant-design/ant-design#6900]
我想做这个交易记录，下面有很多行数据，貌似没有这个功能，我就嵌套了个TABLE进去，
{
    title:'交易记录',
    key:'charge',
    render:(text,record)=>{
      return (
        <Table
          columns={chargecolumns}
          dataSource={subjectrechargeItem}
          rowKey={record =>{'charge'+record.id}}
          size="small"
          bordered={true}
          pagination={false}
        />
      )
    }
  }
```
显示如图，但是一直说Key重复了，原因是嵌套Table的columns的key重复了，
```
const chargecolumns=[
    {
      title: '剩余节数',
      dataIndex: 'leftCount',
      key: `leftCount`,
    },
    {
      title: '剩余金额',
      dataIndex: 'balance',
      key: `balance`
    },
    {
      title: '转出节数',
      dataIndex: '',
      key: `outputNumber`,
}]
```
不知怎么解决，或者有没更好的思路
![image](https://user-images.githubusercontent.com/23169397/28359445-cceb9a80-6ca4-11e7-9248-0cccde41c02f.png)

**Comment by xgqfrms-gildata** [comment]
@CoderChow1994

You must be using a `number` as a key's value OR  a string that can be transformed to a number!

# Here is my solution!

https://gist.github.com/xgqfrms-gildata/36be904c705bfe4952122b6d2e63357c
