### ISSUE TITLE
TreeSelect组件在Form下无法清除

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#6902]
### Version
2.12.1

### Environment
windows64 chrome 57.0.2987.133 (64-bit)

### Reproduction link
[https://codepen.io/yesmeck/pen/XgdYaM](https://codepen.io/yesmeck/pen/XgdYaM)

### Steps to reproduce
在TreeSelect组件中选择一条非叶子节点的数据，控制台会打印“触发清空操作”，表明resetFields方法确定是会执行的；
之后点击查看log按钮，打印出TreeSelect的值，可以看到resetFields并没有起作用。

### What is expected?
TreeSelect组件的值被重置，恢复到没有选择数据的情况。

### What is actually happening?
TeeeSelect组件还是显示刚才选择的数据

**Comment by afc163** [comment]
> 之后点击查看log按钮

在你提供的 codepen 里并没有找到 log 按钮。

**Comment by chj-damon** [comment]
@afc163 不好意思，链接贴错了。是这个：
https://codepen.io/chj-damon/pen/ZydydE

**Comment by afc163** [comment]
在你的的例子里操作。

1. 在TreeSelect组件中选择一条非叶子节点的数据。

> 控制台会打印“触发清空操作”

2. 点击查看log按钮

> 打印 undefined。

![1](https://user-images.githubusercontent.com/507615/28397351-aa448ade-6d33-11e7-8029-b6578e3bc412.gif)

和楼主的描述不符。

**Comment by chj-damon** [comment]
@afc163 点击查看log之后打印出了选择的那个非叶子节点的ID，这说明我执行的onSelect方法里面的this.props.form.resetFields(['treeSelect']);并没有生效。因为如果生效了，那么点击查看log按钮看到的才应该是undefined。

**Comment by afc163** [comment]
你看我的 gif，打印出来的是 undefined。

**Comment by afc163** [comment]
1. getFieldDecorator 会使用 onChange 来修改 form 里的值。
2. 先触发了 onSelect，楼主进行了 resetFields 操作。
3. 然后触发了 onChange，又修改了 form 里的值。
