### ISSUE TITLE
<Select> has no default width, while <Input> defaults to 100%

### ISSUE THREAD

**Issue by maxkrieger** [ant-design/ant-design#6904]
### Version
2.12.1

### Environment
Chrome 59 on Mac OS X Sierra

### Reproduction link
[https://codepen.io/a9/pen/WOqPpx](https://codepen.io/a9/pen/WOqPpx)

### Steps to reproduce
Create a `<Select>` element with no `style={{width: x}}` prop.

### What is expected?
It would ideally have the same behavior as `<Input>`, where it fills the parent by default.

### What is actually happening?
It takes the minimum width possible with default padding.

---
It would be nice to have all data entry elements with the same default layout configs.

**Comment by afc163** [comment]
It would be a break change which affect people's layout. So I like to maintain it's orignal way. You can just add `style` prop for Select.

**Comment by ybning** [comment]
This is not perfect！

**Comment by afc163** [comment]
Actually, I consider to give Input a default width other than `100%`.

**Comment by maxkrieger** [comment]
@afc163 That would be even more of a breaking change for people wrapping inputs in `<Col>`s. It's also better usability in my opinion to have `100%`, because then you don't need explicit style for every element in your form, assuming you are using flexbox.

**Comment by kennylbj** [comment]
```100%``` width is best style IMO. 
Hope that it can be resolved in future release.
