### ISSUE TITLE
Dropdown组件里面使用Popconfirm，当浏览器窗口变化时，Popconfirm确认框，位置跑到了最左上角

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#6905]
### Version
2.12.1

### Environment
chrome 58.0.3029.81

### Reproduction link
[https://codepen.io/merlingli/pen/dRxboq](https://codepen.io/merlingli/pen/dRxboq)

### Steps to reproduce
点击dropdown下的子项删除按钮，弹出Popconfirm确认是否删除框，打开F12，确认框位置错位，跑到了浏览器最左上角

### What is expected?
不会错位

### What is actually happening?
错位

---
单独使用popconfirm不会出现此现象，结合Dropdown才会出现此现象

**Comment by afc163** [comment]
Your codepen is not working.

**Comment by afc163** [comment]
因为 Dropdown 默认的行为是点击菜单就关闭。如果希望 MenuItem 里的 Popconfirm 不消失，那么 Menu 自身不能消失。你可能需要自行控制 Dropdown 的 visible 属性。

https://codepen.io/merlingli/pen/zzgxvv?editors=0110

---

另外，弹出层嵌套弹出层不是非常好的交互，建议使用 `Modal.confirm` 来代替 `Popconfirm`。
