### ISSUE TITLE
 popover 在手机上 点击overlay会鼠标穿透，体验很不好，demo也有这问题

### ISSUE THREAD

**Issue by Moredou** [ant-design/ant-design#6908]
### Version
2.12.1

### Environment
chrome

### Reproduction link
[http://779215221@qq.com](http://779215221@qq.com)

### Steps to reproduce
same issue with demo

### What is expected?
popover 点击overlay popover关掉，不会穿透点击overlay后面的元素

### What is actually happening?
 popover 在手机上 点击overlay会鼠标穿透，体验很不好，demo也有这问题

**Comment by afc163** [comment]
Check https://thx.github.io/mobile/300ms-click-delay & https://github.com/ftlabs/fastclick
