### ISSUE TITLE
Allow ReactNode / JSX in Select.Option value label

### ISSUE THREAD

**Issue by zavrick** [ant-design/ant-design#6910]
### What problem does this feature solve?
This allows us to style the options in the select menu.
Eg. Having different colours inside one option.

### What does the proposed API look like?
```
<Select.Option>
  <span>
    <span>
      Option
    </span>
    <span>
      1
    </span>
  </span>
</Select.Option>
```

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/GEVzgP?&editors=001
