### ISSUE TITLE
Input TextArea disabled使用之后css样式问题

### ISSUE THREAD

**Issue by DevilViy** [ant-design/ant-design#6912]
![image](https://user-images.githubusercontent.com/21967852/28453046-fe9029aa-6e27-11e7-8150-e021a78198c3.png)
在最新版本中使用TextArea的disabled属性，目标框手势不是禁止，目标框也未呈现灰色状态

**Comment by benjycui** [comment]
@DevilViy 试下来个 PR？

**Comment by DevilViy** [comment]
![qq20170721-155736-hd](https://user-images.githubusercontent.com/21967852/28454470-01e04ad0-6e2e-11e7-8809-e7422626bbb1.gif)

**Comment by afc163** [comment]
> @DevilViy 试下来个 PR？

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/6858
