### ISSUE TITLE
doubts about 'getFieldDecorator' in 'form'

### ISSUE THREAD

**Issue by Alixiaodian** [ant-design/ant-design#6913]
### Version
2.12.1

### Environment
codepen测试

### Reproduction link
[https://codepen.io/xiaodian516/pen/OgKGpE?editors=0010](https://codepen.io/xiaodian516/pen/OgKGpE?editors=0010)

### Steps to reproduce
Quite confused about the usage of "getFieldDecorator" of "form" after reading the official guidance:
https://ant.design/components/form-cn/. The doc. says we should use "getFieldDecorator" like this:

getFieldDecorator(id, options)

but the examples seem to be like:

getFieldDecorator(id, options)( some dom in formItem)

well I just follow the example to start my form like this:
https://codepen.io/xiaodian516/pen/OgKGpE?editors=0010

This is exactly the example from the document. I made one change:  defined a const test to return some dom, and set the const into getFieldDecorator. Then it does not work.

what's wrong?

### What is expected?
form works

### What is actually happening?
not working

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/gRVyNQ?editors=0010

You should learn ES2015 and React first.
