### ISSUE TITLE
table   I hope I don't have to write rowKey

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#6914]
### What problem does this feature solve?
The interface has no key, I need to write it like this  
```
                           rowKey={(record, index) => index}

```

### What does the proposed API look like?
I want to use index by default when I don't write rowKey

**Comment by afc163** [comment]
Nope, Table without rowKey or using index as rowKey may cause strange bugs, it is not recommended way. So we won't treat this as default behavious.
