### ISSUE TITLE
表单输入框大小样式失效

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#692]
- 问题: 使用 antd 0.10.4, 设置输入框的大小不起作用
- 源代码: 
  ```
  <Form>
    <FormItem
       label="昨成交额下限："
       >
         <Input size="small"/>
     </FormItem>
  </Form>
  ```
- 效果:
![antd-form-input-size-error](https://cloud.githubusercontent.com/assets/1996891/11837940/e0f36116-a41e-11e5-83a5-89a02745d2cc.png)

**Comment by afc163** [comment]
对，设计规范要求，标准表单中必须使用大号的输入框。

**Comment by zhbhun** [comment]
设计规范在哪里可以参考, 这个只看组件文档的话, 没说明的话, 会很疑惑!

**Comment by afc163** [comment]
部分设计稿在内部，没有开放~
