### ISSUE TITLE
select need reset value when seleced value invaild

### ISSUE THREAD

**Issue by aegisho** [ant-design/ant-design#6921]
### What problem does this feature solve?
when select option change, origin value is invaild，the form validate not work

see dmoe [https://codepen.io/aegisho/pen/OjLxyd?editors=0011](https://codepen.io/aegisho/pen/OjLxyd?editors=0011)

### What does the proposed API look like?
please clean select value

**Comment by afc163** [comment]
Select don't check the value is matched or not. You could check it's validity by yourself.
