### ISSUE TITLE
ES6+ with class mixins 问题

### ISSUE THREAD

**Issue by JiangAmber** [ant-design/ant-design#693]
今天使用validation组件进行表单验证，但是我使用的方式是ES6+ class 的方式 请问如何实现`mixins: [Validation.FieldMixin]`

```jsx
export class InputValidation extends React.Component {
    constructor(props){
      super(props);
      mixins: [Validation.FieldMixin];
    }
}
```
谢谢

**Comment by benjycui** [comment]
不支持，see: https://facebook.github.io/react/docs/reusable-components.html#no-mixins

**Comment by gdzgshum** [comment]
有什么解决的办法吗？

**Comment by benjycui** [comment]
需要 mixins 的时候，用回 `React.createClass` 吧

**Comment by JiangAmber** [comment]
请问下一个版本会把`mixins` 丢弃掉吗，毕竟官方已经不推荐了，换成class继承的方式
