### ISSUE TITLE
Need to be translated

### ISSUE THREAD

**Issue by pierreneter** [ant-design/ant-design#6931]
# Need to be translated
This issue was created to list the documents that need to be translated or updated, maybe me or you will help translate these documents into English.
> This article has not been translated, hope that your can PR to translated it.

See more about calling for help: #1471 (Chinese to English).

**Note**
* You must rename a main Chinese file `{name}.md` to `{name}.zh-CN.md` then create a file: `{name}.en-US.md` and save the translation into the `en-US` file.
_**Example:**_ `font.md` to be `font.zh-CN.md` and the translation save as `font.en-US.md`
* While you are translating, please edit the meta information.
_**Example:**_
```
---
order: 6
title:
  zh-CN: 文案
  en-US: Copywriting
---
```
become:
```
---
order: 6
title: 文案
---
```
In the `.zh-CN.md` file, and:
```
---
order: 6
title: Copywriting
---
```
In the `.en-US.md` file.

---

## Guidelines
- [x] https://ant.design/docs/spec/font (need translate) [[docs/spec/font.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/font.md)] @picodoth
- [x] https://ant.design/docs/spec/navigation (need translate) [[docs/spec/navigation.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/navigation.md)] @zachguo 
- [x] https://ant.design/docs/spec/data-entry (need translate) [[docs/spec/data-entry.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/data-entry.md)]
- [x] https://ant.design/docs/spec/data-display (need translate) [[docs/spec/data-display.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/data-display.md)]
- [x] https://ant.design/docs/spec/feedback (need translate) [[docs/spec/feedback.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/feedback.md)]
- [x] https://ant.design/docs/spec/layout (need translate) [[docs/spec/layout.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/layout.md)]
- [x] https://ant.design/docs/spec/overview (need translate) [[docs/spec/overview.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/overview.md)]
- [ ] https://ant.design/docs/spec/copywriting (need translate) [[docs/spec/copywriting.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/copywriting.md)]
- [x] https://ant.design/docs/spec/visual (need translate) [[docs/spec/visual.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/visual.md)]
- [x] https://ant.design/docs/spec/motion (need translate) [[docs/spec/motion.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/motion.md)]

## Components
All translated.
Need updates.

## Patterns

@zachguo undertake.

- [x] https://ant.design/docs/pattern/navigation (need translate) [[docs/pattern/navigation.md](https://github.com/ant-design/ant-design/blob/master/docs/pattern/navigation.md)] @zachguo 
- [x] https://ant.design/docs/pattern/form (need translate) [[docs/pattern/form.md](https://github.com/ant-design/ant-design/blob/master/docs/pattern/form.md)] @shenlin192 
- [x] https://ant.design/docs/pattern/list (need translate) [[docs/pattern/list.md](https://github.com/ant-design/ant-design/blob/master/docs/pattern/list.md)]
- [ ] ~~https://ant.design/docs/pattern/table (need translate) [[docs/pattern/table.md](https://github.com/ant-design/ant-design/blob/master/docs/pattern/table.md)]~~
- [ ] ~~https://ant.design/docs/pattern/complex-table (need translate) [[docs/pattern/complex-table.md](https://github.com/ant-design/ant-design/blob/master/docs/pattern/complex-table.md)]~~

### Punctuation mark
Moving Chinese to English punctuation in `en_US` files.
Example: `。` become `.`, `『abc』` become `"abc"`, etc...

## Notice
If you've just edited the document no matter what language, leave a comment here so people can update the same content for the other languages. (i will add it to above list).

**Comment by pierreneter** [comment]
@afc163 @benjycui Do we also need to replace the Chinese photos into English photos?

**Comment by zachguo** [comment]
This should be added to #1471 's `Contributing` section.

**Comment by afc163** [comment]
@pierreneter no for now.

**Comment by zachguo** [comment]
I'll take over rest of `Patterns`.

**Comment by benjycui** [comment]
ping~

**Comment by zachguo** [comment]
@benjycui thx for reminding me

**Comment by kirkins** [comment]
Hi, +1 for English translation of this page.

https://ant.design/docs/spec/data-entry

**Comment by awwmeow** [comment]
i can help translate [visualization](https://ant.design/docs/spec/visual) or [copywrighting](https://ant.design/docs/spec/copywriting)

**Comment by balloonio** [comment]
Hi, I'd love to translate the Motion Guideline

**Comment by zy410419243** [comment]
https://ant.design/docs/spec/icon (need update) [[docs/spec/icon.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/icon.en-US.md)]

https://ant.design/docs/spec/work-with-us (need remove?)[[docs/spec/work-with-us.en-US.md](https://github.com/ant-design/ant-design/blob/master/docs/spec/work-with-us.en-US.md)]

**Comment by balloonio** [comment]
Ping. Reviewer needed for #14756

**Comment by dj1109** [comment]
Bii

**Comment by jljsj33** [comment]
[Motion doc](https://github.com/ant-design/ant-motion/issues/204) and [landing doc](https://github.com/ant-design/ant-design-landing/issues/1) need help.

**Comment by klouskingsley** [comment]
@awwmeow Are you still working at [copywriting](https://ant.design/docs/spec/copywriting)? If not, I can take over that and [feedback](https://ant.design/docs/spec/feedback).

**Comment by afc163** [comment]
Only https://ant.design/docs/spec/copywriting is not translated now.

**Comment by VitorGultzgoff** [comment]
Actually it's not _mandatory_ to understand completely the concepts involved, but would not be **useful** in _didactic_ terms in case of someone edit/translate the image of [Framework Informations - Overview - Ant Design](https://ant.design/docs/spec/overview#Framework-Information) ?

**Comment by afc163** [comment]
@VitorGultzgoff Of cause

**Comment by NitroBAY** [comment]
@dchan3 said he would do the copywriting thing but he doesn't seem to. @klouskingsley fork is also unmodified. Is anyone doing it ? I would love reading it (I don't speak chinese)

**Comment by dchan3** [comment]
@NitroBAY, I just did an initial commit on my fork.

**Comment by pierreneter** [comment]
@NitroBAY, https://github.com/dchan3/ant-design/commits/translation-copywriting is this your meaning, right? @dchan3

**Comment by dchan3** [comment]
@pierreneter Yes, that is what I mean.

**Comment by NitroBAY** [comment]
Yes @pierreneter thanks so muchhhh to @dchan3 thanks for this work.
I'm surprised that your project which seem so huge and have a paid version still have an untranslated document. In French we would probably directly write everything in English (obviously I'm not complaining I love this project, I want to stop using material design because it's not web oriented at all and not exhaustive about interactions on the web. Your framework is what we all needed !)

**Comment by say25** [comment]
Any update on `copywriting`? any reason to not merge down @dchan3's start as it only adds English?

**Comment by afc163** [comment]
- [ ] https://ant.design/docs/spec/data-format
- [ ] https://ant.design/docs/spec/copywriting
- [ ] https://ant.design/docs/spec/buttons
- [ ] https://ant.design/docs/spec/visualization-page
- [ ] https://ant.design/docs/spec/detail-page
- [ ] https://ant.design/docs/spec/illustration

**Comment by hoho2017** [comment]
q
