### ISSUE TITLE
The installation and cloning code does not match

### ISSUE THREAD

**Issue by onlinelemon** [ant-design/ant-design#6936]
### Version
2.12.2

### Environment
win7、chrome@latest

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
1、npm install antd@latest  Own file node_modules\antd\lib\menu\style\css.js
2、clone antd  Then npm run compile
Missing file antd\lib\menu\style\css.js

### What is expected?
clone antd  Then npm run compile 
Own file antd\lib\menu\style\css.js

### What is actually happening?
clone antd  Then npm run compile
Missing file antd\lib\menu\style\css.js

---
1、npm install antd@latest 【node_modules\antd\lib\menu\style\**】
2、clone antd  Then npm run compile【antd\lib\menu\style\**】
Why not?

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/28507341-ba65c156-7064-11e7-9d6b-b604fbcb50c2.gif)

> clone antd Then npm run compile Missing file antd\lib\menu\style\css.js

It it not missing.

**Comment by onlinelemon** [comment]
###Environment
win7、antd@latest

Is it related to the operating system?

**Comment by afc163** [comment]
Any errors when you run `npm run compile`?

**Comment by onlinelemon** [comment]
There is no mistake.

**Comment by afc163** [comment]
Is it same logs like the gif I posted?

**Comment by onlinelemon** [comment]
Exactly the same, `npm run dist ` has error, It shouldn't matter.

**Comment by onlinelemon** [comment]
antd\lib\menu\style\ Missing index.css
antd\lib\menu\style\ Missing css.css

`
//antd-tools run compile
//gulpfile.js
function compile(modules) {
  rimraf.sync(modules !== false ? libDir : esDir);
  const less = gulp.src(['components/**/*.less'])
    .pipe(through2.obj(function (file, encoding, next) {
      this.push(file.clone());
      if (file.path.match(/\/style\/index(\.web)?\.less$/)) {
        transformLess(file.path).then((css) => {
          file.contents = new Buffer(css);
          file.path = file.path.replace(/\.less$/, '.css');
          this.push(file);
          next();
        }).catch((e) => {
          console.error(e);
        });
      } else {
        next();
      }
    }))
    .pipe(gulp.dest(modules === false ? esDir : libDir));
  const assets = gulp.src(['components/**/*.@(png|svg)']).pipe(gulp.dest(modules === false ? esDir : libDir));
  let error = 0;
  const source = [
    'components/**/*.tsx',
    'typings/**/*.d.ts',
  ];
  // allow jsx file in components/xxx/
  if (tsConfig.allowJs) {
    source.unshift('components/**/*.jsx');
  }
  const tsResult = gulp.src(source).pipe(ts(tsConfig, {
    error(e) {
      tsDefaultReporter.error(e);
      error = 1;
    },
    finish: tsDefaultReporter.finish,
  }));

  function check() {
    if (error && !argv['ignore-error']) {
      process.exit(1);
    }
  }

  tsResult.on('finish', check);
  tsResult.on('end', check);
  const tsFilesStream = babelify(tsResult.js, modules);
  const tsd = tsResult.dts.pipe(gulp.dest(modules === false ? esDir : libDir));
  return merge2([less, tsFilesStream, tsd, assets]);
}`

**Comment by afc163** [comment]
I am going to close this cause we don't provide official support for developing in windows.You could still dig into it and help us to fix it.
