### ISSUE TITLE
Can I use Jsonp in Uploader?

### ISSUE THREAD

**Issue by StarryF** [ant-design/ant-design#6939]
### What problem does this feature solve?
I need use the upload with jsonp, but I don't find the api of this

### What does the proposed API look like?
can use the upload with jsonp

**Comment by yesmeck** [comment]
No, you can't. You need POST to upload a file, but you can't POST using JSONP.

**Comment by StarryF** [comment]
那就是说，我要在上传组件里用jsonp的请求上传图片是不行的咯？

**Comment by yesmeck** [comment]
不行。

**Comment by StarryF** [comment]
继续请教一下，已经将接口改成crossdomain的了，jQuery调用可以使用。但是放在上传组件里，已经配置了headers，仍然不行是为什么？
```
headers: {
          'Access-Control-Allow-Origin': '.baidu.net' || '.baidu.com',
          'Access-Control-Allow-Methods': 'GET, POST',
          'Access-Control-Allow-Credentials': 'true'
        },
```

**Comment by StarryF** [comment]
请教一下 http://jsonplaceholder.typicode.com/posts/这个接口是如何实现的，这里跨域上传就一点问题都没有呢？ @yesmeck

**Comment by yesmeck** [comment]
建议到 SegmentFault 上提问
