### ISSUE TITLE
请问TreeSelect中的属性treeDataSimpleMode的作用和用法？

### ISSUE THREAD

**Issue by Evoque** [ant-design/ant-design#6940]
### What problem does this feature solve?
不明白这个功能是干嘛的， 按照提示信息进行了尝试， 依然没有试出来

### What does the proposed API look like?
希望能给予解答

**Comment by benjycui** [comment]
Search `treeDataSimpleMode` in http://react-component.github.io/tree-select/examples/basic.html

**Comment by Evoque** [comment]
thx, I will do that next time.

**Comment by ergoulee** [comment]
treeDataSimpleMode: { rootPId:0}  //根节点
const treeData = [
  {id:1, pId:0, value:'11', label:"test11"},  //父节点
  {id:2, pId:0, value:'12', label:"test12"},
  {id:3, pId:0, value:'13', label:"test13"},
  {id:11, pId:1, value:'21', label:"test21"},  //子节点
  {id:12, pId:2, value:'22', label:"test22"},
  {id:13, pId:3, value:'23', label:"test23"},
];

**Comment by blankzust** [comment]
hi.Could you please tell me how to set key for every node?
![image](https://user-images.githubusercontent.com/8541906/40344171-2e036196-5dc6-11e8-8114-164611e5a1cd.png)
@ergoulee

**Comment by blankzust** [comment]
This is my treeData:
![image](https://user-images.githubusercontent.com/8541906/40344259-905d8060-5dc6-11e8-9a94-8e5a364389c0.png)

**Comment by blankzust** [comment]
The version is 
```
"antd": "^2.6.0",
```
