### ISSUE TITLE
ie9 Responsive layout works wrong

### ISSUE THREAD

**Issue by zhjin024399** [ant-design/ant-design#6946]
### Version
2.12.2

### Environment
win10 IE9 

### Reproduction link
[https://ant.design/components/layout/#components-layout-demo-responsive](https://ant.design/components/layout/#components-layout-demo-responsive)

### Steps to reproduce
IE9 打开链接就能重现

### What is expected?
样式正常

### What is actually happening?
左右布局变为上下布局

**Comment by afc163** [comment]
Layout component is using Flex so it is not supported in IE9.

https://ant.design/components/layout/#Component-Overview

**Comment by chengwangping** [comment]
@zhjin024399 
ie9 兼容layout 布局
![image](https://user-images.githubusercontent.com/5220595/29657718-1956444e-88eb-11e7-9658-6fcae250b66b.png)

**Comment by afc163** [comment]
@chengwangping 👍，来个 PR 如何？

**Comment by chengwangping** [comment]
可以
