### ISSUE TITLE
Docs: function signature breaks due to "|" character

### ISSUE THREAD

**Issue by newswim** [ant-design/ant-design#6947]
### Version
2.12.2

### Environment
MacOS, Chrome 59

### Reproduction link
[http://imgur.com/a/kJjeM](http://imgur.com/a/kJjeM)

### Steps to reproduce
Go to https://ant.design/components/pagination

### What is expected?
The function definition should not break over multiple table columns.

### What is actually happening?
It does.

---
This seems to occur on both EN and CN pages. I think a simple fix is escaping the characters.

 eg. `\|`

I'm happy to submit a PR 😄

**Comment by afc163** [comment]
PR is welcome~
