### ISSUE TITLE
Dropdown menu will disappear if I hover menu before menu showed itself completely

### ISSUE THREAD

**Issue by dwb1994** [ant-design/ant-design#6949]
### Version
2.12.2

### Environment
chrome

### Reproduction link
[https://ant.design/components/dropdown/](https://ant.design/components/dropdown/)

### Steps to reproduce
hover the title "</a>", if I hover menu before menu showed itself completely( in a very short time ), the menu will disappear.

### What is expected?
hover the title "</a>", if I hover menu before menu showed itself completely( in a very short time ), the menu will not disappear.

### What is actually happening?
the menu will disappear

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/6314

**Comment by benjycui** [comment]
ad92793 cc @afc163 

1. When an element is going to show, events should work.
1. When an element is going to disappear, events should not work.
