### ISSUE TITLE
The imported Antd component override the local scope variable

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#6951]
### Version
2.12.2

### Environment
MacOS 10.11.6

### Reproduction link
[https://github.com/zheeeng/antd-admin/compare/b2b0aa872f36c228054c1a4d0d8f61a3c4f35b24...777af9d3b0a86e1f3de0eed1443498ee7ec366c1](https://github.com/zheeeng/antd-admin/compare/b2b0aa872f36c228054c1a4d0d8f61a3c4f35b24...777af9d3b0a86e1f3de0eed1443498ee7ec366c1)

### Steps to reproduce
It happens in projects which are built by webpack and can't be reproduced in Codepen. So I forked the antd-admin project and made the reproduction. You could check it by running this project or read the modifications below:

The core part:
```
// file-path: antd-admin/src/index.js

import './index.html'
import 'babel-polyfill'
import dva from 'dva'
import createLoading from 'dva-loading'
import { browserHistory } from 'dva/router'
import { message } from 'antd'

import React from 'react'
import ReactDom from 'react-dom'

const testFunc = () => {
  const message = `rewritten message`
  const arr = [{
    message: `I'm string message, not component!`,
    dva: `I'm string dva`,
    createLoading: `I'm string createLoading`,
    browserHistory: `I'm string browserHistory`,
    React: `I'm string React`,
    ReactDom: `I'm string ReactDom`
  }]
  /* Unexpted value of res.
   * The 'res.message' isn't string type.
   * If you console.log the 'message' in 'console.log', the 'message' is the correct value 'I am string message, not component!'. 
   * /
  const res = arr.map(
    ({ message, dva, createLoading, browserHistory, React, ReactDom }) => ({ message, dva, createLoading, browserHistory, React, ReactDom })
  )
  console.log(res)
}

testFunc()
``` 

Be noticed, the imported the `message` component(no matter what else Antd component), changed the expected behavior in the es6 short properties syntax. The property which has the same property name with Antd component (just like the `message`), has the correct key -- `message`, but the value is overrided by the the Antd component not the expected string `I'm string message, not component!`. Just like the screenshot:

![image](https://user-images.githubusercontent.com/1303154/28557528-8a697958-713f-11e7-9195-d15397d56ec7.png)

Even I re-assigned the value to a local variable `message` with `rewritten message`, it doesn't change the `message`'s value.

**With the reason that this situation only happens on Antd component, not other modules were written by myself, imported by another third libs, I come up this issue here.**

### What is expected?
the res[0] should be:
```
{
  React: "I'm string React",
  ReactDom: "I'm string ReactDom",
  browserHistory: "I'm string browserHistory",
  createLoading: "I'm string createLoading",
  dva: "I'm string dva",
  message: "I'm string message, not component!"
}
```

### What is actually happening?
res[0].message is the Antd-Component

**Comment by yesmeck** [comment]
Actually, it's [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)'s bug.

**Comment by zheeeng** [comment]
@yesmeck Yeah, I thought it's may be caused by babel plugin, I tried many methods but I can't reproduce this situation apart from Antd component, doesn't any pack tech antd used triggers this bug?

**Comment by yesmeck** [comment]
Related https://github.com/ant-design/babel-plugin-import/issues/127

**Comment by zheeeng** [comment]
@yesmeck I came up this issue in https://github.com/ant-design/babel-plugin-import, you can close this issue as pleasure.
