### ISSUE TITLE
分页器Pagination如何显示中英文pagesize自定义文字

### ISSUE THREAD

**Issue by JarVan007** [ant-design/ant-design#6952]
每页几条，一共多少条都是可以设置中英文的，请问pagesize中怎么设置中英文？

【50条/页】 跳至【】页   就这个地方怎么自定义？文档中没有找到，求大神解答，谢谢～

**Comment by JarVan007** [comment]
50条/页】 跳至【】页 =》 【5/page】 goto 【】  请问这个地方怎么设置呢？

**Comment by yesmeck** [comment]
https://ant.design/components/locale-provider/#components-locale-provider-demo-basic
