### ISSUE TITLE
ask for advice about a a question such as(0,function)

### ISSUE THREAD

**Issue by xumin2015** [ant-design/ant-design#6954]
### Version
2.12.2

### Environment
系统版本

### Reproduction link
[https://github.com/ant-design/ant-design＃node_modules/dora-plugin-webpack/lib/index.js](https://github.com/ant-design/ant-design＃node_modules/dora-plugin-webpack/lib/index.js)

### Steps to reproduce
hello ,my ant design version is 1.1.0,when i watch some code I see a lot of codes such as "webpackConfig = (0, _getWebpackCommonConfig2.default)(this)",but it just like _getWebpackCommonConfig2.default(this),what's the differents of both formats？
您好，我用的是1.10版本，我看其中的打包程序，有很多类似的写法，如webpackConfig = (0, _getWebpackCommonConfig2.default)(this);这个函数的运行结果和_getWebpackCommonConfig2.default(this)不应该是一样的吗？(0,function)这样的写法有什么特殊的含义吗？

### What is expected?
learn about the meaning of code format such as (0,function);
希望了解(0,function)的用法

### What is actually happening?
its the first time I see these format and I dont know it's meaning.
查阅相关资料但不是很理解这样的用法

---
node_modules/dora-plugin-webpack/lib/index.js ：its the path the code format appears.
那个重现链接＃前面可不看，后面是出现的文件地址。

**Comment by afc163** [comment]
It is not related to antd, I suggest you ask it in stackoverflow.

**Comment by xumin2015** [comment]
@ant-design-bot @afc163 thanks!
