### ISSUE TITLE
AutoComplete opens up

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#6956]
### Version
2.9.3

### Environment
Chrome 59.0

### Reproduction link
[https://codepen.io/froston/pen/dzPWXW](https://codepen.io/froston/pen/dzPWXW)

### Steps to reproduce
I have two `AutoComplete` components next to each other. Options of the second one depend on the first one's value. After selecting the value of the first one, there is an ajax call which returns and sets data for the second one. In callback of the ajax call I use `setState()`.

### What is expected?
After selecting value of the first `AutoComplete` it will close the option's pop-up, set the data of the second one and won't pop up again.

### What is actually happening?
After selecting value of the first `AutoCompelte`, it closes the option's pop-up but after setting state in the ajax call callback (in the example: `setTimeout 500ms`) it opens up again the pop-up.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/6600

Try latest version of antd and reinstall node_modules.
