### ISSUE TITLE
Dynamic form like dynamic input

### ISSUE THREAD

**Issue by rbtsolis** [ant-design/ant-design#6957]
### What problem does this feature solve?
When we need many forms example to create multiple prices with name and them are a multiple relation, in this case is similar to django to add multiple values or forms, its called "Django inline forms"

### What does the proposed API look like?
Its similar to the dynamic input but in this case is "Dynamic form" to add or delete form

**Comment by benjycui** [comment]
How about this? https://ant.design/components/form/#components-form-demo-dynamic-form-item

**Comment by rbtsolis** [comment]
No, its not dynamic field, is the entire and multiple forms, for example to add multiple prices to the service

**Comment by afc163** [comment]
I don't understand what is multiple forms. You could just create forms as much as you want.

**Comment by benjycui** [comment]
According to me, it's just one form with several dynamic form items.
