### ISSUE TITLE
wrapped DatePicker used in Form with rules

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#6961]
### Version
2.12.2

### Environment
antd 2.12.2

### Reproduction link
[https://codepen.io/CallMeXYZ/pen/rzaQvY?editors=1111](https://codepen.io/CallMeXYZ/pen/rzaQvY?editors=1111)

### Steps to reproduce
 wrapping a `DatePicker` as a new Component then used in `Form` with `rules`

### What is expected?
works as a normal `DatePicker`

### What is actually happening?
failed to pick date

**Comment by yesmeck** [comment]
You can not pass a stateless component to getFieldDecorator.

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/commit/8e496966cffa11063636540dd34e581feed3c5d3

**Comment by CallMeXYZ** [comment]
see..but my `React` version is `15.4.2`

**Comment by yesmeck** [comment]
See first note.
