### ISSUE TITLE
consistent style of  `DatePicker.RangePicker` 

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#6963]
### What problem does this feature solve?
unifying disabled style of DatePicker

### What does the proposed API look like?
add  disabled style to `DatePicker.RangePicker` and remove disabled focusing style

**Comment by benjycui** [comment]
It works fine now:

![image](https://user-images.githubusercontent.com/3580607/28606108-e36dc2d4-7207-11e7-8184-0e1dada3c267.png)

Try the latest antd.
