### ISSUE TITLE
The installation and cloning code does not match

### ISSUE THREAD

**Issue by onlinelemon** [ant-design/ant-design#6964]
### Version
2.12.2

### Environment
mac、react@2.12.2

### Reproduction link
[htt://antd](htt://antd)

### Steps to reproduce
1、npm install antd@latest Own file node_modules\antd\dist\antd.less
2、clone antd Then npm run dist
Missing file antd\dist\antd.less

### What is expected?
Own file antd\dist\antd.less

### What is actually happening?
Missing file antd\dist\antd.less

---
Antd font color and border color under Mac, the effect is good, but under windows, the effect is general

**Comment by benjycui** [comment]
You don't need to case about the publish detail. Or you can dig it by yourself.
