### ISSUE TITLE
Rate component selected color change

### ISSUE THREAD

**Issue by RequiemSoul** [ant-design/ant-design#6966]
### What problem does this feature solve?
請問Rate控件可否改變選中的顔色？好像衹有未選中的顔色可改
How to change selected Rate component color? by default it's orange

### What does the proposed API look like?
<Rate selectedColor="#000" />

**Comment by benjycui** [comment]
Override css

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/90511c3261caa36e2da40dacc7767b100171c4e1/components/style/themes/default.less#L326
