### ISSUE TITLE
form中的select组件的数据保存到上层组件,  标签方式展示不出来, 分组方式可以展示

### ISSUE THREAD

**Issue by justkuai** [ant-design/ant-design#6967]
### Version
2.12.2

### Environment
codepen

### Reproduction link
[https://codepen.io/yuechen323/pen/MvYREB](https://codepen.io/yuechen323/pen/MvYREB)

### Steps to reproduce
God组件是上层组件,  Kid中operTypes的数据保存在God中,  用tag方式的select展示都展示不出来, 但是group方式可以

### What is expected?
期望可以展示出来

### What is actually happening?
展示不出来

**Comment by benjycui** [comment]
Your CodePen doesn't work.

**Comment by justkuai** [comment]
@benjycui  刚才一直是loading吗? 现在可以了, 展示的是白板, 因为用到了 tag类型的select组件, 就啥也展示不出来了, 换成group形式的就ok

**Comment by afc163** [comment]
The type of `Select[mode=tags]`'s value is **array**, not a string.

https://codepen.io/afc163/pen/eENNvO?editors=0110
