### ISSUE TITLE
表格记录单选问题

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#697]
1. 使用 rowKey 重新定义表格记录的唯一标识后, 点击某条记录的单选按钮, 所有记录均被选中!
2. 使用单选框来实现表格单选比较奇怪 --- 在表格出现横向滚动条的时候, 必须拖动到最左边才能选中某一条记录, 一般都是点击某一行实现单选.

如图, 表格使用 "代码" 作为记录的唯一标识, 点击某一条记录的单选按钮, 出现全选的情况
![image](https://cloud.githubusercontent.com/assets/1996891/11888522/64f56364-a579-11e5-905c-558b5e56361d.png)

antd 版本: 0.10.4

**Comment by zhbhun** [comment]
如图, 表格使用 "代码" 作为记录的唯一标识, 点击某一条记录的单选按钮, 初选全选的情况
![image](https://cloud.githubusercontent.com/assets/1996891/11888522/64f56364-a579-11e5-905c-558b5e56361d.png)

ant 版本: 0.10.4

**Comment by afc163** [comment]
没有重现呢，看下你的数据和 rowKey 都是什么样的？

能给出重现的例子就更好了：http://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by zhbhun** [comment]
```
/*
const {Datepicker} = antd;

var Hello = React.createClass({
    render() {
        return <div style={{margin:10}}>
        <h1>antd@{antd.version}</h1>
        <Datepicker />
        </div>;
    }
});
 
ReactDOM.render(
    <Hello />,
    document.getElementById('container')
);
*/


const {Table} = antd;

const columns = [{
  title: '姓名',
  dataIndex: 'name',
  render: function(text) {
    return <a href="#">{text}</a>;
  }
}, {
  title: '年龄',
  dataIndex: 'age'
}, {
  title: '住址',
  dataIndex: 'address'
}];
const data = [{
  id: '1',
  name: '胡彦斌',
  age: 32,
  address: '西湖区湖底公园1号'
}, {
  id: '2',
  name: '胡彦祖',
  age: 42,
  address: '西湖区湖底公园1号'
}, {
  id: '3',
  name: '李大嘴',
  age: 32,
  address: '西湖区湖底公园1号'
}];

// 通过 rowSelection 对象表明需要行选择
const rowSelection = {
  type: 'radio'
};

ReactDOM.render(<Table rowSelection={rowSelection} columns={columns} dataSource={data} />
, document.getElementById('container'));
```

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/develop-0.11.0/components/table/index.jsx#L266

这里直接用 `record.key` 了，改下就行。

**Comment by afc163** [comment]
@benjycui 改之。

**Comment by duanbowen** [comment]
rowKey 中的key必须改变，对应在table中的那一行才会显示更改的数据？
