### ISSUE TITLE
Get value of DOM Input node

### ISSUE THREAD

**Issue by Luchanso** [ant-design/ant-design#6970]
### What problem does this feature solve?
I have uncontrolled antd input, and I need to get text value from DOM element because browser plugins like a grammarly modify DOM without firing onChange event

### What does the proposed API look like?
I would like to have the QuickJumper custom function to customize the page number of the display input

**Comment by Luchanso** [comment]
Now I taking value via 
```
this.myElement.refs.input.textAreaRef.value
```

**Comment by afc163** [comment]
I think you can do it by youself. It will be more simple than a custom QuickJumper function.

https://codepen.io/afc163/pen/brddvO?editors=0010

**Comment by Luchanso** [comment]
@afc163 sorry, I missed text from clipboard, and I mean:
### What does the proposed API look like?
```<Input ref={node => console.log(node.value)}/>```

**Comment by Luchanso** [comment]
please reopen

**Comment by Luchanso** [comment]
now I can't take value from input via this.myComponent.value

**Comment by afc163** [comment]
You can trace this problem at https://github.com/ant-design/ant-design/issues/5489

**Comment by afc163** [comment]
I strongly suggest to use controlled input, it is more React.

**Comment by Luchanso** [comment]
@afc163 Thank you, I know about controlled input, but plugins for chrome like a "grammarly" modify input throw document.querySelector('textarea').value = 'blablabla'... and I can't control it in React

**Comment by bluebill1049** [comment]
`I strongly suggest to use controlled input, it is more React.`

What about if you want to `focus` on a specific element? You still need to use `ref` or DOM element query? I think our community is heavily invested in controlled component for form input and validation and made us all believe controlled component is more `React`, but at the end of the day we all using DOM API and manipulate with DOM tree. I don't see much of the issue of exposing `ref` and give us (dev) the freedom to achieve what we want to archive. I am sure it's not React's intention to make everything controlled especially for form and inputs.

**Comment by alanhg** [comment]
> Now I taking value via
> 
> ```
> this.myElement.refs.input.textAreaRef.value
> ```

Error:(86, 91) TS2341: Property 'textAreaRef' is private and only accessible within class 'TextArea'.

**Comment by bluebill1049** [comment]
I still hope one day andt and material-ui will start to expose more components with their `ref` 🤞🏻however, i do understand that's going to be large change accoss the lib and projects contributors have their own prioiries and missions. i will be waiting tho ❤️

**Comment by VladimirTambovtsev** [comment]
Apollo v2.6 use (in official docs)
```node
        <input
          ref={node => {
            input = node;
          }}
        />
```
with hooks. And this is not the only case.

It would be great to use ref in ```<Input />```
