### ISSUE TITLE
New wider padding issue

### ISSUE THREAD

**Issue by inev** [ant-design/ant-design#6973]
### What problem does this feature solve?
New widerPadding issue for cards

### What does the proposed API look like?
It makes it really hard to style the cards and there seems no way we can turn it off. Can we add an option like `disableWidePadding`?

**Comment by benjycui** [comment]
I don't understand, could you provide more info? An online demo or at least a screenshot will be better.

**Comment by topvis** [comment]
@inev Not sure if this is what you need.
```
.ant-card-body {
    padding: 1px;
}
```

**Comment by inev** [comment]
@benjycui I'm specifically talking about this commit https://github.com/ant-design/ant-design/commit/6ffe39145df24394e7b9af6ed45fafc09ffe1310
Earlier it was easy to restyle because there was no variable class names.  Now `.ant-card-wider-padding` is added according to width which makes it harder and more confusing to style.

@topvis That doesn't work because of CSS specificity rules. Under some conditions `.ant-card-wider-padding` is added and the default rules take over. I had it like this before and after the recent update it stopped working,

**Comment by benjycui** [comment]
cc @afc163

**Comment by afc163** [comment]
Added `@card-padding-base` and `@card-padding-wider`, you can override the `@card-padding-wider` same as `@card-padding-base` avoiding auto-expand behaviour.

**Comment by kushalmahajan** [comment]
If someone has to use Card with `card-padding-base` how exactly can he do that with props?
