### ISSUE TITLE
How to check/uncheck the checkbox within the TreeSelect compoment by clicking the label text beside it?

### ISSUE THREAD

**Issue by richartan** [ant-design/ant-design#6974]
### What problem does this feature solve?
It will be more convinient by selecting the item by clicking the label text. just like the most label/check box in a form.

### What does the proposed API look like?
select a item by clicking label text in TreeSelect complent.

**Comment by yesmeck** [comment]
You use `onSelect` to collect selected nodes, then set them as checked.

**Comment by violabg** [comment]
actually, if you have a checkbox it means you set treeCheckable: true, and so you don't have onSelect when you click the label.
is there another way  to check/uncheck the checkbox within the TreeSelect compoment by clicking the label text beside it?
