### ISSUE TITLE
Checkbox checkall issue

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#6978]
### Version
2.12.2

### Environment
IOS, "react": "^15.1.0",

### Reproduction link
[https://codepen.io/Aggie23/pen/eENjqe](https://codepen.io/Aggie23/pen/eENjqe)

### Steps to reproduce
Replace plaindata of checkbox from simple string array to object array, then the checkall feature doesn't work well.

### What is expected?
normal checkall feature, checkall and all the checkbox options checked and vice versa.

### What is actually happening?
when click checkall, the checkbox options weren't been checked.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/NvqOwL?editors=0010

Beware of the format of `CheckGroup`'s value.

**Comment by Aggie123** [comment]
Thanks for your quick response. What stupid mistake I have made. 囧.
And have a nice day.
