### ISSUE TITLE
Inner style Card

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#6979]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/507615/28659671-df4ba230-72e2-11e7-9668-ce305156a79b.png">

## Difference from Card

- 灰色的标题栏背景。
- 更小的默认标题字体。
- 更窄的内边距，并且不动态伸缩。

## API

```jsx
<Card type="inner">
  xxx
</Card>
```

## Usage

Use on the page content or inside normal Cards.

**Comment by ddcat1115** [comment]
> 并且不动态伸缩。

这是啥意思？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/e1a46cc419fb4975ae1782ba793b378c8e584057

**Comment by inev** [comment]
This sounds great! The new dynamic stretching has broken previous CSS overwrites and the animation is causing a lot of errors. Keep getting `Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at Card.updateWiderPadding`. Would prefer if this style didn't have any of those calculations as well.

**Comment by afc163** [comment]
@inev this should be fixed at https://github.com/ant-design/ant-design/pull/6976

**Comment by inev** [comment]
@afc163 Thank you so much. 

Moving forward if there are any big changes like this can we make the default as it used to be and use another property to turn on the new behavior? For this it would have been something like `autoAdjustPadding={true}` This way it's easy to stay up to date with all the great work you guys put out on a regular basis without fearing what might break.

**Comment by benjycui** [comment]
如果我这样用会怎样？

```jsx
  <Card title="卡片标题" noHovering type="inner">
    <Card.Grid style={gridStyle}>卡片内容</Card.Grid>
  </Card>
```

**Comment by afc163** [comment]
inner 主要影响的是 header 部分。

**Comment by benjycui** [comment]
Close in https://github.com/ant-design/ant-design/pull/7120
