### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by wangpin34** [ant-design/ant-design#698]
![nico-error](https://cloud.githubusercontent.com/assets/12655367/11863198/fb6988a0-a4cc-11e5-8589-2ef8f4d0d74f.png)

被这个问题 卡住了，希望得到一些帮助。

win7 64 , node v4.2.1, npm 2.14.7

**Comment by afc163** [comment]
本项目自身的开发不建议使用 windows 系统。
