### ISSUE TITLE
Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.

### ISSUE THREAD

**Issue by hanzhangyu** [ant-design/ant-design#6984]
### Version
2.12.0

### Environment
window8,chrome59,node7,react15.4

### Reproduction link
[https://codepen.io/hanzhangyu/pen/prjPKY?editors=0011](https://codepen.io/hanzhangyu/pen/prjPKY?editors=0011)

### Steps to reproduce
见链接及注释

### What is expected?
没有warning

### What is actually happening?
提示我root被更换

**Comment by benjycui** [comment]
Your CodePen doesn't work, please fix it first.

**Comment by hanzhangyu** [comment]
I had tried again，It works. What's the problem?
the Modal component will open success, but I will receive a warning about a new root component rendered.

**Comment by benjycui** [comment]
Your own code's issue:

![image](https://user-images.githubusercontent.com/3580607/28707102-a245b34a-73a9-11e7-932f-a301a548e0fa.png)

**Comment by hanzhangyu** [comment]
How can i use `getContainer` props? the `tooltip` is create in the `trigger event` done. but this `modal s`  create time is the component render.  In the frist render `this.refs.body` will be `undefined`. 
Actually, i can use `document.getElementById` to get a exist Dom,  but it is no logic!
