### ISSUE TITLE
will Tabs support drag and resort

### ISSUE THREAD

**Issue by lixiaoyang1992** [ant-design/ant-design#6985]
### What problem does this feature solve?
resort Tabs 

### What does the proposed API look like?
<Tabs onTabPositionChange={callback} draggable>
    <TabPane tab="Tab 1" key="1">Content of Tab Pane 1</TabPane>
    <TabPane tab="Tab 2" key="2">Content of Tab Pane 2</TabPane>
    <TabPane tab="Tab 3" key="3" draggable={false}>Content of Tab Pane 3</TabPane>
  </Tabs>

**Comment by afc163** [comment]
Nope.
