### ISSUE TITLE
Input 组件拿不到 ref 的值

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#699]
```
<Input type="text" ref="keyword" />

this.refs.keyword.value  --> undefined

```

**Comment by afc163** [comment]
@benjycui 看下。

**Comment by silentcloud** [comment]
看了源码，需要这么拿  this.refs.keyword.refs.input.value
源码 ref 写死的 input

**Comment by benjycui** [comment]
@afc163 我把 `ref` 改为可配置的？

**Comment by afc163** [comment]
我看到 react bootstrap 也是 `ref="input"`，我不太确定了。你问下 @simaQ 吧。

**Comment by silentcloud** [comment]
@benjycui 真实的input外层还有dom的，所以现在这种方式是可以的，只不过文档上得写明一下
目前这样子是ok的

**Comment by benjycui** [comment]
`ref` 不可以这么用，`this.refs.xxx` 只能是 owner 引用 ownee，不可能直接引用到内层的 `input`，获取值还是监听 `onChange` 吧。

See: https://facebook.github.io/react/docs/more-about-refs.html#summary

**Comment by freepander** [comment]
现在的`Input`, `TimePicker`等组件只能通过监听`onChange`事件获得用户输入吗？ 能否对各种数据输入组件封装类似`getValue`的方法来获得用户输入。

**Comment by benjycui** [comment]
@freepander https://github.com/ant-design/ant-design/issues/388

**Comment by ycjcl868** [comment]
只能通过监听 `onChange` 事件获取了
![image](https://cloud.githubusercontent.com/assets/13595509/26181537/68c26f48-3ba3-11e7-8c39-8bad47d9b75d.png)
