### ISSUE TITLE
Something wrong with render method of 'Tooltip'

### ISSUE THREAD

**Issue by fireswork** [ant-design/ant-design#6990]
`
import React from 'react';
import { Link, Route } from 'react-router-dom';
import { Menu } from 'antd';

export default () =>
  <div>
    <Menu>
        <Menu.Item>
            <Link to="/page/pageSite">首页</Link>
        </Menu.Item>
        <Menu.Item>
            展示页
        </Menu.Item>
    </Menu>
  </div>;
`
this is my code , very simple. when i change the code ,  refresh my browser after hot-update, i will receive a error:

**> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Tooltip`.**

**Comment by 16slowly** [comment]
@fireswork hello 你解决这个问题了吗 ？

**Comment by fireswork** [comment]
@16slowly when you update your react to v 16+, you will recieve this error. 
updating antd's version can solve it
