### ISSUE TITLE
onSelect not triggered in `multiple` mode in TreeSelect

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#6991]
### Version
2.12.2

### Environment
macos: 10.12.5   chrome: 59.0.3071.115

### Reproduction link
[https://codepen.io/daskyrk/pen/JyYpbj?editors=0011](https://codepen.io/daskyrk/pen/JyYpbj?editors=0011)

### Steps to reproduce
1. open https://ant.design/components/tree-select/
2. open the multiple demo in codepen, add a `onSelect` props and function
3. nothing logged in console.

```javascript
  onSelect = (value) => {
    console.log('onSelect', value);
  }
```

### What is expected?
`onSelect` may should be triggered in `multiple` mode

### What is actually happening?
nothing happened

**Comment by afc163** [comment]
When `treeCheckable` is true, the select behavis will not trigger onSelect but check will do.
