### ISSUE TITLE
Add data-attribute to td in Tree data table component

### ISSUE THREAD

**Issue by likhita-palavali** [ant-design/ant-design#6994]
<img width="906" alt="screen shot 2017-07-28 at 12 18 00 pm" src="https://user-images.githubusercontent.com/17817231/28734472-023f74fc-7396-11e7-8ceb-f6f3571c87c7.png">
### What problem does this feature solve?
I am using Tree data table component as per our display requirements.
I am trying to display a tooltip on hover for all the first td values in the table because the values are too big to display in a cell. 
To do this I need to add a data-attribute to first td of all rows.
Please provide a way to add data-attributes to td of tree data table.
Thanks.

### What does the proposed API look like?
Using the api (Tree data table for this.)
The api will show tooltip for long values.
I will use react-tooltip where i just need to provide a custom data-attribute to the td.

**Comment by yesmeck** [comment]
You can pass props to td like this:

```javascript
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  render: () => {
    return {
      children: 'foo',
      props: {
        'data-tip': 'a very long text',
      },
    };
  },
}]
```

**Comment by likhita-palavali** [comment]
Thank you. It worked . 
Great help

**Comment by sydinh** [comment]
@yesmeck  Good work. 🙇

**Comment by roseniltonreis** [comment]
If you can another way, "onCell" is functional on this case:

`const columns = [{
  title: 'Name',
  dataIndex: 'name',
  onCell: (record, rowIndex)=>({"data-custom": "custom_value"})
  render: () => {}
}]`
