### ISSUE TITLE
Fixed collapsible sider menu

### ISSUE THREAD

**Issue by mkermani144** [ant-design/ant-design#6997]
### What problem does this feature solve?
Although an example of a fixed Sider is provided in the documentation (#5660), the trick of making Sider position fixed does not work easily if the Sider has collapsible menu. The developer should manage left (or right) property of the content by hand, and change it on collapse. Is there any better approach to do it, or is it intended to add a feature facilitating this?

### What does the proposed API look like?
For example, `Sider` parent (which is a `Layout`) could have a `collapsibleFixedSider`, by setting which the `Sider` position becomes fixed, and its sibling (probably a `Layout` or `Layout.Content`) `margin` property updates is handled inside of the library itself, adding a layer of abstraction to the developer.

**Comment by marswong** [comment]
@mkermani144 
you want to implement a `Sider` just like [YouTube](https://www.youtube.com/)?

**Comment by mkermani144** [comment]
@marswong 
No. You tube hides its `Sider` totally when you click on hamburger menu.

**Comment by marswong** [comment]
@mkermani144 
why developers should manage left (or right) property of the content by hand, and change it on collapse? the style of `SubMenu` is ok. could u add an online demo? it's so hard to understand what u describe.

**Comment by wzard** [comment]
@marswong  I am facing the same issue. I have uploaded a video here. https://youtu.be/nZ8Tuswd7JI .

When you make a fixed sidebar collapsible, the responsive-ness of the Content disappears. 
I did a workaround by adding the margin of the content getting changed everytime the menu is collapsed or uncollapsed. 

As you can see in the video, the interface looks lagging and not smooth, at all. 

@mkermani144 How did you worked around this one?

**Comment by mkermani144** [comment]
@wzard As I said, I manage `margin` property of main content manually (by changing `state`), but in my case, it's smooth and does not lag.

**Comment by wzard** [comment]
@mkermani144  When I am making the position: "fixed" for the Sider, the Inline Icons on collapse also doesn't work. Can you share a codepen demo of how you are making it work, please?

**Comment by Xemnoras** [comment]
@mkermani144 I'm also trying to achieve the same effect and would be interested if you could share your solution.

**Comment by mkermani144** [comment]
@Xemnoras As I said earlier, I manage `margin` style of the main content manually using `state`.

**Comment by abilash13** [comment]
So are there any plans to fix this behavior?

**Comment by vitorsilvalima** [comment]
I think having the side menu to be able to have a fixed position and at the same time being able to collapse would be great and I really look forward for this feature. It may not be implemented but it would be great to have examples in the doc to show to do that.

**Comment by AntonBramsen** [comment]
I'm hoping for nice solution to this, I would love to manage as little state as possible in my application.

**Comment by edpark11** [comment]
I did the same thing, fixed it by creating a setMarginLeftHandler in the parent Layout and passing that as a prop to a wrapped Sider. Then onCollapse (on the Sider), call props.setMarginLeftHandler to fix up the margins of the parent. In my case I used a HOC recompose component so I could still use functional React components but if would of course work with standard stateful react components too. Regardless, definitely a tad awkward.

**Comment by afc163** [comment]
You can see Ant Design Pro width fixed sider: https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=1

<img width="483" alt="image" src="https://user-images.githubusercontent.com/507615/52269119-3d228e80-2978-11e9-9601-776f29d1e0f7.png">

**Comment by Uhel** [comment]
I did simply by adding some css rules! Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l

**Comment by hmassad** [comment]
> I did it simply by adding some css rules! 👍
> Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l

by changing Sider style to
` style={{
          overflow: 'auto',
          height: '100vh',
          position: 'sticky',
          top: 0,
          left: 0,
        }}`

**Comment by simonsankar** [comment]
> I did it simply by adding some css rules! 👍
> Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l

You legend

**Comment by Terkea** [comment]
> > I did it simply by adding some css rules! 👍
> > Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l
> 
> by changing Sider style to
> ` style={{ overflow: 'auto', height: '100vh', position: 'sticky', top: 0, left: 0, }}`

this solution doesn't seem to work on v 4.5.x

**Comment by AltRoot17** [comment]
> > I did it simply by adding some css rules! 👍
> > Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l
> 
> by changing Sider style to
> ` style={{ overflow: 'auto', height: '100vh', position: 'sticky', top: 0, left: 0, }}`

Thanks buddy, its worked for me

**Comment by madrelax** [comment]
> > I did it simply by adding some css rules! 👍
> > Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l
> 
> by changing Sider style to ` style={{ overflow: 'auto', height: '100vh', position: 'sticky', top: 0, left: 0, }}`

Thanks. U r awesome)))

**Comment by Blooming786** [comment]
How could we move the collapsible sidebar to the top left instead of now having it at the left bottom?

**Comment by moabbar** [comment]
> I did it simply by adding some css rules! 👍 Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l

if you hover over the menu items while the side bar's collapsed, and scroll the page, the tooltip of the hovered menu item will slide as well.
Does anyone know how to fix this issue?

**Comment by aizhanadb** [comment]
> > I did it simply by adding some css rules! 👍 Demo's here: https://codesandbox.io/s/antd-sider-fixed-solved-hgz5l
> 
> if you hover over the menu items while the sidebar's collapsed, and scroll the page, the tooltip of the hovered menu item will slide as well. Does anyone know how to fix this issue?

Thank you so much!
