### ISSUE TITLE
RangePicker 无法正确手动填写开始时间

### ISSUE THREAD

**Issue by phxsuns** [ant-design/ant-design#6999]
### Version
2.12.2

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
直接看官网示例。RangePicker的开始时间输入框，输入到符合format的时间时，就会清空输入框，非常奇怪。

### What is expected?
用户可以正确手动输入开始时间，并最终效果和从日历上选一样。

### What is actually happening?
开始时间框输入符合format格式的时间时，会被清空。

**Comment by benjycui** [comment]
cc @paranoidjk 

rc-calendar 这层好像就有问题了 

<img src="http://g.recordit.co/XqIYQQq4eH.gif" />

**Comment by comeriven** [comment]
I also encountered this bug in the development process.
Best regards

**Comment by comeriven** [comment]
也许有人能解决这个问题？

**Comment by Witee** [comment]
我发现使用 defaultValue 时显示是对的，但实际选中的还是默认的，好奇怪

**Comment by paranoidjk** [comment]
@benjycui 这是要自己实现的..  https://github.com/react-component/calendar/blob/master/examples/antd-range-calendar.js#L165 demo 只处理了显示，没有处理输入更新

**Comment by benjycui** [comment]
ref: https://github.com/react-component/calendar/issues/286

**Comment by Frank1e0927** [comment]
相同的问题，现在也遇到了，看了一下antd官网，似乎还没有进行修复。希望尽早修复。
