### ISSUE TITLE
文件上传Upload中props的action属性类型问题

### ISSUE THREAD

**Issue by fanyangyang** [ant-design/ant-design#7002]
### What problem does this feature solve?
能解决文件上传的问题

### What does the proposed API look like?
期望API中props的action属性能从string变成对象或者是其他能够方便变更的类型，在我开发的过程中，使用action作为请求地址来发送get请求，有发送多次的需求，而且每次action后跟的参数还不一样，由于目前action类型为String，所以再次发送请求的时候其不会发生变化，所以多少有点不满足需求，还望能发现并及时做出处理

**Comment by afc163** [comment]
`action={`/upload?query=${xxxx}`}`

请认真学习 JSX。

**Comment by fanyangyang** [comment]
初学者，请见谅😅
