### ISSUE TITLE
Tooltip定位功能对SVG元素似乎不准确

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#7003]
### Version
2.12.2

### Environment
macOS Chrome 60.0.3112.78 beta

### Reproduction link
[https://codesandbox.io/embed/Xo4VErVMk](https://codesandbox.io/embed/Xo4VErVMk)

### Steps to reproduce
1. 打开[https://codesandbox.io/embed/Xo4VErVMk](https://codesandbox.io/embed/Xo4VErVMk)
2. 将鼠标移至热力图的方块上，查看Tooltip的位置
3. 将鼠标移到下方“This produces correct tooltip”文字上，查看Tooltip位置

### What is expected?
当鼠标移至热力图广场上时，应该在当前广场的上方中间位置显示Tooltip

### What is actually happening?
在广场上时，Tooltip对齐到了方块的左上角

---
使用其它`placement`同样会有问题

**Comment by benjycui** [comment]
The minimal re-producible online demo: https://codepen.io/anon/pen/EvPMWP?editors=0010

**Comment by benjycui** [comment]
Ref: https://stackoverflow.com/questions/18147915/get-width-height-of-svg-element

Pending for: https://github.com/yiminghe/dom-align/pull/22
