### ISSUE TITLE
Default Checked Row for Select (Dropdown) when using mapPropsToFields

### ISSUE THREAD

**Issue by tsupol** [ant-design/ant-design#7004]
### Version
2.12.2

### Environment
Windows 10, Chrome 59.0.3071.115, react 15.5.4

### Reproduction link
[https://codepen.io/tsupol/pen/Nvxxop?editors=001](https://codepen.io/tsupol/pen/Nvxxop?editors=001)

### Steps to reproduce
* Using `Form` with mapPropsToFields
* Using `Select` with labelInValue and multiple selection
* Sets default value with key and label

### What is expected?
When dropped down, the the selected values aren't checked

### What is actually happening?
When dropped down, the the selected values are checked

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/Nvxvod?editors=0010

The key or value of Select.Option have to be a string for now, you can trace future plan in #2857

**Comment by tsupol** [comment]
@afc163 glad to hear that integer key will be support in the future and thank you very much for clarification.
