### ISSUE TITLE
Table的当表格内容较多不能一次性完全展示时怎么禁用掉。

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#701]
RT
具体的问题就是我有个数组如下图所示，作为表格的数据源，现在他自动加上可展开的按钮了，实际上我只想第一层的数据，不需要下面的。
![20151217164735](https://cloud.githubusercontent.com/assets/433259/11865267/e9fdeb54-a4dd-11e5-8d5e-1c25f865b196.png)
![qq 20151217165051](https://cloud.githubusercontent.com/assets/433259/11865345/5f5bdff0-a4de-11e5-97bb-66fdb0fc3d06.png)
@afc163 
:monkey:

**Comment by afc163** [comment]
自行将数据进行裁剪。

**Comment by bang88** [comment]
这个不科学吧，嵌套的数据要扁平化？
