### ISSUE TITLE
_renderNewRootComponent  warning using Message component

### ISSUE THREAD

**Issue by eldyvoon** [ant-design/ant-design#7012]
### Version
2.12.2

### Environment
chrome, osx

### Reproduction link
[http://google.com](http://google.com)

### Steps to reproduce
I have a Message.js component like below

```
import { message } from 'antd';

const Message = ({success, msg}) => {
	
	return(
		<div>
			{success ? <div>{message.success(msg)}</div> : 
				<div>{message.error(msg)}</div>
			}
		</div>
	)
}

export default Message;
```

then somewhere I do ```<Message success={success} msg={msg} />```,

### What is expected?
No error in the console

### What is actually happening?
Got an warning in console

> Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of Message.

**Comment by djyde** [comment]
`message.success(msg)` dose not return a React node. Why did you put it in `<div>`

**Comment by afc163** [comment]
Wrong usage, please follow the documentation.
