### ISSUE TITLE
Removing scroll bar from table header leads to misalignment

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#7017]
### Version
2.12.2

### Environment
OS: Windows 10, Browser:Chrome ,  React :15

### Reproduction link
[https://codepen.io/anon/pen/XaXZQv)

### Steps to reproduce
Run the https://codepen.io/anon/pen/XaXZQv codepen .
override the css for removing scrollbar from the table header

### What is expected?
Table header and body should be aligned if one does not want scroll bar on table header

### What is actually happening?
I have override the css for removing scrollbar from the table header. After doing this, table body and header are misaligned.

**Comment by afc163** [comment]
Yep, it is useful and don't override it. And some workarounds is been tried but none of them perfect.

https://github.com/ant-design/ant-design/issues/4637#issuecomment-280829518
