### ISSUE TITLE
Disabled Dropdown is showing Menu on hover

### ISSUE THREAD

**Issue by sanchan** [ant-design/ant-design#7018]
### Version
2.12.2

### Environment
macOS Sierra, Chrome 59.0.3071.115/Firefox 54.0

### Reproduction link
[https://codepen.io/danilovb/pen/vJLQxe](https://codepen.io/danilovb/pen/vJLQxe)

### Steps to reproduce
Just hover the Actions dropdown

### What is expected?
The Dropdown is disabled, so I expect that the menu doesn't show up.

### What is actually happening?
The Menu is showing up.

**Comment by benjycui** [comment]
You should disabled Dropdown itself, not its children:

```diff
- <Dropdown overlay={overlay}>
+ <Dropdown overlay={overlay} disabled>
```

**Comment by sanchan** [comment]
@benjycui Yes, I tried that too, but it's the same result. You can see it in my demo, change it as you said and you will see it's not working as expected.

**Comment by benjycui** [comment]
Yep, it seems that we had missed this API

**Comment by afc163** [comment]
How about：

```jsx
{
  this.state.disabled ? <Button disabled={this.state.disabled}>Action</Button> : (
    <Dropdown overlay={overlay}>
      <Button disabled={this.state.disabled}>Action</Button>
    </Dropdown>
  )
}
```

**Comment by sanchan** [comment]
Yep @afc163, that's a good workaround in my case. I'm doing something similar but I prefer your approach. Thank you :)

**Comment by sanchan** [comment]
@benjycui I'll see if I can fix this and make a PR :)
