### ISSUE TITLE
popconfirm建议增加国际化

### ISSUE THREAD

**Issue by JiangAmber** [ant-design/ant-design#702]
在使用popconfirm的时候，希望能自定义确定以及取消的按钮内容。（ex: cancel / confirm)
![image](https://cloud.githubusercontent.com/assets/6375421/11866101/c668c05a-a4e3-11e5-80bc-04bc50b5ba52.png)

**Comment by benjycui** [comment]
已支持 https://github.com/ant-design/ant-design/commit/51a2798eb55e526a84e1e38e924dec52dcafab9a

在 [0.11.0](https://github.com/ant-design/ant-design/issues/413) 中可用。

**Comment by JiangAmber** [comment]
谢谢
