### ISSUE TITLE
column的fixed问题

### ISSUE THREAD

**Issue by aqtata** [ant-design/ant-design#7023]
### Version
2.12.3

### Environment
windows 10、chrome 59.0.3071.115

### Reproduction link
[https://codepen.io/aqtata/pen/YxwmEd](https://codepen.io/aqtata/pen/YxwmEd)

### Steps to reproduce
table的column设置fixed='right'属性时发生。

### What is expected?
table只有一列，且居右显示

### What is actually happening?
table出现了两列

**Comment by benjycui** [comment]
你会有这么极端的场景么？只有一列然后还要 fixed?!

**Comment by afc163** [comment]
只有一列时固定没有实际意义。

**Comment by aqtata** [comment]
第一，我提问是遵循了官方提倡的问题最小化原则，让问题凸显出来，才没有写很多列进去，实际你加了若干列也是一样的效果。
第二，有无意义这东西比较主管就不讨论了，从代码上看我只定义了一列，却出现两列数据，这个符合逻辑吗？

**Comment by afc163** [comment]
按照官方网站的演示来看应该是没问题的：https://ant.design/components/table/#components-table-demo-fixed-columns

你的业务开发过程具体有遇到什么问题吗？

**Comment by aqtata** [comment]
我有一张table，有若干column，我想让最后一个column靠右对齐，正好column中有这么个属性fixed可以设置，设置left时没有问题时正常的，但是当fixed=right时，这个列就会渲染出两列出来。codepen代码我加了两列，您看看，antd版本是2.12.2

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/MvygGP

注意看文档，固定列需要指定宽度。

<img width="627" alt="image" src="https://user-images.githubusercontent.com/507615/28770138-a5096496-7610-11e7-9199-d02328d6af3d.png">

**Comment by yhw601071569** [comment]
在使用table的column设置fixed='left'时， 列数不多未出现滚动条时，使用fixed的列后多了一列，为空的列。

**Comment by catgu** [comment]
> 在使用table的column设置fixed='left'时， 列数不多未出现滚动条时，使用fixed的列后多了一列，为空的列。

我也遇到这个问题，但是我的是重复出现了一次该列

**Comment by Sara1991908** [comment]
我也出现了，指定fixed时，出现空白列

**Comment by TronSun** [comment]
> > 在使用table的column设置fixed='left'时， 列数不多未出现滚动条时，使用fixed的列后多了一列，为空的列。
> 
> 我也遇到这个问题，但是我的是重复出现了一次该列

我也遇到了 很麻烦啊

**Comment by ivanberry** [comment]
按照文档说的填写固定宽度就好啦

**Comment by suncunhu** [comment]
可以参考这个  [ant-design Table组件错位/对不齐](https://blog.csdn.net/baozhuona/article/details/94007661#3_96)

**Comment by baohuse** [comment]
https://yuque.antfin-inc.com/wb-yxl411213/lbl2te/eqd1zw

**Comment by yoyo837** [comment]
@baohuse 你发的内网 😭

**Comment by ZhaoTim** [comment]
> 按照文档说的填写固定宽度就好啦

写固定宽度了，还是不好
