### ISSUE TITLE
Disable title attribute in Badge

### ISSUE THREAD

**Issue by marwej** [ant-design/ant-design#7024]
### What problem does this feature solve?
Is it possible to somehow disable the title attribute on the badge? This triggers a small popup with the badge text which, in some cases, is wanted. I, however, use the badge on quite large components and do not want that popup on the whole component.

### What does the proposed API look like?
`<Badge text={myBadgeContent} useTitleAttr={false}><OtherComponent /></Badge>`

**Comment by anpmcroak** [comment]
Why was this closed? Has there been a solution implemented?

**Comment by johannesstroebele91** [comment]
I'm also curious if a problem was found. this definitely should be optional to be disabled.
