### ISSUE TITLE
when one of treeNodes is "null",tree will throw an error.

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#7025]
### Version
2.12.3

### Environment
chrome

### Reproduction link
[https://codepen.io/twisger/pen/brpbEg?editors=0010](https://codepen.io/twisger/pen/brpbEg?editors=0010)

### Steps to reproduce
the Tree's or TreeNode's child node is null or undefind,

### What is expected?
not to throw an error,ignore it and continue to render next child.

### What is actually happening?
throw error "Cannot read property 'props' of null",and the tree won't be rendered.

---
I want to generate treeNode through an loop function, some treeNodes need't display so I want to hide them  by return null.It not working, I wiil have to filter the data before render Tree.

**Comment by afc163** [comment]
trace #6530
