### ISSUE TITLE
The isLeaf property of TreeNode is confusing.

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#7026]
### Version
2.12.3

### Environment
chrome

### Reproduction link
[https://codepen.io/twisger/pen/BdKaPG?editors=0010](https://codepen.io/twisger/pen/BdKaPG?editors=0010)

### Steps to reproduce
no

### What is expected?
I expected the treeNode can't be expand when I set a `isLeaf=true` property on it,though it has child node. 
Even if it hasn't child, `isLeaf=false` is still invalid because the loadData function is not specified.
Actually the isLeaf property is first determined by children of TreeNode, then loadData and isLeaf.

### What is actually happening?
no

---
I'm not sure about which performance is pretty, but at least point out it in the doc.

**Comment by benjycui** [comment]
I think it's OK, it's just for `loadData`, if you think the documentation is confusing, you can try to PR to update it, thanks.
