### ISSUE TITLE
select只能默认出现一次空选，选了其他之后就出现不了，如何解决啊

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#7029]
### What problem does this feature solve?
因为有的条件不是必选的，现在搞得选了一次之后，后面就成了必选了，这样就容易误导用户选择的内容

### What does the proposed API look like?
希望有一个空值选项，而且他的值最好能为null或空或undefine

**Comment by yesmeck** [comment]
给个 demo ?

**Comment by djyde** [comment]
You should try `allowClear={true}`
