### ISSUE TITLE
如何禁用InputNumber默认赋值行为

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#703]
我自己的例子：max=10000，min=-10000，当输入框获得焦点在不输入值的情况下失去焦点，会将值置为0。
官方例子中：max=10，min=1，删除输入框中的值，会将值置为1。
我想关闭这种自动赋值的行为，文本框没有值时就空着。

**Comment by benjycui** [comment]
[rc-input-number](https://github.com/react-component/input-number/blob/master/src/InputNumber.js#L73) 目前不支持。

@afc163 对于这情况是？
1. 添加 `dirty` 标记，对于不曾操作过的 `InputNumber` 禁用默认赋值行为。
1. 对有 `required` 属性的 `InputNumber` 才启用默认赋值行为。
1. 组合上面两个方案。

**Comment by afc163** [comment]
应该是 bug 。

**Comment by afc163** [comment]
试试重新安装 antd，`rc-input-number@3.4.3` 里修复。
