### ISSUE TITLE
Does it exit a attribute named onInit for Select Component?

### ISSUE THREAD

**Issue by chairy11** [ant-design/ant-design#7032]
### What problem does this feature solve?
It can use to  trigger a function when initial a input with already known value, just like 'onChange' attribute.

比如一行表单， 第一个input选择后，onChange会触发一个函数，函数会请求后台数据，得到结果会告诉我，第二个input是什么类型（单选、多选、级联单选、树多选、text型input），是否需要发请求、url和参数是什么，综合起来得到第二个input的类型和选项。

input1 ->发请求 ->得知input2的类型及如何请求选项。

这在新建表单是容易实现的。
但如果是编辑表单，input1和input2的value是知道的，但input2的类型和选项，还是得从input1那个触发函数来。
那有没有方法，类似于onInit，在初始化input1时，就触发请求的？

### What does the proposed API look like?
onInit

**Comment by afc163** [comment]
`componentDidMount`

It is not a issue of `antd`, you could learn React first. http://facebook.github.io/react/

**Comment by chairy11** [comment]
I think " componentDidMount " is use for the whole class initial, but what I need was only trigger for many  input. 

Of course I can query for  the data for every input before the form create,  but I think a onInit attribute will be much more elegant.

What I need was trigger the onChange method on initial input when edit the form. 
There are too many input1 to send the request.

因为表单非常复杂，有太多行，每行都有 input1 ，选择后input1后才能决定input2的类型（text，select单选多选，Cascader，TreeSelect）和选项请求对应的数据（可能直接提供数据，可能来自url，url有针对不同接口有不同调用方法等）。
如果是整个表单初始化时一一单独请求，太麻烦了。其实我只需要初始化每个input的时候，有个类似onChange的触发点而已。

**Comment by afc163** [comment]
按照 React 的哲学，组件不应该提供生命周期管理。你可以尝试把 Input 封装成一个高阶组件，在里面的 componentDidMount 去调用相关方法。

**Comment by chairy11** [comment]
可能我还是没说明白我的想法。
我们的表单比较复杂，动态删减（用mobx的额外的一个keys变量来控制结构），又全是动态请求选项（选择了这一行表单的input1，才知道input2是什么类型，要发什么请求来获取选项），所以也在Antd的组件上封装了自动请求数据的方法。
比如
```
<Select dictUrl="xx" dictKey="xx" dictSite="xx" onChange={fetchInput2info(k)}/>
```
所以，进入一个edit表单，如果在能有一个onInit方法, 在它初始化select的时候，就触发这个onChange函数，像
```
<Select dictUrl="xx" dictKey="xx" dictSite="xx" onChange={fetchInput2info(k)} onInit={fetchInput2info(k)}/>
```
一切就变得毫不费劲，也不需要单独发请求，就会简洁太多了。

**Comment by afc163** [comment]
既然已经二次封装了 antd 的组件，那么你可以在封装的组件里自行实现 onInit 的方法。

```jsx
class YouSelect extends Component {
  componentDidMount() {
    this.props.onInit();
  }
  render() {
    return <Select {...this.props} />;
  }
}
```

**Comment by chairy11** [comment]
好吧，已经到家，明天上班再试，谢谢了，晚安。
