### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'rc-util/lib/Dom/addEventListener'.

### ISSUE THREAD

**Issue by aftdotleo** [ant-design/ant-design#7033]
### Version
2.12.3

### Environment
"typescript": "2.4.2"

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx#L3](https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx#L3)

### Steps to reproduce
with tsconfig.json -> "strict": true,

npm run dev for my project

### What is expected?
No ts error, just like antd@2.12.2

### What is actually happening?
I also see
https://github.com/ant-design/ant-design/blob/master/typings/custom-typings.d.ts#L15
and
https://github.com/react-component/util/blob/master/src/Dom/addEventListener.js,

but, where is the RcUtilEventHandler?

**Comment by djyde** [comment]
Try to `rm -rf node_module` and `npm install`?

**Comment by aftdotleo** [comment]
Hi all,
I try, I just try...

ermm, I use yarn, so I following the steps:
yarn cache clean
rm -rf node_modules
rm yarn.lock
yarn install

ಥ_ಥ

It does not help...

So I rollback to antd@2.12.2, it's ok again.

It's wired.

**Comment by suitedjimster** [comment]
I'm having the same problem. RcUtilEventHandler doesn't exist in rc-util/lib/Dom/addEventListener.js

**Comment by djyde** [comment]
😅 I found that there is no exported `rc-util/lib/Dom/addEventListener` declaration in compiled `index.d.ts`

**Comment by djyde** [comment]
Seems that must be declared in `rc-util` lib internal. I will create a PR to `rc-util` tomorrow. Sorry for my mistake. 😵

**Comment by djyde** [comment]
Since `rc-util` has no entry file, I couldn't write a declaration for it. Because when we do `import addEventListener from 'rc-util/lib/Dom/addEventListener'`, the TypeScript compiler will look up `rc-util/lib/Dom/addEventListener.d.ts`. But the `lib` folder is generated by the build tool, I am not able to touch it.

There is no good way to solve it with the compile tool https://github.com/Microsoft/TypeScript/issues/8305

How do you think of it? If there is no good idea, let me remove the declaration in `custom-typings` and keep the `rc-util*` with `any`.

@afc163

**Comment by benjycui** [comment]
> Since rc-util has no entry file, I couldn't write a declaration for it. Because when we do import addEventListener from 'rc-util/lib/Dom/addEventListener', the TypeScript compiler will look up rc-util/lib/Dom/addEventListener.d.ts. But the lib folder is generated by the build tool, I am not able to touch it.

See: https://unpkg.com/rc-dialog@6.5.10/lib/

Maybe you can just rewrite rc-util into TypeScript, then, it can be compiled just like rc-dialog.

**Comment by silentbalanceyh** [comment]
Please check your version of "babel-plugin-import", I have upgraded "babel-plugin-import" to 1.3.x when antd update to 2.12.3. But I compared the changes and modify "babel-plugin-import" to 1.2.1. This issue has been resolved here. 
From my understanding, most of user used "babel-plugin-import" to do importing when it's used here, but I think may be this issue refer to "babel-plugin-import" 1.3.x. Now I have resolved this issue. I'm not sure it's the root course, but now my environment issue has been resolved when I change "babel-plugin-import" from 1.3.x to 1.2.1. 
Regards Lang.

**Comment by aftdotleo** [comment]
@silentbalanceyh 
Wu... I've using antd with TypeScript, so it is just fall down at typescript compiling our components.
I've checked source code at that version, it is never export function named RcUtilEventHandler in code.

**Comment by djyde** [comment]
https://github.com/ant-design/ant-design/pull/7043 这个 merged 了，这个 issue 可以 close 了
