### ISSUE TITLE
DatePicker in popover closes the popover when date is selected

### ISSUE THREAD

**Issue by kdipika** [ant-design/ant-design#7036]
### Version
2.8.0

### Environment
Chrome, React JS

### Reproduction link
[https://codepen.io/dekommur/pen/eEZWaX](https://codepen.io/dekommur/pen/eEZWaX)

### Steps to reproduce
There is a Datepicker added to a poppver and when the date is selected, the popover closes itself.
Please find this in action here

https://codepen.io/dekommur/pen/eEZWaX

This has been the same issue for select dropdown before but adding getPopupContainer={triggerNode => triggerNode.parentNode} to it solved the issue. This fix does not work for the Datepicker though.

I am looking for solutions to stop the close of popover on date selection. Can anyone please help?

### What is expected?
The popover should not get closed on selection of date

### What is actually happening?
when the date is selected, the popover closes itself.

**Comment by kdipika** [comment]
Actually found it myself. There is a similar config for date picker getCalendarContainer

**Comment by jinrichardJIN** [comment]
i have the same as question
