### ISSUE TITLE
Conditionally style/highlight Table rows

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#7037]
### What problem does this feature solve?
I sometimes need to style Table rows differently based on a condition. For example you might use a table to show a list of items in a shop as a result of a search. You may wish to highlight items already in the users cart.
For my use case, I'm showing a list of configs the user could load and I want to style the currently active config differently than the other ones.

### What does the proposed API look like?
I propose a function which can either return a boolean or a class name on the `<tr>` if a true bool is return apply a highlight style, otherwise apply the classname.

```
function isStyledDifferently(rowObject, index) {
  return rowObject.isActive ? true : false;
}


<Table
  dataSource={dataSource}
  columns={columns}
  rowHighlightTest={isStyledDifferently}
/>
```

**Comment by topvis** [comment]
You can use the Table property "rowClassName". Something like:
```
<Table
   rowClassName={ (record, index) => {  your code here }   }

```

**Comment by megawac** [comment]
Awesome, I missed that!

**Comment by shekhar7** [comment]
Awesome! TFS

**Comment by vitor-alves** [comment]
Thanks

**Comment by mauryaavinash95** [comment]
Thanks!!

**Comment by ahsansher** [comment]
@topvis super, just missed it in docs. 👍

**Comment by cesc1802** [comment]
I have click on a row, and inside the function rowClassName, I cannot console.log(record, index). pls help me

**Comment by abudjakov** [comment]
Hi, it doesn't work with fixed columns

**Comment by ali-alamine** [comment]
How to use this code to highlight the selected row?

**Comment by awarmfastbear** [comment]
Example for anyone that is coming here from Google

https://jsfiddle.net/scs07x52/

**Comment by ma-henderson** [comment]
Those Fiddles are amazing! :D

**Comment by MaheshTrapasiya** [comment]
I want to highlight row on dragover event
