### ISSUE TITLE
table Pagination 左边那一块能不能定制，好放导出等按钮

### ISSUE THREAD

**Issue by cnhongwei** [ant-design/ant-design#7041]
### What problem does this feature solve?
因为表格好多都要做导出功能，想把表格导出相应的链接或按钮放到表格中。现在感觉放分页组件左边这一块空的地方还可以。所以这个地方能为能做为一个功能区开放出来。

### What does the proposed API look like?
分页组件左边区域做一个可定制的组件，如footer一样。让用户放自己想要的东西。

**Comment by chendonghai** [comment]
我也想要这个功能，还有老大建议我们用英文去写，有时我们想找答案，看到好多英语的答案都看不懂。

**Comment by benjycui** [comment]
`pagination={false}`, and then add your own Pagination.

**Comment by Smile-dan** [comment]
表格设置pagination={false}，然后自己添加分页组件
`<Table
          columns={columns}
          dataSource={dataSource}
          loading={loading}
          rowKey={record => record.id}
          pagination={false}
        />
        <Pagination
          className="ant-table-pagination"
          total={total}
          current={current}
          pageSize={PAGE_SIZE}
          onChange={pageChangeHandler}
        />`

**Comment by cnhongwei** [comment]
benjycui smile-dan 好办法，谢谢！
