### ISSUE TITLE
How to use Create-React-App + TypeScript + Ant-Design without Eject

### ISSUE THREAD

**Issue by comerc** [ant-design/ant-design#7044]
[react-app-rewired](https://github.com/timarney/react-app-rewired) + [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) = [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)

[boilerplate project](https://github.com/comerc/cra-ts-antd)

happy coding!

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git
