### ISSUE TITLE
Want a `Modal.create()`

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#7053]
### What problem does this feature solve?
Want a `Modal.create()`, which will create and show a Modal just like others `Modal.method()` but the body is empty (without icon).

### What does the proposed API look like?
`Modal.create({modalProps})`

**Comment by afc163** [comment]
```jsx
<Modal footer={null}>
</Modal>
```

This is enough.

**Comment by djyde** [comment]
Nope. I don't mean I don't need the footer (I still need okCancel). I need a **imperative** way to create and show a Modal just like others `Modal.method()` but I want it has no `ant-confirm-**` prefix class and a `<Icon />` which interferes my content body, while everything is just like a normal Modal (with the Promise  resolve confirmLoading helper):

```jsx
<Modal {...props}>
  {props.content}
</Modal>
```

**Comment by afc163** [comment]
Just use `Modal`.

**Comment by refex** [comment]
Can you clarify on 

> Just use Modal

?
