### ISSUE TITLE
Type of PaginationProps.showTotal is incorrect

### ISSUE THREAD

**Issue by fix777** [ant-design/ant-design#7054]
### Version
2.12.2

### Environment
OS: macOS Sierra Version 10.12.5 Browser: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit) React: V 15.4.4

### Reproduction link
[https://codepen.io/guoguo777/pen/BdzxMX?editors=0010](https://codepen.io/guoguo777/pen/BdzxMX?editors=0010)

### Steps to reproduce
<Table
      columns={props.columns}
      dataSource={props.dataSource}
      pagination={{
        total: props.dataSource.length,
        // Types of property 'showTotal' are incompatible.
        // Type '(total: any, range: any) => string' is not assignable to type '(total: number) => ReactNode'.
        showTotal: (total, range) => `${range[0]}-${range[1]} of ${total} items`,
        pageSize: 50,
      }}
    />

### What is expected?
No compile error.

### What is actually happening?
// Types of property 'showTotal' are incompatible.
// Type '(total: any, range: any) => string' is not assignable to type '(total: number) => ReactNode'.

---
showTotal?: (total: number) => React.ReactNode; => showTotal?: (total: number, range: any[]) => React.ReactNode;

**Comment by afc163** [comment]
Could you provide a reproducible repo, cause everthing looks fine in my machine.

**Comment by fix777** [comment]
Sorry, I mean the Tpye Definition of showTotal is incorrect, the param
range is missing.😓

**Comment by afc163** [comment]
Thx~
