### ISSUE TITLE
表格的表头添加全部展开按钮

### ISSUE THREAD

**Issue by Smile-dan** [ant-design/ant-design#7058]
### What problem does this feature solve?
展开这列是自动生成的，应该怎么在表头添加按钮？

### What does the proposed API look like?
想在这列的表头添加一个全部展开的按钮，类似全选，点击会全部展开，再次点击全部收起

![aa](https://user-images.githubusercontent.com/16626064/28861882-898b4712-7795-11e7-929d-89a619253f81.png)

**Comment by ddcat1115** [comment]
用 `defaultExpandAllRows` 控制默认状态 ok 么？感觉这个需求不是太常见，很少有需要主动展开所有的场景，如果需要，建议自己实现一个触发器去控制 `expandedRowKeys`

**Comment by Smile-dan** [comment]
@ddcat1115 默认是都不展开的，我也考虑用expandedRowKeys，现在想在自动生成的展开按钮那一列的表头添加一个按钮，如何实现呢？

**Comment by ddcat1115** [comment]
这里没有开API，感觉只能通过覆盖样式（针对 `.ant-table-expand-icon-th`）模拟一个按钮，同时增加点击事件

**Comment by benjycui** [comment]
@afc163 如果设计不希望支持这个场景，就把 issue 关了？

**Comment by yesmeck** [comment]
Duplicate #8791
