### ISSUE TITLE
Affix does not work under cheap-module-eval-source-map with ie

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#7060]
### Version
2.12.3

### Environment
windows 10 ie11 

### Reproduction link
[https://ant.design/components/affix-cn/](https://ant.design/components/affix-cn/)

### Steps to reproduce
if i set devtool with cheap-module-eval-source-map in webpack like

```javascript
devtool:cheap-module-eval-source-map
```

then the affix component does not work with ie.

and Then the console throws SCRIPT65535: 调用的对象无效的错误

if i change the webpack config to

```javscript
devtool:source-map
```

i work ok.

### What is expected?
the affix component can work ok in cheap-module-eval-source-map mode

### What is actually happening?
i does not work and throws error with ie

**Comment by afc163** [comment]
Could you provide a re-producible repo to help us？

**Comment by buxuku** [comment]
OK,I  have provide a repo for this issue at
```
https://github.com/buxuku/antd-affix.git
```

run `npm start` it work ok 

but run `npm run dev` it does not work;

The only difference before they is the devtool setting in the webpack

**Comment by afc163** [comment]
https://github.com/vuejs/vue/issues/4465

**Comment by afc163** [comment]
Thx for reporting and reproducing it.
