### ISSUE TITLE
Tabs.TabPane 使用 key 存储数据，和 React.Children 的 map、toArray 方法冲突

### ISSUE THREAD

**Issue by reoszo** [ant-design/ant-design#7061]
### Version
2.12.3

### Environment
all

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
React.Children.map 和 React.Children.toArray 会修改 key，导致对 Tabs 的封装非常痛苦

### What is expected?
不用 key 属性作为数据数据

### What is actually happening?
包装扩展组件时 key 属性错误

---
不晓得会拒绝问题，可能考虑设计时就是这样，虽然现在有这个缺陷

**Comment by paranoidjk** [comment]
并不会修改key，请给出可复现的demo。

**Comment by afc163** [comment]
close for no reproducible demo
