### ISSUE TITLE
How to set Layout.Content Auto Width @2.12.1-2.12.3

### ISSUE THREAD

**Issue by zix2002** [ant-design/ant-design#7062]
### What problem does this feature solve?
When update to 2.12.1 - 2.12.3 , I use `postion:"fixed"` instead `height:100vh` to  set fixed Sider, but Layout.Content would not auto width when Layout.Sider collapsed. So I set Layout.Content `marginLeft` to fix it , but it will faster than Layout.Sider And Menu's animation. 

### What does the proposed API look like?
2.12.0 work well, Have any solution for it.

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
If you are reporting a bug, use the bug template please.

**Comment by zix2002** [comment]
@afc163 

https://codepen.io/zix2002/pen/aymwXz?editors=0010

**Comment by wzard** [comment]
@zix2002 The Submenu is not correctly working also right, when collapased?. I am facing the same issue.

**Comment by zix2002** [comment]
@wzard that issue is record by #7048 , my question is `Layout.Content` how to auto width.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/xLROYN?editors=0010

Use `defaultOpenKeys` other than `openKeys`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/5da1403bc0510fad56aa415ad6ab639afa638a92
