### ISSUE TITLE
AutoComplete 支持不完全匹配情况

### ISSUE THREAD

**Issue by haohao667788** [ant-design/ant-design#7065]
### What problem does this feature solve?
在用户输入的内容不能完全匹配到自动补全的内容时，不主动触发 onSelect 事件

目前的一个情况：https://codepen.io/anon/pen/MvjYwN?editors=1111

在 Search 的 onSearch 触发后，会引起 AutoComplete 的 onSelect 事件

### What does the proposed API look like?
<AutoComplete allowDismatch />

**Comment by afc163** [comment]
Is it a bug report or a feature request, I am confused. 😕

**Comment by haohao667788** [comment]
feture request, I hope onselect is not trigger when input is not matched

**Comment by afc163** [comment]
`defaultActiveFirstOption={false}`

**Comment by chendonghai** [comment]
当不完全匹配情况下怎么来处理啊，要不然会把错误的信息提交到服务器上去，还问一下这个有没有手工清除他数据的api啊，因为我用onBlur事件最后来检查一下数据的是否有效性，当不是有效性时再来清空他
