### ISSUE TITLE
Cascader be used with Input will be bug

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design#7067]
### Version
2.12.3

### Environment
macos、chrome59.0.3071.115

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
edit user,I will select deparment,use the Cascader,the options from model，use getFieldDecorator to do initialValue,it is all right.but,I change input value,the cascader will null,will show.please help me!

### What is expected?
Cascader and Input will be used together but will be unaffected.

### What is actually happening?
change input value while the cascader is affected

---
code:
import React from 'react';
import { Form, Input, Tooltip, Icon, Cascader, Select, Row, Col, Checkbox, Button, AutoComplete,Radio,DatePicker,Upload,Spin } from 'antd';
const FormItem = Form.Item;
const Option = Select.Option;
const AutoCompleteOption = AutoComplete.Option;
const RadioGroup = Radio.Group;

import moment from 'moment';
import { routerRedux } from 'dva/router';

import { connect } from 'dva';

function UserEdit({
    dispatch,
    form,
    user,
    department,
    loading
  }){

  const { getFieldDecorator} = form;

  const { selectItem} = user;

  if(!selectItem.jobNumber){
    history.back();
    return null;
  }

  const formItemLayout = {
    labelCol: {
      xs: { span: 4 },
      sm: { span: 4 },
    },
    wrapperCol: {
      xs: { span: 20 },
      sm: { span: 20 },
    },
  };

  const tailFormItemLayout = {
    wrapperCol: {
      xs: {
        span: 14,
        offset: 2,
      },
      sm: {
        span: 14,
        offset: 2,
      },
    },
  };

  return(
    <Spin spinning={loading}>
    <div style={{padding:10}}>
      <div className="contentHead">
        <span className="contentLabel">编辑员工</span>
      </div>
      <Form layout="horizontal">
        <Row>
          <Col span={12}>
            <FormItem
              {...formItemLayout}
              label="工号"
              hasFeedback
              required
            >
              {getFieldDecorator('jobNumber', {
                rules: [{
                  required: true, message: '请输入工号',
                  }],
                initialValue:selectItem.jobNumber
                })(
              <Input />
                )}
            </FormItem>
            <FormItem
              {...formItemLayout}
              label="部门"
            >
              {getFieldDecorator('departmentId', {
                rules: [{
                  required: true, message: '请选择部门!',
                  }],
                  initialValue:selectItem.departmentIds
                })(
                  <Cascader options={department.dataSource} placeholder="选择部门" changeOnSelect/>
                )}
            </FormItem>
          </Col>
        </Row>

        <FormItem {...tailFormItemLayout}>
          <Button type="primary" htmlType="submit" size="large" onClick={(e)=>{handleSubmit(e)}}>保存</Button>
          <Button size="large" className="marginL10" onClick={(e)=>{
          dispatch(routerRedux.push({
              pathname: '/app/user'
          }));
        }}>取消</Button>
        </FormItem>
      </Form>
    </div>
    </Spin>
  )
}

function mapStateToProps({ user,department,loading }) {
  return {
    user,
    department,
    loading:loading.models.user
  };
}

export default connect(mapStateToProps)(Form.create()(UserEdit));

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7066#issuecomment-319853403

**Comment by wboykron** [comment]
I know ,but help me!

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by wboykron** [comment]
I can not provide the demo,becasue the options from model.According to the official example，It is all right！

**Comment by ddcat1115** [comment]
You can use mock data, and provide us the most simplified demo. If it works fine(with the mock data), maybe you should check the correctness of your data.

**Comment by afc163** [comment]
If you can't provide a reproducible demo, I am afaid we are not able to help you based on your decription.

**Comment by afc163** [comment]
close for no response
