### ISSUE TITLE
通过改变表单中某个下拉框的值动态改变表单中的FormItem

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#7069]
### Version
2.12.3

### Environment
windows64 chrome 57.0.2987.133 (64-bit)

### Reproduction link
[https://codepen.io/chj-damon/pen/KvgXNg?editors=0010](https://codepen.io/chj-damon/pen/KvgXNg?editors=0010)

### Steps to reproduce
1. 选择类型下拉框test1，出现字段下拉框，选择姓名；
2. 重新选择类型下拉框test2，出现字段下拉框和列表输入框，选择字段下拉框时控制台报错；

### What is expected?
字段下拉框可以选择

### What is actually happening?
控制台报错：
Uncaught TypeError: Cannot read property 'filter' of undefined
    at Object.getRules (VM1037 antd.js:33985)
    at VM1037 antd.js:34090
    at Array.forEach (<anonymous>)
    at Object.validateFieldsInternal (VM1037 antd.js:34077)
    at Object.onCollectValidate (VM1037 antd.js:33873)
    at Object.fireChange (VM1037 antd.js:81196)
    at Object.onMenuSelect (VM1037 antd.js:80779)
    at Object.onSelect (VM1037 antd.js:76930)
    at Object.onClick (VM1037 antd.js:77180)
    at Object.r (VM1035 react-dom.min.js:14)

**Comment by benjycui** [comment]
ComponentA 与 ComponentB 的 getFieldDecorator 的第一个参数用了同一个名字，id 必须唯一。

**Comment by chj-damon** [comment]
@benjycui 也就意味着我无法重用这个组件吗？

**Comment by chj-damon** [comment]
@benjycui 按道理来说，我选择test1和test2时在Form里面是不会同时出现field这个字段的，那为什么antd还会认为我的field不唯一呢？

**Comment by YuArtian** [comment]
@chj-damon 是不是用了switch case 语句来做判断？应该用 if

**Comment by HSunboy** [comment]
2.x 版本的同学可以看下这个方法。
https://github.com/react-component/form/pull/117#issuecomment-616281956

**Comment by anprettyboy** [comment]
It will be better to write your issue/comment in Chinese, so more people can understand you.
And this means that more people can help you or benefit from your issue/comment.
