### ISSUE TITLE
Broken align style in Dropdown.Button

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#7070]
### Version
2.12.3

### Environment
Windows 10.0.15063 & Chrome 60.0.3112.90

### Reproduction link
[https://codepen.io/hansnow/pen/JyROQG](https://codepen.io/hansnow/pen/JyROQG)

### Steps to reproduce
Just open the codepen link provided above.

### What is expected?
A normal horizontal align

### What is actually happening?
Broken align style

**Comment by afc163** [comment]
> Broken align style

Where is it?

<img width="177" alt="image" src="https://user-images.githubusercontent.com/507615/28908773-f73526b2-7857-11e7-9cef-e7c0a0fa899e.png">

**Comment by hansnow** [comment]
Why???!!! 😱
![image](https://user-images.githubusercontent.com/4365899/28908836-59952b2c-7858-11e7-89c9-572ee60bf725.png)

**Comment by afc163** [comment]
It is related to font-family, I am checking it.

**Comment by afc163** [comment]
broken via https://github.com/ant-design/ant-design/commit/a6037d66c0662ec6e2f2b5e3bf37e36bdb29a70e
