### ISSUE TITLE
Incorrect typings for notification?

### ISSUE THREAD

**Issue by DanHarman** [ant-design/ant-design#7073]
### Version
2.12.3

### Environment
windows, typescript 2.4.2

### Reproduction link
n/a - typings issue

### Steps to reproduce
use notification with standard api props:
        notification.error({
            description: "hello",
            duration: 0,
            message: "Title",
        });

### What is expected?
no build error.

### What is actually happening?
TS2345: Argument of type '{ description: ReactNode; duration: number; message: ReactNode; }' is not assignable to parameter of type 'ArgsProps'.
      Property 'type' is missing in type '{ description: ReactNode; duration: number; message: ReactNode; }'.

---
Looks like a required 'type' property was added to `ArgsProps` in `components/notification/index.tsx` with this commit:

https://github.com/ant-design/ant-design/commit/401519ec6fd263f4b0ccaf299889cc5568915c1d

This isn't in the docs and doesn't look like it should be required for users of the api.

**Comment by paranoidjk** [comment]
Welcome PR to help us fix it.

**Comment by marswong** [comment]
@afc163 is it necessary to add an unconfigurable `type` to the `ArgsProps`? I think the `ArgsProps.icon` is enough.

**Comment by afc163** [comment]
@yesmeck Why did we add `type` in 401519e?

**Comment by yesmeck** [comment]
TypeScript throw errors when compile...

**Comment by paranoidjk** [comment]
> TypeScript throw errors when compile...

TypeScript throw errors everyday 😄 

  I almost need to fix compile error every week...  upgrade deps etc... typescript, types/react types/react-native types/react-dom....

**Comment by afc163** [comment]
It seems to be good when I remove it.

**Comment by marswong** [comment]
``` javascript
['success', 'info', 'warning', 'error'].forEach((type) => {
  api[type] = (args: ArgsProps) => api.open({
    ...args,
    type,
  });
});
```
for **TypeScript** is static, maybe we cannot extend the interface dynamically 🙈

**Comment by DanHarman** [comment]
I had a look at the code and its an easy fix. The only issue I had is that I couldn't run the linter successfully and the test suite failed on a tonne of suites, which makes me uncomfortable to do a pull request.
