### ISSUE TITLE
Check if Message component visible

### ISSUE THREAD

**Issue by eldyvoon** [ant-design/ant-design#7074]
### Version
2.12.3

### Environment
Windows

### Reproduction link
[https://codesandbox.io/s/qLmJDVV3](https://codesandbox.io/s/qLmJDVV3)

### Steps to reproduce
https://codesandbox.io/s/qLmJDVV3 try to login in with random username and password, you shall see the error box appear, then change the filed, you shall see the Message box on every keypress

### What is expected?
Form component should work well with Message component

### What is actually happening?
Form Component rerender on keypress and there's no API to check whether the Message is visible or not so the Message keep appearing

**Comment by ddcat1115** [comment]
You can't call `messageBoxSuccess`/`messageBoxError` in the `render` function, it should be called only when you submit the form, for example, in the `handleSubmit`, according  to the parameter `err` passed by `validateFields`.

**Comment by eldyvoon** [comment]
@ddcat1115 if I call the message in event handlers, how can I display the message which most likely is passed from the server?

**Comment by ddcat1115** [comment]
You can certainly get the result in the ajax callback

**Comment by ddcat1115** [comment]
Actually I think it's about code logic, not relevant to antd usage, so I will close it ~
