### ISSUE TITLE
use yarn  and  npm  install  have difference

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design#7075]
### Version
2.12.2

### Environment
win10  

### Reproduction link
[https://github.com/zuiidea/antd-admin/issues/472](https://github.com/zuiidea/antd-admin/issues/472)

### Steps to reproduce
yarn  install
![1](https://user-images.githubusercontent.com/11306229/28949817-d4105d10-78f1-11e7-95b2-4ffc741d2d26.png)

，
npm install
![2](https://user-images.githubusercontent.com/11306229/28949820-d9a5f2b2-78f1-11e7-8ef0-6bf7a80ab16c.png)

### What is expected?
have  difference

### What is actually happening?
same

**Comment by afc163** [comment]
Try `yarn upgrade`, it is not a antd-related problem.
