### ISSUE TITLE
card component noHovering prop typo

### ISSUE THREAD

**Issue by xiaoyu-li** [ant-design/ant-design#7078]
### Version
2.12.3

### Environment
latest

### Reproduction link
[https://ant.design/components/card-cn/#Card](https://ant.design/components/card-cn/#Card)

### Steps to reproduce
docs typo

### What is expected?
see additional

### What is actually happening?
see additional

---
The default value for card prop noHovering is false, please double check that.

URL : https://ant.design/components/card-cn/#Card

参数	: noHovering
说明 :鼠标移过时是否浮起
类型	: boolean
默认值: true

**Comment by afc163** [comment]
Thx for reminding! ~ 😄
