### ISSUE TITLE
Tree组件onCheck(checkedKeys,e)中的checkedKeys能否在父节点下嵌套子节点的数组以体现父节点和子节点被选中时的关系

### ISSUE THREAD

**Issue by ppboyly** [ant-design/ant-design#7083]
### What problem does this feature solve?
父节点下字节点并非全部选取时，父节点会存在halfCheckedKeys里，而checkedKeys里没有父节点信息，只有子节点，导致父子节点不能对应清楚。修改后checkedKeys可以通过嵌套数组的形式体现节点的父子关系。这样在进一步操作时可以方便拿到整个Tree被选中的父子节点以及他们的对应关系

### What does the proposed API look like?
onCheck()里加入新的参数可以使用，通过新参数获得所有选择的父子节点数组，子节点可以嵌套在父节点中

**Comment by benjycui** [comment]
节点之间的父子关系组件不做记录，这个之前的 Menu 就讨论过类似问题了，最后还是让业务层自行处理。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1599
https://github.com/ant-design/ant-design/issues/1709
https://github.com/ant-design/ant-design/issues/3083

**Comment by guohuihuiguo** [comment]
写了这个方法后会把所有的input框都选中 而不是单个的  请大神指教一下onCheck = (v,e) => {
      console.log(v, e);
      let checkedKeys=[];
      let halfKey=e.halfCheckedKeys;
      if(halfKey.length){
          for (var i in halfKey) {
              if (halfKey.hasOwnProperty(i)) {
                  checkedKeys.push(halfKey[i]);
              }

          }
      }

      for (var i in v) {
          if (v.hasOwnProperty(i)) {
              checkedKeys.push(v[i]);
          }

      }
      console.log(checkedKeys);
      this.setState({checkedKeys});
    this.props.changeKeys(checkedKeys);
  };
