### ISSUE TITLE
The select component renders the data 2000-5000 difficult and slow

### ISSUE THREAD

**Issue by onlinelemon** [ant-design/ant-design#7086]
### Version
2.12.3

### Environment
windows、chrome

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
Render data list (2000-5000) ，or >5000

### What is expected?
Respond quickly to the web native control (select)

### What is actually happening?
slow

**Comment by marswong** [comment]
@onlinelemon the render function of components is synchronous and components doesn't control your state, you should control your bc logic. just try [debounce](https://lodash.com/docs/4.17.4#debounce)

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by onlinelemon** [comment]
5000 It takes seconds to expand, retract, and click. https://codepen.io/onlinelemon/pen/brqaqr

**Comment by onlinelemon** [comment]
@marswong It's not clear where to add debounce. view demo https://codepen.io/onlinelemon/pen/brqaqr

**Comment by marswong** [comment]
@onlinelemon refer to this [demo](https://ant.design/components/select/#components-select-demo-select-users), and never try to render all the data to Select.Option, u r just challenge the performance of JavaScript and make a bad design.

**Comment by onlinelemon** [comment]
@marswong Server query is a solution. But sometimes the server doesn't support it.
Antd 2000 will be slower. 
Native JS implementation is not slow.
Hopefully antd can optimize this

**Comment by johanbaath** [comment]
I'm having the same issue with lists of this size. Would be great if the performance could be optimized somehow :).

**Comment by codTango** [comment]
any updates on this? I actually have the similar issue in our product, which we have larger list (>10k items)

I'd appreciate that if `antd.select` supports infinite scroll or virtualized dropdown. The simplest solution I can think of is that `antd.select` supporting tracking viewport of the drop-down/popup area, then only display 20 | 50 items at a time, then I could know what's the current beginning and ending item id or number, then paginate and load new list of items, and remove the dom of list that is out of the current viewport.

@marswong possible to support this?

**Comment by onlinelemon** [comment]
@yesmeck Is it in progress?

**Comment by yesmeck** [comment]
Not yet.

**Comment by codTango** [comment]
@onlinelemon @yesmeck I'm wondering what will be the plan and ETA?

**Comment by tiffon** [comment]
A version 3.0.3 example with 2000 options.

https://codepen.io/anon/pen/eygNeR?editors=0010

Takes awhile to open and scrolling does not perform well.

(Side note: Ant Design is awesome, great work! :+1:)

**Comment by yesmeck** [comment]
Track in #3789

**Comment by chenxiaochun** [comment]
Excuse me, have any progress about this issue?

**Comment by pmjhonwang** [comment]
active pls
