### ISSUE TITLE
antdesign在google chrome下动画不流畅

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#709]
是否有优化空间？

**Comment by afc163** [comment]
例如？另外，我们特别欢迎 PR 。

**Comment by dyf2015** [comment]
collapse 比IE11慢些

**Comment by dyf2015** [comment]
大部分还是很OK的，感谢开源！

**Comment by benjycui** [comment]
Tree 的动画是用 velocity 实现的，DatePicker 的动画是用 CSS3 实现的，好像都不是我们可以优化的范围？

P.S. 需要统一动画的实现么？ @afc163

**Comment by afc163** [comment]
`不重要也不紧急`，先不折腾。

**Comment by afc163** [comment]
先把 collapse 的实现改为用 rc-animate 。

**Comment by benjycui** [comment]
现在就是用 rc-animate ....

https://github.com/react-component/collapse/blob/master/src/Panel.jsx#L3

**Comment by afc163** [comment]
用 Animate 的 transitionName 属性来实现。

**Comment by afc163** [comment]
看了下好像现在用的也是 transition ？那不应该卡啊...

**Comment by afc163** [comment]
close via https://github.com/react-component/collapse/commit/bb179d278b9a3d8071d230bc666168aa81671f54
