### ISSUE TITLE
Collapsible Header navigation

### ISSUE THREAD

**Issue by churcho** [ant-design/ant-design#7091]
### What problem does this feature solve?
I am looking to implement a top navigation only layout without the sidebar. The layout component currently doesn't collapse the nav links on the header. I would like to experiment with that kind of a layout option and free up the bottom part of my application without having a sidebar. The links would collapse to how the sidebar works on mobile size (based on media queries)

### What does the proposed API look like?
```
<Sider
    breakpoint="lg"
    collapsedWidth="0"
    onCollapse={(collapsed, type) => { console.log(collapsed, type); }}
  >
```
Extending this to work on the Menu

**Comment by afc163** [comment]
Sorry, no plan for now. You can try do it by youself.
