### ISSUE TITLE
1、不设置 defaultActiveKey 时，子元素变更会导致没有默认激活 tab；2、使用 React.Children.map 或 React.Children.toArray 处理后，不显示默认 tab

### ISSUE THREAD

**Issue by reoszo** [ant-design/ant-design#7093]
### Version
2.12.3

### Environment
windows 7、chrome 59

### Reproduction link
[https://codepen.io/anon/pen/KvNYjO?editors=0010](https://codepen.io/anon/pen/KvNYjO?editors=0010)

### Steps to reproduce
1、链接 demo 中 点击删除第一个 tab，会导致不焦点任何 tab（删除功能是模拟实际使用 tab 时，数据中 map 产生的 TabPane 变更）
2、demo 第二个 tab 设置的 defaultActiveKey 没有焦点，包装 Tabs 组件时，因为 key 属性特殊性，只能使用 forEach 进行 push 操作，不能使用 React.Children.map 和 React.Children.toArray，比较不爽

### What is expected?
1、没有设置 defaultActiveKey 和 activeKey 时永远焦点第一个 tab
2、使用非 key 作为 tab 的标识，例如 identity，虽然我也想不到更好的词，貌似 key 最贴切，但是它是 react 用于 diff 节点的

### What is actually happening?
1、Tabs children 变更后，没有焦点 tab
2、没有默认焦点 tab

---
可能考虑设计就是这样，虽然现在有这些缺陷

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/817

**Comment by reoszo** [comment]
key问题考虑开始设计问题，那就考虑一下第一个问题吧。。。
