### ISSUE TITLE
SubMenu not working with Sider (Layout) collapsible breakpoint

### ISSUE THREAD

**Issue by PrzemekPopowicz** [ant-design/ant-design#7095]
### Version
2.12.3

### Environment
Windows 10, Chrome and Firefox

### Reproduction link
[https://codepen.io/anon/pen/JybgZK?editors=0010](https://codepen.io/anon/pen/JybgZK?editors=0010)

### Steps to reproduce
Decrease width of browser window. Try to hover over User/Team when Sider is collapsed.

When Sider has breakpoint (to collapse on smaller screens) and is collapsed (screen width<breakpoint) the SubMenu (User/Team in example) is not showing on hover. On the other hand Menu.Item (File in example) shows ok in example.

### What is expected?
SubMenu shows on hover when Sider is collapsed 

<Sider collapsible breakpoint='xl' >

### What is actually happening?
SubMenu not shows on hover and shows badly on click (only for first time). After one click and one badly show it starts to show on hover. (it works without breakpoint='...')

---
http://pichoster.net/images/2017/08/05/158935fb9eee9e495f7a8bfa6bdde455.png

**Comment by afc163** [comment]
Duplicated and fixed in #7048
