### ISSUE TITLE
Need to show some message like popover when onRowMouseEnter or onRowMouseLeave fired!

### ISSUE THREAD

**Issue by jzoe** [ant-design/ant-design#7096]
### What problem does this feature solve?
I need to show user some information when onRowMouseEnter fired! This could be a message or record data.

需要在 onRowMouseEnter 事件触发时显示一个类似于 Popover 的消息框，这个消息框给出该行的数据或者其它信息。 

### What does the proposed API look like?
```javascript
  const handleMouseEnter = (record, index) => {
    <Popover content={record.msg}/>
  }
```

**Comment by ddcat1115** [comment]
In fact, we have supported it...

https://github.com/react-component/table#api  search by `onRowMouseEnter ` and `onRowMouseLeave`

**Comment by jzoe** [comment]
I have been see those APIs in the new version, my question is about how to render the the message like Popover in `onRowMouseEnter` and `onRowMouseLeave`  event handler !

**Comment by benjycui** [comment]
> my question is about how to render the the message like Popover in onRowMouseEnter and onRowMouseLeave event handler !

So, the Popover is for the whole row or just one cell?

**Comment by jzoe** [comment]
One cell Popover can write in column's render API, but i have never seen how to write a Popover for the whole row!

**Comment by benjycui** [comment]
> One cell Popover can write in column's render API, but i have never seen how to write a Popover for the whole row!

Just write in columns's render API, and use `visible` to control it.

```jsx
columns[n].render = <Popover visible={visible} />

onRowMounseEnter = () => visible = true;
```

**Comment by jzoe** [comment]
@benjycui It's a good solution in some case. But if i have 10 columns or more, maybe the `columns[n]` is not present in current window, and in such case, we cannot see the Popover any more!

If there is no other solution, maybe we could use the Table's `expandedRowRender` to show the full record information.

**Comment by benjycui** [comment]
> But if i have 10 columns or more, maybe the columns[n] is not present in current window, and in such case, we cannot see the Popover any more!

Fixed column.

**Comment by jzoe** [comment]
But i think the most elegant solution is that the table's `onRowMounseEnter` API support render() . So developer can use this API to show anything they want in a easy way! It's a pretty common, natural idea to show message through the `onRowMounseEnter`, isn't it?

**Comment by benjycui** [comment]
> But i think the most elegant solution is that the table's onRowMounseEnter API support render(). 

It is not elegant at all. Event handle is not a renderer. Think in React.

It's impossible to wrap table row with Popover now, unless Table expose new API cc @yesmeck 

So I think the only work around is https://github.com/ant-design/ant-design/issues/7096#issuecomment-320555648 now.

**Comment by jzoe** [comment]
Look forward the new API, thanks for your awesome work!! @benjycui @yesmeck

**Comment by yesmeck** [comment]
I like this idea https://github.com/react-component/table/issues/139, so that we don't need defined so many `onRowXxxx` events.
