### ISSUE TITLE
Use in commercial project

### ISSUE THREAD

**Issue by mcheung63** [ant-design/ant-design#7105]
### Version
2.12.4

### Environment
Mac, Safari 10.1.2

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
none

### What is expected?
none

### What is actually happening?
none

---
1. Can use ant-design in commercial project?
2. Your manager can do coding?

**Comment by OscarYuen** [comment]
I think this could help you.
[https://github.com/ant-design/ant-design/blob/master/LICENSE](url)
