### ISSUE TITLE
When the inline Menu is collapsed, style is abnormal if used MenuItemGroup.

### ISSUE THREAD

**Issue by cxyxc** [ant-design/ant-design#7109]
### Version
2.12.4

### Environment
win10、Chrome 59.0.3071.115

### Reproduction link
[https://codepen.io/anon/pen/gxgeea?editors=0010](https://codepen.io/anon/pen/gxgeea?editors=0010)

#### used Menu.ItemGroup and inlineCollapsed = true

```html
<Menu
    mode="inline"
    theme="dark"
    inlineCollapsed={this.state.collapsed}>
    <Menu.ItemGroup title="标题标题标题标题标题标题">
    <Menu.Item key="1">
        <Icon type="pie-chart" />
        <span>Option 1</span>
    </Menu.Item>
    <Menu.Item key="2">
        <Icon type="desktop" />
        <span>Option 2</span>
    </Menu.Item>
    <Menu.Item key="3">
        <Icon type="inbox" />
        <span>Option 3</span>
    </Menu.Item>
    </Menu.ItemGroup>
</Menu>
```

### What is expected?
I need a normal Menu with a folding style after using Menu.ItemGroup.

### What is actually happening?
When the inline Menu is collapsed, style is abnormal if used MenuItemGroup.

**Comment by nikogu** [comment]
what does `abnormal ` mean? can you describe it with screenshot？ @cxyxc

**Comment by cxyxc** [comment]
## inlineCollapsed=false
![image](https://user-images.githubusercontent.com/20027281/29010260-829c2820-7b5c-11e7-8b70-c29141d68af6.png)

## inlineCollapsed=true 
![image](https://user-images.githubusercontent.com/20027281/29010284-a2d64954-7b5c-11e7-9075-4651d153f837.png)

**Comment by afc163** [comment]
Sorry for fixing it lately.

**Comment by cxyxc** [comment]
Thanks a lot!
