### ISSUE TITLE
Checkbox component miss e.nativeEvent.

### ISSUE THREAD

**Issue by elowes** [ant-design/ant-design#7111]
### Version
2.12.4

### Environment
macOS 10.12.6

### Reproduction link
[https://codepen.io/kaijunhe/pen/oeBywo](https://codepen.io/kaijunhe/pen/oeBywo)

### Steps to reproduce
Checkbox onChange event cannot get e.nativeEvent (return undefined)

### What is expected?
get the correct native event.

### What is actually happening?
undefined

**Comment by benjycui** [comment]
ref: https://github.com/react-component/checkbox/issues/30

**Comment by benjycui** [comment]
Use case?

**Comment by elowes** [comment]
不需要了，我发现 Popconfirm 这个组件可以满足我的需求:)
