### ISSUE TITLE
建议sider导航菜单增加收起和展开功能

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design#712]
左侧导航菜单占据了较大宽度，对于展现信息量的业务画面，容易出现水平滚动条，建议增加收起和展开功能。
（阿里云后台管理参考)
![aliyun](https://cloud.githubusercontent.com/assets/12553638/11921191/ca214216-a7be-11e5-8c6f-76c69b8601cc.png)

**Comment by afc163** [comment]
可以先自行实现，导航作为基础元件暂不加入进一步的复杂交互。感谢建议！

不排除以后加上这一功能，或用最佳实践的方式给出。
