### ISSUE TITLE
Dropdown lose width after rendering

### ISSUE THREAD

**Issue by marswong** [ant-design/ant-design#7124]
### Version
2.12.4

### Environment
macOS 10.12.6, Chrome 60

### Reproduction link
[https://codepen.io/marswong/pen/zdNyzV?&editors=001](https://codepen.io/marswong/pen/zdNyzV?&editors=001)

### Steps to reproduce
Just select the Dropdown menu element by DevTools

### What is expected?
``` html
<div class="ant-dropdown  ant-dropdown-placement-bottomCenter  ant-dropdown-hidden" style="left: 22px; top: 56px; width: 90.5px;">
```

### What is actually happening?
``` html
<div class="ant-dropdown  ant-dropdown-placement-bottomCenter  ant-dropdown-hidden" style="left: 22px; top: 56px;">
```

---
before antd@2.12.3, Dropdown would set a width style to the Dropdown overlay's root container, so that the overlay's width is equal to the Dropdown Element's. While since antd@2.12.3, the root container lose the `width` property of style, which makes the overlay unharmonious.

**Comment by afc163** [comment]
Fixed in `2.12.5`.
