### ISSUE TITLE
如果父节点设置了行高，InputNumber 和 RangePicker 样式会错乱

### ISSUE THREAD

**Issue by zzh-a** [ant-design/ant-design#7126]
### Version
2.12.4

### Environment
win7，  chrome 版本 59.0.3071.115（正式版本） （64 位）

### Reproduction link
[https://codepen.io/anon/pen/EvZrJw?editors=0010](https://codepen.io/anon/pen/EvZrJw?editors=0010)

### Steps to reproduce
https://codepen.io/anon/pen/EvZrJw?editors=0010

### What is expected?
正常显示

### What is actually happening?
样式错乱

**Comment by nikogu** [comment]
i think you can reset the components line height by this way.

```jsx
<div style={{lineHeight: '60px'}}>
    <InputNumber style={{lineHeight: '1.5'}} min={1} max={10} defaultValue={3} />
</div>
```

and we can discuss that is necessary to specified the component's line height ?

**Comment by afc163** [comment]
They have been fixed in https://github.com/ant-design/ant-design/commit/5a3377423899f593f8f98d4d44767bdd6e6ab85c and https://github.com/ant-design/ant-design/commit/e3b6430a4b23b2e6c24c74e23d26f1b454c9cd42, wait for next patch.
