### ISSUE TITLE
关于select默认值的问题

### ISSUE THREAD

**Issue by kivenZhou** [ant-design/ant-design#7127]
### What problem does this feature solve?
因为做一个单向联动效果，选择第一个选项的时候需要清空第二个select的值，让第二个值默认为空，如果第二个以前选中过，那么值还是上次选择的，但是下拉框里面没有这个值

### What does the proposed API look like?
有没有什么方法可以清空上次选中的值？

**Comment by afc163** [comment]
`value`

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by kivenZhou** [comment]
感谢，当时没注意到这个value属性，没想到还真有这个属性！谢谢！ @afc163
