### ISSUE TITLE
树型数据表格rowSelection不支持子树部分的全选功能

### ISSUE THREAD

**Issue by suntenghub** [ant-design/ant-design#7130]
### What problem does this feature solve?
使用场景：嵌套的树型数据展示表格，带有行多选框rowSelection，目前当子节点选中时，只有整个表格全选框显示"-"状态，对应树形结构父节点不显示"-"状态；且选中某一父节点时，其所有子节点不能被全选中。
如[示例](https://codepen.io/suntenghub/pen/wqJJBJ) 选中Jim Green jr.此行后，Jim Green所在行的checkbox没变为“-”，选中Jim Green，Jim Green jr.和Jimmy Green sr.也不能自动全选中

### What does the proposed API look like?
按照树状结构，实现rowselection选择树形数据某一行时，（1）全选其所有子节点（2）上级父节点根据子节点选中状态显示全选或者"-"状态

**Comment by benjycui** [comment]
@yesmeck 其实这种使用场景，还是推荐用受控模式实现？不然 rc-table 就要实现 rc-tree 里面的选中逻辑了。

**Comment by yesmeck** [comment]
1. 可以自己用受控模式实现；
2. 比较麻烦，暂时不会在 rc-table 里加这种逻辑。
