### ISSUE TITLE
doesn't work well with webpack.optimize.ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by lili21** [ant-design/ant-design#7131]
### Version
antd@2.12.5

### Environment
macOS Sierra 10.12.5,  Chrome 60.0.3112.90, react@15.6.1, react-dom@15.6.1

### Reproduction link
[https://github.com/lili21/antd-issue](https://github.com/lili21/antd-issue)

### Steps to reproduce
1. `yarn`
2. `npm start`
3.  open browser devtools
4. modify `src/components/App.js`, waiting for browser reload.

### What is expected?
nothing broken.

### What is actually happening?
everything is broken.

**Comment by lili21** [comment]
![antd-issue-iloveimg-compressed](https://user-images.githubusercontent.com/4456380/29055936-24bf2c80-7c32-11e7-953d-33fe33c4434f.gif)

**Comment by stevewillard** [comment]
I have the same issue. I will try to put together a small reproducible example.

**Comment by afc163** [comment]
babel-plugin-import is not compatible with `ModuleConcatenationPlugin`. Don't use it and import styles manually.

https://github.com/lili21/antd-issue/pull/1

**Comment by lili21** [comment]
will `babel-plugin-import` be compatible with `ModuleConcatenationPlugin`?
