### ISSUE TITLE
Title property for Select.Option doesn't work 

### ISSUE THREAD

**Issue by ihorml** [ant-design/ant-design#7138]
### Version
2.12.5

### Environment
OSX, Chrome (doesn't matter)

### Reproduction link
[https://paste.ofcode.org/e2qpaVdrJKgumAzTKvBQYy](https://paste.ofcode.org/e2qpaVdrJKgumAzTKvBQYy)

### Steps to reproduce
1. Click on select
2. Select A
3. You will see the select title is `A` except `Aa`

### What is expected?
1. Click on select
2. Select A
3. The title of select is `Aa`

### What is actually happening?
Select gets option value for title except using `title` property of Select.Option

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
https://codepen.io/anon/pen/JyWZMW?&editors=001

It works.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/507615/29071937-55774c72-7c78-11e7-9815-ec4bf37d4ee4.png">

**Comment by ihorml** [comment]
@afc163 I was confused about this property functions... how can I display `xxxx` when you click on `Lucy` ?

**Comment by afc163** [comment]
The `title` of Option is just like the `title` of div: `<div title="title">xxx<div>`.

---

> how can I display xxxx on select value when you click on Lucy ?

Just change the children of Option.

```
<Option value="xx">whatever you want to display</Option>
```

**Comment by ihorml** [comment]
@afc163 the problem is to have different from options children placeholders. 

when user select the following `option`:
`<Option value="a">A</Option>`.

I want to see select with placeholder (selected value)`A12345`. How can I have different display values from the options children?

**Comment by afc163** [comment]
Try `optionLabelProp`

**Comment by lvlephistophele** [comment]
Hello!

1. In my typescript project i got an error:
`TS2339: Property 'title' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, ComponentState>> & Readonly...'.
webpack: Failed to compile.`

2. I need an option title property because of it's bug. When a children of option component is another React Node (for example a react-router Link), a title showes as [object Object] 

[codepen example](https://codepen.io/anon/pen/YxLMJG?editors=0010)

**Comment by Dergash** [comment]
@ghost and anyone who still encountered this problem, current documentation for v. 2.3.11 states that Select.Option provides "title" property; we are running 2.12.1 and have the same problem with incorrect tooltip and typescript warning.
It can be solved by passing 'title' property not directly but with a spread operator:
```js
// typescript warning
<Select.Option title="custom title" />
```
```js
// no typescript warning
const titleFix = { title: "custom title" }
<Select.Option {...titleFix} />
```

I don't know if documentation wrong on this or title prop was added to OptionProps after 2.12.1, it seems that there is no mention of it in changelog

**Comment by Nosnickers** [comment]
When using options property, add title to the obj
![image](https://user-images.githubusercontent.com/8192906/87122111-cc8f4800-c2b6-11ea-8abb-cdbedf5cade7.png)

it will pop up tooltip
