### ISSUE TITLE
Let wrap Table.Column

### ISSUE THREAD

**Issue by ramiel** [ant-design/ant-design#7139]
### What problem does this feature solve?
I want to wrap Table.Column in order to export a component which is a column with a predefined behavior. This look impossible. Is there a way to do it?

### What does the proposed API look like?
It would be nice to have or

```js
class SortedColumn extends React.Component{
 render(){
  return <Column sorter={...} />
 }
}
```

or extending directly from Table.Column and change the props.sorter in constructor

**Comment by ramiel** [comment]
I think it's related to this #4853

**Comment by yesmeck** [comment]
Trace in #4853
