### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#714]
相似的 issue 不少，计划添加 [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) 缓和这个问题。

内容大概包括：

1. 引导用户查看 FAQ（待编写）。
1. 对于 FAQ 没有的问题，建议用户先搜索一下 issue。
1. 以上两个方法都找不到，则按我们建议的格式提 issue。

暂时只想到这些。

**Comment by afc163** [comment]
直接写成英文好了，国人不怎么看这个的。

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md

FAQ 要晚些时候才有空写了，而且也需要长期逐步完善，issue 先关。
