### ISSUE TITLE
Allow preset date choices on non-range DatePicker

### ISSUE THREAD

**Issue by davidmcooper** [ant-design/ant-design#7140]
### What problem does this feature solve?
A common feature of many date pickers is to provide quick one-click access to preset values.  The Ant Design date-range picker supports this, but I feel it's a feature which should be supported with the single DatePicker as-well.  The use-case for this is that the end-user should be able to choose a preset date by clicking a shortcut.  This is very useful for quick selection of "Beginning of Year", "End of Year", "One Week Ago", etc. and would make the single date picker consistent with the date range picker.

This use case is very common when working with financial sites, and showing performance values over well defined periods of time.  You frequently want to specify a "from" date with a preset "from" relative to the financial data you're looking at.

### What does the proposed API look like?
The API could look similar to the date range API except instead of two dates being passed, a single date could be defined for each preset value.

```
presets={{ Today: [moment()], 'End of Month': [moment().endOf('month')], 'Beginning of Year': [moment().beginningOf('year')] }
```

**Comment by benjycui** [comment]
Nope, just use extra footer https://ant.design/components/date-picker/#components-date-picker-demo-extra-footer

**Comment by davidmcooper** [comment]
Ah, had overlooked that. Thanks.
