### ISSUE TITLE
When datasource is empty ant set scroll in x at table component,the scrollbar should under the table, not under the table header

### ISSUE THREAD

**Issue by renhe1990** [ant-design/ant-design#7142]
### Version
2.12.5

### Environment
window 7 、chrome 59.0.3071.115

### Reproduction link
[https://codepen.io/renhe1990/pen/vJmEMy](https://codepen.io/renhe1990/pen/vJmEMy)

### Steps to reproduce
1.create an empty table component.
2.set scroll={x:50000}  (the width greater than screen width)

### What is expected?
the scrollbar should under the table

### What is actually happening?
the scrollbar under the table header

**Comment by afc163** [comment]
I think scrollbar should not display when there is no data.

**Comment by qq645381995** [comment]
@afc163  2.12.6  It still doesn't show the scroll bar

**Comment by qq645381995** [comment]
？

**Comment by afc163** [comment]
What's your problem? Please file a new issue by http://new-issue.ant.design/

**Comment by qq645381995** [comment]
When there is no data, it is not very nice to have a list

**Comment by qq645381995** [comment]
When there is no data, the width of the column is vertical and not good

**Comment by afc163** [comment]
I will revert the fix of this issue due to https://github.com/ant-design/ant-design/issues/7298 and https://github.com/react-component/table/issues/163

**Comment by L1nY4n** [comment]
![image](https://user-images.githubusercontent.com/20768106/30698134-9af34a04-9f13-11e7-8f6a-e0eddd06d378.png)To filter the list, I add a condition in one columns in view which is scrolled ,when no data show ,I can't  scroll  right to change  or remove the conditions,  To solve this, I add a tag block to show conditions which can be removed.
![image](https://user-images.githubusercontent.com/20768106/30698761-74fe0b34-9f15-11e7-97c9-e94e34e65688.png)  @qq645381995 

I think scrollbar is  in need @afc163

**Comment by afc163** [comment]
Sorry, scrollbar for empty data is hard to implement and bring a lot of other issues.

**Comment by L1nY4n** [comment]
Actually I render a select component in each columns(more than 20),  I think it's  not the problem of render position.
Thank you for response and I would try other way. (Maybe add item to show empty in datalist  and using colSpan props)

**Comment by yixuanwang26** [comment]
![image](https://user-images.githubusercontent.com/20641215/37512210-70e9a63c-293c-11e8-923b-5cb8a6cff9a1.png)
When datasource is empty, the  scrollbar is under the table header..

**Comment by fanshipi** [comment]
> ![image](https://user-images.githubusercontent.com/20641215/37512210-70e9a63c-293c-11e8-923b-5cb8a6cff9a1.png)
> When datasource is empty, the scrollbar is under the table header..

Have you solved the problem？
