### ISSUE TITLE
use Upload  up file to aliyun-oss

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design#7143]
### Version
2.12.5

### Environment
win10

### Reproduction link
[https://ant.design/components/upload/](https://ant.design/components/upload/)

### Steps to reproduce
use upload  up file to aliyun-oss
use api onChange (file)   this file is not  a  File?    
![h 4ug bkutguo whvw9r00](https://user-images.githubusercontent.com/11306229/29102749-d58f08da-7ced-11e7-843d-55ec3ac65de4.png)

### What is expected?
success  

### What is actually happening?
error

**Comment by benjycui** [comment]
Ref: https://github.com/ant-design/ant-design/issues/5737
