### ISSUE TITLE
checkbox只能选择一个互相是排斥的

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#7147]
### Version
2.12.5

### Environment
chrome macOS Sierra

### Reproduction link
[https://codepen.io/nai6514531/pen/PKmPjr](https://codepen.io/nai6514531/pen/PKmPjr)

### Steps to reproduce
当模态框数据变化是checkbox只能单选。不清楚问题出在哪里

### What is expected?
数据变化时可以多选checkbox

### What is actually happening?
数据变化时不可以多选checkbox

**Comment by nai6514531** [comment]
![wechatsight5](https://user-images.githubusercontent.com/13310359/29104842-812564b6-7cfb-11e7-9446-cdd17867ad2d.gif)
这个是演示

**Comment by yesmeck** [comment]
Use `CheckboxGroup`.

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by nai6514531** [comment]
when use CheckboxGroup,it seems ok, but use from and checkbox,pageData changed,it is invaild

**Comment by benjycui** [comment]
> https://codepen.io/nai6514531/pen/PKmPjr

@nai6514531 your CodePen doesn't work, please provide a re-producible online demo.
