### ISSUE TITLE
InputNumber validate failed, but I did not write any validate code

### ISSUE THREAD

**Issue by eruca** [ant-design/ant-design#7149]
### Version
2.10.2

### Environment
mac os lastest chrome 60

### Reproduction link
[https://codepen.io/eruca/pen/qXmZVR?editors=0010](https://codepen.io/eruca/pen/qXmZVR?editors=0010)

### Steps to reproduce
输入一个数字，就报错误

### What is expected?
不知道哪里触发了validator

### What is actually happening?
no comment

**Comment by afc163** [comment]
默认校验规则是 `type: 'string'`，InputNumber 返回的值是数字。
