### ISSUE TITLE
更新2.12.5

### ISSUE THREAD

**Issue by yiranlee** [ant-design/ant-design#7153]
### Version
2.12.5

### Environment
chorme

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
table 里面的分页器报错Uncaught TypeError: Cannot set property 'handleClick' of undefined
    at Pager ，

undefined.handleClick = function () {
	    props.onClick(props.page);
	  };
	
	  undefined.handleKeyPress = function (e) {
	    props.onKeyPress(e, props.onClick, props.page);
	  };

 出现了两个undefined；
我的代码：
<Table bordered rowSelection={ rowSelection } pagination={ true } columns={ columns } dataSource={ this.state.dataSource } onRowClick={ this.onRowClick }
              rowKey={ record => record.id } 
              scroll={{ x: '150%'}}/>

const pagination = {
      showSizeChanger: true,
      showQuickJumper: true,
      showTotal: (total) => `总共${this.state.total}条`,
      total: this.state.total,
      onShowSizeChange: this.page,
      onChange: this.page,
    };

只要把pagination 设为 false 就不报错

### What is expected?
不应该报错，

### What is actually happening?
一直爆这样的错

**Comment by yiranlee** [comment]
别看标题呀  不是更新，是更新后的问题

**Comment by paranoidjk** [comment]
底层依赖 bug，已修复。图片是请你重装依赖即可。

**Comment by yiranlee** [comment]
我就是重装了依赖才过来问的 ，你们今天才修复的吗 ？我今天中午重装了两次了 还是这个问题

**Comment by afc163** [comment]
Fixed in `rc-pagination@1.10.6`.

**Comment by yiranlee** [comment]
rc-pagination@1.10.6 发布npm 上了吗？  我怎么查不到 ，麻烦了

**Comment by afc163** [comment]
别这样：https://www.npmjs.com/package/rc-pagination
