### ISSUE TITLE
Fix open/close icon missing issue of TreeSelect

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#7154]
### Version
2.12.5

### Environment
macOs, chrome

### Reproduction link
[https://ant.design/components/tree-select/](https://ant.design/components/tree-select/)

### Steps to reproduce
after upgrading to version 2.12.5 the open/close icon is missing from treeSelect

### What is expected?
to see open/close icon on treeSelect

### What is actually happening?
empty open/close icon on treeSelect

---
the icon is marked with class "ant-select-tree-noline_close" and "ant-select-tree-noline_open", but no such selector is present on the css.
I have found the old selector "ant-select-tree-switcher_close" and "ant-select-tree-switcher_open", and by overriding that class name with "ant-select-tree-noline_close" and "ant-select-tree-noline_open" it work again.

**Comment by afc163** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/507615/29115131-085542f8-7d29-11e7-8f84-3257fae21047.png">

Works in demo page. Please provide a reproducible demo for your problem.

**Comment by afc163** [comment]
It works fine in my machine so you are better to create a reproducible repo for your problem.

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by weirDozzz** [comment]
i have same problem, because a commit [https://github.com/ant-design/ant-design/commit/63c3c7c88f921a82bc8d514548e909465ae700e8#diff-9e0ab30a07b8d2639f7d6c331ea60309](url) make this problem, downgrade version to <2.12.3 will be fixed!!!
