### ISSUE TITLE
select support select/deselect all

### ISSUE THREAD

**Issue by sunshiner** [ant-design/ant-design#7155]
### What problem does this feature solve?
in multiple select mode,  when the option is more than ten, one by one select efficiency is very low, so i wish has a quick select/deselect function just like [bootstrap-select](https://codepen.io/sunshiner/pen/YxVNVJ)

### What does the proposed API look like?
```
<Select
        mode="multiple"
        selectControl={true/false(default)}
      >
</select>
```

**Comment by benjycui** [comment]
```jsx
<Select>
  <Option>Select All</Option>
</Select>
```

**Comment by benjycui** [comment]
Online demo: https://codepen.io/anon/pen/LjzpRR?editors=0010

```jsx
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { Select, version } = antd;
const Option = Select.Option;

class SelectDemo extends React.Component {
  state = { value: [] };
  handleChange(value) {
    if (value.includes('all')) {
      this.setState({ value: ['1', '2', '3'] });
    } else {
      this.setState({ value });
    }
  }
  render() {
    return (
      <Select
        mode="multiple" style={{ width: 100 }}
        value={this.state.value}
        onChange={this.handleChange.bind(this)}
      >
        <Option value="all">Select All</Option>
        <Option value="1">1</Option>
        <Option value="2">2</Option>
        <Option value="3">3</Option>
      </Select>
    );
  }
}

ReactDOM.render(
  <div>
    <p className="version">antd version: {version}</p>
    <SelectDemo />
  </div>
, mountNode);
```

**Comment by tim-soft** [comment]
How could this be implemented with `getFieldDecorator`? The values change on the field but the select UI doesn't update to reflect the changes

**Comment by DongShi** [comment]
Having a similar problem here about 'clear all'....
Seen from the doc, we have an '[allowClear](https://ant.design/components/select-cn/#header)' option which is to show a inline span with 'x' to the right of the option (works for multiple mode as well).

Is it possible to expose a method on Select to hook the click event on this span, just like in [rc-select](https://github.com/react-component/select/blob/34b459a2036e730fbb9e02e7bf8f3a1533c64419/src/Select.jsx#L374)?

It makes sense to treat the clear all as a special senario, I think.

@benjycui, your thoughts?

**Comment by mojjy** [comment]
> How could this be implemented with `getFieldDecorator`? The values change on the field but the select UI doesn't update to reflect the changes

Instead of keeping state, one could use
` this.props.form.setFieldsValue({fieldName:allValues})`
inside the onClick handler,

**Comment by renjiie** [comment]
@mojjy All values as an array of strings right?

**Comment by mojjy** [comment]
> @mojjy All values as an array of strings right?

yes

**Comment by bytetang** [comment]
found the [TreeSelect](https://ant.design/components/tree-select/),]  exmple,https://codesandbox.io/s/ant-design-tree-select-select-all-dnekz?file=/index.js

**Comment by ManojBahuguna** [comment]
I created a custom hook for convenience.

demo: https://codesandbox.io/s/select-with-all-option-hoxxyk?file=/src/App.js

```js
function useSelectAllOption(options) {
  const optionsWithAllOption = useMemo(() => [SELECT_ALL_OPTION, ...options], [
    options
  ]);

  /** pass this to Form.Item's getValueFromEvent prop */
  const getValueFromEvent = useCallback(
    (value, selections) => {
      if (!selections?.length) return selections;
      if (!selections?.some((s) => s.value === SELECT_ALL_OPTION.value)) {
        return selections;
      }
      const labelInValue = typeof value[0]?.label === "string";
      // if "Select All" option selected, set value to all options
      // also keep labelInValue in consideration
      return labelInValue ? options : options.map((o) => o.value);
    },
    [options]
  );

  return [getValueFromEvent, optionsWithAllOption];
}
```

usage:
```js
const [getValueFromEvent, optionsWithAllOption] = useSelectAllOption(options);

return (
    <Form>
      <Form.Item
        getValueFromEvent={getValueFromEvent}
        name="selectWithAllOption"
        label={'Select with "All" option'}
      >
        <Select allowClear mode="multiple" options={optionsWithAllOption} />
      </Form.Item>
    </Form>
);
```

**Comment by reme3d2y** [comment]
```tsx
import { Button, SelectProps } from "antd";
import React, { useCallback, useMemo } from "react";

export function useSelectAll({
    showSelectAll = true,
    options = [],
    value,
    onChange,
}: { showSelectAll?: boolean } & SelectProps) {
    const handleSelectAll = useCallback(() => {
        onChange?.(
            options.map((option) => option.value),
            options
        );
    }, [onChange, options]);

    const handleUnselectAll = useCallback(() => {
        onChange?.([], []);
    }, [onChange]);

    const enchancedOptions = useMemo(() => {
        if (!showSelectAll) return options;

        return [
            {
                label: !value?.length ? (
                    <Button type="link" onClick={() => handleSelectAll()}>
                        Select All
                    </Button>
                ) : (
                    <Button type="link" onClick={() => handleUnselectAll()}>
                        Unselect All
                    </Button>
                ),
                options,
            },
        ];
    }, [handleSelectAll, handleUnselectAll, options, showSelectAll, value?.length]);

    return {
        options: enchancedOptions,
        value,
        onChange,
    };
}
```

```tsx
const selectProps = useSelectAll({
        showSelectAll: true,
        value,
        onChange,
        options: [
            {
                label: "Label 1",
                value: "value 1",
            },
            {
                label: "Label 2",
                value: "value 2",
            },
        ],
    });

return <Select {...selectProps} />;
```

<img width="397" alt="image" src="https://user-images.githubusercontent.com/9968618/225815988-8c42ebdb-d7ee-4064-859a-d7e85da40edc.png">

**Comment by ghasemikasra39** [comment]
> ```tsx
> import { Button, SelectProps } from "antd";
> import React, { useCallback, useMemo } from "react";
> 
> export function useSelectAll({
>     showSelectAll = true,
>     options = [],
>     value,
>     onChange,
> }: { showSelectAll?: boolean } & SelectProps) {
>     const handleSelectAll = useCallback(() => {
>         onChange?.(
>             options.map((option) => option.value),
>             options
>         );
>     }, [onChange, options]);
> 
>     const handleUnselectAll = useCallback(() => {
>         onChange?.([], []);
>     }, [onChange]);
> 
>     const enchancedOptions = useMemo(() => {
>         if (!showSelectAll) return options;
> 
>         return [
>             {
>                 label: !value?.length ? (
>                     <Button type="link" onClick={() => handleSelectAll()}>
>                         Select All
>                     </Button>
>                 ) : (
>                     <Button type="link" onClick={() => handleUnselectAll()}>
>                         Unselect All
>                     </Button>
>                 ),
>                 options,
>             },
>         ];
>     }, [handleSelectAll, handleUnselectAll, options, showSelectAll, value?.length]);
> 
>     return {
>         options: enchancedOptions,
>         value,
>         onChange,
>     };
> }
> ```
> 
> ```tsx
> const selectProps = useSelectAll({
>         showSelectAll: true,
>         value,
>         onChange,
>         options: [
>             {
>                 label: "Label 1",
>                 value: "value 1",
>             },
>             {
>                 label: "Label 2",
>                 value: "value 2",
>             },
>         ],
>     });
> 
> return <Select {...selectProps} />;
> ```
> 
> <img alt="image" width="397" src="https://user-images.githubusercontent.com/9968618/225815988-8c42ebdb-d7ee-4064-859a-d7e85da40edc.png">

Can you please also show how your `onChange` method look like and how you're handling the `value`?
