### ISSUE TITLE
Tabs 和 Table的筛选菜单一起使用出现异常

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#7157]
### What problem does this feature solve?
方便用户使用

### What does the proposed API look like?
能符合需求

![qq 20170809175736](https://user-images.githubusercontent.com/18378998/29116108-6bea7448-7d2c-11e7-8ab4-0af7d1ad459b.png)
因为搜索框的显示与隐藏是改变state控制的，在我切换tab后，点击搜索框，两个pane的框都出现了，目前我了解的解决这个问题只能根据不同的tab维护不同的控制搜索框显示与隐藏的state，增加了额外的重复代码量，当tab在好几个的时候，不太方便，有没有什么别的办法？

**Comment by afc163** [comment]
多个浮层的显示状态应该用多个 state 来维护，复用 state 是不合理的。
