### ISSUE TITLE
doesn't work well with `uglifyjs-webpack-plugin`

### ISSUE THREAD

**Issue by lili21** [ant-design/ant-design#7158]
### Version
2.12.5

### Environment
macOS Sierra 10.12.5, Chrome 60.0.3112.90, react@15.6.1, react-dom@15.6.1

### Reproduction link
[https://github.com/lili21/antd-issue](https://github.com/lili21/antd-issue)

### Steps to reproduce
1. `yarn`
2. `npm run serve`
3. visite `http://localhost:5000`
3.  open browser devtools

### What is expected?
no error

### What is actually happening?
![2017-08-09 7 14 21](https://user-images.githubusercontent.com/4456380/29119745-f9e9dda8-7d39-11e7-9a75-27ff6c692a73.png)

I can fix the problem temporarily by updating `UglifyJSPlugin` config like below,

```
new UglifyJSPlugin({
      uglifyOptions: {
        ecma: 5,
        compress: {
          warnings: false
        }
      },
      sourceMap: true
    })
```

**Comment by afc163** [comment]
[create-react-class](https://unpkg.com/create-react-class@15.6.0) which is not es6 syntax will cause this problem.

Consider replace it with https://github.com/brigand/react-mixin

- [ ] rc-trigger
- [ ] rc-form
- [ ] rc-calendar

**Comment by benjycui** [comment]
@paranoidjk and then, `object-assign` is here again https://github.com/brigand/react-mixin/blob/master/index.js#L2

😢

**Comment by paranoidjk** [comment]
Actually, i did't understand why none es6 syntax cause problem ?

Do you mean uglifyjs do not support compress es6 syntax? Then we can convert it to es5 with babel first?

**Comment by benjycui** [comment]
The problem may be uglify-es doesn't support non-es2015 module.

**Comment by afc163** [comment]
Check https://github.com/afc163/antd-issue/tree/issue-7158

```
npm install
npm run serve
```

Visit http://localhost:5000 and see console.

**Comment by benjycui** [comment]
@afc163 I try the following code locally: 

```jsx
import React from 'react'
import createReactClass from 'create-react-class'

const AppCreateClass = createReactClass({
  render() {
    return <div>AppCreateClass</div>
  },
})

function AppFunction() {
  return <div>AppFunction</div>;
}

class AppClass extends React.Component {
  render() {
    return <div>AppClass</div>;
  }
}

export default AppCreateClass;
```

Not only AppCreateClass, but also AppFunction and AppClass will cause the same error when we turn UglifyJSPlugin on.

**Comment by afc163** [comment]
Nope, just create-react-class. Try to remove importing `create-react-class`.

**Comment by benjycui** [comment]
OK, I understand. The following works, but I think this will be an issue of `create-react-class`?

```jsx
import React from 'react'
// import createReactClass from 'create-react-class'

// const AppCreateClass = createReactClass({
//   render() {
//     return <div>AppCreateClass</div>
//   },
// })

function AppFunction() {
  return <div>AppFunction</div>;
}

class AppClass extends React.Component {
  render() {
    return <div>AppClass</div>;
  }
}

export default AppFunction;
```

**Comment by benjycui** [comment]
In [create-react-class](https://unpkg.com/create-react-class@15.6.0/factory.js), there are the following code: 

```jsx
var ReactClassComponent = function() {};
_assign(
  ReactClassComponent.prototype,
  ReactComponent.prototype,
  ReactClassMixin
);
```

This works fine. However, after `uglify-es`, it becomes something like this:

```jsx
var x = ()=>{};
r(x.prototype, e.prototype, w);
```

And there is no `prototype` in arrow function:

```bash
➜  ~ node
> var t = function() {}
undefined
> t.prototype
t {}
> var a = () => {}
undefined
> a.prototype
undefined
```

So, `create-react-class`'s code becomes: 

```jsx
_assign(
  undefined, // !!!!
  ReactComponent.prototype,
  ReactClassMixin
);
```

**Comment by afc163** [comment]
https://github.com/mishoo/UglifyJS2/issues/2271

**Comment by benjycui** [comment]
So, just close now, not antd's issue.

**Comment by lili21** [comment]
@afc163 @benjycui Thanks. You guys are amazing. great work and keep going.
