### ISSUE TITLE
Can't resolve 'antd/lib/column-group, Can't resolve 'antd/lib/column-group/style

### ISSUE THREAD

**Issue by burhanmubarok** [ant-design/ant-design#7160]
### Version
2.12.5

### Environment
ubuntu 17.04, react 15.6.1, webpack 3.4.1

### Reproduction link
[none](https://github.com/ant-design/ant-design/issues/None)

### Steps to reproduce
1. using webpack
2. using less loader
3. configure  .babelrc
```
  ....
  "plugins": [
    ["import", {
      "libraryName": "antd",
      "style": true
    }]
  ]
```
4. use antd Table component
5. build project with webpack

### What is expected?
it should load js and less file from folder "node_modules/antd/lib/column-group", but no folder at it's path.

### What is actually happening?
it returns:
... "Error: Can't resolve 'antd/lib/column-group" ...

**Comment by benjycui** [comment]
There is no ColumnGroup in antd.

**Comment by roblingle** [comment]
I just did the same thing with `InputGroup`. 😄 Reading [the documentation](https://ant.design/components/input/), I jumped past the top of the file and just assumed `InputGroup` was imported. Would a PR to specify `<Input.Group ...`, `<Column.Group ...` (and similar) be useful?

```
import {
  Input, Col, Select, InputNumber, DatePicker, AutoComplete, Cascader,
} from 'antd';

const InputGroup = Input.Group;

// ...

render() {
    return (
      <div>
        <InputGroup size="large">
          <Col span={5}>
            <Input defaultValue="0571" />
          </Col>
          <Col span={8}>
            <Input defaultValue="26888888" />
          </Col>
        </InputGroup>
        <br />
        <InputGroup compact>
```
