### ISSUE TITLE
Menu Sider Bar Trigger gets drawn over the last menu item

### ISSUE THREAD

**Issue by esuteau-pro** [ant-design/ant-design#7161]
### Version
2.12.5

### Environment
mac osx, chrome 59.0.3071.115,     "antd": "^2.12.5",     "react": "^15.6.1",     "react-dom": "^15.6.1",     "react-fa": "^4.2.0",     "react-icons": "^2.2.5",     "react-router": "^4.1.2",     "react-router-dom": "^4.1.2",     "react-scripts": "1.0.10"

### Reproduction link
[https://codepen.io/anon/pen/NvjozE?editors=0011](https://codepen.io/anon/pen/NvjozE?editors=0011)

### Steps to reproduce
Run the code in codepen. Taken from the example on the website from which I removed the Layout element right below the Sider.

### What is expected?
the trigger should not be drawn over the last menu item. It should have its own space below the menu.

### What is actually happening?
It's being drawn on the last element of the menu.

**Comment by nikogu** [comment]
i think is a bug. @afc163 take a look
