### ISSUE TITLE
The input of DatePicker is not in right position

### ISSUE THREAD

**Issue by AUCG** [ant-design/ant-design#7162]
### Version
3.0.0-alpha0

### Environment
Mac, Chrome & Safari

### Reproduction link
[https://github.com/ant-design/ant-design/commit/eb3c274e01160895eb8169291da51dc3544be4bb](https://github.com/ant-design/ant-design/commit/eb3c274e01160895eb8169291da51dc3544be4bb)

### Steps to reproduce
DatePicker

### What is expected?
The input of DatePicker should be in the middle of the line

### What is actually happening?
The input is much higher than the icon

---
Change the value of vertical-align from "top" to "middle" is a solution.

**Comment by afc163** [comment]
It turns out that the problem mentioned in https://github.com/ant-design/ant-design/commit/eb3c274e01160895eb8169291da51dc3544be4bb has been fixed by https://github.com/ant-design/ant-design/commit/b687a32044de6fad057f57cd5883838f1eb41e83. So just revert it to avoid vertical align issue.

**Comment by afc163** [comment]
BTW: Do not use `3.0.0-alpha` in production environment.

**Comment by AUCG** [comment]
Thanks for your reminding. I just take this version for a try because version 2.12.5 seems to have some issues in the style of input. We are expecting for the coming stable version.
