### ISSUE TITLE
Is that setFields error can not throws this error to validateFieldsAndScroll?

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#7163]
### Version
3.0.0-alpha0

### Environment
Ubuntu chrom

### Reproduction link
[https://codepen.io/anon/pen/qXmeNL?editors=0011](https://codepen.io/anon/pen/qXmeNL?editors=0011)

### Steps to reproduce
I use setFields  to manual set an error to a field。
when i submit this form,I think the validateFieldsAndScroll should get this error.

### What is expected?
the validateFieldsAndScroll  should  get this error.

### What is actually happening?
the validateFieldsAndScroll  can not get this error.

**Comment by benjycui** [comment]
When you call `validateFieldsAndScroll`, it will reset errors.
