### ISSUE TITLE
用Form.Item 包裹的 DatePicker.RangePicker在safari下行高问题

### ISSUE THREAD

**Issue by sixiancici** [ant-design/ant-design#7164]
### Version
2.12.5

### Environment
safari 10.0.3

### Reproduction link
[https://codepen.io/anon/pen/OjmKxX?editors=001](https://codepen.io/anon/pen/OjmKxX?editors=001)

### Steps to reproduce
用Form.Item包裹DatePicker.RangePicker，在safari 10.0.3下打开

### What is expected?
日期显示的时间文字应该垂直居中

### What is actually happening?
日期显示的时间文字未垂直居中

---
设置ant-calendar-range-picker-input类line-height不为inherit即可解决

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/7135
