### ISSUE TITLE
Menu切换菜单示例为横排展示模式时，选中二级菜单subnav时会出现展示问题

### ISSUE THREAD

**Issue by Begin5257** [ant-design/ant-design#7165]
### Version
3.0.0-alpha0

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
切换横排模式后，鼠标滑过第二级menu subnav时，第三级menu会出现展示错误。

### What is expected?
期望得到正常展示的第三级菜单。

### What is actually happening?
得到错误展示的第三级菜单。

**Comment by Begin5257** [comment]
Version

3.0.0-alpha0

Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

Reproduction link

https://ant.design/components/menu-cn/

Steps to reproduce

When you switch the arrangement mode, the third level menu will show an error when the mouse is over the second level menu named subnav.

What is expected?

expected normal display.

What is actually happening?

accept error third menu.

![bug](https://user-images.githubusercontent.com/14305563/29158316-21742416-7ddd-11e7-8f1e-c9f8377618c1.gif)

**Comment by jljsj33** [comment]
key 一样了，，改下就行了

**Comment by benjycui** [comment]
@jljsj33 👍 

![image](https://user-images.githubusercontent.com/3580607/29202868-b0206046-7e9e-11e7-862d-b47d594ccb09.png)
