### ISSUE TITLE
When used RangePicker in Form.Item, Form.Item is highter than usual.

### ISSUE THREAD

**Issue by cxyxc** [ant-design/ant-design#7171]
### Version
2.12.5

### Environment
win10、Chrome 版本 59.0.3071.115

### Reproduction link
[https://codepen.io/anon/pen/zdzazg?editors=0010](https://codepen.io/anon/pen/zdzazg?editors=0010)

### Steps to reproduce
```html
<div>
    <Form>
      <Form.Item>
         <DatePicker />
       </Form.Item>
      <Form.Item>
         <RangePicker />
       </Form.Item>
    </Form>
  </div>
```

### What is expected?
Form.Item height coincident.

### What is actually happening?
Form.Item height inconsistent.

---
In a Form, FormItem not having the same height. I have to add css to solve this.

**Comment by cxyxc** [comment]
![image](https://user-images.githubusercontent.com/20027281/29198898-8d466828-7e7a-11e7-8ed1-b7e0ff156754.png)

![image](https://user-images.githubusercontent.com/20027281/29198907-9a48435c-7e7a-11e7-87fb-0eb084b2af39.png)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/7135
