### ISSUE TITLE
低版本 chrome 浏览器 form 里的input框 兼容性问题

### ISSUE THREAD

**Issue by zzh-a** [ant-design/ant-design#7174]
### Version
2.12.5

### Environment
win7   chrome 版本 45.0.2454.85 m

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
打开官网form组件

### What is expected?
行高正常

### What is actually happening?
行高不正常

**Comment by zzh-a** [comment]
![a](https://user-images.githubusercontent.com/9522769/29200157-8b86ace0-7e85-11e7-89d3-f54d1bbe9b36.gif)

**Comment by benjycui** [comment]
这种版本就不管了。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/7135
