### ISSUE TITLE
RadioButton 取消选择

### ISSUE THREAD

**Issue by Smile-dan** [ant-design/ant-design#7182]
### What problem does this feature solve?
选中的RadioButton 再次点击后会清除选中状态，现在RadioGroup 选中一个后就无法取消

### What does the proposed API look like?
选中的RadioButton 再次点击后会清除选中状态，该RadioGroup 的值为空

**Comment by afc163** [comment]
原生 Radio 就是这个交互：http://www.w3school.com.cn/tiy/t.asp?f=html_form_radio

保持原样。

**Comment by lihongbin100** [comment]
Now, I will kill it.
```jsx
// It's important.
<div onClick={this.clickIt}>
 <RadioGroup onChange={this.onChange} value={this.state.value}>
         <Radio value="1"/>
        <Radio value="2"/>
        <Radio value="3"/>
 </RadioGroup>
</div>

// click handler
const clickIt=(e)=>{
   const tag = e.target;
       if (tag.type === 'radio' && this.state.value.toString() === tag.value.toString()) {
         this.setState({
            value: '',
         });
    }
}
```

finish!

Welcome to my blog: http://yondu.vip

**Comment by Iwouldliketobeapig** [comment]
我们开发中解决过类似的问题，然后基于ant checkbox写了个单选可取消组件
[这是实现方法](https://github.com/Iwouldliketobeapig/radio-abandon/blob/master/radioAbandon/index.tsx)。

**Comment by guoshencheng** [comment]
在开发的时候遇到相同的问题，查到这里，给大家提供一个思路，直接用checkbox，然后`prefixCls="ant-radio"`就能模拟出radio的样式，然后限制一下选择个数就行

**Comment by afc163** [comment]
https://ux.stackexchange.com/a/13513

**Comment by XiaMii** [comment]
可以这样做，亲测有效
`
  const [chooseStatus,SetchooseStatus] = useState("");

  const radioButtonOnChange= (checked: { target: { value: React.Key } }) => {
    SetchooseStatus(checked.target.value);      
  };

  const radioCancleChoose = ()=>{
      SetchooseStatus("");
  }
              <Radio.Group buttonStyle="solid" onChange={radioButtonOnChange} value={chooseStatus}>
                <Radio.Button onClick={radioCancleChoose} value="1">竣工</Radio.Button>
                <Radio.Button onClick={radioCancleChoose} value="0">在建</Radio.Button>
                <Radio.Button onClick={radioCancleChoose} value="-1">准备</Radio.Button>
              </Radio.Group>            
`

**Comment by LiXiaoRan** [comment]
@XiaMii  very good

**Comment by daiwanxing** [comment]
> 可以这样做，亲测有效
> 
> ```
>   const [chooseStatus,SetchooseStatus] = useState("");
> 
>   const radioButtonOnChange= (checked: { target: { value: React.Key } }) => {
>     SetchooseStatus(checked.target.value);      
>   };
> 
>   const radioCancleChoose = ()=>{
>       SetchooseStatus("");
>   }
> ```
> 
> ```
>               <Radio.Group buttonStyle="solid" onChange={radioButtonOnChange} value={chooseStatus}>
>                 <Radio.Button onClick={radioCancleChoose} value="1">竣工</Radio.Button>
>                 <Radio.Button onClick={radioCancleChoose} value="0">在建</Radio.Button>
>                 <Radio.Button onClick={radioCancleChoose} value="-1">准备</Radio.Button>
>               </Radio.Group>            
> ```

在 AntD v5 这种写法仍然有效，唯一不足就是会有两次的 re-render
