### ISSUE TITLE
ant-design 升级后引入lodash路径错误

### ISSUE THREAD

**Issue by yezishan** [ant-design/ant-design#7184]
### Version
2.11.1

### Environment
windows7 chrom浏览器 react版本： 0.14

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
step1: antd升级到2.11.1版本
step2: npm run dev启动 
          此时报错：lodash中的方法引入错误

下面是其中一个错误的信息：
ERROR in ./~/rc-form/lib/createBaseForm.js 
Module not found: Error: Cannot resolve ‘file’ or ‘directory’ C:\windows\Systems32\20170731_spring11\react\node_modules\lodash\lodash.min.js/set in C:\windows\Systems32\20170731_spring11\react\node_modules\rc-form\lib
@ ./~/rc-form/lib/createBaseForm.js 47:11-32

### What is expected?
能够正确引入lodash方法，而不需要手动修改

### What is actually happening?
需要把引入方法由“lodash/set”改为"lodash\\set"就不会报错了，但是需要改好几个地方

---
不好意思，重现链接我随便填的

**Comment by yezishan** [comment]
有个地方写错了：
引入方法应该是改为"lodash\\set"就不会报错了

**Comment by yezishan** [comment]
改为"lodash\set"，这里是两个反斜杠的

**Comment by afc163** [comment]
> \lodash\lodash.min.js

It is not a bug, check and try to remove your webpack alias config about lodash.

**Comment by yezishan** [comment]
没太明白要怎么改啊，我的lodash引入是这样的"lodash": "/node_modules/lodash/lodash.min.js", 没问题吧

**Comment by afc163** [comment]
建议去掉。

**Comment by yezishan** [comment]
但是我需要用到lodash的功能呀

**Comment by afc163** [comment]
去掉 webpack 的 `resolve.alias` 相关属性不影响你用 lodash。
