### ISSUE TITLE
Wrong TabPanel position with card type and default animated props

### ISSUE THREAD

**Issue by laispace** [ant-design/ant-design#7185]
### Version
2.12.5

### Environment
Mac.Chrome.v60.0.3112.90 / Antd.v2.12.5

### Reproduction link
[https://codepen.io/laispace/pen/zdzQEV](https://codepen.io/laispace/pen/zdzQEV)

### Steps to reproduce
Use `Tabs` with `type='card'` without setting `animated`.

### What is expected?
Only one `TabPanel` within `Tabs`

### What is actually happening?
Multiple `TabPanel`s within `Tabs`

**Comment by afc163** [comment]
BTW, you shouldn't override `.ant-tabs:not(.ant-tabs-vertical) > .ant-tabs-content > .ant-tabs-tabpane` style.

**Comment by laispace** [comment]
@afc163 In my case, I need to set min-height of TabPanel.
The style in demo just for  reproducing the bug.
