### ISSUE TITLE
如何判断 Pagination 组件的页码更改是来自跳转框输入还是点击页面按钮？

### ISSUE THREAD

**Issue by elowes** [ant-design/ant-design#7186]
### What problem does this feature solve?
用户要求已有的数据所在的页码永远不变，新的数据往后追加，且打开时默认显示最新的数据，且页码排序是由大到小排序。我使用了 itemRender 属性实现了这个需求。（假设总共有 3 页数据，现在页码显示为 3 2 1，但是存在一个问题就是通过跳转框输入 1 时会和我点击 3 是一样的操作，这是不符合人的认知的。所以如果可以判断这次页码变化是来自输入框的话，我就可以计算得出 1 的真正下标为 3，将其置于正确的选中位置）。说的有点啰嗦，还望说明白了。

### What does the proposed API look like?
- onChange 的回调函数 Function(page, pageSize)，增加一个参数 quickJumperFlag，用来表示页码变化是否来自快速跳转输入框
``` js
onChange: (page, pageSize, quickJumpFlag) => {
    quickJumpFlag ?
        // balabalabala ...
    :
        // balabalabala ...
}
```

**Comment by afc163** [comment]
> 通过跳转框输入 1 时会和我点击 3 是一样的操作

不是这样的，输入 1 就会跳转到第一页。

**Comment by elowes** [comment]
@afc163 不，我改了页码的显示顺序啊，现在页面 3 的下标是第一个，点击它的 onChange 返回的 page 是 1，我是自己根据数据总量计算了一下，点击 3 的时候，由 1 计算得到 3 然后发请求给服务器。现在直接用输入框输入 1 的时候，也是相当于点了下标第一个，但这时候我也会计算一遍由 1 得到 3 然后发给服务器。但是这不合理，用户输入 1 的时候肯定是想跳转到第一页，怎么能跳转到第三页呢？（我自己刚刚粗糙的加了个 input 框用来跳转，关掉了 <Table> 组件自带的 quickJumper，先实现需求再说 :] ）

**Comment by afc163** [comment]
嗯我明白了，我在考虑有没有必要满足这个需求。对，自定义的 jump 框可以解决，这里有一个 demo 你可以参考：https://github.com/ant-design/ant-design/issues/6970#issuecomment-318039942

**Comment by elowes** [comment]
@afc163 感谢，已经搞定需求了。项目主要是一个标注系统。标注员喜欢按照页码来分配任务。所以要保证旧的数据页码是稳定的，但是新的数据还要显示在前面，所以只能做成页码从大到小了😁

**Comment by afc163** [comment]
OK，这个需求比较极端，就做不改动了。
