### ISSUE TITLE
Recommend ts-import-plugin in README

### ISSUE THREAD

**Issue by Brooooooklyn** [ant-design/ant-design#7188]
### What problem does this feature solve?
I wrote a TypeScript Plugin that has familiar APIs and features with `babel-import-plugin`, and work fine in my project. Could you please recommend it in your README, I believe it would help many people who write TypeScript & antd.

Here is repo address: https://github.com/Brooooooklyn/ts-import-plugin

**Comment by afc163** [comment]
I like it, could you try to give us a PR for this?

**Comment by afc163** [comment]
This could be useful to be mentioned at #6193 too.

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以非常方便的做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 更简洁，性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；
