### ISSUE TITLE
antd-demo antd-init安装报错 请帮忙看看 好像是依赖问题

### ISSUE THREAD

**Issue by jcs12311** [ant-design/ant-design#719]
npm ERR! peerinvalid The package atool-build@0.4.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer dora-plugin-hmr@0.1.3 wants atool-build@^0.3.1
npm ERR! peerinvalid Peer dora-plugin-atool-build@0.2.1 wants atool-build@^0.4.2

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/issues/5
