### ISSUE TITLE
Carousel - change slides programatically

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#7191]
### Version
3.0.0-alpha.1

### Environment
Mac OS Sierra, Newest Google Chrome

### Reproduction link
[https://github.com/akiran/react-slick/blob/master/examples/PreviousNextMethods.js](https://github.com/akiran/react-slick/blob/master/examples/PreviousNextMethods.js)

### Steps to reproduce
Follow the steps  in `minimal reproduction` link.

### What is expected?
I expect to methods like `slickNext` to be available if using the same steps as in the provided example

### What is actually happening?
`Uncaught TypeError: this.slider.slickNext is not a function`

**Comment by afc163** [comment]
Try `this.slider.refs.slick.innerSlider.slickNext()`.

**Comment by afc163** [comment]
`this.slider.innerSlider` should be working after f6d349731c9ca372644560f0799c4ef8ea42101d fix.
