### ISSUE TITLE
Layout支持collapsedWidth设置，Menu却不支持collapsedWidth设置？它们怎么配合？

### ISSUE THREAD

**Issue by Leo2088** [ant-design/ant-design#7192]
### Version
3.0.0-alpha.1

### Environment
react

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
Layout支持collapsedWidth设置，Menu却不支持collapsedWidth设置？它们怎么配合？

### What is expected?
希望Menu也能支持collapsedWidth设置，这样方便布局，目前好像是定死64px。

### What is actually happening?
目前好像是定死64px。

**Comment by afc163** [comment]
Don't use alpha version.

**Comment by afc163** [comment]
```jsx
<Menu
  inlineCollapsed={this.state.collapsed}
  style={{ width: this.state.collapsed ? 100 : '' }}
>
```

https://codepen.io/anon/pen/LjjXQL?&editors=001
