### ISSUE TITLE
改变Modal组件的visible状态，没有对应效果

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#7193]
### Version
3.0.0-alpha.1

### Environment
MacOs sierra 10.12.5  npm5.3.0

### Reproduction link
[https://codepen.io/ouzhou/pen/xLLmMy?editors=0111](https://codepen.io/ouzhou/pen/xLLmMy?editors=0111)

### Steps to reproduce
设置自己定义的传入参数props（代码中const props={}），让props.defaultProps.visible = true;点击弹出层外面或者关闭按钮。

### What is expected?
点击外部或者关闭按钮会关闭掉弹窗

### What is actually happening?
没有期望效果

---
如果设置props.defaultProps.visible = false;是可以达到逻辑效果的

**Comment by yesmeck** [comment]
`{...defaultProps}` 把上面的 `visible={this.state.visible}` 覆盖调了。
