### ISSUE TITLE
how to reduce the package size with webpack

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#7194]
### What problem does this feature solve?
In webpack, I used babel-plugin-import: 
```
plugins: [
           ['import',{'libraryName':'antd','style':'css'}] //antd按需加载组件和样式
]
```
but I think it's still large , especially CSS file 。

![image](https://user-images.githubusercontent.com/20348639/29248194-e5cff218-8044-11e7-876b-9d190bd320a8.png)

### What does the proposed API look like?
how to reduce size 。

**Comment by yesmeck** [comment]
A reproduction repo would helpful.
