### ISSUE TITLE
treeSelect treeCheckStrictly

### ISSUE THREAD

**Issue by captainbob** [ant-design/ant-design#7197]
### Version
2.12.2

### Environment
mac 10.12.3 chrome 60.0.3112.90

### Reproduction link
[https://codepen.io/anon/pen/OjxXNQ?&editors=001](https://codepen.io/anon/pen/OjxXNQ?&editors=001)

### Steps to reproduce
i found the problem in fireChange when i use treeCheckStrictly true in TreeSelect.  please don't setState labs,because vls is labelInValue

### What is expected?
i found the problem in fireChange when i use treeCheckStrictly true in TreeSelect.  please don't setState labs,because vls is labelInValue

### What is actually happening?
i found the problem in fireChange when i use treeCheckStrictly true in TreeSelect.  please don't setState labs,because vls is labelInValue

---
把treeselect的treeCheckStrictly的fireChange函数改一下，这步不需要setState labs，因为vls是labelInvalue形式的。赶紧改了吧。

**Comment by benjycui** [comment]
Please make sure that your CodePen work, and provide steps to re-produce bugs.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tree-select/pull/69
