### ISSUE TITLE
Hello, hope to support the configuration of the table should be done in each row of the method

### ISSUE THREAD

**Issue by MrChongdong** [ant-design/ant-design#7198]
### What problem does this feature solve?
english: 
Because there is a scene, the user infinitely dropping data, datas tracks data once large, each new item will lead to all the datasues re-rendering virtual dom, hoping to let us customize each line shouldcomponentUpdate method to reduce these consumption

中文:
因为有一种场景,用户无限下拉加载数据的时候,datasourse数据一旦大,每新增一个项都会导致所有的datasourse重新渲染虚拟 dom, 希望通过让我们自定义 每一行的shouldcomponentUpdate()方法来减少这些消耗

### What does the proposed API look like?
 rowUpdateCondition={()=>{}}

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/2884#issuecomment-270049602
