### ISSUE TITLE
导航栏显示问题

### ISSUE THREAD

**Issue by berubou** [ant-design/ant-design#7199]
### Version
3.0.0-alpha.1

### Environment
任意

### Reproduction link
[https://ant.design/components/table-cn/#footer](https://ant.design/components/table-cn/#footer)

### Steps to reproduce
将滚动条移动至页面底部，导航栏显示有问题

### What is expected?
。

### What is actually happening?
。

**Comment by afc163** [comment]
> 导航栏显示有问题

什么问题？

**Comment by berubou** [comment]
![image](https://user-images.githubusercontent.com/14237234/29265150-7538871c-8112-11e7-974e-f45a43eb3340.png)
