### ISSUE TITLE
快速上手 

### ISSUE THREAD

**Issue by nowgoant** [ant-design/ant-design#72]
快速上手 按照步骤做不work!
index.css 缺失。能不能在 antd init 后，生成可运行的demo。
类似Yeoman的[generator-webapp](https://github.com/yeoman/generator-webapp)做法。

**Comment by afc163** [comment]
实测是可以跑通的，不知道 @nowgoant 的操作步骤和命令行 log 都是什么呢？

**Comment by yuche** [comment]
@nowgoant 你应该是确实按照步骤来操作了。事实上 readme 少了第一步：`npm install`

**Comment by afc163** [comment]
README 里是本仓库的开发步骤，并非使用步骤。

上手教程里是有 npm install 的。

**Comment by nowgoant** [comment]
谢谢
