### ISSUE TITLE
table设置scroll以后，table的表头与内容无法对齐

### ISSUE THREAD

**Issue by taotiehai** [ant-design/ant-design#7202]
**Version**

2.12.5

**Environment**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Reproduction link**
公司内部系统不便透漏

**Steps to reproduce**
创建一个表头比较多的table，我这里有22列。表格内容长短不一，设置了table标签的scroll以后（scroll={{x:false,y:300}} ），table按照表格内容自动展开，但title并未按照同样的规则展示，因此出现title与表格内容错位的情况

**What is expected?**

设置table的scroll以后，title与table内容仍然按照title的长度展示，并且可以一一对应

**What is actually happening?**

**Comment by he5310** [comment]
@taotiehai 带上scroll属性会自动在thead和tbody外层包上一个div,所以对不不齐.暂时找不到解决方案.

**Comment by xuhuanghuang** [comment]
@taotiehai  加了宽定也不管用呢，还有其他的解决方法吗
