### ISSUE TITLE
Should showSearch property in <Select /> search for option labels as well?

### ISSUE THREAD

**Issue by mauriciosoares** [ant-design/ant-design#7205]
### What problem does this feature solve?
I believe it's a good idea for the `showSearch` feature to also search labels as well, some times the value of an option is simply an ID, let's say <Option value="12345">Facebook</Option>, in this case, the end user probably don't know the ID itself, so he/she'll search for the option label.

I don't know if ant.design provides this already, but if it doesn't, it would be a nice to have, to make the search feature cover more use cases.

This may also be configurable... by default it searches by the value of the option, but using some flag you can also search by the label.

Here's a [Codepen](https://codepen.io/anon/pen/YxrVVP) with an example:

The values are `1` and `2`, but the text is `One` and `Two`.

![screen shot 2017-08-14 at 13 47 45](https://user-images.githubusercontent.com/2321259/29270721-5ed8dc0c-80f8-11e7-89a1-505a55eff90f.png)
![screen shot 2017-08-14 at 13 47 52](https://user-images.githubusercontent.com/2321259/29270720-5ec0f0ec-80f8-11e7-8396-4fe59251179f.png)

### What does the proposed API look like?
This may search by both value and label
```
<Select showSearch />
```

Or we can have this configurable
```
<Select showSearch searchBy="value" />
<Select showSearch searchBy="label" />
```

**Comment by afc163** [comment]
`optionFilterProp`

**Comment by mauriciosoares** [comment]
Sorry for that, thanks for the quick reply :)

![images](https://user-images.githubusercontent.com/2321259/29271898-0aa27584-80fe-11e7-8108-d2f7405a454b.png)
