### ISSUE TITLE
Tabs [type="card"] style improvement

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#7206]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/507615/29393176-d0c5d868-8334-11e7-92a3-ff0ad6879b2a.png">

**Comment by benjycui** [comment]
`+` 在哪里？

**Comment by afc163** [comment]
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/507615/29393459-5a4a7c14-8336-11e7-9d3d-6cc9a1b8ac2c.png">
