### ISSUE TITLE
tree checkable时,父子多种勾选模式

### ISSUE THREAD

**Issue by tofdragon** [ant-design/ant-design#7207]
### What problem does this feature solve?
目前是勾选父，子全勾选；子都取消勾选,父也取消；实践应用中有子取消，父可选择，参见ztree中http://www.treejs.cn/v3/demo.php#_201  父子级联勾选

### What does the proposed API look like?
通过属性设置父子级联勾选模式

**Comment by afc163** [comment]
checkStrictly

**Comment by afc163** [comment]
建议自行控制，情况很多 API 很难覆盖全。

**Comment by tofdragon** [comment]
@afc163 Thank you for your reply!
