### ISSUE TITLE
表单验证没有错误信息提示，也没有错误的class加载

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#721]
HI，
我按照 http://ant.design/components/validation/ 上面的例子写了个页面，只有1个输入框，只有一个规则`required: true`，使用时发现有很多问题：
  
* 使用trigger=onChange好像没有作用，改变内容也不会触发校验
* validateStatus没有效果，内容为空的时候也不会出现css error的样式，我设了断点看了一下，好像formData的值一直是undefined，但我没看到例子里面在哪个地方有做setState
* rule里面的message在错误时也不会显示
* 例子里面的按钮是onClick={this.handleSubmit}，但我写的时候发现要这样才对: onClick={this.handleSubmit.bind(this)}
  
请问是我的使用姿势不对，还是这个组件本身还不成熟的问题？有没有jsbin的例子可以让我在线调试一下？谢谢

**Comment by benjycui** [comment]
要不你 fork http://jsfiddle.net/yiminghe/9zrstuto/1/ 重现下？

**Comment by zhaozhiming** [comment]
我用React.createClass的方式是OK的，http://jsfiddle.net/zhaozhiming/a2186d8y/2/。

但我用class Hello extends React.Component的方式就不行了，下面是代码。

```js
import React from 'react';
import {Validation, Button, Form, Input, Select} from 'antd';
const Validator = Validation.Validator;
const FormItem = Form.Item;


class Hello extends React.Component {
// const Hello = React.createClass({
  mixins: [Validation.FieldMixin]

  state = {
    status: {
      name: {},
    },
    formData: {
      name: undefined,
    },
  }
 
 ......
}

export default Hello;

```

**Comment by benjycui** [comment]
ES6 的语法无法支持 mixins, see: https://facebook.github.io/react/docs/reusable-components.html#no-mixins

用回 `React.createClass` 先，直到 React 官方提供替代方案。
