### ISSUE TITLE
Tabs sliding is not responsive

### ISSUE THREAD

**Issue by chunliu** [ant-design/ant-design#7210]
### Version
2.12.5

### Environment
Windows 10, Chrome 60.0.3112.90

### Reproduction link
[https://codepen.io/anon/pen/PKJVQG?&editors=001](https://codepen.io/anon/pen/PKJVQG?&editors=001)

### Steps to reproduce
1. Tabs doesn't show sliding buttons in horizontal mode by default. 
2. Change the window size to a smaller size. 
3. Tabs still doesn't show sliding buttons. 

### What is expected?
Tabs should show sliding buttons when windows size changes to a smaller size. 

### What is actually happening?
It doesn't show it.

**Comment by afc163** [comment]
Your codepen is empty.

**Comment by chunliu** [comment]
sorry, please try this one: https://codepen.io/anon/pen/PKJVQG?&editors=001

**Comment by owen-m1** [comment]
what is the solution?
