### ISSUE TITLE
DatePicker with showTime has a localization problem

### ISSUE THREAD

**Issue by swchen** [ant-design/ant-design#7213]
### Version
2.12.6

### Environment
Win 10 (64bit)  Chrome 60.0.3112.90(64bit)

### Reproduction link
[https://codepen.io/swchen/pen/gxGxVb](https://codepen.io/swchen/pen/gxGxVb)

### Steps to reproduce
1. DatePicker default in Chinese local
2. Click the datePicker input to show the dropdown.
3. Click on "选择时间" at the bottom ('Select Time' in Chinese)
4. Select time and close the dropdown
5. Click the datePicker input to show the dropdown. 

### What is expected?
In the dropdown, month and weekday display in Chinese 

### What is actually happening?
In the dropdown, month and weekday display in English

**Comment by czl1378** [comment]
Same problem.

**Comment by czl1378** [comment]
@luolonghao

**Comment by nikogu** [comment]
@swchen in your `codepen`, i see the always chinese. Does the steps correct?

**Comment by swchen** [comment]
![DatePicker](https://raw.githubusercontent.com/swchen/image/master/DatePicker.png)

**Comment by benjycui** [comment]
Try https://ant.design/components/date-picker/#API

**Comment by swchen** [comment]
I use 

```javascript
import moment from "moment";
import "moment/locale/zh-cn";
moment.locale("zh-cn");
```
and the BUG as ever.

So why just ask me try and close the issue.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by swchen** [comment]
`moment.locale("zh-cn")` and `default locale` are invalid
https://codepen.io/swchen/pen/gxGxVb

`<LocaleProvider locale={locales.zh_CN}>` is valid
https://codepen.io/swchen/pen/ayEKQa

**Comment by swchen** [comment]
https://github.com/swchen/antd-datepicker-demo

**Comment by benjycui** [comment]
Because of the order of code execution.

This line of [code](https://github.com/react-component/time-picker/blob/227e6ec28c733bba0a4b56e0583058489c0684a6/src/Panel.jsx#L52) is executed before your `moment.locale('zh-cn')`. So, the locale is `en` in the `defaultOpenValue`, when user select, we just clone it and generate a new value which has an en locale.

**Comment by benjycui** [comment]
I am not going to fix this, the logic of locale of time-related components is too complicated, I afraid that we will introduce more bugs when we modify this logic.

We will change the default locale of antd to English in `3.0`, that will resolve this issue more elegant, trace: https://github.com/ant-design/ant-design/issues/5570

**Comment by benjycui** [comment]
Just use LocaleProvide to resolve this issue now, sorry.

**Comment by swchen** [comment]
if you set ``defaultOpenValue: moment()`` at ``static defaultProps`` , will make another issue. 

after you show a view with ``DatePicker`` , you wait for a few seconds, then you select a ``date``, the ``time`` is old.

![DatePicker](https://raw.githubusercontent.com/swchen/image/master/DatePicker2.png)

**Comment by benjycui** [comment]
Yep, it's not ideal, so you had better set your own

**Comment by swchen** [comment]
OK. Thank you.

**Comment by czl1378** [comment]
Give a defaultValue to showTime can fix this issue. 
https://codepen.io/czl1378/pen/GvxOdp

**Comment by benjycui** [comment]
> Give a defaultValue to showTime can fix this issue.

Yep, it is impossible for antd to set a `defaultValue` which is meaningful in every project, so just set your own.
