### ISSUE TITLE
Timeline组件只有一个子节点时，不应该延伸出了一条实线。

### ISSUE THREAD

**Issue by xuchenchenBoy** [ant-design/ant-design#7214]
### What problem does this feature solve?
当时间轴只有一条记录时，应该保持一个点，而不应该多延伸出一条实线。这样破坏了整体风格，以及给客户造成困惑。

### What does the proposed API look like?
    <Timeline>
      <TimelineItem>时间轴1</TimelineItem>
    </Timeline>

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
demo: https://codepen.io/anon/pen/oeoMVB?editors=0010

**Comment by xuchenchenBoy** [comment]
@benjycui Thank you.
