### ISSUE TITLE
Date-Picker highlight specific days

### ISSUE THREAD

**Issue by RGregat** [ant-design/ant-design#7216]
### What problem does this feature solve?
I have a use case, where I restrict the range of dates a user can pick from. The range is based on a min/max calculation of a bunch of valid dates. That means that not every day inside of the range actually has some usefull meanings. I need the range for some other processes, but it would be nice to show the user valid dates with a different highlighting  color like yellow or so.

### What does the proposed API look like?
It could work similar as the disableDate API.

```
_highlightDate = (highlightableDates, current) => {
        const highlightDate = highlightableDates.filter((singleHighlightableDate) => {
            return moment(singleHighlightableDate) === current.valueOf();
        });

        if (highlightDate.length >= 1){
             return true;
        }
        
        return false;
    }
```
Maybe it is a little bit to verbose to filter everytime the complete list of days which should be highlighted.
Probably there is already a way to do some highlighting?

**Comment by nikogu** [comment]
Does this [demo](https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date) can solve your problem ?

**Comment by RGregat** [comment]
Well, that seems to be the same which I have already implemented. Of course I could disable every date which is not valid in my context, but I would like to keep the daterange. I upload a simple image to illustrate my odd wish :)

The yellow color highlights all valid dates.
It is only possible to pick a range to the end of april, everything beyond is disabled.

![calender_highlighting](https://user-images.githubusercontent.com/3974162/29317671-52bbc4fe-81cd-11e7-88a4-ce53cc269f15.png)

**Comment by benjycui** [comment]
I don't understand.. Could you provide an image to show what you are going to implement? And you had better to describe your goal in details..

**Comment by RGregat** [comment]
Sure, I will do my best to describe my purpose.

I have a Database with informations which I visualize on a leaflet.js Map. Every entry in the Database has a timestamp. Between the Frontend and the Database is a Backend which controls the dataflow.
For my calender the Backend generates the min and max datetime to restrict the range of pickable dates. This is already implemented and works like a charm. Now I had the problem that a client picked not a range but a single day for the start and end date. this choosen day has no information in the Database and the result was an empty Map.
So my idea is to highlight inside of the possible range all valid dates. 
Maybe it sounds a little bit strange to have a range and on the other hand explicit days. But in my case it is important to have the option to pick a range and to say mehh just set start and end date the same day. On both cases I want a visualisation on the map.

I hope it is now a little bit clearer what my goal is, if not, tell me.

**Comment by benjycui** [comment]
So, you are providing two DatePicker for your users to select a time range to filter data in database.

But some ranges will filter no data, so you want to forbid this, right?

**Comment by RGregat** [comment]
Yes I have two DatePicker. I create a restriction based on the min and max Datetime of all Entries in my Database. In between this min and max Datetime are dates with no information. Well I could start to restrict with a finer grain instead of the overall min max, but i thought i could mark all valid dates with a highlighting color.

**Comment by benjycui** [comment]
Actually, just disabled all the dates which have no information will be better, otherwise, users must learn which style means disabled/with-information/no-information.

If you insist, you can try to expose dateRender, see: https://github.com/react-component/calendar

**Comment by RGregat** [comment]
Hey @benjycui thx for the link. The API is the same like the one you provide with the antd calender?
If I take a deeper thought on this topic,  I come to the same conclusion you said. It might be to difficult to understand the meaning of all these colors. 
But I think, it could be a great addition to highlight dates on a calender. Not for my use case, but for example to mark birthdays or important events and so on.

**Comment by benjycui** [comment]
> If you insist, you can try to expose dateRender, see: https://github.com/react-component/calendar

antd.DatePicker doesn't support this now, but it is based on rc-calendar, so you can try to PR to expose it.

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/pull/7710

**Comment by yesmeck** [comment]
Closing since #7710 has been merged.

**Comment by PaulPCIO** [comment]
With ant.d you could simply do this with the date picker

` <Datepicker disabledDate={this.disabledDateWithoutData} />`

and then return only the dates that have data

`  disabledDateWithoutData = current => {
    if (current && arrayObject.some(row => moment(row.filter.date).format("DDMMYYYY") === moment(current._d).format("DDMMYYYY"))) {
      return false
    }else{
      return current
    }
  }`

**Comment by Mahadi92** [comment]
I solved this this way 

`
import React from 'react';
import { DatePicker } from 'antd';

const holidays = ['2023-09-04', '2023-09-05', '2023-09-11']; // Replace with your holiday dates

function isHoliday(currentDate) {
  const formattedDate = currentDate.format('YYYY-MM-DD');
  return holidays.includes(formattedDate);
}

function dateCellRender(currentDate) {
  if (isHoliday(currentDate)) {
    return <div className="holiday-cell">{currentDate.date()}</div>;
  }
  return currentDate.date();
}

const MyDatePicker = () => {
  return (
    <DatePicker
      dateRender={dateCellRender}
    />
  );
};

export default MyDatePicker;

`

**Comment by ThinNandarAung-dev-prog** [comment]
I used DatePicker from antd design. But instead of showing auto focus blue ring in today. I want to show my system's business day. How can I do this?
