### ISSUE TITLE
Antd init之后的项目跑不起来

### ISSUE THREAD

**Issue by FarmanYu** [ant-design/ant-design#722]
安装完最新的antd，报这个警告。
Warning: antd@0.10.4 need react@~0.14.2 or higher, which is react@0.13.3 now.

下面是js报错：
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

**Comment by benjycui** [comment]
升级下你项目依赖的 react 到 0.14.3

**Comment by FarmanYu** [comment]
https://a.alipayobjects.com/react/0.14.3/react.js  这里没有这个资源，使用其他单独的CDN资源报错

**Comment by benjycui** [comment]
现在推荐用 npm 安装 react/antd 然后用 webpack 打包

**Comment by FarmanYu** [comment]
webpack打包有 example吗？

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init
