### ISSUE TITLE
build break on newest version (2.12.6) with webpack

### ISSUE THREAD

**Issue by Adidi** [ant-design/ant-design#7222]
### Version
2.12.6

### Environment
Centos 7 linux

### Reproduction link
[http://www.i-dont-have.com](http://www.i-dont-have.com)

### Steps to reproduce
install the new version of antd 2.12.6 
compile it using webpack 
when i try to run the code i see this error shown

### What is expected?
For the code to work smoothly without bugs

### What is actually happening?
There is a bug - an error thrown that isSelectOptGroup calling from undefined causing the all system to stop functioning - the error comes from rc-select component

**Comment by afc163** [comment]
Please provide more information like error log and a reproducible repository.

**Comment by Adidi** [comment]
There you  go
```
Select.js:800 Uncaught (in promise) TypeError: Cannot read property 'isSelectOptGroup' of undefined
    at Select.js:800
    at forEachSingleChild (ReactChildren.js:51)
    at traverseAllChildrenImpl (traverseAllChildren.js:77)
    at traverseAllChildrenImpl (traverseAllChildren.js:93)
    at traverseAllChildren (traverseAllChildren.js:172)
    at Object.forEachChildren [as forEach] (ReactChildren.js:71)
    at Select.addTitleToValue (Select.js:799)
    at new Select (Select.js:60)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:297)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:284)
```

**Comment by afc163** [comment]
`a reproducible repository`

**Comment by Adidi** [comment]
What is that ? I need to clone the repo and make you the error I dont understand ?
Why can't you understand what the problem is according to what I just sent I think its pretty clear

**Comment by afc163** [comment]
Because I tried and can't see this error in my machine.

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html).

**Comment by Adidi** [comment]
Well - Its only happened to me when I run the build for production in webpack - meaning without sourcemaps etc.. - Can you try that ?
And I am on the "smart question" manual - thank !

**Comment by afc163** [comment]
Please give me a reproducible repo on GitHub or I afraid nothing I can do.

**Comment by Adidi** [comment]
Can you explain to me what is a reproducible repo - I have big project with rather complex webpack configuration - what shell I make in this repo ?

**Comment by afc163** [comment]
A GitHub repo Iike @lili21 provided in https://github.com/ant-design/ant-design/issues/7158

**Comment by Adidi** [comment]
I made a repo and got the problem while making
If you include Option and select inside the import like that: 
`import Select, { Option } from 'antd/lib/select';` 
it will throw the error:
https://github.com/Adidi/issues

if you call the Option from the Select itself its working.
`const Option = Select.Option;`

**Comment by afc163** [comment]
Confirmed, Thx for your repo.

It is broken after `2.12.4`, and something change the compiled format of `antd/lib/select/index.js`.

- http://unpkg.com/antd@2.12.3/lib/select/index.js `GOOD`
- http://unpkg.com/antd@2.12.4/lib/select/index.js `BROKEN`

```
module.exports = exports['default'];
```

The code above is missing. Any changes of our workflow? @yesmeck @paranoidjk @benjycui

**Comment by paranoidjk** [comment]
@afc163 Caused by this line of export https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L70 just remove it.

**Comment by paranoidjk** [comment]
This is  babel-plugin-add-module-exports relative code https://github.com/59naga/babel-plugin-add-module-exports/blob/master/src/index.js#L27

**Comment by paranoidjk** [comment]
trace https://github.com/59naga/babel-plugin-add-module-exports/issues/46
