### ISSUE TITLE
在使用Tree树形控件启用checkable后，添加新节点后选中该节点报错

### ISSUE THREAD

**Issue by myuid** [ant-design/ant-design#7224]
### Version
2.12.6 / 2.12.5

### Environment
chrome react 15

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
TypeError: Cannot set property 'checked' of undefined

var halfChecked = _this.props.checkedKeys ? _this.props.checkedKeys.halfChecked : [];
_this.props.onCheck((0, _util.getStrictlyValue)(checkedKeys, halfChecked), newSt);
} else {
if (checked && index === -1) {
 _this.treeNodesStates[treeNode.props.pos].checked = true; //问题在这里
(0, _util.updateCheckState)(_this.treeNodesStates, treeNode.props.pos, true);
}
if (!checked) {
_this.treeNodesStates[treeNode.props.pos].checked = false;
_this.treeNodesStates[treeNode.props.pos].halfChecked = false;
(0, _util.updateCheckState)(_this.treeNodesStates, treeNode.props.pos, false);
}

ant.design version: 2.12.5/2.12.6

### What is expected?
选中节点

### What is actually happening?
选中节点提示TypeError: Cannot set property 'checked' of undefined

**Comment by benjycui** [comment]
Your CodePen is not about `antd.Tree`, but `antd-mobile.Tabs`

**Comment by pengsea** [comment]
## 注意

树节点可以有很多，但在设置`checkable`时，将会花费更多的计算时间，因此我们缓存了一些计算结果（`this.treeNodesStates`）来复用，避免多次重复计算，以此提高性能。但这也带来了一些限制....
上面是官方的解释, 建议你添加loadData
`<Tree` loadData={()=>{}}>
        {treeNodes}
      `</Tree>`

**Comment by ppboyly** [comment]
treeNodesStates没有缓存数据的时候就是一个空对象，所以有时候到这里会导致_this.treeNodesStates[treeNode.props.pos].checked = true;，希望 可以更改一下

**Comment by ppboyly** [comment]
有时treeNodesStates没有缓存数据的时候就是一个空对象，所以有时候到_this.treeNodesStates[treeNode.props.pos].checked = true这里会报错， 希望 可以更改一下

**Comment by benjycui** [comment]
> 有时treeNodesStates没有缓存数据的时候就是一个空对象，所以有时候到_this.treeNodesStates[treeNode.props.pos].checked = true这里会报错， 希望 可以更改一下

Please file another issue and provide online demo.

**Comment by afc163** [comment]
Please provide correct codepen as @benjycui said, then we will reopen ti.

**Comment by babycannotsay** [comment]
I ran into the same problem, but when showing it on the codepen, the problem is not exist.
I think you should go and see under what circumstances will appear that `_this.treeNodesStates` is an empty object(`{}`). The file path is  `rc-tree/lib/Tree.js`.

**Comment by babycannotsay** [comment]
灵光一现，发现checkedKeys在树列表生成之前就已经生效了。这时就会报楼主一样的错误。

CheckedKeys was useable before tree-list generates, the error was happened now.

The sample code is as follows

    const loop = data => {
        return data.map(item => {
          if (item.list.length > 0) {
            return (
              <TreeNode key={item.code} title={item.name}>
                {loop(item.list)}
              </TreeNode>
            );
          }
          return <TreeNode key={item.code} title={item.name} />;
        });
    };

    return (
      <div>
         <Tree checkable onCheck={handleCheck} checkedKeys={checkedKeys}>
            {loop(treeList)}
         </Tree>
      </div>
    );

类似这样一个例子，我在使用dva的model控制treeList和checkedKeys的时候，出现了跟楼主一样的问题。

Like this, I ran into the same proble when I use dva's model control treeList and checkedKeys.

solution: 

    {treeList.length > 0 && <Tree checkable onCheck={handleCheck} checkedKeys={checkedKeys}>
            {loop(treeList)}
    </Tree>}

**Comment by benjycui** [comment]
@babycannotsay Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zlv-thisF** [comment]
i have the same problem.   this.treeNodesStates is empty then Tree.js throws errors
