### ISSUE TITLE
Select will call for the second time when onSelect changes the props that Option use to render

### ISSUE THREAD

**Issue by Hydraz320** [ant-design/ant-design#7225]
### Version
2.11.2

### Environment
MacOS Chrome59 

### Reproduction link
[http://jsfiddle.net/SebastianBlade/3nr3wwug/52/](http://jsfiddle.net/SebastianBlade/3nr3wwug/52/)

### Steps to reproduce
The link above is not mine. But he has the same problem and he doesn't know the inner thing.
To be short, if our <Select> and the content between <Option>xxx</Option> are rendered according to different values of this.props, and there's code in onSelect that will change this.props(such ad setState) and the Select will take it as a change, the result will be that the onSearch is call after the option is selected, and this time, params for onSearch will "" and the response will never be a non-empty list, which in result, the content between <Option>xxx</Option> will be undefined and the content changes to key or value of Option.
That's why he get number after select an option.
When I inspect the code on https://github.com/react-component/select, I really saw that the onSearch again is an intended design. But how could we do when users face the thing above?

### What is expected?
Like https://github.com/ant-design/ant-design/issues/6505 was saying, a cache-like feature.

### What is actually happening?
It actually call onSearch again which is not adequate here.

---
Thanks.

**Comment by benjycui** [comment]
> To be short, if our and the content between xxx

What do you mean? Need demo, and steps to re-produce bug, instead of a conclusion directly.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Hydraz320** [comment]
Sorry about my issue， I just find that it's a mess... I'll give a demo these days. Thanks 大佬

**Comment by afc163** [comment]
close for no response.
