### ISSUE TITLE
Form nested and array values mapPropsToFields not working

### ISSUE THREAD

**Issue by MathiasGilson** [ant-design/ant-design#7228]
### Version
2.12.6

### Environment
Chrome 60.0.3112.90 OSX (irrelevant in this case)

### Reproduction link
[https://codepen.io/MathiasGilson/pen/jLapPz](https://codepen.io/MathiasGilson/pen/jLapPz)

### Steps to reproduce
Try to use mapPropsToFields with an array (`[{ first: {value: "nameArray"} }]`) or a composed object (`{ first: {value: "nestedName"}}`) like in the [codepen](https://codepen.io/MathiasGilson/pen/jLapPz)

### What is expected?
This should set the corresponding inputs with the given values
getFieldDecorator('names[0].first') input should be set to "nameArray"
getFieldDecorator('name.first') input should be set to "nestedName"

### What is actually happening?
the input stay empty, no error in the console to debug

**Comment by MathiasGilson** [comment]
I guess the issue is coming from the required "value" property as nested and array fields appears to work natively in rc-form, check [this example](http://react-component.github.io/form/examples/nested-field.html) from the doc 
As you can see they are not using any value prop when setting the value of the fields
`this.props.form.setFieldsValue({
      member: [
        {
          name: {
            firstname: 'm1 first',
            lastname: 'm1 last',
          },
        },
        {
          name: {
            firstname: 'm2 first',
            lastname: 'm2 last',
          },
        },
      ],
      a: [
        [undefined, {
          b: {
            c: ['Value of a[0][1].b.c[0]'],
          },
        }],
      ],
      w: {
        x: {
          y: {
            z: ['Value of w.x.y.z[0]'],
          },
        },
      },
    });`

**Comment by MathiasGilson** [comment]
Ok I found that the "value" field check comes from rc-form code
here https://github.com/react-component/form/blob/c6f4c1cedf887989c760a2596d11cbfc14be70c3/src/createFieldsStore.js#L67
So this issue might not come from antd, I'll dig deeper into it

**Comment by MathiasGilson** [comment]
@benjycui can you help me ?
thx

**Comment by MathiasGilson** [comment]
Ok apparently the right way to make it work is to use setFieldsValue instead of mapPropsToFields. I manage to make it work in this [codepen](https://codepen.io/MathiasGilson/pen/ayqOwE)
Can someone confirm me that this is the recommended way of doing it ?
Should mapPropsToFields work too ?

**Comment by benjycui** [comment]
It's a known issue, I don't have enough time to dig into it. Need time to redesign data structure and behavior of nested fields.

**Comment by MathiasGilson** [comment]
Ok no worries thanks for your concern and your hard work
I was able to do what I wanted using setFieldsValue if anyone need some help with that please send me a message
Should I close the issue ?

**Comment by badaljain** [comment]
Hi @benjycui,

I have a form and I need to pass in the values, the fields are generated dynamically based on the input object. How can I approaach that? I cannot setField in componentWillReceiveProps as it ends up in infinite loop for sane reason, but whats the other way of doing it?

**Comment by badaljain** [comment]
I found a hack but I don't think its a recommended way of doing it!
something like this:

componentWillReceiveProps (nextProps) {
        const { getFieldDecorator } = this.props.form
        const { data } = nextProps
        if (!isEmpty(data)) {
            console.log(data)
            //form.setFieldsValue(data)
            getFieldDecorator('include[0][country]', { initialValue: data.include[0].country })
        }
    }

**Comment by benjycui** [comment]
Just use `mapPropsToFields`

**Comment by badaljain** [comment]
How can i use mapPropsToFields for dynamic fields? I have an array of countries and other data:

This is what i do in componentWillReceiveProps:

 ```
setNestedFields = (fieldName, fieldKeyWrapper, data) => {
        const { getFieldDecorator } = this.props.form

        data.forEach((value, index) => {
            const country = `${fieldName}[${index}][country]`
            const business = `${fieldName}[${index}][business]`
            const site = `${fieldName}[${index}][site]`
            getFieldDecorator(country, { initialValue: data[index].country })
            getFieldDecorator(business, { initialValue: data[index].business })
            getFieldDecorator(site, { initialValue: data[index].site })
        })
    }
```

**Comment by swierol** [comment]
Hi @badaljain,

This is my approach:
```javascript
function mapPropsToFields(props) {
  const fields = {
    client: Form.createFormField({ value: props.client }),
  }

  props.products.forEach((item, idx) => {
    fields[`products[${idx}].product`] = Form.createFormField({ value: item.product })
    fields[`products[${idx}].quantity`] = Form.createFormField({ value: item.quantity })
    fields[`products[${idx}].price`] = Form.createFormField({ value: item.price })
  })

  return fields
}
```

However in my case validation message is displayed only for the 1st field. Also I'm not able to update nested fields through `setFieldsValues`.

**Comment by badaljain** [comment]
Hi @swierol,

With my approach, I am able to resolve the issues that you have.
Just I need an extra boolean field to check if the fields are created once. otherwise it does into an infinite loop inside componentWillReceiveProps.

**Comment by chillyistkult** [comment]
I have more of a generic solution, but its still far from ideal. The main problem is that rc-forms expects the value field, which forces us to do a back and forth transformation if connected to a "normalized" redux store.

```
@connect(models => ({
  offer: models['newoffer/resource'],
  loading: models.loading.effects['newoffer/resource/load'],
  approving: models.loading.effects['newoffer/resource/approve'],
}))
@Form.create({
  mapPropsToFields: props => {
    const { data } = props.offer
    const transform = (obj) => {
      return Object.keys(obj).reduce((acc, cv) => {
        return {
          ...acc,
          [cv]: typeof obj[cv] === 'object' ? transform(obj[cv]) : Form.createFormField({
            value: obj[cv],
          }),
        }
      }, {})
    }
    return transform(data);
  },
  onFieldsChange(props, fields) {
    console.log('onFieldsChange', fields);
    props.dispatch({
      type: 'newoffer/resource/sync',
      payload: fields, // TODO: Additional data transformation is needed otherwise we will have all the form meta data in redux
    });
  },
})
```

**Comment by vincro** [comment]
I have used both the solution from @chillyistkult and @badaljain exclusively and together, but am unable to get the value of the field from the form using getFieldValue.  Does anyone have a working pre-populated example in a codepen? TIA

**Comment by zcmgyu** [comment]
Here is my solution

```
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Form, Input } from "antd";
import merge from "lodash/merge";
import isArray from "lodash/isArray";

const transform = obj => {
  return Object.keys(obj).reduce((acc, cv) => {
    return {
      ...acc,
      [cv]:
        typeof obj[cv] === "object" && !("value" in obj[cv])
          ? isArray(obj[cv])
            ? obj[cv].map(item => transform(item))
            : transform(obj[cv])
          : Form.createFormField({
              ...obj[cv],
              value: obj[cv].value
            })
    };
  }, {});
};

const CustomizedForm = Form.create({
  name: "global_state",
  onFieldsChange(props, changedFields) {
    props.onChange(changedFields);
  },
  mapPropsToFields(props) {
    const { user } = props;
    const transformed = transform({ user });
    return transformed;
  },
  onValuesChange(_, values) {
    console.log(values);
  }
})(props => {
  const { getFieldDecorator } = props.form;
  return (
    <Form layout="inline">
      <Form.Item label="Username">
        {getFieldDecorator("user.username", {})(<Input />)}
        {getFieldDecorator("user.password", {})(<Input />)}
        {getFieldDecorator("user.children[0].name", {})(<Input />)}
        {getFieldDecorator("user.children[1].name", {})(<Input />)}
      </Form.Item>
    </Form>
  );
});

class Demo extends React.Component {
  state = {
    fields: {
      user: {
        username: {
          value: "username"
        },
        password: {
          value: "password"
        },
        children: [
          {
            name: {
              value: "name1"
            }
          },
          {
            name: { value: "name2" }
          }
        ]
      }
    }
  };

  handleFormChange = changedFields => {
    this.setState(({ fields }) => {
      return {
        fields: merge(fields, changedFields)
      };
    });
  };

  render() {
    const fields = this.state.fields;
    return (
      <div>
        <CustomizedForm {...fields} onChange={this.handleFormChange} />
        <pre className="language-bash">{JSON.stringify(fields, null, 2)}</pre>
      </div>
    );
  }
}

ReactDOM.render(<Demo />, document.getElementById("container"));
```


https://codesandbox.io/s/2z2ojxy22r?fontsize=14
