### ISSUE TITLE
getFieldDecorator第二次验证状态会一直为Validating

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#7229]
### Version
undefined

### Environment
"antd": "^2.12.5",

### Reproduction link
[https://codepen.io/ouzhou/pen/oeoMex?editors=0011](https://codepen.io/ouzhou/pen/oeoMex?editors=0011)

### Steps to reproduce
点击2次checkbox，验证状态会一直为Validating

### What is expected?
第一次点击验证状态为Success， 第二次点击应该验证状态为Error

### What is actually happening?
第二次点击应该验证状态为Validating, 并且能通过验证，但是接受到的值为空对象

**Comment by benjycui** [comment]
`getFieldDecorator(id, opt)` 的 id 必须唯一，且不要一个 id 是另一个的后代。

No `format` `format.child` at the same time.
