### ISSUE TITLE
增加滑动解琐组件

### ISSUE THREAD

**Issue by superRaytin** [ant-design/ant-design#723]
类似 IOS 早期版本的滑动解琐

<img src="https://os.alipayobjects.com/rmsportal/UcROAfaDnIsoWpB.png" width="240" alt="滑动解琐">

Slider 组件目前有类似效果，不知在其基础上能否扩展完成，不过建议是新做组件，毕竟功能不相同

**Comment by afc163** [comment]
暂时不会增加。
