### ISSUE TITLE
Dropdown opening on contextmenu (right mouse button) click

### ISSUE THREAD

**Issue by Tarlord** [ant-design/ant-design#7232]
### What problem does this feature solve?
It would be very nice to have 3rd trigger value as 'context-menu' or 'contextMenu' for user to be able to open menu by right clicking on dropdown item. I had a request in my project and to solve it i was required to hardcode context menu click over dropdown and make all the hiding dropdown stuff on top of it(like when you click outside dropdown it was not triggered because i was manually setting up visible option). Thanks!
It's more like a feature not a bug :)

### What does the proposed API look like?
```
ReactDOM.render(<div>
  <Dropdown overlay={menu} trigger={['contextMenu']}>
    <a className="ant-dropdown-link" href="#">
      Click me <Icon type="down" />
    </a>
  </Dropdown>
</div>, mountNode);
```

**Comment by benjycui** [comment]
Try:

```jsx
<Dropdown overlay={menu} visible={visible} onVisibleChange={this.handleVisibleChange}>
  <a className="ant-dropdown-link" href="#" onContextMenu={this.handleVisibleChange}>
    Click me <Icon type="down" />
  </a>
</Dropdown>
```

**Comment by benjycui** [comment]
Right click is rarely used in web, it's not recommended to do so.

**Comment by afc163** [comment]
It could be useful for electron environment.

**Comment by MrPeak** [comment]
The dependency chain is as follows：

0. ant-design/dropdown
1. react-component/dropdown
2. react-component/trigger
