### ISSUE TITLE
Modal.xxx() 系列方法能否自定义footer(custom footer)

### ISSUE THREAD

**Issue by yikuyirong** [ant-design/ant-design#7235]
### What problem does this feature solve?
Modal内容中为自定义表单（很多种），在应用中需要根据场景动态打开Modal，然后关闭销毁。这样不适合嵌入<Modal />写法。如能隐藏footer，拟用表单的button替代；或支持自定义footer。

### What does the proposed API look like?
Modal.xxx({footer:React.Node,...other})

**Comment by benjycui** [comment]
Nope, `Modal.xxx` is just for convenient, if you want more flexibility, just use Modal
