### ISSUE TITLE
add @menu-collapsed-width to themes/default.less

### ISSUE THREAD

**Issue by lvren** [ant-design/ant-design#7236]
### What problem does this feature solve?
将@menu-collapsed-width这个变量移动到全局theme中，可以配置侧边栏收起时的宽度

move @menu-collapsed-width from menu/style/index.less to style/themes/default.less, so we can edit width for sider menu

### What does the proposed API look like?
move @menu-collapsed-width from menu/style/index.less to style/themes/default.less

**Comment by afc163** [comment]
PR Welcomes

**Comment by lvren** [comment]
提了PR，#7238
