### ISSUE TITLE
tree设置checkStrictly为true时,节点checkable勾选操作是否只能从half过渡到完全选中状态，才能过滤到取消状态

### ISSUE THREAD

**Issue by tofdragon** [ant-design/ant-design#7242]
### Version
2.9.1

### Environment
chorme

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-basic-controlled](https://ant.design/components/tree-cn/#components-tree-demo-basic-controlled)

### Steps to reproduce
checkStrictly=true，实现随机勾选模式,或者勾选父不勾选子模式
1.勾选父节点,子节点一个没勾选，则父节为half状态
2.在勾选父节点，根据业务逻辑一个子节点没勾选应该也为half状态
3.此刻应该如何取消了？

### What is expected?
自行控制勾选级联关系时，如果是随机勾选，则父勾选为hafl状态时，应该会根据状态直接变成未勾选状态

### What is actually happening?
必须从half过渡到完全勾选，才能到取消勾选

**Comment by benjycui** [comment]
你提供的链接和你的描述没关系吧。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by tofdragon** [comment]
问题已解决，是自定义实现的问题，和组件没关系，谢谢

**Comment by benjycui** [comment]
只能适配常见场景，特殊场景则需要基于受控模式自定义。

**Comment by zjdschnappi** [comment]
@tofdragon @benjycui  这里有一个需求，父节点选中时，子节点全部选中，但子节点一个一个勾满时，父节点不会勾上，，简单说时父关联子，但子不关联父。用checkStrictly自己来写入checked，和halfChecked数组，搞了好久，实在是没办法了。特来请教 麻烦能不能给一点思路呢

**Comment by nttdocomo** [comment]
> @tofdragon @benjycui 这里有一个需求，父节点选中时，子节点全部选中，但子节点一个一个勾满时，父节点不会勾上，，简单说时父关联子，但子不关联父。用checkStrictly自己来写入checked，和halfChecked数组，搞了好久，实在是没办法了。特来请教 麻烦能不能给一点思路呢

自己控制checkedkeys就好了
