### ISSUE TITLE
onCellClick 应包含点击行的 index

### ISSUE THREAD

**Issue by loki20140606** [ant-design/ant-design#7243]
### What problem does this feature solve?
onCellClick 既然放在 Column 中进行配置，那获取点击行的 index 尤为重要

### What does the proposed API look like?
参考同在 Column 中的 render 方法 Function(text, record, index) {}，可以为 Function(record, event, index) {}

**Comment by yesmeck** [comment]
`index` 的用处是？

**Comment by loki20140606** [comment]
定位点击的是哪一行的单元格

**Comment by yesmeck** [comment]
描述你你完整的需求吧

**Comment by loki20140606** [comment]
例如我想点击单元格后弹出 modal 修改这个值，虽然我可以在 record 中绑定点击事件实现，但发现这个方法后挺想使用，但是 onCellClick 只告诉我了我点击的这一行的数据 record，却没有这个数据在 dataSource 中的 index，那我就没法完成上述逻辑了。

**Comment by yesmeck** [comment]
自己用 `indexOf` 去找 `dataSource` 里 `record` 的 `index`，现在表格返回的  `index` 不一定是这个 `record` 原来在 `dataSource` 里的 `index`。

**Comment by loki20140606** [comment]
非常感谢，确实是这样“现在表格返回的 `index` 不一定是这个 `record` 原来在 `dataSource` 里的 `index`。”
