### ISSUE TITLE
Form.create(option) 对Select值进行控制，当为空值时 placeholder不显示，Input没问题

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#7244]
### Version
2.12.6

### Environment
chrome较新版

### Reproduction link
[https://codepen.io/madaos/pen/YVmXYY](https://codepen.io/madaos/pen/YVmXYY)

### Steps to reproduce
https://codepen.io/madaos/pen/YVmXYY

### What is expected?
希望 select placeholder 在使用 form.create(option) 进行绑定值之后 空值情况下可以正常显示

### What is actually happening?
不显示

**Comment by afc163** [comment]
Set `value` of Select to `undefined`: https://codepen.io/anon/pen/WEdXPK
