### ISSUE TITLE
Menu Item direction

### ISSUE THREAD

**Issue by jponc** [ant-design/ant-design#7247]
### What problem does this feature solve?
How to implement number 3 of the one below?

https://github.com/ant-design/ant-design/blob/master/docs/pattern/navigation.en-US.md#side-navigation

### What does the proposed API look like?
Menu.Item right ?

**Comment by benjycui** [comment]
？？？？？

**Comment by afc163** [comment]
http://ant.design/components/dropdown

**Comment by jponc** [comment]
I was aking how do you implement #3 of that side-navigation thing via Menu.Item component. How do you align Menu Items to the right?

**Comment by afc163** [comment]
https://ant.design/components/dropdown/#components-dropdown-demo-placement
