### ISSUE TITLE
Add sort to the child column dynamically.

### ISSUE THREAD

**Issue by likhita-palavali** [ant-design/ant-design#7248]
<img width="574" alt="screen shot 2017-08-17 at 11 54 50 am" src="https://user-images.githubusercontent.com/17817231/29428695-f70ad6b4-8342-11e7-9260-2f3218163a8b.png">
### What problem does this feature solve?
In my project I have used "Grouping Table head" Component. Now I need to provide sorting feature for child column dynamically. The data that I have is dynamic.

### What does the proposed API look like?
The api should solve sorting based on the child column with dynamic data.
Example of the api should have sorting icon on %Diff of both grouped columns dynamically.

**Comment by benjycui** [comment]
You can pass new `Table[columns]` when you want to add sorting feature to a child column dynamically.
