### ISSUE TITLE
希望antd中有类似bootstrap的clearfix的公共样式可以使用

### ISSUE THREAD

**Issue by wgqi1126** [ant-design/ant-design#7253]
### What problem does this feature solve?
自己写一些样式的时候不用再自己造轮子

### What does the proposed API look like?
```
import style from 'antd/common-styles';

<div class={style.clearfix}>
...
</div>
```

**Comment by afc163** [comment]
Actually, you can use `clearfix` now but it is not recommended. Because we only provide open API as react components.

https://github.com/ant-design/ant-design/blob/efcc28ed510a6b5d31b0d07492416850611711de/components/style/core/base.less#L119
