### ISSUE TITLE
How to set the default value checked in the Table component?

### ISSUE THREAD

**Issue by fachilles** [ant-design/ant-design#7255]
### What problem does this feature solve?
There is a table with the checkbox in the first column. After loading the data, it needs to set the checkbox checked that is in default value array. And how to handle the function. I tried to resolve the features as follows, but not working.

```
rowSelection={{
    onChange: (selectedRowKeys, selectedRows) => {
        this.setState({selectRegions: selectedRows});
    },
    getCheckboxProps: record => ({
        checked: record.name === 'checked data', 
    }),
}}
```

### What does the proposed API look like?
Any ideas for the issues?

**Comment by nikogu** [comment]
api: https://ant.design/components/table-cn/#rowSelection
demo: https://ant.design/components/table/#components-table-demo-row-selection-custom
