### ISSUE TITLE
no "id" attribute in inputNumber component

### ISSUE THREAD

**Issue by zhengying** [ant-design/ant-design#7257]
### Version
2.12.6

### Environment
browser version

### Reproduction link
[https://ant.design/components/input-number/](https://ant.design/components/input-number/)

### Steps to reproduce
no id attribute， no need reproduce

### What is expected?
the Input component have "id" attribute, but the attribute not exist in inputNumber component, we need id attribute to locate one of some dynamic inputNumbers.

### What is actually happening?
no "id" attribute in inputNumber component
...
 <InputNumber
                id={index}
                onChange={this.onChange}
>
...
  onChange = (e: any) => {
    let index = e.target.id;  // e.target.id is null
  }

---
please add id property

**Comment by benjycui** [comment]
https://github.com/react-component/input-number/blob/939751699f289ce0bb9ea41d66c23d282841067a/src/index.js#L274

**Comment by benjycui** [comment]
If you still meet this issue, please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
I assumed you mean TypeScript definition.

**Comment by zhengying** [comment]
thanks,
In fact, I encountered another bug  in my version 2.10.1，and I can't find "id" attribute in TypeScript definition, I mistakenly believe that there is no id in inputNumber.

the InputNumber component have an wrong behavor that onChange  parameter is value not event object.
[reproduce demo!](https://codepen.io/zhengyingok/pen/xLYQzN)

I test in latest version it's ok
