### ISSUE TITLE
Give interfaces to customize Menu styles.

### ISSUE THREAD

**Issue by cxyxc** [ant-design/ant-design#7260]
### What problem does this feature solve?
When I want to customize Menu, I have to cover css to do it. I hope interfaces to do it more easily.

### What does the proposed API look like?
lightBgColor  = {}, hoverBgColor = {} ...

**Comment by cxyxc** [comment]
I hope my Menu like this, so I have to cover antd css. But when antd upgrade, I do it repeate in all probability. Can antd Menu have a beaufitul style, or give some interfaces to change style?
![image](https://user-images.githubusercontent.com/20027281/29454190-cfc09b96-843e-11e7-8389-f7a1c235521d.png)

**Comment by afc163** [comment]
Try override the style by custom className.
