### ISSUE TITLE
TabPane中的组件使用 <a>标签链接本页某个地方，页面显示不正常。是多个TabPane加载后问题？？？

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design#7265]
### Version
2.12.6

### Environment
chrome ie

### Reproduction link
[https://github.com/google88888888/configurableOfficialWebsite/tree/master/client](https://github.com/google88888888/configurableOfficialWebsite/tree/master/client)

### Steps to reproduce
把TabPane随便点击几下，使其都加载一遍，然后点击产品中心，点击产品简介

### What is expected?
把TabPane随便点击几下，使其都加载一遍，然后点击产品中心，点击产品简介，链接到产品简介，页面显示没问题

### What is actually happening?
把TabPane随便点击几下，使其都加载一遍，然后点击产品中心，点击产品简介，链接到产品简介，页面显示有问题

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Please provide more information and a re-producible online codepen.

**Comment by liyun074** [comment]
请问这个问题您是怎么解决的呢？I have same problem。。。
