### ISSUE TITLE
Checkbox.Group 和 Radio.Group 的 disabled 机制不一样，应该 group 的 disabled 禁用优先级更高，checkbox 是错的

### ISSUE THREAD

**Issue by reoszo** [ant-design/ant-design#7266]
### Version
2.12.6

### Environment
all

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Radio 源码：radioProps.disabled = props.disabled || radioGroup.disabled;
Checkbox 源码：checkboxProps.disabled = 'disabled' in props ? props.disabled : checkboxGroup.disabled;

### What is expected?
Checkbox.Group disable 时，所有 Checkbox disable。

### What is actually happening?
Checkbox 根据自己的 disabled 属性显示禁用状态

**Comment by benjycui** [comment]
按我的理解，应该是 Checkbox 的才是对的，就像 CSS 样式那样，直接加到元素本身的样式，优先级在继承过来的之上。

**Comment by benjycui** [comment]
@reoszo 来个 PR?

**Comment by reoszo** [comment]
你按照的是研发的代码角度看的，要是考虑使用上来说，组都disable了，单项还能用？

**Comment by afc163** [comment]
Checkbox 的属性优先是更合理的。

**Comment by reoszo** [comment]
你确定？业务中使用人员的情况了解一下吧

**Comment by reoszo** [comment]
要是Checkbox是对的，我就不pr了，我自己改我们的Checkbox了，[苦笑]

**Comment by afc163** [comment]
我先找找其他 UI 库的做法。

**Comment by afc163** [comment]
> 按我的理解，应该是 Checkbox 的才是对的，就像 CSS 样式那样，直接加到元素本身的样式，优先级在继承过来的之上。

我理解 @reoszo 的思路了，disabled 不是从 Group 上继承过来的属性。而是 Group 本身的属性和 Checkbox/Radio 自身属性的『或』叠加，只要有一个 disabled 就应该 disabled。

所以 @reoszo 应该是对的，来个 PR 吧。最好补上用例。

**Comment by reoszo** [comment]
吼

**Comment by reoszo** [comment]
就一行代码啊，你们顺手改了吧，呵呵

**Comment by afc163** [comment]
贡献一下，后面说不定还有 bug。

**Comment by reoszo** [comment]
好，我试一把先

**Comment by afc163** [comment]
Thx! @dilidili
