### ISSUE TITLE
When deleting one item in uploaded list, another one will be deleted strangely.

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#7269]
### Version
2.12.6

### Environment
MacOS 10.12.6 (16G29), Chrome  60.0.3112.101

### Reproduction link
[https://codepen.io/leadream/pen/Yxaqwa](https://codepen.io/leadream/pen/Yxaqwa)

### Steps to reproduce
In component `Upload`, if it's `props.defaultFileList` has two items, the first item with `id=0` and another item with the same name as the first one, deleting the first one will trigger deleting the second one strangely.

### What is expected?
just delete the clicked item 

### What is actually happening?
deleting one item will trigger deleting two items

**Comment by leadream** [comment]
@afc163 不好意思，请问为什么关了？

**Comment by afc163** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/507615/29493077-3b3e330a-85c1-11e7-880d-8b6101d47bd8.png">

**Comment by afc163** [comment]
？这个 commit 修复了呀。

**Comment by leadream** [comment]
sorry, 我傻了，还以为那个链接是指向当前 issue 呢，😅。不好意思，周末打扰了。
