### ISSUE TITLE
TimePicker 报错

### ISSUE THREAD

**Issue by whb101** [ant-design/ant-design#727]
TimePicker value="12:08:23"  defaultValue="12:08:23"  format="HH:mm:ss"我这样写  然后告诉我报错了  

这个错：
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)

**Comment by benjycui** [comment]
你用的是什么版本的 antd，然后引入的方式是？

**Comment by whb101** [comment]
0.10.4  import 进去的  其他组件都好好的，就这个组件很奇怪 一直报这个错 都是按你们文档那样写了 还是不行，日期组件都没问题

**Comment by benjycui** [comment]
请查看对应版本的文档 http://010x.ant.design/

**Comment by whb101** [comment]
就是0.10.4 那个版本上面看的啊 还是报错

**Comment by whb101** [comment]
断点看那个type 是undefined

**Comment by afc163** [comment]
0.10.4 是 Timepicker。让你按老文档来写了。

**Comment by whb101** [comment]
那以后升级后 Timepicker 可以还可以用吗还是要改成TimePicker

**Comment by afc163** [comment]
对升级之后要改名。0.11.0 还没发布，你可以关注一下我们的 PR。https://github.com/ant-design/ant-design/pull/700
