### ISSUE TITLE
Input TextArea: can not  use javascript to set the disabled TextArea 

### ISSUE THREAD

**Issue by MrStronger** [ant-design/ant-design#7270]
### Version
2.12.6

### Environment
Windows 10/Chrome 60/null

### Reproduction link
[https://codepen.io/alice_tao/pen/QMmNrb?editors=0010](https://codepen.io/alice_tao/pen/QMmNrb?editors=0010)

### Steps to reproduce
handleClick = () => {
    document.getElementById('textarea').disabled = false
    document.getElementById('textarea').focus()
  }
  render() {
    return (
      <div>
        
        <TextArea rows={4} disabled id='textarea' />
        <Button style={{marginTop: '20px'}} onClick={this.handleClick}>enabled</Button>
      </div>
    );
  }

### What is expected?
textarea can be edited when click the button

### What is actually happening?
textarea can not be edited when click the button

**Comment by afc163** [comment]
Don't do that, you should use `disabled={xxxx}`.

Please learn React before you use antd: http://facebook.github.io/react/

**Comment by MrStronger** [comment]
`<TextArea rows={4} disabled={true} id='textarea' />`
https://codepen.io/alice_tao/pen/QMmNrb?editors=0010

sorry, do you mean this ? textarea can be edited indeed, but the style of the mouse when hover on textarea is still disabled

**Comment by MrStronger** [comment]
Thanks!
