### ISSUE TITLE
table是否能增加一个功能点击一行变色，现在只有鼠标移上去变色

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#7273]
### What problem does this feature solve?
如果增加了点击一行变色功能，这样我修改一行记录的时候就不用去点最左边那个复选框，那个复选框有时我还不一定要的，如果有这个功能，我可以去复选框去掉还可以多出一个位置来，因为有的屏幕还有好多好小的，可以省下来一些空间摆放

### What does the proposed API look like?
加一个方法就ok了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/search?q=table+%E8%A1%8C+%E7%82%B9%E5%87%BB&type=Issues&utf8=%E2%9C%93
