### ISSUE TITLE
Remove babel-plugin-import warning message in antd/es/index.js

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#7275]
https://unpkg.com/antd/es/index.js
https://github.com/crystalschang/gulp-env

**Comment by benjycui** [comment]
es 目录下的不重要吧，see: https://unpkg.com/react@15.6.1/lib/React.js

业务配置里面配合 webpack DefinePlugin 和 uglify 就可以了。

**Comment by afc163** [comment]
主要是这句在 es 下没必要出现了。

```
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
```

**Comment by hnsylitao** [comment]
i use babel-plugin-import 
Is it in development remove warning

**Comment by afc163** [comment]
https://unpkg.com/antd@2.13.2/lib/index.js

@yesmeck lib 下的 warning 从 2.13.2 之后也没了。

**Comment by yesmeck** [comment]
😅 https://github.com/ant-design/antd-tools/commit/856cca716b4e05e4df268982be8acae8c0359fa4

**Comment by afc163** [comment]
Fixed in `2.13.8`.
