### ISSUE TITLE
wrong indeterminate status in Tree when has disabled child nodes

### ISSUE THREAD

**Issue by beiduo** [ant-design/ant-design#7277]
### Version
2.12.7

### Environment
mac os 10.12.2, chrome 60.0.3112.90

### Reproduction link
https://codepen.io/anon/pen/xLWJOJ?&editors=001 

### Steps to reproduce
when 0-0-0-0, 0-0-0-1, 0-0-0-2 and 0-0-2 were checked. 

if: 

1) 0-0-1 and its children were not checked
2) 0-0-1 and its children were all checked

### What is expected?
as i am assuming:
in case of 1, "0-0" should be in indeterminate status,
in case of 2, "0-0" should be checked

### What is actually happening?
the results are quite opposite

---
it happens in the official demo: https://ant.design/components/tree-cn/ the second example

**Comment by afc163** [comment]
You codepen is empty.

**Comment by beiduo** [comment]
@afc163 sorry i just click the link to codepen in the example page and didn't realize that it has not been saved. please use the example page instead (as mentioned in the bottom line)

**Comment by benjycui** [comment]
@beiduo Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by beiduo** [comment]
@benjycui ok, i just saved a copy in here https://codepen.io/anon/pen/xLWJOJ?&editors=001

**Comment by likun7981** [comment]
this demo 
https://ant.design/components/tree-cn/#components-tree-demo-basic-controlled.

the parentNode `0-0`  checkState is wrong
