### ISSUE TITLE
Improve Forms inside Modals: Allow for stateful form components

### ISSUE THREAD

**Issue by tim-soft** [ant-design/ant-design#7279]
### What problem does this feature solve?
The current docs suggest wrapping a stateless Modal component containing a Form inside a parent wrapping component. 

https://ant.design/components/form/#components-form-demo-form-in-modal

Here are the limitations that I am running into, these are pretty typical circumstances:
1. I have a form that must do some async data fetching before displaying (get data for select fields etc). It would be ideal to open the Modal with a spinner during this loading period, then show the form when it's ready. Due to the stateless nature of the Modal example, updating the form is not possible. If the modal is NOT stateless, updating it's body will trigger a re-render every time the loading state changes.

2. Several forms that I'd like to put into Modals rely on many functions, stateless components do not have functions so they must be passed in as props

### What does the proposed API look like?
That is a very good question!

**Comment by benjycui** [comment]
Yep, we use stateless component to wrap Modal and Form in our demo, but you can use normal component, too. It is more than a usage question.
