### ISSUE TITLE
Select.Option should add "style" property ,  typescript

### ISSUE THREAD

**Issue by shengliangli** [ant-design/ant-design#7280]
### Version
2.12.7

### Environment
typescript 2.4

### Reproduction link
[http://none](http://none)

### Steps to reproduce
```
<Select>
  <Select.Option key={'xxx'} style={{color: 'red'}}>
</Select>
```
the code work well, but typescript report a error:
```
[ts] Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, ComponentState>> & Readonly...'.
```
### What is expected?
typescript pass

### What is actually happening?
typescript has a error report

**Comment by benjycui** [comment]
Actually, there is no `style` on `Select.Option`.

**Comment by benjycui** [comment]
It's an empty component, just a carrier. See: https://github.com/react-component/select/blob/master/src/Option.jsx

**Comment by yesmeck** [comment]
As @benjycui said d
