### ISSUE TITLE
如何在Pagination 组件上获取table上的过滤和排序

### ISSUE THREAD

**Issue by limaoscript** [ant-design/ant-design#7283]
### What problem does this feature solve?
获取 过滤和排序参数
Get filtering and sorting params
### What does the proposed API look like?
是否能像 table 的 onChange 可以获取 filter sort 参数，因为 Pagenation 不能获取
Whether it can be like the table onChange can get filter sort params, because Pagenation can not get

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-ajax

**Comment by limaoscript** [comment]
thanks!
