### ISSUE TITLE
calendar 没有农历, 星期格式的选项设置

### ISSUE THREAD

**Issue by pengfeiWang** [ant-design/ant-design#7284]
### Version
2.12.7

### Environment
macos

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
https://codepen.io/pen/?&editors=001

### What is expected?
增加 农历, week 形式选项

### What is actually happening?
没有类似处理, api 也没有详尽说明

**Comment by afc163** [comment]
If you request a feature, please use the feature request template.

**Comment by pengfeiWang** [comment]
应该尝试把中文推出去, 而不是一味的强调用E文

**Comment by pkaq** [comment]
我也需要农历哎
