### ISSUE TITLE
I hope the ValidateFieldsAndScroll can provide a marginTop parameter

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#7287]
### What problem does this feature solve?
If i have a fixed component on the top of the page.I hope when i use ValidateFieldsAndScroll, I can control the marginTop parameter  to avoid the form being obscured;

The current performance @ https://codepen.io/anon/pen/yojKBJ

### What does the proposed API look like?
Function([fieldNames: string[]], options: object, callback: Function(errors, values),[marginTop:string[]])

**Comment by afc163** [comment]
补充一下 antd 文档。

**Comment by buxuku** [comment]
THX.
