### ISSUE TITLE
select的数据联动问题

### ISSUE THREAD

**Issue by cpu220** [ant-design/ant-design#7289]
### Version
2.12.7

### Environment
os10.12.6/chrome60.0.3112.101

### Reproduction link
[https://github.com/cpu220/test](https://github.com/cpu220/test)

### Steps to reproduce
 手动select选择后，点击测试按钮

### What is expected?
select随数据变更而变更

### What is actually happening?
1. 在不碰触select的时候，点击【测试】按钮，随机更改数据，select会随数据变更而变更
2. 但手动点击select，变更选择后，再点测试来更改数据源，select并不会变更，然而redux看到数据已更改

---
1. demo内附2个案例，一个是纯select组件，通过动态修改value值可以做到(已注释)
2. 另一个是form表单，有且仅有一个select表单项，业务场景碰到select联动，则出现反馈问题，数据已变更，render也触发了，但手动select.option 之后，数据则无效

![](http://7xqv6o.com1.z0.glb.clouddn.com/333.gif)

**Comment by yesmeck** [comment]
`setFieldsValue` to set `getFieldDecorator` decorated select.

**Comment by cpu220** [comment]
@yesmeck 
1. 你并没有看懂我的意思
2. 我是父组件改变数据源，通过props传入子组件，且并没有手动操作select的情况下触发render来改变select's initialValue，这是ok的。
3. 我意思是说，一旦我手动操作了select，那么虽然触发了render，却再也不能修改select's initialValue,如果因为props修改了数据源，componentWillReceiveProps使用setFieldsValue死循环。虽然antd 说是可以用mapPropsToFields，但不觉得一个简单的问题被复杂化了？其他的form表单项并没有这种问题。
4. 我demo里`已经` 有`setFieldsValue `说明我并不是简单的要改一个值，我所想要表达的，就是select无法项其他form组件那样，而是因为手动选择这种行为过后，而无法通过render来重新渲染来改变当前组件value的不合理

**Comment by benjycui** [comment]
@yesmeck is right.

`initialValue` is just a placeholder, if you had change the value of select, we should use new value, even you had changed `initialValue`.

**Comment by afc163** [comment]
https://github.com/react-component/form/issues/98
