### ISSUE TITLE
Error walking down react tree

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#7290]
### Version
2.12.7

### Environment
Mac OS Sierra, Newest Google Chrome

### Reproduction link
[https://github.com/ctrlplusb/react-universally](https://github.com/ctrlplusb/react-universally)

### Steps to reproduce
Promise this will be the last issue, but it seems like this Github is the only place we can get help from related to AntUI. It may also help other people in deploying their own projects

Simple project with `React universally` boilerplate. I've struggled with adding AntUI with `babel-plugin-import` to it but I found the solution - the line added in `internal/webpack/configFactory.js` around line `419`.
`ifDevClient(['import', { libraryName: 'antd', style: 'css' }]),`

Now I want to build the project so we can finally deploy its first version. `AntUI` with this config is not included in the production, so I added `ifProdClient(['import', { libraryName: 'antd', style: 'css' }]),`. Built process went through, `yarn run start` and it seems to work, but as soon as I open the homepage I get:

```
Error walking your react tree
ReferenceError: Menu is not defined // Menu is the first AntUI component used inside the app
```

Any idea what might be the problem here? 

### What is expected?
App running as in the dev mode

### What is actually happening?
Error walking your react tree

**Comment by Ancinek** [comment]
I think I got this. This seems to be related to `transform-react-inline-elements` plugin. For now, I'm gonna disable it as there have been too many hours for now. Hope this helps someone.

**Comment by benjycui** [comment]
@Ancinek it seems that you are not reporting a bug about antd..

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5060#issuecomment-283339199
