### ISSUE TITLE
form has ability to set field isTouched.  表单能够设置某个表单项的 isTouched 的值

### ISSUE THREAD

**Issue by pannz** [ant-design/ant-design#7293]
### What problem does this feature solve?
en description:
I encountered this problem by this:
there is a form that contains many form item, inside there is a upload component item.  And the form is wrapped by From.create(). my problem happened on the upload item, here is the code:

```
<FormItem {...formItemProps}>
    {
         getFieldDecorator( 'url',  {...})(
               <Input style={{display: 'none'}}/>
         )
    }
    <Dragger {..draggerProps}>...</Dragger> 
</FormItem>
```

I use getFieldDecorator to decorate a hidden input, and put the upload outside decorator function.
the upload onChange event handler get the uploaded image url and set to decorated value `url` by `form.setFieldValue({ url : 'xxx'})`. ( I am not putting upload component inside the field decorator because `url` value would be a file object if it is inside the field decorator, and I think use hidden input is better)
And by this way the `url` value would be correct set and validate.  When we try to update the form by change some items, we usually call `form.isFieldsTouched()` method before confirm submit to check if the form is really changed, if return false, we think there is no update. And the problem is there, when I only change the upload item (I only want to update the uploaded image) then submit my change, the `form.isFieldsTouched()` says false. 
In my comprehension, the `url` is decorated, in my case it was set by upload onChange function, so  the decorator can't detect this ? 
so, there should be another API that has ability to directly set field touched status?
or the existence API some how can resolve this case?

---

我是这么遇到问题的，需求是表单里一个有上传图片的表单项，然后写的时候是用From.create() 包装的 from，对上传表单项我处理的方法是 

```
<FormItem {...formItemProps}>
    {
         getFieldDecorator( 'url',  {...})(
               <Input style={{display: 'none'}}/>
         )
    }
    <Dragger {...draggerProps}>...</Dragger> 
</FormItem>
```

我是用 decorator 装饰一个隐藏的 input，把上传组件置于 decorator 外，用onChange 事件处理把上传的 url 取到后，通过 from.setFieldValue({url : 'xxx'}) 设置表单项的值（之所以这样处理是因为如果把上传组件放在装饰内部，url的value会是一个 file object，我觉得用上面的方式处理比较清晰）
这样处理后值是可以被正确set，validate 的时候也能正确得到并验证，但是，如果这个有多个表单项的表单仅仅只更改了这个上传（比如在这个表单仅仅更新上传的图片这样的操作），在保存的时候在判断 isFieldsTouched 来做只有修改才更新的判断，这个isFieldsTouched 返回 false，表单会认为没有修改。
我理解是 url 值是装饰过的，这里是通过其他的函数直接设置 url 的值，decorator 无法检测到 url 值的变化？
所以，是否应该存在一个接口，可以改变某个表单项的 isTouched 的值。
或者 form 现有的 api 其实能够完成的功能？

### What does the proposed API look like?
setFiledTouched: Function(fieldName, boolean)
// or setFieldIsTouched

**Comment by pannz** [comment]
any ideas ?

**Comment by pannz** [comment]
codepen demo：message consoled on console，see with console view.
inside decorator：https://codepen.io/pannz/pen/BdGBNj
outside decorator：https://codepen.io/pannz/pen/GvwKRK

**Comment by benjycui** [comment]
这样很诡异，自行增加一个 flag 作为标记吧：

```jsx
if (manualTouchedFlag || isFieldsTouched(name)) {
  ...
}
```

**Comment by pannz** [comment]
添加 flag 我觉得只是个 hack，不是一个好的解决办法。而且，如果在 form 组件内 validate，加个 flag 还能接受，要是在 from 组件外，通过 ref 把实例赋给父组件，在父组件 validate，还需要往表单再传一个 handleFlag 的 prop，这个应该由 from 内部处理比较合适
