### ISSUE TITLE
表格的rowSelection怎么去掉默认选项

### ISSUE THREAD

**Issue by iamhanson** [ant-design/ant-design#7295]
### What problem does this feature solve?
给表格的复选框rowSelection添加自定义配置时，默认的全选当页和反选当页无法删除或者修改

### What does the proposed API look like?
给表格的复选框rowSelection添加自定义配置时，默认的全选当页和反选当页可以去除或者修改

这个是使用ant实现的。

`const rowSelection = {
      selectedRowKeys,
      selections: [{
        key: "all-data",
        text: '所有',
        onSelect: (changableRowKeys) => {
        },
      }],
      onChange: (selectedRowKeys, selectedRows) => {
        _this.setState({ selectedRowKeys, isAll: 0, selectedRows });
      }
    };`

![e9fab7c4-0589-4b09-a2e8-fc24a59b2af1](https://user-images.githubusercontent.com/3264635/29601859-24d22fe4-8810-11e7-8d78-fdbe1896f1ef.png)

这个是产品期望的逻辑，使用了selections之后，只增加了一个，但是默认的全选当页和反选当页无法去除或者修改，另外，key="all"和key="invert" 估计是这两个默认字段的key，因为新增的key如果是这两个，会无法显示出来。
![qq20170823-143352 2x](https://user-images.githubusercontent.com/3264635/29601857-24ad67e0-8810-11e7-85bc-6e1f11b55a4a.jpg)

**Comment by yesmeck** [comment]
`rowSelection.selections`

**Comment by iamhanson** [comment]
求大神解答

**Comment by afc163** [comment]
目前貌似去不掉。

**Comment by iamhanson** [comment]
@afc163 扎心了，多谢解答，只能用css硬上了，期待后续的版本调整

**Comment by chafel** [comment]
👍  Thanks for quick response

**Comment by nowdothat** [comment]
now can success remove ?, I try trigger function, bug can't remove Class="ant-checkbox ant-checkbox-checked"
