### ISSUE TITLE
Link of react-blocks is wrong

### ISSUE THREAD

**Issue by ziluo** [ant-design/ant-design#7297]
### Version
2.12.7

### Environment
PC Browser

### Reproduction link
[https://ant.design/components/grid-cn/](https://ant.design/components/grid-cn/)

### Steps to reproduce
  open `https://ant.design/components/grid-cn/`
  click the `react-blocks`, then go to a `404` page of Github

### What is expected?
go to `https://github.com/whoisandy/react-blocks`

### What is actually happening?
go to `404`

**Comment by afc163** [comment]
PR is welcomes~

**Comment by ziluo** [comment]
PR is done
