### ISSUE TITLE
table  Scroll bars are not displayed

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#7298]
### Version
2.12.7

### Environment
antd version 2.12.7

### Reproduction link
[https://github.com/qq645381995/antdDemo/tree/master](https://github.com/qq645381995/antdDemo/tree/master)

### Steps to reproduce
npm i ; npm start; open localhost:4000
 

### What is expected?
Display scrollbars

### What is actually happening?
Scroll bars are not displayed

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/29605301-ebc0cc58-881c-11e7-80f7-77350a321bd3.png)

**Comment by qq645381995** [comment]
@afc163

**Comment by afc163** [comment]
It is hard to resolve #7142 and this issue perfectly..

**Comment by qq645381995** [comment]
@afc163 
please update https://github.com/qq645381995/antdDemo/tree/master
I described the gap that I expected
I hope that the countless data will not be render, so the format will have problems

**Comment by afc163** [comment]
https://github.com/react-component/table/issues/163

The fix breaks this one. I gonne give up this issue and revert the changes.
