### ISSUE TITLE
Modal 设置key时, form自带的表单验证,在第二次打开modal的时候 不会进行验证了

### ISSUE THREAD

**Issue by 330551887** [ant-design/ant-design#7302]
### Version
2.12.7

### Environment
win10,  Chrom

### Reproduction link
[https://codepen.io/anon/pen/BdVWWp?editors=0010](https://codepen.io/anon/pen/BdVWWp?editors=0010)

### Steps to reproduce
1, 点击open 按钮, 点击确定按钮, 出现 Not Null, 然后关闭 modal.
2, 再次点击open按钮, 点击确定按钮, 就不会再验证输入框了.
3,原因是 打开时给 Modal 设置一个全新的 key, 结果就不验证了. 不设置全新的key 就没有问题了.

### What is expected?
期望给 Modal 设置一个全新的 key时, 第二次 打开modal  还可以继续验证输入框.

### What is actually happening?
实际结果是   给 Modal 设置一个全新的 key时, 第二次 打开modal  ,点击确定的时候 输入框不做验证了

**Comment by xiaoHuangliu** [comment]
厉害了   已收藏

**Comment by feizhoudayelv** [comment]
同上问题求解决

**Comment by annu2007** [comment]
同上 同上 谁来解决啊 急急急!!!

**Comment by PhoebeLove** [comment]
同上问题求解决

**Comment by feizhoudayelv** [comment]
楼上的你们都怎么做啊

**Comment by DevilSA** [comment]
同上 同上 谁来解决啊 急急急!!!

**Comment by 1434326696** [comment]
楼上是演员，已举报， 这个，这个问题

**Comment by henry1027** [comment]
楼主这问题问的好啊，我们项目组棉花团怒正好也有这个问题，求解啊！！！急急急！！！

**Comment by feizhoudayelv** [comment]
双击加关注，双击666老铁

**Comment by DevilSA** [comment]
同上 谁来解决啊 急~

**Comment by afc163** [comment]
https://codepen.io/anon/pen/KveYoZ?editors=0010

getFieldDecorator 装饰的表单项在生命周期里要稳定，否则会出错，使用 new key 会导致渲染出新的 getFieldDecorator。建议使用 resetFields 或者 setFieldsValue 来重置对话框里的表单项。

**Comment by benjycui** [comment]
@afc163 这个问题不好修，其实我是不建议给 Modal 设置一个不稳定的 key 的，因为已经违反 React 设计 key 的初衷了，所以这个 https://ant.design/components/modal/#Destroy-on-close 的使用场景是？

**Comment by neewbee** [comment]
照我的理解，应该是一个重置表单的hack

**Comment by 330551887** [comment]
@afc163  我以前就是用resetFields的, 但是有时候对于复杂的表单来说, resetFields 是不够用的, 例如 一些select联动等等, 所以才想到 设置新的key.
后来发现自定义组件是好用的, 把getFieldDecorator传给自定义组件, 我提的问题就不存在了, 所以我再纠结中

**Comment by afc163** [comment]
我移除了这段说明：https://github.com/ant-design/ant-design/commit/61aac68028050fdb29ed08418af908b603d78736

主要场景是对话框和外部无联动时，为避免保留之前的数据，打开一个全新的 Modal 会简单很多。不过如果和目前的 Form 联动，就会留坑。

**Comment by 330551887** [comment]
感谢各位大神, 根据大神的方法,问题已经解决
[https://codepen.io/anon/pen/BdVWWp?editors=0010](url)
{this.state.visible && <Modal visible={true} />}

**Comment by weiqi19891217** [comment]
不得不说,这得顶上去, 亏我测试了3个晚上都没有搞定 "modal重置"方法, 原来这么简单,
