### ISSUE TITLE
why don't let TreeSelect compoment check/uncheck the checkbox by clicking the label text beside it

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#7303]
### What problem does this feature solve?
It will be more convinient by selecting the item by clicking the label text. just like the most label/check box in a form.

### What does the proposed API look like?
adding a configuration property that allow to check/uncheck the checkbox by clicking the label text beside it.
since when you have treeCheckable: true, you don't have access to the onSelect method, there is no way to achieve this feature otherwise

**Comment by benjycui** [comment]
You can implement this UX with onSelect.

**Comment by violabg** [comment]
but when you have treeCheckable set to true, you don't have access to the onSelect method

**Comment by afc163** [comment]
I agreed, that is a strange UX for TreeSelect.

You can try this https://ant.design/components/tree-select-cn/#components-tree-select-demo-multiple for now.

**Comment by wiziple** [comment]
Temporary ugly solution if you only use TreeSelect with treeCheckable options.

```
:global(.ant-select-tree-node-content-wrapper) {
  cursor: default !important;
  &:hover {
    background-color: #fff !important;
  }
}


:global(.ant-select-tree-node-selected) {
  background-color: #fff !important;
}
```

**Comment by benjycui** [comment]
`rm -rf node_modules && tnpm i`

**Comment by benjycui** [comment]
When Tree is not selectable, you can click label to check checkbox.

**Comment by violabg** [comment]
I'm using the latest version of anti, but still can't select the checkbox by clicking on le label, does this need an update on the source?
I have set selectable:false on the treeSelect, could you give me an example on how to use it?

**Comment by violabg** [comment]
> When Tree is not selectable, you can click label to check checkbox.

you can set selectable to false only on Tree not on TreeSelect

**Comment by zhaohongyan** [comment]
what version support attribute treeCheckable？
