### ISSUE TITLE
modal可定义是否在visible为false时渲染子组件

### ISSUE THREAD

**Issue by vonxq** [ant-design/ant-design#7304]
### What problem does this feature solve?
modal功能基本都是结合button来使用，在编写代码过程中想简化一下，写了个高阶组件来包裹组件实现modal控制显示，如下
```javascript
const withModal = (WrappedComponent) => {
  class ButtonModal extends React.Component {
// ... 一些visible控制逻辑
    render () {
      const { visible } = this.state
      const { buttonText, title, ...extraProps } = this.props
      return (<div>
        <Button type="primary" onClick={this.showModal}>{buttonText}</Button>
        <Modal
          visible={visible}
          title={title}
          onCancel={this.handleCancel}
          onOk={this.handleOk}
        >
          <WrappedComponent {...extraProps} />
        </Modal>
      </div>)
    }
  }
  return ButtonModal
}
export default withModal
```
其中WrappedComponent只会在modal的visible第一次为true时被render，这样如果想在modal didMount时对包裹在其中的子组件进行初始化的话会报错

应用场景：在使用withModal包裹一个些表单（一些FormItem），此控件被父组件(Form)控制并使用setFieldsValue()来设置初值，但父组件在componentDidMount函数执行时子组件还不存在，所以会报错。

### What does the proposed API look like?
希望可以通过一个属性控制是否初始化子组件
```javascript
<Modal
visible='false'
initChild='true'
>
{child}
</Modal>
```

**Comment by afc163** [comment]
试试在 `WrappedComponent` 的 componentDidMount 里初始化数据？

**Comment by vonxq** [comment]
感谢回复~主要是想在Form中统一setFieldsValue，把modal组件抽离出来就是为了在写组件时尽量无状态，并且Form表单会接受其父组件的props更新表单，mapPropsToFields也会因为找不到还未render的Fields而报错

**Comment by vonxq** [comment]
mapPropsToFields实践种可以完成需求，没有报错，抱歉之前太想当然了。请问为什么mapPropsToFields能够找到未render的子组件而在componetDidMount中setFieldsValue就会报错呢

**Comment by afc163** [comment]
因为 mapPropsToFields 是在 Field 被初始化的时候调用的。而 setFieldsValue 调用时，Field 还未被初始化。

**Comment by zqgu2016** [comment]
我也碰到了类似问题，但使用mapPropsToFields时，还是会耦合在form组件内，有其它方式解决呢 @afc163

**Comment by sponia-joker** [comment]
the problem can be salved by follow code,but i know it's not grace.
`setTimeout(() => {
      form.setFieldsValue(initialValues)
      }, 0)`

**Comment by sponia-joker** [comment]
maybe mapPropsToFields is a better solution

**Comment by oopsRookie** [comment]
> 
> 
> the problem can be salved by follow code,but i know it's not grace.
> `setTimeout(() => { form.setFieldsValue(initialValues) }, 0)`

it works! 
and i guess the method of setState is an async function and the dom of Modal component's childrens are only added to this(context) when the Modal is visible, so we couldn't get it's childrens dom before Modal's rendering is complete and i think 'Modal', this component should be added a callback named onShow to monitor its rendering completion.
