### ISSUE TITLE
AutoComplete是否能增加当输入的内容不是选择下拉的内容，而是随便乱输入的一行文字判断处理啊

### ISSUE THREAD

**Issue by chendonghai** [ant-design/ant-design#7306]
### What problem does this feature solve?
当我随便乱输入一行文字，而不是选择下拉的数据时， 这时传到服务器不是正确的数据，又要单独来做一次处理相当麻烦，我希望有一个api设置为当输入的内容不是选择的内容时也就是错误内容时，他就是自动清空，Select组件中搜索用户有这个功能，随便乱输入一行文字时而不是选择下拉的内容时，他就会自动清空，但这个又有一个问题就是mode必须是multiple多选情况下，才带有这个输入选择功能，有时我的需要根本不需要多选功能的，所以也希望这个能支持一个单选输入也有这个功能，谢谢

### What does the proposed API look like?
能像Select组件中搜索用户有这个功能，随便乱输入一行文字时而不是选择下拉的内容时，他就会自动清空

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#components-select-demo-search
