### ISSUE TITLE
[Request] Additional Flex Grid props on Row/Col 

### ISSUE THREAD

**Issue by suitedjimster** [ant-design/ant-design#7309]
### What problem does this feature solve?
I'd like to request a few additional props on the flex grid system. 
I often find the need to add some css style on the Row/Col elements (or is it the recommended way?):

### What does the proposed API look like?
On Row: 
- (flex-)direction: 'row' | 'row-reverse' | 'column' | 'column-reverse' ( ... though 'column' might confuse users due to the "Row" semantic. maybe change Row -> Grid, and Col -> Grid.Item on the next version?)
- (flex-)wrap: 'wrap' | 'no-wrap' | 'wrap-reverse'

On Col:
- (flex-)grow: number. default 0.
- align(-self): auto | start | end | center | baseline | stretch. default 'auto'

**Comment by afc163** [comment]
> (flex-)direction: 'row' | 'row-reverse' | 'column' | 'column-reverse' ( ... though 'column' might confuse users due to the "Row" semantic. maybe change Row -> Grid, and Col -> Grid.Item on the next version?)

I prefer keeping the origin API.

> align(-self): auto | start | end | center | baseline | stretch. default 'auto'

There is a `align` prop already, although the value is `top` `middle` `bottom`, which means `flex-start` `center` `flex-end`.

---

> (flex-)wrap: 'wrap' | 'no-wrap' | 'wrap-reverse'
> (flex-)grow: number. default 0.

I think there are useful, could you propose a PR?

**Comment by suitedjimster** [comment]
I meant for the "direction" and "wrap" to be on the Row. and "alignSelf" and "grow" on the Col.
there's a lot of useful props for flexbox.
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by KeionneDerousselle** [comment]
Could a property on the Row be added to have a vertical gutter? Adding margin or padding to the Row
`<Row style={{ marginBottom: 8 }}></Row>`

is static and doesn't change on different screen sizes the way `gutter` does. Even something like `applyVertGutter="true"` would be helpful.

**Comment by sertac-scotty** [comment]
It would be great if we have prop for flex in column like:

```
<Row type='"flex">
    <Col flex={1}>
        Hello
    </Col>
    <Col flex={{grow:1, shrink:1, basis: '50%'}}>
        world
    </Col>
</Row
```

**Comment by zombieJ** [comment]
`flex` sounds great. We can auto fill as follow:

| shortcut | type | result |
| --------- | ---- | ----- |
| 'none' | string | 'flex: none' |
| 'auto' | string | 'flex: auto' |
| '200px' | string | 'flex: 0 0 200px' |
| 1 | number | 'flex: 1 1 auto' |
| '1 2 30px' | string | 'flex: 1 2 30px' |

**Comment by afc163** [comment]
@zombieJ Are there some usage samples?

**Comment by zombieJ** [comment]
Thanks for notice. Here is the sample:
```jsx
<Row type="flex">
  <Col flex="200px" />
  <Col flex={1} />
  <Col flex={2} />
</Row>

// '0 0 200px' | '1 1 auto' | '2 2 auto'
```

```jsx
<Row type="flex">
  <Col flex="none" />
  <Col flex="1 2 30px" />
  <Col flex="auto" />
</Row>

// 'none' | '1 2 30px' | 'auto'
```

**Comment by vemundeldegard** [comment]
Would be great to have this. I am using the Grid a lot. It should be possible to have the grid vertically, and not only horizontally.

**Comment by mikelhpdatke** [comment]
This is my solution
```
<Row
          type="flex"
          justify="space-around"
          align="middle"
          style={{
          alignItems: 'stretch'
          }}
        >
...
```

**Comment by shaodahong** [comment]
`direction` prop type optional `row` `row-reverse` `column` `column-reverse`, `row` by  default.

```jsx
<Row direction="row">
  <Col span={4}>col-4</Col>
  <Col span={4}>col-4</Col>
  <Col span={4}>col-4</Col>
  <Col span={4}>col-4</Col>
</Row>
```

**Comment by afc163** [comment]
Supported in https://ant.design/components/grid/#components-grid-demo-flex-stretch

**Comment by SinBirb** [comment]
This is not supported on Vue, right?

**Comment by blackrock33** [comment]
> `direction` prop type optional `row` `row-reverse` `column` `column-reverse`, `row` by default.
> 
> ```js
> <Row direction="row">
>   <Col span={4}>col-4</Col>
>   <Col span={4}>col-4</Col>
>   <Col span={4}>col-4</Col>
>   <Col span={4}>col-4</Col>
> </Row>
> ```

There's no `direction` prop anymore?
