### ISSUE TITLE
表单验证，type为number和regexp时功能错误

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#731]
HI，

1. 我使用表单验证时用type: number进行校验，发现即使输入是数字，也说验证不通过（例子：http://jsfiddle.net/zhaozhiming/a2186d8y/11/ ），然后我看到type有3种数字类型，分别是number, integer, float，请问这3种有什么区别？
2. 我用正则表达式做校验时也不行，写了个简单的数字正则校验但没有效果，例子：http://jsfiddle.net/zhaozhiming/a2186d8y/10/ 。
  
在官方示例上好像没看到这几种类型的例子，能否考虑加上各种type的示例？非常感谢。

**Comment by zhujun24** [comment]
看了下，在 **rules** 里加一个 **transform** 属性参见 [async-validator-transform](https://github.com/yiminghe/async-validator#transform)，值为一个转换数字的方法 **toNumber** 参见 [form-validation-example](http://react-component.github.io/form-validation/examples/form.html)，可以解决题主遇到的数字验证问题
[type 介绍戳这里](https://github.com/yiminghe/async-validator#user-content-type)

**Comment by zhaozhiming** [comment]
好的，谢谢    
1. 只写`type: number`不会校验value是number
2. `type: regexp`不用和pattern一起用

**Comment by YeZhiqiuSev** [comment]
@zhaozhiming type:regexp的正则验证怎么解决的

**Comment by internet5** [comment]
@zhujun24 还是你厉害，看了这么多回答，antd官方的人都不知道怎么搞，文档里有，又不能用，问他们，说建议自定义验证，如果不能用不知道文档里为什么要列出来，其实无非就是转换下格式的问题，可能他们懒得理这种问题吧

**Comment by internet5** [comment]
{
                                            type: 'number',
                                            message: '请填写数字',
                                            transform(value) {
                                                return Number(value);
                                            }
                                        }
最终这样就解决了，不管是整型还是浮点型

**Comment by PeterRock** [comment]
找了下相关资料transform只影响验证，不影响原始值。
所以transform和type、以及关联验证需要放在一个object中

**Comment by jabezGit** [comment]
@internet5 用了你的方法，可行。但是有小小的不足在于，当required:false 的时候，还是会提示错误。所以可以加上一个判断。 ps: transform 只影响验证，不影响原始值。
`rules: [
      {
        type:'number',
        required: false,
        message: '只支持数字类型!',
        transform: (value)=>{
            return Number(value)?Number(value):0;
        }
      },
    ],`

**Comment by chou0728** [comment]
{required: true, type: 'string', pattern: '/^\d+$/', message: 'must be a number'}

type 要改成 'string'

**Comment by NevenLiang** [comment]
[改变存储的 input value 的方法](https://github.com/ant-design/ant-design/issues/10003)

```jsx
// Due to and-design's input component, 
// it will store number as string even the type props has been set.

// The below validation methods works first.

// If the input pass the validation, 
// it will convent to number by `convertStringToNumber`.

// 将字符串转化为数值, 替换原来的 string value
convertStringToNumber = e => {
  const convertedValue = Number(e.currentTarget.value);
  if (isNaN(convertedValue)) {
    return 1;
  } else {
    return convertedValue;
  }
};

// 自定义校验函数，要求输入的是一个正整数
checkNumberString = (rule, value, callback) => {
  const number = Number(value);

  if (!Number.isInteger(number) || number < 1) {
    // 如果需要返回 error msg，就把它传给 `callback()`
    callback('The number should be an positive integer');
  } else {
    // 如果通过校验，调用无参数的 `callback()` 即可
    callback();
  }
};

// ...

render() {
  return （
    //...
    <Form.Item label='Amount of Product'>
      {
        getFieldDecorator('amountOfProduct', {
          initialValue: 123,
          rules: [
            {
              validator: this.checkNumberString
            }
          ],
          getValueFromEvent: this.convertStringToNumber
        })(
          <Input type="number" />
        )
      }
    </Form.Item>
  ）;
}
```

**Comment by yuanjianhua** [comment]
> {required: true, type: 'string', pattern: '/^\d+$/', message: 'must be a number'}
> 
> type 要改成 'string'

正则不需要加单引号
{required: true, type: 'string', pattern: /^\d+$/, message: 'must be a number'}
