### ISSUE TITLE
Why the parent node attribute TreeSelect.SHOW_ALL is not displayed ？

### ISSUE THREAD

**Issue by xflife** [ant-design/ant-design#7312]
### Version
2.10.4

### Environment
mac，chorme 60

### Reproduction link
[https://codepen.io/anon/pen/VzdObP?editors=001](https://codepen.io/anon/pen/VzdObP?editors=001)

### Steps to reproduce
Use TreeSelect,
Setting showCheckedStrategy: TreeSelect.SHOW.ALL,
select 1 child node,the parent node is not displayed input?

### What is expected?
select 1 child node,the parent node is displayed input?

### What is actually happening?
select 1 child node,the parent node is not displayed input?

---
use this code in codepen
``` javascript
const { LocaleProvider, TreeSelect, locales } = antd;

const treeData = [
  {label: '1-1', value: '1-1', children: []},
  {label: '1-2', value: '1-2', children: []},
  {label: '1-3', value: '1-3', children: [
    {label: '2-1', value: '2-1', children: []},
    {label: '2-2', value: '2-2', children: []},
  ]},
];

ReactDOM.render(
  <LocaleProvider locale={locales.zh_CN}>
    <TreeSelect treeData={treeData}
                placeholder="请选择"
                showCheckedStrategy={TreeSelect.SHOW_ALL}
                style={{ width: 200 }}
                dropdownMenuStyle={{ maxHeight: 400, overflow: 'auto' }}
                multiple
                treeDefaultExpandAll
                dropdownMatchSelectWidth
                treeCheckable/>
  </LocaleProvider>,
  mountNode
);
```

**Comment by afc163** [comment]
The `TreeSelect.SHOW_ALL` means that show all checked item in input box, the parent item is half-checked when one of it's child is checked, so it won't be shown in input box.

**Comment by xflife** [comment]
can i make the  parent item is half-checked shown in input box ? or in **function onchange**get the half-checked parent item value?

**Comment by afc163** [comment]
https://codepen.io/anon/pen/VzdObP?editors=001

This demo throw error when check items now.

```
TypeError: labs is null
```

**Comment by afc163** [comment]
You can try `treeCheckStrictly` and control the tree node state by youself, after I fixed the undefined bug in https://github.com/react-component/tree-select/pull/69

**Comment by yeyuguo** [comment]
这个问题是如何解决的？ @xflife  我目前也是遇到这个问题
