### ISSUE TITLE
Make an Upload.Dragger to select a directory

### ISSUE THREAD

**Issue by adrianplavka** [ant-design/ant-design#7315]
### What problem does this feature solve?
While drag & dropping, user should be able to select a directory to upload. Currently, it is unachievable with the current API to make Upload to work with directories.

### What does the proposed API look like?
Simply, make another attribute to the Upload.Dragger, such as <Upload.Dragger directory={true} {...props} />. This would allow the dragger to be able to select a directory.

**Comment by benjycui** [comment]
It's just a wrapper of native `<input type="file" />`

**Comment by afc163** [comment]
https://caniuse.com/#feat=input-file-directory

Welcome to propose a PR to https://github.com/react-component/upload/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/fd96967c872600b79bb608e9ddf9f8c38814a704
