### ISSUE TITLE
下拉树选择 是否能够增加个字段控制是否过滤value唯一

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#7323]
### Version
2.8.3

### Environment
chrome

### Reproduction link
[https://codepen.io/anon/pen/JyBBep?editors=0010](https://codepen.io/anon/pen/JyBBep?editors=0010)

### Steps to reproduce
添加个树数据，一个子节点拥有多个父节点

### What is expected?
选择同时拥有多父节点的子节点能够同时勾上，并且去掉的时候也能够同时去掉勾选

### What is actually happening?
去掉勾选会报相同的key值

---
业务上有个下拉选择公司人员树的，有的人挂在多个部门下面，选择的时候实际上还是一个人，value必须一样才能够同时选中并且只显示一条数据，但是这样就出现了以上报错

**Comment by afc163** [comment]
很奇怪的需求，和 Tree 和 TreeSelect 的设计相违背。建议自定义不同的 value 并在选择后自行过滤数据。

**Comment by aw6658913** [comment]
我一开始也是这么做的，手动拼接上value，但是这样的话就变成了代表的是不同的数据但实际上是一个数据，只需要显示一次就行了~~一般来说过滤掉相同key跟value是没错，避免出现重复value，但是某些特殊场景就是要求能够有重复的value，所以我才提议说能否增加个控制字段，默认校验，需要的话自己控制下

**Comment by afc163** [comment]
抱歉，可能你需要自己想办法了~

**Comment by aw6658913** [comment]
我发现tree的key是可以相同的，同样有多个父节点的数据下，使用tree勾选不会报错
https://codepen.io/anon/pen/VzBEqb?editors=001
