### ISSUE TITLE
服务端与客户端渲染Table表头不一致

### ISSUE THREAD

**Issue by kuangshu** [ant-design/ant-design#7324]
### Version
2.12.7

### Environment
WIN10，chrome60均64位

### Reproduction link
[http://cs.udianhuo.com:3000/test](http://cs.udianhuo.com:3000/test)

### Steps to reproduce
为Table设置```scroll={{ y: 530 }}```会为表头添加一个```ant-table-header```的包裹，此时服务器和客户端渲染会不一样。

### What is expected?
服务端与客户端渲染结果一致

### What is actually happening?
服务器上渲染```ant-table-header```的包裹div并没有style属性，但客户端渲染会不一样。
会出现```style="margin-bottom:-17px;padding-bottom:0px;"```，造成服务端和客户端渲染不一致。
从而出现警告：
![Alt text](http://cs.udianhuo.com/tmp/%E5%9B%BE%E7%89%8720170825123634.png "警告")
![Alt text](http://cs.udianhuo.com/tmp/图片20170825123901.png "不一致样式属性")

---
只有设置scroll-y的情况下才会有，推测应该是·ant-table-header·的包裹的问题

**Comment by afc163** [comment]
Trace https://github.com/react-component/steps/issues/38

**Comment by afc163** [comment]
![](https://gw.alipayobjects.com/zos/rmsportal/bauFtxgnExBIMANHWVUR.png)

Cannot see the error message.

**Comment by afc163** [comment]
Can you provide a reproducible repo?

**Comment by afc163** [comment]
？

**Comment by kuangshu** [comment]
感觉没有太大的影响就先关了，手上事情还多先忙过了再看看

**Comment by Essionwsk** [comment]
这个问题也严重的困扰到了我
