### ISSUE TITLE
I think the background color setting is superfluous in the Step component

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#7325]
### What problem does this feature solve?
The Step's container do not necessarily have a white background,Otherwise like this:
https://codepen.io/anon/pen/ayjQyW?&editors=001#

It  becomes very bad.
![step](https://user-images.githubusercontent.com/7866330/29703549-8f6306c8-89a8-11e7-98a1-52eb0a735d54.png)

So,I think the background color setting is superfluous.

### What does the proposed API look like?
removed the background setting about `.ant-steps .ant-steps-title` and `.ant-steps .ant-steps-head`

**Comment by afc163** [comment]
It is a bad implementation, you can try http://react-component.github.io/steps/examples/background.html as workaround for now. We will import it in future as soon as we have time.

**Comment by buxuku** [comment]
THX for http://react-component.github.io/steps/examples/background.html.

That's Great!!!

**Comment by afc163** [comment]
Trace https://github.com/react-component/steps/issues/38
