### ISSUE TITLE
In pagination, is there a goto button that can quickly jump to certain page?

### ISSUE THREAD

**Issue by hmt2014** [ant-design/ant-design#7328]
### What problem does this feature solve?
when there are many pages, users can input certain page to jump to it. I need a goto button

### What does the proposed API look like?
I need a goto button in pagination

**Comment by afc163** [comment]
Won't do it. You can add Button after Pagination like: https://github.com/ant-design/ant-design/issues/6970#issuecomment-318039942

**Comment by hmt2014** [comment]
Thank you very much

**Comment by hmt2014** [comment]
How to combine with table, because there are lots of tables and pagination in webpages needed to be changed. @afc163

**Comment by afc163** [comment]
There is also a undocumented prop `showQuickJumper.goButton`:http://react-component.github.io/pagination/examples/jumperWithGoButton.html

Will be released with rc-pagination@1.11.0 in this week.

**Comment by kangkang1995** [comment]
> 还有一个没有文档的道具`showQuickJumper.goButton`：[http](http://react-component.github.io/pagination/examples/jumperWithGoButton.html)：[//react-component.github.io/pagination/examples/jumperWithGoButton.html](http://react-component.github.io/pagination/examples/jumperWithGoButton.html)
> 
> 本周将发布rc-pagination@1.11.0。

你好，我试了，可以实现，但是文档是boolean类型，所以TS会报错

**Comment by afc163** [comment]
@kangkang1995 Could you send us a PR to fix ts types?

**Comment by kangkang1995** [comment]
@afc163 (⊙o⊙)…PR是什么吗？是让我重新另开一个问题提问是吗

**Comment by afc163** [comment]
来个 Pull Request https://github.com/ant-design/ant-design/pulls

**Comment by kangkang1995** [comment]
@afc163 我没弄过，感觉好像弄错了，要不我把刚才开的那个pr，删掉(⊙o⊙)…，要不你帮忙开一个

**Comment by afc163** [comment]
@kangkang1995 学习一下，第一次总是生疏的~

https://ant.design/docs/react/contributing-cn
https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BA-Pull-Request
https://www.zhihu.com/question/37093917
https://www.jianshu.com/p/d7e48ef76eae
