### ISSUE TITLE
InputNumber 输入超出限制范围的值时发生错误

### ISSUE THREAD

**Issue by lsqaisen** [ant-design/ant-design#7334]
### Version
2.12.7

### Environment
win10, chrome Version 60.0.3112.101 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
1. InputNumber 设置范围，如：min=1,max=10
2. 输入超过10的数字会重置为10，但当输入值不是数字时，如：103aa，重置的值为103而不是10

### What is expected?
但当输入值不是数字时，如：103aa，重置的值为103而不是10

### What is actually happening?
重置的值因为10

**Comment by lsqaisen** [comment]
与Form一起使用才会发生

**Comment by lsqaisen** [comment]
版本暂时无法升级的，也可以使用parser字段解决
` 
<InputNumber
                            placeholder="端口"
                            min={1}
                            max={65535}
                            step={1}
                            parser={value => {
                                if (parseInt(value) > 65535) {
                                    return 65535;
                                } else if (parseInt(value) < 1) {
                                    return 1;
                                }
                                return value;
                            }} />`

**Comment by StephenWong1991** [comment]
> 版本暂时无法升级的，也可以使用parser字段解决
> ` <InputNumber placeholder="端口" min={1} max={65535} step={1} parser={value => { if (parseInt(value) > 65535) { return 65535; } else if (parseInt(value) < 1) { return 1; } return value; }} />`

you are right
