### ISSUE TITLE
Build issue when using Breadcrumb.Item / Menu.Item in --release mode (ant-design/react-starter-kit)

### ISSUE THREAD

**Issue by yongching** [ant-design/ant-design#7339]
### Version
2.12.7

### Environment
Chrome Version 60.0.3112.101

### Reproduction link
[https://github.com/yongching/react-starter-kit](https://github.com/yongching/react-starter-kit)

### Steps to reproduce
https://github.com/yongching/react-starter-kit

'yarn start -- --release' and you should encounter the error.

### What is expected?
Should be able to use Breadcrumb.Item / Menu.Item directly in return() without declaring a const for it.

Example: 
import { Breadcrumb, Icon } from 'antd';
const BreadcrumbItem = Breadcrumb.Item

### What is actually happening?
Getting error message:

proxyConsole.js:56 ReferenceError: Breadcrumb is not defined
    at Object../src/routes/home/index.js (Home.js:35)
    at p (bootstrap f1414df40d2c2c29006e:695)
    at o (bootstrap f1414df40d2c2c29006e:116)
    at <anonymous>

---
removing this line would solve the issue:
https://github.com/ant-design/react-starter-kit/blob/master/tools/webpack.config.js#L327

is there any better solution/workaround for this?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7131
