### ISSUE TITLE
Please help me about antd's popover and steps components,both them can't use together?

### ISSUE THREAD

**Issue by jiayanzhao** [ant-design/ant-design#7343]
### Version
2.12.7

### Environment
"antd": "^2.12.1","react": "^15.6.1"

### Reproduction link
[https://design.alipay.com/develop/web/components/popover/](https://design.alipay.com/develop/web/components/popover/)

### Steps to reproduce
<Popover placement="left" content={content} trigger="hover">
                    <Step title="Finished" description="Populate Context" />
                </Popover>

### What is expected?
when I onhover at a step,there should be a popover to show a detail information.

### What is actually happening?
Uncaught TypeError: Cannot read property 'background' of undefined
    at Step.render (Step.js:126)
    at ReactCompositeComponent.js:795

and the line 126 is :style: { background: wrapperStyle.background || wrapperStyle.backgroundColor }

the wrapperStyle: var wrapperStyle = _props.wrapperStyle;

---
If somebody can resolve the issue,pls help soon, I am newer and the project is worry.thx.

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by jiayanzhao** [comment]
Sorry,I never use the codepen before and I don't konw "You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size."
how to dealwith this.

**Comment by afc163** [comment]
Just ignore the warning.

**Comment by jiayanzhao** [comment]
https://codepen.io/yanzhaoj/pen/gxdBGg?editors=001
Is it? I just want a result that when the mouse on the step, there will be a popover to show some details.

**Comment by afc163** [comment]
`Step` is not composable now, you can wrapper the title and description vis `Popover` separately now: https://codepen.io/anon/pen/OjoBvj?editors=0010

**Comment by jiayanzhao** [comment]
Thank you! Are you the developer of the antd?
