### ISSUE TITLE
404 link in 2.12.8 release announcement for "Use in create-react-app"

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#7348]
### Version
2.12.8

### Environment
any

### Reproduction link
[https://github.com/ant-design/ant-design/releases](https://github.com/ant-design/ant-design/releases)

### Steps to reproduce
see https://github.com/ant-design/ant-design/releases, click on "Use in create-react-app"

### What is expected?
https://github.com/ant-design/ant-design/blob/2.12.8/docs/react/use-with-create-react-app should display usage for create-react-app

### What is actually happening?
404 page not found

**Comment by afc163** [comment]
Sorry about that, it is fixed.
