### ISSUE TITLE
antd   antd-mobile使用babel-plugin-import无法按需加载

### ISSUE THREAD

**Issue by hansinhu** [ant-design/ant-design#7349]
### What problem does this feature solve?
antd   antd-mobile使用babel-plugin-import无法按需加载

### What does the proposed API look like?
["import", {
    "libraryName": "antd-mobile"
  },{
    "libraryName": "antd",
    "style": "css"}
  ]

**Comment by afc163** [comment]
没有提供任何有效信息。

**Comment by afc163** [comment]
Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by WangYang-Rex** [comment]
have you figure out? I have the same problem，how？
