### ISSUE TITLE
Form forms interact with each other

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#7351]
### Version
2.12.7

### Environment
react 15.4.0

### Reproduction link
[https://github.com/Kunoky/dva-form.git](https://github.com/Kunoky/dva-form.git)

### Steps to reproduce
分别点击Form表单的两个label

### What is expected?
两个Form表单之间互相独立，互不影响。

### What is actually happening?
点击第二个label却只对第一个元素起作用

---
他们的getFieldDecorator 的id相同，一个页面的search表单和create表单之间有一个相同的值

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by Kunoky** [comment]
https://codepen.io/anon/pen/VzEvgQ?editors=0010

**Comment by Kunoky** [comment]
What are you saying？
