### ISSUE TITLE
 FormItem hasFeedback true  RangePicker FormItem status icon = 'success'

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design#7352]
### Version
2.12.8

### Environment
mac chrome

### Reproduction link
[https://codepen.io/hnsylitao/pen/gxBbyp?editors=0010](https://codepen.io/hnsylitao/pen/gxBbyp?editors=0010)

### Steps to reproduce
https://codepen.io/hnsylitao/pen/gxBbyp?editors=0010

### What is expected?
RangePicker FormItem status icon = null

### What is actually happening?
RangePicker FormItem status icon = 'success'

**Comment by benjycui** [comment]
@afc163 楼顶的 CodePen 点 Submit 后：

![image](https://user-images.githubusercontent.com/3580607/30014957-4c40e1ae-9181-11e7-86c0-2e81c0134bb3.png)

和之前这个 https://github.com/ant-design/ant-design/issues/4783 冲突了，其实 #4783 才是特殊场景吧，毕竟默认 DatePicker 之类的宽度并不是 100%

**Comment by benjycui** [comment]
@hnsylitao 然后你的问题看不懂，麻烦提供详细重现步骤。

**Comment by benjycui** [comment]
@hnsylitao 懂了，你的问题来自这里 https://github.com/ant-design/ant-design/blob/c651c7a04faeb6186beadc37a2638512352475b1/components/form/FormItem.tsx#L155-L157

**Comment by hnsylitao** [comment]
@benjycui 谢谢，所以我在初始默认的时候给null 就ok了
