### ISSUE TITLE
<NumberInput> need the callback function when the up and down button clicked

### ISSUE THREAD

**Issue by blankzust** [ant-design/ant-design#7354]
### What problem does this feature solve?
I need to make the <input/> readOnly.But I want to click the up and down button to change the input's value 

### What does the proposed API look like?
<InputNumber onUp={() => {}} onDown={()=>{}}/>

**Comment by blankzust** [comment]
I find a way to solve it.I can add 'upHandler' and 'downHandler' to replace the up and down button.I can set the click event by myself as follows.
```<code>
<InputNumber upHandler={
<span onClick={() => { // to set the input's value bigger }}>
    up
</span>
}/>
</code>```

**Comment by afc163** [comment]
> I need to make the readOnly.But I want to click the up and down button to change the input's value

That is weird, I don't think we would support it.

**Comment by blankzust** [comment]
Maybe you need to add 'readOnly' just like 'disabled'.

**Comment by blankzust** [comment]
And the NumberInput offer us to change the value through buttons when readOnly setted disabled

**Comment by blankzust** [comment]
Any I solved my problem using a easy way.Thx
