### ISSUE TITLE
Transfer組件有無「一對多」的支援？

### ISSUE THREAD

**Issue by roth1002** [ant-design/ant-design#7356]
### What problem does this feature solve?
I happen to have a one-to-many transfer request

"Single Source Multiple Targets"

If there is no support that there is no way to achieve this goal?

### What does the proposed API look like?
```
<Transfer
   ...... 
   multiTarget={true}  // default false
/>
```

**Comment by nikogu** [comment]
i think there is no `multiTarget` like what you say, but we can discuss it's necessary. 

by the way, you can use `Tab` + `Transfer` to replace it.

**Comment by afc163** [comment]
Won't support it. You can follow @nikogu's way.
