### ISSUE TITLE
所有表单校验报错了

### ISSUE THREAD

**Issue by nicelj** [ant-design/ant-design#7359]
### Version
2.12.8

### Environment
chrome59 windows7

### Reproduction link
[localhost:3100](localhost:3100)

### Steps to reproduce
之前都是正常的代码出错了

### What is expected?
正常

### What is actually happening?
报错文件是在createBaseForm.js 403行，cannot read property 'push' of undefined

---
没有修改，之前都是正常的代码

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by nicelj** [comment]
发现问题了，我去rc-form里面找代码，发现是我的lodash plugin用法有问题。。

**Comment by shinygang** [comment]
@nicewahson 你最后是移除lodash-webpack-plugin这个了吗？

**Comment by xiaop0817** [comment]
`new LodashModuleReplacementPlugin({paths: true})`
