### ISSUE TITLE
I already installed antd 2.12.8，should I install rc-pagination 1.11.0？ When I deploy my project, It has some errors

### ISSUE THREAD

**Issue by hmt2014** [ant-design/ant-design#7362]
### What problem does this feature solve?
I don‘t know whether should  I install rc-pagination, when i deploy my project, there are some errors that alarms rc-calendar is not installed. I haven't use it

### What does the proposed API look like?
Hope you can help me with my problem

**Comment by afc163** [comment]
I don't understand what your problem. But you don't need to install rc-pagination.

**Comment by hmt2014** [comment]
![1503912533217](https://user-images.githubusercontent.com/9130751/29767856-9ab208a6-8c16-11e7-81e3-362f7440dd76.jpg)

**Comment by hmt2014** [comment]
![1503912913379](https://user-images.githubusercontent.com/9130751/29768112-9c0b6944-8c17-11e7-9f79-c91439b1531b.png)

**Comment by afc163** [comment]
Try [cnpm](https://github.com/cnpm/cnpm) if your network is bad.

**Comment by hmt2014** [comment]
OK thank you～
