### ISSUE TITLE
在form表单中使用Upload

### ISSUE THREAD

**Issue by Zuckjet** [ant-design/ant-design#7364]
### Version
2.12.8

### Environment
ubuntu16.4  chrome最新版本

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
点击编辑按钮，会弹出一个Modal.在该Modal中，有一个表单，表单中有一项是Upload标签组成，我给该项赋一个初始值，希望弹窗出现的时候，在Upload标签上就能显示我给定url的图片，代码如下：
```
{getFieldDecorator('img', {
                valuePropName: 'fileList',
                getValueFromEvent: this.normFile,
                initialValue:[{
                uid: -1,
                name: 'xxx.png',
                status: 'done',
                url: "http://dev.hxcdn.cn/02c746baf82cb0e9ffebd272ad44c352.jpg",
                }]
              })(
                <div>
                  <Upload {...props}>
                    <div>
                      <Icon type="plus" />
                      <div className="ant-upload-text">Upload</div>
                    </div>
                  </Upload>
                </div>
                )}
```

### What is expected?
我希望对话框出来的时候，在upload中能显示我给定url的图片，也就是说给该项一个初始值

### What is actually happening?
实际结果是图片没有显示出来

**Comment by yesmeck** [comment]
Set `valuePropName` to `defaultFileList` or `fileList`.

**Comment by Zuckjet** [comment]
i found it was my mistake,and I am terribly sorry about wasting your time.i will close the issue right away.
