### ISSUE TITLE
Input Placeholder 字体模糊

### ISSUE THREAD

**Issue by Cacivy** [ant-design/ant-design#7365]
### Version
2.12.8

### Environment
windows10 chrome60

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
f12手动把placeholder改成中文模糊更明显

### What is expected?
测试2.12.0版本正常

### What is actually happening?
2.12.8版本模糊

**Comment by nikogu** [comment]
@Cacivy i think you can take a look at the `font-family`, change some `font-family` to debug.

**Comment by Cacivy** [comment]
@nikogu 
I try to change `font-family`，but nothing changed.
And I don't change any code, just `npm i antd@2.12.0`, It's screenshot
![tim 20170829093741](https://user-images.githubusercontent.com/8381177/29800665-fcf3a7fe-8c9d-11e7-9f43-f27261b6ae97.png)
![tim 20170829093917](https://user-images.githubusercontent.com/8381177/29800666-fcf79b0c-8c9d-11e7-9d13-f53ec4ba6245.png)

**Comment by ddcat1115** [comment]
Does InputNumber has this problem?

**Comment by benjycui** [comment]
@Cacivy could you re-produce this issue with others' computer?
