### ISSUE TITLE
tree 的disableCheckbox属性在不同版本上的问题

### ISSUE THREAD

**Issue by HengCC** [ant-design/ant-design#7366]
### Version
2.12.8

### Environment
OSX10.12.6, 

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
1. 参考官网的例子 https://ant.design/components/tree-cn/, 设置某个父节点下面的某个节点的disableCheckbox属性为true.

2. 设置tree的checkedKeys和onCheck事件. 

3. 选中或者取消选中父节点, 被设置了disableCheckbox的节点不会随着父节点被选中或者取消选中.

### What is expected?
我测试过2个版本. 2.10.1, 2.12.2, 这2个版本在我本地是正常的. 并且是我期望的结果:

我期望的结果是 当我设置了某个节点的disableCheckbox属性为true的时候, 它的选中状态依然受父节点的选中状态控制, 当父节点选中的时候该节点也被选中, 当父节点取消选中的时候,该节点取消选中.

### What is actually happening?
实际的结果在版本 2.12.8 上测试的, 结果是 当一个节点设置了disableCheckbox为true的时候, 该节点的选中状态不在受父节点控制.

---
业务场景:  子节点不允许被独立选中. 当选中了父节点的时候自然的拥有子节点的所有状态.

**Comment by afc163** [comment]
Duplicate of #7353

**Comment by benjycui** [comment]
> 选中或者取消选中父节点, 被设置了disableCheckbox的节点不会随着父节点被选中或者取消选中.

@afc163 https://github.com/ant-design/ant-design/issues/6891 https://github.com/react-component/tree/issues/99

个人认为当前的行为更加容易理解，如果 @HengCC 真的有哪种需求，可以用受控模式达到。

**Comment by benjycui** [comment]
Close now, just use controlled mode if you need.
