### ISSUE TITLE
Autocomplete display the options when they are changed programmatically and the component doesn't have the focus 

### ISSUE THREAD

**Issue by fcaballero** [ant-design/ant-design#7367]
### Version
2.12.8

### Environment
windows 10, Chrome 60.0.3112.101, react 15.16.1

### Reproduction link
[https://codepen.io/anon/pen/vJVxLz?&editors=001](https://codepen.io/anon/pen/vJVxLz?&editors=001)

### Steps to reproduce
* Open this [codepen](https://codepen.io/anon/pen/vJVxLz?&editors=001)
* Type `sd` in the autocomplete component in order to not match with any of the options
* Click outside of the input in order to lose the focus from the component (not yet in the button)
* Click in the button with the label `Reset options`

### What is expected?
* The options should not be displayed as the focus is not in the autocomplete component

### What is actually happening?
* The options are displayed even when the focus is not in the autocomplete component and the text in the input doesn't match with any of the options

**Comment by yutingzhao1991** [comment]
Not a bug. You should pass the right options ( options should filter by value ) as AutoComplete children when you reset options. 

https://codepen.io/yutingzhao1991/pen/PEzqep
