### ISSUE TITLE
支持 Checkbox 样式可自定义

### ISSUE THREAD

**Issue by int64ago** [ant-design/ant-design#7368]
### What problem does this feature solve?
目前 Checkbox 的宽高是[写死的](https://github.com/ant-design/ant-design/blob/master/components/checkbox/style/mixin.less#L45)，当自定主题调整 Button 等宽高后，Checkbox 大小会显得很不协调，希望支持宽高可配置（当然这涉及到勾选后样式兼容）

### What does the proposed API look like?
```
@checkbox-width
@checkbox-height
```

**Comment by afc163** [comment]
Added `@checkbox-size`.
