### ISSUE TITLE
Table 能指定滚动范围吗

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design#7371]
### What problem does this feature solve?
实现两种相同类型产品的对比，比如看两种型号的电脑参数，对比一下。
实现任一个Table滚动，对应的Table也同时滚动

### What does the proposed API look like?
添加 onScroll 监听，同时增加 scrollTo 来指定滚动范围

**Comment by afc163** [comment]
Try do this by dom manipulation: https://github.com/ant-design/ant-design/issues/6570#issuecomment-310265840
