### ISSUE TITLE
Tabs组件 activeKey 只能传递字符型数值BUG

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design#7373]
### Version
2.12.8

### Environment
mac chrome

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
用例子直接代码如下：
···
const { Tabs } = antd;
const TabPane = Tabs.TabPane;

function callback(key) {
  console.log(key);
}

ReactDOM.render(
  <Tabs onChange={callback} type="card" activeKey={"1"}>
  ···
, mountNode);
···

### What is expected?
activeKey 是数值类型

### What is actually happening?
只支持字符类型

**Comment by afc163** [comment]
因为目前 React 的 key 只能是 string 类型，详见：https://facebook.github.io/react/docs/lists-and-keys.html#basic-list-component 建议做下类型转换。
