### ISSUE TITLE
when first item is disabled，the table checkbox in the header row can not correctly select all

### ISSUE THREAD

**Issue by ignous** [ant-design/ant-design#7375]
### Version
2.12.8

### Environment
all browser

### Reproduction link
[https://codepen.io/ignous/pen/Jymxvq/](https://codepen.io/ignous/pen/Jymxvq/)

### Steps to reproduce
1. set first item disabled
2. click the checkbox in the header row

### What is expected?
disabled items not selected;
enabled items is selected;

### What is actually happening?
first item is selected; last item is not selected;

**Comment by afc163** [comment]
Your data is not contain rowKey: https://ant.design/components/table/#Note
