### ISSUE TITLE
how to transfer custom props into antd form

### ISSUE THREAD

**Issue by ansonxing168** [ant-design/ant-design#7376]
### Version
2.12.8

### Environment
react 15.6.1, typescript 2.4.2

### Reproduction link
[https://codepen.io/ansonxing168/pen/oeamKj?editors=001](https://codepen.io/ansonxing168/pen/oeamKj?editors=001)

### Steps to reproduce
Fist of all, my project is using typescript. I am writing a common component that contain an antd Form, this component  will receive several props, such as an array for dynamic building fields. The problem is when I use Form.create() to wrap this component, a error occurs in its parent component. But I've tried it in es6, everything is fine.

Here is my code below:

```

import * as React from 'react';
import { Form } from 'antd';
const FormItem = Form.Item;

interface EditorProps {
  save: any;
  form: any;
}

class Editor extends React.Component<EditorProps> {
  render() {
    return (
      <Form onSubmit={this.props.save}>
           。。。。
      </Form>
    )
  }
}

const EditorWrapper = Form.create()(Editor)

ReactDOM.render(
  <div>
    <EditorWrapper save={saveFn}/>
  </div>
, app);

```

### What is expected?
pass the props correctly and no error.

### What is actually happening?
error:
```
    TS2339: Property 'save' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<{}, ComponentState>> & Readonly<{ childr...'.
```

---
我用Form封装好成公共组件，其他组件调用该组件需要传某些参数，但不知道是否由于typescript声明里面没有该自定义的属性，所以无法传递？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/7245/files

https://github.com/ant-design/ant-design/pull/7330/files
