### ISSUE TITLE
table datasource no data,table still render one tr!

### ISSUE THREAD

**Issue by mgoann** [ant-design/ant-design#7379]
### Version
2.12.8

### Environment
win7  chrome 60.0.3112.113（正式版本） （32 位）

### Reproduction link
[http://tdfz.apiaster.xyz:28082](http://tdfz.apiaster.xyz:28082)

https://codepen.io/anon/pen/prxmWp?editors=001

### Steps to reproduce
admin/1登录系统，监督报表-->查询监督报表 ,点击table中第一条数据的详情，展开后再超温情况统计表中有一个表格，这个表格是没有数据的，但是还是渲染了一行数据出来

### What is expected?
不显示任何数据

### What is actually happening?
展示了一行数据

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by mgoann** [comment]
see here!
https://codepen.io/anon/pen/prxmWp?editors=001

**Comment by cathayandy** [comment]
@afc163 I met the same problem. This is because you add a placeholder when dataSource is an empty list.

**Comment by whazyk** [comment]
i have exactly the same problem.   Please fix it!

**Comment by afc163** [comment]
Working on it.

**Comment by afc163** [comment]
Try reinstall node_modules.

**Comment by sduworm** [comment]
Reinstall node_modules seems not work. Now rc-table version 5.6.4 , but bug also exist. Always on codepen.io.

**Comment by afc163** [comment]
codepen will not been fixed until next release cause it use the dist file.

**Comment by sduworm** [comment]
Oh,it works ok, until I add a " fixed: 'left' " to one element in the array of <Table > 'columns' prop.

**Comment by internet5** [comment]
目前rc-table 5.6.7依旧存在类似的问题，如果columns存在fixed属性，columns里return的元素只有一级的时候才能隐藏，直接return “文字” 或者return <div><span>123</span><span>321</span</div>的时候，仍然隐藏不了，看代码发现样式
.ant-table-row-empty-placeholder >td > * {
  color: transparent !important;
}
在项目中立即修复这个问题可直接覆盖该样式
:global .ant-table-row-empty-placeholder * {
  color: transparent !important;
}
就OK了
