### ISSUE TITLE
timepicker设置value值，到底传什么类型的参数？

### ISSUE THREAD

**Issue by luodaxu** [ant-design/ant-design#738]
ps: version 0.10.4, 传string "12:12:12"报错需要object类型，传递Date类型也错
最好给个例子
const Test = React.createClass({
  getInitialState() {
    return {
      value: null,
    };
  },
  onChange(time) {
    time = time && time.toLocaleTimeString('zh-CN', {
      hour12: false
    });
    console.log(time);
    this.setState({ time });
  },
  render() {
    return 
<TimePicker value={this.state.value}
 onChange={this.onChange} />;
  }
});
这个例子感觉没有什么意义

**Comment by afc163** [comment]
0.10.4 没有 value 。https://github.com/ant-design/ant-design/issues/578
