### ISSUE TITLE
对话框可拖动移动位置

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#7382]
### What problem does this feature solve?
对话框挡住了页面信息，需要对话框能够拖动。

### What does the proposed API look like?
NA

**Comment by afc163** [comment]
Duplicate of #3012

**Comment by jszjlfy** [comment]
对于7.0.0以后版本很好处理，利用angular官方cdk中的drag组件。记事本分别打开node_modules\ng-zorro-antd\fesm2015和node_modules\ng-zorro-antd\fesm5下的ng-zorro-antd.js文件：
1.查找 ”NzModalModule“，在imports中添加”DragDropModule“
2.查找”ant-modal-wrap“（共找到2个地方，只需修改第2处），在含有”ant-modal-wrap“的<div>标签加上” cdkDrag“。加好后像这样<div\n    (click)=\"onClickMask($event)\"\n    class=\"ant-modal-wrap {{ nzWrapClassName }}\"\n    [style.zIndex]=\"nzZIndex\"\n    [style.display]=\"hidden ? 'none' : ''\"\n    tabindex=\"-1\"\n    role=\"dialog\"\n  cdkDrag >\n
保存后重新运行你的程序就可以了。

当然，你也可直接该原代码文件：
1.  在 nz-modal.module.ts导入DragDropModule
2. 修改nz-modal.component.html，在<div
    (click)="onClickMask($event)"
    class="ant-modal-wrap {{ nzWrapClassName }}"
    [style.zIndex]="nzZIndex"
    [style.display]="hidden ? 'none' : ''"
    tabindex="-1"
    role="dialog" ckdDrag>
   中加上cdkDrag 。编译后发布
