### ISSUE TITLE
version0.10.4: 表单验证能否使用Timepicker?

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#739]
HI
我在表单验证的[官方示例](http://010x.ant.design/components/validation/)上没看到关于Timepicker的例子.
然后我在[问题区](https://github.com/ant-design/ant-design/issues/738)里看到有人说0.10.4的Timepicker不支持value.
请问是否就意味着表单验证不能用Timepicker了？
望指点，谢谢

**Comment by afc163** [comment]
0.11.x  的 TimePicker 支持 value。
