### ISSUE TITLE
Table can't use `dataIndex` as `key` automatically when grouping columns

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#7392]
### Version
2.12.8

### Environment
Windows 10.0.15063 & Chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/hansnow/pen/gxQKXa?editors=001](https://codepen.io/hansnow/pen/gxQKXa?editors=001)

### Steps to reproduce
1. click the link above
2. open Chrome dev tools
3. switch to `Console` tab

### What is expected?
No warnings.

### What is actually happening?
![image](https://user-images.githubusercontent.com/4365899/29858626-d855d3ba-8d90-11e7-8a1d-3bb87c0a2efb.png)

---
According to the [document](https://ant.design/components/table/#Column), `key` props could be ignored when unique `dataIndex` was provided.

**Comment by yesmeck** [comment]
Reinstall node_modules.
