### ISSUE TITLE
how to set select showSearch props

### ISSUE THREAD

**Issue by blackholll** [ant-design/ant-design#7393]
### What problem does this feature solve?
看文档上说 开启showsearch后， select组件可以根据option里面的value属性的内容来筛选。 我的场景如下:
`<Option value="1">lucy</Option><Option value="2">jack</Option>`
。后端会直接存储id值 而不是jack。 如何自定义筛选属性？文档里面只是说默认value。 并未给出如何自定义

### What does the proposed API look like?
无特殊要求

**Comment by blackholll** [comment]
被转义了，我的用法是： <Option value="1">lucy</Option><Option value="2">jack</Option> 因为为后端存储的是id值。 所以value会设置为id。  根据id过滤太不直观了。 是否可以设置如 <Option value="1" seacrh_name="lucy">lucy</Option><Option value="2" seacrh_name="jack">jack</Option> 然后根据seacrh_name来过滤

**Comment by afc163** [comment]
optionFilterProp

**Comment by xiaofengqqcom123** [comment]
optionFilterProp 试了下不行啊？https://codesandbox.io/s/antd-reproduction-template-bz7t9?fontsize=14&hidenavigation=1&theme=dark
