### ISSUE TITLE
TreeSelect Search for multiple checkable select

### ISSUE THREAD

**Issue by xiamidong** [ant-design/ant-design#7398]
### What problem does this feature solve?
https://ant.design/components/tree-select/#components-tree-select-demo-checkable
在有checkbox的下拉树形选择框中, 我在input框中输入1, 然后筛选中对应的选型, 选中之后, 让输入框中的只有选中的值, 没有搜索的值

### What does the proposed API look like?
在有checkbox的下拉树形选择框中, 我在input框中输入1, 然后筛选中对应的选型, 选中之后, 让输入框中的只有选中的值, 没有搜索的值

**Comment by ddcat1115** [comment]
`treeCheckable`为 true 时默认为多选，选中一个 TreeNode 并不代表选择过程已经完成，此时还需继续依靠搜索的值来过滤选项，不应该被删除。

先关了，有进一步疑问可以再reopen~

**Comment by sky86857322** [comment]
遇到同样的问题，请问楼主解决了吗？可以分享代码？
