### ISSUE TITLE
有没有基于AntDesign风格的Axure RP的rplib库交互设计库文件？

### ISSUE THREAD

**Issue by CherishGuo** [ant-design/ant-design#740]
有没有基于AntDesign风格的Axure RP的rplib库交互设计库文件？
这样方便用户在使用该组件前，能够快速的生成风格类似的交互稿

**Comment by afc163** [comment]
http://ant.design/spec/tools

**Comment by CherishGuo** [comment]
https://github.com/ant-design/ant-design/files/69428/Ant_Design_Components.rplib.zip
好像这里有一点，先看看

**Comment by CherishGuo** [comment]
一直都是无法成功下载，不知道啥问题

**Comment by bang88** [comment]
@CherishGuo  可以下载

**Comment by CherishGuo** [comment]
每次都是这样，过一会就自动结束了，无下载到本地，是不是哪里要设置

**Comment by CherishGuo** [comment]
![Uploading AntDesign-downloaderror.png…]()

**Comment by CherishGuo** [comment]
太奇葩了，电脑重启后就可以下载了，非常感谢 @bang88 @afc163
