### ISSUE TITLE
can't Use RangePicker in Table.Column  filterDropdown

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#7402]
### Version
2.12.8

### Environment
5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Reproduction link
[https://codepen.io/xyy94813/pen/LjMeaQ?editors=001](https://codepen.io/xyy94813/pen/LjMeaQ?editors=001)

### Steps to reproduce
see https://codepen.io/xyy94813/pen/LjMeaQ?editors=001

### What is expected?
can normally use the demo,  => https://codepen.io/xyy94813/pen/LjMeaQ?editors=001

### What is actually happening?
see https://codepen.io/xyy94813/pen/LjMeaQ?editors=001

**Comment by yesmeck** [comment]
Yes, you can.

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/6393
