### ISSUE TITLE
create-react-app-antd demo样式丢失

### ISSUE THREAD

**Issue by JKhench** [ant-design/ant-design#7405]
### Version
undefined

### Environment
windows64 chrome react15.6.1 nodev8.0.0

### Reproduction link
[https://github.com/ant-design/create-react-app-antd](https://github.com/ant-design/create-react-app-antd)

### Steps to reproduce
i download the demo from https://github.com/ant-design/create-react-app-antd
then follow the steps
npm install
npm start
browser open the demo page,
the button of ant is show on the page,but css was lost.

### What is expected?
hope button of ant is show on the page with ant style.

### What is actually happening?
the button of ant is show on the page,but css was lost.

**Comment by JKhench** [comment]
i download the demo from https://github.com/ant-design/create-react-app-antd
then i follow the step
first npm install
then npm start
browser open the demo page,
the button of ant is show on the page,but css was lost.

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd/issues/8
