### ISSUE TITLE
Radio   run  error   Radio  组件无法使用，官网关于 Radio 的例子全都跑不起

### ISSUE THREAD

**Issue by xiaoyan-hou** [ant-design/ant-design#7406]
### Version
2.12.8

### Environment
Mac，chrome60.3

### Reproduction link
[https://ant.design/components/radio-cn/#components-radio-demo-size](https://ant.design/components/radio-cn/#components-radio-demo-size)

### Steps to reproduce
import {Radio} from 'antd';
class App extends Component {
    render() {
        return (
            <div>
                <Radio/>
            </div>
        );
    }
}

run   error， type is object， string  or  function  is ok、

### What is expected?
render a  radio

### What is actually happening?
run  error

---
表单中的 radio 单选

**Comment by afc163** [comment]
Please provide a reproducible demo and then I will reopen it. 

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
