### ISSUE TITLE
Cursor when hovering over the Input (TextArea) bottom right corner

### ISSUE THREAD

**Issue by topvis** [ant-design/ant-design#7410]
### What problem does this feature solve?
Show the right cursor for resizing the Input box (TextArea). This is what it currently looks:
![image](https://user-images.githubusercontent.com/5996531/29938788-e92100c6-8e57-11e7-8c1a-1b1481101a7d.png)

### What does the proposed API look like?
No api change. The cursor should be
![image](https://user-images.githubusercontent.com/5996531/29938823-000dce72-8e58-11e7-8e6e-b8b9196e1ea3.png)

**Comment by afc163** [comment]
Just go back to default cursor of browser: http://www.wibibi.com/info.php?tid=191
