### ISSUE TITLE
The Input value setting to Chinese，the parent element's height from 32px to 33px

### ISSUE THREAD

**Issue by codelegant** [ant-design/ant-design#7411]
### Version
2.12.6

### Environment
 Google Chrome 60.0.3112.113 (正式版本) （64 位）| Windows 10 1703

### Reproduction link
[https://codepen.io/codelegant/pen/wqNaZW](https://codepen.io/codelegant/pen/wqNaZW)

### Steps to reproduce
``` 
<Form>
    <Row width={900}>
      <Col span={10} offset={2}>
        <Form.Item><Input value='中文'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
     </Row>
  </Form>
```
The key point is the `value` attribute of  `Input`  is Chinese，then the height change to 33px；if  `value` attribute is been setted to English，then the height is 32px，when I removed the `line-height` style in `.ant-form-item-control` , it works well.

### What is expected?
left top, right top, left bottom, right bottom has Input Element

### What is actually happening?
Left Bottom  is empty.

---
``` 
<Form>
    <Row width={900}>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
      <Col span={10} offset={2}>
        <Form.Item><Input value='En'/></Form.Item>
      </Col>
     </Row>
  </Form>
```
All the Input value is English , works well.

**Comment by afc163** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/507615/30001822-20d2c9c0-90cc-11e7-8290-7e269a72e52a.png">

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/507615/30001824-2d959cbe-90cc-11e7-8f22-f2ebca784815.png">

It is hard to reproduce it in my environment, maybe you can help us to find a workaround fix.

**Comment by codelegant** [comment]
![image](https://user-images.githubusercontent.com/12785928/30008281-775621dc-9150-11e7-9ded-1b685f7f393b.png)
Environment: Google Chrome 60.0.3112.113 (正式版本) （64 位）| Windows 10 1703
Maybe environment is the point.

**Comment by benjycui** [comment]
@codelegant could you re-produce this with others' computer?

I cannot reproduce this on Mac Chrome@60.0.3112.113

**Comment by codelegant** [comment]
@benjycui Only has issue in my computer. I have no idea what hapened.

**Comment by benjycui** [comment]
Make sure that it is not affected by you browser plugins or other special configuration.

> Only has issue in my computer.

So, close now, we can not fix a bug which can only be re-produced on your computer.

**Comment by codelegant** [comment]
Sorry, my fault.

**Comment by afc163** [comment]
Could you tell what the computed font family in your machine?

**Comment by codelegant** [comment]
@afc163  When use default font family ("Microsoft Yahei"), the layout is correct. But use the ant body's font family, the layout is not correct.

Microsoft Yahei:
![image](https://user-images.githubusercontent.com/12785928/30042516-599e310a-9224-11e7-9e7d-6d67b81b0bc1.png)

ant body's font family:
![image](https://user-images.githubusercontent.com/12785928/30042016-0447e26c-9221-11e7-98a8-d04363e06bf6.png)

**Comment by afc163** [comment]
Check the **computed** font family.

**Comment by afc163** [comment]
Could you find out which font exactly?
