### ISSUE TITLE
Dropdown menu visible property does not work on submenu under dropdown

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#7413]
![submenu_snapshot](https://user-images.githubusercontent.com/18165261/29957573-da8d62c0-8f0b-11e7-8df5-9a5d4aed3154.png)
### Version
2.11.2

### Environment
OS version: Windows10  Browser: Chrome latest

### Reproduction link
[https://codepen.io/anon/pen/JyxXJL?editors=0011](https://codepen.io/anon/pen/JyxXJL?editors=0011)

### Steps to reproduce
Please go through the below codepen link: https://codepen.io/anon/pen/JyxXJL?editors=0011
 

### What is expected?
Menu should not dissapear after clicking on submenu1.

### What is actually happening?
Please go through the below codepen link: https://codepen.io/anon/pen/JyxXJL?editors=0011

In this click after clicking on submenu1, menu disappears. 

---
Actually the requirement  is show menu on hover of image and under there should be Another Submenu. This submenu contains checkboxes and after clicking on submenu, menu should not disappear.

**Comment by afc163** [comment]
Try this workaround: https://codepen.io/anon/pen/MvxKJx?editors=0011
