### ISSUE TITLE
【教程】如何扩展 antd 的 icon

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#7419]
antd 自带的 icon 相信大家都会用了，`<Icon type="team" />` 就搞定了，简直不能更方便了。
但是PM提需求了，team的图标要3个人的，现在是2个人。。。

所以这里教大家如何进行扩展。
- 打开 `http://iconfont.cn/` 搜索 `team`，找到想要的图标，大家可以参考官方的使用方法生成想要的图标.

- 在选择代码的时候要选`Unicode`方式，因为 antd 用的就是这种方式，就像使用字体一样使用图标。
- 点击下面的复制代码，如下
```
@font-face {
  font-family: 'iconfont';  /* project id 403570 */
  src: url('//at.alicdn.com/t/font_403570_giurk9b0g3hxgvi.eot');
  src: url('//at.alicdn.com/t/font_403570_giurk9b0g3hxgvi.eot?#iefix') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_403570_giurk9b0g3hxgvi.woff') format('woff'),
  url('//at.alicdn.com/t/font_403570_giurk9b0g3hxgvi.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_403570_giurk9b0g3hxgvi.svg#iconfont') format('svg');
}
```
- 再添加字义字体的样式代码，同样在帮助中有，代码如下:
```
.iconfont {
  font-family: "iconfont" !important;
  font-size: 14px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;
}
```

- 将以上代码放到你的 css 文件中，并引入项目。

之后就可以使用图标了:
```
<i class="iconfont">&#xe624;</i>
```
其中 `&#xe624;` 就是你的图标名称。

- 注意 `antd` 的图标都有一个 `anticon` 的类，所以一般情况下你需要这样使用图标:
```
<i class="iconfont anticon">&#xe624;</i>
```

- 至此正常使用图标已经没有问题了
但是，我还有个特殊的情况，我的图标是在侧边导航，在点击折叠导航时图标的大小会变化，也就是`font-size: `从`14px`到`16px`，折叠的时候图标会变大，所以我的 css 样式还需要增加一行：
```
.ant-menu-inline-collapsed .iconfont {
  font-size: 16px !important;
}
```
其中 `ant-menu-inline-collapsed`是折叠之后增加的类，所以这样设置就没有问题了。

- 搞定
    希望可以帮助到大家。

**Comment by WangYang-Rex** [comment]
@Witee 楼主你好，请问如何使用本地的svg？可以像antd-mobile一样么，好像不起作用
```js
<Icon className="icon-user-init" type={require('svg/icon-user-init.svg')}>
```

**Comment by Witee** [comment]
本地的我没试过

**Comment by WangYang-Rex** [comment]
本地使用svg的话需要怎么设置呢

**Comment by zhouyingkai1** [comment]
你好  谢谢分享。但是为什么要在iconfont.cn 拿到的unicode码 都显示不出来？
![image](https://user-images.githubusercontent.com/19966486/31474511-d70d7eb8-af2d-11e7-8122-fbaa85e79aa7.png)

**Comment by zhouyingkai1** [comment]
@Witee

**Comment by Witee** [comment]
打开控制台看看是不是网络问题，或是iconfont.cn后台重新生成下代码

**Comment by zhouyingkai1** [comment]
没有  我试了多个， 你这个码可以。  team 能展示出来。
![image](https://user-images.githubusercontent.com/19966486/31482972-1e9ce6e0-af5d-11e7-8dfa-6cec39d71e9e.png)

**Comment by zhouyingkai1** [comment]
![image](https://user-images.githubusercontent.com/19966486/31482994-3f22b64c-af5d-11e7-8619-1dd6572953f4.png)
我自己生成的就不能展示
![image](https://user-images.githubusercontent.com/19966486/31483025-5d1b195a-af5d-11e7-9d8d-ee965b369fd3.png)
![image](https://user-images.githubusercontent.com/19966486/31483033-632b1a3e-af5d-11e7-80b0-e064c8fc4a27.png)

**Comment by zhouyingkai1** [comment]
![image](https://user-images.githubusercontent.com/19966486/31483282-45946a24-af5e-11e7-94b7-e7f0d7dd0b43.png)
好像需要重新生成
![image](https://user-images.githubusercontent.com/19966486/31483297-53362906-af5e-11e7-94e0-977f85cff679.png)
然后就可以了。

**Comment by Witee** [comment]
嗯，因为帮你做CDN了，可能是CDN那边没处理好。

**Comment by sophieChenyx** [comment]
本地的 svg 是怎么做的啊
.png 的图片可以吗  设计只给了  .png 的

**Comment by sophieChenyx** [comment]
本地的 .svg 我用着好像不行啊
<Icon component={MessageSvg} />
用的 官方文档的示例
