### ISSUE TITLE
After the FormItem has triggered getFieldError (), the initialValue assignment cannot be used to remove the error message from getFieldError

### ISSUE THREAD

**Issue by HeLang582** [ant-design/ant-design#7420]
### Version
2.12.8

### Environment
Win 10、 Chrome 60.0.3112.113 （32 ）

### Reproduction link
[https://codepen.io/HeLang582/pen/QMYzNV](https://codepen.io/HeLang582/pen/QMYzNV)

### Steps to reproduce
1.The Children of the FormItem is a wrapped Input component that contains a Button and an Input, and the Input state is ReadOnly, and the required required fields are also set required in the rules of FormItem: true.（FormItem 的Children是一个封装过的Input组件，包含一个Button和一个Input，且Input状态为ReadOnly，并且为required必填项，在FormItem的rules中也进行了设置required: true）

2.The value of Input is controlled by Redux, and by clicking on a Button triggers a Model dialog box, which triggers a change in the value of Redux by the Radio single-selection of the Table column in the dialog box.
（Input 的值由Redux控制，通过点击一个Button触发一个Model对话框，对话框中通过Table列的Radio的单选触发改变Redux的值。）

3.The initialValue of the FormItem is also controlled by Redux, and his value is triggered by the single-box selection action in the second step above（FormItem的initialValue也是由Redux控制，他的值也是通过上面第二步中单选框选择操作触发改变的）

4.When the Input is not assigned value, click Submit , which will trigger getFieldError () to detect the error message that Input is Required.(当不对Input进行赋值的情况下，点击Submit提交，会触发getFieldError()检测到Input为Required的报错提示。)

5.After receiving the error message, the Model is triggered by clicking the Button, selecting the corresponding single box to trigger the change of Redux, the value in Redux has changed, but the initialValue of the FormItem cannot be assigned.(在得到报错提示之后，通过点击Button触发Model，选择相应的单选框触发Redux的改变，此时Redux中值发生了改变，但是FormItem的initialValue无法进行赋值。)

### What is expected?
After the value of Redux changes, initialValue can get the corresponding value and cancel the error state of getFieldError ().(Redux的值改变之后 initialValue可以得到对应的值，并且取消getFieldError () 的报错状态)

### What is actually happening?
InitialValue is not reassigned, and the error status of getFieldError () remains.(initialValue并没有进行重新赋值， getFieldError ()报错状态依旧存在。)

---
There id a BUG in the assignment after the form's null and error check. If the Children do not trigger the onChange event, only the Redux control can be changed, and the corresponding value cannot be obtained through InitialValue.(表单的判空校验报错之后的赋值存在BUG，如果Children不发触发onChange事件的情况下，只通过Redux控制其值得改变，无法通过InitialValue 得到相应的值。)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3311#issuecomment-252025039
