### ISSUE TITLE
Time picker Not positioning correctly on Modal 

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7422]
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/14k8o6jzx3

### Steps to reproduce
When used with the React Modal component with animation, the time picker doesn't position itself correctly.

### What is expected?
it should be positioned correctly

### What is actually happening?
it's not positioning correctly on the modal with animation

**Comment by afc163** [comment]
Try `getPopupContainer`

https://github.com/ant-design/ant-design/issues/3438
