### ISSUE TITLE
Checkbox in error in production

### ISSUE THREAD

**Issue by tsupol** [ant-design/ant-design#7429]
### Version
2.12.8

### Environment
Ubuntu 16.04.2 LTS, "react": "15.5.4"

### Reproduction link
[https://codepen.io/tsupol/pen/ZJPQxg?editors=001](https://codepen.io/tsupol/pen/ZJPQxg?editors=001)

### Steps to reproduce
`<Checkbox>Any Text</Checkbox>` or even using `<Checkbox>` inside `getFieldDecorator`

### What is expected?
`<Checkbox>` to work normally in production build

### What is actually happening?
Everything works fine in dev mode (no warning too) but when in production mode only <Checkbox> causes error and cannot be interacted with. Every other Antd components are fine and the error is 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `t`
```

---
I use latest next.js framework for this. ("next": "^3.2.1")

**Comment by afc163** [comment]
Could you provide a reproducible repo and a steps to it.

**Comment by tsupol** [comment]
@afc163 I could not provide a reproducible repo because the issue seem to be very confused. First it caused by `Checkbox` then `Select` then `styled-component.js` then `next.js` ... and so on until I gave up.

Feel free to close this issue. Thank you.

**Comment by benjycui** [comment]
@tsupol you can post your re-producible link here when you can re-produce it, thanks.

**Comment by tsupol** [comment]
@afc163 @benjycui I think I found the problem is `babel-plugin-import`. Correct me if I am wrong that I am not supposed to put it in .babelrc (the code below) for production environment right? I removed it and all the problem are gone.

```
{
  "presets": ["next/babel"],
  "plugins": [
    ["transform-decorators-legacy"],
    [
      "import",
      {
        "libraryName": "antd"
      }
    ]
  ]
}
```

**Comment by afc163** [comment]
> I am not supposed to put it in .babelrc

You should, or your production file will include all antd component, which is big.

I think it maybe a bug of babel-plugin-import, can you provide a reproducible repo?

**Comment by tsupol** [comment]
@afc163 @benjycui here is the [reproducible repo](https://github.com/tsupol/debug-antd-prod). More details on README.md.

**Comment by benjycui** [comment]
1. git clone
1. npm i  && npm run dev
1. open 127.0.0.1:4000

Then you will see an error:

```bash
Unexpected token .
/private/tmp/debug-antd-prod/node_modules/_react-responsive-carousel@3.1.25@react-responsive-carousel/lib/styles/carousel.min.css:1
(function (exports, require, module, __filename, __dirname) { .carousel .control-arrow,.carousel.carousel-slider .control-arrow{-webkit-transition:all .25s ease-in;-moz-transition:all .25s ease-in;-ms-transition:all .25s ease-in;-o-transition:all .25s ease-in;transition:all .25s ease-in;opacity:.4;position:absolute;z-index:2;top:20px;background:0 0;border:0;font-size:32px;cursor:pointer}.carousel .control-arrow:hover{opacity:1}.carousel .control-arrow:before,.carousel.carousel-slider .control-arrow:before{margin:0 5px;display:inline-block;border-top:8px solid transparent;border-bottom:8px solid transparent;content:''}.carousel .control-disabled.control-arrow{opacity:0;cursor:inherit;display:none}.carousel .control-prev.control-arrow{left:0}.carousel .control-prev.control-arrow:before{border-right:8px solid #fff}.carousel .control-next.control-arrow{right:0}.carousel .control-ne

SyntaxError: Unexpected token .
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._compile (/private/tmp/debug-antd-prod/node_modules/_source-map-support@0.4.15@source-map-support/source-map-support.js:483:25)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/private/tmp/debug-antd-prod/node_modules/_babel-watch@2.0.7@babel-watch/runner.js:63:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

@tsupol make sure that your code works, thanks.

**Comment by tsupol** [comment]
@benjycui I am pretty sure that my repo works (tested on both win and mac). However, I removed some dependencies which might cause the above error. Please do git pull again, thank you.

**Comment by benjycui** [comment]
1. git clone
1. npm i && npm run build && npm start
1. open 127.0.0.1:4000

Then it works fine:

<img src="http://g.recordit.co/fV23KPJal7.gif" />
