### ISSUE TITLE
`fieldset[disabled]` 下的 `Select` 没有 disabled

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#743]
![image](https://cloud.githubusercontent.com/assets/3580607/11991309/bf84622e-aa53-11e5-930c-84603d834939.png)

虽然没有测试，但是除了 `Select` 以外的非原生控件（`Slider` `Switch` 等）应该都没有 disabled。

目前有个思路是，把 `fieldset` 也改为组件 `Fieldset`，当 `Fieldset` disabled 后，遍历 `children` 中的控件自动加上 `disabled`。又或者让用户自行加 `disabled`? 

@afc163

**Comment by yiminghe** [comment]
不要支持这种，组件自己处理自己

**Comment by afc163** [comment]
嗯，这个特性在 html 里也极少用到。

**Comment by benjycui** [comment]
主要是这个用例 http://ant.design/components/form/#demo-disabled

毕竟组件无法知道 `fieldset` 是否 `disabled`。

**Comment by benjycui** [comment]
那先关了，使用场景多才考虑吧。
