### ISSUE TITLE
Keyboard events for Mention component

### ISSUE THREAD

**Issue by xorandiff** [ant-design/ant-design#7430]
### What problem does this feature solve?
Mention component is often used in chat applications as main chat input - user should be able just to press Enter instead of pressing submit button. Regular Input component already has it.

### What does the proposed API look like?
onKeyPress property on Mention component or at least onPressEnter property, just like in case of Input component

**Comment by benjycui** [comment]
A work around for now:

```jsx
import { Mention } from 'antd';

ReactDOM.render(
  <div onKeyPress ={() => console.log('hello')}>
    <Mention />
  </div>
, mountNode);
```

**Comment by xiebl** [comment]
这个方式可以捕获普通按键事件，还是无法处理回车之类的事件。

**Comment by kristiankyvik** [comment]
Has anyone found a solution to this, I want to use the mention component for a chat application, but I need to able to trigger it with a enter key

**Comment by NoureldeanSaed** [comment]
This issue needs fix, how come it is simply skipped to create keyboard events for a text input??

**Comment by jacquescrocker** [comment]
We really need this as well. Seems like we have to fork the component just to add it?
