### ISSUE TITLE
Doc search via algolia

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#7436]
https://www.algolia.com/

**Comment by benjycui** [comment]
简单看了下，不是很懂，但是看了免费版的限制。。感觉不够用。。

![image](https://user-images.githubusercontent.com/3580607/30011136-b0e19f82-9167-11e7-9d61-52b3d3efe3bf.png)

**Comment by afc163** [comment]
https://getbootstrap.com/docs/4.0/getting-started/introduction/ and https://lightningdesignsystem.com/getting-started/ are using it.

**Comment by nikogu** [comment]
今天上午试用了一下，感觉有点鸡肋。。。搜索的数据都是在平台上写好的，然后它自动生成 query 可以查询，但是本身它是没有爬网站的，相当于还是需要自己写数据，不是自动生成...

这样看来感觉跟把搜索数据放到本地，然后用 `AutoCompelte` 是一样的。

好处就是能看到一些统计信息，然后更新的话可以脱离站点独立更新。

antd pro 还是打算先试用一下

**Comment by afc163** [comment]
> 本身它是没有爬网站的

爬网站数据的方案不靠谱的，需要组织化的搜索结果。

**Comment by monkindey** [comment]
之前用过一下 https://github.com/eggjs/egg/pull/542

需要申请对应的`API KEY`, 然后引入algolia对应的cdn js和css.

它应该是会定时在登记的网站爬虫, 然后你输入都是跟algolia获取数据, 而且是有格式化的。

**Comment by nikogu** [comment]
@monkindey 我再看看，我确实拿到了 `API KEY`，不过我这边获取的数据是自己人肉填的，我去看看是否有对应的 `API` 可以调用

**Comment by nikogu** [comment]
https://community.algolia.com/docsearch/

**Comment by monkindey** [comment]
@nikogu  注册好了之后有人用邮件联系你了么? 他会帮你配置对应的爬虫爬网站。不需要你调用对应的API。引入对应的js/css就行了。

**Comment by nikogu** [comment]
@monkindey ...服务这么好，那还是等我们域名固定，内容丰富以后再去找他们好了，我刚才注册了，但是还未有反馈。。。

**Comment by monkindey** [comment]
哈哈, 服务还挺不错的呢, 需要等下时间吧。之前他的邮件内容大概是

```
Thank you for your interest in Algolia DocSearch! We would love to help the eggjs project with the 
search but we'll need to inject a small JavaScript snippet in the page: are you able to do that?
```

**Comment by yesmeck** [comment]
这个可以配合12月底的新网站搞一下吧。

**Comment by afc163** [comment]
对，其实 pro 已经上了。@nikogu 这块是不是可以直接搞掉。

**Comment by yesmeck** [comment]
我来搞下吧
