### ISSUE TITLE
Component DatePicker: When the input box in the component manually modifies the time, the cursor jumps to the end

### ISSUE THREAD

**Issue by laughing-pic-zhu** [ant-design/ant-design#7443]
### Version
2.13.0

### Environment
version 60.0.3112.113 （64 Bit）

### Reproduction link
[https://codepen.io/laughing-pic-zhu/pen/gxEvEJ](https://codepen.io/laughing-pic-zhu/pen/gxEvEJ)

### Steps to reproduce

Click the select time, enter the time in the input box, and the cursor automatically jumps to the end

### What is expected?
We need to change the time in the input box, the cursor does not bounce。

### What is actually happening?
The cursor jumps to the end

**Comment by benjycui** [comment]
Yep, but it only happens when you had inputed a valid date string. So, why do this trouble you?

**Comment by laughing-pic-zhu** [comment]
but the correct date automatically jumps to the end, and the valid data does not jump。

**Comment by benjycui** [comment]
> but the correct date automatically jumps to the end, and the valid data does not jump。

？？？ Details, please.

**Comment by benjycui** [comment]
Close for no response.

**Comment by afc163** [comment]
![calendar](https://user-images.githubusercontent.com/507615/30575086-e9111462-9d30-11e7-9814-ae78a451250d.gif)

**Comment by benjycui** [comment]
> Yep, but it only happens when you had inputed a valid date string. So, why do this trouble you?

@afc163

**Comment by afc163** [comment]
I think the cursor should be consistent.

**Comment by laughing-pic-zhu** [comment]
good Screenshots. That's what I want to say.

**Comment by benjycui** [comment]
antd@3.0 will fix this.
