### ISSUE TITLE
Broken table behavior after update from 2.12.7 version

### ISSUE THREAD

**Issue by gromver** [ant-design/ant-design#7444]
### Version
2.13.0

### Environment
Ubuntu 16.04, react 15.6.1, Chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/gromver/pen/jLJzPV](https://codepen.io/gromver/pen/jLJzPV)

### Steps to reproduce
Trying to render a table with empty items and fixed column.

```js
        <Table
          rowKey={d => d.id}
          dataSource={[]}
        >
          <Column
            title="ID"
            dataIndex="id"
            fixed
          />
          <Column
            title="Name"
            dataIndex="name"
            render={(d) => d.name}
          />
        </Table>
```

### What is expected?
rendered table with "No data" text

### What is actually happening?
Table tries to render an undefined row and throws the error:

uncaught at init TypeError: Cannot read property 'name' of undefined

**Comment by afc163** [comment]
```diff
- render={(d) => d.name}
```

**Comment by gromver** [comment]
- render={(d) => d.name}

This is not solving the problem. Most tables has custom render logic. So if the table has a fixed column we must workaround this like that:
render={(d) => d && d.name}
or like that:
```jsx
<Table
          rowKey={d => d.id}
          dataSource={items}
        >
          <Column
            title="ID"
            dataIndex="id"
            fixed={!!items.length}
          />
          <Column
            title="Name"
            dataIndex="name"
            render={(d) => d.name}
          />
        </Table>
```

I think it's very strange behavior.

**Comment by afc163** [comment]
```diff
- render={(d) => d.name}
+ render={(text, record) => record.name}
```

**Comment by gromver** [comment]
It's right. I rewrote the code <https://codepen.io/gromver/pen/jLJzPV>, it
better reflects the problem:
<Column
   render={(text, record) => {
       // Here I expect to receive a record from my items list, but in fact
I can get an object like this {key: "empty-placeholder-data"}
       // This is confusing, isn't it?
       console.log(record);
   }}
/>

2017-09-04 16:00 GMT+03:00 偏右 <notifications@github.com>:

**Comment by afc163** [comment]
> https://codepen.io/gromver/pen/jLJzPV

But it works. You can just ignore the object of `{key: "empty-placeholder-data"}`.

**Comment by gromver** [comment]
Ok, we just have to keep in mind this weird behavior.
P.S. Please note this in the documentation

2017-09-04 16:54 GMT+03:00 偏右 <notifications@github.com>:

**Comment by joshbenhamou** [comment]
Why does the render function get called if there is no data? this means we need to add additional logic in render functions to verify for empty-placeholder-data?

**Comment by joshbenhamou** [comment]
Also getting console errors because there is no unique property in the rowKey
