### ISSUE TITLE
antd2.13.0 checkbox  build failed

### ISSUE THREAD

**Issue by and80506** [ant-design/ant-design#7447]
### Version
2.13.0

### Environment
macOS Sierra10.12.6 Chrome60.0.3112.113 react15.1.0 webpack3.5.5

### Reproduction link
[https://github.com/and80506/ant-design-demo.git](https://github.com/and80506/ant-design-demo.git)

### Steps to reproduce
npm run build

### What is expected?
webpack build succeed

### What is actually happening?
```
ERROR in ./node_modules/.2.13.0@antd/lib/checkbox/style/index.css
Module build failed: media definitions require block statements after any features
 @ /Users/andy/code/ant-design-demo/node_modules/.2.13.0@antd/lib/checkbox/style/index.css (line 180, column 7)
 near lines:
   }
   @media \0screen {
     .ant-checkbox-checked .ant-checkbox-inner:before,
 @ ./node_modules/.2.13.0@antd/lib/checkbox/style/css.js 5:0-22
 @ ./index.js
 @ multi ./index
```

**Comment by benjycui** [comment]
@afc163 we can revert this commit now https://github.com/ant-design/ant-design/commit/3310f59d2002fd78b713468cf55b77dbcc8156e2

Which cause this issue.

**Comment by afc163** [comment]
Why other workflow works fine?

**Comment by benjycui** [comment]
@and80506 you should not [use less-loader for `.css`](https://github.com/and80506/ant-design-demo/blob/master/webpack.config.js#L74), for less-loader doesn't support this syntax.

@afc163 Anyway, we should remove [hacks for IE8](https://github.com/ant-design/ant-design/search?utf8=%E2%9C%93&q=IE8&type=) now, for antd doesn't support IE8 any more.

**Comment by afc163** [comment]
OK, we can remove it at antd-3.0.

**Comment by xingzhewj** [comment]
this should is bug, when we do not support IE8, but you forget modify this.

**Comment by and80506** [comment]
good job!
