### ISSUE TITLE
希望message组件增加全局config一个参数，可以让限制页面弹出的message个数或者移除之前的message

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#7448]
### What problem does this feature solve?
页面看起来不爽，如果你有一个按钮 这个按钮点击一次会有一个错误提醒，如果你连续点击很多次，上一个message还没有消失，下一个message又出现了，很别扭。

### What does the proposed API look like?
希望提供一个config，让新的message一出现就移除掉还未消失的老message

**Comment by benjycui** [comment]
这个更多的是业务代码没处理好吧。。你那个按钮点击后发生什么？

**Comment by ybning** [comment]
`notification.error({ key: Math.random(), message: '', description: "不能为空"});`
组件notification，可以通过添加key，实现 @ouzhou 想要的效果。
@benjycui 希望组件Message也可以。

**Comment by ouzhou** [comment]
比如点击按钮登录啊，登录出错message提示，用户就能一直点。因为ajax返回结果速度还算快，导致页面出现很多个message，具体的感觉就像是在https://ant.design/components/message-cn/  这个页面多次点击里面的按钮一样，因为我总不能显示用户在登录失败后的2s内不能操作吧

**Comment by afc163** [comment]
点击按钮登录后，应该置 disabled 防止重复点击。message 这个是有意的改动，防止吞掉有用的信息。

**Comment by ouzhou** [comment]
在使用中是设置了 disabled 防止重复点击，但是返回数据的速度还是挺快的，这个disabled 状态 一下子就没有了，还是会出现多个message的情况。

**Comment by 520Yanxiaofei** [comment]
你好，那个多个message解决了吗，是什么方案呢

**Comment by ouzhou** [comment]
官方人员觉得这个是一个feature 不是一个bug  你就这样给你老板说就行了呗

**Comment by 520Yanxiaofei** [comment]
@ouzhou 恩恩，好的，谢谢你的回复

**Comment by monkindey** [comment]
下面是伪代码

思路是加一个变量做控制

```js
let once = false;
Button.onClick = function() {
  if(!once) {
      once = true;
      message.error(msg, 2, () => {
          once = false;
        }
      )
  }
}
```

**Comment by ouzhou** [comment]
@monkindey hhhh 你很有想法  ：）  和我学做菜吧

**Comment by monkindey** [comment]
😂 这个还可以跟做菜扯上关系?
