### ISSUE TITLE
CheckableTag bug CheckableTag extends React.Component<CheckableTagProps> should be CheckableTag extends React.Component<CheckableTagProps, any> 

### ISSUE THREAD

**Issue by lvlephistophele** [ant-design/ant-design#7450]
### Version
2.13.0

### Environment
ant 2.13.0, typescript

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/tag/CheckableTag.tsx](https://github.com/ant-design/ant-design/blob/master/components/tag/CheckableTag.tsx)

### Steps to reproduce
export default class CheckableTag extends React.Component<CheckableTagProps>

should be

export default class CheckableTag extends React.Component<CheckableTagProps, any> 

### What is expected?
successful application compilation

### What is actually happening?
unsuccessful application compilation

---
export default class CheckableTag extends React.Component<CheckableTagProps>

should be

export default class CheckableTag extends React.Component<CheckableTagProps, any>

**Comment by benjycui** [comment]
The version of your TypeScript?

**Comment by lvlephistophele** [comment]
typescript@2.3.4

**Comment by benjycui** [comment]
Try to upgrade your @types/react to latest version.

**Comment by benjycui** [comment]
Close for no response.
