### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react-slick'

### ISSUE THREAD

**Issue by goofusuper** [ant-design/ant-design#7452]
### Version
2.13.0

### Environment
Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

### Reproduction link
[http://no](http://no)

### Steps to reproduce
$ git clone git@github.com:ant-design/ant-design.git
$ npm install
$ npm start

### What is expected?
无报错，正常启动

### What is actually happening?
报错了

---
虚拟机CentOS7环境一把就重现了，npm install 无报错，npm start最后报了错

**Comment by afc163** [comment]
> npm start最后报了错

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by goofusuper** [comment]
ERROR in ./components/carousel/index.tsx
Module not found: Error: Cannot resolve module 'react-slick' in /Users/goofus/Documents/WebstormProjects/ant-design/components/carousel
 @ ./components/carousel/index.tsx 51:20-42

**Comment by goofusuper** [comment]
antd-tools run guard
npm WARN bisheng-plugin-antd@0.15.0 requires a peer of bisheng@^0.22.0 but none was installed.

**Comment by afc163** [comment]
It works in my machine. Try reinstall node_modules and make sure your network is good.

**Comment by goofusuper** [comment]
$ npm install bisheng
antd@2.12.8 /Users/goofus/Documents/WebstormProjects/ant-design
└── UNMET PEER DEPENDENCY bisheng@0.24.2

npm WARN bisheng-plugin-antd@0.15.0 requires a peer of bisheng@^0.22.0 but none was installed.
npm ERR! code 1

**Comment by afc163** [comment]
Is it your npm version is too old? Try npm@4 or yarn or cnpm.

**Comment by goofusuper** [comment]
node_modules removed, and reinstall. The only error:
npm WARN bisheng-plugin-antd@0.15.0 requires a peer of bisheng@^0.22.0 but none was installed.

**Comment by afc163** [comment]
That is a warning that could be ignored.

**Comment by goofusuper** [comment]
God, npm version is 3.10.10

**Comment by goofusuper** [comment]
node version is v6.11.1

**Comment by goofusuper** [comment]
Thanks! ip:8001 open ok.  but reinstall and start, output:
-----------
 WARNING  Compiled with 1 warnings                                                                                                                                     10:07:26

 warning  in ./~/bezier-easing/dist/bezier-easing.js

Critical dependencies:
1:485-492 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

 @ ./~/bezier-easing/dist/bezier-easing.js 1:485-492


webpack: bundle build is now finished.
----------

**Comment by saklen077** [comment]
anrsol
