### ISSUE TITLE
antd的table行高问题

### ISSUE THREAD

**Issue by shazidama** [ant-design/ant-design#7453]
### What problem does this feature solve?
ant design中，table的行高无法调整为0，从而导致使用ant motion时，较难实现table最底一行同时增加最上一行的效果

### What does the proposed API look like?
table行高可以进行设置min

**Comment by afc163** [comment]
I don't understand what your request, maybe you can try override the styles.

**Comment by shazidama** [comment]
Forget to import css file... A stupid bug...
