### ISSUE TITLE
‘multiple’ and ‘showSearch’ in Select

### ISSUE THREAD

**Issue by brevity0209** [ant-design/ant-design#7454]
### What problem does this feature solve?
下拉框内容比较多时，支持搜索，这样比较快捷

### What does the proposed API look like?
<Select  mode='multiple' showSearch    />

**Comment by afc163** [comment]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/507615/30041900-36b98134-9220-11e7-8397-14901f4260d8.png">

Search here.
