### ISSUE TITLE
shows the exception when Table no result  

### ISSUE THREAD

**Issue by w567675** [ant-design/ant-design#7456]
### Version
2.13.0

### Environment
chrome 

### Reproduction link
[https://codepen.io/w567675/pen/PKgwmj?editors=1010](https://codepen.io/w567675/pen/PKgwmj?editors=1010)

### Steps to reproduce
1: dataSource is empty
2: fixed any column

### What is expected?
just show no result 

### What is actually happening?
shows the exception

**Comment by afc163** [comment]
Your codepen works fine.

**Comment by w567675** [comment]
![image](https://user-images.githubusercontent.com/6658087/30043840-8052a74c-922c-11e7-9ee7-2b7d504aab06.png)
why left side has  something ? 
This is normal it?

**Comment by afc163** [comment]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/507615/30044374-50016454-922f-11e7-8eac-96b5c533392e.png">

works on my marchine.

**Comment by afc163** [comment]
I reproduced it by ture on the scroll bar in OSX

**Comment by afc163** [comment]
trace #7456
