### ISSUE TITLE
table Scroll bars are not displayed

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#7457]
### Version
2.13.0

### Environment
antd version 2.13.0

### Reproduction link
[https://github.com/qq645381995/antdDemo/tree/master](https://github.com/qq645381995/antdDemo/tree/master)

### Steps to reproduce
npm i ; npm start; open localhost:4000
 

### What is expected?
Display scrollbars
I described the gap that I expected
I hope that the countless data will not be render, so the format will have problems

### What is actually happening?
Scroll bars are not displayed
![image](https://user-images.githubusercontent.com/7971419/30044600-9dd1f224-9230-11e7-99e4-38978acd89a1.png)

**Comment by qq645381995** [comment]
#7298

**Comment by qq645381995** [comment]
@afc163 周几发版？

**Comment by afc163** [comment]
周末。

**Comment by qq645381995** [comment]
@afc163 还是有点小问题

Warning: Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key.

还是有一次 render 返回的是 empty-placeholder-data
但是 rowKey 用我这数据的 key 就会是 undefined

**Comment by afc163** [comment]
我看看。

**Comment by qq645381995** [comment]
@afc163  更新了
