### ISSUE TITLE
TS2694: Namespace 'React' has no exported member 'TextareaHTMLAttributes'.

### ISSUE THREAD

**Issue by lvlephistophele** [ant-design/ant-design#7459]
### Version
2.13.0

### Environment
typescript 2.3.4

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input/TextArea.tsx](https://github.com/ant-design/ant-design/blob/master/components/input/TextArea.tsx)

### Steps to reproduce
ERROR in [at-loader] ./node_modules/antd/lib/input/TextArea.d.ts:12:47
    TS2694: Namespace 'React' has no exported member 'TextareaHTMLAttributes'.
webpack: Failed to compile.

### What is expected?
succesfull application compilation

### What is actually happening?
ERROR in [at-loader] ./node_modules/antd/lib/input/TextArea.d.ts:12:47
    TS2694: Namespace 'React' has no exported member 'TextareaHTMLAttributes'.
webpack: Failed to compile.

---
i can attach package.json file

**Comment by afc163** [comment]
What version is `@types/react`?

**Comment by lvlephistophele** [comment]
"@types/react": "15.0.24"

**Comment by afc163** [comment]
Could you try latest version?

**Comment by lvlephistophele** [comment]
using latest version returns over 2000 compilation errors =(

**Comment by benjycui** [comment]
A re-producible repo is better, thanks.

**Comment by afc163** [comment]
You should upgrade `@types/react` to latest version.

**Comment by gy134340** [comment]
antd version: 2.13.9
tsc version: 2.5.2

also checked your `package.json` in `2.13.9` vertion, and found 

```
...
@types/react": "^15.0.38",
@types/react-dom": "^0.14.18"
...

```
and changed mine, still met this problem. what do you mean `upgrade @types/react`?  I think for the version `2.13.9`, I already upgrade it.
