### ISSUE TITLE
error TS2304: Cannot find name 'PropertyKey' 

### ISSUE THREAD

**Issue by bva999** [ant-design/ant-design#7464]
### Version
2.13.0

### Environment
Windows 10, Visual Studio Code, 

### Reproduction link
[https://codepen.io/bva99/pen/XaQXgQ](https://codepen.io/bva99/pen/XaQXgQ)

### Steps to reproduce
1) Setup SharePoint Framework (React) project
2) Add antd, `npm install antd --save`
3) Add types `npm install @types/antd -D`
4) Import DatePicker` import { DatePicker } from "antd";`
5) `gulp serve`

### What is expected?
succesfull application compilation

### What is actually happening?
[10:33:21] Error - typescript - node_modules\antd\lib\table\Table.d.ts(116,26): error TS2304: Cannot find name 'PropertyKey'.

[10:33:21] Error - typescript - node_modules\antd\lib\table\Table.d.ts(119,32): error TS2304: Cannot find name 'PropertyKey'.

package.json 
```
"scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.2.0",
    "@microsoft/sp-webpart-base": "~1.2.0",
    "@types/react": "15.0.38",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "antd": "^2.13.0",
    "office-ui-fabric-react": "^4.40.0",
    "react": "15.4.2",
    "react-dom": "15.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.2.0",
    "@microsoft/sp-module-interfaces": "~1.2.0",
    "@microsoft/sp-webpart-workbench": "~1.2.0",
    "@types/antd": "^1.0.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "gulp": "~3.9.1"
  }
}

```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "types": [
      "es6-promise",
      "es6-collections",
      "webpack-env"
    ]
  }
}
```

**Comment by benjycui** [comment]
> Setup SharePoint Framework (React) project

What is this?

**Comment by afc163** [comment]
Don't use `@types/antd`, it is unnessary.

**Comment by bva999** [comment]
> Setup SharePoint Framework (React) project
> What is this?
>>
https://dev.office.com/sharepoint/docs/spfx/sharepoint-framework-overview

**Comment by bva999** [comment]
>Don't use @types/antd, it is unnessary.
>>
I uninstalled it. But I have the same error

**Comment by benjycui** [comment]
You had better provide a re-producible repo.

**Comment by bva999** [comment]
When I commented this two lines of code in Table.d.ts , the error has gone... And components work fine. But I don't think that it's the solution of the problem. 

`getLocale(): {
        filterTitle: string;
        filterConfirm: string;
        filterReset: string;
        emptyText: JSX.Element;
        selectAll: string;
        selectInvert: string;
    } | {
        constructor: Function;
        toString(): string;
        toLocaleString(): string;
        valueOf(): Object;
        hasOwnProperty(v: string): boolean;
        **//hasOwnProperty(v: PropertyKey): boolean;**
        isPrototypeOf(v: Object): boolean;
        propertyIsEnumerable(v: string): boolean;
        **//propertyIsEnumerable(v: PropertyKey): boolean;**
        filterTitle: string;
        filterConfirm: string;
        filterReset: string;
        emptyText: JSX.Element;
        selectAll: string;
        selectInvert: string;
    };`

**Comment by benjycui** [comment]
> You had better provide a re-producible repo.

**Comment by afc163** [comment]
Try upgrade `@types/react` to latest version.
