### ISSUE TITLE
表格固定操作列，数据为空时显示不正常

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#7468]
### Version
2.13.0

### Environment
win10 chrome60

### Reproduction link
[https://codepen.io/anon/pen/JyVXGb?&editors=001](https://codepen.io/anon/pen/JyVXGb?&editors=001)

### Steps to reproduce
打开上面codepen链接，查看`action`列

### What is expected?
数据为空时，操作列应该也是空的

### What is actually happening?
数据为空时，操作列单元格显示了

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/7457
