### ISSUE TITLE
TreeSelect checkable, popover not keeping position

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#7469]
### Version
2.13.0

### Environment
os all version, all browsers

### Reproduction link
[http://dev.mediacross.it/treeselect/](http://dev.mediacross.it/treeselect/)

### Steps to reproduce
TreeSelect with checkable set to true and showCheckedStrategy to SHOW_PARENT
list of nested data that is longer then the height of the browser window.
Start to select checkboxs at various depth of the tree.

### What is expected?
the popover list should stay in place

### What is actually happening?
the popover moves, losing the position of what you were checking, making very difficult to use the component, especially on mobile devices

---
the key point to reproduce the bug is to have the popover longer then the height of the browser window.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3438

https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-will-scroll-with-page

**Comment by violabg** [comment]
That is not the issue I have described, I'm not talking about scrolling the page and wanted to have a fixed popover.
The issue is that when I click a nested checkbox the popover shift position.
Sorry if it wasn't clear before
