### ISSUE TITLE
Table 在固定头和列并且无数据情况下   操作按钮会显示出来 

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#7470]
### Version
2.13.0

### Environment
win7   Google Chrome 61.0.3159.5   

### Reproduction link
[https://codepen.io/anon/pen/ayxNeV?editors=0010](https://codepen.io/anon/pen/ayxNeV?editors=0010)

### Steps to reproduce
使用官网https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header 例子，在codepen中data设为空数组 

### What is expected?
无数据情况下不显示fixed 列表

### What is actually happening?
无数据情况下会显示fixed 列表

**Comment by afc163** [comment]
Fixed in #7457
