### ISSUE TITLE
DatePicker - picker to go away on enter

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#7474]
### What problem does this feature solve?
More user-friendly​ (intuitive)

### What does the proposed API look like?
As for now, the DatePicker allows the user to input the date by himself, but on the Enter press the date is selected, but the picker is still there. Wouldn't it be nice to just hide the picker if a user decides to enter the date manually and confirm it by pressing enter?

**Comment by benjycui** [comment]
We have no time to improve keyboard accessibility, but PR is welcomed, thanks.

**Comment by jzhangs** [comment]
@benjycui @yesmeck  some update in rc-calendar, need your advices. thx

**Comment by afc163** [comment]
It will close Picker when press enter now.
