### ISSUE TITLE
How can we define the number of rows per page on the table pagination? like 10, 25, 50 etc

### ISSUE THREAD

**Issue by jaisonjjames** [ant-design/ant-design#7477]
### What problem does this feature solve?
If we can define the number of rows per page on the table pagination, So we can set a number of rows on the same page according to user wish.

### What does the proposed API look like?
same like columns we can add pageRowCount={25 or 50 or all }

**Comment by jaisonjjames** [comment]
Sorry for posting here, I was posting this question on StackOverflow too, didn't get any answer, So one more query from me is there any way to accomplish to off/on the column in the front end like show: true/false, so we can allow to the end user to arrange the column lengths from the front end itself. looking like `var column = [{
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
  **show:false**
}]`

**Comment by yeomann** [comment]
did you find show/hide then? @jaisonjjames

**Comment by mauricio-msp** [comment]
How I select a maximum number of rows using select All. Ex: in a table with 10 rows select All marks a maximum of 5 rows.
