### ISSUE TITLE
Support Bottom Navigation Component

### ISSUE THREAD

**Issue by bodaz** [ant-design/ant-design#7478]
### What problem does this feature solve?
It is shown that hamburger icon or sider could cost  user engagements for mobile websites, [Why to avoid hamburger menu](https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/) and [this article](http://scotthurff.com/posts/how-to-design-for-thumbs-in-the-era-of-huge-screens) shows that the bottom half of a mobile screen is more natural to interact with. So, the proposal is to support Bottom Navigation component for the mobile web user experience. 

### What does the proposed API look like?
An example is the Google Material Design spcs here: [https://material.io/guidelines/components/bottom-navigation.html](https://material.io/guidelines/components/bottom-navigation.html)

**Comment by afc163** [comment]
Check http://mobile.ant.design/
