### ISSUE TITLE
  Select multiple 情况下是否能disable输入呢？

### ISSUE THREAD

**Issue by pmjhonwang** [ant-design/ant-design#748]
Select multiple 情况下是否能disable输入呢？

**Comment by pmjhonwang** [comment]
<Select
                            multiple
                            size="large"
                            defaultValue={}
                            onChange={this.onChangeHandler}
                            dropdownMatchSelectWidth={false}
                            filterOption={false}
                        >

我是这样配置的

**Comment by afc163** [comment]
```jsx
<Select multiple disabled>
  ...
</Select>
````

**Comment by pmjhonwang** [comment]
我说的不是这个禁用，而是禁用输入框输入字符 而不是禁用整个多选控件
