### ISSUE TITLE
CheckBox with Form was not work

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#7481]
### Version
2.12.8

### Environment
ubuntu14.04, react15.6.1

### Steps to reproduce
I'm first use `<Checkbox>` component to complete , and then use the `<Form>` component nested in the outer layer.
that will show me a error:
```es6
`getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.
```
Then i tyr put  `<CheckboxGroup>` `value` to `<FormItem>` `initialValue`, it's ok.

But next, i try to click some checkbox value,and then to click the `check all` checkbox, it;s not work.

### What is expected?
can be work well

### What is actually happening?
It's work well when first click, but after to click some checkbox value, again to click `check all` is not work

---
After ckick some checkbox, try to click `all check` is not work
I try to remove `<Form>` component,  only one `<CheckBox>` component to work, it's work well.
 so, i think that issue because of `<Form>` and `<CheckBox>` or my code issue?

ps: my english is too bad, sorry to bother you

**Comment by didmehh** [comment]
ok, was updated

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by didmehh** [comment]
[Without Form](https://codepen.io/xiaohesong/pen/ayxrEB?editors=0010)
[Within Form](https://codepen.io/xiaohesong/pen/dzLLrX?editors=0010)

**Comment by afc163** [comment]
Please read the documentation: https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options)

**Comment by afc163** [comment]
In this case, you can give up `getFieldDecorator` and just use setState and onChange.

**Comment by didmehh** [comment]
your mean is can't useable together.

**Comment by afc163** [comment]
yep

**Comment by Faliszek** [comment]
I ran in to similar problem, when i was trying to send form with selected checkbox, because function validateFields expect to get value from field, but checkbox returned "checked", solution to my problem was set in the fieldDecorator valuePropName as 'checked' like this.

```
    <FormItem label="Name">
          {getFieldDecorator('name', {
            initialValue: some.value || '',
            valuePropName: 'checked'
          })(<Checkbox />)}
        </FormItem>
```

**Comment by benjycui** [comment]
@Faliszek 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by R-on** [comment]
I think the correct solution for setting initialValue for checkboxes is the following: You have to set two options:
- valuePropName to "checked"
- initialValue to "true" (or "false" but this is the default)

```
<Form.Item label="Dummylabel">
            {getFieldDecorator("name", {
              valuePropName: "checked",
              initialValue: true
            })(
              <Checkbox />
            )}
          </Form.Item>
```

**Comment by gl2748** [comment]
The above mentioned way will still give you a console warning:
```
Warning: `getFieldDecorator` will override `checked`, so please don't set `checked` directly and use `setFieldsValue` to set it.
```
The correct way to do this is as follows (note the handleCheckbox method is extensible to handle multiple checkboxes for your form):  
### 1. Add checkbox state to component state.
```
    constructor(props: ICreateSourceCodeFormProps) {
        super(props);
        this.state = { handheld: true };
    }

```

### 2. Handle Checkbox onChange method.
```
    handleCheckbox = (checkbox: "handheld") => (e: CheckboxChangeEvent) => {
        switch (checkbox) {
            case "handheld":
                this.setState({ handheld: e.target.checked });
                break;
            default:
                break;
        }
        this.props.form.setFieldsValue({
            [checkbox]: e.target.checked
        })
    }
```
### 3. Make sure the checkbox is registered as a form item.
```
<Form.Item key="handheld" className="create-sourceCode--handheld">
    {getFieldDecorator('handheld', {
        valuePropName: 'checked',
    })(
        <Checkbox value={this.state.handheld} onChange={this.handleCheckbox('handheld')}>
            Is Handheld
        </Checkbox>,
    )}
</Form.Item>,
```

**Comment by gsofter** [comment]
Does the above method still work with `ant design v4`?
