### ISSUE TITLE
Form fields have been reset after pagination changed in table.

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#7485]
### Version
2.13.0

### Environment
Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/RaoHai/pen/MvRddy?editors=0010](https://codepen.io/RaoHai/pen/MvRddy?editors=0010)

### Steps to reproduce
1. Open demo page https://codepen.io/RaoHai/pen/MvRddy?editors=0010
2. Type something into input field.
3. Change pagination to page 2 then change back to page 1.
4. Contents of inputs in page 1 have been reset.

### What is expected?
Contents of inputs in page 1 should keep.

### What is actually happening?
Then all disappeared.

---
:D

**Comment by benjycui** [comment]
rc-form will clear data when its form control is unmounted.

**Comment by benjycui** [comment]
Just cache fields' value before you refresh the list, and restore it after return.
