### ISSUE TITLE
请问upload组件如何自定义上传功能

### ISSUE THREAD

**Issue by JiangAmber** [ant-design/ant-design#749]
例如我在上传图片的时候，我想在拖动或者选择图片后编辑图片或者裁剪图片后再上传到服务器，而且我们使用的云存储不是自己的业务服务器，使用一些云存储服务器需要验证token，请问如何自定义上传功能。谢谢

**Comment by afc163** [comment]
需要 header ？关注 #677

**Comment by JiangAmber** [comment]
对 增加header  要增加一个token的header
