### ISSUE TITLE
The Select component can not control the height of the display box when selecting multiple items.

### ISSUE THREAD

**Issue by lxzhangchao** [ant-design/ant-design#7497]
Version
     2.12.2

Environment
     macos

Reproduction link
     https://ant.design/components/select-cn/

What problem does this feature solve?
    In Select multiple application scenarios, some business requirements may have a lot of data. 
    When you Select too much data, the display box height will be too high!

![default](https://user-images.githubusercontent.com/20981441/30109764-299b6416-933a-11e7-8a36-d33a49e9f60a.png)

What does the proposed API look like?
    can you do the same as https://ganesh-91.github.io/the same, add an isTextWrap property to the Select component to control whether the height of the display box is fixed.

![default](https://user-images.githubusercontent.com/20981441/30109800-44837110-933a-11e7-980d-2eb16f0f07f7.png)

**Comment by yesmeck** [comment]
Try `maxTagCount` in antd 3.

**Comment by Evanna51** [comment]
@yesmeck  hello, multiple select cannot use maxTagCount

**Comment by yesmeck** [comment]
@Evanna51 Create a separator issue if you think it's a bug.

**Comment by Evanna51** [comment]
我没找到这个文档的详细说明，想看看代码再发。谢谢你



发自我的小米手机
在 Wei Zhu <notifications@github.com>，2018年4月18日 22:34写道：

@Evanna51<https://github.com/Evanna51> Create a separator issue if you think it's a bug.
