### ISSUE TITLE
Validating status dosn't work on DatePicker

### ISSUE THREAD

**Issue by JozefBiros** [ant-design/ant-design#7498]
### Version
2.13.0

### Environment
Windows 10, Chrome 60.0.3112.113, react 15.6.1

### Reproduction link
[https://codepen.io/anon/pen/ayrvBV?editors=001#anon-login](https://codepen.io/anon/pen/ayrvBV?editors=001#anon-login)

### Steps to reproduce
1. Use DatePicker component wraped in componnet Form.Item.
2. Set property "validateStatus" on <Form.Item> to 'validating'.

### What is expected?
Show validating in DatePicker.

### What is actually happening?
Nothing.  
In HTML markup is missing class "has-feedback" in div with class "ant-form-item-control"

**Comment by afc163** [comment]
The feedback icon is set to FormItem other than DatePicker due to the development limit.

And default width of DatePicker is not 100% like Input does. So you have to set it to `100%` and controll the FormItem's width to a suitable value.

https://codepen.io/anon/pen/eEaJJK?editors=0010

**Comment by afc163** [comment]
There are some styling problems for other components like TimePicker, I will fix it now.
