### ISSUE TITLE
The Select component can not control the height of the display box when use select multiple feature.

### ISSUE THREAD

**Issue by lxzhangchao** [ant-design/ant-design#7499]
### Version
2.12.2

### Environment
macos

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
When you use multiple options for select components, you select a large number of data, such as 100, and the height of the display box is too high and the style is not beautiful。

### What is expected?
can you do the same as `https://ganesh-91.github.io/multi-select-react/` the same, like `3. Text Warp` ,add an isTextWrap property to the Select component to control whether the height of the display box is fixed. set css style `white-space: nowrap;`

### What is actually happening?
When you select a large number of data, the display box height will be too high

---
In Select multiple application scenarios, some business requirements may have a lot of data.we should develop this feature

**Comment by ddcat1115** [comment]
You can override the styles of Select, I suppose setting `max-height` and `overflow` can work...
