### ISSUE TITLE
关于图片上传显示缩略图

### ISSUE THREAD

**Issue by gdzgshum** [ant-design/ant-design#750]
官方的例子显示不了；
我自己测试，上传成功后，显示的是默认图而不是上传的缩略图

另外我想问问：
1、有没有上传后，只当前显示缩略图，不上传服务器，最后随其他表单内容一并上传

**Comment by afc163** [comment]
搞定了。https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

IE8/9 将不支持。

**Comment by afc163** [comment]
另外，由于官方的例子是静态网站，所以无法模拟上传过程，希望谅解。
