### ISSUE TITLE
Multiple Select - Define content to show

### ISSUE THREAD

**Issue by joshbenhamou** [ant-design/ant-design#7504]
### What problem does this feature solve?
Not all multi select dropdowns need to show the values. The current example is with a column selector for the table. There's no need to show the values for each column, the dropdown should just show "Select Columns"

### What does the proposed API look like?
`displayPlaceholderOnly` option that regardless of the values, only shows the placeholder

**Comment by ddcat1115** [comment]
Don't quite understand what you need... something like [Dropdown](https://ant.design/components/dropdown/)  ?

**Comment by joshbenhamou** [comment]
Similar to the functionality of dropdown except that you can multi-select the items. On the [select](https://ant.design/components/select/) there doesn't seem to be a way to keep the placeholder and not show the values that are currently selected?

**Comment by afc163** [comment]
You can customize dropdown for this: https://codepen.io/anon/pen/XawBRR?editors=0110

**Comment by joshbenhamou** [comment]
Thank you, that's a clever solution. It would be cool to be able to toggle this in the select component as I can see this being useful in forms but will leave it to you. Thanks again
