### ISSUE TITLE
Icon 组件使用导致热加载出现问题

### ISSUE THREAD

**Issue by WenXuanYuan** [ant-design/ant-design#751]
使用Icon组件的时候热加载出现这个错误
VM97111:50 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
不知道是不是BUG，还是我使用不当

**Comment by afc163** [comment]
没有遇到这个问题。

你可以试试 https://github.com/ant-design/antd-init ，预设了 HMR 功能，我试了是没有问题的。
