### ISSUE TITLE
InputNumber is missing onDoubleClick event

### ISSUE THREAD

**Issue by 282159468** [ant-design/ant-design#7511]
### What problem does this feature solve?
<InputNumber onDoubleClick={() => console.log(222)}/> 
it not works

### What does the proposed API look like?
recive rest props

**Comment by afc163** [comment]
Why you need this?

**Comment by 282159468** [comment]
@afc163 open modal and get value from this

**Comment by benjycui** [comment]
It's a weird UX, just add a button near InputNumber.

**Comment by 282159468** [comment]
ok,accept
