### ISSUE TITLE
增加配置项，允许鼠标经过时停止duration计时,鼠标移出后恢复计时

### ISSUE THREAD

**Issue by HeZiGang** [ant-design/ant-design#7513]
### What problem does this feature solve?
如果Notification比较长，用户需要仔细查看其内容，就可以在它自动关闭以前将鼠标移动到它上面。使其不会自动关闭。

### What does the proposed API look like?
增加一个bool值的config节点, 允许用户选择是否启用这个功能。

**Comment by benjycui** [comment]
有道理，可以 PR 到 rc-notification?

**Comment by afc163** [comment]
👍 It is useful.

**Comment by HeZiGang** [comment]
我提交到那边去了， 希望他能读懂我蹩脚的英文
https://github.com/react-component/notification/issues/25

**Comment by afc163** [comment]
你可以直接 PR 过去，那边也是我们在维护。

**Comment by HeZiGang** [comment]
这还是我第一次在github上面提PR，不知道怎么直接PR过去。另外，我下载了rc-notification的代码，增加了一个名为freezeWhenMouseOver的属性，实现了这个功能，但是不知道怎么把代码贡献给你们。-_-||，加上simple.js总共改了3个文件，贴代码好像也不对。

**Comment by afc163** [comment]
学习一下：https://www.zhihu.com/question/21682976

**Comment by benjycui** [comment]
> 增加了一个名为freezeWhenMouseOver的属性

其实我觉得可以不加属性，直接默认行为即可。

**Comment by HeZiGang** [comment]
@afc163 谢谢，学习一下，晚上回家试试，公司不能用Git客户端
@benjycui 好的

**Comment by HeZiGang** [comment]
@afc163 之前忘了修改邮箱了，所以那个PR我是匿名提交的，现在我增加了测试用例，把code coverage增加到了100，是不是需要关闭之前那个PR，然后PR过去。

**Comment by afc163** [comment]
不用，直接在那个分支上继续 push 就好。

**Comment by afc163** [comment]
Thx to @HeZiGang

**Comment by HeZiGang** [comment]
It's OK, 如果需要帮忙fix bug或者加什么功能什么的，也可以@我，我晚上和周末都满闲的，我也想做点力所能及的贡献，不能老是白用大家贡献的代码。😁

**Comment by afc163** [comment]
There is a lot of issues need to do: https://github.com/ant-design/ant-design/issues?q=is%3Aopen+is%3Aissue+label%3A%22PR+welcome%22
