### ISSUE TITLE
在展开Submenu的情况下折叠菜单，无法正常显示

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#7514]
### Version
2.13.0

### Environment
win10

### Reproduction link
[https://codepen.io/anon/pen/NvZwEP?editors=0011](https://codepen.io/anon/pen/NvZwEP?editors=0011)

### Steps to reproduce
1.展开Submenu
2.点击折叠按钮。

### What is expected?
立刻进入内嵌模式

### What is actually happening?
仍保持水平模式，并且可以展开其他Submenu

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/e9a592a9c85d45ccd1d18417c99bc500ca7e56da Thx all the same!

**Comment by Kunoky** [comment]
I tried the revision you said, but unfortunately the result has not changed！

![56q_1bpz7_5f_m e p uj0](https://user-images.githubusercontent.com/26639880/30198599-18888a24-94a1-11e7-8a91-d24b06ecbafe.png)
![qq 20170908141509](https://user-images.githubusercontent.com/26639880/30198610-2609f1ce-94a1-11e7-8708-4c58503b5ce0.png)
