### ISSUE TITLE
嵌套子表格能否默认每次只能打开一个

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#7517]
### What problem does this feature solve?
如果，子表格下的数据是通过获取另一个接口拿到的，而不是和主表格数据接口一起返回的，那么每次点击子表格展开按妞去获取数据，期望其它子表格关闭，不然通过state来控制的话每个子表格的数据是一致的，造成歧义。

### What does the proposed API look like?
支持各种情况

**Comment by afc163** [comment]
Control it by `expandedRowKeys`.
