### ISSUE TITLE
穿梭框，  react-lazy-load 懒加载， 能不能不要这个 懒加载，或者加个 disabled 的功能。

### ISSUE THREAD

**Issue by Yaids** [ant-design/ant-design#7520]
### What problem does this feature solve?
不需要 懒加载的 时候可以 去掉， 不会立即显示出来也是一个比较头疼的问题呢。

### What does the proposed API look like?
lazy={{
   disabled: true
}}

**Comment by afc163** [comment]
You can use `lazy={false}` to turn it off. I will document it.
