### ISSUE TITLE
The default loading feel design in antd is not too friendly

### ISSUE THREAD

**Issue by leesx** [ant-design/ant-design#7521]
### Version
2.13.0

### Environment
win

### Reproduction link
[http://ant.design](http://ant.design)

### Steps to reproduce
This is not a functional bug, I hope antd in the loading design can be more friendly

### What is expected?
This is not a functional bug, I hope antd in the loading design can be more friendly。loading is slow

### What is actually happening?
loading is not better

**Comment by afc163** [comment]
I think this is a ambiguous request.

**Comment by afc163** [comment]
And we will redesign `Spin` UI in antd 3.0
