### ISSUE TITLE
请问2.13.0版本中的主色修改预览功能是如何实现的？

### ISSUE THREAD

**Issue by spiroo** [ant-design/ant-design#7523]
### What problem does this feature solve?
一直想要实现的类似动态换肤功能，而不仅仅是定制。

### What does the proposed API look like?
好像未来3.0版本要提供ThemeProvider？
不知道是不是能实现类似动态换肤的功能

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/7401
