### ISSUE TITLE
在展开Submenu的情况下折叠菜单，无法正常显示

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#7524]
### Version
2.13.0

### Environment
win10

### Reproduction link
[https://codepen.io/anon/pen/NvZwEP?editors=0011](https://codepen.io/anon/pen/NvZwEP?editors=0011)

### Steps to reproduce
1.展开Submenu
2.点击折叠按钮。

### What is expected?
立刻进入内嵌模式

### What is actually happening?
仍保持水平模式，并且可以展开其他Submenu

---
I tried the revision pianyou said, but unfortunately the result has not changed！

  key: 'getRealMenuMode',
        value: function getRealMenuMode() {
            var inlineCollapsed = this.getInlineCollapsed();
            // if (this.switchModeFromInline && inlineCollapsed && !('openKeys' in this.props)) {
            if (this.switchModeFromInline && inlineCollapsed) {
                return 'inline';
            }
            var mode = this.props.mode;

            return inlineCollapsed ? 'vertical' : mode;
        }

**Comment by afc163** [comment]
Sorry for my levity.

**Comment by Kunoky** [comment]
So when will the problem be solved?
