### ISSUE TITLE
Select与TreeSelect的联动调用，TreeSelect改变treeData，显示出错

### ISSUE THREAD

**Issue by pin006** [ant-design/ant-design#7526]
### Version
2.13.0

### Environment
macOs10.12.9   谷歌浏览器版本 60.0.3112.113，react

### Reproduction link
[https://github.com/pin006/antDesignExample.git](https://github.com/pin006/antDesignExample.git)

### Steps to reproduce
说明：Select 与 TreeSelect组成一个联动效果，Select的change会发送请求，返回数据作为TreeSelect的值；
重现：第一步：在Select中选取有返回值不为空的option，选取TreeSelect中的某一值
第二步：在Select中选取有返回值为空数组的option，TreeSelect获取到了空数组，页面上却显示了一条仅一条上一步操作选中的数据

### What is expected?
第二次选取返回值为空的选项时，TreeSelect应该也为空。

### What is actually happening?
TreeSelect显示了上一次被选中的选项

step 1:
checkd the Select
![image](https://user-images.githubusercontent.com/22445111/30212140-34bfa5a2-9469-11e7-9d4f-a14ca41a68c1.png)

step2:checked the TreeSelect Option
![image](https://user-images.githubusercontent.com/22445111/30212160-520f30b4-9469-11e7-9e56-8f6e9a2568e5.png)

step3:
checkd the Select option that don't have data for TreeSelect:
![image](https://user-images.githubusercontent.com/22445111/30212208-85ff1768-9469-11e7-8a3e-8d79578c5037.png)
the TreeSelect value is step2's value

**Comment by nikogu** [comment]
you can clean the preview value by manual ?

**Comment by pin006** [comment]
@nikogu  I can reset the value，but the selected value is the last clicked.
Demo :
step 1.the init value is :
 this.state = {
            treeData: [{
                    label: "Node2",
                    value: "2-1",
                    key: "2-1"
                },
                {
                    label: "Node1",
                    value: "1-1",
                    key: "1-1"
                }
            ]
        };
step 2.I seleted one option
step 3.I reset the state value is like this:
this.setState({
            treeData:  [{
                label: "Node3",
                value: "3-1",
                key: "3-1"
            }]
        });
But, the selected value is the step 2 clicked.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by pin006** [comment]
the code like this:
 import { TreeSelect } from "antd";

export default class TreeSelectChangeVal extends React.Component {
    constructor() {
        super();
        this.state = {
            treeData: [
                {
                    label: "Node2",
                    value: "2-1",
                    key: "2-1"
                },
                {
                    label: "Node1",
                    value: "1-1",
                    key: "1-1"
                }
            ]
        };
    }

    handleChangeTreeValue() {
        let _newArray = [
            {
                label: "2",
                value: "2",
                key: "2"
            }
        ];
        this.setState({
            treeData: _newArray
        });
    }

    render() {
        return (
            <div>
                <TreeSelect
                    style={{
                        width: 300
                    }}
                    dropdownStyle={{
                        maxHeight: 400,
                        overflow: "auto"
                    }}
                    treeData={this.state.treeData}
                    placeholder="Please select"
                    allowClear
                    treeDefaultExpandAll
                />
                <button
                    type="button"
                    onClick={this.handleChangeTreeValue.bind(this)}
                >
                    改变treeSelect的值
                </button>
            </div>
        );
    }
}
ReactDOM.render(<TreeSelectChangeVal />, document.getElementById("root"));

**Comment by benjycui** [comment]
> Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close for no response.
