### ISSUE TITLE
Steps component - Expose vertical label placement from rc-steps

### ISSUE THREAD

**Issue by EduardoAC** [ant-design/ant-design#7528]
### What problem does this feature solve?
Introduce vertical label placement will allow to do more fluent steps using the extra capabilities of rc-steps.

### What does the proposed API look like?
labelPlacement: [ 'vertical', 'horizontal']
```
export interface StepsProps {
  prefixCls?: string;
  iconPrefix?: string;
  current?: number;
  status?: 'wait' | 'process' | 'finish' | 'error';
  size?: 'default' | 'small';
  direction?: 'horizontal' | 'vertical';
  progressDot?: boolean | Function;
  labelPlacement?: 'vertical' | 'horizontal';
}
```

**Comment by afc163** [comment]
Nope, it is not fit Ant Design Design spec. You can use `rc-step`.
