### ISSUE TITLE
AutoComplete控件应该去除 onChange 接口，增加 onClear 接口

### ISSUE THREAD

**Issue by jzoe** [ant-design/ant-design#7533]
### What problem does this feature solve?
在实际使用中，我认为 AutoComplete 一般需要触发3种事件：一个是在输入关键字时触发 onSearch 进行搜索；二是在选择搜索结果下拉框中的选项时触发 onSelect；三是在 allowClear={true} 时，触发重置搜索框。

例如，我在一个高级搜索 form 中使用 `getFieldDecorator` 来装饰这个 AutoComplete 控件，我在 `onSelect` 中触发一次 form 表单的提交，现在我需要在 clear 后再次提交form表单就不好设计了！

目前没有 onClear 接口，只有 onChange 接口 ，onChange 接口的功能完全可以被 onSelect 和 onSearch 取代，但是缺了 onClear 接口。

如果我将 clear 清除事件放在 onChange 中来调用的话，会在输入关键字的时候，每输入一个字符就触发一次 form 表单提交，显然这不是我们想要的！ **我想更多用户需要的是在输入时执行 onSearch, 选择搜索结果下拉的条目时提交表单，在clear内容时再次提交表单。**

### What does the proposed API look like?
```
<AutoComplete allowClear={true} onClear={onSubmit}>
```

**Comment by afc163** [comment]
> 在清楚内容时提交表单

It is a weired UX. I don't think we should support it.

**Comment by jzoe** [comment]
I design a search form like this:

![image](https://user-images.githubusercontent.com/11612990/30237780-9577bdc8-956b-11e7-9255-c0fd22e0a03a.png)

If there is no `onClear` interface, I have to force the user to click the search button after user clear the text!

In such case, user need took two step to reset the search, but I think it could be done with one step by the `onClear` API !

**Comment by afc163** [comment]
I see what you need, `allowClear` is a bad interface for AutoComplete which is extended from Select. Let me check what can I do.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/QMeNVV?editors=0011

**Comment by jzoe** [comment]
I have been try it! This is my component:

```js
import React from 'react'
import PropTypes from 'prop-types'
import { AutoComplete } from 'antd';

class Complete extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: props.value,
      dataSource: [],
    };
  }


  handleSearch = (value) => {
    this.setState({value})
    this.props.fetch(value, dataSource => this.setState({ dataSource }));
  }

  // handleChange = (value) => {
  //   this.setState({value})
  // }
  render() {
    const { dataSource, value } = this.state
    const { placeholder, size, styles, onChange } = this.props
    return (
      <AutoComplete
        size={size}
        dataSource={dataSource}
        style={styles}
        value={value}
        onSelect={onChange}
        onSearch={this.handleSearch}
        placeholder={placeholder}
        allowClear={true}
        backfill={true}
      />
    );
  }
}

Complete.propTypes = {
  value: PropTypes.string,
  onChange: PropTypes.func,

  fetch: PropTypes.func,
  size: PropTypes.string,
  styles: PropTypes.object,
  placeholder: PropTypes.string,
} 

export default Complete

```

And in my search form, I use it like this:

```js
           <div>
              {getFieldDecorator('devName', {initialValue: devName})(
                <Complete size="default" placeholder="开发者姓名" styles={{width: '100%'}} fetch={fetchProduct} onChange={handleChange.bind(null, 'devName')}/>
              )}
            </div>
```

**Comment by afc163** [comment]
Check my codepen for the below part:

```jsx
  onChange(value) {
    if (!value && typeof value !== 'string') {
      console.log('trigger onClear');
    }
  }
```

**Comment by jzoe** [comment]
@afc163  Orz !

It works perfect ! Thanks for your help！

**Comment by afc163** [comment]
I gonne close this one until more request for `onClear`.

**Comment by jzoe** [comment]
OK! Thanks again!
