### ISSUE TITLE
Time picker position off on Modal with animation

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7546]
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/ryj98no4xn

### Steps to reproduce
Run the above link

### What is expected?
It should be positioned like https://i.imgur.com/YTdF8rT.png (this is with animation={false} on the modal)

### What is actually happening?
https://i.imgur.com/0r1aULs.png
the input box is overlapping

**Comment by afc163** [comment]
Your screen capture picture seems to be rc-time-picker but antd's TimePicker, so you should report it in github.com/react-component/time-picker/issues
