### ISSUE TITLE
Time picker position off on Modal with animation

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7548]
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/q387pzjrj6

### Steps to reproduce
Run the above link

### What is expected?
It should be positioned like https://i.imgur.com/kVXKGS1.png (this is with animation={false} on the modal)

### What is actually happening?
https://i.imgur.com/Zl4KHQI.png
the input box is overlapping (will be repositioned when a time is selected)

**Comment by afc163** [comment]
Because bootstrap's Modal has a appear animation from up to down. That affects the position of TimePicker. I suggest:

- Use antd's Modal.
- Or show TimePicker after bootstrap's Modal is shown completely.
