### ISSUE TITLE
文件上传组件的顺序控制 | To change order in Upload Component

### ISSUE THREAD

**Issue by Alexorz** [ant-design/ant-design#7549]
### What problem does this feature solve?
To change the order of images in Upload Component, when the images need to be displayed in sequence.

### What does the proposed API look like?
1. Add 'Left' and 'Right' arrow icons buttons under the 'preview' and 'delete' button, in 'PicturesWall' mode.
2. After click 'Left' and 'Right' button, the images switch order, and the 'onChange' function be triggered.
3. Sometimes we need to show images vertically, so the icons of these two buttons need to be customized (change to 'Up' and 'Down' arrow icons).

**Comment by afc163** [comment]
You could write your owner UploadList instead of using default one.
