### ISSUE TITLE
TimePicker not displaying correctly on Modal

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7550]
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/q387pzjrj6

### Steps to reproduce
1. Click Open
2. Click Confirm (Blue button)
3. Click Open again

### What is expected?
Time picker should be open on step 3 (same as step 1)

### What is actually happening?
Time picker will not show on the second time u click open (it's hidden somewhere probably)

**Comment by nikogu** [comment]
@James2516 i think it's when the `component update`, `TimePicker` is not re-update position.

you can try this, until fixed this problem:

```jsx
class Meeting extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      show: false,
    };
  }
  render() {
    const ModalGen = () => <Modal
      visible={this.state.show}
      title="Some title"
      onCancel={() => this.setState({ show: false })}
      onOk={() => {
        this.props.createMeeting({
          startTime: moment(),
          duration: moment.duration(10, 'm'),
          title: 'asd'.trim(),
        });

        this.setState({ show: false });
      }}
    >
      <MeetingCreator />
    </Modal>;

    return (
      <div>
        <Button
          onClick={() => this.setState({ show: true })}
        >
          Open
        </Button>
        <ModalGen />
      </div>
    );
  }
}
```

**Comment by James2516** [comment]
My MeetingCreator dispatch an action to set the time to the current time in `componentWillMount`, so the above solution causes `componentWillMount` to be called repeatedly, resulting in an infinite loop.

**Comment by benjycui** [comment]
@James2516 make `TimePicker[open]` follow `Modal[visible]`.

It's not easy to make TimePicker detect that its ancestor's visibility had been change, so, you need to tell it.
