### ISSUE TITLE
TimePicker overlapping with other components on modal

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7551]
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/81pp9wo8lj

### Steps to reproduce
Run the above and resize the window

### What is expected?
It should overflow to next line instead of hiding the text at any point.

### What is actually happening?
https://i.imgur.com/BCVwHfH.png
it overlaps with the text

**Comment by afc163** [comment]
It is by designed.
