### ISSUE TITLE
There are some problems in RangePicker,the time  is 12:00:00 When the selection time is 00:00:00

### ISSUE THREAD

**Issue by ShadowNight001** [ant-design/ant-design#7554]
### Version
2.13.0

### Environment
google chrome版本 60.0.3112.113 ;windows7

### Reproduction link
[https://codepen.io/ShadowNight001/pen/WEVqEm](https://codepen.io/ShadowNight001/pen/WEVqEm)

### Steps to reproduce
click the Select time in RangePicker and select time 00:00:00,then you`ll see the time is actually 12:00:00

### What is expected?
The expected time is 00:00:00

### What is actually happening?
The actual is 12:00:00

**Comment by nikogu** [comment]
@ShadowNight001  change `hh:mm:ss` to `HH:mm:ss`

and take a look at https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges
