### ISSUE TITLE
表格固定操作列，数据为空，且列设置为编辑，显示不正常

### ISSUE THREAD

**Issue by yuanjiahui** [ant-design/ant-design#7555]
### Version
2.13.1

### Environment
Win10、Google Chrome  版本 61.0.3163.79（正式版本） （64 位）

### Reproduction link
[https://codepen.io/yuanjiahui/pen/vJoqOZ](https://codepen.io/yuanjiahui/pen/vJoqOZ)

### Steps to reproduce
表格固定操作列，数据为空，且列设置为编辑，显示不正常

![20170911113839](https://user-images.githubusercontent.com/5235098/30257624-023bf7aa-96e6-11e7-9dae-81705fc1908a.png)

### What is expected?
隐藏编辑的单元格

### What is actually happening?
编辑单元格没有隐藏

**Comment by afc163** [comment]
Thx for reporting
