### ISSUE TITLE
Cannot access the website of https://ant.design

### ISSUE THREAD

**Issue by sirius1024** [ant-design/ant-design#7558]
### Version
2.13.1

### Environment
Chrome/Safari/Mobile Phone with 4G

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
Access the url

### What is expected?
I wanna to checkout the docs of ant design

### What is actually happening?
ERR_CONNECTION_CLOSED

**Comment by guojindai** [comment]
me too too too

**Comment by ddcat1115** [comment]
It's ok now, sorry for that 😅

**Comment by BjornVanWettere** [comment]
I'm having the same thing happen to me for at least a week already ..
