### ISSUE TITLE
npm run dev 快速上手，发现date-picker无法找到

### ISSUE THREAD

**Issue by justnull** [ant-design/ant-design#756]
**问题描述**

（描述一下问题）

**发生环境**

- antd 版本："antd": "0.10.x",
- 操作系统及版本：win7 64位
- 浏览器及版本：chrome
- 在线演示地址：

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://jsfiddle.net/yiminghe/9zrstuto/1/

ERROR in ./src/component/App.jsx
Module not found: Error: Cannot resolve module 'antd/lib/date-picker' in e:\lear
nJs\react\antd-demo\src\component
 @ ./src/component/App.jsx 7:18-49

**Comment by benjycui** [comment]
先确认你的 antd 版本，如果是 0.10.x 则用 `Date**p**icker`，0.11.x 则用 `Date**P**icker`。

请再三确认你的版本。
