### ISSUE TITLE
tree组件中的某一个treeNode的key值为1-0,但选中此节点的时候打印出来的key值却是.$1-0，多了一个.$，父元素选中的时候就不会出现这种情况

### ISSUE THREAD

**Issue by xiaojielade** [ant-design/ant-design#7560]
tree组件中的某一个treeNode的key值为1-0,但选中此节点的时候打印出来的key值却是.$1-0，多了一个.$，父元素选中的时候就不会出现这种情况

![image](https://user-images.githubusercontent.com/13671911/30270218-5b5df01c-971e-11e7-8674-18e9f4a1e926.png)

![image](https://user-images.githubusercontent.com/13671911/30270267-8356f4ec-971e-11e7-9aab-928d6acefd0b.png)

**Comment by benjycui** [comment]
Please learn React first.

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by NE-SmallTown** [comment]
This is the default behavior of React.
