### ISSUE TITLE
Form validation status is not synchronized

### ISSUE THREAD

**Issue by zuimeiaj** [ant-design/ant-design#7563]
### Version
2.13.1

### Environment
osx 10.12 、chrome 60 、 react 15.6

### Reproduction link
[https://jsfiddle.net/zuimeiaj/70L1xjxd/5/](https://jsfiddle.net/zuimeiaj/70L1xjxd/5/)

### Steps to reproduce
step1：click submit button
step2：click toggle button

### What is expected?
When clicking the toggle button, the error message should not be displayed

### What is actually happening?
The error message always exists

**Comment by nikogu** [comment]
https://ant.design/components/form/#this.props.form.getFieldDecorator(id,-options)

> After wrapped by getFieldDecorator, value(or other property defined by valuePropName) onChange(or other property defined by trigger) props will be added to form controls，the flow of form data will be handled by Form

i suggest your can set different form `key` like : `name1` & `name2`

**Comment by benjycui** [comment]
Form will not re-validate fields when you change rules.
