### ISSUE TITLE
ant-tabs-ink-bar widths unusual

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#7564]
### Version
2.13.1

### Environment
mac chrome

### Reproduction link
[https://github.com/yangbin1994/cow/tree/tabs-bug](https://github.com/yangbin1994/cow/tree/tabs-bug)

### Steps to reproduce
1: 进入http://xxx:8000/media/weibo/123，会发现tab下面的link宽度异常
2: 在src/index.js或者src/route/app.js等非异步加载的页面，写上
import { Tabs, } from 'antd'
const TabPane = Tabs.TabPane
再次查看，发现宽度正常

### What is expected?
不用加不必要的依赖

### What is actually happening?
要在非按需加载的地方写上不必要的依赖

**Comment by yangbin1994** [comment]
[
      "import", {
        "libraryName": "antd",
        "style": true
      }
    ]

**Comment by afc163** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/507615/30312985-5e1aa830-97ce-11e7-8eec-912ff16a352e.png">

It does'nt make sense.

**Comment by yangbin1994** [comment]
> 2: 在src/index.js或者src/route/app.js等非异步加载的页面，写上
import { Tabs, } from 'antd'
const TabPane = Tabs.TabPane

目标：省略这个步骤
Goal: omit this step

**Comment by nikogu** [comment]
@yangbin1994  show a demo（codepen?）

**Comment by afc163** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/507615/30333014-72553e2e-980e-11e7-9384-1f5c4d467a4f.png">

https://github.com/ant-design/test/issues/48#issuecomment-322661311

像是这个问题。@nikogu

**Comment by nikogu** [comment]
@yangbin1994 你给的项目并未重现，写个 codepen 吧

**Comment by afc163** [comment]
@nikogu 只有本地开发时使用 style-loader 时才能重现。

**Comment by nikogu** [comment]
@yangbing1994 项目貌似有很多问题，页面都是 404，你截个图好了

![image](https://user-images.githubusercontent.com/1179603/30473484-34e72756-9a33-11e7-8cd6-9267730aaafd.png)

@afc163 你重现了吗 ＝。-

**Comment by afc163** [comment]
在 test2 里很容易重现。

**Comment by nikogu** [comment]
@afc163 额，不一定是一个问题。。。。看他描述好像不是。。。 test2 那个我还在看。。

**Comment by afc163** [comment]
@yangbin1994 麻烦给个傻瓜式的必现步骤和截图。

**Comment by yangbin1994** [comment]
@afc163 @nikogu 原git地址，我将一些不相关的文件都删除了，拉下来，访问8000就可以重现。
![image](https://user-images.githubusercontent.com/12080165/30493535-046e6226-9a77-11e7-8a74-f89ecd2ce052.png)

**Comment by benjycui** [comment]
CSS 加载在 JS 执行之后，导致计算错误。

Ref: https://github.com/ant-tool/atool-doc/issues/40

**Comment by afc163** [comment]
Fixed in rc-tabs@9.1.5

**Comment by afc163** [comment]
Need find another solution.

**Comment by cuitianze** [comment]
下划线可以设置宽度么？
ant-design-mobile的tabs宽度可以不等分么

**Comment by hyongzheng** [comment]
现在这个问题解决了吗，为什么我也出现了没有下划线的问题
