### ISSUE TITLE
Can I scroll through the Table page by dragging Table's record?

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#7566]
### What problem does this feature solve?
When a Table page shows a large amount of data and the field, the horizontal scroll bar at the bottom, so that when I want to see other fields in the middle of a data， need to specifically look for the scroll bar, and then come back to see us data, already did not know where it is.

### What does the proposed API look like?
scroll={
x:1000,
y:1000,
drag:true
}

**Comment by afc163** [comment]
I don't think we should modify default behavious of scroll view.

**Comment by Durisvk** [comment]
@afc163 this is becoming a problem on Tables with fixed columns (https://ant.design/components/table/#components-table-demo-fixed-columns) for users with external mouse devices and results in terrible UX (dragging with the middle mouse button doesn't work and the only option is to drag the small scrollbar at the bottom).

With native touchpads, the component works perfectly but that's probably not satisfactory.
A potential solution to this problem might include involving library like https://www.npmjs.com/package/react-indiana-drag-scroll

Would you mind reconsidering putting this feature on the roadmap?
