### ISSUE TITLE
Select组件的多选框，能否定义选中的字体颜色？

### ISSUE THREAD

**Issue by tanrenjie** [ant-design/ant-design#7568]
![20170912154027](https://user-images.githubusercontent.com/23740685/30313828-4a7eaf9e-97d1-11e7-875a-3750321f93e0.png)

**Comment by nikogu** [comment]
@tanrenjie try https://ant.design/docs/react/customize-theme-cn 

and if can not solve your problem, u can cover the select style by your stylesheet.
