### ISSUE TITLE
menu 组件有一个错误

### ISSUE THREAD

**Issue by 499190982** [ant-design/ant-design#7571]
### Version
2.13.1

### Environment
不限

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
 menu组件的  onselect 不调用

### What is expected?
 menu组件的  onselect 被调用

### What is actually happening?
 menu组件的  onselect 不调用

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by 499190982** [comment]
The menu component has a bug and the onSelect event does not perform a callback

**Comment by afc163** [comment]
Please follow the issue template and provide useful imformation like a reproducible codepen.

https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html

**Comment by 499190982** [comment]
Sorry, this is I met this bug when package online, online to work properly, to keep the code has been rolled back, now I put the antd rollback to 2.12.8, onSelect just normal, temporary no can observe the network environment

**Comment by afc163** [comment]
Help us to reproduce it or nothing we can do, even we want to.

**Comment by 499190982** [comment]
onSelectTag = (select) => {
    const tagId = parseInt(select.key, 10)
    const { group } = this.props
    console.log('onselect')
    this.props.dispatch({
      type: 'setting_tags/setSessionTag',
      payload: { tagId, group },
    })
  }
  getTagsDropDown () {
    let tagList = [{ id: -1, name: '无标签' }, ...this.props.tagList]
    let group = this.props.group
    let selectedTag = (group.c.tags && group.c.tags[0] !== undefined) ? group.c.tags[0] : -1
    return (
      <Menu className="m-custom-select-menu" onSelect={this.onSelectTag} selectedKeys={[`${selectedTag}`]}>
        {tagList.map((tag) => {
          return <Menu.Item className="m-custom-select-menu-item" key={tag.id}>{tag.name}</Menu.Item>
        })}
      </Menu>
    )
  }

This is my code, you can install the latest version and try it

**Comment by afc163** [comment]
Help us to reproduce it and don't paste unformatted code.

**Comment by afc163** [comment]
I will reopen it until it can be reproduced.
