### ISSUE TITLE
checke the TreeNode, the printed key value is different from the key value setted,there is '.$' added automatically in the front of the setted key

### ISSUE THREAD

**Issue by xiaojielade** [ant-design/ant-design#7575]
antd version: 2.7.4
mac chrome browser

if i set TreeNode component key as 1-0 and checkabled is true, when i checked the box, it will print '.$1-0', not '1-0'.

i dont know what happen, it's just an example copy from demo code at 
https://ant.design/components/tree-cn/

![image](https://user-images.githubusercontent.com/13671911/30359209-bbdc0dc6-987b-11e7-99d4-2d9a25cd1680.png)

![image](https://user-images.githubusercontent.com/13671911/30359147-602e605a-987b-11e7-96ed-7db86374af6d.png)

**Comment by afc163** [comment]
It works in https://ant.design/components/tree-cn/#components-tree-demo-basic

**Comment by xiaojielade** [comment]
@afc163   i have upgrade the antd to the latest version, and the error still exists, now i can not figure out the reason, so i want to seek help here.

**Comment by afc163** [comment]
Please provide a reproducible demo.

**Comment by benjycui** [comment]
It's the default behavior of React, please learn react first, thanks.

**Comment by afc163** [comment]
> It's the default behavior of React

It is not.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by xiaojielade** [comment]
@benjycui  @afc163   i have found out where the error results from,  the component i wrote includes Tree component,  and i use this way to export this component for using in other place(the name of component i wrote is Show): 
 export default CSSModules(Show, styles); 
 in this way,  when i check the TreeNode, there is '.$' added automatically in the front of the key i setted, 
however, when i change the exporting way of the component to following, the key value is identical from the key i setted, everything is correct:
export default Show;

but in this way, i must put the css file of Show component into the global css file, now i have no better ways to solve this problem to complete my work, and was forced to use this way temporarily.
I have no idea why the CSSModules influences the key value, and i hope somebody can tell me the reason, i will appreciate any feedback;thks

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1068
https://github.com/ant-design/ant-design/issues/573
