### ISSUE TITLE
Ability to replace default icons with FontAwesome icons

### ISSUE THREAD

**Issue by pruhstal** [ant-design/ant-design#7576]
### What problem does this feature solve?
I'd like to know if it's possible (or have been attempted, already), to replace all default icons with my own icons (using them from FontAwesome). 

I really like the icons provided out of the box from ant, but FontAwesome has more options and a little different styling on things like stars that I prefer.

### What does the proposed API look like?
```
<Icon type="custom-star" />
```

or even using the original names:

```
<Icon type="star" />
```

**Comment by afc163** [comment]
Just use https://github.com/andreypopp/react-fa
