### ISSUE TITLE
table中的width属性不起作用

### ISSUE THREAD

**Issue by xiaosunJessica** [ant-design/ant-design#7581]
### Version
2.13.1

### Environment
win10

### Reproduction link
https://codepen.io/jessica_sun/pen/pWoQXX?editors=001

### Steps to reproduce
设置width,列表宽度不变

### What is expected?
设置width=10%0,该列为10%的宽度

### What is actually happening?
结果没有任何变化

**Comment by afc163** [comment]
👎 

Your codepen do not contain any relevant code.

**Comment by xiaosunJessica** [comment]
I have change the codepen  link , now you can open it

**Comment by nikogu** [comment]
@xiaosunJessica your codepen shown it's ok

**Comment by xiaosunJessica** [comment]
it's my mistake, I found I have add some css style, so the width property cannot work

**Comment by afc163** [comment]
You can close this issue.
