### ISSUE TITLE
[Tree] add support for disabling auto expand when drag

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#7583]
### What problem does this feature solve?
need a way to disable auto expand when drag

### What does the proposed API look like?
add a prop like autoExpandWhenDrag or call onExpand when need to expand instead of change expandedKeys directly.

**Comment by benjycui** [comment]
Why? It is part of the UX, and if Tree doesn't expand automatically, it is inconvenient to drop nodes under nested nodes.

**Comment by Frezc** [comment]
It's just a optional prop. For reason, sometime I don't want to drag nodes to nested nodes.
If you think it inconsistent with design, please close this issue.

**Comment by nikogu** [comment]
@Frezc it a UX standardization.

**Comment by zdJOJO** [comment]
@Frezc  Have you found a solution?

**Comment by wangchaoduo** [comment]
@Frezc have you found a solution?

**Comment by Frezc** [comment]
@wangchaoduo 没，根据业务自己写了

**Comment by jaddoescad** [comment]
anyone?
