### ISSUE TITLE
Enable customization of Collapse arrow

### ISSUE THREAD

**Issue by davidhatten** [ant-design/ant-design#7587]
### What problem does this feature solve?
When I have a Collapse.Panel header as a react object that has some alignment, things can look kinda gross. For example, I have a header which is an avatar with some text next to it. I've aligned it all vertically in the middle, but it doesn't look nice next to the top-aligned arrow of the Panel.

I want to be able to vertically align the arrow, or disable it completely. In the case of disabling the arrow, I'd like the contents of the header to justify left to occupy the missing space.

### What does the proposed API look like?
Two new props on Collapse.Panel could do it:

* arrow-align: `top | middle | bottom` (defaults to `top` to preserve current styling)
* arrow-disabled: `true | false` (defaults to `false`)

**Comment by afc163** [comment]
I change the default vertical-align to top, and you can change default look of Collapse by overriding the styles.

**Comment by sammarSayed** [comment]
I am facing the same problem, can't override the svg-arrow `top: 50%` property, any new updates on this issue  ?
