### ISSUE TITLE
使用mapPropsToFields，想把redux异步获得的指绑定到form上初始化数据，出现uncaught at _callee TypeError: Cannot read property 'xxx' of undefined

### ISSUE THREAD

**Issue by PerkinJ** [ant-design/ant-design#7589]
如题，使用redux异步获取到了数据，componentWillReceiveProps不能setFiledValue,所有只能在mapPropsToFields赋值，可以却一直出现uncaught at _callee TypeError: Cannot read property 'xxx' of undefined。由于表单填写内容较多，我是通过三个表单组件都创建了form，最后在容器层，去合并数据再submit的。 每个表单组件都单独form.create的。请问是因为这个原因，导致出现uncaught at _callee TypeError: Cannot read property 'xxx' of undefined吗？但console.log(props)，是可以打印出来数据的。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
ping~ @PerkinJ

**Comment by benjycui** [comment]
Close for no response.
