### ISSUE TITLE
Closable is not working on Modal.success, Modal.info, Modal.error and Modal.warning

### ISSUE THREAD

**Issue by bbolek** [ant-design/ant-design#7597]
### Version
2.13.1

### Environment
Windows 10, Chrome 60.0.3 React 15.6.1

### Reproduction link
[https://codepen.io/anon/pen/GMgxYE?editors=0011](https://codepen.io/anon/pen/GMgxYE?editors=0011)

### Steps to reproduce
Create a modal with Modal.error({
                title: 'Error',
                content: message,
                closable : true
              });

### What is expected?
Close button must be visible and clickable on top right..

### What is actually happening?
No click button is visible

**Comment by afc163** [comment]
It is by designed, if you want customized dialog, try Modal.

**Comment by hustcer** [comment]
@afc163 I know it's by designed, but I hope closable works for Modal.success, Modal.info, Modal.error and Modal.warning, because these method are very convenient and lightweight, while using modal I have to maintain the modal visible status, which is too heavy.
