### ISSUE TITLE
Using TreeSelect  onChange props and click a same tree node,  the onChange function arguments is changed to be undefined.

### ISSUE THREAD

**Issue by Youhandan** [ant-design/ant-design#7599]
### Version
2.12.5

### Environment
mac, chrome

### Reproduction link
[https://codepen.io/anon/pen/gGbKGY?editors=0011](https://codepen.io/anon/pen/gGbKGY?editors=0011)

### Steps to reproduce
Open console, and click Node 1,  and click it once more.

### What is expected?
1. Return the same value.
Or
2. do not return.

### What is actually happening?
return  undefined.

**Comment by Youhandan** [comment]
I can not call back it for other use.

**Comment by nikogu** [comment]
@Youhandan value means currentValue, where you click same node again, you change currentValue to undefined

**Comment by Youhandan** [comment]
It's hard to say that I even can not get the function arguments, not just value.

**Comment by Youhandan** [comment]
Thanks. it works, but i still think it's confused between onSelect and onChange.

**Comment by nikogu** [comment]
onSelect: select a treeNode

onChange: selected treeNodes or input value chang
