### ISSUE TITLE
Provide callback process when typed invalid page number

### ISSUE THREAD

**Issue by yurong111** [ant-design/ant-design#7602]
### What problem does this feature solve?
onChange event will be invoked when changed the page successful, but will not when input invalid string, so I hope you  can provide callback function of error, then I can use it when error occurs, like warning invalid string have been input, so that users will know more clear what they should input

### What does the proposed API look like?
```
const { Pagination } = antd;

function onChange(pageNumber) {
  console.log('Page: ', pageNumber);
}

function onErrorCallback(value) {
  conaole.loe('invalid string', value)
}

ReactDOM.render(
  <Pagination showQuickJumper defaultCurrent={2} total={500} onChange={onChange} errorCallback={onErrorCallback}/>,
  mountNode
);
```

**Comment by afc163** [comment]
I suggest to customize your goto input like this demo: https://github.com/ant-design/ant-design/issues/7328#issuecomment-324875233
