### ISSUE TITLE
Table header and content are misaligned when using scroll.y and columns without width property

### ISSUE THREAD

**Issue by stefan-schweiger** [ant-design/ant-design#7603]
### Version
2.13.1

### Environment
MacOS 10.12.4, Google Chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/anon/pen/jGEdYV?editors=001](https://codepen.io/anon/pen/jGEdYV?editors=001)

### Steps to reproduce
Simply use a Table and set scroll.y to something (e.g. 150) and don't set the width property of at least one column except the last one.

### What is expected?
Header and Content columns should have the same width. If you remove the scroll.y config it works as expected (without scrolling obviously).

### What is actually happening?
Header and Content columns are misaligned and don't have the same width.

---
On the example page it seems to work without a problem but as soon as I tried it out myself it didn't work, because I wasn't setting the width on all columns as in the example.

**Comment by yesmeck** [comment]
Yes, this is documented https://ant.design/components/table/#components-table-demo-fixed-header

**Comment by stefan-schweiger** [comment]
Oh I've must have overlooked that note. But I think it would still be better to work on scrollable tables the same way it does on not scrollable ones.

**Comment by afc163** [comment]
It is hard to implement it now.

**Comment by casamia918** [comment]
Set "width" property in the column is working to me.

**Comment by ant45de** [comment]
Problem still exists.

**Comment by birkanm** [comment]
> Set "width" property in the column is working to me.

That is also worked for me

**Comment by mrKorg** [comment]
I have the same problem. Doe's somebody have solution?

**Comment by ChampyW** [comment]
> Set "width" property in the column is working to me.

Thank you. It is worked for me too

**Comment by nattapon4erudite** [comment]
> Set "width" property in the column is working to me.

didn't work for me.

**Comment by AlyonaUdod** [comment]
For me it works when width 

> Set "width" property in the column is working to me.

For me it works only when table width doesn't need scroll-x. When width is less then columns need header and body started to live different width-life.

**Comment by AlyonaUdod** [comment]
But I found solution. 

    const [width, setWidth] = useState(window.innerWidth);
    const [data, setData] = useState([]);

     useEffect(() => {
        if (!data.length) {
            setData(suppliersList)
        };
    }, [dataList])

    useEffect(() => {
        let a = () => setWidth(window.innerWidth);
        window.addEventListener('resize', a);
        return () => {
            window.removeEventListener('resize', a);
        };
    }, [width]);

    useEffect(() => {
        let head = document.querySelector('.ant-table-thead');
        let headArr = Array.from(head.childNodes[0].childNodes);
        if (data.length) {
            head.childNodes[0].style.display = 'flex';
            let body = document.querySelector('.ant-table-tbody');
            let bodyArr = Array.from(body.childNodes[0].childNodes);
            for (let i = 0; i < headArr.length; i++){
                headArr[i].style.width = bodyArr[i].offsetWidth + 'px';
            };
        };
    }, [data, width]);

**Comment by bsrikan** [comment]
We had a similar issue in my company. Our component renders 2 tables side by side with a split pane in between.
Resizing using the spit pane used to mess the alignment of column header and body. The tables had a scroll for y set to '60vh' and x was set to 'max-content'. Changing the value of x to 1000 or so for the bigger table and about 300 for the smaller did the trick for us.

**Comment by omarragi** [comment]
Does version 4 fix the problem ? it seems it does
v4
https://codesandbox.io/s/fixed-header-ant-design-demo-7uc9e?file=/index.js
v3
https://codesandbox.io/s/cocky-fermat-mrth2?file=/index.js

**Comment by kelvinndmo** [comment]
this will work out the trick for your 
``` 
<Table
      columns={columns}
      tableLayout="auto"
      dataSource={data}
      pagination={false}
      rowKey="id"
      scroll={{ y: 350, x: 'max-content' }}
    />
```

**Comment by alanyeung95** [comment]
For those who still struggle on the scroll and don't want to apply the fixed width, I somehow find the percentage width useful and it saves my day.

```
 {
 title: 'Col_1',
 dataIndex: 'col_1',
 key: "col_1",
 width: "50%",
 },
```

But I think the team should still get the scroll fixed, given the fact that **table is a very important componemnt in EVERY ui library/framework.**
