### ISSUE TITLE
Select tag mode that accept new entries should complete when hitting tab or clicking off of multi select field.

### ISSUE THREAD

**Issue by edencorbin** [ant-design/ant-design#7606]
### Version
2.13.1

### Environment
Windows 10, Chrome, React-Web, Codepen

### Reproduction link
[https://codepen.io/anon/pen/VMLvbY?editors=001](https://codepen.io/anon/pen/VMLvbY?editors=001)

### Steps to reproduce
Create a select with mode="tags" and token separators, enter any non existing entry and hit tab, Alternatively enter any entry and click off of the field. Both of these options should either create the entry, or have a configuration option that allows them to be created on tab or on blur.

### What is expected?
When hitting tab or when clicking off of the select an entry should be created even if the user has not clicked return or a token separator.

### What is actually happening?
When hitting tab or clicking off of the select the current tag input is lost.

---
This may be closer to a feature request, but I thought the bug format would be better to link a codepen and describe the process.

**Comment by nikogu** [comment]
i think it's a UX question?  @afc163

**Comment by afc163** [comment]
I think it is weird, the <kbd>Tab</kbd> should jump between form controls, the `blur` should not update the tag component. I gonne keep original UX.

If you want to custom keyboard shortcuts for this, feel free to PR to rc-select.
