### ISSUE TITLE
option's width is wrong in version 2.13.1 under the react version 16.0.0-rc.3

### ISSUE THREAD

**Issue by dingchaoyan1983** [ant-design/ant-design#7608]
![5a52f4ab-1a4b-44eb-bda8-4b00564f0f07](https://user-images.githubusercontent.com/7593506/30463269-36042142-99fd-11e7-87db-e1c5fa8e412c.png)

The option width of Select in antd's version `2.13.1`  is wrong in react version `16.0.0-rc.3`

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/7609
