### ISSUE TITLE
option's width is wrong in version 2.13.1 under the react version 16.0.0-rc.3

### ISSUE THREAD

**Issue by dingchaoyan1983** [ant-design/ant-design#7609]
### Version
2.13.1

### Environment
react version: 16.0.0-rc.3

### Reproduction link
[https://codepen.io/dingchaoyan1983/pen/bodwrQ](https://codepen.io/dingchaoyan1983/pen/bodwrQ)

### Steps to reproduce
render a select

### What is expected?
![5a52f4ab-1a4b-44eb-bda8-4b00564f0f07](https://user-images.githubusercontent.com/7593506/30463269-36042142-99fd-11e7-87db-e1c5fa8e412c.png)

The option width of Select in antd's version `2.13.1`  is wrong in react version `16.0.0-rc.3`

### What is actually happening?
![5a52f4ab-1a4b-44eb-bda8-4b00564f0f07](https://user-images.githubusercontent.com/7593506/30463269-36042142-99fd-11e7-87db-e1c5fa8e412c.png)

The option width of Select in antd's version `2.13.1`  is wrong in react version `16.0.0-rc.3`

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by dingchaoyan1983** [comment]
under the further investigate, this issue is related a react16 bug https://github.com/facebook/react/issues/10310

**Comment by dingchaoyan1983** [comment]
more context please check https://github.com/facebook/react/issues/10294#issuecomment-318374245

**Comment by gaearon** [comment]
It is not a bug but an intentional breaking change. Please change your usage of `renderSubtreeIntoContainer` to `ReactDOM.createPortal` which is available in 16. You can check for whether it exists and branch in the code.

**Comment by benjycui** [comment]
More info: https://github.com/react-component/util/blob/2061283084910c8c2fed20263759cae7f8892aeb/src/getContainerRenderMixin.jsx#L31-L38

**Comment by dingchaoyan1983** [comment]
@benjycui yes, I have already debug to this function also, but I don't know how to correct it, because I have no more context for this, i don't read the whole code, almost it use to create a dom out of react root.

**Comment by kooinam** [comment]
any quick patch for this?

**Comment by kooinam** [comment]
any update or should we revert back to react 15?

**Comment by afc163** [comment]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/507615/31597788-eb21cc7c-b27c-11e7-9ace-3f69993385fb.png">

http://beta.ant.design/components/select/

**Comment by yesmeck** [comment]
I'm looking into it.

**Comment by dvdhsu** [comment]
@yesmeck can you bump the version? That way when ant-design is reinstalled, we'll get the fix automatically. Thanks!

**Comment by yesmeck** [comment]
rc-select@6.9.4

**Comment by yizhoucao** [comment]
@yesmeck tree select has the same issue. Could you please fix that as well? Thanks.

http://beta.ant.design/components/tree-select/

**Comment by ElliotReeve** [comment]
I updated to 2.13.7 but I still get this issue, do I need to do something else? Thanks

**Comment by yesmeck** [comment]
@ElliotReeve Ensure `npm list rc-select` is 6.9.4, otherwise, reinstall node_modules.

**Comment by yesmeck** [comment]
@yizhoucao Fixed in `rc-tree-select@1.10.11`

**Comment by pueding** [comment]
@yesmeck thank you!
