### ISSUE TITLE
When a child Menu.Item was selected, its parent SubMenu should be expanded

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#7612]
### What problem does this feature solve?
Suppose we have a menu:

```jsx
<Menu defaultSelectedKeys={['sub-1', 'sub-sub-1']}>
  <Menu.SubMenu key='sub'>
    <Menu.Item key='sub-1'>
    </Menu.Item>
    <Menu.SubMenu key='sub-sub'>
      <Menu.Item key='sub-sub-1'>
      </Menu.Item>
    </Menu.SubMenu>
  </Menu.SubMenu>
</Menu>
```

Since `defaultSelectedKeys` is ['sub-1', 'sub-sub-1'], the SubMenu `sub` and `sub-sub` should be automatically expanded.

### What does the proposed API look like?
 FYI

**Comment by afc163** [comment]
I don't think it should be a default behavior, you should controll it by yourself.

**Comment by djyde** [comment]
@afc163 Do you think there can be a `autoExpandParent` props to control it? It can be `false` by default.

**Comment by theodorDiaconu** [comment]
@afc163 why did you close the ticket? It seems like a useful feature, you can leave the default you prefer, but implementing this can be somewhat hard. Think about this scenario: you have a submenu called Users and under it "List"/"New" you would like that when you click "New" to change the route, and keep Users menu expanded, otherwise it results in weird behaviour.

**Comment by theodorDiaconu** [comment]
Maybe another developer hits this and I save him 15-20 mins of his time:

```
import React from 'react';
import { Menu, Icon } from 'antd';
import { withRouter } from 'react-router';

const SubMenu = Menu.SubMenu;

const menu = [
  { icon: 'pie-chart', label: 'Items List', path: '/items/list' },
  {
    icon: 'pie-chart',
    label: 'Items',
    key: 'items',
    isSelected: path => path.indexOf('/items') === 0,
    items: [
      { icon: 'pie-chart', label: 'List', path: '/items/list' },
      { icon: 'pie-chart', label: 'New', path: '/items/new' },
    ],
  },
];

class MainMenu extends React.Component {
  render() {
    const { pathname } = this.props.location;
    const selectedOrOpenKeys = this.getSelectedKeys(menu, pathname);

    return (
      <Menu
        theme="dark"
        defaultSelectedKeys={['1']}
        mode="inline"
        defaultOpenKeys={selectedOrOpenKeys}
        defaultSelectedKeys={selectedOrOpenKeys}
      >
        {menu.map(this.renderMenuItem)}
      </Menu>
    );
  }

  getSelectedKeys(items, pathname) {
    let selectedKeys = [];

    items.map(item => {
      if (item.isSelected) {
        if (item.isSelected(pathname)) {
          selectedKeys.push(item.key ? item.key : item.path);
        }
      } else {
        if (item.path === pathname || item.key === pathname) {
          selectedKeys.push(item.key ? item.key : item.path);
        }
      }
      if (item.items) {
        const itemKeys = this.getSelectedKeys(item.items, pathname);
        selectedKeys.push(...itemKeys);
      }
    });

    return selectedKeys;
  }

  renderMenuItem = item => {
    const { label, path, items, icon, key, ...rest } = item;

    if (item.items) {
      const title = (
        <span>
          {icon && <Icon type={icon} />}
          <span>{label}</span>
        </span>
      );
      return (
        <SubMenu key={key || path} title={title}>
          {items.map(this.renderMenuItem)}
        </SubMenu>
      );
    }

    return (
      <Menu.Item key={key || path} {...rest}>
        {icon && <Icon type="file" />}
        <span onClick={() => this.props.history.push(path)}>{label}</span>
      </Menu.Item>
    );
  };
}

export default withRouter(MainMenu);
```

**Comment by dangdien-tiki** [comment]
if @theodorDiaconu 's solution is the only one then this is stupid

**Comment by Metronomy** [comment]
Why is this issue closed?
The problem is that the project i am working on has dynamic submenu items. Also the selected keys are being generated by react router and sometimes i redirect the user to paths that are referenced to submenu items. 
I don't understand why this is an issue that has been closed.

**Comment by Altair312** [comment]
I will second this. A very nice feature to have, optionally, no need to enforce it by default.

**Comment by mikhelev** [comment]
I wait this feature too!

**Comment by JulienTimsch** [comment]
Same here, having a hard time getting a clean solution

**Comment by djyde** [comment]
Hi @afc163 Could I create a PR to support it?

**Comment by forrest-keller** [comment]
This would be great. Need this feature.

**Comment by iloveip** [comment]
Here is my solution.

```
const menuLinks = [
  {
    name: 'Name1',
    subItems: [
      {
        name: 'SubItem1',
        url: '/subitem1/'
      },
      {
        name: 'SubItem2',
        url: '/subitem2/'
      }
    ]
  },
  {
    name: 'MenuItem1',
    url: '/item1/'
  },
  {
    name: 'MenuItem2',
    url: '/item2/'
  }
]

const SiteMenu = () => {
  const location = useLocation()

  const [openKeys, setOpenKeys] = useState([])

  useEffect(() => {
    if (!menuLinks.find(item => item.url === location.pathname)) {
      const currentSubItem = menuLinks.find(item => item.subItems && item.subItems.find(item => item.url === location.pathname))
      setOpenKeys(currentSubItem.name)
    }
  }, [location.pathname, menuLinks]);

  return (
    <Menu
      mode="inline"
      selectedKeys={[location.pathname]}
      openKeys={openKeys}
    >
      {
        menuLinks.map(
          link => (
            link.subItems ?
              <SubMenu key={link.name} title={link.name}>
                {
                  link.subItems.map(
                    subItem => (
                      <Menu.Item key={subItem.url}>
                        <Link to={subItem.url}>{subItem.name}</Link>
                      </Menu.Item>
                    )
                  )
                }
              </SubMenu> :
              <Menu.Item key={link.url}>
                {
                  <Link to={link.url}>{link.name}</Link>
                }
              </Menu.Item>
          )
        )
      }
    </Menu>
  )
}
```

**Comment by iloveip** [comment]
Here is my solution:

```
const menuLinks = [
  {
    name: 'SubMenu',
    subItems: [
      {
        name: 'SubMenuItem1',
        url: '/subitem1/'
      },
      {
        name: 'SubMenuItem1',
        url: '/subitem2/'
      }
    ]
  },
  {
    name: 'MenuItem1',
    url: '/menuitem1/'
  },
  {
    name: 'MenuItem2',
    url: '/menuitem2/'
  }
]

const SiteMenu = () => {
  const location = useLocation()
  const [openKeys, setOpenKeys] = useState([])

  useEffect(() => {
    if (!menuLinks.find(item => item.url === location.pathname)) {
      if (menuLinks.find(item => item.subItems && item.subItems.find(item => item.url === location.pathname))) {
        const currentSubItem = menuLinks.find(item => item.subItems && item.subItems.find(item => item.url === location.pathname))
        setOpenKeys([currentSubItem.name])
      }
      return
    }
  }, [menuLinks, location.pathname]);

  return (
    <Menu
      mode="inline"
      selectedKeys={[location.pathname]}
      openKeys={openKeys}
    >
      {
        menuLinks.map(
          link => (
            link.subItems ?
              <SubMenu key={link.name} title={link.name}>
                {
                  link.subItems.map(
                    subItem => (
                      <Menu.Item key={subItem.url}>
                        <Link to={subItem.url}>{subItem.name}</Link>
                      </Menu.Item>
                    )
                  )
                }
              </SubMenu> :
              <Menu.Item key={link.url}>
                <Link to={link.url}>{link.name}</Link>
              </Menu.Item>
          )
        )
      }
    </Menu>
  )
}
```

**Comment by Nxtra** [comment]
> Maybe another developer hits this and I save him 15-20 mins of his time:
> 
> ```
> import React from 'react';
> import { Menu, Icon } from 'antd';
> import { withRouter } from 'react-router';
> 
> const SubMenu = Menu.SubMenu;
> 
> const menu = [
>   { icon: 'pie-chart', label: 'Items List', path: '/items/list' },
>   {
>     icon: 'pie-chart',
>     label: 'Items',
>     key: 'items',
>     isSelected: path => path.indexOf('/items') === 0,
>     items: [
>       { icon: 'pie-chart', label: 'List', path: '/items/list' },
>       { icon: 'pie-chart', label: 'New', path: '/items/new' },
>     ],
>   },
> ];
> 
> class MainMenu extends React.Component {
>   render() {
>     const { pathname } = this.props.location;
>     const selectedOrOpenKeys = this.getSelectedKeys(menu, pathname);
> 
>     return (
>       <Menu
>         theme="dark"
>         defaultSelectedKeys={['1']}
>         mode="inline"
>         defaultOpenKeys={selectedOrOpenKeys}
>         defaultSelectedKeys={selectedOrOpenKeys}
>       >
>         {menu.map(this.renderMenuItem)}
>       </Menu>
>     );
>   }
> 
>   getSelectedKeys(items, pathname) {
>     let selectedKeys = [];
> 
>     items.map(item => {
>       if (item.isSelected) {
>         if (item.isSelected(pathname)) {
>           selectedKeys.push(item.key ? item.key : item.path);
>         }
>       } else {
>         if (item.path === pathname || item.key === pathname) {
>           selectedKeys.push(item.key ? item.key : item.path);
>         }
>       }
>       if (item.items) {
>         const itemKeys = this.getSelectedKeys(item.items, pathname);
>         selectedKeys.push(...itemKeys);
>       }
>     });
> 
>     return selectedKeys;
>   }
> 
>   renderMenuItem = item => {
>     const { label, path, items, icon, key, ...rest } = item;
> 
>     if (item.items) {
>       const title = (
>         <span>
>           {icon && <Icon type={icon} />}
>           <span>{label}</span>
>         </span>
>       );
>       return (
>         <SubMenu key={key || path} title={title}>
>           {items.map(this.renderMenuItem)}
>         </SubMenu>
>       );
>     }
> 
>     return (
>       <Menu.Item key={key || path} {...rest}>
>         {icon && <Icon type="file" />}
>         <span onClick={() => this.props.history.push(path)}>{label}</span>
>       </Menu.Item>
>     );
>   };
> }
> 
> export default withRouter(MainMenu);
> ```

Does someone have this working in a SandBox? Can't get it working.

**Comment by Nxtra** [comment]
> Here is my solution:
> 
> ```
> const menuLinks = [
>   {
>     name: 'SubMenu',
>     subItems: [
>       {
>         name: 'SubMenuItem1',
>         url: '/subitem1/'
>       },
>       {
>         name: 'SubMenuItem1',
>         url: '/subitem2/'
>       }
>     ]
>   },
>   {
>     name: 'MenuItem1',
>     url: '/menuitem1/'
>   },
>   {
>     name: 'MenuItem2',
>     url: '/menuitem2/'
>   }
> ]
> 
> const SiteMenu = () => {
>   const location = useLocation()
>   const [openKeys, setOpenKeys] = useState([])
> 
>   useEffect(() => {
>     if (!menuLinks.find(item => item.url === location.pathname)) {
>       if (menuLinks.find(item => item.subItems && item.subItems.find(item => item.url === location.pathname))) {
>         const currentSubItem = menuLinks.find(item => item.subItems && item.subItems.find(item => item.url === location.pathname))
>         setOpenKeys([currentSubItem.name])
>       }
>       return
>     }
>   }, [menuLinks, location.pathname]);
> 
>   return (
>     <Menu
>       mode="inline"
>       selectedKeys={[location.pathname]}
>       openKeys={openKeys}
>     >
>       {
>         menuLinks.map(
>           link => (
>             link.subItems ?
>               <SubMenu key={link.name} title={link.name}>
>                 {
>                   link.subItems.map(
>                     subItem => (
>                       <Menu.Item key={subItem.url}>
>                         <Link to={subItem.url}>{subItem.name}</Link>
>                       </Menu.Item>
>                     )
>                   )
>                 }
>               </SubMenu> :
>               <Menu.Item key={link.url}>
>                 <Link to={link.url}>{link.name}</Link>
>               </Menu.Item>
>           )
>         )
>       }
>     </Menu>
>   )
> }
> ```

This solution seems like what I am looking for!
However using your solution, it is no longer possible to expand submenu's. Is that correct?

For demo, see: https://codesandbox.io/s/vigilant-lovelace-5cnqi

**Comment by Jplus2** [comment]
Hope this feature gets implemented.

**Comment by DungGramer** [comment]
Update on V5. I'm expanded parent when navigate to child.

```js
const items= [
    { label: 'Account', key: '/admin/account' },
    { label: 'Connection', key: '/admin/connection'
      children: [
        { label: 'Devices', key: '/admin/connection/devices', },
      ],
    },
    { label: 'Institution', key: '/admin/institution', },
];

const location = useLocation();
const [openKeys, setOpenKeys] = useState(null);

useEffect(() => {
  if (!items.find((item) => item.key === location.pathname)) {
    const currentSubItem = items.find((item) => item.children?.find((item) => item.key === location.pathname));
    if (currentSubItem) setOpenKeys([currentSubItem.key]);
    return;
  }
  setOpenKeys([]);
}, [items, location.pathname]);

return (
  <>
    {openKeys && (
            <Menu
              theme="dark"
              mode="inline"
              defaultSelectedKeys={[location.pathname]}
              {...(openKeys && { defaultOpenKeys: openKeys })}
              onClick={({ key }) => {
                navigate(key);
              }}
              items={setAllValueWithKey(items, 'preloadable', null)}
              className={menuClassName}
            />
          )}
  </>
)
```

**Comment by nguyenvietdung31** [comment]
> Update on V5. I'm expanded parent when navigate to child.
> 
> ```js
> const items= [
>     { label: 'Account', key: '/admin/account' },
>     { label: 'Connection', key: '/admin/connection'
>       children: [
>         { label: 'Devices', key: '/admin/connection/devices', },
>       ],
>     },
>     { label: 'Institution', key: '/admin/institution', },
> ];
> 
> const location = useLocation();
> const [openKeys, setOpenKeys] = useState(null);
> 
> useEffect(() => {
>   if (!items.find((item) => item.key === location.pathname)) {
>     const currentSubItem = items.find((item) => item.children?.find((item) => item.key === location.pathname));
>     if (currentSubItem) setOpenKeys([currentSubItem.key]);
>     return;
>   }
>   setOpenKeys([]);
> }, [items, location.pathname]);
> 
> return (
>   <>
>     {openKeys && (
>             <Menu
>               theme="dark"
>               mode="inline"
>               defaultSelectedKeys={[location.pathname]}
>               {...(openKeys && { defaultOpenKeys: openKeys })}
>               onClick={({ key }) => {
>                 navigate(key);
>               }}
>               items={setAllValueWithKey(items, 'preloadable', null)}
>               className={menuClassName}
>             />
>           )}
>   </>
> )
> ```

how about Typescript?

**Comment by DungGramer** [comment]
> > Update on V5. I'm expanded parent when navigate to child.
> > ```js
> > const items= [
> >     { label: 'Account', key: '/admin/account' },
> >     { label: 'Connection', key: '/admin/connection'
> >       children: [
> >         { label: 'Devices', key: '/admin/connection/devices', },
> >       ],
> >     },
> >     { label: 'Institution', key: '/admin/institution', },
> > ];
> > 
> > const location = useLocation();
> > const [openKeys, setOpenKeys] = useState(null);
> > 
> > useEffect(() => {
> >   if (!items.find((item) => item.key === location.pathname)) {
> >     const currentSubItem = items.find((item) => item.children?.find((item) => item.key === location.pathname));
> >     if (currentSubItem) setOpenKeys([currentSubItem.key]);
> >     return;
> >   }
> >   setOpenKeys([]);
> > }, [items, location.pathname]);
> > 
> > return (
> >   <>
> >     {openKeys && (
> >             <Menu
> >               theme="dark"
> >               mode="inline"
> >               defaultSelectedKeys={[location.pathname]}
> >               {...(openKeys && { defaultOpenKeys: openKeys })}
> >               onClick={({ key }) => {
> >                 navigate(key);
> >               }}
> >               items={setAllValueWithKey(items, 'preloadable', null)}
> >               className={menuClassName}
> >             />
> >           )}
> >   </>
> > )
> > ```
> 
> how about React Typescript?

Read in the docs: https://ant.design/components/menu

**Comment by nguyenvietdung31** [comment]
The Menu in sidebar still close after i click into a sub-menu.
What props of Antd menu what i miss?
<Menu
            onClick={({key}) => {
              history.push(key);
            }}
            mode="inline"
            defaultSelectedKeys={[location.pathname]}
            {...(openKeys && { defaultOpenKeys: openKeys })}
            style={{height: '100%', borderRight: 0}}
            items={leftMenuList}
/>

Vào Th 6, 24 thg 3, 2023 vào lúc 12:53 Nguyễn Công Dũng <
***@***.***> đã viết:

**Comment by dzung1nguyen** [comment]
**Menu multi level (2, 3, 4, ...), auto open/active sub menu when reload or change location.**

```
interface MainMenuItem {
  path: string
  name: string
  icon?: string
  permissions?: string[]
  children?: MainMenuItem[]
}
// Main menu
const mainMenu: MainMenuItem[] = [
  {
    path: '/',
    name: 'Dashboard',
    icon: 'PieChartOutlined',
    permissions: [],
  },
  {
    path: 'doctor-index',
    name: 'Doctors',
    icon: 'TeamOutlined',
    permissions: [],
    children: [
      {
        path: '/doctors/create',
        name: 'Add New Doctor',
        permissions: [],
        children: [
          {
            path: '/doctors/aaaa',
            name: 'Add New Doctor',
            permissions: [],
            children: [
              {
                path: '/doctors/ddd',
                name: 'Add New Doctor',
                permissions: [],
              },
              {
                path: '/doctors/eeee',
                name: 'list Doctors',
                permissions: [],
              },
            ],
          },
          {
            path: '/doctors/bbbb',
            name: 'list Doctors',
            permissions: [],
          },
        ],
      },
      {
        path: '/doctors/list',
        name: 'list Doctors',
        permissions: [],
      },
    ],
  },
  {
    path: 'patients-index',
    name: 'patients',
    icon: 'TeamOutlined',
    permissions: [],
    children: [
      {
        path: '/patients/create',
        name: 'Add New patient',
        permissions: [],
      },
      {
        path: '/patients',
        name: 'list patients',
        permissions: [],
      },
    ],
  },
]

// Like on document
type MenuItem = Required<MenuProps>['items'][number]

// Define icons for menu
const icons: Record<string, React.ReactNode> = {
  FileOutlined: <FileOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  TeamOutlined: <TeamOutlined />,
  UserOutlined: <UserOutlined />,
}

const getItem = (
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[],
): MenuItem => {
  return {
    key,
    icon,
    children,
    label,
  } as MenuItem
}
// Create menu link
const MenuItemLink = ({ item }: { item: MainMenuItem }) => {
  return (
    <>
      {item.path && !item.children?.length ? (
        <Link to={item.path}>{item.name}</Link>
      ) : (
        item.name
      )}
    </>
  )
}

// Create menu, you can check pernissions here
const createMenu = (
  menu: MainMenuItem[],
  permissions: string[],
): MenuItem[] => {
  const items: MenuItem[] = []
  menu.forEach((item) => {
    const children = item.children?.length
      ? createMenu(item.children, permissions)
      : undefined

    const icon =
      item.icon && Object.prototype.hasOwnProperty.call(icons, item.icon)
        ? icons[item.icon]
        : undefined

    const label = <MenuItemLink item={item} />

    const menuItem: MenuItem = getItem(label, item.path, icon, children)
    items.push(menuItem)
  })
  return items
}

// Find the path to active/open (paths are menu key)
const findParentMenuPaths = (
  menuArray: MainMenuItem[],
  parent: MainMenuItem | null,
  pathname: string,
) => {
  return menuArray
    .map((element) => {
      let paths: string[] = []

      if (element.path === pathname && parent) {
        paths.push(parent.path)
      }
      if (element.children) {
        const tmpPath = findParentMenuPaths(element.children, element, pathname)
        paths = paths.concat(tmpPath)
        if (parent && tmpPath.length > 0) {
          paths.push(parent.path)
        }
      }

      return paths
    })
    .reduce((acc, paths) => acc.concat(paths), [])
}

const MainMenu = () => {
   const location = useLocation()

  const [openKeys, setOpenKeys] = useState<string[] | undefined>([])

   // Get user permission and pass them here
  const items = useMemo(() => {
    return createMenu(mainMenu, [])
  }, [])


  useEffect(() => {
    const keys = findParentMenuPaths(mainMenu, null, location.pathname)
    setOpenKeys(keys)
  }, [location.pathname])

  return (
    <>
      <div>{openKeys?.join(',')}</div>
      <Menu
        theme="dark"
        mode="inline"
        defaultOpenKeys={openKeys}
        selectedKeys={[location.pathname]}
        openKeys={openKeys}
        items={items}
        onOpenChange={(keys: string[]) => {
          setOpenKeys(keys)
        }}
      />
    </>
  )
}

export default MainMenu
``
