### ISSUE TITLE
DatePicker disabledDate set invalid

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#7616]
### Version
2.13.1

### Environment
mac chrome

### Reproduction link
[https://codepen.io/yangbin1994/pen/rGVyza?editors=0011](https://codepen.io/yangbin1994/pen/rGVyza?editors=0011)

### Steps to reproduce
click DatePicker

### What is expected?
返回false的时间设置成不可用
The return false time is set to not available

### What is actually happening?
返回false的时间任然可用
The time to return false is available

**Comment by nikogu** [comment]
i think you should 

```
<DatePicker 
  disabledDate={(current) => {
    return true;
  }}
/>
```

?
