### ISSUE TITLE
Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key.

### ISSUE THREAD

**Issue by johhansantana** [ant-design/ant-design#7623]
I'm trying to figure out how can I get unique keys for each record.

So far, my code looks like this:

```javascript
let lastIndex = 0
const updateIndex = () => {
  lastIndex++
  return lastIndex
}

...

constructor() {
  super()

  this.state = {
    columns: [ {
      title: 'Nombre',
      dataIndex: 'name',
      key: `name${updateIndex()}`
    }, {
      title: 'Precio',
      dataIndex: 'price',
      key: `price${updateIndex()}`
    }, {
      title: 'Precio regular',
      dataIndex: 'regularPrice',
      key: `regularPrice${updateIndex()}`
    }, {
      title: 'Categoría(s)',
      key: `id${updateIndex()}`,
      render: (text, record) => (
        <span>
          {
            record.categories.map((r, index) => (
              <span key={index}>
                {
                  index > 0 &&
                  <span className="ant-divider"/>
                }
                <span>{r.name}</span>
              </span>
            ))
          }
        </span>
      )
    }, {
      title: 'Action',
      key: `id${updateIndex()}`,
      render: (text, record) => (
        <span>
          <a href="#">Editar - {record.name}</a>
          <span className="ant-divider"/>
          <a href="#" style={{color: 'red'}}>Borrar</a>
        </span>
      )
    }, ]
  }
}
```

But I'm still getting the error that each record in table should have a unique `key`.

What would be the best way to achieve this?

**Comment by afc163** [comment]
That means the key of your data, not columns.

**Comment by ahmetkuslular** [comment]
I have the same problem. How can we solve this? @ant-design-bot  @afc163

**Comment by lijinlone** [comment]
With columns if not set dataIndex property, column key should be set unique key.

@johhansantana key not unique ↓

 title: 'Categoría(s)',
 **key: \`id${updateIndex()}\`,**
...
 title: 'Action',
**key: \`id${updateIndex()}\`,**

**Comment by ahmetkuslular** [comment]
I did not fully understand what we had to do. @lijinlone

**Comment by buvinghausen** [comment]
@ahmetkuslular The error message is pretty explicit your data set must contain items with a key property on them or you must specify the rowKey property on the Table component with the name from a field in your dataset which is unique to each row.

[Source Code Here](https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx)

```jsx
<Table 
  columns={columns} 
  dataSource={this.props.categories} 
  rowKey="name" 
/>
```

**Comment by jdhiro** [comment]
This one was confusing to me as well, because I was confusing COLUMN keys with ROW keys.

Ant is expecting you to have a unique key specifically named "key" on each row of data, like so:
```javascript
{ key: 1, value: 'foo'}
```

My data had "id" instead:
```javascript
{ id: 1, value: 'foo'}
```

In order to resolve this, I added a rowKey property to my Table like so:
```html
<Table columns={this.columns} dataSource={this.state.results} rowKey='id' />
```

**Comment by joshpitzalis** [comment]
`<Table .... rowKey={record => record.countryId} ... />` fixed it for me.
`countryId` being a unique values on each item field in your data.

**Comment by ljubic** [comment]
I am getting the same ⚠️  **Warning** although my data is fine & **rowKey** property was either set **"id"** or **{record => record.id}**.
```
[{
  "id": "tCxYIWJPUWdoeFG8sBt1HJsiEqQ2",
  "firstName": "John",
  "lastName": "Doe"
 }, {
  "id": "ClHz4PjoF7dFCOSgieRiYZ6HSqE2",
  "firstName":"Alice",
  "lastName":"Al"
 }, {
  "id": "WKL0yEv1FwQMwpn315weNf3k7t82",
  "firstName":"Bob",
  "lastName":"B"
 }]
```
What could I be doing wrong?

**Comment by storesbuzz** [comment]
Hey guys, adding rowKey to Table solved my issue
<Table rowKey="id" ...../>

'id' is one of my key presents in columns as - 

const columns = [
  {
    title: '#',
    dataIndex: 'id',
    key: 'id',
  },
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
.
.
.
Hope this can help.

**Comment by xgqfrms** [comment]
# solution 1

> each col has on unique `key`

```jsx
// each column with unique key

import React from 'react';

import {
  Table,
} from 'antd';

const leftTableColumns = [
  {
    title: 'Page / Modal',
    dataIndex: 'pageModal',
    key: 'pageModal',
  },
  {
    title: 'Success Rate',
    dataIndex: 'successRate',
    key: 'successRate',
  },
];

const LeftTable = (props) => {
  const {
    leftTableDatas,
  } = props;
  return (
    <>
      <Table
        columns={leftTableColumns}
        dataSource={leftTableDatas}
      />
    </>
  );
};

export {
  LeftTable,
};

export default LeftTable;


```


# solution 2

> only need set `rowkey` on the table with unique value

```jsx
// table with rowkey

import React from 'react';

import {
  Table,
} from 'antd';

const leftTableColumns = [
  {
    title: 'Page / Modal',
    dataIndex: 'pageModal',
  },
  {
    title: 'Success Rate',
    dataIndex: 'successRate',
  },
];

const LeftTable = (props) => {
  const {
    leftTableDatas,
  } = props;
  return (
    <>
      <Table
        // rowKey
        rowKey={obj => obj.id}
        columns={leftTableColumns}
        dataSource={leftTableDatas}
      />
    </>
  );
};

export {
  LeftTable,
};

export default LeftTable;


```

**Comment by keithort** [comment]
@xgqfrms, in solution 2, you can shorten the `rowKey` prop to `rowkey="id"`. It works the same.

**Comment by kfrajtak** [comment]
What I am getting is this message
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TableRow`. See https://fb.me/react-warning-keys for more information.
    in TableCell (created by TableRow)
    in TableRow (created by Connect(TableRow))
    in Connect(TableRow) (created by ExpandableRow)
```
indicating that the problem in the `TableCell`, but how can I set the `key` prop there?

I have noticed the examples on Antd page are not throwing this error.

Thanks for help.

**Comment by tuanalumi** [comment]
> What I am getting is this message
> 
> ```
> Warning: Each child in a list should have a unique "key" prop.
> 
> Check the render method of `TableRow`. See https://fb.me/react-warning-keys for more information.
>     in TableCell (created by TableRow)
>     in TableRow (created by Connect(TableRow))
>     in Connect(TableRow) (created by ExpandableRow)
> ```

Hey, I've just figured it out. In `columns` prop, you need to have either `dataIndex` or `key`.

**Comment by kfrajtak** [comment]
@tuanalumi, thanks for pointing that out, I have added `key` and I am no longer getting that warning!

**Comment by amermemic** [comment]
> This one was confusing to me as well, because I was confusing COLUMN keys with ROW keys. This error has nothing to do with "key" in your column config.
> 
> Ant is expecting you to have a unique key specifically named "key" on each row of data, like so:
> 
> ```js
> { key: 1, value: 'foo'}
> ```
> 
> My data had "id" instead:
> 
> ```js
> { id: 1, value: 'foo'}
> ```
> 
> In order to resolve this, I added a rowKey property to my Table like so:
> 
> ```
> <Table columns={this.columns} dataSource={this.state.results} rowKey='id' />
> ```

fixed it for me, thanks

**Comment by panda6412** [comment]
What if I want to set rowKey with index in antd V4

**Comment by deschantkn** [comment]
> @ahmetkuslular The error message is pretty explicit your data set must contain items with a key property on them or you must specify the rowKey property on the Table component with the name from a field in your dataset which is unique to each row.
> 
> [Source Code Here](https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L86)
> 
> ```js
> <Table 
>   columns={columns} 
>   dataSource={this.props.categories} 
>   rowKey="name" 
> />
> ```

Worked like a charm, thank you!

**Comment by tharindu-ascentic** [comment]
> @ahmetkuslular The error message is pretty explicit your data set must contain items with a key property on them or you must specify the rowKey property on the Table component with the name from a field in your dataset which is unique to each row.
> 
> [Source Code Here](https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L86)
> 
> ```js
> <Table 
>   columns={columns} 
>   dataSource={this.props.categories} 
>   rowKey="name" 
> />
> ```

Awesome :)  Thank You <3

**Comment by Mark910413** [comment]
> being a unique values on each item field in your data.

Don't work for me

**Comment by reneolivo** [comment]
Weirdly enough I got this error because I tried to wrap `<Table.ColumnGroup>` and `<Table.Column>` in a component that would print the necessary tags by passing an object. Ant Design, as always, hated the idea of me using my own components to wrap theirs (which I think it's a pattern I have found with Ant Design). 

So instead of doing this:

```tsx
<Table {...tableProps}>
  <TableColumns columns={columns} /> {/* prints all column groups and columns */}
</table>
```

I had to do this:

```tsx
<Table {...tableProps}>
  {getTableColumns(columns)}
</table>
```

Not working with custom components is bad, but also printing that there's something wrong with the key is terrible as well because I spent hours trying to fix my data source, column keys, etc. And they were absolutely fine :\ Not a very descriptive error.

**Comment by rickvian** [comment]
what if my data doesn't have unique key data?

**Comment by imsarkar** [comment]
just put a random id for each or use index value.

**Comment by imsarkar** [comment]
> what if my data doesn't have unique key data?

just put a random id for each or use index value.

**Comment by cit-gif** [comment]
if your data doesn't have an id yet. you can try

import uuid from 'react-uuid'
...
<Table
      rowKey={() => uuid()}
      bordered
      className="table-order-list"
      columns={columns}
      dataSource={data}					
/>

**Comment by cit-gif** [comment]
if your data doesn't have an id yet. you can try

import  uuid from 'react-uuid';
...
<Table
	rowKey={() => uuid()}
	bordered
	className="table-order-list"
	columns={columns}
	dataSource={data}
				/>

**Comment by cit-gif** [comment]
if your data doesn't have an id yet. you can try
`<Table	
rowKey={() => uuid()}
  columns={columns}
  dataSource={data}
/>`

**Comment by luckymore** [comment]
@cit-gif @autumnblue when using `rowSelection ` mode, will meet a bug that can't select any row😭

> if your data doesn't have an id yet. you can try **import uuid from 'react-uuid';** .... `<Table rowKey={() => uuid()} columns={columns} dataSource={data} />`

**Comment by cit-gif** [comment]
> @cit-gif @autumnblue when using `rowSelection ` mode, will meet a bug that can't select any row😭
> 
> > if your data doesn't have an id yet. you can try **import uuid from 'react-uuid';** .... `<Table rowKey={() => uuid()} columns={columns} dataSource={data} />`

@luckymore you can see my code example : [https://codesandbox.io/s/selection-and-operation-antd-4-20-7-forked-evqw0o?file=/demo.js](url)

**Comment by luckymore** [comment]
@cit-gif you didn't set the `rowKey` property, I have a demo [here](https://codepen.io/luckymore/pen/eYVrwPZ?editors=0011)
```js
rowKey={() => Math.random()}
```

**Comment by duyhung85** [comment]
@luckymore I tried on tree data table and its not working:
[https://codesandbox.io/s/tree-data-antd-4-21-0-forked-305wyd?file=/demo.js](url)
It add dynamic key to the parent only, all the children data is gone. Is this a bug? or any way I can make dynamic key working with tree data table?
Thanks,

**Comment by cit-gif** [comment]
@luckymore if you use key in object then you don't need rowKey
![image](https://user-images.githubusercontent.com/69046350/172291373-554568fb-6995-48fb-af58-f2f22ec804fa.png)

**Comment by luckymore** [comment]
@cit-gif I see! thx!

**Comment by luckymore** [comment]
@duyhung85 Just like @cit-gif said, I make a mistake.... you should set the key in `columns`.

**Comment by ValeronS** [comment]
in Vue 3:

```
<a-table
    ...
    :columns="yourColumns"
    :data-source="yourData"
    // the solution:
    :row-key="record => record.id"
    // or
    :rowKey="record => record.id"
  >
```

**Comment by vitalijalbu** [comment]
what if my api has no ids? i mean all data may have same value

**Comment by rickvian** [comment]
@vitalijalbu you may want to generate the ID on the fly

try to figure out first:
- can i ask for unique ID from Backend?
- can i generate guaranteed unique ID based on multiple field  (composite key)? such as fullname+address+choice
- if not, then you have to generate your own index number into the dataset, or uuid
```
import uuid from 'react-uuid';
<Table	 rowKey={() => uuid()} columns={columns} dataSource={data} />
```

**Comment by Bender101** [comment]
<AntdTable rowKey={({ id }) => id}
