### ISSUE TITLE
Typescript Error Modal zIndex Boolean or Number?

### ISSUE THREAD

**Issue by DavidNorena** [ant-design/ant-design#7624]
### Version
3.0

### Environment
browser version

### Reproduction link
[https://github.com/ant-design/ant-design/blob/antd-3.0/components/modal/Modal.tsx#L65](https://github.com/ant-design/ant-design/blob/antd-3.0/components/modal/Modal.tsx#L65)

### Steps to reproduce
Trying to override the zIndex of the Modal with a number gives error.

### What is expected?
Override the zIndex property, it's supposed to be a Number but the definition is Boolean

### What is actually happening?
The [docs](https://ant.design/components/modal/#API) says that zIndex its a number with default value of 1000 but when you try to override it, its a boolean

**Comment by DavidNorena** [comment]
I can create PR changing boolean for number if you want !

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/11a6cd51a2bec2e7a446a1f699439409f627a8a5

**Comment by afc163** [comment]
Thx for reporting it.

**Comment by DavidNorena** [comment]
Thanks @afc163, I have to wait for new release ?

**Comment by DavidNorena** [comment]
@afc163 I think you forgot https://github.com/ant-design/ant-design/blob/antd-3.0/components/modal/Modal.tsx#L43
