### ISSUE TITLE
Form在引用自定义组件时setFieldsValue报错

### ISSUE THREAD

**Issue by vonxq** [ant-design/ant-design#7625]
### Version
2.13.1

### Environment
windows7，chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/vonxq/pen/aLOYXe](https://codepen.io/vonxq/pen/aLOYXe)

### Steps to reproduce
链接中FormItem的component为自定义的Test组件时，在Form组件的componentDidMount中setFieldsValue会报错（控制台可见错误提示： Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.）
但当component为已有组件时则不会

### What is expected?
期望能在使用自定义组件时setFieldsValue不出错

### What is actually happening?
链接中FormItem的component为自定义的Test组件时，在Form组件的componentDidMount中setFieldsValue会报错（控制台可见错误提示：  Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.）

**Comment by afc163** [comment]
https://codepen.io/anon/pen/yzNqVp?editors=1010

> getFieldDecorator 不能用于装饰纯函数组件。

https://ant.design/components/form-cn/#%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F

**Comment by vonxq** [comment]
看文档太粗心了，感谢 @afc163
