### ISSUE TITLE
hideDefaultSelections prevents first two custom selections from running

### ISSUE THREAD

**Issue by gronstrand** [ant-design/ant-design#7626]
### Version
2.13.1

### Environment
Windows 10, Chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/anon/pen/NaqMom](https://codepen.io/anon/pen/NaqMom)

### Steps to reproduce
1. Create a Table component with a `rowSelection` prop containing `hideDefaultSelections: true` and at least three custom selections.
2. In the rendered table, try to click on the two first options in the row selection dropdown. Nothing happens. The other options will work as intended.

### What is expected?
`onSelect` in `rowSelections.selections[0]` and `rowSelections.selections[1]` should fire when the corresponding option is clicked.

### What is actually happening?
`onSelect` is not triggered for the first two options.

---

I have provided a Codepen-link for minimal reproduction, but the bug also happens in this example on the official page: [https://ant.design/components/table/#components-table-demo-row-selection-custom](https://ant.design/components/table/#components-table-demo-row-selection-custom)

**Comment by benjycui** [comment]
@infeng why? https://github.com/ant-design/ant-design/blame/5a8bd0f6d8fa25d6431d485e9d1b8b785ec0004e/components/table/Table.tsx#L555

cc @yesmeck

**Comment by infeng** [comment]
@benjycui Before add `hideDefaultSelections `，`selections` of `rowSelection` add `all` and `invert` in the beginning, so custom selection start index is greater than 1. When `hideDefaultSelections ` is `true`, the custom selection start index should be equal or greater than 0 :satisfied:.
