### ISSUE TITLE
TextArea in table and scroll={{x: true}}  has Error

### ISSUE THREAD

**Issue by 1003657663** [ant-design/ant-design#7635]
### Version
2.13.1

### Environment
系统：maxOs:10.12.6 (16G29)   浏览器：safari:10.1.2  chrome:60.0.3112.113（正式版本)（64 位）

### Reproduction link
[https://codepen.io/songchao/pen/zEvYwJ](https://codepen.io/songchao/pen/zEvYwJ)

### Steps to reproduce
1. use this example "https://ant.design/components/table-cn/#components-table-demo-edit-row"
2. change one Input to Input.TextArea
3. Table add this Attribute "scroll={{x: true}}"
4. open console window
5. then edit the TextArea to the line end and text wrap
6. you will find one Error
7. Table add this Attribute "autosize={{minRows: 1, maxRows: 6}}"
8. repeat 4-5  
9. you will find some Error

Error text:"Cannot read property 'getBoundingClientRect' of undefined"

### What is expected?
no Error

### What is actually happening?
has Error

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/commit/4dd5918eef91687a9302c81cac1e957b33f21b90

---

> GitHub 出 bug 了，关联 commit 没显示出来。
