### ISSUE TITLE
TreeSelect checkbox and label can't Linkage

### ISSUE THREAD

**Issue by 1003657663** [ant-design/ant-design#7637]
### Version
2.13.1

### Environment
every

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable](https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable)

### Steps to reproduce
1. open the TreeSelect
2. click checkbox and has change Event
3. Click the label next to checkbox and there are not Event and can't linkage

### What is expected?
label and checkbox can linkage
or
click label has Event

### What is actually happening?
no linkage

**Comment by afc163** [comment]
`label: <a href="xx" onClick={xx}>xxx</a>`
