### ISSUE TITLE
Small size icons button do not adjust width

### ISSUE THREAD

**Issue by yizhoucao** [ant-design/ant-design#7638]
### Version
2.13.1

### Environment
Any

### Reproduction link
[https://codepen.io/anon/pen/YryqYO](https://codepen.io/anon/pen/YryqYO)

### Steps to reproduce
Open https://codepen.io/anon/pen/YryqYO

### What is expected?
When icon button size is set as small, both height and width should be adjusted, same as the circle icon button, who radius is adjusted.

### What is actually happening?
When icon button size is set as small, only height is adjusted while width is unchanged.

**Comment by nikogu** [comment]
@yizhoucao i think it's `ant design` specification.

**Comment by yizhoucao** [comment]
@nikogu but according to here, https://ant.design/docs/spec/icon#Icon-sizing it's always a square?

**Comment by afc163** [comment]
@nikogu is right.

**Comment by yizhoucao** [comment]
Ok, thanks for clarification
