### ISSUE TITLE
Form reset

### ISSUE THREAD

**Issue by catherinejing** [ant-design/ant-design#7639]
### Version
2.13.2

### Environment
mac  chrome 60.0.3112.113  15.4

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
<Form><Button htmlType=‘reset’></Form>

### What is expected?
initial form

### What is actually happening?
nothing change

**Comment by afc163** [comment]
建议有空阅读下 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
