### ISSUE TITLE
how to use Modal.confirm's API onOk in redux-saga?  (generator function)

### ISSUE THREAD

**Issue by cnfi** [ant-design/ant-design#7646]
### Version
2.12.1

### Environment
chrome 58.0.3029.81

### Steps to reproduce
```
function* watchLeavePage() {
  yield takeEvery('LEAVE_PAGE', leavePage)
}

function* leavePage() {
  confirm({
    title: 'Do you Want to Leave this page?',
    content: 'Some descriptions',
    onOk() {
      console.log('OK');
      yield put(routerActions.push('/home'));
    },
    onCancel() {
      console.log('Cancel');
    },
  });
}
```

### What is expected?
when i click "ok" button, routes to "/home"

### What is actually happening?
when i click "ok" button, but nothing happened

**Comment by nikogu** [comment]
First of all, it's not a `ant.design` question, i think you should goto [StackOverflow](https://stackoverflow.com/).

By the way, i think you can use `Promise` to wrap `confirm`:

```
// wrap
function confirmPromise() {
  return new Promise((resolve, reject)=>{
    confirm({
      title: 'Do you Want to Leave this page?',
      content: 'Some descriptions',
      onOk() {
        resolve();
      },
      onCancel() {
        reject();
      },
    });
  })
}

// call as synchronization
function* leavePage() {
  yield confirmPromise();
  yield put(routerActions.push('/home'));
}
```

refs: [Generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

**Comment by Fairyshi** [comment]
import { dva } from '...';  // path to dva instance:  dva({ ...createLoading({ effects: true }), history: createHistory(), onError(error) {} })

Modal.confirm({
    title: '操作确认?',
    content: <span>hehe</span>,
    onOk() {
      dva._store.dispatch({ type: 'fooForm/save', payload });
    },
    onCancel() {
      console.log('cancel affectedCreatives');
    },
});

// ref:  https://github.com/dvajs/dva-core/blob/0fa6888/test/effects-test.js#L332-L365

**Comment by Fairyshi** [comment]
onOk中经过用户交互确认后执行 effects or reducers 中的异步方法
