### ISSUE TITLE
treeSelect don't have expand interface and can't control select expand and select

### ISSUE THREAD

**Issue by lvjs** [ant-design/ant-design#7655]
### What problem does this feature solve?
Custom treeNode select (as well as expand). Think about we don't want to select parent node, but click to toggle show it's children.

### What does the proposed API look like?
```
const expandNode = (selectedKeys, e:{selected: bool, selectedNodes, node, event}) => {
  // some code to control tree expand
 // custom select expand, return false to prevent select hide
    return false
}
<TreeNode  onSelect={expandNode}>{xxx}</TreeNode>
```

**Comment by benjycui** [comment]
More details, thanks.

**Comment by stmoreau** [comment]
I am facing the same issue. How can you trigger the expandRow by just clicking on the row you want to expand? @benjycui

**Comment by benjycui** [comment]
@yesmeck should TreeSelect support controlled expandedKeys?

**Comment by stmoreau** [comment]
I think this is what it means @benjycui yes.

**Comment by blackboyhc** [comment]
I got the same issue. Users want to trigger the expandRow by just clicking on the label . @benjycui

**Comment by blackboyhc** [comment]
准备支持吗？用户有强烈需求 @benjycui

**Comment by Miced** [comment]
I am having an opposite issue:
When checkable, the first click on a parent row automatically expands the selection, while also selecting it. This causes an unnecessary second click if the user just wants to select multiple parent rows. Also, if the subtree is long, it causes scrolling, which is also bad.

This does not happen after the first parent selection.

**Comment by zombieJ** [comment]
Since `expandedKeys` & `selectedKeys` can control now. It makes happened:
https://codesandbox.io/s/9zv8y9ow4y

@Miced , you can adjust the logic for sample above : )

**Comment by SeanCraftsman** [comment]
@zombieJ ，Can this feature add into `TreeSelect` too？

**Comment by zombieJ** [comment]
@SeanCraftsman , `TreeSelect` is refectorying and this will happen.

**Comment by andre-engelbrecht** [comment]
This kindof works on TreeSelect, except that the dropdown closes upon select. If only there was a way to prevent this then it would work. Any advice?

**Comment by XiaochanXia** [comment]
@andre-engelbrecht I found one way to solve this issue.
use props: open and onDropdownVisibleChange.
examples: 
https://codesandbox.io/s/lively-surf-rjo2t

**Comment by sahilda** [comment]
@XiaochanXia that mostly works but now the arrows on the left are not clickable / selectable, and I can't figure out why. Do you have any thoughts?
