### ISSUE TITLE
Facebook拒绝修改React的开源许可条款, 关于最近闹的很火的开源协议问题，antd design以后还会继续维护吗？阿里巴巴会换掉所有react相关的东西吗？

### ISSUE THREAD

**Issue by senro** [ant-design/ant-design#7658]
### Version
2.13.2

### Environment
只是一个疑惑

### Reproduction link
[http://taobao.com](http://taobao.com)

### Steps to reproduce
只是一个疑惑

### What is expected?
只是一个疑惑

### What is actually happening?
只是一个疑惑

**Comment by afc163** [comment]
Duplicate of #7656
