### ISSUE TITLE
Table Header size doesn't change with selection enabled

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#7663]
### Version
2.13.2

### Environment
Chrome v60

### Reproduction link
[https://codepen.io/kossel/pen/dVMyVQ?&editors=001](https://codepen.io/kossel/pen/dVMyVQ?&editors=001)

### Steps to reproduce
When you add the props `rowSelection` and `size` props the header size doesn't change only the tbody

### What is expected?
the table header change to middle size just as usual

### What is actually happening?
only body become more compact

**Comment by benjycui** [comment]
I think it works fine:

![image](https://user-images.githubusercontent.com/3580607/30623003-c2bcac96-9d7a-11e7-9ddc-9f5ddb1a5880.png)

![image](https://user-images.githubusercontent.com/3580607/30623012-d1a7c5ce-9d7a-11e7-9cd3-a1829a4bd547.png)

**Comment by kossel** [comment]
if you remove the props 'rowSelection` the header become more compact, just like the demo page
![image](https://user-images.githubusercontent.com/1760498/30627362-4baeaa4e-9d95-11e7-85d8-7a86dc2a08f8.png)

since without the selection column the header now has `padding: 10px 8px`

![image](https://user-images.githubusercontent.com/1760498/30627394-935dadb8-9d95-11e7-872a-e4206b2d1197.png)

Shouldn't the header be the same regardless the rowSelection?
I was expecting like this:

![image](https://user-images.githubusercontent.com/1760498/30627463-fd05412c-9d95-11e7-9882-97f789b80e86.png)
