### ISSUE TITLE
How to get nest table with nested data?

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#7666]
### Version
2.13.2

### Environment
react 15.6.1

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
How to nest table with nested json data as below?
```let data=[
	{	
		cid:1,
		cname:'类别1'
		total_quality:3,
		total_money:300,
		goods:[
			{
				gid:1,
				gname:'商品1',
				total_quality:1,
				total_money:100,
			},{
				gid:2,
				gname:'商品1',
				total_quality:1,
				total_money:100,
			},{
				gid:3,
				gname:'商品1',
				total_quality:1,
				total_money:100,
			}
		]
	},{	
		cid:2,
		cname:'类别1'
		total_quality:14,
		total_money:1700,
		goods:[
			{
				gid:4,
				gname:'商品1',
				total_quality:2,
				total_money:500,
			},{
				gid:5,
				gname:'商品1',
				total_quality:1,
				total_money:100,
			},{
				gid:6,
				gname:'商品1',
				total_quality:1,
				total_money:100,
			},{
				gid:7,
				gname:'商品1',
				total_quality:10,
				total_money:1000,
			}
		]
	}
]
```

### What is expected?
Expect to get nested table as below layout: high-lever category has the same data columns with the nested-lever goods, and shows the total amount of the nested goods.

类别名称	| 商品名称 | 总数量 | 总金额
---------|-------- | -------|--------
a	|	 |     50 |	1500 |
|	|product-1	|8	|100
|	|product-2	|9	|200
|	|product-3	|10	|300
|	|product-4	|11	|400
|	|product-5	|12	|500
b	|	                |112	|6300
|	|product-10	|17	|1000
|	|product-11	|18	|1100
|	|product-12	|19	|1200
|	|product-6	|13	|600
|	|product-7	|14	|700
|	|product-8	|15	|800
|	|product-9	|16	|900
c	|	                |41	|2700
|	|product-13	|20	|1300
|	|product-14	|21	|1400
d	|	               |147	|10500
|	|product-15	|22	|1500
|	|product-16	|23	|1600
|	|product-17	|24	|1700
|	|product-18	|25	|1800
|	|product-19	|26	|1900
|	|product-20	|27	|2000
总计	|	                |350|	21000

### What is actually happening?
官方嵌套例子是表格套表格，可看性不强

**Comment by yesmeck** [comment]
See https://ant.design/components/table/#components-table-demo-expand-children
