### ISSUE TITLE
Upload中的file 怎么获得所选文件的绝对路径 ？？？

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design#7667]
### Version
2.13.2

### Environment
chorme

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
Upload中的file 怎么获得所选文件的绝对路径 ？？？

### What is expected?
Upload中的file 怎么获得所选文件的绝对路径 ？？？

### What is actually happening?
Upload中的file 怎么获得所选文件的绝对路径 ？？？

**Comment by yesmeck** [comment]
安全原因，浏览器端无法获取文件在文件系统里的真实路径。

**Comment by kingcwt** [comment]
Is there any special way to get the absolute path of a file when uploading it?

**Comment by jianglei2jl** [comment]
> 获取文件在文件系统里的真实路



> 安全原因，浏览器端无法获取文件在文件系统里的真实路径。

哦？你这不是说了等于没说吗？我本地上传文件，我想获取自己本地的路径，怎么就不安全了？说来听听。

**Comment by afc163** [comment]
@jianglei2jl 这是浏览器的实现机制，不是 antd 能改变的。你可以用原生 `<input type="file" />` 试一试。

**Comment by afc163** [comment]
ChatGPT：

在浏览器端无法直接获取文件在文件系统中的真实路径，主要出于以下几个安全原因：

1. **隐私保护**：文件路径通常包含用户计算机的目录结构和用户名称，这些信息可能泄露个人隐私。例如，文件路径中可能包含用户的用户名、工作目录，甚至是一些敏感的文件夹名。允许网页访问这些信息会让恶意网站获取到这些细节，从而对用户构成潜在的隐私威胁。

2. **安全隔离**：浏览器是一个沙箱环境，设计初衷是为了隔离用户的本地文件系统与网页之间的直接交互。这种隔离能防止恶意代码通过浏览器获取到用户的本地文件信息，进而发动更具针对性的攻击。

3. **防止路径欺骗**：如果浏览器能够访问和使用用户的文件路径，恶意网站可能会诱导用户上传某些特定位置的文件，而用户可能并不知情。这种路径欺骗可能导致用户无意中上传敏感文件。

4. **安全漏洞利用**：允许网页获取文件系统的路径可能为恶意开发者打开漏洞之门，通过路径信息制定更有效的攻击策略，例如路径遍历攻击或者是利用特定系统路径的已知漏洞。

因此，**浏览器端对文件路径的访问做了限制**，确保用户的本地文件信息不会轻易被暴露给网页脚本。浏览器通常只会返回文件名，而不会提供完整的路径信息。
