### ISSUE TITLE
When I set the showUploadList to true, how do I delete the file

### ISSUE THREAD

**Issue by funreading** [ant-design/ant-design#7668]
### What problem does this feature solve?
My business requirement does not need to uploadList, but there is a button to delete all files, if I set the showUploadList to true, but I don't know how to call the remove event

### What does the proposed API look like?
 I can actively request deletion of events， and abort request

**Comment by benjycui** [comment]
> My business requirement does not need to uploadList, but there is a button to delete all files, if I set the showUploadList to true, but I don't know how to call the remove event

????? Please provide more information, thanks.

**Comment by funreading** [comment]
就我现在有个上传功能，不需要展示uploadList的，所以我把showUploadList设置为true了。
然后页面上还有个删除上传的按钮，但我查了API，不知道怎么主动触发onRemove事件，好像只能按uploadList里的X才会触发？
查了issues，大概是跟 https://github.com/ant-design/ant-design/issues/6087 这条差不多的情况需求。

然后还有个场景是一个表单只允许上传一个文件，后面上传的要把前面的覆盖，所以第二次上传时，我会把第一次的从uploadLIst清除掉，但也只是从uploadLIst清除了而已，第一次的上传请求不知道如何中断掉他

**Comment by benjycui** [comment]
> 就我现在有个上传功能，不需要展示uploadList的，所以我把showUploadList设置为true了。

Are you kidding?

**Comment by funreading** [comment]
打错，showUploadList设置为false

**Comment by benjycui** [comment]
> 不知道怎么主动触发onRemove事件

fileList 是受控的，直接修改即可。

> 然后还有个场景是一个表单只允许上传一个文件，后面上传的要把前面的覆盖，所以第二次上传时，我会把第一次的从uploadLIst清除掉，但也只是从uploadLIst清除了而已，第一次的上传请求不知道如何中断掉他

https://github.com/react-component/upload#methods
