### ISSUE TITLE
Table columns first item must pass a dataIndex

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#7669]
### Version
2.13.2

### Environment
mac chrome

### Reproduction link
[https://codepen.io/yangbin1994/pen/LzNepv?editors=0011](https://codepen.io/yangbin1994/pen/LzNepv?editors=0011)

### Steps to reproduce
所有columns的dataIndex置空，会报错

### What is expected?
columns第一个项目的dataIndex也可以省略

### What is actually happening?
columns第一个项目的dataIndex如果不显示指定，那么
![image](https://user-images.githubusercontent.com/12080165/30626920-d62b79d0-9dff-11e7-88ea-df9dc0c7e1ae.png)

**Comment by nikogu** [comment]
https://ant.design/components/table-cn/#注意

**Comment by yangbin1994** [comment]
@nikogu dataSource数据项目是有key的
