### ISSUE TITLE
table组件要给不同tr添加class

### ISSUE THREAD

**Issue by chaneyandyou** [ant-design/ant-design#7671]
### What problem does this feature solve?
table组件要给不同tr添加class，文档说，rowClassName的类型是Function(record, index):string。添加了函数，确实能拿到record，index，问题是怎么才能加不同的类名呢

### What does the proposed API look like?
有个demo

**Comment by afc163** [comment]
```jsx
rowClassName={(record, index) => record.xxxxxxx ? 'red' : 'blue'}
```
