### ISSUE TITLE
   form 动态增减表单项 ，减少的时候仍会对删除的表单进行校验

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#7672]
### Version
2.13.2

### Environment
最新

### Reproduction link
[https://codepen.io/OneAndOnly1111/pen/wrGjJg?editors=1010](https://codepen.io/OneAndOnly1111/pen/wrGjJg?editors=1010)

### Steps to reproduce
动态增减表单项，每一项是一个panel   panel下有好几个form   ，发现问题： 如何增加后panel不打开就删除，提交的时候回校验删除掉的panel下的form

### What is expected?
动态增减表单可支持多个表单的嵌套

### What is actually happening?
不符合预期

**Comment by OneAndOnly1111** [comment]
![image](https://user-images.githubusercontent.com/18378998/30633184-5ae34212-9e1d-11e7-842e-fd0417853755.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

Not just part of your code, thanks.

**Comment by OneAndOnly1111** [comment]
https://codepen.io/OneAndOnly1111/pen/KXMqPO
业务代码在这，但是弄了很久调不出来，恳请看下

**Comment by benjycui** [comment]
无法重现的话，也帮不了你啊。。。

**Comment by OneAndOnly1111** [comment]
https://codepen.io/OneAndOnly1111/pen/BwzmEa?editors=0011
可重现的代码 @benjycui    
点击添加后  不展开panel 直接 点击panel上的删除图标，console报错，被删除掉的input没有填写  。。

**Comment by OneAndOnly1111** [comment]
如果添加完先展开一下panel再删除，提交的时候不会再去校验删除掉的，不展开直接删除的话，会去校验已经删除掉的，并且提交按钮点击再也无效。

**Comment by afc163** [comment]
> 点击添加后 不展开panel 直接 点击panel上的删除图标，console报错

按此步骤无法重现报错。

**Comment by OneAndOnly1111** [comment]
@afc163 @benjycui   补录的gif图 

![jdfw](https://user-images.githubusercontent.com/18378998/30700261-af30b870-9f19-11e7-93e7-6073713bbb26.gif)

**Comment by OneAndOnly1111** [comment]
点击添加后 不展开panel 直接 点击panel上的删除图标，然后点击提交按钮，console报错 （之前的是我没说清楚，不好意思）

**Comment by benjycui** [comment]
> 点击添加后 不展开panel 直接 点击panel上的删除图标

Chrome 下的确没有重现。

> 如果添加完先展开一下panel再删除，提交的时候不会再去校验删除掉的，不展开直接删除的话，会去校验已经删除掉的，并且提交按钮点击再也无效。

这个我观察到的情况刚好相反，打开后再删除，提交时才会去校验。。

**Comment by benjycui** [comment]
所以还是给出更加详细的步骤，不排除对于某些步骤我们理解不一致，所以操作其实是不一样的。

**Comment by OneAndOnly1111** [comment]
最简单的重现方式，
1. 点击两下add filed按钮  ，此时添加了2个panel，都不展开
2. 选择一个panel，点击上面的删除图标，该panel 被删除掉
3. 点击submit按钮进行提交 ，此时CodePen 的console控制台 出现信息：
   "async-validator:" ["names-1 is required"]
   "async-validator:" ["names-2 is required"]
不理解的是：对于存在的panel ，其下的的input在没有填写的情况下进行校验是ok的；
                     但是，对于刚刚已经删除掉的panel ，仍然对其下的input进行了校验

**Comment by OneAndOnly1111** [comment]
@benjycui  对上述操作录的动图

![gaollg0](https://user-images.githubusercontent.com/18378998/30727432-c23ce668-9f83-11e7-9e3a-f3106c0d520e.GIF)

**Comment by ChiaJune** [comment]
我也有这个问题，

**Comment by OneAndOnly1111** [comment]
@ChiaJune 也是使用panel下包含form才有这个问题嘛？ 有解决思路的话麻烦分享一下

**Comment by ChiaJune** [comment]
@OneAndOnly1111 应该是差不多吧。但是我感觉我的问题比你的更严重。因为业务的需求，我这里需要动态同时添加/删除多个受控组件（如：`Select`, `Input`, `upload`等）,在这个issue[#4901](https://github.com/ant-design/ant-design/issues/4901)启发下，我封装了一个Form组件（带有值的验证），然后根据数据来循环地来生成多个Form，并初始化值。我是操作redux来删除/添加Form，当我触发了某个Form的验证，同时删除这个Form，被删除的Form的验证状态会传递给下一个Form的相同受控组件。我来点图片说明一下：

1. 首先触发某个Form的验证
![1.png](https://i.loli.net/2017/09/24/59c7b0913420b.png)
2. 然后删除这个Form，就可以看到效果了（**注**：被删除的Form的数据肯定是从redux中删除掉的，不存在删错的情况）
![2.png](https://i.loli.net/2017/09/24/59c7b158c696e.png)

我不知道为何会出现这种情况，调试了很久都没找到问题所在，还请开发大大 @benjycui 指导一下

还有就是触发单个受控组件的验证，也是这样的：

1. 验证触发后的样子
![3.png](https://i.loli.net/2017/09/24/59c7b2cfc78e4.png)
2. 删除这个Form后的样子
![4.png](https://i.loli.net/2017/09/24/59c7b30a8a18e.png)

真是愁死我了...

**Comment by ChiaJune** [comment]
@OneAndOnly1111 我不知道是不是一样的。就是，我要删除/添加多个受控组件而不是单个受控组件，所以我把这些受控组件封装到一个Form类里面，然后来循环输出这个Form类（这里借鉴[#4901](https://github.com/ant-design/ant-design/issues/4901)处理方式）。

如图：![5.png](https://i.loli.net/2017/09/24/59c7c3690b783.png)

我找出了自己的问题。就是循环时候`key`的问题。重要的话说三次：`key`一定要唯一！`key`一定要唯一！`key`一定要唯一！哎，之前对于key理解不深刻，这次采坑后肯定不会忘了...

**Comment by benjycui** [comment]
这个问题的原因是：
1. 新增一个 Panel 时，虽然没有把表单域展现出来，但由于 getFieldDecorator 已经被调用了，所以此时这个表单域已经被注册。
1. 没打开 Panel 就删除 Panel，由于表单域虽然已经被注册，但没有被渲染过，所以没有触发 unmount 事件，自然也就没有被解除注册。所以对于表单而言，还是已注册的状态，所以也会校验。
1. 打开 Panel 后再删除，这种情况可以正常触发表单域 unmount，所以可以成功解除注册，自然也不会被校验。

**Comment by OneAndOnly1111** [comment]
目前已经用了一种比较蠢的方法解决了： 新增的Panel默认就给打开。
请问还有其它比较好的解决方案吗？

**Comment by benjycui** [comment]
这个问题如果要遭 Form 里面解决的话，需要把注册这个行为延后到 mount 时，但这样会 break 已有的用法，即直接调用 `getFieldDecorator('keys', { initialValue: [] });` 而没有关联具体的组件 https://ant.design/components/form/#components-form-demo-dynamic-form-item

所以还是在业务代码里面处理吧。

```jsx
const formItems = keys.map((k, index) => {
  return (
    <Panel key={k} header={....}>
      {isVisible ? .... : null}
    </Panel>
  );
});
```

**Comment by wuzhidexiaoheizi** [comment]
一个页面循环输出这么多form元素好吗？
