### ISSUE TITLE
Table 当往dataSource里插入一条统计数据时，会导致数据超出pageSize而被截断

### ISSUE THREAD

**Issue by scliuyang** [ant-design/ant-design#7677]
### Version
2.13.2

### Environment
all

### Reproduction link
[https://codepen.io/anon/pen/bopjMd?editors=0010](https://codepen.io/anon/pen/bopjMd?editors=0010)

### Steps to reproduce
table，查询分页最大条数的数据比如10，并且前端插入一条统计数据在最前面

### What is expected?
table渲染11条数据，第一条为统计数据

### What is actually happening?
table渲染10条，最后一条数据被截断

---
截断代码在table.tsx 862-865，希望能加入参数，能不处理数据长度>分页长度，这样可以实现前端插入统计功能

**Comment by nikogu** [comment]
I think you can use https://ant.design/components/table-cn/#components-table-demo-bordered
or other components to replace it.

By the way, you can change your `pageSize`.

**Comment by yesmeck** [comment]
Duplicate of #5710
