### ISSUE TITLE
Website not reachable...

### ISSUE THREAD

**Issue by BjornVanWettere** [ant-design/ant-design#7681]
### Version
2.13.2

### Environment
Chrome Windows 10

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
Access the url

### What is expected?
I wanna to checkout the docs of ant design.

### What is actually happening?
ERR_CONNECTION_CLOSED

---
 This is the same situation for over 2 weeks already.

**Comment by afc163** [comment]
It works on my machine.

**Comment by yesmeck** [comment]
http://downforeveryoneorjustme.com/ant.design
