### ISSUE TITLE
ios 移动端 RangePicker with ExtraFooter 点选两个日期但是确定按钮还是disabled状态

### ISSUE THREAD

**Issue by JarVan007** [ant-design/ant-design#7687]
### Version
2.13.2

### Environment
ios 11 Safari  

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
Safari登录官网，找到一个带有页脚的 datePicker 点选两个日期，但页脚Ok按钮还是disabled状态无法确定选择
Safari log on to the official website, find a datePicker point with footers, select two dates, but the footer Ok button or disabled status cannot be determined
### What is expected?
 点选两个日期之后页脚的Ok按钮可以正常选择
After selecting the two date, the footer's Ok button is OK
### What is actually happening?
无法正常选择
Cannot choose properly
---
我目前的项目中有用到这个我测试的时候认为时我写的有问题，但是试了一下官网的有也有问题，能解决一下吗？
My current project is useful to this, I test when I think I wrote a problem, but try the official website, there are problems, can you solve it?

**Comment by benjycui** [comment]
IMO, it works fine:

<img src="http://g.recordit.co/3oPfhdgHD0.gif" />

**Comment by JarVan007** [comment]
![img_0191](https://user-images.githubusercontent.com/24792319/30686328-860ef494-9e7d-11e7-9919-649c37a31f4b.PNG)
对不起，我没说明白，出问题的是DatePicker下面的RangePicker组件，在Android和PC都没问题，就iphone Safari浏览器下点选两个日期后下方按钮不刷新样式。
Sorry, I didn't say that. The problem is that the RangePicker components under DatePicker are no problem with Android and PC. Click the two dates under the iPhone Safari browser, and the buttons below do not refresh the style.

**Comment by benjycui** [comment]
与 `renderExtraFooter` 无关， https://ant.design/components/date-picker-cn/#components-date-picker-demo-time 即可重现。

**Comment by yesmeck** [comment]
The reason is the `click` event is not fired on iOS safari.

**Comment by yesmeck** [comment]
Closing due to we don't recommend using antd on mobile devices.
