### ISSUE TITLE
Select 组件多选时 当选择很多个选项时可以显示在一行，避免占据页面很大的地方

### ISSUE THREAD

**Issue by yizao** [ant-design/ant-design#7689]
### What problem does this feature solve?
Select 组件多选时 当选择很多个选项时可以显示在一行，避免占据页面很大的地方

### What does the proposed API look like?
通过参数可配置

**Comment by afc163** [comment]
People keep asking for this. I think we should do something about it.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7497
