### ISSUE TITLE
model如何拖动

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#769]

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/374

**Comment by benjycui** [comment]
Do your homework first, http://doc.zengrong.net/smart-questions/cn.html#homework

**Comment by XUGAOBO** [comment]
实际上应该有啊,这不是组件化的吗,我以前用extjs的时候全部都是属性,感觉挺方便的

**Comment by XUGAOBO** [comment]
@benjycui 看了这篇文章,但是我个人感觉,组件只不过是方便使用的,我没必要费时间去看源码,或者去想解决方法,这是浪费时间的行为
