### ISSUE TITLE
Ability to set Table 'No Data' string

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#7690]
### What problem does this feature solve?
According to the documentation, I don't see any properties on table that would let me override the message when the table has no or empty data set.  Currently it defaults to a "frownie face" icon with the no data in Chinese

### What does the proposed API look like?
`<Table noDataContent="No Rows found" />`

**Comment by afc163** [comment]
`<Table locale={{ emptyText: 'xxx' }} />`

**Comment by anneyangyue** [comment]
How to display images when the table content is empty?

**Comment by kanishk30** [comment]
.ant-table-placeholder {
  display: none;
}
Works in Angular.

**Comment by zcmgyu** [comment]
@shiny Awesome!
Currently, And Design has supported Empty component already.
Something likes this
`<List locale={{ emptyText: <Empty /> }} />`

**Comment by ckOfor** [comment]
Is it possible to display image on tables ?

**Comment by tsaowe** [comment]
> > How to display images when the table content is empty?
> 
> ```js-jsx
> <Table
>   locale={{ emptyText: (<span>
>     暂无订单数据
>     <Button>do something</Button>
>     <img src="https://www.baidu.com/img/bd_logo1.png" />
>     </span>)
>    }} />
> ```

This code works fine,get what I want, replace the default "No data" image and text

**Comment by shamseerahammedm** [comment]
`locale={{ emptyText: 'Please upload a file' }}`
this removes the image how ever ?

**Comment by nirvdrum** [comment]
@shamseerahammedm Unfortunately, it looks like you need to supply your own `Empty` component if you want the image:

```
locale = {{emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Please upload a file" />}}
```

I agree that's unintuitive. If I hadn't come across https://github.com/ant-design/ant-design/issues/7690#issuecomment-479299603, I'd still be looking for an answer.

**Comment by Maxamillian** [comment]
I think this solution feels more intuitive to me: https://ant.design/components/empty/#components-empty-demo-config-provider

**Comment by LL-yibei** [comment]
> .ant-table-placeholder { display: none; } Works in Angular.

it works in React too
