### ISSUE TITLE
`defaultSearchChange` on the Mention component hits exception when suggestions is of type `Nav`

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#7696]
### Version
2.13.2

### Environment
MacOS, Chrome 61

### Reproduction link
[https://codepen.io/sk_tectus/pen/OxRVgx](https://codepen.io/sk_tectus/pen/OxRVgx)

### Steps to reproduce
- Add the Mention component with the input suggestions being an array of `Mention.Nav`
- Add an `onChange` handler
- Try to tag someone

On the console you end up with the following error:
`suggestion.toLowerCase is not a function`

### What is expected?
No exception

### What is actually happening?
The error is on this particular line:
https://github.com/ant-design/ant-design/blob/master/components/mention/index.tsx#L83

**Comment by kappa-gooner** [comment]
@benjycui @RaoHai 

Oops! I submitted a fix for this w/o check the status here.
Feel free to merge/discard.

Thanks!

**Comment by RaoHai** [comment]
closed via #7701
