### ISSUE TITLE
Mixins 何去何从

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#770]
随着 ES6 普及度的提高，关于 Mixins 的问题应该会增加。

1. https://github.com/ant-design/ant-design/issues/514
1. https://github.com/ant-design/ant-design/issues/693
1. https://github.com/ant-design/ant-design/issues/721
1. https://github.com/ant-design/ant-design/issues/708#issuecomment-167378207

目前找到两个方案：

1. [使用高阶组件](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.472vr8nb9)
1. 使用 [ReactMixin](https://github.com/brigand/react-mixin)

个人倾向用 高阶组件，不过 @yiminghe 好像对 ES6 的语法持保留态度？

**Comment by afc163** [comment]
1. 内部实现可以保持现状。
2. 外部对 Mixins 的依赖去除，现在只有 Form 组件使用了这种用法吧。用 rc-form 重写后应该可以去掉。 http://react-component.github.io/form/

**Comment by benjycui** [comment]
Validation 也是用也 Mixins 的 http://ant.design/components/validation/#demo-basic

**Comment by afc163** [comment]
恩，Validation 就是要改造的对象。

**Comment by zhaozhiming** [comment]
高阶组件+1
