### ISSUE TITLE
Singleton Modal

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#7700]
### What problem does this feature solve?
how can I make a  Singleton Modal

### What does the proposed API look like?
how can I make a singleton Modal.conifrm()

**Comment by yesmeck** [comment]
What is a "Singleton Modal"?

**Comment by nai6514531** [comment]
there is only a modal.confirm at the same time。not evvery time trigger the modal.confirm method
to show a  modal .

**Comment by yesmeck** [comment]
I suggest you implement this feature by you self.


```javascript
let confirming = false;
function myConfirm() {
  if (!confirming) {
    Modal.confirm({
      onOk() { confirming = false; },
      onCancel() { confirming = false; }
    });
    confirming = true;
  }
}
```
