### ISSUE TITLE
Tabs组件，关闭图标优化

### ISSUE THREAD

**Issue by LarryLee8** [ant-design/ant-design#7704]
### What problem does this feature solve?
用这个框架做了四个项目了，都是管理平台性质的，都用了Tabs标签页，方便操作。之前老版本的Tabs标签页关闭图标有一点样式修饰，比较大一些，还是容易一次性关闭的。新版本关闭的图标有些小，不方便操作，容易点不上，希望通过自定义关闭组件的方式让用户自己觉得这个关闭图标的大小。

### What does the proposed API look like?
对Tabs组件增加用户自定义关闭图标的API

**Comment by afc163** [comment]
You can override styles: https://codepen.io/anon/pen/mBrRRL?editors=0110
