### ISSUE TITLE
Upload 组件构造函数写法错误

### ISSUE THREAD

**Issue by shirleyYing** [ant-design/ant-design#7706]
### Version
2.8.1

### Environment
window7 , IE9 

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx)

### Steps to reproduce
构造函数中，应该使用props，而不是this.props. 这个不规范的写法导致IE9 无法找到fileList属性。希望改正
```
 constructor(props) {
    super(props);
    this.state = {
      fileList: this.props.fileList || this.props.defaultFileList || [],
      dragState: 'drop',
    };
  }
```

### What is expected?
希望改正写法错误

### What is actually happening?
程序能够正常运行

---
IE9 下上传组件不可用。注意，是IE9 浏览器，IE11模拟IE9可能不能重现

**Comment by yesmeck** [comment]
亲测没问题，这个写法也没有不规范。

**Comment by shirleyYing** [comment]
@yesmeck 看一下官方的说明。super（props）已经继承，就应该使用props,而不是 this.props
https://facebook.github.io/react/docs/react-without-es6.html
![image](https://user-images.githubusercontent.com/12593649/30735178-98abaf82-9fb0-11e7-83f7-b1479d4f3600.png)

**Comment by yesmeck** [comment]
一样的。

**Comment by shirleyYing** [comment]
高级浏览器没有问题，但是在IE9下确实是会报错的，而且我看了你们其他组件，都没有使用你的这种写法，都是标准写法

**Comment by yesmeck** [comment]
看看你的报错。

**Comment by shirleyYing** [comment]
![image](https://user-images.githubusercontent.com/12593649/30735462-bad2bbb8-9fb1-11e7-95a0-c22ffce10d3d.png)

**Comment by yesmeck** [comment]
官网的例子吗？

**Comment by shirleyYing** [comment]
参考文章 https://segmentfault.com/a/1190000006929961
这篇文章也说到了这个问题

**Comment by shirleyYing** [comment]
`
  render() {
    let uploadParams = {
      name: 'file',
      action: '//jsonplaceholder.typicode.com/posts/',
      headers: {
        authorization: 'authorization-text',
      },
      onChange(info) {
        console.log('info',info)
      },
    };

  return (
<div className="applist">
    
    <Upload {...uploadParams}>
          <Button>
             Click to Upload
          </Button>
    </Upload>
    
    </div>)
`

**Comment by afc163** [comment]
这是个坑，constructor 下面访问 this.props 在 IE9/10 下会有问题。

**Comment by yesmeck** [comment]
链接是因为 `Test2` 继承了 `Test` 才出错啊。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1492

**Comment by shirleyYing** [comment]
@afc163 感谢，最后采用 babel-preset-es2015-ie插件的方式解决。同时也希望 @yesmeck 能够修改下。毕竟写法确实有问题。
