### ISSUE TITLE
How do I make the selector dropdown close to the select?

### ISSUE THREAD

**Issue by funreading** [ant-design/ant-design#7707]
### What problem does this feature solve?

![avatar](https://raw.githubusercontent.com/funreading/img/master/8DC8A0F1-55F5-4116-A173-860884197B79.png)
In the antd, He has a gap

When I remove the box-shadow, the gap will look bigger
[https://codepen.io/funya/pen/dVppQB?editors=0100](https://codepen.io/funya/pen/dVppQB?editors=0100)

I tried to give dropdown Style set marginTop - 5, but failed

### What does the proposed API look like?

![avatar](https://raw.githubusercontent.com/funreading/img/master/QQ20170922-151321.png)

This is the style I want

Can u give me some advice to solve this problem? thank you

**Comment by yesmeck** [comment]
The offset is hard coded in https://github.com/react-component/select/blob/fdc0dae366b470fd7184471ce45a03f197b4c4ea/src/SelectTrigger.jsx#L22

I think you can use js change  the `top` property dynamically.

**Comment by afc163** [comment]
Sorry, It can't. It follows Ant Design specification.

**Comment by bn-pshulga** [comment]
Hello @afc163 !
Hope you are doing well , is problem is still exist and will not be solved ?
thank you!

**Comment by bn-pshulga** [comment]
Sorry , problem can be solved with 

 dropdownAlign={{ offset:[20,16 ] }}
