### ISSUE TITLE
Icon button with loading state still displays incorrectly.

### ISSUE THREAD

**Issue by gavinrobertszeco** [ant-design/ant-design#7709]
### Version
2.13.2

### Environment
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/gRoberts84/pen/aLmWmr?editors=0010](https://codepen.io/gRoberts84/pen/aLmWmr?editors=0010)

### Steps to reproduce
1. Add Icon Button with loading enabled (`<Button icon="pause" loading={true} />`) 
2. Add a Button Group with one or more Icon Buttons with loading enabled.

### What is expected?
Loading icon should replace the existing icon without changing the dimensions of the underlying button.

### What is actually happening?
If the Button is outside of a Button Group, or the first in a Button Group, too much left padding is applied.
If the Button is within a Button Group but not the first button, not enough left padding is applied.

---
Related to my previously reported issue - #6822

**Comment by afc163** [comment]
Your codpen is not Icon but Table in it anymore..

**Comment by gavinrobertszeco** [comment]
Hi @afc163 ,

Sorry about that, I had accidentally overwritten it.

I have recreated the issue within the existing codepen, however here is the link just in case:

https://codepen.io/gRoberts84/pen/aLmWmr?editors=0010

Many thanks
