### ISSUE TITLE
DatePicker使用问题

### ISSUE THREAD

**Issue by JiangAmber** [ant-design/ant-design#771]
使用0.11版本的Datepicker 改写以前的DatePicker 发现了一个小问题
```jsx
<DatePicker
        showTime
        format="yyyy-MM-dd HH:mm"
        onChange={this._handleChange}
        locale={locale}
        value={dateTime} />
```
在设置format为`"yyyy-MM-dd HH:mm`以后，选择时间依然会出现秒钟。
![image](https://cloud.githubusercontent.com/assets/6375421/12031903/20d75b7e-ae4d-11e5-991a-2ca336906225.png)
请问怎么解决  谢谢

**Comment by JiangAmber** [comment]
还有一个问题  Daterange设置了locale以后  时间的placeholder依然是中文
![image](https://cloud.githubusercontent.com/assets/6375421/12032242/05d755fa-ae51-11e5-8900-fd9faf0f674d.png)

**Comment by afc163** [comment]
第二个问题：https://github.com/ant-design/ant-design/blob/0ee47a3538245ccf211fe533e22eb01c3e82c5ae/components/date-picker/locale/en_US.js#L8

这里漏了 timePlaceholder

https://github.com/ant-design/ant-design/blob/0ee47a3538245ccf211fe533e22eb01c3e82c5ae/components/date-picker/locale/zh_CN.js#L9

可以自行设置，也欢迎 PR。

**Comment by JiangAmber** [comment]
恩 谢谢

**Comment by JiangAmber** [comment]
那么请问第一个问题如何解决呢  就是时间选择框可以自定义选择小时、分钟、和秒钟

**Comment by benjycui** [comment]
@afc163 现在的实现，`DatePicker` 里的 `TimePicker` 基本上是不可配置的

See: https://github.com/ant-design/ant-design/blob/master/components/date-picker/index.jsx#L59

**Comment by afc163** [comment]
暂不支持，需要进一步配置的，直接和 TimePicker 分开配合。
