### ISSUE TITLE
Change defaultLocale to English one

### ISSUE THREAD

**Issue by ojab** [ant-design/ant-design#7711]
### What problem does this feature solve?
Right now default locale is zh-cn, but English is more accessible for wide audience.
AFAIU it's already planned (comment [here](https://github.com/ant-design/ant-design/blob/master/components/_util/getLocale.tsx#L7) and ` The default language of antd@2.x is still Chinese yet. ` in i18n docs), but I can't find an issue to subscribe in order to track if it's done yet, so creating this one.

### What does the proposed API look like?
--

**Comment by afc163** [comment]
trace #7553
