### ISSUE TITLE
Select选择器中 defaultValue属性 无法选中遍历得到的option的value属性，但可以选中

### ISSUE THREAD

**Issue by devmsg** [ant-design/ant-design#7714]
### Version
2.13.3

### Environment
系统版本:10.12.6 (16G29)  浏览器版本: 61.0.3163.100（正式版本） （64 位）

### Reproduction link
[https://crs.devmsg.com](https://crs.devmsg.com)

### Steps to reproduce
如题

### What is expected?
正常结果

### What is actually happening?
只能是defaultValue的默认值，没有对应上 option 的值，但确确实实是选中了

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
close for no response.
