### ISSUE TITLE
Mention component is displaying text in single-line mode in wrong way

### ISSUE THREAD

**Issue by xorandiff** [ant-design/ant-design#7717]
### Version
2.13.3

### Environment
Linux, Chrome 59.0.3071.115 64bit

### Reproduction link
[https://ant.design/components/mention/#components-mention-demo-controllder-simple](https://ant.design/components/mention/#components-mention-demo-controllder-simple)

### Steps to reproduce
Just type a long text that exceeds space of input shown in 'controlled mode example', it breaks out of input boundaries and goes to new line.

### What is expected?
Text should behave just like in regular `<input>` element, it shouldn't create new lines with `multiLines` set to `false` as default.

### What is actually happening?
![zrzut ekranu-20170924040841-647x149](https://user-images.githubusercontent.com/29928305/30778754-1b8409e4-a0de-11e7-8125-6a4feb426b5e.png)

Input is behaving just like multi-line textbox and it shouldn't.

**Comment by yesmeck** [comment]
Fixed in 3.0
