### ISSUE TITLE
Ability to place Arrow icon to the right of Collapse Panel

### ISSUE THREAD

**Issue by marquezgon** [ant-design/ant-design#7719]
### What problem does this feature solve?
I am trying to find a way to position the _arrow icon_ to the right of the panel inside a Collapse component but the API does not provide an option to do that. It would be great if Panel provided you the option to choose where to align the arrow icon.

### What does the proposed API look like?
`<Collapse>
<Panel arrow="right" header="This is panel header 1" key="1">
...
</Panel>
</Collapse>`

**Comment by benjycui** [comment]
Just override the CSS.

antd will follow the Ant Design Specification, if you want something that against the specification, just override CSS.

**Comment by Migggz** [comment]
+1

**Comment by osamasayed** [comment]
You can add property `expandIconPosition` to `Collapse`. e.g.:

`<Collapse expandIconPosition="right">....</Collapse>`

**Comment by Maikel-Nait** [comment]
> Just override the CSS.
> 
> antd will follow the Ant Design Specification, if you want something that against the specification, just override CSS.

At least it would be great to provide an example, and what exact CSS styles should be overriden

**Comment by allan2** [comment]
@Maikel-Nait `expandIconPosition` does what you need just like his example line.
Although an example could be added to the docs to show this feature

**Comment by anuragpal211** [comment]
how to use expandIconPosition in a functional component .please provide me a solution

**Comment by sohedev** [comment]
the props `expandIconPosition`  is not supported in rtl langs :/
