### ISSUE TITLE
In the form, Select or Cascader component still trigger the validation or focus style when set the disabled is true

### ISSUE THREAD

**Issue by yzuoran** [ant-design/ant-design#7720]
### Version
2.13.3

### Environment
React version 15.6.1;Chrome version 60.0.3112.101

### Reproduction link
[https://codepen.io/zuoran/pen/ZXBeOB](https://codepen.io/zuoran/pen/ZXBeOB)

### Steps to reproduce
create a from containing Input/Select/Cascader components;
set all field required/disabled and make the validate trigger is 'onBlur';
check the style when the field blur.

### What is expected?
all field should not trigger validation or focus style when the disabled is true.

### What is actually happening?
the Select trigger the required validation(specially trigger with click the border and blur );
the Cascader trigger the focus style;
only the Input has no problem.

**Comment by afc163** [comment]
Your codpen can't even work.

**Comment by afc163** [comment]
Try reinstall node_modules.

**Comment by yzuoran** [comment]
@afc163 sorry ,the codepen has fixed...  also, has reinstalled and no problem now. thank  you .
