### ISSUE TITLE
Setting <Select/> mode to tags or multiple makes no difference

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#7721]
### Version
2.13.3

### Environment
macOS 10.12.6, Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/tylerlong/pen/qPqXbp?editors=001](https://codepen.io/tylerlong/pen/qPqXbp?editors=001)

### Steps to reproduce
Open the link to check: https://codepen.io/tylerlong/pen/qPqXbp?editors=001

### What is expected?
The two <Select/> should behave differently because they have different mode ("tags" and "multiple")

### What is actually happening?
The two <Select/> behave identically

---
I didn't find any documentation about the difference between mode "tags" and mode "multiple". So what's the difference? Is it a bug that there are two duplicate modes?

**Comment by afc163** [comment]
It is different, `tags` can create new items by input text and press enter, `multiple` can't create new options.

**Comment by devuxer** [comment]
Should be in the documentation.

**Comment by devuxer** [comment]
@afc163 Should be in the documentation.

**Comment by lcoder** [comment]
用了antd三年了，今天才知道区别，哈哈哈
