### ISSUE TITLE
Flowtype support

### ISSUE THREAD

**Issue by dperetti** [ant-design/ant-design#7722]
### What problem does this feature solve?
Provide Flow type checking and code suggestions.

### What does the proposed API look like?
We just need a libdef like described here. https://flow.org/en/docs/libdefs/
It shouldn't be very complicated to achieve since it can probably be generated from Typescript definitions.

**Comment by benjycui** [comment]
> it can probably be generated from Typescript definitions.

Could your create a PR? Thanks.

**Comment by afc163** [comment]
I think we won't support it. Typescript is enough and better.

**Comment by dperetti** [comment]
"Better" you might think it is, not everybody shares that opinion. But that's not even the point. Nobody is asking you to move to javascript + Flow. You can and should, of course, keep going with Typescript.
This ticket was just about providing _libdefs_ files for Flow compatibility, which I'm sure would delight many, many users in a near future.

**Comment by afc163** [comment]
> providing libdefs files for Flow compatibility

That is always welcome if someone could help us to make it happen. Feel free to propose a PR for it. I just say this is not our first priority now.

**Comment by soulmachine** [comment]
+1

**Comment by rahulthewall** [comment]
Did someone manage to generate the libdefs files?

**Comment by kishoremvrs** [comment]
https://github.com/rj254/antd-flow-types

Someone wrote some flow types.

Can someone validate these?

**Comment by adelespinasse** [comment]
It seems like there are Flow type definitions in the official `flow-typed` repo now:

https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/antd_v3.x.x/flow_v0.104.x-

I have no idea how well they work (have not tried them).
