### ISSUE TITLE
InputItem普通输入框无法输入东西

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design#7725]
### What problem does this feature solve?
普通文本的输入

### What does the proposed API look like?
能够输入文本

**Comment by yesmeck** [comment]
I believe you are encountering this problem https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action

**Comment by yesmeck** [comment]
And if you are reporting a bug, please use the bug template.

**Comment by SanPy** [comment]
I did not set the value of InputItem

**Comment by yesmeck** [comment]
Then you should use the bug form to report a bug.

**Comment by SanPy** [comment]
i have report this problem again by that you said!

**Comment by afc163** [comment]
Then you should report a bug with our bug-report template.
