### ISSUE TITLE
dropdown在trigger为click的情况下可否保持下拉框只受Button的click事件控制

### ISSUE THREAD

**Issue by vonxq** [ant-design/ant-design#7727]
### What problem does this feature solve?
在dropdown中做了一个Checkbox Group，但每次选择都会导致dropdown关闭，自己在checkbox中阻止冒泡也没用。尝试过自己控制dropdown的visible，但这样的话无法做到不操作dom实现点击其它地方关闭dropdown，还是希望原生能提供一个这样的效果，trigger是click按逻辑来说下拉框内部变化也不该触发dropdown的click啊

### What does the proposed API look like?
希望dropdown在trigger是click的情况下，只根据button的click来控制下拉框的显示，下拉框内的click不影响下拉框状态

**Comment by afc163** [comment]
https://ant.design/components/dropdown/#components-dropdown-demo-overlay-visible
