### ISSUE TITLE
表单验证输入框下面的提示文字有动画卡顿

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#7730]
### Version
2.13.3

### Environment
MacOs sierra 10.12.5  npm5.3.0

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
随便在一个require为true的输入框，先随便输入，然后删除刚才的输入，（此时下面会有红色提示），再随便输入文字，可以看到红色的提示先变成灰色 ，然后消失的过渡，会卡一下

### What is expected?
不卡那一下

### What is actually happening?
-。- 有肉眼可见的停顿

**Comment by ouzhou** [comment]
Email那个居然没有问题，第二个password是有问题的

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/7cfd9b2bcb982007c563921c9a8d865f435927a8
