### ISSUE TITLE
When column is kept fixed, render function is triggered every time

### ISSUE THREAD

**Issue by tushariscoolster** [ant-design/ant-design#7732]
### Version
2.13.3

### Environment
chrome

### Reproduction link
[https://codepen.io/tushariscoolster/pen/Nadaev](https://codepen.io/tushariscoolster/pen/Nadaev)

### Steps to reproduce
1) add   fixed: 'right' in any column
2(   render(text, record, index) {
console('this function is triggered multiple times on hover of coummn')
          return moment(record.startTimeStr).format('h:mm a');
        },

### What is expected?
it should not trigger on hover

### What is actually happening?
Function trigger on over when fixed:right is set

**Comment by yesmeck** [comment]
It's a known behavior and this is how fixed column implements (we render two tables). Does this behavior cause any actual problem to you?

**Comment by tushariscoolster** [comment]
@yesmeck  iWhy do you want to re-render on hover. IF user uses multiple renders in the table, all the render will be triggered, which will cause a performance problem, Don't you think so?

**Comment by yesmeck** [comment]
We need sync hover status between two tables, this should not cause performance problem, because only the mouseenter and mouseleave row will rerender.

**Comment by tushariscoolster** [comment]
@yesmeck Ok, you can close this issues, I will customize this setting in fork repo
