### ISSUE TITLE
dropdown can't popup when change it's container node.

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#7737]
### Version
2.13.3

### Environment
MacOS 10.12.6 (16G29), Chrome  60.0.3112.101

### Reproduction link
[https://codepen.io/leadream/pen/NadyOg?editors=0010](https://codepen.io/leadream/pen/NadyOg?editors=0010)

### Steps to reproduce
1、set dropdown's container as is parent node, by `getPopupContainer={() => this.container}`.
2、use `visible` and `handleVisibleChange` to make dropdown menus not hidden when clicking menu.
3、click the trigger button.
4、it can't pop up normally.

### What is expected?
the dropdown menus pops up correctly.

### What is actually happening?
it can't pop up.

**Comment by nikogu** [comment]
@leadream i think you should when dom mount then set the `refs`.

you can see the error in console. `Cannot read property 'appendChild' of null`

**Comment by leadream** [comment]
@nikogu yes, I solved like this way.
