### ISSUE TITLE
Add showCheckedItem to TreeSelect

### ISSUE THREAD

**Issue by zlk89** [ant-design/ant-design#7738]
### What problem does this feature solve?
We don't always want to show selected nodes inside the input box.

Why?
There are at least two use cases needs custom display of selected nodes:
1. When there are a lot of options, and user might choose a large number of nodes like the example below, which looks bad, and hard for user to locate any node.

example:
<img width="334" alt="screen shot 2017-09-25 at 10 16 03 pm" src="https://user-images.githubusercontent.com/7234480/30843663-8c192380-a23f-11e7-8c3d-614e8562fcca.png">

2. For TreeSelect, we would like to show hierarchy of selected nodes, instead of just putting everything as same level inside the input box.

### What does the proposed API look like?
Just add one new `showCheckedItem` to hide control nodes inside input box, and this allows developers to customize the display of selected node, like this:
<img width="484" alt="screen shot 2017-09-25 at 9 33 39 pm" src="https://user-images.githubusercontent.com/7234480/30842736-42a7921e-a239-11e7-83cc-9b3eaa1f02d3.png">

**Comment by afc163** [comment]
I think you are using rc-tree-select other than antd TreeSelect, maybe you can file this to http://github.com/react-component/tree-select

**Comment by zlk89** [comment]
@afc163 I have updated the example using TreeSelect. Actually I am using TreeSelect, but I was using an example of rc-tree-select for demo. This change has to be made in the rc-tree-select repo, because TreeSelect simply is a wrapper of rc-tree-select.

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by zlk89** [comment]
Just simply don't show those control nodes inside input box. And let user to render any format of selected nodes outside of TreeSelect. 

For the example above,
passing `showControlNode= { false }`, this would make TreeSelect input box always shows the placeholder:
<img width="491" alt="screen shot 2017-09-25 at 10 26 15 pm" src="https://user-images.githubusercontent.com/7234480/30843831-91496562-a240-11e7-9bda-8ac556bf1d49.png">

And user can show customized result like:
<img width="269" alt="screen shot 2017-09-25 at 10 27 26 pm" src="https://user-images.githubusercontent.com/7234480/30843879-ce5ea188-a240-11e7-931a-ef2c7643cc2a.png">

**Comment by afc163** [comment]
```diff
- showControlNode
+ showCheckedStrategy={TreeSelect.SHOW_NONE}
```

**Comment by zlk89** [comment]
Right! That's much better, and won't introduce one more prop.
If you are agreed with this feature, I can start work on a PR for this.

**Comment by afc163** [comment]
Ok, you can start with rc-tree-select and then add this feature to branch antd-3.0.

**Comment by zlk89** [comment]
@afc163 Just did some deep dive into the code.
The state `value` in the component `Select` is depends on `showCheckedStrategy`. As you can see [here](https://github.com/zlk89/tree-select/blob/master/src/Select.jsx#L533-L542), and `onChange` also depends on `this.state.value`. So we cannot return empty value in `getValue`, otherwise, there is no way to get value from `onChange`. Instead we have to hide control nodes directly in `renderTopControlNode`.
This would work, but this also would give user only choice 'SHOW_CHILD' [here](https://github.com/zlk89/tree-select/blob/master/src/Select.jsx#L541). However, users might want to get values of strategy `SHOW_PARENT`.

So we might still need a new prop?

**Comment by afc163** [comment]
I see that, you are right, naming of `showCheckedStrategy` is a little confused.

You can try adding a `showCheckedItem`.

**Comment by gzc** [comment]
It's a very useful feature!

**Comment by zombieJ** [comment]
Close old issue since TreeSelect support `treeCheckStrictly` already.

**Comment by zlk89** [comment]
@zombieJ Hi, will `treeCheckStrictly` hide those selected node inside of the input field?

**Comment by zombieJ** [comment]
hi @zlk89 , antd `3.7.0` TreeSelect provide the `maxTagCount` & `maxTagPlaceholder` props which can short this input in better way.

**Comment by dpradha** [comment]
@zlk89 @zombieJ , I checked that when maxTagCount = 0, it doesn't seem to work. Also, when we add maxTagPlaceholder to null, it still returns a box showing the number of items selected. What if you don't want to show what you've selected and just keep showing the placeholder? Would it be better to add another functionality to maxTagPlaceholder? If maxTagPlaceholder = false, then set maxTagCount = 0. That way, I can do minor tweaks in the renderPlaceholder and renderSelection for the MultipleSelector's index

**Comment by zombieJ** [comment]
@dpradha , Good point. I agree the `maxTagCount` should support `0` to only provide the `maxTagPlaceholder`. PR is welcome : )

**Comment by dpradha** [comment]
Awesome... I'll submit a PR soon. Thanks @zombieJ

**Comment by DongShi** [comment]
Hey @zlk89 @zombieJ 

A similar requirement drove me here: I wonder by now is it possible to let user to render the selected content or not ?

I find there is a 'displayRender' API  in the document for Cascader component (https://ant.design/components/cascader/), but there is no similar API in either Select or TreeSelect...

Thanks you.

**Comment by bspatil0001** [comment]
Any update on the above feature request?
