### ISSUE TITLE
GetValueFromEvent method in Form components  

### ISSUE THREAD

**Issue by iceOolongTea** [ant-design/ant-design#7741]
### Version
2.11.2

### Environment
macOS 10.12 chrom 60 

### Reproduction link
[https://codepen.io/anon/pen/vegVOM?editors=0010](https://codepen.io/anon/pen/vegVOM?editors=0010)

### Steps to reproduce
open console,then input some value,and check the log

### What is expected?
i expect an "event" in function handleWriteBack

### What is actually happening?
https://github.com/react-component/form#option-object    In Select components ,it will be a value by using getValueFromEvent. But in Radio  and Input Components, it will be an "event".
document looks like have problem about using getValueFromEvent in form components

---
i try to using getValueFromEvent to solve dynamically add FormItem.so i use handleWriteBack to catch event and set form's data.

**Comment by benjycui** [comment]
Just remove `getValueFromEvent` for Select.
