### ISSUE TITLE
设置 selectedRowKeys 后，表格的checkBox 功能就失效了

### ISSUE THREAD

**Issue by sisiea** [ant-design/ant-design#7745]
### Version
2.13.3

### Environment
系统 win7 浏览器 chrome 60.0.3112.113 

### Reproduction link
[https://codepen.io/sisiea/pen/oGZWMO](https://codepen.io/sisiea/pen/oGZWMO)

### Steps to reproduce
直接去点击 checkbox 

### What is expected?
正常的 勾选表格结果

### What is actually happening?
无法勾选 或者 取消勾选

---
项目中使用的 版本是 1.11.2 的版本，我以为新版本已经解决这个问题。但是我拿2.13.3 的库文件也还是出现这个问题。最后能给出 在 1.11.2 如何修复这个bug的方法。

**Comment by afc163** [comment]
It is not a bug, you should learn about React controlled component first.

https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action
