### ISSUE TITLE
antd升级到2.13.3版本后，Upload组件 accept的文件类型不匹配不会发请求，而之前版本如2.12会发请求

### ISSUE THREAD

**Issue by sam-dingkang** [ant-design/ant-design#7746]
### Version
2.13.3

### Environment
所有

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/f0afa394](https://riddle.alibaba-inc.com/riddles/f0afa394)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/f0afa394 将版本改成2.12会发请求

### What is expected?
最新版本也应该兼容老版本，accept的文件类型不匹配也应该发请求

### What is actually happening?
2.13.3版本Upload组件accept的文件类型不匹配不会发请求给服务端

**Comment by ayiaq1** [comment]
accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
