### ISSUE TITLE
RangePicker - didn't hide picker panel automatically when click presupposed ranges.

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design#7747]
### Version
2.13.3

### Environment
Mac, Chrom 版本 60.0.3112.113（正式版本） （64 位）

### Reproduction link
[https://codepen.io/yutingzhao1991/pen/NapaVj?editors=0010](https://codepen.io/yutingzhao1991/pen/NapaVj?editors=0010)

### Steps to reproduce
Click to open RangePicker panel, then click presupposed ranges. Panel didn't hide automatically.

### What is expected?
Panel hidden automatically.

### What is actually happening?
Panel didn't hide automatically.

---
点击RangePicker中预置的时间范围，选择面板没有自动隐藏。鼠标hover到预置的时间范围的时候确定按钮是置灰的，这种情况应该是用户不需要再去手动点击确定，而是直接隐藏选择面板并触发onOk。

**Comment by benjycui** [comment]
> 鼠标hover到预置的时间范围的时候确定按钮是置灰的

这个交互是有问题，确认按钮应该是蓝色才对。但不关闭时正常的。

**Comment by afc163** [comment]
应该始终关闭的，presets range 是快键方式，应该自带 ok 按钮的交互属性，否则就不够『快键』了。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/7841386fcd46a882ff70b99fe0e7c003000de59a#commitcomment-25229144

@afc163 所以在点击预设值时，也同时出发 onOk？

**Comment by Da-Sheng** [comment]
@benjycui 我翻到了这个问题，借楼问一下，我在点击预设值时，onOk没触发，只是触发了onChange，请问怎么处理
