### ISSUE TITLE
When inline Menu inlineCollapsed={true} initial , defaultOpenKeys will effective in the wrong way.

### ISSUE THREAD

**Issue by cxyxc** [ant-design/ant-design#7748]
### Version
2.13.3

### Environment
win10、Chrome 版本 59.0.3071.115（正式版本） （32 位）

### Reproduction link
[https://codepen.io/cxyxc/pen/OxpxKb?editors=0010](https://codepen.io/cxyxc/pen/OxpxKb?editors=0010)

### Steps to reproduce
```javascript
import React from 'react'
import { Menu, Icon, Button } from 'antd';
const SubMenu = Menu.SubMenu;

class App extends React.Component {
  state = {
    collapsed: true,
  }
  toggleCollapsed = () => {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  }
  render() {
    return (
      <div style={{ width: 240 }}>
        <Button type="primary" onClick={this.toggleCollapsed} style={{ marginBottom: 16 }}>
          <Icon type={this.state.collapsed ? 'menu-unfold' : 'menu-fold'} />
        </Button>
        <Menu
          defaultSelectedKeys={['1']}
          defaultOpenKeys={['sub1']}
          mode="inline"
          theme="dark"
          inlineCollapsed={this.state.collapsed}
        >
          <Menu.Item key="1">
            <Icon type="pie-chart" />
            <span>Option 1</span>
          </Menu.Item>
          <Menu.Item key="2">
            <Icon type="desktop" />
            <span>Option 2</span>
          </Menu.Item>
          <Menu.Item key="3">
            <Icon type="inbox" />
            <span>Option 3</span>
          </Menu.Item>
          <SubMenu key="sub1" title={<span><Icon type="mail" /><span>Navigation One</span></span>}>
            <Menu.Item key="5">Option 5</Menu.Item>
            <Menu.Item key="6">Option 6</Menu.Item>
            <Menu.Item key="7">Option 7</Menu.Item>
            <Menu.Item key="8">Option 8</Menu.Item>
          </SubMenu>
          <SubMenu key="sub2" title={<span><Icon type="appstore" /><span>Navigation Two</span></span>}>
            <Menu.Item key="9">Option 9</Menu.Item>
            <Menu.Item key="10">Option 10</Menu.Item>
            <SubMenu key="sub3" title="Submenu">
              <Menu.Item key="11">Option 11</Menu.Item>
              <Menu.Item key="12">Option 12</Menu.Item>
            </SubMenu>
          </SubMenu>
        </Menu>
      </div>
    );
  }
}

export default App;
```

### What is expected?
when inlineCollapsed={true} SubMenu in defaultOpenKeys is closed, and inlineCollapsed={false} is open

### What is actually happening?
be just reversed.

---
I want my Menu inlineCollapsed={true} when user set it.

**Comment by cxyxc** [comment]
inlineCollapsed={true}
![image](https://user-images.githubusercontent.com/20027281/30899219-98d62412-a391-11e7-9ea4-81926514196a.png)

**Comment by afc163** [comment]
I think that is correct result for respecting the defaultOpenKeys.

You should not pass `defaultOpenKeys` to Menu when `inlineCollapsed={true}`.

**Comment by cxyxc** [comment]
But when inlineCollapsed={false} initial, and then I click Button to set inlineCollapsed={true}.like this:
![image](https://user-images.githubusercontent.com/20027281/30899438-73e512a2-a392-11e7-8535-cbcec2fd4889.png)

![image](https://user-images.githubusercontent.com/20027281/30899444-7e035ca8-a392-11e7-9e0a-25c9b780a32b.png)

**Comment by cxyxc** [comment]
when inlineCollapsed={true} initial, I click Button to set inlineCollapsed={false}.like this:
![image](https://user-images.githubusercontent.com/20027281/30899505-b377ac86-a392-11e7-9849-a45de194b836.png)

![image](https://user-images.githubusercontent.com/20027281/30899515-b93d9ae0-a392-11e7-87a9-9bd448706d81.png)

**Comment by cxyxc** [comment]
If not pass defaultOpenKeys to Menu when inlineCollapsed={true}. When I click Button to set inlineCollapsed={false}. I can not set defaultOpenKeys to expand SubMenu. It is true?

**Comment by afc163** [comment]
You can pass `openKeys` for `inlineCollapsed={false}` and remove it when `inlineCollapsed={true}`, that is my workaround.

**Comment by cxyxc** [comment]
Let me have a try. Thanks a lot.

**Comment by georgehpj** [comment]
Set openKeys to **undefined** or **null** is not working. I have to do like this
`const menuProps = isCollapsed ? {inlineCollapsed: true} : {inlineCollapsed: false, openKeys}
 <Menu {...menuProps} />
`
not cool for the `if ('openKeys' in props)`.
