### ISSUE TITLE
2.13.3版表单效验导致出现表单间距缩放问题

### ISSUE THREAD

**Issue by RecallCode** [ant-design/ant-design#7752]
### Version
2.13.3

### Environment
win7 chrome55

### Reproduction link
[https://stackblitz.com/edit/react-rwrqvx](https://stackblitz.com/edit/react-rwrqvx)

### Steps to reproduce
1. 不要进行输入,直接点击登录, 会出现效验错误信息
2. 在出错的输入框内输入内容, 在输入内容的瞬间.表单之间的间距会增加然后再恢复回来.

### What is expected?
不出现上述描述的缩放问题

### What is actually happening?
存在表单之间间距瞬间缩放问题

---
2.13.2版本中并没有发现这个问题

**Comment by afc163** [comment]
#7730
