### ISSUE TITLE
Probably a use case not a bug - using tabs inside expandedRow in a table, with lots of tabs

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#7753]
### Version
2.13.3

### Environment
ubuntu 16, google chrome version 61.0.3163.100

### Reproduction link
[https://codepen.io/anon/pen/qPrYrr?editors=001](https://codepen.io/anon/pen/qPrYrr?editors=001)

### Steps to reproduce
return a component that renders tabs in the  expandedRowRender method of a table, and the number of tabs makes it wider than it's container

### What is expected?
tabs should be scrollable

### What is actually happening?
tabs are not scrollable, and the last tabs are hidden and not accessible at all

**Comment by afc163** [comment]
https://codepen.io/anon/pen/QqpBpQ?editors=0110

Here is a temporary workaround to make a fixed layout for table, then the cell width would not extend as it's content.

**Comment by AhmedSayed77** [comment]
Thanks, but sadly this will not work for me. I'm building a mobile friendly app, and in small sized window I hide all columns except the first - removing the margin and padding from the hidden column. setting table-layout: fixed will prevent my css on the columns from working

**Comment by afc163** [comment]
You can also try `<Tabs style={{ maxWidth: '100vw' }} />`, the value of `vw` depends on your column width.

**Comment by AhmedSayed77** [comment]
part of the tabs was still invisible, but `<Tabs style={{ maxWidth: '76vw' }} />` did work - because of the empty part at the left under the [+] button. Thanks alot (Y)
