### ISSUE TITLE
Warning when using Menu component and latest react(v16)

### ISSUE THREAD

**Issue by filtudo** [ant-design/ant-design#7754]
### Version
2.13.3

### Environment
Mac os, chrome 61.0.3163.100, antd 2.13.3, react "^16.0.0"

### Reproduction link
[https://stackblitz.com/edit/react-2axs8p?file=index.js](https://stackblitz.com/edit/react-2axs8p?file=index.js)

### Steps to reproduce
Install latest react version and react dom version
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "antd": "^2.13.3",

Create a basic menu component(stateless or class i tried both) 
 const Navigation = (() => {
     return (
         <Menu mode='horizontal'>
              <Menu.Item key="mail">
                     <Icon type="mail" />Navigation One
               </Menu.Item>
                <Menu.Item key="app" disabled>
                     <Icon type="appstore" />Navigation Two
              </Menu.Item>
        </Menu>
     );
 });

The menu get's rendered correctly
Check chrome console
Get following Warning for each menu component: 

Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.null

printWarning	@	warning.js:33
warning	@	warning.js:57
mountIndeterminateComponent	@	react-dom.development.js:10439
beginWork	@	react-dom.development.js:10601
performUnitOfWork	@	react-dom.development.js:12573
workLoop	@	react-dom.development.js:12682
callCallback	@	react-dom.development.js:1299
invokeGuardedCallbackDev	@	react-dom.development.js:1338
invokeGuardedCallback	@	react-dom.development.js:1195
performWork	@	react-dom.development.js:12800
scheduleUpdateImpl	@	react-dom.development.js:13185
scheduleUpdate	@	react-dom.development.js:13124
scheduleTopLevelUpdate	@	react-dom.development.js:13395
updateContainer	@	react-dom.development.js:13425
(anonymous)	@	react-dom.development.js:17105
unbatchedUpdates	@	react-dom.development.js:13256
renderSubtreeIntoContainer	@	react-dom.development.js:17104
hydrate	@	react-dom.development.js:17126
doRender	@	browser.tsx:46
(anonymous)	@	browser.tsx:98
./config/entry/browser.tsx	@	browser.js:501
__webpack_require__	@	bootstrap 44007e8…:711
fn	@	bootstrap 44007e8…:116
0	@	browser.js:4060
__webpack_require__	@	bootstrap 44007e8…:711
webpackJsonpCallback	@	bootstrap 44007e8…:25
(anonymous)	@	browser.js:1

### What is expected?
Don't receive any warning when using menu component and react v16

### What is actually happening?
Receive warning

**Comment by MR03** [comment]
same

**Comment by TDiDa** [comment]
same

**Comment by tjcprince** [comment]
same

**Comment by chenchengwork** [comment]
same

**Comment by zhangwang1990** [comment]
same

**Comment by benjycui** [comment]
WIP

**Comment by afc163** [comment]
#5377
