### ISSUE TITLE
Issue Helper's codepen template is broken

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#7756]
### Version
2.13.3

### Environment
Windows 10.0.15063 & Chrome 60.0.3112.113

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
open codepen link

### What is expected?
DatePicker appear

### What is actually happening?
Nothing on the page

### More info
This problem appears because React v16 changes file name. So `react` and `react-dom` lib get 404.

replace
```
https://unpkg.com/react/dist/react.js
https://unpkg.com/react-dom/dist/react-dom.js
```
with
```
https://unpkg.com/react@15.6.2/dist/react.js
https://unpkg.com/react-dom@15.6.2/dist/react-dom.js
```
would fix the issue.

**Comment by yesmeck** [comment]
@benjycui @afc163  Can we use codesanbox?

**Comment by benjycui** [comment]
Done, thanks!
