### ISSUE TITLE
The Select component can not be Select All when mode="multiple"

### ISSUE THREAD

**Issue by lxzhangchao** [ant-design/ant-design#7758]
### What problem does this feature solve?
When you use multiple options for select components, you select a large number of data, such as 100, and we need select all methods。

### What does the proposed API look like?
add selectAllLabel props ，we can set selectAllLabel props to add select all items ，and can select all items。

**Comment by yesmeck** [comment]
It's easy to archive by passing all data to `value`.

**Comment by lxzhangchao** [comment]
But the style doesn't change, and you can still select other options when you select all of them
![select all](https://user-images.githubusercontent.com/20981441/30951898-f48e6866-a457-11e7-9019-c57aedd3d883.png)

**Comment by yesmeck** [comment]
If you are reporting a bug, please use the bug report template.
