### ISSUE TITLE
ant-tree设置defaultExpandedKeys:false还是展开树节点

### ISSUE THREAD

**Issue by lgmcolin** [ant-design/ant-design#776]
![images](https://t.alipayobjects.com/images/rmsweb/T1OKpkXeXfXXXXXXXX.png)

初始化状态expandAll: true， 通过事件触发改变expandAll为false，发现tree节点还是展开的

- 代码：
```
<Tree  defaultExpandAll={this.state.expandAll} onCheck={this.handleCheck}  onSelect={this.handleSelect} defaultExpandedKeys={this.state.expandedKeys}>
      {this.state.treeNodes}
</Tree>
```

**Comment by benjycui** [comment]
对于 `defaultXXX` 这种属性，都只是在初始化的时候生效，你后面再改是没用的。

这样设计也是 React 的原则，see: https://facebook.github.io/react/docs/forms.html#default-value

**Comment by lgmcolin** [comment]
ok

**Comment by Restry** [comment]
@benjycui  @lgmcolin  请问那我如果想做一个全部展开或全部收缩的功能就只能用expandedKeys把所有的节点给添加进去？
