### ISSUE TITLE
type="password" 密码框在调试工具里的明文显示问题

### ISSUE THREAD

**Issue by zchuhui** [ant-design/ant-design#7761]
使用密码输入框，但密码却可以在调试工具直接看到，这个问题怎么整？
```
<Input  type="password" placeholder="密码" />
```

![image](https://user-images.githubusercontent.com/5125574/30953613-3e21965e-a45f-11e7-9fe8-6b7e4e600b4d.png)

**Comment by afc163** [comment]
It is a naive browser behaviors, I don't think there is anything we can do about it.
