### ISSUE TITLE
Input.Search组件 希望能在输入文字后显示一个清空按钮，并提供其回调方法

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design#7764]
### What problem does this feature solve?
Input组件做为输入框，在用户录入信息后，理应显示清空按钮，完善功能，提高用户体验。

### What does the proposed API look like?
期望添加参数onCancel，接收清除按钮的回调方法。

**Comment by nikogu** [comment]
you can control the `value`, then you can use `this.setState` to clean the value.
