### ISSUE TITLE
form表单域改进建议

### ISSUE THREAD

**Issue by bshy522** [ant-design/ant-design#7766]
### What problem does this feature solve?
1. 所有的表单域都应支持readOnly
2. 表单域如支持placeholder 时，在readOnly时 应不显示placeholder

### What does the proposed API look like?
无

**Comment by nikogu** [comment]
Using `disabled` ?

**Comment by yesmeck** [comment]
`readOnly` 跟 `disabled` 还是有不一样，可以讨论下。

**Comment by afc163** [comment]
https://github.com/callemall/material-ui/issues/6342#issuecomment-286902488
https://github.com/callemall/material-ui/pull/2289#issuecomment-161920496

**Comment by yesmeck** [comment]
想想确实没啥用。

**Comment by benjycui** [comment]
So close now.
