### ISSUE TITLE
Form表单绑定getFieldDecorator后有阻止用户输入的方法吗

### ISSUE THREAD

**Issue by internet5** [ant-design/ant-design#7772]
### What problem does this feature solve?
Form表单使用getFieldDecorator绑定字段后，目前有方法能够用户输入的时候，满足我自己定义的格式再显示在输入框里，不满足则不显示吗，如果不用getFieldDecorator很好实现，onChange里面决定是否setState，输入框绑定state就可以，使用getFieldDecorator后，试了很多方法都不行

### What does the proposed API look like?
希望能在onChange里面能够对当前输入框getFieldValue，或者能够直接返回false来阻止用户输入，如果返回值则当前输入框直接显示返回的值，或者其他解决办法

**Comment by internet5** [comment]
What problem does this feature solve?

Can I prevent inputing of user ,when form component used getFieldDecorator?
Just like setState any value in input's onChange without getFieldDecorator, then input bind the state. it can prevent the inputing that I dont hope, return the inputing that I hope.

What does the proposed API look like?

Hope in using getFieldDecorator, onChange can be prevent the inputing I dont want, and can return that  I want.

**Comment by hansnow** [comment]
maybe you need [options.getValueFromEvent](https://ant.design/components/form/#getFieldDecorator(id,-options)-parameters)

demo: https://codepen.io/hansnow/pen/EwXPWa?editors=001

**Comment by benjycui** [comment]
> maybe you need options.getValueFromEvent

:+1:
