### ISSUE TITLE
Tree 组件增加搜索能力

### ISSUE THREAD

**Issue by sunshiner** [ant-design/ant-design#7777]
### What problem does this feature solve?
目前Tree组件搜索需要写代码实现，官网demo也有，但是demo并没有过滤掉不匹配的节点。希望Tree组件可以有与TreeSelect 一样的搜索功能，[TreeSelect搜索](https://ant.design/components/tree-select-cn/#components-tree-select-demo-basic) ，filterTreeNode不仅仅是高亮效果，而是可以直接过滤掉节点。

### What does the proposed API look like?
```

        <Tree
          filterTreeNode={filterTreeNode} // 根据 返回值决定是否渲染节点
        >
          { loop(data) }
        </Tree>


```

**Comment by afc163** [comment]
自行改造这个例子就可以了：https://ant.design/components/tree/#components-tree-demo-search

**Comment by afc163** [comment]
trace #7750
