### ISSUE TITLE
Form: data lost after change component rendering types

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#7782]
### Version
2.13.3

### Environment
Chome 61.0.3163.100

### Reproduction link
[https://codepen.io/FrankLuLei/pen/yzXaPr?editors=0001](https://codepen.io/FrankLuLei/pen/yzXaPr?editors=0001)

### Steps to reproduce
1. type any text in text area
2. click style1
3. typed text display in input control
4. click style2
5. typed text disappear in text area

### What is expected?
Typed text still exist in text area

### What is actually happening?
Text area is empty

**Comment by lulut** [comment]
When component unmounted, related field with value should not removed from Form.

**Comment by afc163** [comment]
`getFieldDecorator` don't support dynamic render, you can set two different name for each field, or create a HOC like InputOrTextArea.

**Comment by lulut** [comment]
The case is we are providing a tool for user to switch different type of component.  A form value could be bound to a input text or dropdown box.  As is a HOC is not applicable to this case.  Is there any other option for me?

**Comment by afc163** [comment]
>  set two different name for each field

And when pick the correct value accroding to RadioButton's selection.

**Comment by lulut** [comment]
Thanks for your advice.  Actually, we are create a form designer, the field name is the key identity to submit to backend, thus its totally customizable by end user and cannot be renamed, means this way is blocked either T  T...

**Comment by rafaelmaruta** [comment]
use shouldComponentUpdate () { return false } then onChange={() => this.forceUpdate()} in the component

**Comment by danialdezfouli** [comment]
I have The same issue
```
<FormItem name={['questions', id, 'title', lang]}>
    <Input placeholder={`Title ${lang}`} />
</FormItem>

```

**Comment by danialdezfouli** [comment]
I Shall use something like this:
```
   <FormItem label={`Title ${lang}`} required
                                rules={[{ required: true, message: 'This field is required!' }]}>
                                <Input placeholder={`Title ${lang}`}
                                    value={quiz.title && quiz.title[lang]}
                                    onChange={e => {
                                        setQuiz({
                                            ...quiz,
                                            title: {
                                                ...quiz.title,
                                                [lang]: e.target.value
                                            }
                                        })
                                    }}
                                />
                           </FormItem>
```
