### ISSUE TITLE
The demo of form does not work in react v16

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#7784]
### Version
2.13.3

### Environment
chrom,react v16

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-form-in-modal](https://ant.design/components/form-cn/#components-form-demo-form-in-modal)

### Steps to reproduce
The demo in the Form conponent page [Form](https://ant.design/components/form-cn/#components-form-demo-form-in-modal) ,Open it by codePen,It display a blank page if import react v16,and it work will if import react v15.x

And in my local,the deom [components-form-demo-form-in-modal](https://ant.design/components/form-cn/#components-form-demo-form-in-modal) throw waring with react v16:

```
Stateless function components cannot be given refs. Attempts to access this ref will fail.
```

### What is expected?
It can work well in react v16.

### What is actually happening?
Maybe some error or waring with react v16

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/5377
