### ISSUE TITLE
Select[defaultActiveFirstOption=true] doesn't work

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#7786]
### Version
2.13.3

### Environment
Chrome 61/Firefox 55

### Reproduction link
[https://codepen.io/megawac/pen/rGwvdB?editors=001](https://codepen.io/megawac/pen/rGwvdB?editors=001)

### Steps to reproduce
Set [defaultActiveFirstOption=true] on a select menu

### What is expected?
The first option that can be made active, be made active

### What is actually happening?
No option is being selected when active value isn't being managed

**Comment by megawac** [comment]
Nevermind, misunderstood the purpose of this feature. I thought it was to set the defaultValue to the first possible option.

**Comment by refex** [comment]
And what is it its purpose then?

**Comment by yoyo837** [comment]
Related: #8574

**Comment by qsz13** [comment]
> And what is it its purpose then?

Looks like it's whether to highlight the first option when the dropdown is opened.

**Comment by vitalijalbu** [comment]
it still doesn't work..

**Comment by NOELSAJO7** [comment]
Did you guys find any solution to it ?

**Comment by yoyo837** [comment]
If the problem is still here, please provide a reproduction and feel free to open a new issue for that.
