### ISSUE TITLE
Select[defaultValueFirstOption]

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#7787]
### What problem does this feature solve?
Similar to a html select, it can be useful to have selects that have an option selected by default. Often the desired value is the first item in the select list (that isn't disabled).

### What does the proposed API look like?
`Select[defaultValueFirstOption=bool]` with a default to false. 1) Setting it to true would select the first non disabled option to the selected value. 2) If the selected value were to become disable, do step 1)

**Comment by afc163** [comment]
It should use `defaultValue`.
