### ISSUE TITLE
如何给树加上icon？

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#779]
树已经开启了showIcon这项，结果也出现了图标的位置，就是不知道如何引入的？

**Comment by dyf2015** [comment]
自己找了个临时方案。。 把treenode再封装一层自行修改ant-tree-iconEle样式。

**Comment by afc163** [comment]
http://react-component.github.io/tree/examples/simple.html

用样式加上。

**Comment by benjycui** [comment]
支持 `showIcon={<Icon type="xxx" />}` 如何？

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/tree/pull/102

**Comment by benjycui** [comment]
现在 `Tree[showIcon]` 是会影响整棵树的配置，需要再增加 `TreeNode[showIcon]` 单独控制某一节点。

**Comment by ashking** [comment]
Any update on when this will be available in master and as npm update?

**Comment by meimei777** [comment]
@benjycui showIcon={<Icon type="xxx" />}请问这个什么时候支持啊，还用不了啊现在

**Comment by meimei777** [comment]
请问showIcon：treeNode  什么时候支持啊，用不了啊现在

**Comment by luats** [comment]
@benjycui @afc163 节点确实有icon的需求，不同类型的节点，需要从icon来区分。

**Comment by liuyuan512** [comment]
现在还没有解决吗？？需求真的很大呀

**Comment by fearhat** [comment]
As a workaround (until there's an update) you can add an icon to the title and put it over the icon:
`
const iconStyle = {
      left: "-19px",
      top: "6px",
      position: "absolute",
      background: "white"
    };
<TreeNode title={<span><Icon style={iconStyle} type="folder" />title</span>} />
`

**Comment by zombieJ** [comment]
TreeNode 还是添加一个 `icon` 属性，让用户可以自定义图标。
TreeNode 也用 `showIcon` 来做自定义的话如果 Tree 的 `showIcon` 为 `false` 就会有歧义。

意下如何？

**Comment by zombieJ** [comment]
done. https://github.com/react-component/tree/pull/150
