### ISSUE TITLE
表单中form.setFieldsValue无法给CheckboxGroup赋值

### ISSUE THREAD

**Issue by devin-yuan** [ant-design/ant-design#7790]
### Version
2.12.8

### Environment
macOS: 10.12.6/Chrom: 61.0.3163.100

### Reproduction link
[https://codepen.io/devin_yuan/pen/GMEzBz](https://codepen.io/devin_yuan/pen/GMEzBz)

### Steps to reproduce
操作多选后，执行CheckboxGroup的onChange事件，对多选框组合的值进行一些处理再重新赋值

### What is expected?
希望是选中某一个值，便取消其余的选择；或者选择了其他值，那指定值为不选中。

### What is actually happening?
我对选择的结果进行了处理，但是无法把处理后的值通过form.setFieldsValue重新赋给组件

**Comment by benjycui** [comment]
行为符合预期，是你执行 `setFieldsValue` 的时机不对。

你的使用场景是什么？

**Comment by devin-yuan** [comment]
@benjycui 希望是选中某一个值，便取消其余的选择；或者选择了其他值，那指定值为不选中。

**Comment by nikogu** [comment]
@devin-yuan 那你应该去 `onChange Input`，实现1双向绑定，不过我觉得你更需要这个：https://ant.design/components/form-cn/#components-form-demo-global-state

**Comment by yesmeck** [comment]
怎么听着你应该用 Radio。
