### ISSUE TITLE
Antd message is not compatible with React 16

### ISSUE THREAD

**Issue by zhboner** [ant-design/ant-design#7793]
### Version
2.13.4

### Environment
React 16.0.0, React-Dom 16.0.0

### Reproduction link
[https://codepen.io/zhboner/pen/qPXZdR](https://codepen.io/zhboner/pen/qPXZdR)

### Steps to reproduce
Click the button will make the application crashed.

### What is expected?
In React 15, click the button will show a success message, but this application crashed in React 16. 

### What is actually happening?
Cannot read property 'add' of null in node_modules/rc-notification/es/Notification.js:138

**Comment by zhboner** [comment]
With React 15.6.2 it works fine. The followed link points to React 15 version
https://codepen.io/zhboner/pen/dVzMVJ

**Comment by afc163** [comment]
Thx for reporting, trace #7793

**Comment by hezhongjie** [comment]
i meet the same error;
what is the reason?
how to resolve it ?

**Comment by zhboner** [comment]
Maybe wait until the end of the year when officially support the React 16

**Comment by kennylbj** [comment]
+1
```Cannot read property 'add' of null``` in ```node_modules/rc-notification/es/Notification.js:138```
```js
"react": "^16.1.0",
"antd": "^2.13.10",
```

**Comment by alihanniba** [comment]
+1

**Comment by u-kan** [comment]
just for info..

I found out same things happen with ```notification```

**Comment by ml-devninja** [comment]
I had same problem with a notifications. It works only in specyfic component (that was extremly weird) and crash whole app if i wanted to use it in other place (Notification.js:138)

I've udpated React and React-dom packages to 16.2, and ant.design to version 3 and everthing is now fine - works like a charm

**Comment by kennylbj** [comment]
Just updating to ant-design 3.x and everything works fine
