### ISSUE TITLE
Inline select without border

### ISSUE THREAD

**Issue by andriijas** [ant-design/ant-design#7795]
### What problem does this feature solve?
Select box without border for Inline select within sentences.

Check example: https://react.semantic-ui.com/modules/dropdown#dropdown-example-inline-two

### What does the proposed API look like?
https://react.semantic-ui.com/modules/dropdown#dropdown-example-inline

**Comment by afc163** [comment]
Try http://ant.design/components/dropdown ?

**Comment by tfcb93** [comment]
You can use css selectors (`:first-child` or `:nth-child(1)`) to remove the select border.
For Exemple:
 `<antd.Selector className="my-selector-class">...`
on CSS:
`.my-selector-class:first-child{
   border: none;
}`
