### ISSUE TITLE
Ability to do support multiple rowSelection columns on one table 

### ISSUE THREAD

**Issue by xxryan1234** [ant-design/ant-design#7797]
### What problem does this feature solve?
Allows the user to do more than one `rowSelection` to support features like `Select All` and `Bookmark All` at the same table

### What does the proposed API look like?
```
      const rowSelection = [{
        selectedRowKeys,
        boxIcon: checkboxIcon,
      }, {
        bookmarkRowKeys,
        boxIcon: starIcon
      }];
      
      return (
        <Table rowSelection=[rowSelection] />
      )
```
<img width="168" alt="screen shot 2017-10-02 at 2 17 18 pm" src="https://user-images.githubusercontent.com/5448370/31066198-bb2c4b8c-a77d-11e7-9159-da4beb5f6d01.png">

**Comment by yesmeck** [comment]
I thinks it's easy to archive this on the user side, we don't want make table more complex.
