### ISSUE TITLE
Table component slow using Safari 11 on MacOS High Sierra

### ISSUE THREAD

**Issue by vparaskevas** [ant-design/ant-design#7799]
### Version
2.13.4

### Environment
MacOS High Sierra,  Safari 11

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Just use the pagination examples (Selection & Operation and Ajax examples)

### What is expected?
Expected to run as smoothly as it does using other browsers on the same operating system, or using previous versions of Safari

### What is actually happening?
Table component is really slow and almost crashes Safari 11 when using it on a more complicated example (Using nested tables). You can notice the difference even at your examples

**Comment by afc163** [comment]
It works smoothly in my machine.

**Comment by vparaskevas** [comment]
Hi, thanks for your answer,
I'm actually using Safari Version 11.0 (13604.1.38.1.6) High Sierra version 10.13

**Comment by vparaskevas** [comment]
The problem is definetely on Ant Motion
I'm trying to use the list sort example (https://motion.ant.design/exhibition/demo/list-sort) and Safari almost crashes. I'm using a 2016 MacBook Pro

**Comment by afc163** [comment]
emmm... weird perfermance issue.

**Comment by afc163** [comment]
There are something maybe related:

- https://discussions.apple.com/thread/8084399?start=0&tstart=0
- https://www.reddit.com/r/mac/comments/72m0vz/safari_painfully_slow_after_upgrading_to_high/

**Comment by vparaskevas** [comment]
Unfortunately I couldn't find any clue to find the problem. Safari runs fine on any other website.
I noticed that the problem is also on https://motion.ant.design/exhibition/demo/list-sort. All other examples are running just fine. Perhaps the problem is at a specific javascript function.

It tried the above links but they are not connected to my problem.
Lets's hope that a Safari update might solve the problem.

**Comment by reyesyang** [comment]
I have the same problem, unset table loading prop seems have some help.
so I guess this issue maybe related with css animation

**Comment by vparaskevas** [comment]
I tried that already, and indeed there is a small performance improvement but the problem still remains. Perhaps a Safari update will solve the issue.

**Comment by creeonix** [comment]
Same thing here, table component is extremely slow in Safari 11.0.1 (13604.3.5)

**Comment by agileago** [comment]
@creeonix  + 1 table component is extremely slow in Safari 11.0.1 (13604.3.5)

**Comment by wangking873** [comment]
我也遇到同样的问题

**Comment by cheong12001** [comment]
i have the save issue, any solutions ???
the performance is extreme low on desktop safari

**Comment by yesmeck** [comment]
Compared Safari with Chrome, seems like the main bottleneck is react?

Chrome:
![20171127143332](https://user-images.githubusercontent.com/465125/33253752-141a9536-d380-11e7-871c-f5986d56a7b3.png)

Safari:
<img width="1386" alt="20171127143313" src="https://user-images.githubusercontent.com/465125/33253753-1449d224-d380-11e7-8772-93fb334eb9d5.png">

**Comment by stefan1968** [comment]
I've hit this problem, its basically making my web application completely unusable on safari.
Any updates on this??

**Comment by DoranYun** [comment]
When the table is more than 5 columns, it will happen.

Safari verision is 11.0.1 (13604.3.5)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8538

**Comment by gguan** [comment]
Is there any updates/progresses on the issue? Can anyone provide a temporary solution?

**Comment by wupinlang** [comment]
The problem remains.It is serious.

**Comment by mixj93** [comment]
https://github.com/ant-design/ant-design/issues/8538 里面提到一个解决方案：

> 发现 ant-table && ant-table table 的overflow: hidden造成的,去掉以后再safari下不卡顿

**Comment by hardwit** [comment]
I have the same problem. Safari 11.0.3 (13604.5.6).
When I try to scroll page that contents a table, Safari has seriously lags.

**Comment by topwood** [comment]
I was fucked by my boos because of this slow experience while i finally find this issue. Please fix this soon, thanks a lot!

**Comment by pengfu** [comment]
My antd version is ^3.3.0,and the overflow:hidden is removed from the version.
HOWEVER, the issue still remains.

**Comment by pengfu** [comment]
最后是我们的产品过来指导我，说这个地方不能圆角，我去掉了包裹元素上的border-radius属性，结果，神奇的事情发生了，safari下不卡顿了。。。

**Comment by SyMind** [comment]
@pengfu 我开始了思考，觉得我这辈子都学不好前端了。

**Comment by ZhaoTim** [comment]
> 最后是我们的产品过来指导我，说这个地方不能圆角，我去掉了包裹元素上的border-radius属性，结果，神奇的事情发生了，safari下不卡顿了。。。

我还是卡.....崩溃

**Comment by SPineapple** [comment]
Table is not showing in Safari browser, only in chrome.. how can i fix this?
