### ISSUE TITLE
分页页面刷新后如何回到之前的页码

### ISSUE THREAD

**Issue by xuhuan** [ant-design/ant-design#780]
RT，还有后退回来如何回到之前页码。

**Comment by benjycui** [comment]
你可以研究下 [react-router](https://github.com/rackt/react-router)，把页码加到 url 上面就行。

**Comment by bang88** [comment]
@benjycui 这个有个问题，虽然页面变了，但是事件好像没有执行
使用`react-router`控制返回，`table`的页码变了，数据还是之前的数据。
@xuhuan 可以把页码加在`query`上面

**Comment by xuhuan** [comment]
@bang88 有没有demo，还有有 redux-router 的实现方式吗？
只有页码应该不够，感觉应该完整的请求参数全部带上。

**Comment by Ysudo** [comment]
如果用router的话，可以尝试下redux,

xuhuan <notifications@github.com>于2015年12月30日周三 下午4:23写道：

**Comment by xuhuan** [comment]
@Ysudo 目前在考虑用 redux-router

**Comment by Ysudo** [comment]
那就可以用redux管理数据了，页码，表数据都保存好就OK了


xuhuan <notifications@github.com>于2015年12月30日周三 下午4:53写道：

**Comment by xuhuan** [comment]
@Ysudo redux 是如何在页面刷新后还保留页码数据这些？特别是跨浏览器的情况下？有demo吗？

**Comment by Ysudo** [comment]
F5刷新的页面那redux也没办法保留，除非用url里设置数据。
跨浏览器没明白，页面跳转还能跨浏览器？

xuhuan <notifications@github.com>于2015年12月31日周四 上午8:10写道：

**Comment by Ysudo** [comment]
https://github.com/erikras/react-redux-universal-hot-example

这里有个redux的demo，可以参考

云苏东 <lovedo@gmail.com>于2015年12月31日周四 上午11:20写道：

**Comment by xuhuan** [comment]
@Ysudo 网页分享给其他人打开的时候不是就跨浏览器了。所以还是要url跟参。

**Comment by YikaJ** [comment]
@Ysudo 按照Redux只有一个State树的设计来说，只要把保存有当前组件相关的state保存到localstorage或者后台里，再次加载时，可以回溯到之前的状态。
所以组件设计内部state的时候设计成允许通过props传入，或许可以解决。

**Comment by buxuku** [comment]
楼主这个需求后来找到最佳实践的方法了吗？我现在也有这样的一个需求，考虑的是通过browserHistory把分页和搜索那些参数放到url里面去，但在生命周期中遇到了一些问题。

**Comment by blankul** [comment]
怎么样了，这个问题有最佳实践了嘛。。

**Comment by ccloveak** [comment]
怎么样了，这个问题有最佳实践了嘛。。

**Comment by ccloveak** [comment]
3天过去了。。。我卡在这里了
