### ISSUE TITLE
targetKeys property should be optional within TransferProps

### ISSUE THREAD

**Issue by gavinrobertszeco** [ant-design/ant-design#7807]
### Version
2.13.4

### Environment
Typescript 2.4.1 

### Reproduction link
[https://github.com/gRoberts84/antdTypeScriptTransferProps](https://github.com/gRoberts84/antdTypeScriptTransferProps)

### Steps to reproduce
1. `git clone git@github.com:gRoberts84/antdTypeScriptTransferProps.git`
2. `cd antdTypeScriptTransferProps`
3. `yarn install`
4. `tsc`

### What is expected?
TypeScript should successfully build.

### What is actually happening?
```
src/index.tsx(38,15): error TS2322: Type '{ dataSource: any; showSearch: true; onChange: (keys: any) => void; render: (item: any) => any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<TransferProps, ComponentState>> & Readon...'.
  Type '{ dataSource: any; showSearch: true; onChange: (keys: any) => void; render: (item: any) => any; }' is not assignable to type 'Readonly<TransferProps>'.
    Property 'targetKeys' is missing in type '{ dataSource: any; showSearch: true; onChange: (keys: any) => void; render: (item: any) => any; }'.
```

---
Based upon comments to issues raised within the repository, it was advised to remove the `targetKeys` property as this would be populated by the field descriptor. This appears to work perfectly on CodePen however when running within TypeScript, the typings for the TransferProps has `targetKeys` marked as mandatory 

https://github.com/ant-design/ant-design/blob/1bf0bab2a7bc0a774119f501806e3e0e3a6ba283/components/transfer/index.tsx#L23

**Comment by gavinrobertszeco** [comment]
Thanks @afc163 - I was going to look into this tomorrow (been a busy week 😢 )

**Comment by benjycui** [comment]
It is meaningless to make `Transfer[targetKeys]` optional.. Because Transfer only support controlled mode, if you don't provide `targetKeys`, why do you use Transfer??

**Comment by gavinrobertszeco** [comment]
@benjycui When using Transfer within a decorator field, `transferKeys` is automatically set.
