### ISSUE TITLE
Website Examples are not working in code pen

### ISSUE THREAD

**Issue by KalpanaPagariya** [ant-design/ant-design#7808]
### Version
2.13.4

### Environment
OS : Window 10

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
Please go to the below website and try to open any example in code pen. its not working
https://ant.design/components/transfer/ , 

### What is expected?
Examples should work as before it was working

### What is actually happening?
Please go to the below website and try to open any example in code pen. its not working
https://ant.design/components/transfer/ ,

**Comment by anthonykoerber** [comment]
In Pen Settings > Javascript: 

The paths to react, and react-dom are broken:

https://unpkg.com/react-dom@16.0.0/dist/react-dom.js

https://unpkg.com/react@16.0.0/dist/react.js

**Comment by nikogu** [comment]
we don't fully support react@16.0.0, you can check it to react@15.x

**Comment by coljung** [comment]
Any idea of what sections are not supported yet ?
Thx
