### ISSUE TITLE
message not visible in fullscreen

### ISSUE THREAD

**Issue by nadim** [ant-design/ant-design#7815]
### Version
2.13.1

### Environment
Mac OS Sierra 10.12.6 (16G29), Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/Ewbrbx](https://codepen.io/anon/pen/Ewbrbx)

### Steps to reproduce
Go fullscreen with requestFullscreen()
Call message.success
Message is not visible

### What is expected?
message should display

### What is actually happening?
message is not displaying

**Comment by nikogu** [comment]
`message` is a `React Component`. It is need to be `render` to a root node via `ReactDOM.render`.

https://ant.design/components/message/#components-message-demo-other

**Comment by afc163** [comment]
@yesmeck Could new `React.createPortal` API resolve this one?

**Comment by yesmeck** [comment]
Here is a workaround https://codepen.io/yesmeck/pen/NayBxB

**Comment by yesmeck** [comment]
> Could new React.createPortal API resolve this one?

No, the key issue is the container is now included in the fullscreen DOM.

**Comment by afc163** [comment]
@nadim I am afraid there is nothing we can do about this, the fullscreen feature don't allow to show other element but the fullscreen element.

**Comment by lijovijayan** [comment]
@nadim I have a simple solution.

Add an` id` for the full-screen element and configure the `message provider` with below code.

```
message.config({
    getContainer: () => document.fullscreenElement ? document.getElementById(document.fullscreenElement.id) || document.body : document.body
});
```
