### ISSUE TITLE
Table row highliting via store

### ISSUE THREAD

**Issue by sagorshkov** [ant-design/ant-design#7816]
### What problem does this feature solve?
Don't rerender the Table component to change class of one row.

### What does the proposed API look like?
I can't provide exact API, but looks like it can be implemented by your 'store' realization. You use this way to update your switch boxes states of the Table native select functionality.
I'm using the Table component for my project. But I need to implement select functionality with clicks on rows. To highlit selected row I have to use rowClassName and selectedRowKeys props, but in this case I need to rerender full Table component to change row class. But my Table is huge to let me do it on each click. I've checked your realisation of the select switchboxes and detected that you use the store for subscribing your switchboxes and change their states. In this case I can change the row selecting state and switchbox without Table rerendering. Could you advice me how can I change row class in the same way -- without Table rerendering. Perhaps via store. Or some another way? Thanks in advace...

**Comment by nikogu** [comment]
The huge Table ? how is the performance - very slow or ?

For now, i think using `rowClassName` and `selectedRowKeys` must be rerendering.

i have a idea, using the dom API directly and via the `index` to specify the row.

There are my personal thought.

**Comment by afc163** [comment]
See #7732, the PR would be welcome if you have better solution: http://github.com/react-component/table
