### ISSUE TITLE
Set Table expandable property at row level

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#7817]
### What problem does this feature solve?
Currently the Table "Expandable" property can only be specified at for the entire table.  There are use cases where you only want some rows to be expandable.

### What does the proposed API look like?
The simplest way would be to not render the expand icon if `null` or `undefined` is returned via the `expandedRowRender` prop.

```
<Table columns={columns} dataSource={this.props.data} expandedRowRender={(record) =>{
 if(record.expandable) {
     return <p>hello!</p>;
  } else {
     return null;
  } 
}}
/>
```

**Comment by nikogu** [comment]
i think if `expandedRowRender ` return null then does not show the icon.

**Comment by ChuckJonas** [comment]
@nikogu I tested and it didn't seem like that was the case... Maybe I had something else wrong.

**Comment by chenshuai2144** [comment]
This problem has been solved?

**Comment by yesmeck** [comment]
For performance reason, we don't call  expandedRowRender until the row is expanded. If you don't want show expand icon for some rows, you can use `rowClassName` to add a custom className to the row, and hide the expand icon by the css.

**Comment by youngzhaosignifyd** [comment]
@yesmeck Agreed. 

@ChuckJonas Here is an example to achieve your goal with the current API:
https://stackblitz.com/edit/react-eydnk3

**Comment by arch7tect** [comment]
@youngzhaosignifyd Link does not work

**Comment by youngzhaosignifyd** [comment]
@arch7tect Maybe stackblitz doesn't work in your area. Here is the github repo:

https://github.com/zhaocnus/ant-expandable-row

**Comment by ycjcl868** [comment]
https://codesandbox.io/s/o4l12vnnkq

**Comment by hdwong** [comment]
> https://codesandbox.io/s/o4l12vnnkq

@ycjcl868 
Thanks for your solution, but it only hides the expand icon when description field is empty.
I set the property `expandRowByClick` in the <Table> component, and the expanded row will also be shown when clicked.
How do we handle the expand events we need.

**Comment by ashraf-patel** [comment]
@ycjcl868 @hdwong 
It doesn't work even if the description field is empty.
[https://codesandbox.io/s/o4l12vnnkq](https://codesandbox.io/s/o4l12vnnkq)

**Comment by codal-jsojitra** [comment]
i want to remove col-span from expandable row

**Comment by mujtaba14** [comment]
i have an issue in ant design regarding Row rendering...  my query is if any existing row is open  and when i click on next row the existing open row should be closed.... if any have any solution please reply on this comment or show some demo in stackblitz...please need your help ...... Thanks in advance

**Comment by f7753** [comment]
It seems that the problem still exists, why this issue closed?

**Comment by DeoluA** [comment]
I ran into this problem, and would like to share my solution, for whoever it may help. You can set expandable property at the row level. See it here: https://codesandbox.io/s/compassionate-orla-05f02y

(I did this is for version `^3.26.9`, but the logic should be adaptable for newer versions too)

I took advantage of the `expandedRowKeys`, `onExpand` and `expandIcon` features

**Comment by DeoluA** [comment]
> i have an issue in ant design regarding Row rendering... my query is if any existing row is open and when i click on next row the existing open row should be closed.... if any have any solution please reply on this comment or show some demo in stackblitz...please need your help ...... Thanks in advance

Found this answer over on StackOverflow...check it out: https://stackoverflow.com/questions/67295603/react-and-expandedrow-render-in-ant-design
