### ISSUE TITLE
Fixed header of the table

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#782]
How can I make a header of a table fixed (like Telerik Kendo UI data-grid)?
I believe this CSS tip may be very helpful
http://salzerdesign.com/blog/?p=191

**Comment by afc163** [comment]
`useFixedHeader`
it is a undocumented prop in antd.
https://github.com/react-component/table#property

**Comment by kvetoslavnovak** [comment]
Great, thank you. So yI am closing this.

**Comment by afc163** [comment]
http://react-component.github.io/table/examples/scrollBody.html
