### ISSUE TITLE
using immutable data with multi select in antd form

### ISSUE THREAD

**Issue by hieunvtq** [ant-design/ant-design#7822]
### Version
2.13.4

### Environment
Ubuntu 16.04, chrome 61, react 15.6.2, immutable 4.0.0-rc.4

### Reproduction link
[http://local](http://local)

### Steps to reproduce
as title of issue, I use an array data type of immutable to render a multi select with required in a form, when i selecting an option from select, the error occur at webpack:///./~/rc-select/lib/util.js?

"Uncaught TypeError: Cannot use 'in' operator to search for 'value' in undefined"

function getValuePropValue(child) {
  var props = child.props;
  if ('value' in props) {  <<=== ERROR OCCUR HERE !!!
    return props.value;
  }
  if (child.key) {
    return child.key;
  }
  if (child.type && child.type.isSelectOptGroup && props.label) {
    return props.label;
  }
  throw new Error('Need at least a key or a value or a label (only for OptGroup) for '   child);
}

### What is expected?
.

### What is actually happening?
.

**Comment by yesmeck** [comment]
Please provide a reproduction link, thanks!

**Comment by hieunvtq** [comment]
reproduction link: https://codepen.io/hieunvtq/pen/LzQrgE?editors=0010

**Comment by yesmeck** [comment]
You need convert `children` to array.
```javascript
<Select mode="multiple" style={{width: '200px'}}>{children.toArray()}</Select>
```

**Comment by hieunvtq** [comment]
It's okay, thank you
