### ISSUE TITLE
form表单中日期选择显示的时间与最终提交的时间相差8个小时

### ISSUE THREAD

**Issue by mohong122** [ant-design/ant-design#7827]
### Version
2.13.4

### Environment
mac，chrome，react16.0.0

Reproduction link

https://codepen.io/mohong122/pen/YraLQv?editors=0011

### Steps to reproduce
通过日期选择后，显示的日期没有问题，但是将数据转为json提交至后台时，提交的数据比显示的数据少8个小时

### What is expected?
提交的日期时间与选择的时间相同

### What is actually happening?
与实际相差8个小时

![image](https://user-images.githubusercontent.com/1935979/31330003-33ca40b6-aca2-11e7-87f2-f63920680d21.png)

**Comment by muzea** [comment]
This is the time zone problem.

这是时区的问题啦。

**Comment by mohong122** [comment]
@muzea 知道是时区的问题，想知道在哪儿改

**Comment by mohong122** [comment]
@yesmeck demo添加上了。
https://codepen.io/mohong122/pen/YraLQv?editors=0011

**Comment by yesmeck** [comment]
See http://momentjs.com/docs/#/displaying/as-json/
