### ISSUE TITLE
Requires a perfect type definition file

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#7828]
### What problem does this feature solve?
I want to use some props in Select.option, like `style`,But these are missing in the definition file.

### What does the proposed API look like?
such like that
```typescript

interface baseProps {
  style?: Object;
}

interface OptionProps extends baseProps {

}

```

**Comment by yesmeck** [comment]
`Select.Option` don't support `style` prop.

**Comment by muzea** [comment]
@yesmeck 
In fact we are so used and it can work
https://github.com/react-component/select/blob/master/src/Select.jsx#L905
But now have a problem, antd will support the transfer of this parameter Well?

**Comment by benjycui** [comment]
We should place `{...child.props}` before style:

https://github.com/react-component/select/blob/master/src/Select.jsx#L900-L906

**Comment by yesmeck** [comment]
@muzea Don't recommend use undocumented feature. Anyway, free to open PR if you encounter type definition issues.
