### ISSUE TITLE
error fsevents@1.1.2: The platform "linux" is incompatible with this module.

### ISSUE THREAD

**Issue by Ming2008** [ant-design/ant-design#7829]
### Version
2.13.4

### Environment
 CentOS Linux release 7.3.1611 (Core)    yarn 1.1.0

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
yarn add antd

error message :

[2/4] Fetching packages...
error fsevents@1.1.2: The platform "linux" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command

why ? 

### What is expected?
Please tell me how to do it

### What is actually happening?
I try it many times. But still error.

**Comment by yesmeck** [comment]
`antd` doesn't depends on `fsevents`, have you tried npm?

**Comment by Ming2008** [comment]
@yesmeck 
npm is ok
And I try it again ,as yarn add antd --save .OK, no problem.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
"error" is change to  "info"...
I think yarn has a problem
