### ISSUE TITLE
How to make "sticky footer" layout.

### ISSUE THREAD

**Issue by Edge00** [ant-design/ant-design#7830]
![ff78c60a-bc3d-444a-b0a7-05b9114be75f](https://user-images.githubusercontent.com/23715779/31330548-8cbdad50-aca4-11e7-9803-101f93c53398.png)

**Comment by Edge00** [comment]
How could the footer automatically on the end of the brswer?

**Comment by benjycui** [comment]
Try to use `Affix`

**Comment by Edge00** [comment]
@benjycui 
I added the following less code and it worked now.
```
html, body{
 height: 100%;
}
#root {
 height: 100%;
 & > .ant-layout {
  min-height: 100%;
 }
}
.layout-content {
 display: flex;
}

```
