### ISSUE TITLE
Bad suggestions displaying in Mention component

### ISSUE THREAD

**Issue by xorandiff** [ant-design/ant-design#7838]
### Version
2.13.4

### Environment
Chrome 59.0.3071.115, Linux

### Reproduction link
[https://ant.design/components/mention/#components-mention-demo-controllder-simple](https://ant.design/components/mention/#components-mention-demo-controllder-simple)

### Steps to reproduce
Use 'Controlled mode' example. Type `@` at the beginning, then `CTRL+A` and type any letter.

### What is expected?
Suggestions box should not be displayed in such case, if you press enter at that point, it prints `undefined` in Mention's input because there is no trigger char.

### What is actually happening?
![image](https://user-images.githubusercontent.com/29928305/31340724-5cf283a8-ad07-11e7-9a90-b684f1f3e039.png)
And after pressing ENTER
![image](https://user-images.githubusercontent.com/29928305/31340742-681c63ca-ad07-11e7-936a-d7fe370735ac.png)

**Comment by RaoHai** [comment]
ref: https://github.com/react-component/editor-mention/commit/677d89375bdb2debe0f2c5c15146c617f241c94d

`npm install rc-editor-mention@1.0.3` will solve this problem.
