### ISSUE TITLE
Error in the Upload component typings

### ISSUE THREAD

**Issue by dtassone** [ant-design/ant-design#7839]
### Version
2.13.4

### Environment
Chrome, windows 10, react 15.5.4

### Reproduction link
[https://codepen.io/madKakoo/pen/wrmbaa](https://codepen.io/madKakoo/pen/wrmbaa)

### Steps to reproduce
Create a dragger component with a beforeUpload prop assigned.

### What is expected?
Expected before upload typings
beforeUpload: (file:File, fileList: FileList)=> boolean
Expected File interface in 'antd/lib/upload/interface'

### What is actually happening?
The typings were changed to 
beforeUpload: ()=> boolean
The File interface was removed

---
It's all working as expected in the debugger so the code seems ok, just the typings

**Comment by mohamed-seada-1994** [comment]
It seems that what you mean by `File `interface is called `UploadFile`.
The `beforeUpload `typings are beforeUpload: (file:UploadFile,  fileList:Array<UploadFile>)=> boolean.
[upload/interface.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/interface.tsx)

**Comment by afc163** [comment]
>  The File interface was removed

https://github.com/ant-design/ant-design/pull/7183

> The typings were changed to beforeUpload: ()=> boolean

It was not changed: https://github.com/ant-design/ant-design/blob/712451acf7a6727f713a3949d9c4b3061d819e7e/components/upload/interface.tsx#L52
