### ISSUE TITLE
组件拆分

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#784]
以 `Select` 为例，现在是这样调用：

```xml
<Select tags />
<Select multiple />
```

于是代码里面就有很多这类判断：https://github.com/react-component/select/blob/master/src/Select.jsx#L371

能不能拆成这样：

```xml
<Select.TagsSelect />
<Select.MultipleSelect />
```

用户使用起来相差不大，但是实现起来会少很多判断，代码应该会更加清晰。

参考 `DatePicker`：http://ant.design/components/date-picker/

**Comment by warmhug** [comment]
这种配置项转子组件的拆分只解决一部分问题，把里边的 menu 依赖去掉、觉得要优先做起来。这样 tree-select 就不用再拷贝修改 select 代码了，可以直接依赖。

**Comment by benjycui** [comment]
主要是觉得这几个属性影响的范围挺大，甚至能影响其它属性：

![image](https://cloud.githubusercontent.com/assets/3580607/12060226/ea2cd2fc-afa5-11e5-8365-6e90abd0c5fd.png)

所以折成独立的组件，用户使用起来也不需要记这么多东西。

类似的还有 `Slider`：

![image](https://cloud.githubusercontent.com/assets/3580607/12060241/29c42866-afa6-11e5-8ac0-145522770bb9.png)

**Comment by benjycui** [comment]
@warmhug 开了另一个 issue 讨论，`Select` 和 `TreeSelect` 的代码重用的问题 https://github.com/ant-design/ant-design/issues/787

**Comment by warmhug** [comment]
现在 TreeSelect 和 Select API一致，也需要 `tags`、`multiple` 等功能（把 TreeSelect 整合进 Select 里、改叫做 Select.TreeSelect，也是需要的）。所以拆成这样 `<Select.TagsSelect />`、 `<Select.MultipleSelect />` 可能会引入用户更大使用成本。另外考虑本是和 select2 的API命名一致，修改后向后兼容和用户升级成本。这个建议还是要慎重做或者不做。

**Comment by benjycui** [comment]
嗯，懂了。
