### ISSUE TITLE
API For Styling ant-modal-body

### ISSUE THREAD

**Issue by tim-soft** [ant-design/ant-design#7840]
### What problem does this feature solve?
Provides a convenient/easy way to get rid of the padding in the ant-modal-body class, which is particularly useful with long, scrolling modal content.

### What does the proposed API look like?
Add something like `bodyStyle={{ padding: '0' }}` to Modal

```javascript
<Modal
    visible={this.state.isVisible}
    onCancel={this.handleCancel}
    title="Task Overview"
    style={{ top: '20' }}
    bodyStyle={{ padding: '0' }}
    footer={null}
    width={820}
>
    <div style={{ overflow: 'scroll' }}>
        Really long, scrolling content. I dont get cut off by the modal body padding.
    </div>
</Modal
```

Edit: Actually, it looks like this already exists! Maybe this is a more of a docs issue then
ref: http://react-component.github.io/dialog/

**Comment by benjycui** [comment]
> Actually, it looks like this already exists! Maybe this is a more of a docs issue then
> ref: http://react-component.github.io/dialog/

Could you PR to update docs? thanks.

**Comment by adeelibr** [comment]
How can you do the same for 

```
 Modal.error({
      title: 'Are you sure?',
      content: `${t('EDUCATION_CONTENT_THE_LESSON')} [.zip] ${t('EDUCATION_CONTENT_WILL_BE_DELETED')}`,
      onOk: this.onDeleteFile,
      okText: `${t('EDUCATION_CONTENT_DONE')}`,
      className: 'p-0',
      style: { padding: 0 },
      bodyStyle: { padding: 0 }
    });
```

`style` and `bodyStyle` both do not work.
