### ISSUE TITLE
Provide an example of 2nd Level Menu Items header

### ISSUE THREAD

**Issue by EduardoAC** [ant-design/ant-design#7843]
### What problem does this feature solve?
Ant design currently provide certain patterns to follow on the [Top Navigation](https://ant.design/docs/pattern/navigation#Top-Navigation). 

However, there is not example how to achieve the second level with the existing tools

![](https://os.alipayobjects.com/rmsportal/xXaCRVPIfmjDyIL.png)

How can I achieve this? and Will it be possible to add the example to the documentation?

### What does the proposed API look like?
None

**Comment by afc163** [comment]
It is deparated now. My suggestion would be https://ant.design/components/menu/#components-menu-demo-horizontal

**Comment by EduardoAC** [comment]
@afc163 Thanks for your quick answer, What do you mean with 'deparated'?

**Comment by afc163** [comment]
It is not a best design pattern, infact, we never use that. The documentation will be updated soon.

**Comment by pablomolnar** [comment]
There still an example showcasing multi level nav here: https://ant.design/docs/spec/navigation#Top-Navigation
