### ISSUE TITLE
Menu fails to render dynamic children

### ISSUE THREAD

**Issue by drcmda** [ant-design/ant-design#7846]
### Version
2.13.4

### Environment
OSX High Sierra
React 16.0.0

### Reproduction link
[https://gist.github.com/drcmda/632afccf1f7b2d414360fe0453bb2da5](https://gist.github.com/drcmda/632afccf1f7b2d414360fe0453bb2da5)

### Steps to reproduce
Any dynamic Menu.SubMenu child seems to crash.

```js
const Test = () => <Menu.SubMenu />
const App = () => (
    <Menu>
        <Test />
    </Menu>
)
```

### What is expected?
It should behave like a generic React component. Menu should not expect children to be of a certain type, instead it should propagate internals by using the Context api. In a dynamic application menu items are often connected to the store, it would be nice if ant could support it.

### What is actually happening?
Menu seems to inject props into its children.

<img width="805" alt="screen shot 2017-10-10 at 10 28 49" src="https://user-images.githubusercontent.com/2223602/31376622-d9a30370-ada5-11e7-8820-edbccd26b741.png">

**Comment by afc163** [comment]
Try

```diff
- const Test = () => <Menu.SubMenu />
+ const Test = (props) => <Menu.SubMenu {...props} />
```

**Comment by drcmda** [comment]
@afc163 That worked, thanks once again!
