### ISSUE TITLE
关于antd包依赖的moment错误问题

### ISSUE THREAD

**Issue by ansenAC** [ant-design/ant-design#7852]
昨天晚上打包构建，发现moment升级到2.19.0后和用webpack打包会报错，错误如下：

`
WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/XXX.../app/node_modules/moment/src/lib/locale'
 @ ./node_modules/moment/src/lib/locale/locales.js 65:16-60
 @ ./node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/moment/src/moment.js
 @ ./src/index.j
`

就把本地package中moment依赖改为~2.18.1，
但是antd包中依赖的moment依然会自动升级到2.19.0，只能临时搞一个本地的版本moment代替。
请问这种问题改怎么才能彻底解决？

**Comment by benjycui** [comment]
Trace: https://github.com/moment/moment/issues/4216

本地可以先 lock moment 版本

**Comment by maskTAQ** [comment]
I have the same problem as you,but i solve.
1. remove moment folder  under  `antd rc-time-picker rc-calendar ` npm-packages under node-modules folder
2.installde moment by `yarn add moment@2.18`

**Comment by plhosk** [comment]
I tried the workaround of @maskTAQ but it did not work. The moment folders came back after ```yarn start```.

I found another workaround if you use ```yarn``` (not sure about npm). Add the following to ```package.json```:

```
  "resolutions": {
    "antd/moment": "2.18.1",
    "rc-calendar/moment": "2.18.1",
    "rc-time-picker/moment": "2.18.1"
  },
```

then run ```yarn``` to resolve the packages.

**Comment by maskTAQ** [comment]
@plhosk 
I can't speak English, so I may not describe it very well.i did not define resolutions field in packages.json.
first delete moment folder in `antd/node-modules& rc-time-picker/node-modules &rc-calendar/node-modules` . then installed moment at your project like this `yarn add moment@2.18`. In this way, the moment version number that you rely on in your project is 2.18.1

**Comment by plhosk** [comment]
@maskTAQ 
Thanks, I got your method to work as well. I already had moment 2.19 installed as a dependency so your instructions didn't work until I first ran ```yarn remove moment```.

**Comment by maskTAQ** [comment]
@plhosk 
sorry,i forget it, you should remove moment if you use moment in your project before .then install

**Comment by YuArtian** [comment]
在webpack中配置 
`resolve: { alias :{ moment$: 'moment/moment.js' }}`

**Comment by ansenAC** [comment]
@YuArtian  
按照你的方法，我们项目中还会有一个webpack_require类的报错

我这边的解决方案是在本地目录下放一个moment 2.18.1 的包，然后把所有的moment依赖都指向这里

`

resolve: {  
        alias: {
            'moment$': path.resolve(cwd + '/views/app/editor/dep/moment/moment')
        },
        extensions: ['*', '.js', '.jsx']
 },

`

@plhosk 

npm dose not have the resolutions feature in package.json, so i download the moment package(v2.18.1) and put it in my project. then add alias in webpack.config as above.

**Comment by davidsonsns** [comment]
@plhosk Thanks for your help. But it only worked for me in the following way.
```
"resolutions": {
  "moment": "2.18.1"
}
```

**Comment by whathejoe** [comment]
Fix by @davidsonsns worked for me on a project bootstrapped with `create-react-app`.

**Comment by plhosk** [comment]
moment@2.19.1 has been released which fixes the problem.

**Comment by OscarCanek** [comment]
In case it helps someone using npm, I was able to fix the problem installing the moment package as a dependency.

`npm install moment --save`

**Comment by chenkang084** [comment]
@YuArtian it work well for me.thx

**Comment by rdl-candido** [comment]
The solution suggested by @plhosk also works with npm. I just had to use another package called NPM Force Resolutions so npm takes the resolutions block into account.

```
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```
