### ISSUE TITLE
expandIconAsCellprop of Table component is invalid when dataSource is Tree

### ISSUE THREAD

**Issue by tears743** [ant-design/ant-design#7855]
### Version
2.13.4

### Environment
all

### Reproduction link
[https://cloud.githubusercontent.com/assets/200876/9662334/a20b2814-5291-11e5-8b23-4fd95f4fa010.png](https://cloud.githubusercontent.com/assets/200876/9662334/a20b2814-5291-11e5-8b23-4fd95f4fa010.png)

### Steps to reproduce
 dataSource=[{...,children:{...},...}]
```<Table  expandIconAsCell={true} />``` this is invalid

### What is expected?
expandIconAsCell

### What is actually happening?
expandIconAsCell invalid

---
 ```<Table  expandIconAsCell={true} expandedRowRender={someHandler} />```  this is valid.
The code causes this question :   line:927 file: ant-design/components/table/Table.tsx
const expandIconAsCell = this.props.expandedRowRender && this.props.expandIconAsCell !== false;
when dataSource is tree and wanna expand icon as cell , expandIconAsCell will false!

**Comment by ddcat1115** [comment]
In fact the `expandIconAsCell` is not completely supported by underlying component [rc-table](https://github.com/react-component/table) in the tree data scenario, and it's great if you can give us a pr.

**Comment by yesmeck** [comment]
I think it's a design decision. I tried to add `expandIconAsCell` to tree table, but it looks weird when using `rowSelection` at the same time.

![screen shot 2018-03-20 at 16 17 00](https://user-images.githubusercontent.com/465125/37642991-1c3a6cfe-2c5a-11e8-866a-9c5ec18e7100.png)
