### ISSUE TITLE
doc: api sorting follow some rule

### ISSUE THREAD

**Issue by monkindey** [ant-design/ant-design#7856]
### What problem does this feature solve?
We can find what api we need quickly.

#### Option 1 

Following the alphabetical order.

The part of the [Table API](https://ant.design/components/table-cn/#Table)

* rowSelection
* pagination

we can change this to 

* pagination
* rowSelection

#### Option 2

Classify the API, property, event...

Also the part of the Table API

* onChange
* loading
* ...
* onRowMouseLeave

we can change this to 

* loading 
* ...
* onChange
* onRowMouseLeave

**Comment by yesmeck** [comment]
I like option 2, would you like to make a PR?

**Comment by monkindey** [comment]
I think we can combine this two option

First, we Classify the API, then every category follow the alphabetical order.

That is a lot of work, maybe we can write  some script to make it work. Any idea?

**Comment by yesmeck** [comment]
Yeah, we can use https://github.com/wooorm/remark to transform docs to a better format.

**Comment by monkindey** [comment]
OK, I will look into it. Any feedback will come here.

**Comment by benjycui** [comment]
> Yeah, we can use https://github.com/wooorm/remark to transform docs to a better format.

Just write a script to scan every `components/*/index.(zh-cn|en-us).md`, to find out all the tables and then sort it?

So that we can run this script again an again, instead of maintaining the API order manually.

**Comment by monkindey** [comment]
[This](https://gist.github.com/monkindey/21cc865a8a1e5febaf00ad0f11171fb3) is my demo about reading the certain markdown, then use `remark` transform it according to rule above. BTW, I ❤️ remark, Thank @yesmeck let me know. 

And then, I will use the `glob` matching @benjycui regex to find out all component markdown, and transform them.

Any feedback is welcome.

**Comment by monkindey** [comment]
`remark` seem not identify 

```
---
category: Components
type: Feedback
---
```

**Comment by yesmeck** [comment]
Try https://github.com/wooorm/remark-yaml-config

**Comment by monkindey** [comment]
Thanks @yesmeck , It's ok now.

**Comment by monkindey** [comment]
The [original markdown](https://gist.githubusercontent.com/monkindey/21cc865a8a1e5febaf00ad0f11171fb3/raw/d917635776f91d7cdc3f77e4433271711711e6e6/alert.md) about `alert` component

And there are two fomatting related it 

* [table paddedTable true](https://gist.githubusercontent.com/monkindey/21cc865a8a1e5febaf00ad0f11171fb3/raw/d917635776f91d7cdc3f77e4433271711711e6e6/alert_formated.md)
* [table paddedTable fasle](https://gist.githubusercontent.com/monkindey/21cc865a8a1e5febaf00ad0f11171fb3/raw/a8782daf2b27862b2266f43bfff4910f42b6d453/alert_chore.md)

which one you guy prefer? or neither?

**Comment by benjycui** [comment]
> table paddedTable fasle

Prefer this 😄

**Comment by monkindey** [comment]
😄 me too.
