### ISSUE TITLE
message.error/success/... duration argument is optional

### ISSUE THREAD

**Issue by monkindey** [ant-design/ant-design#7857]
### What problem does this feature solve?
Because duration have the default value.

```js
message.error(content, duration, onClose)
```

Sometime I want to use onClose, but have to reassign value to duration even equal to the default value.

### What does the proposed API look like?
I can use it two way.

```js
message.error(content, duration, onClose)
message.error(content, onClose)
```

duration is optional, we can identify the onClose using the `typeof`

**Comment by benjycui** [comment]
Just PR to branch `antd-3.0`, thanks!

**Comment by monkindey** [comment]
Hi, @benjycui . Do you use `prettier` to format ts code ?

**Comment by monkindey** [comment]
I run the `npm run lint` and no warning or error happen, Is what it mean my code follow your eslint?

![image](https://user-images.githubusercontent.com/6913898/31483655-dc99e1d6-aef2-11e7-9c21-80eb43402bf2.png)

**Comment by afc163** [comment]
@monkindey yep

**Comment by monkindey** [comment]
OK, Thanks. Is there still other step to check before send a PR?

**Comment by monkindey** [comment]
`yarn test` test is all right

![image](https://user-images.githubusercontent.com/6913898/31484135-b0ae4132-aef4-11e7-8e7c-8b6e7debd9ec.png)

**Comment by monkindey** [comment]
I created a feature PR.

**Comment by monkindey** [comment]
I am going to close it because of the https://github.com/ant-design/ant-design/pull/7874
