### ISSUE TITLE
表格右固定阴影失效

### ISSUE THREAD

**Issue by shenck215** [ant-design/ant-design#7859]
### Version
2.13.4

### Environment
win10，google 63，react 15.5.4

### Reproduction link
[https://codepen.io/shenck215/pen/PJapgX](https://codepen.io/shenck215/pen/PJapgX)

### Steps to reproduce
表格固定头和列，初始化完毕，固定列和非固定列是用阴影区分的，此时直接把鼠标移到固定列上，滚动鼠标滚轮，阴影消失。

### What is expected?
表格固定头和列，初始化完毕，固定列和非固定列是用阴影区分的，此时直接把鼠标移到固定列上，滚动鼠标滚轮，阴影应不失效。

### What is actually happening?
表格固定头和列，初始化完毕，固定列和非固定列是用阴影区分的，此时直接把鼠标移到固定列上，滚动鼠标滚轮，阴影失效。是多了一个样式将阴影去掉了。

**Comment by afc163** [comment]
Fixed in rc-table@5.6.13
