### ISSUE TITLE
Table组件指定rowSelection时，跳转到其它页没有调用onSelectAll

### ISSUE THREAD

**Issue by luolonghao** [ant-design/ant-design#786]
先选中几行，换页后checkbox都会被初始化，这时候相当于【取消全选】，应该调用rowSelection.onSelectAll。

**Comment by afc163** [comment]
不是很理解，搞个例子吧 http://jsfiddle.net/9zrstuto/70/

**Comment by luolonghao** [comment]
在handlePageChange方法里要添加，因为你在里面已经把selectedRowKeys设置成[]了。
```js
this.props.rowSelection.onSelectAll(false, []);
```

**Comment by afc163** [comment]
页面数据切换时，selectedRowKeys 会进行清洗，只保留当前页面的数据里的 key ，并不是 `取消全选`。

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design/issues/793

**Comment by afc163** [comment]
加了一个 rowSelection.onChange 用于外部使用。onSelect 和 onSelectAll 保持为用户触发的回调。
