### ISSUE TITLE
RangePicker onClear callback

### ISSUE THREAD

**Issue by pagnotta** [ant-design/ant-design#7860]
### What problem does this feature solve?
It would be nice to have a RangePicker 'onClear' API callback function similar to the 'onOk' callback.

In my use case I am filtering a database with the selected RangePicker time range. If I delete the selected range in the RangePicker by clicking on the clear button in the input box, I would like to query the database again without filters. If there was a 'onClear' callback this would be very simple to implement.

### What does the proposed API look like?
RangePicker: 'onClear' - callback when click on clear button - function()

**Comment by afc163** [comment]
Try `onChange`

**Comment by pagnotta** [comment]
Thanks. `onChange` would be the obvious workaround for me at the moment, but this fires on every change....

Just seeing `onClear` as a handy enhancement. Would be there for the same reasons as `onOk`.

**Comment by afc163** [comment]
```
onChange(value) {
  if (value === null) {
    // ..
  }
}
```

**Comment by pagnotta** [comment]
`value` would be an empty array if dates are deleted, so this would do the trick for me:
```
onChange(value) {
  if (value.length === 0) {
    // ..
  }
}
```
