### ISSUE TITLE
inputNumber 在触发了propreceive后 inputValue表现会不一致

### ISSUE THREAD

**Issue by purely-smile** [ant-design/ant-design#7867]
### Version
2.13.5

### Environment
Mac OS X 10_12_6 Chrome/61.0.3163.100

### Reproduction link
[https://codepen.io/purely-smile/pen/rGraYN?editors=1111](https://codepen.io/purely-smile/pen/rGraYN?editors=1111)

### Steps to reproduce
1. 输入框在焦点状态
2. 输入框失焦
3. 再次触发输入框焦点状态 input中的值变更为2，而不是2.0 

### What is expected?
再次触发输入框期待输入框的值为2.0 ，而不是2

### What is actually happening?
输入框结果为2

---
1. 查看了rc-input-number的源码，发现src/mixin.js中 componentWillReceiveProps 方法，会在触发的时候重新设置inputValue,这里没有保留小数位（2.0）,所以就出现上述bug。
2. 经分析所有设置inputValue的地方都是使用了this.toPrecisionAsStep 来格式化数值，只有componentWillReceiveProps中没有。

**Comment by purely-smile** [comment]
@afc163 请问下这个bug会更新到哪个版本上，随后4.0的正式版本吗

**Comment by afc163** [comment]
Just reinstall node_modules.

**Comment by afc163** [comment]
Gonna to revert this.

**Comment by basicfu** [comment]
@afc163 我发现官网的例子依旧有这个问题，输入2.0获取到的值为2，我看`package.json`里的`rc-input-number`已经是4.0的了，<https://ant.design/components/input-number-cn/> ，请问是哪里的问题呢？
