### ISSUE TITLE
Table ‘dataSource ’ The page only shows the first incoming value！ 

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#7868]
### Version
2.13.5

### Environment
mac chrome 

### Reproduction link
[https://github.com/SynChron1zed/carbon-admin](https://github.com/SynChron1zed/carbon-admin)

### Steps to reproduce
npm start 后 点击 活动水平数据录入 -能源活动 -化石燃料燃烧 点击参数选择 

### What is expected?
点击参数选择页面会显示不同的数据

### What is actually happening?
只显示初始值

**Comment by afc163** [comment]
Could you provide a re-producible and **minimum** demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by SynChron1zed** [comment]
@afc163  i want too。。。 but it's a little bit more code  can you copy my github code。。。 thanks ！！！  我自己也debugger 了好久  dataSource 值会传过去 但是并不会渲染在页面上 。。。。。。

**Comment by SynChron1zed** [comment]
@afc163  hi 我用中文沟通了啊 https://codepen.io/anon/pen/KXBzyV  我发现了个问题 不知道是不是这个原因引起的 这个例子 点击11 后  age 和 address  会改变值 但是name 并不会改变  应该是editable这个key值影响的 所以如果点击想改变值的时候 如果data里面有editable这个key 新传入的值就不会渲染页面 如果去掉editable 却可以  如果这是个问题的 就能解释我点击 后 dataSource 的值虽然传入了新的 但是并不会渲染页面 因为dataSource 是有 editable 这个 key的  可是问题是第一次初始值也是有editable 的 为什么却可以渲染页面

**Comment by SynChron1zed** [comment]
@afc163  hi ，River's lake emergency！！！

**Comment by SynChron1zed** [comment]
@afc163 hi ，Please look at the problem！！！thanks！！！

**Comment by SynChron1zed** [comment]
来一个人哇 。。。 天都黑了 。。。 研究下啊。。。 探讨下。。。

**Comment by nikogu** [comment]
没看懂...是啥意思

**Comment by SynChron1zed** [comment]
@nikogu  点击‘11’后  setState dataSource 的值  如果值里面有 editable 页面就不会刷新传入的值

**Comment by nikogu** [comment]
`editable` 为 true 可以改，为 false 不能改..正常的呀

**Comment by SynChron1zed** [comment]
@nikogu  你都没明白我的意思  不是能不能改的问题 是重新传data给 dataSource 页面不会刷新传入的值

**Comment by afc163** [comment]
```diff
  handleChange(key, index, value) {
-   const { data } = this.state;
+   const data = [...this.state.data];
    data[index][key].value = value;
    this.setState({ data });
  }
```

Make a immutable data, let table know it is changed.

**Comment by SynChron1zed** [comment]
@afc163 handleChange 是 edit 触发的 我的问题是 dataSource 传入新的data 页面还是原有的data值 
https://codepen.io/anon/pen/KXBzyV

**Comment by nikogu** [comment]
@SynChron1zed 仔细看 `EditableCell`  的代码，`componentWillReceiveProps` 根本就没有更新 `value`

```diff
- if (nextProps.editable !== this.state.editable) {
-   this.setState({ editable: nextProps.editable });
+ if (nextProps.editable !== this.state.editable || nextProps.value !== this.state.value) {
+    this.setState({ editable: nextProps.editable, value: nextProps.value });
      if (nextProps.editable) {
        this.cacheValue = this.state.value;
      }
    }
```

**Comment by SynChron1zed** [comment]
@nikogu  应该这这里的问题 没注意这一块 我以为这一块就是判断 editable  没有细看 thanks！！！

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/31503263-cd57f3ba-af34-11e7-91bc-75afc48b3cb7.png)

**Comment by SynChron1zed** [comment]
@nikogu  hi ！ 按照你的代码我改了 data的值更新了但是现在会出现这种情况 你看下这个动图 输入的值 只要光标移走就会恢复原值
https://im2.ezgif.com/tmp/ezgif-2-e2d35916e0.gif

**Comment by SynChron1zed** [comment]
@afc163  @nikogu  
发现了问题的所在  当columns 设置了 fixed: 'left' and  fixed: 'right', 的时候 光标进入 columns 就会触发  renderColumns（） 导致update的data值修改后会变回修改前的值  去掉 fixed: 'left' and  fixed: 'right' 移动光标就不会触发renderColumns（）  不知道这是什么原因
