### ISSUE TITLE
TreeSelect 调整为 Select 的子组件 Select.TreeSelect？

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#787]
粗略看了下 `Select` 和 `TreeSelect` 的逻辑，两者上面这部份基本是可以重用的。不同的只是，`Select` 下面用的是 `Menu`，而 `TreeSelect` 用的是 `Tree`，然后分别监听对应的 `onSelect` 之类的事件。

![image](https://cloud.githubusercontent.com/assets/3580607/12060335/481c115a-afa8-11e5-8e99-cf8465093669.png)

**Comment by warmhug** [comment]
select 中 60% 左右代码能重用，再加入 TreeSelect 还需要修改和增加不少代码，各种细节比较多；另外整合涉及到 menu 也可能会修改。综合修改成本比较大，现在先完善和业务里应用 TreeSelect 之后再搞。

**Comment by benjycui** [comment]
嗯，那先关了。
