### ISSUE TITLE
Can I set the RangePicker for  MonthPicker ?

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#7878]
### What problem does this feature solve?
有时我只需要精确度为月的RangePicker 。
Sometimes I just need precision for RangePicker of the month

### What does the proposed API look like?
<RangePicker type='month' />

**Comment by hansnow** [comment]
For now, you can implement this by two MonthPicker and `disabledDate`, https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end

**Comment by ChenYangShao** [comment]
`
    const { MonthPicker } = DatePicker;
`

**Comment by ChenYangShao** [comment]
```javascript
     const { MonthPicker } = DatePicker;
```

**Comment by Kunoky** [comment]
This I used, it needs an independent state to manage, make things troublesome

**Comment by hansnow** [comment]
implement a `MonthRangePicker` component by yourself will increase reuseability and reduce complexity.

**Comment by Kunoky** [comment]
Well, if you can do it, of course, it will be better, otherwise I can only do as you say

**Comment by benjycui** [comment]
See: https://github.com/react-component/calendar/pull/284

antd@3 will suport it.

**Comment by Kunoky** [comment]
That is to say, after 3.0, this API will be supported?
<RangePicker format="YYYY" showPanels={['year', 'year']} />
<RangePicker format="YYYY-MM" showPanels={['month', 'month']} />
<RangePicker format="HH:mm:ss" showPanels={['time', 'time']} />
