### ISSUE TITLE
when Menu contains Menu ,the submenu can not show

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#7881]
### Version
2.13.6

### Environment
macos chrome react16

### Reproduction link
[https://codepen.io/guoxiangwen/pen/boxVBp](https://codepen.io/guoxiangwen/pen/boxVBp)

### Steps to reproduce
1. <Menu> contains <Menu> 
2.second <Menu> contains submenu
3.Submenu can not show dropdown

### What is expected?
show dropdown

### What is actually happening?
not show

**Comment by afc163** [comment]
You should not nest Menu inside Menu, you can do it like this:

```jsx
<div>
  <Menu />   // float: left
  <Menu />   // float: right
</div>
```

**Comment by guoxiangwen** [comment]
ok,i will try this
