### ISSUE TITLE
FormItem & Input Height not match

### ISSUE THREAD

**Issue by syssam** [ant-design/ant-design#7884]
### Version
2.13.6

### Environment
macos chrome react16

### Steps to reproduce
1. set the input size="default"

### What is expected?
1. class="ant-form-item-control " should be 28px line-height
2. input using class "ant-input-default" when I have not set any size.
3. should provide input-padding-horizontal-base, input-padding-horizontal-sm, input-padding-horizontal-lg

### What is actually happening?
1. Form.Item does not match Input Height.
2. class "ant-form-item-control" has generated 32px line-height, but the input(ant-input) has generated 28px height.
3. input using class "ant-input-lg" when I have not set any size.
4. antd provide input-padding-vertical-base, input-padding-vertical-sm, input-padding-vertical-lg, but have not provide input-padding-horizontal-base, input-padding-horizontal-sm, input-padding-horizontal-lg, it is not make sense

**Comment by afc163** [comment]
https://ant.design/components/form/#Form-fields

>  By default, large size controls are used within a form.

---

It is by designed, you can set `size="default"` to override it.

**Comment by syssam** [comment]
Yes, I have set an Input size="default", but Form.Item class "ant-form-item-control" still is 32px line-height.You could check this.

On the other hand, could you provide input-padding-vertical-base, input-padding-vertical-sm, input-padding-vertical-lg less variable?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/d4a5606b92568d3204ecc3ddcf09540c8f0932b8/components/style/themes/default.less#L224-L226

**Comment by syssam** [comment]
Sorry, maybe my English is not well, let I using Chinese explain whats wrong.

```
<Form layout='vertical' onSubmit={this.handleSubmit} className="login-form">
        <FormItem
          label="Username">
          {getFieldDecorator('userName', {
            rules: [{ required: true, message: 'Please input your username!' }],
          })(
            <Input size="default" addonBefore={<Icon type="user" style={{ fontSize: 15 }} />} placeholder="Username" />
          )}
        </FormItem>
</Form>
```

這會顯示Input height是28px, 但class "ant-form-item-control"仍使用了@input-height-lg的32px line-height.

正確不是應該Input height是28px, class "ant-form-item-control"是28px line-height.否則Input只能永遠是使用size="large", 不能更改為"default" / "small"

另外，我想定制主题，less提供了input-padding-horizontal-base, input-padding-horizontal-sm, input-padding-horizontal-lg變量，但卻沒有提供input-padding-vertical-base, input-padding-vertical-sm, input-padding-vertical-lg less，若我只修改horizontal，會導致外觀不佳。

**Comment by afc163** [comment]
> 但卻沒有提供input-padding-vertical-base, input-padding-vertical-sm, input-padding-vertical-lg less，若我只修改horizontal，會導致外觀不佳。

👌 I see it, PR is welcome~

**Comment by afc163** [comment]
> 這會顯示Input height是28px, 但class "ant-form-item-control"仍使用了@input-height-lg的32px line-height.

https://codepen.io/afc163/pen/wrEQNz?editors=0010

表现上应该是没问题的。

**Comment by syssam** [comment]
是的，但若我修改了@input-height-lg為52px  @input-height-base為52px, 然後把input size 設置為default

這樣FormItem 與 FormItem之間的距離便不是margin-bottom: 24px;

@input-height-lg與@input-height-base ／@input-height-sm 數值差距愈大，表現卻與想像中有很大的出入

**Comment by afc163** [comment]
你可以同时定制 https://github.com/ant-design/ant-design/blob/0a6475cb0d5f707530897595f4ac6030d126daa1/components/form/style/index.less#L9 这个变量。

**Comment by syssam** [comment]
不同的表單會使用不同的Size, 這個似乎不能根本解決我的問題，會否增加不同size的 @form-component-height

**Comment by afc163** [comment]
> 不同的表單會使用不同的Size

我建议你还是用自定义样式覆盖比较合适。

**Comment by afc163** [comment]
input-padding-vertical-base, input-padding-vertical-sm, input-padding-vertical-lg

**Comment by syssam** [comment]
恩，不過如果你能做到，會更完美一些。
畢竟這些變量在定制的時候還是比較蠻常用的，謝謝。
