### ISSUE TITLE
Cascader showSearch fails if changeOnSelect turned off and the value of children field on leaf node is 0 size array.

### ISSUE THREAD

**Issue by lshxq** [ant-design/ant-design#7885]
### Version
2.13.4

### Environment
mac os | chrome 60.0.3112.90 | react 15.3.2

### Steps to reproduce
pass following json object as cascader's options
```javascript
const json = [
    {
        label : 'XXX',
        value : 'xxx',
        children : [
            {
                 label : 'YYY',
                 value : 'yyy',
                 children : []
            }
        ]
    }
]
```
The problem is if leaf node has a 0 size array as children field. The current process in flatternTree function won't consider it as a leaf node. Finally leads to showSearch function failed.

问题的原因是因为在cascader平面化可以过滤的被选项时，通过children字段是否存在来判断是不是叶子节点。如果不是叶子节点，那么必须是在changeOnSelect开启的情况下才能形成待检索的结果。  问题是我们后台在生成json对象的时候，叶子节点也生成children字段，只不过是空的array。如上面提供的json对象，这时在antd/.../cascader/index.js中的下面的这段代码，就不会把他当做叶子节点。最终导致无法进行过滤。 
```javascript
{
        key: 'flattenTree',
        value: function flattenTree(options, changeOnSelect) {
            ...
            options.forEach(function (option) {
                var path = ancestor.concat(option);
                if (changeOnSelect || !option.children) {
                    flattenOptions.push(path);
                }
                ...
            });
            return flattenOptions;
        }
    }
```

My workaround is update the if condition as below.  Consider current option as leaf node if children is undefined or 0 size array.

我本地的workaround是把这段代码修改如下， 当json的叶子节点没有children字段，或children字段为0 size的array时，都当做叶子节点处理。这样即便不开启changeOnSelect也可以正确检索了。
```javascript
{
        key: 'flattenTree',
        value: function flattenTree(options, changeOnSelect) {
            ...
            options.forEach(function (option) {
                var path = ancestor.concat(option);
                if (changeOnSelect || !option.children || 0 == option.children.length) {
                    flattenOptions.push(path);
                }
                ...
            });
            return flattenOptions;
        }
    }
```

### What is expected?
showSearch works as expect even if leaf node has 0 size array on children field and changeOnSelect turned off.
在不开启changeOnSelect的情况下，通过如下json构建cascader， 也能够正确进行检索。

### What is actually happening?
当children是 0 size的array时，  不被视为叶子节点，在关闭changeOnSelect和开启showSearch时无法过滤结果。

**Comment by benjycui** [comment]
An online demo will be better, thanks! Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close for no response.
