### ISSUE TITLE
Carousel width does not respond correctly with Sider collapse

### ISSUE THREAD

**Issue by bloodymushroom** [ant-design/ant-design#7887]
### Version
2.13.6

### Environment
env: macOS v10.12.6, browser: Google Chrome v61.0.3163.100

### Reproduction link
[https://codepen.io/bloodymushroom/pen/boxaxM?editors=001](https://codepen.io/bloodymushroom/pen/boxaxM?editors=001)

### Steps to reproduce
1. Create an antd Layout with a collapsible Sider and a Content.
2. Put a carousel with at least 2 items as children in the Content.
3. Collapse the Sider.
4. The width of the carousel children will not expand as the Content width expands - you will see part of item 2 in item 1's view.

### What is expected?
I expect that when the Sider is collapsed, the items in the Carousel with stretch to fit the view.

### What is actually happening?
When the Sider is collapsed, the items in the carousel retain their width and the second item of the carousel shows in the first item's view.

---
Carousel works fine when the window is resized - it may be the Sider animation that is causing problems with the Carousel not detecting the change in width. Ran into this bug while using creating an app using antd Layout with a Carousel in it.

**Comment by afc163** [comment]
According to https://github.com/akiran/react-slick/issues/27, you can set a new key to Carousel for re-layouting.

https://codepen.io/afc163/pen/oGPQEm?editors=0010

**Comment by bloodymushroom** [comment]
Thank you! I ended up triggering a resize event instead of setting the state in the setTimeout so that the entire carousel does not have to re-render.

**Comment by nwicakson** [comment]
For who met this problem.
`toggleSidebar = () => {
    this.setState({ collapsed: !this.state.collapsed });
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'));
    }, 300);
  }`
