### ISSUE TITLE
datepicker locale can't work correctly

### ISSUE THREAD

**Issue by nicewahson** [ant-design/ant-design#7889]
### Version
2.13.6

### Environment
chrmoe 61

### Reproduction link
[https://codepen.io/nicelj/pen/GMXwVo?editors=0010](https://codepen.io/nicelj/pen/GMXwVo?editors=0010)

### Steps to reproduce
1.click '选择时间'
2.choose any option

### What is expected?
locale set correctly

### What is actually happening?
can't

**Comment by benjycui** [comment]
Known issue, trace: https://github.com/ant-design/ant-design/issues/6712
