### ISSUE TITLE
你们好，请问一下，ant的组件怎么样才能继承？

### ISSUE THREAD

**Issue by wefiy** [ant-design/ant-design#789]
有些组件并不能满足使用需求，所以我修改了源代码。但是下次升级的时候会覆盖，请问一下我应该以什么方式继承才不对升级造成影响呢？

**Comment by zhujun24** [comment]
提具体需求的 issue 吧

**Comment by wefiy** [comment]
其实我想问集成或者覆盖ant组件的方式。

**Comment by afc163** [comment]
推荐高阶组件封装。

https://github.com/ant-design/ant-design/issues/770
