### ISSUE TITLE
How to make  nested table show different data in different rows?

### ISSUE THREAD

**Issue by missMHWGO** [ant-design/ant-design#7892]
### Reproduction link
[https://codepen.io/missMHWGO/pen/dVgegY](https://codepen.io/missMHWGO/pen/dVgegY)

### Steps to reproduce
I just follow the official website nested table, then I find the nested table show the same data in every parent table's row.

### What is expected?
I expect I can use different  nested tables in parent table's different row.

### What is actually happening?
Parent table's different row use same nested table and show same data.

**Comment by benjycui** [comment]
It is just a demo, it will works fine when you pass other data.

**Comment by missMHWGO** [comment]
@benjycui Can you show me a demo passing different data in nested table please, what I want to see is at parent table's rows, there are different data, but now I don't know how to do it or more specifically I dont't know how to pass different parameters to _expandedRowRender_? I tried to find the usage, but   nothing to find,I tried my best.Thanks.
