### ISSUE TITLE
The official site can't not be reached.

### ISSUE THREAD

**Issue by fachilles** [ant-design/ant-design#7895]
### Version
2.13.6

### Environment
chrome 

### Reproduction link
[https://ant.design/components](https://ant.design/components)

### Steps to reproduce
Visit the official site.

### What is expected?
The site is normal.

### What is actually happening?
The official site can't be reached.

**Comment by qiaoyixuan** [comment]
+1

**Comment by afc163** [comment]
```
curl -v https://ant.design
* Rebuilt URL to: https://ant.design/
*   Trying 47.88.240.14...
* TCP_NODELAY set
* Connected to ant.design (47.88.240.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```

Very werid problem which only happened for some people.

**Comment by afc163** [comment]
cc @fengmk2

**Comment by fengmk2** [comment]
Please use http instead temporarily http://ant.design/index-cn

**Comment by mountainmoon** [comment]
http://ant.design/index-cn has the same problem for me. But https://design.alipay.com/ can be reached.

**Comment by qiaoyixuan** [comment]
http not work too...@fengmk2

**Comment by fengmk2** [comment]
@mountainmoon @qiaoyixuan show me the log of `curl -v http://ant.design/index-cn`

**Comment by plhosk** [comment]
A minute ago the site (https://ant.design/) started working for me again.

**Comment by fengmk2** [comment]
@fachilles Can you try again?

**Comment by KevinJunJun** [comment]
+1

**Comment by chafel** [comment]
Normal now :clap::clap::clap:

**Comment by fachilles** [comment]
it's working already.

**Comment by afc163** [comment]
时好时坏，我们怀疑是 GFW 的缘故。

**Comment by dingchaoyan1983** [comment]
https://github.com/ant-design/ant-design/issues/7905

**Comment by fengmk2** [comment]
We will deploy `ant.design` on a new server today.

**Comment by YueHui** [comment]
google都能打开却打不开ant

**Comment by shunXwei** [comment]
@fengmk2  but I still cannot access it now

**Comment by afc163** [comment]
19 大的缘故。

**Comment by RifeWang** [comment]
一上午都是访问不了。

**Comment by Tommychou** [comment]
能告诉我怎么可以访问你们的官网么 从早上到现在都不行

**Comment by dingchaoyan1983** [comment]
我们直接在本地的server上面搭建一个，目前来说效果还可以

**Comment by yesmeck** [comment]
本地访问（建议 macOS or Linux）：

```bash
$ git clone https://github.com/ant-design/ant-design.git
$ cd ant-design
$ npm install
$ npm start
$ open http://127.0.0.1:8001
```

**Comment by jdz321** [comment]
为什么不放假让我们在家看直播😂

**Comment by coderzzp** [comment]
@yesmeck 你好，我按照你的方法npm start之后报错了TypeError: JsonML.getChildren(...).forEach is not a function，请问你有碰到过么

**Comment by yesmeck** [comment]
@coderzzp 删除 node_module 重新安装，刚刚有个依赖库发布了一个有问题的版本已经回退了。

**Comment by afc163** [comment]
对于最近的网络抽风问题，没有翻墙条件或者翻墙也无效的同学可以访问这个国内镜像站点：http://ant-design.gitee.io/index-cn

**Comment by qw123qw0324** [comment]
can't open https://ant.design/index-cn

**Comment by qw123qw0324** [comment]
can't open https://ant.design/index-cn

**Comment by duxianwei520** [comment]
![Uploading image.png…]()
想在本地假设个server，但是npm install之后再npm start报错@yesmeck

**Comment by duxianwei520** [comment]
![image](https://user-images.githubusercontent.com/3249653/31979012-0a881f34-b977-11e7-88eb-962985ca156e.png)
npm start之后报错，报错信息
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\tmp\style.less'
    at Object.fs.openSync (fs.js:651:18)
@yesmeck

**Comment by yesmeck** [comment]
@duxianwei520 因为我们都不用 windows ，所以你要自己搞定哦（欢迎 PR 回来），另外可以先访问上面提到的镜像。

**Comment by benjycui** [comment]
Windows 启动的问题，求救 @bang88 😄

**Comment by bang88** [comment]
明天

**Comment by bang88** [comment]
处理下这个路径就好了 @duxianwei520 先试试

**Comment by yesmeck** [comment]
😅https://github.com/ant-design/ant-design/commit/5660e815414f0de29683b96eff8ff1d6f70f39e2

**Comment by bang88** [comment]
😢

**Comment by duxianwei520** [comment]
@bang88  昨天我也解决了这个问题，有两种方案，一种是在d盘下面建立一个tmp的文件夹，第二种是把tmp这个路径去掉，我觉得第二种简单点的吧，不过第二种不好的地方是如果工程放在c盘下面，还是会报错，其他盘倒是没问题，@yesmeck 你发的最新的commit，是解决这个问题了么？

**Comment by bang88** [comment]
那是调试的代码。。 😄 更新就可以正常使用了

**Comment by duxianwei520** [comment]
@bang88 蒽，刚才更新了下，可以跑起来了，不错，选择有一个比较不好的地方就是这里面引用的图片跟字体文件还有svg等图表，有好多个来源，切都是在线的，所以我在内网搭建了一个之后，各种破图，本来想在Linux服务器上搭建的，报错的信息更多，心累

**Comment by haisapan** [comment]
the site was down, again

**Comment by duxianwei520** [comment]
@haisapan 自己本地搭建一个服务就好了，不用再看网上的

**Comment by lvSally** [comment]
http://ant-design.gitee.io， 目前只有访问pc版的镜像吗？有没有移动版的

**Comment by fengmk2** [comment]
@lvSally 你访问还有问题？能否改一下 hosts，测试一下新的 ip

```
47.74.140.126 ant.design
```

**Comment by lvSally** [comment]
@fengmk2 可以了，谢谢

**Comment by yesterlloy** [comment]
官网又打不开了，什么情况？但是能ping到

**Comment by lazyfighter** [comment]
官网打不开啦  可以ping通  但是丢包严重而且延迟非常高

**Comment by floatrx** [comment]
![Screenshot 2022-03-27 at 20 15 19](https://user-images.githubusercontent.com/6949882/160292797-74741459-7f96-427d-999e-d660e33ec8c3.png)

location: 🇺🇦

``` $ curl -v https://ant.design
*   Trying 188.114.96.7:443...
* connect to 188.114.96.7 port 443 failed: Operation timed out
*   Trying 188.114.97.7:443...
* connect to 188.114.97.7 port 443 failed: Operation timed out
* Failed to connect to ant.design port 443: Operation timed out
* Closing connection 0
curl: (28) Failed to connect to ant.design port 443: Operation timed out```

but works with VPN 🇺🇸 )))
