### ISSUE TITLE
Upload上传组件获取上传成功返回值

### ISSUE THREAD

**Issue by dinghuang** [ant-design/ant-design#7897]
我在action定义了api，并且成功进行文件上传，但是我想获取这个api执行成功后的返回值，在官方文档中，我没有看到有关这方面的内容

**Comment by ddcat1115** [comment]
check [onChange](https://ant.design/components/upload/#onChange)

**Comment by dinghuang** [comment]
![image](https://user-images.githubusercontent.com/20722776/31600257-60f5ccf4-b288-11e7-8d37-8c8fb1e2bea6.png)
customRequest中的onSuccess可以获得我想返回的值
