### ISSUE TITLE
select组件在validation中使用有问题

### ISSUE THREAD

**Issue by Liyuk** [ant-design/ant-design#790]
- `select`组件在`validation`中使用的时候，`option`的`key`会变成`key\\.$key`   

---
- 另外`select`设置多选`multiple`时，`option`的`key`值必须等于`value`，否则设置`defaultValue`为`key`数组时，不生效
```xml
<Option key={city}>{city}</Option>
```

**Comment by benjycui** [comment]
第一个问题，我本地无法重现，麻烦提供重现方式: http://jsfiddle.net/9zrstuto/70/

然后要注意你自己是否使用了 `React.Children.toArray`，这个方法会把 `key` 修改为 `.$key`。

**Comment by benjycui** [comment]
第二个问题，这不是预期的行为么？

**Comment by Liyuk** [comment]
第一个问题我使用姿势不对；第二个问题理解了。

**Comment by afc163** [comment]
:smile:
