### ISSUE TITLE
How to make nested table show different data in different rows?

### ISSUE THREAD

**Issue by missMHWGO** [ant-design/ant-design#7901]
### What problem does this feature solve?
At parent table's rows, there are different data in nested table.

### What does the proposed API look like?
These are pseudo code, I hope I have made it clear,thanks.
```
<Table
    columns = {columns}
    expandedRowRender = {( rowIndex ) => {
        const nestedTable = [nestedTable0, nestedTable1, nestedTable2];
        return nestedTable[rowIndex];
    }}				
    dataSource = {data}
/>
```

**Comment by afc163** [comment]
```
expandedRowRender={record => {
  if (record.xxx === 'xxx') {
    return 'xxxxx';
  }
  return 'yyyyy';
}}
```

**Comment by afc163** [comment]
Also fix the document: https://github.com/ant-design/ant-design/commit/fda3f6ddcd37356b7ff875823a0518e71d2a9872

**Comment by missMHWGO** [comment]
@afc163  It works fine now, thank you very much.
