### ISSUE TITLE
Table fixed and filter bug

### ISSUE THREAD

**Issue by loncus** [ant-design/ant-design#7909]
### Version
2.13.6

### Environment
mac PC,chrome 61

### Reproduction link
[https://stackblitz.com/edit/react-pjg1t3?file=index.js](https://stackblitz.com/edit/react-pjg1t3?file=index.js)

### Steps to reproduce
In the case of setting table column fixed,When column few and window wide ,table row will be repeated.
If dynamic cleanup fixed , Filter can't work.

### What is expected?
Do not repeat row and filter work

### What is actually happening?
See demo

**Comment by ddcat1115** [comment]
To prevent duplicate columns, you can make one unfixed column a flexible width, in your demo just remove the `width` setting in the `Column 1`.

I think the latter one is a bug.

**Comment by AnDrOlEiN** [comment]
I'am sorry, but this problem is actual on a lower versions too. Could you please commit this fix to 2.x-stable branch?
