### ISSUE TITLE
Can't open page when using a tag in Button component in Firefox

### ISSUE THREAD

**Issue by jjwong1991** [ant-design/ant-design#7911]
### Version
2.13.6

### Environment
Firefox

### Reproduction link
[https://codepen.io/jjwong1991/pen/aLQGBa](https://codepen.io/jjwong1991/pen/aLQGBa)

### Steps to reproduce
`<Button><a href="https://ant.design">a</a></Button>  //can't open`

`<a href="https://ant.design"><Button>a</Button></a>  //can open`

### What is expected?
always can open page

### What is actually happening?
can't open page when a tag in Button component

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6471
https://github.com/ant-design/ant-design/issues/4560
https://github.com/ant-design/ant-design/issues/3085#issuecomment-248213729
https://github.com/ant-design/ant-design/issues/5578
