### ISSUE TITLE
onClick for Tag component

### ISSUE THREAD

**Issue by danedavid** [ant-design/ant-design#7913]
### What problem does this feature solve?
Currently, if I give an `onClick` prop to the `Tag` component, the event fires on either the `div` or the `span` depending on where we click, and thus we cannot rely on it. Also, we have to use native DOM API such as event object to use these, but isn't that what React tries to avoid ? So we can have an onClick prop for the tag element. ( Anyway the cursor becomes a pointer on hover )

### What does the proposed API look like?
Add a prop `onClick` with a function as value to the Tag component that fires wherever I click inside it.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/oGQMaM?editors=0010

You can use it.

**Comment by danedavid** [comment]
@afc163  I meant why does the `e.target` change every time, depending on where I clicked ?

**Comment by afc163** [comment]
`e.currentTarget`
