### ISSUE TITLE
Table code Merge cells and modifications have conflicts

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#7916]
### Version
2.13.6

### Environment
chrome mac 

### Reproduction link
[https://codepen.io/anon/pen/veQVzJ](https://codepen.io/anon/pen/veQVzJ)

### Steps to reproduce
 render: (text, record, index) => {  const obj = {
            children: text,
            props: {},
          };
            if (index === 3) {
              obj.props.colSpan = 2;
            }
            return obj,
             this.renderColumns(this.state.data, index, 'age', text)
          }

同时返回的话 obj 合并单元格就会无效   

如果
             ---return obj,
             ----this.renderColumns(this.state.data, index, 'age', text)

改为  
                return obj；
                return this.renderColumns(this.state.data, index, 'age', text)
obj 合并单元格会生效 但是修改的话 点击按钮后这个单元格 不会出现input框

### What is expected?
合并单元格 可以和 修改 并存   是不是我的代码写的有问题求指教

### What is actually happening?
合并单元格 不能和 修改 并存

**Comment by nikogu** [comment]
请在写 `issue` 的时候尽量用英语，尽量高亮代码，明确问题，否则其他人很难看懂；

你的这个问题，官网 demo 里面有的：https://ant.design/components/table-cn/#components-table-demo-colspan-rowspan

```jsx
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  render: (text, row, index) => {
    if (index < 4) {
      return <a href="#">{text}</a>;
    }
    return {
      children: <a href="#">{text}</a>, // this.renderColumns
      props: { // setting colSpan
        colSpan: 5,
      },
    };
  },
}, {
```
