### ISSUE TITLE
AutoComplete height issue

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#7918]
### Version
2.13.6

### Environment
Chrome 61

### Reproduction link
[https://codepen.io/froston/pen/YrdzEv](https://codepen.io/froston/pen/YrdzEv)

### Steps to reproduce
Check the demo. Notice and compare the `AutoComplete` component with others.

### What is expected?
The default height of `AutoComplete` should be the same as of the other components.

### What is actually happening?
The height of `AutoComplete` is smaller then the one of `Input`, `Select` and other components

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/43d8c6ad378daa78455925f0e85c0534830c5a56
