### ISSUE TITLE
Smooth Progress Animation When Fast Percent Changing

### ISSUE THREAD

**Issue by wxyyxc1992** [ant-design/ant-design#7920]
### Version
2.13.6

### Environment
Mac PC,chrome 61

### Reproduction link
[https://stackblitz.com/edit/react-l3bgza](https://stackblitz.com/edit/react-l3bgza)

### Steps to reproduce
when the percent props of Progress is changed very fast, the animation is broken and unsmooth

### What is expected?
smooth animation 

### What is actually happening?
unsmooth

**Comment by benjycui** [comment]
Because the animation follow `cubic-bezier(0.08, 0.82, 0.17, 1)`, so if you put several animations together, it will be weirdo. 

It is difficult to fix unless we change the animation.

So, just debounce your update:

```jsx
let percentage = 0;
setTimeout(() => {
  // You may update percentage several time before setState
  // But only setState once
  setState({ percentage });
}, 300);
```

**Comment by ddcat1115** [comment]
@benjycui  I found the performance of circle type is better, can line type works in the same way?

**Comment by benjycui** [comment]
@ddcat1115 when I set animation of Progress[type=line] to `linear`, it looks better. But I think animation should follow our specification, and this issue is just an edge case.

So, @wxyyxc1992 you had better to override the animation of Progress.
