### ISSUE TITLE
IE11，不支持吗？Chrome下能正常显示。

### ISSUE THREAD

**Issue by hengchengfei** [ant-design/ant-design#7923]
只要在 `./app/Greeter,js` 里，引入了 Antd，在 IE 里就不显示了。（已经添加了 Webpack，Babel 等）
只要将下面两句注释掉，IE就能正常显示了。

是不是只要依赖antd一个就可以了呢？IE浏览器要安装什么补丁吗？

<img width="266" alt="1" src="https://user-images.githubusercontent.com/3182964/31702648-f7a7b594-b40a-11e7-8485-94a2abe77549.png">

我把项目放在 GitHub 上了，大牛帮忙看看，在 Chrome 里能运行。
运行方法：

```bash
npm install
npm run server
```

[https://github.com/webReactjs/test_webpack](https://github.com/webReactjs/test_webpack)

**Comment by hengchengfei** [comment]
has updated for english

**Comment by benjycui** [comment]
Need polyfill, please read the documentation.

**Comment by hengchengfei** [comment]
@benjycui 
but I had added them in webpack。

<img width="438" alt="1" src="https://user-images.githubusercontent.com/3182964/31708515-c103e60e-b421-11e7-9319-d88bdeef7a0f.png">
<img width="384" alt="4" src="https://user-images.githubusercontent.com/3182964/31708578-f97f17e2-b421-11e7-97c0-f8d97c17dc3e.png">
