### ISSUE TITLE
Tree-Select option's width is wrong in version with react version 16.0.0

### ISSUE THREAD

**Issue by yizhoucao** [ant-design/ant-design#7926]
### Version
2.13.6

### Environment
antd 3.0.0.alpha.15

### Reproduction link
[http://beta.ant.design/components/tree-select/](http://beta.ant.design/components/tree-select/)

### Steps to reproduce
http://beta.ant.design/components/tree-select/

### What is expected?
When the tree select option is opened for the first time, the width should be set correctly
![image](https://user-images.githubusercontent.com/20528741/31712463-ba16a9ec-b42d-11e7-9f6c-71b21db9fda5.png)

### What is actually happening?
When the tree select option is opened for the first time, the width is not set correctly
![image](https://user-images.githubusercontent.com/20528741/31712478-c5d049b4-b42d-11e7-86af-8bb7f3484eea.png)

**Comment by yizhoucao** [comment]
This is probably related to #7609

**Comment by ddcat1115** [comment]
@yesmeck  has fixed this in https://github.com/react-component/tree-select/commit/317adf0d1395d7bab8445c5a6041ca021dfb016d , you can try reinstall antd after we bump a new version of `rc-tree-select`

**Comment by yizhoucao** [comment]
thanks, will do

**Comment by yesmeck** [comment]
Fixed in rc-tree-select@1.10.10
