### ISSUE TITLE
RangePicker reverts selected values upon selecting second date

### ISSUE THREAD

**Issue by gavinrobertszeco** [ant-design/ant-design#7928]
### Version
2.13.6

### Environment
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/gRoberts84/pen/QqzJGP?editors=001](https://codepen.io/gRoberts84/pen/QqzJGP?editors=001)

### Steps to reproduce
1. Bind RangePicker `value` to the state.
2. Add `onOk` event handler to update the selected value to the state.

### What is expected?
RangePicker should retain selected dates until `onOk` is clicked, where the state will be updated with the selected values.

### What is actually happening?
When selecting the second date, the component reverts to the previously stored value in the state.

**Comment by ddcat1115** [comment]
The demo works fine, please check the difference between `onOk` and `onChange`. And the `onOk` button will show only when the `showTime` prop has been set.

**Comment by ddcat1115** [comment]
Close now, feel free to reopen it if there is any further question.

**Comment by gavinrobertszeco** [comment]
Hi @ddcat1115 

Apologies, I was meant of have enabled `showTime` in my example.

Maybe it's just confusion over how the component is meant to work, but if I'm binding on `value`, it appears that I always have to use `onChange` otherwise the selected value will be pulled from the state, overwriting the selected value?

As you can see from the updated codepen, I have added RangePickers with `showTime` enabled and the issue still applies. It's not possible to defer the selection until onOk is clicked, meaning I'll have to maintain two different states (i.e. we only want to commit the selection to state upon clicking OK)

Does that make sense?

**Comment by benjycui** [comment]
I don't understand your question, maybe you need to read [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action) first?
