### ISSUE TITLE
Table checkbox 如何取消选中

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#793]
场景：

选中 table 中一项，然后操作按钮高亮，点击按钮之后，发送请求，请求成功后更新 table dataSource， 之前选的那项 disabled，checkbox 不选中，按钮又置灰；

问题： 如何在更新了 dataSource 的时候让 disabled 的 checkbox 不被选中？

**Comment by afc163** [comment]
貌似目前搞不定，我来看下。

**Comment by afc163** [comment]
可以参照：http://jsfiddle.net/uaLag3zb/

现在更新数据会清空已选择的项，这样比较合理。

等我周末发个 0.11.2 ，会同步到 0.12.0-beta 上。

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-row-selection-and-operation

我稍晚发下 0.11.2 ，也会同步到 0.12.0-beta 上。

**Comment by afc163** [comment]
需要在 0.10.x 修复并给出用例。

**Comment by afc163** [comment]
0.10.5 的使用范例：http://jsfiddle.net/afc163/jt7bebq5/2/

现在更新 dataSource 会清空选中。

**Comment by silentcloud** [comment]
赞，去试试
