### ISSUE TITLE
table: scroll disrupts header and column alignment

### ISSUE THREAD

**Issue by tony-kerz** [ant-design/ant-design#7931]
### Version
2.13.6

### Environment
osx 10.11.6, chrome, react 16.0.0

### Reproduction link
[https://github.com/tony-kerz/express-oauth-scratch/tree/3101580d9d92f6339cde45cd12f5eada6bc6ad26](https://github.com/tony-kerz/express-oauth-scratch/tree/3101580d9d92f6339cde45cd12f5eada6bc6ad26)

### Steps to reproduce
- `yarn`
- `yarn run mock-dev`
- click "people" link in sider...

### What is expected?
table headers and columns will line up

### What is actually happening?
tables and headers are not lining up

---
commenting out [this line](https://github.com/tony-kerz/express-oauth-scratch/blob/3101580d9d92f6339cde45cd12f5eada6bc6ad26/src/front/people/results.js#L66) with the `scroll` option causes the columns to align...

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
![](https://gw.alipayobjects.com/zos/rmsportal/jPfXQKIePmyVvlPbGMfr.png)

You repo is not working.

Please provide a re-producible demo in codepen then we will reopen and see it.

**Comment by hermanfenderson** [comment]
Having exactly the same problem.

**Comment by hermanfenderson** [comment]
https://codepen.io/hermanfenderson/pen/POqVqZ?editors=0011 Here is a codepen.
I will submit any how a bug report

**Comment by MortimerJarasemy** [comment]
I would like to request the reopening of this issue, it keeps happening and there is no answer here

**Comment by tony-kerz** [comment]
agree with @MortimerJarasemy, reproducible storybook demo here: 

https://github.com/tony-kerz/antd-story

**Comment by tony-kerz** [comment]
here's an even simpler code-pen: https://codepen.io/tony-kerz/pen/mxQXvd
at first i thought it had to do with fixed columns, but apparently just around `scroll`.
fixed column examples in doc recommend scroll tho, so they are minimally related in that way.

**Comment by yesmeck** [comment]
@tony-kerz Please refer to the document https://ant.design/components/table/#components-table-demo-fixed-columns

> Specify the width of columns if header and cell do not align properly.

**Comment by RoudyTarabay** [comment]
Any updates on this?

**Comment by SourceCipher** [comment]
Updated today from 3.10.1 to 3.12.4 and now having this issue. Commented the `scroll` and the issue is gone, but we need to use scroll

**Comment by RoudyTarabay** [comment]
Any downside to just using overflow-y: scroll on the table container?

**Comment by entbit** [comment]
@RoudyTarabay Yeah, it breaks the sticky header.

**Comment by austospumanto** [comment]
Having the same issue.

**Comment by miun173** [comment]
I face the same issues, I had set the width for each column, but still it breaks the fixed header. Is there any solution?

**Comment by buday** [comment]
I have exactly the same issues. @afc163 do you have any solution?

**Comment by s-kris** [comment]
Same issues. Using overflow-y: scroll will break the sticky header. Any solution or quick-fix is appreciated. Thanks!

**Comment by aaronrbg** [comment]
also having this issue. solution?

**Comment by mrKorg** [comment]
I have the same problem. Doe's somebody have solution?

**Comment by keeganfrieslaar** [comment]
Any updates on this issue?....really need a solution if any1 has

**Comment by birdycn** [comment]
同样的问题

**Comment by santiagosemhan** [comment]
+1

**Comment by keeganfrieslaar** [comment]
In your columns array, when setting the width for each object, don't set a width for the last object in the array.

**Comment by Shaquu** [comment]
+1

**Comment by omarragi** [comment]
Does version 4 fix the problem ? it seems it does
v4
https://codesandbox.io/s/fixed-header-ant-design-demo-7uc9e?file=/index.js
v3
https://codesandbox.io/s/cocky-fermat-mrth2?file=/index.js
