### ISSUE TITLE
sound alert component

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#7935]
### What problem does this feature solve?
eg，when server send msg to browser ( by websocket ?), browser will notify user by some noise.

### What does the proposed API look like?
````
ComponentName.alert({
 soundPath: [soundPath]
 ...
})

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
I don't think we should do this, sorry.
