### ISSUE TITLE
RangePicker onCalendarSelect closes popup where showTime is not present

### ISSUE THREAD

**Issue by pebanfield** [ant-design/ant-design#7936]
### Version
2.13.6

### Environment
All 

### Reproduction link
[https://codepen.io/pebanfield/pen/MELJwd](https://codepen.io/pebanfield/pen/MELJwd)

### Steps to reproduce
1. Create a RangePicker
2. Add a custom footer
3. Attempt to handle onchange event and keep popup open

### What is expected?
API should allow better control of open/closed state during the onCalendarSelect interaction. This will better accommodate footer use cases and make the API more flexible and robust.

### What is actually happening?
This line in RC-Calendar dependency is closing the popup where there is no timepicker. 

https://github.com/react-component/calendar/blob/master/src/Picker.jsx#L114

---
Please see the codepen. My use case is to create a custom footer with custom date range selection buttons and api request settings. The api endpoint takes a range argument but also other arguments.

**Comment by pebanfield** [comment]
There are simple solutions. It just depends on whether you consider this an important use case and how you want to modify the api. 

For example, you could expose a prop of Picker - something like overrideClose. Then you modify [this condition](https://github.com/react-component/calendar/blob/master/src/Picker.jsx#L112) to include this property. Then you can set simply pass this property all the way down from DatePicker/RangePicker or you could make it the default where an extra footer is present.

**Comment by benjycui** [comment]
It is expected behavior, try to control it with `RangePicker[open]`

**Comment by pebanfield** [comment]
Yes I am using open, however, onCalendarSelect still closes the popup here - https://github.com/react-component/calendar/blob/master/src/Picker.jsx#L114

The popup close action is animated so it can't be controlled.

It is disappointing to put time into an explanation and be willing to help improve the api, but instead I get a very cursory response. Clearly you did not take the time to understand the problem.
