### ISSUE TITLE
Add an image upload component with a text description

### ISSUE THREAD

**Issue by wujingacross** [ant-design/ant-design#7939]
### What problem does this feature solve?
Many electric business scene, will upload pictures at the same time add the corresponding text description, to facilitate the client to the picture display

### What does the proposed API look like?
Depending on the type of distinction, you can choose to add the upload component with the image description.
Select the picture description function with the upload components, each upload a picture at the same time add an input input box, easy to enter the picture description, the return of the fileList also with the corresponding picture description information

**Comment by ddcat1115** [comment]
Maybe you can customize this component based on [Upload](https://ant.design/components/upload/)

**Comment by wujingacross** [comment]
But to upload pictures multiple-choice, onChange method, there is a photo upload images, and can't get I upload the total number of sheets, cannot be accurately know when upload finished
