### ISSUE TITLE
升级的时候能兼容一下老版本

### ISSUE THREAD

**Issue by andycall** [ant-design/ant-design#794]
antd 频繁升级，从0.10升级到0.11, 日历的 api 名字和用法很多都变了，老代码全部跪完，根本不像rc 亲爹 React 那样升级之后会在 console 提示旧版本 api 的 warning， 希望 antd 下次升级可以考虑各个版本的 api 兼容情况。

**Comment by afc163** [comment]
人力精力有限，升级方式不免粗暴，如有不便之处，非常抱歉。http://ant.design/docs/upgrade-notes
