### ISSUE TITLE
更新package.json中 rc-input-number 至 ~3.7.0

### ISSUE THREAD

**Issue by zzh-a** [ant-design/ant-design#7940]
### Version
2.13.6

### Environment
win7 版本 61.0.3163.100（正式版本） （64 位）

### Reproduction link
[http://ant.design/](http://ant.design/)

### Steps to reproduce
现版本中 rc-input-number 是 ~3.6.0  会拿到  rc-input-number@3.6.8   

这个版本的 rc-input-number组件在form 里面会有问题

### What is expected?
rc-input-number 更新至 3.7.0

### What is actually happening?
rc-input-number为 3.6.8

**Comment by zzh-a** [comment]
图贴不上来，这一段会有影响， 3.7.0 改过来了
```javascript
componentWillReceiveProps(nextProps) {
    if ('value' in nextProps) {
      const value = this.state.focused
        ? nextProps.value : this.getValidValue(nextProps.value);
      this.setState({
        value,
        inputValue: this.toPrecisionAsStep(value),
      });
    }
  },
```

**Comment by 282159468** [comment]
+1

**Comment by afc163** [comment]
@zzh-a 请描述问题。

**Comment by 282159468** [comment]
https://stackblitz.com/edit/react-dmsqpx?file=index.js 输入1立马变成1.00，以前是失去焦点才会处理格式

**Comment by 282159468** [comment]
@afc163 https://stackblitz.com/edit/react-dmsqpx?file=index.js

**Comment by zzh-a** [comment]
我也是这个问题

**Comment by afc163** [comment]
Broken after fix https://github.com/ant-design/ant-design/issues/7867

**Comment by afc163** [comment]
Fixed in rc-input-number@3.6.9
