### ISSUE TITLE
Table rowSelection[onChange]'s selectedRows not correspond with selectedRowKeys

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#7942]
When paginating on the server side, selectedRows may not correspond with selectedRowKeys.

**Comment by yesmeck** [comment]
#9751

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/issues/9751#issuecomment-410987043

**Comment by shilinmu** [comment]
This issue still exists in version 3.15.0

**Comment by crywolfx** [comment]
This issue still exists in version 3.20.5

**Comment by IMSupperkaka** [comment]
This issue still exists in version 3.23.1. 
That is important to keep selectedRowKeys and selectedRows same.

**Comment by gxmln159357** [comment]
maybe you can use selectedRowKeys and onSelect

**Comment by iaminvictus1993** [comment]
mark

**Comment by yoyo837** [comment]
The title of this issue seems to be the same as the title of #9571. What problem is this issue tracking now?

**Comment by fanxinjie** [comment]
In 3.26.9 Still have the bug.

**Comment by jin-benben** [comment]
In 4.0 Still have the bug.

**Comment by 389567702** [comment]
onSelectChange = (selectedRowKeys, selectedRows) => {
    // 处理翻页后，之前存储的selectedRows变为undefined
    // selectedRows合并新数组，过滤undefined，过滤留下对应selectedRowKeys的集合
    let tmpSelectedRows = this.state.selectedRows.concat(selectedRows).filter(item => item != undefined);
    let totalSelectedRows = selectedRowKeys.map(key => tmpSelectedRows.filter(item => item.conferenceSeq == key)[0])
    this.setState({ 
      selectedRowKeys, 
      selectedRows: totalSelectedRows
     });
  };

**Comment by zhangtsh5** [comment]
> maybe you can use selectedRowKeys and onSelect

when I using selectedRowKeys, I meet the same problem, that  selectedRowKeys only contain the rowkeys of current page

**Comment by imnobunny** [comment]
Any updates on this? Or can anyone share their temporary fixes for this bug? thanks!

**Comment by zombieJ** [comment]
Use `preserveSelectedRowKeys` after `antd@4.4.0`.

**Comment by sairabunny** [comment]
@zombieJ, Hello! I already migrated from v 3 to 4 and use the preserveSelectedRowKeys to my table but what about the selectedRows?  selectedRows still not correspond with selectedRowKeys.

**Comment by Even-Lau** [comment]
Seems that the issue has not been solved yet.

**Comment by Even-Lau** [comment]
> Use `preserveSelectedRowKeys` after `antd@4.4.0`.

It seems that this issue has not been solved yet. Did you ever read the headline clearly? @zombieJ

**Comment by MieszkoWrzeszczynski** [comment]
Still occurs in antd@4.11.2. Especially in rowSelection.onSelectAll(selected, selectedRows, changeRows) selectedRows are defined as   undefined when search is not empty.
