### ISSUE TITLE
Tab panes switched by keyboard arrow keys when using tabBarExtraContent

### ISSUE THREAD

**Issue by fix777** [ant-design/ant-design#7948]
### Version
2.13.6

### Environment
os version: macOS Sierra 10.12.6, browser version: Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/guoguo777/pen/VMgXEy?editors=0010](https://codepen.io/guoguo777/pen/VMgXEy?editors=0010)

### Steps to reproduce
1. Use tabBarExtraContent wrap `<Input />`.
2. Focus in `<Input />`.
3. Hit keyboard arrow keys (left or right).
4. You can see the tab pane will switched follow the arrow key hit.

### What is expected?
The cursor in `<Input />` will moved follow the arrow key hit.

### What is actually happening?
The tab pane switched follow the arrow key hit.

**Comment by benjycui** [comment]
Actually, it's not a bug, just stop propagation in your Input's keyboard event handler.

**Comment by zomars** [comment]
[Stop propagation isn't working](https://codepen.io/zomars/pen/JQVeaj?editors=0010)  @benjycui

**Comment by zomars** [comment]
Also related #9768
