### ISSUE TITLE
Customizable Spin indicator

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#7950]
### What problem does this feature solve?
By default the Spin component is hardcoded into 4 dots, there is no way to customize this behavior without doing css hacks.

### What does the proposed API look like?
Provide a props like `indicator` which accept a reactNode and display that node if it's provided, otherwise use the default 4 spinning dots.

I think I can PR if this feature gets approved

**Comment by ddcat1115** [comment]
Nice feature I think.

**Comment by afc163** [comment]
I don't think it is a useful feature. If you want to replace default dots with a new indicator. Why don't you use the indicator directly?

**Comment by kossel** [comment]
Because developers can still take advantage of other features of `Spin` component such like delay, tip, loading etc?

**Comment by afc163** [comment]
OK, you can PR to `antd-3.0` for this.
