### ISSUE TITLE
如何使用新加入的官方图标？

### ISSUE THREAD

**Issue by ronggang** [ant-design/ant-design#7954]
### Version
2.13.6

### Environment
Chrome 61.0.3163.100

### Reproduction link
[https://codepen.io/anon/pen/qPvdGE](https://codepen.io/anon/pen/qPvdGE)

### Steps to reproduce
直接打开重现链接 https://codepen.io/anon/pen/qPvdGE
可以看到 `search` 的图标是可以看到的，但官方新增的 `warning` 是看到不的

![image](https://user-images.githubusercontent.com/8065899/31801194-fcb2e1d4-b578-11e7-833e-97a8cdb88dd6.png)

![image](https://user-images.githubusercontent.com/8065899/31801218-2a9707c4-b579-11e7-9e78-c491f60de94e.png)

### What is expected?
使用新的图标

### What is actually happening?
看不到新图标

---
2.13.6 里的 css 指向的 iconfont 还是 `https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot` ，但这里应该不包含新的图标字体，如何获取新的官方链接？谢谢！

**Comment by ronggang** [comment]
现在只能自己抓文档页里的新链接，然后加到自定义的CSS中。是否需要官方发布 3.0 之后才会更新 antd 库？

**Comment by afc163** [comment]
文档部署错了，稍等我重新部署一下。

**Comment by afc163** [comment]
好了。

**Comment by afc163** [comment]
> 是否需要官方发布 3.0 之后才会更新 antd 库？

是的。

**Comment by ronggang** [comment]
@afc163 我应该缓存一下刚刚的页面。:smile:
