### ISSUE TITLE
The width of the Select component doesn't seem correct when first clicked

### ISSUE THREAD

**Issue by fc01** [ant-design/ant-design#7959]
### Version
antd 2.13.6
react 16.0.0
react-dom 16.0.0

### Environment
all

### Reproduction link
[https://codepen.io/fc01/pen/aLMdgK](https://codepen.io/fc01/pen/aLMdgK)

### Steps to reproduce
first clicked

### What is expected?
select option width is 150px

### What is actually happening?
select option width < 150px

**Comment by afc163** [comment]
Duplicate of #7609
