### ISSUE TITLE
select tags能否支持单选

### ISSUE THREAD

**Issue by mjfunny** [ant-design/ant-design#7960]
### What problem does this feature solve?
有需求在单选情况下,回填到输入框的效果和tags一样,但是查了下文档都说只支持多选.那么是否有其他API可以去修改回填的元素.

### What does the proposed API look like?
提供API去修改选中后回填到输入框的元素

**Comment by afc163** [comment]
单选的 Select[tags] 和 Input 有啥区别？

**Comment by afc163** [comment]
tags 本身就是复数，不支持单选。

**Comment by Pysics** [comment]
@afc163 和input的区别在于我能拿到label对应的value。现在mode为tags和multiple时都是多选，为combobox时却又要求label和value一样，唯独缺少一个单选功能。难道远程搜索的结果只能用作多选？我不明白这样设计的意义。

**Comment by afc163** [comment]
@Pysics `showSearch`

**Comment by HuYuee** [comment]
现在遇到了个问题，设置showSearch参数之后，在输入的时候，输入空格没有任何反应，数字和字母正常

**Comment by bestGao** [comment]
<Select
                      showSearch
                      placeholder="请输入关键字搜索"
                      filterOption={false}
                      notFoundContent={fetching ? <Spin size="small" /> : '无搜索结果'}
                      onSearch={this.fetchCf}
                      onChange={this.handleCf}
                      style={{ width: '100%' }}
                    >
                      {cf.map(d => (
                        <Option label={d.label} key={d.key}>
                          {d.label}
                        </Option>
                      ))}
                    </Select>)}

亲测可用哦
https://ant.design/components/select-cn/#header

**Comment by DaphneChang** [comment]
> 单选的 Select[tags] 和 Input 有啥区别？

区别在于Select支持一批预设好的下拉选项，支持用户快速回填
