### ISSUE TITLE
Is ant-design compatible with Rax?

### ISSUE THREAD

**Issue by AjaxJackjia** [ant-design/ant-design#7964]
### Version
2.13.6

### Environment
macOS 10.12.4; node v7.9.0; webpack 2; 

### Steps to reproduce
currently no thorough tests.

### What is expected?
I need to use Rax or Preact  to replace React in order to  have a better render performance. And I can't find any evidence related to this replacement. Hopefully, there is an official report about this change. Thanks.

### What is actually happening?
seamless compatible

**Comment by afc163** [comment]
We don't realy know it. We don't have plan to support those either right now. But if there are any PR to fix the compatible, we'd like to merge it.

**Comment by AjaxJackjia** [comment]
I will make a PR if necessary. Thanks.
