### ISSUE TITLE
antd   表格用fixed：“left”在typescript中报错

### ISSUE THREAD

**Issue by ng-work** [ant-design/ant-design#7965]
[ts]
Type '{ pagination: { total: number; pageSize: number; defaultPageSize: number; showSizeChanger: true; ...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Table<{}>> & Readonly<{ children?: ReactNode; }> &...'.
  Type '{ pagination: { total: number; pageSize: number; defaultPageSize: number; showSizeChanger: true; ...' is not assignable to type 'Readonly<TableProps<{}>>'.
    Types of property 'columns' are incompatible.
      Type '({ title: string; dataIndex: string; key: string; fixed: boolean; width: number; } | { title: str...' is not assignable to type 'ColumnProps<{}>[]'.
        Type '{ title: string; dataIndex: string; key: string; fixed: boolean; width: number; } | { title: stri...' is not assignable to type 'ColumnProps<{}>'.
          Type '{ title: string; dataindex: string; fixed: string; key: string; render: (text: any, record: any) ...' is not assignable to type 'ColumnProps<{}>'.
            Types of property 'fixed' are incompatible.
              Type 'string' is not assignable to type 'boolean | "left" | "right"'.
(JSX attribute) bordered: true

**Comment by yesmeck** [comment]
@ng-work Can you provide a reproduce repo?

**Comment by zlh19** [comment]
这个问题我也遇到了，没看到解决方案呢

**Comment by yesmeck** [comment]
@zh19 贴下代码吧，还有 TypeScript 和 antd 的版本。

**Comment by zlh19** [comment]
代码跟Table 组件固定列一样。只是加了typescript。
Table组件固定列，fixed:'left'|'right'为string的时候，ts报楼上的错误，设置成false无效。
antd ===3.1.0
typescript====2.5.3

**Comment by yesmeck** [comment]
如果你们先给  `fixed` 定义了 `string` 类型，那么是不允许赋值给 `'left' | 'right'` 的。

**Comment by zlh19** [comment]
什么都没有定义。
除了引入react，and模块外，其他模块都没引入。
总不会react自己定义了fixed为string吧

**Comment by yesmeck** [comment]
You need use type assertion.

```;
import { TableRowSelection } from 'antd/lib/table';

rowSelection(){
    return {
        fixed:true,
        onChange: (selectedRowKeys, selectedRows) => {
            this.setState({
                selectedRowKeys: selectedRowKeys  
            })
            console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
        },
        getCheckboxProps: record => {
            return ({
                disabled: record.name === 'Disabled User',
            })
        }
    } as TableRowSelection<any>;
}

<Table rowSelection={this.rowSelection()} dataSource={data} columns={columns} scroll={{ x: 2000 }} pagination={false}/>
```

**Comment by zlh19** [comment]
按你的方法推，看了源码interface ,是要
在columns=[{fixed:'left'} as ColumnProps<any>]就可以了

**Comment by fulvaz** [comment]
workaround 

columns: [
      {
        title: 'xxx',
        dataIndex: 'xxx',
        fixed: 'left' as 'left', // cast fixed
      },
]

**Comment by yukai-w** [comment]
you can [see the doc](https://ant.design/components/table/#Using-in-TypeScript)

**Comment by BinaryCaptain** [comment]
使用类型断言
```
columns: [
      {
        title: 'xxx',
        dataIndex: 'xxx',
        fixed: 'left' as const
      },
]
```

**Comment by yesmeck** [comment]
建议按文档上的例子那样来定义，那样是不需要额外的类型断言的。

https://ant.design/components/table/#Using-in-TypeScript

**Comment by huiye98** [comment]
> workaround
> 
> ```js
> columns: [
>       {
>         title: 'xxx',
>         dataIndex: 'xxx',
>         fixed: 'left' as 'left', // cast fixed
>       },
> ]
> ```

Thanks a lot !!!!

**Comment by soemxui195** [comment]
> workaround
> 
> ```js
> columns: [
>       {
>         title: 'xxx',
>         dataIndex: 'xxx',
>         fixed: 'left' as 'left', // cast fixed
>       },
> ]
> ```

tks god. Tks Bro <3

**Comment by AltRoot17** [comment]
> columns: [
>       {
>         title: 'xxx',
>         dataIndex: 'xxx',
>         fixed: 'left' as const
>       },
> ]

great, its worked for me

**Comment by 1273082756** [comment]
如果fixed是后台动态返回的呢, 如何消除这个warning

**Comment by yoyo837** [comment]
> 如果fixed是后台动态返回的呢, 如何消除这个warning

同样的, ts里转换一下, 类型不匹配的 as 一下
