### ISSUE TITLE
用columns fixed 写left和right 报错

### ISSUE THREAD

**Issue by ng-work** [ant-design/ant-design#7966]
### Version
2.13.6

### Environment
os

### Steps to reproduce
columns=[
            {
                title: 'QQ',
                dataIndex: 'qq',
                key: 'QQ',
                fixed:'left',
                width:150
            }]
写<Table colums={colums}/>报错

### What is expected?
11

### What is actually happening?
22

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)). We will reopen it if you provide enough information.
