### ISSUE TITLE
Suggest deleting ant-layout-sider-children style in CSS

### ISSUE THREAD

**Issue by neotiango** [ant-design/ant-design#7967]
# Version

2.13.6

# Environment

mac10.12.6 and chrome 62.0.3202.62

# Steps to reproduce

https://ant.design/components/layout/ 
Most of the reference Layout's Left Bar example

The height of the page when I was 100%, the scroll bars always appear, blank at the bottom of the body is greater than 15px, and always disrupted by the left sidebar Logo.

# What is expected?

Full the entire screen

# What is actually happening?

If you delete ant-layout-sider-children style, all issues are resolved, and the Logo height and margin can be adjusted freely, will not break the overall layout

**Comment by afc163** [comment]
You mean this one? https://github.com/ant-design/ant-design/pull/7716

Could you provide a demo to reproduce your problem? http://codepen.io/benjycui/pen/KgPZrE?editors=001

cc @zheeeng

**Comment by neotiango** [comment]
Like this https://codepen.io/tiango/pen/MExBjZ
and 
https://codepen.io/tiango/pen/rGRrjg?editors=0110     (please look:<Layout style={{height: "100%"}})>
Then, at the bottom of the page blank, probably 15px

so , if deleted ant-layout-sider-children:{height:100%}, will perfect

**Comment by neotiango** [comment]
And Logo area is also easy to cause damage.
similarly, ant-layout-sider-children is deleted, then Logo area,  changes of height and margin can be adjusted freely.
And I've do the following things

**index.css**
`.ant-layout-sider-children {
  height: 0;
}`

**index.js end**
`require("./index.css")
export default Index`

**Comment by afc163** [comment]
The problem is comfirmed, Thx for reporting it with so many details!

This bug is introduced by #7716 which due to margin collapse issue: https://stackoverflow.com/questions/19718634/how-to-disable-margin-collapsing

---

I gonna fix it by the solution from https://stackoverflow.com/a/33132624/3040605

**Comment by zheeeng** [comment]
Magic BFC
