### ISSUE TITLE
Tabs组件，默认风格 多选项卡，底部线条初始化经常性充满整个顶部页卡

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#7975]
### Version
2.13.7

### Environment
最新版

### Reproduction link
[https://codepen.io/anon/pen/oGOOzW?editors=001](https://codepen.io/anon/pen/oGOOzW?editors=001)

### Steps to reproduce
重新链接里重新不了这个现象，可能是渲染模式的问题
实际项目写个最简单的tabs  初始化的时候都经常会出现此问题

### What is expected?
初始化 页卡下划线宽度正常

### What is actually happening?
初始化 页卡下划线宽度经常会充满整个页卡所在div

**Comment by afc163** [comment]
trace #8001
