### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#7976]
### Version
2.13.7

### Environment
无

### Reproduction link
[https://codepen.io/null](https://codepen.io/null)

### Steps to reproduce
无

### What is expected?
正常访问

### What is actually happening?
响应时间过长

---
貌似服务器在国外，现在这段时期出不去，所以无法访问，是否有国内服务可以使用？

**Comment by dong894** [comment]
应该是被墙了，我用了科学上网可以访问的

**Comment by wy-Jay** [comment]
我用了科学上网  依然无法访问

**Comment by afc163** [comment]
Duplicate of #7895
