### ISSUE TITLE
There are some problems when I choose the date.

### ISSUE THREAD

**Issue by shihangbo** [ant-design/ant-design#7982]
### Version
2.13.4

### Environment
win 360最新

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design](http://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
There are some problems when I choose the date.
![19144310024189jd](https://user-images.githubusercontent.com/19473390/31875279-05058230-b793-11e7-883c-6c86aaf98da0.png)

### What is expected?
The normal display

### What is actually happening?
There are some problems when I choose the date.

**Comment by nikogu** [comment]
Need a demo in codepen.

**Comment by benjycui** [comment]
Close for no response.
