### ISSUE TITLE
how to turn off request to https://kcart.alipay.com/web/bi.do

### ISSUE THREAD

**Issue by pigletfly** [ant-design/ant-design#7987]
### Version
2.13.7

### Environment
"antd": "2.13.4"

### Reproduction link
[https://kcart.alipay.com/web/bi.do](https://kcart.alipay.com/web/bi.do)

### Steps to reproduce
sometimes it will request https://kcart.alipay.com/web/bi.do

### What is expected?
I find there is a request to https://kcart.alipay.com/web/bi.do, maybe it's used to collect some data usage,so is there a way to turn it off?

### What is actually happening?
how to turn it off

**Comment by afc163** [comment]
I think you can check G2 documentation.
