### ISSUE TITLE
Allow the option to add new Option through API calls in Select

### ISSUE THREAD

**Issue by dorkblue** [ant-design/ant-design#7988]
### What problem does this feature solve?
I have a Select component that is using data retrieved from my server API as options.

Sometimes user wants to add a new option directly from the Select Component, which requires API call to be made to the server to create a new document in the database.

### What does the proposed API look like?
Semantic UI React has a dropdown that allows addition. Custom function can be added as a onClick to send API calls to server

https://react.semantic-ui.com/modules/dropdown#dropdown-example-allow-additions

**Comment by zchodi** [comment]
hello @dorkblue do you have a temporary solution for this? we have the same concern. maybe you could help me.. tnx!

**Comment by dorkblue** [comment]
@zchodi hey. Currently what I'm doing is just to provide the user a button to trigger a modal, add the document from there and update state once the document is created.

**Comment by yutingzhao1991** [comment]
This feature Similar to `mode="tags"` https://codesandbox.io/s/olwy8kv6y5.

What the api should look like in antd? totally same as https://react.semantic-ui.com/modules/dropdown#dropdown-example-allow-additions?

**Comment by joshuagautham** [comment]
Will this be worked on? This is a great feature and could be added to the list of Ant Components

**Comment by yutingzhao1991** [comment]
@joshuagautham I think maybe Select with `mode="tags"` is enough https://codesandbox.io/s/olwy8kv6y5.

**Comment by joshuagautham** [comment]
No, tags is for multi select. I'm talking about a single select.

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/10831
