### ISSUE TITLE
Cascader Component Choice All children is unnecessary

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#7989]
### What problem does this feature solve?
In a form,  We need choice a place, such as, province -> city -> area. 

Most time, we need to choice all select. But, we only need choice province or city or area, in our business, sometime. 

Now, we need to add a switch, and the switch control the 3 Component (ProvinceSelect, CitySelect, AreaSelect) show. I think choice all children is unnecessary

### What does the proposed API look like?
support a new attribute

**Comment by hansnow** [comment]
没看懂你的英文描述，能用中文描述一下吗？

**Comment by xyy94813** [comment]
就是级联组件，加个开关允许我 不选择 所有的级联选项

**Comment by afc163** [comment]
`displayRender`

https://ant.design/components/cascader-cn/#components-cascader-demo-hover

**Comment by afc163** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-change-on-select
