### ISSUE TITLE
Select 选择器

### ISSUE THREAD

**Issue by whb101** [ant-design/ant-design#799]
Select multiple 像这种如果搜索出来的没有这个选项 会提示英文的Not Found  这个能设置吗 让他提示中文

**Comment by azl397985856** [comment]
<Select id="select" size="large" defaultValue="注册就送200条短信" notFoundContent="没有找到" optionFilterProp="text" showSearch onChange={this.setValue.bind(this, 'newpay')}>

**Comment by whb101** [comment]
?????

**Comment by l19861225q** [comment]
![select-not-found](https://cloud.githubusercontent.com/assets/4251365/12109994/97c2e562-b3c2-11e5-8ed0-cb13d573a29f.png)

**设置参数 notFoundContent="xxx"**

```
<Select 
    defaultValue="lucy" 
    style={{width:200}}
    showSearch 
    searchPlaceholder="输入"
    notFoundContent="没有找到">
...
```

**Comment by benjycui** [comment]
补充了文档，THX!
