### ISSUE TITLE
RangePicker: how to make the drop-down panel show always?

### ISSUE THREAD

**Issue by WeiFei365** [ant-design/ant-design#7990]
### What problem does this feature solve?
i don't want to click the input first, and then i will see the drop-down panel; is there any param to make the drop-down panel show always? i have tried the param: open, but it still auto close when i click other place;

### What does the proposed API look like?
anything

**Comment by nikogu** [comment]
You can using the `visible` prop to control it. https://ant.design/components/dropdown/#API

**Comment by WeiFei365** [comment]
oops! 🤕 sorry to make you misunderstood; i mean the component: **DatePicker.Range Picker**, not the Dropdown...

**Comment by benjycui** [comment]
Try [RangePicker[open]](https://ant.design/components/date-picker/#Common-API)
