### ISSUE TITLE
Generic of Table component doesn't work right in TypeScript

### ISSUE THREAD

**Issue by Calvin-Huang** [ant-design/ant-design#7991]
### Version
2.13.7

### Environment
newest browser (such as FF or Chrome)

### Reproduction link
[https://codepen.io/calvinpeak/pen/PJvPgO](https://codepen.io/calvinpeak/pen/PJvPgO)

### Steps to reproduce
Create a Table instance without any generic type argument.

### What is expected?
TypeScript compiler should reports error to remind that the Table component needs generic type argument.

[ts] Generic type 'Table<Data>' requires 1 type argument(s).

### What is actually happening?
TypeScript compiler doesn't detect the generic failure.

**Comment by yesmeck** [comment]
As the error message said, Table requires a type argument. See how to use Table in Typescript here https://ant.design/components/table/#Using-in-TypeScript
