### ISSUE TITLE
Allow for Custom Message type. 

### ISSUE THREAD

**Issue by adamaho** [ant-design/ant-design#7993]
### What problem does this feature solve?
This allows a user to customize the content of a message instead of being locked into the requested icons. I am suggesting we make use of message.custom which takes in any content and renders it in the message container. Essentially a blank message container. 

### What does the proposed API look like?
message.custom(content, duration, config) which returns 

```instance.notice({
    key,
    duration,
    style: {},
    content: (
      <div className={`${prefixCls}-custom-content ${prefixCls}-${type}`}>
        <Content />
      </div>
    ),
    onClose,
  });
  return (function () {
    let target = key  ;
    return function () {
      instance.removeNotice(target);
    };
  }());
}```

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
We won't treat message as a empty container without any antd own styling. You can custom your message.xx like antd.message.
