### ISSUE TITLE
我们的RestCloud微服务快速开发平台用的ant.d做后台管理界面

### ISSUE THREAD

**Issue by restcloud** [ant-design/ant-design#7994]
我们公司选了不少的WebUI框架，选来选出最后还是ant.d看起来最可行，功能确实强大不过问题也是有一些，总体很不错,想要的效果都能做出来.
产品：Rest微服务治理及快速开发平台
网址：<a href="http://www.restcloud.cn" target=_blank >http://www.restcloud.cn </a>
大家可以在线去看看实现的效果，可以在线直接看。
<img src='http://www.restcloud.cn/restcloud/res/images/mycms/webui/home.png'>
<img src='http://www.restcloud.cn/restcloud/res/images/mycms/webui/monitor.png'>
<img src='http://www.restcloud.cn/restcloud/res/images/mycms/webui/task.png'>
<img src='http://www.restcloud.cn/restcloud/res/images/mycms/webui/applist.png'>

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/477
