### ISSUE TITLE
tree重新加载问题

### ISSUE THREAD

**Issue by langwuzhe** [ant-design/ant-design#7999]
### Version
2.13.7

### Environment
谷歌浏览器

### Reproduction link
[https://github.com/langwuzhe/myAntd-](https://github.com/langwuzhe/myAntd-)

### Steps to reproduce
当Tree加载出来以后
1.随便点掉一个多选框，然后再选择上 2.点击下拉框使树重新加载另一组数据 重新加载出来的新树 多选框不会再次选中，随便点其中一个叶子节点，所有的节点会重新都选中

### What is expected?
重新加载新的树数据的时候，树能正常选中多选框

### What is actually happening?
在第一次加载出来的树上面操作多选框 ，重新加载新的树数据的后，多选框显示有问题

**Comment by benjycui** [comment]
Please make sure that you repo work, lots of deps are missing.

**Comment by yangfir** [comment]
官网访问不了了？

**Comment by benjycui** [comment]
Close for no response.
