### ISSUE TITLE
Text flicker caused by Checkbox

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#8000]
### Version
2.13.7

### Environment
chrome 61,

### Reproduction link
[https://codepen.io/twisger/pen/GMaeeW](https://codepen.io/twisger/pen/GMaeeW)

### Steps to reproduce
The text will flicker when you click Checkbox, which is obvious when the background is not white.  
It can't be repeat when the Checkbox and text are in a Modal.
It can't be repeat in firefox.

### What is actually happening?

---
It seems to be causeded by some css3 properties, how to avoid it?

**Comment by afc163** [comment]
#7564
