### ISSUE TITLE
There is a style bug when the Tabs component is initialized

### ISSUE THREAD

**Issue by nodeyu** [ant-design/ant-design#8001]
### Version
2.13.7

### Environment
macOS: 10.13, Chrome: 62.0.3202.62, dva: 1.2.1, react: 15.6.2

### Reproduction link
[https://codepen.io/nodeyu/pen/Xewwbp?editors=001](https://codepen.io/nodeyu/pen/Xewwbp?editors=001)

### Steps to reproduce
When I load or refresh the page in my project, this problem will appear. But it can not recurrent in codepen.

### What is expected?
The selected style will only add to  the activated tab when I load or refresh the page.
![image](https://user-images.githubusercontent.com/16318438/31932511-0dbadd0c-b8d9-11e7-935b-2eba436116ff.png)

### What is actually happening?
The selected style of the activated tab will fill the entire bottom of all the panel tabs, even though I set the "defaultActiveKey" property to Tabs component.
![image](https://user-images.githubusercontent.com/16318438/31932476-fba3d290-b8d8-11e7-989b-27e6fc9d0ed4.png)

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/7564#issuecomment-330420901

**Comment by nikogu** [comment]
If you are using dva, it will be like that ( style loaded after script ) in development environment. https://github.com/dvajs/dva/issues/1300
