### ISSUE TITLE
Sum of column values in footer.

### ISSUE THREAD

**Issue by remyvanderwereld** [ant-design/ant-design#8006]
### What problem does this feature solve?
At this moment there's no solution for adding the table totals in the footer. I tried to add a new table with one row in the footer but this table is not inline with the column width. 

### What does the proposed API look like?
It would be nice to add a footer attribute to the column properties.

**Comment by afc163** [comment]
Duplicate of #5710

**Comment by ehsansk** [comment]
we have same issue i want to sum of column data in that comun footer
