### ISSUE TITLE
Emitted value instead of an instance of Error

### ISSUE THREAD

**Issue by VanquisherMe** [ant-design/ant-design#8007]
### Version
2.13.7

### Environment
macOs

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
 return(
    <Table
      {...tableProps}
      title={() => `共搜索到 ${pagination.total} 条数据`}
      columns={columns}
      expandedRowRender={record => <p>{record.description}</p>}
      rowKey={record => record.id}
      dataSource={dataSource}
    />
  )

### What is expected?
succeed

### What is actually happening?
./node_modules/antd/lib/spin/style/index.less
(Emitted value instead of an instance of Error) autoprefixer: /Users/chen/WebstormProjects/NuggetFrontend/node_modules/antd/lib/spin/style/index.less:72:3: Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rules.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

---
How to solve？

![image](https://user-images.githubusercontent.com/4927398/31947699-8e9d0c40-b89a-11e7-9ed2-16d28702b381.png)

**Comment by tim-soft** [comment]
I'm getting a similar error, although it may not be antd's fault, could be related to autoprefixer

`(Emitted value instead of an instance of Error) autoprefixer: /srv/node/client-portal/node_modules/antd/dist/antd.less:13205:3: Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rules.`

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/3c1b4da51e1d5abd4b049994cc9a543fb5253993

**Comment by flyjennyetn** [comment]
@VanquisherMe  请问楼主解决了吗  我也遇到了这个问题
