### ISSUE TITLE
http://new-issue.ant.design 不能访问了，是不是不让提issue啦！

### ISSUE THREAD

**Issue by sumaolin** [ant-design/ant-design#8008]

**Comment by afc163** [comment]
http://downforeveryoneorjustme.com/new-issue.ant.design

可以访问，请尝试翻墙。

**Comment by qq645381995** [comment]
现在为什么要翻墙了？

**Comment by sumaolin** [comment]
求官网稳定啊，开发常查文档的，现在不稳定的被迫本地搭了个服务查，提issue这个怎么解决啊？

**Comment by afc163** [comment]
@sumaolin https://github.com/ant-design/ant-design/issues/7895

先尝试翻墙访问吧，政府这么搞，我们也很难过。

**Comment by qq645381995** [comment]
你这个网站不是部署在国内？  这中国的东西 真不知道你们为什么会中招？
