### ISSUE TITLE
发现横向的Menu一个BUG

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#801]
鼠标移动到Menu1出现二级菜单，这个时候直接移动到Menu2会导致二级菜单出不来，然后再移动到Menu3又正常出现二级菜单了。。

**Comment by afc163** [comment]
试着重现一下吧。https://jsfiddle.net/0dso5y0x/

**Comment by dyf2015** [comment]
0.11.0和0.11.1出现以下提示：
SCRIPT5007: 无法获取未定义或 null 引用的属性“slice”
jsfiddle下是正常的，jsfiddle是0.12.0吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/new?title=%E8%AF%B7%E5%A1%AB%E5%86%99%E7%AE%80%E6%B4%81%E6%9C%89%E6%95%88%E7%9A%84%E6%A0%87%E9%A2%98&body=**%E9%97%AE%E9%A2%98%E6%8F%8F%E8%BF%B0**%0A%0A%EF%BC%88%E6%8F%8F%E8%BF%B0%E4%B8%80%E4%B8%8B%E9%97%AE%E9%A2%98%EF%BC%89%0A%0A**%E5%8F%91%E7%94%9F%E7%8E%AF%E5%A2%83**%0A%0A-%20antd%20%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8F%8A%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8F%8A%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E5%9C%A8%E7%BA%BF%E6%BC%94%E7%A4%BA%E5%9C%B0%E5%9D%80%EF%BC%9A%0A%0A**%E9%87%8D%E7%8E%B0%E6%AD%A5%E9%AA%A4**%0A%0A1.%20...%0A2.%20...%0A%0A**%E7%BA%BF%E4%B8%8A%E9%87%8D%E7%8E%B0%E6%BC%94%E7%A4%BA**%0A%0Ahttp://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by dyf2015** [comment]
已解决，setState前加上非空判断即可
onToggle(info) {
		if(info.keyPath) {
		    this.setState({
		      openKeys: info.open ? info.keyPath : info.keyPath.slice(1)
		    });
		}
	},
