### ISSUE TITLE
TypeScript error TS7006 for 'calendar/Header.d.ts' and 'table/SelectionBox.d.ts'

### ISSUE THREAD

**Issue by aftdotleo** [ant-design/ant-design#8011]
### Version
3.0.0-alpha.19

### Environment
Node >= 8.4, TypeScript >= 2.5.0

### Reproduction link
[https://github.com/ant-design/ant-design/tree/antd-3.0](https://github.com/ant-design/ant-design/tree/antd-3.0)

### Steps to reproduce
in your new project:

1. tsconfig.json
set -> "strict": true,

2. npm cli
npm run build or npm run dev

### What is expected?
no error;

if input parameter is not generic, just `any` type is ok.

### What is actually happening?
node_modules/antd/lib/calendar/Header.d.ts(11,22): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/antd/lib/table/SelectionBox.d.ts(10,16): error TS7006: Parameter 'e' implicitly has an 'any' type.

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/5627#issuecomment-339056618
