### ISSUE TITLE
[3.0.0-alpha.19]: something inlines moment.js

### ISSUE THREAD

**Issue by drcmda** [ant-design/ant-design#8013]
### Version
3.0.0-alpha.19

### Environment
High Sierra

### Reproduction link
[https://github.com/ant-design/ant-design/blob/antd-3.0/components/select/index.tsx](https://github.com/ant-design/ant-design/blob/antd-3.0/components/select/index.tsx)

### What is actually happening?

```js
import enUS from '../locale-provider/en_US';
```

Ant inlines a locale that depends on moment.js, this adds 250kb, the second largest dependency in our bundle now. We do not use time-pickers or a calendar. I debugged it and the first module that fetches it is dropdown -> selector. It started to happen going from one version to another.

![screen shot 2017-10-25 at 11 34 20](https://user-images.githubusercontent.com/2223602/31991708-b2fec180-b978-11e7-87f8-e53e435f0e26.png)

### What is expected?
It should only require moment when it's needed.

**Comment by benjycui** [comment]
I will handle this, but it seem that you haven't ignore moment just like [this](https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L79). So you import all the locales.

**Comment by drcmda** [comment]
@afc163 @benjycui @yesmeck thank you all for the work you're putting into this daily!

**Comment by andriijas** [comment]
@drcmda how did you generate that image? thx
