### ISSUE TITLE
Maybe Form component not compatible with react-hot-loader

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#8014]
### Version
2.13.7

### Environment
Ubuntu,Chrome

### Reproduction link
[https://github.com/buxuku/antd-form-with-hot-loader](https://github.com/buxuku/antd-form-with-hot-loader)

### Steps to reproduce
If I import react-hot-loader in my project,

if a component was created by Form,

when I change the component,

The browser will throw an exception.

I have submited a demo @ [https://github.com/buxuku/antd-form-with-hot-loader](https://github.com/buxuku/antd-form-with-hot-loader)

### What is expected?
The Form component will work fine with  react-hot-loader

### What is actually happening?
The browser will throw an exception.

**Comment by buxuku** [comment]
In react-hot-loader@3.0.0,It trow an error with this message.

In react-hot-loader@3.1.1,It changed to throw a  warning with this message.

```
React Hot Loader: this component is not accepted by Hot Loader. \n' + 'Please check is it extracted as a top level class, a function or a variable. \n' + 'Click below to reveal the source location: \n', typeSignature
```

**Comment by benjycui** [comment]
Does react-hot-loader works fine with react-redux's connect?

**Comment by buxuku** [comment]
Sorry, I have not use react-redux in my project.

**Comment by benjycui** [comment]
> Sorry, I have not use react-redux in my project.

Just try and find if it will trigger errors, `Form.create` is similar with redux's `connect`

**Comment by buxuku** [comment]
OK, I have tested a project that with redux and without antd, it will trigger the same errors.

**Comment by benjycui** [comment]
> OK, I have tested a project that with redux and without antd, it will trigger the same errors.

So, this maybe an issue of react-hot-loader, see https://github.com/gaearon/react-hot-loader/issues/690
