### ISSUE TITLE
建议antd字体文件随包发布

### ISSUE THREAD

**Issue by shengbeiniao** [ant-design/ant-design#8015]
花了两个小时解决antd字体本地化问题，在issue里面看到很多类似的问题，但是都没有完美的解决方案，即便配置了modifyVars，解析出来的地址要么没有被webpack resolve，要么是相对node_modules/antd目录来解析，都会报找不到文件，如果字体文件像font-awesome那样随包发布就没有这些问题了，而modifyVars需要CDN覆盖时才使用

**Comment by shengbeiniao** [comment]
附代码
```
  const iconPath = '~/asset/antd';

  webpackConfig.module.loaders.forEach(loader=>{
    if(loader.test.toString().indexOf('less')>=0){
      loader.loader=`style!css!resolve-url!less?{"modifyVars": {"icon-url": "'${iconPath}'"}}`;
    }
  });
```

**Comment by futurist** [comment]
这里有两个问题：
1. `~/asset/antd` 表示用户目录，应为 `~asset/antd`
2. 可以添加配置 `resolve.modules` 加上你的源码目录：
```js
resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules']
}
```
这样 `~`会优化寻找源码目录
