### ISSUE TITLE
Fails to compile with Typescript 2.6

### ISSUE THREAD

**Issue by sandersn** [ant-design/ant-design#8018]
### Version
2.13.7

### Environment
Ubuntu, Typescript 2.6

### Reproduction link
[http://typescriptlang.org](http://typescriptlang.org)

### Steps to reproduce
```
$ npm install typescript@next
$ tsc
```

### What is expected?
No compile errors

### What is actually happening?
Three compile errors:
1. components/auto-complete/InputElement.tsx:15 "Property 'ref' does not exist on 'string | number | ...'."
2. components/auto-complete/InputElement.tsx:21 "Argument of type 'ReactNode' is not assignable to parameter of type 'ReactElement<any>'."
3. components/input/TextArea.tsx:118 "Spread types may only be created from object types."

---
Errors (1) and (2) are caused by https://github.com/Microsoft/TypeScript/pull/19185, which is a breaking change. Here's why this change causes error (1): 
1. Previously `Readonly<any>` was equivalent to `any`. In Typescript 2.6 it is equivalent to `{ [s: string]: any }`. 
2. React has `props: Readonly<{children: ReactNode}> & Readonly<P>`.
3. When `P=any`, as in the InputElement case, this means that `props: any` in 2.5, but `{ children: ReactNode, [s: string]: any }` in 2.6.
4. In 2.6, the compiler has `this.props.children: ReactNode`, which has no property named 'ref'. Previously, `children` was of type `any`, so there was no error.

Error (2) happens for a similar reason; now that `this.props.children: ReactNode`, `ReactNode` *might* be a `ReactElement<any>`, but there are lots of other options (`number | boolean | string | any[][] | ...`) that aren't checked for.

Error (3) is caused by stricter checking in object spreads; spreading `null` isn't allowed because it does nothing. `this.state.textareaStyles` is assigned null and never re-assigned in the body of `TextArea`, so the compiler thinks there's no point in allowing the spread. Probably the best fix is to put a type annotation on the declaration of `this.state` since presumably `this.state.textareaStyles` doesn't stay `null`.

**Comment by yanlee26** [comment]
`Argument of type 'typeof Popconfirm' is not assignable to parameter of type '"symbol" | "object" | "details" | "data" | "code" | "input" | "progress" | "select" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | ... 155 more ... | ` still existed! 

ts:version:^3.3.4000
