### ISSUE TITLE
使用timeline组件，如何让item里的内容保持html而不是被转为字符串

### ISSUE THREAD

**Issue by crury** [ant-design/ant-design#8019]
### Version
2.13.7

### Environment
chrome

### Reproduction link
[https://codepen.io/crury/pen/LzwmyE](https://codepen.io/crury/pen/LzwmyE)

### Steps to reproduce
在使用<Timeline.Item>{content} </Timeline.Item>时，如果content内容是html，会被转成字符串显示出来。

### What is expected?
content会被解析成html而不是字符串

### What is actually happening?
content被解析成字符串

**Comment by benjycui** [comment]
https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
