### ISSUE TITLE
Upload组件样式问题

### ISSUE THREAD

**Issue by MaxLee1994** [ant-design/ant-design#802]
当Upload的listType为picture时，`file.name`是英文字符时显示正常，中文字符时显示不正常(会掉下去）

<img width="631" alt="2016-01-02 14 59 40" src="https://cloud.githubusercontent.com/assets/5857749/12073614/2a825012-b162-11e5-931e-63c37bf3ac75.png">

antd@0.11.1
react@0.14.3

**Comment by afc163** [comment]
见鬼了 chrome 下还真是这样，中文英文不知道有啥区别。。
