### ISSUE TITLE
Notification update and not closable.

### ISSUE THREAD

**Issue by callmemb** [ant-design/ant-design#8021]
### What problem does this feature solve?
Would allow to make progress bar on icon slot, change text based on app state, and so much more.
I dont see reasons for blocking edit on closable param, please unlock it.

### What does the proposed API look like?
Best way to use it would be

    key = "newKey";
    let n = notification.open({
      key,
      message: 'title',
      icon: (<Progress type="circle" width={38} percent={0} />),
      duration: 0,
      closable: false
    });

// steps ->

    notifications.update( key, { 
      icon: (<Progress type="circle" width={38} percent={50} />),
    });
    
//  end ->
    
    notifications.update( key, { 
      message: 'all done here',
      icon: (<Progress type="circle" width={38} percent={100} />),
      closable: true
    });

**Comment by nikogu** [comment]
i think is not necessary to do that.

u can disabled auto close by setting `duration` to `null` then control `closable` though setting styles by `className` property.

**Comment by callmemb** [comment]
yes, it's posible to do it like this, but in my opinion it is more like hack than proper solution.
ant notifications are build on top of 'rc-notification', there closable is a propertie. I just think we shuld have access to it, so we dont need to hide its effects with css.

Still .. it's just part of issue, what is your opinion on update ?

**Comment by afc163** [comment]
Try this way:

```jsx
  notification.open({
    message: 'Notification Title',
    description: <MyProgress />,
  });
```

https://codepen.io/afc163/pen/BmLKqg?editors=0010

**Comment by LaiHuanMin** [comment]
@afc163 thanks for reply, the component 's desgin is perfect!

**Comment by callmemb** [comment]
It is far from being perfect.
In 99% cases the value of progress will be defined outside of the component which we can give as a description.
So:
```
  notification.open({
    message: 'Notification Title',
    description: <MyProgress progress={this.state.progress} />,
  });
```
But this approach does not work. That's why the 'update':
```
  let key = notification.open({
    message: 'Notification Title',
    description: <MyProgress progress={0} />,
  });
  notification.update(key,{
    description: <MyProgress progress={12} />,
  });
```
Or simply make 'open()' with 'key' prop update already displayed notifications.
```
  notification.open({
    key: 'known key',
    message: 'Notification Title',
    description: <MyProgress progress={this.state.progress} />,
  });
```

**Comment by callmemb** [comment]
Why this issue is closed ?

**Comment by toxsick** [comment]
I agree with @callmemb completely. Not being able to update already existing notification makes it extremely had to use in cases where the content has to change over time...

**Comment by callmemb** [comment]
@afc163 please open this issue.

**Comment by tiffon** [comment]
I must second that having a way to update a notification would be a powerful enhancement.

It's possible to update the content in a notification, now, as linked in the [comment above](https://github.com/ant-design/ant-design/issues/8021#issuecomment-342369019), but that doesn't cover scenarios where you want to update the actual notification, itself. For instance, in the code-pen, how to allow the close X to be visible only after the progress is done (without resorting to CSS hacks involving things like classes outside the notification)?

Awesome work on **ANT DESIGN FTW**!!!  🎉 🎉 🎉

**Comment by yevhen-hryhorevskyi** [comment]
@afc163 @yesmeck I did the required changes in order to make it possible update the notification content via key. Can you please take a look at least to that PR and say if you are OK to merge it or not?

**Comment by yesmeck** [comment]
@yevhen-hryhorevskyi I also think we should not add this feature to `notification`, the imperative call is not encouraged in react, maybe we should reconsider the API design of `notification`.

**Comment by yevhen-hryhorevskyi** [comment]
@yesmeck actually in large apps react may not be responsible for toast notifications. Depends on the situation. 
For example, people who use redux + any existing solution for async handling may simply write tricky logic.
For example, we have a user form with his info and ability to edit it.
We may create a simple component with validation and 'Save' button. If info saved successfully, we want to redirect to the home page with success notification. Otherwise, we need to show the error and give a user one more try...
We need to show toast with 'Saving' after user clicks the 'Save' button. After the response is received we need to update it with success toast ('Saved') or error toast ('Unable to save user info. Please, try again or concat the support team.').
```
async function saveUserInfo(userInfo) {
  const notification = NotificationService.pending('Saving'); // Some service that wraps rc-notification
  actions.disableUserInfoForm(); // setting some flag to disable form till the end of the request
  try {
     await axios.put(`/api/v1/users/${userInfo.id}`, userInfo);
     notification.success('Saved');
     NavigationService.openHomePage();
  catch(e) {
     notification.error('Unable to save user info. Please, try again or concat the support team.', e);
  }
  actions.enableUserInfoForm(); // setting some flag to enable form back
} 
```
This is quite easy example from the real enterprise apps when you need to separate view part from controllers and have rich UX. Otherwise, such apps takes more efforts for support. 

I don't want to start topic that I may create container for a simple toast text, create a separate reducer, etc. Then it makes no sense to use `rc-notification` static syntax at all.

**Comment by yesmeck** [comment]
Sounds reasonable.
