### ISSUE TITLE
It is recommended that you add the 'selectable' attribute to the tree component document

### ISSUE THREAD

**Issue by wengwengweng** [ant-design/ant-design#8022]
### What problem does this feature solve?
The tree component document does't provide attributes that the parent node can't be selected.

### What does the proposed API look like?
Read the source found antd provided this feature but not exposed in the document, hoping to explain in the document to avoid unnecessary development

**Comment by benjycui** [comment]
You can PR to update the documentation, thanks.

**Comment by wengwengweng** [comment]
PR has been raised.
https://github.com/ant-design/ant-design/pull/8048
