### ISSUE TITLE
Editable table example doesn't work for multi-page table

### ISSUE THREAD

**Issue by llevar** [ant-design/ant-design#8026]
### Version
2.13.7

### Environment
Mac OS X, Chrome, React latest

### Reproduction link
[https://codepen.io/Llevar/pen/zPOOdB](https://codepen.io/Llevar/pen/zPOOdB)

### Steps to reproduce
The editable rows example on https://ant.design/components/table/ works well enough on tables that have a single page, but breaks down for tables with more than one page. This is because the code uses an index variable to update state. This index is relative to the current page that you are on, whereas the state is not aware of pages and thus the wrong records end up being updated.

See codepen, but basically add more records to force a second page to be created. Try to edit a row on the second page. Without clicking on Save or Cancel navigate to the first page and observe that the corresponding row on the first page is also expanded. Inspect the state to see that the wrong record has been marked as editable. 

### What is expected?
It is expected that this code works on tables with multiple pages.

### What is actually happening?
The table does not work on tables with multiple pages. The right row appears to be editable, but also the same row on the first page is editable, and the state has the incorrect row marked as editable.

**Comment by afc163** [comment]
You should not use `index` to identify the data item, it is not accurate because it means the record's index number of current page. You should always use `key` to get the correct record.

**Comment by llevar** [comment]
@afc163 Please reopen the issue, I'm not the one using index. Your own example code on https://ant.design/components/table/ (https://github.com/ant-design/ant-design/blob/master/components/table/demo/edit-row.md) is using the index.

**Comment by afc163** [comment]
That is our mistake, I will fix the demo later, thank you for your report.

**Comment by llevar** [comment]
Thanks, I'm looking forward to your fix. I migrated the code over on my side to use the key which works but I end up computing

```
const recordIndex = Array.indexOf(
            this.state.data.map(obj => obj.key),
            record.key,
          );
```
several time, which is probably not going to be snappy for tables with lots of rows. I hope you have a more elegant solution.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/2d17d8a7689585ce4fec5fa78996a5fedd3fad78/components/table/demo/edit-row.md
