### ISSUE TITLE
ant-design 自定义主题 custom theme 的文档 webpack中配置说明

### ISSUE THREAD

**Issue by sumaolin** [ant-design/ant-design#8028]
### What problem does this feature solve?
非atool-build 使用（antd-init 和 dva-cli 均支持）创建项目中的 自定义主题
官网的说明：[修改 Ant Design 的样式变量](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme)
### 首先读取 package 中的theme配置
```
// antd theme 配置
var fs = require('fs')
const pkgPath = path.resolve(__dirname, './package.json')
const pkg = fs.existsSync(pkgPath) ? require(pkgPath) : {}
let theme = {}
if (pkg.theme && typeof pkg.theme === 'string') {
  let cfgPath = pkg.theme
  // relative path
  if (cfgPath.charAt(0) === '.') {
    cfgPath = path.resolve(__dirname, cfgPath)
  }
  const getThemeConfig = require(cfgPath)
  theme = getThemeConfig()
} else if (pkg.theme && typeof pkg.theme === 'object') {
  theme = pkg.theme
}
```
这时候theme已经是object，不知道 其给出的[参考配置](https://github.com/ant-tool/atool-build/blob/a4b3e3eec4ffc09b0e2352d7f9d279c4c28fdb99/src/getWebpackCommonConfig.js#L131-L138)中`"modifyVars":${JSON.stringify(theme)}}` 为啥又进行了两次转义，这个是试了 直接把变量写给modifyVars才踩出来的；

还是给出的配置中` test: /\.module\.less$/,`加载loader时候，为啥加`\.module`，我还是匹配的`/.less$/`只是这个只解析antd模块中的 ： `include: path.resolve(__dirname, 'node_modules/antd'),`

### 正确的loader配置
直接写webpack 中loader 的配置吧，别的不清楚的网上查吧 （如：ExtractTextPlugin），webpack版本用的最新的 `v 3.6.0` less的模块请用v 2.7.2 最新的有bug
```
{ 
  test: /\.less$/,  // 自己用用的less
  exclude: path.resolve(__dirname, 'node_modules'),
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader' },
      {
        loader: 'less-loader',
      },
    ],
  }),
},
{
  test: /.less$/,  // antd 中的less
  include: path.resolve(__dirname, 'node_modules/antd'),  //这个路径要写准确，否则报错
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
      },
      {
        loader: 'less-loader',
        options: {
          sourceMap: true,
          modules: false,
          modifyVars: theme,
        },
      },
    ],
  }),
},
```

**Comment by afc163** [comment]
Thx for your clarification.
