### ISSUE TITLE
Menu.Item caused warning of "Stateless function components cannot be given refs"

### ISSUE THREAD

**Issue by harryzhux** [ant-design/ant-design#8029]
### Version
2.13.7

### Environment
ubuntu 16.04, chrome 62.0.3202.62 (Official Build) (64-bit). react/react-dom 16.0.0

### Reproduction link
[https://github.com/harryzhux/issue-antd-menuitem](https://github.com/harryzhux/issue-antd-menuitem)

### Steps to reproduce
Here is the github project can be used to reproduce the problem: https://github.com/harryzhux/issue-antd-menuitem
% git clone https://github.com/harryzhux/issue-antd-menuitem
% cd issue-antd-menuitem
% npm install
% npm start
This should open the browser @http://localhost:3000.
Mouse over the down-arrow button to show the menu items and use browser's Inpect feature to see the warnings (in red).

### What is expected?
None

### What is actually happening?
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.null

---
The "null" part in the message is fixed by Facebook React team (see https://github.com/facebook/react/issues/10831).

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/7968

**Comment by afc163** [comment]
ref #5377
