### ISSUE TITLE
npm install --save antd 提示 UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by fxn9801** [ant-design/ant-design#8030]
### Version
2.13.7

### Environment
浏览器谷歌

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
安装antd 
npm install --save antd

D:\我的工具箱\项目框架\project_v1>npm install --save antd
project_v1@0.1.0 D:\我的工具箱\项目框架\project_v1
 -- antd@2.13.7
|  -- array-tree-filter@1.0.1
|  -- css-animation@1.4.1
| | `-- component-classes@1.2.6
| |   `-- component-indexof@0.0.3
|  -- dom-closest@0.2.0
| | `-- dom-matches@2.0.0
|  -- lodash.debounce@4.0.8
|  -- moment@2.19.1
|  -- omit.js@1.0.0
|  -- rc-animate@2.4.1
|  -- rc-calendar@9.0.4
| | `-- rc-trigger@1.11.5
| |   `-- rc-align@2.3.4
| |     `-- dom-align@1.6.5
|  -- rc-cascader@0.11.6
| | `-- shallow-equal@1.0.0
|  -- rc-checkbox@2.0.3
|  -- rc-collapse@1.7.6
|  -- rc-dialog@6.5.11
|  -- rc-dropdown@1.5.1
|  -- rc-editor-mention@0.6.13
| |  -- dom-scroll-into-view@1.2.1
| |  -- draft-js@0.10.4
| |  -- immutable@3.7.6
| | `-- rc-editor-core@0.7.8
|  -- rc-form@1.4.8
| |  -- async-validator@1.8.1
| | `-- hoist-non-react-statics@1.2.0
|  -- rc-input-number@3.6.9
| | `-- rc-touchable@1.2.3
|  -- rc-menu@5.0.13
|  -- rc-notification@2.0.6
|  -- rc-pagination@1.12.10
|  -- rc-progress@2.2.2
|  -- rc-rate@2.1.1
|  -- rc-select@6.9.5
|  -- rc-slider@8.3.5
|  -- rc-steps@2.5.2
|  -- rc-switch@1.5.3
|  -- rc-table@5.6.13
| |  -- lodash.get@4.4.2
| | `-- shallowequal@0.2.2
| |   `-- lodash.keys@3.1.2
| |      -- lodash._getnative@3.9.1
| |      -- lodash.isarguments@3.1.0
| |     `-- lodash.isarray@3.0.4
|  -- rc-tabs@9.1.5
| | `-- rc-hammerjs@0.6.9
| |   `-- hammerjs@2.0.8
|  -- rc-time-picker@2.4.1
|  -- rc-tooltip@3.4.9
|  -- rc-tree@1.7.8
|  -- rc-tree-select@1.10.11
|  -- rc-upload@2.4.3
| |  -- attr-accept@1.1.0
| | `-- warning@2.1.0
|  -- rc-util@4.1.1
| |  -- add-dom-event-listener@1.0.2
| | `-- shallowequal@0.2.2
|  -- UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0
|  -- UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.0.0-0
|  -- react-lazy-load@3.0.12
| |  -- eventlistener@0.0.1
| | `-- lodash.throttle@4.1.1
| `-- shallowequal@1.0.2
 -- UNMET PEER DEPENDENCY react@16.0.0
`-- UNMET PEER DEPENDENCY react-dom@16.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none
 was installed.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but
none was installed.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was ins
talled.
npm WARN react-lazy-load@3.0.12 requires a peer of react@^0.14.0 || ^15.0.0-0 bu
t none was installed.
npm WARN react-lazy-load@3.0.12 requires a peer of react-dom@^0.14.0 || ^15.0.0-
0 but none was installed.

### What is expected?
正常安装无报错

### What is actually happening?
报如上：
|  -- UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0
|  -- UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.0.0-0
 -- UNMET PEER DEPENDENCY react@16.0.0
`-- UNMET PEER DEPENDENCY react-dom@16.0.0
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none
 was installed.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but
none was installed.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was ins
talled.
npm WARN react-lazy-load@3.0.12 requires a peer of react@^0.14.0 || ^15.0.0-0 bu
t none was installed.
npm WARN react-lazy-load@3.0.12 requires a peer of react-dom@^0.14.0 || ^15.0.0-
0 but none was installed.

---
我的环境其他包版本：
"react": "^16.0.0",
"react-addons-pure-render-mixin": "^15.6.2",
"react-dev-utils": "^4.1.0",
"react-dom": "^16.0.0",
"react-hot-loader": "^3.1.1",
"react-redux": "^5.0.6",
"react-router": "^4.2.0",
 "react-router-dom": "^4.2.2",

**Comment by afc163** [comment]
- https://github.com/akiran/react-slick/pull/866

**Comment by yesmeck** [comment]
这个还是要升一下 https://github.com/ant-design/ant-design/pull/7953n

**Comment by fxn9801** [comment]
地址是404您给的
