### ISSUE TITLE
tabs 组件下划线消失

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#8032]
### Version
2.13.7

### Environment
最新版

### Steps to reproduce
上次是下划线宽度有问题，看了作者给的链接更新了下rc-tabs，结果下划线直接消失了，之后删掉node_modules重新安装模块，还是如此，直接复制官网tabs第一个最简单的demo列子，同样如此。

### What is expected?
初始化 页卡下划线正常

### What is actually happening?
初始化 页卡下划线消失
而且加入 tabpane没有内容似乎切换动画都没有了

![tim 20171027115016](https://user-images.githubusercontent.com/23353032/32087344-c029f3c0-bb0d-11e7-9747-314efad336b4.png)

**Comment by afc163** [comment]
Try rc-tabs@9.1.9

**Comment by huyawei** [comment]
@afc163 。。就是9.19  看了下是宽度为0 所以应该不是我这边css的锅

**Comment by afc163** [comment]
能给个重现么，还有浏览器和操作系统的版本。

**Comment by huyawei** [comment]
@afc163 
![tim 20171027141417](https://user-images.githubusercontent.com/23353032/32090292-43389d58-bb21-11e7-8833-e8753fbf3563.png)
chrome 60.0.3112.101 32位

最新版 npm install dva-cli
dva new test
npm install antd babel-plugin-import --save

route文件夹下 indexPage.js 修改为
```js
import React from 'react';
import { connect } from 'dva';
import styles from './IndexPage.css';
import {Tabs} from 'antd';
const TabPane = Tabs.TabPane;
function IndexPage() {
  return (
    <Tabs defaultActiveKey="1">
      <TabPane tab="Tab 1" key="1">Content of Tab Pane 1</TabPane>
      <TabPane tab="Tab 2" key="2">Content of Tab Pane 2</TabPane>
      <TabPane tab="Tab 3" key="3">Content of Tab Pane 3</TabPane>
    </Tabs>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);

```

就是上面图片的效果

**Comment by afc163** [comment]
尝试重装 node_modules，`rc-tabs@9.1.5 ~ rc-tabs@9.1.9` 我都 unpublish 了。

**Comment by huyawei** [comment]
@afc163  好吧，这样的话 宽度问题 是下个版本解决了？

**Comment by afc163** [comment]
重装 node_modules 就可以了。

**Comment by huyawei** [comment]
@afc163   npm install   cnpm install  整体安装 rc-tabs 都是9.1.4版本。  这个版本宽度的确有问题 记得你之前发的链接里说的是9.1.5修复。现在回到9.1.4 刚才测试了下宽度还是老样子

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7564#issuecomment-339888082

**Comment by huyawei** [comment]
@afc163  react-component/tabs#104  被关闭了，刚才更新了下 rc-tabs 9.1.10, 发现还是有这个问题，这个问题 下划线初始化的时候消失现在解决了吗？

**Comment by afc163** [comment]
下划线初始化的时候过长的问题在 9.1.10 里解决了。

> 下划线初始化的时候消失

这个没法解决，目前的实现方式就是渲染之后才能去添加高亮条。

**Comment by 476474988** [comment]
下划线初始化的时候消失
有版本解决计划吗？

**Comment by afc163** [comment]
官网是好的哦，有问题请使用 http://new-issue.ant.design/ 按模板详细报告问题。

@476474988

**Comment by huyawei** [comment]
@476474988  看底层代码所有的参数，目测没得解决，当然你可以在界面初始化的时候做一次 state变更重新render下界面就正常了

**Comment by YJKZHUZHU** [comment]
antd tabs 子组件触发了props的更新，导致切换tab之后下划线消失，但文字还是高亮的，求解决办法
