### ISSUE TITLE
formItem 的key值不能带‘.’

### ISSUE THREAD

**Issue by 422809585mls** [ant-design/ant-design#8034]
### Version
2.13.7

### Environment
reacr

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-dynamic-rule](https://ant.design/components/form-cn/#components-form-demo-dynamic-rule)

### Steps to reproduce
如果formItem 的key值带点，在提交时就会把该key对应的值变为一个对象，原本的键名也会被从小数点开始截取

### What is expected?
如果formItem 的key值带点，在提交时就会把该key对应的值变为一个对象，原本的键名也会被从小数点开始截取

### What is actually happening?
为什么会有这个问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2965
https://github.com/react-component/form/pull/48

**Comment by yesmeck** [comment]
![its-not-a-bug-its-a-feature](https://user-images.githubusercontent.com/465125/32089303-cf95c9b0-baae-11e7-9279-401fba1fc722.jpg)

**Comment by mythinking** [comment]
{getFieldDecorator(`${this.props.searchFields.first.name}`)(<Input placeholder={"请输入" + this.props.searchFields.first.desc} />)}

可以这样写，用ES6反引号

**Comment by AceLeeWinnie** [comment]
反引号并不生效，还是会把 key 拆开
```javascript
const moduleId = 'modules-1.9';
getFieldDecorator(`${moduleId}`);
form.setFieldsValue({ [`${moduleId}`]: fieldValue });
```

**Comment by wangzf-no1** [comment]
I don't want to use this feature, I just want to "."
What should I do?

**Comment by lifeneedspassion** [comment]
fuck this feature

**Comment by topwood** [comment]
有些场景就是有.的，能都关掉这个功能，目前只能将.替换成_,获取值后再换回来，很蛋疼的写法
