### ISSUE TITLE
<Upload /> to upload unsupported files, method beforeUpload return false, then fileList is mistakenly bleached

### ISSUE THREAD

**Issue by BryantZhou** [ant-design/ant-design#8036]
### Version
2.13.1

### Environment
MAC/WIN chrome 61.0

### Reproduction link
[https://codepen.io/funya/pen/pdzaRB?&editors=001](https://codepen.io/funya/pen/pdzaRB?&editors=001)

### Steps to reproduce
Under ver.2.13, when use <Upload /> to upload unsupported files, method beforeUpload return false, then fileList is mistakenly bleached. The same problem is not detected under ver.2.12

### What is expected?
Unsupported don't replace and empty the fileList

### What is actually happening?
Unsupported files empty the fileList and replace it

**Comment by benjycui** [comment]
@afc163 after beforeUpload return false, we just pass fileList to developers:

https://github.com/ant-design/ant-design/blob/9583bb4c8522f42b0f94d201b7f9afbc5cea22aa/components/upload/Upload.tsx#L226-L232

I think we should concat the fileList with `this.state.fileList`, just link onStart:

https://github.com/ant-design/ant-design/blob/9583bb4c8522f42b0f94d201b7f9afbc5cea22aa/components/upload/Upload.tsx#L80-L103

**Comment by w567675** [comment]
me too.  when will it be fixed?

**Comment by modao** [comment]
I meet the same problem，hope this will be fixed soon~

**Comment by Hfimy** [comment]
Now i meet the same problem when beforeUpload return false  ,the fileList  turns into a wrong fileList that contain only type errors , my solution is to add a flag in the wrong file , and when return false ,do not change the fileList in handleChange
```
beforeUpload = (file) => {
    if (!/jpe?g|png$/.test(file.type)) {
        // message.error('Picture format error');
        file.flag=true;
        return false;
    }
    const isLt2M = file.size / 1024 / 1024 < 2;
    if (!isLt2M) {
        // message.error('Picture size more than limit(2M)');
        file.flag=true;
        return false;
    }
    return true;
}

handleChange = ({ fileList, file }) => {
     if (file.flag) {
         return;
      }
      this.setState({fileList}) 
}
```
