### ISSUE TITLE
dora -p 8001 没有启动

### ISSUE THREAD

**Issue by jsers** [ant-design/ant-design#804]
```
> antd-demo@1.0.0 dev /Users/xxx/git/src/demo
> dora -p 8001 --plugins atool-build,proxy,hmr

          proxy: listened on 8989
📦  311/311 build modules
webpack: bundle build is now finished.
```

osx 10.10.2 
node v5.3.0
npm 3.3.12  

原本用的是antd 0.10.x 以及对应的antd-init和相关工具，本来想直接用新版的antd-init boilerplate的package.json覆盖目前的package.json。
但是 `npm run dev` 跑起来后各种错误,怀疑跟es6的babel有关。
后来直接antd-init 重新init个，然后起了以后 就是上面情况，dora -p 8001 没起成功。

**Comment by afc163** [comment]
没发现任何报错呢。。

**Comment by jsers** [comment]
是没有报错， 但是正确的时候 不应该 `dora: listened on 8001`

**Comment by afc163** [comment]
那个是代理的端口，不是应用的端口，无视就好。

**Comment by afc163** [comment]
@sorrycc 提示信息可以优化一下。

**Comment by jsers** [comment]
额，我明白，不是提示信息的问题
sorrycc的dora 会起一个8001的server和proxy的8989
现在只有proxy起了，8001的server没起

**Comment by jsers** [comment]
我没有升级node和npm前, `npm run dev`后是这样的
```
 dora: listened on 8001
 proxy: listened on 8989
```

**Comment by jsers** [comment]
sorry 看来真是提示问题。
8001起了，只是没有提示。
由于开了代理，导致localhost:8001无法访问。

**Comment by sorrycc** [comment]
8001 端口的提示故意隐藏的，不要关心 8001 端口了，只关心 8989 端口吧。
