### ISSUE TITLE
In vertical mode,The submenu is displayed incorrectly

### ISSUE THREAD

**Issue by xforgchengz** [ant-design/ant-design#8040]
### Version
2.13.7

### Environment
win7、chrome55.0.2883.87

### Reproduction link
[https://ant.design/components/menu-cn](https://ant.design/components/menu-cn)

### Steps to reproduce
In the demo,When I turn the mode to 'vertical',Then my mouse over the menuitem 'Navigation Three -> Submenu',It start Flashing

### What is expected?
The submenu can displayed correctly in 'vertical' mode.

### What is actually happening?
The submenu can displayed incorrectly in 'vertical' mode.

**Comment by xforgchengz** [comment]
![image](https://user-images.githubusercontent.com/10679567/32097329-c3c71a20-bb3b-11e7-86d4-7e50da609e98.png)

**Comment by nikogu** [comment]
`<SubMenu key="sub2" title="Submenu">` there have `2` keys, we will fixed it
