### ISSUE TITLE
Disabling Scrollable Tab Bar

### ISSUE THREAD

**Issue by SpringsTea** [ant-design/ant-design#8043]
### What problem does this feature solve?
I would prefer it if I could set tabs to wrap instead of the automatic scroll.

So instead of:
<|ab | Tab | Tab |Ta>

It would be:

| Tab | Tab |
| Tab | Tab |

### What does the proposed API look like?
Just an option to disable the scroll feature.

**Comment by benjycui** [comment]
`antd` must follow Ant Design Specification. If you don't need these scrollable/animation features, you can implement your own Tabs, it will be simple.

**Comment by Shahriar-Shakil** [comment]
this is an important approach I think. can anyone help with this issue
