### ISSUE TITLE
RangePicker with showTime has an error when I disabled all seconds

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#8047]
### Version
2.13.7

### Environment
mac OS 10.10.5 (14F2511)

### Reproduction link
[https://codepen.io/anon/pen/XzWMEy?&editors=001#anon-login](https://codepen.io/anon/pen/XzWMEy?&editors=001#anon-login)

### Steps to reproduce
1.选择日期范围
2.点击选择时间

### What is expected?
1.点击选择时间后,秒那一列应该直接隐藏,因为设置的日期格式是YYYY-MM-DD HH:mm 
2.选择时间后, 确定按钮需要可点击

### What is actually happening?
1.尽管设置了日期格式是"YYYY-MM-DD HH:mm",但是选择时间时秒那一列依然在
2. 确定按钮一直是灰色,好像是因为disable了所有的秒,导致没法选择秒

**Comment by benjycui** [comment]
See: https://ant.design/components/date-picker/#components-date-picker-demo-time

You must set time format in `RangePicker[showTime]`, code is not smart enough to slice time format from date format.
