### ISSUE TITLE
使用了Cascader组件或FormItem label属性使用表达式，build打包后服务器环境出错页面空白

### ISSUE THREAD

**Issue by riguang** [ant-design/ant-design#8049]
### Version
2.13.7

### Environment
Chrome 46.0.2490.86 m

### Reproduction link
[https://github.com/riguang/issue-antd](https://github.com/riguang/issue-antd)

### Steps to reproduce
复制了官网Form组件里注册demo的源码，只保留两个FormItem，其中使用了Cascader组件调试环境页面一切正常，build后放在服务器环境报错，打开主页面空白但是资源全部已载入。

### What is expected?
页面应该呈现且没有报错。

### What is actually happening?
控制报错：Uncaught TypeError: Cannot read property 'onMouseEnter' of undefined
页面空白

---
使用create-react-app脚手架按照官网的配置来的，不使用Cascader组件build后就不会报错，这个是BUG吗？

**Comment by benjycui** [comment]
`antd` does not fully support preact.

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/5048
