### ISSUE TITLE
第一个components button按钮在IE8下无法正常显示样式

### ISSUE THREAD

**Issue by jiehwa** [ant-design/ant-design#805]
第一个components button按钮在IE8下无法正常显示样式。
http://ant.design/components/button/#demo-basic 这个网址用ie8浏览器打开。。发现很多buttom按钮看不到。

**Comment by benjycui** [comment]
虽然样式很丑，但还是有显示的：

![image](https://cloud.githubusercontent.com/assets/3580607/12082526/d04a31f0-b2ce-11e5-87dc-7ca81508c588.png)


确认下你能加载这个样式：http://ant.design/dist/demo.css
