### ISSUE TITLE
add option for 'Select' component to remove selected items from dropdown

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#8050]
### What problem does this feature solve?
Currently as you select multiple items from the DropDown list of 'Select', it does not remove those items, it just marks those items as 'selected'.
For a lot of UX use cases, it is better to have those selected items no longer show up in the list.

### What does the proposed API look like?
add a property for the option like `clearSelectedItems=true` which will filter the dropdown list of the already selected items.

**Comment by hansnow** [comment]
You can implement this by you own.
demo: https://codepen.io/hansnow/pen/LOENWp?editors=001

![image](https://user-images.githubusercontent.com/4365899/32154367-37b3579c-bd6b-11e7-8d2a-18765d09d33a.png)
