### ISSUE TITLE
Select Component Breaks on Certain Pasted Inputs in Tags Mode

### ISSUE THREAD

**Issue by ryanbaer** [ant-design/ant-design#8051]
### Version
2.13.8

### Environment
macOS 10.12.6, Chrome v61

### Reproduction link
[https://codepen.io/ryanbaer/pen/OOJBWO](https://codepen.io/ryanbaer/pen/OOJBWO)

### Steps to reproduce
1. Create a new Select component with a field separator of your choice
2. Somewhere else, write the following input: `[non-field separator][field separator,][non-field separator]`
- Example (field separator `','`): `tag1,,,,,,tag2`
3. Copy it and paste it into the Select field
4. Note that the component breaks with the error: `Uncaught Error: must set key for <rc-animate> children`

### What is expected?
The component should not break when pasting in invalid input

### What is actually happening?
The component breaks and becomes unusable until refreshing the page

---
This issue is incredibly similar to: https://github.com/ant-design/ant-design/issues/5831
The resolution of that issue involved your dependency, `rc-select`, issuing a new release with a fix. However, the fix didn't address the scenario I've illustrated above.

**I've already made a fix to `rc-select` and it was merged in a few minutes ago**:
https://github.com/react-component/select/pull/239

This issue is more to notify you that, once `rc-select` makes a release, you should update to get the latest changes that will hopefully resolve this issue on your Select component.

**Comment by yesmeck** [comment]
Fixed in `rc-select@6.9.6`. Try reinstall node_modules.

**Comment by ryanbaer** [comment]
Didn't realize this was by the same maintainers. Thanks.
