### ISSUE TITLE
Form 行内排列 Select 样式显示不正常

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#8054]
### Version
2.13.8

### Reproduction link
[https://codepen.io/anon/pen/bYNBbr?editors=0010](https://codepen.io/anon/pen/bYNBbr?editors=0010)

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/wPBooP?editors=0010

The `Select` don't have a default width, you have to set one.
