### ISSUE TITLE
Using with next.js report error in production

### ISSUE THREAD

**Issue by mebtte** [ant-design/ant-design#8056]
### Version
2.13.0

### Environment
all

### Reproduction link
[https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60SubPopupMenu%60](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60SubPopupMenu%60)

### Steps to reproduce
it is normal in development, after running `next build` and starting service, the browser will report error.

### What is expected?
normal

### What is actually happening?
report a error

---
error message:
Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60SubPopupMenu%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by afc163** [comment]
trace https://github.com/zeit/next.js/issues/2849

It maybe not be a antd issue.

**Comment by mebtte** [comment]
thanks
