### ISSUE TITLE
如何在getFieldDecorator中拿到Cascader中的label?

### ISSUE THREAD

**Issue by petitspois** [ant-design/ant-design#8057]
### Version
2.13.8

### Environment
mac os 10.10.5

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
getFieldDecorator中拿到Cascader中的label?

### What is expected?
getFieldDecorator中拿到Cascader中的label?

### What is actually happening?
getFieldDecorator只拿到Cascader中的value?

**Comment by afc163** [comment]
Duplicate of #8055
