### ISSUE TITLE
Input cannot focus when using HOC as a wrapper

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#8059]
### Version
2.13.8

### Environment
Chrome 62.0.3202.75

### Reproduction link
[https://codepen.io/CallMeXYZ/pen/zPxZeM](https://codepen.io/CallMeXYZ/pen/zPxZeM)

### Steps to reproduce
As the link

### What is expected?
focus input and input sth

### What is actually happening?
the first input cannot focus

**Comment by yesmeck** [comment]
Don't create component in render.
