### ISSUE TITLE
clearFields of Form

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#8062]
### What problem does this feature solve?
Clear all the form values `to undefined` rather than` initialValue` or add `defaultValue` to `getFieldDecorator` option which can be reset to `undefined`

### What does the proposed API look like?
```
this.props.form.clearFields();
// or add defaultValue option to getFieldDecorator
```

**Comment by afc163** [comment]
1. First of all, `undefined` is not a valid value to React Controlled Component.
2. Also, you can do this by customize `setFieldsValue`.
3. `initialValue` is the default value of form control under `getFieldDecorator`.
