### ISSUE TITLE
Ability to close other expanded row when expand icon clicked

### ISSUE THREAD

**Issue by prionkor** [ant-design/ant-design#8063]
### What problem does this feature solve?
In case of long expanded row user needs to scroll up to close the box. This will help the ux. 

### What does the proposed API look like?
pass instance of the table as third argument of `onExpand` callback. Where we set close other expanded row.

**Comment by afc163** [comment]
Use `expandRowKeys` to control it.

**Comment by prionkor** [comment]
You meant `expandedRowKeys`? I did tried it by binding with state but when I do it seems the table is unable to update the property and rows doesn't expand at all!

`render()`
-----------
```
<Table
    expandedRowKeys={this.state.expandedRowKeys}
/>
```

`onExpand` Callback
------------------
```
	onTableRowExpand(expanded, article){
		var keys = [];
		if(expanded){
			keys.push(article.id);
		}

		this.setState({expandedRowKeys: keys});
		if(expanded){
			this.props.getVariations(article.id);
		}
	}


```

Is there any other way to `get` and `set` that property? Using state doesn't seem to work.

**Comment by Zukhrik** [comment]
const function(){
  const [state, setState] = useState([])
  
  return (
    <Table
      columns={columns}
      dataSource={dataSource}
      expandable={{
        expandedRowRender: (record, index, indent, expanded) => record.lastName,
        onExpand: (_, {id}) => setState([id]),
        expandedRowKeys: state
      }}
    />
  )
}
