### ISSUE TITLE
upload中的文件删除（onRemove）能在其他功能方法中调用

### ISSUE THREAD

**Issue by mayunyi** [ant-design/ant-design#8069]

**Comment by mayunyi** [comment]
比如 我附件在表格中  我删除一行表格数据怎么把附件删除？

**Comment by mayunyi** [comment]
` uploadProps=(field,index)=>{
        return {
            name: 'file',
            action: `${FILE_API}/api/user/files/`,
            headers: {
                authorization: 'authorization-text',
            },
            showUploadList:true,
            data(file) {
                return {
                    name: file.name,
                    a_file: file,
                };
            },
            beforeUpload() {
                return true;
            },
            onChange: (values) => {
                const {file, fileList: [doc = {}]} = values;
                if (file.status === 'done') {
                    const {a_file} = doc.response || {};
                    let state = this.state;
                    state.form.plans[index][`${field}_name`] = doc.name;
                    state.form.plans[index][`${field}_path`] = a_file;
                    state.planFileArr[index]=values.fileList[0];
                    this.setState(state)
                };
            },
        }
    }
handleRemoveImage(file){
        debugger
        console.log(file);
    }

 //点击事件 表格减去行
    onRemove = (index)=>{
        // debugger
        let state = this.state;
        state.form.plans.splice(index,1);
        this.handleRemoveImage(state.planFileArr[index]);

        this.setState(state)
    }
render(){
 return(
 <Upload
                                                                                    {...this.uploadProps('upload',index)}
                                                                                    onRemove={this.handleRemoveImage}
                                                                                >
                                                                                    <Button>
                                                                                        <Icon type="upload" /> 请上传
                                                                                    </Button>
                                                                                </Upload>
)
}`

**Comment by mayunyi** [comment]
`asdsad`

**Comment by mayunyi** [comment]
`uploadProps=(field,index)=>{
        return {
            name: 'file',
            action: `${FILE_API}/api/user/files/`,
            headers: {
                authorization: 'authorization-text',
            },
            showUploadList:true,
            data(file) {
                return {
                    name: file.name,
                    a_file: file,
                };
            },
            beforeUpload() {
                return true;
            },
            onChange: (values) => {
                const {file, fileList: [doc = {}]} = values;
                if (file.status === 'done') {
                    const {a_file} = doc.response || {};
                    let state = this.state;
                    state.form.plans[index][`${field}_name`] = doc.name;
                    state.form.plans[index][`${field}_path`] = a_file;
                    state.planFileArr[index]=values.fileList[0];
                    this.setState(state)
                };
            },
        }
    }`

**Comment by mayunyi** [comment]
`uploadProps=(field,index)=>{`
       ` return {`
         `   name: 'file',`
       `     action: `${FILE_API}/api/user/files/`,`
       `     headers: {`
         `       authorization: 'authorization-text',`
        `    },`
        `    showUploadList:true,`
           ` data(file) {`
            `    return {`
             `       name: file.name,`
             `       a_file: file,`
           `     };`
         `   },`
       `     beforeUpload() {`
            `    return true;`
        `    },`
         `   onChange: (values) => {`
          `      const {file, fileList: [doc = {}]} = values;`
         `       if (file.status === 'done') {`
          `          const {a_file} = doc.response || {};`
          `          let state = this.state;`
          `          state.form.plans[index][`${field}_name`] = doc.name;`
          `          state.form.plans[index][`${field}_path`] = a_file;`
                   ` state.planFileArr[index]=values.fileList[0];`
                  `  this.setState(state)`
                `};`
            `},`
      `  }`
    `}`
`//删除方`
`handleRemoveImage(file){`
     
       ` console.log(file);`
  `  }`

`//删除一行表格数据附件在表格一行数据中`

`  onRemove = (index)=>{`
      
    `    let state = this.state;`
   `     state.form.plans.splice(index,1);`
     `   this.handleRemoveImage(state.planFileArr[index]);`

       ` this.setState(state)`
  `  }`

**Comment by benjycui** [comment]
`Upload[fileList]` is a controlled property.
