### ISSUE TITLE
WHY Tree 限制节点选择事件

### ISSUE THREAD

**Issue by totoSalad** [ant-design/ant-design#8070]
### What problem does this feature solve?
在我的case中，
```javascript
title = (
          <span>
            {obj.code}
            <RadioGroup defaultValue={obj.seq}
              disabled={!obj.checked}
              onChange={onRadio(key)} >
              <Radio value>连续型</Radio>
              <Radio value={false}>非连续型</Radio>
            </RadioGroup>
          </span>
        )
```
新版限制了node Select事件，写在title中的Radio check事件无法触发

### What does the proposed API look like?
取消onSelect 事件

**Comment by benjycui** [comment]
Try `<Tree selectable={false} />`

And you had better provide an online re-producible demo when open a issue

**Comment by totoSalad** [comment]
I am so sorry to find some mistakes between my issue and ur understanding. In my case, the node title includes text and two radio box.

![image](https://user-images.githubusercontent.com/8340876/32259278-5552de40-befa-11e7-9bc2-52ffd9aa4df6.png)

 When click the radio box in title, I want to trigger the radio check event , but the fact does't work as I excepted - no response! Because the above event is replaced by `onSelect`.

In early version, I can get the response of radio check event . Why it changed? I wanna it back.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by totoSalad** [comment]
here is the demo https://codepen.io/anon/pen/MOKVQL?editors=0010

**Comment by benjycui** [comment]
Minimal re-producible demo, when I click on span, it works, but when I click on radio, it doesn't:

```jsx
import { Tree, Radio } from 'antd';

ReactDOM.render((
  <div>
    <Tree>
      <Tree.TreeNode title={<span onClick={() => console.log('span')}>Hello</span>} />
      <Tree.TreeNode
        title={(
          <Radio.Group onChange={() => console.log('radio')}>
            <Radio value="1">1</Radio>
            <Radio value="2">2</Radio>
          </Radio.Group>
        )}
      />
    </Tree>
    <Radio.Group onChange={() => console.log('radio')}>
      <Radio value="1">1</Radio>
      <Radio value="2">2</Radio>
    </Radio.Group>
  </div>
), mountNode);
```

**Comment by benjycui** [comment]
It works fine in `master`, just wait for next patch version, and then you can try it, thanks.

We will publish it in weekend.

**Comment by totoSalad** [comment]
thanks quite well!

**Comment by benjycui** [comment]
Try antd@2.13.9
