### ISSUE TITLE
In the table component using the default filter, change the selected, click on the blank and click [OK] button, both can trigger the table onChange event, can not distinguish

### ISSUE THREAD

**Issue by chenpeng1102** [ant-design/ant-design#8072]
### What problem does this feature solve?
Click on the blank, may just want to revoke the filtering operation (this may be more logical), if you want to perform the filter can be provided by the [OK] button to achieve

reproduce https://ant.design/components/table-cn/#components-table-demo-head
Check a CheckBox, click on the blank will trigger the filter

### What does the proposed API look like?
1、Click on the blank does not trigger the filter, just undo the operation (do not trigger the table onChange event)
2、Or, to trigger the table's onChange event, provide an event action to distinguish whether it is triggered by [OK] or click on the blank

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/pull/8182#issuecomment-343842926
