### ISSUE TITLE
Nested child tables doesn't work correctly。

### ISSUE THREAD

**Issue by zhanbohui** [ant-design/ant-design#8073]
### Version
2.13.3

### Environment
 62.0.3202.75（正式版本） （64 位）

### Reproduction link
[https://codepen.io/zhbohui/pen/NwqNja](https://codepen.io/zhbohui/pen/NwqNja)

### Steps to reproduce
点击展开子表格

### What is expected?
只在展开的行下面展示子表格，不会将子表格的数据添加到父表格下。

### What is actually happening?
在展开的行下面展示了子表格，并且子表格的数据也会添加到父表格下。

**Comment by yesmeck** [comment]
不要用 `column[children]`, `children` 是给树形结构用的。

**Comment by namhq1989** [comment]
@yesmeck how to fix this problem? my data is the same like that, and child table data also added on parent table

<img width="153" alt="screen shot 2018-05-08 at 10 44 51 am" src="https://user-images.githubusercontent.com/1388374/39736989-fdd3658a-52ac-11e8-94bc-a422a23f08e7.png">
