### ISSUE TITLE
variables Table @table-selected-row-bg does't work

### ISSUE THREAD

**Issue by DegaoLi** [ant-design/ant-design#8074]
### Version
2.13.6

### Environment
chrome

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
seleted rows,bg color does't change

### What is expected?
row which is seleted bg color will change

### What is actually happening?
bg color does't change

**Comment by DegaoLi** [comment]
will fix next version?   what's approximate time,  ty

**Comment by afc163** [comment]
It may only be fixed in antd@3.x: https://github.com/ant-design/ant-design/pull/8075

**Comment by yesmeck** [comment]
Should be fixed in antd@3.0.0-rc.1, please help use testing it.
