### ISSUE TITLE
Dropdown组件中MenuItem比较多的时候(300左右)会卡顿

### ISSUE THREAD

**Issue by suiyi8760** [ant-design/ant-design#8076]
### Version
2.13.8

### Environment
react@15.6.2 chrome-62

### Reproduction link
[https://codepen.io/suiyi8760/pen/XzbRxw?editors=001](https://codepen.io/suiyi8760/pen/XzbRxw?editors=001)

### Steps to reproduce
在Dropdown的基础上封装了一个组件，但是渲染较多个menu.item时卡顿

### What is expected?
流畅运行(组件需求来源于旧的ng1.x项目，逻辑差不多在ng上是可以流畅运行的，是ant自带的motion的原因?)

### What is actually happening?
触发checkbox或者hover样式变更时都会触发所有Menu.item的update，卡顿比较严重

**Comment by afc163** [comment]
@benjycui 重构的 rc-menu 可以一并看看这个。

**Comment by suiyi8760** [comment]
还有一个问题，同样出现在这个demo中就是在menu组件中触发键盘输入的时候报错:Uncaught TypeError: obj.onKeyDown is not a function,亲测该问题在所有menu都会出现

**Comment by benjycui** [comment]
> Uncaught TypeError: obj.onKeyDown is not a function

这个已经修复，等 antd@3.0

**Comment by viztor** [comment]
考虑类似 infinite scroll 的解决？

**Comment by mshibl** [comment]
@benjycui antd@3.0 is a version that has not been released yet -- correct?

**Comment by yesmeck** [comment]
Track in #3789
