### ISSUE TITLE
Header messed up in table set with fixed header

### ISSUE THREAD

**Issue by hermanfenderson** [ant-design/ant-design#8078]
### Version
2.13.8

### Environment
react 15.6.2

### Reproduction link
[https://codepen.io/hermanfenderson/pen/POqVqZ?editors=0011](https://codepen.io/hermanfenderson/pen/POqVqZ?editors=0011)

### Steps to reproduce
Just run the default example... if I set scroll={{ y: .... }} headers get messed up. No more in line.

### What is expected?
Headers should be aligned with columns. That's what they  do if I exclude fixed header...

### What is actually happening?
Headers move to the centre of the column...

**Comment by hermanfenderson** [comment]
I put the two cases (not working and working) in sequence in the codepen.

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-fixed-header

Check the demo instruction.

**Comment by hermanfenderson** [comment]
Too small font in the instructions  (I am getting old) 👍

**Comment by pybuche** [comment]
Hi ! Isn't there another way than avoid precising width everywhere?

**Comment by majirosstefan** [comment]
if scroll is enabled, the purpose of table is completely broken  - it would be really nice to have not to define width on each column...

**Comment by ngocnv1712** [comment]
table fixed header when add Sider not working, please check!
