### ISSUE TITLE
`Progress` 无法设置 `className` 和 `style`

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#808]
其实我只是想隐藏 `Progress`，但现在的 API 好像做不到。

**Comment by afc163** [comment]
隐藏 progress 是什么需求。。

**Comment by benjycui** [comment]
这样。。。

![image](https://cloud.githubusercontent.com/assets/3580607/12086798/498ab010-b308-11e5-851b-a362b04efe94.png)

不常见的情况，我就先用 `null` 实现吧。。

**Comment by afc163** [comment]
Progress 要隐藏 Progress，这个需求还是不做吧。
