### ISSUE TITLE
Form表单item遍历，从中间插入item出现问题，请看下是否是bug

### ISSUE THREAD

**Issue by chenghaohao** [ant-design/ant-design#8080]
### Version
2.13.8

### Environment
chrome 版本 62.0.3202.75

### Reproduction link
[https://codepen.io/yezihaohao/pen/RjPdXB](https://codepen.io/yezihaohao/pen/RjPdXB)

### Steps to reproduce
- 点击添加按钮
- item插入成功
- 赋值有问题。应该是空值，但是把下面的item的值赋值给了新插入的item

### What is expected?
插入的item正常，未进行操作的item也正常

### What is actually happening?
赋值有问题。应该是空值，但是把下面的item的值赋值给了新插入的item

---
从中间插入有问题（splice操作），末尾插入item没问题。（代码中有个注释的push方法正常）

**Comment by afc163** [comment]
You should not use index as key, make sure your key is unique and stable.

https://reactjs.org/docs/lists-and-keys.html

**Comment by chenghaohao** [comment]
thanks ! 这么基础的问题我尽然没发现~😌😌
