### ISSUE TITLE
style order diff between dist/antd.less and babel-plugin-import

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#8081]
## version
2.13.8（not matter

## reproduce

- riddle id 70e85c6c

## what's the problem
dist/antd.less make order like

![image](https://user-images.githubusercontent.com/5318333/32259078-0f916c28-be8c-11e7-80e8-9f83f95473ab.png)

while modular less using babel-plugin-import made it like

![image](https://user-images.githubusercontent.com/5318333/32259107-345d3046-be8c-11e7-94bb-904fa4296b8f.png)

the `padding-left: 24px` not apply to the `<input />`, which make the input content overlay with the prefix icon

![image](https://user-images.githubusercontent.com/5318333/32259299-7b4f0c30-be8d-11e7-9053-c18b3d1d00c9.png)

## What is expected?

modular import perform the same as dist/antd.less

**Comment by benjycui** [comment]
When you use babel-plugin-import, the order of styles depend on your JS code.

So, what we can do is just improve the CSS selector specificity of `padding-left: 24px;`

**Comment by benjycui** [comment]
@jaredleechn just PR to master
