### ISSUE TITLE
Have affixed anchor stick when it reaches a certain point after scrolling

### ISSUE THREAD

**Issue by pruhstal** [ant-design/ant-design#8082]
### Version
2.13.8

### Environment
Chrome 61, React 16

### Reproduction link
[https://codepen.io/anon/pen/ooXrbL](https://codepen.io/anon/pen/ooXrbL)

### Steps to reproduce
Go to the codepen and scroll all the way to the bottom. The affixed anchor should never go past the footer container.

### What is expected?
The affixed anchor should stop right before the footer container.

### What is actually happening?
The affixed anchor should have an option to stop right before a target container.

<img width="1412" alt="screen shot 2017-10-31 at 11 15 40 pm" src="https://user-images.githubusercontent.com/624807/32262407-afa958ce-be91-11e7-89f7-f8184426cf04.png">

**Comment by benjycui** [comment]
The question is: how does Affix know which element is your footer and what should it do when body scroll?

You need to control it by yourself.

**Comment by pruhstal** [comment]
Well it doesn’t yet, but I won’t mind submitting a PR to allow for that functionality. 

Was thinking of doing it like so:

Attach a `ref` to the target and add that as a prop on the Affix component.

```
<Affix stickyTarget=“footer” stickyOffset={number in pixels to stop before the sticky target (optional)}>
```

Then the target is

```
<div ref=“footer”>...
```

Thoughts @benjycui?

**Comment by benjycui** [comment]
I don't agree, it will make Affix more complex than it should be.

**Comment by pruhstal** [comment]
https://www.npmjs.com/package/react-sticky is probably a better alternative for anyone looking at this.

**Comment by rphly** [comment]
Hi, revisiting this because react-sticky is no longer being maintained so there is no credible alternative if one were to use Ant Design.

**Comment by MildTomato** [comment]
I think this is a good suggestion - i have used react-sticky but it would be awesome that this is kind of functionality is considered for Antd.

Maybe a more concise request would be that it could be optional that the elements in an Affix won't scroll beyond the affix container.

Probably a good example in the Foundation implementation - https://get.foundation/sites/docs/sticky.html#basics
