### ISSUE TITLE
when table have colums which fixed: left attr ，expandedRowRender will rerender in fixed  left table

### ISSUE THREAD

**Issue by elevensky** [ant-design/ant-design#8083]
### Version
2.13.8

### Environment
Chrome 61, React 15.6.1

### Reproduction link
[https://codepen.io/elevensky/pen/pdJMOR?editors=0010](https://codepen.io/elevensky/pen/pdJMOR?editors=0010)

### Steps to reproduce
when table colums have fixed: left field，the table render fixed left will rerender expandedRowRender, but right will not.

### What is expected?
hope fixed left generate table will not rerender.

### What is actually happening?
field fixed left generate table will rerender, but right not.

**Comment by afc163** [comment]
Don't use fixed column with `expandedRowRender`, It is buggy and no perfect solution.
