### ISSUE TITLE
Custom theme failed that the project created by react-script

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#8084]
### Version
2.13.8

### Environment
MacOS 10.13.1  Chrome  61.0.3163.100 react 16.0.0 react-app-rewire-less 2.0.8 react-app-rewired 1.3.4

### Reproduction link
[https://github.com/WhatAKitty/react-script-antd-custom-issue](https://github.com/WhatAKitty/react-script-antd-custom-issue)

### Steps to reproduce
the file `config-overrides.js`s content:
```
const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config);
  config = rewireLess(config, env, {
    modifyVars: { "primary-color": "red" },
  });
  return config;
};

```

`package.json`s content:
```
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
  },
```

when I execute command `yarn start`

the style is still default.

### What is expected?
the style I customized.

### What is actually happening?
the default style

**Comment by WhatAKitty** [comment]
The PR #8085 has solved my problem. Please merge it.

**Comment by qianzhangsheng** [comment]
怎么解决的呀？
