### ISSUE TITLE
Select filterOption default function

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#8086]
### What problem does this feature solve?
writing the same function over and over

### What does the proposed API look like?
```
filterOption = (value, option) =>
    option.props.children.toString()
      .toLowerCase()
      .includes(value.toLowerCase())
```

**Comment by yesmeck** [comment]
You are free to wrap antd's select to a `<CaseInsensitiveSelect />`.

**Comment by AhmedSayed77** [comment]
I think that in most cases users want to filter options by the value they see - which is the content of the Option tag - not the value of the Option tag - which will probably be the id of the object. Of course I may be wrong, but this sounds more logical

**Comment by yesmeck** [comment]
I you just want filter the option's children, you can `optionFilterProp="children"`.

**Comment by AhmedSayed77** [comment]
It will be case sensitive. Anyway, if you see that this case is not as broad and general as I thought, it's ok. Thanks for your time
