### ISSUE TITLE
The Menu component throw error when the keyboard is pressed

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#8089]
### Version
2.13.8

### Environment
Ubuntu,chrome

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
Exchange click the Menu item,Then press the keyboard,It will throw error in the browser's console panel;

This phenomenon occurs directly in the example of the antd demo.

and the error info is :

```
Uncaught TypeError: t.onKeyDown is not a function
```

### What is expected?
Do not throw error.

### What is actually happening?
It throw error.

---
To reproduce just by @ [menu](https://ant.design/components/menu-cn/)

**Comment by yesmeck** [comment]
Landed in antd@3.0.0-rc.1, please help use testing it.

**Comment by PWDream** [comment]
@buxuku How do you solve it?

**Comment by buxuku** [comment]
@PWDream use antd v3
