### ISSUE TITLE
使用Form.ValueMixin对象时，数据对象的变量名如果不是formData就不能正常工作。

### ISSUE THREAD

**Issue by lijunzhou** [ant-design/ant-design#809]
**问题描述**

  使用Form.ValueMixin对象设置数据对象值的时候，如果数据的对象不是state.formData,比如是state.data,将抛出异常
 

**发生环境**

- antd 版本：0.11.1
- 操作系统及版本：window 7
- 浏览器及版本：版本 36.0.1941.0
- 在线演示地址：无

在ValueMixin.js 第31行直接使用的this.state.formData。

**Comment by benjycui** [comment]
代码写死的：https://github.com/ant-design/ant-design/blob/master/components/form/ValueMixin.jsx#L27

也就个名字，不需要允许自定义吧，就当是个约定。

**Comment by lijunzhou** [comment]
文档里没有写明，很容易踩到坑。

**Comment by benjycui** [comment]
http://ant.design/components/form/

![image](https://cloud.githubusercontent.com/assets/3580607/12106579/f4301ac6-b39b-11e5-8b79-aa310dd11421.png)

**Comment by diaoaa** [comment]
写死好不灵活啊，我一个表单有多个数据对象（每个数据对象有多个属性字段），如何将输入框绑定到这些属性字段上呢？ @benjycui

**Comment by mongris** [comment]
如果用redux的话，使用redux from吧。
我使用redux form来管理fields，validations，而用antd From管理布局。

**Comment by benjycui** [comment]
@diaoaa Try 0.12.0-beta，下周会发布正式版

@mongris 0.12.0 也会对 Redux 进行适配，see: https://github.com/react-component/form
