### ISSUE TITLE
Tree how to loadData using redux and ajax call for data

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#8095]
### What problem does this feature solve?
on https://ant.design/components/tree/#components-tree-demo-dynamic sample, it shows a setTimeout function, that update the local state of the component.

### What does the proposed API look like?
How would you use loadData if you use Redux, and want to keep the treeData on the redux store and not on the component State?
Basically what i'm missing is how you dispatch an action and complete the loadData promise when the async results come back.

**Comment by yesmeck** [comment]
It depends on how do you handle async call in redux, you pass to resolve as callback to your async call library.

```javascript
loadData() {
  return new Promise(resolve => {
    dispatch({
      ...Data,
      callback: resolve,
    })
  })
}
```
