### ISSUE TITLE
antd create-react-app  Customize Theme config rewireLess syntax error

### ISSUE THREAD

**Issue by flasco** [ant-design/ant-design#8096]
### Version
2.13.8

### Environment
mac os 10.12.3  chorme 62 react.js 16.0.0

### Reproduction link
[https://github.com/ant-design/create-react-app-antd/blob/master/config-overrides.js](https://github.com/ant-design/create-react-app-antd/blob/master/config-overrides.js)

### Steps to reproduce
https://ant.design/docs/react/use-with-create-react-app  
-----
the antd Official website doc write : 
   config = rewireLess(config, env, {
      modifyVars: { "@primary-color": "#1DA57A" },
    });

but it's Invalid .  in fact, config should be like this:

config = rewireLess.withLoaderOptions({
    modifyVars: { "@primary-color": "#1DA57A" },
  })(config, env);

Hope the Official website doc can use the current code  :) 

### What is expected?
theme change

### What is actually happening?
if use doc code ,it's Invalid. color never change.

---
use  package:
    "babel-plugin-import": "^1.6.2",
    "react-app-rewire-less": "^2.0.8",
    "react-app-rewired": "^1.3.4"

**Comment by HelloQingGuo** [comment]
I just wanted to create a new issue about the failure of theme customization when using create-react-app based on the [documentation at "antd" website](https://ant.design/docs/react/use-with-create-react-app).  Thanks for pointing it out !!!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/8085

**Comment by josephmax** [comment]
this is not fixed in [Chinese version documentation](https://ant.design/docs/react/use-with-create-react-app-cn).

**Comment by afc163** [comment]
It is fixed now.
