### ISSUE TITLE
Table的columns的render属性必须返回react组件，返回string不能正常工作

### ISSUE THREAD

**Issue by lijunzhou** [ant-design/ant-design#810]
**问题描述**

Table的columns的render属性必须返回react组件，返回string不能正常工作。主要是没有任何异常抛出，只是没有任何反应了。如果table用了loading，则会一直处于loading状态。

**发生环境**

- antd 版本：0.11.1
- 操作系统及版本：win7
- 浏览器及版本：版本 36.0.1941.0
- 在线演示地址：无

**Comment by afc163** [comment]
rc-table@3.6.2 已修复，重新安装 antd 即可。

**Comment by afc163** [comment]
如果table用了loading，则会一直处于loading状态。

> 这是一定的，组件不知道何时该取消 loading，你需要告知它。

另外建议一个问题开一个 issue 。
