### ISSUE TITLE
TreeSelect still fills parent when setting showCheckedStrategy SHOW_CHILD

### ISSUE THREAD

**Issue by leadream** [ant-design/ant-design#8103]
### Version
undefined

### Environment
macOS 10.12.6 Chrome 62.0.3202.75

### Reproduction link
[https://codepen.io/leadream/pen/Bmjrdw](https://codepen.io/leadream/pen/Bmjrdw)

### Steps to reproduce
1. click input field
2. input `1`
3. click parent node `Node2` to select
4. just parent is filled, no children

### What is expected?
fill input field with children, not parent node

### What is actually happening?
just parent is filled, no children

**Comment by zombieJ** [comment]
Close since OOD after refactor

**Comment by Terry-cjgu** [comment]
估计解决你这个问题，导致现在设置 SHOW_All，父节点信息都不显示了，my god
