### ISSUE TITLE
On iOS Safari,  DatePicker panel disappears after tapping on a month in a second level panel / 苹果手机浏览器，日期选择框二级面板点选月份，面板消失

### ISSUE THREAD

**Issue by rockallite** [ant-design/ant-design#8106]
### Version
2.13.8

### Environment
iOS 10.3.3, Safari, React 15.6.1

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
* Open the DatePicker demo page in iOS Safari.
* Tap on the DatePicker component.
* When the date selection panel pops up, tap on the month in the title (e.g. `Nov`).
* When the second level panel appears with month list, tap on any month (e.g. `Dec`).

### What is expected?
The panel remains and goes back to the first level.

### What is actually happening?
The panel disappears, and no date is selected.

---
* This only happens on iOS Safari, not on desktop version of Safari or Chrome.

**Comment by afc163** [comment]
antd is not well optimized for mobile browser, we will stick to desktop browsers fow now.

**Comment by afc163** [comment]
BTW, any Pull Requests to improve mobile functions will be welcome~
