### ISSUE TITLE
Grid  demo is can't run 

### ISSUE THREAD

**Issue by zxhycxq** [ant-design/ant-design#8109]
### Version
2.13.8

### Environment
win 10, chrom 55

### Reproduction link
[https://codepen.io/xwll/pen/vWGxKJ](https://codepen.io/xwll/pen/vWGxKJ)

### Steps to reproduce
I  **copy** the code from [grid-cn](https://ant.design/components/grid-cn/)     (the first demo ) on the codepen.io  ,however,it can't run ,but by   ** 在 CodePen 中打开** ,it can run well. may be the code example on the website is not the latest。

### What is expected?
run as example

### What is actually happening?
nothing 

---
"import { Row, Col } from 'antd';" should be "const { Row, Col } = antd;"

**Comment by afc163** [comment]
codepen usage is just different from normal usage.
