### ISSUE TITLE
建议增加 Popconfirm 和 Tooltip 组件在同一元素上使用时的兼容性

### ISSUE THREAD

**Issue by Carrotzpc** [ant-design/ant-design#811]
使用时发现在Popconfirm 组件内使用 Tooltip 组件时，Tooltip 组件未生效，建议鼠标 hover 时出现 Tooltip ，点击时Tooltip 隐藏、Popconfirm 出现

**Comment by afc163** [comment]
确实有问题：http://jsfiddle.net/6q0qwoyh/

**Comment by afc163** [comment]
暂时可以先包一层 span 来解决：http://jsfiddle.net/cLveue7q/

**Comment by Carrotzpc** [comment]
嗯嗯，谢谢

**Comment by Han001** [comment]
it is the first time for me to use github.I don't know where to ake a suggestion.

http://09x.ant.design/spec/easing--The current page cannot be jump to another version
https://github.com/alipay/x/issues --- 404

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md

**Comment by afc163** [comment]
Fixed in `develop-0.12.0`
