### ISSUE TITLE
Mouse middle button to close tabs

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#8113]
### What problem does this feature solve?
Chrome browser supports closing a tab by click mouse middle button (the wheel).
I want the same feature for ant design tabs. So user doesn't need to locate the tiny 'x' icon in order to close a tab.

### What does the proposed API look like?
```
<Tabs type='editable-card' middleButtonToClose>
....
</Tabs>
```

So when user middle clicked on a tab, it should have same effect as user clicked the tiny 'x' icon.

**Comment by afc163** [comment]
A trick workaround: https://codepen.io/anon/pen/BmLKre?editors=0110

ref #8117

**Comment by tylerlong** [comment]
The demo code doesn't work.

I middle clicked the tabs and nothing was printed in the console.

`onClick` won't be triggered by middle click at all.

Could you please reopen the issue?

**Comment by afc163** [comment]
https://stackoverflow.com/a/1795787/3040605

**Comment by tylerlong** [comment]
@afc163 I guess the link you sent works for jQuery but not for ant design.

For some reason, ant design's `onClick` event only listens for left button click. It doesn't even work for right button, let alone middle button.

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

**Comment by tylerlong** [comment]
Are your sure that the ant design onClick event works the same way as primitive mouse event as documented in the Mozilla documentation?

How do you explain that the demo code you posted doesn't work with middle button? Could you please have a try?

**Comment by afc163** [comment]
I don't have a mouse...

**Comment by afc163** [comment]
It is just javascript and react, you can bind any events you want to div.

```
<div onXxx={this.onXxx} />
```

**Comment by tylerlong** [comment]
I created a new issue here: https://github.com/ant-design/ant-design/issues/8176
