### ISSUE TITLE
Notification is broken on React 16.0.0

### ISSUE THREAD

**Issue by farskid** [ant-design/ant-design#8115]
### Version
2.13.8

### Environment
Mac os, Chrome 62, React 16, antd 2.13.8

### Reproduction link
[https://codepen.io/farskid/pen/xPObwG?editors=001](https://codepen.io/farskid/pen/xPObwG?editors=001)

### Steps to reproduce
Just use React and React dom of version 16.0.0 and use notification of antd 2.13.8.
It will create an error that it can not add on null.

### What is expected?
Expected to work like before and show a notification on top right of window.

### What is actually happening?
var notification = ReactDOM.render(React.createElement(Notification, props), div);
On the line above in Notification.js on line 135, the notification variable is being null.

**Comment by kitoss12** [comment]
I'm having the same issue on message component

**Comment by benjycui** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/7844

**Comment by afc163** [comment]
trace #5377 and #7844
