### ISSUE TITLE
Upload上传excel文件出错

### ISSUE THREAD

**Issue by sunhoudong** [ant-design/ant-design#8116]
### Version
2.11.1

### Environment
ant 2.11.1，谷歌浏览器

### Reproduction link
[https://codepen.io/sunhoudong/pen/wPWoVM](https://codepen.io/sunhoudong/pen/wPWoVM)

### Steps to reproduce
无

### What is expected?
可以正常上传

### What is actually happening?
监听上传的status,前两次都是uploading，第三次是error

**Comment by yesmeck** [comment]
Your link is not working.

**Comment by sunhoudong** [comment]
@yesmeck 这里面，uploadParams因为是临时的，所以我不好贴出来，主要问题出在onChange方法里面，我按照官网的例子，加了进去，第一次上传，一直是uploading,uploading,error,第二次就可以成功了

**Comment by yesmeck** [comment]
那最起码你要提供具体的错误信息。

**Comment by sunhoudong** [comment]
status拿到的就是error，他POST到我当前页面里面了，然后就是request.js:96 POST http://localhost:8099/addInsurance 500 ()，报500错误

**Comment by yesmeck** [comment]
那是你服务端的错误，检查下请求和服务端的日志吧。

**Comment by sunhoudong** [comment]
@yesmeck 我是上传到阿里云oss，如果是你说的那样，第二次也不会成功

**Comment by yesmeck** [comment]
oss 出错会返回错误信息的，自己查下吧。

**Comment by sunhoudong** [comment]
这个确实是使用Upload的时候才出现的，我上传图片都没问题

**Comment by yesmeck** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)). We will reopen it if you can provide enough information.

**Comment by sunhoudong** [comment]
自己的控件的问题不去找，亦或是官网提供的api说的不明白，这些不去处理，为啥我换了方案，直接用input type=file上传就没问题，在这里纠结这个，有意思吗？我已经按照那个fileList受控方案去做了，上传不了，你们倒是推到oss人家头上，厉害，佩服！

**Comment by yesmeck** [comment]
你要提供有用的信息我才能帮你。

**Comment by sunhoudong** [comment]
onChange方法里面，监听状态，先是uploading,最后面变成error，搞不明白的就是为啥会跑到我当前页面去post，结果就是500了，这时候还没有进行任何后台相关的操作，只是上传，最后获取地址而已，我看了一下，问题就在onChange方法里面，但是不知道是什么问题

**Comment by afc163** [comment]
建议有空阅读下 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。抱怨和发泄情绪并不能帮助到彼此，这也是 http://new-issue.ant.design/ 存在的意义。

**Comment by sunhoudong** [comment]
@afc163 我是按照你给别人回到的#2423，这个上面来处理的，在onChange方法里面一直都是setState，fileList的，action和data里面，我取的是和图片上传一样的uploadParams，这个是拿的oss的上传签名和接口相关的，图片是可以上传的，证明这边是没问题的，就是不知道excel上传，我打的日志，第一次上传，status是uploading，uploading,error，而后我再点击一次，就是成功的，并且可以传到oss上了，就是不知道为啥第一次不能成功

**Comment by afc163** [comment]
去这里 http://new-issue.ant.design/ 建个新的 issue 吧，最好给出可重现的 codepen 或者 GitHub repo，方便重现、确认问题和调试。
