### ISSUE TITLE
tabs组件能不能提供右击属性

### ISSUE THREAD

**Issue by LDD123** [ant-design/ant-design#8117]
### What problem does this feature solve?
当tab页面多了之后，想通过这个属性来关闭全部或者是关闭其他tab页这样的功能，一个一个关闭这样太繁琐了

### What does the proposed API look like?
提供一个右击事件的 属性就行了

**Comment by afc163** [comment]
A trick workaround: https://codepen.io/anon/pen/BmLKre?editors=0110
