### ISSUE TITLE
message component is not showing at first call

### ISSUE THREAD

**Issue by nighttiger1990** [ant-design/ant-design#8119]
### Version
2.13.8

### Environment
WINDOWS 10 Pro Version 1703 OS BUILD 15063.674.

### Reproduction link
[https://github.com/nighttiger1990/ddsystem](https://github.com/nighttiger1990/ddsystem)

### Steps to reproduce
message.info('something') at first call is not showing popup

### What is expected?
message.info('something') at first call showing popup

### What is actually happening?
it's strange and i dont know what happening

---
I got bug in my project, i dont know this is bug of antd or not, because it's strange.
My project: https://github.com/nighttiger1990/ddsystem

At http://localhost:3000/Unknowsite
message.info('congrats! message is showing with one call') is working perfect
At http://localhost:3000/Home/Order/OrderItem
message.info('Oops! This message need atleast 2 call to show; (first and after last popup gone in a time (i think duration props))')
When i click Back button to test show message. its need 2 call to show at first or after last popup gone in a time (i think duration props)
I don't know this is bug in message antd or my project.
Anyone help me?
My npm dependencies:

"dependencies": {
    "antd": "^2.13.8",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.15"
  },
Im using WINDOWS 10 Pro Version 1703 OS BUILD 15063.674

**Comment by afc163** [comment]
see #5377 and #7844
