### ISSUE TITLE
Table组件分页问题

### ISSUE THREAD

**Issue by dqaria** [ant-design/ant-design#812]
分页组件传入正确字段分页显示正常，再传入空对象分页未改变，仍保留上一次的items值。
如传入{current: 1, total: 0, pageSize: 20}正常。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/master/components/table/index.jsx#L79

传入空对象是出于什么动机？

**Comment by dqaria** [comment]
返回数据为空时，传入空对象我理解的是清空分页信息。

**Comment by benjycui** [comment]
就是应对这种情况是吧？

![image](https://cloud.githubusercontent.com/assets/3580607/12187855/8afca9ba-b5ea-11e5-80eb-f6131acee510.png)

这样把 `pagination` 设为 `false` 直接隐藏 `Pagination` 可好？

另外，当 `dataSource.length === 0` 时，`Table` 是会自动隐藏 `Pagination` 的。。

**Comment by bang88** [comment]
`dataSource` 貌似是一个对象。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/12188295/d5360ea0-b5ee-11e5-9407-61dac2b5339e.png)

**Comment by bang88** [comment]
:+1:  ...

**Comment by afc163** [comment]
不要传空对象。
