### ISSUE TITLE
自定义校验失效

### ISSUE THREAD

**Issue by FounderIsShadowWalker** [ant-design/ant-design#8123]
给textArea 绑定自定义校验规则，
同时绑定了 mapPropsToFields， onFieldsChange后，自定义校验的callback 不被调用。

import React from 'react';
import { connect } from 'dva';
import { Form, Input, Tooltip, Icon, Cascader, Select, Row, Col, Checkbox, Button, AutoComplete } from 'antd';
import './IndexPage.scss';

const { TextArea } = Input;

const FormItem = Form.Item;

class IndexPage extends React.Component {

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        console.log('Received values of form: ', values);
      }
    });
  }

  customCheck = (rule, value, callback, source, options) => {
    callback(`${value.length}`);        //onChange  不会出现非法信息
  }

  render() {
    const { getFieldDecorator } = this.props.form;
    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 6 },
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 14 },
      },
    };

    return (
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label="评语"
          hasFeedback
        >
          {getFieldDecorator('remark', {
            validateTrigger: ['onChange', 'onBlur'],
            rules: [
              {
                validator: this.customCheck,
              }],
            initialValue: ''
          })(
            <TextArea placeholder="Autosize height with minimum and maximum number of lines"
              rows={4}
              style={{ resize: 'none' }} />
            )}
        </FormItem>
      </Form>
    );
  }
}

IndexPage.propTypes = {
};

function mapStateToProps(state) {
  const { text } = state.textArea;
  return {
    text
  };
}

export default connect(mapStateToProps)(Form.create(
  {
    mapPropsToFields(props) {
      return {
        remark: {
          value: props.text
        }
      };
    },

    onFieldsChange(props, fields) {
      console.log('onFieldsChange', fields);

      props.dispatch({
        type: 'textArea/saveText',
        payload: {
          fields
        }
      })
    },
  }
)(IndexPage));

**Comment by captainblue2013** [comment]
干！中国人的东西还要求英文写，不合格式就关，问题解决了吗

**Comment by yoyo837** [comment]
你叫Windows别提供中文包呗。要国际化需要使用国际语言，不然你也去殖民他们几百年，让世界都使用中文。
