### ISSUE TITLE
antd 自定义校验失效

### ISSUE THREAD

**Issue by FounderIsShadowWalker** [ant-design/ant-design#8124]
### Version
2.6.4

### Environment
chrome 61.0.3163.100

### Reproduction link
[https://codepen.io/write/antd-validate-error](https://codepen.io/write/antd-validate-error)

### Steps to reproduce
none

### What is expected?
each textarea onchange event call validate‘s callback

### What is actually happening?
textarea onchange event actually was triggered，but validator‘s callback appearance is not showing。

---
在接入onFieldsChange前，自定义的校验方法里的callback 每次都会执行，看了console 确实执行了，但是没有表现在页面上。

**Comment by LDD123** [comment]
页面挂了

**Comment by afc163** [comment]
Please provide a valid reproduce demo.

**Comment by FounderIsShadowWalker** [comment]
很抱歉，这里补上正确的链接
https://codepen.io/shadowwalkerzero/post/async-validate-error

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
@FounderIsShadowWalker
