### ISSUE TITLE
 「对比」和「足不出户」这两个地方是不是冲突了

### ISSUE THREAD

**Issue by dongm2ez** [ant-design/ant-design#8127]
### Version
2.13.9

### Environment
文档

### Reproduction link
[https://ant.design/docs/spec/stay-cn](https://ant.design/docs/spec/stay-cn)

### Steps to reproduce
在对比中有这样一句话系统应该保持中立，不能替用户或者诱导用户做出判断。
而在足不出户的确认删除那里给的示例图却确认删除和取消使用不同的颜色，诱导了用户做出判断

### What is expected?
统一

### What is actually happening?
差异，前后矛盾

**Comment by Lyndon001** [comment]
> 在对比中有这样一句话系统应该保持中立，不能替用户或者诱导用户做出判断。
保持中立是有一定前提的，比如一个审批单中『同意』和『驳回』，我们希望『设计者』需要保持中立，让用户自行决策。


> 而在足不出户的确认删除那里给的示例图却确认删除和取消使用不同的颜色，诱导了用户做出判断
对于一些常见的问题（例如二次确认），区分主次帮助用户快速做出决策，做出显而易见的决策。
