### ISSUE TITLE
In guideline there is a problem for Select component when using ts

### ISSUE THREAD

**Issue by kungcn** [ant-design/ant-design#8128]
### Version
2.13.9

### Environment
OS X, Chrome  61.0.3163.100

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
1. using ts in IDE like VSCode
2. copy the example code in your project

### What is expected?
can run correctly and show like that in guideline

### What is actually happening?
ts error: 'props' is not exist in the 'Object'
Maybe it is not totally correct for I forget it, but it will show error in both VSCode and Chrome page.

---
Finally I gave up "this.props.children" but used "this['props'].children". Fortunately it works. I think it maybe some problems for 'this.props'. I tried to console 'this' and it does have 'props'... Maybe props doesn't exist when rendering ?
This sentence shows in attribute 'filterOption'. So I think it will be better if the guidelines can take some tips.

**Comment by yesmeck** [comment]
PRs are always welcome if you found any type definition issue.
