### ISSUE TITLE
QueueAnim组件在安卓设备上非常卡，请教一下如何优化？

### ISSUE THREAD

**Issue by Tinker404** [ant-design/ant-design#813]
对性能优化这些没什么概念，求指点一下。

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/709

**Comment by benjycui** [comment]
提问前可以查下相关 issue，另外建议以后在任何开源项目开 issue 前，都看下对应项目的 [CONTRIBUTING](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)

**Comment by l19861225q** [comment]
消除 transition 闪屏

```
.css {
    /*设置内嵌的元素在 3D 空间如何呈现：保留 3D*/
    -webkit-transform-style: preserve-3d;
    /*（设置进行转换的元素的背面在面对用户时是否可见：隐藏）*/
    -webkit-backface-visibility: hidden;
}
```

开启硬件加速

```
.css {
    -webkit-transform: translate3d(0, 0, 0);
    -moz-transform: translate3d(0, 0, 0);
    -ms-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}
```

#### 注意
只对我们需要实现动画效果的元素应用以上方法，如果仅仅为了开启硬件加速而随便乱用，那是不明智的。

小心使用这些方法，如果通过你的测试，结果确是提高了性能，你才可以使用这些方法。使用GPU可能会导致严重的性能问题，因为它增加了内存的使用，而且它会减少移动端设备的电池寿命
