### ISSUE TITLE
Cascader的options有空的children导致showSearch工作不正常

### ISSUE THREAD

**Issue by jdz321** [ant-design/ant-design#8130]
### Version
2.13.9

### Environment
mac os / chrome

### Reproduction link
[https://codepen.io/jdz321/pen/vWXRyM](https://codepen.io/jdz321/pen/vWXRyM)

### Steps to reproduce
输入关键词搜索

### What is expected?
得到正常提示选项

### What is actually happening?
显示 `not found`

**Comment by jdz321** [comment]
https://github.com/ant-design/ant-design/issues/7885

**Comment by jdz321** [comment]
https://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L226

此处 `children.lenth` 为0时，flattenTree结果不正确，建议增加children非空判断

```js
      if (changeOnSelect || !option.children || !option.children.length) {
        flattenOptions.push(path);
      }
```

**Comment by afc163** [comment]
来个 PR~
