### ISSUE TITLE
Fixed width on class "ant-input-number"

### ISSUE THREAD

**Issue by ColinVDH** [ant-design/ant-design#8131]
### Version
2.13.9

### Environment
Any

### Reproduction link
[https://codepen.io/anon/pen/xPEerv?editors=0010](https://codepen.io/anon/pen/xPEerv?editors=0010)

### Steps to reproduce
See code

### What is expected?
width is set at 100%

### What is actually happening?
width is fixed at 80px

**Comment by afc163** [comment]
It is by designed, try `<InputNumber style={{ width: '100%' }} />`.

**Comment by clleker** [comment]
<Form  form={itemForm} id={"itemForm"} >
Define id to form
#itemForm  .ant-input-number{ width: 100% }   css
