### ISSUE TITLE
modal的width属性填写字符串无效？

### ISSUE THREAD

**Issue by mrzhao1129** [ant-design/ant-design#8134]
### Version
2.13.8

### Environment
win7、chrome60、react16.0.0、antd2.13.8

### Reproduction link
[https://codepen.io/mrzhao1129/pen/zPoGgz?editors=0010](https://codepen.io/mrzhao1129/pen/zPoGgz?editors=0010)

### Steps to reproduce
在react16.0.0环境下，使用Modal并填写width=”800“属性。

### What is expected?
Modal会变成width 800px状态。

### What is actually happening?
Modal会变成width 100%状态。

---
width=”800px“好使；在react15下没这个问题。

**Comment by afc163** [comment]
`width={800}` or `width="800px"`

React will not add `px` to string-type style.width after 16.0.0.

**Comment by tsheng** [comment]
For my understanding, we should use it as width={800} or width="800px", just give a try. 
Good luck.
