### ISSUE TITLE
Autocomplete [object Object]

### ISSUE THREAD

**Issue by NugzarGaguliya** [ant-design/ant-design#8141]
### Version
2.12.2

### Environment
Windows 10, Chrome 62.0.3202.89

### Reproduction link
[https://codepen.io/NookieGrey/pen/KyNgmo](https://codepen.io/NookieGrey/pen/KyNgmo)

### Steps to reproduce
on init

### What is expected?
component must get value from object and set label as visible text

### What is actually happening?
visible text is [object Object]

---
How I can send to Autocomplete component object with value and text, so value will be value of component, and text will be visible text?
If i send value as value, visible text becomes value, not text in dataSource object.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/zPoomo?editors=0010
