### ISSUE TITLE
Select 组件功能与描述不服

### ISSUE THREAD

**Issue by zhang-ning** [ant-design/ant-design#8145]
### Version
最新版

### Environment
mac

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
无

### What is expected?
labelInValue | 是否把每个选项的 label 包装到 value 中，会把 Select 的 value 类型从 string 变为 {key: string, label: ReactNode} 的格式

### What is actually happening?
实际 label 并不支持 ReactNode，
请在官网给出，支持的例子, 尤其是 “multiple” 模式

**Comment by yesmeck** [comment]
https://codepen.io/yesmeck/pen/JOEjYr?editors=0010

**Comment by afc163** [comment]
@yesmeck `labelInValue`

**Comment by yesmeck** [comment]
Updated.

**Comment by zhang-ning** [comment]
是不是没看懂我写的中文？
 
defaultValue={[{key:1,label:<span><Avatar src="http://taobao.com"/>22</span>}]}

**Comment by yesmeck** [comment]
Updated.

**Comment by zhang-ning** [comment]
两个就不行了


defaultValue={[{key:1,label: <span style={{ color: 'green' }}>22</span>},{key:1,label: <span style={{ color: 'green' }}>3344</span>}]}

**Comment by zhang-ning** [comment]
另外请把 Avatar 加上，看看效果，在 git 评论里贴进来被屏蔽了

**Comment by yesmeck** [comment]
key 不能一样。

**Comment by yesmeck** [comment]
如果你觉得有问题，直接提供一个重现就可以了。

**Comment by zhang-ning** [comment]
defaultValue={[{key:1,label: <span style={{ color: 'green' }}>22</span>}，{key:23333,label: <span style={{ color: 'green' }}>33</span>}]}

**Comment by yesmeck** [comment]
像我贴的那样的在 CodePen 上的重现，谢谢。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by zhang-ning** [comment]
Thanks Guys! https://codepen.io/zhang-ning/pen/gXgbpp?editors=0010 
it's fixed up.  It's my mistake which should not wrap <Option> tag in label property
