### ISSUE TITLE
TextArea添加计数功能

### ISSUE THREAD

**Issue by shenck215** [ant-design/ant-design#8148]
### What problem does this feature solve?
用户在输入字时可以看到自己输入的字数，与表单验证很好的配合。

### What does the proposed API look like?
```js
<Input.TextArea counter={true} />
```

![image](https://user-images.githubusercontent.com/20554664/32593192-ea3413a4-c561-11e7-8cdf-b21627e75de9.png)

**Comment by chenshuai2144** [comment]
这个应该自己写吧   毕竟样式不是很好控制,放在里面还是外面

**Comment by benjycui** [comment]
See: https://ant.design/docs/pattern/form#Character-counting-box

这个依赖于富文本，现在做不了。

**Comment by yesmeck** [comment]
暂时不会做。

**Comment by dw92910** [comment]
https://codesandbox.io/embed/affectionate-hellman-0ivwy
我基于antd自己实现了一个，大家可以参考一下

**Comment by munroe7** [comment]
Is there any plan to implement this? It's a great visual for the user.

**Comment by firedemo1** [comment]
> a
Hi，I completed a component demo，just FYI
[https://codesandbox.io/s/textaraeplus-o1qwu](url)

**Comment by komagic** [comment]
react蛮简单，代码给你们几爷子,style 你们自己调整下:

 <div style={{ position: 'relative' }}>
                <TextArea
                  placeholder="请输入"
                  maxLength={textAreaTotal}
                  rows={4}
                  onChange={this.textAreaOnChange}
                ></TextArea>
                <span className={style.count}>{this.state.textCount}/{this.props.textAreaTotal}</span>
  </div>

// style.css
.count {
  bottom: -7px;
  color: #ADADAD;
  font-size: 6px;
  position: absolute;
  right: 10px;
  user-select: none;
  z-index: 2;
}

**Comment by ctq123** [comment]
https://github.com/ctq123/antd-input 已解决
