### ISSUE TITLE
Tab 组件 defaultActiveKey 如果设置成右侧更多的标签，初始的时候不能显示

### ISSUE THREAD

**Issue by l19861225q** [ant-design/ant-design#815]
如题，如果默认选中的 key 为右侧更多的标签中的某个，初始的时候看不到默认激活的标签，还需要点击右侧的箭头才能看到，希望可以添加多余的参数可以配置 X 轴初始值或者其他的解决办法

**Comment by afc163** [comment]
https://github.com/react-component/tabs/issues/13

**Comment by l19861225q** [comment]
@afc163 么么

**Comment by afc163** [comment]
Fixed in branch `develop-0.12.0`.
