### ISSUE TITLE
How to add multiple forms on same component ?

### ISSUE THREAD

**Issue by jshupptechnologies** [ant-design/ant-design#8151]
### What problem does this feature solve?
We can add multiple form on same component.
I have tried by adding 2 form but action triggered for both form if i submit any one of the form.

### What does the proposed API look like?

`<Form onSubmit={this.handleSubmit} className="login-form">..form controls here</Form>`

`<Form onSubmit={this.handleSubmit1} className="register-form">..form controls here</Form>`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2294#issuecomment-232370445

**Comment by jshupptechnologies** [comment]
@afc163  Thank you so much!, I am unable to read chinese so couldn't find that.

**Comment by nguyenhuutinh** [comment]
You can manage multiple forms through specifying fields in validateFields/validateFieldsAndScroll like

this.props.form.validateFields(['email', 'firstName', 'lastName'], (err, values) => {
    if (!err) {

    }
})
https://ant.design/components/form/#validateFields/validateFieldsAndScroll

**Comment by Salablefuzzball** [comment]
> 1. You can manage multiple forms through specifying fields in validateFields/validateFieldsAndScroll like
> 
> ```
> this.props.form.validateFields(['email', 'firstName', 'lastName'], (err, values) => {
>     if (!err) {
>     }
> })
> ```
> 
> https://ant.design/components/form/#validateFields/validateFieldsAndScroll
> 
> 1. if the items of each form is different you could check the err to find which item of form is invalid
>    ` this.props.form.validateFields((err, values))`

But this does not validate multiple forms. This only validates the form that this.props.form references to and the fields: email firstName and lastName that are in the form. This does not solve the issue with splitting form and then validating them
