### ISSUE TITLE
How to manage the multiple model and multiple form validation ? ant design

### ISSUE THREAD

**Issue by Sathiyamm** [ant-design/ant-design#8153]
How to manage the multiple model and multiple form validation ?

`
loginSubmit= (e) => {
        e.preventDefault();
        debugger;
        this.props.form.validateFieldsAndScroll((err, values) => {
            if (!err) {
}
})
}
registerSubmit = (e) => {
        e.preventDefault();
        debugger;
        this.props.form.validateFieldsAndScroll((err, values) => {
            if (!err) {
}
})
}
render() { 
const { getFieldDecorator } = this.props.form;
return (
<div>
<Model>
<Form>
<Form onSubmit={this.loginSubmit}>
                            <div className='logo-image text-center'>
                                <img alt="KrossDelivery Logo" src={require('../../../assets/images/logo.png')}></img>
                            </div>
                            <FormItem hasFeedback label="Email">
                                {getFieldDecorator('email', {
                                    rules: [{
                                        type: 'email', message: 'The enter is not valid E-mail!'
                                    }, {
                                        required: true, message: 'Please enter your E-mail!'
                                    }]
                                })(
                                    <Input prefix={<Icon type="user" style={{ fontSize: 13 }} />} placeholder="Email" maxLength="35" />
                                    )}
                            </FormItem>
                            <FormItem hasFeedback label="Password">
                                {getFieldDecorator('password', {
                                    rules: [{ required: true, message: 'Please enter your Password!' }]
                                })(
                                    <Input prefix={<Icon type="lock" style={{ fontSize: 13 }} maxLength='2' />} type="password" placeholder="Password" maxLength="20" />
                                    )}
                            </FormItem>
                            <FormItem className="text-center">
                                <Button htmlType="submit">Login</Button>
                            </FormItem>
</Form>
</Model>
<Model>

<FormItem
                                        label="FirstName"
                                        hasFeedback
                                    >
                                        {getFieldDecorator('FirstName', {
                                            rules: [{
                                                message: 'Please enter your FirstName!'
                                            }, {
                                                required: true
                                            }]
                                        })(
                                            <Input maxLength="30" />
                                            )}
                                    </FormItem>
<FormItem
                                        label="E-mail"
                                        hasFeedback
                                    >
                                        {getFieldDecorator('email', {
                                            rules: [{
                                                type: 'email', message: 'The enter is not valid E-mail!'
                                            }, {
                                                required: true, message: 'Please enter your E-mail!'
                                            }]
                                        })(
                                            <Input maxLength="35" />
                                            )}
                                    </FormItem>
 <FormItem>
                                        <Button className="signUpButton" htmlType="submit">Register</Button>
                                    </FormItem>
</Model>
</div>
  );
    }
}
`
[validation.txt](https://github.com/ant-design/ant-design/files/1458043/validation.txt)

**Comment by mianusmankhalid** [comment]
You can manage multiple forms through specifying fields in validateFieldsAndScroll like

this.props.form.validateFieldsAndScroll(['email', 'firstName', 'lastName'], (err, values) => {
if (!err) {
}
})
}

https://ant.design/components/form/#validateFields/validateFieldsAndScroll
