### ISSUE TITLE
Table 的 expandedRowRender 是否支持部分行可以展开，而部分行不展开（不展示icon）？

### ISSUE THREAD

**Issue by BlackGanglion** [ant-design/ant-design#8157]
### What problem does this feature solve?
树形数据结构，子节点不能再向下展开

### What does the proposed API look like?
仅询问是否支持

**Comment by yesmeck** [comment]
@afc163 感觉这个行为可以调整下，expandedRowRender 返回  `false` 的时候不展示 icon？

**Comment by afc163** [comment]
那就会渲染时全部执行一遍了。之前为了解决性能问题，只有展开的时候会执行那一行的 expandedRowRender 。

**Comment by yesmeck** [comment]
之前的逻辑也是渲染的时候全执行一遍的 https://github.com/react-component/table/blob/20a83c6af6d5ead8ae6501d033089f626d7f875b/src/Table.jsx#L331

**Comment by afc163** [comment]
执行前有个判断：

https://github.com/react-component/table/blob/20a83c6af6d5ead8ae6501d033089f626d7f875b/src/Table.jsx#L330

**Comment by BlackGanglion** [comment]
我的场景是这样的，我预先已经知道哪些行展开有数据，哪些行展开没有数据，对于没有数据的行，我不希望展开操作的icon被渲染出来，我看了源码，似乎外界无法干预

**Comment by yesmeck** [comment]
这样的话，用 rowClassName 自己加个 className，然后用 css 隐藏就可以了。
