### ISSUE TITLE
关于ant-modal组件关闭的建议

### ISSUE THREAD

**Issue by Xiu-Lan** [ant-design/ant-design#816]
现在ant-modal组件关闭后，是在ant-modal-maskDom节点上增加ant-modal-mask-hidden样式，建议，组件关闭后，在ant-modal-container节点上增加ant-modal-container-hidden样式，这样，对于有弹窗垂直居中需求时，只要修改部分样式既可

**Comment by Jessie-D** [comment]
接上面的继续建议，ant-modal组件关闭可不可以不隐藏，真的清除弹窗元素

**Comment by yiminghe** [comment]
不行的，有动画逻辑

**Comment by petergzc** [comment]
modal组件的关闭动画，帧率是相当的低，感觉相当卡顿
