### ISSUE TITLE
customize theme build the less file error

### ISSUE THREAD

**Issue by pannz** [ant-design/ant-design#8162]
### Version
2.13.9

### Environment
browser

### Reproduction link
[https://github.com/ant-design/antd-init/issues/126](https://github.com/ant-design/antd-init/issues/126)

### Steps to reproduce
origin this issue:
https://github.com/ant-design/antd-init/issues/126

### What is expected?
should compile without error

### What is actually happening?
./src/index.less
Module build failed:

      color: @text-color-secondary;
      .iconfont-size-under-12px(9px);
    ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
      .../antd/lib/cascader/style/index.less (line 94, column 6)

and less ^2.7.2
less-loader: ^4.0.5   and only with options: strictMath: true,

---
I thought this is a simple issue.
Hope someone from antd will nicely resolve this

**Comment by afc163** [comment]
Perhaps just don't set `strictMath: true`?

**Comment by yesmeck** [comment]
Closing since it's inactive, @pannz if you can upload a reproduction repo, I'll reopen it.

**Comment by mendoncanorma** [comment]
I too have the same issue. Details below:
I was on less 3.11.1, after I upgraded to 4.x.x, ants build fails for less. 

ERROR in ./node_modules/antd/lib/alert/style/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


    position: absolute;
    top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;
  ^
Operation on an invalid type
      Error in D:\_Norma_Learning\r2-ui\node_modules\antd\lib\alert\style\index.less (line 29, column 4)
    at processResult (D:\_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:675:19)
    at D:\_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:777:5
    at D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.lessLoader (D:\_Norma_Learning\r2-ui\node_modules\less-loader\dist\index.js:49:5)
 @ ./node_modules/antd/lib/alert/style/index.js 5:0-23
 @ ./dev/react/containers/BlueSnap/BlueSnap.js 7:0-30
 @ ./dev/react/bundles/bluesnap/Bluesnap.js 26:0-58 43:46-54

ERROR in ./node_modules/antd/lib/dropdown/style/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


    .@{ant-prefix}-btn > .@{iconfont-css-prefix}-down {
      .iconfont-size-under-12px(10px);
    ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
      Error in D:\_Norma_Learning\r2-ui\node_modules\antd\lib\dropdown\style\index.less (line 30, column 6)
    at processResult (D:\_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:675:19)
    at D:\_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:777:5
    at D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.lessLoader (D:\_Norma_Learning\r2-ui\node_modules\less-loader\dist\index.js:49:5)
 @ ./node_modules/antd/lib/dropdown/style/index.js 5:0-23
 @ ./node_modules/antd/lib/table/style/index.js 13:0-31
 @ ./dev/react/components/checkout/shipping/ShippingRestriction/ShippingRestriction.js 5:0-30
 @ ./dev/react/components/checkout/shipping/Shipping.js 49:0-76 623:68-87
 @ ./dev/react/containers/Checkout/Checkout.js 75:0-67 2832:42-50
 @ ./dev/react/bundles/checkout/Checkout.js 27:0-58 44:46-54

@afc163 , I tried `strictMath: false` and no luck.

**Comment by gustav0** [comment]
We are getting the same error with webpack 5 and antd 3.

@mendoncanorma did you manage to get it working?

**Comment by mendoncanorma** [comment]
@gustav0 ,
Unfortunately I had to revert to less 3.11.1 and it started working.

**Comment by pydlv** [comment]
@gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.

Set
`math: 'always'` in your less options for it to compile like it did in Less v3

**Comment by mendoncanorma** [comment]
@pydlv , Thank you. That helped me upgrade.

~Norma

**Comment by liamfend** [comment]
> @gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.
> 
> Set
> `math: 'always'` in your less options for it to compile like it did in Less v3

you did a great thing ~~ in chineses is 🐂🍺 。。

**Comment by Shen120** [comment]
> @gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.
> 
> Set
> `math: 'always'` in your less options for it to compile like it did in Less v3

thanks，I've solved it

**Comment by devil9108** [comment]
I too have the same issue after adding the **antd-scss-theme-plugin** to our project.
we are using wepack: 4.40.2, less: 3.10.3, less-loader: 5.0.0

At first got the below error
`position: absolute;
top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;`
Resolved it by adding `strictMath: true`

After that got the below error
` &-loading-icon {
      .iconfont-size-under-12px(10px);
    ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
      in D:\Phoenix-spa\node_modules\antd\lib\cascader\style\index.less (line 217, column 6)`
      
Its not resolving. Any one please help me on this.

At present my plugin code is like below
`AntdScssThemePlugin.themify({
	loader: 'less-loader',
	options: {
		javascriptEnabled: true,
		strictMath: true,
		strictUnits: false,
		math: 'strict',
		sourceMap: isEnvProduction && shouldUseSourceMap
	}
})`

**Comment by wzx-xle** [comment]
> @gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.
> 
> Set `math: 'always'` in your less options for it to compile like it did in Less v3

thinks, I've solved it. My environment is Less v4.1.2 and less-loader v10.2.0 and AntD v1.7.8 and Vue2.
My vue.config.js is
```
css: {
  loaderOptions: {
    less: {
      lessOptions: {
        javascriptEnabled: true,
        math: 'always',
      }
    }
  }
}
```

**Comment by RichieChoo** [comment]
> > @gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.
> > Set
> > `math: 'always'` in your less options for it to compile like it did in Less v3
> 
> you did a great thing ~~ in Chinese is 🐂🍺 。。

> He may not know how to speak  🐂🍺 ，just like `new bee`

**Comment by ghostcode** [comment]
> @gustav0 @mendoncanorma I had the same issue but I think I have resolved it. If you check the Less options documentation here: https://lesscss.org/usage/ it states that the `strictMath` option was replaced by the `math` option.
> 
> Set `math: 'always'` in your less options for it to compile like it did in Less v3

great，save  my time!
