### ISSUE TITLE
How to use Upload component it's not sending anything

### ISSUE THREAD

**Issue by johhansantana** [ant-design/ant-design#8165]
Hello

I'm trying to use the `Upload` component

```jsx
<Upload
  action="//localhost:3001/api/v1/file/upload"
  listType="picture-card"
  fileList={fileList}
  onPreview={this.handlePreview}
  onChange={this.handleChange}
>
```

but on the endpoint API I receive nothing when I select the file to upload.

**Comment by codercatmomi** [comment]
same problem
have u got the solution? John?

**Comment by kbardi** [comment]
I created a valid issue for this. I have the same problem.

Look at issue #9361
