### ISSUE TITLE
Two items selected by search and choose cleared if i close one of them when setting showCheckedStrategy SHOW_ALL or SHOW_PARENT

### ISSUE THREAD

**Issue by 131310118** [ant-design/ant-design#8167]
### Version
2.13.9

### Environment
chrome 59

### Reproduction link
[https://codepen.io/131310118/pen/OOpBNp](https://codepen.io/131310118/pen/OOpBNp)

### Steps to reproduce
treeSelect:
1. settings
	1. multiple={true}
	2. treeCheckable={true}
	3. allowClear={true}
	4. dropdownStyle={{maxHeight: '500px'}}
	5. dropdownMatchSelectWidth={false}
	6. treeNodeLabelProp="value"
	7. showCheckedStrategy={TreeSelect.SHOW_ALL}
	8. treeData={
		1. P001
			1. 0020
				1. 9459
		1. P002
			1. 0021
				1. 9458
	9. }
		
2. steps:
	1. input 9458 and select 9458
	2. input 9459 and select 9459
	3. close 9458

### What is expected?
9458 was closed and 9459 was still alive

### What is actually happening?
9458 and 9459 were all cleared

**Comment by zombieJ** [comment]
close since `3.7.0` released.
