### ISSUE TITLE
Missing explicit type

### ISSUE THREAD

**Issue by abramobagnara** [ant-design/ant-design#8175]
### Version
2.13.10

### Environment
Linux

### Reproduction link
[http://is.pointless](http://is.pointless)

### Steps to reproduce
tsc --noImplicitAny

### What is expected?
A successful build.

### What is actually happening?
ERROR in [at-loader] ./node_modules/antd/lib/calendar/Header.d.ts:11:22 
    TS7006: Parameter 'value' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/antd/lib/table/SelectionBox.d.ts:10:16 
    TS7006: Parameter 'e' implicitly has an 'any' type.

**Comment by yesmeck** [comment]
You are welcome to help use improve type definitions, see #5627.

For now, you can set `skipLibCheck` to true in tsconfig.json to ignore these errors.
