### ISSUE TITLE
Tabs doesn't support primitive MouseEvent

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#8176]
### Version
2.13.10

### Environment
macOS 10.12.6, Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/tylerlong/pen/rYmjEj?editors=0010](https://codepen.io/tylerlong/pen/rYmjEj?editors=0010)

### Steps to reproduce
Open the link https://codepen.io/tylerlong/pen/rYmjEj?editors=0010. Click tabs and watch console output.

### What is expected?
Should trigger MouseEvent documented here: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

### What is actually happening?
Neither `onClick` nor `onclick` events of the tabs are triggered.

`onTabClick` event was triggered **BUT** you can only get the targetKey as argument, you **cannot** get the primitive MouseEvent documented here: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

---
I created an issue which was closed without actually resolving: https://github.com/ant-design/ant-design/issues/8113

This time I created a new one with a reproducible link.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/BmLKre?editors=0110

**Comment by afc163** [comment]
I think we need event argument of onTabClick, could you create a PR to https://github.com/react-component/tabs for this?

**Comment by tylerlong** [comment]
I will try but I am not sure when I have time to do it.

**Comment by coljung** [comment]
@tylerlong Any updates on this ? Otherwise I'll try to work on it within the next few weeks.

**Comment by tylerlong** [comment]
@coljung. Feel free to take it. I no longer use AntD recently.

**Comment by afc163** [comment]
close by https://github.com/react-component/tabs/pull/118

**Comment by kaminskypavel** [comment]
a workaround in the meanwhile 

```
                    <TabPane
                        tab={<div
                            onMouseUp={(e) => {
                            if(e.button == 1) {
                                console.log("close me");
                            }

                        }}
                        >{pane.title}</div>}
                        key={pane.key}
                    >
                        {pane.content}
                    </TabPane>

```
