### ISSUE TITLE
react 升级16.1.0之后 BackTop target属性发出警告

### ISSUE THREAD

**Issue by duzitengg** [ant-design/ant-design#8179]
```
   <BackTop target={() => document.getElementById('backTop')}>
          <div>
            <Icon type="arrow-up" className='backTop' />
          </div>
        </BackTop>
```

错误提示：
Warning: Invalid value for prop `target` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in div (created by BackTop)
    in AnimateChild (created by Animate)
    in Animate (created by BackTop)
    in BackTop (created by Product)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by Product)
    in Product
    in Unknown (created by Form(WrappedComponent))
    in Form(WrappedComponent) (created by RouterContext)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by FirstPage)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by FirstPage)
    in div (created by FirstPage)
    in FirstPage (created by Connect(FirstPage))
    in Connect(FirstPage) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

有没有同样问题的？怎么解决？

**Comment by superlbr** [comment]
@duzitengg  有一层空的<div>，antd的组件里类似的提示还有很多，个人觉得可以忽略。

**Comment by afc163** [comment]
Fixed in #8848

**Comment by superlbr** [comment]
It's unreasonable that ant-design-bot add invalid label and closed

**Comment by afc163** [comment]
Any issue didn't created by [Issue Helper](http://new-issue.ant.design?repo=ant-design) will be closed by bot.
