### ISSUE TITLE
TimePicker 为受控组件时，希望可以控制面板的收起

### ISSUE THREAD

**Issue by l19861225q** [ant-design/ant-design#818]
如题，希望可以一次性选择完成 时/分/秒 再收起面板，不要每次只能选择一种（时/分/秒）就收起面板，然后要再点击才能弹出面板继续选择，太麻烦

**Comment by afc163** [comment]
现在的交互并不是选中后收起吧。

**Comment by l19861225q** [comment]
@afc163 

@0.11 TimePicker 受控组件 Demo 就是啊，随便选中一项马上就收起了

http://ant.design/components/time-picker/#picker-demo-value

**Comment by afc163** [comment]
感觉是个 bug 。

**Comment by l19861225q** [comment]
@afc163 

我自己现在 hack 了下

```
<TimePicker onChange={ () => { return false } } />
```

然后当选择完成时，点击面板外部即可正常收起
