### ISSUE TITLE
Menu problem in 3.0-beta

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8180]
- [x] Sub Menu width don't match.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/507615/32707549-a648dcf0-c85f-11e7-8409-edd9f64ad5ec.png">

- [x]  ~~Menu inline and Menu vertical padding should be same. ~~

![1](https://user-images.githubusercontent.com/507615/32707580-ddd90b72-c85f-11e7-8a55-e5b935168f01.gif)

**Comment by yesmeck** [comment]
![default](https://user-images.githubusercontent.com/465125/32760131-c89419d2-c927-11e7-8ac8-071d32eb43e5.png)

https://github.com/react-component/menu/commit/e2d85a05e2e4c42412bd92395bd268312c410087

@benjycui

**Comment by benjycui** [comment]
> Menu inline and Menu vertical padding should be same.

See: https://ant.design/components/menu/#components-menu-demo-switch-mode

**Comment by afc163** [comment]
My bad.

**Comment by benjycui** [comment]
@yesmeck reinstall to fix it.

**Comment by benjycui** [comment]
@afc163  reinstall to fix it.
