### ISSUE TITLE
antv 图例跟数据对不上

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8183]
### Version
2.13.10

### Environment
Mac上，chrome浏览器

### Reproduction link
[https://antv.alipay.com/g2/demo/03-area/area-stack.html](https://antv.alipay.com/g2/demo/03-area/area-stack.html)
如图，数据1766那条，对应的图相对于Y轴对应过去明显超过标识2000的数值线，其他的也是一样，没对上

### Steps to reproduce
点开antv官网案例
![image](https://user-images.githubusercontent.com/19485727/32715368-fe633bba-c88c-11e7-9b06-c0ec418489e5.png)

### What is expected?
数据跟图例能对上

### What is actually happening?
数据跟图例能对不上

**Comment by afc163** [comment]
You should create issue to antv's repository.

**Comment by aw6658913** [comment]
OK，Can you tell me the address?

**Comment by afc163** [comment]
https://github.com/antvis/g2
