### ISSUE TITLE
How can I clear the list of uploadList in Upload

### ISSUE THREAD

**Issue by Zhouxingzu** [ant-design/ant-design#8185]
### What problem does this feature solve?
When to use Upload,  I need to clear the list of uploadList by  click one button. I can't find the function

### What does the proposed API look like?
I need to clear the list of uploadList by  click one button

**Comment by afc163** [comment]
Control the `fileList` of Upload.

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by Zhouxingzu** [comment]
thanks

**Comment by Deosaju** [comment]
I can't clear filelist after uploaded successfully.

The preview is still in the page after file is uploaded
