### ISSUE TITLE
antd have some function like Bootstrap(hidden-sm）grid format visible or invisible?

### ISSUE THREAD

**Issue by JediBai** [ant-design/ant-design#8193]
### Version
2.13.10

### Environment
react-antd

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
antd have some function like Bootstrap(hidden-sm）grid format visible or invisible?

### What is expected?
I need something like this function in our project.

### What is actually happening?
visible or invisible elem within grid format.

**Comment by afc163** [comment]
Nope, it is React, you can just use `this.state.visible ? <div /> : null`

**Comment by afc163** [comment]
Try set span to 0: `<Col xs={0} sm={12}>`

**Comment by JediBai** [comment]
thx,its really help

**Comment by masterkrang** [comment]
what if you want to hide individual elements within a Col?

**Comment by JediBai** [comment]
> what if you want to hide individual elements within a Col?

try <Col span={0}>${elem}</Col>

**Comment by JediBai** [comment]
> what if you want to hide individual elements within a Col?

try `<Col span={0}>${elem}</Col>`
