### ISSUE TITLE
inputNumber无法输入小数点

### ISSUE THREAD

**Issue by Solitary-Z** [ant-design/ant-design#8196]
### Version
2.13.10

### Environment
http://react-component.github.io/input-number/examples/decimal.html

### Reproduction link
[http://react-component.github.io/input-number/examples/decimal.html](http://react-component.github.io/input-number/examples/decimal.html)

### Steps to reproduce
**注：当前输入法为中文输入法**
1.进入官方提供的demo链接
2.点击输入框获取焦点，按删除键剩数字8
3.按"."键

### What is expected?
"."正常输入

### What is actually happening?
"."无法输入

---
再输入任何一位数字后，"."可以正常输入

**Comment by Solitary-Z** [comment]
同理可以ant.design   小数的demo  存在同样的问题   https://ant.design/components/input-number-cn/

**Comment by Solitary-Z** [comment]
![image](https://user-images.githubusercontent.com/6871414/32772502-fe8afdce-c960-11e7-8cd2-5c7a5ed0a5bd.png)
能输入这种体验也不是很好

**Comment by yesmeck** [comment]
> 当前输入法为中文输入法

你输的是 `。`？

**Comment by Solitary-Z** [comment]
1.当前输入法为中文输入法当我按"."时我不能确定我按的是"。"还是"."
2.但是参照https://ant.design/components/input-number-cn/  小数的demo  默认为空，当前输入法是中文输入法，这时我可以输入1.2  
3.按删除键删除小数点以及后面的数字后，这时我无法输入“.”，但再次输入一个数字后又能输入"."
4.而且在中国这个大环境下，表单提交大部分内容是中文的，用户不知道也不可能知道在某个输入框输入小数时需要切换成英文输入法。
5.特别奇怪的是第一次输入没有问题，只有删除小数点后再输入小数点会有问题，输入以为数字后又没有问题。

**Comment by hansnow** [comment]
@Solitary-Z 关于5，即第一次输没问题，第二次输有问题
你可以做如下试验：
1. 打开任意一个可以输入文本的程序，比如`notepad.exe`或者浏览器里的input
2. 切换到中文输入法
3. 随便输一个数字，然后多按几次"点"
4. 我猜看到的是这样的结果`1.。。。。。`，也就是说，输完数字后紧接着输入的"句号"被自动转成"."了

**Comment by Solitary-Z** [comment]
@hansnow 结果是那样，但是对于大多数用户来说是不知道的，就会认为你程序是有问题的，从用户体验来说是很不友好的，所以程序是不是需要改进一下?

**Comment by XmYellow** [comment]
不是可是通过precision 设置精度吗
