### ISSUE TITLE
Change Color of Rate

### ISSUE THREAD

**Issue by spaceraccoon** [ant-design/ant-design#8197]
### What problem does this feature solve?
Currently Rate fill color is fixed at @rate-star-color: #f5a623. Setting the color of ant-rate-star-full  in CSS doesn't appear to change it. We should be able to change this.

### What does the proposed API look like?
Either via CSS .ant-rate-star-full {
    color: #NEWCOLOR;
} or `<Rate color='NEWCOLOR'>`

**Comment by afc163** [comment]
Try less variables https://ant.design/docs/react/customize-theme

**Comment by afc163** [comment]
Now we can use `<Rate style={{ color: '#00c' }}>`.

**Comment by sarmad1995** [comment]
the color property would work for the stars which are selected, what about the other stars? I can't find a way to change that

**Comment by udonmai** [comment]
@sarmad1995 set `color` on `.ant-rate-star-first` or `.ant-rate-star-second` will work
