### ISSUE TITLE
table columns width not working when table width exceeds container's

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#8198]
### Version
2.13.10

### Environment
Mac Chrome

### Reproduction link
[https://codepen.io/CallMeXYZ/pen/pdrpdv?editors=001](https://codepen.io/CallMeXYZ/pen/pdrpdv?editors=001)

### Steps to reproduce
See the link

### What is expected?
the table can be scrollable and all columns have the desired width

### What is actually happening?
Setting not working  even if adding `scroll={{x:true}}`

**Comment by CallMeXYZ** [comment]
#6700

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8079#issuecomment-343828418
