### ISSUE TITLE
希望可以实现Table的最大化展示

### ISSUE THREAD

**Issue by fengxiaotx** [ant-design/ant-design#8200]
### What problem does this feature solve?
当数据较多的时候，不用去滚动条操作，就可以操作顶部的按钮和底部的分页。

### What does the proposed API look like?
可以通过配置实现Table的组件最大化展示。例如

``` 
<div>
	<Table />
</div>
```

这里的Table可以撑满整个div ，并且随着div的大小变化而变化

**Comment by hansnow** [comment]
当数据较多的时候，最好固定Table长度(使用`scroll`参数)，方便使用者在不滚动页面的情况下操作翻页条等控件

**Comment by fengxiaotx** [comment]
很难这么做，scroll只能设置表格内部的可变高度。但是，整个表格的最大高度，没法去判断。表格还会有头部什么的

**Comment by benjycui** [comment]
> 可以通过配置实现Table的组件最大化展示。

其实这个更多的是业务代码决定的吧。

**Comment by benjycui** [comment]
不需要额外的配置，业务代码计算需要展示多少行，然后设置即可。

**Comment by fengxiaotx** [comment]
达不到那个效果的，业务代码计算行数？这个就有点不现实了，屏幕有大有小，不设置自动适应大小，怎么去实现最大化，而且，行数怎么计算？参考extjs的实现，说白了，就是要通过计算去得到应该展示的table的大小

**Comment by yesmeck** [comment]
有想法的话直接给我们 PR 吧，issue 不活跃就先关闭了。
