### ISSUE TITLE
ant-design message 多线程bug

### ISSUE THREAD

**Issue by IDrinkMoreWater** [ant-design/ant-design#8201]
### Version
2.13.10

### Environment
windows 7 64bit，chrome 62 

### Reproduction link
[https://codepen.io/anon/pen/xPLJwN?editors=001](https://codepen.io/anon/pen/xPLJwN?editors=001)

### Steps to reproduce
```
message.loading('hello world1111111',0);

setTimeout(()=>{message.destroy();},2000);

message.loading('hello world222222',0);

setTimeout(()=>{message.destroy();},3000);
```

### What is expected?

   

- 场景：由于项目需要我们在项目中封装了自定义fetch，实现fetch之前message弹出数据加载中（message时长为0，不会自动销毁），直到fetch异步回调之后调用message.destroy()手动销毁；
 
-    问题1：2.13.10 版本中，fetch并发时，会弹出多个message，但只要任何一次回调调用message.destroy()，多个message都会全部销毁，并且每次销毁message的示例会赋值null，为null的话再次destroy就直接return；

-    问题2：最近工程想升级到React v16，编译的时候发现rc-notifcation 2.0不兼容，折腾后发现要升级到ant-design 3.0.0-beta.7 ，但去看rc-notifcation 3.0的源码逻辑调整了，多线程的场景下现在message.destroy()的时候只会销毁当前的message，这就更糟糕了，其他线程的message都没办法销毁了，3.0.0-beta.7现在没办法发重现链接（希望以后考虑beta版的放出来，开发者也可以帮忙测试）；

### What is actually happening?
  
-  期望：message可以考虑多线程的场景，建议的解决方法是，每次message后返回一个id甚至直接dom节点的引用，销毁的时候，destroy做个参数重载，再传参进去销毁指定的message。可以参考layer.js的逻辑就是这样实现的。

-    其他：多线程的场景还是很多的，就算不是封装在fetch里面，在ant-design 3.0稍微不注意就会出现message无法销毁的情况，也有想过用Spin，但Spin糅合dom，没有message灵活；如果把多个fetch的实现合并成一个回调，这种方法也能解决问题，但是说实话项目成员水平参差不齐，难免会忘记处理合并成fetchAll。

**Comment by afc163** [comment]
1. you can use hide to destroy the specified message: https://ant.design/components/message/#components-message-demo-loading
2. 3.x will destroy all message: https://codepen.io/afc163/pen/zPEdOY?editors=0010

**Comment by IDrinkMoreWater** [comment]
@afc163 谢谢你的回复，还是没有解决问题，后来经过版本代码比对发现同样是ant-design 3.0.0-beta.7，通过npm安装的和您codepen测试所用的代码（https://unpkg.com/antd@3.0.0-beta.7/dist/antd-with-locales.js）有一些差异，不知道这是不是造成测试结果不同的原因

**npm 下载的message的index.js代码部分如下：**
```
function notice(content) {
    var duration = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : defaultDuration;
    var type = arguments[2];
    var onClose = arguments[3];

    var iconType = {
        info: 'info-circle',
        success: 'check-circle',
        error: 'cross-circle',
        warning: 'exclamation-circle',
        loading: 'loading'
    }[type];
    if (typeof duration === 'function') {
        onClose = duration;
        duration = defaultDuration;
    }
    getMessageInstance(function (instance) {
        instance.notice({
            key: key,
            duration: duration,
            style: {},
            content: React.createElement(
                'div',
                { className: prefixCls + '-custom-content ' + prefixCls + '-' + type },
                React.createElement(Icon, { type: iconType }),
                React.createElement(
                    'span',
                    null,
                    content
                )
            ),
            onClose: onClose
        });
    });
    return function () {
        var target = key++;
        return function () {
            if (messageInstance) {
                messageInstance.removeNotice(target);
            }
        };
    }();
}
```

**codepen的部分代码如下：**

```
function notice(content, duration = defaultDuration, type, onClose) {
    let iconType = ({
        info: 'info-circle',
        success: 'check-circle',
        error: 'cross-circle',
        warning: 'exclamation-circle',
        loading: 'loading',
    })[type];
    if (typeof duration === 'function') {
        onClose = duration;
        duration = defaultDuration;
    }
    getMessageInstance((instance) => {
        instance.notice({
            key,
            duration,
            style: {},
            content: (<div className={`${prefixCls}-custom-content ${prefixCls}-${type}`}>
          <Icon type={iconType}/>
          <span>{content}</span>
        </div>),
            onClose,
        });
    });
    return (function () {
        let target = key++;
        return function () {
            if (messageInstance) {
                messageInstance.removeNotice(target);
            }
        };
    }());
}
```
   看起来差别不大，但是断点运行的时候发现差别很大，codepen测试正常的情况getMessageInstance的回调会先执行，在执行return ,但是通过npm 安装的情况调试的时候会先return 后执getMessageInstance的回调，这样子key++已经执行了，导致hide时候是remove的key=1的message，而getMessageInstance的回调则后执行渲染到dom时标记的key是2，所以出现了remove key=1无法清除message
  
   为了说明问题（**排除是我的环境问题**），我git 了**ant-design-pro**来测试，ant-design-pro用的刚好是3.x的版本，我在ant-design-pro的Analysis.js中componentDidMount方法添加
```
   const hide = message.loading('Action in progress..', 0);
    // Dismiss manually and asynchronously
    setTimeout(hide, 2500);
```
 然后npm start问题立马就出来了，同样了message无法销毁，断点调试一样的结果key值发生了错乱，

PS：ant-design-pro用的是ant-design 3.0.0-beta.1，修改为ant-design 3.0.0-beta.7后问题仍存在，我的node环境6.13，更新到node 8.9.1问题也依然存在

**Comment by afc163** [comment]
> ant-design-pro用的是ant-design 3.0.0-beta.1，修改为ant-design 3.0.0-beta.7后问题仍存在

你更新了本地 node_modules

**Comment by IDrinkMoreWater** [comment]
@afc163 确定更新本地 node_modules的到了ant-design 3.0.0-beta.7，查看了package.json，只要用ant-design-pro应该能重现吧，期待解决，这个问题还是挺闹心的

**Comment by afc163** [comment]
等下个 beta 发布即可。

**Comment by IDrinkMoreWater** [comment]
@afc163 继续反馈Bug，更新到rc1后hide的问题解决了，但是destroy的问题还是存在，依然是codepen中测试没有问题，但是工程整合进去就有问题，还有项目要忙我就没去细看源码了，具体说下问题和重现。
       测试环境还是**ant-design-pro**加 **ant 3.0.0-rc.1** ，什么都没改，就只是在在ant-design-pro的Analysis.js中componentDidMount方法添加如下代码块
```
        message.loading('Action in progress1..', 0);
	message.loading('Action in progress2..', 0);
        setTimeout(()=>{message.destroy();}, 2000);
	setTimeout(()=>{message.destroy();}, 4000);
```

**期望：** 第一次setTimeout到达时，两个message应该全部销毁；

**结果：**progress2被销毁，progress1未销毁；

**分析：**如果只执行一次loading和destroy，message可以正常销毁，像上面的如果执行2次，然后异步回调则progress1未销毁，执行三次则只有progress3销毁，就是说destroy只会销毁最后一个。

**PS：**我想这个问题要延伸一下，为什么dist到codepen的包没有问题，一整合到项目中就异常了，是TypeScript和Babel的编译问题，还是webpack的配置环境问题，其他组件会不会有类似的问题，请ant团队能够明确下问题根本原因。

**Comment by afc163** [comment]
代码本身有问题，codepen 的包也有问题。
