### ISSUE TITLE
在create-react-app中按照官网配置使用antd后无法使用webpack的别名alias

### ISSUE THREAD

**Issue by cc616** [ant-design/ant-design#8203]
### Version
2.13.10

### Environment
OSX 10.11.6 、Google Chrome 61.0.3163.100、node v6.10.1、npm v6.10.1

### Reproduction link
[https://github.com/cc616/antd-dome](https://github.com/cc616/antd-dome)

### Steps to reproduce
1.按照中文官网创建antd-dome
2.使用npm run reject 展开配置项
3.按照官网修改package.json和新建config-overrides.js文件以及npm install 必要的package
4.修改webpack.config文件中resolve的alias配置项，在引用自定义组件时使用别名

### What is expected?
按照官网配置antd后也能够使用别名来引用组件

### What is actually happening?
若按照官网修改了package.json中的scripts参数则启动项目时会报Module not found: Can't resolve 'Src/App' 在项目中，若不修改packkage.json中的scripts参则能使用别名来引用组件，但是无法使用antd样式

---
希望在文档中补充需要安装react-scripts包，这个地方已坑了两次

**Comment by afc163** [comment]
npm run eject 和 config-overrides.js 是冲突的。如果你 eject 了配置，你需要自行探索。

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git
