### ISSUE TITLE
Prevent value from showing if the option does not exist

### ISSUE THREAD

**Issue by gavinrobertszeco** [ant-design/ant-design#8205]
### Version
2.13.10

### Environment
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/gRoberts84/pen/ZaJVpY?editors=001](https://codepen.io/gRoberts84/pen/ZaJVpY?editors=001)

### Steps to reproduce
Specify a value that does not exist within the available options (if any)

### What is expected?
Element with placeholder or nothing at all displayed.

### What is actually happening?
The raw value provided is shown.

---
When pre-populating fields before the available options exist, or if the option has been removed, then the raw value is shown. 

Is there a way we can only show a value, if an option exists that matches it?

**Comment by yesmeck** [comment]
Use `labelInValue`, then set value to `{ key: 1, label: 'One' }`.
