### ISSUE TITLE
关于ant-design 2.13.10版本使用Upload组件编译打包报错的问题

### ISSUE THREAD

**Issue by GankLun** [ant-design/ant-design#8210]
### Version
2.13.10

### Environment
win7 

### Reproduction link
[https://github.com/ant-design/ant-design/issues/7515](https://github.com/ant-design/ant-design/issues/7515)

### Steps to reproduce
import { Breadcrumb, Icon, message ,Upload} from 'antd';
<Upload/>

### What is expected?
能打包成功

### What is actually happening?
打包编译失败

---
ERROR in ./node_modules/_attr-accept@1.1.0@attr-accept/dist/index.js
Module build failed: ReferenceError: [BABEL] C:\Users\Administrator\Desktop\FEK\node_modules\_attr-accept@1.1.0@attr-accept\dist\index.js: Using removed Babel 5 o
ption: C:\Users\Administrator\Desktop\FEK\node_modules\_attr-accept@1.1.0@attr-accept\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.
io/docs/plugins/#presets
    at Logger.error (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\options\option-manager.js
:220:20)
    at OptionManager.init (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\options\option-manager.js:368:12)

    at File.initOptions (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-loader@7.1.2@babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-loader@7.1.2@babel-loader\lib\index.js:175:20)
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/AjaxUploader.js 51:18-40
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/Upload.js
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/index.js
 @ ./node_modules/_antd@2.13.10@antd/lib/upload/Upload.js
 @ ./node_modules/_antd@2.13.10@antd/lib/upload/index.js
 @ ./src/detail/index.js
 @ ./src/routes/route.js
 @ ./src/app/index.js
 @ ./src/home/home.js
 @ ./src/routes/index.js
 @ ./src/index.js
 @ multi ./node_modules/_webpack-dev-server@2.9.4@webpack-dev-server/client?http://localhost:3002 ./src/index.js

**Comment by afc163** [comment]
Could you provide a reproduce GitHub repo?

**Comment by GankLun** [comment]
this is my package.json 
{
  "name": "first-react",
  "version": "1.0.0",
  "description": "my first react sample",
  "main": "./public/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "cross-env NODE_ENV=development webpack-dev-server --open --progress --colors",
    "build": "cross-env NODE_ENV=production webpack -p --progress --colors"
  },
  "theme": {
    "primary-color": "#108ee9"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-import": "^1.6.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "create-ecdh": "^4.0.0",
    "cross-env": "^5.1.0",
    "css-loader": "^0.28.7",
    "eslint": "^4.8.0",
    "eslint-plugin-react": "^7.4.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "html-webpack-plugin": "^2.30.1",
    "jquery": "^3.2.1",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "path": "^0.12.7",
    "style-loader": "^0.18.2",
    "url-loader": "^0.5.9",
    "webpack": "^3.5.6",
    "webpack-dev-server": "^2.8.1"
  },
  "dependencies": {
    "antd": "^2.13.10",
    "babel-polyfill": "^6.26.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^2.8.1",
    "whatwg-fetch": "^2.0.3"
  }
}

webpack.config.js

const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const extractTextPlugin = new ExtractTextPlugin({
    filename: 'index-[hash].css',
    disable: process.env.NODE_ENV === 'development'
});
const host = process.env.NODE_ENV === 'development' ? 'http://localhost:8080/' : 'http://10.51.12.191:8088/';
module.exports = {
    devtool: 'none',
    entry: ['./src/index.js'],
    output: {
        path: __dirname + '/dist',
        filename: 'index-[hash].js'
    },
    devServer: {
        contentBase: './dist',
        port: 3002,
        host: 'localhost',
        proxy: {
            '/LJWidget/**': {
                target: 'http://10.51.12.191:8088/',
                changeOrigin: true,
                secure: false
            },
            '/front-end/**': {
                target: host,
                changeOrigin: true,
                secure: false
            }
        },
        historyApiFallback: true,
        inline: true
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        'presets': [
                            'env',
                            'react',
                            'stage-0'
                        ],
                        'plugins': [
                            ['import', { libraryName: 'antd', style: true }]
                        ]

                    }

                }


            },
            {
                test: /\.css$/,
                use: extractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader'
                })
            },
            {
                test: /\.less$/,
                use: extractTextPlugin.extract({
                    use: [{
                        loader: 'css-loader'
                    }, {
                        loader: 'less-loader',
                        options: {
                            'modifyVars': { '@primary-color': '@blue-6' }
                        }
                    }],
                    // use style-loader in development
                    fallback: 'style-loader'
                })
            },
            {
                test: /\.(png)|(jpg)|(gif)$/,
                use: {
                    loader: 'url-loader?limit=20000&name=images/[name]-[hash:8].[ext]'
                }

            },
            {
                test: /\.(woff)|.(woff2)|.(svg)|.(eot)|.(ttf)$/,
                use: {
                    loader: 'url-loader?limit=10000&name=font/[name].[ext]'
                }
            }
        ]
    },
    plugins: process.env.NODE_ENV === 'production' ? [
        new webpack.BannerPlugin('This file is created by czl,版权所有，翻版必究'),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin(),
        new webpack.DefinePlugin({
            PRODUCTION: JSON.stringify(true),
    
        }),
        new HtmlWebpackPlugin({
            template: path.join(__dirname + '/src', 'index.html'),
            filename: 'index.html',
            inject: 'body',
            title: 'Fek-Repository-学的不仅是技术，更是梦想！',
            favicon: './favicon.ico'

        }),
        extractTextPlugin

    ] :
        [
            new webpack.BannerPlugin('This file is created by czl,版权所有，翻版必究'),
            new webpack.optimize.OccurrenceOrderPlugin(),
            new webpack.DefinePlugin({
                PRODUCTION: JSON.stringify(false),
        
            }),
            new HtmlWebpackPlugin({
                template: path.join(__dirname + '/src', 'index.html'),
                filename: 'index.html',
                inject: 'body',
                title: 'Fek-Repository-学的不仅是技术，更是梦想！',
                favicon: './favicon.ico'
            }),
            extractTextPlugin
        ]

};

import { Upload} from 'antd';
<Upload/> 

then error happens 

if not include <Upload/> ,just import  { Upload} from 'antd';
error won't happen

**Comment by afc163** [comment]
Could you provide a reproducible GitHub repo?

**Comment by GankLun** [comment]
https://github.com/GankLun/FirstDemo

**Comment by afc163** [comment]
https://github.com/GankLun/FirstDemo/pull/1
