### ISSUE TITLE
it is work that use the antd on environment of development react SSR but it's not working on production

### ISSUE THREAD

**Issue by masonyeh** [ant-design/ant-design#8212]
### Version
2.12.2

### Environment
Mac OS chrome, react^15.3.1, SSR,building on production

### Reproduction link
[https://github.com/masonyeh/react-ssr-ant-design](https://github.com/masonyeh/react-ssr-ant-design)

### Steps to reproduce
##it's work when i use the antd on environement of development react SSR but it's not working on production

*as no style on production when i npm run build then npm run start.no style on it.so i don't know what happening?

npm command
develop
npm run dev

product
npm run build
npm run start

### What is expected?
get all of styles from antd and it's working on SSR of react.

### What is actually happening?
no style from antd

**Comment by yesmeck** [comment]
You can not just throw such a big project to us and tell us "it's not working and I don't why", try reproduce your issue with a minimal config. If you can confirm it's antd's problem, ping me anytime to reopen this issue.
