### ISSUE TITLE
Customizeable <CheckboxGroup />

### ISSUE THREAD

**Issue by xxryan1234** [ant-design/ant-design#8219]
### What problem does this feature solve?
With this we are not limited to just passing the `options` key values to the `<CheckboxGroup />` property, we can customize how the checkboxes group would look like. We can put them inside <Card> components for example

### What does the proposed API look like?
```
<Card>
  <Checkbox>
    Select All
  </Checkbox>
</Card>

<Card>
  <CheckboxGroup
    value={1}
  >
    Option 1
  </CheckboxGroup>
</Card>

<Card>
  <CheckboxGroup
    value={2}
  >
    Option 2
  </CheckboxGroup>
</Card>

<Card>
  <CheckboxGroup
    value={3}
  >
    Option 3
  </CheckboxGroup>
</Card>
```

it would look like this https://imgur.com/a/TVegf

**Comment by yesmeck** [comment]
I'v implemented a similar feature in a internal project, I'd like the API looks like this:

```javascript
<CheckboxGroup>
  <Card>
    <Checkbox all>
      Select All
    </Checkbox>
  </Card>

  <Card>
    <Checkbox value={1}>
      Option 1
    </Checkbox>
  </Card>

  <Card>
    <Checkbox value={2}>
      Option 2
    </Checkbox>
  </Card>

  <Card>
    <Checkbox value={3}>
      Option 3
    </Checkbox>
  </Card>
</CheckboxGroup>
```

**Comment by xxryan1234** [comment]
Have you implemented it using ant-design @yesmeck? could you possibly share how you did it?

**Comment by yesmeck** [comment]
😱 We's already support this https://codepen.io/yesmeck/pen/yPPXYz?editors=0010

**Comment by xxryan1234** [comment]
if that is the case this kind of scenario should also be added in the list of examples. the example on using `<CheckboxGroup />` makes you believe that it is not possible and is limited only to passing an options value in the property

**Comment by yesmeck** [comment]
@xxryan1234 Would you like to write a example?

**Comment by xxryan1234** [comment]
this issue is not supposed to be closed yet. 😅

**Comment by yesmeck** [comment]
See https://codepen.io/yesmeck/pen/EbbXXO?editors=0010

**Comment by yesmeck** [comment]
Just replace `options` with `Checkbox`.

**Comment by xxryan1234** [comment]
Thanks for the help @yesmeck. When I free up some time I will help updating the documentation. 👍

**Comment by shashankMadan-designEsthetics** [comment]
can i implement also a redirection kind of a functionality on the labels when they are clicked along with check all function?

**Comment by sonsina** [comment]
> 😱 We've already support this https://codepen.io/yesmeck/pen/yPPXYz?editors=0010

@yesmeck hi, I am trying to use this code as a reference (or even as is, copy paste) and I get 
`Warning: [antd: Checkbox] 'value' is not a valid prop, do you mean 'checked'? `

Are you familiar?

**Comment by yogithesymbian** [comment]
how about 
```
<Checkbox.Group
              // options={permissions}
              options={permissions.map((data: any) => {
                return {
                  ...data,
                  render: (item: any) => <>hey</>, // customize
                };
              })}
              value={checkedValues}
              onChange={(values) => onChange(index, values)}
            />
```
