### ISSUE TITLE
different height of FormItem under chrome

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#8220]
### Version
2.13.10

### Environment
Mac 10.12.6, Chrome 62.0.3202.89, Safari 11.0.1

### Reproduction link
[https://codepen.io/CallMeXYZ/pen/jaayYa?editors=0010](https://codepen.io/CallMeXYZ/pen/jaayYa?editors=0010)

### Steps to reproduce
open the link with chrome and safari

### What is expected?
all `FormItem`s have same height to apply to grid layout

### What is actually happening?
under Chrome the height of `FormItem` depends on the wrapped component (`0.5px` difference) while fine under Safari

PS: works fine if setting the size of  all wrapped component 'middle'

**Comment by CallMeXYZ** [comment]
@afc163 would you mind explaining it ?

**Comment by afc163** [comment]
I realy don't know why....

**Comment by sealday** [comment]
我注意到另一个事情，那个 InputNumber 的 size 似乎变成了 large，看样式里面添加了 ant-input-number-lg，而代码中并没有指定 size="large"，这是为什么？
