### ISSUE TITLE
size of the checkbox

### ISSUE THREAD

**Issue by havantuan** [ant-design/ant-design#8223]
### What problem does this feature solve?
How to increase the size of the checkbox?

### What does the proposed API look like?
different sizes:
https://raw.githubusercontent.com/sebastianha/angular-bootstrap-checkbox/HEAD/sizes.png?raw=true

**Comment by yesmeck** [comment]
You need override default style.

**Comment by MandyMeindersma** [comment]
I have tried:

https://stackoverflow.com/questions/306924/can-i-change-the-checkbox-size-using-css
and
changing font size: https://github.com/ant-design/ant-design/pull/7374#issuecomment-328002113

and both do not seem to work. Is there any way this feature could still be implemented?
