### ISSUE TITLE
TreeSelect Search for multiple checkable select

### ISSUE THREAD

**Issue by sky86857322** [ant-design/ant-design#8224]
### What problem does this feature solve?
https://ant.design/components/tree-select/#components-tree-select-demo-checkable
在有checkbox的下拉树形选择框中, 我在input框中输入1, 然后筛选中对应的选型, 选中之后, 输入框生成了标签，但搜索的值无法像上述连接例子一样清空。用户会对此感到困扰

### What does the proposed API look like?
暴露一个参数，让用户决定，选择后，输入框的搜索值可以被清空（结束搜索）

**Comment by yesmeck** [comment]
没明白“但搜索的值无法像上述连接例子一样清空”是什么意思。

**Comment by sky86857322** [comment]
@yesmeck 在输入框输入“1”，下拉框列出相关节点，选择其中一个节点后，输入框生成相应标签，而原本输入的“1”已被删除。
而我的情况是这个“1”没有被清空，依然存在于输入框中

**Comment by yesmeck** [comment]
官网上没有重现你说的问题，请 fork https://codepen.io/benjycui/pen/KgPZrE?editors=001 提供一个在线的重现例子。

**Comment by sky86857322** [comment]
[https://codepen.io/anon/pen/ooowZR?editors=001](url)
我怀疑是环境或是版本的问题了，我把相关参数都用了一次，也无法重现，但我本地即使用官网例子都有这个问题。
请问TreeSelect在那方面会有可能引起这个问题？

**Comment by yesmeck** [comment]
浏览器版本？是否有错误信息？录屏？

**Comment by sky86857322** [comment]
Chrome 55.0.2883.87 m (64-bit)
antd: "^2.12.8", 但试过最新版本2.13.10也没用，
没有任务错误提示，只是输入框的值不消失

**Comment by yesmeck** [comment]
别的浏览器有问题的？

**Comment by sky86857322** [comment]
应该与浏览器无关，我换过浏览器，也换过电脑都一样

**Comment by yesmeck** [comment]
不能提供重现的话，也没办法帮你解决。

**Comment by sky86857322** [comment]
https://codepen.io/anon/pen/ooowZR?editors=001
抱歉，确实无法提供重现，一样的代码在codepen上都没有我这个问题。但我发现2个问题
1、以上的例子，包括官网
1.1 先选择一项
1.2 输入搜索值
1.3 再根据搜索结果选择一项
1.4 删除刚选择的项，结果变成清空了

2、我本地的问题，我研究发现.ant-select-search__field这个input是负责输入搜索值的，render时就有，但value是空的，在官网和我的例子上，只要出发onChange事件value就会被清空，但我本地的就不会

**Comment by yesmeck** [comment]
在你给的例子里发现了另外一个问题，不过你的说问题都没重现。

**Comment by sky86857322** [comment]
@yesmeck 删除单项变成清空的问题，有时会变为无法删除，是随机出现其中一个的
另外我本地的问题暂时通过其他方法解决了，虽然我本地的问题无法重现，但我本地是不会出现问题1的情况

**Comment by yesmeck** [comment]
无法重现你说的问题，先关闭了，如果能再提供准确的重现，我再打开。
