### ISSUE TITLE
How to make relative positioning on popover

### ISSUE THREAD

**Issue by windwalker** [ant-design/ant-design#8225]
### What problem does this feature solve?
Hi,

In our page, we'd like to shift the popover card a little bit down than its original position, say '30px' along the Y axis.

 I tried to add 

```
overlayStyle = {{position: 'relative'; top: '30px'}}
overlayStyle  = {{transform: translateY(30px);}}
```

However, none of it works. I think the reason is that you guys have recalculate the positions and ignores whatever has been added on the popover card style.

### What does the proposed API look like?
Could you please take the original overlayStyle or overlayClass into consideration when you re-calculate the position of the popover card?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5899#issuecomment-297219359

**Comment by sayjeyhi** [comment]
@afc163 what about now? `Tooltip` has not `popupAlign` prop to be set like `popupAlign={{ offset: [-5, -5] }}`

**Comment by johnmeng24** [comment]
set align property: align={{ offset: [0, 5] }}
example: https://react-component.github.io/tooltip/examples/simple.html
