### ISSUE TITLE
language translation

### ISSUE THREAD

**Issue by manoj13036** [ant-design/ant-design#8227]
### Version
2.13.10

### Environment
ubuntu 16.04,chrome,react

### Reproduction link
[https://ant.design/components/locale-provider/](https://ant.design/components/locale-provider/)

### Steps to reproduce
please update

### What is expected?
language of range picker not correctly changing

### What is actually happening?
not changing language of range picker

---
when we apply language translation using antd some thing wrong happening in date picker and range picker

**Comment by yesmeck** [comment]
Please provide online reproduction by forking this codepen http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/507615/32950363-07536a5e-cbe1-11e7-87bf-faff331e116a.png">

**Comment by benjycui** [comment]
The recommended way to switch language is to refresh the page, so this issue will not occur in real world.

The problem is, how to update this demo.
