### ISSUE TITLE
Select menu item click closes filter panel

### ISSUE THREAD

**Issue by prilutskiy** [ant-design/ant-design#8231]
### Version
2.13.10

### Environment
mac os x, react 15, latest chrome

### Reproduction link
[Demo](https://codepen.io/anon/pen/yPKrzp?editors=0110)

### Steps to reproduce
1. Create custom filter panel (uncontrolled, not using filterDropdownVisible) for Table component
2. Place a select component inside custom filter panel JSX
3. Click on select component to open the menu
4. Click on menu item

### What is expected?
I am expecting filter panel not to be closed until I click on reset / apply button or perform a click outside of filter panel

### What is actually happening?
Filter panel closes

---
I am 99.99% sure that you guys use document click handler to track "outside" clicks, but as far as dropdown menu is appended to body your algorithm that most likely uses something like "if (!filterPanel.contains(clickSource)) { closeFilterPanel(); }" does not work in this case.

**Comment by prilutskiy** [comment]
[Demo](https://codepen.io/anon/pen/yPKrzp?editors=0110)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3438

**Comment by prilutskiy** [comment]
@afc163 How this one is related to popover you're referencing?
