### ISSUE TITLE
More flexible setting about trigger in sider

### ISSUE THREAD

**Issue by abz53378** [ant-design/ant-design#8232]
### What problem does this feature solve?
- To customize zeroWidthTrigger.
- To configure triggers with two states, collapsed and expanded.

For now, there are three type triggers of sider, `zeroWidthTrigger`, `expandedTrigger` and `collapsedTrigger`, `zeroWidthTrigger` is the trigger only appears when the `collapsedWidth` is set to 0, and others are the triggers under the sider at different sider status (expanded and collapsed). But we can only use the props `trigger` to set `expandedTrigger` and `collapsedTrigger` with the same ReactNode.  Maybe we can provide more props to configure these triggers detailly. Thanks!

### What does the proposed API look like?
Add two props to sider:
``` js
expandedTrigger: string|ReactNode
collapsedTrigger: string|ReactNode
```
and when collapsedWidth is 0, the `expandedTrigger` and `collapsedTrigger` will replace the default `zeroWidthTrigger`, so the zeroWidthTrigger becomes stateful.

**Comment by ddcat1115** [comment]
I think it's a little bit complex... you can customize the zeroWidthTrigger by setting `trigger={null}` , like [demo](https://ant.design/components/layout/#components-layout-demo-custom-trigger)

**Comment by ddcat1115** [comment]
Please feel free to reopen this issue if there is any other question~
