### ISSUE TITLE
Ant Design 3 RC

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#8233]
It's more than a year from last major release of antd, now the first RC of antd 3 is avaliable for public testing. Here is the preview address http://beta.ant.design.

## Installation

The RC has been published to NPM with the tag "next".

```bash
$ yarn add antd@next
```

or

```bash
$ npm install --save antd@next
```

## Major Changes

- We changed our primary color from `#108EE9` to `#1890FF`, we called the new primary color "拂晓蓝" which means the color of the sky at daybreak.
- Increased the base font size from 12px to 14px.
- Changed default locale to en_US.
- Improved global css style.
- A lot of style improvements.
- Support React 16.
- New [List](http://beta.ant.design/components/list/) Component.
- New [Divider](http://beta.ant.design/components/divider/) Component.
- New [icons](http://beta.ant.design/components/icon/).

## Breaking Changes

- Card's `noHovering` has changed to `hoverable`，and it's default value now is `true`.
- Added new Grid breakpoints. [#7230](https://github.com/ant-design/ant-design/pull/7230)
- Form
  - Removed `exclusive` option of `getFieldDecorator`.
  - Added `createFormField`, and you must use it to wrap field data in `option.mapPropsToFields` of `Form.create`:
    After antd@3.0.0
    ```diff
    import { Form } from 'antd';
    Form.create({
      mapPropsToFields() {
        return {         
    -     name: { value: 'antd' },
    +     name: Form.createFormField({ value: 'antd' }),
        };
      },
    })
    ```
- Since we improved the global reset style, if you prefer the v2 way, we provide a compatible style.

  ```javascript
  import 'antd/style/v2-compatible-reset';
  ```
  or
  ```less
  @import '~antd/style/v2-compatible-reset.css';
  ```

- Since we changed default locale to en_US, so `LocalProvide` is not required for English users now, but for Chinese user, locale must set by `LocalProvide` .

## New Features

- Tabs added new `large` size。
- Grid's `Row[gutter]` now support responsive setting.
- Badge added `offset` to allow setting offset of the badge.
- Spin adde `indicator` to allow setting custom indicator. [#7977](https://github.com/ant-design/ant-design/pull/7977) [@kossel](https://github.com/ant-design/ant-design/pull/7977)
- Progress adde new `@processing-color` less variable.
- Menu added `subMenuOpenDelay` and `subMenuCloseDelay` to allow setting delay time foor submeny toggling。
- Input added `Input.Search[enterButton]` to allow setting custom search button.
- Mention added `placement` to allow setting the popup direction.
- Carousel added `next()`, `prev()`, `goTo(slideNumber)` to allow controlling slides programmatically.
- Card
  - Added new `inner` type. [Demo](http://beta.ant.design/components/card/#components-card-demo-inner)。
  - Added `cover`、`actions` and a new `Meta` component. [Demo](http://beta.ant.design/components/card/#components-card-demo-meta)。
- DatePicker
  - Added `mode` and `onPanelChange` to allow controlling the panel mode. [Demo](http://beta.ant.design/components/date-picker/#components-date-picker-demo-mode)。
  - Added new `WeekPicker`.
  - Added `dateRender` to allow customizing date cell.
- TimePicker
	- Added `hourStep`、`minuteStep`、`secondStep` to allow customizing time setps. [Demo](http://beta.ant.design/components/time-picker/#components-time-picker-demo-interval-options)
	- Added `focusOnOpen` to allow opening panal when input gets focus.
	- Added `@timepicker-item-height` less variable.
- Table
  - Added `components` to allow overriding default table elements.
    ```javascript
    const components = {
      table: MyTable,
      header: {
        wrapper: HeaderWrapper,
        row: HeaderRow,
        cell: HeaderCell,
      },
      body: {
        wrapper: BodyWrapper,
        row: BodyRow,
        cell: BodyCell,
      },
    };

    <Table components={components} columns={columns data={data}}  />
    ```
  - Added `onRow` to allow passing custom props to table body row.
  - Added `onHeaderRow` to allow passing custom props to table header row.
  - Added `column[onCell]` to allow passing custom props to table body cell.
  - Added `column[onHeaderCell]` to allow passing custom props to table header cell.
  - Added `column[align]` to allow setting how text aligns.
	- Added `column[defaultSortOrder]` to allow setting [#8111](https://github.com/ant-design/ant-design/pull/8111)
	- Added `rowSelection[fixed] to allow fixing the selection column.
  - Following props are deprecated:
    - `onRowClick`
    - `onRowDoubleClick`
    - `onRowContextMenu`
    - `onRowMouseEnter`
    - `onRowMouseLeave`

    Please use `onRow` instead:
    ```javascript
    <Table onRow={(record) => ({
      onClick: () => {},
      onDoubleClick: () => {},
      onContextMenu: () => {},
      onMouseEnter: () => {},
      onMouseLeave: () => {},
    })} />
    ```
  - Deprecate `getBodyWrapper`, please use `components` instead。
- Select
  - Option's value can be number in `single` or `multiple` mode.
  - Added `maxTagCount` and `maxTagPlaceholder`.
  - Added `showAction` to allow setting the trigger action for popup.
  - Added `onMouseEnter` and `onMouseLeave`。
- LocaleProvider
  - Added Icelandic. [#7561](https://github.com/ant-design/ant-design/pull/7561) [@paunovic-stefan](https://github.com/paunovic-stefan)
  - Added Egyptian Arabic. [#7888](https://github.com/ant-design/ant-design/pull/7888) [@mohamed-seada-1994](https://github.com/mohamed-seada-1994)
  - Added Ukrainian. [#8169](https://github.com/ant-design/ant-design/pull/8169) [@anxolerd](https://github.com/anxolerd)

## Bug Fixes and Improvements

- Badge's `status` can use with `children` now. [#8164](https://github.com/ant-design/ant-design/issues/8164)
- Form
  - Added animation when showing validate message.
  - Fixed issue result in Input icon is hovered by feedback icon.
  - Now allow to bind same field name for dynamic components rendering.
- Menu
  - Imporoved animation.
  - Fixed keydown error. [#8089](https://github.com/ant-design/ant-design/issues/8089)
- Rate changed to a new color.
- Message
  - `duration` can be optional. [#7857](https://github.com/ant-design/ant-design/issues/7857) [@monkindey](https://github.com/monkindey)
  - Fixed destroy issue, when multiple message exists. [#8201](https://github.com/ant-design/ant-design/issues/8201)

## Removed deprecations

- DatePicker.Calendar has been removed, you can use Calendar directly.
- DatePicker's `toggleOpen` prop has been removed,  use `onOpenChange` instead.
- Form's `inline`, `horizontal`, `vertical` props has been removed, use `layout` instead.
- Input's `type` prop has dropped `textarea`,  please use `Input.TextArea`.
- Mention's `toEditorState` has been removed.
- Select's `multiple`, `combobox`, `tags` props has been removed, use `mode` instead.
 
## Other Changes

- Don't need set `allowSyntheticDefaultImports` when using in TypeScript.
- We removed `react@0.14` and `react@15` from `peerDependencies`, since we may use the new features only exists in React 16 in the future.
- Fully es module support, if you are using webpack 3, you can set `babel-import-plugin`'s `libraryDirectory` to `es` to enable tree shaking .

**Comment by andriijas** [comment]
Great work! already using beta 8 in production 😎

**Comment by grunmin** [comment]
> Select.Option's value can be number in single or multiple mode.

Thanks, it troubles me for a long time.

**Comment by lcoder** [comment]
6666,赶紧试一把🎉

**Comment by drcmda** [comment]
Congratulations! Ant design is such a good product!

@yesmeck 
> Removed global css style.

Does this mean we can stop using babel-plugin-import? Do components import their own styles?

**Comment by afc163** [comment]
Breaking Changes miss the reset style change. https://github.com/ant-design/ant-design/issues/4331#issuecomment-332523121

**Comment by afc163** [comment]
And no more LocaleProvider for English users (oppsite for chinese)

**Comment by PancakeLa** [comment]
666 期待已久

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7232

**Comment by TsuryKnox** [comment]
#8334

**Comment by afc163** [comment]
https://medium.com/ant-design/announcing-ant-design-3-0-70e3e65eca0c

Ant Design 3.0 released now! 🎉 🎉 🎉

**Comment by antonmedv** [comment]
What do we need `Form.createFormField`? What's purpose of?

**Comment by lcoder** [comment]
问下全局样式冲突怎么处理，antd给的方案是不是就是自己覆盖？
