### ISSUE TITLE
Considering using style-resources-loader to customize theme

### ISSUE THREAD

**Issue by yenshih** [ant-design/ant-design#8234]
### What problem does this feature solve?
I'd like to customize theme with `modifyVars` option in less-loader at first. However, I found it impossible to enable HMR when I change my theme files, since they're not dependencies in webpack.

Inspired by @Justineo, I have wrote a [style-resources-loader](https://github.com/yenshih/style-resources-loader) to solve this problem.

It just simply adds our customized theme files to webpack dependencies and inject all these variables into original less files provided by ant-design.

It works great in my project.

### What does the proposed API look like?
I was wondering if we could revise the [Customize Theme](https://ant.design/docs/react/customize-theme) documentation and make ant-design better. 

Thanks.

**Comment by yesmeck** [comment]
Haha, I wrote a same purpose plugin https://github.com/yesmeck/webpack-less-theme-plugin which is more simple to use. But I think the current config is simple enough, so I's like keep it as it is. Thanks anyway.
