### ISSUE TITLE
Broken submenu width

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8236]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/507615/33000149-49059240-cde1-11e7-9380-eb20089bac2b.png">

antd-3.0

**Comment by benjycui** [comment]
当时吧那个 display: inline-block 去掉好像就是为了修复这个问题。

**Comment by benjycui** [comment]
> 当时吧那个 display: inline-block 去掉好像就是为了修复这个问题。

确认了，就是为了修复这个问题。
