### ISSUE TITLE
Progress component can not display well in table

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design#8239]
### Version
2.13.10

### Environment
OS: macOS High Sierra  
browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/kennylbj/pen/KyveQq?editors=0011](https://codepen.io/kennylbj/pen/KyveQq?editors=0011)

### Steps to reproduce
Render ```Progress``` component in table

### What is expected?
Display ```Progress``` component in one line.

### What is actually happening?
The percentage text of ```Progress``` component is broke up into two lines if the percentage value is larger than 9.
![image](https://user-images.githubusercontent.com/6435874/33003258-2cf1d300-cd7f-11e7-9716-27c3b4d1e9fa.png)

**Comment by yesmeck** [comment]
For now, you can set a custom class name on the Progress and set `work-break` to `normal`.

```javascript
<Progress className="my-progress" percent={progress} status='active' />
```

```css
.my-progress {
  word-break: normal;  
}
```

**Comment by kennylbj** [comment]
@yesmeck Problem solved, thx. 
Waiting for official fix anyway.

**Comment by yesmeck** [comment]
I'm afraid this issue won't be fixed, because table is agnostic of what you render to the cell. Maybe we  can add a `wordBreak` option to the `column`,  I'm not sure.

**Comment by kennylbj** [comment]
You are right.  IMO, however, adding ```Progress``` with additional styles in order to work fine with table is kind of odd.

**Comment by yesmeck** [comment]
Added `word-break: normal;` as progress's default style.
