### ISSUE TITLE
In the case of LAN, there is no Internet connection. All icons are abnormal

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design#8241]
### Version
2.13.10

### Environment
Win10 & Chrome 62 & LAN without Internet

### Reproduction link
[https://codepen.io/tomgao365/pen/NwyGQj](https://codepen.io/tomgao365/pen/NwyGQj)

### Steps to reproduce
1) Download the lastest antd project;
2) Run npm install && npm start
3) Visit http://localhost:8001/components/icon-cn/ , all icons are abnormal

### What is expected?
All icons are normal without internet;

### What is actually happening?
All icons are abnormal

---
Some government programs do not allow Internet access

**Comment by yesmeck** [comment]
See https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
