### ISSUE TITLE
Broken highlighting of Menu.Item in Layout.Sider

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#8242]
### Version
3.0.0-rc.1

### Environment
Windows 10.0.16299.64 & Chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/hansnow/pen/gXvavO?&editors=001](https://codepen.io/hansnow/pen/gXvavO?&editors=001)

### Steps to reproduce
open the codepen link.
all code is copied from [this demo](http://beta.ant.design/components/layout-cn/#components-layout-demo-side), and the following lib's version are reset.
* react@16
* antd@next

### What is expected?
Proper highlighting like this.
![image](https://user-images.githubusercontent.com/4365899/33010096-2966ab08-ce14-11e7-8f6a-d274fd0dac4c.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/4365899/33010063-0d4ca8dc-ce14-11e7-9578-67418b562d66.png)

---
Wonder why it works fine in [demo](http://beta.ant.design/components/layout-cn/#components-layout-demo-side)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/8e6e91b9328d82a65a21abed6d790fabb5d147b0
