### ISSUE TITLE
 has-feedback would not vertical align on the Form component when Input size set to "default" / "small"

### ISSUE THREAD

**Issue by syssam** [ant-design/ant-design#8243]
### Version
2.13.10

### Environment
--

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
```
<FormItem hasFeedback>
          {getFieldDecorator('userName', {
            rules: [{ required: true, message: 'Please input your username!' }],
          })(
            <Input size="default />} placeholder="Username" />
          )}
</FormItem>
```

### What is expected?
has-feedback icon follows the input component vertical align middle when I set the input size to "defalut" / "small"

### What is actually happening?
has-feedback icon follows the input component vertical align middle only working when I set the input size to "large"

**Comment by ddcat1115** [comment]
Works fine in my demo... 

<img width="376" alt="2017-11-20 5 38 52" src="https://user-images.githubusercontent.com/7017767/33011748-d5f8b9ba-ce19-11e7-82cb-23f14e054315.png">

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by syssam** [comment]
It's fine. It's my problem.
Please close this issue.

**Comment by syssam** [comment]
now I found out the problem because I have using config-overrides.
Please follow these setting.
@input-height-sm = 28
@input-height-base = 35
@input-height-lg = 50
Then you can see the problem.

**Comment by ddcat1115** [comment]
I reproduced it...

**Comment by syssam** [comment]
Yes, you look like find.
Here is my screen. you could see has-feedback is using @input-height-lg(49px), but .ant-input int height 35px, so it case this problem.

<img width="1164" alt="2017-11-21 19 20 59" src="https://user-images.githubusercontent.com/20774834/33069963-3e1a3d52-cef1-11e7-880c-311eb3aa198f.png">

**Comment by syssam** [comment]
I have a latest discover, you may change @form-component-height to @input-height-base, then you will see the problem, or you can using Input addonBefore(not surely)

**Comment by ddcat1115** [comment]
I see... Using @input-height-lg is OK, but someting wrong with the Input addon

**Comment by syssam** [comment]
In my opinion, I think it has-feedback should be follow the input line height even any size.

you fell fine when not using "input addon", however, "has-feedback" has different margin with "input field" on the different size. Do u?
