### ISSUE TITLE
The item can't drag  to the bottom in tree-component

### ISSUE THREAD

**Issue by suxiaoxin** [ant-design/ant-design#8246]
### Version
2.13.10

### Environment
chrome

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
Open the site：https://ant.design/components/tree-cn/， Move to drag demo

i want to drag the item to the bottom, but  it can not work normally

![image](https://user-images.githubusercontent.com/17695103/33013004-2a0f1976-cda8-11e7-9cf9-56bbebb4073f.png)

### What is expected?
drag the item to the bottom

### What is actually happening?
i want to drag the item to the bottom, but  it can not work normally

**Comment by yesmeck** [comment]
Fixed, thanks for reporting.
