### ISSUE TITLE
Add [width] to Table[rowSelection]

### ISSUE THREAD

**Issue by hedylow** [ant-design/ant-design#8247]
### What problem does this feature solve?
客户需要能调整table的selection宽度

### What does the proposed API look like?
使用less方式自定义列表选择框宽度

**Comment by yesmeck** [comment]
`rowSelection` 可以加个 `width`，@hedylow 要不要来个 PR。

**Comment by yesmeck** [comment]
@ant-design-bot Translate plz.

**Comment by afc163** [comment]
能自动翻译么
