### ISSUE TITLE
ant-demo  build出错

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#825]
build出错。错误日志见附件：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\bg204936\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.3.0
3 info using node@v4.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild antd-demo@1.0.0
6 info build antd-demo@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info antd-demo@1.0.0 Failed to exec build script
9 verbose stack Error: antd-demo@1.0.0 build: `rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\bg204936\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:223:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\bg204936\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid antd-demo@1.0.0
11 verbose cwd E:\ltcrm\trunk\client\admin
12 error Windows_NT 6.1.7601
13 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bg204936\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.0.0
15 error npm  v3.3.0
16 error code ELIFECYCLE
17 error antd-demo@1.0.0 build: `rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/`
17 error Exit status 1
18 error Failed at the antd-demo@1.0.0 build script 'rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/'.
18 error This is most likely a problem with the antd-demo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/
18 error You can get their info via:
18 error     npm owner ls antd-demo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by azl397985856** [comment]
脚本如下：
 "build": "rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/"

**Comment by afc163** [comment]
Try reinstall antd-init@0.6.x .

And read the damn doc here: https://github.com/ant-design/antd-init#faq

**Comment by benjycui** [comment]
@azl397985856 建议在任何开源项目开 issue 之前，都要看下对应的 [CONTRIBUTING](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)。

不然你会经常见到 RTFD STFW
