### ISSUE TITLE
Anchor: The page would blink first and then scroll to the right position after clicked in safari

### ISSUE THREAD

**Issue by haoranliu1220** [ant-design/ant-design#8250]
### Version
2.13.10

### Environment
Safari 9.1.1

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/anchor](https://github.com/ant-design/ant-design/tree/master/components/anchor)

### Steps to reproduce
Click on Anchor Link, the page would blink first and then scroll to the right position 

### What is expected?
Should work smoothly as Chrome and FireFox

### What is actually happening?
Would blink

**Comment by benjycui** [comment]
> Safari 9.1.1

See: https://github.com/ant-design/ant-design#environment-support

**Comment by benjycui** [comment]
I cannot re-produce this in Safari 11
