### ISSUE TITLE
TS2694: Namespace 'React' has no exported member 'InputHTMLAttributes'.

### ISSUE THREAD

**Issue by SenvenQi** [ant-design/ant-design#8251]
提示我没有导出这个inputHtmlAttributes    在我使用material-ui 的时候  

这是我的版本  
{
    "@types/material-ui": "^0.17.16",
    "@types/react": "15.0.35",
    "@types/react-dom": "15.5.1"
}

**Comment by benjycui** [comment]
Are you kidding? Please file this issue in material-ui's repo, thanks.
