### ISSUE TITLE
Upload组件loading和disabled同时使用，disabled失效

### ISSUE THREAD

**Issue by superlee9527** [ant-design/ant-design#8255]
### Version
2.12.8

### Environment
Windows, Chrome 62.0.3202.94 64bit

### Reproduction link
[https://codepen.io/anon/pen/xPYMor?editors=0010](https://codepen.io/anon/pen/xPYMor?editors=0010)

### Steps to reproduce
Clicking the button open a file dialog even though it is loading and disabled.

### What is expected?
Do not show the file dialog.

### What is actually happening?
Show file dialog.

**Comment by ddcat1115** [comment]
`disabled` also should be added on the `Upload`, please check the [API](https://ant.design/components/upload-cn/#API)
