### ISSUE TITLE
antd3.0版本List增加onChange方法

### ISSUE THREAD

**Issue by DiroKate** [ant-design/ant-design#8256]
### What problem does this feature solve?
解决翻页，过滤，排序的问题。里面已经有了pagination，但是没有相应的onChange进行翻页

### What does the proposed API look like?
onChange?: (pagination: PaginationProps | boolean, filters: string[], sorter: Object) => any;

**Comment by viztor** [comment]
What problem does this feature solve?

List will react to (pagination, sorter, filter) change.

What does the proposed API look like?

onChange?: (pagination: PaginationProps | boolean, filters: string[], sorter: Object) => any;

**Comment by nikogu** [comment]
@DiroKate List `pagination` property has `onChange` function, you can use it, it's not necessary to add onChange to List. http://beta.ant.design/components/pagination/#API

**Comment by DiroKate** [comment]
what about filter and the sorter?

**Comment by nikogu** [comment]
> what about filter and the sorter?

filter & sorter you can change `dataSource` by your self, u hold the opportunity.

**Comment by andriijas** [comment]
there is already filtering, sorting and pagination in Table, i think code can be reused because logic and api should be same, just rendering output is list instead of table row.  The code is already there in Table, just need to make it common.

**Comment by FourEyebrowXiake** [comment]
this is my code :
javascript```
onst pagination = {
            pageSize: 2,
            current: 1,
            total: listData.length,
            onChange: ((e) => { 
                
            }),
        };
```
I want to achieve the function of turning page.
 how to change the value of current?

I set the pageSize value to 2, but  list shows all items in first page. why?
@DiroKate

**Comment by DiroKate** [comment]
@FourEyebrowXiake you should achieve the onChange

**Comment by eruca** [comment]
@DiroKate my problem is like @FourEyebrowXiake 
the pageSize is 2, but first page show all, the pagination is not work, I make the component controlled, but not resolve the problem.

**Comment by eruca** [comment]
your meaning is to control the dataSource to render?

**Comment by nikogu** [comment]
@eruca  @FourEyebrowXiake  list just a ui, it bring a huge flexibility.

In your condition, all you need to do it is just control your `dataSource`, you can update your `dataSource` depend on pagination.

here it is a example: https://preview.pro.ant.design/#/list/basic-list
code: https://github.com/ant-design/ant-design-pro/blob/master/src/routes/List/BasicList.js#L124
