### ISSUE TITLE
Tooltip 不支持 defaultVisible

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#8257]
https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L70

https://github.com/react-component/tooltip#props

https://riddle.alibaba-inc.com/riddles/f3021ec2?mode=jsx

**Comment by afc163** [comment]
defaultVisible 意义不大，visible 就够了。

**Comment by silentcloud** [comment]
@afc163 我的业务场景里需要 defaultVisible，不然要自己在 componentWillReceiveProps 里去处理 state

**Comment by afc163** [comment]
👌
