### ISSUE TITLE
Modal里的表格，固定列的高度和普通列的高度不一致，去掉Modal则显示正常

### ISSUE THREAD

**Issue by sealzrt** [ant-design/ant-design#8263]
### Version
2.13.9

### Environment
mac, chrome 62.0.3202.94, react 15.6.2

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Modal里的表格，固定列的高度和普通列的高度不一致，去掉Modal则高度一致

### What is expected?
高度显示一致

### What is actually happening?
Modal里的表格，固定列的高度和普通列的高度不一致

**Comment by sealzrt** [comment]
![cuowei](https://user-images.githubusercontent.com/6469925/33063925-0b7a98a4-cedf-11e7-9f61-a14297a5ead5.jpeg)

**Comment by sealzrt** [comment]
![zhengchang](https://user-images.githubusercontent.com/6469925/33063948-1ac34edc-cedf-11e7-9c60-c77e32fa86e3.jpeg)

**Comment by sealzrt** [comment]
有一半的几率 固定列的高度 显示不对，如图1
有时候打开显示正常，如 图2

**Comment by ddcat1115** [comment]
You should fork the demo in the codepen, then edit and save, and provide us your own link.
