### ISSUE TITLE
建议与immutable兼容

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design#8264]
### What problem does this feature solve?
immutable 有助于 app 性能，但是 antd 的组件不兼容 Immutable 的数据格式

### What does the proposed API look like?
希望能够兼容 immutable ，例如支持传入 object 的地方希望也支持传入 Map, 支持传入 array 的地方也支持传入 List

**Comment by yesmeck** [comment]
暂时不会考虑这个，传的时候自己转换下吧。谢谢建议。
