### ISSUE TITLE
Use codesandbox as reproduce sample

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8265]
It is more accurate and fast.

Replace all links of codepen in antd@3.0.

**Comment by yesmeck** [comment]
https://github.com/CompuIves/codesandbox-client/issues/332
https://github.com/CompuIves/codesandbox-client/issues/263

**Comment by yesmeck** [comment]
https://u.ant.design/codesandbox-repro

**Comment by Airkro** [comment]
but why not use it in doc ?

**Comment by yesmeck** [comment]
@Airkro https://github.com/ant-design/ant-design/issues/8535
