### ISSUE TITLE
DatePicker 和 TimerPicker 如何设置指定时区

### ISSUE THREAD

**Issue by chowsource** [ant-design/ant-design#8267]
### What problem does this feature solve?
页面里的DatePicker 和 TimerPicker 比如我想指定为印度的时区或者英国美国的时区,而不是显示我本机时间,因为时区不同,比如点击"今天"应该会不同时区不一样的日期,而不是一直是我本机的日期,怎么设置,我看了以前很早的版本local配置里有个timezone的配置项,2.13的版本好像没有这个属性配置了.是现在没有这个功能了吗?

### What does the proposed API look like?
设置timezone,组件就按指定时区的时间显示

**Comment by ddcat1115** [comment]
try [moment utcOffset](http://momentjs.cn/docs/#/manipulating/utc-offset/)

**Comment by chowsource** [comment]
@ddcat1115 我知道moment utcoffset,我这里说的是组件本身比点击'此刻',他显示的是本机的此刻时间,而不是指定时区时间.  moment不是这里的需求.
![image](https://user-images.githubusercontent.com/5119971/33108165-ce0e51a8-cf75-11e7-88dc-eeed51de3484.png)

![image](https://user-images.githubusercontent.com/5119971/33108175-deb0787e-cf75-11e7-9b79-f006290d3970.png)
比如这两个截图的 Today,假如我现在本机是北京东八8区时区,现在如果是23:20,那么如果是东9区,那么已经是第二天了,这个时候组件点击today日期就达不到指定时区的日期. 点击Now原理也一样,本机是东8区,假如此刻是8:36,那么指定东9区就应该是9:36,而点击now始终是按照本机时区8:36,不能指定不同时区,而自动显示不同时区此刻时间.

**Comment by yesmeck** [comment]
暂时不支持单独指定时区，需要通过 `LocalProvider` 设置 locale，参考 https://ant.design/components/date-picker/#API

**Comment by yesmeck** [comment]
https://github.com/moment/moment/issues/3433

**Comment by babulin** [comment]
我用的版本是Ant Design Vue 1.7.8 。使用
<a-date-picker v-model="create_time" show-time placeholder="选择时间" @change="onChange" />
我是这样来更改时区的
```
methods:{
   onChange (e, dateString) {
      e.tz('America/New_York').format('YYYY-MM-DD HH:mm:ss')
    }
}
```
这样，点击此刻，时间就会按时区更改，不影响单独选择时间
