### ISSUE TITLE
Select dropdown moves when scrolling

### ISSUE THREAD

**Issue by Sokal21** [ant-design/ant-design#8268]
### Version
2.13.10

### Environment
browser version

### Reproduction link
[https://codepen.io/anon/pen/XzEdgJ](https://codepen.io/anon/pen/XzEdgJ)

### Steps to reproduce
Open the modal by clicking on show button, open the drop down and resize the display view till you can scroll on the view with the menu open, then scroll down or up.

### What is expected?
The drop down options should stay at the bottom of the menu when scrolling

### What is actually happening?
The drop down options are staying in a fixed position of the screen when scrolling up or down

**Comment by ddcat1115** [comment]
You can use `getPopupContainer` to change the parent node which the selector should be rendered to. [demo](https://codepen.io/afc163/pen/zEjNOy?editors=0010)

**Comment by jyothibetabulls** [comment]
Hi,
This is Ashok.
             I am new for ant design.when i am designing the template i got some designing issues. ie i am designing select box dropdown options will be in fixed position.please check the below screen. i hope you understand my problem. 
![s 1](https://user-images.githubusercontent.com/31284711/38538424-68faf236-3cb1-11e8-8515-1f667e9d6c61.PNG)
Thanks
Ashok

**Comment by justinlazaro-ubidy** [comment]
is this already fix?

**Comment by alexcambose** [comment]
Is this issue fixed ?

**Comment by Driggs88** [comment]
add this Select Props **getPopupContainer={trigger => trigger.parentNode}**

**Comment by raymondjacobson** [comment]
fwiw -- make sure your parent is set (as Driggs calls out) and its position=relative.

**Comment by coskunuyar** [comment]
That solves the problem but causes rendering problem on internet explorer 11. Is there any one who has a solution ? Maybe you can say that it is because of console.log usage in app that causes this kind of problems but I used polyfill for console.log no effect.

**Comment by bishnu476** [comment]
> The drop down options are staying in a fixed position of the screen when scrolling up or down

Use getPopupContainer={() => document.getElementById('id_of_dropdown_container') || document.body} 
and in css file place
 #id_of_dropdown_container .ant-dropdown-placement-topCenter {
  position: fixed;
}

**Comment by asbansal** [comment]
<Select dropdownStyle = {{ position: "fixed" }}>
will fix the issue. I had the same problem

**Comment by rahuls360** [comment]
If you are trying to fix this globally read about [https://ant.design/components/config-provider/](https://ant.design/components/config-provider/)

Found the solution [#3487](https://github.com/ant-design/ant-design/issues/3487) by @afc163 
Be cautious. You may need to recheck if your styling works as expected after the change. It broke few styles for me.

**Comment by harirahman** [comment]
```
 <div>
          <Select
            defaultValue="Select"
            style={{ width: 120 }}
            getPopupContainer={trigger => trigger.parentNode}
          >
            {plants.items &&
              plants.items.map((plant) => (
                <option key={plant.plant_id} value={plant.plant_id}>
                  {plant.plant_name}
                </option>
              ))}
          </Select>
          </div>
```

**Comment by chrkglobal** [comment]
what about search suggestion box
![image](https://user-images.githubusercontent.com/3340263/119497742-8930b180-bd82-11eb-885b-94eff5ce89ab.png)

**Comment by chrkglobal** [comment]
plz help me

**Comment by yoyo837** [comment]
> plz help me

What's your problem? Feel free to open a new issue for that.

**Comment by raghurambachu** [comment]
For anyone still stuck at this and are using it along with Typescript 
add this prop to Select

getPopupContainer={(triggerNode: HTMLElement) => triggerNode.parentNode as HTMLElement }

**Comment by hoatep** [comment]
I have same issue with <Dropdown/>. I tried  getPopupContainer={trigger => trigger.parentNode} but not work. Any solution? pls

**Comment by SeniyaD** [comment]
In case someone is still struggling, I just added the 
 ```
getPopupContainer={(triggerNode: HTMLElement) =>
                (triggerNode?.parentNode as HTMLElement) || document.body
              }
```
to `ConfigProvider`. But have doubts whether is this going to affect only to the `Select` components.
![image](https://user-images.githubusercontent.com/92571977/154403700-f10345fa-8e86-404a-a24b-b593e632f299.png)

**Comment by jonnathanc765** [comment]
Hello! Add the trigger node does not work, any solution?

**Comment by jonnathanc765** [comment]
I used de config provider and this works for me!

**Comment by Sansith** [comment]
In case someone is still struggling, I just added the 
 ```
getPopupContainer={(triggerNode: HTMLElement) =>
                (triggerNode?.parentNode as HTMLElement) || document.body
              }
```
to `ConfigProvider` and this fixed all the Select element issues. But have doubts whether is this going to affect only to the `Select` components.
![image](https://user-images.githubusercontent.com/92571977/154403700-f10345fa-8e86-404a-a24b-b593e632f299.png)

**Comment by Sharif052** [comment]
@Sansith your solution work for me. thank you so much.
if you explain how it works. it would be helpful for better understanding.

**Comment by anand-cubyts** [comment]
> <Select dropdownStyle = {{ position: "fixed" }}> will fix the issue. I had the same problem

This worked for me, thank you! :)

**Comment by lucky-lore** [comment]
> I have same issue with Dropdown . I tried getPopupContainer={trigger => trigger.parentNode} but not work. Any solution? pls

Same here. Any resolutions on this one?

**Comment by neeerajtk** [comment]
> 

Adding the prop `getPopupContainer={(trigger) => trigger.parentNode}` to `Dropdown` solved the issue for me.

<img width="420" alt="Screenshot 2022-09-02 at 5 20 23 PM" src="https://user-images.githubusercontent.com/29975820/188135723-ff1ed8e5-bd5e-4a5e-ba21-db72f9825c35.png">

antd version: `4.21.4`

**Comment by neeerajtk** [comment]
> > I have same issue with Dropdown . I tried getPopupContainer={trigger => trigger.parentNode} but not work. Any solution? pls
> 
> Same here. Any resolutions on this one?

> 

Adding the prop `getPopupContainer={(trigger) => trigger.parentNode}` to `Dropdown` solved the issue for me.

<img width="420" alt="Screenshot 2022-09-02 at 5 20 23 PM" src="https://user-images.githubusercontent.com/29975820/188135723-ff1ed8e5-bd5e-4a5e-ba21-db72f9825c35.png">

antd version: `4.21.4`

**Comment by filipp-kononskiy** [comment]
> add this Select Props **getPopupContainer={trigger => trigger.parentNode}**

Thank you!

**Comment by gamble4846** [comment]
I've created a work around using basic JavaScript

app.component.html - 
```
<div class="inner-content" (scroll)="SetupOnScroll($event,routerOutletContainer)" #routerOutletContainer>
     <router-outlet></router-outlet>
</div>
```


app.component.ts - 

```
SetupOnScroll(event:any,routerOutletContainer:any){
  let overlaypanes:any = document.getElementsByClassName("cdk-overlay-pane");
  let amountScrolled = this.lastScrollTop - routerOutletContainer.scrollTop;
  this.lastScrollTop = routerOutletContainer.scrollTop;
  if(overlaypanes.length > 0){
    for (let index = 0; index < overlaypanes.length; index++) {
      const overlaypane = overlaypanes[index];
      const paneTop = overlaypane.style.top;
      const paneBottom = overlaypane.style.bottom;
      if(paneTop != 0){
        overlaypane.style.top = Number(paneTop.replace("px", "")) + amountScrolled +"px";
      }
      if(paneBottom != 0){
        overlaypane.style.bottom = Number(paneBottom.replace("px", "")) + (amountScrolled * -1) +"px";
      }
    }
  }
}
```

This would update the top or bottom of the currently opened `cdk-overlay-pane` according to the scroll value

**Comment by greenyboiz** [comment]
> In case someone is still struggling, I just added the
> 
> ```
> getPopupContainer={(triggerNode: HTMLElement) =>
>                (triggerNode?.parentNode as HTMLElement) || document.body
>              }
> ```
> 
> to `ConfigProvider` and this fixed all the Select element issues. But have doubts whether is this going to affect only to the `Select` components. ![image](https://user-images.githubusercontent.com/92571977/154403700-f10345fa-8e86-404a-a24b-b593e632f299.png)

Thank you!
![Screenshot 2022-12-20 183113](https://user-images.githubusercontent.com/87219140/208657066-87378801-46c4-434f-9033-8b474d46d566.png)

Anyway, in Vue 3, I didn't get document.body, it shows a fail like an image above. Any idea that could help me out? Thank you

**Comment by adityabarvegupshup** [comment]
getPopupContainer={(trigger) => trigger.parentNode
This is causing infinite rendering.

**Comment by Torexxx** [comment]
Please help, I have a SplitPane component which contains two parts: sidePanel and mainPanel.
I passed getPopupContainer={(triggerNode) => (triggerNode?.parentNode as HTMLElement)} to Dropdown  props so now menu is scrolling.
 
 The problem is that my modal menu is cut by second panel.  Is it possible to fix it somehow?
 
 1) be able to remain first menu scrollable
 2) make it over the second panel
 
![image](https://user-images.githubusercontent.com/60657123/231947449-898086a9-46a3-45e9-93dd-2f721386bd5b.png)

**Comment by bibinantony98** [comment]
This issue is fixed in antd 5x versions please check

**Comment by Torexxx** [comment]
"antd": "^5.4.2",
 
 Still have the same issue

**Comment by bibinantony98** [comment]
Check antd doc (their example works perfectly, ie. i checked by controlling height in their example through inspect), default select with no props of 5x version work perfectly for me, please don't provide any props to control dropdown as child

**Comment by Torexxx** [comment]
I don't have a Select. I have Dropdown like this:

![image](https://github.com/ant-design/ant-design/assets/60657123/e2abbbfb-8665-4b59-954e-981db2b3f6ff)

**Comment by bibinantony98** [comment]
It works in the dropdown as well, I hope the placement in your dropdown causes the issue checked it in the doc by editing their example through inspect

https://github.com/ant-design/ant-design/assets/48233705/b1167b0c-2a8c-4fe7-b63b-f3c35303075b

**Comment by agageldidurdyyev** [comment]
If doesn't work any solution, please try this

`const [key, setKey] = useState(0);

useEffect(() => {
  const handleScroll = () => {
    setKey(prevKey => prevKey + 1);
  };

  window.addEventListener('scroll', handleScroll);

  return () => {
    window.removeEventListener('scroll', handleScroll);
  };
}, []);

<Select {...rest} key={key} />`

**Comment by agageldidurdyyev** [comment]
If any of the solution doesn't work, please try this:

```jsx
const [key, setKey] = useState(0);

useEffect(() => {
  const handleScroll = () => {
    setKey(prevKey => prevKey + 1);
  };

  window.addEventListener('scroll', handleScroll);

  return () => {
    window.removeEventListener('scroll', handleScroll);
  };
}, []);

<Select {...rest} key={key} />
```

**Comment by mohamedali69** [comment]
> trigger

did you find a solution ?

**Comment by mohamedali69** [comment]
> ```js
> key={key}
> ```



> If any of the solution doesn't work, please try this:
> 
> ```js
> const [key, setKey] = useState(0);
> 
> useEffect(() => {
>   const handleScroll = () => {
>     setKey(prevKey => prevKey + 1);
>   };
> 
>   window.addEventListener('scroll', handleScroll);
> 
>   return () => {
>     window.removeEventListener('scroll', handleScroll);
>   };
> }, []);
> 
> <Select {...rest} key={key} />
> ```

For me it still not working even when i add the useEffect, is there any solution to fix this issue

**Comment by ae-mhd** [comment]
still  have the issue that I cant scroll down and its stick on the top, im using Antd 5.15.2 
![logo](https://github.com/ant-design/ant-design/assets/55931050/eb88d732-72e8-4ea7-81d4-5ac9ba584110)

![image](https://github.com/ant-design/ant-design/assets/55931050/72a0c8e8-fcd4-4e19-9436-b4287fdb9930)

**Comment by UmmeZaiba-i** [comment]
How to solve this?

The dropdown also scrolls when the table scrolls, so how to resolve it.
We could make the table not scrollable when we open the dropdown

![image](https://github.com/user-attachments/assets/e5252716-1f45-4f58-91ca-7c0997d07aa1)

**Comment by LilitVardanyan1** [comment]
> const [key, setKey] = useState(0);
> 
> useEffect(() => {
>   const handleScroll = () => {
>     setKey(prevKey => prevKey + 1);
>   };
> 
>   window.addEventListener('scroll', handleScroll);
> 
>   return () => {
>     window.removeEventListener('scroll', handleScroll);
>   };
> }, []);

I use this and this works for me
