### ISSUE TITLE
adding validation errors from server 

### ISSUE THREAD

**Issue by saeidalidadi** [ant-design/ant-design#8271]
### Version
2.12.2

### Environment
Development

### Reproduction link
[https://codepen.io/Alidadi/pen/MOVezm](https://codepen.io/Alidadi/pen/MOVezm)

### Steps to reproduce
create a form, create a redux store, connect store to form, request the field, add validation error from response

### What is expected?
Show error for duplicate name filed

### What is actually happening?
Maximum call stack size exceeded

**Comment by yesmeck** [comment]
Don't call `setFields` in the `componentWillUpdate`,  this leads to a infinite loop.

**Comment by yesmeck** [comment]
Don't call `setFields` in the `componentWillUpdate`, this will lead to a infinite loop.

**Comment by benjycui** [comment]
Try `mapPropsToFields`, you can consult the documentation.

**Comment by Dev-Dipesh** [comment]
@saeidalidadi did you find any solution? I'm also running into the same problem.

**Comment by jasnoponjatno** [comment]
@Dev-Dipesh did you found any solution?

**Comment by hungdev** [comment]
did you found any solution? @jasnoponjatno  @Dev-Dipesh

**Comment by hungdev** [comment]
i found out the solution: https://stackoverflow.com/a/47261247/5826956

**Comment by sandalwoodbox** [comment]
It turns out antd uses rc-fields-form under the hood, which documents how to set validation errors here: https://field-form-react-component.vercel.app/demo/reset

**Comment by anaselbahrawy** [comment]
```
import React, { useState } from 'react';
import { Form, Input } from 'antd';

const YourComponent = () => {
    const [errorFields, setErrorFields] = useState({});

    // Assuming error is an object containing data
    const handleError = (error) => {
        setErrorFields(error?.data?.errors || {});
    };

    return (
        <Form>
            <Form.Item
                name="name"
                label="Continents"
                help={errorFields?.name}
                validateStatus={errorFields?.name ? 'error' : ''}
                rules={[{ required: true, message: 'plz enter Continents' }]}
            >
                <Input placeholder="Continents" />
            </Form.Item>
        </Form>
    );
};

export default YourComponent;
```
