### ISSUE TITLE
RangePicker's  presetted ranges won't generate new value for new click.

### ISSUE THREAD

**Issue by Hsia1993** [ant-design/ant-design#8281]
### Version
2.13.10

### Environment
Google Chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/anon/pen/GOxzvM?editors=0010](https://codepen.io/anon/pen/GOxzvM?editors=0010)

### Steps to reproduce
please open the codepen link first then:
 1.  Open rangepicker then click recent two days , say you get a range` [2017-11-20 15:01:28,2017-11-22 15:01:28]`, that's awesome.
 2.  Wait for 5 sec or 1 hour then click again, you still get a range `[2017-11-20 15:01:28,2017-11-22 15:01:28]`, definitely wrong.

### What is expected?
Range value should be `[2017-11-20 15:01:33,2017-11-22 15:01:33]`.

### What is actually happening?
Range value still be the same with the old value 

---
By definition, the type of DatePickers ranges attribute is `{ range: string: moment[] }`, this is wrong cause current time is not a constant, it should be ` { range: string: () => moment []}`, then for every trigger you will always get the current time

**Comment by yesmeck** [comment]
Will release this weekend.

**Comment by topwood** [comment]
example on https://ant.design/components/date-picker-cn/ still has the problem, please update the example and show how to use the function

**Comment by yesmeck** [comment]
@topwood Could send a PR?

**Comment by topwood** [comment]
@yesmeck sorry, a say this because i do not know how to use it.
