### ISSUE TITLE
Select 下拉选择内容过长鼠标一上去不会显示全部

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8282]
### Version
2.13.10

### Environment
chrome

### Reproduction link
[https://codepen.io/anon/pen/GOxeKG?editors=001](https://codepen.io/anon/pen/GOxeKG?editors=001)

### Steps to reproduce
随便弄个select选择，选择项文本长度长一点超出选择框长度，这时候选择项目会显示省略号，但是鼠标一上去不会显示显示全部，之前是会的，title属性没了？

### What is expected?
鼠标移到选择项目会显示全部

### What is actually happening?
鼠标移动上去不会显示全部

**Comment by yesmeck** [comment]
You need set title on `Option` `<Option title="long text" />`

**Comment by aw6658913** [comment]
之前不是会自动判断？能不能跟之前一样默认渲染，因为下拉选择肯定会经常出现超出长度的情况的，每次都要设置有点麻烦

**Comment by yesmeck** [comment]
之前也没自动判断的，自动比较难判断 title 内容。

**Comment by WLyKan** [comment]
现在的最新版好像可以配置title，但是文档并没有说明。Option
![image](https://user-images.githubusercontent.com/2155093/94358228-0b70b500-00d2-11eb-8a88-d1e1123731db.png)
这个options配置，可以只配置value，如果配置了title，鼠标悬浮会显示title内容

**Comment by yoyo837** [comment]
@WLyKan  来帮忙修改一下文档？
