### ISSUE TITLE
antd 3.0 - Form didn't work with array data when editing value

### ISSUE THREAD

**Issue by jittuu** [ant-design/ant-design#8283]
### Version
3.0.0-rc.1

### Environment
chrome:  62.0.3202.94, 
react: 16.1.1, 

### Reproduction link
[https://codepen.io/anon/pen/XzZvEO?editors=0010](https://codepen.io/anon/pen/XzZvEO?editors=0010)

### Steps to reproduce
1. open in codepen
2. edit text box
3. click submit button
4. check console output

### What is expected?
form values should have edited value.

### What is actually happening?
form values are undefined.

---
It was working in version 2x. Here is working example (same code, different antd/react version). https://codepen.io/anon/pen/PORLvY?editors=0011

**Comment by afc163** [comment]
@yesmeck https://codepen.io/afc163/pen/qVowQz?editors=0010

3.0 has a unexpected rerender when edit input.

**Comment by yesmeck** [comment]
Will fix in next release, thanks for reporting.

**Comment by afc163** [comment]
Fixed in `3.0.0-rc.3`
