### ISSUE TITLE
ant design table 单列过滤变成多列过滤

### ISSUE THREAD

**Issue by bnerDY** [ant-design/ant-design#8284]
### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/master/components/table/demo/custom-filter-panel.md 
看了下现在已有的搜索过滤highlight仅仅只能作用在一个列上，能不能应用到多个列上

### What does the proposed API look like?
搜索的时候全列匹配，或者定义哪些列加入搜索匹配，而不是单一的

**Comment by ddcat1115** [comment]
你在上面那个例子的基础上，自己调整下 `onSearch` 的逻辑就能实现。但是目前的过滤触发器都是放在每列列头的，不适合用来完成多列的搜索过滤，建议你在 table 外部自己实现一个用来过滤的触发器，本质还是改变 table 的渲染数据

**Comment by ddcat1115** [comment]
这是使用问题，先close了，有问题再reopen~

**Comment by bnerDY** [comment]
@ddcat1115 我问题表达不对，其实是多个列表筛选之后，如果没有符合条件return null的时候会做一次重新渲染，这时候表格会样式丢失，有什么办法可以让它样式不崩么？
