### ISSUE TITLE
打包后 base.less和index.css同时存在

### ISSUE THREAD

**Issue by janjon** [ant-design/ant-design#8287]
### Version
2.13.10

### Environment
chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
.babelrc 文件中已经 配置
["import", {
"libraryName": "antd",
"style": true
}]

### What is expected?
只需要引入less文件

### What is actually happening?
但是还会引入index.css

**Comment by afc163** [comment]
Could you provide a re-producible repo?

**Comment by janjon** [comment]
我是从 antd 2.10.x 升级到 2.13.10 后出现的这问题 原来不会出现 index.css， 只有 base.less，我是想通过 package.json 的方式 覆盖一些 theme. 结果 base.less 已经引用到了, 但是 index.css出现了覆盖了 base.less

**Comment by wangtao0101** [comment]
@afc163 i just find i have the same problem version "2.13.8"

**Comment by afc163** [comment]
> Could you provide a re-producible **repository**?

**Comment by wangtao0101** [comment]
@afc163 i find that my problem  is caused by using a css version component based on antd.

**Comment by afc163** [comment]
Then no problems of us ~ 😃

**Comment by janjon** [comment]
@wangtao0101  Where can I see the CSS version of the configuration?. Can you give us some clues?
thank you

**Comment by janjon** [comment]
@wangtao0101  Which component introduces the CSS file?

**Comment by janjon** [comment]
ant-design-pro The problem after I introduced this

**Comment by wangtao0101** [comment]
@janjon my own component [react-form-antd](https://github.com/wangtao0101/react-form-antd), I have fixed the bug using different babelrc config [babelrc](https://github.com/wangtao0101/react-form-antd/blob/master/.babelrc) from production and development

**Comment by janjon** [comment]
How can you make ant-design-pro use Less files?
@afc163 @wangtao0101 thanks

**Comment by janjon** [comment]
@afc163 ant-design-pro 会使用 index.css
