### ISSUE TITLE
notification message 在2.13.10版本报错,我替换到3.0rc就不会报错

### ISSUE THREAD

**Issue by chowsource** [ant-design/ant-design#8289]
### Version
2.13.10

### Environment
mac,chrome62

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce
import { notification,message } from 'antd';//notification,message 两个在componentWillReceiveProps方法里使用会报错
componentWillReceiveProps(nextProps){
        if(nextProps.createId > 0 && nextProps.createId !== this.props.createId){
            notification.success({message:'Create success!'});//这行会报错(message同样会报错)换成,页面就空白了,但是当我antd换到3.0rc版本就不会报错
        }else if(nextProps.createId == -1 && nextProps.createId !== this.props.createId){
            notification.error({message:'Create failed!'});//这行会报错(message同样会报错),页面就空白了,但是当我antd换到3.0rc版本就不会报错
        };
    }

### What is expected?
期望是呼出提示信息

### What is actually happening?
报错了,页面也边空白了

---
///下面是报错的错误信息
Notification.js:138 Uncaught (in promise) TypeError: Cannot read property 'add' of null
    at Object.notice (http://localhost:8080/static/main.js:81236:20)
    at Object.notice [as open] (http://localhost:8080/static/main.js:26579:81)
    at Object.api.(anonymous function) [as success] (http://localhost:8080/static/main.js:26627:20)
    at MyComponent.componentWillReceiveProps (http://localhost:8080/static/main.js:86223:1748)
    at MyComponent.componentWillReceiveProps (http://localhost:8080/.tmp/dev-vendors.js:12577:30)
    at callComponentWillReceiveProps (http://localhost:8080/.tmp/dev-vendors.js:45938:14)
    at updateClassInstance (http://localhost:6075/.tmp/dev-vendors.js:46117:7)

**Comment by afc163** [comment]
We support React 16 in 3.x. https://github.com/ant-design/ant-design/issues/5377

**Comment by sosohime** [comment]
hey gays, if you want to use antd 2.x on react 16+
you can do this to make message and notification work normally
@afc163 偏右大佬有空解释一下原理么-。-
```
import { notification as antd_notification, message as antd_message } from 'antd';

export const notification = Object.entries(antd_notification).reduce((obj, [key, func]) => {
    return {
        ...obj,
        [key]: function () {
            setTimeout(() => {
                func(...arguments);
            }, 0);
        },
    };
}, {});

export const message = Object.entries(antd_message).reduce((obj, [key, func]) => {
    return {
        ...obj,
        [key]: function () {
            setTimeout(() => {
                func(...arguments);
            }, 0);
        },
    };
}, {});
```
