### ISSUE TITLE
tab 和 search 组件默认特别高，这是不是bug？

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design#8290]
### Version
2.12.8

### Environment
"react": "^15.6.1"

### Reproduction link
[http:// 懒得弄了](http:// 懒得弄了)

### Steps to reproduce
在页面上任意一个容器内引入 search 组件或者 tab 组件，这两个组件高度自动充满整个容器

### What is expected?
应该是收缩到最小高度啊

### What is actually happening?
高度充满整个容器

**Comment by afc163** [comment]
close for no reproduce
