### ISSUE TITLE
The function of additions and deletions

### ISSUE THREAD

**Issue by wjtGitHub** [ant-design/ant-design#8291]
### What problem does this feature solve?
The function that I can add and del tree's node can be used in the Tree.

### What does the proposed API look like?
```
<tree
   add="function"
   del="fun"
   update="fun">
```
tree componet's styles akin vscode's tree

**Comment by yesmeck** [comment]
啥意思？

**Comment by ddcat1115** [comment]
同不明白...

**Comment by wjtGitHub** [comment]
The function of additions and deletions in tree component.The function that I can add and del tree's node can be used in the Tree. @yesmeck @ddcat1115

**Comment by yesmeck** [comment]
Treat nodes as state. https://reactjs.org/docs/thinking-in-react.html

**Comment by wjtGitHub** [comment]
@yesmeck .I don't think the iusse is Usage.The iusse is feature.
![image](https://user-images.githubusercontent.com/17404628/33158104-149be280-d042-11e7-8f3c-349b7ec655e7.png)
like above.
I hope the Tree component support right click.I use the function can change data,or your component show the update and add function's button.

**Comment by yesmeck** [comment]
Right click example http://react-component.github.io/tree/examples/contextmenu.html

**Comment by wjtGitHub** [comment]
thank you very much @yesmeck

**Comment by wjtGitHub** [comment]
I'm sorry. I didn't look at the document carefully @yesmeck
