### ISSUE TITLE
Popover not closing on mobile

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#8296]
### Version
2.13.10

### Environment
iOS safari

### Reproduction link
[https://ant.design/components/popover/](https://ant.design/components/popover/)

### Steps to reproduce
click on a Popover, Tooltip or Dropdown component, from a mobile browser.

### What is expected?
the overlay opens, close it, either by clicking outside of it, or re-clicking on the original component 

### What is actually happening?
the overlay opens, but there is no way to close it, either by clicking outside, of it or re-clicking on the original component

**Comment by ddcat1115** [comment]
antd is basically desktop oriented, we won't make optimization for mobile. But you are welcome to give us a PR to improve the mobile experience~

**Comment by violabg** [comment]
I'm pretty sure it use to work on version prior to 2.13.10, maybe 2.13.8
