### ISSUE TITLE
上传组件必须带附加参数点击确定之后才能上传，而不是直接上传到后台

### ISSUE THREAD

**Issue by xiamidaxia** [ant-design/ant-design#830]
![image](https://cloud.githubusercontent.com/assets/4162271/12169259/5701b8da-b572-11e5-9a38-a5084c02f993.png)

如题，因为安全限制 ～～

**Comment by afc163** [comment]
https://github.com/react-component/upload/issues/17

**Comment by JonneyYan** [comment]
Upload的ajax只是一个可选的上传方式，你可以通过beforeUpload方法取消上传，并将file保存在state中，然后通过你的form上传文件和参数

**Comment by afc163** [comment]
@JonneyYan :+1:

**Comment by zhaotoday** [comment]
beforeUpload 中返回的 file 怎么取到文件流，我用 FileReader 不行。

**Comment by ChenLi0830** [comment]
@zhaotoday file是beforeUpload的argument。直接用reader.readAsDataURL(file)即可。
```
                         <Upload
                            action="cfs/files/zenApps/"
                            listType="picture-card"
                            fileList={this.state.fileList}
                            beforeUpload={this.handleLogoUpload}
                        >
                            <Icon type="plus" />
                            <div className="ant-upload-text">上传照片</div>
                        </Upload>

handleLogoUpload(logoFile){
        let reader = new FileReader();
        reader.readAsDataURL(logoFile);

        reader.onloadend = function () {
            this.setState({
                fileList:[{
                    uid: -1,
                    name: 'xxx.png',
                    status: 'done',
                    url: reader.result
                }]
            });
        }.bind(this);

        //Prevent file uploading
        return false;
    },
```

**Comment by lcc19941214** [comment]
我的做法是，给checkbox的onChange加一个回调，设置父组件的state改变，然后beforeUpload的时候去取得这个state然后比较，如果当前state为空则return false中断上传。

我当时遇到的情况是，直接在beforeUpload里设置setState如果不加状态的比对，会导致组件刷新然后filelist清空；而且多个文件上传的时候重复的在beforeUpload里setState会有一定的延迟。

**Comment by huangyingjie** [comment]
不如针对上传时机专门做一个API，免得新用户每次都有疑问。
比如：
````js
uploadOnSelect: true代表选中文件立即上传，默认为true；给用户设为false的明确途径。
startUpload: true代表开始上传，默认false
````

**Comment by BeckyWang** [comment]
如果通过beforeUpload方法取消上传，那么进度条，上传状态这些是不是也要自己重新写？ @JonneyYan

**Comment by zjh65204** [comment]
非常有用！正在做一个表单中上传TXT文件获得流的功能！感谢感谢！

**Comment by nicelj** [comment]
问一下怎么通过form来进行upload的上传？

**Comment by Restry** [comment]
ie9不支持beforeUpload ,那怎样手动上传???? @afc163

**Comment by afc163** [comment]
无法支持，请使用原生 `<input type="file />`。

**Comment by Restry** [comment]
@afc163  谢谢你的回复,  使用原生 input的话可以和antd 的form 搭配一起吗?   比如:
{getFieldDecorator('upload', {
            valuePropName: 'fileList',
            getValueFromEvent: this.normFile,
          })(
            <input type="file" />
          )}
还是只能使用原生的form表单 .

**Comment by Feel-Joy** [comment]
感谢此问题的提问者和解答者，解决了我当前遇到的一个文件上传的问题，感谢各位~

**Comment by suifengpiao14** [comment]
我觉得你这个场景可以退化为传统表单提交情景。就是用multipart/form-data 格式提交。
如果是这样，那很简单，在beforeUpload 中返回false，然后在提交表单时获取数据，这是 upload 组件对应的字段（比如image）是一个数组，包含文件 file 、文件列表filelist。从新构建表单 formData=new FormData(); 然后将数据append进去。注意 文件上传字段，如果是单张文件，只需要append("onfile",image.file)。如果是多张图片就循环image.filelist逐个加入。 最后提交formdata对象就行。在网络上formData对象自动回转成传统multipart/form-data 表单格式

**Comment by aaronxdd** [comment]
> [react-component/upload#17](https://github.com/react-component/upload/issues/17)
> 
> https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

这种情况下怎么显示进度条

**Comment by aaronxdd** [comment]
> 我觉得你这个场景可以退化为传统表单提交情景——跟随表单一起提交
> 如果是这样，那很简单，在beforeUpload 中返回false，然后在提交表单时获取数据，这时 upload 组件对应的字段（比如image）是一个数组，包含最后一个文件 file 、文件列表filelist。
> 重新构建表单 formData=new FormData(); 然后将数据append进去。
> 注意 文件上传字段（image），如果是单张文件，只需要append("onfile",image.file)。如果是多张图片就循环image.filelist逐个加入。
> 最后提交formdata对象就行。在网络上formData对象会自动组装成传统multipart/form-data 表单格式传输

这个情况下，如果要显示文件上传进度条咋做

**Comment by yoyo837** [comment]
表带提交也可以ajax，进度原来怎么做就怎么做

**Comment by aaronxdd** [comment]
> 表带提交也可以ajax，进度原来怎么做就怎么做

https://ant.design/components/upload-cn/#components-upload-demo-upload-manually，没明白，像这种进度条应该怎样搞

**Comment by yoyo837** [comment]
你发的链接没有进度条啊？没太明白你的问题。

**Comment by aaronxdd** [comment]
> 你发的链接没有进度条啊？没太明白你的问题。

![image](https://user-images.githubusercontent.com/16145101/93955598-b0158e80-fd82-11ea-936a-7fb914b41463.png)
我要实现这样的，确定才是真正的提交，但是还要有进度条的显示

**Comment by yoyo837** [comment]
那就参考你发的这个链接的demo即可，自行发起ajax提交，进度数据通过ajax的progress取

**Comment by aaronxdd** [comment]
> progres

OK，我了解了，谢谢
