### ISSUE TITLE
Dropdowns don't move on scroll

### ISSUE THREAD

**Issue by stefan-schweiger** [ant-design/ant-design#8300]
### Version
2.13.10

### Environment
Windows 10, Chrome 61

### Reproduction link
[https://codepen.io/anon/pen/jaxdMz?&editors=001](https://codepen.io/anon/pen/jaxdMz?&editors=001)

### Steps to reproduce
Put a Component with a Dropdown(e.g. DatePicker, Select) in an element with overflow which can be scrolled.

### What is expected?
The Dropdown should move with the Component on Scroll.

### What is actually happening?
 When you scroll inside the element with the mouse wheel the Component itself moves as expected but the Dropdown stays in the same place.

Before Scroll:
![datepicker](https://user-images.githubusercontent.com/3532342/33171082-306da800-d04b-11e7-8696-03573b8accad.PNG)

After Scroll:
![datepickerscrollbroken](https://user-images.githubusercontent.com/3532342/33171083-3082b6be-d04b-11e7-981c-dad243024947.PNG)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3438

**Comment by afc163** [comment]
Duplicate of #8268

**Comment by stefan-schweiger** [comment]
@afc163 I've tried to set the popup container to every element I can think of but the scroll behavior is still broken.

Example with getPopupContainer:
https://codepen.io/anon/pen/OOZqyw?editors=0010

**Comment by stefan-schweiger** [comment]
@afc163 This still is making problems with every element I use, can you provide any help as to what I'm supposed to set the PopupContainer to?

**Comment by afc163** [comment]
https://codesandbox.io/s/4j168r7jw0

**Comment by stefan-schweiger** [comment]
@afc163 This works for Select but not for the DatePicker component

https://codesandbox.io/s/mmw6qqrmq8

**Comment by afc163** [comment]
https://ant.design/components/date-picker/

DatePicker has a different prop name: `getCalendarContainer`

**Comment by stefan-schweiger** [comment]
@afc163 Thank you very much, I must have overlooked that one.

But is there any reason `getCalendarContainter `and `getPopupContainer` don't default to a function which gets the next parent element with a scrollbar? This is what I'm using right now and it works as expected:

    getScrollParent(node) {
        if (node.parentElement === null) {
            return node;
        }

        return node.parentElement.scrollHeight > node.clientHeight
            || node.parentElement.scrollWidth > node.clientWidth
                 ? node.parentElement
                 : getScrollParent(node.parentElement);
    }

**Comment by oneshubh** [comment]
> @afc163 I've tried to set the popup container to every element I can think of but the scroll behavior is still broken.
> 
> Example with getPopupContainer:
> https://codepen.io/anon/pen/OOZqyw?editors=0010

use "getCalendarContainer" for datePicker
