### ISSUE TITLE
By clicking on the submit form, simulating clicking on other elements triggers more than one commit

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#8301]
### Version
2.13.10

### Environment
win10 chrom

### Reproduction link
[https://codepen.io/anon/pen/zPjewQ?editors=0011](https://codepen.io/anon/pen/zPjewQ?editors=0011)

### Steps to reproduce
Fill in the data and click submit to see the output of console

### What is expected?
Submit only once

### What is actually happening?
submit twice

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/JOvzZy?editors=0011

It is more like a React issue than antd's.

**Comment by yesmeck** [comment]
React 16 has fixed this bug https://jsfiddle.net/832x524a/
