### ISSUE TITLE
update docs about  expandRowByClick={true}

### ISSUE THREAD

**Issue by gy134340** [ant-design/ant-design#8303]
### What problem does this feature solve?
I think we can add this to Table from lastest rc-table, can enable the whole row clickable to expand, just add this api to the sample page, and developpers do not have to look for rc-table for some new apis or write some stupid code to hack. also, great work of antd.

### What does the proposed API look like?
```
     <Table
        columns={columns}
        expandRowByClick={true} // from lastest rc-table api
        expandedRowRender={expandedRowRender}
        dataSource={data}
      />
```

**Comment by yesmeck** [comment]
Welcome PR.

**Comment by danedavid** [comment]
Which files have to be updated other than `ant-design/components/table/index.en-US.md` ? Or is it the only one ? ( somebody has to do the chinese )

**Comment by yesmeck** [comment]
@danedavid You can update `index.en-US.md` only, leave the Chinese version to me.

**Comment by danedavid** [comment]
@yesmeck ok :+1:

**Comment by danedavid** [comment]
@yesmeck will the [site](https://ant.design/components/table/#Table) get updated automatically ?

**Comment by yesmeck** [comment]
@danedavid Site need deploy manually.
