### ISSUE TITLE
FormItem Button default large, can not be set to normal

### ISSUE THREAD

**Issue by farzer** [ant-design/ant-design#8304]
### Version
2.13.10

### Environment
Chrome Version 62.0.3202.94

### Reproduction link
[https://codepen.io/farzer/pen/aVKBmx?editors=001](https://codepen.io/farzer/pen/aVKBmx?editors=001)

### Steps to reproduce
Button has no 'default' value for the 'size' props

### What is expected?
Button can be set to normal size

### What is actually happening?
Button no 'normal' value

**Comment by ddcat1115** [comment]
seems to work fine...

<img width="750" alt="2017-11-24 11 09 24" src="https://user-images.githubusercontent.com/7017767/33194057-0cc4cc90-d108-11e7-96ae-08c621c8510e.png">

**Comment by farzer** [comment]
sorry, my fault. it makes error in ts check

**Comment by farzer** [comment]
![image](https://user-images.githubusercontent.com/9881593/33194134-b154c0ee-d108-11e7-87db-a40b7d08b237.png)

**Comment by ddcat1115** [comment]
fixed~ and we will release a new version in this week

**Comment by farzer** [comment]
thx
