### ISSUE TITLE
Add ids to form related components ( date input fields, radio buttons and checkboxes, dropdowns, etc)

### ISSUE THREAD

**Issue by TimMisikos** [ant-design/ant-design#8305]
### What problem does this feature solve?
It makes it easy to do end-to-end testing  using Selinium and xPath

### What does the proposed API look like?
For example  a code like this:

`<DatePicker id='datepicker' />`   should give in the compiled code  something like this: 

```
...
<div class="ant-calendar-date-input-wrap">
       <input class="ant-calendar-input " value="" placeholder="Select date"  id="datepicker">
</div>
...
```

Thank you very much for the great job you are doing!

**Comment by yesmeck** [comment]
Adding ids won't work for all component. Let's say Select component, a simplest Select component doesn't render input, you can not assign a value to input to change Select's value.

**Comment by TimMisikos** [comment]
@yesmeck thank you for giving me more information regarding this issue, so is there any other way around that you are aware? Do you know any other tools which would work well for end-to-end testing? is this going to work on the antd@3? If no... at least we will be able to read pre-populated values.

**Comment by yesmeck** [comment]
Adding id to `DatePicker` input won't work. I you want to populate a  DatePicker, you need simulate user behavior:

1.  Find '.ant-calendar-picker' and simulate a click;
2.  Find '.ant-calendar-input ' and populate this' value;
3. Simulate click on body to close data picker panel.

**Comment by mgrdevport** [comment]
As far as I could see, there is currently no way to pass any kind of id to the input field with the class '.ant-calendar-input'.
I will have a look into the rc-calendar module.

**Comment by JeffreyATW** [comment]
Adding an `id` to input fields (even inside components like `DatePicker`) is important for accessibility reasons. I want to add an `htmlFor` to associated labels, and focus the input fields when I click the labels.

**Comment by yesmeck** [comment]
PR anytime if you find any component doesn't support id.

**Comment by ttgiang** [comment]
I'm using uilicious.com for my UI testing and it's very challenging when IDs are not present.

**Comment by yogithesymbian** [comment]
for cypress output rc_select_1 , its random dynamic for all dropdown / `ant select`

**Comment by yogithesymbian** [comment]
> for cypress output rc_select_1 , its random dynamic for all dropdown / `ant select`

```
<input autocomplete="off" class="ant-select-selection-search-input" role="combobox" aria-expanded="false" aria-haspopup="listbox" aria-owns="rc_select_2_list" aria-autocomplete="list" aria-controls="rc_select_2_list" type="search" value="" id="rc_select_2">
```
