### ISSUE TITLE
antd如何新增样式（不是自定义）？

### ISSUE THREAD

**Issue by JediBai** [ant-design/ant-design#8309]
### What problem does this feature solve?
ant-form-item-label的class中需要添加text-overflow: ellipsis;让label过多的文字隐藏；

### What does the proposed API look like?
通过roadhogrc的"theme"配置如下：

theme.js
-------------------------------------------
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
  "primary-color": "#1DA57A",
  "ant-form-item-label":"text-overflow: ellipsis",
  "label-color":"red",
};

自定义的样式的确生效了，但是新增"ant-form-item-label":"text-overflow: ellipsis",的效果并没有成功，如果需要新增样式，怎么去实现？

**Comment by yesmeck** [comment]
自己在 css 写。

```css
.ant-form-item-label {
  text-overflow: ellipsis;
}
```
