### ISSUE TITLE
DatePicker组件只高亮选中的该年该月的日期，不要高亮所有月份的该日期

### ISSUE THREAD

**Issue by neuscx** [ant-design/ant-design#8310]
### What problem does this feature solve?
在我看来，正常的选择日期、月份的时候（特别是月份），我都只是想选择一个月份，但是每个月份的某个日期都高亮会让我有一种不知道到底选择的是哪个月的日期的感觉。很有可能用户觉得我切换了一下月份，他就已经选择到了想要的日期。
In my opinion, when i want to change the date(or the month), i don't want the same day highlighted in every month. This will bother me. I think the most users just want the day they chose to be highlighted. When they change the month and see the highlighted day, they may think this day is the day they choose.

### What does the proposed API look like?
可以是在api中加一个属性，判断是不是所有月份的某一天、每年的同一个月都显示高亮。
或者简单实现，可以在选中年的某一个父元素上加上一个class，比如切换月份的组件，可以在ant-calendar-month-panel-table，这个table上加一个ant-calendar-month-panel-select-table。
In my opinion, it can be a property in API. It determines whether or not the day of the month and the month of the year needs highlighted or not.
Or, we can add a class to one of the parent dom of this day or month. Such as we can add 'ant-calendar-month-panel-select-table' to the table which the class is 'ant-calendar-month-panel-table' in the MonthPicker.

**Comment by benjycui** [comment]
Deplicated: https://github.com/ant-design/ant-design/issues/6146
