### ISSUE TITLE
Select组件使用this.props.form.setFieldsValue更新指定的value无效

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design#8313]
### Version
2.13.10

### Environment
mac os, chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/motorfu/pen/VrdrZP?editors=0010](https://codepen.io/motorfu/pen/VrdrZP?editors=0010)

### Steps to reproduce
通过onChange方法 使用过this.props.form.setFieldsValue更新Select组件的value, Select内容没有改变成更新的value。

### What is expected?
通过this.props.form.setFieldsValue更新Select组件指定的内容

### What is actually happening?
this.props.form.setFieldsValue更新Select组件指定内容无效

**Comment by MotorFu** [comment]
补充: 使用this.props.form.resetFields(); 对Select组件无效

**Comment by afc163** [comment]
You should use `normalize` instead of `setFieldsValue`.

https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options)

**Comment by MotorFu** [comment]
Thank you!

**Comment by Gjb7598189** [comment]
这个setFieldsValue应该是异步执行的，导致获取到的值还是上次的值
