### ISSUE TITLE
需求：Table组件嵌套子表格使用expandedRowRender自定义返回值为null时不显示展开图标

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design#8315]
### What problem does this feature solve?
体验问题

### What does the proposed API look like?
我希望expandedRowRender方法返回值是null, 展开图标不显示。 Table实例中的树形数据展示demo, children为空时，展开图标是不显示的，我希望使用expandedRowRender自定义的嵌套子表格也能实现这个。

**Comment by yesmeck** [comment]
See #8157
