### ISSUE TITLE
TreeSelect dropdown not closing on mobile

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#8316]
### Version
2.13.10

### Environment
iOS safari

### Reproduction link
[https://ant.design/components/tree-select/](https://ant.design/components/tree-select/)

### Steps to reproduce
click on a TreeSelect component, to open the Dropdown from a mobile browser.

### What is expected?
the Dropdown opens, close it by clicking outside of it

### What is actually happening?
the Dropdown opens, but there is no way to close it by clicking outside

---
the same is true for all components that use overlay as popover.
this bug is not present on rc-tree-select@1.10.12
http://react-component.github.io/tree-select/examples/basic.html

**Comment by yesmeck** [comment]
https://github.com/react-component/trigger/pull/71

**Comment by violabg** [comment]
https://github.com/ant-design/ant-design/issues/8296
