### ISSUE TITLE
🎉 Congrats on 20,000 stars on Github! 🎉

### ISSUE THREAD

**Issue by bodaz** [ant-design/ant-design#8321]
Congrats to the ant-design project reaching 20,000 stars on Github! 

Honestly, it's been one of my favourite React open source project out there, and I can't imagine my life without it, I could spin up some React demo project in minutes with the help with ant design! It's beautifully designed, simple to use and actively being developed/improving! With the new v3.0 around the corner (for those interested, see #8233), I can't wait to see how far the project will go!

Huge _props_ to the team behind it as well, just to name a few: @afc163, @benjycui, @yiminghe, @yesmeck and I know there are more people out there who also deserves a shout out! 

What are your favourite feature about the project? And what would've you like to see in the future?

**Comment by bodaz** [comment]
![screen shot 2017-11-26 at 01 42 03](https://user-images.githubusercontent.com/6238558/33236473-0cbd7d5a-d24d-11e7-98a5-484ff94ab864.png)

**Comment by ChuckJonas** [comment]
I just want to second that sentiment.  This library allows you to accomplish amazing things in such a short amount of time.  I've been using it everyday for almost 3 months now and there are very few cases where what I wanted to do wasn't covered by a out-of-the-box antd component.
