### ISSUE TITLE
can dropdown in treeselect has the same  feature as placement of dropdown do

### ISSUE THREAD

**Issue by juicy-tangerine** [ant-design/ant-design#8326]
### What problem does this feature solve?
it can set optional dropdown position when some times dropdown need to display in other position

### What does the proposed API look like?
hope can use dropdown in treeselect as pagination in table

**Comment by afc163** [comment]
Can't understand what you need.. 😢

**Comment by yesmeck** [comment]
Closing since this issue is inactive.
