### ISSUE TITLE
Dropdown position to mouse point when trigger is contextMenu

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8327]
Infavor of #7232, we now support popup dropdown when user right click on trigger. But its position is same as other trigger way. We need something like this:

```jsx
<Dropdown trigger={['contextMenu']} alignToMousePointer />
```

<img width="366" alt="image" src="https://user-images.githubusercontent.com/507615/33254313-0bb66fca-d383-11e7-9205-13305441b4b2.png">

**Comment by P0oOOOo0YA** [comment]
So what is the latest status of this feature? looking after using ant design with electron

**Comment by zombieJ** [comment]
Hi @P0oOOOo0YA，
You can check contextMenu example:https://ant.design/components/dropdown-cn/#components-dropdown-demo-context-menu
