### ISSUE TITLE
您好，请教一个问题

### ISSUE THREAD

**Issue by sincerefly** [ant-design/ant-design#833]
我的程序是使用react组织的，我的想法是把react和react-dom在前端进行引入，因为有CDN,速度会快一点

然后使用browserify进行打包，但是发现一个问题就是，antd引用了react，导致前端打开界面会报一个错误

```text
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

搜索了一下，应该是多次引入的问题，如果我不用CDN，在后台通过require引入react和react-dom，则不会出现这个问题

请问你有什么好办法能够让antd正常使用，又可以在前端引入react吗

**Comment by sincerefly** [comment]
打错了，是用gulp组织的

**Comment by benjycui** [comment]
webpack 可以把一些依赖设为 [externals](https://webpack.github.io/docs/library-and-externals.html#examples)，browserify 应该也有类似的设置，你自己查文档吧。
