### ISSUE TITLE
在3.0.0-RC3版本中，多处Modal无法被正确关闭的BUG

### ISSUE THREAD

**Issue by dreamcog** [ant-design/ant-design#8330]
### Version
3.0.0-RC3

### Environment
MAC,Chrome

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce

现在有2种情况无法被正确关闭Modal

第一种情况，使用Modal.Confirm

```

import {Input,Icon,Button,Select,Table,Modal} from 'antd'
const Option = Select.Option;
const confirm = Modal.confirm;

class PostList extends CommonList {

    deletePost(coursepost_id) {

        var that = this;
        confirm({
            title: '你确定要删除吗?',
            content: '删除后不能恢复数据，请确认',
            onOk() {
                that.props.deleteCoursepost(coursepost_id).then(function(){
                    that.refresh();
                })
            },
            onCancel() {},
        });
   }
}
```

在上面代码中，2.13和之前的稳定版本是没问题的，但是在 3.0.0-RC3版本中，无法被正确关闭。

第二种情况，使用普通的Modal方法。

```

        var add_link_html = null;
        if (this.state.showAddVideoBox == true) {
            add_link_html = <Modal title="插入视频" confirmLoading={this.state.is_fetching} visible={this.state.showAddVideoBox} onCancel={this.handleShowAddVideoBox} onOk={this.addVideo}>
                <div className="block-line-form block-modal-addlink">
                    <div className="input-group">
                        <div className="input-group-addon">网址</div>
                        <input type="text" className="form-control" placeholder="输入链接网址" onChange={this.handleEventValueChange.bind({},'url')}/>
                    </div>
                    <div className="notice">
                        <p className="help">支持优酷，腾讯视频，爱奇艺等视频网站链接</p>
                    </div>
                </div>
            </Modal>
        }
```

当this.state.showAddVideoBox从True变成false的时候，并不会关闭这个Modal,当this.state.showAddVideoBox重新再变成true的时候会出现2个同样的Modal。

其他：
因为，采用PRO的一些组建在重构后台，所以把整个项目升级成了3.0.0.RC3版本了，希望能尽快修复这个比较严重的BUG。实在不知道如何下手。
谢谢。

### What is expected?
Modal能正确关闭

### What is actually happening?
Modal无法被关闭

**Comment by dreamcog** [comment]
https://codepen.io/
似乎只能提供2.13版本的antd，如何能在上面使用3.0.0-rc3版本？

**Comment by nikogu** [comment]
`setting -> javascript -> change version`

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/OOoPmd?editors=0010

**Comment by dreamcog** [comment]
@nikogu @afc163 谢谢你们的帮助，我在codepen重现了一下这个问题，发现在codepen中的确不存在这个BUG，可能是我自己的问题，我继续查一下原因。

**Comment by dreamcog** [comment]
似乎是我用了react@15.4.2的问题。

**Comment by yesmeck** [comment]
https://codesandbox.io/s/00417wj0mv

**Comment by dreamcog** [comment]
@afc163 @nikogu @yesmeck 我确认了是因为用react的16以下的版本配合ant3.0.0-rc3才会出现这个无法关闭modal的bug.
我的解决方案是把ant.design降级到了稳定版本。

多谢各位，能否帮忙关闭这个ISSUE

**Comment by afc163** [comment]
你可以自行关闭。
