### ISSUE TITLE
Ant 3 RC - Validation in large Input is not centered

### ISSUE THREAD

**Issue by TsuryKnox** [ant-design/ant-design#8334]
Using 3.0.0-rc.3
Pretty straight forward. When using the 'large' Input, validation sign is not centered.
[Example](https://i.imgur.com/Ii3Q9ja.png)

**Comment by yesmeck** [comment]
@TsuryKnox Could you create a issue using http://new-issue.ant.design/

**Comment by TsuryKnox** [comment]
Can't select version 3 there.

**Comment by TsuryKnox** [comment]
#8336
