### ISSUE TITLE
Ant 3 RC3 - Validation in large Input is not centered

### ISSUE THREAD

**Issue by TsuryKnox** [ant-design/ant-design#8336]
### Version
2.13.10

### Environment
macOS Sierra, React 16, Chrome (latest)

### Reproduction link
[https://i.imgur.com/Ii3Q9ja.png](https://i.imgur.com/Ii3Q9ja.png)

### Steps to reproduce
Create a large Input with validation

### What is expected?
The validation icon should be vertically centered.

### What is actually happening?
The icon is anchored to the top. [Example](https://i.imgur.com/Ii3Q9ja.png)

**Comment by afc163** [comment]
You can fork this one: https://codepen.io/afc163/pen/OOoPmd?editors=0010

**Comment by yesmeck** [comment]
https://codesandbox.io/s/1v320mz497
