### ISSUE TITLE
Preparing 3.0

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#8337]
A checklist for 3.0 releasing.

- [x] Merge `antd-3.0` to `master`
- [x] Checkout `2.x-stable` branch.
- [x] Deploy  http://2x.ant.design for 2.x dos.
- [x] Ensure all issues labeled by `v3` are resolved. [v3 issues](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+label%3Av3)
- [x] Ensure all dependencies up to date
- [x] Changelog & upgrade guide #8364
- [x] Release blog post
- [x] Ship antd@3.0
- [x] Deploy new site #8238

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8238
