### ISSUE TITLE
Form advanced search demo style is broken

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#8339]
http://beta.ant.design/components/form/#components-form-demo-advanced-search

<img width="923" alt="screen shot 2017-11-27 at 23 23 00" src="https://user-images.githubusercontent.com/465125/33274073-0d633f28-d3ca-11e7-9fd7-e734e501668f.png">

**Comment by bodaz** [comment]
Do you mean the expand code icon is not clickable error? If so, I found the issue to be at [here](https://github.com/ant-design/ant-design/commit/daf596a89823c8d43c6ab46ce0f761437b51ffb0#comments)
