### ISSUE TITLE
RangePickers问题

### ISSUE THREAD

**Issue by m927259903** [ant-design/ant-design#834]
![image](https://cloud.githubusercontent.com/assets/6375421/12219814/79c28968-b78d-11e5-9f53-9517e26d0728.png)
请问这是什么问题 
谢谢

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md#do-your-homework-before-asking-a-question

**Comment by m927259903** [comment]
@benjycui 
不好意思  我实在是没有找到问题
我都已经将范例代码复制下来，还是会报这个警告
```jsx 
App.js
import { DatePicker } from 'antd';
import React from 'react';
import ReactDOM from 'react-dom';
const RangePicker = DatePicker.RangePicker;

function onChange(value) {
  console.log('From: ', value[0], ', to: ', value[1]);
}
ReactDOM.render(<div>
  <RangePicker style={{width: 184}} onChange={onChange} />
  <br />
  <RangePicker showTime format="yyyy-MM-dd HH:mm:ss" onChange={onChange} />
</div>, document.querySelector('#container');
```
这样还是有问题，所以还希望您指教一下
劳烦了！

**Comment by benjycui** [comment]
麻烦 fork 这个 jsfiddle，重现问题 http://jsfiddle.net/0dso5y0x/
