### ISSUE TITLE
Issues of Menu 

### ISSUE THREAD

**Issue by Dod-Annie** [ant-design/ant-design#8341]
### Version
2.13.10

### Environment
WIN10,Chrome60.0.3112.90

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less](https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less)

### Steps to reproduce
The component Menu export an API "theme".but the theme's style relies on some global variables of CSS.So it cause some uncontrollable questions when I modify those global variables.
for example,when I use the Menu component and the API "theme",I select the theme 'dark'
" &&-dark &-item-selected { background-color: @primary-color; }"
this style of theme 'dark' rely on the global variable 'primary-color', 

### What is expected?
I hope to modify the css variables more free by myself

### What is actually happening?
If I want modify the component Menu's background-color,I must modify the global variable 'primary-color', it cause more global problems in my project

**Comment by nikogu** [comment]
@Dod-Annie it is not necessary to change `@primary-color` by `theme` for changing your Menu `background`, you can overwirte the style directly.
