### ISSUE TITLE
字符串包含 - 符号和数字的时候使用 Helvetica Neue 字体, 如果包含 span 那么第一个 span 前会多一个空格

### ISSUE THREAD

**Issue by lastmayday** [ant-design/ant-design#8342]
### Version
2.13.8

### Environment
antd 版本 2.13.8 , 浏览器 chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/anon/pen/LOJJBe](https://codepen.io/anon/pen/LOJJBe)

### Steps to reproduce
详情见 codepen . 自己测试的结果是同时包含 - 符号和数字时, 再同时包含 span 的话, 第一个 span 前会多一个空格

### What is expected?
正常显示, 不多一个空格

### What is actually happening?
同时包含 - 符号和数字时, 再同时包含 span 的话, 第一个 span 前会多一个空格

---
业务场景:

使用 antd 的 Table 组件, 应用示例代码 https://ant.design/components/table-cn/#components-table-demo-reset-filter .
想要实现搜索结果高亮, 所以增加了 span 标签高亮搜索内容. 但遇到了上述问题.

解决办法是手动指定字体去掉 Helvetica Neue

**Comment by lastmayday** [comment]
<img width="93" alt="2017-11-28 2 49 57" src="https://user-images.githubusercontent.com/1724848/33306015-8e4fa564-d44b-11e7-9119-3ec06cd2cbdd.png">

**Comment by afc163** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/507615/33306128-12f56ca4-d44c-11e7-863c-7be7858ce3ec.png">

你给的例子貌似没有问题。

**Comment by lastmayday** [comment]
@afc163 可能是浏览器的问题. 我使用 chrome 62.0.3202.94 查看会有这个问题, 使用 safari 没问题. 
我 close 掉.
