### ISSUE TITLE
Tooltip 3.0.0beta 5 bug，请去掉浏览器默认事件

### ISSUE THREAD

**Issue by chengnuo** [ant-design/ant-design#8346]
### Version
2.13.10

### Environment
mac safari 最新版本 react dva

### Reproduction link
[http://meiyou](http://meiyou)

### Steps to reproduce
.shuxing {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
{
        title: '商品名称',
        dataIndex: 'spu_name',
        className: styles.goodsTd5,
        render: (text) => {
          return (
            <Tooltip
              placement="top"
              title={text}
            >
              <div>
                <div className={`${styles.shuxing} ${styles.goodsTd5}`} >
                  {text}商品名称商品名称商品名称商品名称商品名称
                </div>
              </div>
            </Tooltip>
          );
        },
      },

### What is expected?
开启事件功能，或者去掉浏览器事件

### What is actually happening?
有2个hover，Tooltip 和 系统样式的hover

---
有图，无法上传。

**Comment by afc163** [comment]
Please make your issue readable
