### ISSUE TITLE
Using Sider component creates a unnecessary render call

### ISSUE THREAD

**Issue by HouCoder** [ant-design/ant-design#8347]
### Version
2.13.10

### Environment
Node: v6.11.0, Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/tonni_hou/pen/OOoEbP](https://codepen.io/tonni_hou/pen/OOoEbP)

### Steps to reproduce
Goto the Codepen link, open your browser console, you'll see two `123` outputs.

Now remove the `Sider` component at line 9, use a simple `<div>` to wrap the component, refresh your browser, you'll see only one `123` output.

### What is expected?
Using Sider component should not cause any extra re-render.

### What is actually happening?
Using Sider component causes extra re-render.

**Comment by yesmeck** [comment]
It's a  intended behavior, see https://github.com/ant-design/ant-design/pull/8077
