### ISSUE TITLE
ant design 主题修改

### ISSUE THREAD

**Issue by sunhoudong** [ant-design/ant-design#8348]
### Version
2.13.10

### Environment
windows，谷歌浏览器

### Reproduction link
[https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme)

### Steps to reproduce
无

### What is expected?
如果脚手架工具不是antd-init和dva-cli，这两个，更换主题的方式时什么？

### What is actually happening?
在自己定义的脚手架，项目架构下可以正常使用，希望官网的文档，可以更新一下或者再详细点

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme-cn

**Comment by sunhoudong** [comment]
定义 theme 属性时，需要配合使用（antd-init 或 dva-cli。如果你使用的是其他脚手架，可以参考 atool-build 中 less-loader 的 webpack 相关配置 ，利用 less-loader 的 modifyVars 配置来覆盖原来的样式变量
@afc163,这个有例子吗？

**Comment by afc163** [comment]
底下有个社区教程可以参考一下。

**Comment by yesmeck** [comment]
写了个小插件 https://github.com/yesmeck/webpack-less-theme-plugin

**Comment by sunhoudong** [comment]
TypeError: Cannot read property 'push' of undefined
    at Compiler.compiler.plugin (E:\gitRepo\vendor-shop\node_modules\webpack-less-theme-plugin\index.js:39:36)
    at Compiler.applyPlugins (E:\gitRepo\vendor-shop\node_modules\tapable\lib\Tapable.js:61:14)
    at webpack (E:\gitRepo\vendor-shop\node_modules\webpack\lib\webpack.js:34:12)
    at processOptions (E:\gitRepo\vendor-shop\node_modules\webpack\bin\webpack.js:305:14)
    at Object.<anonymous> (E:\gitRepo\vendor-shop\node_modules\webpack\bin\webpack.js:363:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
@yesmeck ，安装好之后使用，按照您这个上面的步骤，结果报错了，这是什么问题？

**Comment by yesmeck** [comment]
要 webpack 3

**Comment by sunhoudong** [comment]
@yesmeck 换了webpack3 ,还是报那个错

**Comment by yesmeck** [comment]
😂 想想那个插件没啥用，webpack 3 的配置已经简单很多了，按网站上链接里的文章来配就可以了。

**Comment by sunhoudong** [comment]
@yesmeck 那具体怎么来解决我说的那个问题呢？我现在用的是笨办法，直接重写antd的样式，但是这样做，如果我们的设计大面积的想换样式，这工作量就比较大了，所以才想到更换主题，按照官网的提示，单独出来，也就是基于antd-init 或 dva-cli这两个脚手架是可以成功，但是我的原项目用的不是这个，更换脚手架工具，牵扯的又比较多，所以才想请教一下你们，该怎么处理这个问题

**Comment by yesmeck** [comment]
https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f

**Comment by afc163** [comment]
> 底下有个社区教程可以参考一下。

不看我回复的。。。

**Comment by sunhoudong** [comment]
社区的那个教程，没有用啊，加上了没效果
`const fs = require('fs');
const lessToJs = require('less-vars-to-js');
const themeVariables = lessToJs(fs.readFileSync(path.join(__dirname,'./theme/theme.less'),'utf8'));`
`{
                test: /\.less$/,
                use:[
                    {loader:"style-loader"},
                    {loader:"css-loader"},
                    {loader:"less-loader",
                        options:{
                            modifyVars:themeVariables
                        }
                    }
                ]
            },`
`{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    ["import",{"libraryName":"antd","style":true}]
  ]
}`

**Comment by sunhoudong** [comment]
可以了，谢谢，是其他的代码影响到这里了

**Comment by EugeneHuang95** [comment]
@afc163 根据[官网例子](http://ant-design.gitee.io/docs/react/use-with-create-react-app-cn)配置主题：
`modifyVar: { "@primary-color": "#1DA57A" }`，启动应用后打开chrome devtool发现配置的样式被默认样式覆盖，试了下`modifyVar: { "@primary-color": "#1DA57A !important" }`会报错，这该怎么解决？

antd version: 3.1.3

**Comment by huangzhongquan** [comment]
我的ant-vue-css 是通过cdn引入样式的 除了自己重写样式覆盖 还有没有什么办法
