### ISSUE TITLE
form.resetFields() can's clear the Select 's value

### ISSUE THREAD

**Issue by pssgo** [ant-design/ant-design#8349]
### Version
2.13.10

### Environment
chrome nodev8.0

### Reproduction link
[https://codepen.io/pssgo/pen/OOorwq](https://codepen.io/pssgo/pen/OOorwq)

### Steps to reproduce
```
import React from 'react'
import { Form, Select, Button } from 'antd'

const Option = Select.Option
const FormItem = Form.Item

class Node extends React.Component {
  reset = () => {
    this.props.form.resetFields()
  }
  render() {
    const { form } = this.props
    return (
      <Form>
        <FormItem label="todo">
          {form.getFieldDecorator('todo', {
            valuePropName: 'selected',
          })(
            <Select allowClear>
              <Option value="a">1</Option>
              <Option value="b">2</Option>
            </Select>,
          )}
        </FormItem>
        <Button type="primary" onClick={this.reset}>
          reset
        </Button>
      </Form>
    )
  }
}

export default Form.create()(Node)
```

### What is expected?
form.resetFields() can clear the Select 's value

### What is actually happening?
form.resetFields() can't clear the Select 's value

**Comment by yesmeck** [comment]
`Select`'s value props is `value`, not `selected`.

**Comment by zhaodongxx** [comment]
nice

**Comment by anandwebs** [comment]
user this - this.props.form.resetFields()

**Comment by aareyes00** [comment]
Any updates? form.resetFields not working though

**Comment by yoyo837** [comment]
Still any other problem? Please open a new issue and provide a reproduction demo link.

**Comment by aareyes00** [comment]
I removed valuePropName: 'selected' and it works fine now.

**Comment by bidva** [comment]
I needed to use trigger:"onBlur" and valuePropName: "defaultValue" 
now when I want to reset the form the state of the input does not get flush and still keep the last state
here you can reproduce it 
https://codesandbox.io/s/bold-chatterjee-jrn6q?fontsize=14&hidenavigation=1&theme=dark
what is the best way of keeping valuePropName and also resetting the form ?

**Comment by abbostajimov** [comment]
> I removed valuePropName: 'selected' and it works fine now.

Can you show the code with `valuePropName`

**Comment by sk8Guerra** [comment]
I'm facing the same issue with `Select` component using the `mode={'tags}`.
anyone has a suggestion, on how to fully clean the state?

**Comment by mikeaustin** [comment]
I've been using key={Math.random()} to force reset. Not the best, but it works.

**Comment by duchicong** [comment]
For this issue, I have dealt with it using form.setFieldsValue ({ward: ''}) in the event onChange.
You can see more here : [https://ant.design/components/form/v3#Form-control](https://ant.design/components/form/v3#Form-control)
```
<Form.Item
	shouldUpdate
	rules={[{ required: true, message: VALIDATE.REQUIRED }]}
	name="district"
	initialValue={formAnswerFields.district?.uuid || ''}
>
	<Select
		showSearch
		style={{ width: '100%' }}
		optionFilterProp="children"
		onChange={(value, event) => {
		setFormAnswerFields(prev => ({
		  ...prev,
		  district: {
			uuid: value,
			manual_code: event['data-gso'],
			field_metadata_uuid: item?.field_metadata.uuid
		  },
		  ward: null
		}))
		form.resetFields(['ward'])
		form.setFieldsValue({ ward: '' })
		}}
	>
	{filterData(state.district || [], formAnswerFields.province?.uuid, 'district').map(
		option => <Option key={option.uuid} value={option.uuid} data-gso={option.gso_id}>{option.name}</Option>
	)}
	</Select>
</Form.Item>
```

**Comment by Ch3ssMaster** [comment]
> ### Version
> 2.13.10
> 
> ### Environment
> chrome nodev8.0
> 
> ### Reproduction link
> https://codepen.io/pssgo/pen/OOorwq
> 
> ### Steps to reproduce
> ```
> import React from 'react'
> import { Form, Select, Button } from 'antd'
> 
> const Option = Select.Option
> const FormItem = Form.Item
> 
> class Node extends React.Component {
>   reset = () => {
>     this.props.form.resetFields()
>   }
>   render() {
>     const { form } = this.props
>     return (
>       <Form>
>         <FormItem label="todo">
>           {form.getFieldDecorator('todo', {
>             valuePropName: 'selected',
>           })(
>             <Select allowClear>
>               <Option value="a">1</Option>
>               <Option value="b">2</Option>
>             </Select>,
>           )}
>         </FormItem>
>         <Button type="primary" onClick={this.reset}>
>           reset
>         </Button>
>       </Form>
>     )
>   }
> }
> 
> export default Form.create()(Node)
> ```
> 
> ### What is expected?
> form.resetFields() can clear the Select 's value
> 
> ### What is actually happening?
> form.resetFields() can't clear the Select 's value

Hi, I had the same issue and solved it with a state variable. In my case, I needed not clear but set the value to a String. So, on the onClick event, I set the Select's value attribute with the Hook and worked as I needed.
