### ISSUE TITLE
Modal使用问题

### ISSUE THREAD

**Issue by RocDeanGit** [ant-design/ant-design#835]
**问题描述**

Modal使用有问题

**发生环境**
win10 x64
- antd 版本：0.11.2
- react 版本：0.14.5
- nodejs 版本：4.2.2
- 浏览器：vivaldi (用edge也一样)

**重现步骤**

直接使用第一个例子，点击按钮之后，控制台输出
![image](https://cloud.githubusercontent.com/assets/3839895/12225541/9a0b0122-b847-11e5-93c4-96e48ba24944.png)
对话框没出现，背景已经变暗了

**Comment by benjycui** [comment]
直接用 demo 测试没有重现问题，请再确认一下你的代码，如果还有问题，请提供必现的例子 http://jsfiddle.net/9zrstuto/70/

**Comment by RocDeanGit** [comment]
我看了一下那里的依赖，原来是要用react-with-addon
我之前都没用这个，换成这个之后就正常了
thanks
