### ISSUE TITLE
Can't select current date in range picker

### ISSUE THREAD

**Issue by Sathiyamm** [ant-design/ant-design#8350]
### Version
2.13.10

### Environment
Chrome

### Reproduction link
[https://codepen.io/sathiyam/pen/JOaQXQ?editors=0010](https://codepen.io/sathiyam/pen/JOaQXQ?editors=0010)

### Steps to reproduce
Click the range picker.

### What is expected?
Enable the current date

### What is actually happening?
Disable current date

`const { DatePicker } = antd;
const { MonthPicker, RangePicker } = DatePicker;
class DatePicker extends Component {
  constructor(props, context) {
     this.state = {
       earlyPickUpDatetime:[],
            latePickUpDatetime:[]
     };
  }
disabledDate(current) {
  return current && current.valueOf() <= Date.now();
}
    getPickupDateTime(e){
           if (e.length > 1) {
               this.setState({
                   earlyPickUpDatetime: e[0]._d,
                   latePickUpDatetime: e[1]._d
               });
           }
    }
render() { 
  return (
  <div>   
   <RangePicker onChange={(e) => this.getPickupDateTime(e)} placeholder={['Early Delivery', 'Late Delivery']} showTime format="YYYY-MM-DD HH:mm:ss" disabledDate={this.disabledDate}/>
  </div>
);
}
}`

**Comment by yesmeck** [comment]
Your codepen is not working.

**Comment by Sathiyamm** [comment]
@yesmeck i sent link 
return current && current.valueOf() **_<=_** Date.now();
https://codepen.io/sathiyam/pen/QOZmZx?&editors=0010
I'm use condition select current date also but it's not enable current date

**Comment by yesmeck** [comment]
You should compare by day.

**Comment by Sathiyamm** [comment]
How to compare by day? Any example sent? @yesmeck

**Comment by yesmeck** [comment]
`current.format('YYYY-MM-DD') < moment().format('YYYY-MM-DD')`

**Comment by afc163** [comment]
http://momentjs.com/docs/#/query/

**Comment by Sathiyamm** [comment]
https://codepen.io/sathiyam/pen/QOZmZx?editors=0010
I change the code 
disabledDate(current) {
        // Can not select days before today
        var days = 1;
        return current && (current.valueOf() < (Date.now() - days * 24 * 60 * 60 * 1000));
    }
Its working. Thanks @yesmeck and @afc163
