### ISSUE TITLE
I want to change the border color of Input component when it was focus

### ISSUE THREAD

**Issue by n313893254** [ant-design/ant-design#8354]
### What problem does this feature solve?
change the color of Input component when it was focus, there have `@input-hover-border-color` but have not `@input-focus-border-color`

### What does the proposed API look like?
Provider `@input-focus-border-color`

**Comment by n313893254** [comment]
I want my input are the same color when it is `hover` and `focus`, thx

**Comment by n313893254** [comment]
well, I rewrite `.ant-input:focus`, it can address my issue. 
```
.ant-input:focus {
    border-color: #57a8e9;
    outline: 0;
    -webkit-box-shadow: 0 0 0 2px rgba(87,168,233, .2);
    box-shadow: 0 0 0 2px rgba(87,168,233, .2);
}
```

**Comment by tonydesignxd** [comment]
> well, I rewrite `.ant-input:focus`, it can address my issue.
> 
> ```
> .ant-input:focus {
>     border-color: #57a8e9;
>     outline: 0;
>     -webkit-box-shadow: 0 0 0 2px rgba(87,168,233, .2);
>     box-shadow: 0 0 0 2px rgba(87,168,233, .2);
> }
> ```

Thank you so much, my problem was fixed 👯‍♂
