### ISSUE TITLE
The content's position can't be changed on Panel Tag 

### ISSUE THREAD

**Issue by mingChen2017** [ant-design/ant-design#8357]
### Version
2.13.10

### Environment
chrome

### Reproduction link
[https://codepen.io/chenming/pen/eePKOB?&editors=001)

### Steps to reproduce

修改<Panel>标签里面的<img>标签里面的style

### What is expected?
在折叠面板内容里面的图片或者文字，可以改变位置并且被收起

### What is actually happening?
在折叠面板内容里面的图片或者文字，用相对模式改变不了位置 用绝对模式的话又会导致折叠面板收起来的时候图片和文字没有被收起来

**Comment by afc163** [comment]
Your codepen is not working.

**Comment by mingChen2017** [comment]
https://codepen.io/chenming/pen/eePKOB?&editors=001

**Comment by afc163** [comment]
这是你自己 css 的问题，不是 antd 的。。

**Comment by mingChen2017** [comment]
sorry 上面的例子可能举得不太好 麻烦看看我这个例子 
https://codepen.io/chenming/pen/LOgrqq?editors=0010

**Comment by afc163** [comment]
```diff
- postion
+ position
```

建议不要在这里提问。

**Comment by mingChen2017** [comment]
非常抱歉耽误您时间了
