### ISSUE TITLE
Select 控件的allowClear属性设置后无效

### ISSUE THREAD

**Issue by KevinDai** [ant-design/ant-design#836]
如题，设置Select组件的allowClear参数，没有删除图标，我看rc-select是没问题的，是不是样式缺失还是什么问题，没怎么去细看源码。
<Select
                    name="status"
                    value={formData.status}
                    allowClear
                    onChange={this.setValue.bind(this, "status")}>
                    {
                        [...userStatus.entries()]
                            .map(([key,value]) => {
                            return <Option key={key}>{value}</Option>;
                            })
                        }
                </Select>

**Comment by afc163** [comment]
设计层面 Select 不提供这个功能。

**Comment by benjycui** [comment]
文档里有这个 。。。

![image](https://cloud.githubusercontent.com/assets/3580607/12289426/702871c0-ba16-11e5-8fde-e62be379b251.png)

要更新下文档么？

**Comment by afc163** [comment]
嗯，先干掉吧。
