### ISSUE TITLE
Menu组件设置defaultSelectedKeys失效

### ISSUE THREAD

**Issue by emmaccacca** [ant-design/ant-design#8360]
### Version
2.13.10

### Environment
codePen，和ant design的示例一样的环境

### Reproduction link
[https://codepen.io/wmeng/pen/OOBZYq?&editors=001](https://codepen.io/wmeng/pen/OOBZYq?&editors=001)

### Steps to reproduce
直接打开codepen就看到了

### What is expected?
Menu第一项选中

### What is actually happening?
Menu第一项没有选中

**Comment by afc163** [comment]
defaultSelectedKeys only works at first time.

Check https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by SimonLeeee** [comment]
@afc163  but I need to do that how can i achieve it ?
