### ISSUE TITLE
在使用this.props.form.setFieldsValue 给fom表单设置值的时候，如何确保已经用getFieldDecorator 注册过了，有提供方法判断吗 ？

### ISSUE THREAD

**Issue by CxxyLucifer** [ant-design/ant-design#8362]
### Version
2.13.10

### Environment
mac os 10.13.1  chome react 16.1.1

### Reproduction link
[https://github.com/CxxyLucifer/shop-web.git](https://github.com/CxxyLucifer/shop-web.git)

### Steps to reproduce
react 的  componentDidMount方法中调用  this.props.form.setFieldsValue 给表单设值，浏览器console的提醒
Warning: Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it.

### What is expected?
有方法判断 field已经在 `getFieldDecorator` 或者 `getFieldProps` to 是否注册过

### What is actually happening?
没找到这个方法

---
在使用this.props.form.setFieldsValue 给fom表达设置值的时候，如何确保已经用getFieldDecorator 注册过了，有提供方法判断吗 ？

**Comment by afc163** [comment]
你在 render 里使用 getFieldDecorator 注册就行了。

**Comment by CxxyLucifer** [comment]
我在render里面已经使用getFieldDecorator 注册过了，但是我在componentDidMount方法中调用 this.props.form.setFieldsValue 给表单设值还是有warng啊
