### ISSUE TITLE
Select选择器在多选模式下能否自定义输入框的内容

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design#8363]
### What problem does this feature solve?
Select多选模式下如果选了多项内容，往往会把输入框撑的很大，有时不需要看到每一项内容，所以能不能自定义显示内容，类似改成“已选x项”

### What does the proposed API look like?
```
customDisplay: value => `已选${value.length}项`
```

**Comment by yesmeck** [comment]
See https://github.com/react-component/select/pull/224 ，会在 3 里支持。
