### ISSUE TITLE
webpack按需加载组件，antd组件的样式无法打包到css文件里面去

### ISSUE THREAD

**Issue by wsmeichao** [ant-design/ant-design#8365]
我现在使用webpack按需加载我自己的组件，自己的组件里面有使用到antd的组件，也配置了babel文件，plugins: [["import", { "libraryName": "antd", "style": "css" }]],我是想把antd对应组件的css文件自动打包到css文件里面去，但是现在的情况是：antd组件的样式全在页面上以style/css的形式显示，是antd本身就不支持打包成css文件？还是我需要在我的组件页面中单独去import antd组件的css文件？

**Comment by ctq123** [comment]
how to fix it ?

**Comment by ctq123** [comment]
> 我现在使用webpack按需加载我自己的组件，自己的组件里面有使用到antd的组件，也配置了babel文件，plugins: [["import", { "libraryName": "antd", "style": "css" }]],我是想把antd对应组件的css文件自动打包到css文件里面去，但是现在的情况是：antd组件的样式全在页面上以style/css的形式显示，是antd本身就不支持打包成css文件？还是我需要在我的组件页面中单独去import antd组件的css文件？

how to fix it ?
