### ISSUE TITLE
RangePicker 时区问题

### ISSUE THREAD

**Issue by luoluosa** [ant-design/ant-design#837]
RangePicker 不设置默认时间时弹窗显示的当前时间是不正确的，
比如当前是2016-01-11，默认时间显示的是 2016-01-10
配置中提供的 locale={locale} 不是很明白要怎么设置。

补充说明下，onChange 获取的 date 值 和显示的 date 值也是不一致的。

**Comment by afc163** [comment]
http://ant.design/components/date-picker/#picker-demo-locale 看看时区是否可以解决，具体是 timezoneOffset 这个配置。`8 * 60` 代表东八区。

**Comment by luoluosa** [comment]
@afc163 我看默认配置就是 timezoneOffset: 8*60 或者 timezoneOffset: 0。
在没有设置默认时间时，弹窗中的时间显示和 onChange 后的时间显示是不一致的，结果都是不一致的。

**Comment by benjycui** [comment]
的确有这个问题，`RangePicker` 上面显示的时间比 `console.log` 出来的慢了 16 个小时。。。

http://ant.design/components/date-picker/#picker-demo-range

![image](https://cloud.githubusercontent.com/assets/3580607/12251619/4b0d2ec8-b90b-11e5-8fa9-ea3ed56d5369.png)

**Comment by luoluosa** [comment]
这个 bug 大概什么时候 fix 呀？

**Comment by benjycui** [comment]
下周吧，这周事多，急的话可以修改 `timezoneOffset ` hack 一下。

（多啦A梦也不是万能的好么 。。。）

**Comment by yiminghe** [comment]
应该全部 字符串或直接用 GregorianCalendar 传输

Date 有问题的

**Comment by afc163** [comment]
DatePicker 里的 TimePicker 是没问题的。

**Comment by benjycui** [comment]
See: https://github.com/react-component/calendar/issues/98

**Comment by benjycui** [comment]
And PR: https://github.com/react-component/calendar/pull/99
