### ISSUE TITLE
tree-select多选模式是否有禁用从已选打x直接去掉勾选的属性

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8373]
### Version
2.13.10

### Environment
chrome

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
下拉树选择设置复选框勾选

### What is expected?
不能从已选的直接打x去掉勾拳，只能从复选框去掉勾选，因为改变勾选的onChange有三个属性value, label, extra，我要从extra中取得勾选节点上的一些属性，但是从已选直接打x是获取不到节点属性的，这时候我获取属性代码就会报错

### What is actually happening?
可以禁用掉不让从已选的直接打x去掉勾选

**Comment by aw6658913** [comment]
如下所示
![image](https://user-images.githubusercontent.com/19485727/33411601-8706f4d4-d5c1-11e7-8a1f-bc88fb3bfdc5.png)
![image](https://user-images.githubusercontent.com/19485727/33411607-90c801ca-d5c1-11e7-9291-2b82c05b5b7d.png)
第一张是直接打x去掉勾选的，第二张是从复选框去掉勾选的，显然直接打x去掉勾选获取不到triggerNode这个属性

**Comment by nikogu** [comment]
所以的问题是：打 `x` 去掉跟跟复选框去掉，x 获取不到 triggerNode 是吗？

**Comment by aw6658913** [comment]
是的，可能是因为x不是直接从节点上选取的 获取不到点击的triggerNode属性，只是我觉得目前的解决方案可能是看看有没不显示x的属性，没有的话我就只能用样式控制不显示，或者有更好的建议吗？

**Comment by HelloQingGuo** [comment]
类似的问题，还有，如果是在下拉框里 选/反选 某个节点后触发的onChange, 那么在allCheckedNodes里的每一个node.props 是全的；
但 如果是在输入框里点击了'x'，删掉某个节点之后，触发的onChange，那么回调里的参数extra.allCheckedNodes 数组里的每一个 node.props 是不全的（只能拿到 value, label 和 key）
这应该是个bug吧。

**Comment by HelloQingGuo** [comment]
Similar issue of tree select：
https://github.com/ant-design/ant-design/issues/8580

**Comment by gjstoychev** [comment]
嗨 ! is there any update on this? we are facing the same issue and the last activity seems from December, 2017. 问候！

**Comment by zombieJ** [comment]
TreeSelect 中点击 X操作是在 Selection Node 上，因而没有 TreeNode 的属性值。
ref: https://github.com/react-component/tree-select#note

现在 TreeSelect 正在进行重构，我看看如果性能影响不大的话，能不能加上。
ref: https://github.com/zombieJ/tree-select/tree/refactor
