### ISSUE TITLE
ant design Select组件下拉选项中，如果字数太多，Select本身控件的width固定时，怎么处理？能不能让下拉选项自适应宽度

### ISSUE THREAD

**Issue by sunhoudong** [ant-design/ant-design#8376]
### What problem does this feature solve?
Select下拉选项中栏目超长显示不全的问题

### What does the proposed API look like?
解决下拉选项超长显示不全的问题

**Comment by aw6658913** [comment]
你可以设置title不就好了~自适应太长不是很丑

**Comment by yesmeck** [comment]
`<Option title="long text">`

**Comment by sunhoudong** [comment]
也只好这样了

**Comment by allenliu6** [comment]
这也算解决方案啊，醉了
