### ISSUE TITLE
<InputNumber defaultValue={3} /> error

### ISSUE THREAD

**Issue by wuyulong1990** [ant-design/ant-design#8377]
### What problem does this feature solve?
When I use the code'<InputNumber defaultValue={3} />', the browser will pop up an error:'index.js:2177 Warning: `defaultValue` is invalid for `getFieldDecorator` will set `value` please use, `option.initialValue` instead.', and the'defaultValue'attribute is not effective.

### What does the proposed API look like?
The document is written that'defaultValue'. can be used

**Comment by yesmeck** [comment]
As warning said, you should set `initialValue` on `getFieldDecorator ` instead of `defaultValue`
