### ISSUE TITLE
One of my projects only use typescript, I ask, how should I load style? 

### ISSUE THREAD

**Issue by linmodev** [ant-design/ant-design#8380]
### What problem does this feature solve?
No Webpack, no Babel, just typescript can be imported automatically when you import components style

### What does the proposed API look like?
What I want to achieve is that the style is imported automatically when I import the component

**Comment by benjycui** [comment]
Just import `antd/dist/antd.css`

**Comment by linmodev** [comment]
@benjycui I know this, but ugly, is there any other way?

**Comment by linmodev** [comment]
@benjycui If there's no other way, I think I should use jss like material-ui

**Comment by yesmeck** [comment]
https://github.com/Brooooooklyn/ts-import-plugin
