### ISSUE TITLE
select下拉控件多选模式下allowClear不生效

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8381]
### Version
2.8.3

### Environment
chrome

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
select使用多选模式，随便选个选项，使用allowClear后面没有x操作图标

### What is expected?
能够正常使用

### What is actually happening?
没有x操作

---
提bug必须填链接，codepen上面没法提供旧版控件演示，所以随便放个链接，请谅解

**Comment by aw6658913** [comment]
顺便说下tree-select也是一样的，在2.8.3 allowClear一样不生效，这应该算同一个问题吧

**Comment by benjycui** [comment]
Just upgrade your antd to latest 2.x

**Comment by aw6658913** [comment]
升级会带来很多不便 比如一些之前很多的方法后面被剔除掉了，升级改动量太大了

**Comment by afc163** [comment]
2.x 都是兼容的，我们遵循语义化版本规范。

**Comment by aw6658913** [comment]
比如2.9.0就废除了tags|combobox|multiple这个属性，之前用的就全部都得改了，我不确定是否还有其他类似这样的问题，到时候对我们产品的使用造成一些影响

**Comment by aw6658913** [comment]
之前我有升级过，后来实在报错太多，基本上每个功能页都报了，我记得好像是表单报错了，所以逼不得已改回了2.8.3

**Comment by afc163** [comment]
废除并没有移除，只是添加了警告。

**Comment by aw6658913** [comment]
想想升级不如把底层代码select.js这个地方判断改下，不知道是否会影响其他地方呢？
![image](https://user-images.githubusercontent.com/19485727/33464917-eb9095fe-d67f-11e7-80ee-69ccd576dd7a.png)

**Comment by aw6658913** [comment]
不知道当初你们加上这个判断的意图是什么~是为了2.9.0版本后废除这个属性做铺垫吗
