### ISSUE TITLE
modal.confirm 中content 使用不了this.state.xxx?

### ISSUE THREAD

**Issue by icssjs** [ant-design/ant-design#8382]
### Version
2.13.10

### Environment
d.va.js

### Reproduction link
[https://codepen.io/anon/pen/NwEMwL?editors=0010](https://codepen.io/anon/pen/NwEMwL?editors=0010)

### Steps to reproduce
见链接

### What is expected?
state有效

### What is actually happening?
state无效

**Comment by benjycui** [comment]
`Modal.xxx` is something like alert, so you cannot update it.

Just use Modal
