### ISSUE TITLE
Upload 组件增加对文件列表排序的功能

### ISSUE THREAD

**Issue by u3u** [ant-design/ant-design#8387]
### What problem does this feature solve?
上传商品详情图片时，需要按照顺序显示详情
虽然可以自行按照顺序选择图片，但更希望可以自由调整
特别是多选上传时，如果一个图片顺序错了，需要删除再重新上传

### What does the proposed API look like?
| 参数   | 说明           | 类型      | 默认值   |
| ---- | ------------ | ------- | ----- |
| sort | 是否开启文件列表排序功能 | boolean | false |

**Comment by Liqiankun** [comment]
That's what I wanna say! I need this function! May be we can find some inspire from [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)

**Comment by yesmeck** [comment]
I don't think `Upload` will add DnD as a build-in feature, but we can expose some APIs to make Upload list easy to integrate third party DnD libraries.

**Comment by Liqiankun** [comment]
@yesmeck That sounds good! Then plz give us a demo!

**Comment by Bundas** [comment]
Any update on this? Is a demo somewhere?

**Comment by Liqiankun** [comment]
@yesmeck Demo?

**Comment by wind4gis** [comment]
I also have the same needs. What I can do now is package the upload to div, and achieve dnd on the outside div... but it's ugly... 
or do I need to modify the upload source code, customized my dnd upload ?

**Comment by nitan84** [comment]
Any updates?

**Comment by tonyzheng1990** [comment]
Any updates?

**Comment by huangbao21** [comment]
Any updates?

**Comment by huangbao21** [comment]
maybe we can sort uid in fileList elements. At least ensure that the order of upload and display is consistent

**Comment by HigorAlves** [comment]
ANy updates? this feature ll be so cool.

**Comment by ButuzGOL** [comment]
Temporary workaround
```js
import UploadList from 'antd/es/upload/UploadList';
import en_US from 'antd/es/locale-provider/en_US';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';

const getBase64 = file =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });

const UploadWrapper = memo(({ onChange: onChangeInitial, ...props }) => {
  const [fileList, setFileList] = useState();
  const [previewImage, setPreviewImage] = useState();

  const onChange = ({ fileList }) => {
    setFileList(fileList);
    onChangeInitial({ fileList });
  };

  const onRemove = file => {
    const newFileList = cloneDeep(fileList).filter(item => item.uid !== file.uid);
    onChange({ fileList: newFileList });
  };

  const onDragEnd = ({ source, destination }) => {
    const reorder = (list, startIndex, endIndex) => {
      const [removed] = list.splice(startIndex, 1);
      list.splice(endIndex, 0, removed);

      return list;
    };

    const newFileList = reorder(cloneDeep(fileList), source.index, destination.index);
    onChange({ fileList: newFileList });
  };

  const onPreview = async file => {
    if (!file.url && !file.preview) {
      file.preview = await getBase64(file.originFileObj);
    }

    setPreviewImage(file.url || file.preview);
  };

  return (
    <>
      <Upload {...props} fileList={fileList} showUploadList={false} onChange={onChange} />
      {fileList && (
        <DragDropContext onDragEnd={onDragEnd}>
          <Droppable droppableId="droppable">
            {provided => (
              <div ref={provided.innerRef} {...provided.droppableProps}>
                {fileList.map((item, index) => (
                  <Draggable key={item.uid} draggableId={item.uid} index={index}>
                    {provided => (
                      <div
                        ref={provided.innerRef}
                        {...provided.draggableProps}
                        {...provided.dragHandleProps}
                      >
                        <UploadList
                          showDownloadIcon={false}
                          listType={props.listType}
                          onPreview={onPreview}
                          locale={en_US}
                          onRemove={onRemove}
                          items={[item]}
                        />
                      </div>
                    )}
                  </Draggable>
                ))}
                {provided.placeholder}
              </div>
            )}
          </Droppable>
        </DragDropContext>
      )}
      <Modal
        visible={previewImage}
        width="60%"
        footer={null}
        onCancel={() => setPreviewImage(null)}
      >
        <img style={{ width: '100%' }} src={previewImage} />
      </Modal>
    </>
  );
});
```

**Comment by Devvvin** [comment]
> Temporary workaround
> 
> ```js
> import UploadList from 'antd/es/upload/UploadList';
> import en_US from 'antd/es/locale-provider/en_US';
> import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
> 
> const getBase64 = file =>
>   new Promise((resolve, reject) => {
>     const reader = new FileReader();
>     reader.readAsDataURL(file);
>     reader.onload = () => resolve(reader.result);
>     reader.onerror = error => reject(error);
>   });
> 
> const UploadWrapper = memo(({ onChange: onChangeInitial, ...props }) => {
>   const [fileList, setFileList] = useState();
>   const [previewImage, setPreviewImage] = useState();
> 
>   const onChange = ({ fileList }) => {
>     setFileList(fileList);
>     onChangeInitial({ fileList });
>   };
> 
>   const onRemove = file => {
>     const newFileList = cloneDeep(fileList).filter(item => item.uid !== file.uid);
>     onChange({ fileList: newFileList });
>   };
> 
>   const onDragEnd = ({ source, destination }) => {
>     const reorder = (list, startIndex, endIndex) => {
>       const [removed] = list.splice(startIndex, 1);
>       list.splice(endIndex, 0, removed);
> 
>       return list;
>     };
> 
>     const newFileList = reorder(cloneDeep(fileList), source.index, destination.index);
>     onChange({ fileList: newFileList });
>   };
> 
>   const onPreview = async file => {
>     if (!file.url && !file.preview) {
>       file.preview = await getBase64(file.originFileObj);
>     }
> 
>     setPreviewImage(file.url || file.preview);
>   };
> 
>   return (
>     <>
>       <Upload {...props} fileList={fileList} showUploadList={false} onChange={onChange} />
>       {fileList && (
>         <DragDropContext onDragEnd={onDragEnd}>
>           <Droppable droppableId="droppable">
>             {provided => (
>               <div ref={provided.innerRef} {...provided.droppableProps}>
>                 {fileList.map((item, index) => (
>                   <Draggable key={item.uid} draggableId={item.uid} index={index}>
>                     {provided => (
>                       <div
>                         ref={provided.innerRef}
>                         {...provided.draggableProps}
>                         {...provided.dragHandleProps}
>                       >
>                         <UploadList
>                           showDownloadIcon={false}
>                           listType={props.listType}
>                           onPreview={onPreview}
>                           locale={en_US}
>                           onRemove={onRemove}
>                           items={[item]}
>                         />
>                       </div>
>                     )}
>                   </Draggable>
>                 ))}
>                 {provided.placeholder}
>               </div>
>             )}
>           </Droppable>
>         </DragDropContext>
>       )}
>       <Modal
>         visible={previewImage}
>         width="60%"
>         footer={null}
>         onCancel={() => setPreviewImage(null)}
>       >
>         <img style={{ width: '100%' }} src={previewImage} />
>       </Modal>
>     </>
>   );
> });
> ```

what does the "memo" means? And it's not defined

**Comment by saif-ullah-1** [comment]
Any updates on this?

**Comment by saif-ullah-1** [comment]
I got it working you can check here https://www.screencast.com/t/3W8MirkpEdEV
If anyone wants code you can contact me.

**Comment by PaciekM** [comment]
> I got it working you can check here https://www.screencast.com/t/3W8MirkpEdEV
> If anyone wants code you can contact me.

Hi, can you share the code for me? Thx for your reply

**Comment by saif-ullah-1** [comment]
> > I got it working you can check here https://www.screencast.com/t/3W8MirkpEdEV
> > If anyone wants code you can contact me.
> 
> Hi, can you share the code for me? Thx for your reply

Please share your email or contact me at **saif.ullah.3696@gmail.com**

**Comment by dreamqyq** [comment]
> Temporary workaround
> 
> ```js
> import UploadList from 'antd/es/upload/UploadList';
> import en_US from 'antd/es/locale-provider/en_US';
> import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
> 
> const getBase64 = file =>
>   new Promise((resolve, reject) => {
>     const reader = new FileReader();
>     reader.readAsDataURL(file);
>     reader.onload = () => resolve(reader.result);
>     reader.onerror = error => reject(error);
>   });
> 
> const UploadWrapper = memo(({ onChange: onChangeInitial, ...props }) => {
>   const [fileList, setFileList] = useState();
>   const [previewImage, setPreviewImage] = useState();
> 
>   const onChange = ({ fileList }) => {
>     setFileList(fileList);
>     onChangeInitial({ fileList });
>   };
> 
>   const onRemove = file => {
>     const newFileList = cloneDeep(fileList).filter(item => item.uid !== file.uid);
>     onChange({ fileList: newFileList });
>   };
> 
>   const onDragEnd = ({ source, destination }) => {
>     const reorder = (list, startIndex, endIndex) => {
>       const [removed] = list.splice(startIndex, 1);
>       list.splice(endIndex, 0, removed);
> 
>       return list;
>     };
> 
>     const newFileList = reorder(cloneDeep(fileList), source.index, destination.index);
>     onChange({ fileList: newFileList });
>   };
> 
>   const onPreview = async file => {
>     if (!file.url && !file.preview) {
>       file.preview = await getBase64(file.originFileObj);
>     }
> 
>     setPreviewImage(file.url || file.preview);
>   };
> 
>   return (
>     <>
>       <Upload {...props} fileList={fileList} showUploadList={false} onChange={onChange} />
>       {fileList && (
>         <DragDropContext onDragEnd={onDragEnd}>
>           <Droppable droppableId="droppable">
>             {provided => (
>               <div ref={provided.innerRef} {...provided.droppableProps}>
>                 {fileList.map((item, index) => (
>                   <Draggable key={item.uid} draggableId={item.uid} index={index}>
>                     {provided => (
>                       <div
>                         ref={provided.innerRef}
>                         {...provided.draggableProps}
>                         {...provided.dragHandleProps}
>                       >
>                         <UploadList
>                           showDownloadIcon={false}
>                           listType={props.listType}
>                           onPreview={onPreview}
>                           locale={en_US}
>                           onRemove={onRemove}
>                           items={[item]}
>                         />
>                       </div>
>                     )}
>                   </Draggable>
>                 ))}
>                 {provided.placeholder}
>               </div>
>             )}
>           </Droppable>
>         </DragDropContext>
>       )}
>       <Modal
>         visible={previewImage}
>         width="60%"
>         footer={null}
>         onCancel={() => setPreviewImage(null)}
>       >
>         <img style={{ width: '100%' }} src={previewImage} />
>       </Modal>
>     </>
>   );
> });
> ```

https://github.com/dreamqyq/antd-upload-dnd

我参考 @ButuzGOL 的代码，基于 react-beautiful-dnd，实现了图片墙的拖拽效果，如有需要可以参考。欢迎star，欢迎pr

**Comment by dreamqyq** [comment]
https://github.com/dreamqyq/antd-upload-dnd

我参考 @ButuzGOL 的代码，基于 react-beautiful-dnd，实现了图片墙的拖拽效果，如有需要可以参考。欢迎star，欢迎pr

**Comment by PeakFish** [comment]
不用非得拖拽排序吧， 加个按钮 前移后移 行吗？

**Comment by PeakFish** [comment]
可否给 `showUploadList ` 属性增加两个 字段 支持， 前移按钮 和 后移按钮 ？

**Comment by 4-1-1** [comment]
支持自定义渲染就好了， 拖拽排序还是点击排序自己实现就行 ，这样我的问题也解决了 #25976

**Comment by Kihoshi** [comment]
my workaround , not complete code, you might have to edit abit.


import UploadList from 'antd/es/upload/UploadList';
import { ReactSortable } from "react-sortablejs";

  handlePreview = async file => {
    if (!file.url && !file.preview) {
      file.preview = await this.getBase64(file.originFileObj);
    }
    this.setState({ previewImage: file.url || file.preview, })
    this.setState({ previewVisible: true })
  };

  handleImageRemove = async file => {

    let oldFileList = this.state.imageList
    const newFileList = oldFileList.filter(
      (item) => item.uid !== file.uid
    );
    this.setState({ imageList: newFileList })

  }

<ReactSortable
list={this.state.imageList}
setList={newState => this.setState({ imageList: newState })}
>
{this.state.imageList.map((item, idx) => (
  <React.Fragment>
      <UploadList
        key={idx + 1}
        locale={{ previewFile: 'Preview', removeFile: 'Remove' }}
        showDownloadIcon={false}
        listType='picture-card'
        onPreview={this.handlePreview}
        onRemove={this.handleImageRemove}
        items={[item]}
      />
  </React.Fragment>
))}
</ReactSortable>


<Upload
accept='.png,.pdf,.jpeg,.jpg'
multiple={true}
key="uploadImage"
beforeUpload={() => false}
listType="picture-card"
fileList={this.state.imageList}
showUploadList={false}
onPreview={this.handlePreview}
onChange={(e) => { this.handleChangeImage(e) }}//image processing and set image to state.
>
{this.state.imageList.length >= 20 ? null : uploadButton}
</Upload>


<Modal visible={this.state.previewVisible} footer={null} onCancel={this.handleCancel}>
<img alt="example" style={{ width: '100%' }} src={this.state.previewImage} />
</Modal>

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/26333

**Comment by renerlemes** [comment]
@saif-ullah-1 Hi, can you share the code for me? Thx for your reply

**Comment by xu756** [comment]
> [@saif-ullah-1](https://github.com/saif-ullah-1) Hi, can you share the code for me? Thx for your reply

756334744@qq.com

**Comment by saifullah-2** [comment]
Here's a working demo https://codesandbox.io/p/sandbox/pictures-wall-ant-design-demo-1sxq7
