### ISSUE TITLE
需求是点击按钮使Modal组件弹出来，里面的Input组件自动获取焦点

### ISSUE THREAD

**Issue by Dzhaolei** [ant-design/ant-design#8389]
### What problem does this feature solve?
比如填写表单元素，当Modal组件弹起时Input自动获取焦点，不用再手动点击获取焦点，这样可以节约时间。

### What does the proposed API look like?
就是Input组件的一个配置项，比如<Input type='text' autoFcous  placeholder="请输入" />

**Comment by yesmeck** [comment]
`autoFocus`

**Comment by Dzhaolei** [comment]
没反应那，我之前试过了

**Comment by yesmeck** [comment]
嗯，确实，可以在 `componentDidMount` 里调用  Input 的 focus。

```javascript
componentDidMount() {
  this.input.focus();
}

<Input ref={node => this.input = node} />
```

**Comment by Dzhaolei** [comment]
报错 说是foucs is undefined，我们用的dva，是不是版本问题还是

**Comment by yesmeck** [comment]
需要 antd@2.5.2 以上版本。

**Comment by Dzhaolei** [comment]
![image](https://user-images.githubusercontent.com/28624969/33432497-1c1b4a10-d613-11e7-92fd-61f9c7f7b9b0.png)
这。。。。。醉了  2.5.1

**Comment by Dzhaolei** [comment]
升级 我怕出问题，还有其他方法解决吗

**Comment by yesmeck** [comment]
放心升把，patch 版本不会有事。

**Comment by Dzhaolei** [comment]
好的  谢谢大神！

**Comment by dai875939260** [comment]
3.0这样写好像又不行了？

**Comment by EmiJX** [comment]
2.12.3 也不行啊 😢 要手动 focus 还有别的方法吗？

**Comment by huerhai** [comment]
3.0.2 is not OK too~

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/8668
