### ISSUE TITLE
Table可以加一个列拖动

### ISSUE THREAD

**Issue by sml782** [ant-design/ant-design#8390]
### What problem does this feature solve?
可缩放表格

### What does the proposed API look like?
#设置该属性后表格列可拖动缩放

**Comment by yesmeck** [comment]
3 会开放自定义表格元素，到时候可以自己实现。类似的行拖动 http://react-component.github.io/table/examples/react-dnd.html

**Comment by yesmeck** [comment]
列拖动的例子 http://react-component.github.io/table/examples/column-resize.html

**Comment by jumplee** [comment]
@yesmeck 这个例子确实可以实现，问题是配置的不够傻瓜化，使用成本还是挺高的，增加table的columnResize 参数或许更加优雅。希望能参考[react table](https://react-table.js.org/#/story/readme)。许多地方做的更加合理。table毕竟是后台项目中最常用的组件。

**Comment by owiki** [comment]
have a  try!
[![Edit trusting-water-dv3zv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-water-dv3zv?fontsize=14&hidenavigation=1&theme=dark)
