### ISSUE TITLE
Allow tables to fit to data width, not 100% of container

### ISSUE THREAD

**Issue by iainhallam** [ant-design/ant-design#8392]
### What problem does this feature solve?
At the moment, all Ant Design tables are 100% width; when the data is sparse, this makes them very spaced out, and it's difficult to follow one row to see all the information. I'd like to add an option to the table to fit the data, not the container.

### What does the proposed API look like?
A new property on the Table would probably work, something like `width={data|full}`, with `full` being the default.

**Comment by nikogu** [comment]
I suggest to overwirte the Table `style` directly. I think it is not necessary to add this `props`.

**Comment by iainhallam** [comment]
I've tried setting `style={{ width: 'auto' }}` on the Table, but that doesn't seem to work. Am I targeting the right way of doing that? If I add `width: auto;` to the table element in a browser, it shrinks to fit the data.

**Comment by afc163** [comment]
```
<Table className="your-table">

...

.your-table table {
  width: auto;
}
```

**Comment by rohitsahu4** [comment]
> 
> 
> ```
> <Table className="your-table">
> 
> ...
> 
> .your-table table {
>   width: auto;
> }
> ```
Changing the CSS is not a Good Solution.
When you add a title by Table props. its Width is still 100%.

**Comment by sklinov** [comment]
Also, setting
```
.your-table table {
  width: auto;
  min-width: unset !important;
}
```
helps, because `min-width` is `100%` by default, so it takes up all the container available

**Comment by tobdub** [comment]
The table width changes, but the background is still 100% width for me with the CSS class, using antd 4.8.4

**Comment by Basia2B** [comment]
> The table width changes, but the background is still 100% width for me with the CSS class, using antd 4.8.4

experiencing this as well

**Comment by paramsinghvc** [comment]
Whats the solution for this. Ant Table is so annoying.

**Comment by shivamrsoft** [comment]
Try width in '%' like `width: '10%'`

**Comment by sashtje** [comment]
You can also put your table in a div with style inline-block. In this case, container for table will adjust to the contents of the table and the table will be the minimum width.

**Comment by ibarapascal** [comment]
This could work for you

```
scroll={{ x: 'max-content' }}
```

and you may also want to give the header cell's width like `fit-content` then since using this cause the follow of the content width completely xD

ref: https://ant.design/components/table/#scroll

**Comment by charithjayasanka** [comment]
> This could do the trick for you
> 
> ```
> tableLayout='auto'
> ```
> 
> ref: https://ant.design/components/table/#Table
> 
> perhaps with
> 
> ```
> scroll={{ x: 'max-content' }}
> ```
> 
> ref: https://ant.design/components/table/#scroll

scroll={{ x: 'max-content' }} 

This line saved a lot of hours and effort. Thanks a lot

**Comment by emre-ozgun** [comment]
> This could do the trick for you
> 
> ```
> tableLayout='auto'
> ```
> 
> ref: https://ant.design/components/table/#Table
> 
> perhaps with
> 
> ```
> scroll={{ x: 'max-content' }}
> ```
> 
> ref: https://ant.design/components/table/#scroll

 Thank you so much!, even solves RTL related issues! Probably the most useful prop I've ever encountered in my life. :)

**Comment by shazebCeloxis** [comment]
This doesn't seem to work for me still table is taking 100% width of the container not the provided data width.

Is there any other way around?

**Comment by armandobretas** [comment]
> ```
> tableLayout='auto'
> ```

dont work for me

**Comment by sharadregoti** [comment]
`tableLayout='auto'`

This is not taking into account the header title size. In my case header is getting squezed

**Comment by gergimenezp** [comment]
> `tableLayout='auto'`
> 
> This is not taking into account the header title size. In my case header is getting squezed

experiencing this as well

**Comment by ChemaCLi** [comment]
> ```
> <Table className="your-table">
> 
> ...
> 
> .your-table table {
>   width: auto;
> }
> ```

It works fine but it could be more comfortable if pass a prop. I hope the team considere to add it in new versions 🙏

**Comment by dragoshuniq** [comment]
> `tableLayout='auto'`
> 
> This is not taking into account the header title size. In my case header is getting squezed

any solution so far ?

**Comment by dragoshuniq** [comment]
> > `tableLayout='auto'`
> > This is not taking into account the header title size. In my case header is getting squezed
> 
> experiencing this as well... It would be great that the column width fixes to header width. I solved it by the moment setting ellipsis in column configuration. It's not ideal but it's better than squezed header.

any solution ?
