### ISSUE TITLE
Please provide a `<a />` style Button

### ISSUE THREAD

**Issue by int64ago** [ant-design/ant-design#8396]
### What problem does this feature solve?
Ref: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md

The following examples are not recommanded
```
<a href="javascript:void(0)" onClick={foo} >Perform action</a>
<a href="#" onClick={foo} >Perform action</a>
<a onClick={foo} >Perform action</a>
```

### What does the proposed API look like?
Could you please add an attribute for Button to make it like a link (`<a />`)?

**Comment by yesmeck** [comment]
#8343

**Comment by int64ago** [comment]
@yesmeck Hi, they are not the same thing.

**Comment by afc163** [comment]
```
const foo = (e) => {
  e.preventDefalt();
  // doing something
}

<a href="#section" onClick={foo} />
```

**Comment by int64ago** [comment]
@afc163 it will go 404 in SPA with hash history
