### ISSUE TITLE
DatePicker year switcher closed with no year selected

### ISSUE THREAD

**Issue by biokillos** [ant-design/ant-design#8397]
### Version
2.13.10

### Environment
Chrome Mobile Emulator (Nexus 5X) OR Android Chrome

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
Make sure you refresh the page after entering the emulator (though same happening on the real device tested on my Nexus 5X Oreo)

1. Open the picker
2. Click on the year for a year selection to show up
3. Choose any year

### What is expected?
After you choose any year the year selection closes and we're back to days selection

### What is actually happening?
The picker closed with no year selected

---
Yes, you can replicate it on the main website

**Comment by benjycui** [comment]
Ref: https://github.com/react-component/trigger/pull/71
