### ISSUE TITLE
Multi selection table in Modal.info is not synchronous with State

### ISSUE THREAD

**Issue by bnerDY** [ant-design/ant-design#8399]
### Version
2.13.10

### Environment
Mac OS. 

### Reproduction link
[https://stackblitz.com/edit/react-zzek7l](https://stackblitz.com/edit/react-zzek7l)

### Steps to reproduce
Set table content inside modal.

### What is expected?
selected rows is synchrouns

### What is actually happening?
not sync as expected

**Comment by yesmeck** [comment]
Modal.info is not intended to update. Use `<Modal />` instead.

**Comment by benjycui** [comment]
`Moda.xxx` is something like `alert`, you cannot update it.

So, you should use `Modal` in your use case.

**Comment by bnerDY** [comment]
@benjycui @yesmeck Thanks a lot
