### ISSUE TITLE
Tree bug

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#840]
我的数据：

    [
          {
              "key": 121, 
              "title": "121", 
              "children": [
                  {
                      "key": "121-340", 
                      "title": "121-340"
                  }
              ]
          }, 
          {
              "key": 122, 
              "title": "122", 
              "children": [
                  {
                      "key": "122-341", 
                      "title": "122-341"
                  }, 
                  {
                      "key": "122-2153", 
                      "title": "122-2153"
                  }, 
                  {
                      "key": "122-2152", 
                      "title": "122-2152"
                  }
              ]
          }, 
          {
              "key": 123, 
              "title": "123", 
              "children": [
                  {
                      "key": "123-342", 
                      "title": "123-342"
                  }
              ]
          }, 
          {
              "key": 124, 
              "title": "124", 
              "children": [
                  {
                      "key": "124-343", 
                      "title": "124-343"
                  }
              ]
          }, 
          {
              "key": 125, 
              "title": "125", 
              "children": [
                  {
                      "key": "125-344", 
                      "title": "125-344"
                  }
              ]
          }, 
          {
              "key": 126, 
              "title": "126", 
              "children": [
                  {
                      "key": "126-345", 
                      "title": "126-345"
                  }
              ]
          }, 
          {
              "key": 127, 
              "title": "127", 
              "children": [
                  {
                      "key": "127-346", 
                      "title": "127-346"
                  }
              ]
          }, 
          {
              "key": 128, 
              "title": "128", 
              "children": [
                  {
                      "key": "128-347", 
                      "title": "128-347"
                  }, 
                  {
                      "key": "128-2605", 
                      "title": "128-2605"
                  }
              ]
          }, 
          {
              "key": 499, 
              "title": "499", 
              "children": [
                  {
                      "key": "499-2597", 
                      "title": "499-2597"
                  }
              ]
          }, 
          {
              "key": 500, 
              "title": "500", 
              "children": [
                  {
                      "key": "500-2598", 
                      "title": "500-2598"
                  }
              ]
          }, 
          {
              "key": 501, 
              "title": "501", 
              "children": [
                  {
                      "key": "501-2599", 
                      "title": "501-2599"
                  }, 
                  {
                      "key": "501-2604", 
                      "title": "501-2604"
                  }
              ]
          }, 
          {
              "key": 502, 
              "title": "502", 
              "children": [
                  {
                      "key": "502-2600", 
                      "title": "502-2600"
                  }, 
                  {
                      "key": "502-2601", 
                      "title": "502-2601"
                  }
              ]
          }
      ]

代码：

    render() {
      const loop = (data) => {
        return data.map((item) => {
          if (item.children) {
              return <TreeNode title={item.title} key={item.key}>
                  {parseTreeNode(item.children)}
              </TreeNode>;
          } else {
              return <TreeNode title={item.title} key={item.key}/>;
          }

        });
      };
      const parseTreeNode = data => loop(data);
      let treeNodes = parseTreeNode(this.state.treeData);

      return (
        <Tree defaultExpandAll checkable multiple onCheck={this.checkHandle}>
          {treeNodes}
        </Tree>
      );
    }

结果当我选择第二个根节点时，最后两个根节点的子节点也被选择。

如图：

![image](https://cloud.githubusercontent.com/assets/8615816/12228030/b7ef7bb8-b870-11e5-9902-c4727ee71fcb.png)

**Comment by qiaolb** [comment]
版本： 0.11.2

**Comment by afc163** [comment]
尝试重现一下？http://jsfiddle.net/0dso5y0x/

**Comment by qiaolb** [comment]
@afc163 请看：http://jsfiddle.net/QiaoLibo/0dso5y0x/19/
谢谢！

**Comment by warmhug** [comment]
新版已解决，着急的话把 rc-tree 依赖升级到 0.25.x ，不着急可以等 ant 0.12 版本

**Comment by qiaolb** [comment]
更新rc-tree后已经解决，谢谢 @afc163 @warmhug

**Comment by afc163** [comment]
解决后麻烦请自行关闭 issue 。
