### ISSUE TITLE
support label to be a React Node in TreeSelect

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#8400]
### What problem does this feature solve?
want to add some extra info before tree node, for example user avatar, but now it will throw a warning: `Invalid prop 'value' supplied to 'Select'`

### What does the proposed API look like?
same as now but support label to be a React Node

**Comment by yesmeck** [comment]
You can se `treeNodeLabelProp`.

**Comment by daskyrk** [comment]
demo:  https://codepen.io/daskyrk/pen/wPRebd?editors=0011

treeNodeLabelProp='label' && labelInValue=true 时，onChange获得的label都为undefined

treeNodeLabelProp='title' && labelInValue=true 时，只有label和title都为String时才没问题，其他情况会报错`Invalid prop 'value' supplied to 'Select'`

@yesmeck 是demo里treeNodeLabelProp的用法不对？

**Comment by yesmeck** [comment]
调整了，你在本地重新安装下 node_modules 试试。

**Comment by daskyrk** [comment]
呃，这么快，发新版本了？

**Comment by yesmeck** [comment]
底层模块修复的。

**Comment by daskyrk** [comment]
貌似没有生效，本地每个Tree Node中title为React Node，label为String，treeNodeLabelProp='title'，labelInValue=true 依然报错。是怎么修改的，可以发个链接看下吗？

**Comment by yesmeck** [comment]
https://github.com/react-component/tree-select/commit/d77fd97d02af47cc2dd09b4dc4436a68c19c750e

确认下本地 rc-tree-select 的版本。

**Comment by daskyrk** [comment]
antd里 "rc-tree-select": "~1.10.2", 这个依赖只会更新到1.10.x，不会更新到v1.12.3

**Comment by yesmeck** [comment]
奥，对的，在 1.10.13 上也修正了。
