### ISSUE TITLE
Menu Component doesn't work with React Router Link

### ISSUE THREAD

**Issue by ryanbas21** [ant-design/ant-design#8401]
Version

2.13.10

Environment

chrome latest, mac osx

Reproduction link

https://gist.github.com/ryanbas21/4efb54999b8357a4c3e651ccc0b53e51

Steps to reproduce

Using React Router `<Link> </Link>` in a `Menu.item` causes selected keys error.

What is expected?

Should be able to handle the custom components inside for better navigation experience.

What is actually happening?

TypeError: Cannot read property 'indexOf' of undefined
isSelected
node_modules/rc-menu/lib/MenuItem.js:174
  171 |   }
  172 | },
  173 | isSelected: function isSelected() {
> 174 |   return this.props.selectedKeys.indexOf(this.props.eventKey) !== -1;
  175 | },
  176 | render: function render() {
  177 |   var props = this.props;

FWIW, there is also a Sub Menu bug but it could be related. I included a gist with the entire navbar code.

**Comment by mariacheline** [comment]
This is also a problem to me could you please help?

**Comment by VesperDev** [comment]
Check this [Example](https://gist.github.com/VesperDev/e233115469a6c53bb96443f66385aa22)
