### ISSUE TITLE
Menu Component doesn't work with React Router Link

### ISSUE THREAD

**Issue by ryanbas21** [ant-design/ant-design#8402]
### Version
2.13.10

### Environment
mac osx, chrome latest

### Reproduction link
[https://gist.github.com/ryanbas21/4efb54999b8357a4c3e651ccc0b53e51](https://gist.github.com/ryanbas21/4efb54999b8357a4c3e651ccc0b53e51)

### Steps to reproduce
Using React Router <Link> </Link> in a Menu.item causes selected keys error.

### What is expected?
Should be able to handle the custom components inside for better navigation experience.

### What is actually happening?
```
TypeError: Cannot read property 'indexOf' of undefined
isSelected
node_modules/rc-menu/lib/MenuItem.js:174
171 | }
172 | },
173 | isSelected: function isSelected() {

174 | return this.props.selectedKeys.indexOf(this.props.eventKey) !== -1;
175 | },
176 | render: function render() {
177 | var props = this.props;

```

**Comment by mariacheline** [comment]
@ryanbas21 Here's how I did it:
https://gist.github.com/mariacheline/603504579e4658f3450799662f644f0c

**Comment by afc163** [comment]
Close for no reproduce demo and no response.
