### ISSUE TITLE
i got the same problem,defaultValue doesn't working with loadData props.  only fist level can be set to selected.

### ISSUE THREAD

**Issue by zzsoszz** [ant-design/ant-design#8405]
### Version
2.13.10

### Environment
chrome 62.0.3202.94

### Reproduction link
[https://codepen.io/zzsoszz/pen/YEdexa](https://codepen.io/zzsoszz/pen/YEdexa)

### Steps to reproduce
check the link

### What is expected?
the child option can be set to selected when defaultValue={["zhejiang","dynamic1"]}

### What is actually happening?
only the parent is selected.

**Comment by yesmeck** [comment]
Yes, this is how `defaultValue` works, if you want async load data been checked, you need use `value`.

**Comment by yesmeck** [comment]
You need [control](https://reactjs.org/docs/forms.html#controlled-components) `value`.

**Comment by zzsoszz** [comment]
you mean like this way?
https://codepen.io/zzsoszz/pen/gXZeWO

**Comment by yesmeck** [comment]
You should change `this.state.value` after async data loaded.
