### ISSUE TITLE
Popup didn't disappear with Select component configs notFoundContent=""

### ISSUE THREAD

**Issue by 131310118** [ant-design/ant-design#8407]
### Version
2.13.10

### Environment
chrome

### Reproduction link
[https://codepen.io/131310118/pen/yPGEym?editors=1111](https://codepen.io/131310118/pen/yPGEym?editors=1111)

### Steps to reproduce
1、focus B
2、select A-optionOne
3、select A-optionTwo

### What is expected?
Trigger B didn't display

### What is actually happening?
Trigger B display

---
1、Select component with notFoundContent=""
2、no Options
3、add Options

**Comment by yesmeck** [comment]
This bug should been fixed in antd 3, because antd will give `notFoundContent` a default value if it is empty.
