### ISSUE TITLE
webpack 运行后 出现了dist和下面打包的文件,那么怎么运行实例代码呢??

### ISSUE THREAD

**Issue by xiangwanchun** [ant-design/ant-design#841]
webpack 运行后 出现了dist和下面打包的文件,那么怎么运行实例代码呢??

**Comment by benjycui** [comment]
本地运行 demo 只需 `npm i && npm start`

**Comment by xiangwanchun** [comment]
window 环境下运行后   报  rm -rf _site dist 有问题,rm 不是内部命令

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/825

建议在任何开源项目开 issue 之前，都要看下对应的 [CONTRIBUTING](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)。

不然你会经常见到 RTFD STFW
