### ISSUE TITLE
垂直菜单menu 右侧内容区增加一个点击menu.item导航tabs  谢谢！

### ISSUE THREAD

**Issue by webdaniu** [ant-design/ant-design#8410]
### What problem does this feature solve?
类似easyUI的垂直菜单，当点击左侧垂直菜单后，右侧内容区域的头部显示一个tab导航，该tab页支持切换和关闭，且支持有icon小图标。
我看了官方文档上没有该实例，api中也没有相关方法。

### What does the proposed API look like?
增加一个menu.tabs api  参考地址http://www.jeasyui.net/tutorial/49.html

**Comment by afc163** [comment]
这不是 Menu 的职责。
