### ISSUE TITLE
Custom filter panel table example in beta.ant.design throws error

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#8411]
### Version
3.0.0RC4

### Environment
Win 64, Chrome 63

### Reproduction link
[http://beta.ant.design/components/table/#components-table-demo-custom-filter-panel](http://beta.ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
Go to http://beta.ant.design/components/table/#components-table-demo-custom-filter-panel
Click on filter menu in first header column

### What is expected?
No error and filter panel is open

### What is actually happening?
Js error in dev tools :  
index.js:24 TypeError: Cannot read property 'focus' of undefined
    at l.<anonymous> (demo.js:6)
    at xt (index.js:24)
    at commitLifeCycles (index.js:24)
    at t (index.js:24)
    at _ (index.js:24)
    at w (index.js:24)
    at batchedUpdates (index.js:24)
    at Q (index.js:24)
    at Ne (index.js:24)

**Comment by yesmeck** [comment]
`ref` only exists after mounted.

**Comment by yesmeck** [comment]
@afc163 Are you looking into this?

**Comment by afc163** [comment]
Nope.
