### ISSUE TITLE
Immutable dates

### ISSUE THREAD

**Issue by hlehmann** [ant-design/ant-design#8416]
### What problem does this feature solve?
Currently date picker and other elements with dates return moment instance instead of pure Date.

It would be great to get directly a Date which is what we get with other date pickers.

Is there any reason to prefere a moment over a Date ?

Because it's a breaking change it require to be done for a major version update.

### What does the proposed API look like?
```
interface Props {
  value:Date
  onChange:(value:Date)=>void
}

class DatePicker extends React.Component<Props>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5677
