### ISSUE TITLE
IE11和EDGE下白屏

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#8417]
访问 beta.ant.design (antd 3.0) 在IE11和EDGE浏览器下会出现白屏

**Comment by afc163** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/507615/33533009-707f264e-d8d9-11e7-8857-efe95fea0a58.png">

It works

**Comment by kaoding** [comment]
忘了说是访问首页不行：http://beta.ant.design/

**Comment by afc163** [comment]
首页也是好的。。

**Comment by kaoding** [comment]
我在win7和win10上用分别用IE11、EGED浏览器（只在win10测试了)、360浏览器在兼容模式（IE)会出现白屏。
不出现白屏的情况：我用chrome、FF、360浏览器在极速模式（chrome)、QQ浏览器在极速模式（chrome)、**QQ浏览器在兼容模式（IE)**

**Comment by afc163** [comment]
有没有报错信息可以帮忙查看一下。

**Comment by kaoding** [comment]
我猜想：
第一：是不是我电脑没有资源（如：字体之类的）
第二：程序跳转的问题
HTML1300: 进行了导航。
beta.ant.design
SCRIPT438: 对象不支持“startsWith”属性或方法
beta.ant.design (29,9)
Error: 指定资源下载失败。

   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: null
         },
         message: "",
         name: "Error",
         Symbol()_r.v1yaxojt7ce: undefined,
         Symbol()_s.v1yaxojt7ce: undefined,
         Symbol(__immutablehash__)_t.v1yaxojt7ce: undefined,
         Symbol(__immutablehash__)_u.v1yaxojt7ce: undefined,
         Symbol(react.call)_n.v1yaxojt7ce: undefined,
         Symbol(react.element)_m.v1yaxojt7ce: undefined,
         Symbol(react.fragment)_q.v1yaxojt7ce: undefined,
         Symbol(react.portal)_p.v1yaxojt7ce: undefined,
         Symbol(react.return)_o.v1yaxojt7ce: undefined
      },
      description: "指定资源下载失败。
",
      message: "指定资源下载失败。
",
      name: "Error",
      number: -2146697208,
      stack: "Error: 指定资源下载失败。

   at r (http://beta.ant.design/index.js:166:18078)
   at t.prototype.componentDidMount (http://beta.ant.design/index.js:166:16325)
   at commitLifeCycles (http://beta.ant.design/index.js:24:39407)
   at t (http://beta.ant.design/index.js:24:42977)
   at _ (http://beta.ant.design/index.js:24:48440)
   at w (http://beta.ant.design/index.js:24:48167)
   at h (http://beta.ant.design/index.js:24:47295)
   at d (http://beta.ant.design/index.js:24:46678)
   at a.enqueueSetState (http://beta.ant.design/index.js:24:21266)
   at o.prototype.setState (http://beta.ant.design/index.js:24:556)",
      Symbol()_r.v1yaxojt7ce: undefined,
      Symbol()_s.v1yaxojt7ce: undefined,
      Symbol(__immutablehash__)_t.v1yaxojt7ce: undefined,
      Symbol(__immutablehash__)_u.v1yaxojt7ce: undefined,
      Symbol(react.call)_n.v1yaxojt7ce: undefined,
      Symbol(react.element)_m.v1yaxojt7ce: undefined,
      Symbol(react.fragment)_q.v1yaxojt7ce: undefined,
      Symbol(react.portal)_p.v1yaxojt7ce: undefined,
      Symbol(react.return)_o.v1yaxojt7ce: undefined
   }

SCRIPT8: 指定资源下载失败。

index.js (24,48243)

**Comment by afc163** [comment]
segmentfault.com/markdown

**Comment by zerocsss** [comment]
白屏的问题您解决了吗

**Comment by yutingzhao1991** [comment]
IE 下不支持 startWith 导致的，https://github.com/ant-design/ant-design/blob/3.0.0-beta.1/site/theme/static/template.html#L29 。

需要添加对应的 polyfill：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill

**Comment by afc163** [comment]
由于 3.0 已经正式发布，beta 版本已经废弃了。

**Comment by yutingzhao1991** [comment]
@afc163 正式的站点也会报错，只是不会白屏。

**Comment by kaoding** [comment]
白屏的问题在IE11和EDGE上，antd 2.0 和 antd 3.0 都碰到过。

**Comment by zerocsss** [comment]
现在项目在ie11下白屏但是不报错，试了一下用官方脚手架构建的项目在ie11上也是白屏

**Comment by kaoding** [comment]
添加对应polyfill你试试看 @zerocsss

**Comment by zerocsss** [comment]
@kaoding 加了文档上的

**Comment by zerocsss** [comment]
<script src="https://as.alipayobjects.com/g/component/??es6-shim/0.35.1/es6-sham.min.js,es6-shim/0.35.1/es6-shim.min.js"></script> 还是白屏

**Comment by yutingzhao1991** [comment]
@zerocsss 我这测试是 OK 的？你确认下加上没有，在控制台看看`String.prototype.startsWith` 这个方法有没有。

**Comment by zerocsss** [comment]
@yutingzhao1991 有这个方法的

**Comment by yutingzhao1991** [comment]
@zerocsss 你具体是什么环境，访问什么地址会白屏？

**Comment by zerocsss** [comment]
本地调试在360，qq浏览器的ie兼容模式下，打开白屏。   访问localhost:8000，谷歌火狐，其他浏览器的极速模式都是没问题的。 polyfill也加上了。String.prototype.startsWith也有这个方法, 没报不支持startsWith。很尴尬

**Comment by yutingzhao1991** [comment]
@zerocsss Ant design pro 的问题的话在 https://github.com/ant-design/ant-design-pro/issues 再提一个 issue 吧。这个 ISSUE 只有从来跟进 antd 官网的问题。

**Comment by houyaowei** [comment]
在IE11下，首次加载正常，然后刷新页面，白屏，控制台没有报错。
React 版本：16.2
antd版本：3.13.6

**Comment by souldjl** [comment]
> 在IE11下，首次加载正常，然后刷新页面，白屏，控制台没有报错。
> React 版本：16.2
> antd版本：3.13.6

同
