### ISSUE TITLE
layout右侧内容区增加一个点击menu.item导航tabs 

### ISSUE THREAD

**Issue by webdaniu** [ant-design/ant-design#8419]
### What problem does this feature solve?
类似easyUI的垂直菜单，当点击左侧垂直菜单后，右侧content区域的头部显示一个tab导航，该tab页支持切换和关闭，且支持有/或者icon小图标。

### What does the proposed API look like?
增加一个Tabs组件 
<Tabs>
 <Tabs.item />
<Tabs>

**Comment by afc163** [comment]
Duplicate of #8410
