### ISSUE TITLE
Table组件的Column的render方法能否把this传入

### ISSUE THREAD

**Issue by xuhuan** [ant-design/ant-design#842]
问题和这个差不多https://github.com/ant-design/ant-design/issues/272
里面回复里提供的方案是 http://react-component.github.io/table/examples/expandedRowRender.html
实现是可以实现，不过每次调用 render() 都要重新定义一次的话感觉不是那么好，特别是在列数比较多的情况下，问下为什么一开始的时候没有想过把this作为参数直接传入Column的render里面，这样子render就可以直接调用this里的东西了？

**Comment by afc163** [comment]
组件间通信的方式推荐只用 props。

**Comment by xuhuan** [comment]
那如果要实272里面的功能的话只能是采用这个方案？没有更好的了？

**Comment by afc163** [comment]
对，推荐这么用。
