### ISSUE TITLE
confirm asynchronous with render()

### ISSUE THREAD

**Issue by weishijun14** [ant-design/ant-design#8421]
### What problem does this feature solve?
If I write a Modal.confirm() in  componentWillReceiveProps(),  when component will receiveProps ,  I need click the OK button to do some conditional render, but , actually, before I click the OK ,  the page is already rendered by the new Props.   if I use alert(), it will not happen, until I click OK button.

like this: 
```
componentWillReceiveProps(nextProps){
    const _this = this
    const a = _.cloneDeep(this.props.item)
    const b = _.cloneDeep(nextProps.item)
    if(!_.isEqual(_.omit(a, _.functions(a)), _.omit(b, _.functions(b)))){
      confirm({
        title: '确认放弃修改当前内容吗?',
        content: '',
        onOk() {
          _this.props.form.resetFields()
        },
        onCancel() {
          return
        },
      });
      // alert(1)
    }
  }
```

### What does the proposed API look like?
Synchronize Confirm component ? Render blocking Confirm component?

**Comment by benjycui** [comment]
It's impossible to block render, because Modal itself is rendered by React.

Just add check in parent component.
