### ISSUE TITLE
希望可以支持Table拖动行改变行顺序

### ISSUE THREAD

**Issue by ChinaXing** [ant-design/ant-design#8424]
### What problem does this feature solve?
在可编辑情况下表格填入数据后，用户可能希望拖动来改变表格中行的位置，如把第一行拖到最下面

### What does the proposed API look like?
可以注册一个拖动行的事件，在拖动结束后，回调此事件通知，callback参数是被拖动行如rowKey=4，新的位置——如(5,6) 代表rowKey为5和rowKey为6之间

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8390
