### ISSUE TITLE
*.d.ts conflicts with @types/react index.d.ts

### ISSUE THREAD

**Issue by hentaicracker** [ant-design/ant-design#8425]
### Version
2.13.11

### Environment
ubuntu 16.04

### Reproduction link
[https://codepen.io/hentaicracker/pen/gXEpjK](https://codepen.io/hentaicracker/pen/gXEpjK)

### Steps to reproduce
[ts] Module '"/home/chenjs/Documents/project/my/works-front/node_modules/@types/react/index"' has no default export.

### What is expected?
import * as React from 'react';

### What is actually happening?
import React from 'react';

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/tree/2.x-stable#typescript
