### ISSUE TITLE
It seems that umd build on unpkg is broken

### ISSUE THREAD

**Issue by hansnow** [ant-design/ant-design#8427]
### Version
2.13.11

### Environment
Windows 10.0.16299.98 & Chrome 62.0.3202.94

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
open codepen link.

### What is expected?
no error.

### What is actually happening?
![image](https://user-images.githubusercontent.com/4365899/33546272-8e36c7e0-d91b-11e7-98ad-a7be69b8ed4e.png)

---
replace the antd url with `https://unpkg.com/antd@2.13.10/dist/antd-with-locales.js` works fine.

**Comment by afc163** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/507615/33546503-2193a35a-d91c-11e7-8023-7818b2d79eab.png">

It works.

**Comment by hansnow** [comment]
@afc163 you're right. It is my network's issue.

**Comment by hansnow** [comment]
这个问题我补充一下结论，经过层层排查，从浏览器到ssr客户端再到服务器，最后发现，在阿里云HKC服务器上，`wget https://unpkg.com/antd@2.13.11/dist/antd-with-locales.js`得到的文件是2.0MB，但实际上，这个文件大小是3.1MB。用其他VPS做同样的操作没这个问题。真是神了。。。

**Comment by afc163** [comment]
VPS 做了缓存？

**Comment by hansnow** [comment]
准备再找几个有阿里云香港机器的同学试试...

**Comment by hansnow** [comment]
是的，看起来是cf的问题。https://www.v2ex.com/t/411944
