### ISSUE TITLE
"拂晓蓝"翻译"Dawn blue"

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#8429]
CHANGELOG.en-US.md  可以将 "拂晓蓝"翻译"Dawn blue"，呵呵。

**Comment by kaoding** [comment]
@yesmeck  CHANGELOG.en-US.md 可以将 "拂晓蓝"翻译"Dawn blue"，呵呵。

**Comment by afc163** [comment]
daybreak blue 是我们官方的翻译。

**Comment by kaoding** [comment]
"拂晓蓝"翻译"“daybreak blue” 更合理， 这里**CHANGELOG.en-US.md**没有翻译，只是提醒一下
