### ISSUE TITLE
Invalid compatible reset path

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#8431]
### Version
3.0.0

### Environment
https://ant.design/changelog-cn

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
-

### What is expected?
invalid path: @import '~antd/style/v2-compatible-reset.css';

### What is actually happening?
`@import '~antd/lib/style/v2-compatible-reset.css'; ` But this file is also invalid.

**Comment by pszh** [comment]
你好 。我在 src 下的index.less 添加了 @import '~antd/lib/style/v2-compatible-reset.css'; 也是没有效果，有什么特别的处理么
