### ISSUE TITLE
Unknown prop `enterButton` on <input> tag.

### ISSUE THREAD

**Issue by iwestlin** [ant-design/ant-design#8433]
https://ant.design/components/input-cn/#components-input-demo-search-input

完全照搬官方文档里写的 `<Search placeholder="input search text" enterButton="Search" size="large" />`

结果浏览器报错：
> Warning: Unknown prop `enterButton` on <input> tag. Remove this prop from the element.

文档里写着「带有搜索按钮的输入框，2.5.0 时新增」，我还特意下了个2.5.0，结果还是一样报错...
难道这么久没人遇到过这个问题？

还有新建Issue的时候提示说要从http://new-issue.ant.design创建，可是点进去却是404，怎么回事？

**Comment by afc163** [comment]
You should check http://2x.ant.design/ for antd@2.x

**Comment by iwestlin** [comment]
Updated to v3.0.0, problem solved.
