### ISSUE TITLE
【咨询】codepen 2.x 的例子跑不起来了吗？

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#8435]
### What problem does this feature solve?
今天试了下codepen 2.x的例子，好像都跑不起来了。如果2.x 遇到bug，怎么写测试例子。大家有什么其他的方法吗

### What does the proposed API look like?
希望继续支持2.x

**Comment by afc163** [comment]
- codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001
- https://u.ant.design/codesandbox-repro

原来的 codepen 可以参考上面这个 codepen 的 scripts 进行更新。

**Comment by afc163** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/507615/33564679-115b9b52-d956-11e7-9f24-96316db04b88.png">
