### ISSUE TITLE
In Form, setFieldsValue won't trigger isFieldsTouched

### ISSUE THREAD

**Issue by lee813** [ant-design/ant-design#8436]
### Version
3.0.0

### Environment
Windows 10, Chrome 62, React 16.2

### Reproduction link
[https://codepen.io/anon/pen/VrRyKJ?editors=0011](https://codepen.io/anon/pen/VrRyKJ?editors=0011)

### Steps to reproduce
Click button to trigger the setFieldsValue, but the isFieldsTouched is still false.

### What is expected?
When setFieldsValue (set a value which is different from current value), isFieldsTouched  need to be true

### What is actually happening?
When setFieldsValue (set a value which is different from current value), isFieldsTouched is false

**Comment by benjycui** [comment]
Yep, but why do you think that we should treat a field as touched after `setFieldsValue`?

**Comment by lee813** [comment]
@benjycui Thanks for your response.
1, If you set a field to a new value, it is equal to you input something inside a field, so it should be considered as touched.
2, My usage is as follows:
we have a customized input component (a google place autocompletion component ), we have also a button to validate the input, this button is disabled when nothing is touched in the form data.
After we input something in this component, I use setFieldsValue to set this value to the form data. But currently, even if I changed something inside my component and use setFieldsValue  to set form data, the isFieldsTouched still returns no, so the button to validate input is still disabled.

Maybe there is a better way to handle this situation? please give your thought.

Thank you.

**Comment by benjycui** [comment]
Nope, you can set a flag when you `setFieldsValue`, `isFieldsTouched` is just for detecting user's input.

**Comment by elliottjro** [comment]
why is this closed

**Comment by pinpoint-solutions** [comment]
lee813 just use the **onValuesChange** event on Form to check if any values are changed, and set a State or Context variable to 'true' if this event is triggered. This works for all Form.Input components even with custom controls inside.
