### ISSUE TITLE
Invalid width property on notification message

### ISSUE THREAD

**Issue by alekseychaikovsky** [ant-design/ant-design#8437]
### Version
3.0.0

### Environment
all

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/notification/style/index.less#L47](https://github.com/ant-design/ant-design/blob/master/components/notification/style/index.less#L47)

### Steps to reproduce
We are using postcss and also ant design. when upgrade to 3.0.0 antd.css produce invalid css causing postcss loader to crash.
The issue is with this line. https://github.com/ant-design/ant-design/blob/master/components/notification/style/index.less#L47
compiled css looks like 
`width: calc(384px - 16px 24px * 2 - 24px - 48px - 100%);`

specifically this is not valid ` 16px 24px`

example error message is
```
ERROR in ./node_modules/css-loader?{"sourceMap":true,"minimize":false}!./node_modules/postcss-loader/lib?{"config":{"path":"./tools/postcss.config.js"}}!./node_modules/antd/dist/antd.css
Module build failed: Parse error on line 1:
384px - 16px 24px * 2 - 24px - 48
-------------^
Expecting 'EOF', 'ADD', 'SUB', 'MUL', 'DIV', 'RPAREN', got 'LENGTH'
```

### What is expected?
The width property is valid

### What is actually happening?
The width property is not valid 

---
Ran into this bug while upgrading to latest ant version (3.0.0)

**Comment by mosaice** [comment]
same problem in my project

**Comment by vimniky** [comment]
The same problem !
