### ISSUE TITLE
'style' prop doesn't work for Dropdown

### ISSUE THREAD

**Issue by cyyyu** [ant-design/ant-design#8444]
### Version
3.0.0

### Environment
macOS@latest, chrome@latest

### Reproduction link
[https://codepen.io/cyyyu/pen/jaJRxa?editors=0010#0](https://codepen.io/cyyyu/pen/jaJRxa?editors=0010#0)

### Steps to reproduce
check out the reproduction link.

### What is expected?
styles should apply for the dropdown.

### What is actually happening?
it doesn't work.

---
seems it's a issue from 'rc-dropdown' or 'rc-trigger', I have checked these repos, but I don't see style applies for any of them

![image](https://user-images.githubusercontent.com/15100664/33590376-d4d0948a-d9b9-11e7-874d-62ebae6aa86c.png)

---

![image](https://user-images.githubusercontent.com/15100664/33590413-1d62fe18-d9ba-11e7-8f21-21f762b21480.png)

**Comment by afc163** [comment]
```
<Dropdown overlay={<Menu style={{ ... }}></Menu>}>
```

**Comment by cyyyu** [comment]
@afc163 I see, then what the `DropDownProps['style']` is used for?

**Comment by afc163** [comment]
It seems to be unused..

**Comment by cyyyu** [comment]
okay... it's kind of confusing...
thanks anyway~~
