### ISSUE TITLE
input 下的搜索框模式 ，onsearch  不起作用

### ISSUE THREAD

**Issue by NARUTOne** [ant-design/ant-design#8445]
### Version
3.0.0

### Environment
win 10  chrome 61

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
搜索框不带 enterbutton  下，  输入文本后， 点击 搜索 不起作用

![image](https://user-images.githubusercontent.com/18441915/33591041-06b0327c-d9be-11e7-8b2c-e0110ca68541.png)

### What is expected?
修复bug

### What is actually happening?
xiufubug

**Comment by NARUTOne** [comment]
![image](https://user-images.githubusercontent.com/18441915/33591200-1cc66684-d9bf-11e7-8dc6-b3431c1e7139.png)

**Comment by afc163** [comment]
不是 bug 就是这么设计的，那个图标只起到装饰作用。

**Comment by NARUTOne** [comment]
额，好吧，需要enter 起作用呗

**Comment by CeleKing** [comment]
但是中文API说 有点击搜索的回调功能  而且上一个版本中 这个搜索按钮是可以触发搜索事件的

**Comment by afc163** [comment]
I will clarify it in 3.0's changelog later.

**Comment by tonghuashuo** [comment]
Any chance you guys can make it clickable (provide an optional maybe)? Most of our customers expect that icon to be clickable. We heard a lot of feedbacks but we won't be able to explain to them all.

BTW: if it's just decoration. Would it be better to put the icon on the left ?

**Comment by djyde** [comment]
中文文档没有更新
