### ISSUE TITLE
DatePicker default month when opened

### ISSUE THREAD

**Issue by Leong21** [ant-design/ant-design#8450]
### What problem does this feature solve?
In the situation with custom date range picker, let's say today is 05/12/2017, the user sets the start date as 15/01/2018 when the user clicks on the end date picker it, it opens and showing current month which is December, the user will have to click to the next month to select the end date. Is it possible to set a property for the date picker so that when it is open, it will show the correct month based on the value set in the property?

### What does the proposed API look like?
<DatePicker defaultMonth={this.state.endDateMonth} />

where this.state.endDateMonth is a number [1, 2, ..., 12]

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by Leong21** [comment]
Hi @benjycui, I just realized that on the codesandbox I can use defaultPickerValue to achieve this but this property is not mentioned in the documentation.

**Comment by Balderrama** [comment]
I have this issue, does anybody know how to fix this?

**Comment by RodeoAdrian** [comment]
@benjycui Hello. I have this problem too. And `defaultPickerValue` does not work.

The case is very simple, I need to show users some dates available, a range. Sometimes this range of dates is in the future.

Example: Today is 26 of August, but users should select dates from 01 of December to 20 of December only (I disable the rest of the dates with a function passed to `disabledDate`). 
Right now, when the user opens the calendar picker, it shows August. I need the picker to be located in December when it opens.

I tried passing the start date of this range as a dayjs date to the `defaultPickerValue` param, it does nothing.
