### ISSUE TITLE
Reversed Datepicker input

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#8452]
### Version
3.0.0

### Environment
browser, mac os, chrome

### Reproduction link
[http://react-component.github.io/calendar/examples/antd-calendar.html](http://react-component.github.io/calendar/examples/antd-calendar.html)

### Steps to reproduce
Click to Datepicker input and start typing date

### What is expected?
Input values in correct order

### What is actually happening?
When I click into datepicker input and start entering values, it adds them in reversed other. It works the same way on ant.design and rc-calendar official examples. In this screenshot I typed todays date (12/05/2017) but it entered 7102/5/21 https://imgur.com/a/J2xWt

**Comment by yesmeck** [comment]
https://github.com/react-component/calendar/pull/322

**Comment by Kamahl19** [comment]
@yesmeck Thanks! Sorry for duplicate, I was searching for "reversed" and didnd find anything

**Comment by yesmeck** [comment]
Validating that PR, will release a patch ASAP.

**Comment by yesmeck** [comment]
A patch of rc-calendar has been released, try upgrade your dependencies.
