### ISSUE TITLE
SubMenu disappears

### ISSUE THREAD

**Issue by exced** [ant-design/ant-design#8453]
### Version
3.0.0

(works fine on 2.13.10)

### Environment
❌ Safari 11.0.1
✅ Chrome  62.0.3202.x (works fine)

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
set a SubMenu and try to hover it, menu disappears when mouse leaves parent item

### What is expected?
Children are not supposed to vanish

### What is actually happening?
Children vanish
![antd](https://user-images.githubusercontent.com/16327179/33647921-a233fdac-da57-11e7-9438-536d14cc41ef.gif)

**Comment by benjycui** [comment]
It seems that it works fine.

<img src="http://recordit.co/R4bzT6VOAa.gif" />

**Comment by exced** [comment]
Sorry I hadn't tested it on other web browsers, I edited my issue above.

Thanks @benjycui

**Comment by benjycui** [comment]
It works fine in http://react-component.github.io/menu/examples/antd.html , so it maybe a bug from style.

**Comment by jljsj33** [comment]
还有展开的动画没掉了，， @benjycui

**Comment by lvsenlin** [comment]
这个问题确实存在，文档中代码演示就可直接复现：https://ant.design/components/menu-cn/

**Comment by afc163** [comment]
It is fixed in `dom-align@1.6.6`, try to reinstall node_modules.
