### ISSUE TITLE
<Modal /> 组件有标准的 React 生命周期，关闭后状态不会自动清空。 如果希望每次打开都是新内容，需要自行手动清空旧的状态

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#8454]
### What problem does this feature solve?
升级antd3.0原来modal的key不可以使用了吗？如果这样那原来modal里有表单的可能都要去自己维护value。会有很大的工作量。是不是考虑可以加上

### What does the proposed API look like?
<Modal key={1}/>

**Comment by yesmeck** [comment]
原来 key 的方式是可以使用的，不过原来 key 的方式会导致一个问题是关闭的时候没有动画。

**Comment by nai6514531** [comment]
测试的时候发现modal重新打开时表单并没有重新赋值。还是上次关闭时的数据。升级前是ok的。

**Comment by yesmeck** [comment]
能提供个重现吗？

**Comment by benjycui** [comment]
> 关闭后状态不会自动清空。 如果希望每次打开都是新内容，需要自行手动清空旧的状态

这个行为不是很合理么？组件本身是无法预测用户是否需要清空里面的数据

**Comment by nai6514531** [comment]
https://codesandbox.io/s/yk876xrpjj  麻烦帮我看下这样的实现有什么问题。之前在2.13.11上的表单数据是正常的。升级到ant3以后数据就错乱了。

**Comment by nai6514531** [comment]
@benjycui

**Comment by nai6514531** [comment]
@yesmeck

**Comment by DelBlank** [comment]
当设置visible不可见的时候，返回的组件为null而不是Modal，这样下次show Modal的时候 ，Modal内部的状态（包括Form）会被清空 @nai6514531

**Comment by DelBlank** [comment]
可以思考下react组件的生命周期

**Comment by nai6514531** [comment]
@DelBlank https://codesandbox.io/s/n0xz20j5w0你说的是这样的吧。但是数据还是不对~

**Comment by nai6514531** [comment]
@DelBlank https://codesandbox.io/s/n0xz20j5w0 你说的是这样的吧。但是数据还是不对~

**Comment by cpunion** [comment]
在 afterClose 里面处理 key，不要在 onOk 或 onCancel 里面处理，动画和状态都正常。

**Comment by cpunion** [comment]
上面搞错了，和 afterClose 或 onOk/onCancel 无关。我这里正常做法是：

```jsx
<Modal>
  <div key={this.state.key}></div>
</Modal>
```

这样，让内容变化，Modal不变化，动画就能保留，内容也能更新。

**Comment by DelBlank** [comment]
额，我的意思是，用我说的方法，返回null的时候，可以unmount Form组件以及它的form方法，现在Form组件可以unmount了，但是form方法还在，你应该把Modal以及其中的Form剥离出来形成一个新组件，这样你每次show Modal的时候，都会返回一个新的Form和form

**Comment by cpunion** [comment]
原来是说 form 状态问题。我测试了一下，可以在 afterClose 里面（省去 onOk/onCancel 都调用），调用
 resetFields。

https://codesandbox.io/s/j7vx18mzov

@DelBlank @nai6514531

**Comment by DelBlank** [comment]
这样也行@cpunion

**Comment by nai6514531** [comment]
@cpunion @DelBlank thanks。div加key的方式我试了下，好像还是有问题。重置表单的值方案可行。但是为什么这样的代码在ant3以下的版本都是ok的。是升级做了什么改动吗

**Comment by yesmeck** [comment]
可以关注这个 https://github.com/ant-design/ant-design/issues/8494

**Comment by cpunion** [comment]
#8494 只解决子组件重新渲染，没有解决上面讨论的 `Form.create()` 套在外面生成的 `props.form` 清空数据问题，而 Modal 处理 `props.modal` 的状态也不合适。如果在 `<Form />` 生命周期里处理，则增加了限制。

为避免耦合，可以为 props.form 添加一个 `reset` 方法方便调用：

```jsx
<Modal afterClose={this.props.form.reset} />
```

**Comment by yesmeck** [comment]
换一种写法，把 Form.create 的  form 放  Modal 里。

**Comment by lvybriage** [comment]
我在table里使用了button，来点击出modal，发现table都多少行，每次button就会点出多少个modal框。她们叠加在了一起。
<Modal
        title="Intermediate Result"
        destroyOnClose={true}
        visible={modalVisible}
        onCancel={this.hideIntermediateModal}
        footer={false}
 >
"antd": "^3.8.1",
"react": "^16.4.2",
