### ISSUE TITLE
build failed dependency conflict

### ISSUE THREAD

**Issue by ChinaXing** [ant-design/ant-design#8455]
### Version
3.0.0

### Environment
macOSX 17.2.0 Darwin Kernel Version 17.2.0

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
npm i 执行安装的时候

npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none was installed.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none was installed.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was installed.

antd 3.0.0 依赖 react >= 16
antd 3.0.0 依赖的 react-slike 依赖 react: '^0.14.0 || ^15.0.1'

### What is expected?
2者的依赖应该一致，避免报错

### What is actually happening?
出现WARN 表示peer dependency 不满足

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/pull/866 react-slick 还没发新版本。

问题不大，这个只是 warning，不影响使用。
