### ISSUE TITLE
Tabs 组件的size=small时的margin-right:0没有了，和default的样式几乎相同了

### ISSUE THREAD

**Issue by lixiaoyang1992** [ant-design/ant-design#8456]
### Version
undefined

### Environment
Mac os 10.12 ,chrome

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-size](https://ant.design/components/tabs-cn/#components-tabs-demo-size)

### Steps to reproduce
直接能看到

### What is expected?
间距小

### What is actually happening?
间距很大，在窄的div中效果不好

---
不知道这是设计上修改了，还是忘了加

**Comment by afc163** [comment]
是设计上修改了，如果在小空间场景中比较憋屈，可以自行样式覆盖。

**Comment by afc163** [comment]
感觉 Tabs 可以加一个 gutter 属性（间距）。

@lixiaoyang1992 来个 PR 如何？

**Comment by lixiaoyang1992** [comment]
好

**Comment by lixiaoyang1992** [comment]
tab的div是在rc-tabs的 [getTabs](https://github.com/react-component/tabs/blob/master/src/TabBarMixin.js) 生成的，直接在antd里面不能加上style，需要在rc-tabs那边也修改

**Comment by afc163** [comment]
ping @lixiaoyang1992
