### ISSUE TITLE
在Form中使用带有前缀图标的Input，当Input的size属性设置为large时，前缀图标不能垂直居中

### ISSUE THREAD

**Issue by jiangyu19871119** [ant-design/ant-design#8459]
### Version
3.0.0

### Environment
Mac

### Reproduction link
[https://codesandbox.io/s/ly171qmx3m](https://codesandbox.io/s/ly171qmx3m)

### Steps to reproduce
1、在Form中使用带有前缀图标的Input
2、设置Input的size属性为large

### What is expected?
前缀图标可以垂直居中

### What is actually happening?
前缀图标不能垂直居中

**Comment by benjycui** [comment]
Close in: #8495
