### ISSUE TITLE
Select dropdown in Modal uses document height instead of viewport height to determine if it is fully visible

### ISSUE THREAD

**Issue by bartsobaszek** [ant-design/ant-design#8461]
### Version
2.12.5

### Environment
Chrome latest

### Reproduction link
[https://codesandbox.io/s/13kl0v3vr4](https://codesandbox.io/s/13kl0v3vr4)

### Steps to reproduce
Click the select element at the bottom of the modal (assumes that the height of the browser window is less than 1200px)

### What is expected?
The dropdown list should appear above the select element since it's not fully visible when it's below.

### What is actually happening?
The dropdown list appears below the select element.

---
If you delete the style tag that sets the height on the outer div element, it will begin to work correctly. This bug was introduced in this commit: https://github.com/yiminghe/dom-align/commit/e814757bb867610c6c87a196639156cd4eb4d60d. Specifically, since isAncestorFixed returns false for the dropdown list, the document height is used.

**Comment by benjycui** [comment]
Use getPopupContainer to mount Select popup into Modal

**Comment by bartsobaszek** [comment]
Thanks, I just got it working taking that approach:
https://codesandbox.io/s/j750y06mo3

You can mark this issue as resolved.
