### ISSUE TITLE
ant3.0.0的Table组件在移动端样式错乱

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#8465]
### Version
3.0.0

### Environment
3.0.0 react15.6.0

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
官网的例子就可以重现

### What is expected?
可以正确显示ui

### What is actually happening?
Table组件在移动端样式错乱

**Comment by yesmeck** [comment]
不建议在移动端用 Table，移动端的支持优先级比较低，如果有需求，欢迎给我们 PR。

**Comment by wangbagang** [comment]
不知道有没有好的解决方案，项目用的2.x，现在升级到3.0移动端样式全乱了，以前好好的，希望官方可以出一个解决方案！

**Comment by nai6514531** [comment]
![image](https://user-images.githubusercontent.com/13310359/33648532-56a3846e-da95-11e7-9d83-7619dabd0b31.png)
看样子是优化过的。只是还没接受这样的表现~

**Comment by wangbagang** [comment]
如果有右边固定的或者左边固定的列，样式就更丑了，或者表头文字居中显示，真是一种灾难！

**Comment by afc163** [comment]
参照 https://semantic-ui.com/collections/table.html 做了响应式的优化。

**Comment by nai6514531** [comment]
增加一个可选的配置项。可以回到2.x那样的展示

**Comment by afc163** [comment]
这么窄的空间，展示起来会不会太挤？

**Comment by wangbagang** [comment]
@afc163 不会的，在2.x表现如下
![default](https://user-images.githubusercontent.com/17397318/33654828-4a552bc4-daac-11e7-8735-a5c6ef15a6c0.png)
![default](https://user-images.githubusercontent.com/17397318/33654855-612a8632-daac-11e7-8f4e-26c02039996b.png)
还是比较完美的，移动端可以滑动看响应的数据，3.0现在这种header完全对不上，另外如果有fixed的话就无法显示了，ant官网就可以看具体的效果，缩小至手机版的看看

**Comment by afc163** [comment]
Fixed 列的表格不做这个响应式优化，是不是就能解决你的问题。

**Comment by wangbagang** [comment]
@afc163 这样子其实也不行的哦，现实中有很多的表格header是很长的，有十几个甚至几十个，这样子的表格如果以现在的column（从上到下）的展现方式表现出来，那么我看到数据的时候就不知道数据对应的header是什么（这点很让人抓狂）！

**Comment by afc163** [comment]
> 有很多的表格header是很长的，有十几个甚至几十个

如果是这样也没有 fixed columns 的话，应该也挤成一团了吧。

**Comment by wangbagang** [comment]
是的，总之目前这种展现方式在移动端确实很不友好。

**Comment by afc163** [comment]
我先去掉这段优化好了。

**Comment by wangbagang** [comment]
Thanks， 辛苦了！

**Comment by kossel** [comment]
我把Table 封包了一下，如果加responsive prop会以类似List 的方法显示
https://kossel.github.io/bsa-ui-2-doc/#!/Table/23

**Comment by afc163** [comment]
@kossel 看上去不错，@wangbagang 看看这样的响应式方案是不是可以接受？

**Comment by wangbagang** [comment]
@afc163 我觉的添加一个mode参数更好，mode可选参数有‘normal, responsive, list’等等，这样子有很大的灵活度，有的时候类似list的显示方式会好点，有时候normal好点，把这个选择权交给用户，我们ant只提供选项。

**Comment by keke122765** [comment]
> @afc163 我觉的添加一个mode参数更好，mode可选参数有‘normal, responsive, list’等等，这样子有很大的灵活度，也好扩展，有的时候类似list的显示方式会好点，有时候normal好点，把这个选择权交给用户，我们ant只提供选项。

list有没有实现呢

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/1755#issuecomment-405009460
