### ISSUE TITLE
Allow validate with component's state

### ISSUE THREAD

**Issue by cpunion** [ant-design/ant-design#8466]
### Version
3.0.0

### Environment
macOS 10.13, Chrome 62.0.3202.94

### Reproduction link
[https://codesandbox.io/s/rjz7w04kyp](https://codesandbox.io/s/rjz7w04kyp)

### Steps to reproduce
1. Input some text into input control.
2. Click "Submit", wait 1 second.
3. Now state.errors be assigned {name: 'Out of quota'}, but it doesn't display.
4. Input more into input control, the error message will shown.

### What is expected?
Submit a form and get some error response is very common, I think form validation should run validations when state changed. _Maybe should run when props or state changed._

### What is actually happening?
Validation just execute when control value changed.

**Comment by yesmeck** [comment]
You should use `setFields`.

**Comment by cpunion** [comment]
A more common case is captcha, you can't validate it without submittal. If you get errors from response, maybe other fields have errors too. So merge them into form validation is very useful.

**Comment by cpunion** [comment]
@yesmeck Oh, I'll look it.

**Comment by yesmeck** [comment]
Close since it's a usage question.

**Comment by cpunion** [comment]
@yesmeck Perfectly! Thanks.
