### ISSUE TITLE
为什么modal有width属性却没有height属性

### ISSUE THREAD

**Issue by mingChen2017** [ant-design/ant-design#8467]
### What problem does this feature solve?
能自由设置modal的height

### What does the proposed API look like?
height=

**Comment by afc163** [comment]
因为 height 是跟着内容走的。

**Comment by mingChen2017** [comment]
你好，非常感谢你的回答。我已经找到了解决的方法所以我关闭了问题 。但是我还是有疑惑，既然height被限定跟着内容走，为什么width就可以赋予不跟着内容走的自由？

**Comment by afc163** [comment]
两个都和内容走的话，如果是一个文本段落，长宽不定，要如何展现呢？

**Comment by neekey** [comment]
感觉width自适应的场景还是挺多的，而且从模块层次上来说，modal不应该太关心其内容物的尺寸才对。否则如果modal里面的内容宽度会变化的话，还得想办法线上传递到modal这一层设置width。

> 两个都和内容走的话，如果是一个文本段落，长宽不定，要如何展现呢？

这个我觉得就是该怎么展示怎么展示，内容物应该自己管理好自己的尺寸

**Comment by s97712** [comment]
宽度应该由css来控制吧，提供额外的宽度设置有什么用途？

**Comment by s97712** [comment]
width只能是数值吗 改成fit-context会被清除
