### ISSUE TITLE
您好，antd 官方没有出日期组件跟时间组件结合的组件吗？

### ISSUE THREAD

**Issue by gitCoy** [ant-design/ant-design#8468]
### What problem does this feature solve?
我现在想要选择日期的同时选择时间，只能分开引入两个组件吗？

### What does the proposed API look like?
我希望引入一个组件就能实现日期跟时间的选择

**Comment by yesmeck** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-time

**Comment by gitCoy** [comment]
Thanks! It`s not very obvious!

**Comment by hytStart** [comment]
有， showTime={true}
          format="YYYY-MM-DD HH:mm:ss"

**Comment by InsHomePgup** [comment]
感谢，搞定了。
