### ISSUE TITLE
弱网下Demo.js加载慢

### ISSUE THREAD

**Issue by superlbr** [ant-design/ant-design#847]
请问有没有好的解决方案?
![image](https://cloud.githubusercontent.com/assets/8142164/12252997/463e2e72-b917-11e5-8e32-d790f0a7f37c.png)

**Comment by afc163** [comment]
可以翻墙，或 clone 到本地来看。https://github.com/ant-design/ant-design/wiki/%E7%BD%91%E7%AB%99%E5%92%8C%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%AF%B4%E6%98%8E

**Comment by superlbr** [comment]
你们有试过Webpack的CODE SPLITTING么?

**Comment by afc163** [comment]
欢迎 PR !!! ~~~ :smile_cat:
