### ISSUE TITLE
Input.Search can not accept click event

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#8470]
### Version
3.0.0

### Environment
Chrome,Ubuntu

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
If the Search component has no `enterButton`,

It can only accept an enter event.

If I click the search icon, It does nothing.

### What is expected?
It can respond the `onSearch`  function when I click the search icon.

### What is actually happening?
It only accept enter event

**Comment by buxuku** [comment]
And I think the search icon should have a style of `hover`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8445
