### ISSUE TITLE
The CSS style margin and padding style of the HTML elements in version 3.0 are gone, and previous versions are available

### ISSUE THREAD

**Issue by es3154** [ant-design/ant-design#8473]

**Comment by aschrijver** [comment]
ha @es3154! am i right you had the same rude experience with this issue bot thing?
wow, and that for a UX library :)

**Comment by es3154** [comment]
ha @aschrijver  I now have a copy of the 2.X version of the global Settings body, div, dl, dt, dd, ul, ol... The style of setting margin:0,padding: 0, in my theme style file, it is very helpless
