### ISSUE TITLE
collapsed menu will not working, when defaultOpenKeys not in all SubMenu keys

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#8475]
### Version
2.13.11

### Environment
All browsers

### Reproduction link
[https://codepen.io/Hughen/pen/LOvKWL](https://codepen.io/Hughen/pen/LOvKWL)

### Steps to reproduce
```javascript
    defaultOpenKeys=['sub10']
    allSubMenuKeys=['sub1', 'sub2']

   // defaultOpenKeys ∩ allSubMenuKeys = 0
```

### What is expected?
every submenu will be expanded, the point hover on it.

### What is actually happening?
the menu defaultOpenKeys can not find anything from Menu.SubMenu keys, any submenu is not appeared when sider bar has been collapsed

**Comment by afc163** [comment]
I don't understand, your codepen don't make any sense, `sub10` is not existed in Menu keys.

**Comment by Hughen** [comment]
define allSubMenuKeys, just want to said the all SubMenu of Menu, and it's not a property of Menu.
from my demo:
```javascript
    <Menu
      defaultOpenKeys={['sub10']}
    >
      <SubMenu key="sub1">...</SubMenu>
      <SubMenu key="sub2">...</SubMenu>
    </Menu>
```

**Comment by afc163** [comment]
Is this a bug report or a feature request?

**Comment by Hughen** [comment]
It's a bug.
ex:
![image](https://user-images.githubusercontent.com/3334378/33660445-bddc0e52-dabe-11e7-8788-e4438536f0f5.png)
my point hover on "Navigation One", but there is disappearing submenu.

**Comment by Hughen** [comment]
@afc163 
from your commit log, and I copy your tips in antd@2.13.11。
I am sorry to tell you, there are still problems, but it's a new bug which can not collasped after expanded.
Maybe you should carefully test, looking forward to your new solution.
![menu-collapsed-error](https://user-images.githubusercontent.com/3334378/34088757-7a19612a-e3e6-11e7-97d8-f47890198953.gif)

**Comment by afc163** [comment]
@Hughen Could u provide a reproducible steps of your gif?

**Comment by Hughen** [comment]
base on your commit, gif demo code:
```javascript
<Menu
  mode="inline"
  theme="dark"
>
  <SubMenu
    title="Main Menu"
    key="main"
  >
    <Menu.Item key="s1">
      <a href="#">Sub 1</a>
    </Menu.Item>
    <Menu.Item key="s2">
      <a href="#">Sub 2</a>
    </Menu.Item>
  </SubMenu>
</Menu>
```
