### ISSUE TITLE
LocaleProvider does not work

### ISSUE THREAD

**Issue by Zzzen** [ant-design/ant-design#8476]
### Version
3.0.0

### Environment
react@15.x, chrome 64

### Reproduction link
[https://codepen.io/anon/pen/LOoPRY?editors=0010](https://codepen.io/anon/pen/LOoPRY?editors=0010)

### Steps to reproduce
1. Open date picker
2. select a random date
3. reopen date picker

### What is expected?
Weekdays should be displayed in Chinese: '日' to '六'

### What is actually happening?
Weekdays are displayed in English: 'Su' to 'Sa'

---
I've tested it on react@16.2.0, and get the same error

**Comment by afc163** [comment]
It is a bit different to get locales in dist file.

https://codepen.io/afc163/pen/WXBvod?editors=0010

**Comment by Zzzen** [comment]
I think there is something wrong with `antd\lib\locale-provider\zh_CN.js`.
```javascript
exports['default'] = {
    locale: 'zh-cn',
    // ... other props
};
module.exports = exports['default'];
```
is the same as
```javascript
module.exports = {
    locale: 'zh-cn',
    // ... other props
}
```
, which does not match its definition
```typescript
declare const _default: {
    locale: string;
    // ... other props
};
export default _default;

```
When I use `import zhCN from 'antd/lib/locale-provider/zh_CN'`,  `zhCN` is `undefined`
I'm using tsc 2.6.2.

**Comment by afc163** [comment]
```
import * as zhCN from 'antd/lib/locale-provider/zh_CN';
```

Or use `allowSyntheticDefaultImports` http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by Zzzen** [comment]
`allowSyntheticDefaultImports` is useless since its definition file already provides a default export. If I use `import * as zhCN from 'antd/lib/locale-provider/zh_CN';`, I have to cast `zhCN` to `any` before passing it to `LocaleProvider`
