### ISSUE TITLE
resolve type name collisions

### ISSUE THREAD

**Issue by hackape** [ant-design/ant-design#8478]
### What problem does this feature solve?
* Type { InputProps } from 'antd/lib/auto-complete' collide with { InputProps } from 'antd/lib/input'
* rename { SearchProps } from 'antd/lib/transfer' collide with { SearchProps } from 'antd/lib/input'

### What does the proposed API look like?
* rename { InputProps } from 'antd/lib/auto-complete' to { AutoCompleteInputProps }
* rename { SearchProps } from 'antd/lib/transfer' to { TransferSearchProps }

**Comment by yesmeck** [comment]
Why they are conflicting? These interfaces in different module.

**Comment by GauravV-02** [comment]
@hackape Can I work on this?

**Comment by yesmeck** [comment]
@GauravV-02 Yes, but can you answer my question?

**Comment by GauravV-02** [comment]
@yesmeck I haven't looked it why its conflicting yet. Lets think we have a module where I have to import both the interfaces from input and auto complete, I will give a duplicate identifier error because the names of the interfaces are same.

**Comment by yesmeck** [comment]
Hmm, make sense. welcome PR.

**Comment by hackape** [comment]
Sorry guys I totally missed out this thread. 

@GauravV-02 yes that's exactly the case I ran into, I made a module layer that functions as a customization point, which effectively import, extend, then re-export everything. At the time I check, it's already merged, thank you for you effect.
