### ISSUE TITLE
Tree is not working if we have multiple child node with same key

### ISSUE THREAD

**Issue by codegeous** [ant-design/ant-design#8480]
### Version
3.0.0

### Environment
Chrome Version 62.0.3202.94

### Reproduction link
[https://codesandbox.io/s/5vq956q3yl](https://codesandbox.io/s/5vq956q3yl)

### Steps to reproduce
Just check and un-check the first children (0-0-0-0) of all the nodes. Un-check is not working when we use multiple child with same key.

### What is expected?
On checking it checked all the keys of 0-0-0-0, but while unchecking it should uncheck all the 0-0-0-0 under all parents. 

### What is actually happening?
On checking it checked all the keys (0-0-0-0) but unchecking is not working

**Comment by benjycui** [comment]
Of course, key must be unique.

**Comment by vikyd** [comment]
If not allow duplicate key in Tree component, 

it is hard to load staff tree data in which one staff(with one staff id) may appear in multiple virtual organization.
