### ISSUE TITLE
Table组件，当Fixed和嵌套同时使用时出现高度不对齐当bug

### ISSUE THREAD

**Issue by javaxiu** [ant-design/ant-design#8483]
![image](https://user-images.githubusercontent.com/4281225/33664742-a25893ba-dacf-11e7-9497-33c8ef45b4b0.png)

如图，经检查，fixed列的高度不确定，有的高一点（34px），有的低一点（31px），滚动区固定是（34px）
使用场景：table用small，fix前两列，表格有嵌套[用的是这里的数据](https://ant.design/components/table-cn/#components-table-demo-expand-children)

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by javaxiu** [comment]
done after upgrade to version 3.0.0. Thanks
