### ISSUE TITLE
Upload is reloading

### ISSUE THREAD

**Issue by jrvboesch** [ant-design/ant-design#8485]
### Version
3.0.0

### Environment
ios ipad and tablet

### Reproduction link
[https://codesandbox.io/s/l9518rj70l](https://codesandbox.io/s/l9518rj70l)

### Steps to reproduce
After you select the image to upload it reloads the page

### What is expected?
The image is shown to be uploaded.

### What is actually happening?
The page is reloading.

---
this only happends in ipod and apple tablets.

**Comment by yesmeck** [comment]
Because upload is failed.

**Comment by jrvboesch** [comment]
@yesmeck this doesn't happen on my windows desktop or my android phone

**Comment by yesmeck** [comment]
Try print info.file.status to see if the file upload successfully.

**Comment by jrvboesch** [comment]
> uploading
> uploading
> done

[https://imgur.com/a/unRBi](screenshot)

**Comment by yesmeck** [comment]
Yes...It's done, and the image shows...

**Comment by dengfuping** [comment]
Could you give a gif to show it ? Beacouse your reprodution link can't to reproduce the problem.

**Comment by jrvboesch** [comment]
@dengfuping did you tried on an apple phone or tablet?

**Comment by dengfuping** [comment]
@jrvboesch I have no iPhone or iPad, but I tried it on my MacBook Pro and no problem found. Isn't it related to browsers rather than devices? It's better to show your problem simplely and consider using gif.
