### ISSUE TITLE
Modal onOpen support

### ISSUE THREAD

**Issue by farzer** [ant-design/ant-design#8491]
### What problem does this feature solve?
fetch the remote data only while open the modal

### What does the proposed API look like?
```js
<Modal onOpen={doSomething} />
```

**Comment by farzer** [comment]
https://github.com/react-component/dialog/issues/69

**Comment by afc163** [comment]
open 的时机完全是你控制的，onOpen 是多余的。

https://github.com/react-component/dialog/issues/69#issuecomment-341632074
