### ISSUE TITLE
form validate not' work and form's state not update

### ISSUE THREAD

**Issue by pssgo** [ant-design/ant-design#8492]
### Version
3.0.0

### Environment
win10 chrome react16

### Reproduction link
[https://codepen.io/pssgo/pen/OOorwq?editors=0010](https://codepen.io/pssgo/pen/OOorwq?editors=0010)

### Steps to reproduce
first input some on the input 

second clear the input content

three click the error Button 

four click the submit Button 

### What is expected?
form.validateFields()  can pass the validate form's state can be update

### What is actually happening?
form.validateFields()  can't pass the validate form's state not update

**Comment by benjycui** [comment]
I don't understand what you are going to say. According to me, it works fine.

More about dynamic rules, please consult https://ant.design/components/form/#components-form-demo-dynamic-rule

**Comment by benjycui** [comment]
Close for no response.
