### ISSUE TITLE
Add [destroyOnHide] to Modal

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#8494]
The original request is from https://github.com/react-component/dialog/issues/22 

It's a common usage to reset form fields in Modal every time when open it. But the current implementation of Modal doesn't unmount components inside modal, that is to say you need reset form fields after modal opened manually. Adding `destroyOnHide` to Modal can make resetting automatically.

How to archive this:

1. Open a PR to [`rc-dialog`](https://github.com/react-component/dialog) repo to support `destroyOnHide`.
1. After previous PR been accepted, open a PR to this repo to update the `rc-dialog` dependency and the document.

Attention：

1. We need support both React 15 and 16.
1. Close animation should be triggered when unmount modal.

**Comment by nai6514531** [comment]
antd2的版本加key的方式是不是卸载了modal的内部表单组件

**Comment by yesmeck** [comment]
yes

**Comment by Rohanhacker** [comment]
Can I work on this ?

**Comment by yesmeck** [comment]
@Rohanhacker Of cause, here is the [guide](https://github.com/ant-design/ant-design/blob/contributing/.github/CONTRIBUTING.md#sending-a-pull-request) directs how to add a feature.
