### ISSUE TITLE
Pagination reset when the table is re-rendered.

### ISSUE THREAD

**Issue by bnerDY** [ant-design/ant-design#8496]
### What problem does this feature solve?
Data table is re-rendered, whereas the pagination remain the same with old state.

### What does the proposed API look like?
pagination:{reset:true}

**Comment by benjycui** [comment]
Just reset it by `Table[pagination={...}]`

**Comment by sdenisen** [comment]
> Just reset it by `Table[pagination={...}]`

could you please explain what is it mean? 
Table[pagination={}] - ???

**Comment by 07akioni** [comment]
pagination of the table is controlled by yourself. if you want to reset it, just update `pagination` prop to the value you desired
