### ISSUE TITLE
select doesn't auto topLeft and safari menu hover bug

### ISSUE THREAD

**Issue by lvsenlin** [ant-design/ant-design#8497]
### Version
3.0.0

### Environment
macOS safari 

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
https://ant.design/components/select-cn/
https://ant.design/components/menu-cn/

### What is expected?
select auto topLeft
safari menu hover normal

### What is actually happening?
select doesn't auto topLeft
safari menu hover bug

---
目前采用了临时解决方案：
1.menu延迟0.5秒关闭，感觉有点混乱，但凑合能用：subMenuCloseDelay={'0.5'}
2.位于页面较靠底部的位置时显示不全，全局中限制下拉框高度（只显示三行），有点影响使用体验：
  .ant-select-dropdown-menu {
    max-height: 125px;
  }

~

**Comment by afc163** [comment]
> select doesn't auto topLeft

Cannot understand.

**Comment by afc163** [comment]
Duplicate of #8453

**Comment by lvsenlin** [comment]
在Modal中使用Select选择器时，当位于Modal较下面时不会自动上弹，前几个版本会自动上弹
我现在的解决办法是限制了它的高度，让它只显示了三行，这样有Modal的footer可以支撑显示三行的空间
这个自动上弹是取消了，还是bug了？

<img width="957" alt="qq20171208-2 2x" src="https://user-images.githubusercontent.com/3062415/33749737-6af82a34-dc0a-11e7-944d-1171532eb295.png">

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this: http://codepen.iohttp://u.ant.design/codesandbox-repro

**Comment by lvsenlin** [comment]
@afc163 
http://1x.ant.design/components/select/
<img width="1087" alt="qq20171208-2 2x" src="https://user-images.githubusercontent.com/3062415/33754970-9b792a22-dc29-11e7-8123-da216fcb94dd.png">

https://ant.design/components/select-cn/
<img width="997" alt="qq20171208-1 2x" src="https://user-images.githubusercontent.com/3062415/33754977-9f6a7726-dc29-11e7-8c5b-fe3d15bec3d1.png">

**Comment by lvsenlin** [comment]
@afc163 
3.0.1还是不能自动上弹

**Comment by lvsenlin** [comment]
https://codesandbox.io/s/n99y1qvkkj

**Comment by afc163** [comment]
原来的自动上弹在页面还有滚动空间时会造成 https://github.com/ant-design/ant-design/issues/5130 浮层频繁抖动的问题。所以我们优化了这个逻辑，只有在页面的真实区域边缘外才会自动定位，能滚动到的地方都不重新定位。

**Comment by lvsenlin** [comment]
非常谢谢！
我有看到5130这个问题，项目是从2.10.0升级过来的，退到2.10.0前后的几个版本就会自动上弹。
沙盒里的项目会上弹，所以应该是构建或者版本依赖的问题，我昨天升级了相关包版本失败了。今天再尝试一下，如果还是不行就只能重搭项目了
