### ISSUE TITLE
设置垂直菜单为多选时，选中某一个MenuItem，SubMenu会关闭

### ISSUE THREAD

**Issue by yuxuan** [ant-design/ant-design#8498]
### Version
2.11.1

### Environment
MacBook Pro，Chrome，React15.6.2

### Reproduction link
[https://codepen.io/GavinSolo/pen/XzwQee?editors=001](https://codepen.io/GavinSolo/pen/XzwQee?editors=001)

### Steps to reproduce
如codepen链接，在Menu mode="vertical"中加入mutiple，点击SubMenu的Item时，SubMenu会关闭。如果这是用在dropdown中，与dropdown组合成二级多选，虽然一级可以设置visible=true，但是二级点选时依然会关闭

### What is expected?
在为mutliple时，SubMenu点选时不关闭，点击外面关闭。

### What is actually happening?
点击item会关闭

**Comment by benjycui** [comment]
业务场景是？虽然 Menu 支持选中一个 MenuItem，但是我一直不能理解这种场景。

**Comment by yuxuan** [comment]
@benjycui，场景应该更接近于select，而不是menu。基本就是作为TreeSelect的变形吧，但是我个人感觉比TreeSelect整洁，层级更清楚些，筛选更方便。

**Comment by benjycui** [comment]
> Edit： 再补充一点，目前这种交互，感觉multiple没有什么意义吧

只能在 Menu[inline] 里面使用。

也觉得 Menu 这样使用不合理，你还是用回 TreeSelect 之类吧，先关了，有更多使用场景时再统一考虑。
