### ISSUE TITLE
It will be wrong when I use official  List's example of typescript on webstorm

### ISSUE THREAD

**Issue by mingChen2017** [ant-design/ant-design#8499]
### What problem does this feature solve?
http://kinggame.oss-cn-shanghai.aliyuncs.com/DreamBook/1.png
http://kinggame.oss-cn-shanghai.aliyuncs.com/DreamBook/2.png

These are correlation graph,the complete code is
<List
    itemLayout="horizontal"
    dataSource={data}
    renderItem={item => (
      <List.Item>
        <List.Item.Meta
          avatar={<Avatar src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png" />}
          title={<a href="https://ant.design">{item.title}</a>}
          description="Ant Design, a design language for background applications, is refined by Ant UED Team"
        />
      </List.Item>
    )}
  />

it's copy by the official without modifying.

### What does the proposed API look like?
I can use normally

**Comment by yesmeck** [comment]
Yes, `extra` should be optional, it has been fixed, wait for the weekend release.

https://github.com/ant-design/ant-design/commit/e27061ea5b2f2d3273b45862d9b87285448f0998

**Comment by yesmeck** [comment]
A temporary workaround is pass a empty string to `extra`.
