### ISSUE TITLE
Fast click for mobile

### ISSUE THREAD

**Issue by ssssssssssss** [ant-design/ant-design#85]
Hi there,

Is there any plan to employ the fast click for mobile devices?
https://github.com/JakeSidSmith/react-fastclick
http://stackoverflow.com/questions/24335821/can-i-fastclick-reactjs-running-in-cordova/30316754#30316754

**Comment by yiminghe** [comment]
have not tested components on mobile yet

**Comment by ssssssssssss** [comment]
@yiminghe Do you have any concrete plan to target mobile platform which needs better responsive design?
