### ISSUE TITLE
Please avoid overwrite the exports variable in the lib exports.

### ISSUE THREAD

**Issue by acrazing** [ant-design/ant-design#8500]
For example: in the `lib/layout/layout.js`, the js file ends with the following code:

```js
Layout.Header = Header;
Layout.Footer = Footer;
Layout.Content = Content;
exports['default'] = Layout;
module.exports = exports['default'];
```

This means the `module.exports.default` will never been assigned, If we write with TypeScript by using `import Layout from 'antd/lib/layout/layout'` and without babel. This will emit error, you know that.

**Comment by acrazing** [comment]
Any one could fix this? I do not want to submit a issue twice. @ascoders @afc163 @benjycui

**Comment by yesmeck** [comment]
Do you have any  particular advice how can we fix it?

**Comment by acrazing** [comment]
Two ways to do this:

1. fix the plugin [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) by adding extra line like `module.exports.default = module.export`.
2. avoid use babel to compile source code to `lib`, TypeScript is enough, after run `tsc`, run `find ./lib -type f -name '*.js' | xargs -I % bash -c "echo 'module.exports = exports.default.default = exports.default;` >> %"`. You can get a tsconfig file to emit es5 code from `components` to `lib` directory at [here](https://github.com/acrazing/ant-design/blob/9262ec79a5c9225490020ce986e80544d6ad190e/tsconfig.json).

**Comment by nick1247** [comment]
Any updates on this?
It would be great to include @acrazing solution

**Comment by yesmeck** [comment]
We'v removed `babel-plugin-add-module-exports`. Does this issue still exists? Can you provide a reproduction repo?

**Comment by nick1247** [comment]
I updated from 3.1.1 to 3.1.3 and exports are correct now.
I think this issue could be closed.

Thank you for the work and sorry for the noise.

**Comment by nick1247** [comment]
if anybody is interested, typescript@2.7 will have ESModuleInterop flag that solves issue with commonjs exports without assigned default key

more info [here](https://github.com/Microsoft/TypeScript/issues/16093)
