### ISSUE TITLE
Select 组件中的 Option 的 value 属性是否可以支持 number 类型的？

### ISSUE THREAD

**Issue by ryan-hung** [ant-design/ant-design#8502]
在后端返回接口中经常会出现下拉菜单中选项的 value 为 number 的情况，查看了 antd 中关于 Select Option 相关的文档，在 Option 子组件中 value 的属性验证必须为 string 类型，如果直接传递 number 类型则会爆出类型不匹配，而每次将 number 转换为 string 又比较麻烦，是否可以考虑同时支持 string|number 两种类型？

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/2857
