### ISSUE TITLE
defaultExpandAllRows missing in typescript TableProps<T>

### ISSUE THREAD

**Issue by ChrisFerrell** [ant-design/ant-design#8507]
### Version
3.0.0

### Environment
windows 10

### Reproduction link
[http:///localhost.com](http:///localhost.com)

### Steps to reproduce
```  
return <Table
            columns={this.props.columns}
            dataSource={this.props.data}
            defaultExpandAllRows={true}
            expandedRowRender={(record) => this.expandedRowRender(record.key)}
        />
```

// typescript compiler complains because missing in definition

### What is expected?
Need to be added to TableProps<T> in interface.tsx.

### What is actually happening?
error given by typescript compiler when used

**Comment by yesmeck** [comment]
Feel free to open a PR.
