### ISSUE TITLE
What' s is the best way to  prevent onDoubleClick(onRowDoubleClick) events to trigger onClick(onRowClick) events in onRow events ?

### ISSUE THREAD

**Issue by CeleKing** [ant-design/ant-design#8508]
### What problem does this feature solve?
To prevent onDoubleClick(onRowDoubleClick) events to trigger onClick(onRowClick) events in onRow events ?

### What does the proposed API look like?
Sorry, I have no idea about it .

**Comment by danedavid** [comment]
See https://stackoverflow.com/a/880792/6473435
Basically, your UI should be such that click and double click leads to progressive actions.  
If you really want to **NOT** fire the click event, consider adding a delay before calling the click event, possibly using utilities like [lodash debounce](https://lodash.com/docs/4.17.4#debounce)
