### ISSUE TITLE
关于ant的webpack打包后没有hash，以及html中路径替换

### ISSUE THREAD

**Issue by Liyuk** [ant-design/ant-design#851]
1、打包后的文件没有hash值，请问下怎样修改配置文件能让打包后的文件带上hash呢？
2、打包后，打包文件的路径是变化的，如果增加了hash之后文件名也变化了，怎样在html中进行替换呢？

---
我看了下webpack关于修改html路径的内容，是在`webpack.config.js`中修改的`plugins`，输出路径到一个json文件里，再自己写脚本去读json进行替换，如下：
```javascript
plugins: [
  function() {
    this.plugin("done", function(stats) {
      require("fs").writeFileSync(
        path.join(__dirname, "...", "stats.json"),
        JSON.stringify(stats.toJson()));
    });
  }
]
```
但是antd生成项目的webpack配置文件是在运行时`npm run build`时生成，并且有`plugins`，想问下如何修改？

谢谢。

**Comment by afc163** [comment]
webpack 相关问题建议求助 Google 或 stackoverflow 。

antd-init 生成的项目的 webpack 配置文件可以参考：http://ant-tool.github.io/webpack-config.html
