### ISSUE TITLE
submenu does not survive when the mouse is moved to the submenu

### ISSUE THREAD

**Issue by yxqme** [ant-design/ant-design#8513]
# Version

3.0.0

# Environment

mac os, safari 10.0.3 (12602.4.8)

# Reproduction link

https://ant.design/components/menu-cn/

# Steps to reproduce

# What is expected?

# What is actually happening?

Using the horizontal top navigation menu, when the mouse hover over the submenu will trigger the submenu, but the submenu does not survive when the mouse is moved to the submenu

**Comment by benjycui** [comment]
Fixed, and will publish in this weekend.

**Comment by yxqme** [comment]
@benjycui Thank you! reference the issues, I have fixed it, just reinstall dom-align to version 1.6.6
