### ISSUE TITLE
submenu does not survive when the mouse hover over the submenu

### ISSUE THREAD

**Issue by yxqme** [ant-design/ant-design#8514]
### Version
3.0.0

### Environment
mac os, safari 10.0.3 (12602.4.8)

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
Trigger submenu, mouse hover over the submenu

### What is expected?
Using the horizontal top navigation menu, submenu will survive when the mouse hover over the submenu

### What is actually happening?
Using the horizontal top navigation menu, submenu does not survive when the mouse hover over the submenu

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/8453
