### ISSUE TITLE
Click search icon in Input.Search can't trigger onSearch event .

### ISSUE THREAD

**Issue by CeleKing** [ant-design/ant-design#8517]
### Version
3.0.0

### Environment
MacOS High Sierra 10.13.1; Chrome:62.0.3202.94

### Reproduction link
[https://codesandbox.io/s/2x6k8xj0pr](https://codesandbox.io/s/2x6k8xj0pr)

### Steps to reproduce
const Search = Input.Search;

ReactDOM.render(
  <div>
    <Search
      placeholder="input search text"
      onSearch={value => console.log(value)}
      style={{ width: 200 }}
    />
  </div>,
  document.getElementById('root')
);

### What is expected?
click search icon can trigger onSearch event  and console input value

### What is actually happening?
click search icon can't trigger onSearch event can't console input value

---
search icon refer to ant-input-suffix

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8445

**Comment by CeleKing** [comment]
I remebered it worked at 2.x versions . Thank you all the same !

**Comment by afc163** [comment]
I will clarify it in 3.0's changelog later.
