### ISSUE TITLE
Upload image not to preview when beforeUpload was false

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#8518]
### Version
3.0.0

### Environment
react 16.2.0
antd 3.0.0
ubuntu 14.04
node 6.1.0

### Reproduction link
[Upload within codepen](https://codepen.io/xiaohesong/pen/XzLPwV?editors=0010)

### Steps to reproduce
redirect to the codepen

### What is expected?
could be show thumbnail

### What is actually happening?
1. Always show `Uploading`, no thumbnails.
I am try to console log the file when `handleChange`. not to see `url` of `status` columns.
```javascript
handleCardChange = ({fileList}) => {
    console.log("file list id change", fileList);
    this.setState({ cardImgList: fileList })
  }
```
2. All right, I try to search this issue, but not helpful.
[#8020](https://github.com/ant-design/ant-design/issues/8020)

**Comment by didmehh** [comment]
Hi, i was solve it by [#830](https://github.com/ant-design/ant-design/issues/830).
```javascript
    let reader = new FileReader();
    reader.readAsDataURL(logoFile);
```
set `file url` from `reader.result`
Ps: this issue was a feature?

**Comment by afc163** [comment]
I think it is better not doing anything if beforeUpload return false, let user decide what need to be done.

**Comment by didmehh** [comment]
i don't known how to set header `Content-Type` for submit form within file input and use the `fetch`, or don't do anything.

**Comment by kamkyi** [comment]
could you please show the complete codes @didmehh
