### ISSUE TITLE
RangerPicker 的props value的类型是Array，而Picker的要求的类型是Object

### ISSUE THREAD

**Issue by JonneyYan** [ant-design/ant-design#852]
给RangerPicker增加value属性时发生如下错误
Warning: Failed propType: Invalid prop `value` of type `array` supplied to `Picker`, expected `object`. Check the render method of `RangePicker`.

RangerPicker中value的类型是Array，Picker接收的是Object
RangerPicker:
https://github.com/JonneyYan/ant-design/blob/master/components/date-picker/RangePicker.jsx#L113-L114

Picker:
https://github.com/react-component/calendar/blob/master/src/Picker.jsx#L27-L28

**Comment by benjycui** [comment]
:+1: THX
