### ISSUE TITLE
Multiselect Dropdown

### ISSUE THREAD

**Issue by Hardik21** [ant-design/ant-design#8521]
### What problem does this feature solve?
I want to display tag by <option> text name instead of key value. And also need key value for store in database

### What does the proposed API look like?
Display "Option Text" instead of "Option Value"

And also i want to search on text not id. 
[CodePen Demo](https://codepen.io/hieunvtq/pen/LzQrgE?editors=0010)

In this demo, search with record id(default functionality).

I want to display text & get key value on submit.

**Comment by yesmeck** [comment]
> And also i want to search on text not id.

You can override default search function with `filterOption`.

> I want to display text & get key value on submit.

Try set `labelInValue` to `true`.

**Comment by oleole90** [comment]
The Demo of `labelInValue mode="multiple"` that I wished included in the docs:
 https://codepen.io/oleole90/pen/KZWKXX
(keep console window open)

**Comment by SHUBHAMDAVE001** [comment]
I want to select multiple image from the dropdown can anybody give me suggestion!!
