### ISSUE TITLE
Input.Textarea is undefined 

### ISSUE THREAD

**Issue by fdelbos** [ant-design/ant-design#8522]
### Version
3.0.0

### Environment
browser: chrome osx Version 62.0.3202.94 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/LOKvdm?editors=0011](https://codepen.io/anon/pen/LOKvdm?editors=0011)

### Steps to reproduce
```
import {Input} from 'antd';
const {Textarea} = Input;
console.log(Textarea); // output: 'undefined'
```
### What is expected?
Textarea should be defined.

### What is actually happening?
Textarea is not defined

---
I have checked the file 'ant-design/components/input/index.tsx' also I don't know much about ts, it seems correct. What am i missing here ?

**Comment by afc163** [comment]
```diff
- Textarea
+ TextArea
```
