### ISSUE TITLE
mapPropsToFields可否增加返回空值时不改变form 现有fields值

### ISSUE THREAD

**Issue by vonxq** [ant-design/ant-design#8523]
### What problem does this feature solve?
后台管理系统，表单数据存储在redux的store中，希望在提交表单时提交按钮有个loading状态，loading状态也是redux管理的
表单提交的loading状态改变会触发mapPropsToFields，从而使提交过程中表单被重置到上一次store里的值了，提交完成又会被map为正确结果
希望能避免中间的一次表单重置操作，或者有没有什么好的解决方案，望指教
```javascript
const mapStateToProps = (state) => {
  return {
    resulValue: state.systemCommand.ipmac,
    loading: state.loading.effects['systemCommand/queryIpMac'],
  }
}
const mapPropsToFields = (props) => {
  const { resulValue = {}, loading } = props
// 希望在loading时不要改变fields的值
  if (loading) {
    return
  }
  return {
    mac: Form.createFormField({ value: resulValue.mac }),
    ip: Form.createFormField({ value: resulValue.ip }),
  }
}
export default connect(mapStateToProps)(Form.create({ mapPropsToFields })(IpMac))
```

### What does the proposed API look like?
mapPropsToFields 直接return的时候不要改变fields的值

**Comment by benjycui** [comment]
使用 `mapPropsToFields` 时，应该使用 `onFieldsChange` 同步最新的数据到 Redux。

**Comment by vonxq** [comment]
@benjycui Redux Store只存了和后台相同的表单值，用来作为表单项的initialValue，使用onFieldsChange的意思是说表单的每一次改变都要存到Redux store吗?这样感觉会有点复杂，表单的值只需要在最后提交时收集到就行，中间状态都是不需要的

**Comment by benjycui** [comment]
> Redux Store只存了和后台相同的表单值，用来作为表单项的initialValue

如果是这个场景，根本就不需要 mapPropsToFields，直接使用 getFieldDecorator 的 initialValue 即可。

**Comment by sbyps** [comment]
@benjycui 在componentDidMount中将数据存在redux store中，此时触发mapPropsToFields将值设置到组件中，存在一个问题：别的props如loading一变化此时也会触发mapPropsToFields，用户编辑过的值就被清除了；
