### ISSUE TITLE
In Form, the Select component is different with other components like Input when we use mapPropsToFields to assign null value

### ISSUE THREAD

**Issue by kurryluo** [ant-design/ant-design#8524]
### Version
3.0.0

### Environment
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Reproduction link
[https://github.com/kurryluo/ant-design](https://github.com/kurryluo/ant-design)

### Steps to reproduce
just try to use mapPropsToFields 

### What is expected?
When we use mapPropsToFields to assign null value， the placeholder of Select component will not disappear just like Input

### What is actually happening?
the placeholder of the Select component will disappear

---
if we use an undefined value,  it works.

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2367
