### ISSUE TITLE
error style in nested table

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#8525]
### Version
3.0.0

### Environment
react 16.2

### Reproduction link
[https://codesandbox.io/s/xj4p85xx1z](https://codesandbox.io/s/xj4p85xx1z)

### Steps to reproduce
parent table with `size="small"` and child table with `size="middle"`

### What is expected?
correct middle table's style

### What is actually happening?
chid middle table's style is `small`

**Comment by afc163** [comment]
```diff
          <Table
            size="middle"
            columns={columns}
            dataSource={data}
-           size="small"
          />
```

**Comment by vthinkxie** [comment]
same error style when remove this line.

**Comment by afc163** [comment]
Fixed that.
