### ISSUE TITLE
InputNumber component to include the same pre / post tab feature as Input component

### ISSUE THREAD

**Issue by nsepehr** [ant-design/ant-design#8527]
### What problem does this feature solve?
We love the Ant Design UI and components. We have an issue where the value type we need to same using the form for our number fields has to stay as JavaScript "Number". InputNumber saves the values as Number which works great. However it doesn't have the "Pre / Post tab" feature of Input component. And if we switch to Input component and set the type as "number" then the value still gets saved as a string which breaks our validation form validation. 

### What does the proposed API look like?
<InputNumber addonBefore="BeforeTab" addonAfter="AfterTab" />

**Comment by afc163** [comment]
You can try https://ant.design/components/input/#components-input-demo-group

**Comment by cdesch** [comment]
@nsepehr you probably don't have this issue any more, but here is a solution I used:
```
<Input.Group compact>
  <InputNumber
	style={{
	  width: 200,
	}}
	min={0}
	max={100}
	step={0.125}
	precision={3}
	{...field}
  />
  <span className="ant-input-group-addon">%</span>
</Input.Group>
```
