### ISSUE TITLE
Tooltip 浮层位置可以变化

### ISSUE THREAD

**Issue by Jessie-D** [ant-design/ant-design#853]
![1](https://cloud.githubusercontent.com/assets/10069496/12282951/667c6642-b9dd-11e5-8d65-16ee476d5b8c.png)
![2](https://cloud.githubusercontent.com/assets/10069496/12282952/6d7fd2a8-b9dd-11e5-836c-b0059c3a39ab.png)

 
Tooltip 浮层位置可以变化

**发生环境**

- antd 版本：0.10.4
- 操作系统：win 7 
- 浏览器及版本：谷歌 火狐
- 在线演示地址：http://ant.design/components/tooltip/

**重现步骤**

1. 光标移到12个方向的下边
2. 移动光标位置，Tooltip 浮层偶尔是居左下，而不是正居中下
 
在我做的后台系统中会很明显
 

 
![3](https://cloud.githubusercontent.com/assets/10069496/12282987/c6284746-b9dd-11e5-950f-cc8ba1b64321.png)

**Comment by Jessie-D** [comment]
补充一下popover中也会有这样的情况
 

![Uploading 6.png…]()

**Comment by afc163** [comment]
确实有这个问题。

**Comment by afc163** [comment]
是否也是快速移入移出时才会出现？

**Comment by afc163** [comment]
另一个：

```
        <Popover overlay={content} title="转接说明" trigger="click">
          <Icon type="book" style={{
            'fontSize': '15px'
          }} onClick={this.onClick}/>
        </Popover>
```

onClick 里面有 setState ，也导致了一个错位问题。可能两个问题原因是一样的。

**Comment by BackWorld** [comment]
我也发现了

**Comment by afc163** [comment]
https://github.com/react-component/animate/commit/6c6ef2bccdba876fa2a4b8a59af84683a4f0a86d

@all 已修复，重新安装 antd 即可。
