### ISSUE TITLE
Weird behavior in form for  dynamic array of objects 

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#8532]
### Version
3.0.0

### Environment
ubuntu 16.4, chrome  62.0.3202.94 (64-bit), react 16, antd 3.0.0

### Reproduction link
[https://codesandbox.io/s/wq5rj10188](https://codesandbox.io/s/wq5rj10188)

### Steps to reproduce
click on the button twice

### What is expected?
two input fields bound to name properties of objects inside the array

### What is actually happening?
This is what happens in the form:
1- getFieldDecorator('arr') creates an empty array as expected
2- clicking on the button sets 'arr' to be [{}] as expected
3- getFieldDecorator('arr[${index}].name') changes the 'arr' to an object the structure displayed in the console in the example

**Comment by benjycui** [comment]
Just as the error said.

You can consult the demo https://ant.design/components/form/#components-form-demo-dynamic-form-item

**Comment by AhmedSayed77** [comment]
@benjycui thanks for the response, I'm aware of the demo, and I'm aware of the workarounds to handle the dynamic array, but the bug is in the behavior of nested objects/arrays, not in the dynamic part.
I've updated the demo to include nested objects - not dynamic. getFieldDecorator creates a property with key "" that is bound to the parent object. check the code written in the componentDidMount and check the console

**Comment by sowdri** [comment]
I could confirm this behavior as well. The array is converted into an object with indexes as keys and the original array as value of an empty key. Just as demonstrated in the codesandbox above.

**Comment by benjycui** [comment]
It is not a bug, you cannot use `a` and `a.b` at the same time. It will make form data too complicated.

**Comment by benjycui** [comment]
I will add a warning message for this.

**Comment by AhmedSayed77** [comment]
I should be able to use a, a.b, a.c and a.d. The are all properties of the main object. let's say that I want to change the values of a.b, a.c and a.d, so instead of setting the values in 3 lines of code, I can set a: {b, c, d} in one line

**Comment by Ancinek** [comment]
I've jumped from version 2.x.x to 3.0.2 yesterday and this is also what is happening to me.
In the 2.x.x version we had forms using multiple dynamic fields, so for example, you can add multiple `users.name` by defining the `id` to `user[0].name`, `user[${key}].name`. This has been changed now.

In your code example you shows to register the `id` like this `user-${key}`. Why did this behavior change comparing to the version 2.x.x? I mean, was there any reason to do it?

**Comment by benjycui** [comment]
@Ancinek see: df1c56e

**Comment by hz-equityzen** [comment]
This shouldn't be labelled as "won't fix". It is a very common usage of form sets.
For example, redux-form has this "Field Array": https://redux-form.com/6.0.5/examples/fieldarrays/ (go to the link and click on Add Members"

**Comment by Aeyos** [comment]
We understand that `users[i]` is considered a field and `users[i].name` is considered another field, but not allowing this type of construct makes a repeater field with multiple inputs much more difficult than it needs to be. UX is also developer's experience.

**Comment by AhmedSayed77** [comment]
@Aeyos thanks for your help. How about removing a user?

**Comment by Aeyos** [comment]
> @Aeyos thanks for your help. How about removing a user?

Sorry for the very late response, I was wrapped up in a lot a stuff.

What I ended up doing was creating a new field to store the count for how many entries my array has. I suppose you're trying to make a repeater field just like in formik or redux-form where we could do things like: ``<input name={`users[${i}].name`} />``

Problem is, when you call `getFieldDecorator`, whatever you pass in as the name, can't be used as part of another field... For example, the following is NOT allowed:

```javascript
  ...
  getFieldDecorator('users', { initialValue: [] });
  ...
  getFieldDecorator('users[0].name', { initialValue: 'Dan' });
```

To get around this issue, what I did was instead of declaring the "Array" users, I declared a field that holds how many users I have, like so:
`getFieldDecorator('.repeat-users', { initialValue: 0 });`
then, I make a for-loop starting at 0 and going all the way to `.repeat-users`.

- Rendering users
```javascript
const rows = getFieldValue(`.repeat-users`);
for (let index = 0; index < rows; index++) {
  ...
  getFieldDecorator(`users[${index}].name`, ...)
  ...
}
```

- Adding a new user:
```javascript
addRow() {
  // Antd functions
  const { getFieldValue, setFieldsValue } = this.props.form;
  // Increment field counter
  setFieldsValue({ '.repeat-users': getFieldValue('.repeat-users') + 1 });
}
```
This should make a new field to be rendered on your for-loop

- Removing an existing user
```javascript
delRow(index) {
  const { getFieldValue, setFieldsValue } = this.props.form;
  const entries = getFieldValue('users').slice();
  entries.splice(index, 1);
  setFieldsValue({ users: entries });
  setFieldsValue({ '.repeat-users': getFieldValue(`.repeat-users`) - 1 });
}
```
This makes the for-loop render `n-1` fields, thus removing one entry from the array.

This code was extensively tested and I can confirm it works. If you need further help, you can find me at vinicius.m.negrao@gmail.com, don't be afraid to contact me, I was very frustrated by this as well but managed to make it work. Hope this helps anyone having this kind of problems

**Comment by snapwich** [comment]
@benjycui the demo page you link to does not demonstrate how to generate a repeating _group_ of fields, only a singular repeating field.  Generating a repeating group seems like a valid and somewhat common use case for forms, as demonstrated in @hz-equityzen's example, and I have run into the same issue the others here are experiencing while trying to implement such a case.

How would you propose to do this with the restrictions we have here?  @Aeyos solution works, but seems extremely hacky (no offense, gotta do what you gotta do) to work around the imposed limitations.

Can you provide an example of how we should be implementing a repeating group of fields?

**Comment by OwenMelbz** [comment]
Looks like this is still a problem.

We're having the same trouble, it looks like the `setFieldsValue` only assumes you're adding/editing and never removing as if you did something like:

```js
const things = [
    {name: xx, email: xx},
    {name: yy, email: yy},
]

this.props.form.setFieldsValue({
    things: things
})

console.log(this.props.form.getFieldsValue())

// { things: [{name: xx, email: xx}, {name: yy, email: yy}] }
```

Then when you try to completely empty it e.g. 

```js
this.props.form.setFieldsValue({
    things: []
})
```

You still get the exactly same result as before being

```js
// { things: [{name: xx, email: xx}, {name: yy, email: yy}] }
```

**Comment by liudonghua123** [comment]
I have also the same strange behavior.

**Comment by liudonghua123** [comment]
I modified the example (https://ant.design/components/form/#components-form-demo-dynamic-form-item), and now it worked. see https://codepen.io/liudonghua123/pen/gNeqjp for more details.
