### ISSUE TITLE
antd table组件在safari下卡顿

### ISSUE THREAD

**Issue by memoryza** [ant-design/ant-design#8537]
浏览器版本：版本 11.0.2 (13604.4.7.1.3)
系统：10.13.2（macos high sierra）

试验过后发现antd的table 在safari 渲染直接阻塞住页面其他事件，造成页面卡顿
期间 table 有一个prefixCls  的属性，我将属性不传递给rc-table的时候也没渲染不卡了，
感觉是css什么属性影响到了，但是没找到

其中 https://preview.pro.ant.design/#/list/table-list 例子中翻页，排序，然后点击其他均有卡顿现象。

在系统升级之前，safari（12.06）确认过同样的页面渲染和交互不卡顿。升级之后造成的。

**Comment by memoryza** [comment]
后来经过排查，发现ant-table  && ant-table table 的overflow: hidden造成的

**Comment by superlbr** [comment]
确实会卡顿，但是overflow：hidden去掉还是卡 @memoryza

**Comment by wupinlang** [comment]
@superlbr @memoryza 请问你们是怎么解决这个问题的？

**Comment by lucky3mvp** [comment]
@memoryza 把overflow:hidden去掉了，不卡了，感谢！！！

好奇这种问题当初排查的时候是怎么排查的。。。
