### ISSUE TITLE
antd table components render so slow in safari

### ISSUE THREAD

**Issue by memoryza** [ant-design/ant-design#8538]
### Version
2.13.7

### Environment
mac 10.13.2（macos high sierra）
 safari 11.0.2 (13604.4.7.1.3)

### Reproduction link
[https://preview.pro.ant.design/#/list/table-list](https://preview.pro.ant.design/#/list/table-list)

### Steps to reproduce
you can click pager or sorter, then please scroll page or click other btn (not in table)
this page is so slow .

**i find the "className"  `ant-table` and `ant-table table` have   overflow: hidden make the table so slow.**

### What is expected?
不要卡顿

### What is actually happening?
slow

---
浏览器版本：版本 11.0.2 (13604.4.7.1.3)
系统：10.13.2（macos high sierra）

试验过后发现antd的table 在safari 渲染直接阻塞住页面其他事件，造成页面卡顿
期间 table 有一个prefixCls 的属性，我将属性不传递给rc-table的时候也没渲染不卡了，
感觉是css什么属性影响到了，但是没找到

其中 https://preview.pro.ant.design/#/list/table-list 例子中翻页，排序，然后点击其他均有卡顿现象。

在系统升级之前，safari（12.06）确认过同样的页面渲染和交互不卡顿。升级之后造成的。

后来经过排查，发现ant-table && ant-table table 的overflow: hidden造成的,去掉以后再safari下不卡顿，

**Comment by afc163** [comment]
Duplicate of #7799

**Comment by afc163** [comment]
Thx for the information!!! 👍

**Comment by han88829** [comment]
Solved my problem, thank you very much!
