### ISSUE TITLE
Rate can't reset

### ISSUE THREAD

**Issue by vellengs** [ant-design/ant-design#8539]
### What problem does this feature solve?
reset the value.

### What does the proposed API look like?
compare the behavior
```
http://angular-ui.github.io/bootstrap/#!#rating
```
I want to reset the rate.

https://github.com/NG-ZORRO/ng-zorro-antd/issues/713

**Comment by afc163** [comment]
So basicl, you wish to set its value to 0 by double-clicking rate?

**Comment by vellengs** [comment]
Yes,  like the bootstrap did.
```
http://angular-ui.github.io/bootstrap/#!#rating

```

**Comment by afc163** [comment]
It is not a double-clicking, just toggle it. I think we can implement it.

- http://angular-ui.github.io/bootstrap/#!#rating
- https://sapui5.hana.ondemand.com/#/sample/sap.m.sample.RatingIndicator/preview

**Comment by vellengs** [comment]
Yes, It's not really double click.
