### ISSUE TITLE
table 的row可以高亮

### ISSUE THREAD

**Issue by lyuehh** [ant-design/ant-design#854]
比如给数据添加一个属性, highlight: true, 然后table中的那一列就高亮

**Comment by afc163** [comment]
https://github.com/react-component/table#property

可以用 rowClassName 来配置。undocumented 属性。

**Comment by lyuehh** [comment]
搞定，非常感谢~

**Comment by XUGAOBO** [comment]
只能初始化的时候使用这个方法,如何更换另一行

**Comment by ranzhu123** [comment]
如果在加载完毕后再高亮另一行呢？需要重新画table吗？
