### ISSUE TITLE
Anchor ink ball does not change when using <Layout> Component 

### ISSUE THREAD

**Issue by yonidejene** [ant-design/ant-design#8543]
### Version
2.13.11

### Environment
"react": "^15.6.1",   "antd": "^2.13.1",

### Reproduction link
[https://codepen.io/yonidejene/pen/XVrdzZ?editors=001](https://codepen.io/yonidejene/pen/XVrdzZ?editors=001)

### Steps to reproduce
Create Anchors in a Sider component and create divs with corresponding target IDs in Content component. Wrap both Sider and Content components in a Layout component as shown in docs.

### What is expected?
The Anchor ink ball will update as user scrolls to the respective div.

### What is actually happening?
The Anchor ink ball does not update. So when user scrolls through, it does not reflect their current position. I have included the general structure of my code in repo. It works perfectly fine when I remove the <Layout> component and it's children.

**Comment by afc163** [comment]
You codepen is not working.
