### ISSUE TITLE
the size of Select component is not consistent with Input and Button

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#8544]
### Version
3.0.0

### Environment
antd3.0 , chrome 63.0.3239.84

### Reproduction link
[https://codepen.io/anon/pen/LePNrq?&editors=001](https://codepen.io/anon/pen/LePNrq?&editors=001)

### Steps to reproduce
look at the demo

### What is expected?
the size of Select component should keep consistent with Input and Button

### What is actually happening?
|component|small|default|larger|
|----|-------|---------|--------|
|Select|22 | 30| 38|
|Input|24|32|40|
|Button|24|32|40|

**Comment by afc163** [comment]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/507615/33818165-56e48b20-de7e-11e7-8374-93edffdccc67.png">

It works just fine.
