### ISSUE TITLE
Menu导航菜单 的选项之间，是否也可以像弹出菜单一样，可以使用 Divider分割线？

### ISSUE THREAD

**Issue by jikunchong** [ant-design/ant-design#8547]
### What problem does this feature solve?
有时候只是简单分隔，不需要使用分组。

### What does the proposed API look like?
Menu.Divider 支持 Menu导航菜单

**Comment by afc163** [comment]
`MenuItem  MenuItem  MenuItem | MenuItem`

I think it is what @jikunchong ask for.

**Comment by afc163** [comment]
It works now: https://codesandbox.io/s/713qj62z6q
