### ISSUE TITLE
A bug in ant-popover-arrow width and height

### ISSUE THREAD

**Issue by daqi** [ant-design/ant-design#8549]
### Version
3.0.1

### Environment
3.0.1

### Reproduction link
[https://github.com/ant-design/ant-design/blob/bbbdb9911d0d39e1721252c02046074ead7279a1/components/popover/style/index.less#L105](https://github.com/ant-design/ant-design/blob/bbbdb9911d0d39e1721252c02046074ead7279a1/components/popover/style/index.less#L105)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/bbbdb9911d0d39e1721252c02046074ead7279a1/components/popover/style/index.less#L105
This `&` will overwrite the width and height has set before

### What is expected?
Do not overwrite the width and height

### What is actually happening?
width:0;
height:0;

**Comment by afc163** [comment]
I cannot see any bug in your description.

**Comment by afc163** [comment]
Although these code is unused now.

**Comment by daqi** [comment]
@afc163 I just set a 'modifyVars' of '@popover-arrow-width' , but it no effect, just because this style!

**Comment by afc163** [comment]
Right, fixed above.
