### ISSUE TITLE
Autocomplete: notFoundContent does not work

### ISSUE THREAD

**Issue by nick1247** [ant-design/ant-design#8553]
### Version
3.0.1

### Environment
win10, chrome 64.0.3278.0

### Reproduction link
[https://codesandbox.io/s/r7o8765w5q](https://codesandbox.io/s/r7o8765w5q)

### Steps to reproduce
Try to input some text in field

### What is expected?
Based on [https://github.com/ant-design/ant-design/issues/4729](https://github.com/ant-design/ant-design/issues/4729) showing spinner is expected

### What is actually happening?
Spinner does not show

---
Looks like it's happened, because notFoundContent is disabled for select in combobox mode
[https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L138](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L138)

**Comment by RaoHai** [comment]
跟这个 issue 一样的，不过那个被机器人关了。。
+ https://github.com/ant-design/ant-design/issues/8551

**Comment by closertb** [comment]
has this issue fixed ???
