### ISSUE TITLE
menu and table running slowly in ie and edge

### ISSUE THREAD

**Issue by sjmmm** [ant-design/ant-design#8554]
### What problem does this feature solve?
problems with ie and edge:
1.The subMenu is particularly slow to Expand and collapse.
2.The cpu continues to rise when slide the mouse over the table

### What does the proposed API look like?
run smoothly

**Comment by yesmeck** [comment]
Have you tried demos on https://ant.design, are they slowly too?

**Comment by sjmmm** [comment]
Testing demos found that the table scrolling and sliding hover will cause the cpu to rise and the page to load slowly.

**Comment by yesmeck** [comment]
Trace #8306
