### ISSUE TITLE
3.0.0版本中 Form表单中使用Checkbox报错

### ISSUE THREAD

**Issue by wushengqiang** [ant-design/ant-design#8555]
在Form表单中
   
<FormItem>
     {getFieldDecorator('remember', {
         valuePropName: 'checked',
         initialValue: true
     })(
            <Checkbox>记住用户名密码</Checkbox>
     )}
  </FormItem>
有警告提示，提示如下
Warning: Failed prop type: Invalid prop `checked` supplied to `Checkbox`.

**Comment by wongwf82** [comment]
Leaving a comment on the solution here for `antd 3.x` versions. We encountered this same error on `antd 3.16.5` for Checkbox.

The solution that worked for us is setting initialValue to boolean `true` or `false`, while avoiding using string type.
