### ISSUE TITLE
How to use growingIO api in antd?

### ISSUE THREAD

**Issue by WebPuY** [ant-design/ant-design#8556]
### What problem does this feature solve?
Here is the growingIO api.

"开启输入文本框内容采集

由于输入文本框可能涉及一些隐私信息，比如账号、密码等，GrowingIO在采集数据的时候默认不采集输入文本框的数据。如果您希望采集某些文本框输入内容，比如搜索词，可以在input标签中设置growing-track属性，这样该文本框中的输入内容就会被采集到。如果input类型是password，即使开启内容采集，也不会采集该文本框的输入内容。

    <input type='text' growing-track='true' />"

In my project, we want to add growingIO api to antd's Input component to analysis of user data. When I use that api, antd gave me a warning of "Unknown prop `growing-track` on <input> tag. Remove this prop from the element. For details".This is the standard API. How to solve it?

### What does the proposed API look like?
````
<input type='text' growingTrack="true" />
````

**Comment by afc163** [comment]
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html
