### ISSUE TITLE
Sub Menu flash when hover from one to another

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8557]
![flash](https://user-images.githubusercontent.com/507615/33825834-e06082f4-de9d-11e7-8054-0dc288fdcdc5.gif)

version: 3.0.1
browser: all
link: https://ant.design/components/menu/#components-menu-demo-vertical

**Comment by jljsj33** [comment]
will-change: transform

**Comment by jljsj33** [comment]
啥时候把展开的劝画加回上去，，，@benjycui

**Comment by afc163** [comment]
@jljsj33 3.0.1 已修复。

**Comment by benjycui** [comment]
预期效果是什么？

**Comment by jljsj33** [comment]
从下（第二个）经过上（第一个）时，，第一个的弹出菜单会闪。。。他的截取GIF没截好。。。帧频少了就看不出闪动了。。。

**Comment by benjycui** [comment]
在 rc-menu 无法重现 http://react-component.github.io/menu/examples/antd.html ， @afc163 确认下 rc-menu 在你那里也无法重现。

**Comment by afc163** [comment]
对，rc-menu 里重新不了。
