### ISSUE TITLE
When the <Table> component sets the showQuickJumper and showSizeChanger parameters for pagination, the margin property between the sizeChanger <Select> and the jump to the page is 0.

### ISSUE THREAD

**Issue by duan602728596** [ant-design/ant-design#8559]
### What problem does this feature solve?
When the **&lt;Table&gt; component** sets the **showQuickJumper** and **showSizeChanger** parameters for pagination, the **margin** property between the **sizeChanger &lt;Select&gt; component** and the **jump to the page component** is 0.   
`.ant-select: margin 0` covered `.ant-pagination-options-size-changer: margin-right: 8px`. I don't think it looks very beautiful.

### What does the proposed API look like?
When the **&lt;Table&gt; component** sets the **showQuickJumper** and **showSizeChanger** parameters for pagination, the interval between **sizeChanger &lt;Select&gt; component** and **jump to the page component** will be more beautiful.

**Comment by afc163** [comment]
Could you provide a screen capture at least?

**Comment by duan602728596** [comment]
![https://github.com/duan602728596/document/blob/master/image/1.png](https://github.com/duan602728596/document/blob/master/image/1.png)
