### ISSUE TITLE
渲染上一次的数据

### ISSUE THREAD

**Issue by basicfu** [ant-design/ant-design#8560]
### Version
3.0.0

### Environment
mac/win chrome safair都有这个问题

### Reproduction link
[https://user-images.githubusercontent.com/26153901/33829813-b1aa11be-deac-11e7-81e5-a5b638382ed8.gif](https://user-images.githubusercontent.com/26153901/33829813-b1aa11be-deac-11e7-81e5-a5b638382ed8.gif)

### Steps to reproduce
- 见上述链接gif
- 多台电脑都尝试了，都是使用更新了依赖后才发生的问题，没有更新依赖之前是没问题的，之前使用的是3.0beta版本，现在使用的是3.0线上版本
- gif演示：<https://user-images.githubusercontent.com/26153901/33829813-b1aa11be-deac-11e7-81e5-a5b638382ed8.gif>
- 在线链接：<http://weiduo.dmka.cn/>
- 用户名：test
- 密码：test
- 进入后点击设备管理

### What is expected?
不应渲染上一次数据

### What is actually happening?
渲染的是上一次的数据

---
请问这是什么情况，当编辑一条数据的后再次编辑其他数据，随便每次修改一下就会渲染上一次操作的数据，这个问题在我移除了之前安装的依赖后重新cnpm install新的依赖后发生，依赖版本都和demo一致，开发了2个月了都没出现这种情况，就今天重新装了下依赖发生的，不理解

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codesandbox: http://u.ant.design/codesandbox-repro

**Comment by HunDunDM** [comment]
It happens when Modal and Form are used simultaneously.

I have the same problem on this side.

**Comment by basicfu** [comment]
I understand.
See:[#3311](https://github.com/ant-design/ant-design/issues/3311#issuecomment-252025039)
initialValue = defaultValue ,Only for the first time
I now use mapPropsToField，No problem

**Comment by HunDunDM** [comment]
I think `mapPropsToField` is going to be used with Redux. It's not necessary.

In fact, I would get `You cannot set field before registering it.` from console. But I've never used `setFieldsValue`, just set up `initialValue` in `getFieldDecorator`. And I'm sure I've already called `resetFields` before.

However, I can't reappear in the new project. So I think it's more likely to be my problem.

**Comment by HunDunDM** [comment]
I found out how to reappear. And I probably know the reason for my problem.

It's because of the use of `hidden` in `getFieldDecorator`.

If a field is set up `hidden: true`, `resetFields` is not effective for it. The previous version was not the same.

Look at the `rc-form` `createFieldsStore.js` `resetFields`

[1.5.0](https://github.com/react-component/form/blob/1.5.0/src/createFieldsStore.js)
`const { fields } = this;`

[2.1.5](https://github.com/react-component/form/blob/2.1.5/src/createFieldsStore.js)
`this.getValidFieldsName();` This ignores the hidden fields.

I want to know which is the expected effect.

**Comment by benjycui** [comment]
@basicfu you can use reset fields.

@HunDunDM will trace your issue in rc-form.

So, this issue will be close, thanks.

**Comment by deivamagalhaes** [comment]
Hi, I'm having the same issue and trying to navigate these Chinese comments/links. What is not clear to me is where I should use `resetFields`. Can somebody please clarify?

**Comment by yesmeck** [comment]
@deivamagalhaes In 3.1.0, we've introduced a new prop called `destroyOnClose`.

**Comment by msdlisper** [comment]
I have the same problem, when I try to set a value to a FormItem that  doesn't exist(Form doesn't have the FormItem for the value's key)
