### ISSUE TITLE
Allow data-attributes for all components

### ISSUE THREAD

**Issue by DStoyanoff** [ant-design/ant-design#8561]
### What problem does this feature solve?
Hello, we are using antd in my team and we love it. In the process of our automated testing, we need to add custom html attributes to the DOM elements, so we can easily find them on the page. However most of the components do not respect custom attributes, thus not rendering them. Is it possible that such thing is implemented?

### What does the proposed API look like?
Allow rendering ...rest properties, passed to a component.

**Comment by yesmeck** [comment]
Related #8305

**Comment by yesmeck** [comment]
All components accept `className`,  you can add unique className to component, then find them by className.

**Comment by apieceofbart** [comment]
@yesmeck using `className` is workaround - it pollutes the markup, can potentially break the app if someone uses wrong class name etc. The standard way would be to allow for `data` attributes to be passed.
Curious: why not allow to pass any custom attributes?

**Comment by sander-vink** [comment]
We could really use this feature as well. Abusing the `className` property is not a good idea, and we would very much like to avoid that workaround.

**Comment by matthewlein** [comment]
I'm going to start work on PRs to allow `data-*` attributes for many of the components unless there are are objections from the maintainers. @yesmeck @afc163 Any issues with that? Would you want them in one PR for all, or each component at a time?

**Comment by matthewlein** [comment]
Planning on something like this https://github.com/matthewlein/ant-design/commit/335807b16b8c3ece9f63a0d8b73113ddfc2ec5c1

**Comment by apieceofbart** [comment]
@matthewlein why not allow passing any attributes?

**Comment by matthewlein** [comment]
@apieceofbart Yea, my preference would be to pass everything, but I opted for the more conservative since I don't own this project.

Ideally, I'd do something like

```
const { all, props, we, want, ...otherProps } = this.props;
<Component {...otherProps} />
```

And now that I've looked at the codebase more, there are a fair amount of examples like that:

```
...
let checkboxProps: CheckboxProps = { ...restProps };
...
const divProps = omit(others, [
  'onTabChange',
]);
```
So maybe I will switch to that, it should cover `data-*`, `aria-*`, and the unknown wild future of attributes.

Ultimately, I just want to do the one that will get merged though 😅.

**Comment by apieceofbart** [comment]
Yeah, I understand you totally, just a thought that `data-` isn't that special and there are other cases. I think  you'll have to extend (if I'm correct) every props interface to allow `data-` props, you might as well do that for any custom props. Thanks for working on that!

**Comment by matthewlein** [comment]
True, types are where things could get a bit tricky. I realize now that the demos .md are not using typescript...I'll have to review that.

You can allow any string prop with `[key: string]: any;` but that allows any string prop...

`aria-*` attributes are predefined, so they are easier to include via https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3b8b13474ed4e489c95702d0a337598573428970/types/react/index.d.ts#L991-L1176

**Comment by apieceofbart** [comment]
hmmm but react allows any dom attribute, right? shouldn't this be in the types as well?
https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Comment by matthewlein** [comment]
@apieceofbart that article deals with jsx's handling of props, but that won't play into ant's component prop type-checking through typescript. Fortunately it seems to Just Work™. TS does not error on `data-*` or `aria-*` props. Other random props will error, as expected.

**Comment by matthewlein** [comment]
With https://github.com/ant-design/ant-design/pull/10922, the following list of components should be passing `data-*`, `aria-*`, and `role` props to their elements or rc-components. There are PRs open on many of the underlying rc-components, and when those are merged this whole list _should_ work directly, or with a workaround.

```
Alert
Button
Card
Checkbox
DatePicker -> rc-calendar
  The date input -> https://github.com/ant-design/ant-design/pull/10922
    The rc-calendar date picker widget is too complicated to pass through a single props, it would require something complicated like many popupProps, popupProps.inputProps, etc
Form
Icon
Input
InputNumber -> rc-input-number -> https://github.com/react-component/input-number/pull/107
Menu
  Menu.Item
Message
  filed https://github.com/ant-design/ant-design/issues/10919 for approval before starting
Modal -> https://github.com/ant-design/ant-design/pull/10922
  <Modal wrapProps={{
    'data-test': 'whaaaa'
  }} />
  just needed update ModalProps with `wrapProps?: any;`
Pagination -> rc-pagination -> https://github.com/react-component/pagination/pull/135
Radio
  Radio.Button
Select -> rc-select -> https://github.com/react-component/select/pull/305
  Select.Option
Spin
Table -> rc-table -> https://github.com/react-component/table/pull/211
  Can also accomplish with custom table component
  class MyTable extends React.Component<any, {}> {
    public render() {
      return (
        <table data-test="Table">
          {this.props.children}
        </table>
      )
    }
  }
  <Table columns={columns} dataSource={data} data-test="Table" aria-errormessage="Table" components={{table: MyTable}} />
Tooltip -> rc-tooltip
  works by passing in react element to title
  <Tooltip title={<span data-test="tooltipContent">tooltip content</span>}>
TreeSelect -> rc-tree-select -> https://github.com/react-component/tree-select/pull/112
  TreeNode -> rc-tree -> https://github.com/react-component/tree/pull/172
```

**Comment by liangpure** [comment]
I develop a babel-plugin to auto add test className.
https://github.com/liangpure/babel-plugin-antd-test-class, still need some work on it.

emm...
(my team used className to set the id of the QC auto test. But now QC still wants to use id.
Maybe It's useless for my team...)

**Comment by liangpure** [comment]
I develop a babel-plugin to auto add test className.
[babel-plugin-antd-test-class](https://github.com/liangpure/babel-plugin-antd-test-class ).(need more work on it)
if could use data-*, It will be a better choice.

**Comment by afc163** [comment]
You could feel free to send PR to us for rest components which do not support yet.

**Comment by matthewlein** [comment]
@DylanVann @afc163 I made that PR to rc-notification on Jun 20...4 months ago 😢 
https://github.com/react-component/notification/pull/43

**Comment by afc163** [comment]
@matthewlein You can resolve the conflict and I will handle it ASAP.

**Comment by DylanVann** [comment]
@afc163 I rebased that PR: https://github.com/react-component/notification/pull/54

**Comment by hzaben81** [comment]
It seems that `Tabs.TabPane` does not render `data-tid`. Could you fix this as well?

**Comment by hzaben81** [comment]
It seems you can do this for tabs pane
```javascript
  <Tabs.TabPane
    tab={(
      <span data-tid="...">
        {ttitle}
      </span>
    )}
  >
```
And it will render the data-tid with the text of the tab

**Comment by mlsad3** [comment]
Hi @DylanVann, has this made it in yet? From my searches it looks like it is in limbo. I really really want to use this for my end-to-end testing

**Comment by momesana** [comment]
> All components accept `className`, you can add unique className to component, then find them by className.

That advice amounts to abusing an attribute that is highly volatile, subject to change and above all meant for styling as a means to query elements. There is a reason data-attributes exist and they also come in handy for ui-testing purposes: https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements.

It would be really nice and would spare us a lot of workarounds if antd passed unmatched props (...otherProps) down to it's container elements or children.

We worked around this by writing a HOC that wraps the Component in a div/span etc. which correctly handle data-attributes.

**Comment by michelmeeuwissen** [comment]
```
<Modal
            title={title}
            visible={true}
            closable={true}
            onCancel={() => onClose()}
            destroyOnClose={true}
            data-testid={'dummy'}  //Does not work
            className={'dummy'} /> //Work
        >
```
antd 3.26.11
Going to use className for now as a workaround

**Comment by RavilM** [comment]
Up

**Comment by luco** [comment]
Up

**Comment by YuvarajPandiyan** [comment]
> https://codesandbox.io/s/4xw97z4jyw

Adding an extra span element will create a problem so slowness unnaseoerry element creation.

**Comment by shamseerahammedm** [comment]
+1
