### ISSUE TITLE
Bordered list with pagination styling

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#8562]
### Version
3.0.1

### Environment
Chrome 62

### Reproduction link
[https://codesandbox.io/s/404kpxqo07](https://codesandbox.io/s/404kpxqo07)

### Steps to reproduce
List: bordered = true, paginated = object

### What is expected?
The footer area should have equal padding around the paginated numbers.

Something like: 

![image](https://user-images.githubusercontent.com/842078/33838824-81198954-de88-11e7-8ebb-8edb9d1f9a3e.png)

### What is actually happening?
It's sticking to the bottom of the footer, causing a "double border" effect.

![image](https://user-images.githubusercontent.com/842078/33838756-60443d28-de88-11e7-8441-5e1feb0d1c40.png)

**Comment by wangbagang** [comment]
You can do this: https://codesandbox.io/s/y001n3jr8v.
