### ISSUE TITLE
Trriger Click

### ISSUE THREAD

**Issue by vinceDa** [ant-design/ant-design#8567]
### Version
3.0.1

### Environment
win7x64  Maxthon

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
click on the secondary menu, then unpack the menu, and the selected item will become unselected

### What is expected?
the selected item should still be selected

### What is actually happening?
the selected item is not selected

**Comment by afc163** [comment]
Can you take a gif?

**Comment by dengfuping** [comment]
![2017-12-12 15_14_58](https://user-images.githubusercontent.com/14918822/33871929-98ef466e-df4f-11e7-8352-7242b3a3755d.gif)

like this? @vinceDa

**Comment by dengfuping** [comment]
![2017-12-12 15_21_46](https://user-images.githubusercontent.com/14918822/33872053-360c3a88-df50-11e7-876c-0f01754d4131.gif)

like this? @vinceDa

**Comment by danedavid** [comment]
Looks like `keyPath` is not being set as intended.  
When clicked on 'Option 5', the keyPath is `["5"]` instead of `["5", "sub1"]`, the behavior I saw in `rc-menu` component.

![image](https://user-images.githubusercontent.com/19928280/33874789-03f4fad0-df46-11e7-9b0f-b5f3977431a6.png)

**Comment by vinceDa** [comment]
Yes,thank you for your reply.I'm sorry that I didn't have the habit of opening the mailbox.I will pay attention to the mailbox later(ps:yao shi ke yi yong zhong wen gou tong duo hao...)


On 12/12/2017 15:23，诸岳<notifications@github.com> wrote：

like this? @vinceDa

**Comment by vinceDa** [comment]
I'm sorry...I was too late to  revert you..
On 12/12/2017 10:43，偏右<notifications@github.com> wrote：

Can you take a gif?
