### ISSUE TITLE
Icon 组件能否支持使用 svg 格式的 icon

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design#8568]
### What problem does this feature solve?
iconfont.cn 已经推荐使用 svg 的方式使用图标了，antd 里的 Icon 组件能否支持使用 svg 格式的 icon

### What does the proposed API look like?
```
<Icon type="link" mode="svg" />
```

**Comment by afc163** [comment]
暂时没有这个计划，font 在部署、样式覆盖、文本排版上都有很大的优势。
