### ISSUE TITLE
增加  picture-card upload

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#857]
和现在 Uploader 完全不同的结构和样式：

<img width="426" alt="2016-01-13 2 28 04" src="https://cloud.githubusercontent.com/assets/200876/12286796/5820ce60-ba02-11e5-9100-0797c6d9ede9.png">

@kasinooya

**Comment by afc163** [comment]
ref #708

**Comment by shepherdwind** [comment]
和我的 dropzone 有点像啊 https://github.com/react-component/dropzone

**Comment by afc163** [comment]
和 http://ant.design/components/upload/#demo-picture-style 的信息结构是一样的，增加一种样式即可。
