### ISSUE TITLE
Select defaultValue not updating on second re-render

### ISSUE THREAD

**Issue by synapse** [ant-design/ant-design#8574]
### Version
3.0.1

### Environment
browser Chrome

### Reproduction link
[https://codesandbox.io/s/r1300koln](https://codesandbox.io/s/r1300koln)

### Steps to reproduce
Check the sandbox code

### What is expected?
Should update the defaultValue

### What is actually happening?
Remains empty

---
I've created an example where using a multiselect. The items are fetched via AJAX (in this case setTimeout). If the select' defaultValue is set on the first render everything works fine but if set in an async way it won't update.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically
