### ISSUE TITLE
Does ant-design has full screen popup component?

### ISSUE THREAD

**Issue by jonahfang** [ant-design/ant-design#8575]
### What problem does this feature solve?
We use  full screen popup component to avoid page transition

### What does the proposed API look like?
full screen popup.

**Comment by afc163** [comment]
what is a full screen popup?

**Comment by benjycui** [comment]
Just use a `div` with the following CSS:

```css
position: fixed;
top: 0;
left: 0;
height: 100vh;
width: 100vw;
```
