### ISSUE TITLE
Table component does not respect size in regards to cellpadding when using a fixed header or column

### ISSUE THREAD

**Issue by LinusCenterstrom** [ant-design/ant-design#8577]
### Version
3.0.1

### Environment
any

### Reproduction link
[https://ant.design/components/table/#components-table-demo-dynamic-settings](https://ant.design/components/table/#components-table-demo-dynamic-settings)

### Steps to reproduce
Select fixed header in the dynamic table in the demo, then change Size. The padding for the cells stays the same no matter which size is selected.

### What is expected?
The cell padding to be the same as when not using fixed header or column

### What is actually happening?
The cell padding is the same no matter which size you use

**Comment by goreRatzete** [comment]
Not sure if this is related, I posted on Gitter yesterday:
Hi guys, I just updated to 3.0.1 and the Table size is no longer working with scroll
I have a demo here: https://codesandbox.io/s/zk9jzpo35x
