### ISSUE TITLE
Lost css rules in IE9

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design#8578]
### Version
3.0.1

### Environment
MacOS 10.13.1 / Chrome 62.0.3202.94 / antd@3.0.1

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Use `antd` in IE9.

### What is expected?
Can see table component work well in IE9.

### What is actually happening?
Table has no css rules for displaying.

---
CSS of `antd` has too many css rules. IE9 have work around for the 4095 rule limit. I resolve the problem by using `css-split-webpack-plugin`.

**Comment by benjycui** [comment]
We already split CSS, see 

https://github.com/ant-design/ant-design/blob/0eac8aa1c6392cd820fcb5a41421ad70fdb10aff/site/bisheng.config.js#L97

**Comment by afc163** [comment]
The office site is frozen in IE9 now.

**Comment by lovekonakona** [comment]
@benjycui Ops, I just write `@import '~antd/dist/antd.less';` in my main less, so I got that problem, my bad.
