### ISSUE TITLE
IE8下antd组件无法加载， default 在IE8下是关键字？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#858]
以前没遇到过，突然就出现了。 不知道是不是 default 没用引号包裹引起的， 我看rc的js是'default' 
![image](https://cloud.githubusercontent.com/assets/2271825/12286781/401c58ca-ba02-11e5-9c5e-81364c0368eb.png)

**Comment by afc163** [comment]
https://github.com/ant-tool/atool-build/issues/28

**Comment by sorrycc** [comment]
之前的配置没处理 node_modules，试下这个配置：
https://github.com/ant-design/antd-init/blob/master/boilerplate/webpack.config.js#L10-L14

**Comment by codering** [comment]
@sorrycc   不用webpack, 怎么处理？

**Comment by benjycui** [comment]
你指的单独用是只引进某个组件么？

```js
import Button from 'antd/lib/button';
```

**Comment by codering** [comment]
@benjycui  恩。

**Comment by codering** [comment]
@benjycui  我疑惑的是 rc组件没依赖es3ify也可用，antd就不可用，编译工具不一样？

**Comment by benjycui** [comment]
1. 只要你是用 `antd-init` 生成的模板进行开发，在打包时会自动按需打包。
1. `npm i antd` 得到的代码就已经是编译过的了。

**Comment by sorrycc** [comment]
@codering rc-component 编译是用的 babel5，所以没问题。
@afc163 @benjycui  antd 编译代码的时候加入 es3ify ?

**Comment by afc163** [comment]
可以有。

**Comment by sorrycc** [comment]
dist 文件可以加，但 src 下的文件加起来挺麻烦的，还是不要搞了。redux 作者采用的方法是切换成 commonjs 的 module 写法。

https://phabricator.babeljs.io/T2817#70267

**Comment by codering** [comment]
我用的fis3, 自己写个基于es3ify的parser插件解决了。

**Comment by afc163** [comment]
目前 https://github.com/ant-design/antd-init 脚手架的默认模板已经解决了 IE8 的问题。

**Comment by sorrycc** [comment]
https://phabricator.babeljs.io/T2817#73231

**Comment by afc163** [comment]
babel@6.6 解决了这个问题。babel/babel#3368
