### ISSUE TITLE
TreeSelect: Clicks "X" to remove selected item in the input box of filter, the returned information is not complete compared to unselect a selected item in the dropdown menu.

### ISSUE THREAD

**Issue by lydiahearful** [ant-design/ant-design#8580]
### Version
2.13.8

### Environment
Windows 10, Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Reproduction link
[https://codesandbox.io/s/0m46kqvvml](https://codesandbox.io/s/0m46kqvvml)

### Steps to reproduce
1. Checked both the Node1 and Node2.
2. Click 'X' to remove Node2 from the input box.

### What is expected?
Console log the props of each selected node. Both Click 'X' to remove Node2 and unselect Node2 from drop-down menu should return value list below.
Object {value: "0-0", title: "Node1", disabled: false, selectable: true, foo: 1, children: Array[1]}

### What is actually happening?
Unselect from drop-down menu is correct. But click 'X' to remove Node2 will return incomplete info for Node1. It returns
Object {title: "Node1", label: "Node1", value: "0-0", children: Array[1]}
The "foo" and some other properties are missed.

---
When user clicks "X" to remove selected item in the input box of filter, the returned information is not complete compared to unselect a selected item in the dropdown menu. Which means, I cannot get the property ("foo") of the selected item when user removing the item by click "X"

**Comment by HelloQingGuo** [comment]
I have successfully run ant-design locally, and tracked it down this issue and found the dependency `rc-tree-select` that `Antd` is using has officially clarified that this behaviour is actually as expected:
[Note of rc-tree-select](https://github.com/react-component/tree-select#note)
> In treeCheckable mode, It has the same effect when click x(node in Selection box) or uncheck in the treeNode(in dropdown panel), but the essence is not the same. So, even if both of them trigger onChange method, but the parameters (the third parameter) are different. （中文：在treeCheckable模式下，已选择节点上的x删除操作、和相应 treeNode 节点上 checkbox 的 uncheck 操作，最终效果相同，但本质不一样。前者跟弹出的 tree 组件可以“毫无关系”（例如 dropdown 没展开过，tree 也就没渲染好），而后者是 tree 组件上的节点 uncheck 事件。所以、即便两者都会触发onChange方法、但它们的参数（第三个参数）是不同的。）

**Comment by zombieJ** [comment]
done. https://github.com/react-component/tree-select/pull/105
