### ISSUE TITLE
Click on checkable tree label does not check/uncheck option

### ISSUE THREAD

**Issue by blkdr** [ant-design/ant-design#8581]
### Version
3.0.1

### Environment
Linux, Chrome >62

### Reproduction link
[https://codesandbox.io/s/1o7050y72j](https://codesandbox.io/s/1o7050y72j)

### Steps to reproduce
Click on any label inside the TreeSelect component ('Click me!' text)

### What is expected?
Option may be checked or uncheked on label selection.

### What is actually happening?
The label is highlighted, neither Enter o Space bar check or uncheck the highlighted tree nodes/childrens

---
I tried to manually check/uncheck the tree nodes (although this behaviour maybe need to be the default) only to see that `onSelect` callback does not trigger when labels are selected while `treeCheckable` is set to `true`

**Comment by afc163** [comment]
1. The check and select behaviors are individual now.
2. `onSelect` should be triggered when `treeCheckable` is true, I think it is a bug.

**Comment by yesmeck** [comment]
`onSelect` has different meaning in `TreeSelect` other than `Tree`. I think the initial purpose of  `onSelect` is it only triggers when a node is  selected as `TreeSelect`'s value. Maybe we should introduce a new prop `onTreeNodeSelect`.

**Comment by yesmeck** [comment]
Further more, I think we add check/uncheck on select as a default behavior?

**Comment by blkdr** [comment]
@yesmeck that makes sense :+1:

**Comment by valleykid** [comment]
Is this expected? @blkdr 
![treeselect](https://user-images.githubusercontent.com/1892857/34973775-63db1c1a-fac4-11e7-9ae3-7c4e3f257c12.gif)

**Comment by blkdr** [comment]
@valleykid yes, I though that will be the default behaviour.

**Comment by Zero0331** [comment]
Is this problem solved? I wnat to use Tree click on the text to selected node Instead of TreeSelect

**Comment by yutingzhao1991** [comment]
fixed in rc-tree-select 1.12.9. update antd for this problem.
