### ISSUE TITLE
Carousel or react-slick's bug

### ISSUE THREAD

**Issue by WingMrL** [ant-design/ant-design#8583]
### Version
2.13.9

### Environment
* MacOS Sierra version: 10.12.4, 
* Chrome Version: 62.0.3202.94 (Official Build) (64-bit), 
* React version: 16.0.0

### Reproduction link
[https://codepen.io/winguno/pen/ZvEgMz](https://codepen.io/winguno/pen/ZvEgMz)

### Steps to reproduce
1. When the page loaded, click `click me to show` to show the Popover with content of Carousel.
2. Click `click me to show` again to hide Popover.
3. Resize the window(broswer).
4. Click `click me to show` to show the Popover.
5. That's it. 

### What is expected?
The three cards do not overlap together and play well.

### What is actually happening?
The three cards overlap together and dots play well. It's believed this bug is produced by react-slick.

---
I know this : https://github.com/akiran/react-slick/issues/824

Thx !

**Comment by afc163** [comment]
You can try `destroyTooltipOnHide` of Popover for a workaround.

**Comment by WingMrL** [comment]
@afc163 Thank you for your time. That's a good idea which will reset Carousel's index to 0 however.
