### ISSUE TITLE
Menu model设置成vertical 怎么不显示箭头

### ISSUE THREAD

**Issue by k365266378** [ant-design/ant-design#8585]
### What problem does this feature solve?
在antd2.x版本 Menu Model设置成vertical后。 设置的宽度刚好显示一个图标时不会显示箭头。 升级成3.x以后。会显示箭头
![image](https://user-images.githubusercontent.com/34059972/33924116-87c1642e-e00f-11e7-88b3-bd5fd9b75631.png)

### What does the proposed API look like?
隐藏箭头

**Comment by afc163** [comment]
If you are trying to report a bug, please use bug-report template other than feature request.
