### ISSUE TITLE
The sidebar shrinks and the menu still displays

### ISSUE THREAD

**Issue by zhayes** [ant-design/ant-design#8587]
### Version
3.0.1

### Environment
antd @3.0.1

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
侧边栏收缩后，下拉菜单仍然显示到页面

### What is expected?
侧边栏收缩后，下拉菜单同样消失

### What is actually happening?
侧边栏收缩后，下拉菜单停留在页面
![image](https://user-images.githubusercontent.com/17758062/33927358-ea75aa46-e01c-11e7-9da4-c0a6ac30e26d.png)

![image](https://user-images.githubusercontent.com/17758062/33927350-e3a35722-e01c-11e7-8e4f-673a8d8a27a4.png)

**Comment by zhayes** [comment]
@ant-design-bot @afc163  online link: [https://codesandbox.io/s/xrznrk15q4](https://codesandbox.io/s/xrznrk15q4)

**Comment by afc163** [comment]
Menu will always respect `openKeys` prop, I think it is correct behavior.

**Comment by zhayes** [comment]
@afc163  It's not going to happen in v2.3.1

**Comment by afc163** [comment]
Alrough we should still hide the sub-menu because there is not suitable position for it when menu is collapsed to `0px`.

**Comment by zhayes** [comment]
@afc163   I updated the version last night, and it happened

**Comment by zhayes** [comment]
@afc163  I bound a method of onCollapse to Menu.Side.The problem has been solved for a while.

**Cache re-empty**
```
    const onCollapse=(collapsed, type) => {
        if(collapsed){
            this.setState({
                lastsideOpenkeys:this.state.sideOpenKeys,
                sideOpenKeys:[]
            })
        }else{
            this.setState({
                lastsideOpenkeys:[],
                sideOpenKeys:this.state.lastsideOpenkeys
            })
        }
    }
```

**Comment by zhayes** [comment]
But it's not perfect  !!!!!!!!!!!!!

**Comment by wanghqwe** [comment]
The latest version of this problem remains unsolved

**Comment by treasureDouDou** [comment]
这个问题的最新版本仍未解决 +1

**Comment by wjkang** [comment]
3.5.3 仍然有这个问题

**Comment by wjkang** [comment]
@zhayes  你好，请问你解决这个问题了吗？

**Comment by clearloop** [comment]
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

this warning while  `collapsedWidth={0}`

```
"antd": "^3.18.1",
"react": "^16.8.6",
"react-dom": "^16.8.6"
```
