### ISSUE TITLE
Using with react-responsive. antd cause react-responsive failure

### ISSUE THREAD

**Issue by Stupidism** [ant-design/ant-design#8590]
### Version
3.0.1

### Environment
jest test environment

### Reproduction link
[antd-react-responsive-demo](https://github.com/Stupidism/antd-react-responsive-demo)

### Steps to reproduce
I met this bug in a complex situation and I tried to simplify it, so this test case seems strange.

```
import React from 'react';
import { mount } from 'enzyme';

import 'antd';
import MediaQuery from 'react-responsive';

test('<MediaQuery />', () => {
  const wrapper = mount(
    <div>
      <MediaQuery minDeviceWidth={1224} values={{ deviceWidth: 1600 }}>
        <div>You are a desktop or laptop</div>
      </MediaQuery>
    </div>
  );

  expect(wrapper.text()).toBe('You are a desktop or laptop');
});
```

### What is expected?
`import 'antd'` should not affect `react-responsive`

### What is actually happening?
once `antd` is imported before `react-responsive`
this test fails

---
Comment `import 'antd'` or move it one line below would make this test pass.

**Comment by benjycui** [comment]
Please provide a re-producible repo, thanks.

**Comment by Stupidism** [comment]
@benjycui https://github.com/Stupidism/antd-react-responsive-demo

**Comment by benjycui** [comment]
Just put antd after react-responsive before we can find a solution: 

```jsx
import MediaQuery from 'react-responsive';
import 'antd';
```

**Comment by yesmeck** [comment]
Closing since this issue is inactive for a long time.

**Comment by Stupidism** [comment]
@benjycui @yesmeck Consider change the variable name to a more special one? like with antd prefix?

**Comment by benjycui** [comment]
@Stupidism it is impossible to do so, this polyfill is not for antd itself.

**Comment by joelgetaction** [comment]
Hi,

Has there been any progress on this?  I'd like to use `react-responsive` but this issue is making me apprehensive to do so.  It's not so easy to just say "import MediaQuery before antd" because some style guidelines require imports to be ordered alphabetically.  And relying on the order of imports to guarantee code correctness is not reliable and is just a bug waiting to happen.

Any ideas how to fix this?

Please re-open!  :-)

Thanks!

**Comment by contra** [comment]
This is an issue with antd - they muck up the global `window` object, here is their code:

```
window.matchMedia = window.matchMedia || matchMediaPolyfill;
```

Unfortunately we can't do anything about it - you should ask them to not do this, it is frowned on to patch `window`. The polyfill we use doesn't write to the `window` object.

**Comment by contra** [comment]
FWIW the issue is that our polyfill will read `window.matchMedia` and return that if it exists already, so it doesn't polyfill when it doesn't need to. Since antd writes to that it is returning the `antd` polyfill. I'm not sure why exactly their polyfill fails, but the issue is still on them to not do that.

**Comment by joelgetaction** [comment]
@benjycui @yesmeck please see remarks from @contra above that this is a problem in antd.  Any chance you can fix this?

For now I am using react-media but I'd rather use react-responsive.

**Comment by pfurini** [comment]
> For now I am using react-media but I'd rather use react-responsive.

@joelgetaction why do you prefer react-responsive?.. take a look at this [comment](https://github.com/ReactTraining/react-media/issues/70#issuecomment-347774260) on the fundamental difference between the two, and while you should prefer react-media:

> ... when the media query does not match you still create all of those elements, but essentially discard them when none of them are rendered to the page.
> In contrast, **react-media takes a different approach by using a render prop to conditionally create elements only when the media query matches**, which saves you creating all those element objects when it doesn't, so it's a lot more efficient.

**Comment by contra** [comment]
@pfurini That comment is 100% incorrect - react-responsive also supports render functions as children, and predates react-media. I don't really appreciate people spreading misinformation to try to persuade others into using their packages.

**Comment by pfurini** [comment]
@contra I'm sorry if my comment hurt your feelings, and yes I was wrong, I didn't read through all both repo READMEs. What is misleading is the comment of one of the `react-media` collaborators, I don't know if that was intentionally wrong, but I truly hope not. Obviously I'm not a member of the project, I'm only a potential user.
If I may add, please don't take it personal here on GH.. I'd have appreciated if your comment simply pointed out the relevant section of the `react-responsive` README, and that'd be a helpful reference for future readers of this issue too.

P.
