### ISSUE TITLE
treeSelect父节点设置为disabled的时候能不能不影响该节点的下拉？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8591]
### What problem does this feature solve?
目前设置为disabled的时候 连同下拉都不行了，但实际是我只是想要禁用掉选中这个节点

### What does the proposed API look like?
我希望的是设置为disabled的时候只是该节点无法选中而不会影响其他功能的使用

**Comment by dechuangchang** [comment]
楼主解决了吗 我也遇到了

**Comment by aw6658913** [comment]
没解决，后面自己控制选父节点的时候提示下~

**Comment by valleykid** [comment]
你们的预期是 父节点可展开和收起，只是禁止选择 对吗？

**Comment by aw6658913** [comment]
是的

**Comment by aw6658913** [comment]
你说的是checkox复选框勾选的情况，我那是单选的，没有checkbox，没法用这个属性吧

**Comment by valleykid** [comment]
Fixed by [antd@3.3.0](https://github.com/ant-design/ant-design/releases/tag/3.3.0).

**Comment by jYh1014** [comment]
@aw6658913 你的问题解决了吗？

**Comment by ccw1989825** [comment]
现在单选依然父节点disabled，无法展开看子节点

**Comment by younth** [comment]
mark
