### ISSUE TITLE
InputNumber does not lost focus

### ISSUE THREAD

**Issue by leonardopavanello** [ant-design/ant-design#8592]
### Version
3.0.1

### Environment
this cand be reproduced at the document site https://ant.design/components/input-number-cn/

### Reproduction link
[https://drive.google.com/file/d/1E9sLsyK6ChcFO7RvASXZI3A9su_GRCXH/view?usp=sharing](https://drive.google.com/file/d/1E9sLsyK6ChcFO7RvASXZI3A9su_GRCXH/view?usp=sharing)

### Steps to reproduce
Focus on an InputNumber
Click on the down button to the lower value
Try to focus on another component or outside the InputNumber

### What is expected?
If click outside, the InputNumber must lost the focus 

### What is actually happening?
The focus comeback to the inputNumber

---
I've attached a "screenshot" video of cinnamod

**Comment by Rohanhacker** [comment]
The bug is in rc-input-number, submitted a pr there

**Comment by fritx** [comment]
It's weird that **dev** was fine but in **production** `focusOnUpDown` seems not work (behaves like =false)

i.e. **in production**, InputNumber never loses focus no matter how many times up/down were clicked.

```plain
antd: v3.3.1 both
rc-input-number: v4.0.3 both
rmc-feedback: v1.0.4 both
```

**Comment by yoyo837** [comment]
@fritx Same issue in production. dev is work fine.
