### ISSUE TITLE
标题与列 不对齐

### ISSUE THREAD

**Issue by sealzrt** [ant-design/ant-design#8593]
### Version
3.0.1

### Environment
mac, chrome 63

### Reproduction link
[https://codesandbox.io/s/jj90ym2885](https://codesandbox.io/s/jj90ym2885)

### Steps to reproduce
scroll.x  不知道应该设置为多少

### What is expected?
标题与列 对其

### What is actually happening?
标题与列 不对齐

**Comment by sealzrt** [comment]
![image](https://user-images.githubusercontent.com/6469925/33941801-ca9d195c-e04e-11e7-868d-cd24f940e1a5.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/pkjlo3wwvq
