### ISSUE TITLE
in antd 3.x differently than 2.x the expandedRowRender is called on initial component mount even if the row is not expanded.

### ISSUE THREAD

**Issue by wallaroo** [ant-design/ant-design#8599]
### Version
3.0.1

### Environment
all environments

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
create a Table using antd 3.x and define the expandedRowRender property to ()=>{console.log("expanded")}

### What is expected?
the expandedRowRender is called only when user clicks on   button (this is the behavior of antd 2.x)

### What is actually happening?
in antd 3.x differently than 2.x the expandedRowRender is called on initial component mount even if the row is not expanded.

**Comment by yesmeck** [comment]
Fixed, try reinstall node_modules.

**Comment by MrObe13** [comment]
Now expandedRowRender is called a number of times equal to the number of expanded rows. 

After being opened, expandedRowRender is called only once when I try to close and reopen the same line.

**Comment by yesmeck** [comment]
@MrObe13 Could you provide a reproduction? Use this template https:/u.ant.design/codesandbox-repro
