### ISSUE TITLE
Checkbox 多选框的描述错误

### ISSUE THREAD

**Issue by zifeixu85** [ant-design/ant-design#860]
**问题描述**

Checkbox 的「何时使用」字段，使用了「Switch」的说明

> 需要表示开关状态/两种状态之间的切换时；

**发生环境**

- antd 版本：0.11
- 在线演示地址：[错误地址](http://ant.design/components/checkbox/)

**重现步骤**

![Switch](http://qiniu.zifeixu.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%203.png)

![Checkbox](http://qiniu.zifeixu.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%204.png)

**Comment by zifeixu85** [comment]
而且，个人认为 `Switch` 应该跟 `Radio` 的关联更大，因为两者都是标记或改变某 **一个** 选项或状态。特别是在 `Radio` 只有两个选项时，更容易产生混淆使用。

是否这样更合适：

> 和 `Radio` 的区别是，切换 `Switch` 会直接触发状态改变，而 `Radio` 一般用于状态标记，需要和提交操作配合。

**Comment by afc163** [comment]
文案的描述没错的。和 Radio 不一样，只有一个 Radio 的时候没有办法进行切换。

不过上面的文案确实太像了，可以改改措辞。

**Comment by zifeixu85** [comment]
只有一个 `Radio` 的时候应该是错误的使用了 `Radio`，不过这个关系不大，不做过多讨论。

想确认一下的是，你说的文案描述没有错误是下面这一段吗（就是一样的，不是像...）：

> Checkbox 的描述「需要表示开关状态/两种状态之间的切换时；」
