### ISSUE TITLE
pagination improvements in List component

### ISSUE THREAD

**Issue by andriijas** [ant-design/ant-design#8600]
### What problem does this feature solve?
There is currently example of pagination with List component at https://ant.design/components/list/#components-list-demo-vertical  but it doenst explicit say that its only basic support (it doesnt automatically paginate when datasource changes etc) . There is already very good pagination support in Table component and I think it can be broken out and shared commonly between list and table. Even filtering can be commonly shared between List and Table.

### What does the proposed API look like?
Same as pagination in Table

**Comment by afc163** [comment]
#8256

**Comment by andriijas** [comment]
sorry i tried to check through open issues before creating but didnt find it.
