### ISSUE TITLE
Sider Menu does not respect collapsedWidth prop

### ISSUE THREAD

**Issue by delesseps** [ant-design/ant-design#8601]
### Version
3.0.1

### Environment
Mac OSX Chrome 63

### Reproduction link
[https://codepen.io/delesseps/pen/WdbKVZ](https://codepen.io/delesseps/pen/WdbKVZ)

### Steps to reproduce
Set collapsedWidth to something other than 80px e.g. 60px and try to collapse

### What is expected?
Menu should fit inside Sider

### What is actually happening?
Menu expands outside of Sider

![image](https://user-images.githubusercontent.com/5125315/33964546-dec4a68a-e0ac-11e7-937b-967b666cbc25.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/f54d73617fe831e3a5b12657194f37ab264c9c77/components/style/themes/default.less#L309
