### ISSUE TITLE
官方demo 不可选日期disabledDate  显示不对

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design#8608]
### Version
3.0.1

### Environment
window 7

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
把 showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }} 改成  showTime={{ defaultValue: moment('23:59:59', 'HH:mm:ss') }}
第一次点击 时间框不能选择当天时间，选择后一天，然后就可以选择当天了

### What is expected?
可以直接选择当天的时间

### What is actually happening?
不能直接选择当天的时间

import moment from 'moment';
import { DatePicker } from 'antd';
const { MonthPicker, RangePicker } = DatePicker;

function range(start, end) {
  const result = [];
  for (let i = start; i < end; i++) {
    result.push(i);
  }
  return result;
}

function disabledDate(current) {
  // Can not select days before today and today
  return current && current.valueOf() < Date.now();
}

function disabledDateTime() {
  return {
    disabledHours: () => range(0, 24).splice(4, 20),
    disabledMinutes: () => range(30, 60),
    disabledSeconds: () => [55, 56],
  };
}

function disabledRangeTime(_, type) {
  if (type === 'start') {
    return {
      disabledHours: () => range(0, 60).splice(4, 20),
      disabledMinutes: () => range(30, 60),
      disabledSeconds: () => [55, 56],
    };
  }
  return {
    disabledHours: () => range(0, 60).splice(20, 4),
    disabledMinutes: () => range(0, 31),
    disabledSeconds: () => [55, 56],
  };
}

ReactDOM.render(
  <div>
    <DatePicker
      format="YYYY-MM-DD HH:mm:ss"
      disabledDate={disabledDate}
      disabledTime={disabledDateTime}
      showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}  // 就是这个时间的改变
    />
    <br />
    <MonthPicker disabledDate={disabledDate} placeholder="Select month" />
    <br />
    <RangePicker
      disabledDate={disabledDate}
      disabledTime={disabledRangeTime}
      showTime={{
        hideDisabledOptions: true,
        defaultValue: [moment('00:00:00', 'HH:mm:ss'), moment('11:59:59', 'HH:mm:ss')],
      }}
      format="YYYY-MM-DD HH:mm:ss"
    />
  </div>,
  mountNode
);

**Comment by wunayou** [comment]
初始值为 null

**Comment by wunayou** [comment]
我同事不能帮我写英文 本人english水平有限

**Comment by muzea** [comment]
@wunayou 时间不要使用文本，使用moment对象可以规避这个问题

**Comment by encorehe** [comment]
@muzea   我是使用的moment对象规避不了这个问题啊

**Comment by wunayou** [comment]
@muzea  @encorehe   这个问题 return current && current.valueOf() < Date.now(); 这里造成的 因为官方判断考虑不全  你可以根据自已的设的时间 来与现在的时间 减去几分钟

**Comment by afc163** [comment]
官方这是一个简单的示例，业务代码需要根据具体需求自行改造这个判断。

**Comment by muzea** [comment]
@encorehe @wunayou  https://codesandbox.io/s/38qnwvxpz1
我这么写是完全没有问题的
