### ISSUE TITLE
Tree 升级rc-tree到0.25.5版本后选择的问题

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#861]
rc-tree升级后onCheck有变化：
之前：

    function(e:{checked:bool,node,checkedKeys,event})
之后：

    function(e:{checked:bool, node, checkedKeys, event, allCheckedNodesKeys})

之前通过checkedKeys来获得选择的值，现在不对了，allCheckedNodesKeys看起来好像是对的，请问是否需要通过allCheckedNodesKeys来获取选择的值？ @warmhug @afc163 请帮忙，谢谢！

**Comment by warmhug** [comment]
可以的。 之前你看到的是「不受控」状态下的返回值，现在「受控和不受控」状态check回调参数不同。

**Comment by qiaolb** [comment]
谢谢
