### ISSUE TITLE
table: custom dropdown position bug when scroll

### ISSUE THREAD

**Issue by gy134340** [ant-design/ant-design#8610]
### Version
3.0.1

### Environment
general

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
see gif

### What is expected?
need track the table's positon, but  can't find any API ` getPopupContainer={triggerNode => triggerNode.parentNode}` in Table

### What is actually happening?
see gif

![bug](https://user-images.githubusercontent.com/14243932/33974847-a9c20374-e0c5-11e7-800b-0547ffa6da3a.gif)

**Comment by yesmeck** [comment]
See https://ant.design/components/dropdown/#Dropdown

**Comment by gy134340** [comment]
@yesmeck sorry, I didn't use dropdown, just write some simple `<ul>` list, not the `<Dropdown />` component, also find this issue in the docs
![bug](https://user-images.githubusercontent.com/14243932/33975271-6618dee2-e0c8-11e7-9a3a-6f42e86ceb19.gif)

**Comment by yesmeck** [comment]
See https://github.com/react-component/select/issues/253

**Comment by gy134340** [comment]
@yesmeck that‘s the point, fix that, thanks
