### ISSUE TITLE
配合next.js一起使用时Layout.Sider不能触发onCollapse事件，图标也无法显示

### ISSUE THREAD

**Issue by pixcai** [ant-design/ant-design#8612]
### Version
3.0.1

### Environment
Mac 10.12.1 Chrome 64.0.3282.24

### Reproduction link
[https://github.com/pixcai/bekit](https://github.com/pixcai/bekit)

### Steps to reproduce
运行重现链接中的例子

### What is expected?
Layout.Sider点击可以折叠，图标可以显示

### What is actually happening?
Layout.Sider不响应任何事件，图标也不显示

---
和next.js、mobx使用时有问题

**Comment by yesmeck** [comment]
Duplicated of #8604
