### ISSUE TITLE
移动端UC浏览器下组件无法渲染

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#8613]
### Version
3.0.1

### Environment
移动端UC浏览器

### Reproduction link
[http://xxx](http://xxx)

### Steps to reproduce
使用移动端UC浏览器访问页面

### What is expected?
正常渲染

### What is actually happening?
无法渲染

**Comment by yesmeck** [comment]
![img_9ed89ca2d380-1](https://user-images.githubusercontent.com/465125/33982396-5602e192-e0eb-11e7-8043-00ba9e520950.jpeg)

Works on my phone.

**Comment by afc163** [comment]
自行探索 polyfill，我们不对移动端做专门支持。
