### ISSUE TITLE
Popconfirm onConfirm handler promise 

### ISSUE THREAD

**Issue by marshalys** [ant-design/ant-design#8614]
### What problem does this feature solve?
like Modal onOk handler, to support promise will be good if the action is not finish very quickly.

### What does the proposed API look like?
like Modal onOk handler, to support promise.

**Comment by benjycui** [comment]
-1 for this.

Popconfirm is for lightweight operation, should not block users' operation.

Just use Modal in these case.

**Comment by marshalys** [comment]
I'm not agree with you @benjycui 

I think the advantage of Popconfirm to compare with Modal is:
1. less distance to move your mouse to click "confirm" or "cancel" button;
2. more clear witch data you action for, because the Popconfirm is close your action button.

so in some case Popconfirm has better User Experience than Modal.

And I don't think Popconfirm is **only** for lightweight operation, and if Popconfirm support promise it's aslo can used for lightweight operation, it's not conflict.

**Comment by yesmeck** [comment]
Closing since it's inactive, you can control Popconfirm by `visible` anyway.
