### ISSUE TITLE
IE9-10 issue with all animated components

### ISSUE THREAD

**Issue by Oreanor** [ant-design/ant-design#8618]
### Version
3.0.1

### Environment
Win10 64bit, IE9-10 emulation mode in IE11

### Reproduction link
[https://codesandbox.io/s/k278o43m0v](https://codesandbox.io/s/k278o43m0v)

### Steps to reproduce
1.npm install antd-init -g
2. antd-init
3. Add recommended poylfills in index.html for IE9-10 support

 
    
    <script src="https://as.alipayobjects.com/g/component/??es6-shim/0.35.1/es6-sham.min.js,es6-shim/0.35.1/es6-shim.min.js"></script>

4. npm start

### What is expected?
Click on Datapicker opens the month panel

### What is actually happening?
got an null 'children' error in IE9-10 
https://i.imgur.com/VOihbir.png

**Comment by yesmeck** [comment]
Fixed, try reinstall node_modules.
