### ISSUE TITLE
Support SASS/SCSS

### ISSUE THREAD

**Issue by Subalee** [ant-design/ant-design#8619]
### What problem does this feature solve?
Hey,
I think that the title says it clearly.
Support for my request are the results of recent survey: https://stateofjs.com/2017/css/results

I have absolutely fell in love with ant design however I find using LESS would add unnecessary complexity to my build step and this is preventing me from using it.

### What does the proposed API look like?
complete rewrite/addition of SCSS support.

**Comment by afc163** [comment]
We love scss but it will be a huge rewrite work and break change. So we gonna pass it.

**Comment by joshua-turner** [comment]
To expand on this: it looks like the majority of the rewrite would come from having to rewrite the current inline javascript being used during the CSS build.

Sass doesn't currently support inline javascript [the way that less does](https://www.bennadel.com/blog/2638-executing-javascript-in-the-less-css-precompiler.htm), so rewriting the functions without javascript, specifically those in `bezierEasing.less` and `tinyColor.less` just isn't practical.

**Comment by Subalee** [comment]
@joshua-turner Now that is a reason i can understand.

Do you think it's still an option in the future?

**Comment by joshua-turner** [comment]
@Subalee I was actually curious about this, and I ended up being able to make it work by using [postcss-functions](https://github.com/andyjansson/postcss-functions) in my webpack configuration to overcome the lack of inline javascript available in Sass.

I put it together and threw it in a repo [here](https://github.com/joshua-turner/ant-design-sass).

I did some initial testing of a handful of components, if you notice anything do me a favor and file an issue or make a pull request solving it.

**Comment by Temoto-kun** [comment]
If you're using node-sass, you could use the experimental `functions` option to have some JavaScript expressions evaluated and brought to you in the Sass files.

**Comment by LinBoLen** [comment]
I have refactor all of it into scss.

https://github.com/gradii/triangle/tree/master/triangle-ui

**Comment by YUFENGWANG** [comment]
@LinBoLen nice job, but what about the inline javascript?

**Comment by LinboLen** [comment]
related #38406
