### ISSUE TITLE
Tag 组件与 react-router Link 兼容性：<a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by Carrotzpc** [ant-design/ant-design#862]
**问题描述**
实际使用时发现在 Link 中使用 Tag 组件会有一个警告 `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See Hello > a > ... > AntTag > a.`，个人建议将 Tag 组件的 `href` 属性剔除，让它安安静静做一个 Tag ，或者根据有无`href`属性，决定是否使用 `<a>`。

**线上重现演示**
未使用 Link ，只是将 Tag 放在了 `<a>` 中
http://jsfiddle.net/rjnebgex/

**Comment by afc163** [comment]
有理有据。剔除 href 属性吧，来个 PR 如何？

**Comment by Carrotzpc** [comment]
好，下班回去尝试来个 PR  :smiley:

**Comment by afc163** [comment]
已在 0.12.0-beta 中。
