### ISSUE TITLE
Make a official css utilities

### ISSUE THREAD

**Issue by Airkro** [ant-design/ant-design#8624]
### What problem does this feature solve?
Sometime we need to bring some css effect to our custom component(or just a div/span tag).

But use three party utilities may cause side effects. copy from repositories not a good idea neither. 

How about make a official css utilities, like bootstrap utilities, or <https://css.sitetent.com/utilities.html>. but use `color palette` and `break point` setting  same with  `Antd`.

### What does the proposed API look like?
```js
import 'antd/lib/utilities.less';
import { Card } form 'antd';

render (
  <Card>
    <span class="margin-sm color-primary">...</span>
     ...
  </Card>
);
```

**Comment by afc163** [comment]
Nope, we won't expose class utilities.

**Comment by Airkro** [comment]
@johnunclesam

No, But I do use some Common CSS helper.  something like `Atomic CSS`, like <https://www.sitepoint.com/using-helper-classes-dry-scale-css/> or `Bootstrap Utilities`. It's not good enough but useful, when I use any UI library (e.g. Antd). 

That's why I request some .class by Antd's `color palette` and `break point`.

Now I make it by my self: <https://github.com/Airkro/css-bit/blob/master/package/antd-color.scss>

**Comment by shamseerahammedm** [comment]
+1 for this

**Comment by Mdzahin** [comment]
use
https://www.npmjs.com/package/antd-css-utilities
