### ISSUE TITLE
tree-select 连续两次选择同一个，第二次会清空数据，并且不会触发onSelect

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8626]
### Version
3.0.1

### Environment
chrome

### Reproduction link
[https://codepen.io/anon/pen/RxPemY?editors=001](https://codepen.io/anon/pen/RxPemY?editors=001)

### Steps to reproduce
选择同一个节点两次

### What is expected?
每次选中onSelect都能生效，而且选中同一个应该跟select控件一样 还是原来的值

### What is actually happening?
tree-select 连续两次选择同一个，第二次会清空数据，并且不会触发onSelect

**Comment by afc163** [comment]
TreeSelect 的选择行为继承自 https://ant.design/components/tree/ ，需要有 Toggle 行为，和 Select 不完全一致。
