### ISSUE TITLE
Upload上传组件跨域失败，源于rc-request设置问题

### ISSUE THREAD

**Issue by tofishes** [ant-design/ant-design#863]
问题：我们使用上传组件配置了七牛的直传，在升级组件后，出现无法跨域上传的问题，浏览器报错如下：

```
XMLHttpRequest cannot load http://upload.qiniu.com/. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://our-domain' is therefore not allowed access.
```

根据错误提示，搜索了antd库，发现/node_modules/antd/node_modules/rc-upload/lib/request.js文件中如下代码会导致该错误：

```
if ('withCredentials' in xhr) {
    xhr.withCredentials = true;
  }
```

请处理一下这个问题吧。

**Comment by afc163** [comment]
https://github.com/react-component/upload/pull/27

表示看不明白，@shepherdwind  看看？

**Comment by shepherdwind** [comment]
好吧，这个做成配置吧。这个是传递 cookie 的配置

**Comment by shepherdwind** [comment]
这个感觉默认关闭比较好，需要的自己开启比较好

**Comment by shepherdwind** [comment]
重新安装一下看看，发了 1.7.2 版本

**Comment by tofishes** [comment]
已试用1.7.2通过，感谢这么快处理。

**Comment by flyfinec** [comment]
withCredentials的配置项能否加到文档（https://ant.design/components/upload/）里去，不然得找到这里才能解决

**Comment by afc163** [comment]
来个 PR ~ @flyfinec

**Comment by jiyinyiyong** [comment]
我还是找到嗯这里....

**Comment by afc163** [comment]
https://segmentfault.com/a/1190000011174923
