### ISSUE TITLE
当mode为vertical时加入openKeys={openKeys}会出现菜单文字隐藏不起来

### ISSUE THREAD

**Issue by chendonghai1982** [ant-design/ant-design#8632]
### Version
3.0.1

### Environment
windows, 谷歌浏览器

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
由于这个问题我要多写一层重复的代码：
mode == "inline" ?
                        <Menu
                            theme="light" mode={mode}
                            onClick={this.handleMenuClick}
                            openKeys={openKeys}
                            onOpenChange={this.onOpenChange}
                            style={MenuStyle}>
                            {this.leftMenuDataBind(leftMenuData)}</Menu> :
                        <Menu
                            theme="light" mode={mode}
                            onClick={this.handleMenuClick}
                            onOpenChange={this.onOpenChange}>
                            {this.leftMenuDataBind(leftMenuData)}</Menu>
                    }
                </div>
当mode="vertical"不能使用openKeys={openKeys}

### What is expected?
能够兼容，不要我多写一层处理

### What is actually happening?
当mode为vertical时加入openKeys={openKeys}会出现菜单文字隐藏不起来

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by chendonghai1982** [comment]
你们刚刚更新的3.0.2我发现已经修改了我的BUG，谢谢

**Comment by afc163** [comment]
虽然还是不知道你是什么问题。。

**Comment by chendonghai1982** [comment]
好像就是这个人提出的问题跟我一样：https://github.com/ant-design/ant-design/issues/8587

**Comment by afc163** [comment]
你看人家提的问题就比你提的要好懂很多。

**Comment by chendonghai1982** [comment]
嗯。我下次注意一下，我发现我提的问题代码内容竟然 跟我发表的不一样，好奇怪，少了好多代码

**Comment by afc163** [comment]
http://segmentfault.com/markdown
