### ISSUE TITLE
Change locale of RangePicker

### ISSUE THREAD

**Issue by GrishaAngelov** [ant-design/ant-design#8635]
### Version
3.0.1

### Environment
Linux Mint 17, Chrome 63.0.3239.108

### Reproduction link
[https://codepen.io/anon/pen/aEOrLZ?editors=1010](https://codepen.io/anon/pen/aEOrLZ?editors=1010)

### Steps to reproduce
Provide ```locale``` object as prop to <DatePicker.RangePicker>

### What is expected?
Locale to be changed and strings in header and footer of RangePicker to be translated to the language in locale object

### What is actually happening?
The language is not changed and is still the default one (en)

---
After some experimenting I found the following thing:
If we open ```antd/lib/date-picker/wrapPicker.js``` and change

```js
{
      key: 'render',
      value: function render() {
        return React.createElement(
          _LocaleReceiver2['default'],
          { componentName: 'DatePicker', defaultLocale: this.getDefaultLocale},
          this.renderPicker
        );
      }
    }
```
to

```js
 {
            key: 'render',
            value: function render() {
              const getLocale = () => this.props.locale

              return React.createElement(
                    _LocaleReceiver2['default'],
                    { componentName: 'DatePicker', defaultLocale: this.props.locale.lang ? getLocale : this.getDefaultLocale},
                    this.renderPicker
                );
            }
        }
```

then the locale is changed as it should (and if not provided then we have the default one).

So it looks that always is applied the default locale without check for the user defined.
In the previous versions e.g. 2.13.x providing with locale object was enough.
This is my observation, am I missing something ?

**Comment by Atala** [comment]
Hi,

I am under the impression that the fix is not working with antd `3.0.2` (which include 
7919d76 ) and the codepen linked above (https://codepen.io/anon/pen/MryzKd?editors=1010 with antd 3.0.2).

Maybe something specific to the `RangePicker` component.

Thanks for your dedication & great project,

**Comment by GrishaAngelov** [comment]
I have updated antd to ```3.0.2``` and everything seems to work correct - the strings that have not been translated before now are ok

**Comment by Atala** [comment]
Quite surprised, in my project the translation of the calendar days doesn't seem to work (I am working on the french translation). 

It seems the same to me in your Codepen, the calendar days are still not translated (in russian) in `3.0.2` - maybe I am missing something?

<img width="552" alt="capture d ecran 2017-12-20 a 10 01 06" src="https://user-images.githubusercontent.com/4426585/34199061-bd5a5caa-e56c-11e7-82f0-b7bdc568e724.png">
<img width="639" alt="capture d ecran 2017-12-20 a 10 00 50" src="https://user-images.githubusercontent.com/4426585/34199062-bd7bc444-e56c-11e7-99a2-884fa0b3dc34.png">

**Comment by GrishaAngelov** [comment]
Probably you could not edit the provided codepen, because you are not the author or something...
I made the change in the env
![image](https://user-images.githubusercontent.com/1625243/34200055-6059a766-e578-11e7-8206-a4f03a6d614b.png)

and change some strings, not all to french locale
![image](https://user-images.githubusercontent.com/1625243/34200111-8f663344-e578-11e7-8156-13fd7a50d452.png)

seems to work

**Comment by yutingzhao1991** [comment]
Part of locale of DatePicker, MonthPicker, RangePicker, WeekPicker is read from value. So, please set the locale of moment correctly.

ref: https://codepen.io/yutingzhao1991/pen/aEZbaB

![image](https://user-images.githubusercontent.com/1061968/34200290-7411f780-e5ab-11e7-892d-1036cf65458b.png)

**Comment by Atala** [comment]
Yes indeed I noticed it in the docs, but got confused with this bug + correctly loading the moment locales.

No problem with Antd then.

Thanks for your answer!

**Comment by didmehh** [comment]
https://codepen.io/benjycui/pen/KgPZrE?editors=001
if change the `locale` to `zh_CN`, it don't work when the second selected.that will change to `en`
