### ISSUE TITLE
Numbers entered into an Input element changes the letter spacing of all characters

### ISSUE THREAD

**Issue by CGreenburg** [ant-design/ant-design#8636]
### Version
3.0.1

### Environment
MacOS 10.12.6, Google Chrome 63.0.3239.108

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
Go to https://ant.design/components/input/ in Google Chrome. Type some letters into any input field, then type a number. The spacing should change.

### What is expected?
The letter spacing should remain the same.

### What is actually happening?
The letter spacing is changing.

---
This does not happen in Firefox or Safari on my MacBook.

**Comment by CGreenburg** [comment]
Here's a gif of what's happening. Again, this doesn't happen in Firefox or Safari, only Chrome.
![input_spacing_bug](https://user-images.githubusercontent.com/13036301/34057256-dade0486-e19b-11e7-828d-5f809dd97629.gif)

**Comment by afc163** [comment]
I believe it is chrome's bug to treat unicode chars in same word as same font face.

https://github.com/ant-design/ant-design/blob/754d330baead900a367688ce16bef82f4a472a0e/components/style/core/base.less#L10-L15
https://css-tricks.com/almanac/properties/u/unicode-range/

**Comment by afc163** [comment]
Change `Helvetica Neue` to `Tahoma` for number to resolve this problem. 😅
