### ISSUE TITLE
table增加一列修改列，然后点击后执行一些判断，官方给的就是点击跳转，应该怎么实现哪

### ISSUE THREAD

**Issue by allces** [ant-design/ant-design#864]
table增加一列修改列，然后点击后执行一些判断，官方给的就是a标签然后点击跳转，应该怎么实现哪

**Comment by afc163** [comment]
http://react-component.github.io/table/examples/expandedRowRender.html

#272

**Comment by allces** [comment]
谢谢

**Comment by allces** [comment]
谢谢
