### ISSUE TITLE
火狐下按钮链接不跳转

### ISSUE THREAD

**Issue by yujingwyh** [ant-design/ant-design#8640]
### Version
2.13.11

### Environment
火狐浏览器

### Reproduction link
[http://www.sosho.cn](http://www.sosho.cn)

### Steps to reproduce
以下代码点击超链接在火狐浏览器没有反应
<Button.Group>
        <Button>
          <a href={signQRcode} target='_blank'>签到二维码</a>
        </Button>
</Button.Group>

### What is expected?
正常新窗口打开页面

### What is actually happening?
没有打开页面，点击事件估计被拦截

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1108
