### ISSUE TITLE
Cannot find module 'antd'.

### ISSUE THREAD

**Issue by etroynov** [ant-design/ant-design#8642]
### Version
3.0.1

### Environment
ubuntu 16.04

### Reproduction link
[https://github.com/etroynov/eco-navation](https://github.com/etroynov/eco-navation)

### Steps to reproduce
execute command: `npm run dev`

### What is expected?
compile without error

### What is actually happening?
Rise error error TS2307: Cannot find module 'antd'.

**Comment by yesmeck** [comment]
Since, you set `module` to `ESNext`, You'd have to set `moduleResolution` to `node` explicitly.

**Comment by etroynov** [comment]
Thanks a lot.
