### ISSUE TITLE
Can a calendar component add a time interval control

### ISSUE THREAD

**Issue by zhayes** [ant-design/ant-design#8645]
### What problem does this feature solve?
Calendars need time range control

### What does the proposed API look like?
exp:  
```<Calendar  beginDt={ } endDt={ }  />```

beginDt and endDt is  a Moment obj or string;

**Comment by yutingzhao1991** [comment]
You can use prop `disabledDate`.

![image](https://user-images.githubusercontent.com/1061968/34086637-6b3fa0dc-e3d8-11e7-8185-e81091c35ff1.png)

**Comment by zhayes** [comment]
@yutingzhao1991  I need to control this

![image](https://user-images.githubusercontent.com/17758062/34086923-cd6c9ea2-e3da-11e7-8458-75290ce54eb9.png)

**Comment by yutingzhao1991** [comment]
I think `disabledDate` is enough for your need. The controller you marked is not necessary to disable. Give me more reason for you want.

**Comment by zhayes** [comment]
@yutingzhao1991  It's not just the choice of time limit, but also the display of time

**Comment by yutingzhao1991** [comment]
@yesmeck What's your opinion?

**Comment by zhayes** [comment]
@yutingzhao1991  The time interval of the calendar can be configured on its own

**Comment by yesmeck** [comment]
I think we can add a range prop to calendar. `disabledDate` represents which dates can not interactive, but a range prop represents which dates to show.

Ref https://fullcalendar.io/docs/current_date/validRange/

**Comment by Rohanhacker** [comment]
@yesmeck Will you accept a PR for this ?

**Comment by yesmeck** [comment]
@Rohanhacker Of course.

**Comment by 422809585mls** [comment]
@yesmeck Do you accept the PR for this demand?

**Comment by yesmeck** [comment]
@422809585mls yes

**Comment by 422809585mls** [comment]
where? @yesmeck

**Comment by yesmeck** [comment]
No one sended a PR now, do you want to try?

**Comment by 422809585mls** [comment]
yes @yesmeck

**Comment by 422809585mls** [comment]
When will this need be achieved? @yesmeck

**Comment by yesmeck** [comment]
No deadline, take your time.

**Comment by 422809585mls** [comment]
I do not understand what you mean,what is PR? @yesmeck

**Comment by DejectedBird** [comment]
Can this problem be resolved?@yesmeck
