### ISSUE TITLE
dropdown.d.ts中DropDownProps的trigger少了contextMenu

### ISSUE THREAD

**Issue by cjahv** [ant-design/ant-design#8646]
### Version
3.0.2

### Environment
electron

### Reproduction link
[https://codesandbox.io/s/547n50y1jl](https://codesandbox.io/s/547n50y1jl)

### Steps to reproduce
打开重现链接的index.tsx文件定位第33行

### What is expected?
trigger支持 "click" | "hover" | "contentMenu" 这三个值

### What is actually happening?
只支持 "click" | "hover" 两个值

**Comment by cjahv** [comment]
### Version
3.0.2

### Environment
electron

### Reproduction link
[https://codesandbox.io/s/547n50y1jl](https://codesandbox.io/s/547n50y1jl)

### Steps to reproduce
open reproduction link targeting to index.tsx 33 line

### What is expected?
trigger support "click" | "hover" | "contentMenu" 

### What is actually happening?
but support "click" | "hover" only

**Comment by afc163** [comment]
@cjahv Could you make a PR for this?
