### ISSUE TITLE
那个异步树貌似不行啊！

### ISSUE THREAD

**Issue by silverPanda** [ant-design/ant-design#865]
我check了一下源码，，，，根本就没有 onDataLoaded 这个方法，请问例子里面是肿么实现的？

**Comment by afc163** [comment]
底层依赖了 http://github.com/react-component/tree

**Comment by silverPanda** [comment]
我就是看的这个rc_tree，里面也没有这个方法啊。。。。我懵逼了

**Comment by silverPanda** [comment]
还是这个rc_tree的新版本不支持这个。。。

**Comment by afc163** [comment]
https://github.com/react-component/tree/blob/master/HISTORY.md#023x--2015-12-31

**Comment by silverPanda** [comment]
Tree 组件不能像例子里面写onDataLoaded，而是使用 loadData 。不知道是不是 rc_tree作者换方法名字了。。

**Comment by afc163** [comment]
？？？

**Comment by silverPanda** [comment]
![image](https://cloud.githubusercontent.com/assets/2177207/12298598/e8eb841c-ba4d-11e5-890d-394bca9f938b.png)
这个属性

**Comment by afc163** [comment]
你不看上面的链接的？

**Comment by silverPanda** [comment]
换成 loadData  官网上的那个例子就能跑了。。。

**Comment by silverPanda** [comment]
好吧我瞎了。thx
