### ISSUE TITLE
Dropdown在两个包含子菜单的条目上移动会出现闪烁

### ISSUE THREAD

**Issue by joenil** [ant-design/ant-design#8653]
### Version
3.0.2

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

### Reproduction link
[https://codepen.io/anon/pen/mpVLPZ?&editors=001](https://codepen.io/anon/pen/mpVLPZ?&editors=001)

### Steps to reproduce
Dropdown在两个包含子菜单的条目上移动会出现闪烁

### What is expected?
流畅的动画

### What is actually happening?
动画出现了闪烁

**Comment by afc163** [comment]
Duplicate of #8557
