### ISSUE TITLE
umd file broken: antd-with-locales.js

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8654]
http://codepen.io/benjycui/pen/KgPZrE?editors=001

`SyntaxError: missing ) in parenthetical`

**Comment by yesmeck** [comment]
<img width="776" alt="screen shot 2017-12-19 at 10 26 19" src="https://user-images.githubusercontent.com/465125/34137649-11eea79c-e4a7-11e7-9419-70d4af275014.png">

Works on my mac.

**Comment by afc163** [comment]
The file is been cut off in my machine: 

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/507615/34137827-b6d8576c-e4a7-11e7-8d4f-a13e033ab2ed.png">

**Comment by yesmeck** [comment]
Change your proxy. 😂
