### ISSUE TITLE
fixed后，table的header 样式出问题

### ISSUE THREAD

**Issue by liyingpu0630** [ant-design/ant-design#8657]
### What problem does this feature solve?
table展示多数据的时候，固定某列。但是刷新的时候，header的高度很大，从别的页面进入，不会有这个问题

### What does the proposed API look like?
简介但细致

**Comment by yesmeck** [comment]
终于创建成功了，但是你应该用“错误报告”的表单，并且需要使用 https://u.ant.design/codesandbox-repro 提供一个重现。
