### ISSUE TITLE
dropdown should have active class name

### ISSUE THREAD

**Issue by halluct** [ant-design/ant-design#8658]
### What problem does this feature solve?
Demos on your official website of Dropdown component, you always use `Button` or `link` as trigger element. But i usually want to trigger dropdown menu on `div` or `span` those element do not have focus status default. So i can not add active status when dropdown menu is opening. May you guys add active class like 'ant-dropdown-open' on the trigger element or its parent node to solve my problems.

### What does the proposed API look like?
```
<div class="ant-dropdown-open">
  <span class="ant-dropdown-trigger"></span>
</div>
```
or
```
<span class="ant-dropdown-trigger ant-dropdown-open"></span>
```

**Comment by yesmeck** [comment]
I don't think it's a good idea to add styles to the trigger element, it may cause style conflicting.

**Comment by halluct** [comment]
No style. I just need the class name.

**Comment by halluct** [comment]
You should do this just as you did in component `Popover`.

**Comment by yesmeck** [comment]
You can achieve it by CSS.

**Comment by ChiQianBingYue** [comment]
@yesmeck hi, I am not sure how to do so?
