### ISSUE TITLE
customize spin indicator in all antd components

### ISSUE THREAD

**Issue by halluct** [ant-design/ant-design#8659]
### What problem does this feature solve?
I want to customize indicator of Spin component in my project. But i found there is no api provided to custom the indicator in component List. I looked into your source code of List.
```jsx
const content = (
      <div>
        <Spin spinning={loading}>{childrenContent}</Spin>
        {loadMore}
        {(!loadMore && pagination) ? paginationContent : null}
      </div>
    );
```
So there is no way to customize my own spin indicator at all. It's quite no convenience.
Please consider to add an api to do this customization in List or other components contain loading status.

### What does the proposed API look like?
```jsx
<List loading={loading} loadingIndicator={(<Element />)} />
```

or you may consider providing ways to customize spin indicator globally.
```jsx
Spin.indicator = <Element />;
```

**Comment by yesmeck** [comment]
You can wrap your own `Spin`.

**Comment by halluct** [comment]
@yesmeck in `List` component i can not use my own `Spin`.

**Comment by yesmeck** [comment]
Hmm, `List[loading]` should support object like `Table[loading]` [does](https://github.com/ant-design/ant-design/blob/9a022b8aaca954bfca82234cfec812e801ba0c4e/components/table/Table.tsx#L987).
