### ISSUE TITLE
Upload文件上传－能否做到表单Form提交的时候再上传

### ISSUE THREAD

**Issue by diaoaa** [ant-design/ant-design#866]
Upload组件作为FormItem，目标是当Form提交的时候，再连同其他FormItem一起提交。<br/>
现状是每次选择完文件就上传，如果后续的没有提交，那么这份存储就浪费了。也就是能否做到保留上传的ui效果，但是取消发送上传action请求？

**Comment by benjycui** [comment]
印象中文件一开始只是上传到 `/tmp`，只要不转存到别的地方，就不会永久保存。

**Comment by JonneyYan** [comment]
我是这样做的：每次Upload组建Change时，把文件存到state中，form提交时从state中取

**Comment by afc163** [comment]
duplicate #830
