### ISSUE TITLE
table with fixed column display not as excepted when set size small

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#8660]
### Version
3.0.2

### Environment
chrome 63.0.3239.84 ，win10

### Reproduction link
[https://codepen.io/anon/pen/qpZBKP?&editors=001](https://codepen.io/anon/pen/qpZBKP?&editors=001)

### Steps to reproduce
look the reproduction link

### What is expected?
the height of Cell should keep consistent 

### What is actually happening?
the height of Cell is not consistent

**Comment by yesmeck** [comment]
@afc163  https://github.com/ant-design/ant-design/commit/0eac8aa1c6
