### ISSUE TITLE
DatePicker 英语里夹杂着韩语

### ISSUE THREAD

**Issue by chowsource** [ant-design/ant-design#8662]
### Version
3.0.2

### Environment
react16 mac chrome63

### Reproduction link
[http://nosite.no](http://nosite.no)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/5119971/34149644-b73a8d0e-e4e0-11e7-9d9e-23d091c712a4.png)

### What is expected?
应该是全部英文的

### What is actually happening?
结果却是英文里夹杂着韩语,看截图

**Comment by chowsource** [comment]
我这边很难提供示例,简单的demo好像不能重现这个bug,
但是我项目也不知道什么时候突然出现这个bug,开始的时候是正常的,
现在的情况是如果这个DatePicker选择了日期,那么点开就全是英文是正常的,看下面截图图
![image](https://user-images.githubusercontent.com/5119971/34240096-b15ddfe6-e646-11e7-86f0-643c24ef9727.png)
但如果把上面的值去掉,变成如下图
![image](https://user-images.githubusercontent.com/5119971/34240134-f16b87f0-e646-11e7-80f2-7ed309b92fc2.png)
这个时候再点击拉开面板就显示混着的语言了看下面图
![image](https://user-images.githubusercontent.com/5119971/34240165-24ceb46e-e647-11e7-97c6-8a6f878abbe1.png)

如果可以,我加你QQ,你可以远程看我的代码环境

**Comment by cjahv** [comment]
@chowsource try setting language using moment api and DatePicker locale field.

**Comment by yutingzhao1991** [comment]
应该是你的 moment 的 locale 设置有问题。参考 #8635

**Comment by chowsource** [comment]
@yutingzhao1991 没有设置moment

**Comment by yutingzhao1991** [comment]
@chowsource 好好排查下，看看你的项目里面有没有其它地方不小心修改了。如果不能提供复现的链接，我们也很难帮到你。

**Comment by chowsource** [comment]
@yutingzhao1991 
看下面代码:
```javascript
import React from 'react';
import { render } from 'react-dom';

import { DatePicker, version } from 'antd';

//打开哪个就显示就日期里的星期几就显示哪个语言的星期几
// import enUS from 'antd/lib/locale-provider/en_US';
// import koKR from 'antd/lib/locale-provider/ko_KR';//打开注释,如果DatePicker没有设值则显示韩语,如果设值了则不影响
// import zhCN from 'antd/lib/locale-provider/zh_CN';//打开注释,如果DatePicker没有设值则显示中文,如果设值了则不影响
// import jaJP from 'antd/lib/locale-provider/ja_JP';//打开注释,如果DatePicker没有设值则显示日语,如果设值了则不影响

import thTH from 'antd/lib/locale-provider/th_TH';//打开注释,如果DatePicker没有设值则显示该语言,如果设值了则不影响

//上面可以依次类推,import哪个语言包,DatePicker 就显示哪个语言


  render(
    <div>
        <p style={{ marginBottom: 24 }}>
            Current antd version: {version} <br/>

            //打开哪个就显示就日期里的星期几就显示哪个语言的星期几<br/>
            // import enUS from 'antd/lib/locale-provider/en_US';<br/>
            // import koKR from 'antd/lib/locale-provider/ko_KR';//打开注释,如果DatePicker没有设值则显示韩语,如果设值了则不影响<br/>
            // import zhCN from 'antd/lib/locale-provider/zh_CN';//打开注释,如果DatePicker没有设值则显示中文,如果设值了则不影响<br/>
            // import jaJP from 'antd/lib/locale-provider/ja_JP';//打开注释,如果DatePicker没有设值则显示日语,如果设值了则不影响<br/>
            <br/>
            import thTH from 'antd/lib/locale-provider/th_TH';//打开注释,如果DatePicker没有设值则显示该语言,如果设值了则不影响<br/>
            <br/>
            //上面可以依次类推,import哪个语言包,DatePicker 就显示哪个语言<br/>
        </p>
        <DatePicker/>
    </div>,
    document.getElementById('react-root')
  );
```
看下面截图:
![image](https://user-images.githubusercontent.com/5119971/34246647-737b75c0-e66a-11e7-9696-3257a0d5e760.png)
![image](https://user-images.githubusercontent.com/5119971/34246829-23ff7540-e66b-11e7-8b73-fbe4788c19bf.png)

**Comment by yesmeck** [comment]
> import哪个语言包,DatePicker 就显示哪个语言

因为语言包里会自动设置 moment locale，这个不是 bug。

**Comment by chowsource** [comment]
@yesmeck 那就是我一定要显性设置moment locale才能避免这个错误了是吗

**Comment by yesmeck** [comment]
我不知道你的需求是什么。

**Comment by chowsource** [comment]
@yesmeck 需求就是国际化
![image](https://user-images.githubusercontent.com/5119971/34433315-679181f0-ecb9-11e7-9f09-a765a8d8c54a.png)
![image](https://user-images.githubusercontent.com/5119971/34433319-7657cd5c-ecb9-11e7-891d-2db69a0a7bab.png)
和LocaleProvider冲突了感觉

**Comment by yesmeck** [comment]
@benjycui Can we lazy set moment locale in LocaleProvider?

```javascript
// zh_CN.tsx

export default {
  setMomentLocale: () => { moment.locale('zh-cn'); }
}
```

Call `setMomentLocale` in `LocaleProvider` util it's used.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/62mzz0wpz3

**Comment by yesmeck** [comment]
> 我加入了moment.local('en')不起作用

@chowsource  `moment.local('en-gb');`

**Comment by chowsource** [comment]
你能在我的代码仓库里的项目跑一下吗,因为我自己用create-react-app创建的react Demo 没有出现类似bug,在线上代码也不能重现我的bug

**Comment by yesmeck** [comment]
@chowsource 我明白你的问题了，我们讨论下怎么修。

**Comment by chowsource** [comment]
@yesmeck OK

**Comment by yesmeck** [comment]
@chowsource https://codesandbox.io/s/62mzz0wpz3 在这里重现下。

**Comment by geraldchen890806** [comment]
![image](https://user-images.githubusercontent.com/7379903/34810000-ad5c9f66-f6d3-11e7-8027-0d5571cc7a5c.png)
en mix zh....

**Comment by chowsource** [comment]
@yesmeck 
升级到3.1.3基本修复bug了,但是我这边如果切换一下显示别的语言,在切换会英语的时候,如果是隐性用null代替默认英语,如下面截图
![image](https://user-images.githubusercontent.com/5119971/34929866-459e2b3e-fa01-11e7-9726-6cf931e7ae9d.png)
还是会出现这个bug,显性加载英语,就完全没有bug了,但是增加了打包体积2k多.
![image](https://user-images.githubusercontent.com/5119971/34929906-7e24b5fe-fa01-11e7-85e0-044461327b9a.png)
有没有更好办法,英语的话因为默认是英语了,就不要显性import了,这样可以剩下这跟2k多体积

**Comment by yesmeck** [comment]
@chowsource 可能是你从 lib 目录下 import 的 enUS，但是又从 es 目录下 import 的组件。

**Comment by chowsource** [comment]
@yesmeck 是的,我应该怎么import呢
![image](https://user-images.githubusercontent.com/5119971/34930146-0ec7436e-fa03-11e7-8d4d-1fc4fef8b9d5.png)
![image](https://user-images.githubusercontent.com/5119971/34930167-2ed8dd70-fa03-11e7-9ec6-0078fd1a9c83.png)

**Comment by yesmeck** [comment]
这样 `import enUS from 'antd/es/locale-provider/en_US'`.

不过要显性加载的问题我再看下。

**Comment by yesmeck** [comment]
@chowsource 不需要显示加载的，我把 6f9c8da502f3173d44a2abe8327e71c25165f301 revert 掉。

**Comment by chowsource** [comment]
@yesmeck 我试了要显性的,你在我的bug-demo上试一下就知道了,初次进入是英语,用null是没问题,但假如这时你点击切换语言按钮,比如切换到日语,或则中文,点击那个datepick组件也正确显示对应的语言,但这时再切换会英语,就又混杂着上次的语言了

**Comment by chowsource** [comment]
@yesmeck 谢谢,我用显性已经能解决了bug,也解决了体积问题了

**Comment by yesmeck** [comment]
@chowsource 嗯，因为 demo 里手动做了一次 `moment.locale('en')` 所以不需要显示加载 `en_US` 了。

**Comment by chowsource** [comment]
@yesmeck 
![image](https://user-images.githubusercontent.com/5119971/34931129-0038e848-fa08-11e7-846b-b6555a2bd02e.png)
建议文档说明改一下,要不然大家都从lib下import语言包

**Comment by geraldchen890806** [comment]
just fixed . 
because package mutl moment
webpack add config
```
alias: {
  moment: path.resolve(path.join(__dirname, 'node_modules', 'moment'))
},
```

**Comment by yesmeck** [comment]
@chowsource 能在你的 bug-demo 里再演示下切换的问题吗？我试了下没重现出来。

**Comment by chowsource** [comment]
@yesmeck 我项目里是这样的,应该存在一样bug的,我去写一下演示代码

**Comment by chowsource** [comment]
@yesmeck 我提交了新的bug demo,还是同一git地址:
https://github.com/chowsource/antd-datepicker-bug-demo.git

**Comment by yesmeck** [comment]
@chowsource 感谢，我看看。

**Comment by yesmeck** [comment]
@chowsource 这个 commit https://github.com/ant-design/ant-design/commit/a7b939db437aecdea026e197145320cd5081b671 应该能修正你的问题了。

**Comment by chowsource** [comment]
@下个版本就OK了吧,我现在都用显性也没什么问题,提出来是怕其他人遇到相似的问题

**Comment by yesmeck** [comment]
@chowsource 👍 对的。

**Comment by chowsource** [comment]
@yesmeck 继续提bug
![image](https://user-images.githubusercontent.com/5119971/34935966-a0169c54-fa1a-11e7-8d97-a0201b1ab13d.png)
RangePicker 还是混杂
我已经用显性代码书写了,我bug demo 提交了,你拉下来看一下 RangePicker

**Comment by yesmeck** [comment]
@chowsource 这个其实是已知问题。做  locale 切换的时候需要把所有 moment 实例都做一次切换，但是底层的 react-components 没做这个逻辑。还是建议切换 locale 的时候刷新页面吧，毕竟不是常用的操作。或者有兴趣来帮我们完善下吗？

**Comment by geraldchen890806** [comment]
@chowsource 应该是你项目自己也安装了moment
webpack配置里指定下moment就行
```
alias: {
  moment: path.resolve(path.join(__dirname, 'node_modules', 'moment'))
},
```

**Comment by chowsource** [comment]
@geraldchen89080 是的用了moment ,我现在用你的方法试试

**Comment by chowsource** [comment]
@geraldchen890806 我试了,你这个方法在我这个项目没有用,在demo里也没有用
你可以拉我这个demo,试试你的方法看看
https://github.com/chowsource/antd-datepicker-bug-demo.git

**Comment by chowsource** [comment]
@yesmeck 目前就RangePicker 存在语言显示问题,其它组件,如DatePicker,Table,Pagenation都是OK的

**Comment by yesmeck** [comment]
@chowsource 麻烦建个独立的 issue 吧，我看看好不好修。

**Comment by weiliang903** [comment]
> @chowsource thanks,its work for me
