### ISSUE TITLE
ie browser page don't respond

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#8663]
### Version
2.13.3

### Environment
ie 9 10 11

### Reproduction link
[https://ant.design/(Private chat)](https://ant.design/(Private chat))

### Steps to reproduce
点击登陆

### What is expected?
页面可以显示出来

### What is actually happening?
页面无反应

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/34151028-0dcc11ca-e4e5-11e7-8620-21877ad702dc.png)
cause？

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/34151071-2f9258e6-e4e5-11e7-959f-cfc627938551.png)

**Comment by afc163** [comment]
I don't think it is antd's problem.

**Comment by SynChron1zed** [comment]
@afc163  if use  babel-polyfill  and babel-plugin-transform-runtime  roadhogrc setting ist right?
