### ISSUE TITLE
upgrade to antd 3.0.2, can't resolve 'rc-animate'

### ISSUE THREAD

**Issue by vmwell** [ant-design/ant-design#8664]
use webpack 3.10.0 build dll, build failed, error information:

ERROR in ./node_modules/antd/es/alert/index.js
Module not found: Error: Can't resolve 'rc-animate' in 'F:\react\react-learn\react-antd\node_modules\antd\es\alert'
 @ ./node_modules/antd/es/alert/index.js 8:0-33
 @ ./node_modules/antd/es/index.js
 @ dll vendor

ERROR in ./node_modules/antd/es/back-top/index.js
Module not found: Error: Can't resolve 'rc-animate' in 'F:\react\react-learn\react-antd\node_modules\antd\es\back-top'
 @ ./node_modules/antd/es/back-top/index.js 7:0-33
 @ ./node_modules/antd/es/index.js
 @ dll vendor

ERROR in ./node_modules/antd/es/badge/index.js
Module not found: Error: Can't resolve 'rc-animate' in 'F:\react\react-learn\react-antd\node_modules\antd\es\badge'
 @ ./node_modules/antd/es/badge/index.js 17:0-33
 @ ./node_modules/antd/es/index.js
 @ dll vendor

ERROR in ./node_modules/antd/es/form/FormItem.js
Module not found: Error: Can't resolve 'rc-animate' in 'F:\react\react-learn\react-antd\node_modules\antd\es\form'
 @ ./node_modules/antd/es/form/FormItem.js 11:0-33
 @ ./node_modules/antd/es/form/Form.js
 @ ./node_modules/antd/es/form/index.js
 @ ./node_modules/antd/es/index.js
 @ dll vendor

**Comment by afc163** [comment]
It is just fixed, try reinstall node_modules
