### ISSUE TITLE
create-react-app + typescript + antd 3.0.2版本报错，3.0.0版本正常

### ISSUE THREAD

**Issue by wanghewanghe** [ant-design/ant-design#8665]
按照官网写法：https://ant.design/components/layout-cn/#components-layout-demo-top-side

本地编译后会报下面这个错：

./node_modules/rc-menu/es/SubPopupMenu.js
Module not found: Can't resolve 'rc-animate' in '/xxxxxx/node_modules/rc-menu/es'                                                                                           

版本降到3.0.0后正常渲染

**Comment by yesmeck** [comment]
重新安装下依赖。

**Comment by wanghewanghe** [comment]
感谢回复。升级后也正常渲染
