### ISSUE TITLE
ie SubMenu click error

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#8667]
### Version
2.13.3

### Environment
ie 10

### Reproduction link
[http://120.76.194.221/carbon-test31/#/login?_k=37wcis](http://120.76.194.221/carbon-test31/#/login?_k=37wcis)

### Steps to reproduce
点击导航栏切换 报错

### What is expected?
可以切换

### What is actually happening?
无法切换

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/34161662-4e7124be-e50c-11e7-9ca5-c73640c1e77a.png)

**Comment by SynChron1zed** [comment]
@afc163  能帮忙看下 ？ 很急

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by SynChron1zed** [comment]
@yesmeck  就是按照文档来的 
![image](https://user-images.githubusercontent.com/18717051/34190631-d412136a-e57c-11e7-8c7d-56d1f6890de0.png)
是这样配置的么？ 我这样弄的话 会报 promise undefined 于是我在网上看到了加了这个 
![image](https://user-images.githubusercontent.com/18717051/34190696-3326080c-e57d-11e7-8c97-98e245a809ae.png)
这样的话 promise 就没有问题了 页面可以显示 但是点击菜单栏切换 就会报 find 也就是上面的那个错误

**Comment by yesmeck** [comment]
可以参考 pro https://github.com/ant-design/ant-design-pro/blob/master/src/index.js#L1

**Comment by SynChron1zed** [comment]
@yesmeck  在index.js 里面 添加 import 'babel-polyfill'; 这种方式的话会报这个错：

SCRIPT5022: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by yesmeck** [comment]
非 antd 的问题，自己调试看看吧。

**Comment by yesmeck** [comment]
非 antd 的问题，自己调试看看吧。

**Comment by SynChron1zed** [comment]
@yesmeck  ok 我在看看吧  thanks！

**Comment by SynChron1zed** [comment]
@yesmeck  
![image](https://user-images.githubusercontent.com/18717051/34195316-d40b91c8-e597-11e7-918e-94d8b8a3a9e6.png)
ie10下 find方法我的项目确实报错  删了这段就好了
