### ISSUE TITLE
autoFocus doesn't work inside a modal

### ISSUE THREAD

**Issue by ealvarezk** [ant-design/ant-design#8668]
### Version
3.0.2

### Environment
Chrome

### Reproduction link
[https://codesandbox.io/s/20nloq2oop](https://codesandbox.io/s/20nloq2oop)

### Steps to reproduce
Add an input with autoFocus prop in a modal. In the example the modal is opened directly and you can check that the input doesn't have the focus. You can have it doing two tabs.

### What is expected?
The input has the focus when the modal is opened.

### What is actually happening?
A div that contains the modal has the focus

**Comment by yesmeck** [comment]
HTML `autoFocus` means focus input when the page loads. You can calling focus on `componentDidMount`:

```javascript
class InputExample extends React.Component {
  componentDidMount() {
    setTimeout(this.input.focus());
  }
  render() {
    return <Input ref={node => this.input = node} />;
  }
}
```

Note, `setTimeout` is required, because we want modal been focused after open, so we call `this.wrap.focus()` [here](https://github.com/react-component/dialog/blob/6546b60e77d2eae0e61ef51d19ccfb9b5db5221d/src/Dialog.tsx#L86). And `Dialog`'s `componentDidMount` executes after `InputExample`'s `componentDidMount`.

**Comment by ealvarezk** [comment]
Perhaps we can send an autoFocus prop to the modal so that this.wrap.focus() is optional.

**Comment by wenzhizhou** [comment]
it still does not work, Cannot read property 'focus' of undefined

**Comment by grahamtallen** [comment]
Same issue

**Comment by sam-jg** [comment]
+1

**Comment by wenzhizhou** [comment]
ok

**Comment by wangekko** [comment]
+1

**Comment by ferociousfox** [comment]
same  issue

**Comment by gcfabri** [comment]
Facing the same problem, too.

**Comment by afc163** [comment]
https://codesandbox.io/s/yq5kn348l1

**Comment by afc163** [comment]
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/507615/40872791-f5400980-6686-11e8-8515-71e9aa59d53c.png">

The `autoFocus` prop is not rendered to input in Modal.

**Comment by afc163** [comment]
If you guys meet problem like `Cannot read property 'focus' of undefined`, please provide a reproducible demo by http://u.ant.design/codesandbox-repro so that we can try to resolve it.

**Comment by ferociousfox** [comment]
Thankyou!!

**Comment by zhangchengzheng91** [comment]
3.9.2 的解决方式
class App extends React.Component {
  handleClick = () => {
    const { input } = this.inputRef; // 如果是textArea的话，const { textAreaRef } = this.inputRef;
    input.focus();
    input.setSelectionRange(0, input.value.length);
    // input.select(); // 可全部选中
  };
  
  render() {
    return (
      <div>
        <Input ref={(input) => { this.inputRef = input; }} defaultValue="foo" />
        <button onClick={this.handleClick}>Focus</button>
      </div>
    );
  }
}

**Comment by ddcatgg** [comment]
> 3.9.2 的解决方式
> `class App extends React.Component {
> handleClick = () => {
> const { input } = this.inputRef; // 如果是textArea的话，const { textAreaRef } = this.inputRef;
> input.focus();
> input.setSelectionRange(0, input.value.length);
> // input.select(); // 可全部选中
> };
> 
> render() {
> return (
> 
> <Input ref={(input) => { this.inputRef = input; }} defaultValue="foo" />
> Focus
> 
> );
> }
> }`

我今天也遇到这个需求，不过我的 Input 在一个 Modal 里，而想在外层组件里直接对这个 Input 设置焦点，用你的方法好像不行。

**Comment by italoborges** [comment]
In my case, I'm using a panel which is shown by animation. The panel contains my form and also, inside of it I have a prop **visible** which manage to show or not the panel.

Because of that, I had to put the focus inside componentDidUpdate with a conditional to prop visible.

```
// My input
<Input ref={(node) => { this.nameInput = node; }} placeholder="Name" type="text" />,

// The method to catch the update
componentDidUpdate() {
    const { visible } = this.props;
    if (visible) setTimeout(() => this.nameInput.focus(), 100);
}
```

Just one thing I couldn't understand here.
If I click to open my panel, it works the focus.
If I click outside the input, it will loose the focus. This is the expected behaviour!

In the next time I try to open the panel, it won't work. Just If I set the time to 100 will work again.
When it looses its focus, it will not recover it again. Strange.

**Comment by oliviayizhang** [comment]
This solved my problem: 
```
<Input
   ref={(input) => input && input.focus()}
/>
```

**Comment by awais0000** [comment]
3.9.2 的解决方式
`class App extends React.Component {
handleClick = () => {
const { input } = this.inputRef; // 如果是textArea的话，const { textAreaRef } = this.inputRef;
input.focus();
input.setSelectionRange(0, input.value.length);
// input.select(); // 可全部选中
};

render() {
return (

<Input ref={(input) => { this.inputRef = input; }} defaultValue="foo" />
Focus

);
}
}`

**Comment by linzpeng** [comment]
Modal setting `destroyOnClose` and autoFocus work

**Comment by xinghul** [comment]
can we reopen the issue please? 
- the solution provided (`ref.focus()`) is just a workaround
- even setting `destroyOnClose` no longer works for the latest `antd`, not sure if it's a regression.

would love to know how to properly fix this

**Comment by yurasytnyk** [comment]
`<Modal destroyOnClose={true}>
  <Input ref={(input) => input && input.focus()} autoFocus={true} />
</Modal>`

**Comment by krcdxnh** [comment]
> `<Modal destroyOnClose={true}> <Input ref={(input) => input && input.focus()} autoFocus={true} /> </Modal>` This solved my problem (Antd: 4.24.1)

This not solved problem (Antd: 4.24.1)

**Comment by vitalyster** [comment]
Focus does work in first Modal, but does not work in second one. (4.24.8)

**Comment by alessiocancian** [comment]
This is working for me (Antd 4.24.10): 
```
<Modal destroyOnClose>
   <Input
      ref={(input) => setTimeout(input && input.focus())}
      autoFocus
   />
</Modal>
```

**Comment by it-rcmart** [comment]
A workaround (Antd 5.5.2):

Pass a random string to your component (e.g. timestamp)

`const inputRef = useRef();

useEffect(() => {
    setTimeout(function() {
        if (inputRef && inputRef.current) {
            inputRef.current.focus();
        }
    });
}, [timestamp]);

<Modal destroyOnClose>
    <Input ref={inputRef} />
</Modal>`

**Comment by ecarreras** [comment]
Another workarround could be:

```js

const inputRef = useRef();

<Modal afterOpenChange={(open) => open && inputRef.current?.focus()}>
  <Input ref={inputRef as any}/>
</Modal>
```

**Comment by podlomar** [comment]
There is actually no need for any workarounds. The `autoFocus` prop is handled by React, not by Ant. The problem is that Ant renders modal dialogs outside the application's root DOM element. This probably confuses React enough to break the `autoFocus` prop. To fix this, tell Ant to render the Modal into the root element. Let's say it has id `#app`. 

```
  <Modal
     getContainer={document.getElementById('add')!}
     // ...
  >
```

**Comment by t2elzeth** [comment]
> Another workaround could be:
> 
> ```js
> const inputRef = useRef();
> 
> <Modal afterOpenChange={(open) => open && inputRef.current?.focus()}>
>   <Input ref={inputRef as any}/>
> </Modal>
> ```

this works for me in antd 5.13.3

**Comment by anand-cubyts** [comment]
> Another workaround could be:
> 
> ```js
> const inputRef = useRef();
> 
> <Modal afterOpenChange={(open) => open && inputRef.current?.focus()}>
>   <Input ref={inputRef as any}/>
> </Modal>
> ```

This worked for me too.. none of the other solutions worked.. thank you @ecarreras  🙏  🎉

**Comment by aconrad** [comment]
For proper typing of the input ref in TypeScript (without `as` casting) and have it focused after the modal opens, you can use the following:

```tsx
import {
  Input,
  InputRef,
  Modal,
} from "antd";
import { FC, useRef } from "react";

export const MyModal: FC = () => {
  const inputRef = useRef<InputRef>(null);

  return <Modal
    // ... other modal props
    afterOpenChange={(open) => {
      open && codeInputRef.current?.focus();
    }}
  >
    <Input ref={inputRef} />
  </Modal>
};
```

Autofocus should happen after the animation is completed, so using `afterOpenChange()` is appropriate.

Tested with AntD v5.

**Comment by ezeparziale** [comment]
> For proper typing of the input ref in TypeScript (without `as` casting) and have it focused after the modal opens, you can use the following:
> 
> import {
>   Input,
>   InputRef,
>   Modal,
> } from "antd";
> import { FC, useRef } from "react";
> 
> export const MyModal: FC = () => {
>   const inputRef = useRef<InputRef>(null);
> 
>   return <Modal
>     // ... other modal props
>     afterOpenChange={(open) => {
>       open && codeInputRef.current?.focus();
>     }}
>   >
>     <Input ref={inputRef} />
>   </Modal>
> };
> Autofocus should happen after the animation is completed, so using `afterOpenChange()` is appropriate.
> 
> Tested with AntD v5.

Working OK in v5.27.2
