### ISSUE TITLE
Input cursor goes out of bounds when typing on an input that's inside a modal

### ISSUE THREAD

**Issue by johhansantana** [ant-design/ant-design#8669]
### Version
3.0.0

### Environment
any iphone with safari

### Reproduction link
[https://ant.design/components/form/#components-form-demo-form-in-modal](https://ant.design/components/form/#components-form-demo-form-in-modal)

### Steps to reproduce
click on the `new collection` button and try typing on any input

### What is expected?
Your cursor stays inside the input field

### What is actually happening?
Your cursor randomly appears elsewhere and not where you're typing

**Comment by benjycui** [comment]
And cannot be re-produced in Android..

**Comment by benjycui** [comment]
@warmhug could you try? I have no idea about mobile..

**Comment by warmhug** [comment]
ref https://github.com/ant-design/ant-design-mobile/issues/2177

**Comment by yesmeck** [comment]
It's bug of safari https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8

**Comment by yesmeck** [comment]
https://bugs.webkit.org/show_bug.cgi?id=176896
