### ISSUE TITLE
为何没有一个通用的shouldComponentUpdate

### ISSUE THREAD

**Issue by mooncakelmn** [ant-design/ant-design#867]
为什么不引入 `PureRenderMixin` (`React.createClass`) 或者ES6的方式引入PureRender的HOC？完全交给VirtualDOM吗？能少update一点算一点啊。

**Comment by afc163** [comment]
摊子太大，欢迎 PR ~

**Comment by benjycui** [comment]
Relative: https://github.com/facebook/react/issues/5788

**Comment by mooncakelmn** [comment]
@benjycui React从lib本身考虑不把｀pureRender`作为default行为也能理解，毕竟只是推荐没有强制data的使用方式。

@afc163 从基于React的component lib而言，data format可控，即使不用immutable，也可把`React.Component` wrap一下，加上default的`shouldComponentUpdate`

以上是个建议，等有需求使用ant的时候，如果React或者ant还没啥变化的话，会申请PR

**Comment by afc163** [comment]
http://segmentfault.com/a/1190000004290333

特意去补了一下知识，感谢 @mooncakelmn 的普及。
