### ISSUE TITLE
Modal中无法根据id获取元素(Modal can't get elements by id)

### ISSUE THREAD

**Issue by HeLang582** [ant-design/ant-design#8671]
### Version
3.0.2

### Environment
Win 10、 Chrome 63.0.3112.113 （32 ）

### Reproduction link
[https://codesandbox.io/s/kqx8pwjrr](https://codesandbox.io/s/kqx8pwjrr)

### Steps to reproduce
1、使用ant-design创建一个form，添加一个FormItem。   ( create a form using ant-design and add a FormItem)

```
<Form.Item {...formItemLayout}>
      {getFieldDecorator('mosaic', {
           initialValue: template.template.mosaic
      })(<MasicSet />)}
</Form.Item>
```

2、其中MasicSet 作为一个子组件传递进来。 (The MasicSet is passed in as a subcomponent)

3、MasicSet  中包含一个Model，Model中有id为drag的div。 (The MasicSet contains a Model with a div with an id in it)

```
<Modal>
       <div className={styles.drag} id="drag">
                     .........
       </div
</Modal>

```
四、在MasicSet 的生命周期componentDidMount中进行尝试获取“drag”。(Try to get "drag" in the life cycle of MasicSet)

```
  componentDidMount = () => {
    let oDrag = document.getElementById('drag');
    console.log('oDrag----',oDrag);                                       //oDrag = null
    .......
  };
```

### What is expected?
项目功能期望：
       点击一个预览按钮，弹出一个Model框，Modal框中可以展示一个图片，图片上层有一个通过canvas绘制的马赛克小框，可拖动可改变大小。根据这个马赛克所在位置获取到相对的XY坐标值，以及宽高值。

Project function expectations:
Click on a preview button to pop up a Model box. In the Modal box, you can show a picture. In the upper part of the picture, there is a Mosaic box drawn by canvas, which can be pulled and resized.According to the location of this Mosaic, the relative values of the x and y coordinates are obtained, as well as the wide and high values.

### What is actually happening?
现在存在的问题：
      点击子组件MasicSet 的预览Button，Modal框弹出来。然后在元素的生命周期componentDidMount中通过getElementById尝试去获取id为drag的div发现返回值为null。是我用的有问题还是因为组件有BUG？？？因为测试了如果是一个非Model中的元素在生命周期中是可以通过id获取到该元素的。

Existing problems:
Click on the subcomponent <MasicSet /> preview Button, the Modal box pops out.Then, in the life cycle of the element, componentDidMount tries to obtain the return value of null by using getElementById to try to get a div that id is drag.Is it something that I use or is there a BUG in the component???Because you've tested if it's a non-model element that you can get by id in your life cycle.

---
希望大神可以给一个Modal中操作Canvas的思路（Hopefully the great god can give you a way to manipulate Canvas in a Modal）

**Comment by HeLang582** [comment]
In order to better describe my problem, I have used both Chinese and English to describe the problem

**Comment by yesmeck** [comment]
A online reproduction link better than thousand of words.

**Comment by HeLang582** [comment]
Why can't I comment

**Comment by HeLang582** [comment]
@ant-design-bot @yesmeck I have updated the link

**Comment by yesmeck** [comment]
DOM in modal is not visible until modal open.

**Comment by yesmeck** [comment]
You can wrap element in modal to a separate component, then access DOM in that separate component's componentDidMount.

**Comment by yesmeck** [comment]
```javascript
class Foo extends React.Component {
   componentDidMount() {
     // Access DOM here
   }

   render() {  ... }
}


class App extends Rect.Component {
  render() {
    return (
      <Modal><Foo /></Modal>
    )
  }
}
```

**Comment by yesmeck** [comment]
Close since it's a usage question.
