### ISSUE TITLE
Modal中无法根据id获取元素(Modal can't get elements by id)

### ISSUE THREAD

**Issue by HeLang582** [ant-design/ant-design#8673]
### Version
3.0.2

### Environment
Win 10、 Chrome 63.0.3112.113 （32 ）

### Reproduction link
[https://codesandbox.io/s/kqx8pwjrr](https://codesandbox.io/s/kqx8pwjrr)

### Steps to reproduce
1、使用ant-design创建一个form，添加一个FormItem。   ( create a form using ant-design and add a FormItem)

```
<Form.Item {...formItemLayout}>
      {getFieldDecorator('mosaic', {
           initialValue: template.template.mosaic
      })(<MasicSet />)}
</Form.Item>
```

2、其中MasicSet 作为一个子组件传递进来。 (The MasicSet is passed in as a subcomponent)

3、MasicSet  中包含一个Model，Model中有id为drag的div。 (The MasicSet contains a Model with a div with an id in it)

```
<Modal>
       <div className={styles.drag} id="drag">
                     .........
       </div
</Modal>

```
四、在MasicSet 的生命周期componentDidMount中进行尝试获取“drag”。(Try to get "drag" in the life cycle of MasicSet)

```
  componentDidMount = () => {
    let oDrag = document

**Comment by yutingzhao1991** [comment]
ref: https://reactjs.org/docs/refs-and-the-dom.html
