### ISSUE TITLE
upload组件 listType 为'picture-card'时设置disable, 希望文件列表的浮层上的删除功能消失或失效

### ISSUE THREAD

**Issue by duhongjun** [ant-design/ant-design#8677]
### What problem does this feature solve?
upload组件 disabled时, 确实无法上传, 但是图片浮层上的删除按钮是有效的, 可以把图片删除掉

### What does the proposed API look like?
上传组件禁用状态 且 `listType` 为`picture-card`的时候, 图片浮层中的删除功能不生效

**Comment by dengfuping** [comment]
What's the scenario of your feature? It's strange that you cannot delete the uploaded file.

**Comment by duhongjun** [comment]
@dengfuping  but the component is disalbed, i just want user to preview the file , rather than delete the file

**Comment by dengfuping** [comment]
@duhongjun We have provided the feature to do that. You can set the prop `showUploadList={{ showRemoveIcon: false }}` to hidden the remove icon.
![image](https://user-images.githubusercontent.com/14918822/34333985-057e07a2-e97d-11e7-9fe0-9cbd2dcc2047.png)

**Comment by duhongjun** [comment]
@dengfuping thanks❗️

**Comment by RQAccount** [comment]
thanks

**Comment by snowtreetree** [comment]
Dragger 里面设置了disable之后，删除按钮不显示？

**Comment by sophieChenyx** [comment]
为什么我这边设置了 disable 以后
删除按钮不在了呢 我是需要删除按钮的啊
。。。。  我快肝死了

**Comment by yoyo837** [comment]
showUploadList 控制的删除按钮，如果还有问题 ，提供复现

**Comment by excellnn** [comment]
Upload组件为disabled之后，即使配置
```
showUploadList={{
            showRemoveIcon: true
          }
```
也无法点击删除按钮！这个删除按钮能否点击应该交给用户来配置而不是继承Upload组件的disabled
