### ISSUE TITLE
tabs component active item don't have underline

### ISSUE THREAD

**Issue by OPY-bbt** [ant-design/ant-design#8678]
### Version
3.0.2

### Environment
mac use dva@2.1.0

### Reproduction link
[https://github.com/OPY-bbt/antTabsPostBug.git](https://github.com/OPY-bbt/antTabsPostBug.git)

### Steps to reproduce
- demo in homepage
- set defaultActiveKey second item's key

### What is expected?
first render correctly 

### What is actually happening?
the active Item don't have underline

**Comment by suxu** [comment]
Cannot read property 'ownerDocument'  version at 3.8.0
