### ISSUE TITLE
自动完成组件，更改数据源时会自动弹出

### ISSUE THREAD

**Issue by LDD123** [ant-design/ant-design#8679]
### Version
2.13.10

### Environment
win10   chrome63

### Reproduction link
[http://没在giuthub上写](http://没在giuthub上写)

### Steps to reproduce
使用dva ,改变了modal里面的数据，使得备选框里的source={[.....]}值发生改变，备选框全部弹出来了，界面中一共有5个，全自动弹出来了

### What is expected?
想知道这是我的问题还是组件不完整

### What is actually happening?
数据源发生改变时，能够不自动弹出备选框

**Comment by yesmeck** [comment]
Duplicate of #7367
