### ISSUE TITLE
input的前后置标签高度与input高度不一致

### ISSUE THREAD

**Issue by jdongdong** [ant-design/ant-design#8680]
### Version
3.0.2

### Environment
操作系统：win7 
chrome:版本 60.0.3112.78（正式版本） （32 位）

### Reproduction link
[https://81y10nlyy0.codesandbox.io/](https://81y10nlyy0.codesandbox.io/)

### Steps to reproduce
见重现链接

### What is expected?
前后置标签高度与input高度一致

### What is actually happening?
前后置标签高度与input高度不一致

**Comment by yutingzhao1991** [comment]
Can't see reproduction code.

![image](https://user-images.githubusercontent.com/1061968/34203522-6b5c885c-e5b6-11e7-8730-03b401e67b66.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/81y10nlyy0
