### ISSUE TITLE
Upload 手动上传加上进度条

### ISSUE THREAD

**Issue by Y00z** [ant-design/ant-design#8681]
### What problem does this feature solve?
请求Upload组件的手动上传加上进度条，更直观看到上传进度

### What does the proposed API look like?
在{...props}中 设置一个参数，是否显示进度条，默认true，

**Comment by afc163** [comment]
手动上传是什么意思？

**Comment by dengfuping** [comment]
手动上传的话会一次性上传多个文件，这样的话应该是每个文件都有一个单独的进度条

![image](https://user-images.githubusercontent.com/14918822/34284275-ab18d60c-e70b-11e7-93ce-3b3fe53730a1.png)

**Comment by joint-song** [comment]
@dengfuping 一个跟本issue关系不大的问题是，可不可以不通过Upload本身去上传，而是构造一个Progress的Object给props，然后自己去构建上传的ajax，因为很多时候希望用project内已有的代码逻辑来构建ajax，上面说到的手动模式是不是就可以实现这样的功能呢？通过`beforeUpload => false`来手动处理Promise的逻辑？    
但是action参数必填又很糟心(有点多余的，又不知道填什么，但又不能不填):)；    
但是我又希望方便得使用Upload组件的interface、UI styles来做前端功能。因为AntDesign确实很方便得能让我快速搭建出来一个统一风格、专业的网站来。

**Comment by kanweiwei** [comment]
It seems like the animation of uploading  is related to  some attributes of the single `UploadFile ` object, like `status`、 `percent`, etc. We can update the  `UploadFile ` object in the onprogress callback of xhr2. I am trying to implement the feature.

**Comment by bytrix** [comment]
问题解决了吗？我现在项目中也需要用手动上传显示进度，无奈只能用定时器自己做一个伪进度

**Comment by bytrix** [comment]
找到解决方法了，beforeUpload中返回false会无法触发onChange事件，需要自己发送ajax请求，浏览器原生的XMLHttpRequest.upload中的onprogress方法可以获取进度
`
          this.xhr = new XMLHttpRequest();
          const formData = new FormData();
          formData.append('video_file', this.props.form.getFieldValue('video_file').file);
          this.xhr.open('POST', 'http://192.168.96.131:8001/api/videos/upload/');
          this.xhr.upload.onprogress = event => {
            this.setState({
              ...this.status,
              percent: Math.round((event.loaded / event.total) * 100),
            });
          };
          this.xhr.send(formData);
`

**Comment by ZCatherine** [comment]
@bytrix 前端小白求给个完整代码看一下

**Comment by ShadowWalker627** [comment]
实现样例：https://juejin.im/post/5e984a87e51d4546f27ffca5
