### ISSUE TITLE
Unable to access inputs using name 

### ISSUE THREAD

**Issue by tgsd96** [ant-design/ant-design#8683]
### Version
3.0.2

### Environment
Mac Os X

### Reproduction link
[https://github.com/tgsd96/ant-design](https://github.com/tgsd96/ant-design)

### Steps to reproduce
Suppose we create a form, with Input and Autocomplete component.
Suppose the form looks like:
<form>
<Autocomplete name="ac"/>
<Input name="input"/>
</form>
When the form is submitted, the Input is accessible by using event.target.input but Autocomplete is undefined in the target.

### What is expected?
Well, to make submission of large forms easier, other input methods like Autocomplete, Select, Switch should be accessible through name parameter. So it should be accessible like event.target.ac 

### What is actually happening?
event.target.ac comes out to be undefined

**Comment by afc163** [comment]
You should collect values by React and antd's way, not by the old html way:

https://reactjs.org/docs/forms.html

http://ant.design/components/form/

**Comment by sorsaffari** [comment]
@afc163 Libraries like formik rely on the `name` attribute on the form elements. Could you please advice me on how could use an external library (like formik or redux-form) for the logic alongside Ant Design's Form Component for the presentation?

**Comment by adavia** [comment]
@sorsaffari Have you tried using setFieldValue prop from Formik?
Example:
`<Autocomplete onChange={value => setFieldValue('your_input',  value)} onSelect={setFieldTouched} />`

**Comment by richrd** [comment]
This is really annoying. In use case I need to create  a FormData object from the form (with uploads and other fields) to send to a backend. Now since none of the fields have a name my FormData is always empty. Is there any way I can work around this? I know I can do it the "antd" way but I'd go with web standards.

**Comment by ztplz** [comment]
@richrd 
For example:
``````
currently

{getFieldDecorator('note', {
            rules: [{ required: true, message: 'Please input your note!' }],
          })(
            <Input />
)}
``````

What you expect:
``````
{getFieldDecorator({
            rules: [{ required: true, message: 'Please input your note!' }],
          })(
            <Input name="note" />
)}
`````
It doesn't seem to be necessary IMO, just to be more like a web standard ?
If my example is not the same as what you imagine, please correct me.

**Comment by richrd** [comment]
Yeah, that's exactly what I meant for the `<Input>` fields, and it seems to work fine. However doing `<Upload name="videoFile">` doesn't set the name attribute of the file input.

**Comment by ztplz** [comment]
Because `name` is the name of uploading file in `Upload`.

**Comment by florian-bd** [comment]
One reason to add support for name is browser autocompletion. If you specify a name or an id to an input, the browser will save values that you enter.

**Comment by richrd** [comment]
@florian-bd Excellent point, I had been wondering why the forms in my antd frontend never seemed to offer autocomplete. Would be really nice if the name attributes were added by default.

**Comment by elie222** [comment]
Ya. Just ran into this issue with Ant Design Select too.

**Comment by coderdix** [comment]
Same with antd select :-(

**Comment by elie222** [comment]
How I solved with Formik custom component and AntD Select:

```ts
import * as React from 'react'
import { FieldProps } from 'formik'
import { Form, Select } from 'antd'

export const CustomSelectComponent = ({
  field, // { name, value, onChange, onBlur }
  form: { touched, errors, setFieldValue }, // also values, setXXXX, handleXXXX, dirty, isValid, status, etc.
  ...props
}: FieldProps & {
  label: string
  options: Array<{ value: string; label: string }>
  style?: React.CSSProperties
}) => {
  const { options } = props

  return (
    <Form.Item label={props.label}>
      <Select
        {...field}
        {...props}
        defaultValue={options[0]?.value}
        style={props.style}
        onChange={value => setFieldValue(field.name, value)}
      >
        {options.map(option => (
          <Option key={option.value} value={option.value}>
            {option.label || option.value}
          </Option>
        ))}
      </Select>
      {/*  */}
      {touched[field.name] && errors[field.name] && (
        <ErrorMessage>{errors[field.name]}</ErrorMessage>
      )}
    </Form.Item>
  )
}
```

**Comment by kaloraat** [comment]
@elie222 wow `Object.values` is a life saver :)

**Comment by benwiley4000** [comment]
> You should collect values by React and antd's way, not by the old html way:
> 
> https://reactjs.org/docs/forms.html
> 
> http://ant.design/components/form/

Nothing to do with collecting values, everything to do with HTML standards.

**Comment by nvmnghia** [comment]
This is quite a surprise for me. I think we should honor the standard, and put `name` on the inputs.

**Comment by Jaimayal** [comment]
Just leaving some documentation in case someone runs into the same issue with `Upload` when using NextJS 13+.
[As stated above](https://github.com/ant-design/ant-design/issues/8683#issuecomment-445836034), you can't directly change the `name` attribute of the `<input type="file" />` thats rendered on the DOM, so you are not able to submit the file directly to your server action.

There are several workarounds that you can do, in our case, we built a Route Handler (which is a simple API endpoint) that receives the file thats submitted on the [`action`](https://ant.design/components/upload#api) event of the `Upload` component. Inside the route handler, we built the relative file path, stored the image and returned the same path inside the JSON response. Finally, we checked for the `done` state on the [`onChange`](https://ant.design/components/upload#onchange) event, accessed the Route Handler response (by doing `info.file.response.fileLocation`) and stored the path on a hidden `<input />` element which is then passed to the server action to store the file location on the db.
