### ISSUE TITLE
display problem when the DatePicker receives an invalid date.

### ISSUE THREAD

**Issue by aityahiaidir** [ant-design/ant-design#8685]
### Version
3.0.2

### Environment
Windows 10 , Firefox 57 64 bits

### Reproduction link
[https://codepen.io/iaityahia/pen/ZvOGPw](https://codepen.io/iaityahia/pen/ZvOGPw)

### Steps to reproduce
A simple Antd Form with a datepicker filed mapped to a the form state via it's props, when an invalid date is setted in the state 

### What is expected?
We get wrong display and we cant sette a date 

### What is actually happening?
We get a NaN in wall calendar days, when we try to nullate the date it impossible
as you can see in the attached codepen snippet

**Comment by afc163** [comment]
I think it is a intent behavior and swallowing up error is not good. You should make sure that value is valid.

**Comment by aityahiaidir** [comment]
I think it's better to manage that, for example convert invalid values to Null instead of  having an erroned display
