### ISSUE TITLE
RangePicker  Chinese display bug

### ISSUE THREAD

**Issue by thbgh** [ant-design/ant-design#8691]
### Version
3.0.2

### Environment
react16   win    chrome63

### Reproduction link
[https://user-images.githubusercontent.com/9399517/34239832-0f7194e4-e645-11e7-8862-70489c2ab04d.png](https://user-images.githubusercontent.com/9399517/34239832-0f7194e4-e645-11e7-8862-70489c2ab04d.png)

### Steps to reproduce
https://user-images.githubusercontent.com/9399517/34239832-0f7194e4-e645-11e7-8862-70489c2ab04d.png

### What is expected?
Chinesize totally

### What is actually happening?
https://user-images.githubusercontent.com/9399517/34239832-0f7194e4-e645-11e7-8862-70489c2ab04d.png

**Comment by chowsource** [comment]
this bug is the same as mine.
 see: [#8662](https://github.com/ant-design/ant-design/issues/8662).

**Comment by Airkro** [comment]
Got same problem, `LocaleProvider` is not enough， I use this fix it:

```js
import moment from 'moment';
import 'moment/locale/zh-cn';

moment.locale('zh-cn');
```

But maybe don't need it.

**Comment by thbgh** [comment]
I did use this setting,then chinese showed not totally.

**Comment by Airkro** [comment]
https://codesandbox.io/s/8nklm200y2

**Comment by thbgh** [comment]
antd 2.x, no problem
upgraded to antd 3.x ,problem came out.
Why not totally.It means my language setting works,but work halfly.

**Comment by thbgh** [comment]
After i restart my project using antd3
NO Problem !

**Comment by yesmeck** [comment]
`moment.locale('zh-cn');` is not required, but you need `import 'moment/locale/zh-cn';`. I've updated document.

**Comment by Airkro** [comment]
I know `moment.locale('zh-cn');` is not required.
However, in my project, I have to use it.
Without it, will be not working, like @ thbgh's example.

I still try to figure out why, maybe it's some kind of side effect by `import order` or `vendor/dll Plugin`

**Comment by thbgh** [comment]
I can agree @Airkro  more ! 
the inside configurations of 2.x and 3.x  are different

**Comment by chowsource** [comment]
@yesmeck 这就关闭bug了?这个bug没有解决呀,和我这个bug是一样的,这是bug,不是moment设置问题

**Comment by yesmeck** [comment]
@chowsource 请提供重现。

**Comment by chowsource** [comment]
@yesmeck 在我提的链接里我都贴代码了,也没人回复
https://github.com/ant-design/ant-design/issues/8662

**Comment by yesmeck** [comment]
@chowsource 在线可运行的重现 demo 或者精简的可重现代码仓库。

**Comment by chowsource** [comment]
@yesmeck 在线运行的,不一定能真实展现bug,我提的bug已经很清楚了,都截图了

**Comment by yesmeck** [comment]
@chowsource 如果你希望你的 bug 快速解决的话，帮助我们重现是最好的办法。

**Comment by afc163** [comment]
@chowsource 试试用 http://u.ant.design/codesandbox-repro 重现一下，或者干脆提供一个 GitHub repository。

**Comment by Airkro** [comment]
能够确定的是引发问题的原因不止一个，最好大家都能提供精简过的repo

**Comment by chowsource** [comment]
![image](https://user-images.githubusercontent.com/5119971/34431074-a75799fe-eca6-11e7-92c4-049035280af6.png)
提供的网址运行不了

**Comment by yesmeck** [comment]
参考 https://u.ant.design/codesandbox-repro

**Comment by chowsource** [comment]
@yesmeck bug demo 代码仓库:https://github.com/chowsource/antd-datepicker-bug-demo.git

**Comment by lileilei** [comment]
> 我知道`moment.locale('zh-cn');`不是必需的。
> 但是，在我的项目中，我必须使用它。
> 没有它，将无法正常工作，例如@ thbgh的示例。
> 
> 我仍然试图找出为什么，也许是某种副作用的`import order`或`vendor/dll Plugin`

我这里一样打里dll后，不光datepick，可能分页也会有此问题。但是日期我选择一下后立马就变成了中文。
