### ISSUE TITLE
饼形图有三个维度选择时，有一个维度的数据为空，点击另外两个维度会将数据显示到为空的维度内。

### ISSUE THREAD

**Issue by chengzl** [ant-design/ant-design#8692]
### Version
3.0.2

### Environment
win7,google,v6.9.5

### Reproduction link
[https://preview.pro.ant.design/#/dashboard/analysis)

### Steps to reproduce
将“销售额类别占比”中“全部渠道”的数据设置为空，然后刷新，点击“线上”或“门店”再点击“全部渠道”，发现本为空的数据，会把“线上”或“门店”的数据显示到“全部渠道”中

### What is expected?
为空就显示空，不应受其他维度的影响

### What is actually happening?
为空的维度里会显示其他维度中的图形

**Comment by yesmeck** [comment]
你应该提到 https://github.com/ant-design/ant-design-pro
