### ISSUE TITLE
All components have default margin and padding

### ISSUE THREAD

**Issue by AleksandrZhukov** [ant-design/ant-design#8695]
### Version
3.0.2

### Environment
all

### Reproduction link
[http://joxi.ru/4AkaGMPsM7wQXm](http://joxi.ru/4AkaGMPsM7wQXm)

### Steps to reproduce
Check css styles of any component with prefix `ant-`. Each has default margin and padding equal to 0.

### What is expected?
Component has no default margin and padding values equal to 0. It adds some problems of using global styles with the same specificity. 

### What is actually happening?
Components has default values.

**Comment by yutingzhao1991** [comment]
You should ensure your global styles className Keep not the same to `ant-`.

**Comment by AleksandrZhukov** [comment]
I don't use `ant-` classnames. The problem that I can't use another class with the same specificity. I think components (like buttons or checkboxes) should not set any outer values(margins), they should inherit them

**Comment by yutingzhao1991** [comment]
Sorry, we follow Ant Design design guideline which we have to set margin etc...

Ant you can use props style:

```
<Button type="primary" style={{ padding: 50 }}>Button</Button>
```

**Comment by AleksandrZhukov** [comment]
@yutingzhao1991 Will be better to have variables for this values instead of setting them to 0
