### ISSUE TITLE
按钮样式

### ISSUE THREAD

**Issue by lovexurongquan** [ant-design/ant-design#8699]
### What problem does this feature solve?
按钮样式不够用，不同场景用的按钮不一样。

### What does the proposed API look like?
希望加点success warning info 这类的按钮。

**Comment by afc163** [comment]
Sorry, we follow Ant Design design guideline which does'nt contain those types of button.

**Comment by dengfuping** [comment]
@lovexurongquan It's easy to encapsulate these kinds of button based on Antd Button by yourself.
