### ISSUE TITLE
table 没有 tfoot 标签

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#8706]
### What problem does this feature solve?
完整的table结构更利于打印结构化，没有tfoot标签无法识别表尾

### What does the proposed API look like?
能否提供个属性来设置表尾呢

**Comment by yesmeck** [comment]
> 打印结构化，没有tfoot标签无法识别表尾

能说详细点吗？

**Comment by aw6658913** [comment]
打印的时候经常会遇到表格数据过多一页打印不下，会分页到第二页的情况，这时候就需要把表格数据根据表头表尾辨别进行分页，然后中间数据分页，保留表头表尾，但是我看控件只有表头没有表尾

**Comment by yesmeck** [comment]
Traced in #5710

**Comment by LDD123** [comment]
很傻的一个解决方法感觉
