### ISSUE TITLE
menu 收缩动画

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#8707]
1.submenu 收回时文字直接没了。。。

2.submenu 的下拉收回直接没了

3.submenu icon 没过渡了

占坑。。。

#6955

**Comment by unrealsmart** [comment]
ant design 3.0.3
menu 组件，在缩起状态下（小图标模式）子菜单会出现闪几下的情况，emmmm，就跟抽了疯似的
谷歌浏览器：版本 63.0.3239.108（正式版本） （64 位）

**Comment by jljsj33** [comment]
@unrealsmart 你这问题可以重新提个 issuse，把你遇到的 bug 描述清楚。。
