### ISSUE TITLE
get lots of warning information when using Menu component

### ISSUE THREAD

**Issue by limengke123** [ant-design/ant-design#8708]
### Version
3.0.1

### Environment
react v16

### Reproduction link
[https://github.com/limengke123/blog_react](https://github.com/limengke123/blog_react)

### Steps to reproduce
when using Menu component,this will be found

### What is expected?
no error 

### What is actually happening?
the Menu component works correctly , but got lots of warning infomation in Console.
e.g.
React does not recognize the `inlineIndent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inlineindent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by dengfuping** [comment]
@limengke123 Please give a separated example to reproduce your problem rather than to give whole project. I don't think it's result from antd after running your project. In fact, I separate your header component and no error found.

**Comment by limengke123** [comment]
@dengfuping you can follow the below link to check the error on the console. 
     https://codesandbox.io/s/14qlkl80j4

**Comment by limengke123** [comment]
@dengfuping you can check below link to check this error in the console. https://codesandbox.io/s/14qlkl80j4

**Comment by yesmeck** [comment]
Don't put `<a className="logo" to="/" />` under `Menu` directly.

**Comment by yesmeck** [comment]
Yes.

**Comment by kkuzmina** [comment]
@yesmeck What if I need to use Link instead of Menu.Item (the reason is to be able to see 'open in a new tab' option on right-click)?

**Comment by gondar00** [comment]
Facing this even by using ant design `Divider` component

**Comment by awarmfastbear** [comment]
> 
> 
> @yesmeck @kkuzmina You get the error if you nest vanilla HTML elements, but you can nest react `Components`.
> 

Are you sure this is true? I get all of errors described above by having an empty MaterialUI List component in the Antd Menu component. I can't figure out a way to solve it :(
