### ISSUE TITLE
Input.Search最后搜索按钮无法使用

### ISSUE THREAD

**Issue by phper-jser** [ant-design/ant-design#8709]
### Version
3.0.2

### Environment
windows、chrome-61.0.3163.100、react-16.2.0

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
直接引入 Input.Search默认点搜索Icon无法搜索，按下回车键可以，官网demo亦如此！

### What is expected?
Input.Search正常使用

### What is actually happening?
Input.Search 最后的搜索Icon无法点击，无法正常使用

**Comment by dengfuping** [comment]
Duplicate with #8445
