### ISSUE TITLE
layout api 参考

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#871]
http://developer.telerik.com/featured/demystifying-nativescript-layouts/

**Comment by pizn** [comment]
赞

**Comment by afc163** [comment]
http://whoisandie.github.io/react-blocks/

**Comment by afc163** [comment]
http://bulma.io/documentation/grid/

**Comment by afc163** [comment]
http://roylee0704.github.io/react-flexbox-grid/

**Comment by yiminghe** [comment]
https://github.com/STRML/react-grid-layout
