### ISSUE TITLE
Add `forceRender` to `Collapse.Panel`

### ISSUE THREAD

**Issue by gimenete** [ant-design/ant-design#8714]
### What problem does this feature solve?
Sometimes you need some components to be loaded even if they are not visible. There is already a `forceRender` attribute in `Tabs.TabPane` but the same behavior is desired for `Collapse.Panel` too.

### What does the proposed API look like?
`forceRender`: Force rendering of content in panels, instead of lazy rendering it. Type `boolean`, default `false`

**Comment by gimenete** [comment]
Btw, awesome work on this library! 💪

**Comment by paulcmason** [comment]
This seems to make sense to me.

@yutingzhao1991 - I am happy to work on this - first thing is to add the feature to rc-collapse component library and then come back to ant-design to add the feature / pass the new prop through to rc-collapse?

**Comment by yutingzhao1991** [comment]
@paulcmason YES!

**Comment by paulcmason** [comment]
@yutingzhao1991 - I'll get together a pull request for rc-collapse

**Comment by paulcmason** [comment]
Waiting for https://github.com/react-component/collapse/pull/82 to be merged now before doing a pull request for ant-design
