### ISSUE TITLE
Mention设置多个prefix时，触发的下拉列表异常

### ISSUE THREAD

**Issue by fx-2** [ant-design/ant-design#8720]
### Version
2.13.11

### Environment
Chrome 63.0.3239.84

### Reproduction link
[http://2x.ant.design/components/mention-cn/](http://2x.ant.design/components/mention-cn/)

### Steps to reproduce
自定义触发字符示例中：
1.按正常流程输入@afc163 = #1.0 and @afc163 ；
2.在第一步的文本基础上删除@afc163 = #1.0，文本变为 and @afc163 ；
3.在文本最前面重新按正常流程输入@afc163 = #1.0时，@可以正常出现下拉列表，当输入到trigger为#时，下拉列表没有改变，还是@触发的下拉列表；

### What is expected?
按照上述步骤，每一步都出现正常的下拉列表

### What is actually happening?
按照上述步骤最后一步，#触发的下拉列表不正确

**Comment by dengfuping** [comment]
@RaoHai In antd 3.0 version, it won't trigger when the prefix is # according to the reproduce steps.

**Comment by yutingzhao1991** [comment]
![bug](https://user-images.githubusercontent.com/1061968/34330852-4b6c8f84-e95c-11e7-887b-09b5e671900a.gif)

只要后面有 `@` 前面输入 `#` 的提示就会有问题。

**Comment by RaoHai** [comment]
Thanks for feedback and reproduction, I'll fix it later.

**Comment by RaoHai** [comment]
* rc-editor-mention@0.6.14 for antd 2.x
* rc-editor-mention@1.1.3 for antd 3.0

**Comment by RaoHai** [comment]
Reinstall your dependency packages would solve the problem.

**Comment by fx-2** [comment]
@RaoHai It's ok now, Thank you.
