### ISSUE TITLE
list control sample:Infinite & virtualized has some errors

### ISSUE THREAD

**Issue by monkingame** [ant-design/ant-design#8721]
### Version
3.0.3

### Environment
Windows 10/macOS High Sierra,Chrome 63,react v16

### Reproduction link
[https://ant.design/components/list/#components-list-demo-infinite-virtualized-load](https://ant.design/components/list/#components-list-demo-infinite-virtualized-load)

### Steps to reproduce
paste the sample codes into a react sample project,error occured:
TypeError: Cannot read property 'scrollTop' of null

### What is expected?
List result same as document 

### What is actually happening?
TypeError: Cannot read property 'scrollTop' of null
dimensions.js:64 Uncaught TypeError: Cannot read property 'scrollTop' of null
Uncaught TypeError: Cannot read property 'removeEventListener' of null
Uncaught TypeError: Cannot read property 'scrollTop' of null

**Comment by yutingzhao1991** [comment]
Can you give a reproduce demo with https://codesandbox.io/s/o4worj9orz .

**Comment by monkingame** [comment]
https://codesandbox.io/s/8njlnq1m92

Can you see the reproduce  demo?

**Comment by yanguoyu** [comment]
you delivery scrollElement=null into WindowScroller, this cause element is null .`  if (element === window) {
    return {
      top: 'scrollY' in window ? window.scrollY : document.documentElement.scrollTop,
      left: 'scrollX' in window ? window.scrollX : document.documentElement.scrollLeft
    };
  } else {
    return {
      top: element.scrollTop,
      left: element.scrollLeft
    };
  }`
but i think the function should add null judgeMent

**Comment by monkingame** [comment]
Thanks @yanguoyu 
I tested the sample code and it works correctly if ` scrollElement={null} ` removed.
Since I haven't learn any react-virtualized yet, I don't know why the error occured.

**Comment by monkingame** [comment]
`return (
      <List>
        {
          data.length > 0 && (
            <WindowScroller scrollElement={null}>
              {infiniteLoader}
            </WindowScroller>
          )
        }
        {this.state.loading && <Spin className="demo-loading" />}
      </List>
    );`
Above codes are from sample document ,perhaps react-virtualized lib updated and the sample codes didn't update synch.
But what is the correct codes if  scrollElement used?

**Comment by yanguoyu** [comment]
i think you should open a issues in react-virtualized.  
the function getScrollOffset should has null exception judgement at least.
i don't know react-virtualized lib. but i know you should delivery a scrollElement  that has scrollTop and scrollLeft property at least.
