### ISSUE TITLE
Memu内包含不是类型为Memu.Item的子节点

### ISSUE THREAD

**Issue by yanguoyu** [ant-design/ant-design#8722]
### Version
2.13.11

### Environment
mac osx 10.13.1 chrome  63.0.3239.84

### Reproduction link
[https://codesandbox.io/s/644vz1p46r](https://codesandbox.io/s/644vz1p46r)

### Steps to reproduce
1：在Menu中包含了不是Menu.Item的子节点。
2：会提示没有Menu需要的一些属性。例如：renderMenuItem、rootPrefixCls。

### What is expected?
1：对存在于Menu内的非Menu的子节点分别处理，不去走menu的渲染流程。直接返回该子节点。

### What is actually happening?
1：应该是对每个Menu的一级子节点都进行了Menu的渲染过程，导致很多props找不到。

---
这个并不是个bug，不影响Menu组件的使用，只是觉得有优化的可能性。

**Comment by yesmeck** [comment]
Duplicate of #4853

目前没有好的解决方案。
