### ISSUE TITLE
table设置为small，fixed的列会有padding值

### ISSUE THREAD

**Issue by liyingpu0630** [ant-design/ant-design#8724]
### Version
3.0.3

### Environment
windows

### Reproduction link
[https://codesandbox.io/s/r5nwm0nmzp](https://codesandbox.io/s/r5nwm0nmzp)

### Steps to reproduce
table设置为small；
固定列；

### What is expected?
正常显示的小表格

### What is actually happening?
固定的列会有左右padding值

**Comment by chowsource** [comment]
@afc163 
原来3.03版本 我的small表格是正常的,现在更新到3.1.0反而出现了这个bug,顾此失彼
![image](https://user-images.githubusercontent.com/5119971/34479826-c240f842-efe3-11e7-9dca-89e3d0bc9928.png)
上面这个截图是3.03版本的small table,正常的,

![image](https://user-images.githubusercontent.com/5119971/34479891-25165304-efe4-11e7-87ab-5551d730ddf5.png)
这个截图是3.1.0版本,不正常了,我的表格没有固定表格
