### ISSUE TITLE
Radio 的 children 用 span 包裹不太合适

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#8725]
代码行： https://github.com/ant-design/ant-design/blob/master/components/radio/radio.tsx#L78

目前 radio 的 children 用 span 包裹，且没有给接口加样式，业务上还得自己找元素；业务上 children 的结构可能比较复杂， span 行内标签嵌套 div 这类的跨级元素也不合适；

建议：去掉 span 包裹，业务自己来搞

**Comment by afc163** [comment]
现在的 span 主要是用来放间距样式的。

> span 行内标签嵌套 div 这类的跨级元素也不合适

这个不用拘泥，可以套，antd 里也有很多套了的。
