### ISSUE TITLE
RangePicker showTime.defaultValue can‘t use in typescript

### ISSUE THREAD

**Issue by marshalys** [ant-design/ant-design#8727]
### Version
3.0.3

### Environment
typescript:2.6.2

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
my code from example https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date :

```
showTime={{
                format: "HH:mm:ss",
                defaultValue: [moment("00:00:00", "HH:mm:ss"), moment("11:59:59", "HH:mm:ss")]
              }}
```

### What is expected?
I wish it can work right

### What is actually happening?
TS2322: Type '{ className: any; placeholder: [string, string]; format: "YYYY-MM-DD HH:mm:ss"; showTime: { forma...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RangePickerProps, ComponentState>> & Rea...'.
  Type '{ className: any; placeholder: [string, string]; format: "YYYY-MM-DD HH:mm:ss"; showTime: { forma...' is not assignable to type 'Readonly<RangePickerProps>'.
    Types of property 'showTime' are incompatible.
      Type '{ format: string; defaultValue: Moment[]; }' is not assignable to type 'boolean | TimePickerProps | undefined'.
        Type '{ format: string; defaultValue: Moment[]; }' is not assignable to type 'TimePickerProps'.
          Types of property 'defaultValue' are incompatible.
            Type 'Moment[]' is not assignable to type 'Moment | undefined'.
              Type 'Moment[]' is not assignable to type 'Moment'.
                Property 'format' is missing in type 'Moment[]'.

**Comment by yesmeck** [comment]
`defaultValue` is `Moment`, not a array.

**Comment by marshalys** [comment]
![image](https://user-images.githubusercontent.com/344530/34721691-b22c233c-f57e-11e7-86a4-7ec089d61a65.png)

RangePicker is different, you can see in doc:  https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date

**Comment by marshalys** [comment]
😄

**Comment by marshalys** [comment]
thank you @yesmeck
