### ISSUE TITLE
<Button>{0}</Button> 显示结果和预期不符合

### ISSUE THREAD

**Issue by Cuihongsen** [ant-design/ant-design#8728]
### Version
3.0.3

### Environment
mac 10.13.2 |   Google Chrome 版本 63.0.3239.84  | react 16.2.0

### Reproduction link
[https://github.com/Cuihongsen/ant-design-pro](https://github.com/Cuihongsen/ant-design-pro)

### Steps to reproduce
Clone git repository 
src/routes/Dashboard/Analysis.js   render function

cnpm i
cnpm start

<Button>{0}</Button>and<Button>0</Button> 
The display does not match the expected result

### What is expected?
a button with text 0

### What is actually happening?
a button with text empty string

**Comment by yutingzhao1991** [comment]
Simple reproduce link: https://codesandbox.io/s/84rv7l85l2

**Comment by yesmeck** [comment]
@Cuihongsen Could you open a PR?
