### ISSUE TITLE
Update docs on create-react-app import guide

### ISSUE THREAD

**Issue by bodaz** [ant-design/ant-design#8730]
### What problem does this feature solve?
In the current `Use in create-react-app` doc page, to import a component is instructed under the "Advanced Guide" section and leads people to install `babel-plugin-import` just to do `import { Button } from "antd"`, but it is possible for a beginner to Ant Design to just do: `import { Button } from "antd"` without `react-app-rewired` or `babel-plugin-import` 

### What does the proposed API look like?
Under the "Import antd" section, remove the example of `import Button from 'antd/lib/button'` and just do `import { Button } from "antd"`. I'm happy to make a PR for the doc change.

**Comment by yutingzhao1991** [comment]
I don't agree to remove the example of import Button from 'antd/lib/button', but you can add more doc to tell user about  `import { Button } from "antd"` at the bottom of `Import antd`.

just make a PR ant we will review it.

**Comment by yesmeck** [comment]
Importing components from `antd` directly will load all components which even not use.  That's why we `import Button from 'antd/lib/button'` and why `babel-plugin-import` exists.
