### ISSUE TITLE
In official site: https://ant.design/docs/react/introduce-cn, demo expample source code open in CodePen is blank page

### ISSUE THREAD

**Issue by happier2** [ant-design/ant-design#8731]
### Version
3.0.3

### Environment
Windows 10， Chrome 63

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
1. open https://ant.design/components/select-cn/
2.click and expand source code，click CodePen icon

### What is expected?
codepen render result

### What is actually happening?
codepen result is blank

**Comment by afc163** [comment]
It works on my mac: 

<img width="822" alt="image" src="https://user-images.githubusercontent.com/507615/34344304-82320792-ea1f-11e7-9584-e5e57fa476c9.png">

**Comment by dengfuping** [comment]
@happier2 @afc163 It seems that only the example named Search Box is a blank page when opened in [CodePen](https://codepen.io/pen/?&editors=001).

**Comment by afc163** [comment]
Those codepen is hard to implement. That is why https://github.com/ant-design/ant-design/issues/8265 existed.
