### ISSUE TITLE
cdn file executes failed

### ISSUE THREAD

**Issue by shhider** [ant-design/ant-design#8735]
### Version
3.0.3

### Environment
macOS 10.13.2、Chrome 63、react 16、react-dom 16

### Reproduction link
[https://jsfiddle.net/haohong/svh0jp0k/](https://jsfiddle.net/haohong/svh0jp0k/)

### Steps to reproduce
1. add react, react-dom to html file
2. add antd file too
3. open html file by browser
4. run ``antd`` in browser console

### What is expected?
``antd`` should be added in ``window``, and there is no error.

### What is actually happening?
there is some errors in console:

```
Uncaught TypeError: pa(...) is not a function
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/6236cb144bc4c72bc7906176f1ad56f8102fde93

**Comment by shhider** [comment]
Thanks.

And, this tip about ``moment`` has not be added to ant.design yet.
