### ISSUE TITLE
Document said Menu's selectable is true by default, but it's not.

### ISSUE THREAD

**Issue by shhider** [ant-design/ant-design#8736]
### Version
3.0.3

### Environment
macOS 10.13.2、Chrome 63、react 16、react-dom 16

### Reproduction link
[https://jsfiddle.net/haohong/svh0jp0k/](https://jsfiddle.net/haohong/svh0jp0k/)

### Steps to reproduce
1. add react, react-dom to html file
2. add antd's js and css files to html file
3. add code from [https://jsfiddle.net/haohong/svh0jp0k/](https://jsfiddle.net/haohong/svh0jp0k/) to html file
4. open the file by browser, and open browser console
5. after Menu instance is rendered, click any one item

### What is expected?
The console should print "select" message

### What is actually happening?
nothing.

And, after adding ``selectable`` to Menu element, click a un-selected item again, 'select' message is printed.

**Comment by afc163** [comment]
It works: https://codepen.io/afc163/pen/JMEXGO?editors=0010

**Comment by shhider** [comment]
Thanks.

And sorry, I didn't know ``menu cannot be selectable in dropdown defaultly`` before.
