### ISSUE TITLE
Cannot close Modal wrapped inside Button

### ISSUE THREAD

**Issue by oluckyman** [ant-design/ant-design#8738]
### Version
3.0.3

### Environment
osx, Chrome

### Reproduction link
[https://codesandbox.io/s/yn3rzwxn1](https://codesandbox.io/s/yn3rzwxn1)

### Steps to reproduce
Wrap Modal into Button component, as in first example

### What is expected?
Modal `onOk` and `onClose` callbacks have access to state of the parent component so modal could be closed

### What is actually happening?
calling `this.setState` from `onOk` and `onClose` does not changes state of the parent component

---
when the modal is placed outside Button component it works as expected.

You may suggest do not wrap `Modal` inside `Button` component. It's not a problem.
The problem is a large codebase written on `ant@2.x` and full of `<Button><Modal></Button>` snippets. It's hard to find and it requires adding redundant `<div>` wrapper which breaks styles sometimes.

**Comment by yesmeck** [comment]
`Modal` used `React.createPortal`  internally, `React.createPortal` will propagate event to the outer button. You can stop propagation in onOk.

```javascript
onOk={(e) => {
  e.stopPropagation();
  this.setState({ isOpen1: false })
}}
```

Further reading https://github.com/facebook/react/issues/11387
