### ISSUE TITLE
The rowSelection of Table

### ISSUE THREAD

**Issue by arcsin1** [ant-design/ant-design#8741]
### What problem does this feature solve?
I hope  it will provide a configuration in order to make the  one of the rowSelection or some of the rowSelection can 'hidden' or 'show' . thanks!

### What does the proposed API look like?
hiddenSelectedRows: string[]

**Comment by yesmeck** [comment]
Use `rowClassName` to specify the hidden row, and hide it use css.

**Comment by arcsin1** [comment]
sorry, I describe it not clearly. I hope 'checkbox' can 'hidden' or 'show' （one of the rowSelection or some of the rowSelection）

**Comment by yesmeck** [comment]
`.hidden-row input { display: none }`

**Comment by arcsin1** [comment]
`.hidden-row .ant-checkbox-wrapper {display: none} `  it can work
