### ISSUE TITLE
use css-loader error when handling the antd/es/spin/style/index.css file, especially the line 84

### ISSUE THREAD

**Issue by lory-lu** [ant-design/ant-design#8742]
### Version
3.0.3

### Environment
antd: 3.0.3; react: 15.5.4; chrome: 63.0.3239.84

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
//  webpack.config.js
{
        loader: 'css-loader',
        options: {
          minimize: true || {
            // autoprefixer: {
            //   add: true,
            //   remove: true,
            //   browsers: ['last 2 versions'],
            // },
            discardComments: {
              removeAll : true,
            },
            discardUnused: false,
            mergeIdents: false,
            reduceIdents: false,
            safe: true,
            sourcemap: project.sourcemaps,
          }
        }
      }

### What is expected?
success

### What is actually happening?
in ./~/css-loader?{"minimize":true}!./~/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["/Users/jinglu/WORKSPACE/subject-management-tool/src/styles"]}!./~/less-loader/dist/cjs.js?{"sourceMap":true}!./~/antd/es/spin/style/index.css
Module build failed: 

  /* autoprefixer: off */
  filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
              ^
Unrecognised input
      in /Users/jinglu/WORKSPACE/subject-management-tool/node_modules/antd/es/spin/style/index.css (line 84, column 16)

**Comment by afc163** [comment]
Please make your issue readable. http://segmentfault.com/markdown

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4915#issuecomment-283176932
