### ISSUE TITLE
antd 3.x 版本 Upload 组件的 onChange 回调只执行一次

### ISSUE THREAD

**Issue by wb-chenlong** [ant-design/ant-design#8746]
### Version
3.0.0

### Environment
macOs，chrome 63，antd pro

### Reproduction link
[http://github.abssqr.cn/chenlong/abssqr-react/tree/master](http://github.abssqr.cn/chenlong/abssqr-react/tree/master)

### Steps to reproduce
- 环境：antd pro
- antd-version：3.0.0
- 重现：
	- Upload 组件，onChange 回调只执行了 uploading，无论成功还是失败，都没有执行 done 和 error。

![image](https://user-images.githubusercontent.com/14194437/34373730-0ddc1f8c-eb18-11e7-815c-a79d690c2ce2.png)
![image](https://user-images.githubusercontent.com/14194437/34373774-43f57fbe-eb18-11e7-9516-a4884638a58a.png)

### What is expected?
能执行相应的 uploading done error removed 等状态。

### What is actually happening?
只执行了 uploading 状态

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/2423

**Comment by liyun074** [comment]
批量上传文件时，每个文件分别调用了一次接口，请问如何只调用一次谢谢
