### ISSUE TITLE
CheckboxGroup is not vertical-align with form label

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#8749]
### Version
3.0.3

### Environment
Chrome,Ubunto

### Reproduction link
[https://codesandbox.io/s/zlkqmo9k4m](https://codesandbox.io/s/zlkqmo9k4m)

### Steps to reproduce
See the demo link

### What is expected?
CheckboxGroup is vertical-align middle with form label

### What is actually happening?
CheckboxGroup is not vertical-align with form label

**Comment by afc163** [comment]
Fixed in #8739
