### ISSUE TITLE
table怎么增加一列自增的序号

### ISSUE THREAD

**Issue by allces** [ant-design/ant-design#875]
table怎么增加一列自增的序号，谢谢

**Comment by bang88** [comment]
```js
render (text, record, index) {
 //TODO 
  return index
} 
```

http://ant.design/components/table/#column

**Comment by henryzp** [comment]
@fanjunzhi @bang88 @afc163 @ystarlongzi @benjycui 

上面的序号有问题吧？到了第二页又重新归0计算了？

我期望的是render里面，能有一个页码的参数，到第二页能变成11，到第三页能变成21，这样的。。

不然按照现在的处理方式，得手动监听页码的change事件，然后给data数组对象一个序列的变量

**Comment by bang88** [comment]
> 
```js
render (text, record, index) {
 //TODO 
  return currentPage + index
}
``` 

You can get `current page` from onPagination change event

**Comment by henryzp** [comment]
@bang88 ，这确实是个方案。。

但感觉有些挫，不能通过 render function 提供一个currentPage吗？

**Comment by bang88** [comment]
Sorry for confused. it should be `current * PageSize + index`

`current` start from 0

**Comment by henryzp** [comment]
yeah，it should be support pagation object，like this:

```
{
     pageSize: 10,
    currentPage: 1
}
```
