### ISSUE TITLE
ant-d 对fastJson生成的带自引用标志"$ref"的json有没有处理方法？

### ISSUE THREAD

**Issue by limeng32** [ant-design/ant-design#8755]
### What problem does this feature solve?
英文苦手请见谅。带自引用的json解析成对象后非常方便，比如我可以写出 person.dept.person[0]==person 这样的表达式，当时在kissy上找到了解决方案，想问下ant-d有没有解决方案呢？

### What does the proposed API look like?
jsonStr中含有 {"$ref" : "$.person[0]" } 型内容，使用JsonPlus.parse(jsonStr)后生成一个带有自相关特性的对象，如可以 person.dept.person[0]==person 。

**Comment by yesmeck** [comment]
antd 是组件库，你的问题跟  antd 没有关系。
