### ISSUE TITLE
Want to access current tag info inside onClose call

### ISSUE THREAD

**Issue by yubozhao** [ant-design/ant-design#8759]
### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/d20b4c910c09003f76fb71d00c53a8b99f78425b/components/tag/index.tsx#L48

Currently, there is no way to access current tag's info inside onClose all.  Would love to access it to do external stuff such as update local store and etc...

**Comment by yutingzhao1991** [comment]
```
const name = 'name';
<Tag onClick={() => {
  // here you can get you name
  console.log(name)
}}>{name}</Tag>
```
