### ISSUE TITLE
Pressing spacebar when focussed on a Switch component should NOT scroll the page.

### ISSUE THREAD

**Issue by mitchelldemler** [ant-design/ant-design#8761]
### Version
3.0.3

### Environment
Windows 10, Firefox latest, Chrome latest.

### Reproduction link
[https://ant.design/components/switch/](https://ant.design/components/switch/)

### Steps to reproduce
* Tab to a switch component so that it is in focus.
* Press spacebar.
* The switch component correctly toggles on/off, but the page has been scrolled down.

### What is expected?
The page should not scroll.

### What is actually happening?
The page is scrolling when spacebar is pressed.

**Comment by afc163** [comment]
Scrolling page is a default behavior of browser when pressing <kbd>whitespace</kbd>. You can try `event.stopPropagation()` in switch onKeyDown prop.

**Comment by mitchelldemler** [comment]
Fair enough. I figured it should copy the behaviour of `Checkbox`, but the workaround will do for now.
