### ISSUE TITLE
DefaultKey doesn't work on Tab that is inside a Modal

### ISSUE THREAD

**Issue by carendivinagracia22** [ant-design/ant-design#8762]
I have a Modal which has a Tab element. This Tabs has 3 TabPane, in which I set the first ("1") TabPane as the defaultActiveKey in Tabs. The Modal will be shown each time I clicked a button. But when I click the third("3") TabPane and closes the Modal, when I open the Modal, the third("3") TabPane is shown and not the first("1") TabPane or defaultActiveKey.

Please help. Thanks.

**Comment by webberwang** [comment]
I'm also getting this issue as well
