### ISSUE TITLE
Table  动态控制表格属性，文档样式或者其他问题导致页面变形

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#8764]
### Version
3.0.3

### Environment
操作系统 ：Mac macOS High Sierra 版本:10.13.2  浏览器：Google Chrome 版本 63.0.3239.84（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-dynamic-settings](https://ant.design/components/table-cn/#components-table-demo-dynamic-settings)

### Steps to reproduce
访问中文文档页面就能重现。

### What is expected?
同其他表格的呈现效果一致

### What is actually happening?
表格样式乱

**Comment by yesmeck** [comment]
@hqwlkj 说下重现步骤吧

**Comment by hqwlkj** [comment]
@yesmeck  访问此链接就能重现 https://ant.design/components/table-cn/#components-table-demo-dynamic-settings,

不知道是不是我的电脑 屏幕大小的问题，

电脑操作系统 ：MacBook Pro (Retina, 13-inch, Late 2013)

**Comment by yesmeck** [comment]
`Address` 列没有设置宽度的原因，是预期行为。
