### ISSUE TITLE
setFieldValue 是一个异步的方法 但是我的有些操作需要在这个方法之后

### ISSUE THREAD

**Issue by ybintian** [ant-design/ant-design#8771]
### What problem does this feature solve?
解决 setFieldValue 后置的一些操作问题

### What does the proposed API look like?
添加相应的callback

**Comment by afc163** [comment]
Please describe why you need it and what problem you want to resolve with it.

**Comment by ybintian** [comment]
![image](https://user-images.githubusercontent.com/22540492/34405073-2959ee54-ebec-11e7-86e0-70b7f4c0bd9b.png)
This is nested form.
when i need change one field value, to callback change another field value ， its will trouble。

就是 我想修改nestedform 里面的一个值， 之后会触发修改其他值的操作， 但是因为这是一个异步操作的方法，  所以导致两次 操作修改的值 有一个会被之前的覆盖掉。

**Comment by yutingzhao1991** [comment]
Why change one filed value cause another filed changed? Can you reproduce it on https://codesandbox.io?
