### ISSUE TITLE
Table column设置fixed：‘right’时渲染错乱

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#8772]
![1](https://user-images.githubusercontent.com/4537450/34404122-245261d4-ebe7-11e7-9093-b8ca0576b4ce.jpg)
### Version
3.0.3

### Environment
ant-pro最新版本

### Reproduction link
[https://github.com/ant-design/ant-design-pro](https://github.com/ant-design/ant-design-pro)

### Steps to reproduce
在table column中设置任意一列属性为fixed:'right'

### What is expected?
可正常显示

### What is actually happening?
显示混乱

**Comment by afc163** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/507615/34404160-4ce03ffe-ebe7-11e7-83df-d85a3ef41659.png">
