### ISSUE TITLE
“tabs component"   tabBarStyle  set 'font-size'  can't work

### ISSUE THREAD

**Issue by memoryza** [ant-design/ant-design#8773]
### Version
2.13.11

### Environment
mac 10.13.2（macos high sierra）and  safari \chrome

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)
### Steps to reproduce
https://ant.design/components/tabs-cn/
` <Tabs defaultActiveKey="1" onChange={callback} tabBarStyle={{fontSize: 22, 'font-size': '22px'}}>

    <TabPane tab="Tab 1" key="1">Content of Tab Pane 1</TabPane>

    <TabPane tab="Tab 2" key="2">Content of Tab Pane 2</TabPane>

    <TabPane tab="Tab 3" key="3">Content of Tab Pane 3</TabPane>

    </Tabs>
`

tabs  components can't work because 

`  &-nav-container { at  line 32  set 
             "font-size: @tabs-title-font-size;",
`

### What is expected?
cat set font-size effect tabbar font-size

### What is actually happening?
can't

**Comment by yesmeck** [comment]
You can override default style by css.

**Comment by Blet** [comment]
tabBarStyle doesn't work ，

**Comment by DavidJiah** [comment]
我想去掉tab的下划线
![image](https://user-images.githubusercontent.com/51731944/64064305-2607fe80-cc32-11e9-8471-f33aa06d9099.png)

**Comment by BeatriceHe** [comment]
> It bothered me for a few days！Finally I found a good solution , now I will share with you.
> 
> ```
> <TabPane tab={<span style={{fontSize:18}}>Tab1</span>} key="1">
> 	tab内容
> </TabPane>
> ```
> 
> You can also put an icon in the span tag like below:
> 
> ```
> <TabPane tab={<span style={{fontSize:18}}><Icon type="question-circle-o" />Tab1</span>} key="1">
> 	tab内容
> </TabPane>
> ```
> 
> If you can speak Chinese ,you can visit my CSDN blog [https://blog.csdn.net/jiangkai528/article/details/80052201]

Great help! Thanks!

**Comment by zhuoqinyue** [comment]
> 我想去掉tab的下划线
> ![image](https://user-images.githubusercontent.com/51731944/64064305-2607fe80-cc32-11e9-8471-f33aa06d9099.png)

你好, 請問這個效果你做到了嗎? 我也對這個沒辦法
