### ISSUE TITLE
logo旁边的圣诞老人的问题

### ISSUE THREAD

**Issue by amythos** [ant-design/ant-design#8774]
### Version
3.0.3

### Environment
mac 10.13.2 chrome/firefox

### Reproduction link
[http://ant-design.gitee.io/index-cn](http://ant-design.gitee.io/index-cn)

### Steps to reproduce
打开网页http://ant-design.gitee.io/index-cn 系统cpu会冲高

### What is expected?
期望可以暂停圣诞老人动画

### What is actually happening?
圣诞老人导致页面一直在重绘，消耗系统资源，会导致用户误认为antd控件性能不好

**Comment by afc163** [comment]
It would be taken off soon 🎅 🎅 🎅
