### ISSUE TITLE
Let nested table row can high light when hover on it .

### ISSUE THREAD

**Issue by Wang-Kai** [ant-design/ant-design#8775]
### What problem does this feature solve?
It make users read information from nested table rows easily .

### What does the proposed API look like?
I wish \<Table\> has an attribute call "highLightColor" . In normal , user can use it to determined which background color will be showed while hover event fire. When using nestedTable, this attribute can show different background color from parent table, it make users read information from nested table rows easily .

Now, it is a little terrible to read nestedTable information from rows .

eg:

![](http://owkd4slbl.bkt.clouddn.com/nestedTable.png)

**Comment by yesmeck** [comment]
You can remove default hover style by css, see my commit above.

**Comment by danibram** [comment]
@yesmeck that doesn`t work for me I dont no why... For the last version this worked for me, in .less format, adding the class `no-hover` on the nestedTable className. 
Hope it helps!

```
.no-hover {
    .ant-table-thead > tr.ant-table-row-hover > td,
    .ant-table-tbody > tr.ant-table-row-hover > td,
    .ant-table-thead > tr:hover > td,
    .ant-table-tbody > tr:hover > td,
    tr:hover > td {
        background: #fbfbfb;
    }
}

.ant-table-expanded-row {
    .ant-table-thead > tr > th {
        background: #f1f1f1;
    }

    .ant-table-tbody > tr > td {
        background: #fff;
    }
}
```

**Comment by Evangelione** [comment]
same
