### ISSUE TITLE
disabledHours in TimePicker

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#8776]
### Version
3.0.3

### Environment
not important

### Reproduction link
[http://not.important](http://not.important)

### Steps to reproduce
The `TimePicker` component has an option to disable the hours using `disabledHours` property.
For pure example, let's say that I want to disable even hours (like 2, 4, 6 etc.). How am I suppose to do that? I can't compare the time.

Don't really know if I explained it clearly. If not, then please go ahead and try my example above (with even hours being disabled) - you will see what I mean.

### What is expected?
The function should have `hour` attribute so I can compare it and return a specific boolean.

### What is actually happening?
Nothing to compare it with. The function doesn't have any argument.

**Comment by dengfuping** [comment]
@Ancinek There is no need to pass params to disabledHours function. You just need to return an array containing the hours you want to disable.
```
disabledHours={() => [1, 2, 3]}
```
![image](https://user-images.githubusercontent.com/14918822/34431752-98ed6fe6-ecac-11e7-892b-565ea9ceb8e7.png)

**Comment by Ancinek** [comment]
Thank you for the answer! It would be good to include this part in the docs!
Have a nice ending of 2017!

**Comment by yutingzhao1991** [comment]
@Ancinek welcome to make a pr help us improve docs.

Have a nice ending of 2017!
