### ISSUE TITLE
Upload组件：beforeUpload上传前检查问题

### ISSUE THREAD

**Issue by LynnHg** [ant-design/ant-design#8779]
### Version
3.0.3

### Environment
win7,chrome63.0.3239.84

### Reproduction link
[https://codepen.io/LynnHg/pen/YYZdRV](https://codepen.io/LynnHg/pen/YYZdRV)

### Steps to reproduce
handleBeforeUpload(file) {
    const sizeOk = file.size < 1024 * 300;
    const typeOk =
      file.type === 'image/jpeg' ||
      file.type === 'image/png' ||
      file.type === 'image/bmp' ||
      file.type === 'image/gif';

    if (!typeOk) {
      message.error('照片格式有误！');
    } else {
      if (!sizeOk) {
        message.error('照片大小超过300K！');
      }
    }

    return sizeOk && typeOk;
  }

### What is expected?
当上传错误格式的照片，提示格式错误，但不显示任何效果

### What is actually happening?
当上传错误格式的照片，提示格式错误，但界面上显示了"文件上传中"

**Comment by infeng** [comment]
这是因为`onChange`的回调方法有问题，不能这样写

**Comment by yutingzhao1991** [comment]
I think it's a problem, When `beforeUpload` retrun false, `file` object in callback `onChange` should give a right `status`.

**Comment by sponialdy** [comment]
and if use Promise, reject wont trigger `onChange`, but return false does!

**Comment by Cecilxx** [comment]
`
if (!typeOk) {
   message.error('照片格式有误！');
   return false
} else {
  if (!sizeOk) {
    message.error('照片大小超过300K！');
    return false
  }
}
return sizeOk && typeOk;
`

**Comment by afc163** [comment]
Duplicate of #8020

**Comment by iiiok** [comment]
beforeUpload (file) {
    const maxFileSize = 2;
    const isLtMax = file.size / 1024 / 1024 < maxFileSize;  

    return new Promise((resolve, reject) => {
      if(isLtMax) {
        reject(file);
      } else {
        resolve(file);
      }
    });
  };
This way will prevent the error file from adding to the fileList.
