### ISSUE TITLE
关于使用ant-design的一些疑问

### ISSUE THREAD

**Issue by xiongjiabin** [ant-design/ant-design#878]
这几天在使用ant-design，有几个疑问，现在的默认项目中产生一个index.html, 如果我后台有很多页面，是不是在index.html平行目录中生成，比如setting.html,  a.html, b.html来实现这些后台的功能？ 每个页面都是加载同样的左边，头部，以及自己的中间部分?

ant-design的官网好像有一个预先加载？

另外，如果我使用ajax的操作去获取服务器端的数据，是不是我自己选择jquery这样的类库加到里面去操作？

官方有没有一些最好的建议！

非常感谢！

**Comment by afc163** [comment]
上述问题，你可以学习一下 react-router、flux、redux、relay 这些库和概念，也可以看看一些成熟的项目脚手架，如：https://github.com/erikras/react-redux-universal-hot-example https://github.com/tj/frontend-boilerplate

也建议你到 React 论坛提问，会获得更好的效果，如 http://reactjs.cn/
