### ISSUE TITLE
日历插件-卡片模式

### ISSUE THREAD

**Issue by code-lynn** [ant-design/ant-design#8781]
### Version
3.0.3

### Environment
win7--本地时间29号

### Reproduction link
[https://ant.design/components/calendar-cn/](https://ant.design/components/calendar-cn/)

### Steps to reproduce
选择月份  

### What is expected?
选中其他月份不选中 29号

### What is actually happening?
比如今天是29号，选择其他月份时 29号是选中状态 造成误解，

---
用value赋值时也是这样问题

**Comment by dengfuping** [comment]
@code-lynn The default day every month is the day what you select finally. It's to avoid the situation that no day is selected.

**Comment by yutingzhao1991** [comment]
It by design, maybe you can update the day manually when month changed.
