### ISSUE TITLE
List组件 在ie下的只兼容9，但是会报foreach的错

### ISSUE THREAD

**Issue by RRRRROOOO** [ant-design/ant-design#8784]
### Version
3.0.3

### Environment
ie edge

### Reproduction link
[https://ant.design/components/list-cn/](https://ant.design/components/list-cn/)

### Steps to reproduce
使用ie浏览器打开连接， 有头像的list显示不正常，可能是flex 不兼容， ie9、10的环境是正常显示 ，但是foreach报错， ie11 无法正常显示，foreach不报错

with use ie，the list is not normal css，and ie9、10 foreach warring， ie11（edge）css is Insanity

### What is expected?
能够兼容ie9 以上的版本，都能够不报错吧，正常显示

Can be compatible with more than IE9 version, can not report the wrong, normal display

**Comment by yesmeck** [comment]
> 对于 IE 系列浏览器，需要提供 es5-shim 和 es6-shim 等 Polyfills 的支持。

https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by johnnychen** [comment]
antd官方组件demo里也有这个问题，看样子跟polyfills没关系

**Comment by johnnychen** [comment]
## 关于IE报错 - antd官网报错

forEach报错应该是antd官方网站的报错，跟antd本身没有关系。具体是调用了NodeList的forEach方法，但这个方法目前IE不支持

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

![image](https://user-images.githubusercontent.com/1297278/34460194-e8652b58-ee42-11e7-8f67-98c2040777ad.png)

## 关于IE报错 - 开发环境报错

我猜你开发环境IE下面的报错，是因为roadhog的缘故，参见：https://github.com/sorrycc/roadhog/issues/497

## 最后

LIST样式兼容性问题是存在的，但根IE报错应该没必然的关系，只不过IE报错不方便你开发环境下调试排查。

**Comment by johnnychen** [comment]
@afc163 哥，css兼容性问题还没修复，别急着close掉呃

**Comment by johnnychen** [comment]
```html
 <style type="text/css">
    .ant-list-item .ant-list-item-meta-avatar, .ant-list-item .ant-list-item-meta-content{
      flex: none;
      -ms-flex: none;
    }
  </style>
```

我遇到的场景，先这么临时解决了

但全局修改很暴力，另外，没有测所有用例的List, 我只测了自己的场景, 比较简单

![image](https://user-images.githubusercontent.com/1297278/34460599-0c994d32-ee4e-11e7-8102-1ccc0ce48152.png)

**Comment by benjycui** [comment]
@afc163 close now?

**Comment by johnnychen** [comment]
@benjycui 样式问题还没解决，怎么close呢。。

**Comment by johnnychen** [comment]
@benjycui 你可以自己到https://ant.design/components/list-cn/，看看IE11的效果

**Comment by nikogu** [comment]
@johnnychen 这个我稍后修复

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design/pull/8798

多谢反馈。

原因是在 ie11 下，如果两个并排布局都定义了 `flex` 属性，则 `flex-grow: 0` 会被压缩（即使小于本身宽度），处理办法就是只定义 `flex-grow: 1` 的一方，另一方不定义 `flex 属性即可`，所有浏览器都会按照默认本身的宽度来处理。
