### ISSUE TITLE
建议增加的组件

### ISSUE THREAD

**Issue by BackWorld** [ant-design/ant-design#879]
1.类似以于semantic-ui的图片鼠标经过/移出时更换图片或显示内容的图片组件：
http://www.semantic-ui-cn.com/elements/reveal.php
2.分割条组件。
3.评论组件：【整体CommentBox】
ps: 如果你们也能加入这样的组件会更好。

**Comment by JonneyYan** [comment]
@BackWorld ant-design更适合做后台页面

**Comment by afc163** [comment]
1. 暂时没有这个需求。
2. 这个作为有点浅。简单的目前可以用 `<span className="ant-divider"></span>`。
3. 这个太业务了，建议自行封装。

非常感谢建议！
