### ISSUE TITLE
Transfer render Item 是否能支持"隐藏" 在没有搜索框的情况下

### ISSUE THREAD

**Issue by wangyazhen** [ant-design/ant-design#8792]
### What problem does this feature solve?
**Sorry, my English is poor**

我有一个业务场景---
1. 左侧框根据一个树的节点获取的数据进行变化，比如有10条
2. 我选择了左侧的两个点击`>`添加到了右边 - 右边有2条
3. 此时我切换树的节点获取新的结果-15条，展示到左边需要显示15条
4. 此时transfer的`DataSource`已经改变， 右侧也就不能保持2条已选中的结果（业务场景是需要保持的）

我的想法是`transfer`的`dataSource`  `contact` 每次树的新结果，也就是这个list 保留了所有数据

左侧渲染的时候我想在`render`里隐藏一些不符合条件的`item` 

我的做法是`return null` 可是我看到不是我期望的结果

我的代码片段:
```
<Transfer
          rowKey={record => record.id}
          dataSource={paramsetList}
          titles={['待选参数', '已选参数']}
          targetKeys={state.targetKeys}
          selectedKeys={state.selectedKeys}
          onChange={this.handleChange}
          onSelectChange={this.handleSelectChange}
          listStyle={{width: '40%', height: 350 }}
          render={item => {
            if (item.paramsetName === paramsetName) {
              return item.paramName
            } else {
              return null
            }
          }}
        />
```

实际的渲染结果是:
```
<div class="LazyLoad is-visible" style="height: 32px;">
<li class="ant-transfer-list-content-item" title="test">
<label class="ant-checkbox-wrapper">
<span class="ant-checkbox">
<input type="checkbox" class="ant-checkbox-input" value="on">
<span class="ant-checkbox-inner"></span></span>
</label>
<span>
<div class="hide___2Ky_E"></div></span>
</li>
</div>
```
因为框架要渲染左侧的`checkbox`框，所以不能自定义整个`item`

我提交这个`issues`的目的是：
1. 根据我的业务场景，我的想法或做法是否有错误----  我错误的使用了框架的一些功能
2. 我希望`Transfer` 能提供一个`hidden item` 或者说 `filter Item` 这样类似的接口支持

非常感谢能提供任何建议。

### What does the proposed API look like?
期望 code:
```
<Transfer
          rowKey={record => record.id}
          dataSource={paramsetList}
          titles={['待选参数', '已选参数']}
          targetKeys={state.targetKeys}
          selectedKeys={state.selectedKeys}
          onChange={this.handleChange}
          onSelectChange={this.handleSelectChange}
          listStyle={{width: '40%', height: 350 }}
          filterItem={item => item.paramsetName === paramsetName}
        />
```

**Comment by afc163** [comment]
There is a `filterOption` you can try out. https://ant.design/components/transfer/#API

**Comment by afc163** [comment]
> 我的想法是transfer的dataSource contact 每次树的新结果，也就是这个list 保留了所有数据，左侧渲染的时候我想在render里隐藏一些不符合条件的item

建议这么做：transfer 的 dataSource 在切换时，concat targetKeys 里的数据（右侧的数据）。这样 dataSource 始终保留当前树节点的数据（待选）和过去已选择的数据。

**Comment by wangyazhen** [comment]
谢谢 你是对的  元旦快乐  祝项目越来越好 ^_^
