### ISSUE TITLE
3.10 里 Modal的 maskClosable 属性默认值不对

### ISSUE THREAD

**Issue by xd19831203** [ant-design/ant-design#8794]
### Version
3.1.0

### Environment
chrome 63

### Reproduction link
[https://codesandbox.io/s/6x119jkzn3](https://codesandbox.io/s/6x119jkzn3)

### Steps to reproduce
不设maskClosable  属性时 

### What is expected?
-

### What is actually happening?
-

---
3.10 里 Modal的 maskClosable 属性默认值不对

**Comment by dengfuping** [comment]
@xd19831203 In fact, click event on  mask is to call the onCancel function when maskClosable is true. So if you set visible false in onCancel function, everything will be right. For further knowledge, you can reference [this source code fragment](https://github.com/ant-design/ant-design/blob/6e6cda5b2e13af383fe1e617bf01345a3541eb8a/components/modal/Modal.tsx#L24).

**Comment by xd19831203** [comment]
因为我记得官方中文版手册里明确这个属性是默认false

**Comment by afc163** [comment]
https://ant.design/components/modal/#API

**Comment by xd19831203** [comment]
我提这个BUG的时候，中文版的手册上写的还是false
