### ISSUE TITLE
Incorrect TypeScript definition for Menu Component defaultProps

### ISSUE THREAD

**Issue by jmca** [ant-design/ant-design#8796]
### Version
3.1.0

### Environment
Chrome

### Reproduction link
[https://codesandbox.io/s/o7lxqxy7xz](https://codesandbox.io/s/o7lxqxy7xz)

### Steps to reproduce
Version: 3.1.0

`Menu` Component's `defaultProps` is defined as:
```
static defaultProps: {
    theme: string;
    ...
};
```
But `MenuProps` interface is expecting:
```
theme?: 'light' | 'dark';
```

### What is expected?
No error

### What is actually happening?
This is causing TypeScript compiler to throw:
```
Error:(87, 25) TS2345: Argument of type 'typeof Menu' is not assignable to parameter of type 'string | ComponentClass<MenuProps> | StatelessComponent<MenuProps>'.
  Type 'typeof Menu' is not assignable to type 'StatelessComponent<MenuProps>'.
    Types of property 'defaultProps' are incompatible.
      Type '{ prefixCls: string; className: string; theme: string; }' is not assignable to type 'Partial<MenuProps>'.
        Types of property 'theme' are incompatible.
          Type 'string' is not assignable to type '"light" | "dark"'.
```

---
This can be corrected by changing `defaultProps` to:
```
static defaultProps: {
    theme: 'light' | 'dark';
    ...
};
```

**Comment by jmca** [comment]
Similar issue with `Modal` component:

```
export interface ModalFuncProps {
    ...
    okType?: ButtonType;
}

static defaultProps: {
    ...
    okType: string;
};
```

**Comment by dengfuping** [comment]
@jmca It was fixed in the latest version. Please upgrade your Antd. Further to [the Menu code fragment](https://github.com/ant-design/ant-design/blob/6e6cda5b2e13af383fe1e617bf01345a3541eb8a/components/menu/index.tsx#L61) and [the Modal code fragment](https://github.com/ant-design/ant-design/blob/6e6cda5b2e13af383fe1e617bf01345a3541eb8a/components/modal/Modal.tsx#L91)

**Comment by jmca** [comment]
Hm, it looks okay in this repo's source code. When grabbing the lib (via `yarn` in my case), the offending declaration is located at:
`./node_modules/antd/lib/modal/Modal.d.ts` (or `./node_modules/antd/es/modal/Modal.d.ts`)

I used `<--------` to denote the areas below:
```
/// <reference types="react" />
import * as React from 'react';
import { ButtonType } from '../button/button';
export interface ModalProps {
    /** 对话框是否可见*/
    visible?: boolean;
    /** 确定按钮 loading*/
    confirmLoading?: boolean;
    /** 标题*/
    title?: React.ReactNode | string;
    /** 是否显示右上角的关闭按钮*/
    closable?: boolean;
    /** 点击确定回调*/
    onOk?: (e: React.MouseEvent<any>) => void;
    /** 点击模态框右上角叉、取消按钮、Props.maskClosable 值为 true 时的遮罩层或键盘按下 Esc 时的回调*/
    onCancel?: (e: React.MouseEvent<any>) => void;
    afterClose?: () => void;
    /** 宽度*/
    width?: string | number;
    /** 底部内容*/
    footer?: React.ReactNode;
    /** 确认按钮文字*/
    okText?: string;
    /** 确认按钮类型*/
    okType?: ButtonType;     <--------LOOKS GOOD
    /** 取消按钮文字*/
    cancelText?: string;
    /** 点击蒙层是否允许关闭*/
    maskClosable?: boolean;
    destroyOnClose?: boolean;
    style?: React.CSSProperties;
    wrapClassName?: string;
    maskTransitionName?: string;
    transitionName?: string;
    className?: string;
    getContainer?: (instance: React.ReactInstance) => HTMLElement;
    zIndex?: number;
    bodyStyle?: React.CSSProperties;
    maskStyle?: React.CSSProperties;
    mask?: boolean;
}
export interface ModalFuncProps {
    prefixCls?: string;
    className?: string;
    visible?: boolean;
    title?: React.ReactNode;
    content?: React.ReactNode;
    onOk?: (...args: any[]) => any | PromiseLike<any>;
    onCancel?: (...args: any[]) => any | PromiseLike<any>;
    width?: string | number;
    iconClassName?: string;
    okText?: string;
    okType?: ButtonType;     <--------LOOKS GOOD
    cancelText?: string;
    iconType?: string;
    maskClosable?: boolean;
    zIndex?: number;
    okCancel?: boolean;
    style?: React.CSSProperties;
    type?: string;
}
export declare type ModalFunc = (props: ModalFuncProps) => {
    destroy: () => void;
};
export interface ModalLocale {
    okText: string;
    cancelText: string;
    justOkText: string;
}
export default class Modal extends React.Component<ModalProps, {}> {
    static info: ModalFunc;
    static success: ModalFunc;
    static error: ModalFunc;
    static warn: ModalFunc;
    static warning: ModalFunc;
    static confirm: ModalFunc;
    static defaultProps: {
        prefixCls: string;
        width: number;
        transitionName: string;
        maskTransitionName: string;
        confirmLoading: boolean;
        visible: boolean;
        okType: string;     <--------THROWS TS ERROR
    };
    static propTypes: {
        prefixCls: any;
        onOk: any;
        onCancel: any;
        okText: any;
        cancelText: any;
        width: any;
        confirmLoading: any;
        visible: any;
        align: any;
        footer: any;
        title: any;
        closable: any;
    };
    handleCancel: (e: React.MouseEvent<HTMLButtonElement>) => void;
    handleOk: (e: React.MouseEvent<HTMLButtonElement>) => void;
    componentDidMount(): void;
    renderFooter: (locale: ModalLocale) => JSX.Element;
    render(): JSX.Element;
}
```

Similar case with Menu component at `./node_modules/antd/lib/menu/index.d.ts` regarding the `theme` property.

I removed `node_modules` and `yarn.lock` and reinstalled via `yarn` just in case something went sideways. But the result is the same. It looks like the issues is happening during the distribution process when TypeScript is extracting definition files.

I'm using **tsc Version 2.6.2**

**Comment by jmca** [comment]
@dengfuping I'm thinking it's an issue with TS Inference. Here's a quick page on it:
https://basarat.gitbooks.io/typescript/docs/types/literal-types.html

Referring to https://github.com/ant-design/ant-design/blob/c14b13d4acbf0c51f0ef67a93270516ac0572a0a/components/modal/Modal.tsx#L98
TS is inferring that this prop should be a `string` type.

The solution could possibly be to just cast the prop:
```
static defaultProps = {
    ...
    okType: 'primary' as ButtonType,
};
```
Then the extracted `.d.ts` files should infer the correct type (`ButtonType` instead of `string`).

**Comment by dengfuping** [comment]
@jmca Thanks for your critical opinion. Welcome PR.

**Comment by plrthink** [comment]
also found this issue with `Popover` component whose `placement` props is just string in the `d.ts`, which could be fixed by cast as `as TooltipPlacement`

**Comment by GauravV-02** [comment]
Hi @jmca can i work  on this,

**Comment by jmca** [comment]
@GauravV-02 Sure, it's all yours.

**Comment by jmca** [comment]
https://github.com/ant-design/ant-design/pull/8820

**Comment by yesmeck** [comment]
Related #7965

**Comment by yesmeck** [comment]
Can anyone create a reproduce repo?

**Comment by eddiemoore** [comment]
This seems to happen with a lot of components. Including (but not limited to) `Upload`, `Form`, `Progress` and `Spin`. They all have an issue with the default props and the main prop types not matching properly.

**Comment by yesmeck** [comment]
@eddiemoore PRs welcome.

**Comment by eddiemoore** [comment]
Will see if I can find some time to submit a PR
