### ISSUE TITLE
Broken link for example related to "getPopupContainer" in "Select" component docs

### ISSUE THREAD

**Issue by arorayash** [ant-design/ant-design#8797]
### Version
3.1.0

### Environment
Google Chrome, Firefox

### Reproduction link
[https://ant.design/components/select/#Select-props](https://ant.design/components/select/#Select-props)

### Steps to reproduce
The example redirects to "https://codesandbox.io/s/4j168r7jw01" which doesn't exist.

### What is expected?
The link should redirect to the Sandbox page with the example code.

### What is actually happening?
The sandbox instance doesn't exist.

**Comment by afc163** [comment]
Thx for reporting it.
