### ISSUE TITLE
There is no active underline when only one TabPane in Tabs component 

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design#8801]
### Version
3.1.0

### Environment
mac 10.13.2 chrome

### Reproduction link
[https://codepen.io/motorfu/pen/qpjzQK](https://codepen.io/motorfu/pen/qpjzQK)

### Steps to reproduce
when only one TabPane in Tabs component .

### What is expected?
active TabPane have underline when only one TabPane in Tabs component.

### What is actually happening?
just title is highlighted when only one TabPane in Tabs component.

**Comment by valleykid** [comment]
Please use the hack temporarily as follow:
```css
.ant-tabs-ink-bar-animated {
  min-width: 68px;
}
```
