### ISSUE TITLE
🐞 修复 Table 在设置 size=small 的情况下出现多余 padding 的问题。#8724,这个bug没有完全修复

### ISSUE THREAD

**Issue by chowsource** [ant-design/ant-design#8802]
### Version
3.1.0

### Environment
react16 

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
换到3.0.3的版本就没有这个问题,3.1.0就出现这个问题

### What is expected?
3.0.3版本是OK的,3.1.0反而出现了bug

### What is actually happening?
不应该有空白padding

---
看截图
![image](https://user-images.githubusercontent.com/5119971/34508334-08c54148-f079-11e7-8d9f-3fc1ffa204a3.png)

**Comment by afc163** [comment]
These padding is by designed.
