### ISSUE TITLE
 Table header and table body can't aligned

### ISSUE THREAD

**Issue by happysearch** [ant-design/ant-design#8803]
### Version
3.1.0

### Environment
Windows 10,Chrome 63,FireFox 57,react-dom 16.2.0,

### Reproduction link
[https://codesandbox.io/s/14n6r74lj7](https://codesandbox.io/s/14n6r74lj7)

### Steps to reproduce
After setting up Y attribute of scroll in table component,  the columns of table header and table body can't go aligned when   scroll bar appeared.

### What is expected?
 Table header and table body can aligned.

### What is actually happening?
 Table header and table body can't aligned.

**Comment by afc163** [comment]
#8078
