### ISSUE TITLE
日期选择框的WeekPicker 设置可选择范围后  不可选择部分 颜色没有变灰

### ISSUE THREAD

**Issue by shicunyong** [ant-design/ant-design#8804]
### Version
3.1.0

### Environment
谷歌浏览器

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
日期选择框的WeekPicker 设置可选择范围后  不可选择部分 颜色没有变灰， 仅仅是点击没有效果

### What is expected?
日期选择框的WeekPicker 设置可选择范围后  不可选择部分 颜色变灰

### What is actually happening?
日期选择框的WeekPicker 设置可选择范围后  不可选择部分 颜色没有变灰

---
weekPicker的bug 所有场景都有

**Comment by shicunyong** [comment]
日期选择框的WeekPicker 设置可选择范围后  不可选择部分 颜色没有变灰

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us: http://u.ant.design/codesandbox-repro

**Comment by gpzjyw** [comment]
A example is like this: https://codesandbox.io/s/qv9mn1k009. 
I have set the disabledDate props in WeekPicker. But the disabledDate is not set ash.
