### ISSUE TITLE
Table组件不同大小样式Less文件中并没有使用公共变量

### ISSUE THREAD

**Issue by ryanhoho** [ant-design/ant-design#8805]
### What problem does this feature solve?
在视图定义更加紧凑的页面时，调整了@padding-xs @table-padding-vertical变量后发现并未生效，查看源码后发现表格的size.less文件中padding直接写死了padding大小，并未使用公共变量！

### What does the proposed API look like?
若有可能，此处应当使用公共变量？

**Comment by yesmeck** [comment]
@ryanhoho Could you open a PR?
