### ISSUE TITLE
antd setFieldsValue with nested fields not work

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#8806]
### Version
3.0.2

### Environment
node -v 6.1.0

### Reproduction link
[https://codesandbox.io/s/yqo8j67n2z](https://codesandbox.io/s/yqo8j67n2z)

### Steps to reproduce
https://codesandbox.io/s/yqo8j67n2z

### What is expected?
can change the drivers phone.

### What is actually happening?
no change.

I want to known,  it's a known issue?or because of my code?

**Comment by afc163** [comment]
I think it works well: https://codesandbox.io/s/nr8jn3r95l

**Comment by didmehh** [comment]
i had change.
please see [https://codesandbox.io/s/00ox4m498p](https://codesandbox.io/s/00ox4m498p)
your mean's was `antd` unsupport that way?

**Comment by afc163** [comment]
`drivers[0][phone]` is not a valid syntax for https://lodash.com/docs/4.17.4#get

**Comment by didmehh** [comment]
thank you very much.
that was work https://codesandbox.io/s/00ox4m498p

**Comment by hosembafer** [comment]
I have simple add/update/remove nested array of objects, and can't realize remove.

Adding
```js
getFieldDecorator(`drivers[${values.length}].name`, {
    initialValue: "Alex",
});

getFieldDecorator(`drivers[${values.length}].age`, {
    initialValue: 35,
});
```

Removing 
```js
let values = getFieldValue('drivers');
values = values.filter((item, index) => {
    return index !== k;
});

setFieldsValue({
    drivers: values,
});
```

But last one has no effect, drivers count is not changing.

In examples of Component:Form I can find only array of primitive values and only realization with driversKeys helper array.

**Comment by hosembafer** [comment]
May be related to https://github.com/react-component/form/pull/48

**Comment by hosembafer** [comment]
@daydayuphuan , it seems impossible, we will discuss with a team about migration from antd forms to redux-form or @jaredpalmer/formik, but still, we will use antd form components for the view(because they are powerful we have decorated it with CSS), but not antd form HOC.

**Comment by hosembafer** [comment]
@daydayuphuan Right now I'm in love with formik, and after stress test I can write you about results.
