### ISSUE TITLE
anchor won't work when anchor/link's href is a complete link (/somepath#id)

### ISSUE THREAD

**Issue by jjzhangg** [ant-design/ant-design#8808]
### Version
3.1.0

### Environment
any

### Reproduction link
[https://codesandbox.io/s/o97wp51vmq](https://codesandbox.io/s/o97wp51vmq)

### Steps to reproduce
just scroll page

### What is expected?
some link of the anchor being active

### What is actually happening?
none link being active

---
We introduced base tag in our html
`<head><base href="/somebase">...<head>`
and with this setting, every #id, will be translated by browser into /somebase#id, not document.href#id. As a result, we need to specify anchor/link href as complete link. 
But the current code of anchor, take href as #id by default, and will not work with a complete link like '/hello/world#id'.

**Comment by dengfuping** [comment]
@jjzhangg The problem exists indeed when opened in codesandbox. But it's all right in codepen and riddle. How about your local env？
