### ISSUE TITLE
There are online resources in the style

### ISSUE THREAD

**Issue by hanangjie** [ant-design/ant-design#8810]
### Version
3.1.0

### Environment
window7

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less)

### Steps to reproduce
```
// ICONFONT
@iconfont-css-prefix    : anticon;
@icon-url               : "https://at.alicdn.com/t/font_148784_r2qo40wrmaolayvi";

```

### What is expected?
Reference local resources

### What is actually happening?
Reference online Resources

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
