### ISSUE TITLE
使用babel-plugin-import样式错误

### ISSUE THREAD

**Issue by jdongdong** [ant-design/ant-design#8812]
### Version
3.1.0

### Environment
win7
babel-plugin-import：1.6.3
roadhog：1.3.3

### Reproduction link
无

### Steps to reproduce
配置babel-plugin-import为["import", { "libraryName": "antd", libraryDirectory: "es", "style": true }]时，字体显示异常，部分图标无法显示，如下图：
![image](https://user-images.githubusercontent.com/11850305/34513240-42f511d0-f0a2-11e7-9990-d035ab7f3211.png)
配置成["import", { "libraryName": "antd", libraryDirectory: "es", "style": ‘css'}]时正常，如下图：
![image](https://user-images.githubusercontent.com/11850305/34513255-62db2a20-f0a2-11e7-8a0d-d6491200145e.png)

### What is expected?
字体、图标显示正常

### What is actually happening?
字体、图标显示不正常

**Comment by dengfuping** [comment]
@jdongdong Just follow the docs and add the config
```
["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
```
Why did you set "style" to "true".

**Comment by jdongdong** [comment]
I just found that the ant-design-pro is configured with `"style": true`

**Comment by yesmeck** [comment]
@jdongdong 提供下能重现的 repo 吧。

**Comment by jdongdong** [comment]
找到问题原因了，我现在是使用的roadhog，同时我又自建了一个webpack.config.js，这种情况设置`"style": true`就会出现问题

**Comment by jdongdong** [comment]
经排查发现是设置了theme的@font-family和@icon-url引起的
[babel-plugin-import样式问题.zip](https://github.com/ant-design/ant-design/files/1605477/babel-plugin-import.zip)

**Comment by yesmeck** [comment]
你的字体 `public` 放错位置了，应该放在项目根目录下。

**Comment by jdongdong** [comment]
出来了，thks
