### ISSUE TITLE
DatePicker汉化问题

### ISSUE THREAD

**Issue by Lxg1582** [ant-design/ant-design#8816]
### Version
3.1.0

### Environment
Chrome

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
最新版本3.1.0的DatePicker使用LocaleProvider这个进行中文汉化，结果是只有日期选择器的按钮的字汉化了，但是月、星期天没有汉化，按文档中所说的使用defaultValue传入的moment对象进行汉化，如果传moment对象是没问题的，但是我默认情况下是没有moment对象的，只是显示“请选择时间”这个文案，我折腾了几个小时。实在不知道该怎么解决，也许是我的方法有问题，如果是你们bug的话，希望能改一下

### What is expected?
汉化能成功

### What is actually happening?
汉化成功不了

**Comment by afc163** [comment]
`moment.locale('zh-CN')`

**Comment by Cecilxx** [comment]
![image](https://user-images.githubusercontent.com/20623617/34555884-07e82c8a-f16f-11e7-88e6-6fcea5709492.png)
