### ISSUE TITLE
how forbid esc close modal

### ISSUE THREAD

**Issue by dotequiet** [ant-design/ant-design#8818]
### Version
3.1.0

### Environment
develop

### Reproduction link
[https://ant.design/components/modal-cn/#components-modal-demo-manual](https://ant.design/components/modal-cn/#components-modal-demo-manual)

### Steps to reproduce
esc close modal

### What is expected?
controll esc close modal, if need esc close modal close else not close modal

### What is actually happening?
can't controll esc close modal

**Comment by dengfuping** [comment]
@dotequiet The key event of "Esc" calls the onCancel function by default. And there is no option to forbid it.

**Comment by benjycui** [comment]
Just control `Modal[visible]`, think in React, instead Ext.js

**Comment by afc163** [comment]
We can pass the `keyboard` config into `Modal.confirm`: https://github.com/ant-design/ant-design/blob/455b9e40e0a650afe08297eaffd62b322190f187/components/modal/confirm.tsx#L46-L57

**Comment by dotequiet** [comment]
@afc163 controll onCancel is ok, but cancel btn and x is invalid
