### ISSUE TITLE
The vertical spacing between two formItems is large, how to personlize it?

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design#8829]
### Version
3.0.0

### Environment
macOs

### What is expected?
personlize vertical spacing as I expect

### What is actually happening?
default spacing

**Comment by afc163** [comment]
Please use bug report template at http://new-issue.ant.design/

**Comment by hudawen** [comment]
![image](https://user-images.githubusercontent.com/9697127/34592380-7bd87098-f1fe-11e7-81f9-d7050fe26721.png)
As the picture shows, the default vertical spacing between Name and Nickname(two formItems) is large for me, I just wonder if there is a way to narrow the spacing.

**Comment by afc163** [comment]
Try `<Form.Item style={{ marginBottom: 12 }}>`

**Comment by hudawen** [comment]
@afc163 By the way, a formItem always occupy one line even when I set Form.layout="inline", how can I make two formItems in the same line besides using <Row> and <Col>?

**Comment by tigersaggy** [comment]
In my case, i wanted to reduce the default space between Rows, and marginBottom was not helpful (since it adds more space). So as a workaround for now, i have set height on column to make it work.
Example : <Col style={{ height: '40px' }} span={6}>

**Comment by SergeyVolynkin** [comment]
As a quick-fix you can use:
```
.ant-form-item {
  margin-bottom: 8px !important;
}
```
