### ISSUE TITLE
Can't get e.target.className from the Checkbox added className property

### ISSUE THREAD

**Issue by CeleKing** [ant-design/ant-design#8834]
### What problem does this feature solve?
get className from CheckBox onClick event(e.target.className), so can easily bind onClick event in constructor and don't transfer extra params in new onClick event in Component !

### What does the proposed API look like?
className: [string]

**Comment by yesmeck** [comment]
**What problem does this feature solve?**

**Comment by CeleKing** [comment]
Actually, I think the problem is if I add a className to CheckBox , but i can't get the className in e.target.className, it's an empty string.

**Comment by afc163** [comment]
> get the className in e.target.className

You don't need this, the className is added by youself so you should be able to get it easily.
