### ISSUE TITLE
Table onRow Event multiple triggered

### ISSUE THREAD

**Issue by dogbutcat** [ant-design/ant-design#8835]
### Version
3.1.0

### Environment
macos 10.12.6, chrome 63

### Reproduction link
[codepen](https://codepen.io/dogbutcat/pen/wprmrR)

### Steps to reproduce
My component which using Table component in 2.x versions, when I migrate to 3.x versions, console print out such error```webpack-internal:///15:49 Warning: onRowClick is deprecated, please use onRow instead.```, when I replace onRowClick with onRow event, my Component BREAK DOWN, as I use ```setState``` with onRowClick[onRow]

### What is expected?
event should be triggered when I click table item

### What is actually happening?
it triggered when each line rendered

---
when I look into source code in Table component, https://github.com/ant-design/ant-design/blob/1eff817b9ada2169f0ddeb5e2e9fd2df88270134/components/table/Table.tsx#L218, why you execute props onRow event, cuz used in onRowClick is bind event, or maybe you have changed the usage purpose of this function

**Comment by dengfuping** [comment]
@dogbutcat In version  3.x, onRow is to set props on per row, not the same as onRowClick in version 2.x. So you can't replace onRowClick with onRow.

**Comment by dogbutcat** [comment]
@dengfuping Many thanks, I've confused by the Warning, seemed event has moved to rowSelection part.

**Comment by TimKraemer** [comment]
with `onRowClick` deprecated, how would I achieve a row-selection by clicking somewhere on the row?
Currently I'm doing it like this:
```
<Table onRowClick={cylinder => this.changeSelection()} />
```

**Comment by dogbutcat** [comment]
@TimKraemer ,as @dengfuping said, the ```onRow``` event is to set props for each row, it means the work of ```onRow``` is changed, and you need to pass ```rowSelection```[Object] props to deal with select events. You can checkout my modified [codepen](https://codepen.io/dogbutcat/pen/wprmrR ),OR check the document this part: https://ant.design/components/table/#rowSelection. Hope this helps. Also I think they should change the warning description as this props function totally changed, not instead.

**Comment by cllgeek** [comment]
@dogbutcat it dont's work , still have this problem

**Comment by dogbutcat** [comment]
@cllgeek en....Best to provide your simple reproduce example or component, whether had checked the codepen I fixed above: https://codepen.io/dogbutcat/pen/wprmrR. As it works fine for me now.

**Comment by aaronplanell** [comment]
Hello everybody,

First of all, thanks @dogbutcat for your full explanation. I agree with you: the warning description must be changed, because it seems that you must replace _onRowClick_ by _onRow_ and they don't do the same. In fact, as I am concerned, there is no similar functionality in v3.0... You cannot click to an entire row and give it the same callback, you must create a _rowSelection_ and this means that a column with checkboxes will appear and you can click any checkbox, and it's not the same :cry: 

Any idea? Why deprecate _onRowClick_? :thinking: 

Thanks!

**Comment by yesmeck** [comment]
@aaronplanell You can pass arbitrary props to `<tr />` through `onRow` prop, so we don't use encourage use `onRowClick` and other `onRowWhateverEvent` any more. See more details in our 3.0 release log. https://ant.design/changelog

**Comment by aaronplanell** [comment]
Perfect!!! 

It works with: 
```
onRow={(record) => ({
    onClick: () => { myCallBackThatReceivesTheID(record.key); }
})}
```

Thanks a lot @yesmeck !!!

**Comment by springxiege** [comment]
At this point, there is a click event in the row ,at the time, there is a button in the row, and there is also a lick event. When I click the button, the two events will be triggered. and in fact, I just want to trigger the event of the button, do not trigger event of the row.

**Comment by dogbutcat** [comment]
@springxiege if you work with method @aaronplanell describe, you **MUST** stopPropagation in your click event, if you still confused with what I describe, check codepen in reproduction link above. Hope it helps!

**Comment by springxiege** [comment]
@dogbutcat I have resolved it by what you describe, Thank you very much!

**Comment by cllgeek** [comment]
@dogbutcat  Thank you very much

**Comment by lstak** [comment]
The following example may help to use a v2 style onRowClick function with v3 style onRow
```
 <Table
        onRow={(record, index) => ({
          onClick: (event) => { onRowClick(record, index, event) } 
        })}
       ....
```

**Comment by mikaelascorn** [comment]
Is there a way to highlight the row once that row is selected?

**Comment by rborosak** [comment]
@mikaelascorn I'm doing it like this...
 
```
const onRow = (record: any, rowIndex: any) => {
	return {
		onClick: () => { setSelectedRow(rowIndex) }
	}
}

const rowClassName = (record: any, index: number): string => {
	return index === selectedRow ? `${gStyles.active}` : ``;
}

<Table rowClassName={rowClassName} onRow={onRow} ......></Table>
```

**Comment by MrMuhammadRizwan** [comment]
**If you still getting this issue : Warning: onRowClick is deprecated, please use onRow instead.**
you can fixed this issue by trying this:
```
onRow={(record) => ({
                                    onClick: () => { this.rowClick(record.key) }
                                              
})}
```

**Comment by nischalhubbler** [comment]
When I am clicking on Checkbox of any row of the table then onRow functionality of the table is being triggered at the same time because of event bubbling. I am not able to stop this because they are not giving event in rowSelection .

**Comment by stefatkins** [comment]
> When I am clicking on Checkbox of any row of the table then onRow functionality of the table is being triggered at the same time because of event bubbling. I am not able to stop this because they are not giving event in rowSelection .

I'm having the same issue.

**Comment by dogbutcat** [comment]
@nischalhubbler @stefatkins What's your antd version, I've just fix my fixed codepen https://codepen.io/dogbutcat/pen/wprmrR which using antd@3.1.0. Hope this example will help.

**Comment by nischalhubbler** [comment]
@dogbutcat  It was 4.0.4 when I was facing this issue. But antd has fixed this in the later version. Now I am using 4.1.1 and in this, it has been fixed.

**Comment by AlexeyKorkoza** [comment]
@stefatkins , @nischalhubbler Today I have confronted with this issue. I use the 3.26.16 version of the ant. To get rid of bubbling you must add `onClick` to the Checkbox component and call the stopPropagation method. I reproduced my fix using the codesanbox. Here is a link: https://codesandbox.io/s/bold-hodgkin-voiol?file=/src/App.js
I spent approximately one hour to fix this issue. I found out that the Checkbox component has the `OnClick` property after looking through allowed properties in the source of the component. You can ensure: https://github.com/ant-design/ant-design/blob/master/components/checkbox/Checkbox.tsx#L16

**Comment by acifuentesv** [comment]
```
<Menu.Item onClick={(e)=>{ 
             e.domEvent.stopPropagation();
              handleUpdate(id)}}>
              Edit
 </Menu.Item>
```

**Comment by jailsonpaca** [comment]
> ```
> <Menu.Item onClick={(e)=>{ 
>              e.domEvent.stopPropagation();
>               handleUpdate(id)}}>
>               Edit
>  </Menu.Item>
> ```

Thank you! this solve my problem!
