### ISSUE TITLE
Button layout is broken when inside a form

### ISSUE THREAD

**Issue by Cinamonas** [ant-design/ant-design#8836]
### Version
3.1.0

### Environment
Demo site for components on Chrome 63

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
1. Go to [https://ant.design/components/form/](https://ant.design/components/form/)
2. Make sure you hard refresh
3. Look at buttons

### What is expected?
Button layout matches the one seen in [https://ant.design/components/button/](https://ant.design/components/button/).

### What is actually happening?
Button layout is broken:

<img width="642" alt="screenshot 2018-01-05 09 49 57" src="https://user-images.githubusercontent.com/136233/34599979-f8e2f866-f1fd-11e7-8e6b-6a2bf2bc984f.png">

**Comment by eminx** [comment]
Up up! I'm trying to convince my team to switch to Ant.design from MUI. This doesn't help :/

It seems that `.ant-form-item-control` class has a `line-height` property that causes the issue. I don't feel it's the CSS honestly. 

Why not use flexbox? This is a perfect case for that!

**Comment by afc163** [comment]
It is broken by https://github.com/ant-design/ant-design/commit/455b9e40e0a650afe08297eaffd62b322190f187 which is not released yet. You can try latest antd version that should works fine: https://codesandbox.io/s/q8vp5pzn1j

Thx for reporting it!
