### ISSUE TITLE
Select render error when use tags and OptGroup

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#8840]
### Version
3.1.0

### Environment
osx 10.12 chrome 63

### Reproduction link
[https://codesandbox.io/s/4x15yo6y8x](https://codesandbox.io/s/4x15yo6y8x)

### Steps to reproduce
select a option

### What is expected?
The list of options should not change

### What is actually happening?
The selected option is incorrectly rendered in each group

**Comment by yesmeck** [comment]
Duplicate #5986
