### ISSUE TITLE
Table在谷歌浏览器版本较低（49.0.2623.110）下，A页面一开始是有横向滚动条，切换到B没有横向滚动条页面，在切回A，发现A页面的滚动条不见了

### ISSUE THREAD

**Issue by liyun074** [ant-design/ant-design#8842]
### Version
2.13.11

### Environment
window

### Reproduction link
[http://2x.ant.design/components/table-cn/](http://2x.ant.design/components/table-cn/)

### Steps to reproduce
React应用，页面部分刷新，单页面。Table在谷歌浏览器版本较低（49.0.2623.110）下，设置scroll.x值，A页面一开始是有横向滚动条，切换到B没有横向滚动条页面，在切回A，发现A页面的滚动条不见了

### What is expected?
切换回A页面时，滚动条还是存在

### What is actually happening?
切换回A页面时，滚动条消失，但是页面点击按钮或者改变CSS属性，或者改变窗口大小，滚动条出现了。

---
MAC没问题，window有问题。

**Comment by afc163** [comment]
49 实在是太老了，没办法提供支持了，建议升级浏览器。
