### ISSUE TITLE
The thumbnail of a video cannot be generated correctly when upload a video file.

### ISSUE THREAD

**Issue by luyilin** [ant-design/ant-design#8843]
### Version
3.1.0

### Environment
chrome version 63.0.3239.132

### Reproduction link
[https://codesandbox.io/s/rl6k7l0qjn](https://codesandbox.io/s/rl6k7l0qjn)

### Steps to reproduce
Just open the [codesandbox link](https://codesandbox.io/s/rl6k7l0qjn) and upload a video file, then you can see the thumbnail of the file cannot be displayed.

### What is expected?
The element to preview should be rendered as a video tag instead of an img tag when users upload a video file.
Maybe you should render different preview element according to the type of the uploaded file.

### What is actually happening?
The preview element is rendered as an img tag all the time.

---
The bug had been raised before, https://github.com/ant-design/ant-design/issues/4653, but sadly had not been fixed. Or is there any options I ignored to diaplay it correctly?

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/4653 was closed because we don't think it is a bug. If you want show thumbnail for other files than image, you need generate thumbnail by yourself and assign a `thumbUrl` to the file object.

**Comment by luyilin** [comment]
A little confused, could you write a simple example just in codesandbox? Really glad to see it.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/18wv2pwowl

**Comment by luyilin** [comment]
But the thumbUrl of the video only can be rendered correctly by a video tag. Do you mean generate an image url of the first frame of the video manually? I haven't got it.
Render it as a video tag is an easier way to achieve it?

**Comment by yesmeck** [comment]
Yes, upload list only support show image at present. You implement your own upload list if you show  other files then images.

**Comment by luyilin** [comment]
I see. Thanks a lot for your assistance.

**Comment by luyilin** [comment]
I just modified the source code to render a video tag depends on the filename extension. There is my [modification](https://github.com/luyilin/ant-design/commit/2815d0e170893eac24e56aae2e664d6b26324462)
Does it can be a feature? If yes I could submit a pull request.
Actually I just want to publish a bot package in npm to test, but it's hard to build as I have to rename the package 😅 
 It can work, but I don't know if there is any other problems that I have't noticed. Gald to hear your opinions!
