### ISSUE TITLE
InputNumber will not blur nicely when submitting a form with the return key that asks for a focus() somewhere else (pressing submit is OK)

### ISSUE THREAD

**Issue by hermanfenderson** [ant-design/ant-design#8846]
### Version
3.1.0

### Environment
Chrome on OSX and Windows. Didn't test other browses

### Reproduction link
[https://codepen.io/hermanfenderson/pen/baoJrd](https://codepen.io/hermanfenderson/pen/baoJrd)

### Steps to reproduce
On the third field of the example form (focused at startup) submit the form using the return key. 

### What is expected?
It should focus on the first field (as happens pressing the submit button). By the way this is the behaviour with a Input component (second field).

### What is actually happening?
The form is submitted but the field is not blurred and the first one is not focused (this works on the other end on the second field).

---

**Comment by hermanfenderson** [comment]
I wonder if there's a connection with the fact that blur() seems not to be working on inputnumber component

**Comment by yutingzhao1991** [comment]
You should add a timeout to ensure focus trigger after forceupdate ended.

```
    if (field === this.state.willFocus) {
      setTimeout(() => {
        input.focus();
      }, 0);
    }
```
