### ISSUE TITLE
.roadhogrc is no longer used with dva-cli

### ISSUE THREAD

**Issue by frxncisjoseph** [ant-design/ant-design#8847]
### Version
3.1.0

### Environment
dva-cli version 0.9.1, dva version 2.1.0

### Reproduction link
[https://github.com/sorrycc/roadhog#extrababelplugins](https://github.com/sorrycc/roadhog#extrababelplugins)

### Steps to reproduce
https://ant.design/docs/react/practical-projects

### What is expected?
Edit .roadhogrc to integrate babel-plugin-import.

### What is actually happening?
.roadhogrc is no longer used by roadhog and is now deprecated.
.webpackrc (or .webpackrc.js) is now used instead for the configuration.

---
Please update your website and documentation to reflect this.

**Comment by frxncisjoseph** [comment]
> Edit .webpackrc to integrate babel-plugin-import.
> 
> `{
>     "extraBabelPlugins": [
>         "transform-runtime",
>         ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
>     ],
> }

This should be the correct format.
`

**Comment by afc163** [comment]
@sorrycc We need to update our practical-projects document.
