### ISSUE TITLE
Draggable Tree component has different action between version 1.x and 3.0.x

### ISSUE THREAD

**Issue by sisiea** [ant-design/ant-design#8857]
### Version
1.11.2

### Environment
浏览器：版本 63.0.3239.84（正式版本） （64 位）

### Reproduction link
[http://1x.ant.design/components/tree/](http://1x.ant.design/components/tree/)

### Steps to reproduce
in the draggable tree demo。

0-0-0-0  、 
0-0-0-1  、
0-0-0-2  

Step：
    Drag node named 0-0-0-2 to the gap between node named 0-0-0-0 and node named 0-0-0-1。

### What is expected?
expected result：

0-0-0-0 、
0-0-0-2 、
0-0-0-1 

### What is actually happening?
while dragging a little blue line show on the top of 0-0-0-1 or the bottom of 0-0-0-0.

in the version 1.x which I use，
when blue line show at the top of 0-0-0-1，actual result：
0-0-0-0 、
0-0-0-2 、
0-0-0-1 

when blue line show at the bottom of 0-0-0-0，actual result：
0-0-0-2 、
0-0-0-0 、
0-0-0-1 

but，in the version 2.x and 3.0.x

no matter where the blue line show at， the result is：
0-0-0-0 、
0-0-0-2 、
0-0-0-1 

。And that is what I want.

---
Maybe it is a bug in version 1.x and it is fixed in later version。But I browser the change log， I cannot find it。Can u help me how to fix it in version 1.x.0？

**Comment by yesmeck** [comment]
It is not the bug of tree itself, it is the bug of the demo. You can compare demo code of two versions to find what's the difference.
