### ISSUE TITLE
新版发布后切换到旧版本无法回到最新版

### ISSUE THREAD

**Issue by maiko331** [ant-design/ant-design#8863]
### Version
3.1.0

### Environment
Chrome

### Reproduction link
[http://2x.ant.design/changelog](http://2x.ant.design/changelog)

### Steps to reproduce
https://ant.design/docs/spec/introduce-cn 进入这个页面
右上角切换早先的版本，就回不到3.0了
只能浏览器返回。。= =？

### What is expected?
下拉里把3.0加进去呗。怎么进来怎么回去。

### What is actually happening?
我要回去！

**Comment by afc163** [comment]
建议自己回去吧，旧版文档不会包含新版的信息的，否则每发一个大版本，就要把所有旧版文档改一遍也是很麻烦的。
