### ISSUE TITLE
RangePicker can show last month and this month at initial open

### ISSUE THREAD

**Issue by Shirley89** [ant-design/ant-design#8864]
### What problem does this feature solve?
I use this picker to select range of past days to show some data，like 'react-bootstrap-daterangepicker' do , I hope my user will can not see the right pannel that he never use

### What does the proposed API look like?
add a property to set this initial show

**Comment by afc163** [comment]
There is a undocumented `defaultPickerValue` you can try.

https://github.com/ant-design/ant-design/blob/9bf76ff76ab59d60f2654cb9257703689ee24cf7/components/date-picker/index.tsx#L63

**Comment by Shirley89** [comment]
还是解决不了问题，我需要是在任何时候，尤其是value有值的情况下右侧的面板为所选的截止日期所在的月份

**Comment by mintsweet** [comment]
@Shirley89 解决了吗。。。。遇到这个变态需求了

**Comment by Shirley89** [comment]
> @Shirley89 解决了吗。。。。遇到这个变态需求了

木有

**Comment by jhenry9636** [comment]
Was this ever resolved? For my UI I am showing previous 7 days data. If that range falls in the previous month I need to show that month. Please advise.

Thanks for this great tool!

**Comment by vincentFzzf** [comment]
any solution ?

**Comment by Shirley89** [comment]
> any solution ?

nope
