### ISSUE TITLE
Form组件getFieldDecorator id嵌套返回问题

### ISSUE THREAD

**Issue by uraidiot** [ant-design/ant-design#8868]
### Version
3.0.0

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

### Reproduction link
[https://codesandbox.io/s/jnw46698m3](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
{getFieldDecorator('member[0].name.firstname', {})(<input/>)}
{getFieldDecorator('member[1].name.firstname', {})(<input/>)}

### What is expected?
[{ name: {firstname: "xxx"} }, { name: {firstname: "yyy"} }]

### What is actually happening?
{
    "0": {
        "firstName": "1",
        "lastName": "1",
    },
    "1": {
        "firstName": "2",
        "lastName": "2"
    },
    "": "2"
}

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by uraidiot** [comment]
it seems like all my fault, sorry
