### ISSUE TITLE
Table component should support function or node as emptyText's value

### ISSUE THREAD

**Issue by jihgao** [ant-design/ant-design#8871]
### What problem does this feature solve?
It is requried  to put a shortcut link besides emptyText to create a new record in a lot of scenarios. The table component in rc-table support this feature which is restricted to only support strings in ant-design. If you could add this feature, it will make the component more flexable.

### What does the proposed API look like?
```
<Table emptyText={()=>{
   return 'no data';
}}
/>

<Table emptyText={()=>{
   return <div><span>No data</span><a href="">Create a new record</a></div>
}}
/>
```

**Comment by afc163** [comment]
PR is welcome~
