### ISSUE TITLE
Ant Design 的中心色板一共包含了从白到黑的 14 个颜色。（“中心色板” 应该为 “中性色板”）

### ISSUE THREAD

**Issue by w605672534** [ant-design/ant-design#8875]
### Version
3.1.1

### Environment
chrome

### Reproduction link
[https://ant.design/docs/spec/colors-cn](https://ant.design/docs/spec/colors-cn)

### Steps to reproduce
色彩 - 系统级色彩体系 - 中性色板 - Ant Design 的中心色板一共包含了从白到黑的 14 个颜色。

### What is expected?
Ant Design 的中性色板一共包含了从白到黑的 14 个颜色。

### What is actually happening?
Ant Design 的中心色板一共包含了从白到黑的 14 个颜色。

**Comment by afc163** [comment]
PR is welcome~
