### ISSUE TITLE
增加 lightbox 

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#888]
集成进用户上传图片后预览

```
<Upload listType='picture-card'>
```

或增加 onView api

```
<Upload listType='picture-card' onView={function(url){
  new LightBox(url)
}}>
```

## refer

http://lokeshdhakar.com/projects/lightbox2/

http://ashleydw.github.io/lightbox/

**Comment by afc163** [comment]
lightbox 就是 Modal .

**Comment by yiminghe** [comment]
lightbox 有图片导航的作用，（左右箭头）

或Uploader 需要提供个接口使用现有的 lightbox 组件（）

**Comment by afc163** [comment]
图片切换配合 Carousel 就可以实现：

https://github.com/ant-design/ant-design/blob/7404e759a944c4cfd5cd46cfcad2c43efbf4332f/scripts/demo.js#L192

个人感觉交互上不要搞这么复杂，打开新窗口适应性最好，特别是长宽超过屏幕大小的图片。

**Comment by afc163** [comment]
暂不实现。
