### ISSUE TITLE
关于LocaleProvider汉化的问题

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#8881]
### Version
3.1.0

### Environment
Chrome  win10

### Reproduction link
[https://ant.design/components/locale-provider-cn/](https://ant.design/components/locale-provider-cn/)

### Steps to reproduce
我根据官网的说明 配置相关
index.html

    <script src="//cdn.bootcss.com/moment.js/2.20.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.20.1/moment-with-locales.min.js"></script>
    <script src="https://cdn.bootcss.com/moment.js/2.20.1/locale/zh-cn.js"></script>
    <script src="//cdn.bootcss.com/antd/3.1.0/antd.min.js"></script>
    <script src="//cdn.bootcss.com/antd/3.1.0/antd-with-locales.min.js"></script>

entry.jsx
```
      const { LocaleProvider, locales } = antd;
      moment.locale('zh-cn');
        <Provider store={store}>
         <LocaleProvider locale={locales.zh_CN}>
           <HashRouter>
        <Switch>
          <Route path="/user" render={props => <UserLayout {...props} />} />
          <Route path="/" render={props => <DashboardLayout {...props} />} />
        </Switch>
      </HashRouter>
    </LocaleProvider>
  </Provider>,
```

### What is expected?
DatePicker组件英文变成中文

### What is actually happening?
在某一个页面中用 DatePicker组件，初始化的时候是显示的中文，但是today还是英文。当选择日期的时候再次打开 全部变成英文

---
因为这个设计到环境的问题，我的antd组件都是挂载window下的。所以无法用codeopen重现

**Comment by afc163** [comment]
```
<script src="//cdn.bootcss.com/antd/3.1.0/antd.min.js"></script>
<script src="//cdn.bootcss.com/antd/3.1.0/antd-with-locales.min.js"></script>
```

这两个是重复的。

**Comment by guoxiangwen** [comment]
@afc163 已经改过来了，还是一样的效果

**Comment by afc163** [comment]
`<script src="//cdn.bootcss.com/moment.js/2.20.1/moment-with-locales.min.js"></script>`

保留这个一个就够了，`moment.min.js` 和 `zh-cn.js` 也是重复的。

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/LeQVxg?editors=0010

发现需要这么写才行：`locales.zh_CN.default`。

**Comment by afc163** [comment]
@yesmeck 这块是不是可以修正？

**Comment by guoxiangwen** [comment]
厉害。谢谢了

**Comment by guoxiangwen** [comment]
@afc163 大神，还有个问题，就是我的所有antd的组件以及css都是通过link和script标签挂载在window下的。然后在webpack extral.如果要修改字体大小或者其他的属性。按照官网的方法是行不通的。有没有什么办法呢？

**Comment by yesmeck** [comment]
奇怪，我本地 build 出来没有这个 default。
