### ISSUE TITLE
Select prop defaultValue is not Correctly selected by value 

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#8883]
### Version
3.1.0

### Environment
google chorem 63.0.3239.132 ant-design 3.1.0 

### Reproduction link
[https://codesandbox.io/s/r064ozwpl4](https://codesandbox.io/s/r064ozwpl4)

### Steps to reproduce
    <Select defaultValue={1} style={{ width: 120 }} onChange={handleChange}>
      <Option key={1}>Jack</Option>
      <Option key={2}>Lucy</Option>
      <Option key={3}>yiminghe</Option>
      <Option key={4}>xiaohu1</Option>
    </Select>

### What is expected?
according to key ,  Setting the defaultValue ，can  Correctly selected

### What is actually happening?
can not Correctly selected

**Comment by yesmeck** [comment]
`key` will convert to `string`. So you need use `string` `defaultValue` as well.

**Comment by yupeilin123** [comment]
Thanks
