### ISSUE TITLE
Select prop onChange ， Dynamic rendering Value 

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#8884]
### What problem does this feature solve?
The value of the display is  controlled and not only according to options ' value 

### What does the proposed API look like?
onChange( value )  { return value }

![image](https://user-images.githubusercontent.com/28672197/34711185-5d5b777e-f559-11e7-9e82-fd3274f7e9bd.png)

**Comment by yesmeck** [comment]
啥意思？

**Comment by yupeilin123** [comment]
能根据option的值来动态的生成select展示的值

**Comment by yesmeck** [comment]
Use `optionLabelProp`.
