### ISSUE TITLE
【DatePicker】display incorrect time  after setting 'showTime' and 'allowClear'

### ISSUE THREAD

**Issue by jackie19** [ant-design/ant-design#8885]
### Version
3.1.1

### Environment
macOS 10.12.6 , chrome 版本 63.0.3239.132（正式版本） （64 位）,

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5d7aedf6?mode=jsx](https://riddle.alibaba-inc.com/riddles/5d7aedf6?mode=jsx)

spare link:  
[https://codesandbox.io/s/x933235xro](https://codesandbox.io/s/x933235xro)

### Steps to reproduce
1.click clear button  
2.display datePicker panel  
2.click a date  in  datePicker panel like: 2018-1-1 ( do not click other place to  hide datePicker )  
3.click a date (2018-1-1) again 

### What is expected?
2018-1-1 12:12:12

### What is actually happening?
the time part is current time, not 12:12:12

### code 
```javascript
import { DatePicker } from 'antd';
import moment from 'moment';
let defaultValue = moment('2018-12-12 12:12:12');
let cleared = false;
function onChange(value, dateString) {
  console.log('Selected Time: ', value);
  console.log('Formatted Selected Time: ', dateString);

  if (cleared) {
    value = moment(moment(value).format('YYYY-MM-DD 12:12:12'));
    cleared = false;
  }

  if (!value) {
    cleared = true;
  }

  render(value);
}

function onOk(value) {
  render(value);
  console.log('onOk: ', value);
}

function render(value) {
  ReactDOM.render(
    <div>
      <DatePicker
        showTime
        value={value}
        format="YYYY-MM-DD HH:mm:ss"
        placeholder="Select Time"
        onChange={onChange}
        onOk={onOk}
      />
      <br />
    </div>,
    mountNode,
  );
}

render(defaultValue);

```
---
want to set a default time after clear date, but when I click a date second time, the default time is overwriten by current time.

**Comment by yesmeck** [comment]
The behavior is expected.

1.click clear button 

value is cleared.

2.display datePicker panel 

nothing to show.

3.click a date in datePicker panel like: 2018-1-1 ( do not click other place to hide datePicker )

shows `2018-12-12 12:12:12` as you set in `onChange`.

4.click a date (2018-1-1) again

shows current date time.

**Comment by jackie19** [comment]
1.click clear button,
2.display datePicker panel , choose a date , **click other place to hide panel**,
3.display panle and choose  another date, the time part will be 12:12:12,

How do you explain this？

**Comment by yesmeck** [comment]
As I said you set value to `YYYY-MM-DD 12:12:12` in `onChange`.

**Comment by jackie19** [comment]
How do I make it show 12:12:12 on second click?
(after clear the value, and not hide panel between clicks.)

**Comment by yesmeck** [comment]
Hmm, that's a bug.

**Comment by jackie19** [comment]
:D, shall we talk this in DingTalk ?

**Comment by yesmeck** [comment]
@jackie19 边柳
