### ISSUE TITLE
UPload组件，使用IE11浏览器无任何反应，一直显示空白页面，也没有报错

### ISSUE THREAD

**Issue by gpwang2000** [ant-design/ant-design#8887]
### Version
3.1.1

### Environment
IE11浏览器

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
使用antd的upload照片墙用例进行测试

### What is expected?
能正常显示照片墙

### What is actually happening?
显示照片墙

**Comment by dengfuping** [comment]
@gpwang2000 It has been tested in my IE 11 and no problem found.

![image](https://user-images.githubusercontent.com/14918822/34752885-db6b3ff0-f5ef-11e7-98c5-9742101ab74c.png)

**Comment by gpwang2000** [comment]
经测试，使用creat-react-app构建app，在IE11下报错，Type-Error：对象不支持“startsWith”属性或方法
