### ISSUE TITLE
this.fetch is not a function. (In 'this.fetch(a)', 'this.fetch' is undefined)

### ISSUE THREAD

**Issue by kingslay** [ant-design/ant-design#889]
对table的列进行排序的时候。报这个错。下面是我的代码。
handleTableChange(pagination, filters, sorter) {
        const pager = this.state.pagination;
        pager.current = pagination.current;
        this.setState({
            pagination: pager
        });
        var sort = sorter.field;
        if (!sorter.order){
            sort += ",desc";
        }

        const params = {
            size: pagination.pageSize,
            page: pagination.current,
            sort: sorter.field,
            order: sorter.order
        };
        for (let key in filters) {
            params[key] = filters[key];
        }
        this.fetch(params);
    }

 fetch(params = {}) {
        this.setState({loading: true});
        $.get("/userInfoes",params)
            .then((response) => {
                    const pagination = this.state.pagination;
                    pagination.total = response.page.totalPages;
                    this.setState({users: response._embedded.userInfoes, loading: false, pagination,})
                }
            )
    }

**Comment by kingslay** [comment]
我是使用safari9.1  是用es6来写ant-design

**Comment by benjycui** [comment]
建议阅读 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)，然后更新下你的 issue。

同时学习下 markdown 可好？https://help.github.com/categories/writing-on-github/
