### ISSUE TITLE
Make default template project title configurable

### ISSUE THREAD

**Issue by wmz7year** [ant-design/ant-design#8890]
### What problem does this feature solve?
Default antd template project title config is in 'src/layouts/BasicLayout.js#getPageTitle'.

Make it configurable such as menu config.

### What does the proposed API look like?
src/common/project.js
```
{
  "title": "ant design"
}
```

**Comment by yesmeck** [comment]
You should open issue to https://github.com/ant-design/ant-design-pro/issues
