### ISSUE TITLE
如何显示表格总行数？

### ISSUE THREAD

**Issue by imperio-wxm** [ant-design/ant-design#8892]
### What problem does this feature solve?
如何在header or footer显示这个表格一共有多少行的数据？

### What does the proposed API look like?
在分页最左边，显示这个表格一共有多少行的数据

**Comment by yesmeck** [comment]
`<Table dataSource={data} footer={<div>{data.length} 条数据</div>} />`

**Comment by lipengfei003** [comment]
@imperio-wxm     footer={()=> {return(<strong>共{data.length}条数据</strong>)}}

**Comment by lipengfei003** [comment]
@imperio-wxm   footer={()=> {return(<div>共{relationSites.length}条数据</div>)}}
