### ISSUE TITLE
Google Places Autocomple 

### ISSUE THREAD

**Issue by ahmetkuslular** [ant-design/ant-design#8894]
How can we use google places autocomplete with ant autocomplete? Or can we integrate this [react-places-autocomplete](https://github.com/kenny-hibino/react-places-autocomplete) I could not use it in the form.

**Comment by yesmeck** [comment]
`<AutoComplete backfill  />`

FYI you can use custom input in form, see https://ant.design/components/form/?locale=en-US#components-form-demo-customized-form-controls

**Comment by ahmetkuslular** [comment]
@yesmeck I do not fully understand. Could you explain a bit more? [react-places-autocomplete](https://github.com/kenny-hibino/react-places-autocomplete) will I be able to use it together? Or do I have to write it myself?

**Comment by yesmeck** [comment]
You can react-places-autocomplete with a little wrap. See "Customized Form Controls" section in above link.

**Comment by ahmetkuslular** [comment]
@yesmeck I can validate it like this. The problem is this: When AutoComplete elements are listed, they remain under all of the form elements. 

![adsiz](https://user-images.githubusercontent.com/17436691/34729786-acf0a434-f56e-11e7-9b56-31a62adc2714.png)

**Comment by jameskennethrobinson** [comment]
@ahmetkuslular Any way you could post the code you used to get this working? I may have a solution for your overlapping problem!

**Comment by PhilipTKC** [comment]
> <img alt="screen shot 2018-10-05 at 3 38 44 pm" width="979" src="https://user-images.githubusercontent.com/8107077/46563159-d0f22a00-c8b4-11e8-9322-9980dd944d63.png">
> 
> @ahmetkuslular Any way you could post the code you used to get this working? I may have a solution for your overlapping problem (as you can see, my address dropdown pushes content out of the way rather than obscuring inputs below).

A bit late reply, But for anyone else that has this issue.

```
.autocomplete-dropdown-container {
  background-color: #FFF;
  box-shadow: 0 1px 3px 0 #e6ebf1;
  padding: 10px;
  position: absolute;
  width: 100%;
  z-index: 100;
}

.autocomplete-dropdown-container:empty {
  display: none;
}
```

![deepinscreenshot_select-area_20190220154510](https://user-images.githubusercontent.com/32603341/53062719-9f59c280-3526-11e9-89ec-3cad196fa5c3.png)

![deepinscreenshot_select-area_20190220154539](https://user-images.githubusercontent.com/32603341/53062720-9ff25900-3526-11e9-8534-a935ce808ec3.png)

**Comment by jasan-s** [comment]
@jameskennethrobinson  can you share a working example of address autocomplete

**Comment by PhilipTKC** [comment]
@jasan-s I threw together a quick gist.

https://gist.github.com/PhilipTKC/7ba3fbdc1d7faa2bfcb846d6dac2491e

You might need to change a few things but you get the idea it's fairly simple.

**Comment by gmkhussain** [comment]
We can use google places autocomplete this way

```jsx
import React, { useState } from ;react';
import Input from 'antd/es/input/Input';
import { LoadScript, Autocomplete } from '@react-google-maps/api';

const MyComponent= () => {

    const handleOnPlaceChanged = () => {
        /* 
          Do something onPlaceChanged
       */
    };

    return (<>
        <LoadScript
            googleMapsApiKey={'YOUR_GOOGLE_MAP_API_KEY'}
            libraries={['places']}
        >
            <Autocomplete
                onLoad = {() => console.log('Do something onLoad')}
                onPlaceChanged={handleOnPlaceChanged}
                fields={['geometry.location', 'formatted_address']}
            >
                <Input placeholder="Enter your address" />
            </Autocomplete>
        </LoadScript>
    </>)
}

export default MyComponent
```

**Comment by gmkhussain** [comment]
We can use google places autocomplete this way

```jsx
import React, { useState } from 'react';
import Input from 'antd/es/input/Input';
import { LoadScript, Autocomplete } from '@react-google-maps/api';

const MyComponent= () => {

    const handleOnPlaceChanged = () => {
        /* 
          Do something onPlaceChanged
       */
    };

    return (<>
        <LoadScript
            googleMapsApiKey={'YOUR_GOOGLE_MAP_API_KEY'}
            libraries={['places']}
        >
            <Autocomplete
                onLoad = {() => console.log('Do something onLoad')}
                onPlaceChanged={handleOnPlaceChanged}
                fields={['geometry.location', 'formatted_address']}
            >
                <Input placeholder="Enter your address" />
            </Autocomplete>
        </LoadScript>
    </>)
}

export default MyComponent
```

**Comment by acanimal** [comment]
Anybody has made it work react-places-autocomplete with antd Select component?
