### ISSUE TITLE
[Select] maxTagCount and maxTagPlaceholder props does not seems to be available

### ISSUE THREAD

**Issue by urakozz** [ant-design/ant-design#8895]
### Version
3.1.1

### Environment
OSX 10.13.2, Safari, Node 9.3.0, ts 2.6.2, antd 3.1.1

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L35](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L35)

### Steps to reproduce
Create component with `maxTagCount`
```typescript
<Select maxTagCount={1}></Select>
```

### What is expected?
succesfull compilation and working `maxTagCount`

### What is actually happening?
```
error TS2339: Property 'maxTagCount' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Select> & Readonly<{ children?: ReactNode; }> & Re...'.
```

**Comment by dengfuping** [comment]
@urakozz Select Component is based on the [react-component/select](https://github.com/react-component/select). The maxTagCount and maxTagPlaceholder props are available in react-component/select. Further to [the source code fragment](https://github.com/react-component/select/blob/40ff9d8e423440d9f977c3c9342bb95d1aac6a0e/src/Select.jsx#L1026).

**Comment by afc163** [comment]
We need to fix the typescript types.
