### ISSUE TITLE
New Component Drawer

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8898]
- https://www.npmjs.com/package/react-drawer
- https://github.com/stoeffel/react-motion-drawer
- http://www.material-ui.com/#/components/drawer

<img width="844" alt="image" src="https://user-images.githubusercontent.com/507615/37821552-e815b0ca-2ebe-11e8-8db6-95947528026f.png">

**Comment by devphc** [comment]
<Icon type="dashboard" /> display none

**Comment by yesmeck** [comment]
https://github.com/ant-motion/drawer-menu

**Comment by yesmeck** [comment]
http://react-component.github.io/drawer/

**Comment by chenshuai2144** [comment]
现在使用的这个
https://github.com/ant-motion/drawer-menu

**Comment by afc163** [comment]
API 要重新设计过。

**Comment by JesperWe** [comment]
I am absolutely thrilled that you are adding a Drawer to antd, this will increase to perfection level substantially :-) !

However I worry a bit when I see that it is based on https://github.com/balloob/react-sidebar, which has an important issue that I reported as https://github.com/balloob/react-sidebar/issues/113 a long time ago. I hope this can be addressed....?

**Comment by chenshuai2144** [comment]
感觉可以合了

**Comment by afc163** [comment]
https://deploy-preview-10791--ant-design.netlify.com/components/drawer-cn/

@yesmeck @zombieJ 都来看下。

**Comment by JesperWe** [comment]
I checked how this preview works on a smartphone. There are some problems using Chrome for Android:
- The overlay appears and disappears, which means you can't tap it to close the drawer.
- You can't scroll the drawer sideways, so you can't reach the X to close when it is wide (as the item preview example)

**Comment by zombieJ** [comment]
* css 还是有点问题，关闭的时候滚动条也会出现。导致窗体关闭会略微左弹一下。 应该做成动画结束再展现 scroll bar。
* “对象编辑” 这个窗口调整成左侧展开，放右边和问卷调查冲突了：
<img width="84" alt="2018-06-28 2 56 20" src="https://user-images.githubusercontent.com/5378891/42018037-749bc08c-7ae3-11e8-83c1-f5a39e75d828.png">

**Comment by jljsj33** [comment]
@zombieJ :+1:

**Comment by jljsj33** [comment]
@zombieJ 在动画结束时再展现 scroll bar 也是不行的，，展现 scroll bar 肯定是有一段闪屏的。。。

我搞了下，在设定 hidden 时把 width 设为 calc(100% - 15px); ，然后在打开的过渡时把 width 恢复到 100%，关闭时也是同样的，先设定宽为 calc(100% - 15px);， 在关闭过渡时恢复 100%;

```jsx
     if (open) {
        document.body.style.overflow = 'hidden';
        if (right) {
          document.body.style.transition = '';
          document.body.style.width = `calc(100% - ${right}px)`;
         // fixed 定位, 加上 matrix 以当前为定位。。。
          document.body.style.transform = 'translateZ(0px)';
          setTimeout(() => {
            document.body.style.transition = 'width .3s';
            document.body.style.width = '';
          })
          // document.body.style.paddingRight = `${right}px`;
        }
      } else {
        document.body.style.overflow = '';
        if (this.isOpenChange && right) {
          document.body.style.transform = 'translateZ(0px)';
          document.body.style.transition = '';
          document.body.style.width = `calc(100% + ${right}px)`;
          setTimeout(() => {
            document.body.style.transition = 'width .3s';
            document.body.style.width = '';
          });
        }
      }
```

**Comment by jljsj33** [comment]
我换个 rc-drawer 的 issues.

**Comment by chenshuai2144** [comment]
resolve in  #10791
