### ISSUE TITLE
icon dashboard 不显示 bug

### ISSUE THREAD

**Issue by devphc** [ant-design/ant-design#8900]
### Version
3.1.1

### Environment
google 浏览器

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
复制粘贴icon dashboard

### What is expected?
显示出来

### What is actually happening?
不显示

**Comment by devphc** [comment]
ant-design Icon dashboard display none

**Comment by afc163** [comment]
Please check the antd version, the dashboard icon is added after 3.0.0
