### ISSUE TITLE
Badge wants to support icon mode?(Badge希望支持图标模式?)

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#8901]
### What problem does this feature solve?
The user image shows a VIP icon in the lower right corner.
(用户头像右下角显示一个vip的icon)

### What does the proposed API look like?
```jsx
<Badge icon={<img /> | url} position={'tr'}></Badge>
```

**Comment by yesmeck** [comment]
https://codepen.io/yesmeck/pen/OzQYZP?editors=0010
