### ISSUE TITLE
message.loading置顶

### ISSUE THREAD

**Issue by AmyShieh** [ant-design/ant-design#8906]
### What problem does this feature solve?
when I use the config of 'getContainer'，all the content in this dom would be empty.
使用message里的这个api配置后会清空XXX节点里所有内容。
```
message.config({
    getContainer: () => document.getElementById('XXX')
});
```

### What does the proposed API look like?
The message.loading() can be use in global DOM and the content won't be clear.
进行全局 loading，message提示可置顶

### Solution
I found there's a components named 'Toast' in 'antd-mobile', you can use it to instead of 'message'
解决方案：
可以引入ant-mobile中的toast组件，其中有一个mask参数，默认为true, toast为遮罩层

**Comment by nikogu** [comment]
@AmyShieh 最好不要同时引入 mobile 和 pc 两个库，不是最佳实践。

**Comment by nikogu** [comment]
rc-notification@3.0.1

**Comment by shen-lan** [comment]
message.config 不是全局配置吗？写在入口文件里吗？
