### ISSUE TITLE
Build Failing!

### ISSUE THREAD

**Issue by eminx** [ant-design/ant-design#8910]
### Version
3.1.1

### Environment
Travis-ci

### Reproduction link
[https://travis-ci.org/ant-design/ant-design](https://travis-ci.org/ant-design/ant-design)

### Steps to reproduce
Hej it's just on the landing page of both github and npm. I'm making a presentation to my team today trying convince them. This doesn't help :/

### What is expected?
Build passing :)

### What is actually happening?
Build seems to be failing

---
Probably a quick fix for you guys. BUT don't you have auto-tests that make sure the builds don't fail before publishing a version to NPM?

**Comment by yesmeck** [comment]
It's passing now. We do [run all tests](https://github.com/ant-design/ant-design/blob/4e2e9da7d2fde5bbe922499555a97a5f36a14427/package.json#L191) before publishing.
