### ISSUE TITLE
Menu只展开父级菜单，结合布局组件Sider使用的时候，收起侧边栏样式出错

### ISSUE THREAD

**Issue by OneAndOnly1111** [ant-design/ant-design#8911]
### Version
3.1.1

### Environment
Chorme 63.0.3239.108（正式版本） （64 位）

### Reproduction link
[https://codepen.io/OneAndOnly1111/pen/dJmoym](https://codepen.io/OneAndOnly1111/pen/dJmoym)

### Steps to reproduce
1.点击展开一个菜单，点击一个子项，
2.然后点击收起侧边栏，
3.出错： 悬浮的菜单还是在之前的位置

### What is expected?
期望点击侧边栏后，悬浮的菜单紧贴收起的侧边栏

### What is actually happening?
悬浮的菜单还是在侧边栏收起之前的位置

---
重现链接：https://codepen.io/OneAndOnly1111/pen/dJmoym

**Comment by dengfuping** [comment]
@OneAndOnly1111 Just need to remove the openKeys prop.

**Comment by OneAndOnly1111** [comment]
@dengfuping  I know remove the openKeys is ok，but i want to keep the menu bar simple

**Comment by yesmeck** [comment]
Duplicate of #8587?

**Comment by afc163** [comment]
Try control openKeys when menu is collapsed.

https://codepen.io/afc163/pen/EENxRO?editors=0010

**Comment by OneAndOnly1111** [comment]
thankyou, it works

**Comment by BeAce** [comment]
Although it's been a long time, I want to say more. It's better to have an ·openkey· cache so `openkey· can be restored when displayed.

**Comment by Yhspehy** [comment]
@afc163 
[https://codepen.io/afc163/pen/EENxRO?editors=0010](https://codepen.io/afc163/pen/EENxRO?editors=0010)
There is a flicker of hoverMenu in` antd@3.18.2`, is it correct  ?
