### ISSUE TITLE
Mention组件一直选择，内容会换行溢出

### ISSUE THREAD

**Issue by Joudee** [ant-design/ant-design#8914]
### Version
3.1.1

### Environment
线上

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
示例先输入@唤起下拉，然后不停的@选中

### What is expected?
超出不显示

### What is actually happening?
超出会换行溢出

**Comment by yesmeck** [comment]
Duplicate of #7717
