### ISSUE TITLE
Calendar component: the annual drop-down list is not wide enough and the year is incomplete. 日历组件: 年下拉列表宽度不够, 年显示不完整

### ISSUE THREAD

**Issue by yaoyu** [ant-design/ant-design#8916]
### Version
3.1.1

### Environment
win10, Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

### Reproduction link
[https://ant.design/components/calendar-cn/](https://ant.design/components/calendar-cn/)

### Steps to reproduce
日历组件在示例 "用于嵌套在空间有限的容器中" 中年显示不全

### What is expected?
显示完整的年份列表.  Display a complete annual list.

### What is actually happening?
下拉列表宽度不够, 年列表显示不全,  The drop-down list is not wide enough and the annual list is not full

**Comment by afc163** [comment]
Works on my machine, could you provide a screen capture?
