### ISSUE TITLE
首页中文链接失效

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8917]
http://ant.design/index-cn

会被跳转到

http://ant.design/

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/blob/master/site/theme/static/template.html#L49

**Comment by yesmeck** [comment]
🤣

**Comment by afc163** [comment]
<img width="164" alt="image" src="https://user-images.githubusercontent.com/507615/34778029-0f45f178-f657-11e7-971d-0e6c5372766d.png">

还是给我跳到英文了。

**Comment by afc163** [comment]
Firefox

**Comment by yesmeck** [comment]
localStorage 的优先级更高啊

**Comment by afc163** [comment]
好像是我切换过英文了。
