### ISSUE TITLE
Select Dropdown not remaining fixed to container while scrolling

### ISSUE THREAD

**Issue by adamaho** [ant-design/ant-design#8921]
### Version
2.10.2

### Environment
Ubuntu 16.04, chrome version 60.0.3112.90

### Reproduction link
[https://codepen.io/adamaho/pen/KZoezp](https://codepen.io/adamaho/pen/KZoezp)

### Steps to reproduce
click the Select to open the dropdown and scroll. 

### What is expected?
I would expect the dropdown to remain attached to its container when you scroll.

### What is actually happening?
The dropdown is detaching from its container and scrolling.

---
 
Proposed Solution: Have the `Select` component be wrapped in a div and then pass that div to `getPopupContainer` using a `ref`. In my testing this resolved the scrolling issue.

**Comment by afc163** [comment]
#8268

https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-scroll-with-page

**Comment by megawac** [comment]
We've been having to implement `getPopupContainer` on almost all of our components, is there not a better way this can be implemented in a general fashion @afc163?

> Proposed Solution: Have the Select component be wrapped in a div and then pass that div to getPopupContainer using a ref. In my testing this resolved the scrolling issue.

Could this be done on the `Select` component?

**Comment by romanshutsman** [comment]
`<Select getPopupContainer={trigger => trigger.parentNode}>`

**Comment by visakhvjn** [comment]
removes the name of the datepicker when I apply getPopupContainer={trigger => trigger.parentNode}

**Comment by sebasvivas1** [comment]
A little bit late, but another solution for this is simply adding the following line to the Select: 
`getPopupContainer={(trigger) => trigger.parentElement}`
