### ISSUE TITLE
Table component pagination props

### ISSUE THREAD

**Issue by nicolaszs** [ant-design/ant-design#8924]
### Version
3.1.1

### Environment
macOs, node: 8.3.0

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/table/interface.tsx](https://github.com/ant-design/ant-design/blob/master/components/table/interface.tsx)

### Steps to reproduce
```
  const tableConfig = {
      loading: this.state.loading,
      columns: columns,
      dataSource: data,

      pagination: false,
 }

 return (
     <Table {...tableConfig}/>
 )
```

### What is expected?
hide the table pagination

### What is actually happening?
Types of property 'pagination' are incompatible.
      Type 'boolean' is not assignable to type 'false | PaginationProps | undefined'.

![image](https://user-images.githubusercontent.com/17349158/34806536-7f8317ce-f6be-11e7-940b-44e99c8ab02b.png)

If I set the `pagination: {}`, it work fine

**Comment by yutingzhao1991** [comment]
It work fine in my demo: https://codesandbox.io/s/8l5j3y40oj

**Comment by yesmeck** [comment]
Related @8796

@nicolaszs Could you create a reproduce repo?

**Comment by nicolaszs** [comment]
@yutingzhao1991 You repo didn't use typescript, the error I got when I use typescript.

**Comment by yesmeck** [comment]
@nicolaszs Can you create a reproduction repo?

**Comment by muzea** [comment]
the problem is,in typeScript `var foo = false`  the foo's type is `boolean ` not `false`,

https://codesandbox.io/s/8x6zjoqwxj

```
const config = {
  pagination: false as false,
}
```

**Comment by yesmeck** [comment]
http://www.typescriptlang.org/play/index.html#src=type%20Pagination%20%3D%20false%20%7C%20%7B%20size%3A%20number%20%7D%3B%0A%0Aconst%20p%20%3D%20false%3B%0A%0Afunction%20table(pagination%3A%20Pagination)%20%7B%20%0A%20%20%20%20console.log(pagination)%3B%0A%7D%0A%0Atable(p)%3B

Still can not reproduce it.

**Comment by muzea** [comment]
@yesmeck like this http://www.typescriptlang.org/play/index.html#src=type%20Pagination%20%3D%20false%20%7C%20%7B%20size%3A%20number%20%7D%3B%0A%0Aconst%20p%20%3D%20%7B%0A%20%20%20%20val%3A%20false%2C%0A%7D%3B%0A%0Afunction%20table(pagination%3A%20Pagination)%20%7B%20%0A%20%20%20%20console.log(pagination)%3B%0A%7D%0A%0Atable(p.val)%3B

**Comment by yesmeck** [comment]
```typescript
import { TableProps } from 'antd/lib/table';

const tableConfig = {
  loading: this.state.loading,
  columns: columns,
  dataSource: data,
  pagination: false,
} as TableProps<any>;

<Table {...tableConfig}/>
```

**Comment by deepali-gudulkar** [comment]
Thanks a lot, this worked for me. Now, I could be able to use the actual Pagination component outside Table
