### ISSUE TITLE
Error in component which have method : Uncaught Error: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by chenzhq** [ant-design/ant-design#8927]
### Version
3.1.0

### Environment
MacOS 10.12.6, Chrome, react 16.2.0, electron 1.6.10

### Reproduction link
[https://codesandbox.io/s/vj53pvwv5y](https://codesandbox.io/s/vj53pvwv5y)

### Steps to reproduce
**SORRY! THE LINK DEMO CANNOT REPLAY THE BUG.**

The demo is copied from the website, 

### What is expected?
Click any button or item. The `visible` state turn into `true` Show the modal. 
Then click close or ok, the `visible` state turn into `false`, and the modal become hidden.

### What is actually happening?
When the Modal is visible, console an error.

---

Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

And the modal cant be closed even i manual turn the `visible` state into `false` using Developer Tool.

---
Actually this problem is also happened when using mention component and other components which have method. 
May be the same problem like  #1784 
I checked react version and found i have only one react. 

This is my dependencies and dev-dependecies
```
"dependencies": {
    "antd": "^3.1.0",
    "devtron": "^1.4.0",
    "electron-debug": "^1.2.0",
    "font-awesome": "^4.7.0",
    "history": "^4.6.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-hot-loader": "3.0.0-beta.6",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.7.1",
    "redux-thunk": "^2.2.0",
    "source-map-support": "^0.4.15"
  },
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-eslint": "^8.1.1",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.1.0",
    "babel-minify-webpack-plugin": "^0.2.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dynamic-import-webpack": "^1.0.1",
    "babel-plugin-flow-runtime": "^0.11.1",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-preset-env": "^1.5.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "chalk": "^2.0.1",
    "concurrently": "^3.5.0",
    "cross-env": "^5.0.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^0.28.3",
    "electron": "^1.6.10",
    "electron-builder": "^19.8.0",
    "electron-devtools-installer": "^2.2.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-formatter-pretty": "^1.1.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-compat": "^1.0.4",
    "eslint-plugin-flowtype": "^2.33.0",
    "eslint-plugin-flowtype-errors": "^3.3.0",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jest": "^20.0.3",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.1.0",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "fbjs-scripts": "^0.8.0",
    "file-loader": "^0.11.1",
    "flow-bin": "^0.63.1",
    "flow-runtime": "^0.13.0",
    "flow-typed": "^2.1.2",
    "html-webpack-plugin": "^2.29.0",
    "identity-obj-proxy": "^3.0.0",
    "jsdom": "^11.0.0",
    "minimist": "^1.2.0",
    "node-sass": "^4.5.3",
    "redux-logger": "^3.0.6",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.6",
    "sinon": "^2.3.5",
    "spectron": "^3.7.0",
    "style-loader": "^0.18.1",
    "stylefmt": "^6.0.0",
    "stylelint": "^7.12.0",
    "stylelint-config-standard": "^16.0.0",
    "url-loader": "^0.5.8",
    "webpack": "^3.0.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-dev-server": "^2.5.0",
    "webpack-merge": "^4.1.0"
  },
```

If you need other information, please tell me. Thank you!

**Comment by yesmeck** [comment]
99% possible you have two copies of react in your node_modules. Try run `npm list react` in your project.

**Comment by chenzhq** [comment]
Unfortunately, it's not the reason. 
Here is the result:
```
$ npm list react
tagview@0.0.1 /Users/chenzheqi/TagView
└── react@16.2.0
```

**Comment by yesmeck** [comment]
It's more like a build tool issue. If you can upload a minimal reproduction repo, I can take a look.

**Comment by chenzhq** [comment]
how to upload?

**Comment by yesmeck** [comment]
A GitHub repo...

**Comment by chenzhq** [comment]
Ok, this is the [repo](https://github.com/chenzhq/TagView).
Actually, it's a clone of https://github.com/chentsulin/electron-react-boilerplate. I changed some code. But i'm not sure where they are.😅

**Comment by yesmeck** [comment]
A **minimal** reproduction.

**Comment by chenzhq** [comment]
All right. You know it's not a bug in code. May be a build problem or some other package cause it. How can I find the minimal reproduction.

**Comment by chenzhq** [comment]
I have minimized the repo. Now the core code is two file 
1. Modal Component
https://github.com/chenzhq/TagView/blob/master/app/components/DialogDemo.js
``` javascript
import React from 'react';
import { Modal, Button } from 'antd';

class DialogDemo extends React.Component {
  state = { visible: false };
  showModal = () => {
    this.setState({
      visible: true,
    });
  };
  handleOk = e => {
    console.log(e);
    this.setState({
      visible: false,
    });
  };
  handleCancel = e => {
    console.log(e);
    this.setState({
      visible: false,
    });
  };
  render() {
    return (
      <div>
        <Button type="primary" onClick={this.showModal}>
          Open
        </Button>
        <Modal
          title="Basic Modal"
          visible={this.state.visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
          <p>Some contents...</p>
          <p>Some contents...</p>
          <p>Some contents...</p>
        </Modal>
      </div>
    );
  }
}

export default DialogDemo;
```
2. App.js
https://github.com/chenzhq/TagView/blob/master/app/containers/App.js

``` javascript
export default class App extends React.Component<Props> {
  render() {
    return (
      <div>
        <DialogDemo />
      </div>
    );
  }
}
```

You can clone it into your workspace and run `npm install && npm run dev`

**Comment by afc163** [comment]
Could you create a repo containing code above we can start with?

**Comment by shaderzak** [comment]
@chenzhq any success on this issue? I am facing similar problem, and cannot see multiple reacts as well.

**Comment by shaderzak** [comment]
@afc163 This is actually a React bug, I downgraded to 15.6.2 from 16.2.0 and Modal is working perfectly.
