### ISSUE TITLE
how to make the filters checked by default in table's columns?

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design#8929]
### Version
3.0.0

### Environment
Mac Os

### What is expected?
a property like defaultFilterValue or other solutions

### What is actually happening?
have no idea how to achieve it

**Comment by yesmeck** [comment]
`defaultFilterValue` is not supported currently. See #6168

**Comment by hudawen** [comment]
@yesmeck So, is there a way to make the filter checked rather than click on it?

**Comment by yesmeck** [comment]
Use `filteredValue` and use `onChange` to control it.

**Comment by hudawen** [comment]
@yesmeck I tried, data could be filtered as expected, yet the checkbox was still unchecked.

**Comment by yesmeck** [comment]
@hudawen Reproduction link https://u.ant.design/codesandbox-repro

**Comment by hudawen** [comment]
@yesmeck it's not easy to reproduct...My expect is the page renders with the filter checked, but `onChange` is a action after rendering, right?

**Comment by yesmeck** [comment]
https://codepen.io/yesmeck/pen/mpxNLq?editors=0010

**Comment by hudawen** [comment]
@yesmeck Thx a lot. I found I made a mistake... `filteredValue ` is assigned with int[] rather than string[] due to the int `value` of `filters`.

**Comment by DurgaPammi** [comment]
Hello..

I have one doubt regarding to search results should be configurable with respect to The columns that the user wants to see..for this can anyone help..how to go through that..or any sample examples for this..

Thanks in Advance

**Comment by thekennysong** [comment]
I see that defaultFilteredValue is now a prop but I am unable to get this to work. Has anyone gotten it to work?
