### ISSUE TITLE
mode='vertical'时，怎么自己控制menu的子菜单的绝对定位的位置。

### ISSUE THREAD

**Issue by qiaogr** [ant-design/ant-design#8930]
### What problem does this feature solve?
mode='vertical'时，我想自己控制submenu子菜单的绝对定位位置，怎么做？
At mode='vertical', I want to control the absolute location of the submenu submenu, and how do I do it?

### What does the proposed API look like?
mode='vertical'时，可以通过配置项关闭submenu子菜单的绝对定位位置的自动计算。
At mode='vertical', an automatic calculation of the absolute location of the submenu submenu can be closed by the configuration item.

**Comment by afc163** [comment]
暂不支持。

**Comment by heavenlian** [comment]
@afc163 
```
<div style="position: absolute; top: 0px; left: 0px; width: 100%;"> 
……
</div>
````
能在 这里帮忙可以添加的class名字。
