### ISSUE TITLE
When set state in beforeUpload of Upload component, the return true is no effect

### ISSUE THREAD

**Issue by QDJobson** [ant-design/ant-design#8933]
### Version
2.13.11

### Environment
win10    Chrome  63.0.3239.132

### Reproduction link
[https://codepen.io/anon/pen/wpmVdj?editors=0010](https://codepen.io/anon/pen/wpmVdj?editors=0010)

### Steps to reproduce
When setState in beforeUpload of Upload component, the return true is no effect. But remove the setState operation, everything is right.

### What is expected?
return true and start upload

### What is actually happening?
not start upload

**Comment by yesmeck** [comment]
Can not reproduce on your codepen.

**Comment by yesmeck** [comment]
https://reactjs.org/docs/faq-functions.html#how-do-i-bind-a-function-to-a-component-instance

**Comment by yesmeck** [comment]
You need bind beforeUpload to component instance.
