### ISSUE TITLE
Add a prop to force Layout to know it has a Sider (with SSR)

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#8937]
### What problem does this feature solve?

This will prevent the layout from flickering when loading after server-side rendering (`SSR`).
  
Example:  

```jsx
<Layout>
  <Layout.Sider />
  <Layout>
    <Layout.Content />
  </Layout>
</Layout>
```

As it is, `Layout.Content` appears below `Layout.Sider` during an instant, and only after the JS load is done it sets in the right position.

### What does the proposed API look like?

```jsx
<Layout hasSider />
<Layout hasSider={true} />
```
or 
```jsx
<Layout withSider />
<Layout withSider={true} />
```

**Comment by yesmeck** [comment]
#8604
