### ISSUE TITLE
form 表单在 navigator 固定情况下滚动时 form 表单位于图层最上方

### ISSUE THREAD

**Issue by imphoney** [ant-design/ant-design#8938]
### Version
3.1.1

### Environment
windows 10, chrome 64.0.3278.0

### Reproduction link
[https://github.com/NJU-itxia/react-redux-itxia](https://github.com/NJU-itxia/react-redux-itxia)

### Steps to reproduce
yarn start 

### What is expected?
Header is always the most top for such case.

### What is actually happening?
Form covers the Header when scrolling the window.

**Comment by benjycui** [comment]
I try your demo in Chrome/Firefox/Safari, and it works fine

<img src="http://g.recordit.co/whuS2EKNlj.gif" />

**Comment by benjycui** [comment]
http://g.recordit.co/whuS2EKNlj.gif

**Comment by imphoney** [comment]
Yes, yesterday l set the z-index of header component, so it now works well. However, it can be a default promise that the header to some extent is painted up-front. Thanks for freedback.

**Comment by imphoney** [comment]
you can checkout to 'first commit' to see the problem.

**Comment by imphoney** [comment]
you can checkout to 'first commit' to see the problem.

**Comment by yesmeck** [comment]
Closing since it's more like a usage question.
