### ISSUE TITLE
RangePicker中使用format显示周数的问题

### ISSUE THREAD

**Issue by LeuisKen** [ant-design/ant-design#894]
使用如下代码显示RangePicker

```
<RangePicker showTime format="yyyy年第w周"/>
```

选择日期为2015年1月1日时，显示2015年第1周

选择日期为2015年12月31日时，显示2015年第1周（应该为2016年第一周）

**Comment by afc163** [comment]
> 上面关联错了。

尝试给个重现方式吧。http://jsfiddle.net/0dso5y0x/

**Comment by LeuisKen** [comment]
线上demo：http://codepen.io/anon/pen/VerJLV
我在defaultValue里面设置的是2015年第1周 显示的是2014年第1周 应该可以说明问题
好像我定义format成这种格式没办法设置defaultValue为“2015年01月01日至2015年12月31日”
另外问一点 format似乎只会影响<RangePicker>本身 不会对其弹出的选择框产生影响（下图所示位置） 查阅文档似乎没有设置对应format的选项 而antd使用的rc-calendar是可以对其进行配置的 希望能够进行调整

![qq 20160120145858](https://cloud.githubusercontent.com/assets/7701575/12441873/626d323a-bf86-11e5-8387-97b7894b8fa9.png)

**Comment by afc163** [comment]
moment 貌似也有类似的问题：https://github.com/moment/moment/issues/2915

**Comment by LeuisKen** [comment]
那么请问上面图中提到的那部分日期的格式能够设定不

**Comment by afc163** [comment]
fixed in https://github.com/yiminghe/gregorian-calendar-format/issues/2

更新后使用 `YYYY-w`.

---

@LeuisKen 应该支持，另开 issue 吧，一事一议。:smile:
