### ISSUE TITLE
expandedRowRender errors with empty headers array

### ISSUE THREAD

**Issue by tastypackets** [ant-design/ant-design#8941]
### Version
3.1.1

### Environment
Linux & Windows, FF 57, react 16

### Reproduction link
[https://codepen.io/anon/pen/GydyQM?editors=0010](https://codepen.io/anon/pen/GydyQM?editors=0010)

### Steps to reproduce
Headers array is empty, all others such as data can be filled in.

### What is expected?
It is expected that nothing will be inserted into the headers if the headers array is empty.

### What is actually happening?
Attempts to access index 0 in the headers array and causes an error.

---
Error: rows[0] is undefined

I came across this issue since my headers were dynamic based on data retrieved from an API, I was able to work around the issue by initializing the columns to have a single object:
headers: [{key:"1"}]

(Headers is a variable passed to the table columns)

**Comment by afc163** [comment]
What is the expected look of table if the columns is `[`?

**Comment by tastypackets** [comment]
Currently it shows "No data" if there are no columns and I think that is a good implementation, it's just the expandedRowRender breaking it by trying to reference index 0 of the array.

I tried using the loading setting to wait for the dynamic content to be received, however this still renders the table and creates the undefined error.

Giving it a temporary columns object works okay, but it'd be nice to avoid Doing this.

**Comment by afc163** [comment]
> it's just the expandedRowRender breaking it by trying to reference index 0 of the array.

I think it should be fixed, would you mind to propose a PR to http://github.com/react-component/table for this?

**Comment by tastypackets** [comment]
I'll take a look and see if I can make a PR when I return to work next week.

**Comment by yesmeck** [comment]
Fixed in rc-table@6.1.5
