### ISSUE TITLE
Table 固定列没有自适应高度

### ISSUE THREAD

**Issue by w567675** [ant-design/ant-design#8943]
### Version
3.1.1

### Environment
chrome 62.0.3202.75,  win10 

### Reproduction link
[https://codepen.io/w567675/pen/MOmBKd](https://codepen.io/w567675/pen/MOmBKd)

### Steps to reproduce
点击编辑之后非固定列的高度被Select 撑开。 固定列的高度没有自适应调整。

### What is expected?
点击编辑之后非固定列的高度被Select 撑开。 固定列的高度没有自适应调整。

### What is actually happening?
 固定列的高度自适应调整。

---
这次是从antd2升级antd3,  在2.12.3的业务代码中，固定列会自适应调整。升级到3.1.1 就不行了，请问下是去掉了个这个功能么？

**Comment by yesmeck** [comment]
Thanks for reporting. Fixed in rc-table@6.1.3, try reinstall your dependencies.
