### ISSUE TITLE
Select 做前端搜索时候是否可以加个显示 Option 的个数?

### ISSUE THREAD

**Issue by samchanye** [ant-design/ant-design#8944]
### What problem does this feature solve?
如果条目较多, 会卡顿, 自己做了 slice 切个条目之后就不卡了?

### What does the proposed API look like?
当有 filterOption props 时, 判断 props => maxFilterOptions:number 是否有, 若有则筛选之后的结果最多显示 maxFilterOption 条

**Comment by yesmeck** [comment]
自己实现下 `filterOption` 即可。

**Comment by samchanye** [comment]
@ant-design-bot ok, I'll pay attention next time.

**Comment by samchanye** [comment]
@yesmeck let me think
