### ISSUE TITLE
Menu组件中的SubMenu下拉菜单在nextjs的page页面中会全屏显示

### ISSUE THREAD

**Issue by Zegapaiz** [ant-design/ant-design#8945]
### Version
3.1.1

### Environment
macOS Sierra 10.12.2, Google Chrome 63.0.3239.132（正式版本） （64 位）

### Reproduction link
[https://github.com/Zegapaiz/antd-Issue-Helper-small.git](https://github.com/Zegapaiz/antd-Issue-Helper-small.git)

### Steps to reproduce
下载项目后npm start 在本地 端口9000 就能看到页面，鼠标滑动到文章上就可以看到SubMenu下拉菜单沾满了全屏
![image](https://user-images.githubusercontent.com/12904995/34858963-5e3fa23c-f78e-11e7-88a9-4e82d016fd33.png)

### What is expected?
如官网示例中，SubMenu下拉菜单有合适固定的宽度

### What is actually happening?
SubMenu下拉菜单沾满了全屏

**Comment by yesmeck** [comment]
You are using wrong css https://github.com/Zegapaiz/antd-Issue-Helper-small/blob/master/pages/index.js#L52
