### ISSUE TITLE
树形table与拖拽冲突

### ISSUE THREAD

**Issue by teeemooo** [ant-design/ant-design#8947]
### Version
3.1.1

### Environment
chrome antd最新

### Reproduction link
[http://null.pointer](http://null.pointer)

### Steps to reproduce
可拖拽table采用树结构数据导致展开按钮失效

### What is expected?
期望实现类似extjs的treegrid的可拖拽树形表格

### What is actually happening?
应用拖拽后无法正常展开关闭节点

**Comment by yesmeck** [comment]
你这个范围太大了，要提具体的 bug。

**Comment by fenghuizhang** [comment]
I have the same problem, still have no idea how to solve it

**Comment by souldjl** [comment]
这个现在都没解决

**Comment by souldjl** [comment]
@teeemooo 不知你最后怎么处理了 @fongfai
