### ISSUE TITLE
Table 设置pagination的current的值，用浏览器的前进后退，偶尔出现多个激活button，点击页面才能消失

### ISSUE THREAD

**Issue by lixuguang88** [ant-design/ant-design#8948]
### Version
3.1.1

### Environment
window7、chrome、react-router4

### Reproduction link
[https://github.com/lixuguang88/blog/tree/master/react/antd/table](https://github.com/lixuguang88/blog/tree/master/react/antd/table)

### Steps to reproduce
1. 注册Table pagination的onChange事件， 更改页面search的值，同是更新 pagination.current 值，
2. componentDidUpdate 里面比对两次search的值，更新 pagination.current 值，

*  用浏览器的前进，后退，偶尔出现多个激活button，点击页面才能消失
* table loading =true 的时候出现滚动条 . [更改样式](https://github.com/ant-design/ant-design/blob/master/components/spin/style/index.less#L26) 添加left：0;

主要代码 ：
```js

  componentDidUpdate(prevPrpos){
    const search = this.props.location.search;
    if(search !== prevPrpos.location.search){
      //不同page
      let page =  search  ?  parseInt(search.slice(6), 10) : 1;
      this.setState({
        current: page
      })
      this.fetchData(page)
    }
  }

  pagerChange(current){
    const { history, match} = this.props;
    if(current){
      history.push({
        pathname: match.url,
        search: `?page=${current}`
      })
    }
    this.setState({
      current: current
    })
  }

  render(){
    let match = this.props.match;
    let columnRender = columns(match.url);

    return (
      <div style={{width: 1200, margin: '50px auto'}}>
        <Table bordered pagination={{
          current: this.state.current,
          total: 100,
          onChange: e => this.pagerChange(e)
        }} loading={this.state.ajax} 
        columns={columnRender} 
        dataSource={this.state.data}
        rowKey={record => record.id}
      />
     </div>
    )
  }
```

### What is expected?
不要出现多个激活按钮
没有滚动条

### What is actually happening?
![多个激活按钮](https://user-images.githubusercontent.com/3655386/34861325-069bf7d6-f79f-11e7-93a1-7e2ea196065d.png)
![滚动条](https://user-images.githubusercontent.com/3655386/34861365-4b1d44fa-f79f-11e7-8d8c-2602e120fe66.png)

**Comment by yesmeck** [comment]
单独使用 Pagination 也会有这个问题。

**Comment by dkvirus** [comment]
I've had this problem, too.

**Comment by muzea** [comment]
稍微糊了一个dome  https://codesandbox.io/s/zn877w5093 ，这边应该是因为有个focus的样式在上面

![focus style bug](https://user-images.githubusercontent.com/7843281/37813543-7ce35aaa-2ea0-11e8-8407-8748f0c70b4f.png)

我觉得用户点击之后移除focus就行（英语还是拙计啊

-------

[Reproduction link](https://codesandbox.io/s/zn877w5093)  This bug is because there is a focus style on it.
I think can remove focus after user clicking.

**Comment by pkl93** [comment]
不仅是前进后退， 在我这快速地连续翻页也容易出现 2 个按钮同时被激活的情况
