### ISSUE TITLE
在table组件的render方法中，如何使用this值

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#8950]
### What problem does this feature solve?
我想通过this.state改变表格操作的图标按钮，比如<Icon type="plus"  onClick={() => this.addRole(record.key)}/> 改成<Icon type="minus" onClick={() => this.delRole(record.key)}/>，怎么去使用this.state去实现三元表达式，会提示this is a reserved word

### What does the proposed API look like?
怎么使用呢

**Comment by yesmeck** [comment]
https://reactjs.org/docs/faq-functions.html#how-do-i-bind-a-function-to-a-component-instance
