### ISSUE TITLE
Bigger default font size vs. Responsiveness

### ISSUE THREAD

**Issue by aaronplanell** [ant-design/ant-design#8951]
### Version
3.1.1

### Environment
Linux Ubuntu 4.4.0-104-generic with Chrome 63.0.3239.132 (Build oficial) (64 bits)

### Reproduction link
[https://github.com/aaronplanell/cra-antd-v3-size](https://github.com/aaronplanell/cra-antd-v3-size)

### Steps to reproduce
```
yarn
yarn start
```

### What is expected?
It will appear an example of the component ButtonSize with green color and size 12px.

### What is actually happening?
Hello,

As you know, Antd v.3 increased the size of the components. For instance, the @font-size-base was 12px and nowadays is 14px. I updated a project that has a lot of responsive displays and now all the media queries are wrong :/. I tried set the font-size-base to 12px with less variables (see project attached) and works... for the text. The buttons have the same size :_(

Do you have any `config-overrides.js` configuration for setting the same sizes to the previous version of Antd. What I mean, I want update to v.3 using the same sizes than in v.2.

Thanks a lot for your answer!

Best regards,
Aaron Planell

**Comment by afc163** [comment]
> setting the same sizes to the previous version of Antd

Sorry, I think you have to stick in antd@2.x if you need exact same size of component.
