### ISSUE TITLE
Form fieldDecorator seems buggy when dynamic show

### ISSUE THREAD

**Issue by pannz** [ant-design/ant-design#8952]
### Version
3.1.1

### Environment
browser

### Reproduction link
[https://codesandbox.io/s/lpmzy960nm](https://codesandbox.io/s/lpmzy960nm)

### Steps to reproduce
initial is
test0: Open
test1: hello
test2: world

1)
when test0 select to Closed, test2 will not shown  
so, select to Pending, everything is OK  
select to Closed, test2 not shown, this is right behavior  
but, when reSelect to not-Closed option, Open/Pending,  the test2 will be null, it should be 'world'

2)
and if you input some value in test2, 'good', or whatever 
then select to Closed, test2 not shown, reSelect to Open/Pending, the test2 still null, not expected 'good'

it seems when change the field show, it will affect the field value.

### What is expected?
1)  test2: 'world'
2)  test2: 'good' 

### What is actually happening?
test2: null

**Comment by afc163** [comment]
I think it is a correct behavior cause the initial value of test2 is rendered in first render. And when select is changed to `closed`, input test2 is destroyed with its value, meanwhite `mapPropsToFields` was not executed during whole time.

Here is a workaround, use `display: none` to hide `test2`.

**Comment by pannz** [comment]
OK, accept !
It means when a child component destroyed, the form value will be set to null as well.
Or it can add an `initialValue` to init the input value every time the component remount, and that is just an init value
