### ISSUE TITLE
Missing the Instagram icon

### ISSUE THREAD

**Issue by akolybelnikov** [ant-design/ant-design#8959]
### What problem does this feature solve?
It is one of the icons that should not be missed

### What does the proposed API look like?
http://fontawesome.io/icon/instagram/

**Comment by dengfuping** [comment]
@akolybelnikov You can use the [Instagram icon fonts](http://www.iconfont.cn/search/index?q=instagram) temporarily. Adding the instagram icon will be considered.

**Comment by luco** [comment]
+1 on this.

**Comment by afc163** [comment]
trace #9092
