### ISSUE TITLE
Cascader 能不能可以不选择叶子节点？

### ISSUE THREAD

**Issue by Jeffy2012** [ant-design/ant-design#896]
比如有三级节点，我只想选择到第一级节点

**Comment by afc163** [comment]
自行裁剪数据，当选择项没有 children 时，会直接选中。

**Comment by Jeffy2012** [comment]
意思是我可以选择到任意节点，而不是只能选择到叶子节点

**Comment by afc163** [comment]
可以手动指定中间节点为叶子节点：https://github.com/react-component/cascader/blob/master/examples/dynamic-options.js#L9

**Comment by yiminghe** [comment]
是既可以选择叶子节点，又可以选择指定中间节点的意思吧

**Comment by afc163** [comment]
正在咨询设计师。

**Comment by afc163** [comment]
贴一下旺旺的交流：

![](https://os.alipayobjects.com/rmsportal/JaRzCsEZAmdqXYS.png)

**Comment by afc163** [comment]
已咨询设计师，建议在下一级放『所有xx』来解决，交互上比较直观合理。目前业务上可自行添加数据。cascader 组件需要考虑一下是否可以支持自动生成这个『所有xx』。

**Comment by afc163** [comment]
@Jeffy2012 

### 最终解决方案

参照淘宝收货地址增加了一种交互形式，选择任何选项都将直接上到输入框中，这样可以实现选择父级节点。

![](https://os.alipayobjects.com/rmsportal/tGBOjxHnNiJlXKO.png)

![](https://os.alipayobjects.com/rmsportal/qQgguxgWizldiIO.png)

有选中父级选项即完成的需求，添加 `changeOnSelect` 属性即可。

```jsx
<Cascader changeOnSelect />
```

交互方式可参考：http://react-component.github.io/cascader/examples/change-on-select.html
