### ISSUE TITLE
Page number don't reset to 1 when dataSource changed

### ISSUE THREAD

**Issue by jiacai2050** [ant-design/ant-design#8963]
### Version
3.0.1

### Environment
chrome

### Reproduction link
[https://github.com/jiacai2050/history-master](https://github.com/jiacai2050/history-master)

### Steps to reproduce
I use a table component to display browsing history items in one day, when I was at page 2, and changed to another day, apparently the data is different, but I was still at page 2 not page 1.

### What is expected?
when data changed, page number reset to 1

### What is actually happening?
when data changed, page number remains.

**Comment by yesmeck** [comment]
It's intended. You need reset it by yourself.

**Comment by jiacai2050** [comment]
Thanks. I found solution in  https://github.com/ant-design/ant-design/issues/335
