### ISSUE TITLE
Module not found: Can't resolve 'antd/es/content'

### ISSUE THREAD

**Issue by Mr-Kapok** [ant-design/ant-design#8965]
### Version
3.1.3

### Environment
dva-cli:0.9.2    

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
按照实战项目使用dva-cli创建项目，项目能够成功启动。
当我尝试使用antd模块的时候，项目报错，错误提示如下:
Module not found: Can't resolve 'antd/es/content' in 'D:\workspace\YunShlStore\src\routes'

### What is expected?
成功编译启动

### What is actually happening?
编译失败

**Comment by yesmeck** [comment]
没有 content 这个组件的。

**Comment by yesmeck** [comment]
```javascript
import { Layout } from 'antd';
const { Header, Footer, Sider, Content } = Layout;
```

**Comment by Mr-Kapok** [comment]
```
import React from 'react';
import {connect} from 'dva';
import {Layout,Header,Sider,Content,Footer} from 'antd';


function IndexPage() {
  return (
    <Layout>
      <Header>header</Header>
      <Layout>
        <Sider>left sidebar</Sider>
        <Content>main content</Content>
        <Sider>right sidebar</Sider>
      </Layout>
      <Footer>footer</Footer>
    </Layout>
  );
}

IndexPage.propTypes = {};

export default connect()(IndexPage);
```

**Comment by afc163** [comment]
@Mr-Kapok 按演示的写法来，不要发明代码。

**Comment by Mr-Kapok** [comment]
@yesmeck @afc163 谢谢,自己看错了！
