### ISSUE TITLE
echarts中的ChartShowLoading组件，自适应有问题

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design#8971]
### Version
3.1.3

### Environment
win10,chrome

### Reproduction link
[http://antd-admin.zuiidea.com/chart/ECharts](http://antd-admin.zuiidea.com/chart/ECharts)

### Steps to reproduce
1、http://antd-admin.zuiidea.com/chart/ECharts
2、选择ChartShowLoading组件，等【加载中】消失，然后F12调试
3、加载中会再次出现，且不会消失

### What is expected?
加载中需要消失掉

### What is actually happening?
加载中没有消失

**Comment by afc163** [comment]
It is not related with antd.
