### ISSUE TITLE
ant.design bug

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design#8973]
### Version
undefined

### Environment
win7，chrome

### Reproduction link
[https://ant.design/components/notification-cn/](https://ant.design/components/notification-cn/)

### Steps to reproduce
1、https://ant.design/components/notification-cn/
2、“Placement”，select “topLeft”
3、"Customized style"click button “Open the notification box”
this notification box show order the Windows

### What is expected?
this notification box show in the Windows

### What is actually happening?
this notification box show order the Windows

**Comment by valleykid** [comment]
Sorry, I don't think it is a bug.

**Comment by yesmeck** [comment]
It's not bug. The "Customized style" demo is customized for `topRight` placement.

**Comment by xiaohuoni** [comment]
hehe

**Comment by xiaohuoni** [comment]
@yesmeck @valleykid

**Comment by tiffon** [comment]
Maybe the "Customized style" demo should just change the background color, then? That way it will work in any placement. (I thought it was a bug, too.)

**Comment by yesmeck** [comment]
@tiffon Could you send a PR?
