### ISSUE TITLE
antd DatePicker not work within locale

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#8975]
### Version
3.1.3

### Environment
node6.1

### Reproduction link
[https://codesandbox.io/s/0xz3nwxymv](https://codesandbox.io/s/0xz3nwxymv)

### Steps to reproduce
https://codesandbox.io/s/0xz3nwxymv

### What is expected?
show language by specified

### What is actually happening?
some language show the english, not my specified language.

---
it's a bug or my problem?
i had use `LocaleProvider`, it not work.
i had use `locale` for `DatePicker`, it's not work.
if i to use `moment`, it's show my specified language, but had to need a default value.

**Comment by ddcat1115** [comment]
You miss `import 'moment/locale/zh-cn';`

Please check the [API note](https://ant.design/components/date-picker/#API)

**Comment by didmehh** [comment]
I don't think so.
i had try to `import` in my `entry` js file. 
- for first example:
```javascript
...
import {LocaleProvider} from 'antd'
import zhCN from 'antd/lib/locale-provider/zh_CN';
import 'moment/locale/zh-cn';

ReactDOM.render(
  <Provider store={store}>
    <LocaleProvider locale={zhCN}>
      <App />
    </LocaleProvider>
  </Provider>,
  document.getElementById('root')
);
``` 
if's not work.

- for second example
i had try to `import` within specific js file for `DatePicker`

```javascript
...
// Date.js
import zhCN from 'antd/lib/locale-provider/zh_CN';
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');

...
render(){
  return(
     <Form>
        <FormItem {...formItemLayout} label="年月" hasFeedback validateStatus="">
        {getFieldDecorator("month",{
          initialValue: ""
        })(
          <MonthPicker locale={zhCN}/>
        )}

        </FormItem>
    </Form>
  )
}
```
It's not work too.

**Comment by didmehh** [comment]
https://github.com/ant-design/ant-design/issues/8816
4 days ago had merged.  
I try to update to `3.1.2`. It's work.
