### ISSUE TITLE
How to implement insert content in TextArea by current focus

### ISSUE THREAD

**Issue by ZiHi** [ant-design/ant-design#8977]
### What problem does this feature solve?
Ref as title
Something like Sina Weibo‘s comment textArea，which allow insert '@' or emoji (xxx[cry]x) in anywhere (usually on focus) when typing content.  Some Rich Content?

### What does the proposed API look like?
There is some callback function or other solutions，maybe

**Comment by ddcat1115** [comment]
Describe your demands in more detail please.

**Comment by ZiHi** [comment]
Something like Sina Weibo‘s comment textArea，which allow insert '@' or emoji (xxx[cry]x) in anywhere (usually on focus) when typing content. Some Rich Content?

**Comment by ddcat1115** [comment]
Maybe you need https://ant.design/components/mention/ ?

**Comment by ZiHi** [comment]
Oh ............My fault !
