### ISSUE TITLE
表格排序的图标点击的区域超出表头的范围

### ISSUE THREAD

**Issue by zichen-cici** [ant-design/ant-design#8979]
### Version
3.1.3

### Environment
win10
node 9.3.0

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-reset-filter](https://ant.design/components/table-cn/#components-table-demo-reset-filter)

### Steps to reproduce
https://ant.design/components/table-cn/#components-table-demo-reset-filter 点击表格排序

### What is expected?
点击区域不超出表头的范围

### What is actually happening?
点击区域超出表头的范围

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/commit/913daa2668

@afc163 这个 commit 改掉的，是啥原因改的？

**Comment by afc163** [comment]
表头少加了 `overflow: hidden`。
