### ISSUE TITLE
如何使用CSSTransitionGroup？

### ISSUE THREAD

**Issue by man0sions** [ant-design/ant-design#898]
如何使用CSSTransitionGroup，在框架中
![image](https://cloud.githubusercontent.com/assets/2936472/12444034/4b6965de-bf97-11e5-9933-28d3431ae060.png)
在console中一直
![image](https://cloud.githubusercontent.com/assets/2936472/12444055/696610f0-bf97-11e5-8426-8f1d7b18d44c.png)

而且动画效果也没出来
css如下
![image](https://cloud.githubusercontent.com/assets/2936472/12444076/7a9dc8ae-bf97-11e5-9b56-8317a493dc10.png)

**Comment by afc163** [comment]
和 Ant Design 没有联系，去 React 论坛提问。

**Comment by man0sions** [comment]
谢谢！
已解决，或许对别人有帮助。
![image](https://cloud.githubusercontent.com/assets/2936472/12444280/081bc13a-bf99-11e5-95a8-706fd4638725.png)
