### ISSUE TITLE
table style bug with bordered: true and size: 'small'

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#8980]
### Version
3.1.3

### Environment
latest

### Reproduction link
[https://codesandbox.io/s/k5omv9rlno](https://codesandbox.io/s/k5omv9rlno)

### Steps to reproduce
set bordered to `true` and size to `small`

### What is expected?
table body is align to column Header

### What is actually happening?
table body is not align to column Header

**Comment by SwordsmanYao** [comment]
+1

**Comment by wSLecHayfIeNdock** [comment]
Add border to Small size table.
@yesmeck [Grouping table header columns children no `border-right`. Demo:](https://codesandbox.io/s/z379omn9pp)

![image](https://user-images.githubusercontent.com/16831715/37266274-25a0be5e-25f4-11e8-8b47-fca629200c78.png)

**Comment by turenc** [comment]
Hi, Grouping table header columns children no border-right. How must we fixed it?
