### ISSUE TITLE
Table api about 'minWidth'

### ISSUE THREAD

**Issue by cyzeng-Luca** [ant-design/ant-design#8981]
### What problem does this feature solve?
i want to decide minWidth to solve cell in newline Instead of limiting a fixed width. i'm glad to use the default responsive width without setting attribute width but if the width equal to the minWidth,i want to it is a fixed vaule what i set.

### What does the proposed API look like?
hava a api like minWidth in Column.

**Comment by nikogu** [comment]
You can set the `css style` for it directly.

**Comment by spector32** [comment]
What if I need one column to stay at certain width letting all other columns to stretch depending on the window width and not having a break wrap?

**Comment by peleisgit** [comment]
still nothing? Any resolution?

**Comment by leiyangs** [comment]
还没有这个api

**Comment by MarianCN** [comment]
please up

**Comment by cnt-null** [comment]
Perhaps someone will find this method useful.

```jsx
const columns = [
  { title: 'A', dataIndex: 'a', width: 100 },
  { title: 'B', dataIndex: 'b' },
  { title: 'C', dataIndex: 'c' },
  { title: 'D', dataIndex: 'd', width: 200 },
];
const totalFixedWidth = columns.reduce((result, { width }) => result + (width ?? 0), 0);
const minResponsiveWidth = 500;
return <Table columns={columns} scroll={{ y: totalFixedWidth + minResponsiveWidth }} />;

```

When there is enough space, the responsive columns will stretch, and if there is not enough space, a scroll will appear, preventing them from collapsing.
