### ISSUE TITLE
select选择器在IE11浏览器下，点击选择框的上下箭头，或者拖动滚动条，选择框自动消失

### ISSUE THREAD

**Issue by tianlang89757** [ant-design/ant-design#8984]
### Version
3.1.3

### Environment
windows7、IE11浏览器

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
select选择器在IE11浏览器下，点击选择框的上下箭头，或者拖动滚动条，选择框自动消失

### What is expected?
在IE11浏览器下，点击选择框的上下箭头，或者拖动滚动条，选择框能正常使用

### What is actually happening?
目前点击选择框的上下箭头，或者拖动滚动条，选择框自动消失

**Comment by afc163** [comment]
Duplicate of #7934

**Comment by tianlang89757** [comment]
There is still a problem with Internet explorer's Edge document mode.

**Comment by tianlang89757** [comment]
@afc163 这个问题我已经解决了，解决方法是删除antd.css样式表里面的.ant-select-dropdown-menu样式下的overflow:auto样式，就能解决IE11浏览器Edge文档模式下拖动滚动条选择框消失的问题
