### ISSUE TITLE
handle submit outside of HOC Form

### ISSUE THREAD

**Issue by bnerDY** [ant-design/ant-design#8986]
### What problem does this feature solve?
it seems there is no way to trigger handleSubmit outside of HOC form. 

### What does the proposed API look like?
<WrapperedForm triggerSubmit = {()=>{ do something.}} />

**Comment by ddcat1115** [comment]
By storing form data into upper component, you can trigger the submit action outside of Form. https://ant.design/components/form/#components-form-demo-global-state

**Comment by bnerDY** [comment]
@ddcat1115 any example by doing this.?
currently i am doing stuff like
```
<Myform onMount={c => (this.Myform = c)} />;
//some actions like

onClick()=>{
  this.Myform.handleSubmit()
}

//in my child component

class wrapperForm extends PureComponent{
  componentDidMout(){
    this.props.onMount(this)
  }
}
```

it actually return error or value from lower component. but it will not automatically shows the warning on the screen like your demo did.

i can only view the validation through console. Any alternative solution?
![image](https://user-images.githubusercontent.com/5085327/35028906-3e454ac8-fb93-11e7-9378-7caae19d49c6.png)

**Comment by ddcat1115** [comment]
upper link is a demo

**Comment by bnerDY** [comment]
@ddcat1115  do you mean call submit by ref?

<img width="1176" alt="screen shot 2018-01-17 at 5 20 22 pm" src="https://user-images.githubusercontent.com/5085327/35034961-cc1248bc-fbaa-11e7-81ce-52bd35f96ada.png">

However, it telling me about this when I trigger submit function

**Comment by ddcat1115** [comment]
https://ant.design/components/form/#components-form-demo-global-state

**Comment by bnerDY** [comment]
@ddcat1115 https://codesandbox.io/s/5wl6wpw4wl
It seems the can only trigger onchange and relative fields value? is there any solutions for submit?

**Comment by mgrdevport** [comment]
There is no need to store the data outside of the form by using a ref:
[https://codesandbox.io/s/l4qny89x6m](https://codesandbox.io/s/l4qny89x6m)

**Comment by bnerDY** [comment]
@mgrdevport  thanks a lot!

**Comment by Triyugi** [comment]
@mgrdevport  I am not getting it work into redux. In redux, `refs` doesn't seems to be working.
