### ISSUE TITLE
Is there any way to make Cascader supports custom input?

### ISSUE THREAD

**Issue by secreter** [ant-design/ant-design#8988]
### What problem does this feature solve?
We use Cascader to select json path,but sometimes ,we need to input a custom path .

### What does the proposed API look like?
Add an attribute name input ,when input={true}, Cascader  can save the custom result.

**Comment by afc163** [comment]
Try to customize trigger: https://ant.design/components/cascader/#components-cascader-demo-custom-trigger

**Comment by secreter** [comment]
Thanks for your answer,it does work!But I find a problem,I'm not sure if it is a bug ,when I nest an Input in Cascader,it can input letter with no problem ,but when I want to delete it ,I typed 'Backspace' key,it didn't work.That is mean it can input but can't delete.
```
class CitySwitcher extends React.Component {
    constructor (props){
        super(props)
        this.state = {
            text: 'Unselect',
          };
    }
  onChange = (value, selectedOptions) => {
    this.setState({
      text: selectedOptions.map(o => o.label).join(', ')
    });
  }
  render() {
    return (
      <span>
      <Input />
        {this.state.text}
        <Cascader showSearch options={options} onChange={this.onChange}>
            <Input />   
        </Cascader>
      </span>
    );
  }
}
```

**Comment by secreter** [comment]
It's really a bug ,I test then find,when I input something,the Input box get focused,but when I type  'Backspace' key,the Cascader get focused。It's so upset,my problem is still there.

**Comment by marlti7** [comment]
> It's really a bug ,I test then find,when I input something,the Input box get focused,but when I type 'Backspace' key,the Cascader get focused。It's so upset,my problem is still there.



> Thanks for your answer,it does work!But I find a problem,I'm not sure if it is a bug ,when I nest an Input in Cascader,it can input letter with no problem ,but when I want to delete it ,I typed 'Backspace' key,it didn't work.That is mean it can input but can't delete.
> 
> ```
> class CitySwitcher extends React.Component {
>     constructor (props){
>         super(props)
>         this.state = {
>             text: 'Unselect',
>           };
>     }
>   onChange = (value, selectedOptions) => {
>     this.setState({
>       text: selectedOptions.map(o => o.label).join(', ')
>     });
>   }
>   render() {
>     return (
>       <span>
>       <Input />
>         {this.state.text}
>         <Cascader showSearch options={options} onChange={this.onChange}>
>             <Input />   
>         </Cascader>
>       </span>
>     );
>   }
> }
> ```

same problem;.cant delete char in input; do you fixed it?
