### ISSUE TITLE
Can component -tree select multiple units at the same time?

### ISSUE THREAD

**Issue by Linbubin** [ant-design/ant-design#8990]
### What problem does this feature solve?
I see the onSelect function the `selectedKeys` is a array, does it mean that you can choose two(more) at the same time.

why need:
because I not only want to check the row to do something, but also want to select the rows(MultiLine) to see something about it.

### What does the proposed API look like?
when the `selectedKeys.length > 1`, it can choose many line at the same time.

I tried to pass in a complex array, but that didn't work.

**Comment by yesmeck** [comment]
`<Tree multiple />`

**Comment by yesmeck** [comment]
You need set `multiple` to `true`.
