### ISSUE TITLE
if there has a Tabs in the Popover,the first active TabPane's underline is in the wrong position.

### ISSUE THREAD

**Issue by Alice2222** [ant-design/ant-design#8992]
### Version
3.1.0

### Environment
react@15.x   chrome@63.0.3239.132   antd@3.1.0 MacBook Pro

### Reproduction link
[https://codepen.io/anon/pen/GyYvap](https://codepen.io/anon/pen/GyYvap)

### Steps to reproduce
点击重现连接的bell图标，然后出先popover，在popover里有tabs,tabs的默认active第一个tabpane下划线位置不对。除此之外，如果改变tabs的默认值为2，那么active的tabpane显示也不正确。

### What is expected?
能在正下方

### What is actually happening?
偏左了

**Comment by ddcat1115** [comment]
Something wrong with the ink bar style... But actually I think the a Tabs is too heavyweight for a Popover.

**Comment by Alice2222** [comment]
but it is used like this in your official ant design pro.

**Comment by bradabelgit** [comment]
+1 

Running into the same thing. I am also referencing it from ant design pro. It's only on the initial render. Once you have tabbed back and forth things are fine.

**Comment by bradabelgit** [comment]
Seems to be fixed in 3.2.0

**Comment by osvald0** [comment]
I have the same issue with the last version.

**Comment by NikFranki** [comment]
I have the same problem

**Comment by zombieJ** [comment]
fixed in `rc-tabs@9.4.2`: https://codesandbox.io/s/2zmnqx1nyp
