### ISSUE TITLE
antd tree我认为应该需要一个自定义属性可以用来添加对每个分支进行可操作的控制的按钮

### ISSUE THREAD

**Issue by ITGraves** [ant-design/ant-design#8997]
### What problem does this feature solve?
用户需要在tree上面直接进行编辑该分支的时候，可以添加这个菜单项

### What does the proposed API look like?
<Tree renderContent={(...args)=>renderContent(...args)}/>
const renderContent = (...) => {
  //return 自定义的组件
}

**Comment by yesmeck** [comment]
TreeNode[title] 可以是 ReactNode 的。

**Comment by yesmeck** [comment]
参考 http://react-component.github.io/tree/examples/basic.html

**Comment by t880216t** [comment]
自己写了个，有需要可以参考下。
[antd tree 增加编辑菜单](https://orion-c.top/2018/05/09/ant_design_tree/)
