### ISSUE TITLE
Table使用会报错，其他组件测试是好的，antd版本3.1.1

### ISSUE THREAD

**Issue by WALLE729** [ant-design/ant-design#8999]
### Version
3.1.1

### Environment
mac

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
引用Table模块就会报错

### What is expected?
正常使用组件

### What is actually happening?
报错：
Failed to compile
./node_modules/antd/lib/spin/style/index.css
Module build failed: 

  /* autoprefixer: off */
  filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
              ^
Unrecognised input
      in /Users/walle/WorkZoom/newreactsite/node_modules/antd/lib/spin/style/index.css (line 85, column 16)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4915#issuecomment-283176932
