### ISSUE TITLE
组件开发计划

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#9]
## 一期（6月15日）：

- [x] [首页](http://ant.design/)
- [x] [iconfont](http://ant.design/components/iconfont/)
- [x] [layout](http://ant.design/components/layout/)
- [x] [button](http://ant.design/components/button/) 
- [x] [dropdown](http://ant.design/components/dropdown/)
- [x] [datepicker](http://ant.design/components/datepicker/)
- [x] [tooltip](http://ant.design/components/tooltip/)
- [x] [select](http://ant.design/components/select/)
- [x] [tabs](http://ant.design/components/tabs/)
- [x] [progress](http://ant.design/components/progress/)
- [x] [modal + confirm](http://ant.design/components/modal/)

## 二期（7月15日）：

- [x] [工程化](https://github.com/ant-design/antd-bin)
- [x] [动画方案](http://ant.design/components/motion/)
- [x] [input 输入框](http://ant.design/components/form/)
- [x] [checkbox 多选](http://ant.design/components/checkbox/)
- [x] [radio 单选](http://ant.design/components/radio/)
- [x] [form 表单](http://ant.design/components/form/)
- [x] [pagination 分页](http://ant.design/components/pagination/)
- [x] [table 表格](http://ant.design/components/table/)
- [x] [popover 气泡卡片](http://ant.design/components/popover/)
- [x] [popconfirm 气泡确认框](http://ant.design/components/popconfirm/)
- [x] [slider 滑动条](http://ant.design/components/slider/)
- [x] [switch 开关](http://ant.design/components/switch/)
- [x] [message 全局消息通知](http://ant.design/components/message/)
- [x] [step 步骤条](http://ant.design/components/steps/)
- [x] [collapse 折叠面板](http://ant.design/components/collapse/)
- [x] [inputNumber 数字输入框](http://ant.design/components/inputNumber/) 
- [x] [breadcrumb 面包屑](http://ant.design/components/breadcrumb/)

## 三期（8月05日）：

- [x] menu 导航菜单
- [x] upload 上传
- [x] carousel 走马灯
- [x] tree 树形控件
- [x] notification 通知框
- [x] validation 表单校验
- [x] affix 悬停
- [x] alert 消息样式
- [x] enterAnimation 进场动效
- [x] 色板
- [x] 排版

## 正式发布（8月25日）`0.8.0`

正式发布上线。

## 四期（9月15日）`0.9.0`

补充几个新组件，完善旧组件的演示。

- [x] timeline 时间轴
- [x] badge 通知数字

已有组件补充：

- [x] table 表格折叠区域
- [x] step `竖版`
- [x] radio `button style`

##  五期（10月15日）`0.10.0`

- [ ] calendar 日历面板
- [ ] timepicker 时间选择

**Comment by jay61439476** [comment]
加油！

**Comment by chenboxiang** [comment]
加油！

**Comment by jumplee** [comment]
ajaxlist 组件或许应该在一期。pagination 分页表示用不到。。。

**Comment by luqin** [comment]
:+1: 支持

**Comment by Suixinlei** [comment]
加油！

**Comment by chenerzhang** [comment]
支持！

**Comment by rubyless** [comment]
支持下.

**Comment by hui** [comment]
加油加油

**Comment by zlyi** [comment]
谢谢，这将是个了不起的工作。加油

**Comment by next2014** [comment]
非常棒

**Comment by Tinker404** [comment]
看到这个框架简直被惊艳了，但是无奈新手用不太来，文档也是面向有一定基础的人，希望能加入新手向的教学，另外求一个QQ讨论群

**Comment by okoala** [comment]
赞啊，拿来做管理后台了，小清新 :smile:

**Comment by jay61439476** [comment]
很赞，  想请教下 浏览器兼容性如何， 最近被IE折腾的不行

**Comment by clarkhan** [comment]
@jay61439476 和 react 一样，IE8+ 。对于 IE8，需要提供 es5-shim 等 Polyfills 的支持。

**Comment by jay61439476** [comment]
@clarkhan 了解  最近正在看React, 偶然找到了你们的这么库  惊艳至极  加油！ :+1:

**Comment by clarkhan** [comment]
@jay61439476 误会了，我不是开发者。感谢他们保持开放的态度，持续的贡献了那么多优秀的开源作品。

**Comment by tindytian** [comment]
:+1:

**Comment by next2014** [comment]
能做了移动日期的插件么？效果是点选择时间日期时，组件在屏幕下方固定位置里选择时期时间地域等

**Comment by elevensky** [comment]
作为一个国内顶尖前端和可怕执行力的团队。努力学，希望后期帮助文档多点。

**Comment by ecafe8** [comment]
希望加入图表组件.

**Comment by to0ld** [comment]
这个库的样式及布局是支持响应式的么？能自适应pc&mobile么？

**Comment by colincatsu** [comment]
comgrid非常常用

**Comment by colincatsu** [comment]
希望开发好了可以替代easyui

**Comment by airwin** [comment]
不错的UI库，React用户的福音

**Comment by transtone** [comment]
markdown 编辑器没在列？editor.md，github的编辑器，codding.net的编辑器，知乎的编辑器都不错，好歹也参考一个吧。

**Comment by qq157788394** [comment]
加油！

**Comment by WenXuanYuan** [comment]
有莫有qq群呀，求加入

**Comment by panlw** [comment]
我们现在也在用 React+Webpack 做开发，
看到你们的部件库已经非常丰富，尝试使用一把。
你们有微信群吗？求加入:)

**Comment by afc163** [comment]
建议在 issues 上进行讨论，方便搜索引擎索引，造福更多人。

**Comment by humanhuang** [comment]
Up :)

**Comment by aidenzou** [comment]
ant-design qq群：425818130

**Comment by hazelGranger** [comment]
赞赞赞

**Comment by Liu-Huaqing** [comment]
太赞了，简直造福人类啊~

**Comment by kevinxh** [comment]
请问现在有哪个网站在用这个库吗? 很赞!

**Comment by afc163** [comment]
蚂蚁金服的中后台系统大量使用。

**Comment by laurieliu** [comment]
颜色比较淡，主要对比度不强烈，看起来比较费劲，但是整个框架很淡雅，先支持一下

**Comment by quany** [comment]
支持

**Comment by honger05** [comment]
支持

**Comment by kylezhang** [comment]
在form组件中使用input,并且required: true, 那么在输入中文的时候回出现一大推的拼音，这怎么回事呢？

**Comment by kylezhang** [comment]
群名称：antd.design
群   号：374962734
方便快速交流，issue有时太慢了
