### ISSUE TITLE
css file modularize

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#900]
# antd

```
src
├── README.md
├── components
│   ├──button
│            ├── style
│                      ├── index.js
│                      ├── index.less
│            ├── index.js
│   ├──dropdown
│            ├── style
│                      ├── index.js
│                      ├── index.less
│            ├── index.js
├── style
│   ├──index.js
│   ├──index.less
│   ├──effect.less
│   ├──variable.less
│   ├──mixin.less
```

## style/index.js
```js
import 'normalize.css';
import './index.less'
```
## button/style/index.less
```less
@import '../../style/variable.less';
@import "../../style/mixin.less";
// button' less
```

## button/style/index.js
```js
import "./index.less";
```

## dropdown/style/index.less
```less
@import '../../style/variable.less';
@import "../../style/mixin.less";
// dropdown' less
```
## dropdown/style/index.js
```js
import "../../button/style";
import "./index.less";
```

# publish antd

```
├── lib
│   ├──button
│            ├── style
│                      ├── index.js
│                      ├── css.js
│                      ├── index.less
│                      ├── index.css
│            ├── index.js
├── style
│   ├──css.js
│   ├──index.css
│   ├──index.js
│   ├──index.less
│   ├──effect.less
│   ├──variable.less
│   ├──mixin.less
```

style/css.js

```js
require('./index.css');
```

lib/button/style/css.js

```js
require('./index.css');
```

# using antd
### entry
```js
import 'antd/style';
```
### component A
```js
import {dropdown} from 'antd';
```

### entry

```js
require('antd/style');
```

### component A
```js
var Dropdown = require('ant/lib/dropdown');
require('antd/lib/dropdown/style')
```

**Comment by yiminghe** [comment]
https://medium.com/front-end-developers/css-modules-solving-the-challenges-of-css-at-scale-85789980b04f#.2r1qq64oi

**Comment by benjycui** [comment]
以下几个点觉得需要讨论：

1. 如果使用 CSS Modules，因为 [Composition](https://github.com/css-modules/css-modules#composition) 不是标准语法，Less 编译会报错，所以对于样式重用，是用 Less 的方式，还是放弃 Less?
1. 由于是多人开发，className 的命名不怎么统一，是否需要在这次整理时统一下，然后参考的标准是？

**Comment by yiminghe** [comment]
http://rscss.io/index.html

**Comment by someok** [comment]
看了下感觉不如 less 舒服啊

**Comment by TossShinHwa** [comment]
Yet another option: [Radium](https://github.com/FormidableLabs/radium).

**Comment by plandem** [comment]
here is another way to solve:
http://jamesknelson.com/taming-css-globals-with-react-without-webpack-or-inline-style/

P.S.:
please no Radium/JSS:
http://jamesknelson.com/why-you-shouldnt-style-with-javascript/

**Comment by afc163** [comment]
### Solution

Keep less as css preprocessor.



```
style
├── README.md
├── components
│   ├── affix.less
│   ├── alert.less
│   ├── badge.less
│   ├── breadcrumb.less
│   ├── button.less
│   ├── calendar.less

...

```

You can  `import 'style/components/affix.less'` individually without any less compile errors.

Use [babel-plugin-antd](https://github.com/ant-design/babel-plugin-antd) to handle importing less on demand:

```
// webpack.config.js
  "plugins": [["antd", {
    "style": true
  }]]
```

And that will convert this

```jsx
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>, mountNode);
```

to

```jsx
var _button = require('antd/lib/button');
require('antd/style/components/button');
ReactDOM.render(<Button>xxxx</Button>, mountNode);
```

**Comment by yiminghe** [comment]
css better be inside components

```
src
├── README.md
├── components
│   ├──button
│            ├── index.less
│            ├── index.js

...

**Comment by yiminghe** [comment]
updated 2016-03-21 14:19 GMT+8:00

**Comment by pingan1927** [comment]
棒棒哒

**Comment by lingxuan630** [comment]
Css module 未必要用，但是拆分组件样式很有必要。antd实在太大了，不拆分样式文件非常大，足足有270k的css，大部分组件可能没有用上，浪费带宽，现在要通过手动load less的方式按需加载，还是很不方便的。

`// Load Antd Core
@import "../node_modules/antd/style/themes/default/index.less";
@import "../node_modules/antd/style/mixins/index.less";
@import "../node_modules/antd/style/core/base.less";
@import "../node_modules/antd/style/core/iconfont.less";
@import "../node_modules/antd/style/core/layouts.less";
@import "../node_modules/antd/style/core/motion.less";

// Load Antd Components
@import "../node_modules/antd/style/components/button.less";`

**Comment by yiminghe** [comment]
add `publish antd` section

https://github.com/ant-design/babel-plugin-antd/issues/12

**Comment by Catlite91** [comment]
Use babel-plugin-antd to handle importing less on demand:

// webpack.config.js
  "plugins": [["antd", {
    "style": true
  }]]

这个是什么意思？webpack plugins？

**Comment by benjycui** [comment]
https://github.com/ant-design/babel-plugin-antd

这种事，从命名不就看出来了么。。

**Comment by Catlite91** [comment]
webpack plugin是这样配置的么？以前以为英文文档难读，现在连中文文档都看不懂了。。。悲剧啊

**Comment by benjycui** [comment]
这是 Babel 插件。。。。

**Comment by shengliangli** [comment]
babel-plugin-antd折腾了一天还是不行，唉，东西是好东西，可惜文档太差！

**Comment by afc163** [comment]
...

http://babeljs.io/docs/plugins/

可以仔细读下 babel 插件的文档。
