### ISSUE TITLE
How I can pass class as Dropdown overlay?

### ISSUE THREAD

**Issue by hosembafer** [ant-design/ant-design#9002]
### What problem does this feature solve?
I have a Notifications component and need to know how to pass React.Component class as an overlay to Dropdown?

### What does the proposed API look like?
I need to pass class instead of Menu type as an overlay.

**Comment by yesmeck** [comment]
You can pass any ReactNode to `overlay`.

**Comment by hnlinzhi19** [comment]
不能传ReactNode 到 overlay里面呀，这样用一直报错的哦

**Comment by lyyourc** [comment]
In fact, you need to wrap with `React.Component` if your `overlay` component is not a `Menu` component.

```js
import React from 'react'
import { Dropdown } from 'antd'

class UserDropdown extends React.Component {
  render() {
    return (
      <Dropdown overlay={MyOverlay}>Foo</Dropdown>
    )
  }
}

function MyOverlay() {
  return <React.Fragment>overlay</React.Fragment>
}
```

Or error throws:

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
