### ISSUE TITLE
when click tabs item several times, the tab's width will bigger than before

### ISSUE THREAD

**Issue by yangxiaolin** [ant-design/ant-design#9005]
### Version
3.1.3

### Environment
OS: macOS High Sierra 10.13.2. Browser: Chrome 63.0.3239.132 (64-bit) 

### Reproduction link
[here is a smaller example](https://github.com/yangxiaolin/antd-bug.git)

### Steps to reproduce
1. open a tabs with 3 items
2. click 2nd item
3.  click  3rd item
4. now, the tabs's width is bigger than before

### What is expected?
with serval times click, the tabs's width not change

### What is actually happening?
with serval times click, the tabs's width go bigger

**Comment by AlanKnightly** [comment]
I meet the same issue, and i havent find a good way to solve it....

**Comment by AlanKnightly** [comment]
I meet the same issue...

**Comment by dengfuping** [comment]
@yangxiaolin You can set `overlayStyle={{ width: xxx }}` for Popover to solve the problem.

**Comment by yangxiaolin** [comment]
@dengfuping i will try. thank you

**Comment by xjiangiao** [comment]
solve this problem by setting tabs animated false
