### ISSUE TITLE
when DatePicker.RangePicker set mode=['month', 'month'] , there disabledDate is wrong 

### ISSUE THREAD

**Issue by sharkwarn** [ant-design/ant-design#9008]
### Version
3.1.3

### Environment
react 

### Reproduction link
[https://sharkwarn.github.io/#/](https://sharkwarn.github.io/#/)

### Steps to reproduce
```

  disabledDate=(value) => {
    return true
  }
....
  render() {
    return (
      <div>
          <RangePicker
            disabledDate={this.disabledDate}
            mode={ ['month', 'month']}
          />
      </div>
    )

```

### What is expected?
disabled some Date

### What is actually happening?
The disabledDate doesn't work

**Comment by yesmeck** [comment]
`disabledDate` is designed for days only.

For months and weeks we may need `disabledMonth` and `disabledWeek`.

**Comment by marcosfede** [comment]
Is there any way to implement disabling months on the rangepicker on version 3.1.3 ?  using `disabledDate` does not work.

**Comment by jeffycai** [comment]
I think this is a reasonable demand, and the antd team can give priority to support.

**Comment by yesmeck** [comment]
Tagging as PR welcome.

**Comment by jzhangs** [comment]
PR sent to rc-calendar. It seems we don't need disabledMonth or disabledWeek, current disabledDate callback is fine. Not sure if I missed something.

**Comment by couzic** [comment]
I'm experiencing this issue, currently with antd 3.6.1. disabledDate still has no effect.

Is the fix supposed to have been applied already ?

**Comment by swwinone** [comment]
When can you support？

**Comment by lj2312763** [comment]
I would like to know if the problem has been solved. I still have this problem in version 3.17.0
我想知道问题解决了没，我在3.17.0版本还有这个问题

**Comment by qq645381995** [comment]
现在支持了吗？

**Comment by scottdao** [comment]
> ### Version
> 3.1.3
> 
> ### Environment
> react
> 
> ### Reproduction link
> https://sharkwarn.github.io/#/
> 
> ### Steps to reproduce
> ```
> 
>   disabledDate=(value) => {
>     return true
>   }
> ....
>   render() {
>     return (
>       <div>
>           <RangePicker
>             disabledDate={this.disabledDate}
>             mode={ ['month', 'month']}
>           />
>       </div>
>     )
> ```
> 
> ### What is expected?
> disabled some Date
> 
> ### What is actually happening?
> The disabledDate doesn't work
不过还是多谢吧，这种与需求不是特别符合

**Comment by afc163** [comment]
Please check new RangePicker in antd v4, it should be rewriten and fixed now.

https://ant.design/components/date-picker/

**Comment by mizi-lin** [comment]
这解决方案神了··

**Comment by AWhiteMouse** [comment]
所以v4实现了，v3的坑就不填了吗……

**Comment by lishaoh** [comment]
应该是这样
