### ISSUE TITLE
When I nest an Input in Cascader,is there any Api to make my customize input supports search like add the attribute 'showSearch'

### ISSUE THREAD

**Issue by secreter** [ant-design/ant-design#9010]
### What problem does this feature solve?
I customize an input nested in Cascader,but it can not search to filter.

### What does the proposed API look like?
showSearch={(searchString)=>{}}

**Comment by afc163** [comment]
Yep, I afraid you have to deal with it all by youself.

**Comment by secreter** [comment]
Thank you .
