### ISSUE TITLE
不知为何出现的warning

### ISSUE THREAD

**Issue by oxgos** [ant-design/ant-design#9011]
### Version
3.1.3

### Environment
dva-cli version 0.9.2 , node v8.9.1

### Reproduction link
/

### Steps to reproduce
./node_modules/_css-loader@0.28.8@css-loader/lib/css-base.js
There are multiple modules with names that only differ in casing.This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\lib\css-base.js
    Used by 3 module(s), i. e.
    D:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\index.js?{"importLoaders":1,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!D:\project\dva-news\node_modules\_postcss-loader@2.0.10@postcss-loader\lib\index.js?{"ident":"postcss"}!D:\project\dva-news\src\index.css
* d:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\lib\css-base.js
    Used by 7 module(s), i. e.
    d:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\index.js?{"importLoaders":1}!d:\project\dva-news\node_modules\_postcss-loader@2.0.10@postcss-loader\lib\index.js?{"ident":"postcss"}!d:\project\dva-news\node_modules\_antd@3.1.3@antd\es\style\index.css

./node_modules/_style-loader@0.18.2@style-loader/lib/addStyles.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\addStyles.js
    Used by 3 module(s), i. e.
    D:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\index.js!D:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\index.js??ref--6-1!D:\project\dva-news\node_modules\_postcss-loader@2.0.10@postcss-loader\lib\index.js??postcss!D:\project\dva-news\src\index.css
* d:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\addStyles.js
    Used by 7 module(s), i. e.
    D:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\index.js!D:\project\dva-news\node_modules\_css-loader@0.28.8@css-loader\index.js??ref--7-1!D:\project\dva-news\node_modules\_postcss-loader@2.0.10@postcss-loader\lib\index.js??postcss!d:\project\dva-news\node_modules\_antd@3.1.3@antd\es\style\index.css

./node_modules/_style-loader@0.18.2@style-loader/lib/urls.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\urls.js
    Used by 1 module(s), i. e.
    D:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\addStyles.js
* d:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\urls.js
    Used by 1 module(s), i. e.
    d:\project\dva-news\node_modules\_style-loader@0.18.2@style-loader\lib\addStyles.js

### What is expected?
去除warning

### What is actually happening?
去除warning

---
去除所有引入样式之后，warning会消失,包括初始化项目的index.css

**Comment by yesmeck** [comment]
You should open issue to dva-cli.

**Comment by wisetc** [comment]
This warning may raised by webpack process. Cause it some system like Windows is not sensitive to case and antd have mixed use upper case and lower case to name modules.

For example,

```
_antd@3.22.1@antd/lib/Button/index.js
_antd@3.22.1@antd/lib/button/index.js
```

Webpack 警告说，文件的命名不应该用大小写来区分彼此，因为有些系统是不支持的，可能会导致不可预期的行为。从经验上来说，确实如此（比如 windows 引用，编译成功，转到 linux 编译失败，报错找不到模块）。希望官方能够复现和重视一下。

**Comment by wisetc** [comment]
dammit. 靠，我自己引错了，把 antd/lib/button 引成了 antd/lib/Button.
