### ISSUE TITLE
在Table表格中使用滑动效果后RadioGroup 或者ButtonGroup 会产生两份

### ISSUE THREAD

**Issue by qq328180750** [ant-design/ant-design#9026]
### What problem does this feature solve?
![qq 20180119110407](https://user-images.githubusercontent.com/33867025/35132979-dd2bcf2e-fd08-11e7-8142-8def4f6b78df.jpg)
列属性设置了fixed: 'right',与width: 210,Table属性是scroll={{x: 3000}}

该列的render 
![qq 20180119110825](https://user-images.githubusercontent.com/33867025/35133035-1a6b03e6-fd09-11e7-93d3-c69ac4cbba7f.jpg)

是否需要设置样式

### What does the proposed API look like?
不是知道是不是我的使用方法不对

**Comment by qq328180750** [comment]
拖动滚动条后，会在底部还会显示一个按钮组

**Comment by qq328180750** [comment]
给ant-table-fixed-right 增加z-index解决了

**Comment by afc163** [comment]
Fixed in #9014
