### ISSUE TITLE
编译3.1.13 出现样式报错  tree组建的.opacity 为定义  使用2.*没问题

### ISSUE THREAD

**Issue by SongOfSpring** [ant-design/ant-design#9028]
### Version
3.1.3

### Environment
mac系统 react16 dva1.2.1 dora 0.4.0

### Reproduction link
~~deleted~~

### Steps to reproduce
下载代码 package.json修改react版本16.0.0 dva1.2.1 dora 0.4.0

### What is expected?
能使用最新的antd

### What is actually happening?
目前再用2.13

**Comment by yesmeck** [comment]
别贴内网地址

**Comment by yesmeck** [comment]
@SongOfSpring 直接钉钉上找我吧（边柳）。
