### ISSUE TITLE
不是必填项的验证问题

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#903]
**场景**： 有时候表单中有些字段不是必须填写的，但是如果填写了就需要验证是否是指定类型，例如下面的，原来的意思是，这个高度可以不填写，如果填写就要验证时`number`类型，现在只要提交表单就会验证。

**问题**：能不能这样设置去验证还是需要用`transform`，但是这种需求应该很常见，这个配置应该也算合理，不需要再加`transform`

```js
{
    'label': '高度(CM)：',
    'name': 'height',
    'input': {},
    'required': false,
    'rules': [
      {
        'required': false,
        'type': 'number'
      }
    ]
  },
```
@afc163 求解答

**Comment by afc163** [comment]
`required` 现在的含义不明：`配置项必选` 还是 `规则必选`。

例如以下规则：

```
    'rules': [
      {
        'required': true,
        'type': 'number'
      },  {
        'required': false,
        'type': 'email'
      }
    ]
```

若是规则必选，则楼主的要求是合理的。意外着 `required: false` 给 type 添加了空的判断。未填也可通过校验。

若是项目必选，则上面的两个 required 相反，则是矛盾的。

**Comment by afc163** [comment]
required 和 type 和 min max 目前校验上是`且`的关系，互不影响。

内建的规则例如 `type="email"` 的正则实际上已经包含了 required 的校验，所以你现在设置 `required={false}` 是无效的，建议自定义 pattern 。

**Comment by bang88** [comment]
个人感觉 这个required 如果存在则应该是且的关系

2016年1月21日星期四，偏右 <notifications@github.com> 写道：

**Comment by afc163** [comment]
我也被绕糊涂了，目前关键在 `required={false}` 对于 `type="number"` 是无效的。

**Comment by afc163** [comment]
@yiminghe 来看看..

**Comment by yiminghe** [comment]
async-validator 1.4.1

http://react-component.github.io/form/examples/overview.html: number input

直接 InputNumber 简单

**Comment by afc163** [comment]
和 number 没关系吧，其他 type 也是一样。

**Comment by bang88** [comment]
嗯 跟`number` 没有关系，其他类型也是这样

**Comment by yiminghe** [comment]
和 transform 写法很有关系

**Comment by bang88** [comment]
:smiley: 如果可以的话这种需求真的很常见，简单配置一下就可以使用，不然又得写代码了。

**Comment by yiminghe** [comment]
https://github.com/yiminghe/async-validator/commit/f5ba4274b6d5daf1c4491c3bb518f2a331699816

**Comment by afc163** [comment]
:+1:

**Comment by bang88** [comment]
:+1:
