### ISSUE TITLE
Input Search click search icon invalid

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9030]
### Version
3.1.3

### Environment
windows 10 ,chorme latest,react latest

### Reproduction link
[https://codesandbox.io/s/947l61jp7w](https://codesandbox.io/s/947l61jp7w)

### Steps to reproduce
```

import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Input } from 'antd';
const Search = Input.Search;

ReactDOM.render(
  <div>
    <Search
      placeholder="input search text"
      onSearch={value => console.log(value)}
      style={{ width: 200 }}
    />
    <br /><br />
  </div>
, document.getElementById('container'));
```

### What is expected?
click icon invalid

### What is actually happening?
click icon can seach

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8445
