### ISSUE TITLE
新增inline edit组件

### ISSUE THREAD

**Issue by j3r0lin** [ant-design/ant-design#9032]
### What problem does this feature solve?
可否增加一个支持原地编辑的组件，有些场景下我们需要用户能够更方便的编辑某一个或者几个字段，使用原地编辑的方式，看起来能够增进一些用户体验。

### What does the proposed API look like?
期望的样子是：https://atlassian.design/guidelines/product/components/inline-edit

**Comment by ddcat1115** [comment]
Do you mean https://ant.design/components/table-cn/#components-table-demo-edit-cell ?

**Comment by j3r0lin** [comment]
no, refer to this atlaskit component https://ak-mk-2-prod.netlify.com/packages/elements/inline-edit

**Comment by dengfuping** [comment]
@j3r0lin I think you can listen to the onmouseenter and onmouseleave events to solve the problem.

**Comment by yutingzhao1991** [comment]
it seems make sense.

**Comment by sahar922** [comment]
@j3r0lin why did you close it?

**Comment by j3r0lin** [comment]
@sahar922 I wrote an InlineEditor base on [this demo](https://ant.design/components/table-cn/#components-table-demo-edit-cell) myself. And the atlassian design also has atlaskit which `@atlaskit/inline-edit` could be imported standalone.

**Comment by adamborowski** [comment]
I am also looking for a components that implements "Make it direct" principle: 
https://ant.design/docs/spec/direct
