### ISSUE TITLE
use ExpandedRowRender,When the field of the data has a children,table's ExpandedRowRender is wrong

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#9035]
### Version
3.1.0

### Environment
google chorme

### Reproduction link
[https://codesandbox.io/s/3yml37n3m1](https://codesandbox.io/s/3yml37n3m1)

### Steps to reproduce
1.点击左边的展开按钮
2.子table的数据在主table也有了

### What is expected?
主table和子table的数据相互不干涉

### What is actually happening?
主table增加显示了子table的数据

**Comment by yupeilin123** [comment]
but this is for `columns`, not for `data`

**Comment by yesmeck** [comment]
Search "Tree data". https://ant.design/components/table/
