### ISSUE TITLE
使用 Cascader 时，当层级太深，超过一屏的时候无法选择后面的

### ISSUE THREAD

**Issue by Mosaic91** [ant-design/ant-design#9037]
### Version
3.1.3

### Environment
最新版的chrome

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
使用的 Cascader 进行级联选择，层级深度太深，所以层级展开超过一屏时，在一屏之外的选项无法选择

### What is expected?
展开超过一屏时选择面板向左移动，从而可以继续选择右边的选项

### What is actually happening?
最右边的无法选择到，因为看不到了

**Comment by yesmeck** [comment]
#1150 

这么深的层级，预期的表现是什么？

**Comment by Mosaic91** [comment]
预期选择面板继续向左移到窗口外，让右边的深层选项可见  @yesmeck

**Comment by benjycui** [comment]
@Mosaic91 能告知你的业务场景么，很好奇有什么业务场景需要这么深的层级。

**Comment by Mosaic91** [comment]
用于展示和选择组织架构，目前公司的组织架构已经达到 11 层 @benjycui 
IPH->公司集团->事业群->部门->角色（销售、运营）类型->服务类型->组->全国各大区->市县->代理->小组->人

**Comment by yesmeck** [comment]
建议用 TreeSelect 吧

**Comment by withzhaoyu** [comment]
加个横向滚动如何，我也遇到类似问题。。。
