### ISSUE TITLE
Using Menu in Multiple Select mode, too many options will lead to the last option will be hidden in the second level

### ISSUE THREAD

**Issue by Mosaic91** [ant-design/ant-design#9040]
### Version
3.1.3

### Environment
any browser

### Reproduction link
[https://codepen.io/Mosaic91/pen/VyqrGb](https://codepen.io/Mosaic91/pen/VyqrGb)

### Steps to reproduce
open the page then you can't see the last option

### What is expected?
last option can be seen and chosen

### What is actually happening?
last option can be seen and can't be chosen

**Comment by yesmeck** [comment]
You should open issue to https://github.com/ant-design/ant-design-mobile
