### ISSUE TITLE
Table  onRow description translation error

### ISSUE THREAD

**Issue by l-Lemon** [ant-design/ant-design#9042]
### Version
3.1.3

### Environment
win10

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-dynamic-settings](https://ant.design/components/table-cn/#components-table-demo-dynamic-settings)

### Steps to reproduce
Table docs

### What is expected?
correct translation

### What is actually happening?
onRow   设置列属性

---
onRow 不应该是设置行属性吗？

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design/commit/4286131735126cfbc1a37ac85c9c58b1b06b8046
