### ISSUE TITLE
treeSelect  showCheckedStrategy 

### ISSUE THREAD

**Issue by superllmin** [ant-design/ant-design#9044]
### Version
3.1.3

### Environment
win 10, chrome 63.0

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
treeSelect. when treeCheckable is false，multiple is true;   showCheckedStrategy is useless, but is equal to checkbox。

### What is expected?
The result is the same with treeCheckable is true.

### What is actually happening?
The result is the different from treeCheckable is true.

**Comment by ddcat1115** [comment]
`multiple` is true while `treeCheckable` is false, the `treeCheckable` do not work.

**Comment by zombieJ** [comment]
Already fixed
