### ISSUE TITLE
Not able to deselect after selecting an existing value if showSearchi is added to <Select /> from code

### ISSUE THREAD

**Issue by DadyByte** [ant-design/ant-design#9048]
### Version
3.1.3

### Environment
chrome

### Reproduction link
[https://stackoverflow.com/questions/48357787/how-to-deselect-select-on-select-of-another-select-in-react/48358158#48358158](https://stackoverflow.com/questions/48357787/how-to-deselect-select-on-select-of-another-select-in-react/48358158#48358158)

### Steps to reproduce
1. create 2 select boxes with value attribute containing 2 different values from the state.
2. onChange of select 1 set state for 1st select and for the 2nd select as empty string(to deselect)

### What is expected?
The selected value in the 2nd select should be deselected and placeholder should be visible

### What is actually happening?
empty string is being set as value for the second select causing placeholder to be hidden.

**Comment by yutingzhao1991** [comment]
If you want show placeholder of select, set value to undefined. ref: https://codesandbox.io/s/kk281o5rp5
