### ISSUE TITLE
Ability to pass name of the checkbox input to getCheckedProps in rowSelection in Table

### ISSUE THREAD

**Issue by swistak35** [ant-design/ant-design#9050]
### What problem does this feature solve?
Currently, if we define a function `getCheckedProps` in `rowSelection` for `Table` component, we can only define `disabled` value there. My feature request is about being able to define `name` for the checkbox too. My use-case is that I'm doing a form (wrapping the table), so I want to give specific `name` to the selection checkboxes in my table. 

### What does the proposed API look like?
The result of the function `getCheckboxProps` could have also (optional) `name` argument, not only `disabled`.

**Comment by yesmeck** [comment]
Tagging as good first issue.

**Comment by yesmeck** [comment]
@mgrdevport  is already working on it.

**Comment by yesmeck** [comment]
Will release this weekend.
