### ISSUE TITLE
antd不支持按需加载了？

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design#9051]
如图
![qq20180119-201803](https://user-images.githubusercontent.com/9820142/35191266-9c57fcca-feb1-11e7-8d3e-18bc8aedc1a3.png)
![qq20180119-201928](https://user-images.githubusercontent.com/9820142/35191267-9c900778-feb1-11e7-903b-ca4504b35dcc.png)

**Comment by afc163** [comment]
实测没有问题：https://github.com/ant-design/ant-design-pro/blob/master/.webpackrc#L3

**Comment by smithyj** [comment]
@afc163 https://github.com/smithyj/backend.yangyj.com

**Comment by lchunxiu** [comment]
请问下这是什么工具测试的？
please,could you tell me the tool you use to test ? @smithyj
