### ISSUE TITLE
TreeSelect checkable cant be used with only keyboard

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#9057]
### Version
3.1.4

### Environment
MacOS, Chrome Version 63.0.3239.132

### Reproduction link
[https://codesandbox.io/s/jnw46698m3](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
focus on input, press tab, cursor is moved to tree select

### What is expected?
modal with tree data is opened, data can be selected using only keyboard

### What is actually happening?
modal is not opened, control is not reacting to tab and enter keyboard inputs

**Comment by zombieJ** [comment]
hi, did you provide the wrong reproduction link?

**Comment by zombieJ** [comment]
Is that correct reproduce link?

**Comment by vorlov** [comment]
https://ant.design/components/tree-select/ - Checkable example

**Comment by vorlov** [comment]
any update on this?

**Comment by zombieJ** [comment]
Sorry for delay.
`TreeSelect` is in refactoring, we will support this by keyboard & accessibility.

Ref: https://github.com/zombieJ/tree-select/tree/refactor
related discuss: https://github.com/ant-design/ant-design/issues/10360

**Comment by mikecanann** [comment]
Any update on the keyboard accessibility for TreeSelect?

**Comment by zombieJ** [comment]
@mikecanann , since TreeSelect using `rc-tree-select` depends on `rc-tree` which not support key board yet. This is still in progress.

**Comment by mayankTTN** [comment]
Any update on this issue ?

**Comment by zombieJ** [comment]
v4 TreeSelect support keyboard: https://next.ant.design/components/tree-select/#components-tree-select-demo-basic

**Comment by mayankTTN** [comment]
Thansks @zombieJ for updating about this issue but it still in beta can you give an idea by when v4 would be released ?

**Comment by zombieJ** [comment]
We will release antd `release candidate` version in recent days. After `rc` version released, you can use it in production : )

**Comment by afc163** [comment]
Resolved in antd v4!
