### ISSUE TITLE
how to add a scroll bar on select component?

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design#9060]
### Version
3.0.0

### Environment
Mac Os

### Steps to reproduce
if there is a property to control the display of scroll bar when options is more than a certain number.

### What is expected?
provide an api.

### What is actually happening?
unable to achieve.

**Comment by yesmeck** [comment]
Select has default `max-height` to `250px`, you can change it's height through `dropdownStyle` prop.

**Comment by yesmeck** [comment]
> By the way, when will the select expand upward? 

When page can not scroll down any more.

**Comment by hudawen** [comment]
Indeed, but if the select is on a modal, it expands upward only when the page rather than the modal can not scroll down any more ...

**Comment by yesmeck** [comment]
> When page can not scroll down any more.

When **container** can not scroll down any more. You can use `getPopupContainer` to set container to the modal.
