### ISSUE TITLE
icon font 可否增加一个 file-word

### ISSUE THREAD

**Issue by Phinome** [ant-design/ant-design#9061]
### What problem does this feature solve?
目前 antd 里 file 对应的 iconfont office 系常见的 type 缺少 word ，而 markdown 如今比较常见，希望能添加。

### What does the proposed API look like?
file-word 和 file-markdown

**Comment by nikogu** [comment]
i suggest to use http://iconfont.cn/ depend on your specific request

**Comment by afc163** [comment]
Could you provide what those two icons look like?

**Comment by afc163** [comment]
#9092

**Comment by Phinome** [comment]
thanks
