### ISSUE TITLE
Make TreeSelect component work properly in "combobox" mode.

### ISSUE THREAD

**Issue by markin-io** [ant-design/ant-design#9062]
### What problem does this feature solve?
This feature could improve UX of the antd TreeSelect component. Our team received a few reports from users that doesn't like do "Click TreeSelect -> Click into search field -> search items" routine. They'd rather click once on the select with text input and type directly to it. Like when TreeSelect in "multiple" mode.

### What does the proposed API look like?
```javascript
<TreeSelect
    combobox
    value={this.state.action}
    onChange={this.onChange}
>
    {treeNodes}
</TreeSelect>
```

Actually, this code currently works, but additionally to the ```value``` prop I have to pass ```inputValue``` to make it work.

**Comment by yesmeck** [comment]
I thinks the key point is we should support selecting node by keyboard in search mode.

**Comment by markin-io** [comment]
@yesmeck excuse me, I'm not sure I understand what you mean. How keyboard related to the combobox mode? I'm wondering If it's possible assign someone to review my [pull request](https://github.com/react-component/tree-select/pull/95) for react-component/tree-select, please. If PR will be merged, I would be happy try to make it work for antd/TreeSelect.

**Comment by yesmeck** [comment]
`combobox` it not  supported in `rc-tree-select` at present. There are some "combobox" related codes in `rc-tree-select`, they are copied from `rc-select`.  I think `combobox` is meaningless for `rc-tree-select`.  `combobox` is designed for autocompletion.

**Comment by yesmeck** [comment]
> They'd rather click once on the select with text input and type directly to it.

The key point is they don't want click twice. So we add selecting node by <kbd>Enter</kbd> after text input.
