### ISSUE TITLE
Form.Item, error not show when more than one getFieldDecorator  

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#9063]
### Version
3.1.2

### Environment
node6.1 

### Reproduction link
[https://codesandbox.io/s/4zqyrk21j7](https://codesandbox.io/s/4zqyrk21j7)

### Steps to reproduce
https://codesandbox.io/s/4zqyrk21j7

### What is expected?
the second input can show the error message.

### What is actually happening?
the second input not to show error message.

---
~~does the error message bind the FormItem?~~

**Comment by yesmeck** [comment]
> does the error message bind the FormItem?

You need wrap each getFieldDecorator with Form.Item to show errors automatically.

**Comment by didmehh** [comment]
so, ok.
