### ISSUE TITLE
Hide text in `Table` when `loading` prop is true

### ISSUE THREAD

**Issue by ncknuna** [ant-design/ant-design#9069]
### Version
3.1.4

### Environment
OS X High Sierra, Chrome 63

### Reproduction link
[https://codepen.io/anon/pen/OzdLrR?editors=0010](https://codepen.io/anon/pen/OzdLrR?editors=0010)

### Steps to reproduce
Render a table with no data with the `loading` prop as `true` (see codepen link)

### What is expected?
`locale.emptyText` placeholder text does not show, because the table is still loading

### What is actually happening?
The loading spinner and the `locale.emptyText` placeholder are both visible

---
Originally reported here: https://github.com/ant-design/ant-design/issues/8788

**Comment by yesmeck** [comment]
Tagging as good first issue.

**Comment by Joshuajrodrigues** [comment]
Is it just me or does this not work when you provide a custom locale ?
