### ISSUE TITLE
upload组件accept错误

### ISSUE THREAD

**Issue by wupinlang** [ant-design/ant-design#9071]
### Version
3.1.4

### Environment
macOS,Google Chrome 版本 63.0.3239.132（正式版本） （64 位）

### Reproduction link
[https://codepen.io/wupinlang/pen/MrRYxW](https://codepen.io/wupinlang/pen/MrRYxW)

### Steps to reproduce
accept参数设置为“.zip,.tgz”，点击上传，发现excel/word等文件可以被选中和上传

### What is expected?
不可选中excel/word等文件

### What is actually happening?
可选中上传excel/word等文件

**Comment by wupinlang** [comment]
anyone focus on this issue? @dengfuping

**Comment by yesmeck** [comment]
Bug of chrome, we can do nothing. I'd recommend you write your owner validation.

**Comment by ayiaq1** [comment]
accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

如果只要xls只用第一个 application/vnd.ms-excel

**Comment by answer33** [comment]
> accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
> 
> 如果只要xls只用第一个 application/vnd.ms-excel

如果要兼容*.xlsx后者也加上就可以了（满足只能选择上传excel文件）
