### ISSUE TITLE
将有下拉列表的表单放到固定长度的盒子中，下拉列表的位置不跟着下拉框移动

### ISSUE THREAD

**Issue by liyun074** [ant-design/ant-design#9072]
### Version
3.1.3

### Environment
MAC pro chrome63.0 

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
必现。
1. 将包含form的section加上高度100px 

<img width="473" height="auto" src="https://github.com/liyun074/gooDay-admin/blob/master/images/01.png"></img>

2. 没有跟随下拉框移动

<img width="473" height="auto" src="https://github.com/liyun074/gooDay-admin/blob/master/images/02.png"></img>

### What is expected?
跟着相应的下拉框移动

### What is actually happening?
相对于原来的位置不动

---

**Comment by nikogu** [comment]
It is absolute not moving when your change the position on DOM directly.

So, what's your requirement ? you can show it in codepen.

**Comment by yesmeck** [comment]
> 注意，如果发现下拉菜单跟随页面滚动，或者需要在其他弹层中触发 Select，请尝试使用 getPopupContainer={triggerNode => triggerNode.parentNode} 将下拉弹层渲染节点固定在触发器的父元素中。

**Comment by liyun074** [comment]
@yesmeck   请问是给外层节点加还是当前的下拉框加

**Comment by yesmeck** [comment]
看文档 `getPopupContainer` 的说明里有示例。

**Comment by liyun074** [comment]
@yesmeck   谢谢🙏 可以啦

**Comment by afc163** [comment]
建议自行关闭。@liyun074
