### ISSUE TITLE
form hope to add getAllFieldsName property

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9073]
### What problem does this feature solve?
dynamic this.props.form.setFieldsValue()

### What does the proposed API look like?
```
const data = {.........};
const fields = this.props.form.getAllFieldsName();
const temp = {};
fields.forEach(item=>temp[item]=data[item]);
this.props.form.setFieldsValue(temp);
```

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/35261323-9d0dac2e-004a-11e8-99df-9885f28910b7.png)

**Comment by hengkx** [comment]
```
const data = {...........};
this.props.form.setFieldsValue(data);
```

**Comment by hengkx** [comment]
```
this.props.form.getFieldsValue();
```
This method.Not good  solve.

**Comment by nikogu** [comment]
getFieldsValue : Get the specified fields' values. If you don't specify a parameter, you will get all fields' values.

> This method.Not good solve.

what does this mean ? take a reproduce on codepen?

**Comment by hengkx** [comment]
I want to filed key,don't value

**Comment by hengkx** [comment]
[https://github.com/react-component/form/blob/master/src/createFieldsStore.js#L124](https://github.com/react-component/form/blob/master/src/createFieldsStore.js#L124)

**Comment by hengkx** [comment]
```
const fields = Object.keys(this.props.form.getFieldsValue());
```
