### ISSUE TITLE
Inside the options too much data, ` flattenOptions.filter()` takes too long

### ISSUE THREAD

**Issue by hero-guo** [ant-design/ant-design#9079]
### Version
3.1.4

### Environment
OS X High Sierra, Chrome 63

### Reproduction link
[https://codesandbox.io/s/r53rl20zj4](https://codesandbox.io/s/r53rl20zj4)

### Steps to reproduce
```javascript
import React from 'react';
import { Cascader } from 'antd';

export default () => {
  const options = [];
  const children = [];
  for (let j = 0; j < 20; j ++ ) {
    children.push({
      value: j +  '',
      label: j +  '',
    });
  }
  for (let i = 0; i < 400; i ++ ) {
    options.push({
      value: i +  '',
      label: i +  '',
      children,
    });
  }
  return (
    <Cascader
      options={options}
      placeholder="Please select"
      showSearch
    />
  );
};

```

### What is expected?
You can have a loading state when you want to filter.
期望筛选的时候可以有个loading状态

### What is actually happening?
nside the options too much data, flattenOptions.filter () takes too long
options数据过多的时候 ，generateFilteredOptions 里面 flattenOptions.filter()耗时过长

**Comment by nikogu** [comment]
@hero-guo can you take a look about the long time reason ? Is it your filter calculate or the Options render ?

**Comment by hero-guo** [comment]
@nikogu In the source
```javascript
if (state.inputValue) {
      options = this.generateFilteredOptions(prefixCls);
    }
```
Does long filter time affect component rendering?

**Comment by hero-guo** [comment]
@nikogu https://github.com/ant-design/ant-design/blob/43326136332759e6ad43fb9678cb5338d6adb96d/components/cascader/index.tsx#L253

**Comment by nikogu** [comment]
@hero-guo your codepen is not slow...

**Comment by yesmeck** [comment]
Track in #3789
