### ISSUE TITLE
How to set `key` for <th /> in <Table /> ?

### ISSUE THREAD

**Issue by nemonie** [ant-design/ant-design#9088]
### What problem does this feature solve?
Normally, Antd sets auto-Increment number as key for `<th />`. In most of the cases, it's fine.

But, when the `columns` changes frequently, this will cause some unnecessary unmount and mount.
Especially when I use a React component as some columns' title.

### What does the proposed API look like?
```js
const columns = [];

// when set columns, it can use the key for `<th />`, not only `<td />`
columns.push({
  title: <SomeComponent />,
  dataIndex: 'name',
  key: 'name'
});

return <Table columns={columns} />;
```

**Comment by yesmeck** [comment]
```javascript
columns.push({
  title: <SomeComponent />,
  dataIndex: 'name',
  key: 'name',
  onHeaderRow() {
    return { key: uniqueKey }
  }
});
```

**Comment by afc163** [comment]
Can we use `column.key` for `th` defaultly?

**Comment by yesmeck** [comment]
`column` is for `th > td`, not `th`.

**Comment by afc163** [comment]
There is no `th > td`.

**Comment by nemonie** [comment]
```js
<Table onHeaderRow={() => ({
  key: uniqueKey
})} />
```

@yesmeck It doesn't work for me. The key of `th` is still number.

**Comment by yesmeck** [comment]
Try `rc-table@6.1.4`, will use `column.key || column.dataIndex` as key
