### ISSUE TITLE
table with fixed column display not as excepted when set scroll as {x: true, y:300}

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design#9090]
### Version
3.1.4

### Environment
win7, chrome 61.0.3163.100

### Reproduction link
[https://codepen.io/anon/pen/XVQpXE?&editors=001](https://codepen.io/anon/pen/XVQpXE?&editors=001)

### Steps to reproduce
set scroll as {x: true, y:300} in antd table,
look the reproduction link in browser size 1920 and 1366
set scroll as {x: 1400, y:300} in antd table,
look the reproduction link in browser size 1920 and 1366

### What is expected?
the style of table should keep right, and the scroll in x-axis should keep consistent

### What is actually happening?
the style of column in table which fixed right  don't keep consistent,
and in 1366 browser, the third column "Column 1" is hidden by the two rows which fixed left

**Comment by codercatmomi** [comment]
same problem
is there a solution now?

**Comment by hengkx** [comment]
+1

**Comment by yesmeck** [comment]
Leave at least one column's width to auto to make the table width responsive.

**Comment by sbyps** [comment]
@yesmeck 其中某一个column的width不设置，当scroll.x = true时就没有fixed left的效果了
右边scrollbar样式也不对，拉到最底，table样式错位
https://codepen.io/anon/pen/XVQpXE?&editors=001

**Comment by yesmeck** [comment]
参考例子，设置一个合适 `scroll.x`。
