### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#9092]
- [x] slack #9091
- [x] file-word #9061
- [x] file-markdown #9061 
- [x] lark
- [x] Instagram #8959
- [x] yahoo
- [x] reddit
- [x] fire
- [x] drag #8617
- [x] crown
- [x] stop
- [x] currency icons (doller, euro, yuan..etc)

If you find any icons missing in http://ant.design/components/icon, you can reply under this issue.

**Comment by Sicria** [comment]
Suggestions for new icons:

Yahoo - https://yahoo.com/
TradingView - https://www.tradingview.com/
Flame/Fire Emoji - https://emojipedia.org/fire/ (Similar to this)

All the basic emojis would also be amazing but if not the flame one would be top of the list since you already have rocket.

**Comment by Sicria** [comment]
An icon for Reddit would also be ideal.

**Comment by JulesWang** [comment]
icon-stop:   a small black box

**Comment by afc163** [comment]
@JulesWang what is it looks like?

**Comment by JulesWang** [comment]
@afc163  http://iconfont.cn/search/index?q=stop

**Comment by afc163** [comment]
OK, so it is a `play-stop` stop.

**Comment by Indyandie** [comment]
currency-(dollar, euro, any other popular ones) icon
> This can also apply to the bank icon

**Comment by ollierob** [comment]
A few more `-circle` and `-circle-o` would be helpful e.g. `swap-circle-o`, `edit-circle-o`. Perhaps some `<CircleIcon>` or `<SquareIcon>` component to do this automatically?

**Comment by eugenest** [comment]
need thunderbolt, like http://iconfont.cn/search/index?q=thunderbolt

**Comment by asheinz** [comment]
comment icon, like https://icons8.com/icon/428/comments

**Comment by Sicria** [comment]
@asheinz I'm sure you've already seen it but just in case, ``message`` looks similar, does that work for you?

More icons which would be nice to have:
Lab: http://iconfont.cn/search/index?q=lab

**Comment by felops** [comment]
What about `whatsapp`?

**Comment by schester44** [comment]
- thunderbolt
- add video (https://imgur.com/a/Dh8SPEU)
- add app (https://imgur.com/a/yJ88vt5)

**Comment by jacob87o2** [comment]
I think this issue should be re-opened, as there is one crucial icon missing.

"Poo". Smiling one. 💩

There is no better icon for indicating that something went wrong.
