### ISSUE TITLE
How change the color of the site dynamically with a colorpicker?

### ISSUE THREAD

**Issue by torque2** [ant-design/ant-design#9093]
### What problem does this feature solve?
In the footer of ant.design, with the color picker we can change dynamically the color of the theme... 
How can i do the same in my own site? 

### What does the proposed API look like?
Do the same of ant.design footer colorPicker
![image](https://user-images.githubusercontent.com/35730681/35276434-ae8871de-0043-11e8-8fe9-ce686bc3d7e6.png)

**Comment by mzohaibqc** [comment]
@torque2 This is exactly what I was looking for but colud not find a ready made solution so after tweaking Ant Design's `[script ](https://github.com/ant-design/ant-design/blob/master/scripts/generateColorLess.js)` I was able to update multiple color variables with color pickers. You can read my article at Medium https://medium.com/@mzohaib.qc/ant-design-live-theme-588233ea2bbc or download source code from github and follow that. 

Github: https://github.com/mzohaibqc/antd-live-theme

Live Demo: https://mzohaibqc.github.io/antd-live-theme/
