### ISSUE TITLE
Select 组件 在mode 为tags的情况下，以‘，’ 来分词之后不会触发onSelect 事件，只会触发 onChange事件

### ISSUE THREAD

**Issue by sillyfeng** [ant-design/ant-design#9094]
### Version
3.1.0

### Environment
chrome52

### Reproduction link
[https://codepen.io/sillyfeng/pen/WdWoKv](https://codepen.io/sillyfeng/pen/WdWoKv)

### Steps to reproduce
1、打开连接
2、随便输入什么数据，以逗号来分词
3、查看 console 日志

### What is expected?
期望的结果是在以逗号分词的时候，会触发 onSelect事件，但是现在并不会，只有输入按下Enter键，才会触发onSelect事件

### What is actually happening?
期望的结果是在以逗号分词的时候，会触发 onSelect事件，但是现在并不会，只有输入按下Enter键，才会触发onSelect事件

**Comment by yesmeck** [comment]
目前的设计就是这样的，实际使用中会有什么问题？

**Comment by sillyfeng** [comment]
我这边有一个场景是会用到 onSelect事件，在每次有Select内容的时候会改变另一个table的内容

**Comment by yesmeck** [comment]
@sillyfeng onChange 不行吗？最好用  https://u.ant.design/codesandbox-repro 给个例子。

**Comment by sillyfeng** [comment]
@yesmeck  在问题描述里的那个连接：  https://codepen.io/sillyfeng/pen/WdWoKv 是对刚刚我说的这个现象的描述，不过需要F12 打开控制台看一下结果。
onChange的话，他是把所有的选中项都列出来了，这样我得判断那条是新增的，就有很多额外重复的不必要的工作 

-操作步骤

1. 打开 https://codepen.io/sillyfeng/pen/WdWoKv ，然后在输入框中输入 任意词 ，点击 enter， 查看控制台会有 （onSelect 和onChange的输出）

2. 在输入框中输入 任意词，然后点击 “逗号” ，查看控制台，只有onChange的输出，没有onSelect

**Comment by yesmeck** [comment]
@sillyfeng 是的，这个是预期的行为。我是指你最好示范一下你的应用场景，说明一下为什么这里一定要用 onSelect，不能用 onChange。

**Comment by sillyfeng** [comment]
@yesmeck  我明白你意思了， 我大致描述一下
1、 每次 onSelect 触发的时候，我会 往 table 的data 里面push一条数据 。
2、 table的Data 数据也可以自行页面维护 
3、 如果用onChange， 我就需要判断哪条是新增的，其实也可以认为 _最后一条就是新增的对吧_
4、 但是同样会有onDeselect 事件的处理，这样onChange 就会有局限。我不知道是该新增还是该删除。

**Comment by yesmeck** [comment]
嗯，确实需要触发 `onSelect`。

**Comment by sillyfeng** [comment]
@yesmeck  那如果这个是一个预期行为，那我就限制用户必须输入之后使用enter吧。

**Comment by yutingzhao1991** [comment]
这个算是一个 bug 吧，就是在用 ',' 触发添加一项的时候没有触发 `onSelect`。

**Comment by yutingzhao1991** [comment]
有一个问题要讨论下，onSelect 是有第二个参数的：

![image](https://user-images.githubusercontent.com/1061968/35434477-47e28ccc-02c2-11e8-959a-fc301373f88a.png)

在通过 ',' 触发 onSelect 的情况这个参数应该给什么呢？

**Comment by yesmeck** [comment]
是的， 我一开始对 `onSelect` 的理解就是在点击一个 `Option` 选中后才触发，但是自动分词的结果是没有 Option 的，所以不触发  `onSelect`。另外这里的 `option` 其实也不是原来的 `<Option />`，而是 `Menu.Item` 的实例。

**Comment by yesmeck** [comment]
如果传 option 的话，只能 `createElement` 一个  `Ment.Item`， 很别扭，跟手选的不是一个东西。

**Comment by yesmeck** [comment]
可以跟这个 issue https://github.com/ant-design/ant-design/issues/4597 依赖考虑，是不是把参数里的  option 全部统一成 `Option` 的 `element`。

**Comment by sillyfeng** [comment]
@yesmeck 但是你手动添加一个option点击enter按钮的时候，是有触发onSelect的。像enter这种情况下本身也是没有option的。 他们（“，”分词 和 点击enter键进行分词 ）做的事情应该是一样的吧，可以把第二个参数设置成同样的吗

**Comment by yesmeck** [comment]
enter 就是选中当前选中项

**Comment by sillyfeng** [comment]
老铁这么晚还没有睡觉啊。我站在一个没有考虑太多细节的情况下来说， 感觉enter和','分词是一样的情况
点击enter之前select里的children里没有当前要输入的内容的，然后你输入内容，点击enter之后的情况是select里加了一条option，并且处于选中状态，
“，”分词感觉和这个情况一样，就是同样是再分词之前，select的children里没有内容，在输入内容，点击“，” 之后，select里加了一条option，并且处于选中状态，其实从结果来看，他和点击enter键没有区别。

**Comment by yutingzhao1991** [comment]
嗯，传 Option 可以，但是这样就是一个 breakChange 了。

@yesmeck 不考虑兼容吗？版本应该怎么升？

**Comment by yesmeck** [comment]
应该不会 break，因为用起来是一样的，都是 `option.props`，而且文档里写的就是 Option。
