### ISSUE TITLE
Components cannot be styled without changing the style of the rest of the page

### ISSUE THREAD

**Issue by openjck** [ant-design/ant-design#9096]
### Version
3.1.4

### Environment
All browsers

### Reproduction link
[https://github.com/openjck/bug-demo-ant-design-global-styles](https://github.com/openjck/bug-demo-ant-design-global-styles)

### Steps to reproduce
Import an ant-design component and its styles.

See [this minimal demo](https://github.com/openjck/bug-demo-ant-design-global-styles).

### What is expected?
That component should be styled, but not other page styles should be affected. In the demo, for example, the DatePicker component should be styled but the h1 should not.

### What is actually happening?
Many other page elements are styled, even page elements that are not controlled by ant-design. In the demo, for example, the h1 is styled when it shouldn't be.

---
This is related to #4331 and maybe a duplicate of it.

**Comment by afc163** [comment]
So far, there is no better way to deal with this situation, see https://github.com/ant-design/ant-design/issues/4331#issuecomment-331089741

**Comment by openjck** [comment]
Thanks. If the problem has not been fixed, can you please reopen #4331?
