### ISSUE TITLE
steps组件progressdot 支持换行需求

### ISSUE THREAD

**Issue by ananwf** [ant-design/ant-design#9097]
### What problem does this feature solve?
使用steps组件的progressdot时，需要描述一个很长的步骤时，点与点之间太过密集。需要换一行来展示。
另外，希望能开放progressdot中点大小和颜色的个性化设置

### What does the proposed API look like?
期望steps组件能支持换行，当步骤较多时，让点与点之间不要太密集

**Comment by afc163** [comment]
步骤很长时，不应该使用 `Steps[progressdot]`。建议使用垂直的 `Steps`。
