### ISSUE TITLE
Form中getFieldDecorator绑定组件的id相同时，点击任一个label会focus错误

### ISSUE THREAD

**Issue by DegaoLi** [ant-design/ant-design#9103]
### Version
3.1.4

### Environment
win10 chrome

### Reproduction link
[https://codesandbox.io/embed/rr622o2yx4](https://codesandbox.io/embed/rr622o2yx4)

### Steps to reproduce
1.绑定组件id相同时，点击任意一个FormItem的名称，都会focus到第一个组件上

### What is expected?
focus到正确组件或者名称点击不可以focus

### What is actually happening?
focus到第一个组件

**Comment by nikogu** [comment]
it is right, id need be unique.

**Comment by afc163** [comment]
That is strange, this problem should be fixed in https://github.com/ant-design/ant-design/issues/7351

I will check it later.

**Comment by afc163** [comment]
Broken again by https://github.com/ant-design/ant-design/commit/bf70d30a60595916a38671f384ed17cbd0c4ba5d#diff-94b7635a3702d37a73e4971da7dda90b
