### ISSUE TITLE
Tabs组件同时使用 tabPosition="bottom" type="card" 时样式错误

### ISSUE THREAD

**Issue by ryanhoho** [ant-design/ant-design#9104]
### Version
3.1.4

### Environment
chrome52

### Reproduction link
[https://codesandbox.io/s/x3q5zkrxy4](https://codesandbox.io/s/x3q5zkrxy4)

### Steps to reproduce
使用Tabs组件时，若同时设置了 `tabPosition="bottom" type="card"`属性，样式显示有误。

### What is expected?
Tab标签在Tab内容区下方，并将分割线显示在tab与内容区之间。

### What is actually happening?
Tab标签按钮与内容区的分割线显示在了Tab标签下方，与`tabPosition=“top”`时效果一致。

**Comment by nikogu** [comment]
> tabPosition="bottom" + type="card"

i think it's not a right interaction ?

@afc163 take a look

**Comment by ryanhoho** [comment]
即使只使用 tabPosition="bottom" ，样式应该也是错误的，内容分割线与Active状态线都与top时一样，在下方。
