### ISSUE TITLE
Long input text show not right when use textarea as <AutoComplete>'s child

### ISSUE THREAD

**Issue by zhaozhouyang** [ant-design/ant-design#9111]
### Version
3.1.4

### Environment
macOS 10.13.1 Chrome Version 63.0.3239.132 react 16

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
Input very long in textarea in this link: https://ant.design/components/auto-complete-cn/
![image](https://raw.githubusercontent.com/zhaozhouyang/markdown-photots/master/tmp/antd-auto-complete-bug.png)

### What is expected?
The text should not overflow and float on original input text

### What is actually happening?
Duplicate text overflow
![image](https://raw.githubusercontent.com/zhaozhouyang/markdown-photots/master/tmp/antd-auto-complete-bug.png)

**Comment by zhaozhouyang** [comment]
@ant-design-bot 
thisi is the repo link:
https://codesandbox.io/s/yj8103773x

**Comment by afc163** [comment]
Duplicate of #11035
