### ISSUE TITLE
修改 theme 样式变量之后，要重新 run dev 才可以生效，效率特别低

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#9113]
### What problem does this feature solve?
有没有可以在线动态修改主题样式的功能网站？ 

修改 theme 样式变量之后，要重新 run dev 才可以生效，效率特别低 

### What does the proposed API look like?
类似 echart 的主题配置工具 http://echarts.baidu.com/theme-builder/#

**Comment by yesmeck** [comment]
可以试试 https://github.com/yesmeck/webpack-less-theme-plugin
