### ISSUE TITLE
Removing selected items in virtualized-select closes popover

### ISSUE THREAD

**Issue by pivcec** [ant-design/ant-design#9114]
### Version
3.1.4

### Environment
Mac OS - 10.13.2 (17C88), Google Chrome - 63.0.3239.132 (Official Build) (64-bit), React 16.2

### Reproduction link
[https://codesandbox.io/s/5yop9n04wk](https://codesandbox.io/s/5yop9n04wk)

### Steps to reproduce
Click on popover button; click inside input field; select any item from list; click on either "X" to remove selected item.

### What is expected?
Popover should stay open unless button or area outside of popover is clicked.

### What is actually happening?
Popover closes when selected item is removed by clicking on either "X".

**Comment by Bjarkias** [comment]
Looks similar to the issue I'm dealing with, 
Popover closes when selecting from a select input: https://codesandbox.io/s/1r8orlzy63

**Comment by zombieJ** [comment]
Hmmm, trigger addEventListener to the doc which is not controlled by react. This makes that trigger popup another trigger can not be catch in react event flow.

Let me take a look.
