### ISSUE TITLE
contributing guide link on github is invalid

### ISSUE THREAD

**Issue by pinkyw** [ant-design/ant-design#9116]
### Version
3.1.4

### Environment
none

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md)

### Steps to reproduce
none

### What is expected?
contributing guide

### What is actually happening?
404

---
since this request was merged. https://github.com/ant-design/ant-design/pull/9075

**Comment by yesmeck** [comment]
New site deployed.
