### ISSUE TITLE
Need similar feature as `maxTagCount` for TreeSelect

### ISSUE THREAD

**Issue by codTango** [ant-design/ant-design#9117]
### What problem does this feature solve?
So it will only display the desired number of items in the selection area, but display all the checked items in drop-down

### What does the proposed API look like?
```
<TreeSelect
  maxTagCount={3}
  maxTagPlaceholder={renderMaxTagPlaceHolder}
>

    renderMaxTagPlaceHolder = (selectedRecords: Array<any>) => {
      if (selectedRecords.length < 3) {
        return;
      }

      const recordsLength = selectedRecords.length;
      const items = selectedRecords.slice(3, recordsLength);

      const menu = (
        <Menu>
          {items.map(item => (
            <Item key={item.key}>{item.name}</Item>
          ))}
        </Menu>
      );

      return (
        <Dropdown overlay={menu}>
          <div>
            {`${recordsLength - MAXTAGCOUNT} more...`}
          </div>
        </Dropdown>
      );
    }
```

So the result will look like this:
![screen shot 2018-01-24 at 3 10 08 pm](https://user-images.githubusercontent.com/5359697/35354669-c50ba644-0118-11e8-9c75-125640e954f6.png)

**Comment by weixiaohuster** [comment]
when will this feature be available ?

**Comment by chunglj** [comment]
when will `maxTagCount` for TreeSelect be available ?

**Comment by joesim** [comment]
I need this feature too

**Comment by zombieJ** [comment]
will release in `3.7.0`

**Comment by afc163** [comment]
Could we make this defaultly enable?

**Comment by zombieJ** [comment]
Which is the better magic number? maybe 5?
