### ISSUE TITLE
能否增加属性控制Modal组件在visible为false时依然可以渲染?

### ISSUE THREAD

**Issue by DegaoLi** [ant-design/ant-design#9125]
### Version
3.1.4

### Environment
chrome win10

### Reproduction link
[https://codesandbox.io/s/4r2m0yrm30](https://codesandbox.io/s/4r2m0yrm30)

### Steps to reproduce
第一次打开弹窗时，无法获得弹窗组件的引用。
再次打开才可以。

### What is expected?
增加属性控制在Modal visible为false时就可以让组件渲染，从而可以Modal中子组件的实例引用。例如打开窗口，子组件focus。

### What is actually happening?
visible第一次为true时，才渲染后获得子组件引用。之后再打开方能操作子组件。

**Comment by bang88** [comment]
> 增加属性控制在Modal visible为false时就可以让组件渲染，从而可以Modal中子组件的实例引用。例如打开窗口，子组件focus。

> 子组件focus

不可以在mount的时候自己设置获取焦点吗

**Comment by DegaoLi** [comment]
@bang88 试过，好像不行。

**Comment by yutingzhao1991** [comment]
I prefer to add a prop `onOpen`, it will be trigger when modal opened.

**Comment by DegaoLi** [comment]
我第一次打开通过setTimeOut()临时解决这个问题
