### ISSUE TITLE
cannot disable down button when InputNumber value is null

### ISSUE THREAD

**Issue by pivcec** [ant-design/ant-design#9129]
### Version
3.1.4

### Environment
Mac OS - 10.13.2 (17C88), Google Chrome - 63.0.3239.132 (Official Build) (64-bit), React 16.2

### Reproduction link
[https://codesandbox.io/s/53wy2pljjn](https://codesandbox.io/s/53wy2pljjn)

### Steps to reproduce
Hover mouse over input; click on down button

### What is expected?
Down button should be disabled when value is null

### What is actually happening?
Down button is not disabled, and value gets set to min value

---
Is there any way to use initial null value and have the down button disabled until value is not null and more than zero?

**Comment by yutingzhao1991** [comment]
Value only accept Number.

And maybe you can set `disabled={value == null}` to disabled input.

**Comment by pivcec** [comment]
Is there any way to conditionally disable only the minus button?

**Comment by yutingzhao1991** [comment]
@pivcec why you want set value null ? Give more infomation about your requirement.

**Comment by tastypackets** [comment]
Is there a reason setting the initial value to the min is not an option? For example:
https://codesandbox.io/s/lx9yq029zm

**Comment by afc163** [comment]
Sorry, it is not proper to disable up/down buttons when value is null or undefined.
