### ISSUE TITLE
Calendar component's mode props can't control

### ISSUE THREAD

**Issue by zhiyan** [ant-design/ant-design#9134]
### Version
3.1.4

### Environment
all

### Reproduction link
[https://codesandbox.io/s/o5ly4p25n9](https://codesandbox.io/s/o5ly4p25n9)

### Steps to reproduce
I hope Calendar's view mode could be controled outside the component itself. example use a toggle button in the parent component.

### What is expected?
when i changed mode props by parent compnent, the Calendar should switch the realistic mode.

### What is actually happening?
the Calendar didn't switch it's mode. mode props only work on the initial of Component.

**Comment by yesmeck** [comment]
Tagging as good first issue.
