### ISSUE TITLE
字体无法识别

### ISSUE THREAD

**Issue by taoeer** [ant-design/ant-design#9135]
@font-face{font-family:Monospace Number;src:local("Microsoft Yahei");}

压缩后chrome无法正确识别字体 `Monospace Number`
我猜原因可能是css压缩后把引号去掉了，而且Monospace本身是字体名，就会把Monospace Number当成错误的字体定义

![qq 20180126134411](https://user-images.githubusercontent.com/9425478/35426586-02a02b6a-029f-11e8-8946-dd8b3c52b335.jpg)

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/commit/506f97640ec34a6d3d9fdb18e8036e5d34796a5f
