### ISSUE TITLE
How to set Tree component halfCheckedKeys

### ISSUE THREAD

**Issue by Sylvenas** [ant-design/ant-design#9138]
### What problem does this feature solve?
Tree components are often used to display large amounts of data, so sometimes the data will be loaded asynchronously. In this case, how do we set some tree nodes in half checked state? Because only the state of the current hierarchical nodes is known at this time, it is not known which of the child nodes of the current hierarchical node are in the checked state.        

So i can't use the `checkedKeys` the set the checked keys, because a part of the current hierarchical nodes should be in half checked.

Thanks !

### What does the proposed API look like?
``` js
<Tree
      halfCheckedKeys={['1','2','5']}
     {... otherProps}
      >
      </Tree>
```

**Comment by zombieJ** [comment]
You can use `checkStrictly` to manage halfCheckedKeys: https://codesandbox.io/s/ymj0op2n9
