### ISSUE TITLE
Badge wrapped in Tooltip should hide default tooltip of Badge

### ISSUE THREAD

**Issue by roger-gl** [ant-design/ant-design#9139]
### Version
3.1.4

### Environment
Chrome 

### Reproduction link
[https://codesandbox.io/s/rrp7j6o4mn](https://codesandbox.io/s/rrp7j6o4mn)

### Steps to reproduce
Hover over Badge component

### What is expected?
Only the title provided by Tooltip should be shown.

### What is actually happening?
The Tooltip title and the Badge count is shown as a tooltip

**Comment by nikogu** [comment]
@roger-gl  

> Only the title provided by Tooltip should be shown

u mean only hover on title, Tooltip should be shown ?

**Comment by roger-gl** [comment]
@nikogu 

I think that if I hover over the Badge only the title of the Tooltip should be shown and not additional the default title (the count) from the Badge.

**Comment by dengfuping** [comment]
@roger-gl You can refer to the [demo](https://codesandbox.io/s/r1vl8w9q).

**Comment by deepseafishing** [comment]
@dengfuping Hi, I'm having the same issue and can't see anything from the demo link. It says something is wrong. How can make only the badge icon trigger the tooltip instead of the word text + badge?
