### ISSUE TITLE
WebPack 使用react-hot，使用ant后react-hot无法正常使用

### ISSUE THREAD

**Issue by hodgevk** [ant-design/ant-design#914]
在webpack启动react-hot，后修改component，react-hot无法自动加载刷新页面，报错如下：
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null

**Comment by afc163** [comment]
信息不足，建议自行搜索。

https://www.google.co.jp/search?q=Uncaught+TypeError:+Cannot+read+property+%27__reactAutoBindMap%27+of+null&ie=utf-8&oe=utf-8&gws_rd=cr&ei=KtmuVoOgGYbKmAXZ7rUo
