### ISSUE TITLE
Modal 在 React15 环境下，明文传入属性 getContainer={() => document.body} 导致原有 body 内容被替换

### ISSUE THREAD

**Issue by weihong1028** [ant-design/ant-design#9140]
### Version
3.1.0

### Environment
chrome58 / React15.6.2

### Reproduction link
[https://codesandbox.io/s/vnr90mr9nl](https://codesandbox.io/s/vnr90mr9nl)

### Steps to reproduce
1. 在 Modal-props 传入 getContainer={() => document.body}
2. 点击 open

### What is expected?
弹出 Modal 框的同时原有 body 内容不被覆盖

### What is actually happening?
弹出 Modal 框后原有 body 内容被覆盖

**Comment by benjycui** [comment]
You should not set `container` as `document.body`, just append a new div to `document.body`, and then use it as `container`:

```jsx
const div = document.createElement('div');
document.appendChild(div);

getContainer() { return div; }
```

**Comment by weihong1028** [comment]
是在这种特定的组合下才会出现，react16 + antd3.x 并没有这个问题，而且文档的默认值也是 `() => document.body`，并不需要外部提前创建 div append 到 body 上，我在 antd2.x + react15 并没有这个现象。

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by weihong1028** [comment]
抱歉，我发现提问带的重现链接的依赖被恢复成16了，您再试下 https://codesandbox.io/s/vnr90mr9nl

**Comment by benjycui** [comment]
react@15 + antd@2.x 也有同样的问题 https://codesandbox.io/s/03o160jw9n

**Comment by benjycui** [comment]
react@16 使用的是 React.createPortal，所以能兼容这种情况，但 antd 的代码一直都预期是 https://github.com/ant-design/ant-design/issues/9140#issuecomment-364027417

**Comment by weihong1028** [comment]
好的，不过文档的描述是否欠佳呢，因为看文档会认为是直接返回 document.body。

**Comment by benjycui** [comment]
@weihong1028 来个 PR 改改吧 😄

**Comment by NARUTOne** [comment]
@benjycui 虽然挂载上了，但是切换路由后，报错了
![image](https://user-images.githubusercontent.com/18441915/37399797-ccbbf7e2-27bd-11e8-8476-50a02daa8c50.png)
![image](https://user-images.githubusercontent.com/18441915/37399838-eb83d848-27bd-11e8-98f7-0b275e22b77b.png)

**Comment by Leonewu** [comment]
> @benjycui 虽然挂载上了，但是切换路由后，报错了
> ![image](https://user-images.githubusercontent.com/18441915/37399797-ccbbf7e2-27bd-11e8-8476-50a02daa8c50.png)
> ![image](https://user-images.githubusercontent.com/18441915/37399838-eb83d848-27bd-11e8-98f7-0b275e22b77b.png)

Did you solve this problem?
