### ISSUE TITLE
LESS customization in create-react-app

### ISSUE THREAD

**Issue by trofivan** [ant-design/ant-design#9143]
### Version
3.1.4

### Environment
Ubuntu 17.04 x64, Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app](https://ant.design/docs/react/use-with-create-react-app)

### Steps to reproduce
If I follow the steps described on the page https://ant.design/docs/react/use-with-create-react-app#Customize-Theme button color does not change. 

### What is expected?
Button color is #1DA57A

### What is actually happening?
Button color is #1890ff (primary default)

---
After remove the line `@import '~antd/dist/antd.css';` from App.css the button's color changes.

**Comment by afc163** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/507615/35442078-dfc9ae30-02e0-11e8-8be0-7a11506b5910.png">

**Comment by trofivan** [comment]
Uff, I'm sorry. @afc163 thank you ))
