### ISSUE TITLE
getFieldDecorator messages can only take strings preventing usage of react intl translations

### ISSUE THREAD

**Issue by SidiaDevelopment** [ant-design/ant-design#9146]
### Version
3.1.5

### Environment
Electron

### Reproduction link
[https://codesandbox.io/s/qk9vr6oklj](https://codesandbox.io/s/qk9vr6oklj)

### Steps to reproduce
None

### What is expected?
Form verifier message is able to take JSX.Elements for translation with react intl

### What is actually happening?
the message configuration only takes strings

**Comment by yesmeck** [comment]
You can use [formatMessage](https://github.com/yahoo/react-intl/wiki/API#formatmessage)
