### ISSUE TITLE
Allow elements other than Option in Select's children

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#9150]
### What problem does this feature solve?
Currently `Select` only accepts `Option` and `OptGroup` as its children, however in some cases we need more elements to visually customize the dropdown, for example we can add a `Divider` between two options:

```
|-----------------|
| Select all      |
|-----------------|
| Value A         |
| Value B         |
|-----------------|
```

### What does the proposed API look like?

We can be really excited to have this features supported like:

```
<Select>
  <Optionn value="all">Select All</Option>
  <Divider>
  <Option value="a">Value A</Option>
  <Option value="b">Value B</Option>
</Select>
```

`Select` can filter all `Option` and `OptGroup` elements to collect values and keys, and still keep other elements in its own place

**Comment by yesmeck** [comment]
Duplicate of #4853

**Comment by Namek** [comment]
> Duplicate of #4853

@yesmeck how is this a duplicate?

**Comment by colonel-badmotherfucker** [comment]
@yesmeck  how is it duplicate ?
