### ISSUE TITLE
升级3.1.5后，DatePicker不能正常选择 年、月

### ISSUE THREAD

**Issue by jsuper1980** [ant-design/ant-design#9152]
### Version
3.1.5

### Environment
macos10.13.3，chrome64.0.3282.119, react16.2.0

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
直接使用官网的demo，都不能正常选择年、月

### What is expected?
正常选择日期

### What is actually happening?
不能选择年月，只能手动输入

**Comment by yesmeck** [comment]
感谢反馈，发布了 3.1.6 已经暂时把有问题的修改回滚了。
