### ISSUE TITLE
TreeNode cann't add other element ? example: I want add ' <span> other data from service </span> ' in the TreeNode

### ISSUE THREAD

**Issue by WALLE729** [ant-design/ant-design#9159]
### What problem does this feature solve?
Tree can show more information

### What does the proposed API look like?
<TreeNode title={item.title} key={item.key} dataRef={item} html={'<span> XXXX </span>'}>
            {this.renderTreeNodes(item.children)}
</TreeNode>

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8997

https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

Please learn React first.

**Comment by WALLE729** [comment]
Thanks
