### ISSUE TITLE
合并单元格跨页问题

### ISSUE THREAD

**Issue by liqi07** [ant-design/ant-design#9160]
场景：
table数据动态生成，某项相同数据处理合并单元格，但是如果该项跨页，则展示有问题。

根据官网例子简单重现：

https://codepen.io/liqi07/pen/BYaBqm?editors=0010

**Comment by yesmeck** [comment]
暂时没有好的办法支持这种情况。

**Comment by yesmeck** [comment]
还有这种情况需要根据当前行的  `index` 和分页情况动态去计算 `rowSpan`。

**Comment by liqi07** [comment]
比如我有一个数据，需要第6至于12行合并，于是6到10 和 10到12 分开处理？
是这个意思？

**Comment by yesmeck** [comment]
是的。

**Comment by yesmeck** [comment]
一个例子 https://codesandbox.io/s/64m697mywr

**Comment by wushuangs** [comment]
1. 服务端返回的数据格式这样子，保证需要合并的数据在一个页面显示
`data:[
    {
         key: "1",
         skuName: "宝矿力水特,可口可乐"
    },
    {
         key: "2",
         skuName: "加多宝,可口可乐"
    }
]`

2. 前端拿到数据之后 分解成多条，Table rowSpan 去合并；

3. 把 table 的pageSize 设成动态的，需要计算

**Comment by xujiamin1216** [comment]
1. 不使用表格自带的分页，pagination设置为false；
2. 然后自己在表格底部用Pagination实现分页。
