### ISSUE TITLE
Form.Item 线上代码 filed 为空

### ISSUE THREAD

**Issue by xiekw2010** [ant-design/ant-design#9161]
### Version
3.1.3

### Environment
prod

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/a1d35de](https://riddle.alibaba-inc.com/riddles/a1d35de)

### Steps to reproduce
这段代码在本地跑的好好的，线上跑就会有这种问题

https://gw.alipayobjects.com/zos/rmsportal/qSwKUPHyINFTOGvDCYIb.png

### What is expected?
理想应该和本地一样

### What is actually happening?
FormItem getfiled 变空了

**Comment by benjycui** [comment]
服务端构建时使用的是 rc-form@1.x
