### ISSUE TITLE
方便说一下这个判断吗？

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#9162]
https://github.com/ant-design/ant-design/blob/4a9277277b686768218a7caf94392c543d220e67/components/date-picker/createPicker.tsx#L65

想了解一下，加这个判断的理由是什么？

因为我这边有一个需求是年日历，然后在抄代码和读源码的过程中，发现这一行会影响点击年日历的面板。。去掉这个if，我测试了日期及月份的组件，关系并不大。它的这个判断意义是？

**Comment by yesmeck** [comment]
非受控模式。
