### ISSUE TITLE
when using activeKey to control Panel's display state in Collapse, it should also can be controlled by clicking on header

### ISSUE THREAD

**Issue by haoqian3055** [ant-design/ant-design#9166]
### What problem does this feature solve?
Sometimes, we need to change panel's display state by other operations except clicking panel's header. But, now I only find a way to implement this function by a state to change activeKey property.  However, when using activeKey to control Panel's display state in Collapse, it will can't be controlled by click on panel's header. For example, I have a form in Panel's body, when I submit this form, I want to hide  the form automatically without clicking panel's header, then I also need can show this form by click panel's header.

### What does the proposed API look like?
I hope when using activeKey to control Panel's display state in Collapse, it also can be controlled by click on header.

**Comment by yutingzhao1991** [comment]
When you use `activeKey`, it's means the component is a controlled component. you should change the activeKey in `onChange` handler. ref: https://codesandbox.io/s/nw9x70zkpm .

**Comment by haoqian3055** [comment]
Thanks, you are right.  I also have a question.  How can I know there is a parameter 'key' in onChange handler ?  The api document in https://ant.design/components/collapse-cn/  don't  write it.

**Comment by yutingzhao1991** [comment]
@haoqian3055 hmm... welcome to make a PR to help us improve the doc.

**Comment by hasan-shafiq-ivolve** [comment]
if i have multiple panel in collapse and each panel have one or two button issue is that when i expand one panel and then stop propagation other panel become not expandable how i can i handle this condition plz help
