### ISSUE TITLE
form 表单项required为true时,点击递交按钮,(DatePicker,RangerPicker,Select 如果没有填值)开发环境运行正常,编译成dist版本运行报错

### ISSUE THREAD

**Issue by chowsource** [ant-design/ant-design#9167]
### Version
undefined

### Environment
react16 mac chrome63

### Reproduction link
[https://github.com/chowsource/antd-datepicker-bug-demo.git](https://github.com/chowsource/antd-datepicker-bug-demo.git)

### Steps to reproduce
form 表单required为true时,点击递交按钮,(DatePicker,RangerPicker,Select 如果没有填值)开发环境运行正常,编译成dist版本运行报错,是我编译姿势哪里不对吗

### What is expected?
编译和开发版本应该表现一致

### What is actually happening?
开发版本正常,编译版本报错

下图是编译成dist版本,点击递交按钮,会报错,而且菊花一直再转
![image](https://user-images.githubusercontent.com/5119971/35500281-f80f7538-0510-11e8-8ae0-1110f7fad59e.png)
![image](https://user-images.githubusercontent.com/5119971/35500492-9988d116-0511-11e8-8eae-5374086057d6.png)
Select组件也会报错转菊花
![image](https://user-images.githubusercontent.com/5119971/35500784-99b3910c-0512-11e8-9e75-2645f40c7787.png)

下图是开发调式模式运行一切正常
![image](https://user-images.githubusercontent.com/5119971/35500356-32f943cc-0511-11e8-8616-e19740a5cfff.png)

**Comment by yesmeck** [comment]
It's a build issue, it works after removing LodashModuleReplacementPlugin.

**Comment by chowsource** [comment]
@yesmeck 去掉LodashModuleReplacementPlugin就正常了,但是体积增加了,有没有类似组件减少不需要代码的
![image](https://user-images.githubusercontent.com/5119971/35505259-8d93a656-0520-11e8-8afc-c6ab7c8996ab.png)
去掉后体积变为
![image](https://user-images.githubusercontent.com/5119971/35505267-9283f95e-0520-11e8-91db-590895f1c832.png)

**Comment by yesmeck** [comment]
不好意思，构建的问题你要自己研究。

**Comment by chowsource** [comment]
@yesmeck 应该对LodashModuleReplacementPlugin提bug了,对antd支持有问题
