### ISSUE TITLE
API to show/ hide popover and tooltip

### ISSUE THREAD

**Issue by praneshr** [ant-design/ant-design#9168]
### What problem does this feature solve?
By adding this feature, one can control the visibility of popover or tooltip. 

### Use case:

I've a popover which triggers on `hover`. In the content of the popover, I've a clickable item. When clicked, it takes me to a new route(react-router). After going to the new route, I need the popover to hide.

### Current Secenario

As `hover` is handled internally there is no way to show/hide tooltip/popover manually. `visible` will not help as `onMouseOut` will close the popover.

### Example:

Check this [https://codesandbox.io/s/z3k94jy6y3](https://codesandbox.io/s/z3k94jy6y3)

### What does the proposed API look like?
`<Popover>.show()` - `show` function over an instance of popover/tooltip

`<Popover>.hide()` - `hide` function over an instance of popover/tooltip

**Comment by yesmeck** [comment]
Imperative call is not recommend in React, you can control visible state with `visible` prop.

**Comment by praneshr** [comment]
@yesmeck I agree. How can it handle my use case?

**Comment by yesmeck** [comment]
https://codesandbox.io/s/2knn3rop

**Comment by praneshr** [comment]
@yesmeck Thanks. But, your solution doesn't close the popover during `mouseLeave`.  I've updated your example to handle that. Thanks!

https://codesandbox.io/s/nwv74o40mj

**Comment by htk159131721** [comment]
if i have multi Popover?? Visibled all

**Comment by Vivek205** [comment]
> if i have multi Popover?? Visibled all

Having the same issue.

**Comment by s-kris** [comment]
> > if i have multi Popover?? Visibled all
> 
> Having the same issue.

Use multiple variables to control to multiple popovers.

**Comment by jiananshi** [comment]
This issues is definitely shouldn't be marked as closed

**Comment by amiram** [comment]
Here is a solution for multi popover. The idea is holding a variable in state that will instruct which popover top open.
I have multi popover in a table. The table is like:
```
<Table
   rowGetter={({index}) => this.props.users[index]}>
   <Column cellRenderer={(cell: TableCellProps) => this.someColumn(cell.rowData)}></Column>
</Table>
```
Each cell is showing an icon with a popover that shows the popover for this user. Each row has its own icon and popover.

```
someColumn(user) {
        return <span onMouseEnter={() => this.setState({visiblePopoverUserId: user.id})}
            onMouseLeave={() => this.setState({visiblePopoverUserId: null})}>
            <Popover
                visible={this.state.visiblePopoverUsertId === user.id}
                content={<button onClick={() => {this.setState({visiblePopoverUserId: null}); doAction();}}}>
                    <button>Hover here!</button>
            </Popover>
        </span>;
    }
```
