### ISSUE TITLE
showSearch 无法展示输入框

### ISSUE THREAD

**Issue by dotequiet** [ant-design/ant-design#9171]
### Version
3.1.6

### Environment
3.1。6

### Reproduction link
[https://codepen.io/anon/pen/aqbBdP?&editors=001](https://codepen.io/anon/pen/aqbBdP?&editors=001)

### Steps to reproduce
open the link https://codepen.io/anon/pen/aqbBdP?&editors=001

### What is expected?
show search input

### What is actually happening?
can't show search input

---
chrome

**Comment by yesmeck** [comment]
<img width="308" alt="screen shot 2018-01-29 at 20 56 36" src="https://user-images.githubusercontent.com/465125/35511451-ef014496-0536-11e8-8298-e4b23d7768b3.png">

**Comment by dotequiet** [comment]
![image](https://user-images.githubusercontent.com/20040134/35511487-1362fd48-0537-11e8-9ffe-68d87137d68d.png)
this is i wanted

**Comment by yesmeck** [comment]
We've removed this UI since 1.0.

**Comment by dotequiet** [comment]
how to  search seleted item

**Comment by yesmeck** [comment]
Search in the input directly.

**Comment by dotequiet** [comment]
ok
