### ISSUE TITLE
Theming Timeline component

### ISSUE THREAD

**Issue by mrgeorgegray** [ant-design/ant-design#9174]
### What problem does this feature solve?

Currently the `<Timeline />` component takes a `@primary-color` var to style the "-blue" items. There are also CSS selectors named "green" and "red" referencing other vars (success/error). I'd like to open a PR to move the vars into the theme/default.less so we can customise the look of the component, however I'd like to get some feedback on what to name these modifiers. 

related: https://github.com/ant-design/ant-design/blob/master/components/timeline/style/index.less#L44-L55

### What does the proposed API look like?
I was thinking, `-primary`, `-secondary`, `-tertiary` or perhaps `-info`, `-success`, `-error`?

**Comment by dengfuping** [comment]
@mrgeorgegray It's not necessary to make such a change, because these are the values of color property, not `type` property.

**Comment by mrgeorgegray** [comment]
thanks @dengfuping for your feedback and sorry if I was not clear before, my proposal is to change the `color` prop to something like `type` instead. The reason for this is because [`-blue` is coupled with `@primary-color`](https://github.com/ant-design/ant-design/blob/master/components/timeline/style/index.less#L44-L55). When theming AntDesign, if I change `@primary-color` to "pink", setting the `color` prop to `blue` on the `Timeline` component will actually turn it "pink", not "blue" as the prop would currently suggest.
