### ISSUE TITLE
[Customized Form Controls] Add design convention: cloud have controlled property  `validator`.

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#9181]
### What problem does this feature solve?
When designing a `Customized Form Controls`, we may pass value or defaultValue with a simple structure, but build a complicated data structure inside the `Control`. Applying custom validators on the customized control like [the official sample](https://ant.design/components/form/#components-form-demo-customized-form-controls) does, we have no way to dig out the deep details inner, can't re-use some validation methods the `Customized Control` defined and it's hard to predicate the exposed `value` is valid.

The new convention, make it possible that every time we trigger changes, we feed the prop `validator` with error messages. Each form validation occurrence, form instance collect these error messages.
A variant of this convention is exposing `validator` property of `Customized Form Controls`, it will be call in validation occurrence through `ref` by form instance.

### What does the proposed API look like?
1. validator prop convention

```
class CustomizedControl extends React.Component {
    handleChange = (values) { // this values may be very complicated, but is parsed and easy to validate

        // this is a converter for changing inner values to external values. Certainly, we also have converter to handle outside 'value' and 'defaultValue'.
        const externalValues = this.converter(values)

        if (this.props.onChange) {
            this.props.onChange(externalValues) // externalValues is simple for submitting.
        }
        if (this.props.validator) {   // proposal here! feed errors to validator prop while changing

            // erro1Validator can easy validate innerValues
            const error1 = this.erro1Validator(values) || [] 
            const error2 = this.error2Validator(values) || []

            this.props.validator([error1, error2])
        }
    }
}
```

2. or a variant convention:

```
class CustomizedControl extends React.Component {
    validator = () => {  // proposal here! employ an instance method 'validator' or 'validate', return validation erros
        const error1 = this.erro1Validator(this.state.values) || []
        const error2 = this.error2Validator(this.state.values) || []

        return [error1, error2]
    }
}
```

**Comment by benjycui** [comment]
It's weird to pass validator to component...

> When designing a Customized Form Controls, we may pass value or defaultValue with a simple structure, but build a complicated data structure inside the Control.

How about just expose the complicated structure to form? But you can create a helper class to make your use case simpler.

```jsx
class Value {
  static fromJSON(str) {
    const snippets = str.split(' ');
    return new Value(snippets[0], snippets[1]);
  }

  constructor(price, currency) {
    this.price = price;
    this.currency = currency;
  }

  toJSON() {
    return `${this.price} ${this.currency}`
  }
}

function serializer(key, value) {
  return value.toJSON ? value.toJSON() : value;
}

const value = Value.fromJSON('10 RMB');
console.log(JSON.stringify(value, serializer)); // => "10 RMB"
```

**Comment by zheeeng** [comment]
@benjycui Let me conclude your solution, exposing the in/out converter, static validator util, manually validate data. I have thought that before. It seems good to bring no more conventions, free to self-dependent designing.

But there are still some corners:

1. This way makes the converter to be called at every time validation triggers. What if the converting is heavy cost?

2. The static method has no way to access inner state, which sometimes contributes to the validation. e.g. The output value is deepened on the sum of dices, should we also expose the sum and document a guide for using the validator util?

3. If the validator convention is accepted, the validation fails message could be collected automatically. 

4. The value and onChange props build a two ways binding flow and hidden the data converter by design. Maybe some ppl don't like exposing a 'redundant' converter? Customized Form Component provide built-in validator sounds can't natural more.

BTW, I have another question that, is there any chance that we can directly access the `rules` defined in getFieldDecorator and the error message?
I get this these infomation by reading `this.props['data-__meta']` and `this.props['data-__field']` in the Controled Component.

![image](https://user-images.githubusercontent.com/1303154/35971594-9027ef26-0d09-11e8-8547-5ada09509252.png)

**Comment by benjycui** [comment]
> This way makes the converter to be called at every time validation triggers. What if the converting is heavy cost?

Actually, it won't. We don't need to convert it to validate. And we will only use the helper class when we need to submit the data to server or render it to HTML. So it will be faster than `props.validator`, which will need to convert the value every time it is changed.

**Comment by benjycui** [comment]
> The static method has no way to access inner state, which sometimes contributes to the validation. e.g. The output value is deepened on the sum of dices, should we also expose the sum and document a guide for using the validator util?

Why do you need to do so? Just store every field that value needed to value, and then pass the value to `onChange`

**Comment by benjycui** [comment]
> BTW, I have another question that, is there any chance that we can directly access the rules defined in getFieldDecorator and the error message?

Just use `getFieldError` to read errors of a field.

And why do you need to read `rules` from a from field? It is  YOU who passed rules to it.

**Comment by zheeeng** [comment]
@benjycui My proposal does not require data converting, use built-in(not-exposed, in this example, it is `this.validator`, which runs fast) to validate inner data structure, and then pass the validation error message to `this.props.validator`. A common form UX is error message display field is responsing for each value change event, e.g. an `email` form input is displaying invalidate message until the validation pass.

**Comment by zheeeng** [comment]
I indeed pass the converted value to `onChange`. My point is the validation needs inner the state. If we expose a static validator, it can't access the inner state. At the concurrence of converting the `internal value` to `external value` and then pass it to `this.props.onChange`, we also have the chance to collect inner state(e.g. sum of three dices state) and internal value for validation and then feedback the error messages array to `this.props.validator`.

**Comment by zheeeng** [comment]
`getFieldError ` can only be called outside the controlled component. Assuming we have a rule: `required` in `getFieldDecorator `, the controlled need a mechanism to access the `required` rule, and `message` text, and be responsive to the rule.
I made a `Cascade Multiple Select Input`, it has its own label field, own error message field, a built-in validator. Needs some ways to feedback the validation message to provide the outside `form` with validation info and external value.

**Comment by afc163** [comment]
Check new form component in v4.
