### ISSUE TITLE
Select Component with labelInValue option get wrong value

### ISSUE THREAD

**Issue by Mr-Yy** [ant-design/ant-design#9182]
### Version
3.1.6

### Environment
macOS 10.13.2, Chrome 63

### Reproduction link
[https://codesandbox.io/s/rlww31nxpm](https://codesandbox.io/s/rlww31nxpm)

### Steps to reproduce
I use Select Component in Form.Item with  getFieldDecorator, then select an option and see the log in console. Please see detail in Reproduction link

### What is expected?
```javascript
{
  key: '1',
  label: 'Jack'
}
```

### What is actually happening?
```javascript
{
  key: '1',
  label: '1'
}
```

**Comment by yesmeck** [comment]
`labelInValue` is not expected to work with `combobox` mode.

**Comment by marcosfede** [comment]
Why shouldn't `labelInValue` work in combobox mode? The API should as similar as possible between multiple and single selections

**Comment by Mr-Yy** [comment]
I use `showSearch` and `onSearch` to achieve the feature that select one from request, it seem like `combobox` mode. But Component style is "Select"  not "Input". So, what the `combobox` mode is prefer to do?

**Comment by yesmeck** [comment]
`combobox` is a input in fact.

**Comment by jwmann** [comment]
I'm also having this problem. The API should be consistent.

Even if you manually pass the value of `{ key: 1, label: 'Foo', value: 'Foo' }` it still uses the key instead.
I need to be able to keep the relationship between the key and the label.

Please reconsider.

**Comment by yutingzhao1991** [comment]
@jwmann I have the same opinion as @yesmeck. `combobox` is a input, you can treat the select option just as a quick input helper. For your demand, maybe you can store which option has been selected with `onSelect`.

**Comment by jwmann** [comment]
So I thought I could avoid this by using the Autocomplete component, except looking further into the actual autocomplete component; It's literally just a combobox Select component.

So now I'm pretty stuck.

@yutingzhao1991 I can technically change the `onSelect` as you say, and that sorta works but I'm not sure what I should doing in that function besides choosing the label. I'm also using this inside a `FieldItem` with a `getFieldDecorator`. Which seems to hijack the value and the onChange.

Extremely frustrating.
