### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by qiqingjin** [ant-design/ant-design#9183]
### What problem does this feature solve?
我在使用antd的LocaleProvider时候发现，阿拉伯语等不会自动修改样式为RTL。目前原生支持RTL的UI库并不多，如果antd可以支持，对我们这些开发者将会有非常大的帮助，对antd的国际化也会有很大帮助。我看到了issue #4051，但是没有一个明确的结论。请问目前对RTL支持的进展如何，如果需要，我们团队愿意参与到相关开发中。

### What does the proposed API look like?
希望检测到阿语等语言，自动修改页面所有components为右向左排版。可以使用类似Bootstrap 4的方式（https://github.com/DediData/Bootstrap-RTL），加载一个rtl-antd.css文件，来覆盖原来的样式。

**Comment by afc163** [comment]
继续在 #4051 里讨论即可。
