### ISSUE TITLE
从3.1.0升级到3.1.6后，日期控件的国际化没有按照预期的显示中文

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#9185]
### Version
3.1.6

### Environment
chrome 63.0.3239.84 ，win10 

### Reproduction link
[https://codesandbox.io/s/10jzyx3vv7](https://codesandbox.io/s/10jzyx3vv7)

### Steps to reproduce
查看 示例

### What is expected?
日期控件的国际化按照预期的显示中文

### What is actually happening?
日期控件的国际化没有按照预期的显示中文

---
通过查看`node_modules/antd/lib`下的源码，发现模块不默认支持`,CommonJS`的require写法了。要写成`require('xxxx').default`。

期望支持`UMD`模块的写法

**Comment by afc163** [comment]
这是对的。

```diff
- const zh_CN = require('antd/lib/locale-provider/zh_CN');
+ import zh_CN from 'antd/lib/locale-provider/zh_CN';
```

**Comment by yunxifd** [comment]
这算不算不兼容改动

**Comment by afc163** [comment]
@yesmeck 

We lost `module.exports = exports['default'];` after 3.1.2

similar issue #8881

**Comment by yesmeck** [comment]
那要把 `babel-plugin-add-module-exports`  加回来了。但是最终这个插件可能还是要去掉，目前只支持到 babel@6。

**Comment by yesmeck** [comment]
先加回来了。
