### ISSUE TITLE
Component Card generates an extra div inside div.ant-card-body when migrating from 2 to 3

### ISSUE THREAD

**Issue by cathayandy** [ant-design/ant-design#9186]
### Version
3.1.6

### Environment
MacOS 10.12.3, Google Chrome 63.0.3239.132, React 16.2.0

### Reproduction link
[https://ant.design/components/card-cn/](https://ant.design/components/card-cn/)

### Steps to reproduce
Check the first example in your official doc (both in 2.x and 3.1.6).

```
<Card title="Card title" extra={<a href="#">More</a>} style={{ width: 300 }}>
  <p>Card content</p>
  <p>Card content</p>
  <p>Card content</p>
</Card>
```

Check the structure of rendered div.ant-card-body in dev tools.

### What is expected?
In 2.x:

```
<div class="ant-card-body">
  <p>Card content</p>
  <p>Card content</p>
  <p>Card content</p>
</div>
```

### What is actually happening?
In 3.x:

```
<div class="ant-card-body">
  <div>
    <p>Card content</p>
    <p>Card content</p>
    <p>Card content</p>
  </div>
</div>
```

---
When I use Card in antd@2, I can set `Card.props.bodyStyle` to

```
{ height: calc(100% - theme['card-head-height'] }
```

, and set `Card.props.children` to

```
<div style={{ height: 100% }} />
```

to get **a child with 100% body height**.

But this is broken due to the extra div added in antd@3. And **I can't directly set height on the inner div** because the Card height is controlled by a global gird system(`react-grid-layout`).

**Comment by cathayandy** [comment]
The change was found in commit 2b1bed42c911dfd245aca339b6478a5c7dcb1463. I guess u did this just because u need to wrap multiple components(line 169):

```
{loading ? loadingBlock : <div>{coverDom}{children}</div>}
```

However, the implementation was changed(line 183):

```
{loading ? loadingBlock : <div>{children}</div>}
```

U don't need this wrap now. Also u can use Fragments(`<></>`) to wrap multiple components now.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/2e45074fab2b3f87aeab4e2d1ec8da978680e01f

**Comment by afc163** [comment]
Fixed in #9226

**Comment by cathayandy** [comment]
Thank u very much!

**Comment by yxyhaoshuai** [comment]
什么鬼,为什么都是老外
