### ISSUE TITLE
FORM 表单联动  两个select 的时候  通过this.form 设置值不能进行选择， 通过state改变，会重置第一个select

### ISSUE THREAD

**Issue by headgreen** [ant-design/ant-design#9187]

**Comment by tommymsw** [comment]
我也遇到同样的问题，就是我有一个表单 表单里面有两个 Select 组件， 第二个Select 组件里的数据源是根据第一个 Select 选择的变动而变动的，  当第一个Select onChange后，去数据库异步去第二个Select 数据源  然后 setState  ,这样的话 第一个Select 会被重置。
   
另外还有个问题，为什么作为一个中国企业开发的开源框架，经常有人用中文提问就会出现这样的回答：
It will better to write your issue/comment in English, so more people can understand you.
对，我可以理解要国际化，但是不可回避的是事实，这个框架还是中国人用的最多， 用中文回答下问题就不可以吗？

**Comment by zluo001** [comment]
@tommymsw 装x劲比较大，还more people can understand you。面对问题不解决，more people can laugh at you ali。KPI框架名不虚传。
