### ISSUE TITLE
FORM 表单联动 两个select 的时候 通过this.form 设置值不能进行选择， 通过state改变，会重置第一个select

### ISSUE THREAD

**Issue by headgreen** [ant-design/ant-design#9189]
### Version
3.1.6

### Environment
win7、chrome63

### Reproduction link
https://codepen.io/headgreen/pen/YePomx?editors=0010

### Steps to reproduce
如链接

### What is expected?
form 表单中的 select联动

### What is actually happening?
通过表单联动this.form设置第二个select后不能进行选择，通过state控制，会重置第一个select

**Comment by headgreen** [comment]
https://codepen.io/headgreen/pen/ZrYWjj?editors=0010

**Comment by yesmeck** [comment]
Your link is not working.

**Comment by headgreen** [comment]
已近更新

**Comment by headgreen** [comment]
已经更新https://codepen.io/headgreen/pen/YePomx?editors=0010

**Comment by yesmeck** [comment]
不应该在 render 里创建组件。

**Comment by headgreen** [comment]
@yesmeck 可以单独那拿出来做一个组件  ， 需要数据 在通过props 传递进去 吗

**Comment by yesmeck** [comment]
可以。

**Comment by tommymsw** [comment]
hi ali guys, I have the same problem for some days, can give some suggestion or idea ?
