### ISSUE TITLE
Avoid style dependency with Button in Modal component

### ISSUE THREAD

**Issue by ApacheEx** [ant-design/ant-design#9190]
### Version
3.1.6

### Environment
Google Chrome 64.0.3282.119

### Reproduction link
[https://codesandbox.io/s/6l7nmzy3yw](https://codesandbox.io/s/6l7nmzy3yw)

### Steps to reproduce
Just open a sandbox to see "Open" button.

### What is expected?
"Open" button should have Red background.

### What is actually happening?
- As you can see I don't import antd styles from `Button`, because I use own styles. 
- As soon as I import `Modal` styles, all `Button` styles from antd will be attached and my own styles (`StyledButton`) won't work.
- If I remove `import 'antd/lib/modal/style/css';` from `app.js` all work again. But I need to have `Modal` styles.

- As solution: remove `Button` styles dependency from `Modal` styles.

---
I use styled-components to provide own styles.

**Comment by dengfuping** [comment]
@ApacheEx No such configuration available to avoid style dependency currently. You can use style prop to cover the default style of Button.

**Comment by ApacheEx** [comment]
@dengfuping 
thanks for quick response, I will use the following workaround:

1. Add `import 'antd/lib/button/style/css';` to `button.js`
2. Override styles as I wish (color, width, height, etc...) in `StyledButton`
3. Import styles from Modal
4. Use StyledButton in Modal
