### ISSUE TITLE
表单中的 Upload 组件的 beforeUpload 阻止上传，“Uploading...”与错误提示语同时出现

### ISSUE THREAD

**Issue by codelegant** [ant-design/ant-design#9191]
### Version
3.1.6

### Environment
win10  chrome 64   reactV15.6.1

### Reproduction link
[https://codepen.io/codelegant/pen/YePVXM?editors=0010](https://codepen.io/codelegant/pen/YePVXM?editors=0010)

### Steps to reproduce
上传一个非图片文件，直接显示错误信息，而不是“Uploading”的提示语与错误信息同时显示。
![错误行为](https://s1.ax1x.com/2018/01/30/9CwmrQ.png)

### What is expected?
不显示 “Uploading...”的提示

### What is actually happening?
“Uploading...”与错误提示同时出现
![错误行为](https://s1.ax1x.com/2018/01/30/9CwmrQ.png)

**Comment by afc163** [comment]
Duplicate of #8020
