### ISSUE TITLE
InputNumber cursor positioning error

### ISSUE THREAD

**Issue by rockwong** [ant-design/ant-design#9193]
### Version
3.1.6

### Environment
Mac os   and Chorme 63

### Reproduction link
[https://ant.design/components/input-number/](https://ant.design/components/input-number/)

### Steps to reproduce
Change format the amount '$100' to '$1,200'

### What is expected?
The cursor is positioned after '2'

### What is actually happening?
The cursor is positioned at the end

**Comment by dengfuping** [comment]
@rockwong It's an expected result when the input value is formatted, not an error.

**Comment by yesmeck** [comment]
@dengfuping We should improve this behavior.

**Comment by afc163** [comment]
Duplicate of #9204
