### ISSUE TITLE
Antd Modal loads slow with large amount of content in it

### ISSUE THREAD

**Issue by jm90m** [ant-design/ant-design#9194]
### Version
3.1.6

### Environment
OSX, Chrome

### Reproduction link
[https://busy-master-pr-1376.herokuapp.com/](https://busy-master-pr-1376.herokuapp.com/)

### Steps to reproduce
* Click on any post title and this will open a modal
* Scroll down feed, and open more modals by clicking either Post Title or Post Preview Image
Modals load slow and response time is slow on close

### What is expected?
Modal responds fast

### What is actually happening?
Modals load slow and response time is slow on close

---
Tried to optimize it as much as possible, any suggestions would be great, https://github.com/busyorg/busy/pull/1376

**Comment by yesmeck** [comment]
1. You can use [why-did-you-update](https://github.com/garbles/why-did-you-update) and [react-devtools](https://github.com/facebook/react-devtools)'s  to find out which operation slow down your application.
2. Try add `destroyOnHide` to `Modal`.

**Comment by Evavic44** [comment]
> 1. You can use [why-did-you-update](https://github.com/garbles/why-did-you-update) and [react-devtools](https://github.com/facebook/react-devtools)'s highlight updates feature  to find out which operation slow down your application.
> 2. Try add `destroyOnHide` to `Modal`.

The Why-did-you-update library has reached EOL for quite a while now. Anyone wondering can use an alternative https://github.com/welldone-software/why-did-you-render
