### ISSUE TITLE
请问在内网中不能下载index.css中的资源文件如何解决？谢谢

### ISSUE THREAD

**Issue by Comup-X** [ant-design/ant-design#9197]
content.js:220 GET https://at.alicdn.com/t/font_148784_r2qo40wrmaolayvi.woff net::ERR_CONNECTION_RESET
ready @ content.js:220
10.131.0.121/:1 GET https://at.alicdn.com/t/font_148784_r2qo40wrmaolayvi.ttf net::ERR_CONNECTION_RESET

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
