### ISSUE TITLE
Message全局提示组件,支持最多显示1次提示信息

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#9198]
### What problem does this feature solve?
message重复循环显示，影响页面交互。

### What does the proposed API look like?
message.overflow=true

**Comment by afc163** [comment]
是希望多个 message 在同一个位置互相覆盖？

ref https://github.com/ant-design/ant-design/issues/3543

**Comment by jeffycai** [comment]
right

**Comment by jeffycai** [comment]
stack: false is not work

**Comment by nikogu** [comment]
@jeffycai 你为什么会重复循环显示 `message` 呢，你可以自己控制显示 message 的时机呀，你想显示它一次你就自己控制让调用的时候只在最后一次显示不就好了

**Comment by sbyps** [comment]
@nikogu 就是官网上的示例，比如提交前有错误，然后message提示不能提交，然后就能点很多次提交按钮然后出来一堆message，很影响交互；其实应该能控制只显示多少条message吧

**Comment by jeffycai** [comment]
@afc163 @nikogu 入口是可以控制住显示次数，但是如果组件支持，那就更灵活了。

**Comment by afc163** [comment]
#3543 里提到的 PR 还有问题，所以被回滚了，你可以按 @yeliex 的思路再 PR 一个。

**Comment by yeliex** [comment]
我们现在全部换用notification了:)

经过考虑得出结论: 错误提示这些需要多条醒目提醒的 应该是用类似alert或者notification这种醒目 可以同时提示的 
message应该是一个很弱的消息提醒 暂时没有遇到不能用notification代替message的场景

**Comment by nikogu** [comment]
@sbyps 我感觉你说的这个有问题，点击多次提交按钮是用户的操作，是需要有反馈的，如果你点一次就没反应了，那万一用户没看清楚之前的问题，结果再点都没提示了，这个交互才完全不是最佳实践，甚至是有问题。

**Comment by nikogu** [comment]
> 入口是可以控制住显示次数，但是如果组件支持，那就更灵活了

@jeffycai 我个人认为组件要在灵活度和使用规范上要有平衡，可能确实灵活了，但是正是因为灵活导致规范不了交互，导致使用组件做出来的页面没有交互体验。

**Comment by sbyps** [comment]
![qq 20180201194210](https://user-images.githubusercontent.com/3881956/35676770-0dd6410c-0788-11e8-9727-5f9f490a313e.png)
那这种情况也是好的交互体验吗？还有别的方案么

**Comment by jeffycai** [comment]
@nikogu 没有对和错，支持了更好，不支持也不是错。

**Comment by kanweiwei** [comment]
@sbyps Maybe you can try this, if you can accept
https://codesandbox.io/s/716r26x820

**Comment by jzhangs** [comment]
Proposal patch to rc-notification to add a 'maxItems' prop, may it accepted, it would be fine to use
```
message.config({
  maxItems: 1
}); 
```
to fulfill this feature. I would suggest we set defaultMaxItems of Message to 3.

**Comment by jzhangs** [comment]
@afc163 @nikogu guys, what do you think about this proposal?

**Comment by nikogu** [comment]
@jzhangs pr welcome

**Comment by jeffycai** [comment]
message.config({
    top: 0,
    stack: false,
});

**Comment by nikogu** [comment]
@jzhangs do you have time to update Message with new params, i already publish `rc-notification` to `3.1.5`

**Comment by jzhangs** [comment]
@nikogu PR to `feature-3.5`, please check. No default maxCount.

**Comment by tangofe** [comment]
where is the  'message.config({
top: 0,
stack: false,
});'  set? it can't work when i use it

**Comment by shen-lan** [comment]
@tangofe Hi,  do you resolved it ?
