### ISSUE TITLE
RangePicker 面板 能否把被选中结束日期显示在右侧，左侧面板显示其上个月

### ISSUE THREAD

**Issue by Shirley89** [ant-design/ant-design#9202]
### What problem does this feature solve?
1、原来提过一个issue，回答说使用defaultPickerValue属性，但是只能勉强在初始化并且没有选择的时候显示当前日期在右侧，但是一旦选择日期以后就会把选择日期显示在左侧面板

2、我这里有需求是不允许用户选大于今天的日期，那么我真的禁止用户选大于今天的日期显示效果就会很恐怖，右侧（即下个月）整个面板都是灰色的（不能选），所以我只好委曲求全把禁止选择大于今天日期的功能给咔嚓掉，大大们，能帮忙解决么？

### What does the proposed API look like?
期望能够将选中的结束日期所在月份放在右侧面板，如果不希望改变现有逻辑，能否加一个属性给配置一下下？

**Comment by yesmeck** [comment]
建议自定义一个范围选择吧 https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end

**Comment by vonxq** [comment]
@Shirley89 我也碰到了一样的问题，请问你是怎么解决的呢?

**Comment by Shirley89** [comment]
@vonxq 无解，看楼上的回答，叫我们用他们提供的方案解决

**Comment by Shirley89** [comment]
@hughfenghen 可以说相当hack，非常感谢

**Comment by PSInsight** [comment]
> @vonxq 无解，看楼上的回答，叫我们用他们提供的方案解决

我也遇到这个问题了，有解吗

**Comment by LadenxxxxD** [comment]
rangepicker选择当前日期之前的范围，而禁用当前日期之后，不是一种很常见的场景吗？现在的逻辑怎么看都像是只对选择未来日期的支持更友好
