### ISSUE TITLE
customize Tag component (close icon)

### ISSUE THREAD

**Issue by cyxn** [ant-design/ant-design#9203]
### What problem does this feature solve?
So I have an items that previously have been picked by user, I render them as <Tags />. also user can close this items (closable), in my case this is delete action. This delete action is sort of dangerous action, like it's gonna do some other changes related to this items. I'd like to show popconfirm before closing(deleting) this item, with some short message. I think this is also actual for select(tag mode). The end user experience is to show that is is not a simple action, and he has to be careful with this close action.

### What does the proposed API look like?
My thoughts about api is to make some 'customCloseIcon' prop - Function(onClose):ReactNode
```javascript
<Tag
    key={item.id}
    color={'#108eed'}
    closable
    onClose={() => this.deleteDangerousItem(item.id)}
    customCloseIcon={(onClose) => (
        <Popconfirm
            title="Are you sure?"
            onConfirm={onClose}
            onCancel={() => {}}
            okText="Yes"
            cancelText="No"
        >
            <Icon type="cross" />
        </Popconfirm>
    )}
>
    <span>{item.name}</span>
</Tag>
```
as far as I know it won't break api, it's still going to be animated and stuff like that

**Comment by yesmeck** [comment]
You can prevent close in onClose `onClose={e => e.preventDefault()}`.

**Comment by cyxn** [comment]
ye, but I'd like to show popconfirm

**Comment by yesmeck** [comment]
Hmm, that could be a problem. Maybe we can add  a `close`  prop,  then you can control it's close state.

**Comment by cyxn** [comment]
Sorry, I can not understand how can I show popconfirm above close icon of tag by this way

**Comment by yesmeck** [comment]
You can not do it with the current API

**Comment by cyxn** [comment]
I think it's possible with my api proposal with customCloseIcon

I mean I want something like that
![image](https://user-images.githubusercontent.com/20022927/35628073-735085fa-06a3-11e8-850b-3a038a37f5ae.png)

**Comment by yutingzhao1991** [comment]
Hmm, In this case, I recommend use Button + Icon. Custom close Icon maybe too complicated to Tag.

**Comment by cyxn** [comment]
![image](https://user-images.githubusercontent.com/20022927/35665116-60f89566-072d-11e8-9756-2c16149622d6.png)
works perfectly, I can send pr

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/10890
