### ISSUE TITLE
InputNumber loses caret position if formatter is used

### ISSUE THREAD

**Issue by Jabher** [ant-design/ant-design#9204]
### Version
3.1.6

### Environment
Chrome 63, win

### Reproduction link
[https://codesandbox.io/s/m4zj78jr88](https://codesandbox.io/s/m4zj78jr88)

### Steps to reproduce
1. place caret AFTER ',' sign
2. type anything

### What is expected?
caret keeps its position

### What is actually happening?
caret re-locates to input end

**Comment by fayhy** [comment]
I have reprocedured this issue only with US IME.

And there is another problem when using Chinese IME (eg Microsoft Pinyin). 
Say here is $123, when I typing 4 at the end, the value is '$1,234', and caret should be after '4', but it is after '3' for now.

**Comment by LuckyYaYaChen** [comment]
这个问题解决了吗？怎么关闭issue了？？我也遇到此问题。。。
