### ISSUE TITLE
Table ,filter,children

### ISSUE THREAD

**Issue by cookiexin** [ant-design/ant-design#9209]
### Version
3.1.6

### Environment
react-native 版本

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
1.点击可控的筛选和排序表格中表头中name旁边的filter按钮
2.hover到弹出框的第三个选项submenu出现green和black选项
3.点击选择框后子选项卡没有消失 并且数据被筛选有问题

### What is expected?
得到跟上一级一样的效果

### What is actually happening?
点击选择框后子选项卡没有消失 并且数据被筛选有问题

**Comment by yesmeck** [comment]
> over到弹出框的第三个选项submenu出现green和black选项

并没有第三个选项。

**Comment by cookiexin** [comment]
可是filter里的children使用确实是有bug

**Comment by yesmeck** [comment]
提供下重现

**Comment by yesmeck** [comment]
react-native?

**Comment by cookiexin** [comment]
不好意思弄错了是系统版本 3.0.2  如下这样写会有问题
 filters: [{
    text: 'Submenu',
    value: 'Submenu',
    children: [{
      text: 'Green',
      value: 'Green',
    }],

**Comment by cookiexin** [comment]
children栏点击后会有问题

**Comment by yesmeck** [comment]
https://codesandbox.io/s/v3vm9kwkll

**Comment by cookiexin** [comment]
<img width="455" alt="screen shot 2018-02-02 at 10 47 39 am" src="https://user-images.githubusercontent.com/17781326/35714287-b6186b1e-0806-11e8-9387-8791e7e7568d.png">
<img width="458" alt="screen shot 2018-02-02 at 10 47 48 am" src="https://user-images.githubusercontent.com/17781326/35714288-b64e495a-0806-11e8-8a5c-c26abb6f369f.png">
