### ISSUE TITLE
Upload 支持图片裁剪功能

### ISSUE THREAD

**Issue by myhere** [ant-design/ant-design#921]
upload 组件是否可以支持下图片裁剪功能~

**Comment by afc163** [comment]
交互过于复杂了，暂时不支持。建议由业务自行实现。

**Comment by huangm-fat** [comment]
同样希望支持下图片裁剪功能～

**Comment by blade254353074** [comment]
@huangm-fat 这种需求不是基础组件，还是自己实现吧。

**Comment by benjycui** [comment]
http://roadmanfong.github.io/react-cropper/
