### ISSUE TITLE
Mention组件，当存在placeholder的时候，右击的时候无法黏贴文字

### ISSUE THREAD

**Issue by Rosyeal** [ant-design/ant-design#9215]
### Version
3.1.6

### Environment
任何版本

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
第二行第二个input框内，存在placeholder的情况下，右击无法粘贴

### What is expected?
右击可以粘贴

### What is actually happening?
右击无法粘贴

**Comment by dengfuping** [comment]
@Rosyeal No such problem found in my chrome and safari. Could you give a gif to show that?

**Comment by yutingzhao1991** [comment]
![image](https://user-images.githubusercontent.com/1061968/35853866-b4875a92-0b69-11e8-86c3-1f90290068ec.png)

他说的应该是这个意思，右键没有粘贴，下面的一个例子是有的：

![image](https://user-images.githubusercontent.com/1061968/35854292-f078c7ec-0b6a-11e8-885d-47dcd955b9d7.png)
