### ISSUE TITLE
Introduce a scripts package which can be used with create-react-app.

### ISSUE THREAD

**Issue by SZzzzz** [ant-design/ant-design#9216]
### What problem does this feature solve?
I developed a [scripts package](https://github.com/SZzzzz/react-scripts-ts-antd/tree/master) base on [react-scripts-ts 2.13.0](https://github.com/wmonk/create-react-app-typescript). It's integrated [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin), [react-app-rewired](https://github.com/timarney/react-app-rewired), sass loader, less loader and etc.So you can create a new typescript antd project with **create-react-app my-project --scripts-version=react-scripts-ts-antd** and start it without any configurations.
 

### What does the proposed API look like?
I want to share this package with other antd users and hope you can add a link into the document. The url of repository is https://github.com/SZzzzz/react-scripts-ts-antd. Thank you.

**Comment by yesmeck** [comment]
You can PR to https://ant.design/docs/react/use-in-typescript#Alternative-way

BTW, I'd recommend you write your README in English.

**Comment by SZzzzz** [comment]
Thanks for your recommendation. I will write it in English and create a PR.
