### ISSUE TITLE
Table固定列模式下，使用受控的Popconfirm出现问题

### ISSUE THREAD

**Issue by fayhy** [ant-design/ant-design#9217]
### Version
3.1.6

### Environment
chrome

### Reproduction link
[https://codepen.io/fayhy/pen/pajoeL](https://codepen.io/fayhy/pen/pajoeL)

### Steps to reproduce
调整至出现可以出现横向滚动条的大小，点击action

### What is expected?
固定列处，展示一个Popconfirm

### What is actually happening?
出现两个Popconfirm
- 一个在固定列上（ant-table-fixed-right 区域）
- 一个在滚动列上（ant-table-scroll区域）

---
在需要手动控制visible的前提下  
固定列 render，是否有办法区分 render 在 ant-table-fixed-right 区域还是 ant-table-scroll？  
以便于render控制visible属性

**Comment by afc163** [comment]
trace #9262
