### ISSUE TITLE
Component Card STILL generates an extra div NOW.

### ISSUE THREAD

**Issue by cathayandy** [ant-design/ant-design#9226]
### Version
3.1.6

### Environment
MacOS 10.12.3, Google Chrome 63.0.3239.132, React 16.2.0

### Reproduction link
[https://ant.design/components/card-cn/](https://ant.design/components/card-cn/)

### Steps to reproduce
See #9186

### What is expected?
See #9186

### What is actually happening?
See #9186

---
It's not fixed in 2e45074#diff-ee912701477e4ad530280273efc65d32L200.

Look at line 181 to 185 of `components/card/index.tsx`. In line 183 there's a `div` wrapping `children`.

```
const body = (
  <div className={`${prefixCls}-body`} style={bodyStyle}>
    {loading ? loadingBlock : <div>{children}</div>}
  </div>
);
```

Thus, u are rendering sth like this:

```
<div className={`${prefixCls}-body`} style={bodyStyle}>
  <div>{children}</div>
</div>
```

But what I really want is:

```
<div className={`${prefixCls}-body`} style={bodyStyle}>
  {children}
</div>
```

And u can check the first example in the official doc in dev-tools. **THE FACT** is that there's an extra div wrapping the card's contents.

**Comment by rkeeler** [comment]
This is an issue for me as well. Makes it impossible (as far as i can figure out) to create flexible size cards with content inside them that expands to fill the whole card. Is there a reason the div was added in antd 3?
