### ISSUE TITLE
getFieldDecrator register strangely

### ISSUE THREAD

**Issue by wiyr** [ant-design/ant-design#9231]
### Version
3.1.6

### Environment
macOS 10.11.6, Chrome 63.0.3239.132

### Reproduction link
[https://codesandbox.io/s/o7l8nxyyxy](https://codesandbox.io/s/o7l8nxyyxy)

### Steps to reproduce
click add button more than one time

### What is expected?
the data get by `getFieldsValue` is always an array.

### What is actually happening?
the data got is a object after the second click

---
There is a workaroud can avoid the problem, but it seems inelegant:   `getFieldsDecorator` a new key such as `tempConditions` with a copy data.
Is it a bug of antd  or is it a usage error ?

**Comment by yesmeck** [comment]
> Warning: One field name cannot be part of another, e.g. `a` and `a.b`.

As warning said, `conditions` and `conditions[].value` can not exist at the same time.

**Comment by yesmeck** [comment]
> Are `conditions` and `conditions[]` the same field ?

Yes.  They can not exist at the same time.

**Comment by nodkrot** [comment]
Dynamic form item example from https://ant.design/components/form/

```jsx
    ...
    getFieldDecorator('keys', { initialValue: [] });
    const keys = getFieldValue('keys');
    const formItems = keys.map((k, index) => (
      <Form.Item
        {...(index === 0 ? formItemLayout : formItemLayoutWithOutLabel)}
        label={index === 0 ? 'Passengers' : ''}
        required={false}
        key={k}
      >
        {getFieldDecorator(`names[${k}]`, {
          validateTrigger: ['onChange', 'onBlur'],
          rules: [{
            required: true,
            whitespace: true,
            message: "Please input passenger's name or delete this field.",
          }],
        })(
          <Input placeholder="passenger name" style={{ width: '60%', marginRight: 8 }} />
        )}
        ...
      </Form.Item>
...
```

What doesn't make sense to me why do we need two different fields `getFieldDecorator('keys', { initialValue: [] });` => `keys` and `names`? When submitting the form the data is duplicated:

```js
{
    ...
    keys: [{},{}],
    names: [{},{}],
    ...
}
```

What am I missing here?

**Comment by umair-khanzada** [comment]
@nodkrot have you found the reason?
I am also confused regarding two different fields.

**Comment by nodkrot** [comment]
Unfortunately no, just using two keys and cleaning data after submit :/

**Comment by zry754331875** [comment]
@nodkrot Do you solve this problem?

**Comment by nodkrot** [comment]
I just have duplicate keys and then clean data when submitting. Moving forward I’m planning to use Formik, extremely powerful!

**Comment by teroko** [comment]
I also ran into this problem today when I tried to follow the example. It just didn't make any sense.
Im not sure why keys are even stored into form data... instead of just kept in component state.

```
const [array, setArray] = useState(initialArray);

function addItem() {
    setArray([...array, newItem]);
}

return (<div>
    {array.map((item, index) => {
       ...rest like in example
    })
</div>) 
```


This atleast seems to work for me and no need to clean form data afterwards...

**Comment by bishnu476** [comment]
This works perfectly for me though if the comparator is used the the same warning pop up only at start 
but if comparator is not used (which is used only to make id value to list size at initially ) no warning will be display. 

//Initial value of the keys in the list 
getFieldDecorator("keys", { initialValue: [0, 1, 2] });

//Initial values of the list
    const initialNames = ["A", "B", "C"];

//    const keys = getFieldValue("keys");
  
// Array Comporator
  const arrayEquals = (a, b) => {
      return (
        Array.isArray(a) &&
        Array.isArray(b) &&
        a.length === b.length &&
        a.every((val, index) => val === b[index])
      );
    };

// Comporator that will only true initially and set id value to arrays.length-1
    if (getFieldValue("keys").length === initialNames.length) {
      if (!arrayEquals(getFieldValue("names"), initialNames)) {
        id = getFieldValue("keys").length - 1;
        console.log("id", id);
      }
    }


    const formItems = keys.map((k, index) => (
      <Form.Item
        {...(index === 0 ? formItemLayout : formItemLayoutWithOutLabel)}
        label={index === 0 ? "Passengers" : ""}
        required={false}
        key={k}
      >
        {getFieldDecorator(`names[${k}]`, {
          initialValue: k + 1 <= initialKey.length ? `${initialNames[k]}` : " ",  //values initialized here from initialNames
          validateTrigger: ["onChange", "onBlur"],
          rules: [
            {
              required: true,
              whitespace: true,
              message: "Please input passenger's name or delete this field."
            }
          ]
        })(
          <Input
            placeholder="passenger name"
            style={{ width: "60%", marginRight: 8 }}
          />
        )}
        {keys.length > 1 ? (
          <Icon
            className="dynamic-delete-button"
            type="minus-circle-o"
            onClick={() => this.remove(k)}
          />
        ) : null}
      </Form.Item>
    ));
