### ISSUE TITLE
Image Cropper for profile Images

### ISSUE THREAD

**Issue by sanoop-jose** [ant-design/ant-design#9234]
### What problem does this feature solve?
In my web app,  there is a feature called Edit  Profile. Using this feature, users can add/change/delete their profile image. As per my understanding, currently, there is no component for this use-case. Image Cropper is an alternative solution which helps to crop the image before saving it. The problem with the current Ant's uploader component is it does not support image cropping. A new component equivalent to image uploader will solve this issue.

### What does the proposed API look like?
It will be great if we create an independent image uploader with crop feature. We can extend the uploader component for uploading the image. 
return the cropped image in base64 or any other format.

**Comment by afc163** [comment]
#921

**Comment by TuxujPes** [comment]
@afc163 does this mean that https://github.com/react-component/cropping is a dead repository and will never be used by Ant-design?
