### ISSUE TITLE
The disabledDate in WeekPicker is not set ash

### ISSUE THREAD

**Issue by gpzjyw** [ant-design/ant-design#9237]
### Version
3.1.6

### Environment
 Google Chrome 63.0.3239.132 (64bit)

### Reproduction link
[https://codesandbox.io/s/qv9mn1k009](https://codesandbox.io/s/qv9mn1k009)

### Steps to reproduce
Click the WeekPicker and the calendar is pop up. We can find the disabledDate is not set ash.

### What is expected?
The disabledDate in WeekPicker is set ash.

### What is actually happening?
The disabledDate in WeekPicker is not set ash.

**Comment by yesmeck** [comment]
Duplicate of #9008
