### ISSUE TITLE
Implement generic Input.Button component

### ISSUE THREAD

**Issue by ScriptWorker** [ant-design/ant-design#9245]
### What problem does this feature solve?
We have use case to toggle password characters visibility. Input.Search looks that we need, but it does not allow to set button's type.

I think it can be useful to have generic Input.Button component, which could also accept Button properties to set proper button type and custom class name if required. In such case Input.Search can be a wrapper around such component with predefined button type and icon.

### What does the proposed API look like?
```jsx
<Input.Button
      type="password"
      button={{
           className: "custom-button",
           content: "Show",
           type: "default",
           onClick: (event) => {
               console.log(event);
           }
     }}
    onButtonClick={(inputValue) => {
           console.log(inputValue);
    }}
/>
```

Where:
* `button` property can consume any Button API property
* onButtonClick will have typed into input field value as an argument
* Button's `content` property to set child element (text or some component)
* It is also possible to set onClick handler for button component. I think it is useless for this component, but at the same will not hide any Button API

What do you think about it?

**Comment by yesmeck** [comment]
You can combine Input with button by InputGroup:

```javascript
<InputGroup compact>
  <Input type="password" style={{ width: '200px' }} />
  <Button  type="primary">Show</Button>
</InputGroup>
```
