### ISSUE TITLE
TreeNode doesn't collapse when removed from "expandedKeys" props if one of the child TreeNodes of the expanded TreeNode is also expanded.

### ISSUE THREAD

**Issue by JureSotosek** [ant-design/ant-design#9252]
### Version
3.1.6

### Environment
Mac OSX, tested on latest versions of Chrome and Safari

### Reproduction link
[https://codesandbox.io/s/8lwlkrzl9](https://codesandbox.io/s/8lwlkrzl9)

### Steps to reproduce
Create a nested Tree with "expandedKeys" prop set to a "this.state.expandedKeys" and a "onExpanded" props that takes "expandedKeys" as an arguments and the sets the "this.state.expandedKeys" to that value.

### What is expected?
When you remove a "parent" TreeNode from "expandedKeys", with other TreeNodes nested inside of it expanded,  it should collapse.

### What is actually happening?
The "parent" TreeNode does not collapse even though it is remove from the "expandedKeys".

**Comment by zjdschnappi** [comment]
![image](https://user-images.githubusercontent.com/15072751/35851353-c613c59a-0b62-11e8-8af1-ffb7c4407d02.png)
同一个问题，，当被展开的父节点底下的子节点也展开时，移除state里expandedKeys里父节点的key，无法收起父节点

**Comment by zombieJ** [comment]
fixed in antd `3.4`. Pls check.
