### ISSUE TITLE
Add a way to programmatically expand all TreeNodes in a Tree without having to first figure out all the the keys that are possible to expand and adding them the the expandedKeys prop.

### ISSUE THREAD

**Issue by JureSotosek** [ant-design/ant-design#9253]
### What problem does this feature solve?
This way you are able to have a button that expands all TreeNodes without having to first compute all the expandable TreeNodes from your data.

### What does the proposed API look like?
    expandAllTreeNodes() {
        this.tree.expandAll()
    }

    render() {
        return(
            <Tree ref={(tree) => this.tree=tree}>
                <TreeNode title="sample" key="sample" />
            </Tree>
        )
    }

**Comment by yesmeck** [comment]
Imperative call is not recommended in React.
