### ISSUE TITLE
Table Drag and drop the sorting with fixed column ,If table cell content line feed then fixed column not aligned

### ISSUE THREAD

**Issue by tender001** [ant-design/ant-design#9255]
### Version
3.2.0

### Environment
Windows chrome 64

### Reproduction link
[https://codesandbox.io/s/l5nmpp12ol](https://codesandbox.io/s/l5nmpp12ol)

### Steps to reproduce
table use **react-dnd** drag and drop the sorting, set **fixed column** and one cell content line feed

### What is expected?
The table rows are aligned

### What is actually happening?
The table rows are not aligned

**Comment by yesmeck** [comment]
Should pass style down to table row, see my commit above.
