### ISSUE TITLE
Alert Banner not displaying at the top of the page

### ISSUE THREAD

**Issue by Marmiz** [ant-design/ant-design#9259]
### Version
3.2.0

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0, also tested Linux Ubuntu 17.10.

### Reproduction link
[https://codesandbox.io/s/y04xyqj9kv](https://codesandbox.io/s/y04xyqj9kv)

### Steps to reproduce
Create some markup (`p`, `h2` ...).
Create an `Alert` with the `prop banner` set to `true`.
Make sure that alert is below the markup previously created.

### What is expected?
Display Alert as a banner at top of page.

### What is actually happening?
The Alert is displayed in whatever position has been created to.

---
The same behaviour can be seen in the documentation page under the banner section by adding some markup above the Alerts inside the code sandbox.

**Comment by ddcat1115** [comment]
The `banner` type simply specify some detailed styles, such as `border` `border-radius`, not include `position`, so you have to position it by your own.

**Comment by Marmiz** [comment]
@ddcat1115 thanks for the fast reply.

That's what I imagined by looking at the source code, however in the documentation under the Alert example ( [this one](https://github.com/ant-design/ant-design/blob/master/components/alert/demo/banner.md) ) , it specifically says:

> Display Alert as a banner at top of page.

I personally believe that this is a misleading description since it clearly states "at top of page" (so I assumed some position was involving).

Could be worth a simple rephrase in the example page.

Sorry if this was more worth in the discussion page than as a issue.
