### ISSUE TITLE
Affix not worked

### ISSUE THREAD

**Issue by 422809585mls** [ant-design/ant-design#9260]
### Version
3.2.0

### Environment
chrom

### Reproduction link
[https://ant.design/components/anchor-cn/](https://ant.design/components/anchor-cn/)

### Steps to reproduce
<Col span={12}>
       <Anchor affix={true} bounds={20}>
                        <p className="p-title">选择人员</p>
                        <div className="personInfo">
                            {personInfo.map((p, index)=>{
                                    return <DragSource key={index} people={p}>{p.first_name}</DragSource>
                            })}
                        </div>
                     </Anchor>
</Col>

### What is expected?
affix 生效

### What is actually happening?
affix 未生效

**Comment by ddcat1115** [comment]
Didn't find anything wrong, could you provide a re-producible demo, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001
