### ISSUE TITLE
how to use blur method in InputNumber component

### ISSUE THREAD

**Issue by saostad** [ant-design/ant-design#9263]
I wanna use blue method to run a function if InputNumber lost focus, but I don't know how to use that method?

        <InputNumber
                value={value}
                onChange={this.handleChange}
                onKeyDown={this.onKeyHandler}
                size="small"
                min={0}
                step={0.5}
              />

**Comment by fritx** [comment]
Same here

**Comment by saostad** [comment]
You can user onBlur 
`onBlur={this._onBlur}`

**Comment by Forflower** [comment]
openApplicableVersion = () => {
    this.setState({ showSuitVersionModal: true });
    this.applicableRef.blur();
  };

  closeApplicableVersion = () => {
    this.setState({ showSuitVersionModal: false });
  };
...
 {getFieldDecorator('applicableVersion', {
              initialValue: '',
            })(
              <Input
                onFocus={this.openApplicableVersion}
                ref={input => {
                  this.applicableRef = input;
                }}
              />,
            )}

**Comment by fachreza73** [comment]
for function component:

1. create ref
```
const remoteInput = createRef<HTMLInputElement>()
```

2. apply ref to component
```
<InputNumberAnt
            ref={remoteInput}
            {...props}
            size={props.size || 'large'}
            precision={precision}
            decimalSeparator="."
            placeholder="0"
            formatter={value => String(value).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
            parser={value => String(value)?.replace(/\$\s?|(,*)/g, '')}
/>
```

3. use the blur or focus method
```
remoteInput.current?.focus()
remoteInput.current?.blur()
```
