### ISSUE TITLE
时间选择器 TimePicker 手机端 选择时间时，初次不能选择小于当前时间，需点击后才会出现滚动条，pc端正常

### ISSUE THREAD

**Issue by smileheart2** [ant-design/ant-design#9264]
### Version
3.2.0

### Environment
win10 企业版、谷歌 63.0.3239.132（正式版本） （32 位）、react-native  5.4.2

### Reproduction link
[https://ant.design/components/time-picker-cn/#header](https://ant.design/components/time-picker-cn/#header)

### Steps to reproduce
1.进入antd官网，选择最新版本3.2.0 ；
2.谷歌浏览器切换到手机样式；
3.选择 基本 ；
4.点击 时分秒 选择均无滚动条出现；
5. 选择时后 才出5点后现滚动条，分、秒 选择器 同理；

### What is expected?
手机端和pc端一样效果，点击选择框时就出现滚动条

### What is actually happening?
手机端 点击无滚动条，点击选择一个时间后才出现滚动条

**Comment by dengfuping** [comment]
@smileheart2 `Ant Design` isn't designed for mobile. If you have such demands, [ant-design-mobile](https://mobile.ant.design/index-cn) will be better choice.
