### ISSUE TITLE
当我使用getFieldDecorator.initialValue时报错

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#9268]
### What problem does this feature solve?
父组件传递给子组件的值，需要同步到input，使用以上属性报错，采用value形式是一个只读的
You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Input`.

### What does the proposed API look like?
我想要将数据进行同步怎么采取

**Comment by afc163** [comment]
仔细阅读 http://ant.design/components/form/ 。

**Comment by morris-he** [comment]
` Duplicate field names will result in both fields getting edited together. Field names must be unique`

做编辑功能，用表单组件双向绑定后设置默认值initialValue，初次更改数据会上方的错，再次更改就不报错了。
