### ISSUE TITLE
Table, I want to click table header column sort,but column not click method

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9271]
### What problem does this feature solve?
I want to click table header column sort,but column not click method.Now sort click area very small.

### What does the proposed API look like?
`Column` add `onClick` method

**Comment by yesmeck** [comment]
`column[onHeaderCell]`

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/171

**Comment by hengkx** [comment]
```
{
        title: '序号',
        dataIndex: 'id',
        width: '68px',
        fixed: 'left',
        onHeaderCell: (column) => {
          return {
            onClick: () => {
              console.log('onClick');
            }
          };
        }
      }
```

suggest add use doc

**Comment by azeemaleem149** [comment]
`const columns = [
	{
		title: 'Name',
		dataIndex: 'name',
		render:text=><Link to='/detail'>{text}</Link>
	}
}`

**Comment by AnuragGupta93** [comment]
> ```
> {
>         title: '序号',
>         dataIndex: 'id',
>         width: '68px',
>         fixed: 'left',
>         onHeaderCell: (column) => {
>           return {
>             onClick: () => {
>               console.log('onClick');
>             }
>           };
>         }
>       }
> ```
> 
> suggest add use doc

How to edit properties like width, title inside onClick?
