### ISSUE TITLE
The pageSize select of pagination always expands downward

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design#9272]
### Version
3.0.0

### Environment
Mac Os

### What is expected?
The `pageSize` select expands upward when page can not scroll down any more.

### What is actually happening?
The `pageSize` select of `pagination` always expands downward even though on the bottom of the page, resulting in the options being blocked.

**Comment by hudawen** [comment]
https://preview.pro.ant.design/#/list/table-list

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8497#issuecomment-351702425

**Comment by hudawen** [comment]
i think using `getPopupContainer` to set container to the `table` is better.
