### ISSUE TITLE
Changing certain applications of primary color

### ISSUE THREAD

**Issue by eminx** [ant-design/ant-design#9273]
### What problem does this feature solve?
I'm making an entirely new theme by only changing the less variables and redefine some classes style declarations. What I want to do mainly in relation to this request is to remove the @main-color from applying to a lot of the basic elements. For example on hover, focus etc; I'd like the main-color not to pop up. I want it to be in the background, only visible at certain parts of the application.

Main intention is not to dominate too much with the brand color, and rather emphasize it where relevant and subtly.

What is your suggested way to do it? I mean the @main-color has to be with a certain hue, which means that it can't be any grey. I just wonder if there's an easy way to change it, than going to each class and change the application to another grey...

### What does the proposed API look like?
@use-main-color-everywhere: false;

**Comment by yesmeck** [comment]
I don't fully understand you, does change`@primary-color`  work for you?

**Comment by eminx** [comment]
Yes, but I need to change every css/less class style declarations to affect. 

I'm just proposing that there be a global function to whether or not set the `@primary-color` to be used in all elements... It could be as it is already, by default. 

It'd be good for people who don't want to use @primary-color everywhere in their application. For example, when `<Input />` component is focused; the box-shadow of an input element is with a slight variation of the `@primary-color`. Not everyone wants to use it like that...

Does it help?

**Comment by tsaiDavid** [comment]
@eminx - if I'm not mistaken, couldn't you just override which of those derived colors you would prefer to not use?

**Comment by afc163** [comment]
I think https://ant.design/docs/react/customize-theme is enough for now.
