### ISSUE TITLE
在Form(vertical模式)中使用Radio和Input高度不同导致显示不正确

### ISSUE THREAD

**Issue by wxy450470614** [ant-design/ant-design#9274]
### Version
3.2.0

### Environment
Windows 10,Chrome 64.0.3282.140

### Reproduction link
[https://codepen.io/anon/pen/KQMEZz?editors=0110](https://codepen.io/anon/pen/KQMEZz?editors=0110)

### Steps to reproduce
1. 在Form(vertical)中使用栅格，一行两列
1. 第一行第一列使用Input组件，第二列使用Radio组件，接下来都使用Input

### What is expected?
一行两列，每一行都有两个组件

### What is actually happening?
包含Radio的FormItem的高度小于包含Input的FormItem高度，Radio接下来一行显示出问题，第一列没有FormItem

---
在升级antd到2.13.11时发现问题，在CodePen上测试从2.13.11开始有这个问题，3.0.0以后到3.2.0也有，而且我在上面重现例子上试了一下，在vertical模式下有问题，默认的horizontal模式下没有问题。

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/GQjjRK?editors=0110

去掉 `layout="vertical"` 即可，没有必要给 vertical 添加 Grid 布局使其长得像 horizontal，vertical 就是 label 和控件都占据一行的布局方式。

**Comment by wxy450470614** [comment]
实际上我没有加layout="vertical"，只是在Modal里用Form宽度不够变成了vertical的样子。上面你那个例子3改变宽度好像没什么问题，但是2.13.11里还是有问题，2.13.10还是好好的。
2.13.11:https://codepen.io/codepenwxy/pen/QQKBoy?editors=0110
