### ISSUE TITLE
Sketch Assets in English

### ISSUE THREAD

**Issue by tsaiDavid** [ant-design/ant-design#9280]
### What problem does this feature solve?
Allows for better user experience for international or English dominant users as they are creating mockups using the Ant Design library.

### What does the proposed API look like?
Ideally, it would be great to see the names of the Sketch Symbols be converted to English for wider usage.

**Comment by brianswisher** [comment]
+1 This would be a tremendous benefit!

**Comment by pmorrow** [comment]
Very interested in getting this done. I'm currently working on translating the Sketch symbol names in the Ant.Design.Template.sketch file.

**Comment by afc163** [comment]
@momozzzxy

**Comment by tsaiDavid** [comment]
Let us know how we can help, our company is evaluating using and contributing back!

**Comment by afc163** [comment]
`Ant.Design.Template.sketch` is the sketch template for antd 2.x. We are now have a English-symbol-names template (`Ant.Design.3.0.Components.sketch`) which you can get in https://ant.design/docs/spec/download

The mobile version is still not translated yet and anyone who could help is welcome~

**Comment by tsaiDavid** [comment]
@pmorrow - I sent you the link directly to the template mentioned by @afc163.

@afc163 - Is there a way that `ant-design` as a whole can utilize some sort of version control for the Sketch assets? It'd make collaboration easier.

**Comment by kbaekgit** [comment]
@afc163 Ooh thanks for making this happen! Must easier now that symbol names are in English. I see the placeholder contents are still in Chinese (e.g. 'Select' in form field) but would those be updated as well?

**Comment by afc163** [comment]
@kbaekgit We probably won't do this, you could help us and upload to this issue. We will create a resource card which named as `Ant.Design.Template(English).sketch`.

**Comment by saulmases** [comment]
Hi everyone. I would like to know if anybody is working (or have already finished working) on the translation of all the placeholder contents in english in the sketch file?

We are evaluating using Ant for our BackOffice and if we finally go with it I will do the translation, so it will be nice to know if someone already did it (just to not waste time on re-doing it).

Thanks!

**Comment by saulmases** [comment]
@pmorrow Thank you very much! It's a good starting point for me. 👍

**Comment by equinusocio** [comment]
Any update? We need an official and maintained version of sketch components

**Comment by saulmases** [comment]
@ant-design-bot & Hi everyone!

So I worked a bit on it on my free spots and I finally have a fully translated version of Ant Design, plus some improvements in terms of Symbols for tables and other elements (thanks to Paddy Sketch Plugin) **If anyone wants to have a look at it let me know** (only downside is that I changed all fonts to be Work Sans, the font we are using at my company, but you can change it to the font you like easily)

Any update on the plan of using version control for design assets?

**Comment by equinusocio** [comment]
@saulmases can you share it?

**Comment by saulmases** [comment]
@equinusocio Sure, I prepared it as a Sketch Library 😄 

@tsaiDavid @pmorrow 
I'm trying to configure it to work with Kactus Version Control system (https://kactus.io/) in order to have one unique source of truth, but I'm struggling a bit... so if anyone can help with this it would be great 👍 

[Ant.Design.3.0.Template.Versioned.English.zip](https://github.com/ant-design/ant-design/files/2313822/Ant.Design.3.0.Template.Versioned.English.zip)

**Comment by deklerkmc** [comment]
Hi everyone,

I’m looking to create a Sketch library of the ant.d UI components that have had custom styling. 

The extent of customisation is just overriding some of the `less` variables in https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less 
Does anybody know how the Sketch library was created, or hopefully generated?

**Comment by tabakd** [comment]
Hey there!  Nice work @saulmases. Do you know which steps we would need to take to sync this with the latest antd?

> @equinusocio @tsaiDavid @pmorrow @ant-design-bot @afc163 @brianswisher @MrMonad
> 
> I'm trying to configure the fully translated sketch file I prepared to work with Kactus Version Control system (https://kactus.io/) in order to have one unique source of truth.
> 
> [EDITED]
> I already configured Kactus properly and I have a repository up and running with Ant Design Sketch Assets in English 👍 https://github.com/saulmases/ant-design-sketch
> 
> Any opinion/suggestion from the Ant Design team on how to continue with this? 😄

**Comment by wernerbarnard** [comment]
@saulmases @tabakd How do you get up and running with the english version of the Sketch assets?

See: https://github.com/saulmases/ant-design-sketch/issues/1

**Comment by rublev** [comment]
Any updates on this? I've scoured the web and the ant.design site for sketch resources and they are all still in Chinese.

**Comment by ostiwe** [comment]
+1

I would like to receive an official sketch file with all components, which is available in English.

It's a shame that the English speakers have been forgotten in this regard.

**Comment by ccurtisj** [comment]
+1

**Comment by jAtlasCode** [comment]
Would love an English sketch file, not the best to present non-English mockups/ sketch designs to stakeholders
