### ISSUE TITLE
Click fires twice when clicking on Checkbox container

### ISSUE THREAD

**Issue by terence55** [ant-design/ant-design#9281]
### Version
3.2.0

### Environment
OSX El Capitan, Chrome 64

### Reproduction link
[https://codesandbox.io/s/88yw46lxo8](https://codesandbox.io/s/88yw46lxo8)

### Steps to reproduce
Create a Checkbox and put it in another container(e.g. div, MenuItem). Now click the label of the Checkbox. 

```js
<div onClick={() => console.warn('click checkbox')}>
    <Checkbox>Content</Checkbox>
</div>
```

It was caused by the `label` wrapper of Checkbox.

```js
<label
    className={classString}
    style={style}
    onMouseEnter={onMouseEnter}
    onMouseLeave={onMouseLeave}
    >
    <RcCheckbox
        {...checkboxProps}
        prefixCls={prefixCls}
        className={checkboxClass}
        ref={this.saveCheckbox}
      />
    {children !== undefined ? <span>{children}</span> : null}
</label>
```

### What is expected?
Click fires once

### What is actually happening?
Click fires twice

**Comment by yesmeck** [comment]
It's a browser behavior,  a click on the label will also trigger a click on the associated element.

**Comment by terence55** [comment]
What about change the wrapper of Checkbox from `label` to `span`

**Comment by terence55** [comment]
What about changing the wrapper of Checkbox from `label` to `span`?

**Comment by yesmeck** [comment]
No, `label` is designed to be associated with `input`.
