### ISSUE TITLE
Table, I hope to can drag table column sort

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9282]
### What problem does this feature solve?
I hope to can drag table column sort，
```js
// before
[{
  title: 'Name',
  dataIndex: 'name',
},  {
  title: 'Email',
  dataIndex: 'email',
}];
// after
[  {
  title: 'Email',
  dataIndex: 'email',
},
{
  title: 'Name',
  dataIndex: 'name',
},];
```

### What does the proposed API look like?
not

**Comment by yesmeck** [comment]
You can archive this feature by creating the custom elements, see [this](https://ant.design/components/table-cn/#components-table-demo-drag-sorting) and [this](http://react-component.github.io/table/examples/column-resize.html) example.

**Comment by karan101292** [comment]
> You can archive this feature by creating the custom elements, see [this](https://ant.design/components/table-cn/#components-table-demo-drag-sorting) and [this](http://react-component.github.io/table/examples/column-resize.html) example.

This example shows row sorting. question is about column sorting.

**Comment by codercodingthecode** [comment]
https://codepen.io/raisezhang/pen/MoMoyz

check the above link.
it addresses the column sorting with drag and drop on the header

**Comment by Zeeshan666** [comment]
Hey . this issue still open  or solve?
