### ISSUE TITLE
Tree 组件在设置defaultExpandAll 的时候没有生效

### ISSUE THREAD

**Issue by runfan** [ant-design/ant-design#9284]
### Version
3.2.0

### Environment
mac os 10.13.3 (17D47)，google chrome 64.0.3282.140

### Reproduction link
[https://codesandbox.io/s/rl7q48k6q](https://codesandbox.io/s/rl7q48k6q)

### Steps to reproduce
- 直接初始 data为[]
- 延时加载 data的内容的时候 defaultExpandAll 就失效了

### What is expected?
正常的显示全部展开的树

### What is actually happening?
全部都没有展开

**Comment by yesmeck** [comment]
`defaultExpandAll` 只在第一次渲染时有效。

**Comment by runfan** [comment]
这个设置三动态加载数据的时候变得没用了
因为数据都动态加载的，首次渲染的时候肯定是没数据的，延迟加载的数据又都没有展开
