### ISSUE TITLE
Row height not sync when use fixed column with tree table

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#9287]
### Version
3.2.0

### Environment
Chrome

### Reproduction link
[https://codesandbox.io/s/k9zv8l23j3](https://codesandbox.io/s/k9zv8l23j3)

### Steps to reproduce
Expand first table row

### What is expected?
The fixed column has same row height with other rows.

### What is actually happening?
The fixed column has smaller row height than other rows.

**Comment by ahennie** [comment]
@yesmeck  the reproduction link doesn't work?

**Comment by yesmeck** [comment]
@ahennie I've updated the sandbox since codesandbox.io limit the free plan to 50 sandboxes.
