### ISSUE TITLE
Switch - typo in stylesheet

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#9290]
### Version
3.2.0

### Environment
Firefox 58

### Reproduction link
[https://github.com/ant-design/ant-design/blob/b9b5abab3364bf752e9644415088b142a153e385/components/switch/style/index.less#L59](https://github.com/ant-design/ant-design/blob/b9b5abab3364bf752e9644415088b142a153e385/components/switch/style/index.less#L59)

### Steps to reproduce
Check the stylesheet.

### What is expected?
No CSS errors.

### What is actually happening?
CSS `background: transprent` is not a `background-color` value.

**Comment by afc163** [comment]
@froston Nice catch! Could you help us to fix it by sending a PR?
