### ISSUE TITLE
Tooltip around disabled Button leads to split inside of ButtonGroup

### ISSUE THREAD

**Issue by saerdnaer** [ant-design/ant-design#9296]
### Version
3.2.0

### Environment
Mac OS 10.12.6, Safari 10.1.2

### Reproduction link
[https://codepen.io/anon/pen/MQbybP?editors=0010](https://codepen.io/anon/pen/MQbybP?editors=0010)

<img width="489" alt="temp" src="https://user-images.githubusercontent.com/40266/35920833-4dd59ace-0c19-11e8-8af7-507bba916fc7.png">

### Steps to reproduce
Create a ButtonGroup with three buttons, add Tooltip around first one. Disable first button.

```jsx
    <ButtonGroup>
      <Tooltip title="This text explains what this button does">
        <Button disabled size="small">
          <Icon type="arrow-up" />
        </Button>
      </Tooltip>

      <Button size="small">
        <Icon type="copy" />
      </Button>

      <Button size="small" type="primary">
          <Icon type="edit" />
      </Button>
    </ButtonGroup>
```

### What is expected?
ButtonGroup is visually not split.

### What is actually happening?
ButtonGroup gets visually split and button gets rounded on the right.

**Comment by dengfuping** [comment]
@saerdnaer Your tooltip is so long and there is no enough space on the left. It's designed for avoid that tooltip is out of the browser window. Just make tooltip shorter or leave enough space for tooltip.

**Comment by saerdnaer** [comment]
To problem I tried to highlight is not the text inside the tooltip but the extra pixels between the buttons:
<img width="250" alt="temp" src="https://user-images.githubusercontent.com/40266/35969882-97e5283c-0cc8-11e8-8725-677c23a8859c.png">

**Comment by afc163** [comment]
@saerdnaer I just fixed this problem in 70f3afe

**Comment by saerdnaer** [comment]
Ah, looks like I got confused by the other comment, too – sorry for the noice.

**Comment by tangjinzhou** [comment]
Still have similar problems.
https://codesandbox.io/s/61lqr2m4mr
![image](https://user-images.githubusercontent.com/6937879/42855969-a647452e-8a75-11e8-8dec-8b9b2df6d26c.png)
