### ISSUE TITLE
Select considering value instead of key

### ISSUE THREAD

**Issue by ferreirix** [ant-design/ant-design#9297]
### Version
3.2.0

### Environment
win10, chrome 64

### Reproduction link
[https://codesandbox.io/s/k2qmqnxrzv](https://codesandbox.io/s/k2qmqnxrzv)

### Steps to reproduce
Select with many options where the key is a uuid and value is a number but with repeated values.

### What is expected?
No errors

### What is actually happening?
Error in console :
Warning: Encountered two children with the same key, `.$1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in ul (created by DOMWrap)
    in DOMWrap (created by Menu)
    in Menu (created by DropdownMenu)
    in div (created by DropdownMenu)
    in DropdownMenu (created by SelectTrigger)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup (created by Trigger)
    in Portal (created by Trigger)
    in Trigger (created by SelectTrigger)
    in SelectTrigger (created by Select)
    in Select (created by LocaleReceiver)
    in LocaleReceiver (created by Select)
    in Select (created by TestSelect)
    in div (created by TestSelect)
    in TestSelect
    in div

---
If the key is always different, the value in the option should not interfer with the react key (because it is not even mandatory, only the key is).
Sorry if i'm missing something and thank you!

**Comment by yutingzhao1991** [comment]
Reproduction link: https://codesandbox.io/s/x31xzqvkx4

**Comment by yutingzhao1991** [comment]
@afc163 @yesmeck What your opinion about this, Should Select support Option which has a same value?

**Comment by yesmeck** [comment]
You can omit the value if you have passed key to Option.

**Comment by yesmeck** [comment]
It's not a bug.

**Comment by yesmeck** [comment]
And value should be unique.

**Comment by yutingzhao1991** [comment]
Hmm... @ferreirix Maybe you can set value just like `valuea-1` `valuea-b` and handle it in your code.

**Comment by yesmeck** [comment]
Generating key on every render is also not a good practice, key should be unique and stable.

**Comment by ferreirix** [comment]
@yutingzhao1991 @yesmeck  Thanks for taking a look. Actually i don't see in the specification that value has to be unique https://www.w3.org/TR/html5/sec-forms.html#the-option-element . Maybe i'm missing something but it is weird that the value overrides the key no?

Thank you!

**Comment by yesmeck** [comment]
Refer to https://github.com/ant-design/ant-design/issues/5242 see why value should be unique.

**Comment by ferreirix** [comment]
ok i see. Thank you :)

**Comment by mikexfreeze** [comment]
@yesmeck 不是一两个人提这种需求了，其他框架中的select 也没有像这么玩的。你们团队应该好好讨论一下

**Comment by abelsoares** [comment]
I don't think that Select component should mandate that `value` should be unique because there are use cases where it makes perfect sense to have repeated values. Not doing so will lead to hacky code to handle initial/default values.

**Comment by saraspaudel** [comment]
Duplicate values should be allowed, given unique keys.

**Comment by Jianyi-Ren** [comment]
Use Case：

我希望提供不同的options，其中一部分指向default value / null, 例如

```
Choice A (NO Available Result Yet)
Choice B (Result B)
Choice C (No Available Result Yet)
Choice D (Result D)

```
虽然A和C指向的value一样是NULL，但是为了展示状态，我不能把A和C压缩

请考虑一下添加这个feature，谢谢。
