### ISSUE TITLE
Input的TextArea组件没有提供清空文本框内容的api。

### ISSUE THREAD

**Issue by SAMUELGG** [ant-design/ant-design#9301]
### Version
3.2.0

### Environment
浏览器版本

### Reproduction link
[http://ooooo](http://ooooo)

### Steps to reproduce
在弹窗modal组件中引入textArea组件

### What is expected?
关闭弹窗modal的时候，清空TextArea组件里的文本内容

### What is actually happening?
TextArea组件里的文本内容没法清空

**Comment by afc163** [comment]
Try `destroyOnClose`

https://ant.design/components/modal/
