### ISSUE TITLE
Pagination in List grid is not working

### ISSUE THREAD

**Issue by jaspersorrio** [ant-design/ant-design#9303]
### Version
3.2.0

### Environment
Mac, Chrome

### Reproduction link
[https://codepen.io/anon/pen/QQGJmX?&editors=001](https://codepen.io/anon/pen/QQGJmX?&editors=001)

### Steps to reproduce
Look at codepen

### What is expected?
Instead of rendering the whole list, it should only render the current page

### What is actually happening?
The list renders everything from the data source

**Comment by andriijas** [comment]
It looks like there is no `slice` on dataSource  in https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L175

**Comment by andriijas** [comment]
It should reuse handleShowSizeChange  and handlePageChange   from `Table`

**Comment by nikogu** [comment]
@andriijas List pagination is entire UI, there has no interaction, you can control data by your self

**Comment by lgordey** [comment]
That's truth.
Pagination still doesn't work in List component.
Like here: https://preview.pro.ant.design/#/list/search/projects
Or in @andriijas demo.

**Comment by andriijas** [comment]
I think code can be redactored to pagination utilities and reused in list and table and even userland components

**Comment by nikogu** [comment]
i will mix Pagination default behavior to List later.
