### ISSUE TITLE
Tree throws error when `{null}` appear in multiple children

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#9304]
### Version
3.2.0

### Environment
windows 10(x64), chrome 64

### Reproduction link
[https://codesandbox.io/embed/kmvxwrv49o](https://codesandbox.io/embed/kmvxwrv49o)

### Steps to reproduce
```jsx
<Tree>
  {null}
  {null}
<Tree>
```
or
```jsx
<Tree>
  {null}
  <TreeNode {...props} />
<Tree>
```

### What is expected?
Tree can ignore these {null} children

### What is actually happening?
It throws `Uncaught TypeError: Cannot read property 'key' of null`

---
```jsx
<Tree>
    {hasTreeNode1 && <TreeNode key="1" title="node1"></TreeNode>}
    {hasTreeNode2 && <TreeNode key="2" title="node2"></TreeNode>}
</Tree>
```

Or should I do it in another way?

**Comment by zombieJ** [comment]
Done. https://github.com/react-component/tree/pull/149
