### ISSUE TITLE
form setFieldsValue not work with DatePicker

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#9305]
### Version
3.1.2

### Environment
node 6.1.0

### Reproduction link
[https://codesandbox.io/s/r44rp0n8kp](https://codesandbox.io/s/r44rp0n8kp)

### Steps to reproduce
https://codesandbox.io/s/r44rp0n8kp

### What is expected?
the setFieldsValue work.

### What is actually happening?
the `DatePicker` display the `date` was current `date`

---
now, it work's before submit to change the value.
but i don't known why not work. or that was a bug?

**Comment by yesmeck** [comment]
Use `normalize` if you want alert value after it changes.

```javascript
<FormItem>
  {getFieldDecorator("start_date", {
    rules: [
      {
        required: true,
        message: "请选择行起始时间"
      }
    ],
    initialValue: null,
    normalize: (value) => {
      return value
        .endOf("month")            }
  })(
    <MonthPicker
      placeholder="请选择起始日期"
      format={dateFormat}
    />
  )}
</FormItem>
```

**Comment by benjycui** [comment]
Use `getValueFromEvent` instead of `normalize`, for `normalize` is slow.

**Comment by didmehh** [comment]
thks.
I'm sorry to bother you.
