### ISSUE TITLE
FormItem 支持 extra

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#931]
https://github.com/ant-design/ant-design/commit/60a77bdccf5bab8d66486543ea62b37791e94443

<img width="548" alt="2016-01-26 4 02 55" src="https://cloud.githubusercontent.com/assets/200876/12575285/4f0baa7c-c446-11e5-9ea5-b5a2c18a4418.png">

**Comment by afc163** [comment]
`help="xxx"` 不能解决么？

http://ant.design/components/form/#demo-mix

**Comment by yiminghe** [comment]
help 会被当做错误信息变红，有些描述性的信息

**Comment by benjycui** [comment]
现在的逻辑是：提示信息和错误信息都用 help，只是 validateStatus 不一样。

所以当两者都需要时，就有点麻烦了。。

**Comment by benjycui** [comment]
其实我觉得校验提示信息用 `validateMsg`，普通提示信息用 `help` 会比较符合语义，但是这样改就是不兼容了。

不过只是重命名一个属性，应该还可以接受？

**Comment by afc163** [comment]
建议不要改，help 也涵盖了 `validateMsg`，而且现在使用中也可以显示 `正在校验中` 这样的信息。

**Comment by afc163** [comment]
类似 http://aliceui.org/docs/widget.html#modules-form 的实现，也是把提示信息和错误信息用同一个区块来展示，出现错误信息则隐藏提示信息。

**Comment by benjycui** [comment]
因为 `help` 现在有个自动生成的默认值，然后如果用户自行设置了 `help`，则使用用户提供的值。

如果错误信息和提示信息都用 `help` 设置的话，对 `Form.Item` 来说是无法区分的。

**Comment by kasinooya** [comment]
所以结论呢？

```
<FormItem
            label="领取的leads保护期时长："
            validateStatus={
              classnames({
                error: !!getFieldError('keepLeadsProtectDay'),
              })}
            required
            help={(getFieldError('keepLeadsProtectDay') && '请输入领取的leads保护期时长') || '上限20个'}
            labelCol={{span: 6}}
            wrapperCol={{span: 5}}>
            <InputNumber size="large" min={1} max={20} {...getFieldProps('keepLeadsProtectDay', {
              initialValue: merchant.keepLeadsProtectDay,
              rules: [{
                required: true,
                type: 'number',
                min: 1,
                max: 20,
              }],
            })} style={inputStyle} /> 天
          </FormItem>
```

同样关注
