### ISSUE TITLE
Form validations in modal not working when dynamically generated

### ISSUE THREAD

**Issue by johnernaut** [ant-design/ant-design#9311]
### Version
3.2.0

### Environment
Latest Chrome / React 16 / React DOM latest

### Reproduction link
[https://codepen.io/anon/pen/wygGLm](https://codepen.io/anon/pen/wygGLm)

### Steps to reproduce
Click a calendar event which triggers a modal to open via calling the calendars `onSelect` event.  Click 'ok' in the modal and see that the required field does not show a validation message.  You also can not change the value of the required field.

### What is expected?
You can change the value of the required field, and it should show an error message when validation fails.

### What is actually happening?
You cannot change the field value, and no validation error is shown for the required field.

**Comment by yesmeck** [comment]
You should not treat the model content as a state, once the content is stored in state, I won't be updated on render.
