### ISSUE TITLE
依赖丢失

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#9318]
### Version
3.2.0

### Environment
yarn v1.3.2, parcel v1.5.1, antd v3.2.0

### Reproduction link
[https://github.com/xyy94813/parcel-demo/tree/bugReport](https://github.com/xyy94813/parcel-demo/tree/bugReport)

### Steps to reproduce
* 基于 parcel 官方文档搭建完 React 项目
* yarn add antd
* yarn warning "antd > rc-editor-mention@1.1.5" has unmet peer dependency "immutable@^3.7.4".
* 添加以下代码  import { Layout } from 'antd'
* parcel 报错 antd Cannot resolve dependency 'rc-editor-mention' （in es dir.）

### What is expected?
不会出现依赖错误

### What is actually happening?
antd Cannot resolve dependency 'rc-editor-mention'

**Comment by dengfuping** [comment]
@xyy94813 Nothing wrong  could be found in your demo according to your re-producible steps.

**Comment by afc163** [comment]
@RaoHai

**Comment by yesmeck** [comment]
> "antd > rc-editor-mention@1.1.5" has unmet peer dependency "immutable@^3.7.4".

这个可以忽略。

重新安装下依赖。
