### ISSUE TITLE
support dark theme

### ISSUE THREAD

**Issue by orangeyyy** [ant-design/ant-design#9321]
### What problem does this feature solve?
现在ant-desgin主要用于light theme的场景，如果要在dark theme场景下使用，需要手动调主题参数，比较麻烦，能否提供一个官方的dark theme 配置，并提供开关来使用dark theme？包括组件颜色，文案颜色等等。

### What does the proposed API look like?
提供一个 setTheme的方法可以设置。

**Comment by afc163** [comment]
暂时不提供，建议自行尝试配置一套主题变量并维护。
