### ISSUE TITLE
antd官网3.2版本Tabs组件出bug

### ISSUE THREAD

**Issue by willem20170918** [ant-design/ant-design#9324]
### Version
3.2.0

### Environment
Chrome    antd@3.2.0

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
Tabs组件竖直显示时，点击上下箭头无效然后箭头消失

### What is expected?
这组件和2x版本效果一样，期望立即修正

### What is actually happening?
Tabs组件竖直显示无法使用，连官网都出bug了

**Comment by afc163** [comment]
Broken by https://github.com/react-component/tabs/pull/85

**Comment by afc163** [comment]
Fixed, try reinstall node_modules.
