### ISSUE TITLE
Input tag loses the focus in IE while typing

### ISSUE THREAD

**Issue by Meloman4eg** [ant-design/ant-design#9329]
### Version
2.13.11

### Environment
Windows 10(x64), IE 11.

### Reproduction link
[https://ant.design/components/tree-select/ (Basic - example)](https://ant.design/components/tree-select/ (Basic - example))

### Steps to reproduce
Look at link

### What is expected?
Should be able to type the whole word in input field.

### What is actually happening?
It is possible to type only one symbol per time with loss the focus in input field.

**Comment by dengfuping** [comment]
@Meloman4eg Ant Design supports IE9+, but you should provide es5-shim and es6-shim and other polyfills for IE browsers. For more detail, please refer to the [compatibility document](https://ant.design/docs/react/getting-started#Compatibility).

**Comment by yesmeck** [comment]
Reinstall node_modules.

**Comment by Andreeh** [comment]
Any fix for this yet? I use @babel/polyfill and experience the same issue with an input field inside a popover in IE11. Somehow onBlur is called for each character

**Comment by hzaben81** [comment]
@Andreeh yes I see the same issue

@yesmeck can you repoen this issue?

**Comment by yesmeck** [comment]
@hzaben81 Please file a new issue with a reproduction.

**Comment by gorilla-devs** [comment]
I have this issue too

**Comment by maryainneranoa** [comment]
hello, I experienced this too. any luck?
