### ISSUE TITLE
Allowing specific range in DatePicker

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#9330]
### What problem does this feature solve?
I want to allow the users to pick a date, but within the allowed range. Currently can't be done as the `disabledDate` function has current date as a passed value. That means, that if the DatePicker is empty, there is no date to compare - or am I missing something?

If I am - would it be possible to give me some hint how to do it using the `disalbedDate` function?

### What does the proposed API look like?
Maybe `range` attribute with `min` and `max` values passed as Moment objects?

**Comment by yesmeck** [comment]
https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date

**Comment by Jab0rnal** [comment]
It seems a lot of people point to the documentation which doesn't describe exactly how to do it. You can use the disabledDate function to achieve what OP is wanting.

Ive put a stackblitz up to show an example.
https://stackblitz.com/edit/react-fcce79?file=index.js
