### ISSUE TITLE
Typescript type error when using Form.create({mapPropsToFields}).

### ISSUE THREAD

**Issue by kevinsperrine** [ant-design/ant-design#9331]
### Version
3.2.0

### Environment
Mac OSX Sierra (10.12.6), Firefox 58.0.2, react 16.2.0, antd 3.2.0

### Reproduction link
[https://github.com/kevinsperrine/ant-design-form-test](https://github.com/kevinsperrine/ant-design-form-test)

### Steps to reproduce
Clone the repo and run `yarn start`. Minimal repo created using:

```
create-react-app form-test --scripts-version=react-scripts-ts
yarn add antd
```

### What is expected?
No type errors should occur

### What is actually happening?
A Typescript type error that the 'form' prop is missing is thrown.
```
/Users/chuck/Projects/form-test/src/App.tsx
(66,28): Type '{ username: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<CustomFormProps, "username"> & Cust...'.
  Type '{ username: string; }' is not assignable to type 'Readonly<Pick<CustomFormProps, "username"> & CustomFormProps>'.
    Property 'form' is missing in type '{ username: string; }'.
```

**Comment by kevinsperrine** [comment]
Just some extra debugging info, If I make an interface for just my props without extending `FormComponentProps` it works as expected, so I'm assuming it has something to do with the `FormCreateOption` type not properly omiting the `form` prop? 

```
// custom interface for component.
interface OwnProps {
  username: string;
}

// custom type intersected with FormComponentProps
type CustomFormProps = OwnProps & FormComponentProps;

const mapPropsToFields = (props: OwnProps) => {
  const { username } = props;

  return {
    username: Form.createFormField({ value: username })
  };
};

const FormOptions: FormCreateOption<OwnProps> = { mapPropsToFields };

// No longer throws a type error and compiles successfully.
const WrappedCustomForm = Form.create(FormOptions)(CustomForm);
```

**Comment by caoyuanqi** [comment]
Yes, Got this problem as well in create-react-app-typescript

**Comment by Nokecy** [comment]
当 CustomForm 继承React.Component<any, {}> 时 问题依旧 ， 如 [https://github.com/Nokecy/ant-design-form-test](url)

@yesmeck @benjycui

**Comment by JunyuanZheng** [comment]
Got the same problem after upgrading ANTD from 3.2.0 to 3.2.3

**Comment by yesmeck** [comment]
@Nokecy your repo is using antd@3.2.0, remove yarn.lock and reinstall node_modules.

**Comment by yesmeck** [comment]
@JunyuanZheng Plz provide a reproduction repo.

**Comment by Nokecy** [comment]
@yesmeck  升级到3.2.3 问题依旧 [https://github.com/Nokecy/ant-design-form-test/tree/master](https://github.com/Nokecy/ant-design-form-test/tree/master)

**Comment by yesmeck** [comment]
@Nokecy 嗯, 不要用 any。

**Comment by qzm** [comment]
Use 'FormComponentProps' and 'export default Form.create()(App);'
It work's for me

```typescript

import { Form } from 'antd';
import { FormComponentProps } from 'antd/lib/form';
import { connect } from 'dva';
import * as React from 'react';

export interface IAppProps extends FormComponentProps {
  visible?: boolean;
}

@connect(({ dispatch }) => ({
  dispatch,
}))
class App extends React.PureComponent<IAppProps, any> {
  public render() {
    return <div />
  }
}
export default Form.create()(App);

```
