### ISSUE TITLE
<Timeline> + <Spin> + <TransitionGroup>: Warning: Received `true` for a non-boolean attribute `last`

### ISSUE THREAD

**Issue by antonmedv** [ant-design/ant-design#9333]
### Version
3.2.0

### Environment
chrome, react 16

### Reproduction link
[https://codepen.io/anon/pen/qxrwqj?editors=001](https://codepen.io/anon/pen/qxrwqj?editors=001)

### Steps to reproduce
<Timeline>   <Spin>

### What is expected?
No warning

### What is actually happening?
Got warning:

> Warning: Received `true` for a non-boolean attribute `last`

**Comment by afc163** [comment]
```
<Spin>
  <Timeline>
    <Timeline.Item />
    <Timeline.Item />
  </Timeline>
</Spin>
```
