### ISSUE TITLE
RangePicker 选择年的范围出现异常bug

### ISSUE THREAD

**Issue by chenghaohao** [ant-design/ant-design#9334]
### Version
3.2.0

### Environment
react 15.6.1   chrome 63.0.3239

### Reproduction link
[https://codepen.io/yezihaohao/pen/wydGOg](https://codepen.io/yezihaohao/pen/wydGOg)

### Steps to reproduce
1. 选择RangePicker的年2020-2029
2.显示的上一次选择的年2010-2019.

### What is expected?
正常显示选择的年的范围

### What is actually happening?
每次选择，显示的是上一次的年范围

---
麻烦请大神们看看，急需处理。或者告知哪个版本没有问题，我回滚到没问题的版本也行

**Comment by chenghaohao** [comment]
@benjycui @yesmeck  麻烦请大神看看，谢谢

**Comment by chenghaohao** [comment]
![test](https://user-images.githubusercontent.com/9986914/36071648-ab7d7436-0f4c-11e8-8279-1560dddb41ad.gif)

**Comment by yesmeck** [comment]
Your link is not working.

**Comment by chenghaohao** [comment]
OK...here's another link [https://codepen.io/yezihaohao/pen/xYdOGN](https://codepen.io/yezihaohao/pen/xYdOGN)

**Comment by chenghaohao** [comment]
@yesmeck  i tried react 16.2.0.  it worked well. but react 15.6.1 has the problem

**Comment by ycshill** [comment]
I have the same problem, 一开始选择器面板默认是 【2018年4月26】，然后我选择了【2017年4月23日】，然后用  ``this.props.form.resetFields();`` 清空条件，再打开面板的时候，默认还是在【2017】年

**Comment by afc163** [comment]
Try upgrade react version to 16.x
