### ISSUE TITLE
Link for ant-design next is outdated

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#9336]
### Version
3.2.0

### Environment
all

### Reproduction link
[https://ant.design/docs/react/introduce#Version](https://ant.design/docs/react/introduce#Version)

### Steps to reproduce
visit https://ant.design/docs/react/introduce#Version
see version for next

### What is expected?
No version for next since there's no next branch or 4.X branch.

### What is actually happening?
we see a badge with next version 3.0.0rc4

**Comment by yesmeck** [comment]
Thanks, I've removed the next link.
