### ISSUE TITLE
In confirm modal onOk should get param for promising

### ISSUE THREAD

**Issue by Muzammil-Bilwani** [ant-design/ant-design#9342]
### What problem does this feature solve?
For editing and performing operation on modal params 

### What does the proposed API look like?
onOk(index){
 console.log(index) ; // index or any param that was passed
}

**Comment by dengfuping** [comment]
@Muzammil-Bilwani `Modal` is not designed for interacting with backend services. You can custom the `footer` prop to achieve your demands.

**Comment by yesmeck** [comment]
You are free to pass any variable to `onOk` with closures.

```
function showConfirm(index) {
  confirm({
    title: 'Do you Want to delete these items?',
    content: 'Some descriptions',
    onOk() {
      console.log(index);
    },
    onCancel() {
      console.log('Cancel');
    },
  });
}
```
