### ISSUE TITLE
Search Box doesn't show the option text but show the value instead.

### ISSUE THREAD

**Issue by khiav223577** [ant-design/ant-design#9343]
### Version
3.2.1

### Environment
chrome

### Reproduction link
[https://ant.design/components/select/#components-select-demo-search-box](https://ant.design/components/select/#components-select-demo-search-box)

### Steps to reproduce
use the example in docs

### What is expected?

This is the ajax response:
![image](https://user-images.githubusercontent.com/4011729/36090659-29b2bb16-101c-11e8-879a-da7174a9e2c5.png)

r[0] is the item text
r[1] is the item ID
I expect the option value to be ID, not the text
[search-box.md#L44-L47](https://github.com/ant-design/ant-design/blame/3.2.1/components/select/demo/search-box.md#L44-L47)
```diff
result.forEach((r) => {
  data.push({
-   value: r[0],
+   value: r[1],
    text: r[0],
  });
});
```

### What is actually happening?

the form submit the item text to backend instead of the item ID
But if I change the option value to be ID, the search box will show the option ID, not the option text.

照範例做的話，option value 和 option text 都被設成了文字，顯示上會是正確的，但送到後臺的會是文字，而不是數字

若 option value 設成數字則在 Search Box 的顯示上會錯誤地顯示成數字，而不是文字

**Comment by yesmeck** [comment]
Use `labelInValue`.
