### ISSUE TITLE
Mention handle/intercept Enter key

### ISSUE THREAD

**Issue by synapse** [ant-design/ant-design#9344]
### What problem does this feature solve?
In case the mention box is used to send a chat message it would be used for saving/submitting the message while pressing the Enter key.

### What does the proposed API look like?
```javascript
<Mention
    style={{ width: '100%' }}
    onChange={onChange}
    defaultValue={toContentState('@afc163')}
    suggestions={['afc163', 'benjycui', 'yiminghe', 'RaoHai', '中文', 'にほんご']}
    onPressEnter={handleSubmit}
/>
```

**Comment by kristiankyvik** [comment]
+1 is this in the makings?

**Comment by Dhuliang** [comment]
The good way is to use `addEventListener` , it works for me

**Comment by afc163** [comment]
Try `onKeyDown`.
