### ISSUE TITLE
[Table] Pagination on the top in addition to the bottom

### ISSUE THREAD

**Issue by MrSaints** [ant-design/ant-design#9346]
### What problem does this feature solve?
I'd like to discuss a potential idea / feature request.

Currently, the <Table /> pagination is rendered only at the bottom (see https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L996).

From a user experience point of view, I see more advantages to having the pagination on the top of the table, in addition to the bottom. The only significant disadvantage being the space required to achieve this. Indeed, a user will not have to scroll to the bottom of the table to paginate, and such a case may be necessary when the user already knows that they want to paginate to the next set of results. It will also provide immediate feedback on the total number of items without scrolling to the bottom.

### What does the proposed API look like?
Arguably, we could ship this by default. Or, we can have an option like:

```
paginationPosition: top | bottom | both
```

**Comment by yesmeck** [comment]
How about `<Table pagination={{ position: 'both' }} />`?

**Comment by MrSaints** [comment]
@yesmeck Isn't the `pagination` prop used by https://ant.design/components/pagination/, not the table? The pagination component itself does not know how it is being used.
