### ISSUE TITLE
Table with only fixed columns will show duplicate column

### ISSUE THREAD

**Issue by simondiep** [ant-design/ant-design#9347]
### Version
3.2.1

### Environment
OSX El Capitan, Chrome 63

### Reproduction link
[https://codesandbox.io/s/rxqv73yoq](https://codesandbox.io/s/rxqv73yoq)

### Steps to reproduce
Create a Table with two columns.  For each column, set the property 'fixed': 'left'.
Add some data the rightmost column.  Render the table.

### What is expected?
Only two columns should display.

### What is actually happening?
Four columns display.  One is blank and the other is a duplicate of the rightmost column.

---
I think this is happening based on how a fixed column is implemented as two columns

**Comment by afc163** [comment]
It don't make sense to fix all columns and you should set width to fixed column.

**Comment by simondiep** [comment]
The use case is if there is a column selector and the user decides to deselect columns until there is one left.
