### ISSUE TITLE
Clear Autocomplete after form submit

### ISSUE THREAD

**Issue by cyzeng-Luca** [ant-design/ant-design#9350]
### Version
3.1.6

### Environment
Mac 10.12.6

### Reproduction link
https://codesandbox.io/s/qpo488rzw

### Steps to reproduce
I have a form, one of formItem is AutoComplete(children is Input). I set a fixed value in dataSource at first, i want to clear Autocomplete value which is not in  search list after form submit  with resetFields. But when i clear it, the Autocomplete search list is show.
(if the value which is in search list, the search list is not show after resetField, i want it !)

for example, you can input "qwertyu" and click test

### What is expected?
when i clear Autocomplete value which is not in search list, the search list is hide.

### What is actually happening?
when i clear Autocomplete value which is not in search list, the search list is show.

**Comment by danedavid** [comment]
can I work on this ?

**Comment by yesmeck** [comment]
@danedavid Sure

**Comment by danedavid** [comment]
Just wanted to know if this is a _feature_ ? Like automatically opening the options since you entered a wrong choice ?

**Comment by yesmeck** [comment]
@danedavid It's a feature, but when the Autocomplete lost the focus, it should not automatically opening anymore, what do you think?

**Comment by danedavid** [comment]
@yesmeck Yes, I too think that way. Here is the sandbox I forked from @cyzeng-Luca and replaced the import with the library code for `<AutoComplete>`. When are the methods `focus()` and `blur()` of `AutoComplete` called ? I tried console logging and they didn't show up.

I think a solution is hiding the `Options` inside `onBlur` of the `Select` component. What do you think ?

**Comment by yesmeck** [comment]
I think the related code is here https://github.com/react-component/select/blob/6ab7ea0a9830b53334ce2afad8de1816f1113f59/src/Select.jsx#L137

**Comment by danedavid** [comment]
@yesmeck I did some research and ran through code a few times.
Looks like the issue is, when the submit button is clicked, and the modal 'OK' pressed, the form gets reset. The `getFieldDecorator()` assigns a new `value` props to the `<AutoComplete/>`. Just like deleting characters in the input, the `AutoComplete` takes this value and renders the suggestions as if we just typed `''` into the input.  
Possible solutions is, if the element is not focused when the value changes, set `skipAdjustOpen`, in `componentWillReceiveProps()`  
Any suggestions ?

**Comment by danedavid** [comment]
To be precise, the following lines inside the `if` on [L118](https://github.com/react-component/select/blob/master/src/Select.jsx#L118)
```
      if ( document.activeElement !== this.getInputDOMNode() ) {
        this.skipAdjustOpen = true;
      }
```

**Comment by yutingzhao1991** [comment]
@danedavid 

look at https://github.com/react-component/select/blob/master/src/Select.jsx#L287 you can use `setTimeout` to unset it.

But I think the better way is set open state to false in `adjustOpenState` when the Autocomplete lost the focus. not need set `skipAdjustOpen`.

**Comment by danedavid** [comment]
Adding these lines:
```
    if ( !this._focused ) {
      if ( open ) { open = false; }
    }
```
at the end of `adjustOpenState()` solved the current issue, but so many tests failed after I did that, like:
`Select › does not filter when filterOption value is false`
`Select › backfill`
`Select › number value › search number value` and more.

What could be corrected, or what could be going wrong ?

**Comment by Downchuck** [comment]
combobox appears deprecated from pull #10947

**Comment by afc163** [comment]
This problem is not reproduced in https://codesandbox.io/s/qpo488rzw now, maybe it is been resolved now. Please help to confirm it. @cyzeng-Luca

I will reopen if it is not true.
