### ISSUE TITLE
Sketch 文档中字体的共享样式 | 请让设计师来看此 Issues (๑•̀ㅂ•́)و✧

### ISSUE THREAD

**Issue by arvinxx** [ant-design/ant-design#9354]
### What problem does this feature solve?
 设计师在 Sketch 中设计界面时需要手动修改字体，一方面效率较低，另一方面一致性差。因此建议为 Ant Design Sketch 文档添加对应的字体样式。便于为使用 Ant Design Sketch 的设计师提供更加良好的用户体验。

### What does the proposed API look like?
一份设置好共享样式的文档以及对应的使用指南。（这就是设计师的 API 呀）

![](http://ox55f9bg6.bkt.clouddn.com/2018-02-13-%E5%AD%97%E4%BD%93%E7%B3%BB%E7%BB%9F%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.png)

提供一份我设计完成的 Sketch 文档以供参考。链接:https://pan.baidu.com/s/1o8ZesPW  密码:60jh

如果把字体共享样式的问题搞定，那么接下来则是共享样式在 Symbol 中的使用，如何用一种比较好的模式让不同类型的组件继承所需的字体样式，并且易于在 Nest Symbol 中修改。

**Comment by arvinxx** [comment]
增加两份动图演示
1. 修改样式
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180214/hCEBaJF0ib.gif)
2. 应用样式
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180214/glfmLlif9L.gif)

**Comment by arvinxx** [comment]
文档中关于Sketch的「替换」颜色有点问题。仔细研究后发现会替换掉所有的颜色，这会和预期相违背，目前正在寻找更好的解决方案…

**Comment by yesmeck** [comment]
https://zhuanlan.zhihu.com/p/33925661

感谢分享
