### ISSUE TITLE
IE 9 下的 matchMediaPolyfill 没起作用，仍然报错

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#936]
Carousel 组件使用到 react-slick 中需要 matchMedia，Antd 中提供的 polyfill 在 ie9 下没起作用，仍然报错：
> matchMedia not present, legacy browsers require a polyfill

环境说明：
采用 webpack + babel 编译

**Comment by afc163** [comment]
polyfill 建议全局引用。

试试 http://ant.design/docs/react/getting-started#%E5%85%BC%E5%AE%B9%E6%80%A7 的这个 polyfill 。

**Comment by afc163** [comment]
没有反馈了？

**Comment by someok** [comment]
目前我没有用到这个组件，而且打包使用了Babel-antd插件，所以没再遇到这个问题，晚上我再试试
偏右 <notifications@github.com>于2016年2月1日 周一11:54写道：

**Comment by someok** [comment]
采用上面那个 polyfill 之后，ie9 下正常了
