### ISSUE TITLE
Upload is not working in localhost Component:Upload

### ISSUE THREAD

**Issue by kbardi** [ant-design/ant-design#9361]
### Version
antd 3.2.0
dva 2.0.3

### Environment
Mac OS High Sierra 10.13.3,
Chrome version 64.0.3282.140
Node v6.9.1
npm v5.6.0

### Reproduction link
[https://codesandbox.io/s/q4l788znkw](https://codesandbox.io/s/q4l788znkw)

### Steps to reproduce
Start platform using npm run start:no-proxy. (I configured my no-proxy url in, roadhogrc.mock.js and it's working for all the other api calls)
Upload small image file.

### What is expected?
It is expected to receive the file in my API service.

### What is actually happening?
I checked my API service and it's working calling upload file from a different place, but when I call it from my web built with ant design, using Upload component, Upload shows headers and request body correctly, but my API receive no files. 

---
#### my code:
```
    <Upload
        action="/api/upload_file"
        listType="picture-card"
        showUploadList={{ showPreviewIcon: false }}
        headers={{
          Authorization: `Bearer 'token'`,
        }}
        name="file"
        withCredentials
    >
        <Icon type="plus" />
        <div className="ant-upload-text">Upload</div>
    </Upload>
```
#### Request general:
> **Request URL**: http://localhost:8000/api/upload_file
> **Request Method**: POST

#### Request headers:
> **Accept**: \*/\*
> **Accept-Encoding**: gzip, deflate, br
> **Accept-Language**: en-US,en;q=0.9,es;q=0.8
> **Authorization**: Bearer f3618115e76f934934983ehn9RvpoN5ohGjrOoBm9E3LA9OeZbiJW
> **Connection**: keep-alive
> **Content-Length**: 9815
> **Content-Type**: multipart/form-data; boundary=----WebKitFormBoundaryrNrG4oEpcIkf8gp4
> **Host**: localhost:8000
> **Origin**: http://localhost:8000
> **Referer**: http://localhost:8000/messages/new
> **User-Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) > Chrome/64.0.3282.140 Safari/537.36
> **X-Requested-With**: XMLHttpRequest

#### Request payload is:
> ------WebKitFormBoundaryrNrG4oEpcIkf8gp4
> Content-Disposition: form-data; name="file"; filename="Trenes_de_Buenos_Aires_Logo.png"
> Content-Type: image/png
>
>
> ------WebKitFormBoundaryrNrG4oEpcIkf8gp4--

**Comment by yesmeck** [comment]
It seems like a roadhog bug, you can file a new on roadhog repo https://github.com/sorrycc/roadhog

**Comment by zhuozp** [comment]
@kbardi Have you solved this problem. I got the same problem.

**Comment by kbardi** [comment]
@zhuozp No, it is working on production but it doesn't work on localhost. It seems to be a bug on roadhog as @yesmeck said, because it's everything the same between production and localhost, but in localhost we use proxy defined in .roadhog.mock.js (not the mock api but a locahost url). I don't know can we solve this problem. If you find a solution please let me know.

**Comment by yesmeck** [comment]
Try use webpack's proxy.

**Comment by munroe7** [comment]
@kbardi Did you ever find a solution? I am running into the same issue. I only have a localhost version of my app and can't test any of my upload functionality.

**Comment by kbardi** [comment]
@munroe7  I think the way I found to make it work is adding a proxy to `.roadhogrc.js`, but not really sure...it was a long time ago

It's not the best option because you add to the repo your local api path, and probably developers on the team have different path to the api.
You have to add
```js
proxy: {
    '/api': {
      target: 'http://localhost/PROJECT/API/',
      changeOrigin: true,
    },
  },
```

I think I tried to load that from env variable but it didn't work, I should check that again...

**Comment by habeebtheprogrammer** [comment]
i am also having the same issue. the server file upload api works fine. but when i am using antd design file upload component the file doesnt get to the server. :(

**Comment by munroe7** [comment]
> It seems like a roadhog bug, you can file a new on roadhog repo https://github.com/sorrycc/roadhog

I am not using roadhog and this is still an issue. The antd upload component does not use the proxy address defined in my react app (package.json). Every attempt using the upload component I get a 401 error saying it can't reach the localhost address of my react app and not my api, but if I try through axios, it goes through.

**Comment by vineetvk01** [comment]
Hey, Any solution for this issue?

**Comment by josh231101** [comment]
@vineetvk01  Have you found a solution? Recently I found this bug, used to happen to me only in localhost, now in production too. Everything should be working. Plz help

**Comment by Jood80** [comment]
If you're using `localhost` you'll need to make sure that your server is running concurrently with your client app.
Also your `action` endpoint has to be exist in your server routes too.

**Comment by alexeydemin** [comment]
Same here, the request reaches the PHP API, but without $_FILES

**Comment by t-bello7** [comment]
Pass a dummy request to the customRequest property of the Upload component
````
const dummyRequest = ({ onSuccess }: UploadRequestOption<any>) => {
  // const dummyRequest = ({ file, onSuccess }: {file: any, onSuccess: any}) => {

  setTimeout(() => {
    if (onSuccess) {
      onSuccess('ok');
    }
  }, 0);
}

**Comment by jonathanSimonney** [comment]
Thanks for the suggestion with dummyRequest which DOES fix it, but I'd love if something more "permanent" could be done natively in the lib. Since the problem occurs even with pure localhost backend called without roadhog.
