### ISSUE TITLE
[feature request][themes] runtime theming capability

### ISSUE THREAD

**Issue by DongShi** [ant-design/ant-design#9366]
### Version
3.2.1

### Environment
does not matter

### Reproduction link
[https://ant.design/docs/react/customize-theme](https://ant.design/docs/react/customize-theme)

### What is expected?
First off, sorry if I missed something about AntD theming capability, yet what I see is AntD exposes limited flexibility in theming its components. By reading its documents (https://ant.design/docs/react/customize-theme  and https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f), all these customization happens at compile time? 

So is there an official guideline on how to support theme change for AntD components at runtime, say with a switch in code or something alike?  The fact is, runtime theming is an important feature for business software,  it is feasible in AntD Pro? 

Probably you guys should put some thoughts into this (maybe with CSS custom properties?). I did see some similar requests on github issues, but it seems all of them are closed for no good reasons. This is ....frustrating. 

In our own cases, we have used several  AntD components and to meet our own needs, we have to override the compiled css styles by ourselves, sometimes this is an pain in the daily development (having to dig into the detailed css styles of AntD).  It is currently blocking us form  adopting AntD extensively in our projects.

What we expect form AntD is a read-to-use themable library and we should just need to focus on the biz logic.

Just my two cents.

### What is actually happening?
runtime theming is not supported.

**Comment by tim-soft** [comment]
Allowing this to work beyond build time without weird hacks may introduce a lot of challenges, but I agree. Messing with less, (less loader doesn't support hot reload) and rebooting the app to see the changes is pretty painful in dev.

**Comment by yesmeck** [comment]
We considered using styled-component to support runtime theming but ended up giving up, see reasons [here](https://github.com/ant-design/ant-design/issues/5570#issuecomment-332551645).

But you can still change runtime theming by compiling less on the fly, you can check the color [change button](https://github.com/ant-design/ant-design/blob/a6ffd332faeaf5649e5ace863a90897ae1f1d9ee/site/theme/template/Layout/Footer.jsx#L35-L59) we implemented on ant.design itself as an example.

**Comment by DongShi** [comment]
Thanks for the pointer, we try it anyway.
Hope this official support would be on your timetable soon.

**Comment by Xing-He** [comment]
I tried as you say @yesmeck  , But it doesn't work for me!

it shows the color-picker and changed state successfully, however the primary color still blue as follows:

```css
.ant-btn-primary {
    color: #fff;
    background-color: #1890ff;
    border-color: #1890ff;
}
```



- react : 16.2.0
- dva : 2.1.0
- antd : 3.1.1
- react-color : 2.14.0

- This is my `.roadhogrc` file

```js
{
  "entry": "src/index.js",
  
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        "transform-decorators-legacy",
        "transform-class-properties",
        ["import", { "libraryName": "antd", "style": true }]
      ],
      "theme": "./theme.js"
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        "transform-decorators-legacy",
        ["import", { "libraryName": "antd", "style": true }]
      ],
      "theme": "./theme.js"
    }
  }
}

```

- `theme.js`

```js
module.exports = () => {
  return {
    'table-padding-vertical': '6px', 
    'table-padding-horizontal': '6px',
    'font-size-base': '13px', 
    'table-header-bg': '#fbf6f6', 
  };
};
```
- package.json

```json
{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "antd": "^3.1.1",
    "babel-runtime": "^6.9.2",
    "classnames": "^2.2.5",
    "dva": "^2.1.0",
    "lodash-decorators": "^4.5.0",
    "moment": "^2.19.4",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-color": "^2.14.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "mockjs": "^1.0.1-beta3",
    "redbox-react": "^1.4.3",
    "roadhog": "^1.1.1"
  }
}
```

**Comment by mzohaibqc** [comment]
@DongShi After a long struggle, I was able to write a script to generate `color.less` file containing my required less variables and css rules just to update colors as they are doing for Ant Design website but only for one color `@primary-color`.
You can read my article at Medium https://medium.com/@mzohaib.qc/ant-design-live-theme-588233ea2bbc or download source code from github and follow that. 

Github: https://github.com/mzohaibqc/antd-live-theme

Live Demo: https://mzohaibqc.github.io/antd-live-theme/

**Comment by DongShi** [comment]
Another find: it seems antd is defining "prefixCls" (just search this in the repo), you can see that it is  using this variable to define your own css classname to do the styling/theming work.  So as a last fallback, I guess we can always use this variable to control the look and feel of the antd component at runtime.
@mzohaibqc @tim-soft @Xing-He 

However, there is no mention of this 'prefixCls' thing in the document, i am really curious why....
Is is a ok to use prefixCls?
@yesmeck @afc163

**Comment by yesmeck** [comment]
Yes, you can use it.

**Comment by gevgeny** [comment]
I really like idea to use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) for realtime theming. It is widely supported today by all modern browsers:
<img width="993" alt="screen shot 2018-06-29 at 11 32 52 am" src="https://user-images.githubusercontent.com/1986803/42082282-436c87be-7b90-11e8-8583-a915f1fcd785.png">
But and I understand that adding this feature requires a lot of routine work.
