### ISSUE TITLE
Add an event object to onSelect handler in a Table

### ISSUE THREAD

**Issue by niba** [ant-design/ant-design#9368]
### What problem does this feature solve?
Currently, it's not possible to detect what key on keyboard user held down during selecting rows in a Table.

I would like to mimic windows folder selection e.g. to select multiple items hold down the CTRL key, to select a few items at the same time hold down the SHIFT key. To do that I need an event data in onSelect handler which I pass to rowSelection.

### What does the proposed API look like?
onSelect(record: Script, selected: boolean, selectedRows: Object[], e: Event)

**Comment by kanweiwei** [comment]
@niba Due to the event object comes from `RcCheck`, so I will bring up this issue to [rc-component](https://github.com/react-component/checkbox)
