### ISSUE TITLE
如何禁止Tag标签自带的关闭动画

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#937]
我有一组tag标签，读取this.state.words（数组）渲染，通过onClose操作state实现删除功能（删除words中指定下标的项）。
本来没什么问题，只是tag标签自带关闭动画，每点一次删除，删掉2个标签（真删除一个，自动关闭一个），造成展示的结果跟state对不上。

特别想吐槽：不受控的关闭动画的作用是什么？

**Comment by afc163** [comment]
是否是这样的功能：http://codepen.io/anon/pen/GoxdKb?editors=001

这个例子除了没有动画，没有发现删掉两个标签的问题。楼主看下实现，或者参照给个例子给个重现吧。

**Comment by xiao-hai** [comment]
@afc163 重现例子：http://codepen.io/anon/pen/dGmryR?editors=0011
我发现是由于key不唯一引起的，不知这个情况以后会优化代码还是文档说明一下？

**Comment by afc163** [comment]
保证数组元素的 key 唯一是 React 的基本要求，详见：http://facebook.github.io/react/docs/multiple-components.html#dynamic-children 建议严格遵守，否则会有各种无法预知的问题。

严格的说这和 antd 本身关系不大。

**Comment by xiao-hai** [comment]
@afc163 非常感谢。

**Comment by bang88** [comment]
@xiao-hai 后面你怎么处理。。  我现在也遇到这个问题。   :sake:
