### ISSUE TITLE
Card tabs get cut off when there are too many

### ISSUE THREAD

**Issue by booboothefool** [ant-design/ant-design#9371]
### Version
3.2.1

### Environment
Google Chrome/Firefox

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
At https://ant.design/components/tabs/ under "Add & close tab", add a few and resize your browser until the > appears. Click on it and notice it doesn't properly scroll all the way. `type=line` tabs scroll properly, but not `type=card`.

### What is expected?
When you press > it should scroll all the way to fully reveal the last tab.

### What is actually happening?
It gets cut off.

![screen shot 2018-02-17 at 1 07 03 pm](https://user-images.githubusercontent.com/13257645/36344144-19aba806-13e4-11e8-8a03-0f3aa671213d.png)

**Comment by alisakova** [comment]
the same problem, not only with closable tabs.

**Comment by cesarbecerra** [comment]
Same problem here

**Comment by afc163** [comment]
Fixed in rc-tabs@9.2.4, try reinstall node_modules.

**Comment by alisakova** [comment]
it's still old version of rc-tabs (9.2.0) in node-modules, even after reinstall

**Comment by afc163** [comment]
Check your package-lock.json or yark.lock file.
