### ISSUE TITLE
Menu will not reopen on mobile browsers

### ISSUE THREAD

**Issue by joenot443** [ant-design/ant-design#9377]
### Version
3.2.1

### Environment
iOS 10, Chrome / Safari

### Reproduction link
[https://codesandbox.io/s/3x3p61l60m](https://codesandbox.io/s/3x3p61l60m)

### Steps to reproduce
Open the sandbox on an iOS device. Tap the button to open the dropdown.

Tap away from the dropdown.

Tap the button again.

### What is expected?
It is expected for the dropdown to close upon tapping away. It is expected for the dropdown to open again when the button is tapped.

### What is actually happening?
After the first time the button is pressed, the dropdown will take several taps before it opens correctly. 

---
This bug only seems to exist on mobile browsers. It functions fine in the Chrome Dev Tools device option, and on regular desktop browsers.

**Comment by valleykid** [comment]
Dropdown option `trigger` default value is `['hover']` which is trigger in desktop browser. Please replace it with `['click']`, like [this](https://codesandbox.io/s/xmjzmzkwp). Of course, I suggest you use the [menu](https://mobile.ant.design/components/menu/) in mobile browser.
