### ISSUE TITLE
Submit form from external button (Form in Modal)

### ISSUE THREAD

**Issue by X-Tender** [ant-design/ant-design#9379]
I have a Model with a form in it and would like to submit the form with the button which is in the footer of the modal.
There's no such method like "submit".
The Only way I see right now is to give the form an ID and getit via getElementById and call submit(). 
But I would like to trigger the validation process too.
How can I achieve it?

**Comment by ToJen** [comment]
@X-Tender were you able to solve this?

**Comment by ToJen** [comment]
I found a hack around it. Checkout my [form](https://github.com/Sagrix/superdemo/blob/master/src/user/ui/inputmodals/AddToCircleForm.js) used in this [modal](https://github.com/Sagrix/superdemo/blob/master/src/user/ui/inputmodals/CircleModal.js).

**Comment by X-Tender** [comment]
I cant see any "hack". You only have the Cancel button in the Footer. What we try to achieve is to add a submit button to the Footer.
