### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by chinachuner** [ant-design/ant-design#938]
npm WARN package.json demo@0.1.0 No repository field.
npm WARN locking Error: EACCES, open '/Users/zhangrain/.npm/_locks/antd-aef2b2baa9661f3e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/zhangrain/.npm/_locks/antd-aef2b2baa9661f3e.lock failed { [Error: EACCES, open '/Users/zhangrain/.npm/_locks/antd-aef2b2baa9661f3e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/zhangrain/.npm/_locks/antd-aef2b2baa9661f3e.lock' }
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "antd"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /Users/zhangrain/node_modules/antd, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhangrain/Documents/前端/react/antd/npm-debug.log

**Comment by huangguozhen** [comment]
这看起来像是一个权限受限的问题。或许你可以执行以下命令后再试试
```
sudo chown -R `whoami` /User/zhangrain/.npm
```
另外可以参考这个视频https://www.youtube.com/watch?v=bxvybxYFq2o

**Comment by afc163** [comment]
http://www.lmgtfy.com/?q=Attempt+to+unlock+which+hasn%27t+been+locked

https://github.com/npm/npm/issues/4815
