### ISSUE TITLE
Submit form from external button (Form in Modal)

### ISSUE THREAD

**Issue by X-Tender** [ant-design/ant-design#9380]
### What problem does this feature solve?
I have a Model with a form in it and would like to submit the form with the button which is in the footer of the modal.
There's no such method like "submit".
The Only way I see right now is to give the form an ID and getit via getElementById and call submit().
But I would like to trigger the validation process too.
How can I achieve it?

### What does the proposed API look like?
callable submit method on the form

**Comment by yesmeck** [comment]
See https://ant.design/components/form/?locale=en-US#components-form-demo-form-in-modal

**Comment by gevgeny** [comment]
@yesmeck Unfortunately handling submit via JS is not not enough and submit on enter still does not work.
Fortunately new `form` attribute solves the issue.
```jsx
<Form id="myForm">...</>
...
<Button form="myForm" key="submit" htmlType="submit">
  Submit
</Button>
```
See [browser support](https://caniuse.com/#search=form)

**Comment by kmcaloon** [comment]
Why not use the button `onClick` to update the form's props in order to conditionally run the submit logic?  Here is an example reduced down to what would be needed:

```
class ParentContainer extends PureComponent {

  state = {
    isSubmittingForm: false,
  }

  handleOkClick = () => {

    this.setState({
      isSubmittingForm: true,
    });

  }

  render() {

    <Modal
    onOk={ this.handleOkClick }
    >
      <FormInModal
      isSubmitting={ this.state.isSubmittingForm }
      />
    </Modal>

  }

}
```

```
class FormInModal extends PureComponent {

  // Check to see if form has submit update.
  componentDidUpdate( prevProps ) {

    if( prevProps.isSubmitting !== this.props.isSubmitting ) {
      this.handleSubmit();
    }

  }

  // Run the submission logic.
  handleSubmit = () => {

    // Do what you need to do...
    
  }

}
```

**Comment by saviourdog** [comment]
same request,any solutions?

**Comment by halitogunc** [comment]
this is exactly what you are looking for  https://ant.design/components/form/#components-form-demo-form-in-modal

**Comment by charanjit-singh** [comment]
How about: 

```
 <Modal
        okButtonProps={{form:'category-editor-form', key: 'submit', htmlType: 'submit'}}
        onCancel={() => {
            dispatch({
                type: 'categoryEditor/closeEditor'
            })
        }}>
        <Form id='category-editor-form' layout="vertical" onFinish={onFinish}>

        </Form>
```

**Comment by xr0master** [comment]
Why, guys, do you not like the hooks solution?

```jsx 
const [isOpen, setIsOpen] = useState(false);
const [form] = Form.useForm();

const onSubmit = useCallback((values) => {
// do your staff with values
}, []);

const closePopup = useCallback(() => {
  form.resetFields();
  setIsOpen(false);
}, [form]);

<Modal
  visible={isOpen}
  onOk={form.submit}
  onCancel={closePopup}
>
  <Form
    form={form}
    onFinish={onSubmit}
  />
</Modal>
```

**Comment by khalibloo** [comment]
@xr0master  The hooks solution above works for many cases, but becomes cumbersome when you have several components between the Modal and the Form. You'll find yourself having to drill the props or use the context API.
It would be nice if there were a clean way to obtain a reference to any form on the page by using the form `name` or `id`.

**Comment by webjoyable** [comment]
> How about:
> 
> ```
>  <Modal
>         okButtonProps={{form:'category-editor-form', key: 'submit', htmlType: 'submit'}}
>         onCancel={() => {
>             dispatch({
>                 type: 'categoryEditor/closeEditor'
>             })
>         }}>
>         <Form id='category-editor-form' layout="vertical" onFinish={onFinish}>
> 
>         </Form>
> ```

Exactly what I needed, since I had to connect form submission to buttons on parent (modal)

**Comment by renerlemes** [comment]
How to get values in onOk (modal) instead onFinish (form). With this, it is possible to change the state of the Ok button to show loading

**Comment by yogithesymbian** [comment]
> @yesmeck Unfortunately handling submit via JS is not not enough and submit on enter still does not work. Fortunately new `form` attribute solves the issue.
> 
> ```js
> <Form id="myForm">...</>
> ...
> <Button form="myForm" key="submit" htmlType="submit">
>   Submit
> </Button>
> ```
> 
> See [browser support](https://caniuse.com/#search=form)

its possible for multple form and different form for one single button `submit` ?
