### ISSUE TITLE
AutoComplete.Option children issue

### ISSUE THREAD

**Issue by bwlt** [ant-design/ant-design#9381]
### Version
2.13.11

### Environment
browser

### Reproduction link
[https://codepen.io/anon/pen/QQmJbV](https://codepen.io/anon/pen/QQmJbV)

### Steps to reproduce
When selecting an option a propTypes warning is displayed on console; also the input value is composed with [object Object]

### What is expected?
I'm expecting that the children of AutoComplete.Option could be any React.Node

### What is actually happening?
It stringify the children prop instead of render it

**Comment by yesmeck** [comment]
Duplicate of #4853
