### ISSUE TITLE
The fact that Tabs component's event handlers take activeKey by default as the first positional argument is not revealed in document.

### ISSUE THREAD

**Issue by dudueasy** [ant-design/ant-design#9386]
### What problem does this feature solve?
I found that component Tabs' event handler such as onChange handler would take activeKey by default as the first positional argument by printing arguments[0] out, but it's not mentioned in ant-design's document. 

I think adding this to antd's Tabs component page would make it much understandable.

### What does the proposed API look like?
Just keep it nice and simple.

**Comment by yesmeck** [comment]
You can PR directly next time if you find any document improvement.
