### ISSUE TITLE
[Message] - allow selecting position for display

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#9387]
### What problem does this feature solve?
Be able to select where Message appears: top left corner; top; top right corner; bottom left corner; bottom ; bottom right corner;

### What does the proposed API look like?
Argument: 'position'

**Comment by afc163** [comment]
message should only appear in center/top position.

**Comment by avalanche1** [comment]
@afc163  - that's it? No explanation, no reasoning, no nothing?
Would you accept a PR?

**Comment by muzea** [comment]
Sorry, I'm wrong, it was gloomy in the morning.

**Comment by saostad** [comment]
I need it too. Would you accept a PR?

**Comment by wichopy** [comment]
Got it to the bottom using a few lines of CSS:

```
.ant-message {
  bottom: 20px;
  top: initial;
}
```

At work I'm using Material ui which has a much more customizable api for messages/alerts
https://material-ui.com/demos/snackbars/#positioned

I think its good antd has some solid design rules but this particular one seems too strict.

**Comment by avalanche1** [comment]
How about reopen this?

**Comment by jasonlangdon-sky** [comment]
Adding the ability to have a class associated with a message would be a simple way to rectify not having a position property.

I agree that this should be reopened.

**Comment by victorpinheiro** [comment]
Nothing yet? I'd really like to customize the position of the message.

**Comment by MidouDev** [comment]
I guess what you can do is use custom css using their style property.
I wanted it to be top-right so I did this : 

    message.error({
      content: formatMessage(_get(messages, "feesError")),
      style: { textAlign: "right" },
    });

**Comment by tshyti** [comment]
I'm stuck on trying to use different "top" depending on the message instance.

Let's say that page A needs the message to be displayed in `top:20px` and page B wants it to be displayed in `top:50px`.
If I edit the .ant-message like this:
`.ant-message {
  top: 90px;
}`
It can only be edited once.
We need to have a solution like this: 

`message.error({
   left: 'x px',
   top: 'y px'
 });`

This is a real issue that has to be fixed.

**Comment by vikomte** [comment]
Here for 2 Axis Manipulation
.ant-message {
	position: absolute;
	width: fit-content;
	bottom: 20px;
	top: initial;
	right: 20px;
	left: initial;
}

**Comment by ramavilli** [comment]
any update?

**Comment by igrlk** [comment]
For those who are looking for a way to pin `antd.message` to the bottom of the page with a correct animation, the following code can help:

### In your styles.css file:
```
.ant-message {
  position: absolute;
  bottom: 20px !important;
  top: unset !important;
}
```

### In the code:
```
message.config({
  transitionName: 'move-down',
});
```

### Works with Antd version: "4.6.1"

**Comment by laid0724** [comment]
are you for real? wow.

**Comment by tosh99** [comment]
You can also use this if you don't want a CSS based solution

message.config({
    top: window.innerHeight - 100,
});

**Comment by shamseerahammedm** [comment]
+1 much needed feature

**Comment by shivakantofficial** [comment]
I am using message at many places in my project but at one place I need its position to be bottom. Now I don't want to effect all my message component as per the above css solution. 
I tried giving it a custom className but that doesnt help because position property is given to its parent element.
`<div class="ant-message"><div><div class="ant-message-notice **zxcvb**">...{INTERNAL CODE HERE}...</div></div>`
zxcvb is my custom class here but the position is given to ant-message.
please give the solution.

**Comment by ajaykumarn3000** [comment]
is there any proper way to configure the position of messages, instead of having to use css?
