### ISSUE TITLE
Pills tabs

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#9389]
### What problem does this feature solve?
My interface already contains tabs, I would like to use nested tabs as pills view

### What does the proposed API look like?
Please add new type (style of tabs) = pills

![photo_2018-02-21_21-05-53](https://user-images.githubusercontent.com/1640229/36491153-ebd80c60-174b-11e8-8324-eadde6f2ccb4.jpg)

**Comment by yesmeck** [comment]
As our design guide said you can use Radio.Button inside a Tab for navigation. See https://ant.design/docs/spec/navigation#Pill
