### ISSUE TITLE
table树分层问题

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#939]
![qq 20160126205832](https://cloud.githubusercontent.com/assets/11780264/12581118/9c7f486c-c46f-11e5-86fa-ff3dcb884d03.png)
![qq 20160126205840](https://cloud.githubusercontent.com/assets/11780264/12581120/9d682d66-c46f-11e5-9d52-51876b158796.png)

**Comment by afc163** [comment]
没有看到问题？

**Comment by XUGAOBO** [comment]
没有啊,按照官网上的例子写的table

**Comment by benjycui** [comment]
意思是你要把问题描述清楚，ESR 写这篇 [文章](http://doc.zengrong.net/smart-questions/cn.html) 可不是为了卖弄。

**Comment by XUGAOBO** [comment]
![qq 20160127114237](https://cloud.githubusercontent.com/assets/11780264/12603163/177822c0-c4eb-11e5-9485-f7a411991a76.png)

**Comment by XUGAOBO** [comment]
这个应该清楚了

**Comment by afc163** [comment]
我这里测试是没有问题的。

**Comment by XUGAOBO** [comment]
好的  谢谢  我再看看
