### ISSUE TITLE
AutoComplete does not support maxLength

### ISSUE THREAD

**Issue by Leong21** [ant-design/ant-design#9390]
### Version
3.2.1

### Environment
windows, chrome, IE11

### Reproduction link
[https://codepen.io/anon/pen/BYVjQv?&editors=001](https://codepen.io/anon/pen/BYVjQv?&editors=001)

### Steps to reproduce
add maxLength to AutoComplete , <AutoComplete maxLenght={4}/>
The rendered input does not have maxLength attribute.

### What is expected?
maxLength attribute is in the rendered input, and only allow maxLength characters

### What is actually happening?
maxLength attribute missing from rendered input

**Comment by yesmeck** [comment]
```javascript
<AutoComplete>
  <Input maxLength={100} />
</AutoComplete>
```

**Comment by Leong21** [comment]
Thanks @yesmeck
