### ISSUE TITLE
Can't write nested dataIndex in TypeScript

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9393]
### Version
3.2.1

### Environment
TypeScript 

### Reproduction link
[https://github.com/whtsky/antd-typescript-dataindex](https://github.com/whtsky/antd-typescript-dataindex)

### Steps to reproduce
compile

### What is expected?
can compile

### What is actually happening?
can't compile

---
might related to #9298

**Comment by yesmeck** [comment]
I reverted #9298. Thanks for reporting.
