### ISSUE TITLE
Popconfirm component pop-up location is wrong

### ISSUE THREAD

**Issue by upfain** [ant-design/ant-design#9395]
### Version
3.1.3

### Environment
* macOS High Sierra
* Google Chrome 64.0.3282.167（64 ）

### Reproduction link
![2018-02-22 16_17_27](https://user-images.githubusercontent.com/23690145/36527556-28e17b22-17ed-11e8-9ee8-c7a5970e3b88.gif)
I tried retrying on CodeSandbox, but there is no problem
link : [CodeSandbox](https://codesandbox.io/s/lj9j8v3kz)
A similar problem:
#6905

### Steps to reproduce
Release the mouse after selecting the text

### What is expected?
There should not be any reaction

### What is actually happening?
Back to the upper left corner

**Comment by afc163** [comment]
You have to reproduce it or nothing we can help.
