### ISSUE TITLE
The Table Component Demand: Drag to change the width of the table column

### ISSUE THREAD

**Issue by xiamidong** [ant-design/ant-design#9401]
### What problem does this feature solve?
The  application scene: There are more columns in the table with different data length, and the  user wants to drag to change the width of the column.

### What does the proposed API look like?
I expect the API like the following:

```
  <Table 
     dataSource={dataSource} 
     columns={columns}
     dragColumn = true
 />
```

**Comment by yesmeck** [comment]
See this example http://react-component.github.io/table/examples/column-resize.html

**Comment by whenmoon** [comment]
> See this example http://react-component.github.io/table/examples/column-resize.html

I don't see what this has got to do with Ant Design?

**Comment by keithort** [comment]
@whenmoon React Component's Table (rc-table) is what Ant Design's Table component uses underneath but Ant Design adds a few features and styles.
