### ISSUE TITLE
I suggest the value of empty input/texarea can be configured

### ISSUE THREAD

**Issue by bigdots** [ant-design/ant-design#9403]
### What problem does this feature solve?
Sometimes, I want to get a 'null'  rather than a empty string from the empty input box.

##### Property
emptyValue

##### Description
The initial empty input content

##### Value
`'' | null`

##### Default
`''`

##### Example

```js
<Input emptyValue={null}/>
```

**Comment by yesmeck** [comment]
Please use the feature template if you want to request a feature.

**Comment by yesmeck** [comment]
If you are using `getFieldDecorator`, you can convert `''` to `null` by `getValueFromEvent`.

**Comment by bigdots** [comment]
ok,thanks
