### ISSUE TITLE
关于 ant-design tag标签删除功能需求问题

### ISSUE THREAD

**Issue by dachongdouniwan** [ant-design/ant-design#9405]
### What problem does this feature solve?
在点击现有tag按钮的删除功能时,即使重新制定close方法,默认会先将选中的tag删除.现在有个这样的需求,如果我需要点击x号的时候弹出confirm提示框,让用户选择是否确认删除该tag,如果确认需要则发送网络请求删除tag.上述需求在现有的tag工能是有问题的因为每次点击x号默认都会先删除该tag,
等confirm提示框出来的时候该tag已经在界面上消失,但是在后端服务器上依然存在,因为用户还没有点击确认按钮执行网络请求.

### What does the proposed API look like?
是否可以将点击x号时删除tag的权限,交由开发者来处理,让开发者通过操纵数据源来更新界面.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2970

**Comment by TryChai** [comment]
18年的issue 到现在还没解决嘛？

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/2970
