### ISSUE TITLE
I hope there is an extra parameter that will allow me to control mention`s @ whether there is a space before it

### ISSUE THREAD

**Issue by qhwc2009** [ant-design/ant-design#9407]
### What problem does this feature solve?
In mention component I hope there is an extra parameter that will allow me to control @ whether there is a space before it, because when I want to mention somebody, I don`t want to input a space. 

### What does the proposed API look like?
beforeWithSpace: Bool

**Comment by yesmeck** [comment]
See #6491

> <Mention /> currently use a space letter and a prefix to mark a mention trigger, so if we remove prefix after select, the word you just selected will be identified as a plain text.
