### ISSUE TITLE
建议 modal增加个类似 bootstrap 的 static 属性，以控制点击 mask 的时候不会关闭 modal

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#941]
一般在 modal 中有表单的时候应该防止用户误点击背景的时候关闭 modal 才是合理的选择。

现在的 closable 属性设置为 false 的时候右上角的关闭按钮也没了。

**Comment by afc163** [comment]
`closable={false}` 为什么还需要右上角的关闭按钮？

**Comment by someok** [comment]
这比较符合传统操作习惯吧，我一般不在下面提供「关闭」按钮。

另外顺便问下：modal 提供的关闭按钮 onCancel 的时候怎么触发里面的 form 提交呢？我用 findDOMNode submit 的时候，Form 的 onSubmit 没有拦截成功。

**Comment by afc163** [comment]
https://github.com/react-component/dialog/pull/14
