### ISSUE TITLE
TypeScript Error shows "antd_1.Form.createFormField is not a function"

### ISSUE THREAD

**Issue by missMHWGO** [ant-design/ant-design#9410]
### Version
2.13.11

### Environment
Google Chrome 63.0.3239.132

### Reproduction link
[https://codesandbox.io/s/917kxjp944](https://codesandbox.io/s/917kxjp944)

### Steps to reproduce
I just follow the document demo.

### What is expected?
I hope to see the result and no error.

### What is actually happening?
uncaught at  TypeError: antd_1.Form.createFormField is not a function

**Comment by benjycui** [comment]
You need to upgrade to antd@3.0 to use `Form.createFormField`.

**Comment by missMHWGO** [comment]
@benjycui I see...thank you
