### ISSUE TITLE
谷歌浏览器下使用微软输入法InputNumber控件设置千分位formatter后无法连续输入数字问题

### ISSUE THREAD

**Issue by huajunShan** [ant-design/ant-design#9416]
### Version
undefined

### Environment
操作系统：win10 ；浏览器：谷歌浏览器（63.0.3239.132 64位）；输入法： 微软输入法；antd版本号：2.13.10

### Reproduction link
[https://codepen.io/anon/pen/rJqMgN?&editors=001#anon-signup](https://codepen.io/anon/pen/rJqMgN?&editors=001#anon-signup)

### Steps to reproduce
1.使用微软输入法并切换为半角中文模式，在提供的重现链接的网页下面的千分位输入控件框中输入数字。

### What is expected?
会产生由于控件千分号格式化导致连续输入数字后光标不会永远停留在最后的问题。
直接影响为无法连续输入数字，需要在添加千分位后手动移动光标后继续输入。

### What is actually happening?
输入完数字自动添加千分号后，光标依旧停留在输入框数字的最后，确保可以连续输入数字，不用手动切换光标。

---
重现BUG需要特定的场景：
此BUG只在谷歌浏览中存在，IE，EDGE，火狐并不存在此问题。
此BUG仅在输入法为微软输入法中文输入环境下产生，搜狗输入法不存在此问题。

**Comment by afc163** [comment]
Could you reinstall node_modules for rc-input-number@4.0.3 and try again?

**Comment by afc163** [comment]
Close for no feature response
