### ISSUE TITLE
获取Table的真实DOM结构，用来进行canvas转换

### ISSUE THREAD

**Issue by linlinNB** [ant-design/ant-design#9417]
### What problem does this feature solve?
需要将antv-g2的分组柱状图和antd中的table获取真是的DOM结构，从而拼接转换成为canvas，用来作为图片资源，进行保存

### What does the proposed API look like?
可以获取table数据填充完毕之后的DOM结构

**Comment by afc163** [comment]
可以在 componentDidMount 之后自行获取。
