### ISSUE TITLE
Mention 提及 无法访问

### ISSUE THREAD

**Issue by youmyyou** [ant-design/ant-design#9418]
### Version
3.2.2

### Environment
Google Chrome 版本 64.0.3282.167（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
点击 “Mention 提及” 菜单页面空白

### What is expected?
跳转到 “Mention 提及” 页面

### What is actually happening?
点击 “Mention 提及” 菜单页面空白

**Comment by yutingzhao1991** [comment]
https://codesandbox.io/s/wqq5j587j5

Demo throw error when call focus.

**Comment by yutingzhao1991** [comment]
related #8630
