### ISSUE TITLE
Work on reducing library size

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#9419]
### What problem does this feature solve?
The size of library source is WAY too big!
Importing a button increases app size by 95kb! A single button, omg! 28kb is the Button/index.css & 67kb is antd/index.css
Importing single Datepicker component increases my app size for 354kb!! (ungzipped):
- 71kb - antd/style/index.css
- 28kb - Button/style/index.css 
- 43kb - date-picker/style/index.css
- 30kb - date-picker/misc js files
- 9kb - time-picker/style/index.css
- 10kb - input/style/index.css
- 53kb - rc-calendar minified
- 52kb - moment
- 20kb - rc-time-picker
- 18kb - rc-trigger
- 14kb - dom-align
- 9kb - rc-animate
- 6kb - rc-util

Something has to be done about that - having single component weigh in additional 354kb - that's not possible in 2018.

### What does the proposed API look like?
no api changes

**Comment by yesmeck** [comment]
@avalanche1 Have you tried to analyze your bundle by [webpack visualizer](https://chrisbateman.github.io/webpack-visualizer/)?

**Comment by yesmeck** [comment]
We keep eyes on library size, If you have a more specific suggestion can reduce the library size, welcome leave a comment here. I'm going to close this issue because no actions we can take for now.

**Comment by skizzo** [comment]
Did anybody come up with something that works? My bundle size is huge and contains stuff i definitely don't need (or implement) anywhere.. Thanks!

**Comment by xxyuk** [comment]
@skizzo  @avalanche1 

Maybe this is what you need. 
https://github.com/iamkun/dayjs/issues/529
