### ISSUE TITLE
建议给button做点酷炫的点击效果

### ISSUE THREAD

**Issue by ibufu** [ant-design/ant-design#942]
就像material的button

**Comment by afc163** [comment]
这个可以有，有没有其他推荐，我们不太想直接抄袭 Material Design。

**Comment by jljsj33** [comment]
这个尝试过很多，感觉效果都不佳，所以还是用了最简单的一种方式，如果适合中后台按扭动效方案，可整个动图来看看。。。。

**Comment by stonephp** [comment]
样式也需要丰富一下。bootstrap的 success， danger真的挺好的。体现交互不同的侧重点。目前 antd 有点单一。其实也简单的增加个 color 属性也可以，想martial ui那样，有一系列的颜色可以选择。很容易搭配出不同的风格。

**Comment by afc163** [comment]
http://tympanus.net/Development/ButtonStylesInspiration/
http://codepen.io/hakimel/pen/ZYRgwB
