### ISSUE TITLE
Input Number allows a-z characters

### ISSUE THREAD

**Issue by jgmurillo10** [ant-design/ant-design#9421]
### Version
3.2.2

### Environment
MacOS, Google Chrome

### Reproduction link
[https://codesandbox.io/s/ox7mmz9n7y](https://codesandbox.io/s/ox7mmz9n7y)

### Steps to reproduce
type in the InputNumber component

### What is expected?
It must not allow the user to type a-z characters.

### What is actually happening?
The InputNumber allows the user to type a-z characters

---
It is required the attribute type="number"

**Comment by afc163** [comment]
The interaction is by designed as `<input type="number" />`.

**Comment by jaisonjjames** [comment]
@afc163 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

**Comment by luanpotter** [comment]
Clearly the InputNumber should at least have an option to disallow letters, shouldn't it? Is there any workarounds?

**Comment by ztplz** [comment]
@luanpotter  Please set type to `number`.

**Comment by luanpotter** [comment]
Hi, @ztplz , thanks so much for your feedback, it's working now!

**Comment by avalanche1** [comment]
@ztplz This is undocumented feature. It should be:

1. Documented
2. Set as default

Pls reopen!

**Comment by nossbigg** [comment]
I also agree with @avalanche1, as most people would expect `<InputNumber>` to accept only numbers by default (unless this behavior is explicitly overridden). 

Seems like there's resistance for this change to be implemented in the underlying library `rc-number-input` too (see: https://github.com/react-component/input-number/issues/113)

I guess the best way forward is that we just set `type="number"` in `<InputNumber>` (as per https://github.com/ant-design/ant-design/issues/9421#issuecomment-446812723) and move on 😕🤷🏻‍♂️

**Comment by ceciliamzayek** [comment]
If I set it to `type="number"`, then I cannot use the parser and `formatter` and `parser` to show currency

**Comment by guillermovasta** [comment]
`type="number"` doesn't work in Safari 14.1.

**Comment by conor-tighe-songtradr** [comment]
In the onChange of Input you can use the following to get around this:

```
const onChange = (value) => {
    if (Number.isNaN(value)) return;
    ... do stuff
  };
```

**Comment by DouggyC** [comment]
hows to trigger 

> In the onChange you can use the following to get around this with or without `type="number"` on the `<Input />` component.
> 
> ```
> const onChange = (value) => {
>     if (Number.isNaN(value)) return;
>     ... do stuff
>   };
> ```

how to trigger Forrm.Item warning message from  onChannge?

**Comment by prakashmallow** [comment]
type="number" is not working on the Firefox browser. Please check and fix it. I need to not allow characters to type on InputNumber. How to achieve this?

**Comment by yoyo837** [comment]
> 

It sounds like `<Input />` would be more suitable for your needs

**Comment by prakashmallow** [comment]
@yoyo837 I tried with <Input /> but the type="number" is not working in the Firefox browser.

**Comment by yoyo837** [comment]
I mean this https://github.com/ant-design/ant-design/issues/9421#issuecomment-1322815390

**Comment by prakashmallow** [comment]
@yoyo837 I will try  this  https://github.com/ant-design/ant-design/issues/9421#issuecomment-1104089054 
and update here

**Comment by prakashmallow** [comment]
@yoyo837 @ConorTighe  https://github.com/ant-design/ant-design/issues/9421#issuecomment-1104089054 is not working.

**Comment by yoyo837** [comment]
> @yoyo837 @ConorTighe [#9421 (comment)](https://github.com/ant-design/ant-design/issues/9421#issuecomment-1104089054) is not working.

 What it is you really want? confirm again.

**Comment by prakashmallow** [comment]
@yoyo837 InputNumber only allows entering numbers only. Don't allow text and special characters.

**Comment by yoyo837** [comment]
> @yoyo837 InputNumber only allows entering numbers only. Don't allow text and special characters.

Yes, bug <Input /> can do that. it allows you to enter any character.

**Comment by ConorTighe** [comment]
@yoyo837 @prakashmallow try isNaN

`const onChange = (value) => {
    if (isNaN(value)) return;
    console.log(value);
  };

onChange(100);
onChange("aaa");
onChange(200);`

**Comment by tomekregulski** [comment]
While the solutions given here technically work in terms of preventing a given callback to be called in the case of `isNaN(value)`, they do not seem to prevent the component itself from updating its value.

For reference, my code is like this:
```
<InputNumber
                        bordered={false}
                        controls={false}
                        disabled={disabled}
                        formatter={(value) =>
                            `${value}`.replaceAll(/\B(?=(\d{3})+(?!\d))/g, ',')
                        }
                        placeholder='Enter number'
                        style={{ textAlign: 'right' }}
                        {...restProps}
                    />
```

If I add
```
onChange: (value) => {
    const userInput = Number(value); // immutable value
    if (Number.isNaN(userInput)) return;
    console.log(userInput);
  };
```
The component still will still update its value with any alphanumeric character, which seems to be against the idea of having a component called InputNumber, where a reasonable assumption is that its default behavior would be to not allow inputting non-numbers. 

I've tried passing in `type='number'` but that resulted in strange behavior in the component. Is there not anything else we can do?

**Comment by killthecreator** [comment]
What a shame it is still not fixed. Why have it been closed?

**Comment by afc163** [comment]
@killthecreator Try `<InputNumber type="number" />`.
