### ISSUE TITLE
Font of numbers looks different than letters

### ISSUE THREAD

**Issue by plhosk** [ant-design/ant-design#9422]
### Version
3.2.2

### Environment
Windows 10 1709, Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Reproduction link
[https://codesandbox.io/s/jnw46698m3](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
When I click on the DatePicker and look at the month and year at the top (Feb 2018) the word "Feb" appears more bold than the number "2018". It seems like the numbers are using a different font.

Screenshot below:
![antd-numbers](https://user-images.githubusercontent.com/19312670/36703272-c103c688-1b0f-11e8-86c7-8e0bfc724110.png)

### What is expected?
For English web pages it is expected that the numbers use the same font as letters. This should be the default for English locale.

### What is actually happening?
When I inspect the css it appears the font-family starts with "Monospaced Number" which could account for the difference in font. 

In the default less theme:
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

```
@font-family-no-number  : "Chinese Quote", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
@font-family            : "Monospaced Number", @font-family-no-number;
```

---
As a workaround I can manually set the @font-family less variable to remove the "Monospaced Number" font, but I think this should be fixed by default.

**Comment by afc163** [comment]
It is by design.

**Comment by plhosk** [comment]
Perhaps this illustrates the problem better:
![antd-numbers3](https://user-images.githubusercontent.com/19312670/36708673-ebda6d1c-1b28-11e8-9e70-8ac8add31cff.png)

It looks OK with the regular font-weight but if i set the font-weight to 600 it looks bad. Also the selected option in the drop-down list shows the same problem.

I can see how this feature is intended for displaying numbers in Chinese language web sites but for English text it looks terrible. I think the "Monospace Number" entry in @font-family should be removed from the default english locale and instead only loaded for Chinese locale.

**Comment by afc163** [comment]
You can try override the `@font-family` by following https://ant.design/docs/react/customize-theme
