### ISSUE TITLE
Tree是否支持点击文字，选中节点； selectedKeys的父子节点是否有关联? 

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#9427]
### What problem does this feature solve?
我感觉点击文字选中复选框是个很常见的需求，TreeSelect支持该需求，但是那是一个下拉框，我看过Tree和TreeSelect发现TreeSelect的数据里有label这个参数，是不是跟这个参数有关，如果想在Tree的基础上通过onSelect去点击节点，又有selectedKeys父子节点不关联的情况

### What does the proposed API look like?
selectedKeys 和 checkedKeys 同样有父子节点关联的情况，会不会好一点，或者Tree开放一个可以点击文字选中复选框的功能

**Comment by yesmeck** [comment]
Duplicate of #8581 ?

**Comment by Zero0331** [comment]
@yesmeck  Maybe the demand is the same，I'd prefer Tree to have this function or TreeSelect can choose whether it is a drop-down box

**Comment by yesmeck** [comment]
Tree 的 select 和 check 逻辑就是分开的，你可以自己用 `onSelect` 来同步 select 和 check 的逻辑。

**Comment by Zero0331** [comment]
@yesmeck  我现在用onSelect已经把数据处理好了，需要保存的数据都没有问题，但是onSelect里selectedKeys这个参数，好像父子节点没有关联，导致前端显示有问题，没法处理全选半选的情况，我想用e这个参数去强行设置selected的true/false，不是很理想

**Comment by yesmeck** [comment]
直接把 `selectedKeys` 同步给 `checkedKeys` 就可以了。

**Comment by Zero0331** [comment]
@yesmeck   我没有理解你说的同步是什么意思， 这两个参数有可能会不一样，checkedKeys是正确的  我先把selectedKeys处理成checkedKeys这样的  然后调用onCheck， 最后的结果是正确的，但是前端显示有问题，在全选节点/半选节点 会导致问题。

**Comment by yesmeck** [comment]
@Zero0331 能否把你说的显示问题在 https://codesandbox.io/ 上重现下？

**Comment by Zero0331** [comment]
@yesmeck   我找到问题了  我this.setState写错位置了  因为我数据处理好了，所以很纠结为什么会渲染不对，刚才从头理了一遍逻辑，非常感谢陪我聊这么多，把我的思路理清了，还差点方法的问题我自己就可以解决了
