### ISSUE TITLE
使用ant-design的dva-cli构建开发环境运行项目报错Unexpected token } in JSON at position 114

### ISSUE THREAD

**Issue by Mu-99** [ant-design/ant-design#9428]
### Version
3.2.2

### Environment
windows

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
c:\Users\用户名\dva-project\npm start

### What is expected?
本步骤应该能够运行ant-design的项目，然后再 http://localhost:8000/#/products 打开该页面

### What is actually happening?
实际结构是在cmd命令行执行该步骤出现报错：>roadhog server 和 Unexpected token } in JSON at position 114

---
完成开发并且在开发环境验证之后，就需要部署给我们的用户了。先执行下面的命令：npm run build
build 命令会打包所有的资源，包含 JavaScript, CSS, web fonts, images, html 等。然后你可以在 dist/ 目录下找到这些文件

**Comment by yesmeck** [comment]
建议提到 https://github.com/sorrycc/roadhog
