### ISSUE TITLE
cascader 的key问题

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#943]
![qq 20160127145240](https://cloud.githubusercontent.com/assets/433259/12606116/b9d58c64-c505-11e5-9f17-122570e374d2.png)

**问题**：没有地方设置`key`，直接配置的`options:[]`，选择就报错，而且没有触发`onChange`事件

```js
"antd": "^0.12.0-beta.26"
```

@afc163 :sos:

**Comment by afc163** [comment]
不太理解，目前 key 是由 value 来设置的，因为 value 不可能相同。

`options:[]` 这样设置应该不会有菜单弹出。

**Comment by bang88** [comment]
不是这样设置，`options:[{id:'01',xxx.....},{}]`是有数据的

**Comment by afc163** [comment]
给出具体的配置和代码吧。

**Comment by bang88** [comment]
稍等下，我配置看看。  `key`现在是根据`value`来设置的 ?

**Comment by afc163** [comment]
对的，和 select 一致，选项的值应具有唯一性。

**Comment by bang88** [comment]
配置应该没有问题，数据里面也有value这个字段。

`const category` =>  https://gist.github.com/bang88/d5718d11c37560c0e82a

```js
<Cascader options={category} {...this.props}></Cascader>
```

**Comment by afc163** [comment]
有大量重复的字段。。。

**Comment by bang88** [comment]
主要看`value`现在重构使用的是之前的接口。

**Comment by afc163** [comment]
value 也是重复的，是完全一样的字段。

**Comment by bang88** [comment]
@afc163 谢谢。。   是数据问题
