### ISSUE TITLE
Table size small,don't normal show

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9430]
### Version
3.2.2

### Environment
windows 10 ,chorme latest,react latest

### Reproduction link
[https://codepen.io/hengkx/pen/RQqZww?&editors=001](https://codepen.io/hengkx/pen/RQqZww?&editors=001)

### Steps to reproduce
https://codepen.io/hengkx/pen/RQqZww?&editors=001

### What is expected?
normal show

### What is actually happening?
![image](https://user-images.githubusercontent.com/8358236/36716525-8bf2fa7e-1bd5-11e8-9218-3d182b7396d8.png)

**Comment by yutingzhao1991** [comment]
@hengkx 什么问题？没太看明白，滚动条？
