### ISSUE TITLE
If the List.Item is in A tag, the underline will not be displayed.

### ISSUE THREAD

**Issue by Shurlormes** [ant-design/ant-design#9431]
### Version
3.2.2

### Environment
Google Chrome 63.0.3239.132

### Reproduction link
[https://codepen.io/Shurlormes/pen/wyQrmQ](https://codepen.io/Shurlormes/pen/wyQrmQ)

### Steps to reproduce
Sometimes I want to click on the whole Item to trigger events, not only text.So I Put List.Item in A tag

有时需要点击整条Item触发事件，在外添加A标签后，List.Item的分隔下划线没有显示

### What is expected?
Show underline

显示分隔线

### What is actually happening?
Underline not displayed

没有显示

**Comment by yutingzhao1991** [comment]
`List` must use `List.Item` as child tag, in your case, you should write code like: `<List.Item><a href="javascript:void(0);">{item}</a></List.Item>`

**Comment by Shurlormes** [comment]
Then I have to click text to trigger the event, not , not the whole Item.

**Comment by Shurlormes** [comment]
Oh， It works in onClick

`<List.Item onClick={() => {console.log('a')}}>{item}</List.Item>`
