### ISSUE TITLE
Mention the selected cursor is not at the end

### ISSUE THREAD

**Issue by l-Lemon** [ant-design/ant-design#9432]
### Version
3.2.2

### Environment
win10

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
点击mention选项

### What is expected?
光标应该在最后

### What is actually happening?
光标不是在最后，而是出现在鼠标点击地方

**Comment by afc163** [comment]
I think the current behavior is correct.

**Comment by l-Lemon** [comment]
我选中一个，然后要把光标移到后面在继续输入，用户体验很不好

**Comment by l-Lemon** [comment]
我选中一个，然后要把光标移到后面在继续输入，用户体验很不好

**Comment by afc163** [comment]
用户很可能需要修改 @ 内容。

**Comment by l-Lemon** [comment]
那光标应该也在@ 内容的右边，不应该会出现在@ 的内容之间吧

**Comment by afc163** [comment]
可能需要从中间修改，@ 的内容也是正常的文本。

**Comment by l-Lemon** [comment]
目前遇到的都是偏右的，如果要是需要从中间修改这样确实很方便，多谢解答。
