### ISSUE TITLE
Tabs组件显示左右移动按钮效果后遮住最后一个Tab的问题

### ISSUE THREAD

**Issue by peakandyuri** [ant-design/ant-design#9437]
### Version
3.2.2

### Environment
win10/chrome64

### Reproduction link
[http://peakandyuri.top](http://peakandyuri.top)

### Steps to reproduce
点击左侧菜单option1和option2来回切换

### What is expected?
正常显示最后一个tab标题选项卡

### What is actually happening?
最后一个tab标题选项卡被遮挡住大部分

**Comment by yesmeck** [comment]
Duplicate of #9371
