### ISSUE TITLE
"ReactNode|string"类型似乎不必要，既然ReactNode包括string类型

### ISSUE THREAD

**Issue by hardfist** [ant-design/ant-design#9438]
### Version
3.2.2

### Environment
pass

### Reproduction link
[https://ant.design/components/message/](https://ant.design/components/message/)

### Steps to reproduce
https://ant.design/components/message/

### What is expected?
文档大量的类型是"ReactNode|string",既然ReactNode已经包括string了，为啥还要这样写？

### What is actually happening?
"ReactNode|string" 替换为 ReactNode

**Comment by yesmeck** [comment]
你说的没错，只是为了方面不用 TypeScript 的同学知道。
