### ISSUE TITLE
InputNumber: Issue with entering negative numbers when value prop is bound

### ISSUE THREAD

**Issue by DanHarman** [ant-design/ant-design#9439]
### Version
3.2.2

### Environment
windows 7, chrome 57.0.2987.133 64.0.3282.167

### Reproduction link
[https://codesandbox.io/s/4xj4jpl787](https://codesandbox.io/s/4xj4jpl787)

### Steps to reproduce
Try and type '-0.04' into the inputnumber labelled as bound & broken.

### What is expected?
It should retain the value of '-0' as you type it in, allowing the user to type in '-0.04'.

### What is actually happening?
As soon as the '0' is entered, the minus sign is lost. So if the user keeps typing they incorrectly get '0.04'

---
This only occurs when the value property of the inputnumber is defined. It works fine in the other unbound InputNumber in the reproduction.

**Comment by yutingzhao1991** [comment]
https://github.com/react-component/input-number/issues/91

**Comment by Chevindu** [comment]
> As soon as the '0' is entered, the minus sign is lost. So if the user keeps typing they incorrectly get '0.04'

I can still observe this behavior in InputNumber of version 4.13.0 without using value prop. My implementation is as follows.

```typescript
private getInputNumberField = (id: string, readOnly: boolean) => {
    return <InputNumber type="number" id={id} max={9999.99999999} min={-9999.99999999} precision={8} step={0.00000001} readOnly={readOnly} />
}
```
