### ISSUE TITLE
希望能提供Layout + Menu(含Link) 的例子

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design#9440]
### What problem does this feature solve?
首先非常感谢这么棒的项目和详细的文档，能够让初学者很快上手。但是另外一点不足是整体性的例子似乎不是很多(ant-design-pro太过复杂)。不知道社区工作者们能否提供一个layout + menu(包含link)的例子。这个例子至少可以让初学者很快使用ant-design建立自己的项目。另外这个例子可以让使用者学习到 
1. Layout的使用
2. Menu 和 react-router-dom的结合
3. router component如何将内容render到Layout中
4. history的使用

谢谢

### What does the proposed API look like?
无

**Comment by yesmeck** [comment]
有很多社区项目可以参考 http://scaffold.ant.design/#/

**Comment by jacktang** [comment]
http://scaffold.ant.design/#/ 我有看过，清一色的管理后台的风格(模仿ant-design-pro)。ant-design提供的功能不止这些吧。我们想把ant-design应用到一般网站上却找不到参考

**Comment by yesmeck** [comment]
建议你先自己尝试一下，碰到更具体一点的问题再到 SegmentFault 等社区上寻求帮助。

**Comment by cag2050** [comment]
我写的例子，供参考：https://segmentfault.com/a/1190000014109139

**Comment by cag2050** [comment]
@jacktang 我写的 Layout + Menu(含Link) 例子，供参考：https://segmentfault.com/a/1190000014109139

**Comment by jacktang** [comment]
@cag2050 打开有“权限不足”的错误

**Comment by cag2050** [comment]
@jacktang 我写的 Layout + Menu(含Link) 例子，供参考：http://www.cnblogs.com/cag2050/p/8683161.html
