### ISSUE TITLE
CheckboxGroup

### ISSUE THREAD

**Issue by darianferrer** [ant-design/ant-design#9441]
### What problem does this feature solve?
My use case is that I have a list of questions, each one have a list of possible answers wich aren't exclusive one from another, so I'm modeling this with a list of Checkbox.Group for each question and each answer is an option inside. 

My problem is that I've only one handler for all these groups, but I need additional info because with the current definition I cannot find wich group is used:

`onChange?: (checkedValue: Array<CheckboxValueType>) => void` 

### What does the proposed API look like?
What i propose is adding another parameter to make the handler like this:

`onChange?: (ev: Event, checkedValue: Array<CheckboxValueType>) => void`

This way, if you pass the event I can find wich group is used.

**Comment by yutingzhao1991** [comment]
You can custom onChange handler for distinguish between different events. like:

```
questions.forEach((item) => {
  return <CheckboxGroup onChange={() => {
    // here you can find out find which group is used
    console.log(item);
  }}/>
})
```

Is this your want?

**Comment by darianferrer** [comment]
Thanks for the quick response @yutingzhao1991, after posting the issue I implemented the same solution, with minor changes, so I'm closing this.
