### ISSUE TITLE
Select Component will not update selected value after I modify options

### ISSUE THREAD

**Issue by armslave00** [ant-design/ant-design#9445]
### Version
3.2.2

### Environment
google chrome 64.0.3282.186

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/da63cc3](https://riddle.alibaba-inc.com/riddles/da63cc3)

### Steps to reproduce
Script will auto run. Options changed, but the selected label on Select component not change.

### What is expected?
if the selected Option's label changed, the label on Select component should also change.

### What is actually happening?
only Options updated

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

**Comment by yutingzhao1991** [comment]
more clear reproduction link for this issue: https://codesandbox.io/s/pw43lk52zq

**Comment by yesmeck** [comment]
What scenario do you want to update the Option when using `defaultValue`?

**Comment by armslave00** [comment]
I have a design tool page. User can change the options and the defaultValue. Now I set value prop to solve this problem.
I submit this issue because now I use value prop as defaultValue, I feel it is not what I mean.

**Comment by code-matt** [comment]
I am also running into this problem. My select options depends on two other variables in the app. When the two variables change, I grab data from the backend and update options. Select will still show a label selected for a option that no longer exists :/ It should clear itself out in this case as if nothing is selected.

( or if the label changed for that value, should update. I have not tested this case but guessing it will keep old label )

**Comment by anxiaoyi** [comment]
I meet the same problem !

**Comment by pkrefta** [comment]
Has anybody found a solution to this ? I have to set select's value from outside component. I'm able to set component's `value` through redux state but select displays selected option `value` rather than display selected option `label`

**Comment by paszkowskiDamian** [comment]
I have kind of the same issue. I want to set a default value of the Select if there is only one option, but options are being fetched from a backend. It seems like defaultValue needs to be known during the initial render.

**Comment by ztplz** [comment]
@paszkowskiDamian  Could you provide a online demo for this problem?

**Comment by paszkowskiDamian** [comment]
@ztplz https://codesandbox.io/s/q14q0njyq I hope it will explain more or less what I mean.

**Comment by paszkowskiDamian** [comment]
@ztplz thanks! I've managed to somehow work this around 😉

**Comment by sadmansh** [comment]
@paszkowskiDamian could you explain how? Kind of having the same issue.

**Comment by bernardwiesner** [comment]
I encountered a similar issue, not sure if its related but with me my issue was that I was using an id as the option value, and when I was fetching from backend I was assigning the id as a string inside mounted.

I solved it simply by doing `parseInt(id)` to cast the backend id form string to int and then assign it to the state, then the correct label was shown.

**Comment by rohit-sourcefuse** [comment]
Struggling, with the same issue with Antd 4.9.4 and not getting any solution for it. Any help?
When we change select - options programmatically, it's always, so selected old value, which not even present in the current options list.

**Comment by masonlouchart** [comment]
Same issue for me. I do call an API, it takes 1-2 sec to get the result and re-render the select. Options list updated but selected value not, and "select event" not dispatched.

**Comment by AhmedBHameed** [comment]
Same here with localization.

**Comment by lkenny97** [comment]
I had a similar problem, I was trying to get address input from the user. I had a city Select which on selected was filling in district options for a district Select. I was setting the value of Selects using value prop but since my Selects were in a Form.Item field I had problems. Upon reading the documentation this was my solution:

```
const [form] = Form.useForm()

const getDistricts = (city) => {
    form.setFieldsValue({district: null})
}
...
<Form form={form} onFinish={finishProfile}>
    <Form.Item name="city">
        <Select onSelect={getDistricts}>
            ...
        </Select>
    </Form.Item>
    <Form.Item name="district">
        <Select>
            ...
        </Select>
    </Form.Item>
</Form>
```

The idea is to use useForm hook and use the `setFieldsValue` function that Ant Design provides.

**Comment by VhugoJc** [comment]
@lkenny97 thank you. It was the answer for the problem with update selector value.

**Comment by diegolego** [comment]
The solution I found:
I did not use the form tag in my use case.
On your <Select /> tag, if you have the "defaultValue" prop, change ir for the "value" prop and manage state for that value. Once the state changes, the selected value should update too.

`<Select
              value={selectedQandAFilter}
              onChange={(val) => changeSelectedFilterAndSetQuestion(val)}
            >`

**Comment by Enigama** [comment]
@diegolego thanks, it works for me

**Comment by NgRuiYong** [comment]
The solution for me was to assign the the value to the key of the Select component so that whenever the value updates, it forces react to re render the component.

`<Select key={myValue} value={myValue} onChange={(e) => setMyValue(e}> .....</Select>`

**Comment by adamvu84** [comment]
> The solution for me was to assign the the value to the key of the Select component so that whenever the value updates, it forces react to re render the component.
> 
> `<Select key={myValue} value={myValue} onChange={(e) => setMyValue(e}> .....</Select>`

Thanks, you save my life.

**Comment by zeelmodi-simform** [comment]
> The solution for me was to assign the the value to the key of the Select component so that whenever the value updates, it forces react to re render the component.
> 
> `<Select key={myValue} value={myValue} onChange={(e) => setMyValue(e}> .....</Select>`

@NgRuiYong 
This was really helpful, I had an issue where on initial render for a flash it was showing value in the select instead of label but thanks to you adding key resolved my issue!
