### ISSUE TITLE
Optimize the version component to reduce the module size

### ISSUE THREAD

**Issue by HQidea** [ant-design/ant-design#9446]
### What problem does this feature solve?
Since [this component](https://github.com/ant-design/ant-design/blob/master/components/version/index.tsx) only export the version info, but it leads to extra `7.06 KB` code of `package.json`.

### What does the proposed API look like?
I suggest either use a constant file which is auto generated at build time to provide the version info or reduce the size of `package.json`.

**Comment by afc163** [comment]
We can try tree shaking when build dist files.

**Comment by yutingzhao1991** [comment]
@afc163 tree shaking seems can't reduce the size of package.json.

**Comment by afc163** [comment]
webpack@4.x support it. https://github.com/webpack/webpack/issues/5578

**Comment by yesmeck** [comment]
Waiting for the webpack 4 migration guide https://github.com/webpack/webpack.js.org/issues/1706
