### ISSUE TITLE
Row gutter is not working

### ISSUE THREAD

**Issue by mdsantosdev** [ant-design/ant-design#9447]
### Version
3.2.2

### Environment
Ubuntu Xenial, Chrome Version 64.0.3282.140 (Official Build) (64-bit), React 16.2.0, Antd 3.2.2

### Reproduction link
[https://codepen.io/anon/pen/ddwRxw?editors=001](https://codepen.io/anon/pen/ddwRxw?editors=001)

### Steps to reproduce
Just add a Row with any gutter bigger than 0 and a few cols

### What is expected?
A gap between every Col.

### What is actually happening?
Cols are sticking together.

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/ddwzZx?editors=0010

**Comment by yuanzx** [comment]
@afc163 How do you solved the issue? I met it too and I updated to the latest version(3.30)

**Comment by mdsantosdev** [comment]
Just added a div inside those Col.

2018-03-13 6:09 GMT-03:00 Murphy Yuan <notifications@github.com>:

**Comment by vjustov** [comment]
For the sake of prosperity, the reason it was not working for me is that i was using a custom component and was not passing down the `style` prop

```jsx
 <Row gutter={16}>
    this.state.things.map((thing, i) => (
      <SortableThing key={thing.id} thing={thing} index={i} moveCard={this.reorderThings} />
    ))
 </Row>
```

and in SortableThings i had:
```jsx
render(){
   return (
      <Col span={8} I NEEDED THIS -->> style={ style } <<--- ref={instance => {
        const node = findDOMNode(instance);
        connectDragSource(node);
        connectDropTarget(node);
      }}>
        <Card
          hoverable
          cover={<img alt="example" src={thing.image} />}
          actions={[<Icon type="setting" />, <Icon type="edit" />, <Icon type="ellipsis" />]}
        >
          <Card.Meta
            title={thing.id}
            description="www.instagram.com"
          />
        </Card>
      </Col>
    )
  }
```

**Comment by kidchenko** [comment]
I had the same problem, the solution above worked, just pass style to `Col` inside your component, thanks :)

**Comment by kabike** [comment]
> I had the same problem, the solution above worked, just pass style to `Col` inside your component, thanks :)

Can you tell me how to pass style?

**Comment by zl95826** [comment]
If you want to show the gutter, just avoid adding the style property to the Col component.

**Comment by brhanegiday** [comment]
I think Adding `div` inside the `Col` will solve the issue. This works for me.

**Comment by ItsTarik** [comment]
> If you want to show the gutter, just avoid adding the style property to the Col component.

It was about this thanks @zl95826 !
This was a very fragile design...

**Comment by Howard-Hsiao** [comment]
> I think Adding `div` inside the `Col` will solve the issue. This works for me.

I encountered the same issue, but using a `div` element to wrap my content did not solve the problem for me. Instead, I tried `p` and it worked. 

If you are also facing this issue, experimenting with different HTML tags to wrap your content may be a good idea.

**Comment by matzeeable** [comment]
Also had issues with the `<Row gutter` property. None of the suggested solutions worked for me. In my case, I am not using the `reset.css` file of Antd as I am working within WordPress, so the following rules are missing:

https://github.com/ant-design/ant-design/blob/e9db1071d64863223c2529add349e7140d5a1ee9/components/style/reset.css#L11-L15

My fix is to add a custom CSS:

```
.antd-col {
    box-sizing: border-box;
}
```

**Comment by AzPrime44** [comment]
to make it clear , you shouldn't use `style` or `className` , if you have a style (style proprety or by using a class), you should create a `div` just after the `<Col>`  tag then put your reste of the code inside the div
` <Row
                    gutter={[24,24]}
                    justify="center"
                >
                    {options.map((option, index) => (
                        <Col
                            key={index}
                            xs={{ span: 24 }}
                            md={{ span: 12 }}
                        >
                            <div className={`${option.className}`}>
                           </div>
                          </Col>
    </Row>`
