### ISSUE TITLE
Input组件，className在suffix属性是否存在时生成位置不一致

### ISSUE THREAD

**Issue by lizux** [ant-design/ant-design#9450]
### Version
3.2.2

### Environment
Mac Chrome

### Reproduction link
[https://codesandbox.io/s/m35967v52j](https://codesandbox.io/s/m35967v52j)

### Steps to reproduce
<Input className="number" placeholder="请输入" suffix={<Icon type="down"/>} />

### What is expected?
\<input class="ant-input number" placeholder="请输入" type="text"  />

### What is actually happening?
\<span class="number ant-input-affix-wrapper">
    \<input value="" placeholder="请输入" class="ant-input" type="text" />
\</span>

**Comment by yutingzhao1991** [comment]
It's expected, className should add to the outermost dom.
