### ISSUE TITLE
表单中设置select initialValue 异常

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design#9452]
### Version
3.2.2

### Environment
window7, chrome

### Reproduction link
[https://codesandbox.io/s/jnw46698m3](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
```
<Form layout="horizontal">
          <Form.Item label="利率" {...formItemLayout}>
            {getFieldDecorator('interest_rate_id', {
              initialValue: data ? data.interest_rate_id : interestList[0].id,
            })(
              <Select  optionLabelProp="textValue">
                {
                  interestList.map(
                    item => <Select.Option key={item.id} textValue={item.name}>
                      <Row>
                        <Col xs={14}>{item.name}</Col>
                        <Col xs={10}>{item.type == 1 ? '按日结息' : '按月结息'} {item.rate}</Col>
                      </Row>
                    </Select.Option>)
                }
              </Select>
            )}
          </Form.Item>
</Form>
```

### What is expected?
Select initialValue 会取我设置的 textValue的值

### What is actually happening?
显示key的值

---
我对Select下拉菜单进行了自定义样式,  并设置了optionLabelProp="textValue"  , 但 initialValue 并没有取 textValue ,   
但是我要是下拉选择具体的哪一个,  则会取 textValue 来显示

**Comment by xoptimal** [comment]
发现, value={item.id} 就可以解决问题了  0.0  也就是key , value 都要写

**Comment by jzoe** [comment]
![image](https://user-images.githubusercontent.com/11612990/40032209-bcae6d56-5825-11e8-9841-b63503098bef.png)

按照文档中的说法，这应该算是bug吧！文档应该改一下才行。
