### ISSUE TITLE
antd.min.js 库太大了，有办法减小吗

### ISSUE THREAD

**Issue by DaZiYuan** [ant-design/ant-design#9454]
### What problem does this feature solve?
antd.min.js 文件接近1M
bootstrap.min.js 只有48k

### What does the proposed API look like?
antd.min.js 小到100k以内

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
