### ISSUE TITLE
Select回填内容支持自定义

### ISSUE THREAD

**Issue by liuchaofeng1230** [ant-design/ant-design#9455]
### What problem does this feature solve?
Select选中Option后，value里显示的内容既不想要Option内的子元素，也不想要用value，而是希望能自定义

![image](https://user-images.githubusercontent.com/6177210/36792103-815de2b8-1cd4-11e8-8652-166343e88026.png)

**Comment by afc163** [comment]
optionLabelProp

**Comment by liuchaofeng1230** [comment]
optionLabelProp 配置了后显示的是value，但是我想要显示name

**Comment by liuchaofeng1230** [comment]
搞定了。thx。看了源码
```
export function getPropValue(child, prop) {
  if (prop === 'value') {
    return getValuePropValue(child);
  }
  return child.props[prop];
}
```

把Option的child，加上一个自定义的prop，然后Select的optionLabelProp设为那个自定义的prop。

**Comment by SpecialSupportSection** [comment]
Select : optionLabelProp="name"
<Option key={k.id} name={k.name} value={String(k.id)}>
It's easier to use.

**Comment by MTTTM** [comment]
may i  no use options? i no like it.

**Comment by mqliutie** [comment]
如果服务端返回的格式带HTML，我要过滤掉标签，怎么办呢？现在好像都是只读某个属性吧？

**Comment by mqliutie** [comment]
> 如果服务端返回的格式带HTML，我要过滤掉标签，怎么办呢？现在好像都是只读某个属性吧？

看样只能从元数据入手， 自己添加一个字段， 保存解析后的数据了

**Comment by yoyo837** [comment]
> > 如果服务端返回的格式带HTML，我要过滤掉标签，怎么办呢？现在好像都是只读某个属性吧？
> 
> 看样只能从元数据入手， 自己添加一个字段， 保存解析后的数据了

js 解析html行dom api上取数据
