### ISSUE TITLE
按需加载按文档配置后不成功

### ISSUE THREAD

**Issue by DaZiYuan** [ant-design/ant-design#9456]
### Version
3.2.2

### Environment
react-ts antDesign

### Reproduction link
[https://github.com/DaZiYuan/tampermonkey-react](https://github.com/DaZiYuan/tampermonkey-react)

### Steps to reproduce
1. 下载源码https://github.com/DaZiYuan/tampermonkey-react  
2.yarn install  
3.yarn build  
4.bulid/index.js 有1829kb  

### What is expected?
不引用全部js库

### What is actually happening?
导入了全部js库，文件太大

---
https://github.com/ant-design/babel-plugin-import  
我是按照这个文档配置的，但是我本身才接触js几天，对配置不熟，可能是我配置问题，可以帮忙看一下吗 谢谢

**Comment by yesmeck** [comment]
https://github.com/DaZiYuan/tampermonkey-react/blob/master/src/App.tsx#L3

这行不需要，另外可以自己用 https://github.com/chrisbateman/webpack-visualizer 分析下。
