### ISSUE TITLE
按需加载配置后不生效

### ISSUE THREAD

**Issue by DaZiYuan** [ant-design/ant-design#9460]
### Version
3.2.2

### Environment
react-ts 、antd

### Reproduction link
[https://github.com/DaZiYuan/tampermonkey-react](https://github.com/DaZiYuan/tampermonkey-react)

### Steps to reproduce
1.clone代码
2.yarn analyze
3.查看 build/index.js 很小只有200多k
4.分别注释App.tsx,Config.tsx的相关手动引用代码 
//import Button from 'antd/lib/button';
//import Col from 'antd/lib/col';
///import Row from 'antd/lib/row'; 
修改为  
// import { Row, Col, Button } from 'antd';
5.yarn analyze
6.查看 build/index.js 有1.2M 。 report.html可以看出确实是全引用

### What is expected?
期望 按需加载正常工作

### What is actually happening?
包太大 

---
已经按文档，把配置写入 .babelrc ，但是任然不工作

**Comment by yesmeck** [comment]
TypeScript 请参考 https://ant.design/docs/react/use-in-typescript-cn

不要重复提 issue。

**Comment by DaZiYuan** [comment]
终于对了，感谢
