### ISSUE TITLE
Form Component doesn't work with React's new Context API

### ISSUE THREAD

**Issue by XuejiSun** [ant-design/ant-design#9462]
### Version
3.2.2

### Environment
win OS, Chrome Version 64.0.3282.167, React 16.3.0-alpha.0

### Reproduction link
[https://codesandbox.io/s/32824r1jpp](https://codesandbox.io/s/32824r1jpp)

### Steps to reproduce
1. Put the SubComponent inside GlobalStoreProvider and GlobalStoreConsumer from code.
2. From UI, tap"App Name" menu and then tap "CREAT NEW" to bring out one Modal, the Modal will take much time to be rendered.
3. After the Modal is rendered, the input can't work as normal

### What is expected?
Expect the behavior is same as SubComponent without inside GlobalStoreProvider and GlobalStoreConsumer(without using new Context API). That is: the Modal can be rendered correctly in short time and the input inside the Modal or Form can accept input as normal.

### What is actually happening?
When the modal is triggered to be rendered, the error is popped out: "Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.". Then after that, the input doesn't work and also can't make the modal invisible. It seems antd's Form component is in abnormal state.

---
What's antd's plan to support React new Context API? If there is plan and what is the ETA when the support is available?

<!-- generated by ant-design-issue-helper. DO N

**Comment by yesmeck** [comment]
```javascript
render() {
  const CreateAppInfo = Form.create()(AddAppForm);
}
```

Don't create component in the render.

We will migrate to the new context API once React removed the old one.

**Comment by sunderhus** [comment]
Is this still on track? I'm desperately trying to use the `getFieldDecorator` with a Consumer of my `i18n` context API, but it simply doesn't work... seems like the `getFieldDecorator` simply ignores any changes to it after the first declaration of it's options
