### ISSUE TITLE
website error :the "Form" content has confusioned two funciton

### ISSUE THREAD

**Issue by microchang** [ant-design/ant-design#9465]
### Version
3.2.2

### Environment
macos10.13.3 chrome64.0.3282.186

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-normal-login](https://ant.design/components/form-cn/#components-form-demo-normal-login)

### Steps to reproduce
https://ant.design/components/form-cn/#components-form-demo-normal-login

the function "checkPassword" and  "checkConfirm" should be exchanged;

### What is expected?
work as expected

### What is actually happening?
console will show err :"Maximum call stack size exceeded"

**Comment by yutingzhao1991** [comment]
@microchang I Can reproduce this issue. Can you reproduce it on https://codesandbox.io/s/movorv42zy?
