### ISSUE TITLE
使用table排序时，先选择了table排序条件，然后清除当前filter排序内容，table排序先前选中的内容样式还是选中状态（When I use table sort in one component, reset the filters can't change the style of table sort , even though the table sort condition didn't work）

### ISSUE THREAD

**Issue by talktohebe** [ant-design/ant-design#9469]
### Version
3.2.2

### Environment
浏览器：Google Chrome       版本： 64.0.3282.186（正式版本） （32 位）

### Reproduction link
[https://codepen.io/pen/?&editors=001  (备注：使用ant-design->table->可控的筛选和排序例子)](https://codepen.io/pen/?&editors=001  (备注：使用ant-design->table->可控的筛选和排序例子))

### Steps to reproduce
使用ant-design->table->“可控的筛选和排序”例子，选中tablet排序条件Age，排序的小三角符号变成蓝色，点击“clear filters”按钮，排序的小三角符号依然是蓝色。（Use the example ‘Reset filters and sorters’ in antd Table，first,  I choose table sort condition 'Age', second, I click the btn 'clear filters', the sort condition is turn to 'null', but the style doesn't change.）

### What is expected?
清除table 的排序条件时，小三角符号变成未选中的样式（when I clear the sort condition, the triangle icon's style of condition turn to unchecked style ）

### What is actually happening?
清除table 的排序条件时，小三角符号依然是选中状态的样式（when I clear the sort condition, the triangle icon's style of condition didn't change style ）

---
当table上方有多个搜索框，table上还有排序时，当改变搜索框的查询条件时，table内容改变，table表单上的排序应该重置，虽然已经重置，但是样式依然是选中样式。

**Comment by afc163** [comment]
Your codepen is empty.

**Comment by vipcxj** [comment]
[ant-design](https://ant.design/components/table-cn/#components-table-demo-reset-filter)
He means this link.

**Comment by afc163** [comment]
`clear filter` means to clear filter state not sorter state, which is the active triangle represent.
