### ISSUE TITLE
 DatePicker 日期选择框，在手动编辑时间的时候，日期会变成 2016-01-01

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#947]
**问题描述**

日期选择框 DatePicker ，可以选择时间的情况下，手动编辑时间，日期会变成 2016-01-01

**发生环境**

- antd 版本：0.11.3 +
- 操作系统及版本： OS X EI Capitan 
- 浏览器及版本：Chrome  Version 47.0.2526.111 (64-bit)
- 在线演示地址： 无

**重现步骤**

- 选择一个日期

  ![](https://os.alipayobjects.com/rmsportal/rWNOaUUzEcZVFfo.png)

- 手动编辑时间
 
  ![](https://os.alipayobjects.com/rmsportal/pTquekQXrImuycU.png)

- 这时候左边的日期就会变到 2016-01-01

![](https://os.alipayobjects.com/rmsportal/VQcVNAxGxmdgkXJ.png)

**线上重现演示**

http://ant.design/components/date-picker/

**Comment by benjycui** [comment]
See: https://github.com/react-component/calendar/pull/101

**Comment by yiminghe** [comment]
重装
