### ISSUE TITLE
Array in Form cannot be initialized by key in format of "arrayA[index].column"

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#9471]
### Version
3.2.2

### Environment
Mac, Chrome, 16.2

### Reproduction link
[https://codesandbox.io/s/zn6x15vnl4](https://codesandbox.io/s/zn6x15vnl4)

### Steps to reproduce
Array field in Form could be initialized by the following code which works in Ver 2.x.x of AntD
const formKey = `list[${index}].id`;
form.getFieldDecorator(formKey, { initialValue: index });

When render columns in table:
let key = `list[${i}].column`;
{getFieldDecorator(key, {
            initialValue: ""
          })(<Input />)}

But in Ver 3.x.x, the formKey in format of "arrayA[index].column" will result an Object with key "0".

### What is expected?
As same behavior as Ver 2.x.x, as demonstrated in the following sandbox:

https://codesandbox.io/s/rwp84r6x4n

### What is actually happening?
not working

**Comment by benjycui** [comment]
You demo doesn't work 

![image](https://user-images.githubusercontent.com/3580607/36880787-80a8147e-1e05-11e8-8855-58838f820a75.png)

**Comment by afc163** [comment]
@benjycui It works.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/507615/36880861-f70e894a-1e05-11e8-88f8-946e7f733d76.png">

**Comment by benjycui** [comment]
As the warning say, you cannot use `list` and `list[index]` at the same time.

```bash
Warning: One field name cannot be part of another, e.g. `a` and `a.b`.
```
