### ISSUE TITLE
When using isLoading property on <Button> comp, React returns a warning. See bellow.

### ISSUE THREAD

**Issue by isaklafleur** [ant-design/ant-design#9473]
### Version
3.2.2

### Environment
React 16

### Reproduction link
[https://github.com/isaklafleur/amdm-frontend-react/blob/master/src/components/TreeMenu.js](https://github.com/isaklafleur/amdm-frontend-react/blob/master/src/components/TreeMenu.js)

### Steps to reproduce
<Button type="primary" icon="save" iconLoading={props.isSubmitting} loading={props.isSubmitting} disabled={props.checkable ? undefined : true} onClick={props.onSubmit}>Save</Button>

The code works, but React gives an warning, that is does not recognize iconLoading prop on Button.

### What is expected?
No warning

### What is actually happening?
Warning: React does not recognize the `iconLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by Button)
    in Button (at TreeMenu.js:11)

**Comment by afc163** [comment]
There is no `iconLoading` prop for Button.
