### ISSUE TITLE
table组件 固定表头功能 表头出现滚动条 表身在高度小于最大高度时也出现滚动条

### ISSUE THREAD

**Issue by caiyihua** [ant-design/ant-design#9483]
### Version
3.2.2

### Environment
win7  firefox

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-header](https://ant.design/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce
在设置table组件 scroll={{ y: 240 }} 高度时候 表头会出现滚动条 官网上就可以看到

### What is expected?
在设置scroll={{ y: 240 }} 时候 表头不出现滚动条  在内容小于y的时候 表身不出现滚动条 

### What is actually happening?
在设置scroll={{ y: 240 }} 时候 表头出现滚动条  在内容小于y的时候 表身出现滚动条  影响美观

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5274#issuecomment-286005745

**Comment by zlab** [comment]
https://codepen.io/anon/pen/xaLmmx?editors=0010

**Comment by zlab** [comment]
列都对不齐了

![image](https://user-images.githubusercontent.com/2288630/45131845-4dfc8780-b1c1-11e8-97a0-e9ac5f48a442.png)

**Comment by caiyihua** [comment]
这个官方说了 为了避免bug出现 固定出现2个滚动条 如果没有横向滚动的话 把他去掉没事 @zlab

**Comment by gdmec07150725** [comment]
@caiyihua 那请问怎么去掉呢

**Comment by sugar654321** [comment]
why the table scroll y must needs number?If the table height is not sure the same, I think this API is not good for use.
