### ISSUE TITLE
Autocomplete onSelect second param (option) does not return the Option instance children correctly

### ISSUE THREAD

**Issue by vydimitrov** [ant-design/ant-design#9489]
### Version
3.2.2

### Environment
macOs Heigh Sierra 10.13.1, Chrome 64

### Reproduction link
[https://codesandbox.io/s/74ywrqlvm6](https://codesandbox.io/s/74ywrqlvm6)

### Steps to reproduce
Add an Option which has as a child some React component. Go select the option with the component and console log the second parameter, which is option, within the onSelect method. It return an instance of Option which has props - "value" and "children" and both of them have the same value - the value string.

### What is expected?
To return reference to its children ( the component you pass as a children to Option)

### What is actually happening?
It return the value string. 

---
Before version 3, onSelect second param - option, used to return an instance of Option with all additional props that you pass to the Option component. It seems this is not the case any more and it only returns "value" and "children" props. So now there is no option to pass some additional param and get them in the onSelect. At least if we get correctly the children when we can have these additional props passed to them.

**Comment by vydimitrov** [comment]
The bug happens only when an Option in rendered inside OptGroup. If you render just Option then works as expected.

**Comment by dorkblue** [comment]
Bug appears on Select component as well.

**Comment by vydimitrov** [comment]
Because Options is using Select under the hood.
