### ISSUE TITLE
'npm start'  stop at 'building modules (1721/1722 modules)'

### ISSUE THREAD

**Issue by Sjian1988** [ant-design/ant-design#9493]
### Version
3.2.3

### Environment
OS:centos 7  N-Version:node 8.9

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
$ git clone git@github.com:ant-design/ant-design.git
$ npm install
$ npm start

### What is expected?
start server sucess

### What is actually happening?
stop at build modules

**Comment by Sjian1988** [comment]
log:==============================
[root@localhost ant-design-master]# cnpm install
⠸ [109/124] Installing stylelint@^8.0.0platform unsupported babel-cli@6.26.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(linux)
⠋ [110/124] Installing stylelint-config-standard@^18.0.0[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 124 packages
✔ Linked 1300 latest versions

     *** Thank you for using react-slick! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/react-slick/donate

                    ***

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
✔ Run 6 scripts
antd-tools run guard
peerDependencies link ajv@4.11.8 in /opt/ant-design-master/node_modules/_ajv-keywords@1.5.1@ajv-keywords unmet with /opt/ant-design-master/node_modules/ajv(6.2.0)
peerDependencies WARNING bisheng@0.28.2 › sass-loader@^6.0.6 requires a peer of node-sass@^4.0.0 but none was installed
peerDependencies WARNING bisheng@0.28.2 › url-loader@~0.5.8 requires a peer of file-loader@* but none was installed
deprecate babel-preset-es2015@^6.18.0 ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
deprecate antd-tools@5.1.1 › github@^13.1.0 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
deprecate antd-tools@5.1.1 › gulp@3.9.1 › gulp-util@^3.0.0 gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › graceful-fs@^3.0.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-stream@3.1.18 › minimatch@^2.0.1 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › minimatch@~0.2.11 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › glob@3.1.21 › graceful-fs@~1.2.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate enzyme@3.3.0 › rst-selector-parser@2.2.3 › nearley@2.11.1 › nomnom@~1.6.2 Package no longer supported. Contact support@npmjs.com for more info.
Recently updated (since 2018-02-23): 40 packages (detail see file /opt/ant-design-master/node_modules/.recently_updates.txt)
  Today:
    → ansi-styles@^3.2.0(3.2.1) (01:40:00)
    → babel-eslint@8.2.2 › @babel/code-frame@7.0.0-beta.40 › @babel/highlight@7.0.0-beta.40 › chalk@2.3.1 › supports-color@^5.2.0(5.3.0) (01:07:59)
    → antd-tools@5.1.1 › gulp-typescript@3.2.4 › vinyl-fs@2.4.4 › duplexify@^3.2.0(3.5.4) (05:34:47)
    → rc-scroll-anim@^2.2.1(2.3.0) (01:38:20)
    → bisheng-plugin-antd@0.16.3 › antd@latest(3.2.3) (04:38:02)
✔ All packages installed (1689 packages installed from npm registry, used 2m, speed 194.07kB/s, json 1424(21.72MB), tarball 0B)
[root@localhost ant-design-master]# npm start

> antd@3.2.2 start /opt/ant-design-master
> rimraf _site && node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js

📦  building modules (1721/1722 modules)

**Comment by Sjian1988** [comment]
log:==============================
[root@localhost ant-design-master]# cnpm install
⠸ [109/124] Installing stylelint@^8.0.0platform unsupported babel-cli@6.26.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(linux)
⠋ [110/124] Installing stylelint-config-standard@^18.0.0[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 124 packages
✔ Linked 1300 latest versions

     *** Thank you for using react-slick! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/react-slick/donate

                    ***

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
✔ Run 6 scripts
antd-tools run guard
peerDependencies link ajv@4.11.8 in /opt/ant-design-master/node_modules/_ajv-keywords@1.5.1@ajv-keywords unmet with /opt/ant-design-master/node_modules/ajv(6.2.0)
peerDependencies WARNING bisheng@0.28.2 › sass-loader@^6.0.6 requires a peer of node-sass@^4.0.0 but none was installed
peerDependencies WARNING bisheng@0.28.2 › url-loader@~0.5.8 requires a peer of file-loader@* but none was installed
deprecate babel-preset-es2015@^6.18.0 ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
deprecate antd-tools@5.1.1 › github@^13.1.0 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
deprecate antd-tools@5.1.1 › gulp@3.9.1 › gulp-util@^3.0.0 gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › graceful-fs@^3.0.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-stream@3.1.18 › minimatch@^2.0.1 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › minimatch@~0.2.11 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate antd-tools@5.1.1 › gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › glob@3.1.21 › graceful-fs@~1.2.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate enzyme@3.3.0 › rst-selector-parser@2.2.3 › nearley@2.11.1 › nomnom@~1.6.2 Package no longer supported. Contact support@npmjs.com for more info.
Recently updated (since 2018-02-23): 40 packages (detail see file /opt/ant-design-master/node_modules/.recently_updates.txt)
  Today:
    → ansi-styles@^3.2.0(3.2.1) (01:40:00)
    → babel-eslint@8.2.2 › @babel/code-frame@7.0.0-beta.40 › @babel/highlight@7.0.0-beta.40 › chalk@2.3.1 › supports-color@^5.2.0(5.3.0) (01:07:59)
    → antd-tools@5.1.1 › gulp-typescript@3.2.4 › vinyl-fs@2.4.4 › duplexify@^3.2.0(3.5.4) (05:34:47)
    → rc-scroll-anim@^2.2.1(2.3.0) (01:38:20)
    → bisheng-plugin-antd@0.16.3 › antd@latest(3.2.3) (04:38:02)
✔ All packages installed (1689 packages installed from npm registry, used 2m, speed 194.07kB/s, json 1424(21.72MB), tarball 0B)
[root@localhost ant-design-master]# npm start

> antd@3.2.2 start /opt/ant-design-master
> rimraf _site && node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js

📦  building modules (1721/1722 modules)

**Comment by yesmeck** [comment]
Can not help you if you can not provide more info.

**Comment by danielbiloglav** [comment]
It's related to a new dependency being added in react-slick.
More info here: https://github.com/akiran/react-slick/issues/1003

**Comment by jrossi227** [comment]
I am also experiencing this issue in container environments. This will be fixed if you update your react-slick dependency to 0.19

**Comment by yesmeck** [comment]
Closing since it's not an issue of antd.
