### ISSUE TITLE
Cascader Search is Case-sensitive

### ISSUE THREAD

**Issue by Xoce51** [ant-design/ant-design#9494]
### What problem does this feature solve?
Almost everything is in the title :) When we use the showSearch option for the casacader the searched text is case sensitive to filter results. I think it would be nice to have an option to choose if we want to use case sensitive option or not. Thank you

### What does the proposed API look like?
An exemple would be:
```
<Cascader
      options={options}
      onChange={onChange}
      placeholder="Please select"
      showSearch={{caseSensitive: false}}
    />
```

**Comment by yesmeck** [comment]
We can add it as default behavior like we already do in Select.

Tagging as good first issue.

**Comment by Xoce51** [comment]
It would be nice, I'll take a look this week end.

**Comment by vzan2012** [comment]
I tried with the updated code (in git) not working, still works the case sensitive.

Pls provide what is the cause for it?

**Comment by steven-p-walsh** [comment]
This page is the first result if you search google for this issue.  So here's a quick tip on how to use this:

For the property, you pass in an object with the functions you want to customize:.

So the property might look like this:

showSearch={ { 
filter: <filter function>,  
render: <render function>
} }

all of these functions are optional.  For more details here is the relative line in the source code:
https://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L38
