### ISSUE TITLE
A filter text input below the ColumnTitle in Table

### ISSUE THREAD

**Issue by SimpleFrontend** [ant-design/ant-design#9495]
### What problem does this feature solve?
Currently, there is a filterDropdown that allows developers to build a custom filter panel, so it takes the user one click per column to filter. It works fine if user only uses the filter functionality on one column, but it becomes annoying when the user wants to filter multiple columns. It would be very handy if there is a filterTextInput below the column title that allows users to type directly. 

### What does the proposed API look like?
Basically it's like filterDropdown without the filterDropdownVisible and filterIcon. The text input width should be 100% of the column width, below the column title (so the sorting icon is still next to the column name). It might be a good idea to make filterTextInput and filterDropdown exclusive to each other. Otherwise user would be confused/annoyed.

```jsx
const columns = [{
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      filterTextInput: (
          <Input
            ref={ele => this.searchInput = ele}
            placeholder="Search name"
            value={this.state.searchText}
            onChange={this.onInputChange}
            onPressEnter={this.onSearch}
          />
      ),
    }, ...}]
return  <Table columns={columns} dataSource={this.state.data} />
```

**Comment by yesmeck** [comment]
You can achieve it by passing ReactNode to the column title:

```javascript
const columns = [
  {
    title: (
       <div>Name</div>
       <Input />
    );
  }
]
```

**Comment by karahan6** [comment]
``{
            title: (
                <div style={{ textAlign: 'center' }}>
                    <div>Name</div>
                    <hr />
                    <Input placeholder='Search' ref={user => { this.user = user }}
                        onKeyUp={event => this.filterColumn('user', event.target.value)} />
                </div>
            ),
            dataIndex: 'adi',
            key: 'adi',
            sorter: true,`

**Comment by karahan6** [comment]
@yesmeck, I try your suggestion. But in this case, sorter of column go below of 'title' which means down below search as seen in image. So, in the circumstances, we may need to customize sorter button and functionality too. 
I was using another table library which provide separate filter row property but to have a stable design, I want to use ant design table. Your library provide a rich set of components. But in table, filter row is an important need. 
```
{
            title: (
                <div style={{ textAlign: 'center' }}>
                    <div>Name</div>
                    <hr />
                    <Input placeholder='Search'  />
                </div>
            ),
            dataIndex: 'user',
            key: 'user',
            sorter: true
}
```

![custom_search](https://user-images.githubusercontent.com/11015702/38800555-469a3026-4170-11e8-82f1-c79bbd2d8ebd.PNG)

**Comment by yesmeck** [comment]
@karahan6 You can add the search input as a row.

**Comment by balabukha** [comment]
so is it possible to use  filter functionality in several columns?

**Comment by schechtere** [comment]
Something like https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-server-side-data

**Comment by AdrielLimanthie** [comment]
I found adding the filter input as a row has a problem. 

If I specify 10 rows per page, only 9 rows with actual data will be shown because the first row is a filter row. I can kinda fix it by specifying 11 rows instead, but this complicates things & make the code confusing.

I suggest adding a prop to pass special row that is not included in pagination.

**Comment by yoyo837** [comment]
@AdrielLimanthie 
I think your idea is similar to the #5710's feature requirements, because in the case of pagination, no extra rows are allowed in the table. 

See https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L451

**Comment by yoyo837** [comment]
Right Now, in the table `componentDidUpdate` I use the DOM API (appendChild) to implement it.

![image](https://user-images.githubusercontent.com/6134547/68280238-1aacd580-00b0-11ea-83eb-98f879f829ee.png)

**Comment by freewind** [comment]
I think this issue should be re-opened, since it still has no proper solution or workaround

**Comment by bastek338** [comment]
Any news about this thread?

**Comment by vitalijalbu** [comment]
Hi all, I'd need to create such a filter row in table, how can I?
Meaning to show table data need first submit the form with params.

![Screenshot 2023-05-16 alle 15 02 03](https://github.com/ant-design/ant-design/assets/40239902/09f3dedd-f541-4e26-b39d-7295652e75a0)

**Comment by MadiAbhilash** [comment]
I also need same functionality how you managed it?

**Comment by MadiAbhilash** [comment]
> Hi all, I'd need to create such a filter row in table, how can I? Meaning to show table data need first submit the form with params.
> 
> ![Screenshot 2023-05-16 alle 15 02 03](https://private-user-images.githubusercontent.com/40239902/238666074-09f3dedd-f541-4e26-b39d-7295652e75a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDQ5MTcsIm5iZiI6MTcwMTc0NDYxNywicGF0aCI6Ii80MDIzOTkwMi8yMzg2NjYwNzQtMDlmM2RlZGQtZjU0MS00ZTI2LWIzOWQtNzI5NTY1MmU3NWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAyNTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMzI4ZWY1OTBhYzg1MTQ0YzE4ZjQ3MTY2MTE3OGE2ZjA2MzY1ZjUzN2I5ZDFlNmQ4YTQ4NzZlYWY3MDcwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QFIsczdGmhKPAtwiKrQhOWqm9Vzs21Y7oChOAGYE4A)

I also need same functionality how you resolved it?

![image](https://github.com/ant-design/ant-design/assets/136574224/7c7c1e9e-371e-4bf4-95b9-794b10c4b459)

**Comment by vitalijalbu** [comment]
> > Hi all, I'd need to create such a filter row in table, how can I? Meaning to show table data need first submit the form with params.
> 
> > 
> 
> > ![Screenshot 2023-05-16 alle 15 02 03](https://private-user-images.githubusercontent.com/40239902/238666074-09f3dedd-f541-4e26-b39d-7295652e75a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDQ5MTcsIm5iZiI6MTcwMTc0NDYxNywicGF0aCI6Ii80MDIzOTkwMi8yMzg2NjYwNzQtMDlmM2RlZGQtZjU0MS00ZTI2LWIzOWQtNzI5NTY1MmU3NWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAyNTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMzI4ZWY1OTBhYzg1MTQ0YzE4ZjQ3MTY2MTE3OGE2ZjA2MzY1ZjUzN2I5ZDFlNmQ4YTQ4NzZlYWY3MDcwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QFIsczdGmhKPAtwiKrQhOWqm9Vzs21Y7oChOAGYE4A)
> 
> 
> 
> I also need same functionality how you resolved it?
> 
> 
> 
> ![image](https://github.com/ant-design/ant-design/assets/136574224/7c7c1e9e-371e-4bf4-95b9-794b10c4b459)
> 
> 

Email me, I can share the code.
