### ISSUE TITLE
Calendar组件选择非当前月的日期 onPanelChange 不能触发的问题

### ISSUE THREAD

**Issue by jinyaqiao1102** [ant-design/ant-design#9496]
当我点击日历中上个月或者下个月中的日期时，日期面板已经发生变化，但是没有触发onPanelChange 方法，会导致页面数据没有加载，带来了极差的用户体验，虽然我可以用onSelect方法来解决这个问题，但是我认为官方应该重视这个问题！！！！！！

**Comment by UlyC** [comment]
How did you solve the problem later?

> 当我点击日历中上个月或者下个月中的日期时，日期面板已经发生变化，但是没有触发onPanelChange 方法，会导致页面数据没有加载，带来了极差的用户体验，虽然我可以用onSelect方法来解决这个问题，但是我认为官方应该重视这个问题！！！！！！
> 
> The date panel has changed when I click on a date in the calendar for the last month or the following month, but the onPanelChange method is not triggered, causing the page data to be unloaded, resulting in a poor user experience, although I can use onSelect Method to solve this problem, but I think the official should pay attention to this issue! ! ! ! ! !

**Comment by jinyaqiao1102** [comment]
@UlyC compare date
