### ISSUE TITLE
Navigation of the Tabs component is displayed incorrectly

### ISSUE THREAD

**Issue by wyhaya** [ant-design/ant-design#9499]
### Version
3.2.3

### Environment
Chrome version 64.0.3282.186（64）

### Reproduction link
[https://codesandbox.io/s/1q8qpn4487](https://codesandbox.io/s/1q8qpn4487)

---
![2018-03-03 11_37_27](https://user-images.githubusercontent.com/23690145/36930297-cc0e0e54-1ed8-11e8-8030-2a40f45981e0.gif)

### Steps to reproduce
Set the component transform animation
Or set the display property

### What is expected?
The navigation position's border should be displayed just below the navigation

### What is actually happening?
Offset based on the transform property

**Comment by afc163** [comment]
This problem seems to be fixed now.
