### ISSUE TITLE
Is it possible to put other component in overlay attribute of Dropdown component ?

### ISSUE THREAD

**Issue by minhnhatspk** [ant-design/ant-design#9500]
### What problem does this feature solve?
In some cases, I want to display an text input or something else when dropdown button is clicked, not only a Menu with it's menu items

### What does the proposed API look like?
no

**Comment by yesmeck** [comment]
You can use Popover.

**Comment by minhnhatspk** [comment]
@yesmeck  thank for your answer. On my way, I use `disabled` attr in Menu.Item and override the cursor of  class `.ant-dropdown-menu-item-disabled` to `default`.
