### ISSUE TITLE
When wrapped in a React component, Step returns undefined classnames

### ISSUE THREAD

**Issue by mattcarlotta** [ant-design/ant-design#9501]
### Version
3.2.3

### Environment
Linux Mint 18.3, Chrome 64.0.3282.186, React 16.2, React-Dom 16.2

### Reproduction link
[https://codesandbox.io/s/ly78v53m6m](https://codesandbox.io/s/ly78v53m6m) (code)
[https://ly78v53m6m.codesandbox.io/](https://ly78v53m6m.codesandbox.io/) (development)

### Steps to reproduce
Create a separate React component that returns a Step component and place it inside of a Steps container component. 

For example:

**StepsExample.js**
```
<Steps current={stepIndex}>
  {map(stepLabels, ({ title, icon }, key) => (
    <Stepper
         icon={icon}
         key={key}
         editStep={this.editStep}
         title={title}
         stepKey={key}
         wasReviewed={wasReviewed}
     />
  ))}
</Steps>
```

**Stepper.js**
```
export default class Stepper extends PureComponent {
  handleEditStep = () => this.props.editStep(this.props.stepKey);

  render = () => {
    const { icon, title, wasReviewed } = this.props;

    return (
      <Step
          icon={<Icon type={icon} />}
          onClick={wasReviewed ? this.handleEditStep : undefined}
          title={title}
      />
    );
  };
}
```

### What is expected?
After completing all steps, the Stepper will become clickable and allow the user to use it as a quick navigation to edit a step.

### What is actually happening?
The Stepper (Step) is not being displayed because the css classnames are returning "undefined-item," instead of "ant-steps-item-title" ...etc.
![undefinedstepclassnames](https://user-images.githubusercontent.com/22607722/36931028-920201f0-1e62-11e8-921c-80fe0b2610fc.png)

---
I'm trying to avoid using an arrow function that passes a parameter within the render method. By creating a separate reusable component, I can pass down a key to the child component and when clicked, the child component can pass back the key to the parent component. Since this is a part of a Redux form that triggers updates upon form input changes, this separate component would eliminate duplicated functions during re-renders.

**Comment by afc163** [comment]
https://codesandbox.io/s/pjqvy74oxx

**Comment by daydarkln** [comment]
I have the same issue, but with Menu.Item
![2019-06-06_11-37-47](https://user-images.githubusercontent.com/27866698/59018869-8a900900-884f-11e9-9717-90bc3ea9c3ca.png)
