### ISSUE TITLE
当表格body 出现滚动条后，标题也出现滚动条，标题栏禁用滚动条

### ISSUE THREAD

**Issue by ahbsm** [ant-design/ant-design#9511]
### Version
3.2.2

### Environment
win10 edge ie11

### Reproduction link
[https://ant.design/components/table-cn/#header](https://ant.design/components/table-cn/#header)

### Steps to reproduce
表格body 出现滚动条后，表格为了对齐标题也出现滚动条

### What is expected?
表格body 出现滚动条后，表格标题不出现滚动条

### What is actually happening?
表格body 出现滚动条后，表格为了对齐标题也出现滚动条

**Comment by yutingzhao1991** [comment]
Duplicate of #4637
