### ISSUE TITLE
<Tag> closable 点击删除按钮时，如何禁止标签隐藏的css动画，等删除请求成功后再执行动画

### ISSUE THREAD

**Issue by cdscawd** [ant-design/ant-design#9513]
### What problem does this feature solve?
实现更好的交互逻辑

### What does the proposed API look like?
希望有控制动画的回调

**Comment by yesmeck** [comment]
Duplicate of #9203

**Comment by cdscawd** [comment]
目前再API中只有 
afterClose | 关闭动画完成后的回调
希望有关闭动画之前的回调

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2970

**Comment by andynicoo** [comment]
把tag改成受控组件，把visible设置true
