### ISSUE TITLE
Hope select component onBlur / onFocus method add event parameter

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#9515]
### What problem does this feature solve?
I hope, in the callback, I know which element gets the focus .

### What does the proposed API look like?
Hope the type is
```typescript
interface Demo<T> {
    onBlur:  FocusEventHandler<T>;
    onFocus: FocusEventHandler<T>;
}
```

**Comment by yesmeck** [comment]
Tagging as good first issue.

**Comment by muzea** [comment]
This is a bit strange, [onBlur call in rc-select](https://github.com/react-component/select/blob/20a0b03ae54d988ea5bc43b8b34e83653fe396a3/src/Select.jsx#L397) , callback's type is `( string[] | {key: string; label:string}[]  ) => void`.
Considering compatibility, onBlur's type will be like `( vls: string[] | {key: string; label:string}[], event: extends SyntheticEvent, ): void;` , is this acceptable?

**Comment by ericjam3** [comment]
I would like to work on this issue since it is still open. Will this be possible?

**Comment by ericjam3** [comment]
I am having troubles pinpointing where the code needs to be changed for this issue. Any tips?

**Comment by ericjam3** [comment]
I am no longer working on this issue.

**Comment by muzea** [comment]
@ericjam3 
The place that needs to be revised is probably these few

Select's type declaration
https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L44

The processing part of onBlur
https://github.com/react-component/select/blob/master/src/Select.jsx#L369

Because the actual part is in rc-select, you may need to use npm link to handle this dependency.

**Comment by mnikn** [comment]
want to work on this issue.

**Comment by yesmeck** [comment]
@muzea What particular problem do you want to resolve?

**Comment by muzea** [comment]
It was originally intended to handle some keyboard operations, such as when the mouse click on a select and then use the tab to switch focus. And it is convenient to have an event object to determine the current focus element. 
@yesmeck

**Comment by yesmeck** [comment]
I don't fully understand you when you click on a select, browser will focus on it, if you press <kbd>Tab</kbd>, the browser will focus to the next focusable element, how do you get the currently active element from the blur event?

**Comment by zhaowanhua** [comment]
so ，was this question had a solution？

**Comment by juanmendes** [comment]
As a workaround, you can always get the focused element with [`document.activeElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/72a6febcc49a2efb10d9b35b1c950c3b198b321b
