### ISSUE TITLE
when I run 'npm start' on windows alert a error.

### ISSUE THREAD

**Issue by jjskay** [ant-design/ant-design#952]
See attachments below:
![qq 20160128175331](https://cloud.githubusercontent.com/assets/5975458/12641018/2409581c-c5e8-11e5-9f7a-1d68e356712b.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/698

**Comment by jjskay** [comment]
So, this problem can‘t solve it?

**Comment by benjycui** [comment]
Try linux @jjskay

**Comment by jjskay** [comment]
I hope it running to Linux and windows .
 But it can't . 
So , I select to material-ui build on project .
