### ISSUE TITLE
Popover overlayStyle

### ISSUE THREAD

**Issue by RaedsLab** [ant-design/ant-design#9525]
### Version
3.2.3

### Environment
React 16.2.0

### Reproduction link
[https://codesandbox.io/s/zl041lxo1m](https://codesandbox.io/s/zl041lxo1m)

### Steps to reproduce
Open a popover and style the overlay background width and height 

### What is expected?
Only the overlay is affected by the style

### What is actually happening?
Popover width changes

**Comment by yesmeck** [comment]
It's expected, what do you want to style?

**Comment by RaedsLab** [comment]
I want to style the overlay of the popover. 

When it is open I want all the rest of the page to be black rgba(0,0,0,0.5) .

**Comment by yesmeck** [comment]
`height: 100vh`.

**Comment by RaedsLab** [comment]
Thanks, but I tried that 
hight : https://codesandbox.io/s/4qo7745xn9
hight and width: https://codesandbox.io/s/8lpzyzlmjl

**Comment by yesmeck** [comment]
Hmm, the overlay of the popover is not supposed to be fullscreen, it seems you want to implement a mask for popover (like modal does), you need to achieve it by yourself.

**Comment by TomasHubelbauer** [comment]
It would be cool to have an option to use `mask` with `Popover` as well.
