### ISSUE TITLE
Tree组件存在bug

### ISSUE THREAD

**Issue by AnonymousBoy1** [ant-design/ant-design#9531]
### Version
3.2.3

### Environment
win7, chrome64

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
Tree组件存在问题，使用官方示例的第一个示例即可重现，主要为disabeld的逻辑策略混乱。以下操作均针对第一个示例，从页面打开的初始状态开始。

1. 点击根节点“parent1”，此时“parent1”变更为未选中状态。观察disabled的节点“parent1-0”，发现其仍在选中状态。私以为，应该同步父节点的状态，改为未选中。若讨论其为选中状态为合理的，此时符合文档TreeNode props中的解释：“禁掉响应”。那么看下一条操作，产生逻辑悖论。
2. 点击“parent1-0”的第二个子节点“leaf”, 此时选中状态发生变更，再次点击，发现“parent1-0”的选中状态跟随子节点“leaf”的选中状态而变化的，不符合官方文档中“禁掉响应”的解释，产生悖论。

--------------------------------------------
以下步骤，描述更为混乱的现象，从页面加载的初始状态起，仍针对第一个示例
1. 点击“parent1-0”的第一个子节点“leaf”, 此时disabled的节点变更为未选中。
2. 点击根节点“parent1”，此时除disable和disableCheckbox节点外，其他节点都处于选中状态。
3. 再次点击根节点“parent1”，发现所有其他节点都变更为未选中状态，但是“parent1-0”很诡异的呈现了选中状态。此时，它的子节点没有任何选中情况，反应毫无逻辑可言。

---------------------------------------------
请确认是Tree组件本身的问题，还是示例出了问题？

### What is expected?
Tree组件的disabeld表现，父子节点的选中状态切换应保持关联性且符合逻辑。

### What is actually happening?
Tree组件的disabled表现，混乱且无逻辑。

**Comment by zombieJ** [comment]
感谢反馈，Tree组件目前正在进行部分重构。逻辑会进行调整以解决这些问题。

**Comment by zombieJ** [comment]
done. https://github.com/react-component/tree/pull/149
