### ISSUE TITLE
Cannot use custom child event inside a Select

### ISSUE THREAD

**Issue by dazbo** [ant-design/ant-design#9533]
### Version
3.2.1

### Environment
Windows 7, Chrome 64, Internet Explorer 11

### Reproduction link
[https://codesandbox.io/s/n5oq82m1pj](https://codesandbox.io/s/n5oq82m1pj)

### Steps to reproduce
Create a custom component displaying a modal on click.
Wrap this component inside a Select>Option

### What is expected?
Input fields should accept focus and user inputs

### What is actually happening?
Input can be focus, but no user input are accepted

**Comment by yesmeck** [comment]
The reason is React.createPortl bubble events to the parent component. Don't put Modal inside Option.
