### ISSUE TITLE
Table: Can set more detail rowSelection in Table?  

### ISSUE THREAD

**Issue by imakou** [ant-design/ant-design#9535]
### What problem does this feature solve?
Currently, the Table allows users to create "rowSelection".
But, the original features don't allow users to do more detail setting on the rowSelection.

For example, on the rowSelection, it cannot set "Title" in the header. Secondly, it cannot set the order on the Table.

### What does the proposed API look like?
```javascript 
rowSelection:{{Title:"Primary", order:3}}
```

**Comment by yutingzhao1991** [comment]
In your case, the action seems not like selection, it more like a operation. Maybe you should custom column render for your require. like https://codesandbox.io/s/jj0j3zjjov.
