### ISSUE TITLE
setValue.bind的state名称只能是formData?

### ISSUE THREAD

**Issue by diaoaa** [ant-design/ant-design#954]
`export default React.createClass({

  mixins: [Form.ValueMixin],

  getInitialState() {
    return {
      balanceConfig: {
        isChecked: false,
        type: 'PAY',
        subTransCode: '',
        transMode: '',
        freezeCode: '',
        transCache: false
      },
      moneyFundConfig: {
        isChecked: false,
        subTransCode: '',
        freezeCode: ''
      },
    };
  },
  render() {
    const balanceConfig = this.state.balanceConfig;
  
    return (
      <div>
        <Form inline onSubmit={this.handleSubmit}>
          {/* 余额 */}
          <Row>
            <Col span="2">
              <FormItem>
                <label className="ant-checkbox-inline">
                  <Checkbox id="isChecked" name="isChecked" value={balanceConfig.isChecked} onChange={this.setValue.bind(this, 'isChecked')}/>余额
                </label>
              </FormItem>
            </Col>`

如图，balanceConfig换成formData就可以正常绑定设置，使用balanceConfig就报错

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/809
