### ISSUE TITLE
Use stylelint error, such as 'xxx' has already been disabled!

### ISSUE THREAD

**Issue by Sam618** [ant-design/ant-design#9542]
### Version
3.2.3

### Environment
Docker
node v9.7.1

### Reproduction link
![https://github.com/Sam618/books/blob/master/CSS-secrets/chapter_2/img/QQ%E5%9B%BE%E7%89%8720180306154651.png?raw=true](https://github.com/Sam618/books/blob/master/CSS-secrets/chapter_2/img/QQ%E5%9B%BE%E7%89%8720180306154651.png?raw=true)
![https://github.com/Sam618/books/blob/master/CSS-secrets/chapter_2/img/QQ%E5%9B%BE%E7%89%8720180306154658.png?raw=true](https://github.com/Sam618/books/blob/master/CSS-secrets/chapter_2/img/QQ%E5%9B%BE%E7%89%8720180306154658.png?raw=true)

### Steps to reproduce
Import components using babel-plugin-import on demand, then use stylelint to detect the syntax of SASS, it will be an error!

### What is expected?
Do not report wrong!

### What is actually happening?
A pile of mistakes! Are all "xxx" has already been disabled！！！

**Comment by yutingzhao1991** [comment]
Your reproduction link cannot access. Can you provide a reproduce repo?

**Comment by afc163** [comment]
Just been curious, can you understand your question?

**Comment by Sam618** [comment]
Sorry, I'm trying to upload a picture! @afc163

**Comment by Sam618** [comment]
I tried to use the [template](https://codesandbox.io/s/nn872x73jp) provided to restore the problem, but it does not seem to work.

**Comment by Sam618** [comment]
Please look at the picture, the [template](https://codesandbox.io/s/nn872x73jp) does not seem to restore the problem @yutingzhao1991

**Comment by yutingzhao1991** [comment]
@Sam618 you should not use stylelint on css files which in node_modules. Because built css hard to fit with your stylelint rules.

**Comment by Sam618** [comment]
I tried limiting the node_modules folder, but it did not seem to work, and then I found out that it was because of the css file that introduced node_modules (the css file was inserted automatically on demand, so ...) was wrong. @

**Comment by yesmeck** [comment]
Don't run stylelint on node_modules.

**Comment by Sam618** [comment]
Resolved, need to use webpack configuration, rather than using stylelint comes with the exclusion option. What is my configuration:
```JavaScript
      {
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              require.resolve('css-loader'),
            ],
            exclude: path.resolve(__dirname, '../src'),
          },
          // "postcss" loader applies autoprefixer to our CSS.
          // "css" loader resolves paths in CSS and adds assets as dependencies.
          // "style" loader turns CSS into JS modules that inject <style> tags.
          // In production, we use a plugin to extract that CSS to a file, but
          // in development "style" loader enables hot editing of CSS.
          {
            test: /\.(sass|scss)$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  modules: true,
                  camelCase: true,
                  localIdentName: '[local]___[hash:base64:5]',
                  alias: {
                    'src': path.resolve(__dirname, '../src'),
                  },
                },
              },
              require.resolve('sass-loader'),
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('stylelint')(),
                    require('postcss-flexbugs-fixes'),
                    // require('stylelint')(),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },
```
