### ISSUE TITLE
Module not found: Error: Can't resolve 'antd/lib/list'

### ISSUE THREAD

**Issue by zhaiqiang1987** [ant-design/ant-design#9549]
Module not found: Error: Can't resolve 'antd/lib/list'

**Comment by 2320390964** [comment]
Have you solved the problem?

**Comment by zhaijiamei** [comment]
问题解决了吗，我也是这个问题

**Comment by ztplz** [comment]
@zhaijiamei  Could you provide a mini `git repo`?  It's so hard to look into without reproduce.
