### ISSUE TITLE
Popover in a Select.Option appear with a wrong position

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#9550]
https://riddle.alibaba-inc.com/riddles/5c8662c1

## background
use popover to make a preview of every option in select

## what's wrong
if set `getPopupContainer={(node) => node.parentElement}` to popover, it will appear with a wrong position, looks like
![image](https://user-images.githubusercontent.com/5318333/37022854-2f8643d8-215f-11e8-9538-1e0f160e9ac7.png)

if not set, z-index is not correct
![image](https://user-images.githubusercontent.com/5318333/37022887-433b57e2-215f-11e8-8c9f-dc44231f209c.png)

## what's expected
popover in a option works well

**Comment by yutingzhao1991** [comment]
`z-index` of drropdown is 1050, popover is 1030. It design for most cases. You can custom css style like https://codesandbox.io/s/03049p0n1w.

@jaredleechn any better idea?

**Comment by jaredleechn** [comment]
I think that's a bug of popover-like(tooltip, dropdown) component

If the component render in a parent element whose `overflow !== unset` and `position === relative`, or `overflow !== unset` parent contains `position === relative` parent,  the component always appears with wrong position

It looks like following

```
<div style={{ overflow: 'auto', position: 'relative' }}>
  // the popover-like component rendered
</div>

<div style={{ overflow: 'auto' }}>
  ...
  <div style={{ position: 'relative' }}>
    // the popover-like component rendered
  </div>
  ...
</div>
```

Here's the demo https://riddle.alibaba-inc.com/riddles/d614856c

@yesmeck Remeber the bug I shared to you few months ago? I think they are the same https://riddle.alibaba-inc.com/riddles/9366f798

**Comment by vishim** [comment]
@jaredleechn 
The https://riddle.alibaba-inc.com links do not work

**Comment by afc163** [comment]
You have to do this way: https://codesandbox.io/s/koyyl715k5

**Comment by jaredleechn** [comment]
Any solution about other popover-like component if they need to render under their parent component? The Popover and Select.Option just a temporary hack, once met the situation of `position: relative` and `overflow`, popover-like components always appear in wrong position

**Comment by afc163** [comment]
Nothing we can do if you try to render a popup node inside a container with `overflow` which don't have enough visible area to show the popup.
