### ISSUE TITLE
ie系列浏览器中TreeSelect组件，在搜索框中输入，搜索输入框在输入第一个字符后失去焦点

### ISSUE THREAD

**Issue by Cnax** [ant-design/ant-design#9552]
### Version
3.2.3

### Environment
ie浏览器

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
点击TreeSelect组件，在搜索框中输入，搜索输入框在输入第一个字符后失去焦点

### What is expected?
ie浏览器中TreeSelect组件的搜索框在输入过程中不会失去焦点

### What is actually happening?
ie浏览器中TreeSelect组件的搜索框在输入过程中会失去焦点

**Comment by yesmeck** [comment]
标题？浏览器版本？

**Comment by RoselinOldham** [comment]
https://www.youtube.com/watch?v=RDrfE9I8_hs

**Comment by yesmeck** [comment]
Duplicate of #9329
