### ISSUE TITLE
site css files is not minified

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#9554]
https://ant.design/index-1.css
https://ant.design/index-2.css

**Comment by yesmeck** [comment]
https://github.com/benjycui/bisheng/blob/ab245bc41d85d753616966fc32803ce7e3537c74/packages/bisheng/src/utils/get-bisheng-config.js#L18-L23

@benjycui bisheng 不默认加个 cssnano 吗？

**Comment by benjycui** [comment]
@yesmeck 来个 PR 吧。
