### ISSUE TITLE
Mouse pointer doesn't hit properly a sort-ascending button in a table.

### ISSUE THREAD

**Issue by niba** [ant-design/ant-design#9555]
### Version
3.2.3

### Environment
Chrome - 64.0.3282.186

### Reproduction link
[https://codesandbox.io/s/4xrox7wn70](https://codesandbox.io/s/4xrox7wn70)

### Steps to reproduce
1. Open the example in Chrome and Firefox (58.0.2)
2. Try to sort ascending using an arrow-up button in a table column header.

### What is expected?
1. In Chrome a finger of mouse hand pointer doesn't hit the arrow button and user needs to move the cursor a little higher than expected to select button. In Firefox it works okay.

### What is actually happening?
See "what is expected" section

**Comment by tim-soft** [comment]
![capture](https://user-images.githubusercontent.com/10257939/37487833-62b8b6aa-2858-11e8-8085-17e949f7272a.PNG)

The up/down arrow buttons for sort in my opinion are too small to be practical, the mouse can completely cover them. Sometimes it feels like you need to hold face very close to the screen to see what you're clicking.

I've also noticed that the sort/filter buttons aren't aligned center with the column title, so they always look misaligned.

A simple fix would be to make the sort up/down buttons taller+ wider, along with the clickable area, then align them vertically with the column text.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/eb2290a87f38d23a76e7c6235e0ce4d093ee0fe4
