### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#9556]
### Version
3.2.3

### Environment
Chrome 64.0

### Reproduction link
[https://codesandbox.io/s/w7wo838n1k](https://codesandbox.io/s/w7wo838n1k)

### Steps to reproduce
Register a nested field:
```javascript
this.props.form.getFieldDecorator("test.name") 
```

Then try to set values:
```javascript
this.props.form.setFieldsValue({ test: null })
```

### What is expected?
Warning in console, instead of throwing exception and crashing.

### What is actually happening?
Throws an error: 
```
TypeError: Cannot convert undefined or null to object
```
Call Stack:
`rc-form/lib/utils` on line 75 trying to call foreach on `Object.keys(tree)` while tree is `null`

**Comment by benjycui** [comment]
Actually, you cannot do so. 

The following code means that you want to delete registered field `test.name`:

```jsx
this.props.form.setFieldsValue({ test: null })
```
