### ISSUE TITLE
Programatically select an item in the menu o prevent selection of a one.

### ISSUE THREAD

**Issue by knightlore** [ant-design/ant-design#9560]
### What problem does this feature solve?
I use to put some selectable options in the Menu toolbar for easy and fast access, but the menu makes a selection of the option and the parent menu highlights, even when it's not navigation menu.
It could be useful if I can prevent that selection or programatically put in the previous menu to prevent this.
Even if not used for this goal could be very useful to have those two features.

### What does the proposed API look like?
Something like 

`<Menu.Item selectable={false}>`

and

`menu.select(key)`

**Comment by afc163** [comment]
`selectedKeys`
