### ISSUE TITLE
Form validation rules do not work when using mapPropsToFields. When mapPropsToFields is removed validation works.

### ISSUE THREAD

**Issue by magiccool** [ant-design/ant-design#9561]
### Version
3.2.3

### Environment
Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Reproduction link
[https://codesandbox.io/s/3vpq8w2396](https://codesandbox.io/s/3vpq8w2396)

### Steps to reproduce
1. Use getFieldDecorator to pass in validation rules with a message.
2. User Form.create({}) and pass in mapPropsToFields
3. See that validation from rules are not triggered in UI reaction
4. Remove mapPropsToFields
5. See that validation rules are triggered

### What is expected?
Validation works and messages from rules is displayed.

### What is actually happening?
Nothing, there is something printed in the console: async-validator

**Comment by dengfuping** [comment]
@magiccool Please refer to https://ant.design/components/form/#components-form-demo-global-state.

**Comment by yutingzhao1991** [comment]
@magiccool your reproduction link is the init demo. Please check and update it.

**Comment by magiccool** [comment]
@yutingzhao1991 it's not the init demo, I didn't remove the init index.js I just added other js files into it. 

I've found the issue though, it seems you have to map back the all the field data as well as the value... I was only mapping to the value field from upper component state.

 Is that correct? Is there another way to allow validation without have to do this>

**Comment by yutingzhao1991** [comment]
@magiccool Yes! when you use `mapPropsToFields` means fields status will update when props updated. So you should make sure mapPropsToFields return the all fields info. ref: https://ant.design/components/form/#components-form-demo-global-state.

**Comment by yoyo837** [comment]
@yutingzhao1991 How does `mapPropsToFields` work with non-Field props?
