### ISSUE TITLE
Use a less variable to set border-bottom-width in menu-item selected, hover, active and open

### ISSUE THREAD

**Issue by ealvarezk** [ant-design/ant-design#9566]
### What problem does this feature solve?
Have the capability to change it from the actual 2px

### What does the proposed API look like?
In https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L279 you have `border-bottom: 2px solid @menu-highlight-color;` you can change it to `border-bottom: @menu-highlight-border-width solid @menu-highlight-color;` and then add the variable in https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by valleykid** [comment]
ok, I see. I'll discuss your suggestion with others.

**Comment by afc163** [comment]
I don't think we need it, you can just create a PR if you do rely on it.
