### ISSUE TITLE
Autofocus Tree Select search input

### ISSUE THREAD

**Issue by StephenEsser** [ant-design/ant-design#9568]
### Version
3.2.3

### Environment
All environments

### Reproduction link
[https://ant.design/components/tree-select/](https://ant.design/components/tree-select/)

### Steps to reproduce
1. Navigate to https://ant.design/components/tree-select/
2. Click the first example drop down
3. Observe the search input is not focused and a user cannot type immediately.

### What is expected?
The Tree Select search input should have focus the first time the select menu opens.

### What is actually happening?
The first time the Tree Select drop down opens the input does not have focus and a user cannot type. It requires manually clicking into the search field to type.

---
This issue only happens the first time the Tree Select opens.

Receiving a lot of feedback from our application users that the required additional click into the input slows down progress.

**Comment by zombieJ** [comment]
https://github.com/react-component/tree-select/pull/104

**Comment by zombieJ** [comment]
fixed. ref: https://github.com/react-component/tree-select/commit/61373e16f4f51fc75232b1bb9d0b7107613a3e10
