### ISSUE TITLE
如何能够替换掉moment依赖

### ISSUE THREAD

**Issue by supeng911** [ant-design/ant-design#9570]
### Version
3.2.3

### Environment
react,next,react-dom,antd

### Reproduction link
[http://www.miguomama.com/ask](http://www.miguomama.com/ask)

### Steps to reproduce
没有bug，但是moment模块太大了，打包后还有moment: 476.23 KB

### What is expected?
把moment模块替换成更小的模块，比如fecha或者其他

### What is actually happening?
无

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5677

**Comment by xxyuk** [comment]
@supeng911  Replace Moment.js in Ant Design (Antd) with Day.js https://github.com/iamkun/dayjs/issues/529
