### ISSUE TITLE
Keep the multiple select filtered?

### ISSUE THREAD

**Issue by kissshot** [ant-design/ant-design#9573]
### What problem does this feature solve?
multiple mode 的select， 在选中筛选出的一个选项后， 会自动清除筛选值， 然后选项也被变成未筛选的全部选项， 如果想要选择多个的话， 就需要重新输入筛选值， 这样会很麻烦，希望能保持筛选状态， 最好是给一个配置项， 因为我在以前的issue里发现有些人是需要自动清除的功能的。

### What does the proposed API look like?
<Select
   mode="multiple"
   autoClearInputValue={false}
>
</Select>

**Comment by afc163** [comment]
这种交互有相关的竞品实现么？

**Comment by kissshot** [comment]
@afc163 没用过别的竞品， 我只是觉得， 既然是多选， 为什么筛选出来的选项不能多选， 而是要重新输入，这样很麻烦，选项很多的话， 就需要重复多次输入筛选值，我去看了rc-select的代码， 就是直接清除了，能留个选择吗

**Comment by afc163** [comment]
第一感觉是可以的，我需要看看有没有其他竞品有类似的交互，以便参考。

**Comment by alsikora** [comment]
Hello @afc163 
any news on this topic?
It looks like very interesting feature.

**Comment by jzhangs** [comment]
A proposal patch, [https://github.com/react-component/select/pull/286](https://github.com/react-component/select/pull/286)

Not sure if some new props needed. Since it's multiple select, it make sense to keep filter always here.

**Comment by afc163** [comment]
7531b4d Add a prop of `autoClearSearchValue`, default `false`.
