### ISSUE TITLE
`RadioGroupProps.onChange` is not a `React.ChangeEventHandler<HTMLInputElement>`

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9574]
### Version
undefined

### Environment
TypeScript 

### Reproduction link
[https://codesandbox.io/s/jpw403mn3](https://codesandbox.io/s/jpw403mn3)

### Steps to reproduce
run, click a radio

### What is expected?
show `has cancelable`

### What is actually happening?
show `no cancelable`

---
`React.ChangeEventHandler` should receive a SyntheticEvent( https://github.com/DefinitelyTyped/DefinitelyTyped/blob/db8be7aec245c2158be0bc2c9a8a8c3f8cdfcd96/types/react/index.d.ts#L494,  https://reactjs.org/docs/events.html ) , which must have `cancelable`, `bubbles`, etc. but the param passed by rc-checkbox is not a SyntheticEvent, see https://github.com/react-component/checkbox/blob/master/src/Checkbox.jsx#L66

**Comment by yesmeck** [comment]
`e.nativeEvent`

**Comment by whtsky** [comment]
I'm totally aware that we can use `e.nativeEvent`, but the type is wrong

**Comment by yesmeck** [comment]
Hmm, what scenario do you want to check `cancelable`?  If you want to prevent the change event, you just do not update the state `value`.

**Comment by whtsky** [comment]
In fact `.persist()` is the important part.
I'm using Ant Design with formit using TypeScript. Ant Design declare a lot of event as `SyntheticEvent` but in fact are not, which causes a lot of trouble.
https://github.com/jaredpalmer/formik/issues/187

**Comment by yesmeck** [comment]
We can not change the API for now, as @Spoki4 mentioned in https://github.com/jaredpalmer/formik/issues/187 you'd have to wrap `onChange` by yourself or use `setFieldValue` instead.

**Comment by whtsky** [comment]
IMO it's a bug since the typing info provided by Ant Design is wrong, so I suggest leave the issue open until the typing got corrected?

**Comment by yesmeck** [comment]
@whtsky Fixing.
