### ISSUE TITLE
[Table] onExpend was triggered incorrectly

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#9576]
### Version
3.2.3

### Environment
Chrome:latest

### Reproduction link

[Codesandbox Reproduce Link](https://codesandbox.io/s/zx45z4wp6m)

### Steps to reproduce

+  Click '点我'
+  in console, you will see the onExpend was triggered incorrectly

### What is expected?
When the data changes, `onExpend` should not be triggered.

### What is actually happening?
The `onExpend` was triggered.

**Comment by yesmeck** [comment]
`rc-table@6.1.7` thanks for reporting.
