### ISSUE TITLE
Tooltip does not disappear when button is disabled

### ISSUE THREAD

**Issue by Sokal21** [ant-design/ant-design#9581]
### Version
3.2.3

### Environment
Chrome

### Reproduction link
[https://codesandbox.io/s/64zprz4vmn](https://codesandbox.io/s/64zprz4vmn)

### Steps to reproduce
Pass the mouse over the button, and then take it out without passing it over the tooltip

### What is expected?
The tooltip should disappear

### What is actually happening?
the tooltip stays opened

---
I'm using styled-components to make styles for my components, I'm creating a custom styled components from an antd Button. The problem is that when this button is disabled and I hover over the button the tooltip does not go away. The issue is related to this specific line: https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L121 , here you cant identify that is an antd Button or a coomon button because we are using styled component.

**Comment by dengfuping** [comment]
@Sokal21 You can control whether the tooltip disappears on not with the `visible` prop, as the demo https://codesandbox.io/s/1r2z9463yl shows.

**Comment by Sokal21** [comment]
@dengfuping I need the tooltip to be displayed even when the button is disabled

**Comment by cloudever** [comment]
Did you notice that everything works well with an inline `button`?
IMHO that behavior caused by `ref` exported from the styled-components wrapper.

**Comment by Sokal21** [comment]
@cloudever Yes I realized, but I need to use the styled-component wrapper.

**Comment by afc163** [comment]
Try this as workaround: https://codesandbox.io/s/nkwv5l9k40

**Comment by dengfuping** [comment]
@afc163 The problem exists still. Maybe we should to make `Tooltip` more compatible for styled components.

**Comment by afc163** [comment]
https://codesandbox.io/s/l5qpjp2k4z

**Comment by afc163** [comment]
```diff
const StyledButton = styled(Button)`
  width: 300px;
`;

+ StyledButton.__ANT_BUTTON = true;
```

**Comment by codercatmomi** [comment]
如果是 checkbox呢？
StyledButton.__ANT_BUTTON = true;
这句应该怎么样？

**Comment by codercatmomi** [comment]
@afc163 
如果是 checkbox呢？
StyledButton.__ANT_BUTTON = true;
这句应该怎么样？

**Comment by mcarlotta** [comment]
Experiencing same issue as well in our application. You have to re-hover over it to remove

**Comment by dengfuping** [comment]
@codercatmomi It's the same as above.

https://github.com/ant-design/ant-design/blob/ad721111a43b805f503f9308bcec1860811530c5/components/tooltip/index.tsx#L124

**Comment by udielenberg** [comment]
@dengfuping 

Does adding `Button.__ANT_BUTTON = true;` has any side effects beside fixing the bug?

**Comment by afc163** [comment]
Seems that React resolve this in `16.13.0`: https://github.com/facebook/react/pull/17675

**Comment by fclement-yseop** [comment]
I fixed this problem with https://github.com/react-component/tooltip/issues/18#issuecomment-411476678.
> Workaround:
> Wrap the disabled button/input in another element.
> Add `{pointer-events: none}` style to the disabled button/input.

**Comment by Podsclan** [comment]
> I fixed this problem with [react-component/tooltip#18 (comment)](https://github.com/react-component/tooltip/issues/18#issuecomment-411476678).
> 
> > Workaround:
> > Wrap the disabled button/input in another element.
> > Add `{pointer-events: none}` style to the disabled button/input.

Worked for me, thank you!

**Comment by damiangreen** [comment]
This workaround this causes the tooltip to not show at all for me(when the child component is a disabled Switch).

**Comment by ofkarakus** [comment]
> I fixed this problem with [react-component/tooltip#18 (comment)](https://github.com/react-component/tooltip/issues/18#issuecomment-411476678).
> 
> > Workaround:
> > Wrap the disabled button/input in another element.
> > Add `{pointer-events: none}` style to the disabled button/input.

It worked for select[disabled] as well. Thank you!

**Comment by anjantalatam** [comment]
Here is a workaround

```JSX
<Tooltip title={!disabled ? "Tooltip" : null}> 
    <Button
         type="primary"
         disabled={disabled}
     >
         Tooltip Button
     </Button>
</Tooltip>
```

[Open in Codesandbox](https://codesandbox.io/s/antd-tooltip-on-disabled-button-tg2mk7?file=/demo.tsx:219-478)

**Comment by lichspace** [comment]
> Here is a workaround
> 
> ```js
> <Tooltip title={!disabled ? "Tooltip" : null}> 
>     <Button
>          type="primary"
>          disabled={disabled}
>      >
>          Tooltip Button
>      </Button>
> </Tooltip>
> ```
> 
> [Open in Codesandbox](https://codesandbox.io/s/antd-tooltip-on-disabled-button-tg2mk7?file=/demo.tsx:219-478)

nice in my case
