### ISSUE TITLE
Feature require Time Range Picker feature

### ISSUE THREAD

**Issue by imakou** [ant-design/ant-design#9582]
### What problem does this feature solve?
Hi,
First of all, the framework is awesome!

But, I am facing a feature which doesn't implement by ANTD

This issue could relate this:
https://github.com/ant-design/ant-design/issues/8584

But the feature is still not implemented yet in 3.x ANTD.

### What does the proposed API look like?
```javascript
const RangePicker = TimePicker.RangePicker
...
<RangePicker />
```
Just allows users to pick time range rather than date first then time range.

![screen shot 2018-03-08 at 4 45 25 pm](https://user-images.githubusercontent.com/1507950/37178475-9c86e78e-22f0-11e8-9cb7-96379b657463.png)

**Comment by benjycui** [comment]
Just use RangePicker[mode], see: https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode

**Comment by imakou** [comment]
@benjycui Hi, thanks for your replying.
But, I cannot quite understand how to use it.
I've changed state as ```mode:['time','time']``` for rangepicker.
It shows some error message
```javascript
"Warning: Failed prop type: Invalid prop `mode[0]` of value `time` supplied to `RangeCalendar`, expected one of ['date','month','year','decade'].
    in RangeCalendar (created by RangePicker)
    in RangePicker (created by LocaleReceiver)
    in LocaleReceiver (created by PickerWrapper)
    in PickerWrapper (created by ControlledRangePicker)
    in ControlledRangePicker
    in div"
```

Could you please give me more specific example or demo?

**Comment by imakou** [comment]
any update?

Thanks.

**Comment by yesmeck** [comment]
Related #8858

**Comment by imakou** [comment]
@yesmeck 
Thanks. Will the feature be implemented in the feature?
The time ranger pick is awesome in Ant Design, but it cannot be used independently.
It must be called DatePicker then TimePicker.  Hopely, there is an independent time ranger picker.
:)

**Comment by sahilchopra** [comment]
+1

**Comment by rahulborah** [comment]
Any updates on TimeRangePicker?
Thanks.

**Comment by rahulborah** [comment]
@yoyo837 Can you provide an example code?

**Comment by yoyo837** [comment]
@rahulborah https://codesandbox.io/s/antd-reproduction-template-gl5j0 Just an example, not a complete feature.

**Comment by afc163** [comment]
Already supported in 4.0: https://ant.design/components/time-picker-cn/#components-time-picker-demo-range-picker

**Comment by gouflv** [comment]
> Already supported in 4.0: https://ant.design/components/time-picker-cn/#components-time-picker-demo-range-picker

Is it possible to make this as a build-in component?

**Comment by yoyo837** [comment]
@gouflv It is.
