### ISSUE TITLE
will u consider to develope a  Rich Text Editor 

### ISSUE THREAD

**Issue by zzwar2009** [ant-design/ant-design#9584]
### What problem does this feature solve?
Rich Text Editors base on react on github is not friendly ,hope ant.design team to consider to develop a  Rich Text Editor component

### What does the proposed API look like?
base api for text :such as font-size color indent, 
every feature switch(on/off)
language support(en/zh-cn)
support html/markdown
disable /enable
contentChangecallback
image preview/upload and so on ....

**Comment by yesmeck** [comment]
Duplicated of #1083
