### ISSUE TITLE
Popover detect outside click

### ISSUE THREAD

**Issue by RaedsLab** [ant-design/ant-design#9589]
### Version
3.2.3

### Environment
Any

### Reproduction link
[https://codesandbox.io/s/n0p2m713wm](https://codesandbox.io/s/n0p2m713wm)

### Steps to reproduce
1 - open popover 
2- click anywhere outside of it

### What is expected?
1 - open popover 
2- click anywhere outside of it -> Have a callback event triggered

### What is actually happening?
No callback event

**Comment by afc163** [comment]
https://codesandbox.io/s/pkpvyr1jvm

**Comment by yesmeck** [comment]
`onVisibleChange`

**Comment by RaedsLab** [comment]
Thank you I missed it in the tooltips docs !

**Comment by luishdez** [comment]
@yesmeck  How `onVisibleChange` solve this problem? that event is only fired if visibility is changed not if outside content is clicked. 

How do you add an event to close ( set visible=false) clicking outside ?

**Comment by TomasHubelbauer** [comment]
Since this is the first Google result: Ant `Popover` doesn't support this out of the box.

**Comment by amannn** [comment]
It seems like you can get the behaviour to close the popover on outside click working by using `trigger="click"`.

https://codesandbox.io/s/antdesign-popover-close-click-outside-dc3vy

**Comment by luishdez** [comment]
May be another action is required than close the popover.  

Solution: https://stackoverflow.com/questions/32553158/detect-click-outside-react-component

**Comment by jiewang010203** [comment]
You can get visible state from onVisibleChange, the premise is your tigger props is 'click', and you can manually control visible by yourself

**Comment by Prathapkarumanchi** [comment]
The design system it self is a failure, why someone need to wrap something inside Popover component.
I want to create one Popover component and pass the content and event through props but in this flawed design.
Someone has to wrap this popover around some content if you want to trigger the popover.

I have a dynamically created list items where i want to show popover for each element but this popover thing is not working at all if I have to replace a string content. the component is turned into a generic tag.

**Comment by jiewang010203** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Konstantin-Ushakov** [comment]
In case you use Material UI.
You may want to use `ClickAwayListener` like:
```js
import { ClickAwayListener } from '@material-ui/core';
<ClickAwayListener
  onClickAway={() => props.setIdModalOpen('')}
  mouseEvent="onMouseUp"
  touchEvent="onTouchEnd"
>
  <Popover ...>{...}</Popover>
</ClickAwayListener>
```

**Comment by jiewang010203** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shamseer-ahammed** [comment]
if you set `trigger='click'` then dont set `visible` on Popover, i had to still set `visible` for my usecase, got it working with 

```
onVisibleChange={(isOpen) => {
     if (isOpen) {
          return
     }
     setVisble(false)
}}
```

**Comment by shamseerahammedm** [comment]
if you set `trigger='click'` then dont set `visible` on Popover, i had to still set `visible` for my usecase, got it working with 

```
onVisibleChange={(isOpen) => {
     if (isOpen) {
          return
     }
     setVisble(false)
}}
```

**Comment by jiewang010203** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by standbyoneself** [comment]
Very need this feature
