### ISSUE TITLE
form.setFields(Value) doesn't update the state in the calling component

### ISSUE THREAD

**Issue by pellea** [ant-design/ant-design#9591]
### Version
3.2.3

### Environment
react

### Reproduction link
[https://codesandbox.io/s/k32ypxw8rv](https://codesandbox.io/s/k32ypxw8rv)

### Steps to reproduce
Enter some text in the "name" field.

### What is expected?
The value of the "days" fields to be updated accordingly.

### What is actually happening?
Nothing happens, the value of the "days" field is not updated.

---
To make it works, I need to manually enter a value in the "days" field. But my goal is to programmatically update the field value.

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/37242206-5ef7e86c-24a0-11e8-807b-f372756d9d5d.gif)

It works as your description.

**Comment by pellea** [comment]
Do I use the form component correctly? Do you know if there is any workaround I could use?

**Comment by benjycui** [comment]
When you modify the value of name, it will trigger `onFieldsChange` once, and then you use `setFieldsValue` to trigger `onFieldsChange` again. So, you `this.setState` twice, but the second time, you use the old state.

```diff
  handleFormChange = changedFields => {
-  this.setState({
-    fields: { ...this.state.fields, ...changedFields }
-  });
+  this.setState(({ fields }) => ({
+    fields: { ...fields, ...changedFields }
+  }));
  };
```

**Comment by pellea** [comment]
The sample in the documentation has this code:
```
 handleFormChange = (changedFields) => {
    this.setState({
      fields: { ...this.state.fields, ...changedFields },
    });
  }
```

I think the documentation should be updated to avoid further issues.

**Comment by benjycui** [comment]
@pellea just PR to update docs, thanks.

**Comment by pellea** [comment]
@benjycui The project doesn't lint correctly and I can't commit the code.

**Comment by benjycui** [comment]
`git commit -n`

**Comment by pellea** [comment]
I hope I did it right. This is my first PR ever :)
