### ISSUE TITLE
Problem integrating nextjs with ant design 

### ISSUE THREAD

**Issue by crushy26** [ant-design/ant-design#9596]
### Version
3.2.3

### Environment
MacOS High Sierra 10.13.3, Google Chrome Version 64.0.3282.186 (Official Build) (64-bit), React 16, Nextjs 5

### Reproduction link
[https://bitbucket.org/kushal_siddesh/nextjs-antd-issue](https://bitbucket.org/kushal_siddesh/nextjs-antd-issue)

### Steps to reproduce
Yarn install  
Yarn run dev

### What is expected?
Expecting modular CSS to work ( https://ant.design/docs/react/introduce#Use-modularized-antd )

### What is actually happening?
results in following error :

Invalid or unexpected token
/Users/crushy/dev/nextjs-antd-issue/node_modules/antd/lib/style/index.css:6
@font-face {
^

**Comment by yesmeck** [comment]
It's not issue of antd, see https://github.com/zeit/next-plugins/issues/1
