### ISSUE TITLE
Feature require: checked status when parent item was selected in Tree Select

### ISSUE THREAD

**Issue by imakou** [ant-design/ant-design#9597]
### What problem does this feature solve?
Hi,
There is a feature require which can make UI better.
The current setting is that the children won't be checked when users select the top parent item.
I think the children should be checked even the parent item has been disabled.

![screen shot 2018-03-09 at 10 37 01 am](https://user-images.githubusercontent.com/1507950/37216094-eb6b7c88-2387-11e8-9395-ed4847d1bd20.png)

### What does the proposed API look like?
Accept ```checked:true``` attribute in treeData.

```javascript
children: [
          {
            label: "Saturday",
            value: "Saturday",
            key: "Saturday",
            checked:true
          },
          {
            label: "Sunday",
            value: "Sunday",
            key: "Sunday",
           checked:true
          }
        ]
```

**Comment by afc163** [comment]
Use `value` to indicate the selected items.

**Comment by imakou** [comment]
Hi @afc163,
The issue is that when all children were selected, the value will be the parent, like ```["Weekdays"]``` in this case.

So that, I cannot set value as ```["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]```

In order to have a better UI experience, think that all children should have ```checked``` status even the parent has shown checked status.
