### ISSUE TITLE
Warning: you should not use `ref` on enhanced form, please use `wrappedComponentRef`

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#9598]
### Version
3.2.3

### Environment
Chrome 64.0

### Reproduction link
[https://codesandbox.io/s/5wy3z3v81n](https://codesandbox.io/s/5wy3z3v81n)

### Steps to reproduce
In the link I'm using mix of two demos:
[Using form's `ref`](https://ant.design/components/form/#components-form-demo-form-in-modal) and [Checking form's errors](https://ant.design/components/form/#components-form-demo-horizontal-login) 

Use `getFieldsError()` or `isFieldsTouched()` on wrapped form component ref. Throws a warning: 
```
Warning: you should not use `ref` on enhanced form, please use `wrappedComponentRef`. See: https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140
```

### What is expected?
I have to use `ref` because if I use `wrappedComponentRef`, as the warning encourages me, I wouldn't have access to any of the form's functions. 

That throws the warning, but not for all the functions. For example when I use `validateFields` it doesn't. When I use `isFieldsTouched` or `getFieldsError` it does .

### What is actually happening?
Throws a warning.

Should I pay attention to this warning or it's a bug?

**Comment by benjycui** [comment]
@froston I had updated the documentation, please consult the PR.

You should not use ref for wrapped form, for you are depend on the implementation of `antd.Form.create`, it's dangerous.
