### ISSUE TITLE
npm test on master errors

### ISSUE THREAD

**Issue by bryanberger** [ant-design/ant-design#9599]
### Version
3.2.3

### Environment
macOS 10.13.3
Node v8.5.0

### Reproduction link
[https://github.com/bryanberger/ant-design](https://github.com/bryanberger/ant-design)

### Steps to reproduce
- Fork ant-design master
- clone locally
- npm install
- npm test

### What is expected?
no test errors

### What is actually happening?
a ton of LocaleProvider errors such as:

- Locale Provider › should display the text as ku-iq
- Locale Provider › should display the text as zh-cn
- Locale Provider › should display the text as uk

**Comment by yesmeck** [comment]
CI is passing https://travis-ci.org/ant-design/ant-design/builds/351230389?utm_source=github_status&utm_medium=notification

**Comment by yesmeck** [comment]
Because you updated the snapshot. https://github.com/ant-design/ant-design/pull/9595/files#diff-c04738fb5598c9649ac6b0c58c0b42a1

**Comment by bryanberger** [comment]
@yesmeck yes, but this is happening on a fresh fork as well.

**Comment by yesmeck** [comment]
Try `npm test -- --no-cache`

**Comment by bryanberger** [comment]
not working, would it be helpful to paste the full test log?

**Comment by yesmeck** [comment]
Please.

**Comment by bryanberger** [comment]
https://pastebin.com/XMcBy52r

**Comment by yesmeck** [comment]
It seems the mockdate is not working as expected, what is your timezone?

**Comment by bryanberger** [comment]
EST

**Comment by yesmeck** [comment]
It's an interesting bug, the time we store in the snapshot is in the summertime when you run it in wintertime, it fails.

**Comment by yesmeck** [comment]
It should be fixed.
