### ISSUE TITLE
Table表格增加列拖拽和自定义列显示功能

### ISSUE THREAD

**Issue by xiayz** [ant-design/ant-design#960]
给Table表格增加以下功能，增强Table实用性：
1.列拖拽功能：用户可以通过拖拽调整列顺序。
2.增加列显示自定义：用户可以选择那些列需要显示，显示自己关心的列数据。

**Comment by afc163** [comment]
1. 暂不支持。
2. 内部设计规范有涉及，后面可能会支持，可对下一步开发计划保持关注。

这个先关闭了，感谢建议。
