### ISSUE TITLE
Property 'form' dose not exist on form wrapped by Form.create()

### ISSUE THREAD

**Issue by Last-Order** [ant-design/ant-design#9604]
### Version
3.2.3

### Environment
Windows 10, TypeScript 2.7.2

### Reproduction link
[https://github.com/Last-Order/antd-reproduction](https://github.com/Last-Order/antd-reproduction)

### Steps to reproduce
1. Create a child component and wrapped it by Form.create()
2. Try to pass parent component's form reference to child form. (Please refer to the reproduction repository)

### What is expected?
According to the documentation:

>If the form has been decorated by Form.create then it has this.props.form property. 

And it actually have this property. If I forcefully  declared wrapped subform component as `any`, everything based on `form` property works perfectly.

In fact, I'm following this [article](http://mannyjossy.com/2017/05/18/React-Hoc-Crud/). (In Chinese)

### What is actually happening?
Property 'form' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<SubFormProps & FormComponentProps, ...'

**Comment by yesmeck** [comment]
> Try to pass parent component's form reference to child form.

Don't do that.

**Comment by Last-Order** [comment]
@yesmeck I found the same usage in the rc-form's official  [documentation](http://react-component.github.io/form/examples/parallel-form.html). 
So if antd community doesn't recommend this, is there any alternative method to do this?

**Comment by yesmeck** [comment]
The example only use one `createForm`
