### ISSUE TITLE
Multiple themes support based on parent className

### ISSUE THREAD

**Issue by gibbsfromncis** [ant-design/ant-design#9605]
### What problem does this feature solve?
I have the project where user should be able to select themes - light or dark or midnight. I'm going to create separate repo like "style-guide" where I can customize ant on 3 different files "theme.js". On result I want to have 3 builds like "ant.light.css" etc.

The issue is I'm not sure how can I apply styles to ant elements based on parent element class name like <body className="midnight-theme"> (body.midnight-theme > (ant-element)). 

Also I don't understand can I use few `theme.js` files or not. I'm open for any suggestions or thoughts 

### What does the proposed API look like?
The ability to configure parent variable for all elements

**Comment by gibbsfromncis** [comment]
I suppose it's OK if I can use just one theme.js. I'll create separate repositories for each theme. But how can I make out ant styles to parent className:
body.my-theme {
 // ant styles there
}

**Comment by gibbsfromncis** [comment]
The way I use now looks like:

```
@import "~antd/lib/style/mixins/index";
@import "~antd/lib/style/core/base";
@import "~antd/lib/style/core/iconfont";

body.dark {
  @import "~antd/lib/style/components";
}

```

Is there any better way?

**Comment by yesmeck** [comment]
> The issue is I'm not sure how can I apply styles to ant elements based on parent element class name like (body.midnight-theme > (ant-element)).

I think you just need to load CSS dynamic, the later one will override the early one.

**Comment by marklai1998** [comment]
@gibbsfromncis 
any update on this? I'm looking for a way to dynamically switch between themes in V4
the instruction at the doc is too complex for me

I've followed your code, but no luck

```
@import '~antd/dist/antd.less';

body.dark {
  @import '~antd/dist/antd.dark.less';
}

@primary-color: #ff941f;
```

**Comment by arthur-creek** [comment]
> @gibbsfromncis
> any update on this? I'm looking for a way to dynamically switch between themes in V4
> the instruction at the doc is too complex for me
> 
> I've followed your code, but no luck
> 
> ```
> @import '~antd/dist/antd.less';
> 
> body.dark {
>   @import '~antd/dist/antd.dark.less';
> }
> 
> @primary-color: #ff941f;
> ```

src/index.html
```
<!doctype html>
<html theme="dark">
  ...
  <body>
    <div id="root"></div>
  </body>
</html>
```
src/app/index.less
```
@import '~antd/dist/antd.less';
```
src/app/index.dark.less
```
[theme='dark'] {
  @import '~antd/dist/antd.dark.less';
}
```
src/app/index.tsx
```
import * as React from 'react';
import { hot } from 'react-hot-loader/root';
import { Router, Route, Switch } from 'react-router';
import { MainContainer } from 'app/containers/MainContainer';

import './index.less';
import './index.dark.less';
// render react DOM
export const App = hot(({ history }) => {
  return (
    <Router history={history}>
      <Switch>
        <Route path="/" component={mainContainer} />
      </Switch>
    </Router>
  );
});
```

**Comment by marklaihk01** [comment]
> > @gibbsfromncis
> > any update on this? I'm looking for a way to dynamically switch between themes in V4
> > the instruction at the doc is too complex for me
> > I've followed your code, but no luck
> > ```
> > @import '~antd/dist/antd.less';
> > 
> > body.dark {
> >   @import '~antd/dist/antd.dark.less';
> > }
> > 
> > @primary-color: #ff941f;
> > ```
> 
> src/index.html
> 
> ```
> <!doctype html>
> <html theme="dark">
>   ...
>   <body>
>     <div id="root"></div>
>   </body>
> </html>
> ```
> 
> src/app/index.less
> 
> ```
> @import '~antd/dist/antd.less';
> ```
> 
> src/app/index.dark.less
> 
> ```
> [theme='dark'] {
>   @import '~antd/dist/antd.dark.less';
> }
> ```
> 
> src/app/index.tsx
> 
> ```
> import * as React from 'react';
> import { hot } from 'react-hot-loader/root';
> import { Router, Route, Switch } from 'react-router';
> import { MainContainer } from 'app/containers/MainContainer';
> 
> import './index.less';
> import './index.dark.less';
> // render react DOM
> export const App = hot(({ history }) => {
>   return (
>     <Router history={history}>
>       <Switch>
>         <Route path="/" component={mainContainer} />
>       </Switch>
>     </Router>
>   );
> });
> ```

Thx a lot
I used injectType: 'lazyStyleTag' at `style-loader` at the end.
But now both .less file will become a part of my bundle (~1MB)
Any way to reduce it?
