### ISSUE TITLE
Switch UI doesn't update when set using resetFields

### ISSUE THREAD

**Issue by Fajer39** [ant-design/ant-design#9611]
### Version
3.2.3

### Environment
Latest chrome, OS: High-Siera, latest react

### Reproduction link
[https://codesandbox.io/s/n3rnmmrm50](https://codesandbox.io/s/n3rnmmrm50)

### Steps to reproduce
Select some option from `select` input, then turn `switch` on and click `Submit` button. In console.log, you'll see the right output. Then, use `allowClear` button on Select and click `Submit`. You will receive empty formValues in console, which is right, but the `switch` will still be on.

### What is expected?
Switch should be turned off by using `resetFields` function from `this.props.form`

### What is actually happening?
Switch UI is remaining the same, not respecting the value set inside getFieldDecorator

**Comment by afc163** [comment]
https://codesandbox.io/s/kx6nwk3llr

https://ant.design/components/form/#getFieldDecorator(id,-options)-parameters

Check `options.valuePropName`

**Comment by afc163** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/507615/37242245-039970ca-24a1-11e8-9fdf-b561add5d242.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/507615/37242249-1136befe-24a1-11e8-8f24-6db435a87534.png">

**Comment by Fajer39** [comment]
@afc163 I see, thank you for a quick help.

**Comment by developdeez** [comment]
Not sure why but that didnt work for me:
```
getFieldDecorator("emailNotify", {
                        initialValue: settings.emailNotify,
                        valuePropName: "checked"
                      })
```

**Comment by eliram9** [comment]
I new with ANTD and have the same problem and I can't understand the solution, please help!
here is my code:
`<Switch valuePropName="value"  onChange={(evt) => setAccountsData({...accountsData, active: evt})}/>`

after submit the state getting back to false but the button is still **checked**,
how do I unchecked the switch after submit?

**Comment by MarufSharifi** [comment]
For me it was a little bit different, Switch or checkbox should be the only child of form item, if not it won't work.
