### ISSUE TITLE
when fullscreen is enabled React ant Dropdown is not clickable 

### ISSUE THREAD

**Issue by BijayRai** [ant-design/ant-design#9612]
### Version
2.13.13

### Environment
mac os, chrome, react 16.2.0

### Reproduction link
[https://jsfiddle.net/BijayRai/twj39eaq/](https://jsfiddle.net/BijayRai/twj39eaq/)

### Steps to reproduce
while doing fullscreen react ant dropdown menus should be clickable

### What is expected?
Dropdown should be clickable while full screen in enabled.

### What is actually happening?
i ve used this fullscreen api [https://jsfiddle.net/BijayRai/twj39eaq/] plugin where react ant design Dropdown menu box items are not clickable.
In this example i ve not placed the dropdown menu but i ve implemented with react video js plugin where that dropdown works in normal screen but when i do full screen then dropdown menu is open but it's not clickable.

**Comment by yesmeck** [comment]
See #7815
