### ISSUE TITLE
Font size for .ant-tabs-large has shrunk to 12px

### ISSUE THREAD

**Issue by khalibloo** [ant-design/ant-design#9615]
### Version
3.2.3

### Environment
Windows 10, Firefox 58.0.2 (64 bit), React 16.2.0

### Reproduction link
[https://codesandbox.io/s/zqzyq088o3](https://codesandbox.io/s/zqzyq088o3)

### Steps to reproduce
Add a Tab component and set its size attribute to "large".

### What is expected?
Font size should be 16px for the titles of the tabs. Antd version 3.0.1 for example, uses 16px for .ant-tabs-large.

### What is actually happening?
AntD version 3.2.3 uses 12px. "large" tab font is even smaller than default tab.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/9509
