### ISSUE TITLE
Pagination with simple property does not show total counts correctly

### ISSUE THREAD

**Issue by satyam22** [ant-design/ant-design#9616]
### Version
3.2.3

### Environment
Windows 10,Google Chome 56,react 16

### Reproduction link
[https://codesandbox.io/s/1ololw72mq](https://codesandbox.io/s/1ololw72mq)

### Steps to reproduce
You  will be able to reproduce it by running it self.

### What is expected?
page count should be shown correct

### What is actually happening?
suppose for example if i put total pages as 50 then in UI i only see total pages as 5.

**Comment by afc163** [comment]
`total` means total items, not total page count.

**Comment by rumsky** [comment]
May add a prop to refer is display total count
