### ISSUE TITLE
ant-design-0.11.3试着编译你们的源码, 发现无法通过

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#962]
[root@hubvm0084 ant-design-0.11.3]# webpack --config webpack.antd.config.js
Hash: c87e3e01ac89d7f10b15
Version: webpack 1.12.2
Time: 1372ms
      Asset    Size  Chunks             Chunk Names
    antd.js  2.1 kB       0  [emitted]  antd
antd.js.map    2 kB       0  [emitted]  antd
   [0] multi antd 40 bytes {0} [built] [2 errors]
    + 2 hidden modules

ERROR in Loader /home/root1/wangyun/ant-design-0.11.3/node_modules/babel/index.js?{"presets":["es2015","react","stage-0"],"plugins":["add-module-exports"]} didn't return a function
 @ multi antd

ERROR in Loader /home/root1/wangyun/ant-design-0.11.3/node_modules/css/index.js?sourceMap&-minimize didn't return a function
 @ multi antd

**Comment by afc163** [comment]
不要提重复的 issue 。#961
