### ISSUE TITLE
Full Height for Tabs?

### ISSUE THREAD

**Issue by SebastianStehle** [ant-design/ant-design#9622]
### What problem does this feature solve?
I am looking for a solution to give the tab control the full height and make the content scrollk, if necessary.

### What does the proposed API look like?
Just a property or css example?

**Comment by afc163** [comment]
> give the tab control the full height and make the content scroll

What does this looks like?

**Comment by SebastianStehle** [comment]
I can show you: https://athene.sstehle.com/

I want the tab control on the left to have the full size so that I can control the content by myself. Then I would use overflow-y: auto for the list of shapes so that the tab header and search input always stay on top.

**Comment by valleykid** [comment]
Please try this. Use `js` to calculate height if need to be compatible with other browsers which don't support `calc` or `vh`.
```css
.shapes-list {
   /* bodyHeight - headerHeight - tabBarHeightAndMarginBottom - searchBoxHeight */
    max-height: calc(100vh - 64px - 56px - 32px);
    overflow-y: auto;
}
```

**Comment by SebastianStehle** [comment]
It would be easier to use absolute positioning, but the question is: is there a nice solution?

**Comment by SebastianStehle** [comment]
I solved it with flexbox.

**Comment by chaserstrong** [comment]
@SebastianStehle  Can you share the solution with me?

**Comment by SebastianStehle** [comment]
Sorry, I am really busy, but the source code is there: https://github.com/mydraft-cc/ui

**Comment by SamuelTSO** [comment]
I was able to solved it with this code: 

```
const Container = styled.div`
  max-height: 80vh;

  .ant-layout-sider-children,
  .ant-tabs,
  .ant-tabs-content,
  .ant-tabs-tabpane,
  .tab-panel {
    ${tw`flex flex-col flex-grow min-h-0`}
  }

  .ant-tabs-content {
    ${tw`overflow-auto`}
  }
`;
```

**Comment by ChristopherHButler** [comment]
@SamuelC54 can you explain what tw is here? I would really like to get this working as well!

**Comment by taitems** [comment]
Your solution may vary depending on your context, but two things that helped me finally get this working:
- `flex: 1 1 auto` worked in Chrome and not Safari, `flex: 1 1 0` worked everywhere including Firefox
- `animation={false}` was necessary to overcome the way `margin-left: -100%` was interacting with various other attempts to solve this.

A side note, antd using `margin` to animate seems like a really strange choice to me? Using `transform: translateX(-100%)` is hardware accelerated and would give you buttery smooth frames?

**Comment by weeklyTea** [comment]
In my case adding css below solved full-height problem, but it doesn't seem like universal and good solution...
```css
  .ant-tabs {
    height: 100%;
  }

  .ant-tabs-content-holder {
    display: flex;
  }
```

Is there a better way for to solve it?
