### ISSUE TITLE
ant design和pro官网登不上了！

### ISSUE THREAD

**Issue by chluknight** [ant-design/ant-design#9625]
### Version
3.2.3

### Environment
https://ant.design/docs/react/introduce-cn

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
https://ant.design/docs/react/introduce-cn

### What is expected?
https://ant.design/docs/react/introduce-cn

### What is actually happening?
https://ant.design/docs/react/introduce-cn

**Comment by yesmeck** [comment]
使用代理，或者访问国内镜像 http://ant-design.gitee.io
