### ISSUE TITLE
How to set up the Checkbox value? like Select LabelInValue?

### ISSUE THREAD

**Issue by walkinMrwang** [ant-design/ant-design#9626]
### Version
3.2.3

### Environment
chrome

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
```javascript
<CheckboxGroup  LabelInValue  onChange={(value) => this.handleCheckBoxChange('GradeList', value)} >
                                {getCheckbox(GradeList)}
</CheckboxGroup>


```

### What is expected?
Checkbox和CheckboxGroup都能设置LabelInValue, 

### What is actually happening?
Checkbox和CheckboxGroup都不能设置LabelInValue,

**Comment by afc163** [comment]
Why do you need that? What problem you meet?

**Comment by walkinMrwang** [comment]
我需要根据checkbox值生成table, label作为行名称，value作为值。生成好的table确定后向后台提交数据。现在我只能先生成const newData={label:value,...} 进行反选操作 name=newData[checkboxValue]

**Comment by yesmeck** [comment]
自己维护一个 label、value 的 map 就可以了。
