### ISSUE TITLE
feature requests：New property of   DatePicker component to support set the date length limitations, like no more than 7 days?

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#9629]
### Version
3.2.3

### Environment
mac, chrome

### Reproduction link
[https://codepen.io/anon/pen/JLdaGv](https://codepen.io/anon/pen/JLdaGv)

### Steps to reproduce
Requirement: Need to limit the length of the date range to no more than 7 days. (日期选择器的选择时间不超过7天)
Question: How to make this feature happen? Is there any property of the DatePicker component that supports this feature?

### What is expected?
Need to limit the length of the date range to no more than 7 days

### What is actually happening?
No such property  of the DatePicker component that supports this feature

**Comment by yesmeck** [comment]
You can use `disabledDate` to limit user which dates can be selected.

**Comment by Aggie123** [comment]
Ok, I see. 
So we ca only calculate in advance and then use disabledDate property? No direct property to set the date length?
