### ISSUE TITLE
when there is a input  in Select Component,how to let this input be editable

### ISSUE THREAD

**Issue by zjdschnappi** [ant-design/ant-design#9630]
### Version
3.1.6

### Environment
win10  chrome 版本 64.0.3282.186（正式版本） （64 位） react 16.2

### Reproduction link
[https://jsfiddle.net/zjdschnappi/Lxh4cvL6/28/](https://jsfiddle.net/zjdschnappi/Lxh4cvL6/28/)

### Steps to reproduce
Click the input component in the drop-down list

### What is expected?
the input component can be editable

### What is actually happening?
it cannot be focus or be editable

**Comment by afc163** [comment]
Try `dropdownRender`.

**Comment by NevenLiang** [comment]
Try this， [auto-complete](https://ant.design/components/auto-complete/#components-auto-complete-demo-non-case-sensitive)
