### ISSUE TITLE
table 的header 和 footer 是否可以向对于浏览器fixed; 

### ISSUE THREAD

**Issue by biology-w** [ant-design/ant-design#9635]
### What problem does this feature solve?
当数据列表非常多的时候（列数据和行数据很多），fixed（相对于浏览器fixed） table 的header 和 footer  可以使用户更好的浏览阅读。
(不是固定了table 中body的高后 使得 header 和 footer在某个位置)

### What does the proposed API look like?
headerStyle={{fixed: true, top: number, right: number, left: ...}}

**Comment by dengfuping** [comment]
@biology-w You can use like `scroll={{ y: 240 }}` to achieve your requirement as the demo https://codesandbox.io/s/nwl36qk4zl shows.
