### ISSUE TITLE
formitem下面的upload组件 的问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9637]
### Version
3.2.3

### Environment
windows10 chrome react 16.2.20

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
upload组件在formitem里面如何配合呢？我发先formitem里面的值是一个object 里面有file 和filelist 这个和upload的组件是一样的。但是我后端代码只需要一个url 地址，还有就是我的upload 移除的时候，formitem的value并没有移除。
代码如下：
```
  <FormItem {...Constant.formItemLayout} label="LOGO">
          {this.getFieldDecorator('logo', {
            initialValue: this.currentSetting.logo,
            rules: [{
              required: true, validator: this._validatorLogoUpdate,
            }],
          })(
            <Upload
              action="/file/upload"
              beforeUpload={this.handleLogoBeforeUpload}
              onChange={this.handleLogoOnChange}
              listType="picture-card"
              fileList={logoFileList}
              accept="image/*"
            >
              {logoFileList.length >= 1 ? null : logoUploadButton}
            </Upload>
          )}
 </FormItem>
```
这里我初始化的logo是有用的，但是当我删除上传的文件，再上传一次，那么这个logo的值变成了一个对象，而且在onRemove的时候，并不会移除这个值，我现在只有在表单提交的时候，把这个form的json拿出来，然后再赋值给要传递的参数集合。。

### What is expected?
期望我用upload传值之后，formitem就可以自动把值改成url，而不是那么JSON对象

### What is actually happening?
获取的是json对象

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6699

**Comment by xgj1988** [comment]
@afc163  哥们还有一个问题，我用codesandbox 他一直是resove depence ...这个怎么破啊，，我其实想给你们写demo 但是一直是这个，我很无语。，

**Comment by afc163** [comment]
尝试翻墙或者使用 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by xgj1988** [comment]
@afc163  3Q

**Comment by xgj1988** [comment]
@afc163  初始化值如何设置呢？
我是这样的
  ```
/**
   * 初始化logo
   * @private
   */
  _initLogoInfo = (logoUrl) => {
    this.setState({
      logoFileList: [{uid: -1, url: logoUrl, name: 'logo', status: 'done'}],
    });
  }
```

logoUrl 是后端传回的logo的url 地址。我是构造了一个fileList出去，但是这样感觉有点low，不知道怎么解决。

**Comment by sir-ran** [comment]
> @afc163 初始化值如何设置呢？
> 我是这样的
> 
> ```
> /**
>  * 初始化logo
>  * @private
>  */
> _initLogoInfo = (logoUrl) => {
>   this.setState({
>     logoFileList: [{uid: -1, url: logoUrl, name: 'logo', status: 'done'}],
>   });
> }
> ........
> <FormItem {...Constant.formItemLayout} label="LOGO">
>         {this.getFieldDecorator('logo', {
>           valuePropName: 'fileList',
>           rules: [{
>             required: true, validator: this._validatorLogoUpdate,
>           }],
>         })(
>           <Upload
>             action="/file/upload"
>             beforeUpload={this.handleLogoBeforeUpload}
>             onChange={this.handleLogoOnChange}
>             listType="picture-card"
>             fileList={logoFileList}
>             accept="image/*"
>           >
>             {logoFileList.length >= 1 ? null : logoUploadButton}
>           </Upload>
>         )}
>       </FormItem>
> ```
> 
> logoUrl 是后端传回的logo的url 地址。我是构造了一个fileList出去，但是这样感觉有点low，不知道怎么解决。
> 
> 以上代码 会有一个警告： index.js?8b55:2177 Warning: `getFieldDecorator` will override `fileList`, so please don't set `fileList` directly and use `setFieldsValue` to set it.
> 我把 fileList={logoFileList} 这句话删除了，就没这个警告，但是upload的默认值就不显示了。

我也遇到了这个问题，控制台报这个警告，你后面是怎么解决的？

**Comment by SilentFlute** [comment]
decoratorOption: {
                valuePropName: 'fileList',
                initialValue: logoFileList
              },
<Upload/>中不需要再传fileList={logoFileList}

**Comment by SilentFlute** [comment]
1.
decoratorOption: {
            valuePropName: 'fileList',
            initialValue: logoFileList
          },
2.
删除Upload组件中的fileList={logoFileList}， Upload组件中中不需要再传fileList={logoFileList}

**Comment by SiegeSailor** [comment]
> decoratorOption: {
> valuePropName: 'fileList',
> initialValue: logoFileList
> },
> 2.
> 删除Upload组件中的fileList={logoFileList}， Upload组件中中不需要再传fileList={logoFileList}

Your answer saved my day...but I am just wondering the reason why **Upload** doesn't even need to set fileList? It looks like **Upload** stores the fileList somewhere when the form uses `getFieldDecorator(valuePropName)`.

I use `form.setFieldsValue` to change my `Upload` fileList value in my form.
