### ISSUE TITLE
table组件固定表头字段过多时，希望出现横向滚动条 而不是列变高了

### ISSUE THREAD

**Issue by zzwar2009** [ant-design/ant-design#9638]
### What problem does this feature solve?
个人认为这个可能是bug, table组件固定表头字段过多时，希望出现横向滚动条 而不是列变高了
demo效果如下：https://codepen.io/zzwar2009/pen/RMPdYB
图片效果如下：
![image](https://user-images.githubusercontent.com/2322990/37279162-eb1d865a-2624-11e8-9060-559c2b1cf2a0.png)

### What does the proposed API look like?
不用新api,兼容即可

**Comment by yesmeck** [comment]
可以自己通过 CSS 设置是否换行，使用 `scroll.x` 实现滚动。
