### ISSUE TITLE
Input.Search render both default Button and enterButton's Reactnode

### ISSUE THREAD

**Issue by hxuanhung** [ant-design/ant-design#9639]
### Version
3.3.0

### Environment
Mac, chrome, firefox

### Reproduction link
[https://codesandbox.io/s/32pv456oq](https://codesandbox.io/s/32pv456oq)

### Steps to reproduce
add enterButton={<button type="button">Button</button>} to Input.Search

### What is expected?
two buttons are rendered.

### What is actually happening?
Should only render the given button instead the default one at the same time.

**Comment by chillyistkult** [comment]
So the issue is still there?

**Comment by hxuanhung** [comment]
no I think it's fixed.
