### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#9640]
### Version
3.3.0

### Environment
系统版本

### Reproduction link
[https://ant.design/components/alert-cn/](https://ant.design/components/alert-cn/)

### Steps to reproduce
更新日志
🌟 Alert 组件新增 afterClose 属性，用于实现更流畅的关闭效果。

### What is expected?
文档有 afterClose 属性说明

### What is actually happening?
文档没有 afterClose 属性说明

**Comment by dengfuping** [comment]
@kaoding PR welcome. You can refer to the associated PR #9448.
