### ISSUE TITLE
Right-side Sider Trigger

### ISSUE THREAD

**Issue by arist0tl3** [ant-design/ant-design#9644]
### What problem does this feature solve?
Enables a collapsible sider for the right side.

Currently, if the sider is on the right hand side of the screen, the trigger is positioned as if the sider was on the left hand side:

https://codesandbox.io/s/73j86r15x0

### What does the proposed API look like?
```
<Sider
  collapseRight
</Sider>
```

**Comment by afc163** [comment]
Try rtl mode: https://ant.design/components/layout?direction=rtl#components-layout-demo-custom-trigger
