### ISSUE TITLE
Modal footer submit button cannot trigger Form submit

### ISSUE THREAD

**Issue by kevinkam** [ant-design/ant-design#9649]
### What problem does this feature solve?
I put submit function on onOk props in Modal, and inside the Modal there have a Form, but when I press enter, it will not trigger submit event of the Form, but click ok button will trigger submit.

### What does the proposed API look like?
should trigger form submit in Modal Form while press enter.

**Comment by yesmeck** [comment]
If you are reporting a bug, please use the bug template.

**Comment by ToJen** [comment]
@kevinkam were you able to solve this?

**Comment by kevinkam** [comment]
@ToJen
I put an invisible submit button inside Form.
Like this
<Form><button type=“submit” style={{display: ‘none’}} /></Form>
