### ISSUE TITLE
Form 是否能提供个参数让其设置默认 messages？

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#965]
Form 组件用到了 async-validate，在 createForm 的时候是否允许传入个 messages 参数，直接将中文的错误条件设置好，这样在表单验证条件里面就不需要写那些默认的错误信息了。

**Comment by benjycui** [comment]
http://ant.design/components/form/#demo-validate-basic

现在应该可以满足你的需求的，自动根据 async-validate 的 errors 生成提示信息。

**Comment by benjycui** [comment]
长时间无反馈。

**Comment by yixiudadi** [comment]
我也有同样的需求，错误信息单个汉化太麻烦了，能否提供一个全局配置方法。配置相关的中文提示信息

**Comment by benjycui** [comment]
See: https://github.com/react-component/form#createformoption-object--wrappedcomponent-reactcomponent--reactcomponent

https://github.com/react-component/form/blob/08d3c158ebd1a373cae735f9faf045ee954408e3/tests/createForm.spec.js#L27-L29

**Comment by feibi** [comment]
错误信息可否不显示字段名
