### ISSUE TITLE
有的Select下拉选在展开时 有明文字显抖动现象 （尤其是带搜索功能时）

### ISSUE THREAD

**Issue by pkl93** [ant-design/ant-design#9650]
### Version
3.3.0

### Environment
win10 chrome64.0.3282.186

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
点击antd下拉选， 展开下拉菜单时再现 （不是所有都会），比如这个提issue页面的头两个下拉选。 
TreeSelect 带搜索，有一层子级时问题特别明显。
带搜索框及选项多的时候也很明显。

### What is expected?
正常稳定的展开

### What is actually happening?
展开时发生文字抖动

---
虽然不影响正常使用，但感觉展开时整个下拉选都在抖动，很不舒服，希望能够解决。

**Comment by yesmeck** [comment]
没发现你说的问题，能录个屏吗？

**Comment by RoselinOldham** [comment]
https://www.youtube.com/watch?v=RDrfE9I8_hs
