### ISSUE TITLE
IE Popover bug:  <Input/> in content will blur after type 

### ISSUE THREAD

**Issue by geraldchen890806** [ant-design/ant-design#9652]
### Version
3.3.0

### Environment
ie11

### Reproduction link
[https://codepen.io/geraldchen89/pen/PRPBdd](https://codepen.io/geraldchen89/pen/PRPBdd)

### Steps to reproduce
click button, can't input continuously

### What is expected?
input continuously

### What is actually happening?
can't input continuously

---
chrome is ok

**Comment by yesmeck** [comment]
Related #9329

**Comment by geraldchen890806** [comment]
fixed by:  https://codepen.io/geraldchen89/pen/QmjVvj
but hope to fix this by <Popover />

**Comment by geraldchen890806** [comment]
fixed by https://codepen.io/geraldchen89/pen/PRPBdd
but hope to fixed this in Popover

**Comment by yesmeck** [comment]
Reinstall node_modules.
