### ISSUE TITLE
Can't open ant-design homepage

### ISSUE THREAD

**Issue by JoeyKo** [ant-design/ant-design#9660]
### Version
3.3.0

### Environment
chrome

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
https://ant.design/

### What is expected?
能够打开首页

### What is actually happening?
首页无法访问

**Comment by iHearty** [comment]
我们这边也遇到同样问题，文档打不开，请问是什么原因？
https://ant.design/docs/react/introduce-cn

**Comment by RyanPro** [comment]
首页无法打开

**Comment by dengfuping** [comment]
@JoeyKo @iHearty @RyanPro http://ant-design.gitee.io

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9634#issuecomment-372231758

**Comment by iHearty** [comment]
@afc163 thanks for your works, but why this issue happened? what time that i can use http://ant.design again?

**Comment by afc163** [comment]
https://zh.wikipedia.org/wiki/%E7%AC%AC%E5%8D%81%E4%B8%89%E5%B1%8A%E5%85%A8%E5%9B%BD%E4%BA%BA%E6%B0%91%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A

**Comment by lijia321** [comment]
开完会了 官网还是打不开
