### ISSUE TITLE
How to use Icon in textField

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [ant-design/ant-design#9661]
### What problem does this feature solve?
Sometimes, we want to use icon in textField (just like in value or placeHolder)

### What does the proposed API look like?
The same as ant-design-pro's login page (the icon in userName input and password input)

**Comment by yesmeck** [comment]
No, you can't.

**Comment by yesmeck** [comment]
You can refer to Ant Design Pro's code.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Can use Icon as a plain text?
