### ISSUE TITLE
InputNumber maybe provide a counter style like zen UI

### ISSUE THREAD

**Issue by buxuku** [ant-design/ant-design#9667]
### What problem does this feature solve?
That I can click the counter or stepper easier
![tim 20180314140733](https://user-images.githubusercontent.com/7866330/37385890-16738526-2791-11e8-8a74-2daa7cd85228.png)

@[NumberInput](https://www.youzanyun.com/zanui/zent/en/component/number-input)
### What does the proposed API look like?
```
<InputNumber showCounter />
```

**Comment by afc163** [comment]
It is a design-orientation decision, I think we will pass it, thank you for reporting.
