### ISSUE TITLE
WeekPicker的dateRender不起作用

### ISSUE THREAD

**Issue by Averey** [ant-design/ant-design#9668]
按照ant的文档， dateRender 为公用方法，但我在WeekPicker里传入回调方法后在渲染日历时并没有回调 dateRender
![image](https://user-images.githubusercontent.com/3632515/37388134-3b8fa49e-279a-11e8-8b22-3b6beb2d3729.png)

**Comment by rashmimh** [comment]
facing the same issue. Any breakthrough?
