### ISSUE TITLE
dateRender doesn't invoked by WeekPicker

### ISSUE THREAD

**Issue by Averey** [ant-design/ant-design#9669]
according to the antd docs, dateRender is a common api for WeekPicker. However, the dateRender callback doesn't invoke when the WeekPicker was rendered.
![image](https://user-images.githubusercontent.com/3632515/37388358-183e41d4-279b-11e8-8bf3-58602bc2ffee.png)

**Comment by rashmimh** [comment]
facing the same issue. Any breakthrough?

**Comment by xrkffgg** [comment]
https://ant.design/components/date-picker/#API
