### ISSUE TITLE
upload组件中文参数乱码

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#967]
后台是java

**Comment by dyf2015** [comment]
解决了，java中对参数处理 new String(type.getBytes("ISO-8859-1"),"utf-8");

**Comment by longhuasishen** [comment]
你们这个不会有跨域的问题么upload组件，我们用的springmvc，upload的action发请求过去会跨域啊

**Comment by benjycui** [comment]
跨域问题不是来自 Upload 也不是 SpringMVC，而在于应用架构的设计，自行 Google 下方案？

**Comment by longhuasishen** [comment]
解决了，是SpringMvc默认不支持options方式请求，需要开启，而upload跨域默认会发一次options试探请求，导致拒绝访问
