### ISSUE TITLE
Clear component Table pagination params doesn't work

### ISSUE THREAD

**Issue by xchunzhao** [ant-design/ant-design#9671]
### Version
3.3.0

### Environment
MacOS10.12 Chrom 64.0 React 16.2.0

### Reproduction link
[https://codepen.io/xchunzhao/pen/GxoBLd?editors=0010](https://codepen.io/xchunzhao/pen/GxoBLd?editors=0010)

### Steps to reproduce
Clear button above table

### What is expected?
Expect that the pagination param can be clear

### What is actually happening?
Actually the param `pagination ` in console is my expected value , but the page view  cannot be the actual result.

**Comment by yupeilin123** [comment]
You should add a method for `onChange` in the pagination

**Comment by xchunzhao** [comment]
@yupeilin123 The method `onChange` is designed to handle change page not to make pagination not shown.

**Comment by xchunzhao** [comment]
@yupeilin123 Sorry, my fault. Clear pagination should set pagination `false` not `empty object`
