### ISSUE TITLE
When I reset treeData, the TreeSelect will still record my previous development.

### ISSUE THREAD

**Issue by dingwufu** [ant-design/ant-design#9672]
### Version
3.0.0

### Environment
Chrome 64.0.3282.186

### Reproduction link
[https://codepen.io/dingwufu/pen/wmMYaM?editors=0010](https://codepen.io/dingwufu/pen/wmMYaM?editors=0010)

### Steps to reproduce
1. Load data, expand an item to load data asynchronously.
2.Switching another Select allows the TreeSelect data to be the new treeData.
3.Continue to switch back to the original value via Select, and click to view the TreeSelect.

### What is expected?
I hope that some operations will clear the expandkys of the TreeSelect. And the TreeSelect will not record the expansion of the original data, and the icon will not point downward.

### What is actually happening?
The data item icon previously expanded in the TreeSelect will be pointing downwards

---
The data using the TreeSelect relies on an external property value, and the state in the TreeSelect is initialized when the property value is modified.

**Comment by zombieJ** [comment]
Thanks for feedback.
@yesmeck ， how do u think about provide expandedKey trans from `SelectTrigger` to `TreeSelect` so that user can manage it if needed.

**Comment by dingwufu** [comment]
Thanks for your reply.

**Comment by aco711** [comment]
Is there any way to reset expanded dropdowns (Checkable) when TreeSelect is not in focus?

**Comment by zombieJ** [comment]
@aco711 , for current version we didn't provide the API of that. Since TreeSelect refactored in `3.7.0`, we will provide it after TreeSelect be stable.

**Comment by zombieJ** [comment]
Close since `rc-tree-select@2.0.9` updated in `3.7.0`
