### ISSUE TITLE
Card Componetn attribute title the value overtop width is not show ellipsis

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design#9673]
### Version
3.3.0

### Environment
Mac OS 10.13.3、Chrome 64.0.3282.186、base umijs 1.0.6

### Reproduction link
[https://github.com/smithyj/oa.yangyj.com](https://github.com/smithyj/oa.yangyj.com)

### Steps to reproduce
npm start and see

### What is expected?
attribute title value overflow width is show ellipsis

### What is actually happening?
Card Componetn attribute title the value overflow width is not show ellipsis

**Comment by smithyj** [comment]
I found that the ant-list-item style removes the display ellipsis, this is bug?

**Comment by smithyj** [comment]
I have already reproduced https://codesandbox.io/embed/jplxp084k3

**Comment by dengfuping** [comment]
@smithyj You need to set the card's `width` as the demo https://codesandbox.io/s/mzk610y998 shows.

**Comment by smithyj** [comment]
this is a bad solution，i suggest delete style `display:flex` in class `.ant-list-item`

**Comment by smithyj** [comment]
Because there is no way to be responsive

**Comment by dengfuping** [comment]
@smithyj I think it's a correct way to achieve your demand. If there is no `width` restrict, ellipsis won't display.
