### ISSUE TITLE
Progress type circle no animation when percentage changes from 0

### ISSUE THREAD

**Issue by tijp** [ant-design/ant-design#9676]
### Version
3.3.0

### Environment
All browsers, only tested on macOS

### Reproduction link
[https://codesandbox.io/s/3y70vqyyv6](https://codesandbox.io/s/3y70vqyyv6)

### Steps to reproduce
1. Create a Progress component with type 'circle' and percentage 0
2. Change percentage from 0 to a different value (for example 100)

### What is expected?
It is expected to show an animation. It does show an animation when the percentage changes from 1 to for example 100. It does not show an animation when the percentage changes from 0 to 100. This looks laggy.

### What is actually happening?
No animation is shown, and after about a second the circle will fill the bar.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/progress/pull/80
