### ISSUE TITLE
How to get the value of datepicker?

### ISSUE THREAD

**Issue by s1031432** [ant-design/ant-design#9677]
index.html：
https://gist.github.com/s1031432/da4a2900998edef35d403cef5f7a2aa9
index.js：
https://gist.github.com/s1031432/5e9b5bf3216e0794369c02718d8588b6

I make a datepicker from ant-design,
but I have a question that is I don't know how to get value of datepicker.

My datepicker image：
https://i.imgur.com/m2B8m7y.png

For example, I want to get "2018-03-14 20:32:23" and "2018-03-15 20:32:26",
but I don't know how to get.
I know document.getElementByID(), but now I don't know the ID of datepicker.
What should I do to get the value of datepicker?

**Comment by s1031432** [comment]
I solve this problem.
I set a hidden input id=time in my index.html.
and set a javascript.
when value of datepicker was change.
update time.value

**Comment by afc163** [comment]
You should learn React first.

**Comment by felipevegaaraujo** [comment]
@afc163 that was mean
