### ISSUE TITLE
How to get the value of datepicker?

### ISSUE THREAD

**Issue by s1031432** [ant-design/ant-design#9678]
### What problem does this feature solve?
I make a datepicker from ant-design,
but I have a question that is I don't know how to get value of datepicker.

My datepicker image：
https://i.imgur.com/m2B8m7y.png

For example, I want to get "2018-03-14 20:32:23" and "2018-03-15 20:32:26",
but I don't know how to get.
I know document.getElementByID(), but now I don't know the ID of datepicker.
What should I do to get the value of datepicker?

### What does the proposed API look like?
index.html：
https://gist.github.com/s1031432/da4a2900998edef35d403cef5f7a2aa9
index.js：
https://gist.github.com/s1031432/5e9b5bf3216e0794369c02718d8588b6

**Comment by yesmeck** [comment]
建议先学习下 React
