### ISSUE TITLE
Breadcrumb 路径有点问题

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#968]
![qq 20160201095716](https://cloud.githubusercontent.com/assets/433259/12707411/fd693cd8-c8ce-11e5-94d8-db566b9c44a4.png)

都是 `/`

**Comment by a805883237** [comment]
我也是这个问题，其中manage是根目录：http://localhost:3000/manage/manage/manage/manage/manage/manage/manage/manage/manage/manage/manage/manage/manage/manage/userReview
