### ISSUE TITLE
当使用upload的listType选择picture-card时出现问题

### ISSUE THREAD

**Issue by DevilViy** [ant-design/ant-design#9681]
### Version
3.3.0

### Environment
操作系统：imac
浏览器：chrome

### Reproduction link
使用ant.design线上的upload组件进行测试
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
```
import { Upload, Icon, Modal } from 'antd';

class PicturesWall extends React.Component {
  state = {
    previewVisible: false,
    previewImage: '',
    fileList: [{
      uid: -1,
      name: 'xxx.png',
      status: 'done',
      url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
    }],
  };

  handleCancel = () => this.setState({ previewVisible: false })

  handlePreview = (file) => {
    this.setState({
      previewImage: file.url || file.thumbUrl,
      previewVisible: true,
    });
  }

  handleChange = ({ fileList }) => this.setState({ fileList })

  render() {
    const { previewVisible, previewImage, fileList } = this.state;
    const uploadButton = (
      <div>
        <Icon type="plus" />
        <div className="ant-upload-text">Upload</div>
      </div>
    );
    return (
      <div className="clearfix">
        <Upload
          action="//jsonplaceholder.typicode.com/posts/"
          listType="picture-card"
          fileList={fileList}
          onPreview={this.handlePreview}
          onChange={this.handleChange}
        >
          {fileList.length >= 3 ? null : uploadButton}
        </Upload>
        <Modal visible={previewVisible} footer={null} onCancel={this.handleCancel}>
          <img alt="example" style={{ width: '100%' }} src={previewImage} />
        </Modal>
      </div>
    );
  }
}

ReactDOM.render(<PicturesWall />, mountNode);
```
### What is expected?

解决上传文件过大，点击叉号的取消延迟问题（ps:上传用的是TelegramMac的安装包，大概20兆，

![test3](https://user-images.githubusercontent.com/21967852/37440866-9fceb234-2839-11e8-8949-7db1f0821676.gif)

上传文件中：
![xnip2018-03-74_09-57-27](https://user-images.githubusercontent.com/21967852/37440893-c3853be4-2839-11e8-9636-bccbcf9e05d0.jpg)

点击上传文件的叉号会出现比较明显的延迟：
![xnip2018-03-74_09-59-06](https://user-images.githubusercontent.com/21967852/37440932-f0d35f22-2839-11e8-8587-faec31c68b04.jpg)

### What is actually happening?
待解决

**Comment by dengfuping** [comment]
@DevilViy I cannot reproduce your problem here. Could you supply your browser's type and version?

**Comment by DevilViy** [comment]
@dengfuping  sorry，my browser is chrome 

![image](https://user-images.githubusercontent.com/21967852/37563650-7eccfeea-2ac0-11e8-971d-6842ab9e80a9.png)

and I try it again
![upload2](https://user-images.githubusercontent.com/21967852/37563636-18725460-2ac0-11e8-9f63-4e082615ebc4.gif)

**Comment by afc163** [comment]
@zswang 

https://github.com/ant-design/ant-design/pull/9621

**Comment by dengfuping** [comment]
@DevilViy No problem was found still and my chrome version is `65.0.3325.162` as same as you.

![2018-03-18 17_13_19](https://user-images.githubusercontent.com/14918822/37564387-f46c9714-2acf-11e8-8c24-63158745c031.gif)

**Comment by DevilViy** [comment]
You can try to upload the file which is about 40M

**Comment by dengfuping** [comment]
@DevilViy In fact, I have tried to upload the file whose size is up to 1GB and everything is ok still.

**Comment by DevilViy** [comment]
e..., tomorrow I change a computer to upload the file again

**Comment by DevilViy** [comment]
Maybe I found the reason for this problem

- When I installed this AdBlock extension

![uploadadg](https://user-images.githubusercontent.com/21967852/37576831-3fd15ce6-2b69-11e8-8710-ce793957531b.gif)

- When I remove this AdBlock extension

![uploadnoad](https://user-images.githubusercontent.com/21967852/37576860-6b47167c-2b69-11e8-89a5-fb707b547377.gif)


But I still hope to solve this problem
