### ISSUE TITLE
UI looks weird when setting buttons in an button group to small size

### ISSUE THREAD

**Issue by ycczkl** [ant-design/ant-design#9683]
### Version
3.3.0

### Environment
macos10.10.5, chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Reproduction link
[https://codesandbox.io/s/w0m36w13vk](https://codesandbox.io/s/w0m36w13vk)

### Steps to reproduce
Create an buttons inside an button group. set the button size to small

~~~
  <div>
    <br />
    <br />
    <ButtonGroup>
      <Button size="small">BTN1</Button>
      <Button size="small">BTN2</Button>
      <Button size="small">BTN3</Button>
      <Button size="small">BTN4</Button>
    </ButtonGroup>
    <br />
    <br />
    <ButtonGroup>
      <Button>BTN1</Button>
      <Button>BTN2</Button>
      <Button>BTN3</Button>
      <Button>BTN4</Button>
    </ButtonGroup>
  </div>,
~~~

### What is expected?
The text should be in middle of the button

### What is actually happening?
The text is close to bottom when button size is set to small

![image](https://user-images.githubusercontent.com/6109663/37443374-083c85a6-27c9-11e8-89b5-6e3d4ad14c98.png)

**Comment by afc163** [comment]
Try this:

```jsx
    <ButtonGroup size="small">
      <Button>BTN1</Button>
      <Button>BTN2</Button>
      <Button>BTN3</Button>
      <Button>BTN4</Button>
    </ButtonGroup>
```

**Comment by ycczkl** [comment]
@afc163 worked as expected. thanks
