### ISSUE TITLE
When I use the select component, the defaultValue does not display correctly.

### ISSUE THREAD

**Issue by mintsweet** [ant-design/ant-design#9684]
### Version
3.3.0

### Environment
win10, chrome65

### Reproduction link
[https://codesandbox.io/s/nkyy198l5p](https://codesandbox.io/s/nkyy198l5p)

### Steps to reproduce
  - 加载外部数据或者异步请求的数据
  - 根据数据动态生成select组件的option
  - 默认值设定为其中一个option的值

### What is expected?
展示option值所对应的子节点，比如name之类的

### What is actually happening?
直接展示了默认值，当前组件的数据没有问题。

---
需要动态生成option的时候，默认值显示不对，总是显示的值，而不是值所对应的name

**Comment by yesmeck** [comment]
Use `labelInValue`.

**Comment by mintsweet** [comment]
好像不可以诶，使用`labelInValue`，我的默认值选项需要手动指定`label`的值，不指定还是不能正确显示，但是`label`的值是异步回调回来的呀，一开始我并不知道是什么...

**Comment by yesmeck** [comment]
如果你都不知道，那组件更不知道了。

**Comment by mintsweet** [comment]
懵逼，Sorry.....

**Comment by yesmeck** [comment]
看起来是有问题，能不能把 codesanbox 还原到原来的代码？

**Comment by mintsweet** [comment]
[最开始的代码](https://codesandbox.io/s/nkyy198l5p)
是这样的，我是能知道我的数据是有什么，但是最开始渲染的时候没有数据呀，所以我没法取到数据列表的其中一条数据的一个字段...不知道我这么说对不对...

**Comment by yesmeck** [comment]
不好意思，第一眼看错了，是 bug，跟 #9445 是同一个问题。

**Comment by mintsweet** [comment]
麻烦啦
