### ISSUE TITLE
Select 的 anticon-select-arrow 不在官方图标库里

### ISSUE THREAD

**Issue by ruoqianfengshao** [ant-design/ant-design#9686]
### Version
3.3.0

### Environment
antd@3.3.0

### Reproduction link
[http://ant-design.gitee.io/components/select-cn/](http://ant-design.gitee.io/components/select-cn/)

### Steps to reproduce
1. 将官方图标库完整 copy 到自己的 iconfont 项目，这里是官方图标库：http://www.iconfont.cn/collections/detail?cid=7944
2. 把@icon-url替换掉，并在 html中引入 css
3. select 组件用的箭头图标不在官方库里，即无法显示

### What is expected?
希望能提供 anticon-select-arrow 官方的图标

### What is actually happening?
没找到官方图标

**Comment by afc163** [comment]
<img width="104" alt="image" src="https://user-images.githubusercontent.com/507615/37447808-b290faa6-285e-11e8-8344-d8edd0e87834.png">

**Comment by ruoqianfengshao** [comment]
@afc163 这个 icon 已经存在了，然而和 select 里用的icon name是不一致的，是否意味着需要手动修改 icon name?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/9d7d70becdc2eb1406575a56c9576a68d221ef3f/components/select/style/index.less#L71

这里用的是 unicode 来实现的。

**Comment by ruoqianfengshao** [comment]
@afc163 嗯，thx，我也发现了。只能直接覆盖了

**Comment by Ale-cc** [comment]
.ant-select-combobox .ant-select-arrow{
      display: block;
    }
