### ISSUE TITLE
table with fixed left column display with the border when set size = small and scroll.x

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#9687]
### Version
3.3.0

### Environment
win10 chrome63.0.3239.132

### Reproduction link
[https://codesandbox.io/s/ly739xj1xz](https://codesandbox.io/s/ly739xj1xz)

### Steps to reproduce
无

### What is expected?
Display the border

### What is actually happening?
Do not display a border

**Comment by tim-soft** [comment]
I've observed the same issue, but just with a fixed right column. I feel like this was fixed a few releases back but has returned in the last two or three releases.

**Comment by afc163** [comment]
Fixed #12015 and #11033 too
