### ISSUE TITLE
Table组件的data中的children为空数组时展开按钮还在

### ISSUE THREAD

**Issue by PengJiyuan** [ant-design/ant-design#9689]
### Version
3.3.0

### Environment
node v8.4.0, chrome 64.0.3282.186, antd 3.2.1

### Reproduction link
[https://codesandbox.io/s/xjoxqxvr0q](https://codesandbox.io/s/xjoxqxvr0q)

### Steps to reproduce
Table组件的data中的children为空数组时展开按钮还在。
当从api中拿数据的时候，不可避免的有时候会有children字段，为空的话也会显示展开的按钮，有点儿困扰。

### What is expected?
当data中的children为[]的时候不显示展开按钮

### What is actually happening?
当data中的children为[]的时候会显示展开按钮

**Comment by yesmeck** [comment]
Tagging as `good first issue`

**Comment by afc163** [comment]
不是 bug。点击动态加载数据时，数据未加载前也需要展示展开按钮。

**Comment by afc163** [comment]
Duplicate of #1365
