### ISSUE TITLE
TreeSelect customize the render selected item in the text box

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#9696]
### What problem does this feature solve?
TreeSelect customize the render selected item in the text box(就是自定义展示选中内容在文本框,特别是多选,或者固定一段文本在那里.)

### What does the proposed API look like?
```
<TreeSelect  showCheckedStrategy='请选择'>
  
</TreeSelect>
```

**Comment by yesmeck** [comment]
You can use `treeNodeLabelProp`.
