### ISSUE TITLE
在有Sider的情况下Content组件Width返回整个Window的宽度值

### ISSUE THREAD

**Issue by itachieve** [ant-design/ant-design#9698]
### Version
3.3.0

### Environment
windows10/macOS Sierra, Chrome 60.0.3112.101 version, react 16.2.0

### Reproduction link
[https://codesandbox.io/s/7kxn4oy68j](https://codesandbox.io/s/7kxn4oy68j)

### Steps to reproduce
代码一再重现链接中 全部写完

### What is expected?
在ComponentDidMount的console.log中返回 Window width 减掉 Sider Width

### What is actually happening?
实际结果返回值为Window 的width

**Comment by afc163** [comment]
You can try `hasSider` of Layout or `setTimeout` in componentDidMount to get the right width of sider.

https://codesandbox.io/s/vvmm003zvy

**Comment by itachieve** [comment]
@afc163 Sorry for being a new bee, but just wondering why it is needed to setTimeout ?
