### ISSUE TITLE
TreeSelect 组件属性treeNodeLabelProp

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#9701]
### What problem does this feature solve?
treeNodeLabelProp这个属性值能放开吗?现在只能写'title'和'value'绑定了对应的值,我现在的需求是不管选了什么都是显示'请选择节点'之类的,总之就是放开--Sorry for my poor english.

### What does the proposed API look like?
```
<TreeSelect treeNodeLabelProp='请选择节点' />
```

![avatar](https://pic4.zhimg.com/80/v2-db7956eb7b1ea2794dba7c0dca3a695b_hd.jpg)

**Comment by hqzh** [comment]
https://github.com/ant-design/ant-design/issues/9696感觉这个issue我没说明白

**Comment by zombieJ** [comment]
意思是Node1 Node2 不显示？显示自定义文字？

**Comment by zombieJ** [comment]
┌──────────┐
│| Node1 | Node2 |----│
└──────────┘

变成 
┌──────────────┐
│| 请选择节点 | 请选择节点 |----│
└──────────────┘

还是 移除了选中内容，只有placeholder？
┌──────────────┐
│请选择节点- ------------------│
└──────────────┘

**Comment by hqzh** [comment]
│请选择节点│

**Comment by hqzh** [comment]
`.ant-select-search__field__placeholder {
     display: block !important;
  }
  .ant-select-selection__rendered {
       display: none !important;
  }
`
我是这么强制通过css处理的,但是这样选项多了点击下拉有抖动的现象

**Comment by hqzh** [comment]
而且好奇怪,我点击后面的text文本前面的选项框不勾选

**Comment by Sylvenas** [comment]
输入框里面的值为已经选中的某些Option,实在是太傻了，默认选中了三十行，样子看上去及其臃肿！

**Comment by yesmeck** [comment]
@Sylvenas 欢迎 PR https://github.com/ant-design/ant-design/issues/9117

**Comment by yesmeck** [comment]
Duplicate of #9117
