### ISSUE TITLE
Year Picker

### ISSUE THREAD

**Issue by thamjieying** [ant-design/ant-design#9702]
### What problem does this feature solve?
Select one year

### What does the proposed API look like?
A selector to select one whole year

**Comment by afc163** [comment]
Duplicate of #4524

**Comment by cwtuan** [comment]
Do need a Year Picker !

**Comment by cwtuan** [comment]
@afc163 

 #4524 提到用select代替，但是如果在年份不确定的情况下，不可能把所有年份的列出来在Select里。还是需要有YearPicker
