### ISSUE TITLE
upload show image bug

### ISSUE THREAD

**Issue by TnWah** [ant-design/ant-design#9707]
### Version
3.3.0

### Environment
谷歌版本 63.0.3239.132（正式版本）

### Reproduction link
[https://lljyn5poz9.codesandbox.io/](https://lljyn5poz9.codesandbox.io/)

### Steps to reproduce
const fileList = [{
      uid: -1,
      name: 'filename',
      status: 'done',
      thumbUrl: 'https://ocrjl5j3c.qnssl.com/qUPHxvkwCVb1521190315.jpg?imageView2/1/w/132/h/132`,
    }]
.......
render() {
............
<Upload {...uploadProps} fileList={fileList}>
   <Icon type="upload" />
</Upload>
}

### What is expected?
the image can show

### What is actually happening?
it can't

---
After seven cattle compressed image link does not display preview properly

**Comment by dengfuping** [comment]
@TnWah Your url doesn't conform to the validation rules. 
`thumbUrl: 'https://ocrjl5j3c.qnssl.com/qUPHxvkwCVb1521190315.jpg?imageView2/1/w/132/h/132'` => `thumbUrl: 'https://ocrjl5j3c.qnssl.com/qUPHxvkwCVb1521190315.jpg'`. https://github.com/ant-design/ant-design/blob/540b31fd0295783ab73a5454dafda4ae162ab186/components/upload/UploadList.tsx#L16
