### ISSUE TITLE
table filler统一重置暴露

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design#971]
**问题描述**
table filler统一重置接口暴露，参看下图的『统一重置filter』按钮的功能

如图：
![snip20160201_24](https://cloud.githubusercontent.com/assets/1179603/12709697/969ecc78-c8e9-11e5-99e1-6a386bbaad22.png)

**Comment by nikogu** [comment]
我勒个去，没人管了

**Comment by afc163** [comment]
事情很多，人太少，一步步来。。。
