### ISSUE TITLE
Spin component loads when its spinning property is 'undefined'.

### ISSUE THREAD

**Issue by patientayo** [ant-design/ant-design#9712]
### Version
3.3.0

### Environment
chrome

### Reproduction link
[https://codesandbox.io/s/93584zq7ro](https://codesandbox.io/s/93584zq7ro)

### Steps to reproduce
as codesandbox url.

### What is expected?
Spin should not load.

### What is actually happening?
it loads.

**Comment by yesmeck** [comment]
It's expected, when you pass `undefined` to `spinning`, react will use the default value `true`.
