### ISSUE TITLE
Select doesn't work as expected in combobox mode with labelInValue set

### ISSUE THREAD

**Issue by ukabuer** [ant-design/ant-design#9717]
### Version
3.3.0

### Environment
Win 10, Chrome 65

### Reproduction link
[https://codepen.io/anon/pen/OvRvNy?editors=0010](https://codepen.io/anon/pen/OvRvNy?editors=0010)

### Steps to reproduce
Select one option and check the text in `input`

### What is expected?
In `combobox` mode with `labelInValue` set, `label` attribute of Select's value should be Option's children rather than value.

### What is actually happening?
`label` attribute is Option's value rather than children.

**Comment by yesmeck** [comment]
It's expected, `labelInValue` can not be used in `combobox`.

**Comment by ukabuer** [comment]
Maybe you should point this out in the Select's document? I didn't find something related to this in the page
