### ISSUE TITLE
Layout.Sider does not support "style" prop (incorrect docs)

### ISSUE THREAD

**Issue by ericclemmons** [ant-design/ant-design#9719]
### Version
3.3.0

### Environment
MacOS High Sierra, Firefox Quantum

### Reproduction link
[https://github.com/ant-design/ant-design/blob/a0e161ccddd0797bb6277f99471cdfd220ae3609/components/layout/Sider.tsx#L204-L210](https://github.com/ant-design/ant-design/blob/a0e161ccddd0797bb6277f99471cdfd220ae3609/components/layout/Sider.tsx#L204-L210)

### Steps to reproduce
```
<Layout.Sider style={{ flex: "0 0 100%" }} />
```

### What is expected?
this.props.styles would take precedence over computed styles within Layout.Sider.

### What is actually happening?
Layout.Sider overrides explicit "style" prop

---
I was attempting to make a right Sider 50% width instead of an explicit value.

The documentation indicates that `style` is accepted, but doesn't indicate that in no way can you customize the computed values:
> https://ant.design/components/layout/#Layout.Sider

**Comment by awall** [comment]
Why was this closed? It's still a bug in the most recent version of Ant Design.

**Comment by HAMED-KHODJA-ABDELHAK** [comment]
> 
> 
> Why was this closed? It's still a bug in the most recent version of Ant Design.

China dictatorship ^^

**Comment by gogomogolo** [comment]
问题没有解决。你怎么关门了

The problem is not solved. Why did you closed?

**Comment by yoyo837** [comment]
Could you open a new issue for that?
