### ISSUE TITLE
RadioGroup className / style Props

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#9720]
### What problem does this feature solve?
I would like to tweak the width the RadioGroup buttons and need a style/className property

### What does the proposed API look like?
```<Radio.Group width={{width: '100%'}}>...</Radio.Group>```

**Comment by afc163** [comment]
They are both working.

https://codesandbox.io/s/zn2914mzxx

**Comment by pierre-b** [comment]
Thanks @afc163 it does indeed work. Probably a typo in my code.
