### ISSUE TITLE
RangePicker dosen't work properly with redux-form

### ISSUE THREAD

**Issue by AngelWayfarer** [ant-design/ant-design#9721]
### Version
3.3.0

### Environment
https://codesandbox.io

### Reproduction link
[https://codesandbox.io/s/9lzxo0xjzr](https://codesandbox.io/s/9lzxo0xjzr)

### Steps to reproduce
1. Pick some dates in the datepicker.
2. ry to change them.

### What is expected?
Date picker works properly like at step 1.

### What is actually happening?
TypeError
end.isSame is not a function

---
I have forked my example from here: https://codesandbox.io/s/jzyl70wpk
If datepicker added to there - all works fine.
After upgrating antd to 3.3.0 rangepicker crushes.

**Comment by AngelWayfarer** [comment]
I have understood that the first part of the problem is all the datepickers wait for a moment object and don't work with string. 

If we'll open the reproduction link in external window https://9lzxo0xjzr.codesandbox.io/ and use the redux debugger, we can see that the first attempt of picking dates looks like:
```
@redux-form/FOCUS
@redux-form/BLUR       <----- {..., payload: ''}
@redux-form/FOCUS
@redux-form/CHANGE <----- {...,payload: ['2018-03-14T20:10:05.632Z','2018-03-16T20:10:05.632Z']}
```

and the second attempt looks like this:
```
@redux-form/FOCUS
@redux-form/BLUR       <----- {..., payload: '2018-03-14'}
```

I figured out that the regular datepicker works the same, it crashes with redux-form, because it receives a  string-date on blur. I have converted the string into moment for DatePicker, but I can't do the same for the RangePicker, because I recieve only one value.

**Comment by yesmeck** [comment]
It seems a bug of redux-form.

**Comment by yesmeck** [comment]
redux-form read value from the parameter of `onFocus`, here is a workaround https://codesandbox.io/s/8nz3kzx4o8

**Comment by AngelWayfarer** [comment]
Thanks for the workaround!
I think that this kind of workarounds might be here https://codesandbox.io/s/jzyl70wpk
for all kinds of fields, this can be useful for many pepole!

**Comment by yesmeck** [comment]
@AngelWayfarer Added `RangePicker` to codesandbox.io/s/jzyl70wpk

**Comment by BorodinDK** [comment]
Summarizing:
You need added  preventDefault() on `onFocus` and `onBlur` in render function

```
const renderRangePicker = ({ input }) => (
  <RangePicker
    {...input}
    onFocus={e => e.preventDefault()}
    onBlur={e => e.preventDefault()}
  />
);
```
It's work form me
