### ISSUE TITLE
Input.Search 右侧搜索不能点击

### ISSUE THREAD

**Issue by AinolaLong** [ant-design/ant-design#9728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
当前版本

### Reproduction link
[http://ant.ilvon.cn/components/input-cn/](http://ant.ilvon.cn/components/input-cn/)
![image](https://user-images.githubusercontent.com/21746104/37580750-5494e69a-2b80-11e8-99bd-9e6fce075de0.png)

### Steps to reproduce
直接看

### What is expected?
点击触发onSearch

### What is actually happening?
没有任何反应

**Comment by afc163** [comment]
Duplicate of #8445
