### ISSUE TITLE
Carousel component has a bug when in Modal

### ISSUE THREAD

**Issue by zjdschnappi** [ant-design/ant-design#9732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.6

### Environment
win10   chrome版本 65.0.3325.162（正式版本） （64 位）

### Reproduction link
[https://jsfiddle.net/zjdschnappi/csyzLaop/7/](https://jsfiddle.net/zjdschnappi/csyzLaop/7/)

### Steps to reproduce
click the button and show the Modal more than once

### What is expected?
the Carousel list show as expected

### What is actually happening?
the Carousel list will disappear

**Comment by valleykid** [comment]
OK, I can reproduce it. Thanks for your report.

**Comment by valleykid** [comment]
Solve the bug by Modal's props `destroyOnClose={true}`.
