### ISSUE TITLE
关于Uload组件，是否可以在文件开始上传之前修改data对象中的参数

### ISSUE THREAD

**Issue by DarkerGarfield** [ant-design/ant-design#9734]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以配合阿里云OSS上传

### What does the proposed API look like?
```js
beforeUpload(file, fileList, data) {
        const key = file.name;
        // 对于每个文件的key是不同的，我觉得这样可以用起来更简单；不用重写customRequest
        data['key'] = 'startWith/' +  key;
 }
```

**Comment by yesmeck** [comment]
Data 可以是个 function 的。 https://github.com/react-component/upload/pull/32/files
