### ISSUE TITLE
AntD Popover Within ShadowDOM

### ISSUE THREAD

**Issue by kaufmann42** [ant-design/ant-design#9744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Chrome Version 65.0.3325.162 (Official Build) (64-bit), Mac OS High Sierra 10.13.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14mj6mz4jj)

### Steps to reproduce
1. Add react-shadow dependency to project.
2. Wrap ShadowDOM around Popover component.

### What is expected?
Popover to appear.

### What is actually happening?
Because it's located in a shadow DOM it doesn't work.

**Comment by sbusch** [comment]
Upstream issue: yiminghe/dom-align/issues/33

**Comment by yesmeck** [comment]
Traced in yiminghe/dom-align#33

**Comment by EryouHao** [comment]
@kaufmann42 May I ask if your problem is solved? I had the same problem.
