### ISSUE TITLE
Default value of optionLabelProp for Select component in manual do not match: "children" in manual, "value" in code

### ISSUE THREAD

**Issue by jurkust** [ant-design/ant-design#9745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
any

### Reproduction link
[https://github.com/ant-design/ant-design/blob/a1d1ca4dc68cb12a6e4c5aaba5ccb70760d31e01/components/select/index.tsx#L143](https://github.com/ant-design/ant-design/blob/a1d1ca4dc68cb12a6e4c5aaba5ccb70760d31e01/components/select/index.tsx#L143)

### Steps to reproduce
Check manual and source:
Link to manual: https://ant.design/components/select/
Link to source: https://github.com/ant-design/ant-design/blob/a1d1ca4dc68cb12a6e4c5aaba5ccb70760d31e01/components/select/index.tsx#L143

### What is expected?
Manual should match source.

### What is actually happening?
Default value of "optionLabelProp" for select component in manual is "children", but in source it is "value".

**Comment by SeunghunSunmoonLee** [comment]
We should give example like 
```
<Option exampleProp={item.name}>
  <img src={icon1}/>
  <div>store 1</div>
</Option>
```
<AutoComplete
  optionLabelProp="exampleProp"
>
```
so people understand clearly. Please update the docs. Or how can I do it ?
