### ISSUE TITLE
Select with search at the bottom of the page, renders the filtered list in the wrong position

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#9746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
ubuntu 17.10, firefox 59.0.1 (64-bit), react 16.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y3oq1ym1r9)

### Steps to reproduce
render a Select with showSearch flag at the bottom of a page - the last element in the page, so that the Select opens upwards - and search so that one or no results should show. 

### What is expected?
the popup list should be attached to the Select element

### What is actually happening?
the popup list maintains it's top position, and the result is that it's floating high above the Select element

**Comment by swwinone** [comment]
I met the same problem.the position of filtered list is not recalculate,the rc-trigger is not trigger。

**Comment by pierre-H** [comment]
Same problem ...

**Comment by nikogu** [comment]
ping @yutingzhao1991

**Comment by AhmedSayed77** [comment]
this is fixed
