### ISSUE TITLE
Rate component 'read-only' variation should have default cursor on hover

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#9747]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Rate component 'read-only' variation is mostly used when you want to _display_ something, not give a rating. Thus, having `cursor: not-allowed` on hover is really an anti-pattern here. Why would someone wish to see a `not-allowed` cursor when hovering over a rating of a product for example?

### What does the proposed API look like?
`cursor: default` on hover

**Comment by dengfuping** [comment]
@avalanche1 I think we should rename `disabled` prop to `readOnly` prop and fix the `cursor` style.
