### ISSUE TITLE
table组件多页的情况下rowSelection中onChange的回调参数问题

### ISSUE THREAD

**Issue by wusongV5** [ant-design/ant-design#9751]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
chrome

### Reproduction link
[http://ant-design.gitee.io/components/table-cn/#header](http://ant-design.gitee.io/components/table-cn/#header)

### Steps to reproduce
使用table组件，如果有多页。选中第一页的某条记录，再选择第二页的某条记录。rowSelection中onChange的回调参数selectedRows只有第二页选中的一条记录，没有之前第一页选择的记录

### What is expected?
有选中的所有记录，而不是只有当前页选中的row

### What is actually happening?
只有当前页选中的row

**Comment by shizhanguo** [comment]
这个问题解决了吗？

**Comment by ColinChen2** [comment]
In 3.7.0. Still have the bug. 
When we use the server sider pagination,  selectedRows is a array which only include data in the current page.  Luckily, selectedRowKeys is right.

May be your code like that:
```javascript
const rowSelection = {
      selectedRowKeys,
      onChange: (selectedRowKeys, selectedRows) => {
          const { onSelectRow } = this.props;
         if (onSelectRow) {
          onSelectRow(selectedRows);
         }
     };
};
```
solution: we can cached by ourself.
May be your code like that:
```javascript
//cache all page selectedRows
    if(selectedRowKeys.length > selectedRows.length) {
      // filter not in selectedRowKeys
      let leftRows = this.cachedSelectedRows.filter((row) => {
        return selectedRowKeys.indexOf(row[rowKey]) >= 0
      });

      // filter older selectedRows
      leftRows = leftRows.filter((row) => {
        return selectedRows.map((row)=> row.id).indexOf(row[rowKey]) < 0
      });

      // concat new selectedRows
      this.cachedSelectedRows= [].concat(selectedRows, leftRows);
    } else {
      this.cachedSelectedRows = selectedRows
    }

    if (onSelectRow) {
      onSelectRow(this.cachedSelectedRows);
    }
```

**Comment by WALLE729** [comment]
我也是同样的问题，大牛是怎么解决的，官方会解决吗

**Comment by afc163** [comment]
Duplicate of #11384

**Comment by zombieJ** [comment]
Seems this issue has gone in current version: https://codesandbox.io/s/xpjl73zl2p

**Comment by yesmeck** [comment]
跟 #11384 其实不是同一个问题。

**Comment by zombieJ** [comment]
题头的 issue fix 了，先关了。server pagination 的 issue 移到 #7942 里 reopen。

**Comment by JslinSir** [comment]
请问有什么好的解决方案

**Comment by liaozd** [comment]
解决了么？
