### ISSUE TITLE
antd@3.3.1 Upgrade to the latest version and find a js error.

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#9752]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
win10、chrome 64.0.3282.119（正式版本）

### Reproduction link
[http://ant-design.gitee.io/components/table-cn/#header](http://ant-design.gitee.io/components/table-cn/#header)

### Steps to reproduce
Js error
ReferenceError: kQa is not defined

note:antd@3.3.0 is right

### What is expected?
No error report

### What is actually happening?
ReferenceError: kQa is not defined

**Comment by jeffycai** [comment]
![qq 20180321164446](https://user-images.githubusercontent.com/4546658/37700622-3a64b69e-2d27-11e8-9799-a50914a6c7d5.png)

The online example is harder to build, and you can look at the running stack.

**Comment by jeffycai** [comment]
@afc163

**Comment by afc163** [comment]
I cannot resolve this depends on so little information.
