### ISSUE TITLE
Table size small,fixed left ,last column border right not show

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#9754]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
windows 10 ,chorme latest,react latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/92wq35k10p)

### Steps to reproduce
https://codesandbox.io/s/92wq35k10p

### What is expected?
fixed left ,last column border right show

### What is actually happening?
fixed left ,last column border right not show

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/37700451-82e0cbe8-2d26-11e8-9c0a-929c8982e36e.png)
small

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/37700468-99db5ad4-2d26-11e8-8383-a5a491a2cccc.png)
normal

**Comment by Hunter690** [comment]
I have a similar problem:

Table size medium:

![image](https://user-images.githubusercontent.com/24757872/39281526-c45f5f0c-48ca-11e8-8935-a181f8a30e99.png)

Small:

![image](https://user-images.githubusercontent.com/24757872/39281503-a06fde64-48ca-11e8-9213-3e45105530ee.png)

**Comment by quinnliu** [comment]
I'm facing the exact same problem as @Hunter690. 

Best,
Q

**Comment by quinnliu** [comment]
@yesmeck I was curious when you think this well be fixed? Thanks!
