### ISSUE TITLE
Horizontal form not working with modal

### ISSUE THREAD

**Issue by PhatHoang21** [ant-design/ant-design#9756]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Win 10, chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k34j8n7pmo)

### Steps to reproduce
Implement a form inside modal. Then set layout property of form to 'horizontal'

### What is expected?
Form layout should is horizontal

### What is actually happening?
Form layout is vertical

**Comment by dengfuping** [comment]
@PhatHoang21 It's expected. You need to set the layout for every `FormItem` although `Form` layout is horizontal. Please refer to the demo https://codesandbox.io/s/134p3m0j23.

**Comment by seasonyuu** [comment]
@dengfuping 并没有用，不论是在 Form 设置，还是在 FormItem 设置，或者两个都设置，水平布局在对话框中始终不会出现
