### ISSUE TITLE
Dropdown trigger can not be component

### ISSUE THREAD

**Issue by crudo** [ant-design/ant-design#9757]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Mac OSX 10.13.3, Google Chrome Version 65.0.3325.162 (Official Build) (64-bit) or Firefox 58

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rm7jqk4o7p)

### Steps to reproduce
See https://codesandbox.io/s/rm7jqk4o7p. Dropdown children must be inline HTML, otherwise the dropdown will never appear.

### What is expected?
Dropdown should appear when using component as a trigger.

### What is actually happening?
Dropdown is not shown when using component as a trigger.

**Comment by yesmeck** [comment]
You need to pass props down, see https://codesandbox.io/s/rj4qmp8n7p

**Comment by crudo** [comment]
@yesmeck Why? If there such requirement, it should be in documentation. I can create PR, but need to now why ;)

**Comment by yesmeck** [comment]
Dropdown needs to pass event handlers to the trigger element. PRs welcome.

**Comment by crudo** [comment]
Ok. thanks!

**Comment by yesmeck** [comment]
For host elements, Dropdown will pass event handlers by cloning them, for components, you need to pass props to the host elements manually.
