### ISSUE TITLE
Timeline placing steps to left

### ISSUE THREAD

**Issue by sevketufuk** [ant-design/ant-design#9759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At the moment timeline only orders related items to the right side of the timeline point. That would be great if there was a option to place it to 'left' and 'right'

### What does the proposed API look like?
props:
{
position: 'left' | 'right'
}

**Comment by afc163** [comment]
I think right position of timeline is weired UI.
