### ISSUE TITLE
tabs arrow button did not hide correct

### ISSUE THREAD

**Issue by AHopes** [ant-design/ant-design#9767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
chrome 

### Reproduction link
[http://ant-design.gitee.io/components/tabs-cn/#components-tabs-demo-custom-add-trigger](http://ant-design.gitee.io/components/tabs-cn/#components-tabs-demo-custom-add-trigger)

### Steps to reproduce
点击add添加tab到出现arrow button，关闭一个tab，右边的button与tab间出现空白，点击左右button或者tab后会自己隐藏

### What is expected?
关闭时计算div.ant-tabs-nav.ant-tabs-nav-animated宽度隐藏左右button

### What is actually happening?
左右button未正确隐藏

**Comment by afc163** [comment]
👍 确实有这个问题。
