### ISSUE TITLE
Disable "Tabs" keyboard control in tabBarExtraContent's child

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design#9768]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
"react": "^16.2.0"

### Reproduction link
[https://codepen.io/xaasu/pen/geWdpN?editors=0010](https://codepen.io/xaasu/pen/geWdpN?editors=0010)

### Steps to reproduce
<Tabs tabBarExtraContent="${Any input component, such as <Input />}">
${More than 2 TabPane}
</Tabs>

### What is expected?
I can use the keyboard keys "↑↓←→" on the tabBarExtraContent child "<Input  />"

### What is actually happening?
When I key down the keys "↑↓←→" , TabPane changed，and I can't  select the right place in the input component。
It's serious if the tabBarExtraContent is a modal , because change tabs make the modal hidden, but when you change back, the modal open automatically ， key control the tabs change , but not change the status to close the modal

**Comment by xaasu** [comment]
如果Tabs标签，tab bar 上额外的元素有输入框，没有办法在输入框使用小键盘上下左右，因为使用上下左右会切换窗口，现在场景，在额外元素使用的是模态框，也出现这个问题，我的例子尝试重现这个场景但是没有成功，希望添加一个配置，用于禁止键盘切换标签页

**Comment by valleykid** [comment]
I don't think you must use `tabBarExtraContent`, like [this](https://codepen.io/valleykid/pen/yKXPme) maybe more flexible.

**Comment by huoyanwuzhe629** [comment]
我也遇到了这个问题了，既然提供了tabBarExtraContent的api，在上面增加按钮提供来唤起模态框应该是个很常见的使用场景吧。。。

**Comment by zomars** [comment]
I don't think @valleykid solution is a a valid one. What's the point of the `tabBarExtraContent` prop then?

**Comment by zomars** [comment]
Plus, on mobile this breaks the layout:

![image](https://user-images.githubusercontent.com/3504472/60196531-9a6d8e00-97fa-11e9-8dd8-3b284757d51a.png)

![image](https://user-images.githubusercontent.com/3504472/60196545-a22d3280-97fa-11e9-96ba-d57c8c72d3e2.png)
