### ISSUE TITLE
antd的问题4个问题，3个BUG，1个需求，希望修复一下谢谢。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
antd3.2.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/table-cn/#](https://ant.design/components/table-cn/#)

### Steps to reproduce
1：第一个BUG，但在form里面用Select或者TreeSelect，并且Form的layout 是inline，那么会出现样式不对的问题。除非自己自定宽度，否则无效，用栅栏方式也无效。
2：第二个BUG，table指定scroll={{x:800,y:1300}} 会出现滚动条（这个是正常的），但是会发现整个column的数据并没有居中了。
3：第三个BUG，在弹出一个Modal的时候，里面有 Form表单。如果想focus到第一个Input（其他组件没测试），会发现第一次弹出的时候可以Focus，然后再弹出Input不会获得焦点。
4：第四个需求：这个是一个需求，就是一般我们表格，每一行后面都有一个编辑按钮。点击编辑的时候，应该会弹出一个Modal，这个是否能否让表格的背景色依然是选中当前行的背景色，因为会发现一点的是，如果背景色重置了（默认白色），那么编辑完之后，有些用户不知道编辑了哪一行。

### What is expected?
1：第一个BUG，Form的layout为inline，里面的Select和TreeSelect应该有宽度才对。
2：第二个BUG，就算加了scroll y =xxxx应该样式不受影响。
3：第三个BUG：在弹出一个Modal的时候，不管点击几次都应该可以Focus。
4：第四个算是一个需求，背景色应该不要重置。

### What is actually happening?
1：第一个BUG，样式不对。
2：第二个BUG，样式不对。
3：第三个BUG，不能focus。
4：第四个需求：背景色变了。

**Comment by yesmeck** [comment]
一个 bug 一个 issue 吧，写在一起不好追踪。
