### ISSUE TITLE
Dropdown fires onVisibleChange if select/date-picker component is rendered  in overlay

### ISSUE THREAD

**Issue by sayedatif** [ant-design/ant-design#9770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Mac os, Chrome

### Reproduction link
[https://codepen.io/Atif86/pen/mxmGzy?editors=0010](https://codepen.io/Atif86/pen/mxmGzy?editors=0010)

### Steps to reproduce
Click on dropdown, select value from select dropdown

### What is expected?
It should remain open on selecting values from dynamically created div of select box

### What is actually happening?
Dropdown  should not close on selecting values from select component

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/QmveZp?editors=0010

#3438
