### ISSUE TITLE
how to do "npm publish" for the forked version

### ISSUE THREAD

**Issue by qingbolove** [ant-design/ant-design#9772]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
win server 2012, chrome, react 16

### Reproduction link
[https://github.com/qingbolove/ant-design](https://github.com/qingbolove/ant-design)

### Steps to reproduce
I want to add some external feature of ant-design, so I forked a version of antd, and want to use my forked repo.

### What is expected?
I can install the forked version, and use it successfully.

### What is actually happening?
The problem is that if I install the forked tarball package, it got all the file path same with the source code, but when I use it, it tell me that

./node_modules/antd/index.js
Module not found: Can't resolve './components' in 'E:\github\my-app\node_modules
\antd'
![image](https://user-images.githubusercontent.com/10628904/37772703-5c0c5db8-2dd3-11e8-8784-dd00e906822f.png)

I realized that it is because there is a publish script, which change the source code to lib file. So I need to publish my fork repo and then install it to get a same "npm install antd" result. So I change a package name, and want to do publish, but when I run "npm run pub", there is always a error that "Error: spawn git ENOENT" 
![image](https://user-images.githubusercontent.com/10628904/37772710-6181ea06-2dd3-11e8-8951-9a8c591789e5.png)

---
Can you guys please tell me how to resolve this issue? I think many other user may want to do fork, and this is a blocking issue that we cannot use our forked repo. Thanks so much!

**Comment by yesmeck** [comment]
Change package name in `package.json`, then

```bash
$ npm run compile
$ npm run dist
$ npm publish
```

**Comment by qhxin** [comment]
@yesmeck `Error: 'dist' it should has a file named 'antd.css'`
i changed package name but meet this error.

**Comment by sbusch** [comment]
He @qhxin, could you please take a look here: https://github.com/ant-design/ant-design/issues/13636
