### ISSUE TITLE
Uploader component does not provide correct type info

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9775]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
N/A

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o7nl5x3kq5)

### Steps to reproduce
click upload, select a file

### What is expected?
console output `has originFileObj, is UploadFile!!!`

### What is actually happening?
console output `nop, not a upload file`

---
in Upload component's typing, it claims `beforeUpload` callback will receive a `UploadFile` typed object, but in fact we receive a `File` object.
Which causes a lot of trouble when using in TypeScript, for now we write a lot of `  as any as File` type cast just to get a correct type.

**Comment by yesmeck** [comment]
The `file` is the "originFileObj"

**Comment by whtsky** [comment]
Yes, but the typing is wrong. Wrong typing causes a lot of trouble for TypeScript users. 
https://github.com/ant-design/ant-design/blob/master/components/upload/interface.tsx#L56

**Comment by pizn** [comment]
> Which causes a lot of trouble when using in TypeScript, for now we write a lot of as any as File type cast just to get a correct type.

This is not a reason to modify the file type. `beforeUpload` should be return the real `File` for user to control, such like file verification.

eg: On `beforeupload` to get image size with use `fileReader` / `window.URL. createObjectURL(file)`.

**Comment by whtsky** [comment]
> `beforeUpload` should be return the real `File` for user to control, such like file verification.

total agree, I think fixing the typing is better than do break change

**Comment by danielg2002** [comment]
Also in "fileList" parameter the type is wrong.

**Comment by bora89** [comment]
Yes guys, type of FileList now is an Array. Can not use it in that way. I would like to get real FileList type read-only object as native file input returns (with multiple attr). When to expect it to appear?

**Comment by whtsky** [comment]
any updates on this?
