### ISSUE TITLE
并且Form的layout 是inline ，导致select样式问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.2.3

### Environment
antd3.2.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://codesandbox.io/s/5km1r4mkj4](https://codesandbox.io/s/5km1r4mkj4)

### Steps to reproduce
BUG：但在form里面用Select或者TreeSelect，并且Form的layout 是inline，那么会出现样式不对的问题。除非自己自定宽度，否则无效，用栅栏方式也无效。

### What is expected?
Form的layout为inline，里面的Select和TreeSelect应该有宽度才对。

### What is actually happening?
样式不对

**Comment by xgj1988** [comment]
@afc163  我在codesandbox 一直是 Resolving Dependencies。。

**Comment by xgj1988** [comment]
@afc163  项目地址 ： https://codesandbox.io/s/5km1r4mkj4

**Comment by xgj1988** [comment]
没人回答吗？

**Comment by yesmeck** [comment]
历史原因，Select 默认是没宽度的，可以自己加个宽度。

**Comment by xgj1988** [comment]
@yesmeck  我知道可以自己加，我的意思是这个是一个BUG吧。

**Comment by yesmeck** [comment]
嗯，是个已知问题，但是历史原因暂时不会改回来。

**Comment by swierol** [comment]
Percentage width values are ignored anyway.
https://codesandbox.io/s/n4r3zln060

**Comment by ybning** [comment]
select加个宽度是可以的，但是
栅格布局下，怎么解决select的固定width问题？
@yesmeck

**Comment by gaspire** [comment]
今天发现也有这个问题，怎么没人解决呢

**Comment by wolfFN** [comment]
> select加个宽度是可以的，但是
> 栅格布局下，怎么解决select的固定width问题？
> @yesmeck

@ybning @gaspire @xgj1988 我今天也遇到了问题，最后解决办法是给 `Form.Item` 加了 `style={{ width: '25%' }}`  ，解决了我的问题。我是一行四个 Item

**Comment by guozhenqianga** [comment]
我也遇见这个问题了，刚升级的4.3.0,Form的layout不是inline的时候样式显示正常

**Comment by guozhenqianga** [comment]
我也遇见这个问题

> > select加个宽度是可以的，但是
> > 布局布局下，怎么解决select的固定宽度问题？
> > @yesmeck
> 
> @ybning @gaspire @ xgj1988我今天也遇到了问题，最后解决方法是给`Form.Item`加了`style={{ width: '25%' }}` ，解决了我的问题。我是一行四个

我也遇见这个问题了，刚升级到4.3.0，Select样式宽度会根据option的内容长短来变动，这么久了，也不见修复

**Comment by hdtopku** [comment]
同遇到，参考解决：[解决antd 下拉框 input [defaultValue] 的值的问题](https://www.jb51.net/article/198653.htm)
