### ISSUE TITLE
table指定scroll={{x:800,y:1300}}   会发现整个column的数据并没有居中了

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9778]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.2.3

### Environment
antd3.2.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
BUG：table指定scroll={{x:800,y:1300}} 会出现滚动条（这个是正常的），但是会发现整个column的数据并没有居中了。

### What is expected?
就算加了scroll y =xxxx应该样式不受影响

### What is actually happening?
样式不对

**Comment by dengfuping** [comment]
@xgj1988 It's expected for that the content in column is aligned to left by default. You can set `align: 'center'` for column definition to meet your requirement. Please refer to the commit https://github.com/ant-design/ant-design/pull/9749/commits/977f82b0940786807b618f5cbac737527881ed38.

**Comment by xgj1988** [comment]
@dengfuping   I use your way, But  It is not validate for thie question.

**Comment by dengfuping** [comment]
@xgj1988 Please refer to the demo https://codesandbox.io/s/v6o7m0x5k5.

**Comment by xgj1988** [comment]
@dengfuping  地址：https://codesandbox.io/s/xlz87zr5wo

**Comment by xgj1988** [comment]
没人回答吗？

**Comment by catalsdevelop** [comment]
你的demo 404了
