### ISSUE TITLE
在弹出一个Modal的时候，里面有 Form表单。不能重复focus Input。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.2.3

### Environment
antd3.2.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://codesandbox.io/s/m4ljjl8nw8](https://codesandbox.io/s/m4ljjl8nw8)

### Steps to reproduce
在弹出一个Modal的时候，里面有 Form表单。如果想focus到第一个Input（其他组件没测试），会发现第一次弹出的时候可以Focus，然后再弹出Input不会获得焦点。

### What is expected?
在弹出一个Modal的时候，不管点击几次都应该可以Focus。

### What is actually happening?
样式不对

---
input 不能focus。

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by xgj1988** [comment]
@benjycui  https://codesandbox.io/s/m4ljjl8nw8 你看一下呢。我把地址附上。

**Comment by xgj1988** [comment]
没人回答吗？

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/8668#issuecomment-352955313

**Comment by xgj1988** [comment]
@yesmeck  并没有得到解决。。我问了几个问题都得不到解决，感觉这个团队很水啊

**Comment by afc163** [comment]
https://codesandbox.io/s/3vxzvmlm21

**Comment by xgj1988** [comment]
@afc163  thx
