### ISSUE TITLE
表格背景色不修改

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#9780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这个是一个需求，就是一般我们表格，每一行后面都有一个编辑按钮。点击编辑的时候，应该会弹出一个Modal，这个是否能否让表格的背景色依然是选中当前行的背景色，因为会发现一点的是，如果背景色重置了（默认白色），那么编辑完之后，有些用户不知道编辑了哪一行

### What does the proposed API look like?
perserveBackGround= {true}

**Comment by afc163** [comment]
Try `rowClassName` to customize you need.

**Comment by xuwenjin** [comment]
how to use the rowClassName from css file
