### ISSUE TITLE
Upload component still not providing correct type info 

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9781]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
N/A

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xo161j4lro)

### Steps to reproduce
click upload, select a file

### What is expected?
console output has originFileObj, is UploadFile!!!

### What is actually happening?
console output nop, not a upload file

---
follows up #9775
although https://github.com/ant-design/ant-design/commit/ee0bf4167256f1092821a5aefc7a9400b8a0a208 has fixed type of `file`, the fir param of beforeUpload, the typing of `FileList` is still not correct.
In fact, I believe most of `UploadFile`-typed param in `Upload` component should be the native File object

**Comment by dengfuping** [comment]
@whtsky In fact, the problem has been fixed. You can test it again when the new version `3.3.2` is released this week.

**Comment by whtsky** [comment]
@dengfuping is there any way I can use `3.3.2` before it's release?

**Comment by dengfuping** [comment]
@whtsky Don't hurry it. It's expected that the new version `3.3.2` will be released today.
