### ISSUE TITLE
tree树形组件bug

### ISSUE THREAD

**Issue by huangzhiwei001** [ant-design/ant-design#9782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
antd:2.7.1; react:15.3.0

### Reproduction link
[http://2x.ant.design/components/tree-cn/](http://2x.ant.design/components/tree-cn/)

### Steps to reproduce
写的代码是没有问题的，官方文档也看了，没找到原因何在，这个bug肯定有人遇到过的

1.初始化请求接口生成Tree形结构。
2.点击页面上A按钮，通过接口请求回来的数据正常默认勾选父级里面的3个复选框，再勾选1个复选框，点击页面修改按钮发送请求。
3.再点击页面上的B按钮，依旧调接口，接口回来的数据依旧正常默认勾选父级里面的另外3个复选框。
4.然后再点击A按钮，依旧请求接口，然后再去手动勾选其它没有勾选的复选框，会发现A按钮checkedKeys属性里面3个复选框的值突然被清掉了并且自动把B按钮3个复选框的值给自动勾选上，加上我刚勾选的值，也就是这时候页面出现4个已勾选的复选框，A按钮3个复选框值给我自动清掉了，请问大家有出现这种情况吗？

### What is expected?
不管我点击哪个按钮，树形里面的子节点勾选的值都不应该被上一级按钮复选框的值所影响，应该正常显示

### What is actually happening?
不管我点击哪个按钮，树形里面的子节点勾选的值都不应该被上一级按钮复选框的值所影响，应该正常显示

**Comment by zombieJ** [comment]
感谢反馈，这个bug已经修复。下个minor版本会更新依赖：
https://github.com/react-component/tree/pull/149

**Comment by huangzhiwei001** [comment]
下个版本什么时候发呢

**Comment by zombieJ** [comment]
本周末
