### ISSUE TITLE
ant-select-dropdown-menu don't move down when select multiple items

### ISSUE THREAD

**Issue by hieunvtq** [ant-design/ant-design#9784]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Ubuntu 16.04 LTS, Chrome 65, React 16.2 .0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n7602y6v0p)

### Steps to reproduce
Run minimal reproduction at link, then select for above 5 items.

### What is expected?
With multiple items selected will push down selection menu.

### What is actually happening?
Selection menu don't move down when select multi item.

**Comment by ericjam3** [comment]
I would like to work on this issue since it is still open. Will this be possible?

**Comment by hieunvtq** [comment]
Is this bug fixed ?

**Comment by ericjam3** [comment]
There was a similar issue that was closed recently, however, the comments are mostly in Chinese, so it's hard for me to tell exactly what was the result. I will have a look in the next couple of days.

**Comment by ericjam3** [comment]
This issue appears fixed
