### ISSUE TITLE
0.12版本如何给已经Mount的Form传递初始值。

### ISSUE THREAD

**Issue by ziczhu** [ant-design/ant-design#979]
0.11 版本 Form 可以采用 state 保存 data 数据，表单内容的更新触发的是 state 的变化，然后通过 componentWillReceiveProps 来传递初始化的数据。
类似于
```
getInitialState() {
    return {
      formData: {
        userName: '大眼萌 minion',
        password: undefined,
        gender: 'male',
        remark: undefined,
        agreement: undefined,
        }
    };
  },

  componentWillReceiveProps(nextProps) {
    this.setState({
      formData: nextProps.form
    });
  }
```
升级到 0.12 之后表单初始化数据只能采取 componentDidMount 实现。
```
componentDidMount() {
    this.props.form.setFieldsValue({
      'name': 'hello',
      'email': 'test@126.com'
    });
  }
```
因为 Form 组件被 createForm 包装之后，表单的内容的数据更新触发的是 props 的变化，无法在 componentWillReceiveProps 中执行 this.props.form.setFieldsValue，因为这样就变成了无限循环更新组件的 props。

总结一下就是，0.11 和 0.12 都可以给表单动态赋初始值，0.11 可以通过 componentWillReceiveProps 中 setState，0.12 可以通过 componentDidMount 中 this.props.form.setFieldsValue。

但是 componentDidMount 只会加载一次，所以在这里想咨询一下，在 0.12 中如何可以给一个已经 Mount 的 Form 组件多次传入不同的初始值，复用这个 Form 达到更新多次数据的功能。

**Comment by benjycui** [comment]
[mapPropsToFields](https://github.com/react-component/form#createformformoption-function)

用法可以参考 http://react-component.github.io/form/examples/redux.html

**Comment by ziczhu** [comment]
经过测试，mapPropsToFields确实可以，不过直接通过 props 传入初始值的话需要满足格式如下：
```
const props = {
  name: {
    value: 'asd'
  },
  email: {
    value: 'x@gmail.com'
  }
};

<App {...props} />

mapPropsToFields(props) {
    console.log('mapPropsToFields', props);
    return {
      name: props.name,
      email: props.email
    };
  }

需要将对应字段的值以对象的 value 属性的形式传入。
```

**Comment by guolin** [comment]
这种写法好奇怪呀，

使用mapPropsToFields 和 直接在componentDidMount 中setField 有什么区别吗？
@benjycui

**Comment by benjycui** [comment]
`mapPropsToFields` 的话，值可以从 owner 传进来。

而在 `componentDidMount` 中 `setField`，你是要 hard code 还是发请求？

**Comment by guolin** [comment]
只是填写表单和发送请求，感觉代码量是一样的，而且就我个人而言componentDidMount 中 setFieldsValue 更直观一些。

**Comment by benjycui** [comment]
> 而在 componentDidMount 中 setField，你是要 hard code 还是发请求？

**Comment by flyfinec** [comment]
一开始也没注意到是name: {value: xxx}的格式,调了半天在这才发现

@benjycui 能否完善下文档，mapPropsToFields是对接redux重要的api，文档至少也说明一下mapPropsToFields的return返回的是什么，格式怎么样呀，不然很容易入坑

**Comment by benjycui** [comment]
Updated: https://github.com/ant-design/ant-design/commit/b0f7df547a86c0c18eef1b441b44abc70f116ae1

文档中有什么问题，烦请指出，可能的话，给出相应的建议甚至 PR 会更好。因为我们作为 maintainer，对 antd 的实现是有一定的了解的，所以可能我们觉得文档这样已经足够了，但是其实对大多数开发者来讲还不够清晰，谢谢。

**Comment by afc163** [comment]
感觉 Form 需要一篇深入浅出的介绍，现在我都不怎么看得懂那么多属性。

**Comment by huyansheng3** [comment]
同看不懂form

**Comment by huyansheng3** [comment]
setFields的例子都没看到过~

**Comment by zzzzxiao** [comment]
@huyansheng3 https://github.com/react-component/form/blob/3b9959b57ab30b41d8890ff30c79a7e7c383cad3/examples/server-validate.js#L74-L79
这里有例子
