### ISSUE TITLE
Tree still throws error when both `{null}` and TreeNode appear in children

### ISSUE THREAD

**Issue by mk-nickyang** [ant-design/ant-design#9794]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.2

### Environment
macOS 10.13.3, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k3p4mq26w5)

### Steps to reproduce
```
<Tree>
    {null}
    <TreeNode title="Hello World" key={420} />
</Tree>
```
OR

```
<Tree>
    {null}
    {null}
</Tree>
```

### What is expected?
Tree can ignore these `{null}` children

### What is actually happening?
https://gyazo.com/837425fbd56539a8a8ac00eb44fe5e33

---
There was an exactly same issue being closed and its fix PR being merged 3 days ago (https://github.com/ant-design/ant-design/issues/9304), but it doesn't seem to be fixed

**Comment by yesmeck** [comment]
The fix will be released this weekend.

**Comment by wmy1992** [comment]
Is this problem solved? I still get this problem until now

**Comment by zombieJ** [comment]
@wmy1992  could you help to create a issue for this?

**Comment by ccc159** [comment]
This bug is still there.
