### ISSUE TITLE
Table first column flickering issue on load

### ISSUE THREAD

**Issue by ahennie** [ant-design/ant-design#9795]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.2

### Environment
MacOS, latest Chrome and Firefox

### Reproduction link
[https://github.com/themao/next-antd](https://github.com/themao/next-antd)

### Steps to reproduce
Load the page, and see the flickering issue. Screencast: https://cl.ly/2B2h3D2f3Z2U url: https://deploy-bffymumluu.now.sh/

### What is expected?
Normal loading, which is achieved after 2seconds.

### What is actually happening?
Flickering issue.

**Comment by themao** [comment]
@afc163 @ant-design-bot I tried to reproduce it, but looks like codesandbox does not support server side rendering with next.js? https://codesandbox.io/s/0p6nl60v2n

The page is empty although I specified the start script.

**Comment by afc163** [comment]
Could you provide a github repo for this?

**Comment by themao** [comment]
@afc163 yes, of course. Here it is https://github.com/themao/next-antd

**Comment by themao** [comment]
Looks like I managed to solve the problem, it was caused by the content width
