### ISSUE TITLE
Upload component still not providing correct type info

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9796]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.2

### Environment
N/A

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xo161j4lro)

### Steps to reproduce
click upload, select a file

### What is expected?
console output has originFileObj, is UploadFile!!!

### What is actually happening?
console output nop, not a upload file

---
follows up #9775
it's claimed to have been fixed in 3.3.2 ( #9781 ), but seems not :(

**Comment by dengfuping** [comment]
@whtsky See the comment https://github.com/ant-design/ant-design/commit/ee0bf4167256f1092821a5aefc7a9400b8a0a208#r28254575.

**Comment by dengfuping** [comment]
@whtsky Please reply in the original issue and there is no need to open an issue.
