### ISSUE TITLE
TimePicker/DatePicker popup panel text/element size doesn't change when component size is changed. 

### ISSUE THREAD

**Issue by umstek** [ant-design/ant-design#9797]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
All

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://kj7ro4y9o.codesandbox.io/)

### Steps to reproduce
Add TimePicker/DatePicker components of different sizes. 
Click on each of them in the preview to see the popup panel. 

### What is expected?
Sizes of the elements in popup panel to match the component. 

### What is actually happening?
Sizes of the elements in the popup panels are same regardless of the input size.

**Comment by afc163** [comment]
It is by designed.
