### ISSUE TITLE
Weird compile error with date-picker\style\TimePicker.less

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#9798]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Windows 10

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/date-picker/style/TimePicker.less#L61](https://github.com/ant-design/ant-design/blob/master/components/date-picker/style/TimePicker.less#L61)

### Steps to reproduce

Set up a CRA with antd 3.3.3, `yarn start`, see error : 

```
./src/resources/main.less
Module build failed: 


    &:first-child24px;
               ^
Unrecognised input
      in C:\node-projects\next-ui\node_modules\antd\lib\date-picker\style\TimePicker.less (line 61, column 17)
```

Open node_modules\antd\lib\date-picker\style\TimePicker.less

See unrecognized characters line 61 : 

![image](https://user-images.githubusercontent.com/7466144/37877537-127e3306-305d-11e8-9658-7a5733b6e7ca.png)

After having deleted node_modules\antd and reinstalled antd@3.3.3, the issue is still there.
***If I downgrade to antd@3.3.1 the problem disappears.***

### What is expected?
No build error

### What is actually happening?
./src/resources/main.less
Module build failed: 

    &:first-child24px;
               ^
Unrecognised input
      in C:\node-projects\next-ui\node_modules\antd\lib\date-picker\style\TimePicker.less (line 61, column 17)

**Comment by dengfuping** [comment]
@abenhamdine Could you give a re-producible demo or project?

**Comment by yesmeck** [comment]
The `TimePicker.less` looks good on unpkg https://unpkg.com/antd@3.3.3/lib/date-picker/style/TimePicker.less

**Comment by abenhamdine** [comment]
I close because the issue has disappeared by upgrading to 3.4.0.
