### ISSUE TITLE
Modal 组件能否增加遮罩层相关设置

### ISSUE THREAD

**Issue by superRaytin** [ant-design/ant-design#980]
目前点击遮罩层会触发 onCancel 关闭窗口，有些场景想要点击遮罩层不关闭，必须点‘取消’按钮或右上角 “X” 才关闭窗口，能否增加一个开关属性让用户自定义呢。

**Comment by afc163** [comment]
https://github.com/react-component/dialog/pull/14

**Comment by afc163** [comment]
演示：http://codepen.io/afc163/pen/jWpLWg?editors=001

**Comment by afc163** [comment]
onCancel 0.12.0 上没有传参数，可以先按例子里的 onClose 来。

**Comment by superRaytin** [comment]
:ok_hand: tks~

**Comment by zhaolihang** [comment]
3q
