### ISSUE TITLE
how to get dataSource in the table after filtered with attribute 'onFilter'?

### ISSUE THREAD

**Issue by caoqiqi** [ant-design/ant-design#9805]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
there is a situation that we need to know the  statistical data of the dataSource after filtered.

### What does the proposed API look like?
it is better to have a event listener to get this.

**Comment by yesmeck** [comment]
You can achieve it by returning `true` in `onFilter`, and filter the dataSource by yourself.
