### ISSUE TITLE
TreeSelect 树选择器如何使父节点不可选中，只能做展开收起功能

### ISSUE THREAD

**Issue by GinaQing** [ant-design/ant-design#9806]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect 组件：如何让父元素不可被选中，点击只能展开收起。单选子元素时，回填的内容为父元素名 子元素名，很多场景中会有此需求。

### What does the proposed API look like?
在props中配置某两个属性，解决这两个功能的需求

**Comment by GinaQing** [comment]
问题补充：点击子元素时，无法获取到对应子元素所属父元素的value，建议在onChange或某个函数中添加参数。

**Comment by zombieJ** [comment]
配合 `treeCheckable` 和 `disableCheckbox` 属性，让父节点不可选。
`showCheckedStrategy` 可以改变取值策略。

**Comment by chjiyun** [comment]
这个组件好像没这个功能额，我也期望有这样的展开收起的 api

**Comment by zombieJ** [comment]
@chjiyun coming soon...

**Comment by chjiyun** [comment]
> @chjiyun coming soon...

OK！如果项目升级antd版本，会有大影响么

**Comment by chjiyun** [comment]
> @chjiyun, 放心升级~
我用了一下TreeSelect的 新api，发现父节点还是会被选中啊，我要的是点击父节点跟左边的小箭头一样的展开收起功能，只有叶子节点才能调用onChange，也就是DirectoryTree 那样的 交互

**Comment by zombieJ** [comment]
@chjiyun 能写个重现吗？现在新的 expandedKeys 和 value 应该是可以组合出需要的效果的。

**Comment by chjiyun** [comment]
我觉得是 父节点没有调用onExpand；
```
  state = {
    value: undefined,
    treeExpandedKeys: [],
  }
  onTreeExpand = (expandedKeys) => {
    const newExpandedKeys = expandedKeys.filter(v => {
      return v.length === 1;
    });
    let treeExpandedKeys = [...expandedKeys];
    if(newExpandedKeys.length === 2) {
      treeExpandedKeys = expandedKeys.slice(-1)
    }
    console.log('onTreeExpand', treeExpandedKeys)
    this.setState({
      treeExpandedKeys,
    })
  }
  onChange = (value) => {
   this.setState({
      value,
    })
    console.log('onChange', value)
  }
render() {
  return (
    <TreeSelect
       showSearch
       allowClear
       value={value}
       treeData={this.treeData}
       treeExpandedKeys={treeExpandedKeys}
       style={{ width: 300 }}
       dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
       placeholder="Please select"
       onChange={this.onChange}
       onTreeExpand={this.onTreeExpand}
     />
  )
}
```

**Comment by LittleClown** [comment]
hey，各位，这个问题你们找到解决方案了吗？

**Comment by 1635334137** [comment]
:disable-branch-nodes="true"

**Comment by G-WangZH** [comment]
可以参考这篇文章的思路解决：https://blog.csdn.net/weixin_44949840/article/details/115479601

**Comment by FangTx** [comment]
添加全局样式可解决
.ant-select-tree-switcher {
  position: relative;
}
.ant-select-tree-switcher_open::before,
.ant-select-tree-switcher_close::before {
  content: '';
  position: absolute;
  right: -310px;
  top: 0;
  left: 0;
  bottom: 0;
}

**Comment by ttlb0814** [comment]
> 添加全局样式可解决 .ant-select-tree-switcher { position: relative; } .ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before { content: ''; position: absolute; right: -310px; top: 0; left: 0; bottom: 0; }

优秀！

**Comment by aaronxdd** [comment]
1、首先treeExpandedKeys受控
2、改写父节点的title属性，自定义组件，添加点击事件，控制treeExpandedKeys

**Comment by QingqinLi** [comment]
设置 treeExpandAction={"click"}

**Comment by zhuhh666** [comment]
我们的前端比较粗暴：让服务端把非叶子结点设置为disabled:true

**Comment by Mrcxt** [comment]
还是没有解决方案吗

**Comment by ponywei** [comment]
> 还是没有解决方案吗

treeExpandAction={'click'}
