### ISSUE TITLE
TreeSelect 树形选择器组件，父子节点的选中关联时，若子组件有未选择情况，则最终收集所有checked的时候不包含该节点集父节点

### ISSUE THREAD

**Issue by PuShaoWei** [ant-design/ant-design#9807]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect 树形选择器组件，父子节点的选中关联时，若子组件有未选择情况，则最终收集所有checked的时候不包含该节点集父节点

### What does the proposed API look like?
> 希望即便是在一个节点集合中，子节点未选中，那最终收集所有checked的时候也应该包含该节点集合中的父节点 及其它的兄弟节点

我现在是采用 增加`checkStrictly`方式来取消关联关系，可是这样一个一个点 有些麻烦

**Comment by zombieJ** [comment]
子节点未全选时，父不是选中的状态(halfChecked)。获得的列表里不会有父节点。

@yesmeck ，是否要开放`halfChecked` 给 `checkStrictly` 为 `false`的情况？感觉这个影响会比较大。

**Comment by PuShaoWei** [comment]
这类需求， 我还能采用其他什么方式实现嘛

**Comment by PuShaoWei** [comment]
@zombieJ  `checkStrictly ` 为 `false`的情况 我在子组件应该是开启不了的吧。。然后我有其他什么方式获取该父节点吗

**Comment by PuShaoWei** [comment]
![image](https://user-images.githubusercontent.com/18391791/37946435-e1b55d06-31b7-11e8-8504-4724273d42bf.png)
比如这种 ，只是获取不到父节点而已，但是父节点是有个横线状态的，我拉一下横线状态也行的吧

**Comment by PuShaoWei** [comment]
```
  /**
   * 节点点击触发
   *
   * @param checkedKeys
   * @param halfCheckedKeys
   */
  onCheck = (checkedKeys, { halfCheckedKeys }) => {
    this.props.handleSaveChecked(checkedKeys, halfCheckedKeys);
  };
```

最后去重合并下 `checkedKeys` 和 `halfCheckedKeys`

**Comment by PuShaoWei** [comment]
但是这样就会出现，下次渲染时会对所有子节点打勾，因为此时父节点属于`halfCheckedKeys `

**Comment by zombieJ** [comment]
诶？`checkStrictly`模式父子节点没有关联呐。你能给一个精简的codepen吗？
https://u.ant.design/codesandbox-repro

我看看是什么问题。

**Comment by PuShaoWei** [comment]
就是说，我想要最终结果也包含父节点，所以我采用了如上方式，上传最终结果时合并`checkedKeys` + `halfCheckedKeys`，这样我的结果是没问题了，也包含父节点的ID了，我让其刷新或者重载一遍数据时，该父节点所在集合会被全选。 `ant-design`被墙了，发不了`demo`，我开个代理弄弄

**Comment by elowes** [comment]
我是采用给原始数据增加唯一的key的形式，然后在点击某一个节点的时候遍历一下这个树，然后找到点击的元素加其所有的父节点，然后再指定让他们高亮。

**Comment by Zero0331** [comment]
我在前端写了一大堆判断逻辑去处理这个半选的问题

**Comment by zombieJ** [comment]
非 `checkStrictly` 获取 halfChecked 参考这个：https://codesandbox.io/s/8878zrw9p2
@yesmeck ,  把它加到文档里？

**Comment by PuShaoWei** [comment]
额，上次忘了给您演示demo 了，是这样的，这种解决方式 上个版本我就用了，请看我上面的代码，我最终合并了半选及已选状态，最终合并在一起交给服务端，但是我们存入数据库是不会区分半选还是全选的，下次渲染这个`ID`列表的时候由于父节点已被选中，故这个节点的展示将全部被选中，所以这个应该是要改一下底层判断方式的，因为实在不是专业的前端同学，所以一直没有追底层看

**Comment by Zero0331** [comment]
从后端获取数据后，如果有父节点半选（后端只返回全选和未选），递归判断子节点是否有0，如果有，父节点变为2；
给后端发请求时，同样递归，把半选2传过去，后端判断>0就可以处理是否选中；

**Comment by PuShaoWei** [comment]
哈哈哈 。不用这么麻烦吧

**Comment by zombieJ** [comment]
@PuShaoWei，
对于组件设计而言，两相不足的情况，用户传入的 checkedKey 相比没有 checkedKey 而言优先级更高。否则就会出现另一种情况：
假设有一个很深的树，想选中一个父节点后把子节点全部选中。如果是非传导设计，用户需要递归将所有的子节点取出。

从你的使用场景而言，当你选择不保存halfChecked值的时候，还原回原来结构就需要你自己来处理了。作为组件，假设 checkedKey 是否是 halfCheked 是一个非常不纯粹的行为。

**Comment by PuShaoWei** [comment]
halfCheked 就不能根据子级是否全选 然后再确认状态 ？

**Comment by zombieJ** [comment]
本身就是如此

**Comment by roc2539** [comment]
@PuShaoWei 怎么样？解决了没？ 这个问题很头痛呀。。 办选需要保存，这也是常见的啊。。

**Comment by roc2539** [comment]
@PuShaoWei 怎么样？解决了没？ 这个问题很头痛呀。。 办选需要保存，这也是常见的啊。。

**Comment by PuShaoWei** [comment]
没呢，感觉这块问题挺麻烦的，还有动态权限那儿也有点麻烦，emmmmmmm，是时候深入一下了

**Comment by PuShaoWei** [comment]
@roc2539 一起看看把

**Comment by roc2539** [comment]
嗯 取数据合并checkedKeys, halfCheckedKeys， 还原的时候也按这个还原，只能这也了。 以前用没用jq时代，用的tree都是组件自动能处理的，这里写的不能自动处理，不知道基于什么考虑。。

**Comment by PuShaoWei** [comment]
这个自动处理很简单的其实

**Comment by roc2539** [comment]
目前我的解决是思路是，保存的时候checkedKeys, halfCheckedKeys合并，全部保存到数据库，还原的时候，checkedKeys, halfCheckedKeys区分开来还原，目前看，没有问题。
checkedKeys={
                      {
                        checked:(checkedKeys === null || checkedKeys === undefined) ? [] : checkedKeys,
                        halfChecked:[],
                      }
                    }

**Comment by roc2539** [comment]
目前我的解决是思路是，保存的时候checkedKeys, halfCheckedKeys合并，全部保存到数据库，还原的时候，checkedKeys, halfCheckedKeys区分开来还原，目前看，没有问题。
checkedKeys={
                      {
                        checked:(checkedKeys === null || checkedKeys === undefined) ? [] : checkedKeys,
                        halfChecked:[],
                      }
                    }
@PuShaoWei

**Comment by roc2539** [comment]
@PuShaoWei  自动处理？ 你要改组件？还是？ 你现在怎么处理的？

**Comment by PuShaoWei** [comment]
十分抱歉，我最近没有什么时间改

**Comment by PuShaoWei** [comment]
周末抽出一部分时间看一下这块

**Comment by codepandy** [comment]
遇到同样的问题

**Comment by Zero0331** [comment]
@codepandy  我的办法就是  保存了checkedKeys 和 halfCheckedKeys， 但是antd的halfCheckedKeys有一个bug，如果只有一个checkedKeys的时候， halfCheckedKeys会拿不到跟节点的半选，这个我好像也提过bug，    然后第一次渲染页面的时候，回去遍历判断根节点是否真的是全选（因为半选对后端来说也是有权限的）

**Comment by HuYuee** [comment]
@zombieJ 现在不是这样的，在checkedKeys 设置的时候，后台只返回父节点的时候，会导致子节点所有节点全部选中

**Comment by zombieJ** [comment]
@HuYuee , 默认行为就是父节点勾选子节点传导，如果不需要这个行为可以用 checkStrictly

**Comment by HuYuee** [comment]
@zombieJ 这个行为大部分都是没有问题的，但是有一种情况，比如：我后台父节点a，下面有三个子节点，a1，a2，a3。我当前全部选中，提交给后台。提交之后，我在父节点a下面，新增加了一个子节点a4，这个时候我页面渲染的时候，会显示a4已结选中，但是后台数据库a4是没有选中的

**Comment by HuYuee** [comment]
我看了下源码，conductCheck这个方法在渲染和点击父节点的时候都会调用这个，但是实际应该要分开出来的，毕竟初始化渲染的情况和点击父节点的情况是不一样的

**Comment by zombieJ** [comment]
对于这种情况，就需要自己控制一下了 checkedKeys 了。多一个子节点是让父节点变成不选中，还是让子节点一起选中这是业务逻辑相关的。这不是 Tree 组件本身可以判断的。反过来一样会有 issue 说动态加载的子节点没有被勾选。
从组件设计而言，勾选逻辑应该保持一致。初始化根据 checked 进行传导，那么之后的行为也应该是传导的。

**Comment by HuYuee** [comment]
好的

**Comment by koupeng** [comment]
锁了半天，还得自己控制。。。。

**Comment by stoneAlbert** [comment]
希望在onchange方法中 增加一个参数 为halfCheckedKeys  直接使用半选数组 很常用

**Comment by SoberChina** [comment]
这个问题还有回复吗？

**Comment by wangshanqiang** [comment]
请问下这个有人解决了没呢~~

**Comment by xiaoyaojk** [comment]
看来是 没解决~~

**Comment by skyvow** [comment]
项目中碰到了一样的问题，研究了一下是需要自行控制 checkedKeys，写个了简单的 demo 希望能帮助到大家。😆
`import React, { PureComponent } from 'react'
import { Tree } from 'antd'

// 去重
const unique = (arr) => [...new Set(arr)]

// 过滤
const filter = (arr1, arr2) => arr1.filter((v) => arr2.indexOf(v) === -1)

// 获取字段名
const getFieldName = (field, suffix = 'checked') => `${field}${suffix.charAt(0).toLocaleUpperCase()}${suffix.slice(1)}`

/**
 * 判断数组是否包含
 */
function isContained (wrapArr, innerArr) {
  if (!Array.isArray(wrapArr) || !Array.isArray(innerArr)) return false
  if (wrapArr.length < innerArr.length) return false
  for (let i = 0, len = innerArr.length; i < len; i++) {
    if (wrapArr.indexOf(innerArr[i]) === -1) return false
  }
  return true
}

/**
 * 获取指定元素的所有父级节点
 */
function getAllParentList(data, id) {
  const result = []
  const deep = (id, isRoot) => {
    for (let i = 0, len = data.length; i < len; i++) {
      const v = data[i]
      if (v.id === id) {
        if (!isRoot) {
          result.push(v.id)
        }
        if (v.parentId && v.parentId !== '0') {
          deep(v.parentId, false)
        }
        break
      }
    }
  }
  deep(id, true)
  return result
}

/**
 * 获取指定元素的所有子级节点
 */
function getAllChildList(tree, id) {
  const result = []
  const deep = (data) => {
    for (let i = 0, len = data.length; i < len; i++) {
      const v = data[i]
      result.push(v.id)
      if (v.children && v.children.length) {
        deep(v.children)
      }
    }
  }
  const find = (data) => {
    for (let i = 0, len = data.length; i < len; i++) {
      const v = data[i]
      if (v.id === id) {
        deep(v.children || [])
        break
      } else if (v.children && v.children.length) {
        find(v.children)
      }
    }
  }
  find(tree)
  return result
}

/**
 * 获取半选状态下的节点
 */
function getHalfCheckedKeys(tree, keys) {
  const result = []
  const deep = (keys) => {
    for (let i = 0, len = keys.length; i < len; i++) {
      const v = keys[i]
      const childList = getAllChildList(tree, v)
      const isAllChecked = isContained(keys, childList)
      if (!isAllChecked) {
        result.push(v)
      }
    }
  }
  deep(keys)
  return result
}

/**
 * Array to tree
 */
function arrayToTree(
  array,
  id = 'id',
  parentId = 'pid',
  children = 'children'
) {
  const result = []
  const hash = {}
  const data = [...array]

  data.forEach((item, index) => {
    hash[data[index][id]] = data[index]
  })

  data.forEach(item => {
    const hashParent = hash[item[parentId]]
    if (hashParent) {
      !hashParent[children] && (hashParent[children] = [])
      hashParent[children].push(item)
    } else {
      result.push(item)
    }
  })
  return result
}

const treeData = [{
  "name": "M0-手工",
  "pId": "2",
  "id": "21",
}, {
  "name": "M1中-手工",
  "pId": "2",
  "id": "22",
}, {
  "name": "M1中-手工A组",
  "pId": "22",
  "id": "221",
}, {
  "name": "Root",
  "pId": "0",
  "id": "1",
}, {
  "name": "M2低-手工A组",
  "pId": "3",
  "id": "31",
}, {
  "name": "First",
  "pId": "1",
  "id": "2",
}, {
  "name": "M1中-手工B组",
  "pId": "22",
  "id": "222",
}, {
  "name": "M2低-手工B组",
  "pId": "3",
  "id": "32",
}, {
  "name": "M0-手工B组",
  "pId": "21",
  "id": "211",
}, {
  "name": "Second",
  "pId": "1",
  "id": "3",
}]

const menuIdsList = treeData.map((v) => ({ ...v, title: `${v.name}__${v.id}`, value: v.id, key: v.id, parentId: v.pId, icon: null }))
const menuIdsTree = arrayToTree(menuIdsList, 'id', 'parentId')
const menuIds = ["21", "2", "1", "211"]

export default class Index extends PureComponent {
  constructor(props) {
    super(props)
    this.state = {
      menuIdsList,
      menuIdsTree,
      menuIds,
    }
  }

  onCheck = ({ checked, halfChecked }, { node: { props } }, field) => {
    const { id } = props
    const isAdd = checked.includes(id)
    const treeName = getFieldName(field, 'tree')
    const listName = getFieldName(field, 'list')
    const childIds = getAllChildList(this.state[treeName], id)
    const parentIds = getAllParentList(this.state[listName], id)

    if (isAdd) {
      this.setState({
        [field]: unique([...checked, ...halfChecked, ...parentIds, ...childIds])
      })
    } else {
      this.setState({
        [field]: filter([...checked, ...halfChecked], childIds),
      })
    }
  }

  render() {
    const { menuIdsList = [], menuIdsTree = [], menuIds = [] } = this.state
    const menuIdsHalfChecked = getHalfCheckedKeys(menuIdsTree, menuIds)
    const menuIdsChecked = filter(menuIds, menuIdsHalfChecked)

    return (
      <div>
        {menuIdsList.length > 0 ?
          <Tree
            checkedKeys={{ checked: menuIdsChecked, halfChecked: menuIdsHalfChecked }}
            checkable
            checkStrictly
            defaultExpandedKeys={menuIdsList.map((v) => v.id)}
            treeData={menuIdsTree}
            onCheck={(...args) => this.onCheck(...args, 'menuIds')}
          /> : null}
          {'menuIds: ' + menuIds}
      </div>
    )
  }
}`

**Comment by Shen120** [comment]
> 项目中碰到了一样的问题，研究了一下是需要自行控制 checkedKeys，写个了简单的 demo 希望能帮助到大家。😆
> 
> ```js
> import React, { PureComponent } from 'react'
> import { Tree } from 'antd'
> 
> // 去重
> const unique = (arr) => [...new Set(arr)]
> 
> // 过滤
> const filter = (arr1, arr2) => arr1.filter((v) => arr2.indexOf(v) === -1)
> 
> // 获取字段名
> const getFieldName = (field, suffix = 'checked') => `${field}${suffix.charAt(0).toLocaleUpperCase()}${suffix.slice(1)}`
> 
> /**
>  * 判断数组是否包含
>  */
> function isContained (wrapArr, innerArr) {
>   if (!Array.isArray(wrapArr) || !Array.isArray(innerArr)) return false
>   if (wrapArr.length < innerArr.length) return false
>   for (let i = 0, len = innerArr.length; i < len; i++) {
>     if (wrapArr.indexOf(innerArr[i]) === -1) return false
>   }
>   return true
> }
> 
> /**
>  * 获取指定元素的所有父级节点
>  */
> function getAllParentList(data, id) {
>   const result = []
>   const deep = (id, isRoot) => {
>     for (let i = 0, len = data.length; i < len; i++) {
>       const v = data[i]
>       if (v.id === id) {
>         if (!isRoot) {
>           result.push(v.id)
>         }
>         if (v.parentId && v.parentId !== '0') {
>           deep(v.parentId, false)
>         }
>         break
>       }
>     }
>   }
>   deep(id, true)
>   return result
> }
> 
> /**
>  * 获取指定元素的所有子级节点
>  */
> function getAllChildList(tree, id) {
>   const result = []
>   const deep = (data) => {
>     for (let i = 0, len = data.length; i < len; i++) {
>       const v = data[i]
>       result.push(v.id)
>       if (v.children && v.children.length) {
>         deep(v.children)
>       }
>     }
>   }
>   const find = (data) => {
>     for (let i = 0, len = data.length; i < len; i++) {
>       const v = data[i]
>       if (v.id === id) {
>         deep(v.children || [])
>         break
>       } else if (v.children && v.children.length) {
>         find(v.children)
>       }
>     }
>   }
>   find(tree)
>   return result
> }
> 
> /**
>  * 获取半选状态下的节点
>  */
> function getHalfCheckedKeys(tree, keys) {
>   const result = []
>   const deep = (keys) => {
>     for (let i = 0, len = keys.length; i < len; i++) {
>       const v = keys[i]
>       const childList = getAllChildList(tree, v)
>       const isAllChecked = isContained(keys, childList)
>       if (!isAllChecked) {
>         result.push(v)
>       }
>     }
>   }
>   deep(keys)
>   return result
> }
> 
> /**
>  * Array to tree
>  */
> function arrayToTree(
>   array,
>   id = 'id',
>   parentId = 'pid',
>   children = 'children'
> ) {
>   const result = []
>   const hash = {}
>   const data = [...array]
> 
>   data.forEach((item, index) => {
>     hash[data[index][id]] = data[index]
>   })
> 
>   data.forEach(item => {
>     const hashParent = hash[item[parentId]]
>     if (hashParent) {
>       !hashParent[children] && (hashParent[children] = [])
>       hashParent[children].push(item)
>     } else {
>       result.push(item)
>     }
>   })
>   return result
> }
> 
> const treeData = [{
>   "name": "M0-手工",
>   "pId": "2",
>   "id": "21",
> }, {
>   "name": "M1中-手工",
>   "pId": "2",
>   "id": "22",
> }, {
>   "name": "M1中-手工A组",
>   "pId": "22",
>   "id": "221",
> }, {
>   "name": "Root",
>   "pId": "0",
>   "id": "1",
> }, {
>   "name": "M2低-手工A组",
>   "pId": "3",
>   "id": "31",
> }, {
>   "name": "First",
>   "pId": "1",
>   "id": "2",
> }, {
>   "name": "M1中-手工B组",
>   "pId": "22",
>   "id": "222",
> }, {
>   "name": "M2低-手工B组",
>   "pId": "3",
>   "id": "32",
> }, {
>   "name": "M0-手工B组",
>   "pId": "21",
>   "id": "211",
> }, {
>   "name": "Second",
>   "pId": "1",
>   "id": "3",
> }]
> 
> const menuIdsList = treeData.map((v) => ({ ...v, title: `${v.name}__${v.id}`, value: v.id, key: v.id, parentId: v.pId, icon: null }))
> const menuIdsTree = arrayToTree(menuIdsList, 'id', 'parentId')
> const menuIds = ["21", "2", "1", "211"]
> 
> export default class Index extends PureComponent {
>   constructor(props) {
>     super(props)
>     this.state = {
>       menuIdsList,
>       menuIdsTree,
>       menuIds,
>     }
>   }
> 
>   onCheck = ({ checked, halfChecked }, { node: { props } }, field) => {
>     const { id } = props
>     const isAdd = checked.includes(id)
>     const treeName = getFieldName(field, 'tree')
>     const listName = getFieldName(field, 'list')
>     const childIds = getAllChildList(this.state[treeName], id)
>     const parentIds = getAllParentList(this.state[listName], id)
> 
>     if (isAdd) {
>       this.setState({
>         [field]: unique([...checked, ...halfChecked, ...parentIds, ...childIds])
>       })
>     } else {
>       this.setState({
>         [field]: filter([...checked, ...halfChecked], childIds),
>       })
>     }
>   }
> 
>   render() {
>     const { menuIdsList = [], menuIdsTree = [], menuIds = [] } = this.state
>     const menuIdsHalfChecked = getHalfCheckedKeys(menuIdsTree, menuIds)
>     const menuIdsChecked = filter(menuIds, menuIdsHalfChecked)
> 
>     return (
>       <div>
>         {menuIdsList.length > 0 ?
>           <Tree
>             checkedKeys={{ checked: menuIdsChecked, halfChecked: menuIdsHalfChecked }}
>             checkable
>             checkStrictly
>             defaultExpandedKeys={menuIdsList.map((v) => v.id)}
>             treeData={menuIdsTree}
>             onCheck={(...args) => this.onCheck(...args, 'menuIds')}
>           /> : null}
>           {'menuIds: ' + menuIds}
>       </div>
>     )
>   }
> }
> ```

bug 
![image](https://user-images.githubusercontent.com/33613409/186381524-a4326cb7-987a-4efe-9160-9e7fc5325097.png)

**Comment by hooliy** [comment]
24年了，有没有好的解决方案呢？

**Comment by alanhi** [comment]
要想收集使用父节点就得取消父子关联，但会导致需要一个一个去点选项。
我是这样做的，加上checkStrictly取消父子项的关联，然后通过父元素的选中控制子元素选中
```
<Tree
  checkable
  checkStrictly
  showLine
  treeData={treeData}
  expandedKeys={expandedKeys}
  checkedKeys={checkedKeys}
  onExpand={(expandedKeys) => setExpandedKeys(expandedKeys as string[])}
  onCheck={({ checked }, info) => {
    const keys = new Set(checked as string[]);
    if (info.node.children) {
      const subKeys = findNodesKey(info.node.children);
      subKeys.forEach((key) => {
        if (info.checked) {
          keys.add(key);
        } else {
          keys.delete(key);
        }
      });
    }
    setCheckedKeys(Array.from(keys));
  }}
/>

const findNodesKey = (nodes: TreeDataNode[]): string[] => {
  const keys: string[] = [];
  nodes.forEach((node) => {
    keys.push(node.key as string);
    if (node.children) {
      const subKeys = findNodesKey(node.children);
      keys.push(...subKeys);
    }
  });
  return keys;
};
```

<img width="436" alt="image" src="https://github.com/user-attachments/assets/d10af836-86b4-47c1-bebc-dc6cb4f363cd">

**Comment by heyepeng** [comment]
保存的时候，合并checked和halfChecked保存，以下是还原全选半选的方法，目前没发现问题，有需要的可以验证一下。

```
import { PageContainer } from "@ant-design/pro-components";
import { Card, Tree, TreeDataNode, TreeProps } from "antd";
import React from "react";

const constTreeData: TreeDataNode[] = [
  {
    title: "0-0",
    key: "0-0",
    children: [
      {
        title: "0-0-0",
        key: "0-0-0",
        children: [
          { title: "0-0-0-0", key: "0-0-0-0" },
          { title: "0-0-0-1", key: "0-0-0-1" },
          { title: "0-0-0-2", key: "0-0-0-2" },
        ],
      },
      {
        title: "0-0-1",
        key: "0-0-1",
        children: [
          { title: "0-0-1-0", key: "0-0-1-0" },
          { title: "0-0-1-1", key: "0-0-1-1" },
          { title: "0-0-1-2", key: "0-0-1-2" },
        ],
      },
      {
        title: "0-0-2",
        key: "0-0-2",
      },
    ],
  },
  {
    title: "0-1",
    key: "0-1",
    children: [
      { title: "0-1-0-0", key: "0-1-0-0" },
      { title: "0-1-0-1", key: "0-1-0-1" },
      { title: "0-1-0-2", key: "0-1-0-2" },
    ],
  },
  {
    title: "0-2",
    key: "0-2",
  },
];

const checkedData = ["0-0", "0-0-1","0-0-0", "0-0-1-0","0-0-0-0","0-0-0-1"];

let checked: string[] = [];
let halfChecked: string[] = [];

const initCheckedKeys = (data) => {
  data.forEach(({ key, children }) => {
    if (checkedData.includes(key)) {
      if (children && children.length > 0) {
        let matchKeys: string[] = [];
        children.forEach(({ key: cKey }) => {
          if (checkedData.includes(cKey)) {
            matchKeys.push(cKey);
          }
        });
        if (matchKeys.length === children.length) {
          checked.push(key);
        } else {
          halfChecked.push(key);
        }
        initCheckedKeys(children);
      } else {
        checked.push(key);
      }
    }
  });
};

initCheckedKeys(constTreeData);

console.log("keys", checked, halfChecked);
const Welcome: React.FC = () => {

  const onCheck: TreeProps["onCheck"] = (a, info) => {
    console.log("onCheck", a, info);
  };


  return (
    <PageContainer>
      <Card>
        <Tree
          showLine
          checkable
          checkStrictly
          checkedKeys={{ checked, halfChecked }}
          onCheck={onCheck}
          treeData={constTreeData}
        ></Tree>
      </Card>
    </PageContainer>
  );
};

export default Welcome;
```
