### ISSUE TITLE
DatePicker组件，更换年，或者月之后提交，日期不更改

### ISSUE THREAD

**Issue by duxiaofeng-github** [ant-design/ant-design#9809]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS 10.13.3 (17D102), Chrome 版本 65.0.3325.181（正式版本）（64 位）

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
在日期时间选择的块中，切换一个月份，或者年份，再点确定。

### What is expected?
我只切换月份、年份时，点击确定，应该也可以生效。

### What is actually happening?
只切换月份、年份时点确定，日期不生效。

---
我的场景是，用户选中了当前时间，但用户有时只想切换月份，或者年份，切换完后点确定是很自然的行为。

然而现在必须选天，再点确定才能生效。

而且有另一个问题是，日历打开的时候，天已经是选中的，为蓝色的块。这个时候，用户切换完年月之后，认为天已经选中了，然后就点了确定，结果没有生效，就会感觉莫名其妙。

**Comment by afc163** [comment]
目前的行为是需要点击日期才会触发日期改动，感觉可以优化一下。

**Comment by bobospirit** [comment]
这个问题现在还是没有解决呀，都已经更新到v3.23.5了。还是只有在选择日期的情况下才会更改值

**Comment by hoho2017** [comment]
是吗
