### ISSUE TITLE
react-hot-loader更新问题

### ISSUE THREAD

**Issue by xianshannan** [ant-design/ant-design#981]
用上antd后，react-hot-loader会无法更新,报错如下
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null

**Comment by afc163** [comment]
https://github.com/gaearon/react-hot-loader#deprecation-notice

**Comment by xianshannan** [comment]
跟这个没关系吧

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/751

**Comment by xianshannan** [comment]
换成react-transform，出现一样的问题，说明跟react-hot-loader没啥关系，
用上antd热替换就会出错无法更新

**Comment by afc163** [comment]
你可以试试 https://github.com/ant-design/antd-init

里面用了 react-transform 的热替换功能，我测试是可以的。

**Comment by Tinple** [comment]
Menu 导航菜单也有同样的问题，react-hot-loader 失效，换成 react-transform 可以 work

**Comment by xianshannan** [comment]
之前没把react-hot-loader配置去掉，换成react-transform的确可以。
Icon组件写法跟其他的组件不一样，不是使用createClass方法写的，直接就在方法中返回JSX。

**Comment by benjycui** [comment]
@xianshannan https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components
