### ISSUE TITLE
dataSource can't be rendered when the columns' children are added dynamically

### ISSUE THREAD

**Issue by stupid2013** [ant-design/ant-design#9811]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS 10.12.6、 Chrome 版本 65.0.3325.181（正式版本）（64 位）、 react 15.4.0

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
codes:
![codes](http://ww4.sinaimg.cn/large/0060lm7Tly1fpq73wuou8j314c0zogrp.jpg)

result:
![result](http://ww1.sinaimg.cn/large/0060lm7Tly1fpq71oxgsej318u0a00t9.jpg)

as you can see, the data are't loaded to the table.

### What is expected?
the data can rendered normally, and i can get current record in the render function.

### What is actually happening?
the data can't rendered normally， and i can't get current record in the render function.

**Comment by afc163** [comment]
```diff
- data={data}
+ dataSource={data}
```

**Comment by stupid2013** [comment]
我刚刚提完就发现了这个问题= = 我太粗心了 = = 但是 谢谢你！！！ reply so soon！！！点赞！
