### ISSUE TITLE
Tooltip will show with offset only on first time if tooltip contains a image

### ISSUE THREAD

**Issue by ToffeeLu** [ant-design/ant-design#9813]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
CodePen

### Reproduction link
[https://codepen.io/anon/pen/rdGpWx?&editors=001](https://codepen.io/anon/pen/rdGpWx?&editors=001)

### Steps to reproduce
1. move mouse hover "Tooltip"
1. find that tooltip show with right offset
1. move mouse away
1. move mouse hover "Tooltip" again
1. everything works fine

### What is expected?
tooltips works fine at first time mouse hover it

### What is actually happening?
tooltip shows offset at first time, but works fine later

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/OvxeVW?&editors=001

You should fix the width of tooltip content.

**Comment by ToffeeLu** [comment]
thanks!
