### ISSUE TITLE
Customize Theme with Sass and Webpack

### ISSUE THREAD

**Issue by Kruemelkatze** [ant-design/ant-design#9815]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have a situation many others have: A project using Sass, but with the need to customize Ant Design. We found a quite simple solution to override Ant-variables in a Sass file. This eliminates the need for seperate Less and Sass variable files for Ant Design and your project.

### What does the proposed API look like?
We set up a guide here: [https://gist.github.com/Kruemelkatze/057f01b8e15216ae707dc7e6c9061ef7](https://gist.github.com/Kruemelkatze/057f01b8e15216ae707dc7e6c9061ef7)
If needed, we can also provide a simple example repo, but we think a Gist does a better job in this.

Maybe you can place it in [https://ant.design/docs/react/customize-theme](https://ant.design/docs/react/customize-theme) as a related article.

**Comment by yesmeck** [comment]
I've added it to the related article, thanks!

**Comment by afc163** [comment]
How about https://github.com/prncc/antd-scss-theme-plugin ?

**Comment by Kruemelkatze** [comment]
As it was released yesterday, we did not know about this before. Looks great!

**Comment by max8hine** [comment]
I tend to think Ant_Design should be serious about providing a simple Scss based default theme, **without all the hassles** of the sass-less hack.
Something like `Zurb-Foundation` does, super easy to intergrade with any kind of project, as long as the project use node-sass or another sass compiler.

Both solutions rely on Webpack.

In my case, the node project I work on that only using `node-sass-middleware` to compile Scss to CSS when browser request in the runtime.
