### ISSUE TITLE
2.11.1版本之后form设值异常

### ISSUE THREAD

**Issue by LeeHarlan** [ant-design/ant-design#9816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.11.1

### Environment
chrome 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j707lnr6xw)

### Steps to reproduce
form的值是从redux store获取，Set item的值之后form更新，在clear item的值时，form没有重新渲染

### What is expected?
clear item的值之后form内容应该也清空

### What is actually happening?
clear item的值之后form内容没有清空

---
这个问题已经存在好久了(难道没人使用2.11.0之后的版本？)，由于我这里sandbox环境不稳定，迟迟没有提issue。3.3.x没有这个问题

**Comment by benjycui** [comment]
你 reducer 写错了，根本就没有删除数据。

**Comment by LeeHarlan** [comment]
没写错啊？我把antd版本切换到2.11.0、3.4都表现正常，但是2.11.1之后的版本就表现异常

**Comment by benjycui** [comment]
问题在哪里？

<img src="http://g.recordit.co/wU1QATP4Af.gif" />

**Comment by LeeHarlan** [comment]
我的意思是antd 2.11.0，3.4都表现正常，2.11.1之后的版本不对。我之前给你的重现链接里面是2.13.13的版本

**Comment by afc163** [comment]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/507615/38226837-13f76e32-372e-11e8-8262-ca4bbdac945e.png">

**Comment by LeeHarlan** [comment]
我最之前是重现是用的2.13.13版本，昨天你说我的写错了，后面我自己又改了好几个版本重试过，然后没改回去，2.11.1之后的版本都是有这个问题

**Comment by LeeHarlan** [comment]
![Uploading antd2.11.1.gif…]()

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/38227127-4c3b85fc-372f-11e8-86b8-5436831f34b1.gif)

确实不一样。@benjycui

**Comment by LeeHarlan** [comment]
![antd2 11 1](https://user-images.githubusercontent.com/14872348/38227212-c978bbca-372f-11e8-84e8-9d626e661ce4.gif)

**Comment by benjycui** [comment]
ref: https://github.com/react-component/form/issues/104

2.11.1 后升级 rc-form 为 1.4.x 了 https://github.com/ant-design/ant-design/blob/2.11.1/package.json#L57

**Comment by benjycui** [comment]
这个行为还是不改了，因为这样来回改也会引发其他的问题。

建议升级 antd 或者把 rc-form 锁定版本为 1.3.x
