### ISSUE TITLE
tables组件的filter示例报错

### ISSUE THREAD

**Issue by light-night** [ant-design/ant-design#982]
**问题描述**

tables组件的filter示例报错

**发生环境**

- antd 版本：
- 操作系统及版本：mac 10
- 浏览器及版本：chrome 46
- 在线演示地址：http://ant.design/components/table/#demo-head

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://ant.design/components/table/#demo-head

**Comment by afc163** [comment]
非常感谢反馈。

> 备注： 0.12.0 本身没有问题，是后面的一个改动导致的。
