### ISSUE TITLE
3.3.3 版本 Table的每一列不指定宽度时，并且设置每一列的内容文字不换行，自动拉伸得到的宽度计算错误

### ISSUE THREAD

**Issue by sam019** [ant-design/ant-design#9822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS 10.13.3 chrome 65 react 3.3.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2xoywn56z)

### Steps to reproduce
在重现链接的页面中，将右侧窗口宽度调小，不会出现滚动条，文字有重叠现象。将宽度调大时，各行的宽度填充未按照原有比例填充，导致内容多的列看起来很拥挤，内容少的列看起来很「空旷」

### What is expected?
窗口宽度较小时，小于自然展示所需最小宽度时，能自动出现滚动条。宽度较大时，能按照内容原始宽度的比例扩充。

### What is actually happening?
宽度小时，未出现滚动条。较大时，填充的比例不对

**Comment by yesmeck** [comment]
没重现你说的问题，能给个截图吗？

**Comment by sam019** [comment]
![case](http://p3pks49rk.bkt.gdipper.com/WX20180327-152925.png)

@yesmeck 像图中这样，ABC列的宽度依次递减，在拉伸后，ABC一样宽了，A和B没有得到更大的宽度。而且没有自动出现滚动条

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/pull/9704 引起的，已经 revert 掉，会在下个版本修复。

**Comment by fayhy** [comment]
@yesmeck 目前最新的 3.5.0 还没有 revert 掉，[c7e4167](https://github.com/ant-design/ant-design/commit/c7e4167486429aa34333b849086beb5ca45ce026) 貌似丢了
