### ISSUE TITLE
Checkbox or Switch in Form does not remain selected after coming  back from previous or next Step

### ISSUE THREAD

**Issue by mugilanm7** [ant-design/ant-design#9823]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome latest 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://o7jpk5wl09.codesandbox.io/)

### Steps to reproduce
1. Create Steps with two or more Step
2. Add checkbox using getFieldDecorator in one of the step
3. Check the checkbox and go to next step and come back again the checkbox is unselected

### What is expected?
Check box should be selected and remain in its state

### What is actually happening?
 checkbox is unselected

---
Same applies for switch

**Comment by afc163** [comment]
Just don't destroy inactive content.

https://codesandbox.io/s/lp97mz2nm9

**Comment by yutingzhao1991** [comment]
You should store the value by your self. Maybe Ant Design Pro https://preview.pro.ant.design/#/form/step-form/info can help you.

**Comment by mugilanm7** [comment]
Thanks @afc163 and @yutingzhao1991
