### ISSUE TITLE
InputNumber   Cursor position disorder 数字输入框 格式化展示 输入的光标错乱，无法连续输入完整数字

### ISSUE THREAD

**Issue by huerhai** [ant-design/ant-design#9826]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
任何环境

### Reproduction link
[http://ant-design.gitee.io/components/input-number-cn/](http://ant-design.gitee.io/components/input-number-cn/)

### Steps to reproduce
1 delete $ 1,000
2 input  1234

### What is expected?
1234

### What is actually happening?
3421

---
这个问题很严重诶~

**Comment by Kamahl19** [comment]
I also have a problem with the cursor jumping, when i type 12345 it types 12,354

**Comment by JQuu** [comment]
I have the same issue when using thousand separator formatters, this is happening sporadically.

**Comment by JQuu** [comment]
This issue is actually caused by rc-input-number component that antd inherited, I have submit a issue report to them as well. 

https://github.com/react-component/input-number/issues/98

这个bug是rc-input-number component的锅，我提了个issue 给他们， 链接在此。

**Comment by chenhaizhou** [comment]
this issue still have on v3.6.3
