### ISSUE TITLE
IE11 Incorrect positioning of DatePicker and Cascader controls within Form Items

### ISSUE THREAD

**Issue by Portalesoft** [ant-design/ant-design#9827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Windows 10, IE 11

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
View the Cascader control in the 'Registration' demo and the DatePicker fields in the 'Time-related Controls' demo on the ant.design website. Both controls are aligned to the top of the form item. If the DatePicker uses hasFeedback this additionally renders the feedback outside of the control.

### What is expected?
Cascader and DatePicker controls should be aligned the same as every other control in the demo.

### What is actually happening?
The Cascader and DatePicker controls are aligned to the top of the FormItem.

---
Creating own forms and testing in IE11, checked demo site to confirm issue.

**Comment by 15531400827** [comment]
Do you have a solution? I use IE11 and Firefox 45.9.0, and Datepicker and InputNumber components are aligned to the top.

**Comment by afc163** [comment]
These `display: block` cause the problem:

- [ ] InputNumber: https://github.com/ant-design/ant-design/commit/e3b6430a4b23b2e6c24c74e23d26f1b454c9cd42
- [ ] DatePicker: https://github.com/ant-design/ant-design/commit/43751c9930b988f8f4d52647d39ca9a3d34267ca
