### ISSUE TITLE
react dva antd webpack整合后ie不能正常运行

### ISSUE THREAD

**Issue by CarlLucasYu** [ant-design/ant-design#9828]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
系统:win7,浏览器:ie11

### Reproduction link
[http://www.linuxprobe.org](http://www.linuxprobe.org)

### Steps to reproduce
打开ie访问重现链接

### What is expected?
ie能够正常运行

### What is actually happening?
ie不能正常运行

---
webpack已经在入口处配置了babel_polyfill: "babel-polyfill",但是仍然无法运行，错误信息为：无法获取未定义或 null 引用的属性“call”
以下是package.json配置
{
  "name": "react-ui-demo",
  "version": "1.0.0",
  "description": "react-ui-demo",
  "author": "linuxprobe",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js"
  },
  "dependencies": {
    "antd": "^3.3.1",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "dva": "^2.1.0",
    "dva-loading": "^1.0.4",
    "query-string": "^6.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.7",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "redux": "^3.7.2",
    "styled-components": "^3.2.3"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-af-react": "^0.4.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-flowtype": "^2.46.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-react": "^7.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "less": "^3.0.0",
    "less-loader": "^4.1.0",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "react-hot-loader": "^4.0.0",
    "redbox-react": "^1.5.0",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "style-loader": "^0.20.3",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
以下是webpack入口的部分配置：
context: path.resolve(__dirname, '../'),
  /** 入口文件 */
  entry: {
    babel_polyfill: "babel-polyfill",
    index: path.resolve(__dirname, '../','./src/index.js')
  },
  /** 编译输出配置 */
  output: {
    /** 打包后的文件存放的地方 */
    path: config.build.assetsRoot,
    /** 打包后输出文件的文件名 */
    filename: '[name].js',
    /** 对于按需加载(on-demand-load)或加载外部资源(external resources)（如图片、文件等）来说，
     * output.publicPath 是很重要的选项。如果指定了一个错误的值，则在加载这些资源时会收到 404 错误 */
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },

**Comment by yesmeck** [comment]
@CarlLucasYu 提供一个精简的可重现的 repo。

**Comment by CarlLucasYu** [comment]
@yesmeck 使用ie11打开我提供的链接，www.linuxprobe.org,然后页面不会渲染，你打开开发者工具就能看到这个错误了。

**Comment by CarlLucasYu** [comment]
[react-ui-demo.zip](https://github.com/ant-design/ant-design/files/1887185/react-ui-demo.zip)
@ant-design-bot this is source code
