### ISSUE TITLE
How to change months shortcuts to other language than english?

### ISSUE THREAD

**Issue by bartekcajdler** [ant-design/ant-design#9829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I added LocaleProvider with pl_PL but I can still see months shortcuts in english, other elements are in polish language. is it possible to change it? can i add polish shortcuts for months? I checked it also with french locales but the same behaviour. 

### What does the proposed API look like?
Add possibility to adding custom months shortcuts

**Comment by yesmeck** [comment]
> I added LocaleProvider with pl_PL but I can still see months shortcuts in english

Sounds like a bug, could you reproduce it on https://codesandbox.io ?

**Comment by bartekcajdler** [comment]
look at it: 
https://codesandbox.io/s/kmr1pw5m95  (polish)
https://codesandbox.io/s/61xmyyn953 (french)
You can see 'Miesiac' and 'Rok' in polish but shortcuts for months and days are still in english

**Comment by yesmeck** [comment]
Please refer to the LocaleProvider documentation https://ant.design/components/locale-provider/, you need to import locale of moment as well.

**Comment by bartekcajdler** [comment]
Oh I missed it :) thanks

**Comment by loustak** [comment]
I have the exact same problem, but I don't want to use moment because it's bloated. I'm using date-fns. Any ideas how I could solve this issue?
