### ISSUE TITLE
Badge重置count无效

### ISSUE THREAD

**Issue by liuchaofeng1230** [ant-design/ant-design#983]
Badge修改count后无效

**发生环境**

- antd 版本：0.11.2
- 操作系统及版本：mac
- 浏览器及版本：chrome48

BUG代码:
(截图上传不了。。。)
https://github.com/ant-design/ant-design/blob/master/components/badge/ScrollNumber.jsx 40行

return始终被触发，建议改为 this.state.count === nextProps.count

**Comment by afc163** [comment]
http://ant.design/components/badge/#demo-change

这个例子是有效的，是否有重现代码？

**Comment by afc163** [comment]
我这里重现了。

**Comment by afc163** [comment]
感谢反馈。
