### ISSUE TITLE
Modal's okButton, more quick click, run more times (Popconfirm,Modal.confirm)

### ISSUE THREAD

**Issue by feiZhang** [ant-design/ant-design#9831]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j4lkppzkmy)

### Steps to reproduce
1. show one modal
2. quick click ok button.

### What is expected?
click ok button more times, only run one times

### What is actually happening?
click more times ok button, run more times.

---
1. Modal.confirm  Popconfirm    ,  The same problem
2. some time , onOk run slow, click one time, no reaction, client click more

**Comment by afc163** [comment]
https://codesandbox.io/s/n48l15jm7m

**Comment by feiZhang** [comment]
https://codesandbox.io/s/momkjyww8x
hideModal = e => {
    console.log(1111);
    this.setState({ visible: false });
};


Quick click many times，Such as Double click。
Show more 111 log。hideModal run more times。

expected:
<input type='button' onclick="javascript:{this.disabled=true;console.log(new Date())}" value="To compare(no problem)"></input>

but setState Need a lot of time
