### ISSUE TITLE
make the sider zero-width trigger color not hardcoded to white. 

### ISSUE THREAD

**Issue by Scott-Tugboat** [ant-design/ant-design#9834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, you can override the @layout-sider-background, @layout-trigger-background and @layout-trigger-color LESS vars. If you have a sider that is set to have a white background and is collapsible, you can not see the icon in the zero-width trigger because it is hardcoded to white. (see line 100 in https://github.com/ant-design/ant-design/blob/master/components/layout/style/index.less) Changing this property to use the @layout-trigger-color var would allow for changing the text color in the zero-width trigger. 

Since the project that I'm working on requires a sider that is white, I'm unable to collapse it because the zero-width trigger color is also white. Sad. 

### What does the proposed API look like?
Currently, the LESS is set to this:
```
&-trigger {
        position: absolute;
        top: @layout-header-height;
        right: -@layout-zero-trigger-width;
        text-align: center;
        width: @layout-zero-trigger-width;
        height: @layout-zero-trigger-height;
        line-height: @layout-zero-trigger-height;
        background: @layout-sider-background;
        color: #fff;
        font-size: @layout-zero-trigger-width / 2;
        border-radius: 0 @border-radius-base @border-radius-base 0;
        cursor: pointer;
        transition: background .3s ease;
```
I propose it be changed to:
```
&-trigger {
        position: absolute;
        top: @layout-header-height;
        right: -@layout-zero-trigger-width;
        text-align: center;
        width: @layout-zero-trigger-width;
        height: @layout-zero-trigger-height;
        line-height: @layout-zero-trigger-height;
        background: @layout-sider-background;
        color: @layout-trigger-color;
        font-size: @layout-zero-trigger-width / 2;
        border-radius: 0 @border-radius-base @border-radius-base 0;
        cursor: pointer;
        transition: background .3s ease;
```
This would be much appreciated. 
**thank you.**

**Comment by yutingzhao1991** [comment]
@Scott-Tugboat could you make a PR on it?

**Comment by Scott-Tugboat** [comment]
Pull Request has been created: https://github.com/ant-design/ant-design/pull/9851
