### ISSUE TITLE
upload component need notice or doc

### ISSUE THREAD

**Issue by ybintian** [ant-design/ant-design#9835]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
upload component check url is  image url to render file icon or img is so obscure

### What does the proposed API look like?
doc need be more detail

**Comment by ybintian** [comment]
/^data:image\//.test(url) || /\.(webp|svg|png|gif|jpg|jpeg)$/.test(url)

**Comment by yutingzhao1991** [comment]
related PR https://github.com/ant-design/ant-design/pull/9621

**Comment by afc163** [comment]
I think #9621 is a bad idea, we should use a prop to mark image-type list.

**Comment by ybintian** [comment]
if my image url is only a redirect url without extension，it‘s  hard to use @afc163

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/9936
