### ISSUE TITLE
v0.12下 select组件的验证存在问题

### ISSUE THREAD

**Issue by lyd600lty** [ant-design/ant-design#984]
<Select {...getFieldProps('type', {
        rules: [
            {required: true}
        ]
    })}>
    <Option key="123" value="123">123</Option>
    {[1,2,3].map(function(item ,i) {
        return (
            <Option key={i} value={item}>{item}</Option>
        );
    }, this)}
    </Select>

选中123时正常，选中map返回的option时会出现required的message

**Comment by yiminghe** [comment]
<Option key={i} value={String(item)}>{item}</Option>

**Comment by lyd600lty** [comment]
@yiminghe {item} ?

**Comment by benjycui** [comment]
[Select.Option](https://github.com/react-component/select/blob/master/src/Option.jsx) 加 `proptTypes` 可好？

**Comment by afc163** [comment]
我看这里支持数字了？https://github.com/react-component/select/commit/0bae6cfbacf23351b29b10d0bfd96b49fdc7f3f5

**Comment by yiminghe** [comment]
这里是有的是数字，有的是字符串， {required: true, type: ??}
