### ISSUE TITLE
弹出遮罩时，Input组件层级错乱

### ISSUE THREAD

**Issue by GravityMsc** [ant-design/ant-design#9840]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Win10 Chrome 65 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24kl3k2nyp)

### Steps to reproduce
直接在Dan的弹出示例进行更改，大体逻辑同自身项目一致。
在不对遮罩层做z-index限制时，默认情况Input层级还是在后续div之上，而其他组件如Select等不会出现问题

### What is expected?
Input被遮罩覆盖

### What is actually happening?
Input在遮罩之上

---
导致的 css 为 .ant-input-affix-wrapper .ant-input 的 z-index : 1。不是很清楚这个z-index你们为了解决什么问题，如果不能删除，我这边开发过程中自己对遮罩层做层级限制就好

**Comment by ddcat1115** [comment]
带前后缀的 input 为啥要加 z-index 的原因不太好追溯了，但遮罩层肯定需要加层级限制的，不然也很可能被其他元素穿透。
