### ISSUE TITLE
Menu item default color is wrong when wrapped with Badge and theme is dark

### ISSUE THREAD

**Issue by ToffeeLu** [ant-design/ant-design#9842]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
CodePen

### Reproduction link
[https://codepen.io/anon/pen/yKpoZB?editors=0010](https://codepen.io/anon/pen/yKpoZB?editors=0010)

### Steps to reproduce
1. Select "Option 2"
2. The first menu item of dark theme color is black, looks like invisible
3. Theme light works fine

### What is expected?
Menu item color should be same as "Option 2" which is white when menu theme is dark

### What is actually happening?
Theme dark should have same behavior as light

**Comment by afc163** [comment]
The problem is gone in latest antd version 😋
