### ISSUE TITLE
控制滚动条联动

### ISSUE THREAD

**Issue by LDD123** [ant-design/ant-design#9845]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问如何控制滚动条联动
一个是table另一个是footer    https://codesandbox.io/s/8z28zz08nj

### What does the proposed API look like?
滚动条联动

**Comment by afc163** [comment]
trace #5710

**Comment by LDD123** [comment]
这是要增加新的属性吗，我们在用antd2,12,3,如果增加新的属性，老版本还维护吗，如果需要我们自己加属性，能不能提供一些思路呢。多谢
