### ISSUE TITLE
Error when setting type as 'radio',which is one of the Table component  rowSelection's APIs with TypeScript language.

### ISSUE THREAD

**Issue by lunarsprite** [ant-design/ant-design#9846]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.4

### Environment
"antd": "^3.1.4","@types/react": "^16.0.35","react-redux": "^5.0.6",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54m301y1zp)

### Steps to reproduce
Hello,I want to make my table could be supported to single selection,so I try to set the type as 'radio', which is one of the Table component  rowSelection's APIs.By the way ,I am using TypeScript.  Here is part of my code block:   

``
const rowSelection = {
      onChange: (selectedRowKeys:any, selectedRows:any) => {
        console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
      },
      type: 'radio'
    };

    return (
      <Table rowKey='id'
        rowSelection={rowSelection}
        columns={columns}
        dataSource={ dataSource}
        pagination={this.props.pagination}
        onChange={this.handleTableChange}
        scroll={{ x: 900 }}
        bordered={false} />
    );
``

However,if I cancel some codes which were displaying  below：  

``
type: 'radio'
`` 

there is nothing error  message showing.

### What is expected?
 I can only select a row of table.

### What is actually happening?
error message:
``
 TS2322: Type '{ rowKey: string; rowSelection: { onChange: (selectedRowKeys: any, selectedRows: any) => void; ty...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Table<any>> & Readonly<{ children?: ReactNode; }> ...'.
  Type '{ rowKey: string; rowSelection: { onChange: (selectedRowKeys: any, selectedRows: any) => void; ty...' is not assignable to type 'Readonly<TableProps<any>>'.
    Types of property 'rowSelection' are incompatible.
      Type '{ onChange: (selectedRowKeys: any, selectedRows: any) => void; type: string; }' is not assignable to type 'TableRowSelection<any> | undefined'.
        Type '{ onChange: (selectedRowKeys: any, selectedRows: any) => void; type: string; }' is not assignable to type 'TableRowSelection<any>'.
          Types of property 'type' are incompatible.
            Type 'string' is not assignable to type '"checkbox" | "radio" | undefined'.
``

---
Sorry,the link does not show the error message because the code is not complete.There might be a conflict between antdesign and typescript when using  the 'type' attribute  of rowSelection in Table component.I really want to know how to deal with it .

**Comment by Dpy0407** [comment]
I have the same problem today.
when add type:'radio', the tslint in vscode show the error，& webpack build will fail.
but the antd api shows that:
 export interface TableRowSelection<T> {
type?: RowSelectionType;
...
}
and RowSelectionType is defined as:
export declare type RowSelectionType = 'checkbox' | 'radio';

here is my code:
  const rowSelection = {
            type:'radio',
            onChange: (selectedRowKeys:any, selectedRows:any) => {
              console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
            },
            getCheckboxProps: (record:any) => ({
              disabled: !record.enable, // Column configuration not to be checked
              name: record.name,
            }),
          };

        return (
            <Table
            rowSelection={rowSelection}
            columns={columns}
            dataSource={this.chipTypeList} />
        );

**Comment by Dpy0407** [comment]
I am try solving ths problem as follow:

import { RowSelectionType } from 'antd/lib/table'
...
const type: RowSelectionType = 'radio';
const rowSelection = {
            type: type,
...
}

it's looks have solved this problem, but it's not so perfect, due we must import RowSelectionType

**Comment by yesmeck** [comment]
Another solution is give "radio" a literal type:

```javascript
const rowSelection = {
  onChange: (selectedRowKeys: any, selectedRows: any) => {
    console.log(
      `selectedRowKeys: ${selectedRowKeys}`,
      "selectedRows: ",
      selectedRows
    );
  },
  type: "radio" as "radio"
};
```
