### ISSUE TITLE
Dropdown doesn't move down when a new line is added selecting element 

### ISSUE THREAD

**Issue by ealvarezk** [ant-design/ant-design#9849]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/32mw06yr21)

### Steps to reproduce
Select elements until you have one element in a new row in the input

### What is expected?
the dropdown should move down, to the end of the input

### What is actually happening?
Don't move, so the new line can't be see as you see in the picture
![image](https://user-images.githubusercontent.com/16323103/38039268-42872af8-3283-11e8-92e4-1568ba44cf32.png)

**Comment by ericjam3** [comment]
Hello, I would like to work on this issue for a class project. How long is this estimated to take for a first timer, and can I get any pointers on where to begin? Thanks!

**Comment by yesmeck** [comment]
Hello @ericjam3, @zombieJ has already worked on this issue, if you want to contribute to Ant Design, here is the contribution document https://ant.design/docs/react/contributing

**Comment by ealvarezk** [comment]
Any new about this?

**Comment by namhoai** [comment]
@MrPeak  I have a project that needs fixing this error can you help me fix it fast ? please !

**Comment by yesmeck** [comment]
Fixed in rc-select, try reinstall node_mdoules.

**Comment by namhoai** [comment]
thanks all <3 <3
