### ISSUE TITLE
Overriding Table style passing theme, props

### ISSUE THREAD

**Issue by dbrrt** [ant-design/ant-design#9854]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Some users doesn't like the default theme of the Table component, e.g: too much padding in cells

### What does the proposed API look like?
`<Table {...props}  theme={[ ...cellStyle, ...headerStyle, ...columnsStyle, ...paginationStyle ]}  />`

**Comment by yesmeck** [comment]
Please refer to https://ant.design/docs/react/customize-theme
