### ISSUE TITLE
Expand rows in tables with fixed columns, fixed column styles are out of order

### ISSUE THREAD

**Issue by ldwonday** [ant-design/ant-design#9855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
mac os

### Reproduction link
[https://codepen.io/anon/pen/EEQZxQ?&editors=001](https://codepen.io/anon/pen/EEQZxQ?&editors=001)

### Steps to reproduce
Set fixed columns

### What is expected?
Result OK

### What is actually happening?
Out of order

**Comment by yesmeck** [comment]
The expand row feature is not supposed to use with fixed columns.
