### ISSUE TITLE
Type of ColumnProps<T>['dataIndex'] should be keyof T instead of string

### ISSUE THREAD

**Issue by Jack-Works** [ant-design/ant-design#9856]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A more precise type for ColumnProps

### What does the proposed API look like?
```typescript
interface ColumnProps<T> {
...
dataIndex?: keyof T
...
}
```
Before:
![image](https://user-images.githubusercontent.com/5390719/38072508-3665d108-3359-11e8-9ac6-6ef3c233d77d.png)

After:
![image](https://user-images.githubusercontent.com/5390719/38072523-48c93d76-3359-11e8-9bc6-801ff6e466ef.png)

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/9393

**Comment by Aprillion** [comment]
can we **please** have a new property, e.g. `shallowDataIndex?: keyof T` for people who couldn't care less about the nested `dataIndex?: string` support, but would really love their typescript to be actually useful for something??? `string` is a really usellss type for such an important type check IMHO

**Comment by Jack-Works** [comment]
Yes, nested is really not friendly to the type system
