### ISSUE TITLE
The display of select and treeSelect components is not uniform in multiple choice cases.

### ISSUE THREAD

**Issue by BigBigWen** [ant-design/ant-design#9857]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
运行环境:win10,react版本:v13..2.0,浏览器chrom最新版

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
When the TreeSelect is multiple, select the option first, and then remove the option in the selection input, and the drop-down list disappears.

### What is expected?
The same as the behaviour of the Select component.when the selected item is deleted, the drop-down list is still there.

### What is actually happening?
The TreeSelect component, when the selected item is deleted, delete the first time, the drop-down list expands, delete the second. The drop-down list disappears.

**Comment by zombieJ** [comment]
Thanks for feed back. Let me check.

**Comment by zombieJ** [comment]
`rc-trigger` need improvement for this.

ref: https://github.com/react-component/tree-select/pull/109

**Comment by zombieJ** [comment]
Close since v4 use unique generator to handle this.
