### ISSUE TITLE
Wrong type for Table onChange

### ISSUE THREAD

**Issue by Jack-Works** [ant-design/ant-design#9858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### What is expected?
type of the second param (filtering option) is `Record<keyof T, string[]>`

### What is actually happening?
type of the second param is `string[]`

**Comment by yesmeck** [comment]
@Jack-Works Could you send a PR?

**Comment by baohouse** [comment]
While you're addressing the filters, may want to improve the sorter type as well. I think it's
```
{
  column: ColumnProps<T>;
  columnKey?: React.Key;
  field: string;
  order: 'ascend' | 'descend';
}
```
