### ISSUE TITLE
 Form  component of max, min, if the initial value is Number type, will be prompted to "* * * * is not a string", but not the correct check length

### ISSUE THREAD

**Issue by xiaosheng222** [ant-design/ant-design#9861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.13

### Environment
window，chrome63，react 15.4.2

### Reproduction link
https://codesandbox.io/s/k1ojk182oo

### Steps to reproduce
   <FormItem
                        label="注册资本："
                    >
                        {getFieldDecorator('regCapital', {
                            rules: [{ required: false }, { max: 20, message: '不超过20字符' }],
                            initialValue: getValueByProps(basicInfo, 'regCapital', null)
                        })(
                            <Input className="col" placeholder="可写到小数点后两位，例如52.67" />
                        )}
                        <span>万元</span>
                    </FormItem>

### What is expected?
Correct checking Number types of data

### What is actually happening?
Prompt '* * * * is not a string'

---
When the initial value to give a toString（） coercion

**Comment by xiaosheng222** [comment]
https://codesandbox.io/s/k1ojk182oo
ps: 页面不做任何操作，直接点击按钮

**Comment by dengfuping** [comment]
@xiaosheng222 The validation rules of `max` and `min` is for `string`. If you want to limit the range of `number`, you could customize your validator as the issue #5155 shows.

**Comment by hz-equityzen** [comment]
```{getFieldDecorator('num', {
                  type: 'number',                //<<-----------------------------
                })(
                  <Input />
                )}
```
