### ISSUE TITLE
Card loading leads its content shifting after loading over.

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#9862]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
browser version

### Reproduction link
[https://codepen.io/zheeeng/pen/BrYmwj](https://codepen.io/zheeeng/pen/BrYmwj)

### Steps to reproduce
1. Make sure the screen size is large enough, about 10 inches above. In the Codepen reproduction sample, you can resize the display board to a large enough size.

2. Try click the Card Component repeatedly you will find that the card content is shifting from top left corner to its position.

    2.1. If the first time you open the reproduction sample and the display board is small enough, the content is fixed at its right position. It is the expected behavior no matter what the display board size is.

### What is expected?
The Card content remains at its right position, no shifting transition effect.

### What is actually happening?
After loading over, the Card content shifts to its position.

In a large dashboard panel and there are many loading cards, the content shifting brings undesirable feelings. And it seems an absolute bug.

**Comment by ericjam3** [comment]
I would like to work on this issue since it is still open. Will this be possible?

**Comment by ddcat1115** [comment]
@ericjam3  Thanks and welcome~

**Comment by ericjam3** [comment]
I am working on this issue as a part of a class project in which I my task is to contribute to an open source project. I found Ant Design to be a really cool project and am excited to dig in. I have read all the contributing docs and other relevant information and I am ready to start fixing this issue. Are there any good starting tips someone could offer to help me to pinpoint this issue? Thanks!

**Comment by yesmeck** [comment]
It seems it's by design https://github.com/ant-design/ant-design/blob/f9b8bf7e4d6902619a96eb6b0ec72e829a669a17/components/card/index.tsx#L75-L86

@afc163 Could you confirm it?

**Comment by zheeeng** [comment]
@yesmeck Try click Card repeatedly, different container offsetWidths leads different visual effects. In my use cases, a lot of loading cards' shifting brings vision burden to us. Plz check the design's reasonability, thank you.

**Comment by ericjam3** [comment]
I am no longer working on this issue.
