### ISSUE TITLE
SubMenu cant be wrapped into <MediaQuery />

### ISSUE THREAD

**Issue by dazbo** [ant-design/ant-design#9864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
Found that:
- #4853 references SubMenu as not supporting HOC, but it is only about keyboard features.
- #4933 references SubMenu as not supporting HOC, but links to the above issue too.

### Version
3.3.3

### Environment
Windows 7, Chrome 64, Internet Explorer 11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7k5v37nkp1)

### Steps to reproduce
Import `<MediaQuery />` from [react-responsive](https://github.com/contra/react-responsive).

Wrap a `Menu.SubMenu` into a that component as direct child (line 30 in codesandbox sample).

Wrap another `Menu.SubMenu`into another instance of that component, but render it as children function  (line 37 in codesandbox sample).

Resize the preview window:
- above 640px: only "Navigation One" should be display
- between 640 and 480px: "Navigation Two" should be display too
- under 480px: "Navigation Two" should be hidden, and "Small Navigation Two" should be display

### What is expected?
`Menu.SubMenu`s should be rendering if it matches the media query.

### What is actually happening?
The rendering is crashing when the media query matches and children is passed as a function.

---
Not sure if it is a bug about Ant or about `<MediaQuery />` component, but I already meet a similar bug with `Menu.SubMenu`'s wrapped into High Order Component (but that HOC was my 1st one - wasn't confident about it).

Maybe, it is only a lack of documentation or so, about how to wrap that `Menu.SubMenu` component, or about that wrapping that component is not supported.

Anyway, thanks for this UI framework, appreciate all that work!

**Comment by yesmeck** [comment]
It's known issue as described in #4853.

You can move MediaQuery to out of Menu:

```javascript
<MediaQuery minWidth={480}>
  {(matchMinWidth) => (
    <MediaQuery maxWidth={480}>
      {(matchMaxWidth) => (
        <Menu>
          {matchMinWidth && <SubMenu key="foo" />}
          {matchMaxWidth && <SubMenu key="bar" />}
        </Menu>
      )}
    </MediaQuery>
  )}
<MeidaQuery/>
```
