### ISSUE TITLE
the Order (ASC) button Of Table Component is not easy to click

### ISSUE THREAD

**Issue by wupinlang** [ant-design/ant-design#9865]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
mac系统，chrome版本 65.0.3325.181（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
the Order (ASC) button Of Table Component is not easy to click. Table组件的升序按钮错位了，把手指对准升序肩头的时候很难点到。

### What is expected?
鼠标对准up点击的时候，可以相应

### What is actually happening?
鼠标对准up点击的时候，无相应

**Comment by yesmeck** [comment]
已经做了一些调整。
