### ISSUE TITLE
Menu functionality failing when used with Redux

### ISSUE THREAD

**Issue by coljung** [ant-design/ant-design#9867]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
Latest version OS   Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jvzkzl61x9)

### Steps to reproduce
Trigger the sider, see that the submenus do not show up o expanded view.

### What is expected?
Submenus should show when the Sider is opened.

### What is actually happening?
For some reason, the UL generated by the menu is keeping the .ant-menu-inline-collapsed class even when the sider is opened. This shouldn't happen.

---
If you check on my code, line 43 of <app>, enabling this line and disabling line 41, its basically the same component but WITHOUT the use of react-redux 'connect'.

In that case, the submenus work fine.

I'm scratching my head as to WHY the menu doesnt behave as expected when its wrapped with react-redux. Any ideas ?

**Comment by yesmeck** [comment]
Because Menu is not a pure component, you should tell react-redux it's not pure:

```javascript
export default connect(mapStateToProps, mapDispatchToProps, null, { pure: false })(CustomNavigation);
```

It's a bit confusing since we use context in Menu and the old context api has some [issue](https://github.com/facebook/react/issues/2517) on the update.

**Comment by coljung** [comment]
Wow, thanks a lot.
