### ISSUE TITLE
[Component: Tree] property `checkedKeys` not works if set before tree render.

### ISSUE THREAD

**Issue by narrowizard** [ant-design/ant-design#9869]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome 65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rwxo05016o)

### Steps to reproduce
  expected: click `set data` button before `set check info` button, it works fine.
  unexpected: click `set check info` button before `set data`button, it doesn't check any node.

### What is expected?
the node with key specified in `checkedKeys` property should be checked.

### What is actually happening?
it doesn't check any node.

**Comment by narrowizard** [comment]
this one appears again in the latest version of antd (3.16.3 now).  
could you please reopen this issue? @zombieJ

**Comment by narrowizard** [comment]
does it mean that I need to wait the next release for antd?

**Comment by zombieJ** [comment]
> does it mean that I need to wait the next release for antd?

Hi @narrowizard , this fix is up dependency patch. You can remove node_modules and reinstall : )

**Comment by narrowizard** [comment]
> > does it mean that I need to wait the next release for antd?
> 
> Hi @narrowizard , this fix is up dependency patch. You can remove node_modules and reinstall : )

I don't think it will work, since antd@3.13.6 specify `rc-tree` version at "~1.14.6".

**Comment by zombieJ** [comment]
@narrowizard , nice catch. Let me update 1.14.x also.

**Comment by zombieJ** [comment]
rc-tree@1.14.10 released

**Comment by narrowizard** [comment]
now it works. 😄
