### ISSUE TITLE
Migrate to new context API

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#9870]
The old context API has [several downsides](https://github.com/facebook/react/issues/1373) and causes issues like #9867. We should migrate to the new context API, and we can use https://github.com/jamiebuilds/create-react-context for compatibility.

**Comment by afc163** [comment]
We should migrate to `state contextType` now: https://reactjs.org/docs/context.html#classcontexttype

**Comment by ntucker** [comment]
This is needed to make StrictMode work in 4 https://github.com/ant-design/ant-design/issues/16911

**Comment by liubhub** [comment]
Hello everyone and thank you for this amazing library.

I have checked the related issues and decided to let you know in this thread the issue that I am currently having with `Item`: 
```
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Item
```

Libs versions:
```
"antd": "^4.2.2",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-redux": "^7.2.0",
"react-scripts": "3.4.1",
"redux": "^4.0.5"
```

**Comment by afc163** [comment]
- [ ] Menu https://github.com/ant-design/ant-design/blob/2afab58ac8dbc5bc130d147f5b61ea5b169ff86c/components/menu/SubMenu.tsx#L29
- [ ] List https://github.com/ant-design/ant-design/blob/e1299bfcc97a97078c51f33ae939d815e4eacf7f/components/list/Item.tsx#L139

**Comment by afc163** [comment]
Close in favor of #24577
