### ISSUE TITLE
如何在ice中使用ant

### ISSUE THREAD

**Issue by iloveyo123u1** [ant-design/ant-design#9871]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
快速、方便

### What does the proposed API look like?
希望可以用ice拖动 来快速实现  https://github.com/alibaba/ice/

**Comment by afc163** [comment]
建议提到 ice 的 issue 中去。
