### ISSUE TITLE
RangePicker组件公共方法使用报错

### ISSUE THREAD

**Issue by liuzhen88** [ant-design/ant-design#9872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.11.0

### Environment
windows, chrome 63.0.3239.132

### Reproduction link
[https://cannot.support.code](https://cannot.support.code)

### Steps to reproduce
<RangePicker ref={component => this._rangePicker = component}/>  然后使用this._rangePicker.blur();报错this._rangePicker.blur is not a function

### What is expected?
期望可以使用，让rangepicker组件能够失去焦点

### What is actually happening?
this._rangePicker.blur is not a function

**Comment by yutingzhao1991** [comment]
It's works https://codesandbox.io/s/pqnk4mpmj

**Comment by yesmeck** [comment]
`blur` 是在 3.0 引入的。
