### ISSUE TITLE
proposed to modify the form.d.ts

### ISSUE THREAD

**Issue by nodece** [ant-design/ant-design#9874]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it will work in typescript

### What does the proposed API look like?
use ```@Form.create()``` will occur error in typescript
```
export interface ComponentDecorator {
    <P extends FormComponentProps>(component: React.ComponentClass<P> | React.SFC<P>): React.ComponentClass<Omit<P, keyof FormComponentProps>>;
}
```
modify to
```
export interface ComponentDecorator {
    <P extends FormComponentProps>(component: React.ComponentClass<P> | React.SFC<P>): any;
}
```
It is work

**Comment by nodece** [comment]
@ant-design-bot Can not reproduction ，Because it in node_modules\antd\lib\form\Form.d.ts

**Comment by yesmeck** [comment]
@nodece Could you create a reproduction repo?

**Comment by nodece** [comment]
@yesmeck 
Repo link [https://github.com/nodece/antd-ts-form-test](https://github.com/nodece/antd-ts-form-test)
See TODO, this is error, it only appeared when coding, but build production is ok.
# Fix  it
## This is my suggestion motify form.d.ts
```
export interface FormComponentProps {
    form: WrappedFormUtils;
}
export interface ComponentDecorator {
    <P extends FormComponentProps>(component: React.ComponentClass<P> | React.SFC<P>): React.ComponentClass<Omit<P, keyof FormComponentProps>>;
}
```
to
```
export interface FormComponentProps {
    form?: WrappedFormUtils;
}
```
Login componet use ```@Form.create()``` , But use ```<Login/> ```  props form is require
```
export interface ComponentDecorator {
    <P extends FormComponentProps>(component: React.ComponentClass<P> | React.SFC<P>): React.ComponentClass<Omit<P, keyof FormComponentProps>>;
}
```
