### ISSUE TITLE
父组件里能不能调用子组件的函数

### ISSUE THREAD

**Issue by diaoaa** [ant-design/ant-design#988]
父组件里能不能调用子组件的函数
````javascript
<div>
<Sub />
<Button onClick='submit'/>
</div>
````
目标：点击Button事件，提交整个表单数据（数据的一部分或者全部在Sub组件中），Sub组件的数据比较多，如果都回调父组件方法，放在父组件中太麻烦了；Button也不能放在子组建中。求父组件如何调用子组件方法或者Button的click事件能够传递到子组件中去？

**Comment by benjycui** [comment]
可以用 `[ref](https://facebook.github.io/react/docs/more-about-refs.html)`，但是不建议。

不清楚你的场景，不过应该可以把 `Sub` 下面的的 `onChange` 整合起来，然后 `Sub` 暴露一个 `onChange`，参数为一个包含所有子组件的值的 Object，如：

```
{
  name: '',
  age: '',
  ...
}
```

**Comment by diaoaa** [comment]
父组件按钮点击事件里设置state，然后这个state作为props传给子组件，子组件在shouldComponentUpdate方法中监听，为true则子组件自己提交表单
