### ISSUE TITLE
table组件 列上面有render方法，很简单的一个判断，10条数据，每编辑一行，10条全渲染

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#9881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table组件 列上面有render方法，很简单的一个判断，10条数据，每编辑一行，10条全渲染，建议搞成编辑行渲染，这样效率更高。2884我看过了，没有特别好的方案，希望你们能改进一下。

### What does the proposed API look like?
不要整表渲染，行渲染效率更高。

**Comment by yesmeck** [comment]
Duplicate of #9878.

按我在 #9878 说的，你可以自己尝试实现 shouldComponentUpdate

```javascript
class OptimizedRow extends React.Component {
  shouldComponentUpdate(nextProps) {
    // Perform a custom check
  }

  render() {
    return (
      <tr {...this.props } />
    )
  }
}

<Table components={{ body: { row: OptimizedRow } }} />
```
