### ISSUE TITLE
Card component actions bugs

### ISSUE THREAD

**Issue by haikyuu** [ant-design/ant-design#9882]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
All

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vvvpj6y603)

### Steps to reproduce
Create a card with actions. 
- Clicking on the bottom corner (trigger  the corner as much as possible) of an action hovers but does not trigger a click
- Clicking/ hovering far from the icon does not do anything

### What is expected?
-  Clicking anywhere in the button should a click
-  Hovering anywhere in the button should detect a hover

### What is actually happening?
- Clicking on the bottom corner of an action hovers but does not trigger a click
- Clicking/ hovering far from the icon does not do anything

---
I managed to hack things to make the actions work, but that came at the cost of ruining the UI a bit --> the border between buttons becomes full height.
You can uncomment the css file and see it. This is helpful when debugging.

Other than solving this bug, we might add a `footer` prop for maximum customizability but that's not in the scope of this bug report

**Comment by ddcat1115** [comment]
Actually it's not a button, and the designed active area is larger than icon but smaller than the action item. But the active region of hover and click should be the same. I'll adjust it~

**Comment by JeromeRiiot** [comment]
Hello,

I have exactly the same behaviour as described by haikyuu in v. 3.13.2
I can see that the Card component has changed a lot since dengfuping's fix. 
Any regression?

Jérôme.
