### ISSUE TITLE
Allow select dropdown menu element to be customized

### ISSUE THREAD

**Issue by evantrimboli** [ant-design/ant-design#9888]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the user searches for options in the select from a remote source, a large number of results can be returned. In some cases, it would be useful to use pagination to only show a portion of these results.

By allowing the dropdown to be customized, a developer could attach a pagination component (or other components) to allow users to navigate a larger data set.

### What does the proposed API look like?
I'm not sure what the best way to achieve this would be, since the Dropdown class itself provides specifically functionality, so wrapping it could be difficult.

Possibly, the dropdown could provide a way to "dock" an element to the top or bottom of the drop down list, maybe something like:

```
<Select
   dropdownDockBottom={<Pagination .... />}
/>
```

**Comment by ddcat1115** [comment]
Isn't a [searchable Select](https://ant.design/components/select/#components-select-demo-search) the better solution in this scenes?

**Comment by evantrimboli** [comment]
I am using the search functionality, I want to be able to control how results are displayed. Considering that example, imagine it's loading data remotely and when you search for "Jac" the server returns hundreds of results. All of the examples use very limited datasets so it doesn't really highlight the limitation.

https://ant.design/components/select/#components-select-demo-select-users is the closest to what I want, but I have no way of controlling the list.

**Comment by afc163** [comment]
Duplicate of #10831

**Comment by renjiie** [comment]
How can I customise the dropdown list with select all option in antd to select all the lists.
