### ISSUE TITLE
一个form中一个有Table rowSelection 复选框 ，但是是必选校验怎么写？

### ISSUE THREAD

**Issue by hehaibo** [ant-design/ant-design#9889]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一个form中一个有Table rowSelection 复选框 ，这个rowSelection 能不能作为表单的一部分呢？

### What does the proposed API look like?
有Table rowSelection 复选框 作为form的一部分的，直接提供配置就好了

**Comment by yesmeck** [comment]
请参考 https://ant.design/components/form-cn/?locale=en-US#components-form-demo-customized-form-controls
