### ISSUE TITLE
Menu的onClick事件文档过时

### ISSUE THREAD

**Issue by zsxsoft** [ant-design/ant-design#989]
http://ant.design/components/menu/
![image](https://cloud.githubusercontent.com/assets/2398785/12772873/d657d624-ca70-11e5-84ea-c295443b8d0f.png)
![image](https://cloud.githubusercontent.com/assets/2398785/12772882/eb08a2d8-ca70-11e5-9db6-313b361caade.png)
![image](https://cloud.githubusercontent.com/assets/2398785/12772883/f410bd20-ca70-11e5-8801-622f31f8da91.png)

key在item下，看起来不再独立作为参数了。

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/12772897/27a4f836-ca71-11e5-81c5-a4db088280ad.png)

 版本信息

**Comment by afc163** [comment]
没错的 `{item, key}` 表达的就是图中的结构。

**Comment by zsxsoft** [comment]
咦文档里的意思不是arguments吗

**Comment by afc163** [comment]
`const {item, key} = info`

**Comment by zsxsoft** [comment]
soga __(:з」∠)_
