### ISSUE TITLE
Pagination 联动问题--showQuickJumper=true,onChange发生改变，页码输入框不会改变(迷你版本可复现）

### ISSUE THREAD

**Issue by Simple2012hcz** [ant-design/ant-design#9898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
web 浏览器 chrome 

### Reproduction link
[http://1x.ant.design/components/pagination/  ](http://1x.ant.design/components/pagination/  )

### Steps to reproduce
点击重现链接的迷你版本即可

### What is expected?
可以联动修改输入框中的页码

### What is actually happening?
没有联动，输入框改动，会修改页码

**Comment by ddcat1115** [comment]
I think it's reasonable. The page No. of the jumper is a shortcut to change the current page, so if the jumper change, the current page No. should change too, but it is not correct contrarily. 

You can see in the latest version, the jumper No. is cleared after change, it's a better way.
