### ISSUE TITLE
v3.4  Tree树形组件 TreeNode 设置disabled  ，defaultCheckedKeys不起作用

### ISSUE THREAD

**Issue by xiangfengsu** [ant-design/ant-design#9899]
Version
3.3.3

Environment
macOS 10.13.1 chrome 版本 65.0.3325.181（正式版本） （64 位）

Reproduction link
https://codesandbox.io/s/p5w50984w7

Steps to reproduce
v3.4.0,如果设置为TreeNode 为disabled ，defaultCheckedKeys设置对应的key 不起作用,v3.3.3 是ok的

What is expected?
可以默认选中

What is actually happening?
不能默认选中

![Uploading image.png…]()

**Comment by zombieJ** [comment]
adjust logic to fix this: https://github.com/react-component/tree/commit/0d7fbe5bd84be99efa4ff9a95cf05a202ad98460

**Comment by afc163** [comment]
rc-tree need a patch version.

**Comment by zombieJ** [comment]
Tree update to 1.8.2
