### ISSUE TITLE
关于表格 固定列   子表格 产生的缺陷

### ISSUE THREAD

**Issue by bluexiaowei** [ant-design/ant-design#9900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
pc 浏览器

### Reproduction link
[https://codepen.io/anon/pen/oqdKdr?&editors=001](https://codepen.io/anon/pen/oqdKdr?&editors=001)

### Steps to reproduce
```jsx
<Table
      style={{width: 1000}}
      className="components-table-demo-nested"
      columns={[
    { title: 'Name', dataIndex: 'name', key: 'name' },
    { title: 'Platform', dataIndex: 'platform', key: 'platform' },
    { title: 'Version', dataIndex: 'version', key: 'version' },
    { title: 'Upgraded', dataIndex: 'upgradeNum', key: 'upgradeNum' },
    { title: 'Creator', dataIndex: 'creator', key: 'creator' },
    { title: 'Date', dataIndex: 'createdAt', key: 'createdAt' },
    { title: 'Action', key: 'operation', render: () => <a href="#">Publish</a>, fixed: 'right', width: 100 },
  ]}
      expandedRowRender={这里嵌套表格}
      scroll={{ x: 1200 }}
      dataSource={data}
    />
```
### What is expected?
固定列与表格对齐

### What is actually happening?
高度不对齐

---
单点击展开按钮就会发现不对齐。

**Comment by yesmeck** [comment]
已知问题，展开行不能跟固定列一起用。

**Comment by NsNe** [comment]
I have also encountered this problem now. What should I do?

**Comment by yesmeck** [comment]
@NsNe Expanded row is not supposed to use with fixed columns

**Comment by hxyong** [comment]
这是BUG还是就是不能这么用

**Comment by yesmeck** [comment]
不能这么用。

**Comment by suiyi8760** [comment]
fixed跟展开行不能共用感觉不太好吧，这需求挺常见的，重构一些老项目时卡在这个问题了

**Comment by 410675629** [comment]
不能共用是因为 expandableRowRenderer  会生成一个<tr> <td class="" colspan="n"></td></tr>，占用一行，如果能够返回 <tr> <td class="">1</td> ... <td>n</td></tr>就可以与母列表对齐了。所以建议支持生成第二种 tr , expandedRowRender 增加第5个参数 tdCount,不知可否

**Comment by afc163** [comment]
Maybe we should warn people in a obvious way when people add fixed column and expandableRowRenderer bothly.

@zombieJ @yesmeck

**Comment by Selfron** [comment]
> fixed column and expandableRowRenderer

Why is the fix for this issue a warning about using scroll instead of fixed columns in combination with expandableRowRenderer?

This does not even solve the reported problem and result in the expected behavior.
Even if you completely remove scroll from the example in the reproduction link the fixed column is still misaligned when opening a row.

**Comment by yurizhang** [comment]
不能這麼用去修復啊~~

**Comment by zhangfangbiao** [comment]
同样遇到了这个问题，希望赶紧修复
![image](https://user-images.githubusercontent.com/49065946/70707830-0e9dde80-1d14-11ea-8339-1d669054ad1e.png)

**Comment by zhangfangbiao** [comment]
同样遇到了这个问题，希望赶紧修复
![image](https://user-images.githubusercontent.com/49065946/70707881-34c37e80-1d14-11ea-86cb-62f15e283f2c.png)

**Comment by zombieJ** [comment]
antd v4 support both fixed column & expandedRows.
