### ISSUE TITLE
Tree 组件，使用redux异步获取数据

### ISSUE THREAD

**Issue by hehuasa** [ant-design/ant-design#9904]
```javascript
//（树的数据为this.props.treeData，异步请求到的子节点数据为` this.props.appendData ）
 onLoadData = (treeNode) => {
       const { dispatch } = this.props;
          return new Promise((resolve) => {
               if (treeNode.props.children) {
                   resolve();
                    return;
         }
    dispatch({ // 根据被展开的节点ID，请求该节点下    面的异步数据`
          type: 'resourceTree/append',
          payload: { TreeID: treeNode.props.TreeID     },
           }).then(() => {
   // 根据官网示例，为    treeNode.props.dataRef.children 赋值；此时this.props.treeData 已经被改变了，但是视图不刷新
       treeNode.props.dataRef.children = this.props.appendData;
       dispatch({ // 重新调用dispatch方法，期望能够调用到render（）方法刷新视图，实际还是无效。  
      type: 'resourceTree/reload',
       payload: this.props.treeData,
       }).then(() => {
             resolve();
         });
      });
    });
   };


What is expected?

官网关于Tree组件进行异步请求时，是使用setState()方法实现组件的更新。当使用dva来控制数据时，发生的视图更新滞后的问题。代码如上（树的数据为this.props.treeData，异步请求到的子节点数据为 this.props.appendData ）： 重新调用dispatch方法，期望能够调用到render()方法刷新视图，实际还是无效。

What is actually happening?

现在的疑问是：
为treeNode.props.dataRef.children赋值后，视图不会更新。
官网的例子是把树的数据存在state中，setState（）方法即可更新视图；
但是我通过redux来更新props就无法刷新视图了，因为 给treeNode.props.dataRef.children 赋值时 prop已经更新，再调用diapatch方法，由于数据没有改变，所以视图是不刷新的。
请问各位用redux处理树的异步时，是怎么操作的呢？

**Comment by afc163** [comment]
@ant-design-bot markdown

**Comment by elowes** [comment]
https://ant.design/components/tree-cn/#%E6%B3%A8%E6%84%8F 是因为这个？？

**Comment by hehuasa** [comment]
@elowes 不是，已经测试过了

**Comment by hehuasa** [comment]
解决了。解决办法是更新到最新的版本（3.4.0）。我晕。。。

**Comment by wsyinhuaxing** [comment]
我的时3.15但依然不刷新，现在只能通过设置setState强制render才行
 const {dispatch} = this.props;
    return new Promise((resolve) => {
      if (treeNode.props.children) {
        resolve();
        return;
      }
      dispatch({ // 根据被展开的节点ID，请求该节点下    面的异步数据`
        type: 'shiroUser/getSubOrgTree',
        treeNode: treeNode
      })
      resolve
      this.setState({orgTreeData:this.props.orgTreeData})
    });
－－－－－－－－－action－－－－－－－－－－－
* getSubOrgTree({treeNode}, {call, put}) {
      //const response = yield call(fetchPage, payload);
      //const {list = [], total = 0} = response.data;
      yield put({
        type: 'updateOrgTree',
        payload:
          {
            treeNode: treeNode,
            children: [{
              title: ' 说老地方撒娇 Child1',
              value: '0-0-1',
              key: '0-0-1',
            }, {
              title: ' Node1 Child2',
              value: '0-0-2',
              key: '0-0-2',
            }]
          }
      });
    },
---------------------reducer---------------------
payload.treeNode.props.dataRef.children=payload.children;
      const {orgTreeData}=state
      return {
        ...state,
        orgTreeData: orgTreeData
      };

**Comment by afc163** [comment]
```jsx
this.setState({
  orgTreeData: [...this.props.orgTreeData],
})

return {
  ...state,
  orgTreeData: [...orgTreeData],
};
```
