### ISSUE TITLE
TreeSelect 选择框不能在文本框高度变化时自动调整位置

### ISSUE THREAD

**Issue by wencaizhang** [ant-design/ant-design#9905]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
win7 chrome 65.0.3325.181

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
1. 在文档 TreeSelect 页面： https://ant.design/components/tree-select-cn/ 
2. 代码演示部分，多选 - 多选的树选择。
3. 从上到下依次选中所有选项
![treeselect](https://user-images.githubusercontent.com/34718241/38192110-0270accc-369e-11e8-898e-c0c000e8a7b7.gif)

### What is expected?
依次选择，当选中的选项在文本框中换行，导致文本框高度变化时，选择框位置自动调整，即选择框顶部紧贴文本框底部。

### What is actually happening?
文本框高度发生变化，选择框位置没有自动调整，影响文本框中选项的展示

**Comment by zombieJ** [comment]
`rc-tree-select` up to `1.12.10`
