### ISSUE TITLE
TimePicker 设置了 minuteStep 之后为什么还可以显示 minuteStep 外的数据

### ISSUE THREAD

**Issue by jasonxia23** [ant-design/ant-design#9906]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
浏览器

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
选择步长选项；设置当前时间，默认会把系统的时间带上去，即使当前系统时间分钟数不是 15 的倍数，这和设置的 minuteStep 冲突啊。

### What is expected?
不应该显示非步长的分钟数

### What is actually happening?
即使当前系统时间分钟数不是 15 的倍数，也会把系统的时间带上去

**Comment by ddcat1115** [comment]
如果确实需要限制，自己传 defaultValue 的时候处理一下就可以吧，组件也不好自行处理

**Comment by jasonxia23** [comment]
这个不是 defaultValue 的问题，这样不合理，没有 defaultValue 的话这个问题还是存在的

**Comment by ddcat1115** [comment]
defaultValue，value 都是一样的，外部传一个非步长的时间进去，组件是应该矫正为更早的时间还是更晚的呢？这个不好定的，所以还是自己传值时处理比较靠谱

**Comment by jasonxia23** [comment]
回晚了。
我觉得无论是更早的值还是更晚的值起码都不应该出现不合法的值。像我在使用的时候其实更关注的是值是否合法。
