### ISSUE TITLE
Input control can't be internationalized via react-intl

### ISSUE THREAD

**Issue by foxmuldercp** [ant-design/ant-design#9909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
win, chrome, react 16.3.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o7r8rv9ro9)

### Steps to reproduce
import {FormattedMessage} from 'react-intl'
import {Input } from 'antd'
...
<IntlProvider locale="en">
..
    <Input placeholder={\<FormattedMessage id='any.key.here' />\} />
.. 
 </IntlProvider>

### What is expected?
i18n value taken from FormattedMessage key or plain key name if it not exists

### What is actually happening?
produced [object Object] as input placeholder

**Comment by yesmeck** [comment]
You should use `injectIntl`, then:

```javascript
<Input placeholder={intl. formatMessage('any.key.here')} />
```
