### ISSUE TITLE
DatePicker和Affix共用时候的问题

### ISSUE THREAD

**Issue by ajsdhf** [ant-design/ant-design#991]
DatePicker放在Affix中，当DatePicker处于open状态时，滚动页面，open的选择框不会随着滚动条滚动

**Comment by afc163** [comment]
。。。目前确实是不支持的。

**Comment by afc163** [comment]
rc-trigger 里有一个属性 `getPopupContainer`，可以用来定义浮层的容器，默认是放到 body 的。https://github.com/react-component/trigger/blob/74577009bfb97e52b658aa4e827722ef8a0cd367/examples/simple.js#L50

在 rc-calendar 里继承为 `getCalendarContainer`，目前 DatePicker 里没有传递进去。我来改下。

改完后将可以这样定义浮层的容器。

```jsx
function getCalendarContainer(trigger) {
  return trigger.parentNode;
}

ReactDOM.render(<DatePicker getCalendarContainer={getCalendarContainer} />, mountNode);
```

这样就会随着触发元素一起移动了。

**Comment by afc163** [comment]
其他触发元素可以用 `getPopupContainer`。

**Comment by afc163** [comment]
今天我会发一个 `0.12.1`。
