### ISSUE TITLE
Table sorter only works in one direction

### ISSUE THREAD

**Issue by jakelauer** [ant-design/ant-design#9911]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome, Win 10, React 16.3.1

### Reproduction link
[https://codepen.io/anon/pen/rdKzZr?&editors=001](https://codepen.io/anon/pen/rdKzZr?&editors=001)

### Steps to reproduce
Filter a table ascending by numerical value

### What is expected?
Items are sorted in ascending order

### What is actually happening?
Items are sorted out of order, with pairs of rows being sorted correctly but the whole dataset being sorted incorrectly.

---
I have changed the ages so they are all different. Descending works correctly and produces [41, 36, 32, 31, 22, 6], but ascending produces [32, 41, 22, 36, 6, 31]. It looks to me like the data is being sorted in pairs (32, 41) / (22, 36) / (6, 31). Each of those pairs is sorted ascending, but the list of pairs is out of order.

**Comment by yesmeck** [comment]
> It looks to me like the data is being sorted in pairs (32, 41) / (22, 36) / (6, 31).

Did you click the ascending icon twice?

**Comment by jakelauer** [comment]
@yesmeck I just clicked the column header multiple times to observe the differences in the two sorting results. One is correct, one is not.

**Comment by afc163** [comment]
It is by designed, I think current behavior it is correct.

**Comment by jakelauer** [comment]
@afc163 The behavior is definitely not correct, the numbers are not in order, as I described

**Comment by jakelauer** [comment]
> Descending works correctly and produces [41, 36, 32, 31, 22, 6], but ascending produces [32, 41, 22, 36, 6, 31].

**Comment by afc163** [comment]
1. click down arrow => sorted by descending

<img width="239" alt="image" src="https://user-images.githubusercontent.com/507615/38290124-51b032ac-380c-11e8-9d72-b5b79703cd31.png">

2. click down arrow again => means to toggle it => back to initial order in dataSource

<img width="217" alt="image" src="https://user-images.githubusercontent.com/507615/38290148-6ff2680c-380c-11e8-9717-51200296dc73.png">

**Comment by afc163** [comment]
If you need to sort data in ascend, just click up arrow.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/507615/38290168-89cc1ef8-380c-11e8-9e23-53da4481a0ce.png">

**Comment by jakelauer** [comment]
@afc163 I see now, I did not realize you could click on different portions to sort in different directions. 

I assumed clicking on the header would just swap between ascending and descending - I expect many users would thing the same thing, because the up and down arrows do not look like buttons (there is no button-like border). Perhaps the styles could be improved to make that more obvious.

**Comment by afc163** [comment]
I think we can change our sorter behavior to be togglable.

**Comment by sirrodgepodge** [comment]
welllll in the meantime, here's a pure CSS way to make the current table sort be a toggle instead of micro-buttons, idea kernel credit goes to @nkalinov

```
// hacking sorter component
.ant-table-thead > tr > th { // we want the click target to be the whole "th" (column header) element
	position: relative;
}
.ant-table-column-sorter {
	position: static;
	.ant-table-column-sorter-up,
	.ant-table-column-sorter-down {
		position: static;
		&::after {
			top: 0;
			left: 0;
			height: 100%;
			width: 100%;
		}
		&.on::after {
			pointer-events: none;
		}
	}

	// initial toggle on "up" arrow
	.ant-table-column-sorter-up.off + .ant-table-column-sorter-down.off::after {
		pointer-events: none
	}
}
```

**Comment by m26597** [comment]
@jakelauer @sirrodgepodge @yesmeck but I haven't realized the sort function by clicking arrow. I've tried antd 3.9.2 and antd 3.9.3. But it seems doesn't work. How could I realize this function? Need I change the sort code beside : sorter: (a, b) => a.name.length - b.name.length?

**Comment by sirrodgepodge** [comment]
Oh I think you can feed in custom sorters, 80% sure, check docs/code

**Comment by zjscy666** [comment]
我也遇到同样问题了，翻了一遍源码，发现没问题，最后找issue，西湖的水我的泪啊，宝宝心里苦，但是宝宝不说话
