### ISSUE TITLE
 Why domestic document servers often crash?

### ISSUE THREAD

**Issue by EliShaXu** [ant-design/ant-design#9915]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
win10 chrome

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
open https://ant.design

### What is expected?
Can display a document

### What is actually happening?
chrome: ERR_CONNECTION_RESET

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7895#issuecomment-338577202
