### ISSUE TITLE
Boolean value will auto change to string in Table column filters.

### ISSUE THREAD

**Issue by neoscript99** [ant-design/ant-design#9916]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux    -----   google-chrome-stable/panda,now 63.0.3239.132-1 amd64

### Reproduction link
[https://github.com/neoscript99/antd-pro-graphql/blob/graphql/src/routes/SysConfig/DepartmentList.js](https://github.com/neoscript99/antd-pro-graphql/blob/graphql/src/routes/SysConfig/DepartmentList.js)

### Steps to reproduce
```javascript
columns:[
  {
    title: '是否启用',
    dataIndex: 'enabled',
    render: val => (val ? '是' : '否'),
    filters: [{
      text: '是',
      value: true,
    }, {
      text: '否',
      value: false,
    }],
    filterMultiple: false,
    onFilter: (value, record) => {
      console.log(typeof value) // the result is string
      // === is not work
      return record.enabled === value;
    },
]
```

### What is expected?
`onFilter: (value, record)`, value should be `boolean`.

### What is actually happening?
`onFilter: (value, record)`, value is `string`.

**Comment by yoyo837** [comment]
I am focusing this, but I see that all of menu items are using key by string type, what should I do?
