### ISSUE TITLE
Tree component: loadData event will be triggered twice

### ISSUE THREAD

**Issue by zhuaizhuaixi** [ant-design/ant-design#9920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
System version: windows 10 、Chrome version : 63.0.3239.84 、 antd : 3.4.0 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5ym6rw3yn4)

### Steps to reproduce
<Tree loadData={this.onLoadData}>  </Tree>

onLoadData = (treeNode) => {
    console.dir(111)
}

method onLoadData will be triggered twice so '111' will be printed twice

### What is expected?
'111' print once

### What is actually happening?
'111' print twice

---
3.3.3之前loadData事件只会触发一次，更新3.4.0后就会触发2次

**Comment by zombieJ** [comment]
感谢反馈，我看一下

**Comment by zhuaizhuaixi** [comment]
前两天更新的3.4.1还是没有修复这个问题呢

**Comment by zombieJ** [comment]
@zhuaizhuaixi , `rc-tree` 1.9.0 修复了该问题。下个版本 antd 会更新到新版的 rc-tree

**Comment by zhuaizhuaixi** [comment]
好的，谢谢

**Comment by zombieJ** [comment]
update: https://github.com/react-component/tree/tree/1.8.x
