### ISSUE TITLE
Menu.Item is not rendered inside Context Consumer

### ISSUE THREAD

**Issue by dachinat** [ant-design/ant-design#9921]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS 10.13.4, Chrome 65.0.3, React 16.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zq6vmv32l3)

### Steps to reproduce
1. Create context `AppContext` with `React.createContext`

2. Create App component and render 

```
<AppContext.Provider value={{text: "My menu item"}}>
   {props.children}
</AppContext.Provider>
```

3. Create Header component and render

```
<Layout>
      <Menu theme="dark" mode="horizontal">
        <AppContext.Consumer>
          {props => {
            return <Menu.Item>{props.text}</Menu.Item>;
          }}
        </AppContext.Consumer>
      </Menu>
</Layout>
```
      
    

### What is expected?
A Menu.Item has to be rendered inside Context

### What is actually happening?
A TypeError Cannot read property 'indexOf' of undefined is being dispatched

**Comment by yesmeck** [comment]
It's a known issue(#4853), you need to use `Context.Consumer` in MenuItem:

```javascript
<Layout>
  <Menu theme="dark" mode="horizontal">
    <Menu.Item>
      <AppContext.Consumer>
        {props => props.text}
      </AppContext.Consumer>
    </Menu.Item>
  </Menu>
</Layout>
```

**Comment by dachinat** [comment]
@yesmeck Thanks. So, there's no other solution for this currently right? Such structure doesn't really suite my needs. I might not be rendering `Menu.Item` at all if user is not authorized. Thanks.

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/9864#issuecomment-377215308

You can move `Context.Consumer` out of Menu.

**Comment by dachinat** [comment]
@yesmeck Thanks for your response and thanks for this project.
