### ISSUE TITLE
Cascader自定义 options 数据字段

### ISSUE THREAD

**Issue by zhayes** [ant-design/ant-design#9927]
官方的例子中 options = [{
value: 'zhejiang',
label: 'Zhejiang',
children: [{
value: 'hangzhou',
label: 'Hangzhou',
children: [{
value: 'xihu',
label: 'West Lake',
}],
}]；

现在的需求是 我的数据结构是一样的，但是对应的字段名有点不一样，如何指定展示的字段内容

**Comment by ShuBuShao** [comment]
@zhayes 解决了么

**Comment by afc163** [comment]
@ShuBuShao https://github.com/react-component/cascader/pull/23

**Comment by zhayes** [comment]
@ShuBuShao  我之前都是写了个单独的方法去遍历递归数据，以符合组件的数据格式要求。目前没有改过。
