### ISSUE TITLE
type error with react 16.3.1

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#9931]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
`@types/react 16.3.4` , antd 3.4.0

### Reproduction link
[https://github.com/whtsky/antd-react-16.3.1-type](https://github.com/whtsky/antd-react-16.3.1-type)

### Steps to reproduce
npx tsc

### What is expected?
compile

### What is actually happening?
node_modules/antd/lib/badge/ScrollNumber.d.ts(28,81): error TS2344: Type '{ className: string; style: { transition: string | boolean; msTransform: string; WebkitTransform:...' does not satisfy the constraint 'HTMLAttributes<HTMLElement>'.
  Types of property 'style' are incompatible.
    Type '{ transition: string | boolean; msTransform: string; WebkitTransform: string; transform: string; }' is not assignable to type 'CSSProperties'.
      Types of property 'transition' are incompatible.
        Type 'string | boolean' is not assignable to type 'string'.
          Type 'true' is not assignable to type 'string'.
node_modules/antd/lib/badge/ScrollNumber.d.ts(38,77): error TS2344: Type '{ className: string; style: { transition: string | boolean; msTransform: string; WebkitTransform:...' does not satisfy the constraint 'HTMLAttributes<HTMLElement>'.
  Types of property 'style' are incompatible.
    Type '{ transition: string | boolean; msTransform: string; WebkitTransform: string; transform: string; }' is not assignable to type 'CSSProperties'.
      Types of property 'transition' are incompatible.
        Type 'string | boolean' is not assignable to type 'string'.
          Type 'true' is not assignable to type 'string'.

**Comment by whtsky** [comment]
antd version is 3.4.0
![image](https://user-images.githubusercontent.com/876694/38289582-8992414a-3809-11e8-9935-81c1f1300da9.png)

**Comment by KevinWang15** [comment]
happens to me too.
```
antd: 3.4.0
react: 16.3.1
react-dom: 16.3.1
@types/react: 16.3.5
@types/react-dom: 16.0.4
typescript: 2.8.1
```

for the time being I edited ```node_modules/antd/lib/badge/ScrollNumber.d.ts```
replacing all ```string | boolean``` with ```string```

**Comment by yesmeck** [comment]
@whtsky I don't see codes in your repo.

**Comment by KagamiChan** [comment]
@yesmeck It is antd's type definition (specifically, `ScrollNumber.d.ts`) that is incompatible with latest `@types/react` definition, running `tsc` will reproduce the issue.

IMO boolean value `transition` in component's `style` props does not make sense, so the latest `@types/react` is correct, and `ScrollNumber.d.ts` needs a fix

**Comment by whtsky** [comment]
@yesmeck We don't need any code to reproduce this problem. Simply import `antd` will cause type error.

**Comment by narrowizard** [comment]
@yesmeck same error to me.

**Comment by lucasriondel** [comment]
same here. changing `transition: string | boolean;` to `transition: string;` in `ScrollNumber.d.ts` line 31&41 did it for me though, thanks @KagamiChan .

**Comment by kanweiwei** [comment]
happens to me too.

**Comment by alesdrobysh** [comment]
@yesmeck are you planning to issue a patch release?

**Comment by afc163** [comment]
https://ant.design/changelog#Release-Schedule

**Comment by afc163** [comment]
You can try `@types/react@~16.2.0` as workaround now.

**Comment by alesdrobysh** [comment]
@afc163 downgrading doesn't work if I have some `@types/react-*` dependencies; 

for example `@types/react-redux` internally installs the latest react typings and it causes compilation failure

**Comment by KevinWang15** [comment]
@alesdrobysh You can try to modify ```node_modules/antd/lib/badge/ScrollNumber.d.ts``` and then use https://github.com/ds300/patch-package for now (refer to my previous comment)

**Comment by zheeeng** [comment]
Happens to me.

**Comment by bora89** [comment]
yes, the problem does exist

**Comment by dfreire** [comment]
It happens to me too.

**Comment by lvlohammadi** [comment]
Is this an urgent issue? 
Currently i cant make any changes in `node_modules`, Because it's on the gitlab pipeline.

**Comment by bora89** [comment]
According to their schedule they ought to do a release at the end of each week, so we would rather wait a bit

**Comment by alesdrobysh** [comment]
as a temporary solution it works to add skipLibCheck flag to tsconfig

**Comment by Rain120** [comment]
我理解的更新之后的版本和新版的react可能不兼容，所以你可以将版本降下去，我的版本是@antd 3.2.0, @types/react 16.25.0
