### ISSUE TITLE
IE10、IE11 和 Edge下 table 固定列快速滚动时，不固定列和固定列会有一个错位现象

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#9937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
V3.4.0

### Environment
win10  IE10 、IE11和Edge 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/40zpknk5kw)

### Steps to reproduce
鼠标放置在表格内快速滚动滑轮

### What is expected?
固定列和不固定列 滚动速度一致

### What is actually happening?
固定列和不固定列 滚动有一个明显的时间差，看到明显错位现象

---
Chrome下无此问题。

**Comment by Nokecy** [comment]
#3096 与这个问题一样，在IE10 、IE11 、 Edge下有这个问题。

**Comment by Portalesoft** [comment]
There are serious issues with Ant Design and Internet Explorer to the point, currently I don't think we can use it, which is a shame. See below issues on the main site, using IE11 to browse the Table demos.

![ie11](https://user-images.githubusercontent.com/25370239/38353663-071b50e8-38af-11e8-9579-4949d0b0e716.png)

**Comment by Nokecy** [comment]
经过测试，发现是IE10 IE11 下启动了平滑滚动 导致了onscroll时间有延迟，最后结果就是 fixed table 和当前滚动的列滚动速度不一致。

**Comment by Nokecy** [comment]
@afc163

**Comment by SkyblueWZZQ** [comment]
Chrome also has this problem, when rendering we can see the fixed columns height is Inconsistent with other columns.
