### ISSUE TITLE
InputNumber triggers change event twice

### ISSUE THREAD

**Issue by byaman** [ant-design/ant-design#9939]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.4

### Environment
Windows 10, Chrome 65.0.3325.181, React, React-Dom : 16.2.0

### Reproduction link
[https://codepen.io/bertanyaman/pen/yKqZyP?editors=0010](https://codepen.io/bertanyaman/pen/yKqZyP?editors=0010)

### Steps to reproduce
1) Change value of the input
2) Blur input
3) Check the console you will see onChange function triggered twice

### What is expected?
Trigger onChange function once

### What is actually happening?
Triggers onChange function twice

---
It is calling once on Input component. But on InputNumber it is calling twice. Thanks in advance

**Comment by ddcat1115** [comment]
For InputNumber will comfirm the vadility of value when onBlur is triggered [code](https://github.com/react-component/input-number/blob/master/src/index.js#L205). Is this causing you trouble?

**Comment by afc163** [comment]
It is by designed.

**Comment by soeyi** [comment]
if the onBlur event is passed by itself, validate the value by onBlur is better ?
Or the onChange event will trigger twice, its kind of weird.
