### ISSUE TITLE
Style (border-width) on Input with suffix doesn't work

### ISSUE THREAD

**Issue by tb2johm** [ant-design/ant-design#9941]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.0

### Environment
doesn't matter

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z6w2q36lp)

### Steps to reproduce
Set the style property _borderWidth_ on a _Input_ and it will work nice, but if I add a _suffix-property_ (for example an <Icon>) the _borderWidth_ is not set on the correct dom-object

### What is expected?
borderWidth should be set on the correct object

### What is actually happening?
it's set on another object
Problem here is that the style is moved to be set on the wrapper div instead of the input it self. Not really sure how to fix this. Some styles (like the border) should probably stay on the Input, while other styles (like size) should go on the wrapper...
I'm no CSS expert, but would it hurt to have the styles on both objects?

**Comment by ddcat1115** [comment]
For Input with prefix/suffix and addonBefore/addonAfter, we put the style setting on the wrapper dom. I think you can try add `className` according to the state, and set styles for both `.className input` and `input.className`.

**Comment by BruceHong666** [comment]
@ddcat1115 
according to Input.tsx at line 176 . className will miss in this line.
根据第176行，className,原Input上的className也会丢失。不过外层会有这个className。原谅我抠脚的英语...
```javascript
    {React.cloneElement(children, { style: null, className: this.getInputClassName() })}
```
