### ISSUE TITLE
Dropdown 的展开项不只是菜单。

### ISSUE THREAD

**Issue by jamieYou** [ant-design/ant-design#9942]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Dropdown 的 多级菜单是左右布局的，我想在手机下实现 bootstrap 的效果(即上下布局)。但是 Dropdown 只接受 mode=vertical 的菜单。
我发现 飞冰 那里的 Dropdown 是可以接受任意组件的，不知道会不会考虑下还原呢。

### What does the proposed API look like?
https://alibaba.github.io/ice/#/component/dropdown

**Comment by afc163** [comment]
You can try https://github.com/react-component/trigger

**Comment by jamieYou** [comment]
@afc163 Tried but encountered new problems.
https://github.com/react-component/trigger/issues/84
