### ISSUE TITLE
Select as an input for Form

### ISSUE THREAD

**Issue by TylerGriffin99** [ant-design/ant-design#9946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
antd: 3.0.3, Mac Sierra 10.13.3, Chrome Version 65.0.3325.181

### Reproduction link
[https://github.com/HarvesterTechnologies/harvester-dev/blob/profile-page/src/containers/Profile/SoilSettings.js](https://github.com/HarvesterTechnologies/harvester-dev/blob/profile-page/src/containers/Profile/SoilSettings.js)

### Steps to reproduce
In order to run inside the link navigate to the 'harvester-dev' repo and clone the repo in the link (the link is where the error is occuring), install dependencies with 'yarn' then run 'yarn start'
open localhost:3000 in the browser, click on the person image icon in the top right, navigate to 'Profile' then to the 'Soil Settings' tab then click the 'edit' button and in the modal click the dropdown for irrigation method and select and item

### What is expected?
When a user user the select drop down inside a form element which is inside a modal popup I want the 'irrigationMethod' state to update with the users selection 'value'

### What is actually happening?
The app breaks with the "Cannot read property 'id' of undefined" error message

---
Currently using:
handleChange = (e) => {
    this.setState({
      [e.target.id]: e.target.value
    })
  }

If a new handle change method is created the error "Cannot read property 'value' occurs
handleSelectChange = (e) => {
    this.setState({
      irrigationMethod: e.target.value
    })
  }

<Form style={styleModalMargin}>
              <FormItem
                {...formItemLayout}
                label={
                  <IntlMessages id="forms.soilSettings.irrigationMethod" />
                }
              >
                  <Select value={this.state.irrigationMethod} onChange={this.handleChange} style={{ width: '100%' }}>
                      <Option selected value="Variable Rate">Variable Rate</Option>
                      <Option value="Block Level">Block Level</Option>
                      <Option value="Orchard As One Block">Orchard As One Block</Option>
                  </Select>
              </FormItem>
</Form>

**Comment by yesmeck** [comment]
Please refer to the documentation, the first parameter of onChange if `value`.
