### ISSUE TITLE
An extra scrollbar on the header when applying fixed left columns and header in Table

### ISSUE THREAD

**Issue by SimpleFrontend** [ant-design/ant-design#9952]
### Version
3.3.3

### Environment
macOS High Sierra 10.13.3, Chrome version 65.0.3325.181

### Reproduction link
[https://ant.design/components/table/#components-table-demo-fixed-columns-header](https://ant.design/components/table/#components-table-demo-fixed-columns-header)

### Steps to reproduce
The demo page is already showing this issue. When the header and the columns are both fixed, there will be an extra scrollbar beneath the header when you scroll.

### What is expected?
No scrollbar for the header

### What is actually happening?
An extra scrollbar appears when you scroll within the table.

---
This issue does not appear on Firefox with macOS. I tried to make `overflow: hidden` to fix the issue on Chrome with macOS, then it will break on Windows (also on Chrome).

**Comment by afc163** [comment]
#6800
