### ISSUE TITLE
InputNumber buttons not managing onBlur/focus correctly

### ISSUE THREAD

**Issue by gronstrand** [ant-design/ant-design#9953]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.2 to 3.4.0

### Environment
Windows 7/Mac OSX 10.12.3/Ubuntu 17.10   Chrome 65.0.3325.181   React 16.3.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7r4ylojl6)

### Steps to reproduce
* Try increasing/decreasing a number by clicking the buttons for an InputNumber.
The whole field is focused.
* Try clicking outside, in another field or on another component.

### What is expected?
The InputNumber field should no longer be focused/highlighted and an onBlur-event should fire. Alternatively the onBlur-event should fire immediately when releasing the button.

### What is actually happening?
Nothing. The only way to remove focus and trigger onBlur is to click inside the same field as the buttons, and then clicking outside.

Here's an example of how it used to work, using 3.3.1: [https://codesandbox.io/s/849ro0pwoj](https://codesandbox.io/s/849ro0pwoj)

---
This bug seems to have been introduced with version 3.3.2, since the behavior is not present in version 3.3.1.

**Comment by dingtwo** [comment]
开发环境下没有问题, prod环境又出现这个bug

**Comment by yoyo837** [comment]
此问题还是存在
