### ISSUE TITLE
Divider style problem

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#9956]
### Version
3.4

### Environment
Chrome:latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x3ylzy9y5w)

### Steps to reproduce
Narrow the display space until the text breaks and you will see problems with Divider's location

### What is expected?
Divider's position should be below the text

### What is actually happening?
Divider's position in the middle of the text

**Comment by afc163** [comment]
I fixed it by adding `clear: both`. And you should use Col and Divider like this through.

**Comment by muzea** [comment]
Although I can write like this
```jsx
  <Row>
    <Col span={24}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta? Refert tamen, quo modo.</Col>
    <Col span={24}><Divider /></Col>
  </Row>
```
but this col looks unnecessary

**Comment by afc163** [comment]
How about:

```jsx
  <Row>
    <Col span={24}>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta? Refert tamen, quo modo.
      <Divider />
    </Col>
  </Row>
```

**Comment by muzea** [comment]
> It's all the product's fault 😂

Our layout like this

```jsx
  <Row>
    <Col span={12}>
      <h2 style={{ fontSize: 14 }}>我是标题</h2>
    </Col>
    <Col span={12} style={{ textAlign: 'right' }}>
      <Switch />
    </Col>
    <Col  span={16}>
      我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字我是字
    </Col>
    <Col span={24}><Divider /></Col>
  </Row>
```
