### ISSUE TITLE
TimePicker component has extra bottom padding after the last element of lists

### ISSUE THREAD

**Issue by bzhangzju** [ant-design/ant-design#9957]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS 10.13.3, Chrome 65.0.3325.181

### Reproduction link
[https://codepen.io/bzhang/pen/MVzZWR](https://codepen.io/bzhang/pen/MVzZWR)

### Steps to reproduce
1. import TimePicker component from antd, and set its default value to '23:59:59'
2. As you can see, there is extra padding of 160px at the bottom of TimePicker. In Chrome on Desktop, scrollbar is not shown by when it is not active. It may appear to users that only 23:59:59 is listed in TimePicker and no other times can be selected.

### What is expected?
It should not have any padding at the bottom of TimePicker after the last element in the list.

### What is actually happening?
It has extra bottom padding of 160px at the bottom of TimePicker.

---
From TimePicker style, it has css rule: 
.ant-time-picker-panel-select ul {
      padding: 0 0 160px;
}

The bottom padding should be 0 instead of 160px.

**Comment by afc163** [comment]
#8953
