### ISSUE TITLE
After Click Button, If the focus is not lost, Enter keyboard events are bound by default.

### ISSUE THREAD

**Issue by Shurlormes** [ant-design/ant-design#9958]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome

### Reproduction link
[https://codepen.io/Shurlormes/pen/LdXqwa](https://codepen.io/Shurlormes/pen/LdXqwa)

### Steps to reproduce
1. Click Button
2. Press Enter Key

![](https://voidforce-public.oss-cn-shanghai.aliyuncs.com/images/Ant%20Design%20Button%20Key%20Down%20Demo.png)

### What is expected?
Button should not default to bind keyboard events.

### What is actually happening?
Button defaults to keyboard events.

---
Maybe can add an attribute，default is false
```javascript
<Button bindToEnter="true">Button</Button>
```

**Comment by afc163** [comment]
I think it is reasonable to focus button after click it and it is a browser default behavior.
