### ISSUE TITLE
TreeSelect css组织问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#996]
TreeSelect 由于prefixCls 要是自己的，所以现在是分别拷贝 Tree 和 Select 组件的样式，比如修改 Select 或 Tree 组件样式时、一般也要到 TreeSelect 组件里去修改一遍，这样比较麻烦，也容易出漏洞。

类似的“样式复用”、css modules 等问题再确认下？

**Comment by warmhug** [comment]
Select 没有默认值，disabled 时 单选模式下有背景灰色，多选模式下没有，这样表现不一致、看起来不对的。 TreeSelect 同样问题。 @afc163

**Comment by afc163** [comment]
Mixin 进来。

**Comment by afc163** [comment]
提 PR

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/12805594/bfc49f60-cb37-11e5-9ed4-213b3084756f.png)

颜色值要改掉的。不然多选有默认值就这样子。
