### ISSUE TITLE
表单验证报错后，界面布局混乱问题。

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design#9960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
Chrome 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xo0oozkmp)

### Steps to reproduce
1. 点开重现链接
2. 点击Search 按钮
3. 再Field2中 输入任意字符

### What is expected?
界面布局不动

### What is actually happening?
界面布局错乱

---
这个问题已经提交过，但是被关闭了。提供的解决方案也不是有效的解决方案。
之前问题链接：https://github.com/ant-design/ant-design/issues/9907#issuecomment-377971677

**Comment by ganxunzou** [comment]
![image](https://user-images.githubusercontent.com/5092728/38465423-05cd7a62-3b4e-11e8-9a6a-ce46ed965dfb.png)

@ddcat1115 上个问题被您关闭了，我重新提交。上次你提供的解决方案并不能解决问题。测试链接点：`Reproduction link`。

错误效果图如下（已经去除`formItemStyle`样式设置）：

![snip20180408_2](https://user-images.githubusercontent.com/5092728/38465447-581ef084-3b4e-11e8-8363-0438529df885.png)

**Comment by afc163** [comment]
I think you missed the PR code update in https://github.com/ant-design/ant-design/pull/9908/files

**Comment by ganxunzou** [comment]
@afc163  i use lastest version (3.4.0)。

![image](https://user-images.githubusercontent.com/5092728/38465531-80b81ace-3b4f-11e8-878d-a3f00fe2dd4a.png)

**Comment by ganxunzou** [comment]
大概知道了，应该还没有发布版本。

**Comment by ddcat1115** [comment]
3.4.1 has been released~
