### ISSUE TITLE
UpLoad can not run well in IE11

### ISSUE THREAD

**Issue by immary** [ant-design/ant-design#9965]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.2.0

### Environment
win7、IE11

### Reproduction link
[https://github.com/ant-design/ant-design/issues/2422](https://github.com/ant-design/ant-design/issues/2422)

### Steps to reproduce
点击上传，上传后文件一直显示Loading，而且还会下载一个文件

### What is expected?
正常上传

### What is actually happening?
上传变成了下载

**Comment by afc163** [comment]
Please see #2422
