### ISSUE TITLE
datePicker

### ISSUE THREAD

**Issue by dotequiet** [ant-design/ant-design#9970]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
pro

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
no

### What is expected?
whether there is an event clear selection in DatePicker

### What is actually happening?
i can't find this event

**Comment by yesmeck** [comment]
`onChange`

**Comment by dotequiet** [comment]
@yesmeck 
this DatePicker is in the search , there is a rest btn ，when the btn is clicked i need clearing the timer

**Comment by yesmeck** [comment]
`value`

**Comment by dotequiet** [comment]
the value begin is empty string or undfine,  but datePicker need moment otherwise have error in console

**Comment by dotequiet** [comment]
![image](https://user-images.githubusercontent.com/20040134/38477432-0ae305c0-3be5-11e8-8886-ef4a74c99452.png)
like this , reset can't clear timer

**Comment by yesmeck** [comment]
Set value to `null`.

**Comment by dotequiet** [comment]
ok , thank you
