### ISSUE TITLE
Align the TreeSelect search input with Select

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#9972]
### What problem does this feature solve?
`TreeSelect` search input has 2 place to display:
* single: in the popup panel
* multiple: on the input bar.

Check the history and find that `Select` display in popup panel in version 0.x: http://012x.ant.design/components/select/#demo-search

v1 and upper, `Select` has change the design but `TreeSelect` not follow the new design.

### What does the proposed API look like?
Follow the new `Select` design

**Comment by zombieJ** [comment]
@yesmeck @afc163

**Comment by afc163** [comment]
In fact, I am think reverse the showSearch look of Select cause it will confuse people sometimes.

**Comment by zombieJ** [comment]
Let's remove the sample doc of 'combobox' in `Select` preview page since already provide the `AutoComplete` preview page.

We need more discuss for the design to diff the `Select` & `Input`.

**Comment by dani-media** [comment]
Hey guys, I noticed a bug in IE11, when I try to use the showSearch of TreeSelect it's not letting me type more than one character and loses focus. You can try this behavior here https://ant.design/components/tree-select/ using IE11.

Should this be reported as bug, or is this known issue?

**Comment by afc163** [comment]
Just reverse Select showSearch to http://012x.ant.design/components/select/#demo-search

@zombieJ

**Comment by chillyistkult** [comment]
@afc163 Hello, it's not clear for me what the conclusion on this issue is? Af of today it is still inconsistent to `<Select />`.

**Comment by zombieJ** [comment]
Close since v4 done the align.
