### ISSUE TITLE
CheckboxGroup disable某一个item时未生效

### ISSUE THREAD

**Issue by Nemo0915** [ant-design/ant-design#9973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.11

### Environment
Linux、Chrome最新版本

### Reproduction link
[http://2x.ant.design/components/checkbox-cn/](http://2x.ant.design/components/checkbox-cn/)

### Steps to reproduce
const optionsWithDisabled = [
  { label: 'Apple', value: 'Apple' },
  { label: 'Pear', value: 'Pear' },
  { label: 'Orange', value: 'Orange', disabled: false },
];

<CheckboxGroup options={optionsWithDisabled} disabled defaultValue={['Apple']} onChange={onChange} />

所有的Item均被disable了，Orange选项也不可点

### What is expected?
单一item可设置是否disable

### What is actually happening?
设置为disable: false的item依然被禁掉了

---
这是antd 2.X官网上的示例，实际使用中也出现了同样的bug

**Comment by yesmeck** [comment]
It's intended, see https://github.com/ant-design/ant-design/issues/7266

**Comment by amit3512** [comment]
how to disable all other checkboxes in a tabular row when one is selected
