### ISSUE TITLE
可编辑表格中，列编辑组件为选择器组件是，选择器滚动下拉项时影响表格滚动

### ISSUE THREAD

**Issue by Xiodra** [ant-design/ant-design#9976]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
Chrome：版本 65.0.3325.146（正式版本） （32 位）；react：16.2.0；react-dom：16.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wkvk7jw08w)

### Steps to reproduce
点击编辑，进行选择器选择时，滚动选择器下拉选项

### What is expected?
滚动选择器下拉选项，不会影响表格滚动

### What is actually happening?
滚动选择器下拉选项影响表格滚动

**Comment by yesmeck** [comment]
Duplicate of #9033
