### ISSUE TITLE
antd表格默认值无法设置

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#9980]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
dataSource属性为空时，展示给no data给用户，我不需要是这个，如何修改

### What does the proposed API look like?
dataSource属性为空时，展示给no data给用户，我不需要是这个，如何修改

**Comment by yesmeck** [comment]
`<Table locale={{ emptyText: '' }} />`
