### ISSUE TITLE
Avatar image not in middle using {verticalAlign: "middle"}

### ISSUE THREAD

**Issue by johnunclesam** [ant-design/ant-design#9983]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Latest everything

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/72z4jjjpjj)

### Steps to reproduce
`<Avatar style={{ verticalAlign: 'middle' }}>`

### What is expected?
`<Avatar style={{ verticalAlign: 'middle' }}>`

It should be vertically aligned middle without `marginTop`.

### What is actually happening?
`<Avatar style={{ verticalAlign: 'middle' }}>`

It is not vertically aligned middle.

**Without marginTop**:
![withoutmargin](https://user-images.githubusercontent.com/21275217/38559276-e132e8a0-3cd2-11e8-8162-a0b21fe66d0a.PNG)

**With marginTop**:
![withmargintop](https://user-images.githubusercontent.com/21275217/38559273-dfeb3b78-3cd2-11e8-842e-0e057d6d9150.PNG)

**Comment by dengfuping** [comment]
@johnunclesam In fact the image is in the middle although `verticalAlign: 'middle'` is not applied to `Avatar`. Your image has extra blank on the top, so it looks not middle.

![image](https://user-images.githubusercontent.com/14918822/38596402-ea1087a0-3d83-11e8-91d2-7897ad2b8f82.png)

**Comment by johnunclesam** [comment]
@dengfuping Please don't treat me like a fool.

![image](https://user-images.githubusercontent.com/21275217/38602770-03d46f2a-3d6c-11e8-8cf0-8c952a250d89.png)

The space is not an image space.

**Comment by johnunclesam** [comment]
@dengfuping Look at it now:

https://codesandbox.io/s/72z4jjjpjj

![image](https://user-images.githubusercontent.com/21275217/38602912-7821736e-3d6c-11e8-9498-dac15419f609.png)

**Comment by dengfuping** [comment]
@johnunclesam What is your browser and version? Everything is all right on my computer.

![image](https://user-images.githubusercontent.com/14918822/38607333-f0601eaa-3daa-11e8-9d48-668892b1a1e7.png)
