### ISSUE TITLE
Width update error using Col and Affix

### ISSUE THREAD

**Issue by ealvarezk** [ant-design/ant-design#9984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/766zw4n30)

### Steps to reproduce
Scroll down to the bottom with the browser not maximized and a resolution less than 992px, then maximize the browser

### What is expected?
The Left Col width is updated

### What is actually happening?
The Col width is not updated. 
Before maximizing it is like:
![image](https://user-images.githubusercontent.com/16323103/38560743-b2fbbb18-3cac-11e8-978c-4f27d25cb94a.png)
After maximizing:
![image](https://user-images.githubusercontent.com/16323103/38560785-d344392c-3cac-11e8-9ea7-7d73d61857b3.png)
Instead of:
![image](https://user-images.githubusercontent.com/16323103/38560811-e09137e2-3cac-11e8-9c13-a696aba65836.png)

**Comment by yesmeck** [comment]
No luck to reproduce your issue.

![kapture 2018-04-11 at 16 27 16](https://user-images.githubusercontent.com/465125/38605207-3e7e5364-3da5-11e8-9ab4-f838c4b4cf80.gif)

**Comment by ealvarezk** [comment]
the problem happen when you press maximize button. You can see it in this video.
![issue_9984](https://user-images.githubusercontent.com/16323103/38634592-593255ea-3d99-11e8-8073-62b5af039644.gif)

**Comment by yesmeck** [comment]
@ealvarezk Still can't reproduce your issue on Chrome 65, could you help us identify the problem?

**Comment by cathayandy** [comment]
To reproduce it, you need to scroll to BOTTOM and maximize or minimize the window. P.S. Change the size again or scroll to top will fix it immediately.
