### ISSUE TITLE
Configure the visibility of the close button on the top-right corner of Modal

### ISSUE THREAD

**Issue by SimpleFrontend** [ant-design/ant-design#9985]
### What problem does this feature solve?
Currently the close button is always visible and there is no API to hide it or customize it.

### What does the proposed API look like?
Similar to the footer configuration. 
Set as closeButton={null} when you don't need the default close button, or you can provide a ReactNode that serves as a close button.

**Comment by dengfuping** [comment]
@SimpleFrontend `closable` prop has already existed.
![image](https://user-images.githubusercontent.com/14918822/38592212-64b8fe9a-3d6d-11e8-91b9-fd1bf5c597cd.png)
