### ISSUE TITLE
Slider label is not moving with the handle

### ISSUE THREAD

**Issue by mquandalle** [ant-design/ant-design#9987]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Linux, Firefox and Chrome

### Reproduction link
[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce
Move the slider

### What is expected?
The label should move as well

### What is actually happening?
The label doesn't move

![antd slider bug](https://user-images.githubusercontent.com/1730702/38563539-66540bea-3cdd-11e8-8b03-854b12395469.gif)

**Comment by chenyang-biu** [comment]
I want to contribute to the optimization problem
Dose anyone give me some advice?

**Comment by mquandalle** [comment]
This was broken in a recent version, so a `git bisect` should be able to identify the source of the bug.

**Comment by yesmeck** [comment]
Fixed in tooltip@3.7.1, try reinstall node_modules.

**Comment by adambjorgvins** [comment]
When attempting to adjust the slider while the draggableTrack option is set to true and the tooltip is open, the tooltip fails to follow the slider's movement
