### ISSUE TITLE
[NEED HELP] Get typescript errors when running npm run compile

### ISSUE THREAD

**Issue by xuyl0104** [ant-design/ant-design#9988]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Mac OS X 10.12.3; npm version=5.7.1; node versione=v6.11.0; typescript@2.8.1

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```
git clone https://github.com/ant-design/ant-design.git
npm install
npm run compile
```

### What is expected?
Compiled without errors; generate /es and /lib folders at the root directory;
less/css/js/ts file in each subfolders under these two folders.

### What is actually happening?
Only get some less/css files in each subfolders under /es or /lib folders, e.g. /path-to-ant-design/es/input/style/index.css
No js/ts files are generated.

> antd-tools run compile

antd-tools run compile
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
components/anchor/Anchor.tsx(224,22): error TS2531: Object is possibly 'null'.
components/anchor/Anchor.tsx(224,56): error TS2339: Property 'getElementsByClassName' does not exist on type 'Element | Text'.
  Property 'getElementsByClassName' does not exist on type 'Text'.
components/avatar/index.tsx(58,27): error TS2531: Object is possibly 'null'.
components/avatar/index.tsx(58,54): error TS2339: Property 'getBoundingClientRect' does not exist on type 'Element | Text'.
  Property 'getBoundingClientRect' does not exist on type 'Text'.
components/form/FormItem.tsx(251,23): error TS2531: Object is possibly 'null'.
components/form/FormItem.tsx(251,50): error TS2339: Property 'querySelector' does not exist on type 'Element | Text'.
  Property 'querySelector' does not exist on type 'Text'.
components/menu/index.tsx(125,43): error TS2531: Object is possibly 'null'.
components/menu/index.tsx(125,61): error TS2339: Property 'querySelectorAll' does not exist on type 'Element | Text'.
  Property 'querySelectorAll' does not exist on type 'Text'.
components/tabs/index.tsx(83,50): error TS2339: Property 'className' does not existon type 'Element | Text'.
  Property 'className' does not exist on type 'Text'.
components/tabs/index.tsx(84,15): error TS2339: Property 'className' does not existon type 'Element | Text'.
  Property 'className' does not exist on type 'Text'.
components/transfer/list.tsx(104,24): error TS2531: Object is possibly 'null'.
components/transfer/list.tsx(104,51): error TS2339: Property 'querySelectorAll' does not exist on type 'Element | Text'.
  Property 'querySelectorAll' does not exist on type 'Text'.
[11:15:33] TypeScript: 12 semantic errors
[11:15:33] TypeScript: emit succeeded (with errors)

---
We plan to add some extra features to the UI framework and add some themes. The instructions online on how to create themes do not meet our need.
(https://medium.com/@GeoffMiller/how-to-customize-ant-design-with-react-webpack-the-missing-guide-c6430f2db10f)

**Comment by yesmeck** [comment]
Fixed, thanks for reporting.
