### ISSUE TITLE
Pagination分页组件 能否中文展示

### ISSUE THREAD

**Issue by caojin24** [ant-design/ant-design#9989]
version ： 3.1.6 

分页组件中 更多分页中的page 能否用中文 页 展示？ 还有 改变中的 goto 用中文展示 ？

**Comment by yanlee26** [comment]
就是不支持中文配置喽。。。

**Comment by lemovel** [comment]
> antd 默认的语言包应该是英语，你可以在 https://ant.design/components/locale-provider-cn/ 找到解决方案，语言包改为中文就行了

你好，请问怎么改，我也遇到这个问题，文案全部都改成中文了

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/

**Comment by lemovel** [comment]
我是用umi脚手架生成的，这个在哪里设置呢。

**Comment by afc163** [comment]
https://umijs.org/zh-CN/plugins/plugin-locale#antd

**Comment by lemovel** [comment]
我是umi2的版本，antd 升级到了4，所以文案不能空值了，这样的情况怎么办呢，是只能升级umi到3了么？

**Comment by afc163** [comment]
升级到 umi 2 最新版本即可：https://github.com/umijs/umi/releases/tag/umi%402.13.13
