### ISSUE TITLE
braft-editor空格不能显示

### ISSUE THREAD

**Issue by gaoyajuan** [ant-design/ant-design#9997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
普通浏览器

### Reproduction link
[https://github.com/margox/braft-editor](https://github.com/margox/braft-editor)

### Steps to reproduce
braft-editor富文本框编辑带有空格的文字，打印出来空格没有了

### What is expected?
去掉标签之后还有空格存在

### What is actually happening?
没有空格

---
比如我再管理平台用了braft-editor这个富文本框编辑消息，在会员系统显示消息没有空格

**Comment by yesmeck** [comment]
请提 issue 到 https://github.com/margox/braft-editor/issues
