### ISSUE TITLE
columns fixed can not work

### ISSUE THREAD

**Issue by xiaoqiang730730** [ant-design/ant-design#9998]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
win10、chrome

### Reproduction link
[https://stackblitz.com/edit/react-antd](https://stackblitz.com/edit/react-antd)

### Steps to reproduce
1. change the page width
2, when this width is > the table scroll x value
3. columns fixed can not work

### What is expected?
columns fixed can work

### What is actually happening?
columns fixed can not work

**Comment by yesmeck** [comment]
I think it's expected, if the width of container greater the value of `scroll.x`, scroll makes not sense anymore.
